import type { VocabTheme } from "./types";

/**
 * Verbos — 82 words.
 *
 * The one theme where the headword rarely appears in its own example: *cortar*
 * shows up as *corta*, *ir* as *voy*. That is the point — a verb you can only
 * recognize in the infinitive is a verb you can't use — but it does mean the
 * content test's headword-containment guard skips this theme by slug. Review
 * carries it instead.
 */

export const verbos: VocabTheme = {
  slug: "verbos",
  label: "Verbos",
  labelEn: "Verbs",
  words: [
    { id: "v-verbos-trabajar", es: "trabajar", en: "to work", example: "Trabaja de noche y estudia de día.", exampleEn: "He works nights and studies days." },
    { id: "v-verbos-jugar", es: "jugar", en: "to play", example: "Sus hijos juegan en el pasillo mientras ella estudia.", exampleEn: "Her kids play in the hallway while she studies." },
    { id: "v-verbos-caminar", es: "caminar", en: "to walk", example: "Camino desde la estación aunque llueva.", exampleEn: "I walk from the station even when it rains." },
    { id: "v-verbos-correr", es: "correr", en: "to run", example: "Corrí para alcanzar el tren y se me fue igual.", exampleEn: "I ran to catch the train and missed it anyway." },
    { id: "v-verbos-manejar", es: "manejar", en: "to drive", example: "Aprendió a manejar a los treinta y ocho.", exampleEn: "She learned to drive at thirty-eight." },
    { id: "v-verbos-volar", es: "volar", en: "to fly", example: "Vuela a ver a su mamá una vez al año.", exampleEn: "He flies to see his mother once a year." },
    { id: "v-verbos-nadar", es: "nadar", en: "to swim", example: "Nunca aprendió a nadar y le da vergüenza decirlo.", exampleEn: "He never learned to swim and is embarrassed to say so." },
    { id: "v-verbos-ir", es: "ir", en: "to go", example: "Voy a la escuela caminando casi siempre.", exampleEn: "I go to school on foot almost always." },
    { id: "v-verbos-parar", es: "parar", en: "to stop", example: "Para un momento, que no te sigo.", exampleEn: "Stop a second, I'm not following you." },
    { id: "v-verbos-seguir", es: "seguir", en: "to follow", example: "Sigue las instrucciones aunque no entienda todas las palabras.", exampleEn: "She follows the instructions even without understanding every word." },
    { id: "v-verbos-pensar", es: "pensar", en: "to think", example: "Estoy pensando en español y me sale más lento.", exampleEn: "I'm thinking in Spanish and it comes out slower." },
    { id: "v-verbos-decir", es: "decir", en: "to speak / say", example: "Dilo aunque salga mal.", exampleEn: "Say it even if it comes out wrong." },
    { id: "v-verbos-comer", es: "comer", en: "to eat", example: "Comemos algo rápido antes de la clase de la noche.", exampleEn: "We eat something quick before the night class." },
    { id: "v-verbos-beber", es: "beber", en: "to drink", example: "Bebe café hasta las once de la noche.", exampleEn: "He drinks coffee until eleven at night." },
    { id: "v-verbos-matar", es: "matar", en: "to kill", example: "Este frío me está matando.", exampleEn: "This cold is killing me." },
    { id: "v-verbos-morir", es: "morir", en: "to die", example: "Su papá murió el año que ella llegó.", exampleEn: "Her father died the year she arrived." },
    { id: "v-verbos-sonreir", es: "sonreír", en: "to smile", example: "Sonríe cada vez que le sale una frase entera.", exampleEn: "She smiles every time a whole sentence comes out." },
    { id: "v-verbos-reir", es: "reír", en: "to laugh", example: "Nos reímos con mi error todo el resto de la clase.", exampleEn: "We laughed about my mistake the rest of the class." },
    { id: "v-verbos-llorar", es: "llorar", en: "to cry", example: "Lloró al leer su propia carta en voz alta.", exampleEn: "She cried reading her own letter out loud." },
    { id: "v-verbos-comprar", es: "comprar", en: "to buy", example: "Compré el libro usado y venía subrayado.", exampleEn: "I bought the book used and it came underlined." },
    { id: "v-verbos-pagar", es: "pagar", en: "to pay", example: "Paga la renta antes que cualquier otra cosa.", exampleEn: "She pays the rent before anything else." },
    { id: "v-verbos-vender", es: "vender", en: "to sell", example: "Vende comida los domingos en el mercado.", exampleEn: "She sells food on Sundays at the market." },
    { id: "v-verbos-disparar", es: "disparar", en: "to shoot (a gun)", example: "En la película disparan y se acabó la historia.", exampleEn: "In the movie they shoot and the story's over." },
    { id: "v-verbos-aprender", es: "aprender", en: "to learn", example: "Aprendí más en un mes hablando que en un año leyendo.", exampleEn: "I learned more in a month speaking than in a year reading." },
    { id: "v-verbos-saltar", es: "saltar", en: "to jump", example: "Saltó el charco y llegó con los zapatos secos.", exampleEn: "He jumped the puddle and got there with dry shoes." },
    { id: "v-verbos-oler", es: "oler", en: "to smell", example: "Todo el piso huele a lo que están cocinando abajo.", exampleEn: "The whole floor smells like whatever they're cooking downstairs." },
    { id: "v-verbos-oir", es: "oír", en: "to hear (a sound)", example: "Oí algo en el pasillo y no era nadie.", exampleEn: "I heard something in the hallway and it was nobody." },
    { id: "v-verbos-escuchar", es: "escuchar", en: "to listen (music)", example: "Escucho el mismo audio hasta que me lo sé.", exampleEn: "I listen to the same recording until I know it." },
    { id: "v-verbos-probar", es: "probar", en: "to taste", example: "Prueba esto y dime qué le falta.", exampleEn: "Taste this and tell me what it's missing." },
    { id: "v-verbos-tocar", es: "tocar", en: "to touch", example: "No toques eso, que está recién pintado.", exampleEn: "Don't touch that, it's just been painted." },
    { id: "v-verbos-ver", es: "ver", en: "to see (a bird)", example: "Vi un pájaro raro desde la ventana del salón.", exampleEn: "I saw a strange bird from the classroom window." },
    { id: "v-verbos-mirar", es: "mirar", en: "to watch (TV)", example: "Miramos las noticias en español sin subtítulos.", exampleEn: "We watch the news in Spanish without subtitles." },
    { id: "v-verbos-besar", es: "besar", en: "to kiss", example: "Se besaron en la puerta y todo el salón aplaudió.", exampleEn: "They kissed at the door and the whole class clapped." },
    { id: "v-verbos-quemar", es: "quemar", en: "to burn", example: "Se me quemó el arroz mientras contestaba un correo.", exampleEn: "I burned the rice while answering an email." },
    { id: "v-verbos-derretir", es: "derretir", en: "to melt", example: "La nieve se derritió en un día y volvió al otro.", exampleEn: "The snow melted in a day and came back the next." },
    { id: "v-verbos-cavar", es: "cavar", en: "to dig", example: "Cavaron todo el jardín buscando la fuga.", exampleEn: "They dug up the whole yard looking for the leak." },
    { id: "v-verbos-explotar", es: "explotar", en: "to explode", example: "Explotó una tubería y cerraron la calle.", exampleEn: "A pipe burst and they closed the street." },
    { id: "v-verbos-sentarse", es: "sentarse", en: "to sit", example: "Siéntate adelante, que se oye mejor.", exampleEn: "Sit up front, you can hear better." },
    { id: "v-verbos-pararse", es: "pararse", en: "to stand", example: "Se paró a hablar sin que nadie se lo pidiera.", exampleEn: "He stood up to speak without anyone asking him to." },
    { id: "v-verbos-amar", es: "amar", en: "to love", example: "Ama este trabajo aunque la deje sin voz.", exampleEn: "She loves this job even though it leaves her without a voice." },
    { id: "v-verbos-pasar", es: "pasar", en: "to pass by", example: "Paso por tu casa camino a la escuela.", exampleEn: "I pass by your place on the way to school." },
    { id: "v-verbos-cortar", es: "cortar", en: "to cut", example: "Corta el pan mientras yo pongo la mesa.", exampleEn: "Cut the bread while I set the table." },
    { id: "v-verbos-pelear", es: "pelear", en: "to fight", example: "Pelearon por una tontería y ya no se hablan.", exampleEn: "They fought over something silly and don't speak now." },
    { id: "v-verbos-acostarse", es: "acostarse", en: "to lie down", example: "Se acuesta a las once y se levanta a las cinco.", exampleEn: "She lies down at eleven and gets up at five." },
    { id: "v-verbos-bailar", es: "bailar", en: "to dance", example: "Bailamos en el salón el último día del curso.", exampleEn: "We danced in the classroom on the last day of the course." },
    { id: "v-verbos-dormir", es: "dormir", en: "to sleep", example: "Duerme cinco horas y llega igual de puntual.", exampleEn: "He sleeps five hours and shows up just as punctual." },
    { id: "v-verbos-despertarse", es: "despertarse", en: "to wake up", example: "Me despierto antes que el despertador y me da rabia.", exampleEn: "I wake up before the alarm and it irritates me." },
    { id: "v-verbos-cantar", es: "cantar", en: "to sing", example: "Canta en el carro donde nadie la oye.", exampleEn: "She sings in the car where nobody hears her." },
    { id: "v-verbos-contar", es: "contar", en: "to count", example: "Cuenta con los dedos y llega antes que yo.", exampleEn: "He counts on his fingers and gets there before I do." },
    { id: "v-verbos-casarse", es: "casarse", en: "to marry", example: "Se casaron en la iglesia de la esquina.", exampleEn: "They got married at the church on the corner." },
    { id: "v-verbos-rezar", es: "rezar", en: "to pray", example: "Reza antes de cada examen, aunque estudie.", exampleEn: "She prays before every exam, even when she's studied." },
    { id: "v-verbos-ganar", es: "ganar", en: "to win", example: "Ganamos el concurso de la escuela sin ensayar.", exampleEn: "We won the school contest without rehearsing." },
    { id: "v-verbos-perder", es: "perder", en: "to lose", example: "Perdí el hilo a mitad de la frase.", exampleEn: "I lost the thread halfway through the sentence." },
    { id: "v-verbos-mezclar", es: "mezclar", en: "to mix / stir", example: "Mezcla bien antes de que se asiente.", exampleEn: "Stir well before it settles." },
    { id: "v-verbos-doblar", es: "doblar", en: "to bend", example: "Dobla la hoja por la mitad y guárdala.", exampleEn: "Fold the page in half and put it away." },
    { id: "v-verbos-lavar", es: "lavar", en: "to wash", example: "Lavo los platos mientras repaso en voz alta.", exampleEn: "I wash the dishes while I review out loud." },
    { id: "v-verbos-cocinar", es: "cocinar", en: "to cook", example: "Cocina para toda la semana los domingos.", exampleEn: "She cooks for the whole week on Sundays." },
    { id: "v-verbos-abrir", es: "abrir", en: "to open", example: "Abre la ventana antes de que llegue la gente.", exampleEn: "Open the window before people arrive." },
    { id: "v-verbos-cerrar", es: "cerrar", en: "to close", example: "Cierran la biblioteca a las ocho en punto.", exampleEn: "They close the library at eight sharp." },
    { id: "v-verbos-escribir", es: "escribir", en: "to write", example: "Escribo una frase mía cada noche, aunque sea corta.", exampleEn: "I write one sentence of my own every night, even a short one." },
    { id: "v-verbos-llamar", es: "llamar", en: "to call", example: "Llámame cuando salgas del trabajo.", exampleEn: "Call me when you get off work." },
    { id: "v-verbos-voltear", es: "voltear", en: "to turn", example: "Voltea la hoja, que sigue del otro lado.", exampleEn: "Turn the page over, it continues on the other side." },
    { id: "v-verbos-construir", es: "construir", en: "to build", example: "Estoy construyendo una aplicación para practicar en las noches.", exampleEn: "I'm building an app to practice at night." },
    { id: "v-verbos-ensenar", es: "enseñar", en: "to teach", example: "Enseño a adultos que ya saben más de la vida que yo.", exampleEn: "I teach adults who already know more about life than I do." },
    { id: "v-verbos-crecer", es: "crecer", en: "to grow", example: "La clase creció de ocho a veinte en dos meses.", exampleEn: "The class grew from eight to twenty in two months." },
    { id: "v-verbos-dibujar", es: "dibujar", en: "to draw", example: "Dibuja lo que no puede decir todavía.", exampleEn: "He draws what he can't say yet." },
    { id: "v-verbos-alimentar", es: "alimentar", en: "to feed", example: "Alimenta a cinco personas con lo que gana en un turno.", exampleEn: "She feeds five people on what she earns in one shift." },
    { id: "v-verbos-atrapar", es: "atrapar", en: "to catch", example: "Atrapó el vaso antes de que llegara al piso.", exampleEn: "He caught the glass before it hit the floor." },
    { id: "v-verbos-lanzar", es: "lanzar", en: "to throw", example: "Lanzó la pelota y se fue al patio del vecino.", exampleEn: "He threw the ball and it went into the neighbor's yard." },
    { id: "v-verbos-limpiar", es: "limpiar", en: "to clean", example: "Limpia oficinas de madrugada y llega a clase a las siete.", exampleEn: "She cleans offices at dawn and gets to class at seven." },
    { id: "v-verbos-encontrar", es: "encontrar", en: "to find", example: "Encontré la palabra tres horas después, en el tren.", exampleEn: "I found the word three hours later, on the train." },
    { id: "v-verbos-caer", es: "caer", en: "to fall", example: "Se le cayó el teléfono y siguió funcionando.", exampleEn: "He dropped his phone and it kept working." },
    { id: "v-verbos-empujar", es: "empujar", en: "to push", example: "Empuja la puerta fuerte, que se traba.", exampleEn: "Push the door hard, it sticks." },
    { id: "v-verbos-jalar", es: "jalar", en: "to pull", example: "Jala la silla para acá y te oigo mejor.", exampleEn: "Pull your chair over here and I'll hear you better." },
    { id: "v-verbos-cargar", es: "cargar", en: "to carry", example: "Cargo los cuadernos de toda la clase en una bolsa.", exampleEn: "I carry the whole class's notebooks in one bag." },
    { id: "v-verbos-romper", es: "romper", en: "to break", example: "Se rompió el proyector y dimos la clase sin nada.", exampleEn: "The projector broke and we taught the class with nothing." },
    { id: "v-verbos-usar", es: "usar", en: "to wear", example: "Usa el mismo abrigo desde que llegó.", exampleEn: "He's worn the same coat since he arrived." },
    { id: "v-verbos-colgar", es: "colgar", en: "to hang", example: "Cuelga el abrigo antes de que se moje todo.", exampleEn: "Hang the coat up before everything gets wet." },
    { id: "v-verbos-sacudir", es: "sacudir", en: "to shake", example: "Sacude el paraguas afuera, por favor.", exampleEn: "Shake the umbrella off outside, please." },
    { id: "v-verbos-firmar", es: "firmar", en: "to sign", example: "Firma aquí abajo y ya está.", exampleEn: "Sign down here and that's it." },
    { id: "v-verbos-golpear", es: "golpear", en: "to beat", example: "Golpeó la mesa sin querer y saltó todo el mundo.", exampleEn: "He hit the table by accident and everyone jumped." },
    { id: "v-verbos-levantar", es: "levantar", en: "to lift", example: "Levanta la caja con las piernas, no con la espalda.", exampleEn: "Lift the box with your legs, not your back." },
  ],
};
