import type { QuestionSection } from "./types";

export const questionnaireSections: QuestionSection[] = [
  {
    id: "workday",
    part: "Part 2",
    title: "Workday rhythm",
    description: "Think about last week or a typical week.",
    fields: [
      {
        id: "work-hours",
        label: "What time does work usually start and end?",
        type: "text",
        placeholder: "9–5; teaching Tue/Thu 6–8pm…",
      },
      {
        id: "work-blocks",
        label: "How many classes / meetings / deep-work blocks per day?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "work-lunch",
        label: "Lunch: where, with whom, what kind of food?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "work-daily-habit",
        label: "One thing you do every day at work without thinking",
        type: "textarea",
        rows: 2,
      },
      {
        id: "work-recent",
        label: "Something that happened at work recently (good or bad — no real names if you prefer)",
        type: "textarea",
        rows: 3,
      },
    ],
  },
  {
    id: "evening",
    part: "Part 2",
    title: "Evening",
    fields: [
      {
        id: "evening-after-work",
        label: "What do you usually do after work?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "evening-study",
        label: "Do you study, code, read, cook, call family — when and for how long?",
        type: "textarea",
        rows: 3,
      },
      {
        id: "evening-sleep",
        label: "What time do you try to sleep?",
        type: "text",
      },
      {
        id: "evening-last-night",
        label: "One thing you did last night",
        type: "textarea",
        rows: 2,
      },
    ],
  },
  {
    id: "weekend",
    part: "Part 2",
    title: "Weekend",
    fields: [
      {
        id: "weekend-saturday",
        label: "Typical Saturday",
        type: "textarea",
        rows: 2,
      },
      {
        id: "weekend-sunday",
        label: "Typical Sunday",
        type: "textarea",
        rows: 2,
      },
      {
        id: "weekend-errands",
        label: "Errands you run often (grocery store, laundry, gym, etc.)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "weekend-recharge",
        label: "How you recharge",
        type: "textarea",
        rows: 2,
      },
    ],
  },
  {
    id: "home",
    part: "Part 2",
    title: "Home & neighborhood",
    fields: [
      {
        id: "home-description",
        label: "Describe your home in one sentence (size, light, vibe)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "home-favorite-spot",
        label: "Favorite spot in your apartment",
        type: "text",
      },
      {
        id: "home-not-yet",
        label: "One thing that still doesn't feel like home yet",
        type: "textarea",
        rows: 2,
      },
      {
        id: "neighborhood-words",
        label: "Your neighborhood in three words",
        type: "text",
        placeholder: "e.g. gritty, waterfront, loud",
      },
      {
        id: "neighborhood-places",
        label: "Places you walk to often (café, park, library, etc.)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "neighborhood-season",
        label: "Season you notice most where you live — what does it feel like?",
        type: "textarea",
        rows: 2,
        placeholder: "Boston winter…",
      },
    ],
  },
  {
    id: "work-esol",
    part: "Part 3",
    title: "Work — ESOL & teaching",
    description: "Fill gaps or update what's changed.",
    fields: [
      {
        id: "students-who",
        label: "Who are your learners? (ages, countries, levels)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "students-proud",
        label: "What you're proud of about them lately",
        type: "textarea",
        rows: 2,
      },
      {
        id: "students-hard",
        label: "What's hard about teaching them right now",
        type: "textarea",
        rows: 2,
      },
      {
        id: "students-click",
        label: 'A moment when something "clicked" for a student (anonymous)',
        type: "textarea",
        rows: 3,
      },
      {
        id: "students-phrase-1",
        label: "Phrase you'd like in Spanish (1)",
        type: "text",
      },
      {
        id: "students-phrase-2",
        label: "Phrase you'd like in Spanish (2)",
        type: "text",
      },
      {
        id: "students-phrase-3",
        label: "Phrase you'd like in Spanish (3)",
        type: "text",
      },
      {
        id: "school-type",
        label: "Name or type of school (adult ed, community college, etc.)",
        type: "text",
      },
      {
        id: "school-feel",
        label: "What your classroom feels like",
        type: "textarea",
        rows: 2,
      },
      {
        id: "school-policy",
        label: "One policy or routine unique to your program",
        type: "textarea",
        rows: 2,
      },
      {
        id: "school-coworkers",
        label: "Coworkers — who you eat lunch with, who you vent to",
        type: "textarea",
        rows: 2,
      },
      {
        id: "school-meetings",
        label: "Meetings you have often — what they're about",
        type: "textarea",
        rows: 2,
      },
      {
        id: "work-hard-day",
        label: "What makes a teaching day feel difficult?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "work-recover",
        label: "What you do to recover after a hard day",
        type: "textarea",
        rows: 2,
      },
      {
        id: "work-colleague-spanish",
        label: "Something you wish you could tell a colleague in Spanish",
        type: "textarea",
        rows: 2,
      },
      {
        id: "code-languages",
        label: "Language(s) you're learning (coding / career change)",
        type: "text",
      },
      {
        id: "code-project",
        label: "Current project (name or description)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "code-frustrating",
        label: "What's frustrating right now",
        type: "textarea",
        rows: 2,
      },
      {
        id: "code-rewarding",
        label: "What's rewarding right now",
        type: "textarea",
        rows: 2,
      },
      {
        id: "code-why",
        label: "Why you want this change",
        type: "textarea",
        rows: 2,
      },
      {
        id: "code-side-project",
        label: "Side project you'd mention at a party",
        type: "text",
      },
    ],
  },
  {
    id: "family",
    part: "Part 4",
    title: "Family & friends",
    fields: [
      {
        id: "family-who-where",
        label: "Who lives where?",
        type: "textarea",
        rows: 3,
      },
      {
        id: "family-talk-most",
        label: "Who do you talk to most often? How (call, text, video)?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "family-visit",
        label: "How often you visit",
        type: "text",
      },
      {
        id: "family-miss",
        label: "What you miss most about being there",
        type: "textarea",
        rows: 2,
      },
      {
        id: "family-food-ritual",
        label: "Food or ritual you miss",
        type: "textarea",
        rows: 2,
      },
      {
        id: "family-last-convo",
        label: "Last conversation that stuck with you",
        type: "textarea",
        rows: 3,
      },
      {
        id: "mom-1",
        label: "Three things about your mom (or closest family member) — 1",
        type: "text",
      },
      {
        id: "mom-2",
        label: "… 2",
        type: "text",
      },
      {
        id: "mom-3",
        label: "… 3",
        type: "text",
      },
      {
        id: "mom-always-says",
        label: "Something she always says",
        type: "text",
      },
      {
        id: "mom-next-visit",
        label: "When you'll see her next",
        type: "text",
      },
      {
        id: "friend-here",
        label: "Close friend here — how you met, what you do together",
        type: "textarea",
        rows: 3,
      },
      {
        id: "friend-home",
        label: "Close friend back home — what you talk about",
        type: "textarea",
        rows: 2,
      },
      {
        id: "friends-making",
        label: "Making friends in your current city — easy or hard? Why?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "friends-memory",
        label: "Growing up where you did — one memory you'd tell someone",
        type: "textarea",
        rows: 3,
      },
      {
        id: "distance-good",
        label: 'What "far from home" feels like on a good day',
        type: "textarea",
        rows: 2,
      },
      {
        id: "distance-gray",
        label: "What it feels like on a gray or lonely day",
        type: "textarea",
        rows: 2,
      },
    ],
  },
  {
    id: "learning",
    part: "Part 5",
    title: "Learning & growth",
    fields: [
      {
        id: "spanish-why",
        label: "Why you came back to Spanish (or keep going)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "spanish-practice",
        label: "How you practice besides this app",
        type: "textarea",
        rows: 2,
      },
      {
        id: "spanish-media",
        label: "Media you consume in Spanish (podcasts, shows, music)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "spanish-grammar",
        label: "One grammar point that still annoys you",
        type: "text",
      },
      {
        id: "spanish-phrase-steal",
        label: "One phrase you heard recently and want to steal",
        type: "text",
      },
      {
        id: "learn-book",
        label: "Book you're reading (or want to read)",
        type: "text",
      },
      {
        id: "learn-podcast",
        label: "Podcast you listen to",
        type: "text",
      },
      {
        id: "learn-this-week",
        label: "Something new you learned this week",
        type: "textarea",
        rows: 2,
      },
      {
        id: "learn-next-skill",
        label: "Skill you want next (guitar, cooking, etc.)",
        type: "text",
      },
    ],
  },
  {
    id: "travel",
    part: "Part 6",
    title: "Travel & places",
    fields: [
      {
        id: "travel-last",
        label: "Last trip — where, why, one detail you remember",
        type: "textarea",
        rows: 3,
      },
      {
        id: "travel-next",
        label: "Next trip you're planning (or wish you were)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "travel-home-frequency",
        label: "How often you go back home",
        type: "text",
      },
      {
        id: "travel-pack",
        label: "What you pack every time",
        type: "textarea",
        rows: 2,
      },
      {
        id: "travel-city",
        label: "Getting around your current city — lost yet? Favorite route?",
        type: "textarea",
        rows: 2,
      },
      {
        id: "travel-changed",
        label: "Somewhere you've been that changed you",
        type: "textarea",
        rows: 2,
      },
      {
        id: "travel-want",
        label: "Somewhere you want to go and why",
        type: "textarea",
        rows: 2,
      },
      {
        id: "travel-live",
        label: "Place you'd live if money weren't an issue",
        type: "text",
      },
    ],
  },
  {
    id: "food",
    part: "Part 8",
    title: "Food & drink",
    fields: [
      {
        id: "food-today",
        label: "What you ate today (or yesterday)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "food-coffee",
        label: "Coffee or tea habit — how, when, where",
        type: "textarea",
        rows: 2,
      },
      {
        id: "food-regional-miss",
        label: "Southern (or regional) food you miss",
        type: "textarea",
        rows: 2,
      },
      {
        id: "food-restaurant",
        label: "Favorite restaurant here — what you order",
        type: "textarea",
        rows: 2,
      },
      {
        id: "food-tired",
        label: "What you cook at home when you're tired",
        type: "text",
      },
      {
        id: "food-energy",
        label: "What you cook when you have energy",
        type: "text",
      },
      {
        id: "food-friends-meal",
        label: "Last meal with friends — where, what, vibe",
        type: "textarea",
        rows: 3,
      },
      {
        id: "food-order-spanish",
        label: "Food you want to learn to order confidently in Spanish",
        type: "textarea",
        rows: 2,
      },
    ],
  },
  {
    id: "news",
    part: "Part 9",
    title: "Current events & interests",
    description: "Only what you'd actually mention in conversation.",
    fields: [
      {
        id: "news-recent",
        label: "Something in the news that caught your attention lately",
        type: "textarea",
        rows: 2,
      },
      {
        id: "news-education",
        label: "Education policy or schools in the news — your take",
        type: "textarea",
        rows: 2,
      },
      {
        id: "news-city",
        label: "Something happening in your city right now",
        type: "textarea",
        rows: 2,
      },
      {
        id: "news-home",
        label: "Something happening back home",
        type: "textarea",
        rows: 2,
      },
      {
        id: "news-tech",
        label: "Tech or AI thing you're following",
        type: "textarea",
        rows: 2,
      },
      {
        id: "news-hobby",
        label: "Hobby or fandom you'd small-talk about",
        type: "textarea",
        rows: 2,
      },
    ],
  },
  {
    id: "dreams",
    part: "Part 10",
    title: "Dreams & future",
    fields: [
      {
        id: "dream-recent",
        label: "A dream you had recently (sleep dream)",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-recurring",
        label: "A dream that keeps coming back",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-imagine",
        label: "A life you sometimes imagine",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-free-time",
        label: "What you'd do with more free time",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-live",
        label: "Where you'd live someday",
        type: "text",
      },
      {
        id: "dream-career-5",
        label: "Career in five years — honest guess",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-this-year",
        label: "This year I want to…",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-next-summer",
        label: "Next summer I hope to…",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-project",
        label: "A project I'm planning",
        type: "textarea",
        rows: 2,
      },
      {
        id: "dream-learn-next",
        label: "Next thing I'll learn",
        type: "text",
      },
    ],
  },
  {
    id: "situations-work",
    part: "Part 11",
    title: "Situation wishlist — Work",
    description: "Check what matters, then write 2–3 true sentences below.",
    fields: [
      {
        id: "sit-work-esol",
        label: "Your ESOL students",
        type: "checkbox",
      },
      {
        id: "sit-work-school",
        label: "The school where you teach",
        type: "checkbox",
      },
      {
        id: "sit-work-code",
        label: "Learning to code",
        type: "checkbox",
      },
      {
        id: "sit-work-hard-day",
        label: "A difficult day teaching",
        type: "checkbox",
      },
      {
        id: "sit-work-coworkers",
        label: "Your coworkers",
        type: "checkbox",
      },
      {
        id: "sit-work-meeting",
        label: "A work meeting",
        type: "checkbox",
      },
      {
        id: "sit-work-side-project",
        label: "A coding side project",
        type: "checkbox",
      },
      {
        id: "sit-work-sentences",
        label: "Sentences for checked work situations",
        type: "textarea",
        rows: 5,
        placeholder: "2–3 sentences about the situations you checked…",
      },
    ],
  },
  {
    id: "situations-family",
    part: "Part 11",
    title: "Situation wishlist — Family & friends",
    fields: [
      {
        id: "sit-family-atlanta",
        label: "Family in Atlanta (or your city)",
        type: "checkbox",
      },
      {
        id: "sit-family-distance",
        label: "Being far from home",
        type: "checkbox",
      },
      {
        id: "sit-family-friend",
        label: "A close friend",
        type: "checkbox",
      },
      {
        id: "sit-family-south",
        label: "Growing up in the South (or your region)",
        type: "checkbox",
      },
      {
        id: "sit-family-mom",
        label: "Your mom",
        type: "checkbox",
      },
      {
        id: "sit-family-making-friends",
        label: "Making friends in Boston (or your city)",
        type: "checkbox",
      },
      {
        id: "sit-family-sentences",
        label: "Sentences for checked family situations",
        type: "textarea",
        rows: 5,
      },
    ],
  },
  {
    id: "situations-daily",
    part: "Part 11",
    title: "Situation wishlist — Daily life",
    fields: [
      {
        id: "sit-daily-morning",
        label: "Your morning routine",
        type: "checkbox",
      },
      {
        id: "sit-daily-commute",
        label: "Taking the T / your commute",
        type: "checkbox",
      },
      {
        id: "sit-daily-apartment",
        label: "Your apartment",
        type: "checkbox",
      },
      {
        id: "sit-daily-winter",
        label: "Boston winter (or your local season)",
        type: "checkbox",
      },
      {
        id: "sit-daily-weekend",
        label: "Your weekend",
        type: "checkbox",
      },
      {
        id: "sit-daily-errands",
        label: "Errands you ran today",
        type: "checkbox",
      },
      {
        id: "sit-daily-neighborhood",
        label: "Your neighborhood",
        type: "checkbox",
      },
      {
        id: "sit-daily-sentences",
        label: "Sentences for checked daily-life situations",
        type: "textarea",
        rows: 5,
      },
      {
        id: "sit-other-1",
        label: "Other situation you wish existed (1)",
        type: "text",
      },
      {
        id: "sit-other-2",
        label: "Other situation you wish existed (2)",
        type: "text",
      },
      {
        id: "sit-other-3",
        label: "Other situation you wish existed (3)",
        type: "text",
      },
    ],
  },
  {
    id: "frames",
    part: "Part 12",
    title: "Frame scenarios",
    description:
      "For each frame, three micro-scenarios from your life (time, place, or mood).",
    fields: [
      { id: "frame-i-want-1", label: "I want…", type: "table-row", column: "Scenario 1" },
      { id: "frame-i-want-2", label: "I want…", type: "table-row", column: "Scenario 2" },
      { id: "frame-i-want-3", label: "I want…", type: "table-row", column: "Scenario 3" },
      { id: "frame-i-need-1", label: "I need…", type: "table-row", column: "Scenario 1" },
      { id: "frame-i-need-2", label: "I need…", type: "table-row", column: "Scenario 2" },
      { id: "frame-i-need-3", label: "I need…", type: "table-row", column: "Scenario 3" },
      {
        id: "frame-going-to-1",
        label: "I'm going to…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-going-to-2",
        label: "I'm going to…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-going-to-3",
        label: "I'm going to…",
        type: "table-row",
        column: "Scenario 3",
      },
      {
        id: "frame-would-like-1",
        label: "I would like…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-would-like-2",
        label: "I would like…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-would-like-3",
        label: "I would like…",
        type: "table-row",
        column: "Scenario 3",
      },
      {
        id: "frame-feel-like-1",
        label: "I feel like…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-feel-like-2",
        label: "I feel like…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-feel-like-3",
        label: "I feel like…",
        type: "table-row",
        column: "Scenario 3",
      },
      { id: "frame-i-have-1", label: "I have…", type: "table-row", column: "Scenario 1" },
      { id: "frame-i-have-2", label: "I have…", type: "table-row", column: "Scenario 2" },
      { id: "frame-i-have-3", label: "I have…", type: "table-row", column: "Scenario 3" },
      {
        id: "frame-dont-have-1",
        label: "I don't have…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-dont-have-2",
        label: "I don't have…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-dont-have-3",
        label: "I don't have…",
        type: "table-row",
        column: "Scenario 3",
      },
      {
        id: "frame-there-is-1",
        label: "There's / There are…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-there-is-2",
        label: "There's / There are…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-there-is-3",
        label: "There's / There are…",
        type: "table-row",
        column: "Scenario 3",
      },
      { id: "frame-i-use-1", label: "I use…", type: "table-row", column: "Scenario 1" },
      { id: "frame-i-use-2", label: "I use…", type: "table-row", column: "Scenario 2" },
      { id: "frame-i-use-3", label: "I use…", type: "table-row", column: "Scenario 3" },
      { id: "frame-i-think-1", label: "I think…", type: "table-row", column: "Scenario 1" },
      { id: "frame-i-think-2", label: "I think…", type: "table-row", column: "Scenario 2" },
      { id: "frame-i-think-3", label: "I think…", type: "table-row", column: "Scenario 3" },
      {
        id: "frame-i-believe-1",
        label: "I believe…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-i-believe-2",
        label: "I believe…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-i-believe-3",
        label: "I believe…",
        type: "table-row",
        column: "Scenario 3",
      },
      { id: "frame-i-feel-1", label: "I feel…", type: "table-row", column: "Scenario 1" },
      { id: "frame-i-feel-2", label: "I feel…", type: "table-row", column: "Scenario 2" },
      { id: "frame-i-feel-3", label: "I feel…", type: "table-row", column: "Scenario 3" },
      {
        id: "frame-yesterday-1",
        label: "Yesterday I…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-yesterday-2",
        label: "Yesterday I…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-yesterday-3",
        label: "Yesterday I…",
        type: "table-row",
        column: "Scenario 3",
      },
      { id: "frame-today-1", label: "Today I…", type: "table-row", column: "Scenario 1" },
      { id: "frame-today-2", label: "Today I…", type: "table-row", column: "Scenario 2" },
      { id: "frame-today-3", label: "Today I…", type: "table-row", column: "Scenario 3" },
      {
        id: "frame-when-little-1",
        label: "When I was little…",
        type: "table-row",
        column: "Scenario 1",
      },
      {
        id: "frame-when-little-2",
        label: "When I was little…",
        type: "table-row",
        column: "Scenario 2",
      },
      {
        id: "frame-when-little-3",
        label: "When I was little…",
        type: "table-row",
        column: "Scenario 3",
      },
    ],
  },
  {
    id: "vocabulary",
    part: "Part 13",
    title: "Vocabulary you live with",
    description: "Words that should appear in your glosses and phrasebanks.",
    fields: [
      {
        id: "vocab-work-1-en",
        label: "Work & teaching — word/phrase (1)",
        type: "text",
      },
      {
        id: "vocab-work-1-ctx",
        label: "What it means in your context (1)",
        type: "text",
      },
      {
        id: "vocab-work-2-en",
        label: "Work & teaching — word/phrase (2)",
        type: "text",
      },
      {
        id: "vocab-work-2-ctx",
        label: "What it means in your context (2)",
        type: "text",
      },
      {
        id: "vocab-work-3-en",
        label: "Work & teaching — word/phrase (3)",
        type: "text",
      },
      {
        id: "vocab-work-3-ctx",
        label: "What it means in your context (3)",
        type: "text",
      },
      { id: "vocab-home-1-en", label: "Home & city — English (1)", type: "text" },
      { id: "vocab-home-1-ctx", label: "Your context (1)", type: "text" },
      { id: "vocab-home-2-en", label: "Home & city — English (2)", type: "text" },
      { id: "vocab-home-2-ctx", label: "Your context (2)", type: "text" },
      { id: "vocab-food-1-en", label: "Food & brands — English (1)", type: "text" },
      { id: "vocab-food-1-note", label: "Notes (1)", type: "text" },
      { id: "vocab-food-2-en", label: "Food & brands — English (2)", type: "text" },
      { id: "vocab-food-2-note", label: "Notes (2)", type: "text" },
      { id: "vocab-tech-1-en", label: "Tech / coding — English (1)", type: "text" },
      { id: "vocab-tech-1-note", label: "Notes (1)", type: "text" },
      { id: "vocab-tech-2-en", label: "Tech / coding — English (2)", type: "text" },
      { id: "vocab-tech-2-note", label: "Notes (2)", type: "text" },
      { id: "vocab-name-1", label: "Name / place (1)", type: "text" },
      { id: "vocab-name-1-role", label: "Role in your life (1)", type: "text" },
      { id: "vocab-name-2", label: "Name / place (2)", type: "text" },
      { id: "vocab-name-2-role", label: "Role in your life (2)", type: "text" },
    ],
  },
  {
    id: "capture",
    part: "Part 14",
    title: "Quick capture",
    description: "When you think \"I wish I could say that in Spanish,\" write it here.",
    fields: [
      {
        id: "capture-1-en",
        label: "This week I wanted to say (1) — English",
        type: "text",
      },
      {
        id: "capture-1-ctx",
        label: "Context (1)",
        type: "text",
      },
      {
        id: "capture-2-en",
        label: "This week I wanted to say (2) — English",
        type: "text",
      },
      {
        id: "capture-2-ctx",
        label: "Context (2)",
        type: "text",
      },
      {
        id: "capture-3-en",
        label: "This week I wanted to say (3) — English",
        type: "text",
      },
      {
        id: "capture-3-ctx",
        label: "Context (3)",
        type: "text",
      },
      {
        id: "capture-4-en",
        label: "This week I wanted to say (4) — English",
        type: "text",
      },
      {
        id: "capture-4-ctx",
        label: "Context (4)",
        type: "text",
      },
      {
        id: "capture-5-en",
        label: "This week I wanted to say (5) — English",
        type: "text",
      },
      {
        id: "capture-5-ctx",
        label: "Context (5)",
        type: "text",
      },
      {
        id: "capture-retell",
        label: "Something that happened I could retell in Spanish",
        type: "textarea",
        rows: 4,
      },
    ],
  },
];

export const completedSectionSummaries = [
  { part: "Part 1", title: "About you", note: "Already answered — included in export." },
  {
    part: "Part 2",
    title: "Morning routine",
    note: "Already answered — included in export.",
  },
  {
    part: "Part 7",
    title: "Feelings",
    note: "Already answered — included in export.",
  },
];
