import type { SpeakDay } from "./types";
import { week2SpeakDays } from "../drafts/week2-prompts";
import { week3SpeakDays } from "../drafts/week3-prompts";
import { week4SpeakDays } from "../drafts/week4-prompts";
import { week5SpeakDays } from "../drafts/week5-prompts";
import { week6SpeakDays } from "../drafts/week6-prompts";
import { week7SpeakDays } from "../drafts/week7-prompts";
import { week8SpeakDays } from "../drafts/week8-prompts";
import { week9SpeakDays } from "../drafts/week9-prompts";
import { week10SpeakDays } from "../drafts/week10-prompts";
import { week11SpeakDays } from "../drafts/week11-prompts";
import { week12SpeakDays } from "../drafts/week12-prompts";
import { week13SpeakDays } from "../drafts/week13-prompts";

/**
 * Pues — Speak-First prompts (Otoño / fall), days 92+.
 *
 * Week 1 ("Resumir") below; append future weeks in place, keep index-aligned
 * with content/frames/otono.ts. Each day retells/reacts to that day's
 * installment of "Naty se muda" in content/readings/otono.ts.
 */
export const otonoSpeakDays: SpeakDay[] = [
  {
    day: 92,
    themeEs: "Buenas noticias",
    themeEn: "Good news",
    missionEs: "Cuenta la noticia de Naty en pocas frases.",
    missionEn: "Tell Naty's news in a few sentences.",
    line: "Una buena historia empieza con pocas palabras.",
    lineEn: "A good story starts with a few words.",
    prompts: [
      {
        id: "d92-trata-de",
        frameStem: "Trata de…",
        english: "It's about a friend who's moving to Boston.",
        spanish: "Trata de una amiga que se muda a Boston.",
        situationLabel: "Contándole a Priya",
        why: "*Trata de* names the topic before the detail — the opening move of any summary.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "friend", es: "una amiga" },
          { en: "moving", es: "se muda" },
          { en: "boston", es: "a boston" },
        ],
      },
      {
        id: "d92-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that she got the job she wanted.",
        spanish: "La idea principal es que consiguió el trabajo que quería.",
        situationLabel: "Resumiendo la noticia",
        why: "*La idea principal* is exactly the phrase Marlana uses with her own students — naming the one thing that matters most.",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "got", es: "consiguió" },
          { en: "job", es: "el trabajo" },
          { en: "wanted", es: "quería" },
        ],
      },
      {
        id: "d92-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, Naty is moving to Boston.",
        spanish: "En pocas palabras, Naty se muda a Boston.",
        situationLabel: "La versión corta",
        why: "*En pocas palabras* signals you're about to compress a whole story into one line.",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "moving", es: "se muda" },
          { en: "boston", es: "a boston" },
        ],
      },
      {
        id: "d92-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is she finally got the job.",
        spanish: "Lo importante es que por fin consiguió el trabajo.",
        situationLabel: "Lo que más importa",
        why: "*Lo importante es que* filters out the noise and states the one fact worth keeping.",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "finally", es: "por fin" },
          { en: "got", es: "consiguió" },
          { en: "job", es: "el trabajo" },
        ],
      },
      {
        id: "d92-al-final",
        frameStem: "Al final…",
        english: "In the end, they offered her the position last week.",
        spanish: "Al final, le ofrecieron el puesto la semana pasada.",
        situationLabel: "Cómo terminó todo",
        why: "*Al final* closes a summary the way a good story should — with the resolution.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "offered", es: "ofrecieron" },
          { en: "position", es: "el puesto" },
          { en: "last week", es: "la semana pasada" },
        ],
      },
    ],
  },
  {
    day: 93,
    themeEs: "Empacando",
    themeEn: "Packing",
    missionEs: "Cuenta cómo va el caos de la mudanza.",
    missionEn: "Tell how the moving chaos is going.",
    line: "Un buen resumen encuentra el orden dentro del caos.",
    lineEn: "A good summary finds order inside chaos.",
    prompts: [
      {
        id: "d93-trata-de",
        frameStem: "Trata de…",
        english: "It's about packing a whole life into boxes.",
        spanish: "Trata de empacar toda una vida en cajas.",
        situationLabel: "Describiendo la mudanza",
        why: "*Trata de* + infinitive works just as well as *trata de* + noun for naming a process.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "packing", es: "empacar" },
          { en: "life", es: "una vida" },
          { en: "boxes", es: "cajas" },
        ],
      },
      {
        id: "d93-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that she doesn't have boxes yet.",
        spanish: "La idea principal es que todavía no tiene cajas.",
        situationLabel: "El problema del día",
        why: "*Todavía no* is the natural way to say “not yet” in the middle of a sentence.",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "doesn't have", es: "no tiene" },
          { en: "yet", es: "todavía" },
          { en: "boxes", es: "cajas" },
        ],
      },
      {
        id: "d93-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, it's total chaos.",
        spanish: "En pocas palabras, es un caos total.",
        situationLabel: "La versión honesta",
        why: "Sometimes the honest one-line summary is the most useful one.",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "total chaos", es: "un caos total" },
        ],
      },
      {
        id: "d93-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is her mom is going to help her.",
        spanish: "Lo importante es que su mamá va a ayudarla.",
        situationLabel: "Lo que la tranquiliza",
        why: "*Ayudarla* attaches the object pronoun straight onto the infinitive.",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "mom", es: "su mamá" },
          { en: "help her", es: "ayudarla" },
        ],
      },
      {
        id: "d93-al-final",
        frameStem: "Al final…",
        english: "In the end, she got boxes from the corner store.",
        spanish: "Al final, consiguió cajas de la tienda de la esquina.",
        situationLabel: "Cómo se resolvió",
        why: "*La tienda de la esquina* — “the corner store” — is a small, concrete detail that makes a retelling feel real.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "got", es: "consiguió" },
          { en: "corner store", es: "la tienda de la esquina" },
        ],
      },
    ],
  },
  {
    day: 94,
    themeEs: "El camino",
    themeEn: "The road",
    missionEs: "Cuenta cómo fue el viaje de Naty a Boston.",
    missionEn: "Tell how Naty's trip to Boston went.",
    line: "Cada viaje largo se resume en unas pocas frases.",
    lineEn: "Every long trip fits into just a few sentences.",
    prompts: [
      {
        id: "d94-trata-de",
        frameStem: "Trata de…",
        english: "It's about an eighteen-hour drive.",
        spanish: "Trata de un viaje de dieciocho horas.",
        situationLabel: "Contando el viaje",
        why: "*Un viaje de + [number] horas* is the natural way to size up a trip in one phrase.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "eighteen-hour", es: "de dieciocho horas" },
          { en: "drive", es: "un viaje" },
        ],
      },
      {
        id: "d94-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that the trip was really long.",
        spanish: "La idea principal es que el viaje fue larguísimo.",
        situationLabel: "Resumiendo lo esencial",
        why: "The *-ísimo* ending pushes *largo* (long) to its most emphatic form — “really, really long.”",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "trip", es: "el viaje" },
          { en: "really long", es: "larguísimo" },
        ],
      },
      {
        id: "d94-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, it was an exhausting trip.",
        spanish: "En pocas palabras, fue un viaje agotador.",
        situationLabel: "La versión corta",
        why: "*Agotador* — exhausting — is the kind of specific adjective that beats a generic “tired” or “long.”",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "exhausting", es: "agotador" },
          { en: "trip", es: "un viaje" },
        ],
      },
      {
        id: "d94-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is they arrived safely.",
        spanish: "Lo importante es que llegaron bien.",
        situationLabel: "Lo que de verdad importa",
        why: "*Llegar bien* — literally “arrive well” — is how you say “arrive safely” in everyday Spanish.",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "arrived", es: "llegaron" },
          { en: "safely", es: "bien" },
        ],
      },
      {
        id: "d94-al-final",
        frameStem: "Al final…",
        english: "In the end, they arrived in Boston after midnight.",
        spanish: "Al final, llegaron a Boston pasada la medianoche.",
        situationLabel: "El final del viaje",
        why: "*Pasada la medianoche* — “past midnight” — is a compact way to give a time without a full clause.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "arrived", es: "llegaron" },
          { en: "past midnight", es: "pasada la medianoche" },
        ],
      },
    ],
  },
  {
    day: 95,
    themeEs: "El apartamento nuevo",
    themeEn: "The new apartment",
    missionEs: "Cuenta cómo van los primeros días de Naty en su apartamento.",
    missionEn: "Tell how Naty's first days in her apartment are going.",
    line: "Hasta los días difíciles se pueden resumir con cariño.",
    lineEn: "Even hard days can be summed up with kindness.",
    prompts: [
      {
        id: "d95-trata-de",
        frameStem: "Trata de…",
        english: "It's about a small, empty apartment.",
        spanish: "Trata de un apartamento pequeño y vacío.",
        situationLabel: "Describiendo el nuevo espacio",
        why: "Two adjectives after the noun (*pequeño y vacío*) paint the whole picture in one phrase.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "small", es: "pequeño" },
          { en: "empty", es: "vacío" },
          { en: "apartment", es: "un apartamento" },
        ],
      },
      {
        id: "d95-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that she doesn't have furniture yet.",
        spanish: "La idea principal es que todavía no tiene muebles.",
        situationLabel: "Lo que falta",
        why: "*Los muebles* — furniture — is always plural in Spanish, even for one piece.",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "furniture", es: "muebles" },
          { en: "yet", es: "todavía" },
        ],
      },
      {
        id: "d95-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, she's feeling a little lost.",
        spanish: "En pocas palabras, se siente un poco perdida.",
        situationLabel: "Cómo se siente",
        why: "*Sentirse perdida* — to feel lost — works for a new city just as well as for a literal wrong turn.",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "feeling", es: "se siente" },
          { en: "a little", es: "un poco" },
          { en: "lost", es: "perdida" },
        ],
      },
      {
        id: "d95-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is she's not completely alone — I'm close by.",
        spanish: "Lo importante es que no está sola del todo — yo estoy cerca.",
        situationLabel: "Lo que la reconforta",
        why: "*Del todo* softens *sola* — “not alone, exactly” rather than a flat statement.",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "not alone", es: "no está sola" },
          { en: "close", es: "cerca" },
        ],
      },
      {
        id: "d95-al-final",
        frameStem: "Al final…",
        english: "In the end, she called me and we talked for two hours.",
        spanish: "Al final, me llamó y hablamos dos horas.",
        situationLabel: "Cómo terminó el día",
        why: "A long phone call is its own kind of happy ending to a hard day.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "called me", es: "me llamó" },
          { en: "we talked", es: "hablamos" },
          { en: "two hours", es: "dos horas" },
        ],
      },
    ],
  },
  {
    day: 96,
    themeEs: "El primer día",
    themeEn: "The first day",
    missionEs: "Cuenta cómo le fue a Naty en su primer día de trabajo.",
    missionEn: "Tell how Naty's first day at work went.",
    line: "Hasta los momentos incómodos se convierten en una buena historia.",
    lineEn: "Even awkward moments turn into a good story.",
    prompts: [
      {
        id: "d96-trata-de",
        frameStem: "Trata de…",
        english: "It's about her first day of work.",
        spanish: "Trata de su primer día de trabajo.",
        situationLabel: "Contando cómo empezó",
        why: "*Su primer día de trabajo* is the whole topic in four words — the kind of compact noun phrase a good summary opens with.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "first day", es: "su primer día" },
          { en: "work", es: "de trabajo" },
        ],
      },
      {
        id: "d96-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that she couldn't answer a question.",
        spanish: "La idea principal es que no supo responder una pregunta.",
        situationLabel: "El momento difícil",
        why: "*No supo* (from *saber*) means she didn't know how — different from *no pudo*, which would mean she wasn't able to.",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "couldn't answer", es: "no supo responder" },
          { en: "question", es: "una pregunta" },
        ],
      },
      {
        id: "d96-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, she blanked for a moment.",
        spanish: "En pocas palabras, se quedó en blanco un momento.",
        situationLabel: "La versión honesta",
        why: "*Quedarse en blanco* — literally “to stay blank” — is exactly how you say “to blank” in Spanish.",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "blanked", es: "se quedó en blanco" },
          { en: "a moment", es: "un momento" },
        ],
      },
      {
        id: "d96-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is she asked for help.",
        spanish: "Lo importante es que pidió ayuda.",
        situationLabel: "Lo que hizo bien",
        why: "*Pedir ayuda* is a small phrase worth praising on purpose — asking is the skill, not a failure.",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "asked for help", es: "pidió ayuda" },
        ],
      },
      {
        id: "d96-al-final",
        frameStem: "Al final…",
        english: "In the end, the team invited her to lunch.",
        spanish: "Al final, el equipo la invitó a almorzar.",
        situationLabel: "Cómo terminó el día",
        why: "*Invitar a + infinitive* is the standard pattern for “invite someone to do something.”",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "team", es: "el equipo" },
          { en: "invited her", es: "la invitó" },
          { en: "lunch", es: "almorzar" },
        ],
      },
    ],
  },
  {
    day: 97,
    themeEs: "Ya se siente en casa",
    themeEn: "Feeling at home",
    missionEs: "Cuenta cómo ha cambiado todo para Naty después de un mes.",
    missionEn: "Tell how everything has changed for Naty after a month.",
    line: "Un mes después, la historia ya tiene un final feliz.",
    lineEn: "A month later, the story already has a happy ending.",
    prompts: [
      {
        id: "d97-trata-de",
        frameStem: "Trata de…",
        english: "It's about a whole month in Boston.",
        spanish: "Trata de un mes entero en Boston.",
        situationLabel: "Marcando el tiempo pasado",
        why: "*Entero* — “whole” — emphasizes that a full month has really gone by.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "whole month", es: "un mes entero" },
          { en: "boston", es: "en boston" },
        ],
      },
      {
        id: "d97-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that she found a favorite coffee shop.",
        spanish: "La idea principal es que encontró una cafetería favorita.",
        situationLabel: "Una señal de que ya se instaló",
        why: "Finding a favorite coffee shop is a small, telling sign that a new city is starting to feel like home.",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "found", es: "encontró" },
          { en: "favorite", es: "favorita" },
          { en: "coffee shop", es: "una cafetería" },
        ],
      },
      {
        id: "d97-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, she's got a routine now.",
        spanish: "En pocas palabras, ya tiene una rutina.",
        situationLabel: "El cambio más grande",
        why: "*Ya* — “already/now” — marks the shift from chaos to routine in one small word.",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "already", es: "ya" },
          { en: "routine", es: "una rutina" },
        ],
      },
      {
        id: "d97-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is she found her place.",
        spanish: "Lo importante es que encontró su lugar.",
        situationLabel: "Lo que más importa ahora",
        why: "*Encontrar su lugar* — “to find one's place” — works both literally (a city) and figuratively (belonging).",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "found", es: "encontró" },
          { en: "her place", es: "su lugar" },
        ],
      },
      {
        id: "d97-al-final",
        frameStem: "Al final…",
        english: "In the end, I'm going to visit her next weekend.",
        spanish: "Al final, voy a visitarla el próximo fin de semana.",
        situationLabel: "El siguiente capítulo",
        why: "*Visitarla* attaches the object pronoun to the infinitive, just like *ayudarla* back on day 93.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "visit her", es: "visitarla" },
          { en: "next weekend", es: "el próximo fin de semana" },
        ],
      },
    ],
  },
  {
    day: 98,
    themeEs: "Repaso: resumir",
    themeEn: "Review: summarizing",
    missionEs: "Resume todo el mes de Naty en cinco frases.",
    missionEn: "Sum up Naty's whole month in five sentences.",
    line: "Un mes entero cabe en cinco frases, si sabes cuáles elegir.",
    lineEn: "A whole month fits into five sentences, if you know which ones to choose.",
    prompts: [
      {
        id: "d98-trata-de",
        frameStem: "Trata de…",
        english: "It's about a friend who changed cities and careers at the same time.",
        spanish: "Trata de una amiga que cambió de ciudad y de carrera al mismo tiempo.",
        situationLabel: "Resumiendo el mes",
        why: "*Al mismo tiempo* — “at the same time” — packs two big changes into one clean phrase.",
        wordHints: [
          { en: "about", es: "trata de" },
          { en: "friend", es: "una amiga" },
          { en: "changed", es: "cambió" },
          { en: "cities", es: "de ciudad" },
          { en: "careers", es: "de carrera" },
          { en: "same time", es: "al mismo tiempo" },
        ],
      },
      {
        id: "d98-idea-principal",
        frameStem: "La idea principal es que…",
        english: "The main idea is that Naty moved from Atlanta to Boston a month ago.",
        spanish: "La idea principal es que Naty se mudó de Atlanta a Boston hace un mes.",
        situationLabel: "El resumen de todo",
        why: "*Hace un mes* — “a month ago” — is the standard way to anchor an event in the recent past.",
        wordHints: [
          { en: "main idea", es: "la idea principal" },
          { en: "moved", es: "se mudó" },
          { en: "a month ago", es: "hace un mes" },
        ],
      },
      {
        id: "d98-pocas-palabras",
        frameStem: "En pocas palabras…",
        english: "In a few words, Naty did it.",
        spanish: "En pocas palabras, Naty lo logró.",
        situationLabel: "La versión más corta",
        why: "*Lo logró* — “she did it/pulled it off” — is the shortest possible way to say someone succeeded.",
        wordHints: [
          { en: "in a few words", es: "en pocas palabras" },
          { en: "did it", es: "lo logró" },
        ],
      },
      {
        id: "d98-lo-importante",
        frameStem: "Lo importante es que…",
        english: "The important thing is she never stopped trying.",
        spanish: "Lo importante es que nunca dejó de intentarlo.",
        situationLabel: "Lo que se queda de la historia",
        why: "*Dejar de + infinitive* means “to stop doing something” — *nunca dejó de intentarlo* is “she never stopped trying.”",
        wordHints: [
          { en: "important", es: "importante" },
          { en: "never stopped", es: "nunca dejó de" },
          { en: "trying", es: "intentarlo" },
        ],
      },
      {
        id: "d98-al-final",
        frameStem: "Al final…",
        english: "In the end, we're very proud of her.",
        spanish: "Al final, estamos muy orgullosas de ella.",
        situationLabel: "Cómo termina la historia",
        why: "*Orgullosas* agrees in the feminine plural — Marlana and Priya, both women, speaking about Naty.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "proud", es: "orgullosas" },
        ],
      },
    ],
  },
  ...week2SpeakDays,
  ...week3SpeakDays,
  ...week4SpeakDays,
  ...week5SpeakDays,
  ...week6SpeakDays,
  ...week7SpeakDays,
  ...week8SpeakDays,
  ...week9SpeakDays,
  ...week10SpeakDays,
  ...week11SpeakDays,
  ...week12SpeakDays,
  ...week13SpeakDays,
];
