/**
 * Sentence Builder — a tap-to-build game for Práctica.
 *
 * The learner reads an English prompt, taps Spanish word tiles in order, and
 * checks the answer. Each card is self-contained: the correct word sequence,
 * the bank of tappable tiles (with a few distractors), and the teaching note.
 *
 * Matching is order-sensitive but case- and accent-tolerant on the comparison
 * side, so a tile that reads "Tengo" (capitalised at the start of the answer)
 * still matches the lowercase target "tengo". Distractor tiles are simply any
 * `availableTiles` entry that never appears in `targetSpanish`.
 */

export type RecallData = {
  type: "typed_blanks";
  /** Display string with first-letter hints, e.g. "T____ q__ ll____ a mi m____" */
  prompt: string;
  /** Words the learner must fill in, in left-to-right blank order */
  missingWords: string[];
  revealAnswerAllowed: boolean;
};

export type SayData = {
  promptEnglish: string;
  displayAnswer: string;
  /** Instruction shown below the prompt, e.g. "Intenta decirlo sin mirar." */
  instruction: string;
};

export type RemixData = {
  promptEnglish: string;
  targetSpanish: string[];
  displayAnswer: string;
  availableTiles: string[];
  /** Teaching note shown after the remix is answered correctly */
  explanation: string;
};

export type SentenceCard = {
  id: string;
  mode: "sentence_builder";
  /** The English sentence to translate. */
  promptEnglish: string;
  /** Correct Spanish word order, lowercase. The source of truth for checking. */
  targetSpanish: string[];
  /** Tiles shown in the bank — the target words shuffled in with distractors. */
  availableTiles: string[];
  /** The finished sentence, properly cased and punctuated, for the reveal. */
  displayAnswer: string;
  /** The grammar pattern this card teaches, e.g. "Tengo que + infinitive". */
  pattern: string;
  /** One-line teaching note shown under the bank and in the Pista popover. */
  hint: string;
  /** The "why" shown on a correct answer. */
  explanation: string;
  /** Three quick echoes of the pattern, shown under the teaching note. */
  examples: string;
  /** Gentle nudge shown on a wrong answer. */
  almost: string;
  /** Level label for the mini progress card. */
  level: string;
  /** When present, enables the 5-step ladder flow for this card. */
  recall?: RecallData;
  say?: SayData;
  remix?: RemixData;
};

/** Lowercase + strip accents so "Tengo" and "tengo" compare equal. */
export function normalizeWord(word: string): string {
  return word
    .toLocaleLowerCase("es")
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim();
}

/** Split a typed sentence into normalized words for comparison. */
export function normalizeSentence(text: string): string[] {
  return text
    .replace(/[.?!,¿¡]/g, "")
    .split(/\s+/)
    .map(normalizeWord)
    .filter((w) => w.length > 0);
}

/** Spanish strings to pre-generate audio for (consumed by scripts/generate-audio.ts). */
export function sentenceBuilderAudioTexts(): string[] {
  const texts = new Set<string>();
  for (const card of sentenceBuilderCards) {
    texts.add(card.displayAnswer);
    if (card.say) texts.add(card.say.displayAnswer);
    if (card.remix) texts.add(card.remix.displayAnswer);
  }
  return [...texts];
}

export const sentenceBuilderCards: SentenceCard[] = [
  {
    id: "tengo_que_llamar_mama_001",
    mode: "sentence_builder",
    promptEnglish: "I have to call my mom.",
    targetSpanish: ["tengo", "que", "llamar", "a", "mi", "mamá"],
    availableTiles: ["mamá", "mi", "a", "que", "tengo", "llamo", "llamar", "yo", "la"],
    displayAnswer: "Tengo que llamar a mi mamá.",
    pattern: "Tengo que + infinitive",
    hint: "Después de “tengo que”, el verbo siempre va en infinitivo.",
    explanation: "Después de “tengo que”, usamos el infinitivo: llamar.",
    examples: "Tengo que llamar, tengo que estudiar, tengo que trabajar…",
    almost: "Casi. Revisa el verbo después de “tengo que”.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "T____ q__ ll____ a mi m____",
      missingWords: ["tengo", "que", "llamar", "mamá"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "I have to call my mom.",
      displayAnswer: "Tengo que llamar a mi mamá.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "I have to call my sister.",
      targetSpanish: ["tengo", "que", "llamar", "a", "mi", "hermana"],
      displayAnswer: "Tengo que llamar a mi hermana.",
      availableTiles: ["hermana", "mi", "a", "que", "tengo", "llamar", "mamá", "llamo", "yo"],
      explanation: "Solo cambiaste 'mamá' por 'hermana'. El patrón sigue igual: tengo que + infinitivo.",
    },
  },
  {
    id: "voy_a_estudiar_noche_002",
    mode: "sentence_builder",
    promptEnglish: "I'm going to study tonight.",
    targetSpanish: ["voy", "a", "estudiar", "esta", "noche"],
    availableTiles: ["noche", "estudio", "voy", "esta", "a", "mañana", "estudiar", "soy"],
    displayAnswer: "Voy a estudiar esta noche.",
    pattern: "Voy a + infinitive",
    hint: "“Voy a” + infinitivo expresa una acción futura.",
    explanation: "Después de “voy a”, usamos el infinitivo: estudiar.",
    examples: "Voy a comer, voy a salir, voy a dormir…",
    almost: "Casi. Después de “voy a” va el infinitivo.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "V__ a est____ esta n____",
      missingWords: ["voy", "estudiar", "noche"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "I'm going to study tonight.",
      displayAnswer: "Voy a estudiar esta noche.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "I'm going to eat tonight.",
      targetSpanish: ["voy", "a", "comer", "esta", "noche"],
      displayAnswer: "Voy a comer esta noche.",
      availableTiles: ["noche", "como", "voy", "esta", "a", "mañana", "comer", "estudiar"],
      explanation: "Solo cambiaste 'estudiar' por 'comer'. El patrón es el mismo: voy a + infinitivo.",
    },
  },
  {
    id: "quiero_tomar_cafe_003",
    mode: "sentence_builder",
    promptEnglish: "I want to drink coffee.",
    targetSpanish: ["quiero", "tomar", "café"],
    availableTiles: ["té", "quiero", "tomo", "café", "bebo", "tomar"],
    displayAnswer: "Quiero tomar café.",
    pattern: "Querer + infinitive",
    hint: "Después de “quiero”, el segundo verbo va en infinitivo.",
    explanation: "Quiero + infinitivo: quiero tomar.",
    examples: "Quiero comer, quiero ir, quiero descansar…",
    almost: "Casi. Después de “quiero” va el infinitivo.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "Q____ t____ c____",
      missingWords: ["quiero", "tomar", "café"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "I want to drink coffee.",
      displayAnswer: "Quiero tomar café.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "I want to drink tea.",
      targetSpanish: ["quiero", "tomar", "té"],
      displayAnswer: "Quiero tomar té.",
      availableTiles: ["té", "quiero", "tomar", "café", "bebo", "tomo"],
      explanation: "Solo cambiaste 'café' por 'té'. El patrón sigue igual: quiero + infinitivo.",
    },
  },
  {
    id: "me_gusta_leer_libros_004",
    mode: "sentence_builder",
    promptEnglish: "I like to read books.",
    targetSpanish: ["me", "gusta", "leer", "libros"],
    availableTiles: ["libros", "leo", "gusta", "me", "casa", "leer", "gusto"],
    displayAnswer: "Me gusta leer libros.",
    pattern: "Me gusta + infinitive",
    hint: "Para hablar de gustos, usa “me gusta” + infinitivo.",
    explanation: "Me gusta + infinitivo: me gusta leer.",
    examples: "Me gusta cantar, me gusta cocinar, me gusta caminar…",
    almost: "Casi. Después de “me gusta” va el infinitivo.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "M__ g____ l____ l____",
      missingWords: ["me", "gusta", "leer", "libros"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "I like to read books.",
      displayAnswer: "Me gusta leer libros.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "I like to cook.",
      targetSpanish: ["me", "gusta", "cocinar"],
      displayAnswer: "Me gusta cocinar.",
      availableTiles: ["cocinar", "gusta", "me", "leer", "libros", "cocino", "casa"],
      explanation: "Solo cambiaste 'leer libros' por 'cocinar'. El patrón sigue igual: me gusta + infinitivo.",
    },
  },
  {
    id: "necesito_trabajar_manana_005",
    mode: "sentence_builder",
    promptEnglish: "I need to work tomorrow.",
    targetSpanish: ["necesito", "trabajar", "mañana"],
    availableTiles: ["trabajo", "mañana", "necesito", "hoy", "trabajar", "necesita"],
    displayAnswer: "Necesito trabajar mañana.",
    pattern: "Necesitar + infinitive",
    hint: "Después de “necesito”, el verbo va en infinitivo.",
    explanation: "Necesito + infinitivo: necesito trabajar.",
    examples: "Necesito dormir, necesito comer, necesito salir…",
    almost: "Casi. Después de “necesito” va el infinitivo.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "N_______ t_______ m______",
      missingWords: ["necesito", "trabajar", "mañana"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "I need to work tomorrow.",
      displayAnswer: "Necesito trabajar mañana.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "I need to rest today.",
      targetSpanish: ["necesito", "descansar", "hoy"],
      displayAnswer: "Necesito descansar hoy.",
      availableTiles: ["hoy", "descansar", "necesito", "mañana", "trabajar", "descanso"],
      explanation: "Solo cambiaste 'trabajar mañana' por 'descansar hoy'. El patrón sigue igual: necesito + infinitivo.",
    },
  },
  {
    id: "puedo_hablar_espanol_006",
    mode: "sentence_builder",
    promptEnglish: "I can speak Spanish.",
    targetSpanish: ["puedo", "hablar", "español"],
    availableTiles: ["español", "hablo", "puedo", "inglés", "hablar", "puede"],
    displayAnswer: "Puedo hablar español.",
    pattern: "Poder + infinitive",
    hint: "Después de “puedo”, el verbo va en infinitivo.",
    explanation: "Puedo + infinitivo: puedo hablar.",
    examples: "Puedo ir, puedo ayudar, puedo manejar…",
    almost: "Casi. Después de “puedo” va el infinitivo.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "P____ h____ e______",
      missingWords: ["puedo", "hablar", "español"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "I can speak Spanish.",
      displayAnswer: "Puedo hablar español.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "I can speak English.",
      targetSpanish: ["puedo", "hablar", "inglés"],
      displayAnswer: "Puedo hablar inglés.",
      availableTiles: ["inglés", "puedo", "hablar", "español", "hablo", "puede"],
      explanation: "Solo cambiaste 'español' por 'inglés'. El patrón sigue igual: puedo + infinitivo.",
    },
  },
  {
    id: "tenemos_que_limpiar_casa_007",
    mode: "sentence_builder",
    promptEnglish: "We have to clean the house.",
    targetSpanish: ["tenemos", "que", "limpiar", "la", "casa"],
    availableTiles: ["casa", "limpiamos", "que", "tenemos", "la", "el", "limpiar", "tengo"],
    displayAnswer: "Tenemos que limpiar la casa.",
    pattern: "Tener que + infinitive",
    hint: "Después de “tenemos que”, el verbo va en infinitivo.",
    explanation: "Tener que + infinitivo: tenemos que limpiar.",
    examples: "Tenemos que estudiar, tenemos que salir, tenemos que esperar…",
    almost: "Casi. Revisa el verbo después de “tenemos que”.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "T_______ q__ l_____ la c____",
      missingWords: ["tenemos", "que", "limpiar", "casa"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "We have to clean the house.",
      displayAnswer: "Tenemos que limpiar la casa.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "We have to cook dinner.",
      targetSpanish: ["tenemos", "que", "cocinar", "la", "cena"],
      displayAnswer: "Tenemos que cocinar la cena.",
      availableTiles: ["cena", "cocinar", "que", "tenemos", "la", "casa", "limpiar", "cocinamos"],
      explanation: "Solo cambiaste 'limpiar la casa' por 'cocinar la cena'. El patrón sigue igual: tenemos que + infinitivo.",
    },
  },
  {
    id: "ella_quiere_bailar_008",
    mode: "sentence_builder",
    promptEnglish: "She wants to dance.",
    targetSpanish: ["ella", "quiere", "bailar"],
    availableTiles: ["bailar", "baila", "ella", "quiere", "él", "quieren"],
    displayAnswer: "Ella quiere bailar.",
    pattern: "Querer + infinitive",
    hint: "Después de “quiere”, el verbo va en infinitivo.",
    explanation: "Quiere + infinitivo: quiere bailar.",
    examples: "Quiere comer, quiere salir, quiere descansar…",
    almost: "Casi. Después de “quiere” va el infinitivo.",
    level: "Principiante 1",
    recall: {
      type: "typed_blanks",
      prompt: "E___ q____ b_____",
      missingWords: ["ella", "quiere", "bailar"],
      revealAnswerAllowed: true,
    },
    say: {
      promptEnglish: "She wants to dance.",
      displayAnswer: "Ella quiere bailar.",
      instruction: "Intenta decirlo sin mirar.",
    },
    remix: {
      promptEnglish: "She wants to sing.",
      targetSpanish: ["ella", "quiere", "cantar"],
      displayAnswer: "Ella quiere cantar.",
      availableTiles: ["cantar", "quiere", "ella", "bailar", "canta", "él"],
      explanation: "Solo cambiaste 'bailar' por 'cantar'. El patrón sigue igual: quiere + infinitivo.",
    },
  },

  /* ── Principiante 2 · El presente del día a día ──────────────────────── */
  {
    id: "trabajo_en_el_centro_101",
    mode: "sentence_builder",
    promptEnglish: "I work downtown.",
    targetSpanish: ["trabajo", "en", "el", "centro"],
    availableTiles: ["centro", "el", "en", "trabajo", "trabaja", "la", "casa"],
    displayAnswer: "Trabajo en el centro.",
    pattern: "Presente · yo (-ar)",
    hint: "Para “yo”, los verbos en -ar terminan en -o: trabajo.",
    explanation: "Yo trabajo: la terminación -o marca la primera persona.",
    examples: "Trabajo, hablo, estudio, cocino…",
    almost: "Casi. Para “yo”, el verbo termina en -o.",
    level: "Principiante 2",
  },
  {
    id: "ella_come_en_casa_102",
    mode: "sentence_builder",
    promptEnglish: "She eats at home.",
    targetSpanish: ["ella", "come", "en", "casa"],
    availableTiles: ["casa", "en", "come", "ella", "como", "comen", "el"],
    displayAnswer: "Ella come en casa.",
    pattern: "Presente · ella (-er)",
    hint: "Para “él/ella”, los verbos en -er terminan en -e: come.",
    explanation: "Ella come: la terminación -e marca la tercera persona.",
    examples: "Come, bebe, lee, corre…",
    almost: "Casi. Para “ella”, el verbo en -er termina en -e.",
    level: "Principiante 2",
  },
  {
    id: "vivimos_cerca_escuela_103",
    mode: "sentence_builder",
    promptEnglish: "We live near the school.",
    targetSpanish: ["vivimos", "cerca", "de", "la", "escuela"],
    availableTiles: ["escuela", "la", "de", "cerca", "vivimos", "viven", "el", "vivo"],
    displayAnswer: "Vivimos cerca de la escuela.",
    pattern: "Presente · nosotros (-ir)",
    hint: "Para “nosotros”, los verbos en -ir terminan en -imos: vivimos.",
    explanation: "Nosotros vivimos: -imos marca la primera persona del plural.",
    examples: "Vivimos, escribimos, abrimos, salimos…",
    almost: "Casi. Para “nosotros”, el verbo en -ir termina en -imos.",
    level: "Principiante 2",
  },
  {
    id: "hablas_ingles_muy_bien_104",
    mode: "sentence_builder",
    promptEnglish: "You speak English very well.",
    targetSpanish: ["hablas", "inglés", "muy", "bien"],
    availableTiles: ["bien", "muy", "inglés", "hablas", "hablo", "habla", "mal"],
    displayAnswer: "Hablas inglés muy bien.",
    pattern: "Presente · tú (-ar)",
    hint: "Para “tú”, los verbos en -ar terminan en -as: hablas.",
    explanation: "Tú hablas: la terminación -as marca la segunda persona.",
    examples: "Hablas, trabajas, estudias, cantas…",
    almost: "Casi. Para “tú”, el verbo en -ar termina en -as.",
    level: "Principiante 2",
  },
  {
    id: "bebo_agua_todos_los_dias_105",
    mode: "sentence_builder",
    promptEnglish: "I drink water every day.",
    targetSpanish: ["bebo", "agua", "todos", "los", "días"],
    availableTiles: ["días", "los", "todos", "agua", "bebo", "bebe", "las", "día"],
    displayAnswer: "Bebo agua todos los días.",
    pattern: "Presente · yo (-er)",
    hint: "Para “yo”, los verbos en -er también terminan en -o: bebo.",
    explanation: "Yo bebo: la terminación -o sirve para -ar y -er en la primera persona.",
    examples: "Bebo, como, leo, corro…",
    almost: "Casi. Para “yo”, el verbo en -er termina en -o.",
    level: "Principiante 2",
  },
  {
    id: "el_escribe_una_carta_106",
    mode: "sentence_builder",
    promptEnglish: "He writes a letter.",
    targetSpanish: ["él", "escribe", "una", "carta"],
    availableTiles: ["carta", "una", "escribe", "él", "escribo", "un", "escriben"],
    displayAnswer: "Él escribe una carta.",
    pattern: "Presente · él (-ir)",
    hint: "Para “él/ella”, los verbos en -ir terminan en -e: escribe.",
    explanation: "Él escribe: -er y -ir comparten la terminación -e en tercera persona.",
    examples: "Escribe, vive, abre, recibe…",
    almost: "Casi. Para “él”, el verbo en -ir termina en -e.",
    level: "Principiante 2",
  },
  {
    id: "estudio_espanol_por_la_noche_107",
    mode: "sentence_builder",
    promptEnglish: "I study Spanish at night.",
    targetSpanish: ["estudio", "español", "por", "la", "noche"],
    availableTiles: ["noche", "la", "por", "español", "estudio", "estudia", "el", "mañana"],
    displayAnswer: "Estudio español por la noche.",
    pattern: "Presente · yo + “por la noche”",
    hint: "“Por la noche” dice cuándo haces algo, sin hora exacta.",
    explanation: "Estudio (yo) + por la noche: la rutina del día.",
    examples: "Por la mañana, por la tarde, por la noche…",
    almost: "Casi. Revisa el orden: verbo, luego “por la noche”.",
    level: "Principiante 2",
  },
  {
    id: "ella_lee_el_periodico_108",
    mode: "sentence_builder",
    promptEnglish: "She reads the newspaper.",
    targetSpanish: ["ella", "lee", "el", "periódico"],
    availableTiles: ["periódico", "el", "lee", "ella", "leo", "la", "leen"],
    displayAnswer: "Ella lee el periódico.",
    pattern: "Presente · ella (-er)",
    hint: "“El periódico” es masculino: lleva el artículo “el”.",
    explanation: "Ella lee: tercera persona; “el periódico” es masculino.",
    examples: "Lee, come, bebe, aprende…",
    almost: "Casi. Para “ella”, el verbo en -er termina en -e.",
    level: "Principiante 2",
  },
  {
    id: "abrimos_la_tienda_a_las_nueve_109",
    mode: "sentence_builder",
    promptEnglish: "We open the store at nine.",
    targetSpanish: ["abrimos", "la", "tienda", "a", "las", "nueve"],
    availableTiles: ["nueve", "las", "a", "tienda", "la", "abrimos", "abren", "el", "abro"],
    displayAnswer: "Abrimos la tienda a las nueve.",
    pattern: "Presente · nosotros + hora",
    hint: "Para decir la hora usamos “a las…”: a las nueve.",
    explanation: "Nosotros abrimos (-ir) + “a las nueve” para la hora.",
    examples: "A las ocho, a las nueve, a las diez…",
    almost: "Casi. La hora va con “a las”.",
    level: "Principiante 2",
  },
  {
    id: "viven_en_la_ciudad_110",
    mode: "sentence_builder",
    promptEnglish: "They live in the city.",
    targetSpanish: ["viven", "en", "la", "ciudad"],
    availableTiles: ["ciudad", "la", "en", "viven", "vive", "vivimos", "el"],
    displayAnswer: "Viven en la ciudad.",
    pattern: "Presente · ellos (-ir)",
    hint: "Para “ellos/ellas”, los verbos en -ir terminan en -en: viven.",
    explanation: "Ellos viven: -en marca la tercera persona del plural.",
    examples: "Viven, escriben, abren, salen…",
    almost: "Casi. Para “ellos”, el verbo en -ir termina en -en.",
    level: "Principiante 2",
  },

  /* ── Principiante 3 · Preguntas ──────────────────────────────────────── */
  {
    id: "donde_vives_201",
    mode: "sentence_builder",
    promptEnglish: "Where do you live?",
    targetSpanish: ["dónde", "vives"],
    availableTiles: ["vives", "dónde", "vivo", "cómo", "vive"],
    displayAnswer: "¿Dónde vives?",
    pattern: "Pregunta · ¿Dónde…?",
    hint: "“¿Dónde…?” pregunta por el lugar; el verbo va justo después.",
    explanation: "¿Dónde vives?: la palabra de pregunta abre la frase.",
    examples: "¿Dónde vives?, ¿dónde trabajas?, ¿dónde comes?…",
    almost: "Casi. Empieza con la palabra de pregunta: “¿Dónde…?”.",
    level: "Principiante 3",
  },
  {
    id: "a_que_hora_es_la_clase_202",
    mode: "sentence_builder",
    promptEnglish: "What time is the class?",
    targetSpanish: ["a", "qué", "hora", "es", "la", "clase"],
    availableTiles: ["clase", "la", "es", "hora", "qué", "a", "el", "cuándo"],
    displayAnswer: "¿A qué hora es la clase?",
    pattern: "Pregunta · ¿A qué hora…?",
    hint: "Para preguntar la hora exacta usamos “¿A qué hora…?”.",
    explanation: "¿A qué hora es…?: pregunta el momento exacto de algo.",
    examples: "¿A qué hora es la clase?, ¿a qué hora abres?…",
    almost: "Casi. Empieza con “¿A qué hora…?”.",
    level: "Principiante 3",
  },
  {
    id: "quieres_cafe_203",
    mode: "sentence_builder",
    promptEnglish: "Do you want coffee?",
    targetSpanish: ["quieres", "café"],
    availableTiles: ["café", "quieres", "quiero", "té", "quiere"],
    displayAnswer: "¿Quieres café?",
    pattern: "Pregunta · sí / no",
    hint: "En preguntas de sí o no, el verbo va primero: ¿Quieres…?",
    explanation: "¿Quieres café?: sin palabra de pregunta, empieza el verbo.",
    examples: "¿Quieres café?, ¿quieres agua?, ¿quieres salir?…",
    almost: "Casi. Para “tú”, el verbo es “quieres”.",
    level: "Principiante 3",
  },
  {
    id: "como_te_llamas_204",
    mode: "sentence_builder",
    promptEnglish: "What's your name?",
    targetSpanish: ["cómo", "te", "llamas"],
    availableTiles: ["llamas", "te", "cómo", "qué", "me", "llamo"],
    displayAnswer: "¿Cómo te llamas?",
    pattern: "Pregunta · ¿Cómo…?",
    hint: "“¿Cómo te llamas?” es la forma natural de pedir el nombre.",
    explanation: "Literalmente “¿cómo te llamas?” = “¿how do you call yourself?”.",
    examples: "¿Cómo te llamas?, ¿cómo estás?, ¿cómo se dice…?",
    almost: "Casi. El orden es “¿Cómo te llamas?”.",
    level: "Principiante 3",
  },
  {
    id: "donde_esta_el_bano_205",
    mode: "sentence_builder",
    promptEnglish: "Where is the bathroom?",
    targetSpanish: ["dónde", "está", "el", "baño"],
    availableTiles: ["baño", "el", "está", "dónde", "la", "es", "están"],
    displayAnswer: "¿Dónde está el baño?",
    pattern: "Pregunta · ¿Dónde está…?",
    hint: "Para ubicar algo usamos “estar”: ¿Dónde está…?",
    explanation: "Para lugares usamos “estar”, no “ser”: ¿Dónde está el baño?",
    examples: "¿Dónde está el baño?, ¿dónde está la salida?…",
    almost: "Casi. Para ubicación usamos “está”, no “es”.",
    level: "Principiante 3",
  },
  {
    id: "cuanto_cuesta_206",
    mode: "sentence_builder",
    promptEnglish: "How much does it cost?",
    targetSpanish: ["cuánto", "cuesta"],
    availableTiles: ["cuesta", "cuánto", "cuántos", "cuestan", "cómo"],
    displayAnswer: "¿Cuánto cuesta?",
    pattern: "Pregunta · ¿Cuánto…?",
    hint: "“¿Cuánto cuesta?” pregunta el precio de una cosa.",
    explanation: "¿Cuánto cuesta? para una cosa; ¿cuánto cuestan? para varias.",
    examples: "¿Cuánto cuesta?, ¿cuánto es?, ¿cuánto cuestan?…",
    almost: "Casi. Para una sola cosa: “¿Cuánto cuesta?”.",
    level: "Principiante 3",
  },
  {
    id: "que_haces_207",
    mode: "sentence_builder",
    promptEnglish: "What do you do?",
    targetSpanish: ["qué", "haces"],
    availableTiles: ["haces", "qué", "hago", "dónde", "hace"],
    displayAnswer: "¿Qué haces?",
    pattern: "Pregunta · ¿Qué…?",
    hint: "“¿Qué haces?” pregunta por la acción; “hacer” para “tú” es “haces”.",
    explanation: "¿Qué haces?: la palabra de pregunta abre y el verbo sigue.",
    examples: "¿Qué haces?, ¿qué quieres?, ¿qué comes?…",
    almost: "Casi. Para “tú”, el verbo es “haces”.",
    level: "Principiante 3",
  },
  {
    id: "hablas_ingles_208",
    mode: "sentence_builder",
    promptEnglish: "Do you speak English?",
    targetSpanish: ["hablas", "inglés"],
    availableTiles: ["inglés", "hablas", "hablo", "español", "habla"],
    displayAnswer: "¿Hablas inglés?",
    pattern: "Pregunta · sí / no",
    hint: "En preguntas de sí o no, empieza el verbo: ¿Hablas…?",
    explanation: "¿Hablas inglés?: sin palabra de pregunta, el verbo va primero.",
    examples: "¿Hablas inglés?, ¿hablas español?, ¿trabajas hoy?…",
    almost: "Casi. Para “tú”, el verbo es “hablas”.",
    level: "Principiante 3",
  },
  {
    id: "cuando_empezamos_209",
    mode: "sentence_builder",
    promptEnglish: "When do we start?",
    targetSpanish: ["cuándo", "empezamos"],
    availableTiles: ["empezamos", "cuándo", "empiezo", "dónde", "empiezan"],
    displayAnswer: "¿Cuándo empezamos?",
    pattern: "Pregunta · ¿Cuándo…?",
    hint: "“¿Cuándo…?” pregunta por el momento; el verbo va después.",
    explanation: "¿Cuándo empezamos?: nosotros → la terminación -amos.",
    examples: "¿Cuándo empezamos?, ¿cuándo sales?, ¿cuándo llega?…",
    almost: "Casi. Para “nosotros”, el verbo es “empezamos”.",
    level: "Principiante 3",
  },
  {
    id: "por_que_estudias_espanol_210",
    mode: "sentence_builder",
    promptEnglish: "Why do you study Spanish?",
    targetSpanish: ["por", "qué", "estudias", "español"],
    availableTiles: ["español", "estudias", "qué", "por", "estudio", "porque", "inglés"],
    displayAnswer: "¿Por qué estudias español?",
    pattern: "Pregunta · ¿Por qué…?",
    hint: "“¿Por qué…?” (dos palabras) pregunta la razón; “porque” (una) la responde.",
    explanation: "Pregunta con “por qué” separado; se responde con “porque” junto.",
    examples: "¿Por qué estudias?, ¿por qué trabajas?, ¿por qué vienes?…",
    almost: "Casi. La pregunta usa “por qué” en dos palabras.",
    level: "Principiante 3",
  },

  /* ── Principiante 4 · Rutina y reflexivos ────────────────────────────── */
  {
    id: "me_levanto_temprano_301",
    mode: "sentence_builder",
    promptEnglish: "I wake up early.",
    targetSpanish: ["me", "levanto", "temprano"],
    availableTiles: ["temprano", "me", "se", "levanto", "levanta", "tarde", "mi", "despierto"],
    displayAnswer: "Me levanto temprano.",
    pattern: "Reflexivos · me + verbo",
    hint: "Los verbos reflexivos llevan “me” para “yo”: me levanto.",
    explanation: "Me levanto: el pronombre “me” marca que la acción es sobre mí.",
    examples: "Me levanto, me ducho, me visto…",
    almost: "Casi. Para “yo”, el reflexivo usa “me”.",
    level: "Principiante 4",
  },
  {
    id: "se_llama_maria_302",
    mode: "sentence_builder",
    promptEnglish: "Her name is María.",
    targetSpanish: ["se", "llama", "maría"],
    availableTiles: ["maría", "se", "llama", "me", "te", "llamo", "llamas", "llaman"],
    displayAnswer: "Se llama María.",
    pattern: "Reflexivos · se",
    hint: "“Se llama” = his/her name is. El pronombre “se” es para él/ella.",
    explanation: "Se llama María: “se” marca la tercera persona.",
    examples: "Me llamo, te llamas, se llama…",
    almost: "Casi. Para “él/ella” usa “se”.",
    level: "Principiante 4",
  },
  {
    id: "me_ducho_por_la_manana_303",
    mode: "sentence_builder",
    promptEnglish: "I take a shower in the morning.",
    targetSpanish: ["me", "ducho", "por", "la", "mañana"],
    availableTiles: ["mañana", "la", "por", "ducho", "me", "se", "ducha", "en", "noche"],
    displayAnswer: "Me ducho por la mañana.",
    pattern: "Reflexivos · rutina",
    hint: "“Por la mañana” dice cuándo; el reflexivo es “me ducho”.",
    explanation: "Me ducho por la mañana: rutina diaria en primera persona.",
    examples: "Me ducho, me lavo, me peino…",
    almost: "Casi. Revisa el pronombre “me” y “por la mañana”.",
    level: "Principiante 4",
  },
  {
    id: "nos_vemos_manana_304",
    mode: "sentence_builder",
    promptEnglish: "We'll see each other tomorrow.",
    targetSpanish: ["nos", "vemos", "mañana"],
    availableTiles: ["mañana", "nos", "vemos", "se", "ve", "les", "hoy", "vamos"],
    displayAnswer: "Nos vemos mañana.",
    pattern: "Reflexivos · nos",
    hint: "“Nos vemos” = see you. El pronombre “nos” es para nosotros.",
    explanation: "Nos vemos mañana: “nos” marca la primera persona del plural.",
    examples: "Nos vemos, nos hablamos, nos cuidamos…",
    almost: "Casi. Para “nosotros” usa “nos”.",
    level: "Principiante 4",
  },
  {
    id: "se_acuesta_tarde_305",
    mode: "sentence_builder",
    promptEnglish: "He goes to bed late.",
    targetSpanish: ["se", "acuesta", "tarde"],
    availableTiles: ["tarde", "se", "acuesta", "me", "acuesto", "temprano", "te", "acostar"],
    displayAnswer: "Se acuesta tarde.",
    pattern: "Reflexivos · se",
    hint: "“Acostarse” es reflexivo: para él/ella, “se acuesta”.",
    explanation: "Se acuesta tarde: “se” + verbo en tercera persona.",
    examples: "Me acuesto, te acuestas, se acuesta…",
    almost: "Casi. Para “él/ella” usa “se”.",
    level: "Principiante 4",
  },
  {
    id: "me_siento_cansada_hoy_306",
    mode: "sentence_builder",
    promptEnglish: "I feel tired today.",
    targetSpanish: ["me", "siento", "cansada", "hoy"],
    availableTiles: ["hoy", "cansada", "siento", "me", "se", "siente", "cansado", "mañana", "estoy"],
    displayAnswer: "Me siento cansada hoy.",
    pattern: "Reflexivos · sentirse",
    hint: "“Sentirse” describe cómo estás: me siento cansada.",
    explanation: "Me siento cansada: “me” + siento para hablar de mí.",
    examples: "Me siento bien, me siento feliz, me siento cansada…",
    almost: "Casi. Para “yo” usa “me siento”.",
    level: "Principiante 4",
  },
  {
    id: "te_vistes_rapido_307",
    mode: "sentence_builder",
    promptEnglish: "You get dressed quickly.",
    targetSpanish: ["te", "vistes", "rápido"],
    availableTiles: ["rápido", "te", "vistes", "se", "viste", "me", "visto", "lento"],
    displayAnswer: "Te vistes rápido.",
    pattern: "Reflexivos · te",
    hint: "Para “tú”, el reflexivo usa “te”: te vistes.",
    explanation: "Te vistes rápido: “te” marca la segunda persona.",
    examples: "Me visto, te vistes, se viste…",
    almost: "Casi. Para “tú” usa “te”.",
    level: "Principiante 4",
  },
  {
    id: "me_levanto_y_hago_cafe_308",
    mode: "sentence_builder",
    promptEnglish: "I get up and make coffee.",
    targetSpanish: ["me", "levanto", "y", "hago", "café"],
    availableTiles: ["café", "hago", "y", "levanto", "me", "se", "levanta", "hace", "té", "pero"],
    displayAnswer: "Me levanto y hago café.",
    pattern: "Reflexivos + “y”",
    hint: "Une dos acciones con “y”: me levanto y hago café.",
    explanation: "Dos cosas seguidas: “me levanto” y luego “hago café”.",
    examples: "Me levanto y desayuno, me ducho y salgo…",
    almost: "Casi. Une las dos acciones con “y”.",
    level: "Principiante 4",
  },
  {
    id: "nos_quedamos_en_casa_los_domingos_309",
    mode: "sentence_builder",
    promptEnglish: "We stay home on Sundays.",
    targetSpanish: ["nos", "quedamos", "en", "casa", "los", "domingos"],
    availableTiles: ["domingos", "los", "casa", "en", "quedamos", "nos", "se", "queda", "la", "domingo", "el"],
    displayAnswer: "Nos quedamos en casa los domingos.",
    pattern: "Reflexivos · nos + rutina",
    hint: "“Los domingos” = every Sunday. El reflexivo es “nos quedamos”.",
    explanation: "Nos quedamos en casa los domingos: hábito de fin de semana.",
    examples: "Los lunes, los domingos, los fines de semana…",
    almost: "Casi. Para “nosotros” usa “nos” y “los domingos”.",
    level: "Principiante 4",
  },
  {
    id: "me_preparo_para_el_trabajo_310",
    mode: "sentence_builder",
    promptEnglish: "I get ready for work.",
    targetSpanish: ["me", "preparo", "para", "el", "trabajo"],
    availableTiles: ["trabajo", "el", "para", "preparo", "me", "se", "prepara", "por", "la", "trabajar"],
    displayAnswer: "Me preparo para el trabajo.",
    pattern: "Reflexivos · me + para",
    hint: "“Para” indica el objetivo: me preparo para el trabajo.",
    explanation: "Me preparo para el trabajo: “para” marca el propósito.",
    examples: "Me preparo para la clase, para el día, para salir…",
    almost: "Casi. Usa “me preparo” y “para”.",
    level: "Principiante 4",
  },

  /* ── Intermedio 1 · El pretérito ─────────────────────────────────────── */
  {
    id: "ayer_trabaje_todo_el_dia_401",
    mode: "sentence_builder",
    promptEnglish: "Yesterday I worked all day.",
    targetSpanish: ["ayer", "trabajé", "todo", "el", "día"],
    availableTiles: ["día", "el", "todo", "trabajé", "ayer", "trabajo", "trabajaba", "la", "mañana", "trabajó"],
    displayAnswer: "Ayer trabajé todo el día.",
    pattern: "Pretérito · yo (-ar)",
    hint: "En pretérito, “yo” en -ar termina en -é: trabajé.",
    explanation: "Trabajé: acción terminada en el pasado, primera persona.",
    examples: "Trabajé, hablé, estudié, cociné…",
    almost: "Casi. Para “yo” en pasado: trabajé.",
    level: "Intermedio 1",
  },
  {
    id: "anoche_comi_en_casa_402",
    mode: "sentence_builder",
    promptEnglish: "Last night I ate at home.",
    targetSpanish: ["anoche", "comí", "en", "casa"],
    availableTiles: ["casa", "en", "comí", "anoche", "como", "comía", "comió", "la", "hoy"],
    displayAnswer: "Anoche comí en casa.",
    pattern: "Pretérito · yo (-er)",
    hint: "En pretérito, “yo” en -er/-ir termina en -í: comí.",
    explanation: "Comí: pasado terminado en primera persona.",
    examples: "Comí, bebí, salí, escribí…",
    almost: "Casi. Para “yo” en pasado: comí.",
    level: "Intermedio 1",
  },
  {
    id: "fuimos_al_centro_403",
    mode: "sentence_builder",
    promptEnglish: "We went to the center.",
    targetSpanish: ["fuimos", "al", "centro"],
    availableTiles: ["centro", "al", "fuimos", "vamos", "fueron", "fui", "el", "a"],
    displayAnswer: "Fuimos al centro.",
    pattern: "Pretérito · ir (irregular)",
    hint: "“Ir” es irregular: nosotros → fuimos.",
    explanation: "Fuimos: pretérito irregular de “ir”.",
    examples: "Fui, fuiste, fue, fuimos…",
    almost: "Casi. Para “nosotros”: fuimos.",
    level: "Intermedio 1",
  },
  {
    id: "ella_hablo_con_la_directora_404",
    mode: "sentence_builder",
    promptEnglish: "She spoke with the director.",
    targetSpanish: ["ella", "habló", "con", "la", "directora"],
    availableTiles: ["directora", "la", "con", "habló", "ella", "habla", "hablé", "el", "director", "hablaba"],
    displayAnswer: "Ella habló con la directora.",
    pattern: "Pretérito · ella (-ar)",
    hint: "En pretérito, “él/ella” en -ar termina en -ó: habló.",
    explanation: "Habló: pasado en tercera persona; ojo con el acento.",
    examples: "Habló, trabajó, estudió, llamó…",
    almost: "Casi. Para “ella” en pasado: habló.",
    level: "Intermedio 1",
  },
  {
    id: "ayer_hice_la_cena_405",
    mode: "sentence_builder",
    promptEnglish: "Yesterday I made dinner.",
    targetSpanish: ["ayer", "hice", "la", "cena"],
    availableTiles: ["cena", "la", "hice", "ayer", "hago", "hizo", "hacía", "el", "hacer"],
    displayAnswer: "Ayer hice la cena.",
    pattern: "Pretérito · hacer (irregular)",
    hint: "“Hacer” es irregular: yo → hice.",
    explanation: "Hice: pretérito irregular de “hacer”.",
    examples: "Hice, hiciste, hizo, hicimos…",
    almost: "Casi. Para “yo”: hice.",
    level: "Intermedio 1",
  },
  {
    id: "estudiaste_anoche_406",
    mode: "sentence_builder",
    promptEnglish: "Did you study last night?",
    targetSpanish: ["estudiaste", "anoche"],
    availableTiles: ["anoche", "estudiaste", "estudias", "estudió", "estudiaba", "ayer", "estudiaron"],
    displayAnswer: "¿Estudiaste anoche?",
    pattern: "Pretérito · tú (-ar)",
    hint: "En pretérito, “tú” en -ar termina en -aste: estudiaste.",
    explanation: "Estudiaste: pasado en segunda persona.",
    examples: "Estudiaste, trabajaste, hablaste…",
    almost: "Casi. Para “tú” en pasado: estudiaste.",
    level: "Intermedio 1",
  },
  {
    id: "llego_tarde_407",
    mode: "sentence_builder",
    promptEnglish: "He arrived late.",
    targetSpanish: ["llegó", "tarde"],
    availableTiles: ["tarde", "llegó", "llega", "llegué", "temprano", "llegaba", "llegaron"],
    displayAnswer: "Llegó tarde.",
    pattern: "Pretérito · él (-ar)",
    hint: "En pretérito, “él/ella” en -ar termina en -ó: llegó.",
    explanation: "Llegó: pasado terminado en tercera persona.",
    examples: "Llegó, salió, entró, terminó…",
    almost: "Casi. Para “él” en pasado: llegó.",
    level: "Intermedio 1",
  },
  {
    id: "compre_un_libro_nuevo_408",
    mode: "sentence_builder",
    promptEnglish: "I bought a new book.",
    targetSpanish: ["compré", "un", "libro", "nuevo"],
    availableTiles: ["nuevo", "libro", "un", "compré", "compro", "compró", "una", "vieja", "compraba"],
    displayAnswer: "Compré un libro nuevo.",
    pattern: "Pretérito · yo (-ar)",
    hint: "“Compré” es pasado; “un libro nuevo” concuerda en masculino.",
    explanation: "Compré: pasado en primera persona; libro es masculino → nuevo.",
    examples: "Compré, vendí, encontré, pagué…",
    almost: "Casi. Para “yo” en pasado: compré.",
    level: "Intermedio 1",
  },
  {
    id: "lo_pasamos_bien_409",
    mode: "sentence_builder",
    promptEnglish: "We had a good time.",
    targetSpanish: ["lo", "pasamos", "bien"],
    availableTiles: ["bien", "pasamos", "lo", "la", "pasó", "mal", "paso", "les"],
    displayAnswer: "Lo pasamos bien.",
    pattern: "Pretérito · expresión",
    hint: "“Pasarlo bien” = to have a good time. Nosotros → lo pasamos bien.",
    explanation: "Lo pasamos bien: forma común de decir que disfrutamos.",
    examples: "Lo paso bien, lo pasamos bien, lo pasaron bien…",
    almost: "Casi. La expresión es “lo pasamos bien”.",
    level: "Intermedio 1",
  },
  {
    id: "que_hiciste_ayer_410",
    mode: "sentence_builder",
    promptEnglish: "What did you do yesterday?",
    targetSpanish: ["qué", "hiciste", "ayer"],
    availableTiles: ["ayer", "hiciste", "qué", "haces", "hizo", "hacías", "hoy", "dónde"],
    displayAnswer: "¿Qué hiciste ayer?",
    pattern: "Pretérito · pregunta",
    hint: "“Hacer” para “tú” en pasado es “hiciste”: ¿Qué hiciste?",
    explanation: "¿Qué hiciste ayer?: pregunta sobre una acción pasada.",
    examples: "¿Qué hiciste?, ¿qué comiste?, ¿adónde fuiste?…",
    almost: "Casi. Para “tú” en pasado: hiciste.",
    level: "Intermedio 1",
  },

  /* ── Intermedio 2 · Ser, estar, por y para ───────────────────────────── */
  {
    id: "soy_maestra_501",
    mode: "sentence_builder",
    promptEnglish: "I'm a teacher.",
    targetSpanish: ["soy", "maestra"],
    availableTiles: ["maestra", "soy", "estoy", "es", "maestro", "ser", "está"],
    displayAnswer: "Soy maestra.",
    pattern: "Ser · profesión",
    hint: "Para profesiones e identidad usamos “ser”: soy maestra.",
    explanation: "Soy maestra: “ser” para lo que eres de forma estable.",
    examples: "Soy maestra, soy de Georgia, soy alta…",
    almost: "Casi. Para profesión usa “soy”, no “estoy”.",
    level: "Intermedio 2",
  },
  {
    id: "estoy_cansada_hoy_502",
    mode: "sentence_builder",
    promptEnglish: "I'm tired today.",
    targetSpanish: ["estoy", "cansada", "hoy"],
    availableTiles: ["hoy", "cansada", "estoy", "soy", "está", "cansado", "ser", "mañana"],
    displayAnswer: "Estoy cansada hoy.",
    pattern: "Estar · estado",
    hint: "Para estados y emociones usamos “estar”: estoy cansada.",
    explanation: "Estoy cansada: “estar” para cómo te sientes ahora.",
    examples: "Estoy cansada, estoy feliz, estoy en casa…",
    almost: "Casi. Para un estado usa “estoy”, no “soy”.",
    level: "Intermedio 2",
  },
  {
    id: "el_cafe_es_para_ti_503",
    mode: "sentence_builder",
    promptEnglish: "The coffee is for you.",
    targetSpanish: ["el", "café", "es", "para", "ti"],
    availableTiles: ["ti", "para", "es", "café", "el", "por", "está", "mí", "una", "yo"],
    displayAnswer: "El café es para ti.",
    pattern: "Para · destinatario",
    hint: "“Para” marca a quién va dirigido algo: para ti.",
    explanation: "Para ti: “para” indica el destinatario.",
    examples: "Para ti, para mí, para mi mamá…",
    almost: "Casi. El destinatario va con “para”.",
    level: "Intermedio 2",
  },
  {
    id: "estudiamos_por_la_manana_504",
    mode: "sentence_builder",
    promptEnglish: "We study in the morning.",
    targetSpanish: ["estudiamos", "por", "la", "mañana"],
    availableTiles: ["mañana", "la", "por", "estudiamos", "para", "el", "noche", "estudiar", "estudian"],
    displayAnswer: "Estudiamos por la mañana.",
    pattern: "Por · parte del día",
    hint: "Para partes del día usamos “por”: por la mañana.",
    explanation: "Por la mañana: “por” con momentos del día.",
    examples: "Por la mañana, por la tarde, por la noche…",
    almost: "Casi. Las partes del día van con “por”.",
    level: "Intermedio 2",
  },
  {
    id: "ella_esta_en_casa_505",
    mode: "sentence_builder",
    promptEnglish: "She is at home.",
    targetSpanish: ["ella", "está", "en", "casa"],
    availableTiles: ["casa", "en", "está", "ella", "es", "están", "la", "el", "ser"],
    displayAnswer: "Ella está en casa.",
    pattern: "Estar · ubicación",
    hint: "Para ubicación usamos “estar”: está en casa.",
    explanation: "Está en casa: el lugar siempre va con “estar”.",
    examples: "Está en casa, está aquí, está en el centro…",
    almost: "Casi. Para ubicación usa “está”, no “es”.",
    level: "Intermedio 2",
  },
  {
    id: "la_clase_es_a_las_ocho_506",
    mode: "sentence_builder",
    promptEnglish: "The class is at eight.",
    targetSpanish: ["la", "clase", "es", "a", "las", "ocho"],
    availableTiles: ["ocho", "las", "a", "es", "clase", "la", "está", "el", "por", "los", "nueve"],
    displayAnswer: "La clase es a las ocho.",
    pattern: "Ser · hora de un evento",
    hint: "La hora de un evento va con “ser”: la clase es a las ocho.",
    explanation: "Es a las ocho: para eventos y horas usamos “ser”.",
    examples: "Es a las ocho, es a la una, es el lunes…",
    almost: "Casi. La hora del evento usa “es”.",
    level: "Intermedio 2",
  },
  {
    id: "gracias_por_tu_ayuda_507",
    mode: "sentence_builder",
    promptEnglish: "Thanks for your help.",
    targetSpanish: ["gracias", "por", "tu", "ayuda"],
    availableTiles: ["ayuda", "tu", "por", "gracias", "para", "su", "la", "ayudar", "ti"],
    displayAnswer: "Gracias por tu ayuda.",
    pattern: "Por · motivo",
    hint: "“Gracias por…” agradece el motivo: por tu ayuda.",
    explanation: "Por tu ayuda: “por” da la razón del agradecimiento.",
    examples: "Gracias por tu ayuda, por todo, por venir…",
    almost: "Casi. “Gracias por…”, no “para”.",
    level: "Intermedio 2",
  },
  {
    id: "este_regalo_es_para_mi_mama_508",
    mode: "sentence_builder",
    promptEnglish: "This gift is for my mom.",
    targetSpanish: ["este", "regalo", "es", "para", "mi", "mamá"],
    availableTiles: ["mamá", "mi", "para", "es", "regalo", "este", "por", "está", "tu", "esta", "el"],
    displayAnswer: "Este regalo es para mi mamá.",
    pattern: "Para · destinatario",
    hint: "El destinatario de un regalo va con “para”: para mi mamá.",
    explanation: "Para mi mamá: “para” marca quién recibe.",
    examples: "Para mi mamá, para ti, para mis amigos…",
    almost: "Casi. El destinatario va con “para”.",
    level: "Intermedio 2",
  },
  {
    id: "estoy_feliz_porque_es_viernes_509",
    mode: "sentence_builder",
    promptEnglish: "I'm happy because it's Friday.",
    targetSpanish: ["estoy", "feliz", "porque", "es", "viernes"],
    availableTiles: ["viernes", "es", "porque", "feliz", "estoy", "soy", "está", "por", "sábado", "ser"],
    displayAnswer: "Estoy feliz porque es viernes.",
    pattern: "Estar + porque",
    hint: "“Estoy feliz” (estado) + “porque” da la razón.",
    explanation: "Estoy feliz porque es viernes: estado + motivo con “porque”.",
    examples: "Estoy feliz porque…, cansada porque…, en casa porque…",
    almost: "Casi. Emoción con “estoy” y razón con “porque”.",
    level: "Intermedio 2",
  },
  {
    id: "mi_novio_es_de_el_salvador_510",
    mode: "sentence_builder",
    promptEnglish: "My boyfriend is from El Salvador.",
    targetSpanish: ["mi", "novio", "es", "de", "el", "salvador"],
    availableTiles: ["salvador", "el", "de", "es", "novio", "mi", "está", "en", "la", "del", "soy"],
    displayAnswer: "Mi novio es de El Salvador.",
    pattern: "Ser · origen",
    hint: "El origen va con “ser de”: es de El Salvador.",
    explanation: "Es de El Salvador: “ser de” indica de dónde es alguien.",
    examples: "Soy de Georgia, es de El Salvador, son de México…",
    almost: "Casi. El origen usa “es de”.",
    level: "Intermedio 2",
  },

  /* ── Intermedio 3 · Frases largas ────────────────────────────────────── */
  {
    id: "tengo_que_trabajar_porque_necesito_dinero_601",
    mode: "sentence_builder",
    promptEnglish: "I have to work because I need money.",
    targetSpanish: ["tengo", "que", "trabajar", "porque", "necesito", "dinero"],
    availableTiles: ["dinero", "necesito", "porque", "trabajar", "que", "tengo", "trabajo", "por", "necesita", "tiempo", "para"],
    displayAnswer: "Tengo que trabajar porque necesito dinero.",
    pattern: "Obligación + razón",
    hint: "Une una obligación con su razón usando “porque”.",
    explanation: "Tengo que trabajar (obligación) porque necesito dinero (razón).",
    examples: "…porque necesito, porque quiero, porque es importante…",
    almost: "Casi. Conecta las dos partes con “porque”.",
    level: "Intermedio 3",
  },
  {
    id: "quiero_estudiar_pero_estoy_cansada_602",
    mode: "sentence_builder",
    promptEnglish: "I want to study but I'm tired.",
    targetSpanish: ["quiero", "estudiar", "pero", "estoy", "cansada"],
    availableTiles: ["cansada", "estoy", "pero", "estudiar", "quiero", "quiere", "y", "soy", "cansado", "estudio"],
    displayAnswer: "Quiero estudiar pero estoy cansada.",
    pattern: "Contraste con “pero”",
    hint: "“Pero” marca un contraste entre las dos ideas.",
    explanation: "Quiero estudiar, pero estoy cansada: deseo contra estado.",
    examples: "…pero estoy cansada, pero no puedo, pero es tarde…",
    almost: "Casi. El contraste va con “pero”.",
    level: "Intermedio 3",
  },
  {
    id: "voy_al_centro_y_despues_como_603",
    mode: "sentence_builder",
    promptEnglish: "I go to the center and then I eat.",
    targetSpanish: ["voy", "al", "centro", "y", "después", "como"],
    availableTiles: ["como", "después", "y", "centro", "al", "voy", "va", "el", "antes", "comer", "pero"],
    displayAnswer: "Voy al centro y después como.",
    pattern: "Secuencia con “después”",
    hint: "“Y después” ordena dos acciones en el tiempo.",
    explanation: "Voy al centro y después como: primero una cosa, luego otra.",
    examples: "…y después como, y después salgo, y después descanso…",
    almost: "Casi. Ordena con “y después”.",
    level: "Intermedio 3",
  },
  {
    id: "cuando_llego_a_casa_hago_la_cena_604",
    mode: "sentence_builder",
    promptEnglish: "When I get home, I make dinner.",
    targetSpanish: ["cuando", "llego", "a", "casa", "hago", "la", "cena"],
    availableTiles: ["cena", "la", "hago", "casa", "a", "llego", "cuando", "llega", "el", "hace", "mientras", "comida"],
    displayAnswer: "Cuando llego a casa, hago la cena.",
    pattern: "Condición con “cuando”",
    hint: "“Cuando” (sin acento) conecta dos acciones; la pregunta lleva acento.",
    explanation: "Cuando llego a casa, hago la cena: una acción y luego otra.",
    examples: "Cuando llego…, cuando termino…, cuando puedo…",
    almost: "Casi. Aquí “cuando” va sin acento.",
    level: "Intermedio 3",
  },
  {
    id: "ella_trabaja_por_la_manana_y_estudia_por_la_noche_605",
    mode: "sentence_builder",
    promptEnglish: "She works in the morning and studies at night.",
    targetSpanish: ["ella", "trabaja", "por", "la", "mañana", "y", "estudia", "por", "la", "noche"],
    availableTiles: ["noche", "la", "por", "estudia", "y", "mañana", "la", "por", "trabaja", "ella", "él", "para", "pero", "día", "estudian"],
    displayAnswer: "Ella trabaja por la mañana y estudia por la noche.",
    pattern: "Dos rutinas con “y”",
    hint: "Repite la estructura “por la…” para cada parte del día.",
    explanation: "Trabaja por la mañana y estudia por la noche: dos rutinas unidas con “y”.",
    examples: "…por la mañana y por la noche, por la tarde y por la noche…",
    almost: "Casi. Usa “por la” para cada momento del día.",
    level: "Intermedio 3",
  },
  {
    id: "me_gusta_mi_trabajo_porque_cada_clase_cuenta_606",
    mode: "sentence_builder",
    promptEnglish: "I like my job because every class counts.",
    targetSpanish: ["me", "gusta", "mi", "trabajo", "porque", "cada", "clase", "cuenta"],
    availableTiles: ["cuenta", "clase", "cada", "porque", "trabajo", "mi", "gusta", "me", "gustan", "tu", "por", "clases", "cuentan"],
    displayAnswer: "Me gusta mi trabajo porque cada clase cuenta.",
    pattern: "Gusto + razón",
    hint: "“Cada clase” es singular, así que el verbo es “cuenta”.",
    explanation: "Me gusta mi trabajo porque cada clase cuenta: gusto y su razón.",
    examples: "…porque cada clase cuenta, porque ayudo, porque aprendo…",
    almost: "Casi. “Cada clase” lleva el verbo en singular: cuenta.",
    level: "Intermedio 3",
  },
  {
    id: "podemos_salir_si_quieres_607",
    mode: "sentence_builder",
    promptEnglish: "We can go out if you want.",
    targetSpanish: ["podemos", "salir", "si", "quieres"],
    availableTiles: ["quieres", "si", "salir", "podemos", "puedo", "salgo", "cuando", "quiero", "y"],
    displayAnswer: "Podemos salir si quieres.",
    pattern: "Condición con “si”",
    hint: "“Si” (sin acento) plantea una condición: si quieres.",
    explanation: "Podemos salir si quieres: la segunda parte es la condición.",
    examples: "…si quieres, si puedes, si tienes tiempo…",
    almost: "Casi. La condición va con “si”.",
    level: "Intermedio 3",
  },
  {
    id: "estoy_aprendiendo_espanol_para_hablar_con_estudiantes_608",
    mode: "sentence_builder",
    promptEnglish: "I'm learning Spanish to talk with my students.",
    targetSpanish: ["estoy", "aprendiendo", "español", "para", "hablar", "con", "mis", "estudiantes"],
    availableTiles: ["estudiantes", "mis", "con", "hablar", "para", "español", "aprendiendo", "estoy", "soy", "aprendo", "por", "mi", "estudiante"],
    displayAnswer: "Estoy aprendiendo español para hablar con mis estudiantes.",
    pattern: "Gerundio + propósito",
    hint: "“Estoy aprendiendo” (ahora) + “para” (propósito).",
    explanation: "Estoy aprendiendo español para hablar con mis estudiantes: acción en curso y su meta.",
    examples: "…para hablar, para entender, para ayudar…",
    almost: "Casi. El propósito va con “para”.",
    level: "Intermedio 3",
  },
  {
    id: "mi_novio_cocina_y_yo_lavo_los_platos_609",
    mode: "sentence_builder",
    promptEnglish: "My boyfriend cooks and I wash the dishes.",
    targetSpanish: ["mi", "novio", "cocina", "y", "yo", "lavo", "los", "platos"],
    availableTiles: ["platos", "los", "lavo", "yo", "y", "cocina", "novio", "mi", "tu", "cocino", "lava", "las", "el"],
    displayAnswer: "Mi novio cocina y yo lavo los platos.",
    pattern: "Dos sujetos con “y”",
    hint: "Cada sujeto lleva su verbo: él cocina, yo lavo.",
    explanation: "Mi novio cocina y yo lavo los platos: dos personas, dos acciones.",
    examples: "…y yo lavo, y yo limpio, y yo cocino…",
    almost: "Casi. Cada sujeto tiene su propio verbo.",
    level: "Intermedio 3",
  },
  {
    id: "si_practico_todos_los_dias_mejoro_610",
    mode: "sentence_builder",
    promptEnglish: "If I practice every day, I improve.",
    targetSpanish: ["si", "practico", "todos", "los", "días", "mejoro"],
    availableTiles: ["mejoro", "días", "los", "todos", "practico", "si", "practica", "el", "día", "mejora", "cuando"],
    displayAnswer: "Si practico todos los días, mejoro.",
    pattern: "Condición + resultado",
    hint: "“Si” presenta la condición; después viene el resultado.",
    explanation: "Si practico todos los días, mejoro: condición y su resultado.",
    examples: "Si practico…, si estudio…, si descanso…",
    almost: "Casi. Empieza con la condición: “Si practico…”.",
    level: "Intermedio 3",
  },
];

/* ── Home-screen copy ─────────────────────────────────────────────────── */

export const sentenceBuilderOverview = {
  pill: "Juego",
  title: "Construye la frase.",
  gloss:
    "Read an English sentence, then tap the Spanish words into the right order. A calm way to feel how Spanish sentences fit together — one tile at a time.",
};

/** The three-step "how to play", kept as data so the home screen stays simple. */
export const sentenceBuilderHowTo = [
  {
    title: "Lee la frase",
    body: "Arriba ves la frase en inglés: eso es lo que vas a decir en español.",
  },
  {
    title: "Toca las palabras",
    body: "Tócalas en orden. ¿Te equivocaste? Toca una palabra de tu frase para devolverla al banco.",
  },
  {
    title: "Comprueba",
    body: "Pulsa Comprobar. Si aciertas, escuchas la frase y pasas a la siguiente.",
  },
];

/* ── Levels ───────────────────────────────────────────────────────────── */

export type SentenceLevelStatus = "available" | "soon";

export type SentenceLevel = {
  /** Matches `SentenceCard.level` for available levels. */
  name: string;
  /** Short theme, e.g. "Verbo + infinitivo". */
  tagline: string;
  /** One calm line describing what you practise. */
  blurb: string;
  /** A few example patterns this level covers. */
  patterns: string[];
  status: SentenceLevelStatus;
};

export const sentenceBuilderLevels: SentenceLevel[] = [
  {
    name: "Principiante 1",
    tagline: "Verbo + infinitivo",
    blurb: "Combina un verbo común con un infinitivo para hablar de planes, deseos y obligaciones.",
    patterns: ["Tengo que + infinitivo", "Voy a + infinitivo", "Quiero / Me gusta + infinitivo"],
    status: "available",
  },
  {
    name: "Principiante 2",
    tagline: "El presente del día a día",
    blurb: "Frases cortas en presente: lo que haces cada día, en casa y en el trabajo.",
    patterns: ["Verbos -ar / -er / -ir", "Yo, tú, él y ella"],
    status: "available",
  },
  {
    name: "Principiante 3",
    tagline: "Preguntas",
    blurb: "Arma preguntas naturales para conversar y pedir lo que necesitas.",
    patterns: ["¿Qué…? ¿Dónde…? ¿A qué hora…?", "El orden de la pregunta"],
    status: "available",
  },
  {
    name: "Principiante 4",
    tagline: "Rutina y reflexivos",
    blurb: "Describe tu día con verbos reflexivos: levantarse, ducharse, sentirse y más.",
    patterns: ["me · te · se · nos", "Rutina diaria"],
    status: "available",
  },
  {
    name: "Intermedio 1",
    tagline: "El pretérito",
    blurb: "Cuenta lo que ya pasó: ayer, anoche y la semana pasada, en pretérito.",
    patterns: ["Pasado -é / -í / -ó", "Irregulares: fui, hice"],
    status: "available",
  },
  {
    name: "Intermedio 2",
    tagline: "Ser, estar, por y para",
    blurb: "Las parejas que más cuestan: ser vs estar y por vs para, en contexto.",
    patterns: ["Ser / Estar", "Por / Para"],
    status: "available",
  },
  {
    name: "Intermedio 3",
    tagline: "Frases largas",
    blurb: "Conecta ideas con porque, pero, y, cuando y después en frases más completas.",
    patterns: ["porque · pero · y", "cuando · después · si"],
    status: "available",
  },
];

/** The cards that belong to a given level, in authored order. */
export function cardsForLevel(levelName: string): SentenceCard[] {
  return sentenceBuilderCards.filter((c) => c.level === levelName);
}

/** How many cards live in a given level — drives the count shown on the home screen. */
export function levelCardCount(levelName: string): number {
  return cardsForLevel(levelName).length;
}
