import { SEASONS } from "@/lib/season";

export type Temporada = {
  index: 1 | 2 | 3 | 4;
  range: string;
  rangeEn: string;
  seasonLabel: string;
  color: string;
  title: string;
  titleEn: string;
  body: string;
  bodyEn: string;
  goals: string[];
  goalsEn: string[];
  /** The season's three movements, from content/CURRICULUM.md. */
  arc: string;
  arcEn: string;
  /** One tema per week — 13 per season (weeks beyond Verano are planned, not yet authored). */
  weeks: string[];
  weeksEn: string[];
};

export const TEMPORADAS: Temporada[] = [
  {
    index: 1,
    range: "Jun – Ago · verano",
    rangeEn: "Jun – Aug · summer",
    seasonLabel: "verano",
    color: SEASONS[0].color,
    title: "El verano que hablo",
    titleEn: "The summer I speak",
    body: "Una conversación simple, sin pánico — y tu primera noticia corta.",
    bodyEn: "One simple conversation, no panic — and your first short news story.",
    goals: ["Una conversación simple, sin pánico.", "Leer una noticia corta, entera."],
    goalsEn: ["One simple conversation, no panic.", "Read one short news article, all the way through."],
    arc: "afirmar → interactuar → profundizar",
    arcEn: "assert → interact → deepen",
    weeks: [
      "Afirmar I",
      "Afirmar II",
      "Preguntas",
      "Pedir",
      "Reaccionar",
      "Historias",
      "Explicar",
      "Consejos",
      "Planes",
      "Matices",
      "Problemas",
      "Sentimientos",
      "La conversación entera",
    ],
    weeksEn: [
      "Assert I",
      "Assert II",
      "Questions",
      "Asking for things",
      "Reacting",
      "Stories",
      "Explaining",
      "Advice",
      "Plans together",
      "Nuance",
      "Problems",
      "Feelings",
      "The whole conversation",
    ],
  },
  {
    index: 2,
    range: "Sep – Nov · otoño",
    rangeEn: "Sep – Nov · fall",
    seasonLabel: "otoño",
    color: SEASONS[1].color,
    title: "Seguir el hilo",
    titleEn: "Follow the thread",
    body: "Sigues una historia en las noticias · hablas un minuto sin parar.",
    bodyEn: "You follow a story in the news · you speak for a minute without stopping.",
    goals: ["Seguir una historia varios días.", "Hablar un minuto sin parar."],
    goalsEn: ["Follow one story for several days.", "Speak for a minute without stopping."],
    arc: "recontar → conectar → sostener",
    arcEn: "retell → connect → sustain",
    weeks: [
      "Resumir",
      "Dice que…",
      "Dijo que…",
      "Ya había pasado",
      "Además",
      "Sin embargo",
      "Por eso",
      "Ordenar las ideas",
      "¿Te enteraste?",
      "Opinar",
      "Seguir la historia",
      "El minuto entero",
      "El hilo entero",
    ],
    weeksEn: [
      "Summing up",
      "It says…",
      "She said…",
      "It had already happened",
      "What's more",
      "However",
      "That's why",
      "Ordering your ideas",
      "Did you hear?",
      "Weighing in",
      "Following the story",
      "The full minute",
      "The whole thread",
    ],
  },
  {
    index: 3,
    range: "Dic – Feb · invierno",
    rangeEn: "Dec – Feb · winter",
    seasonLabel: "invierno",
    color: SEASONS[2].color,
    title: "Sin subtítulos",
    titleEn: "No subtitles",
    body: "Ves algo sin subtítulos, sin perderte · una charla de ida y vuelta.",
    bodyEn: "You watch something without subtitles, without getting lost · a back-and-forth conversation.",
    goals: ["Ver algo sin subtítulos.", "Una charla de ida y vuelta."],
    goalsEn: ["Watch something without subtitles.", "A back-and-forth conversation."],
    arc: "sonar natural → subjuntivo → tiempo real",
    arcEn: "sound natural → subjunctive → real time",
    weeks: [
      "Muletillas I",
      "Muletillas II",
      "Al teléfono",
      "Notas de voz",
      "Quiero que…",
      "Cuando llegues…",
      "Ojalá",
      "Es mejor que…",
      "Interrumpir",
      "El turno",
      "Sin captar todo",
      "A velocidad real",
      "Ida y vuelta",
    ],
    weeksEn: [
      "Fillers I",
      "Fillers II",
      "On the phone",
      "Voice notes",
      "I want you to…",
      "When you arrive…",
      "Hopefully",
      "It's better if…",
      "Interrupting",
      "Taking turns",
      "Not catching it all",
      "At real speed",
      "Back and forth",
    ],
  },
  {
    index: 4,
    range: "Mar – May · primavera",
    rangeEn: "Mar – May · spring",
    seasonLabel: "primavera",
    color: SEASONS[3].color,
    title: "Conversación completa",
    titleEn: "Full conversation",
    body: "Una conversación larga, con bromas y silencios, sin esfuerzo.",
    bodyEn: "A long conversation, with jokes and silences, effortlessly.",
    goals: ["Una conversación larga y natural.", "Bromas y silencios, sin esfuerzo."],
    goalsEn: ["A long, natural conversation.", "Jokes and silences, effortlessly."],
    arc: "tu voz → debate suave → conversación larga",
    arcEn: "your voice → gentle debate → the long conversation",
    weeks: [
      "Tu estilo",
      "Humor ligero",
      "Exagerar",
      "Historias con sabor",
      "Debate suave I",
      "Debate suave II",
      "Cambiar de registro",
      "Temas grandes",
      "Profundizar",
      "Sin preparación",
      "Conversación larga I",
      "Conversación larga II",
      "El año entero",
    ],
    weeksEn: [
      "Your style",
      "Light humor",
      "Exaggerating",
      "Stories with flavor",
      "Gentle debate I",
      "Gentle debate II",
      "Switching register",
      "Big topics",
      "Going deeper",
      "No prep",
      "The long conversation I",
      "The long conversation II",
      "The whole year",
    ],
  },
];
