import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 12 draft — "El minuto entero" (days 169–175).
 *
 * Append to content/prompts/otono.ts. prompt.spanish must stay verbatim with
 * week12-frames.ts examples for the matching frameStem.
 */
export const week12SpeakDays: SpeakDay[] = [
  {
    day: 169,
    themeEs: "El plan",
    themeEn: "The plan",
    missionEs: "Presenta tu plan de práctica con estructura de monólogo.",
    missionEn: "Present your practice plan with monologue structure.",
    line: "Un minuto empieza con «Hoy quiero hablar de…»",
    lineEn: "A minute starts with \"Today I want to talk about…\"",
    prompts: [
      {
        id: "d169-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about my plan to practice Spanish.",
        spanish: "Hoy quiero hablar de mi plan para practicar español.",
        situationLabel: "Abrir el monólogo",
        why: "*Hoy quiero hablar de* is the monologue opener — name your topic before the three things.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "want to talk", es: "quiero hablar" },
          { en: "plan", es: "plan" },
          { en: "practice", es: "practicar" },
        ],
      },
      {
        id: "d169-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things I want to do: read, listen, and speak.",
        spanish: "Hay tres cosas que quiero hacer: leer, escuchar y hablar.",
        situationLabel: "Las tres metas",
        why: "*Hay tres cosas que* sets up the scaffold — your listener knows three beats are coming.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "want to do", es: "quiero hacer" },
          { en: "read", es: "leer" },
          { en: "listen", es: "escuchar" },
          { en: "speak", es: "hablar" },
        ],
      },
      {
        id: "d169-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is deciding when I practice each day.",
        spanish: "Lo primero es decidir cuándo practico cada día.",
        situationLabel: "Paso uno",
        why: "*Lo primero es* — beat one. Simple, clear, no rushing.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "deciding", es: "decidir" },
          { en: "when", es: "cuándo" },
          { en: "each day", es: "cada día" },
        ],
      },
      {
        id: "d169-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is listening to a podcast in the car.",
        spanish: "Lo segundo es escuchar un podcast en el carro.",
        situationLabel: "Paso dos",
        why: "*Lo segundo es* — beat two. The scaffold keeps you going when you stumble.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "listen", es: "escuchar" },
          { en: "podcast", es: "podcast" },
          { en: "car", es: "carro" },
        ],
      },
      {
        id: "d169-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, I'll tell you Friday how it went.",
        spanish: "Para terminar, te cuento el viernes cómo me fue.",
        situationLabel: "Cerrar",
        why: "*Para terminar* closes the monologue — your listener knows you're wrapping up.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "tell you", es: "te cuento" },
          { en: "friday", es: "viernes" },
          { en: "how it went", es: "cómo me fue" },
        ],
      },
    ],
  },
  {
    day: 170,
    themeEs: "La lectura",
    themeEn: "Reading",
    missionEs: "Cuenta tu experiencia leyendo en voz alta con estructura.",
    missionEn: "Tell your out-loud reading experience with structure.",
    line: "Lo primero es empezar. Ya lo hiciste.",
    lineEn: "The first thing is starting. You already did.",
    prompts: [
      {
        id: "d170-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about reading out loud last night.",
        spanish: "Hoy quiero hablar de leer en voz alta anoche.",
        situationLabel: "El tema del día",
        why: "*Leer en voz alta anoche* — specific topic, one night — keeps the monologue focused.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "reading out loud", es: "leer en voz alta" },
          { en: "last night", es: "anoche" },
        ],
      },
      {
        id: "d170-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things I underlined in the article.",
        spanish: "Hay tres cosas que subrayé en el artículo.",
        situationLabel: "Tres detalles",
        why: "*Subrayé* — preterite — three concrete things from last night's reading.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "underlined", es: "subrayé" },
          { en: "article", es: "artículo" },
        ],
      },
      {
        id: "d170-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is starting — I already did.",
        spanish: "Lo primero es empezar — ya lo hice.",
        situationLabel: "Victoria pequeña",
        why: "*Ya lo hice* — I already did it — the win worth naming first.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "starting", es: "empezar" },
          { en: "already did", es: "ya lo hice" },
        ],
      },
      {
        id: "d170-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is not skipping reading tomorrow.",
        spanish: "Lo segundo es no saltarme la lectura mañana.",
        situationLabel: "La continuidad",
        why: "*No saltarme* — reflexive — the commitment to day two.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "not skip", es: "no saltarme" },
          { en: "reading", es: "lectura" },
          { en: "tomorrow", es: "mañana" },
        ],
      },
      {
        id: "d170-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, I'll say I felt better at the end.",
        spanish: "Para terminar, diré que me sentí mejor al final.",
        situationLabel: "Cómo terminó",
        why: "*Me sentí mejor al final* — the honest close after a nervous start.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "felt better", es: "me sentí mejor" },
          { en: "at the end", es: "al final" },
        ],
      },
    ],
  },
  {
    day: 171,
    themeEs: "Escuchar",
    themeEn: "Listening",
    missionEs: "Estructura tu experiencia con el podcast de hoy.",
    missionEn: "Structure your experience with today's podcast.",
    line: "Escuchar, repetir, no rendirse — tres cosas.",
    lineEn: "Listen, repeat, don't give up — three things.",
    prompts: [
      {
        id: "d171-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about listening in the car.",
        spanish: "Hoy quiero hablar de escuchar en el carro.",
        situationLabel: "El tema",
        why: "*Escuchar en el carro* — dead time turned into practice — a monologue topic with built-in detail.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "listening", es: "escuchar" },
          { en: "car", es: "carro" },
        ],
      },
      {
        id: "d171-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things that help: listen, repeat, and don't give up.",
        spanish: "Hay tres cosas que ayudan: escuchar, repetir y no rendirse.",
        situationLabel: "La fórmula",
        why: "*No rendirse* — infinitive in a list — the third pillar of listening practice.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "help", es: "ayudan" },
          { en: "repeat", es: "repetir" },
          { en: "don't give up", es: "no rendirse" },
        ],
      },
      {
        id: "d171-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is listening without translating.",
        spanish: "Lo primero es escuchar sin traducir.",
        situationLabel: "Sin traducir",
        why: "*Sin traducir* — the listening goal that sounds simple and isn't.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "listening", es: "escuchar" },
          { en: "without translating", es: "sin traducir" },
        ],
      },
      {
        id: "d171-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is repeating even if it sounds weird.",
        spanish: "Lo segundo es repetir aunque suene raro.",
        situationLabel: "Repetir",
        why: "*Aunque suene raro* — subjunctive — repeat anyway, even when it feels strange.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "repeat", es: "repetir" },
          { en: "even if", es: "aunque" },
          { en: "sounds weird", es: "suene raro" },
        ],
      },
      {
        id: "d171-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, come back tomorrow even if I don't understand everything.",
        spanish: "Para terminar, volver mañana aunque no entienda todo.",
        situationLabel: "Volver mañana",
        why: "*Volver mañana aunque no entienda todo* — the close that commits you to day four.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "come back", es: "volver" },
          { en: "tomorrow", es: "mañana" },
          { en: "don't understand everything", es: "no entienda todo" },
        ],
      },
    ],
  },
  {
    day: 172,
    themeEs: "Hablar sola",
    themeEn: "Talking alone",
    missionEs: "Cuenta tu práctica frente al espejo con estructura.",
    missionEn: "Tell about your mirror practice with structure.",
    line: "Tropiezas a los veinte segundos. Sigues.",
    lineEn: "You stumble at twenty seconds. You keep going.",
    prompts: [
      {
        id: "d172-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about practicing in front of the mirror.",
        spanish: "Hoy quiero hablar de practicar frente al espejo.",
        situationLabel: "El espejo",
        why: "*Practicar frente al espejo* — the embarrassing topic worth naming out loud anyway.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "practicing", es: "practicar" },
          { en: "mirror", es: "espejo" },
        ],
      },
      {
        id: "d172-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things that helped me last night.",
        spanish: "Hay tres cosas que me ayudaron anoche.",
        situationLabel: "Tres ayudas",
        why: "*Me ayudaron anoche* — preterite — three things from a specific session.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "helped me", es: "me ayudaron" },
          { en: "last night", es: "anoche" },
        ],
      },
      {
        id: "d172-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is not stopping when I stumble.",
        spanish: "Lo primero es no parar cuando tropiezo.",
        situationLabel: "No parar",
        why: "*Cuando tropiezo* — present — the rule you practice every time.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "not stopping", es: "no parar" },
          { en: "stumble", es: "tropiezo" },
        ],
      },
      {
        id: "d172-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is telling Diego's story.",
        spanish: "Lo segundo es contar la historia de Diego.",
        situationLabel: "Contenido conocido",
        why: "*Contar la historia de Diego* — known content — what you talk about when the timer is running.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "tell", es: "contar" },
          { en: "story", es: "historia" },
          { en: "diego", es: "diego" },
        ],
      },
      {
        id: "d172-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, I'll try again tonight.",
        spanish: "Para terminar, lo intento otra vez esta noche.",
        situationLabel: "Otra vez",
        why: "*Lo intento otra vez* — the close that schedules the next attempt.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "try again", es: "lo intento otra vez" },
          { en: "tonight", es: "esta noche" },
        ],
      },
    ],
  },
  {
    day: 173,
    themeEs: "Escribir",
    themeEn: "Writing",
    missionEs: "Resume tu semana en tres cosas con estructura de monólogo.",
    missionEn: "Summarize your week in three things with monologue structure.",
    line: "Viernes: tres cosas, una frase que te quedas.",
    lineEn: "Friday: three things, one sentence you keep.",
    prompts: [
      {
        id: "d173-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about my practice week.",
        spanish: "Hoy quiero hablar de mi semana de práctica.",
        situationLabel: "El repaso semanal",
        why: "*Mi semana de práctica* — Friday's topic is the whole week in one frame.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "practice week", es: "semana de práctica" },
        ],
      },
      {
        id: "d173-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things I want to tell you about this week.",
        spanish: "Hay tres cosas que quiero contarte de esta semana.",
        situationLabel: "Tres logros",
        why: "*Quiero contarte de esta semana* — direct address to Priya — monologue as report.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "tell you", es: "contarte" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d173-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is that I read out loud three nights in a row.",
        spanish: "Lo primero es que leí en voz alta tres noches seguidas.",
        situationLabel: "Lectura",
        why: "*Tres noches seguidas* — three nights in a row — the first win worth naming.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "read out loud", es: "leí en voz alta" },
          { en: "three nights", es: "tres noches seguidas" },
        ],
      },
      {
        id: "d173-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is that I spoke forty-five seconds without stopping.",
        spanish: "Lo segundo es que hablé cuarenta y cinco segundos sin parar.",
        situationLabel: "Cuarenta y cinco segundos",
        why: "*Cuarenta y cinco segundos sin parar* — measured progress — beat two with a number.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "spoke", es: "hablé" },
          { en: "forty-five seconds", es: "cuarenta y cinco segundos" },
          { en: "without stopping", es: "sin parar" },
        ],
      },
      {
        id: "d173-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, I'm keeping this sentence from my notebook.",
        spanish: "Para terminar, me quedo con esta frase del cuaderno.",
        situationLabel: "La frase",
        why: "*Me quedo con esta frase* — the sentence you keep — a close with something concrete.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "keeping", es: "me quedo" },
          { en: "sentence", es: "frase" },
          { en: "notebook", es: "cuaderno" },
        ],
      },
    ],
  },
  {
    day: 174,
    themeEs: "El balance",
    themeEn: "The balance",
    missionEs: "Haz el balance de la semana con estructura de monólogo.",
    missionEn: "Assess the week with monologue structure.",
    line: "Lo que funcionó. Lo que faltó. Para terminar, sigues.",
    lineEn: "What worked. What was missing. To finish, you continue.",
    prompts: [
      {
        id: "d174-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about the balance of my week.",
        spanish: "Hoy quiero hablar del balance de mi semana.",
        situationLabel: "El balance",
        why: "*Del balance de mi semana* — Saturday's honest assessment as monologue topic.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "balance", es: "balance" },
          { en: "week", es: "semana" },
        ],
      },
      {
        id: "d174-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things that worked this week.",
        spanish: "Hay tres cosas que funcionaron esta semana.",
        situationLabel: "Lo que funcionó",
        why: "*Funcionaron esta semana* — preterite — name what worked before what didn't.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "worked", es: "funcionaron" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d174-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is reading before bed — I did that almost every day.",
        spanish: "Lo primero es leer antes de dormir — eso sí lo cumplí.",
        situationLabel: "Lo que cumplí",
        why: "*Eso sí lo cumplí* — I did accomplish that — honest credit where it's due.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "reading before bed", es: "leer antes de dormir" },
          { en: "accomplished", es: "lo cumplí" },
        ],
      },
      {
        id: "d174-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is talking alone — embarrassing, but it works.",
        spanish: "Lo segundo es hablar sola — da vergüenza, pero funciona.",
        situationLabel: "Vergüenza y progreso",
        why: "*Da vergüenza, pero funciona* — the honest middle beat — embarrassment plus results.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "talking alone", es: "hablar sola" },
          { en: "embarrassing", es: "vergüenza" },
          { en: "works", es: "funciona" },
        ],
      },
      {
        id: "d174-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, I'll say what was missing: the full minute.",
        spanish: "Para terminar, diré lo que faltó: el minuto completo.",
        situationLabel: "Lo que falta",
        why: "*Lo que faltó: el minuto completo* — name the gap honestly, then keep going next week.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "what was missing", es: "lo que faltó" },
          { en: "full minute", es: "minuto completo" },
        ],
      },
    ],
  },
  {
    day: 175,
    themeEs: "Repaso: el minuto entero",
    themeEn: "Review: the full minute",
    missionEs: "Entrega el monólogo completo de tu semana de práctica.",
    missionEn: "Deliver the full monologue of your practice week.",
    line: "Un minuto. Cinco stems. Tu semana entera.",
    lineEn: "One minute. Five stems. Your whole week.",
    prompts: [
      {
        id: "d175-hoy-quiero",
        frameStem: "Hoy quiero hablar de…",
        english: "Today I want to talk about my practice week — the whole review.",
        spanish: "Hoy quiero hablar de mi semana de práctica — el repaso entero.",
        situationLabel: "Abrir el repaso",
        why: "Repaso: open with the full week's topic in one phrase.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "practice week", es: "semana de práctica" },
          { en: "whole review", es: "repaso entero" },
        ],
      },
      {
        id: "d175-tres-cosas",
        frameStem: "Hay tres cosas que…",
        english: "There are three things I learned: read, listen, and speak.",
        spanish: "Hay tres cosas que aprendí: leer, escuchar y hablar.",
        situationLabel: "Tres aprendizajes",
        why: "*Aprendí* — preterite — three pillars of the week in one line.",
        wordHints: [
          { en: "three things", es: "tres cosas" },
          { en: "learned", es: "aprendí" },
          { en: "read", es: "leer" },
          { en: "listen", es: "escuchar" },
          { en: "speak", es: "hablar" },
        ],
      },
      {
        id: "d175-lo-primero",
        frameStem: "Lo primero es…",
        english: "The first thing is that reading before bed works.",
        spanish: "Lo primero es que la lectura antes de dormir funciona.",
        situationLabel: "Lo que funciona",
        why: "*Funciona* — present — a habit that works keeps working.",
        wordHints: [
          { en: "first thing", es: "lo primero" },
          { en: "reading before bed", es: "lectura antes de dormir" },
          { en: "works", es: "funciona" },
        ],
      },
      {
        id: "d175-lo-segundo",
        frameStem: "Lo segundo es…",
        english: "The second thing is that the mirror doesn't bite.",
        spanish: "Lo segundo es que el espejo no muerde.",
        situationLabel: "El espejo",
        why: "*El espejo no muerde* — the week's best line — humor closes the embarrassment.",
        wordHints: [
          { en: "second thing", es: "lo segundo" },
          { en: "mirror", es: "espejo" },
          { en: "doesn't bite", es: "no muerde" },
        ],
      },
      {
        id: "d175-para-terminar",
        frameStem: "Para terminar…",
        english: "To finish, I got to forty-five seconds — and I'll keep going.",
        spanish: "Para terminar, llegué a cuarenta y cinco segundos — y sigo.",
        situationLabel: "Seguir",
        why: "Repaso day: close with the number and the commitment — *y sigo*.",
        wordHints: [
          { en: "to finish", es: "para terminar" },
          { en: "got to", es: "llegué" },
          { en: "forty-five seconds", es: "cuarenta y cinco segundos" },
          { en: "keep going", es: "sigo" },
        ],
      },
    ],
  },
];
