import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 11 draft — "El regreso de Diego" (days 162–168).
 *
 * Append to content/readings/otono.ts. themeEs must match week11-prompts.ts.
 * Six installments (162–167) + fresh recap on 168 (isRecap: true).
 */
export const week11ReadingDays: ReadingDay[] = [
  {
    day: 162,
    themeEs: "El regreso",
    storyTitle: "El regreso de Diego",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "regresar", en: "to return", example: "Diego regresó ayer del extranjero." },
      { es: "el extranjero", en: "abroad", example: "Estuvo seis meses en el extranjero." },
      { es: "extrañar", en: "to miss", example: "Extrañábamos su sentido del humor." },
      { es: "la sala de maestros", en: "the teachers' lounge", example: "Apareció en la sala de maestros." },
      { es: "abrazar", en: "to hug", example: "Todos lo abrazaron al verlo." },
    ],
    dialogue: {
      title: "Diego está de vuelta",
      situation: "En la sala de maestros, a primera hora del lunes",
      lines: [
        { speaker: "A", es: "Priya, ¿viste? Diego regresó ayer.", en: "Priya, did you see? Diego returned yesterday." },
        { speaker: "B", es: "¡No puede ser! ¿Ya está en el colegio?", en: "No way! Is he already at school?" },
        { speaker: "A", es: "Sí, apareció en la sala de maestros con una mochila llena de recuerdos.", en: "Yes, he showed up in the teachers' lounge with a backpack full of souvenirs." },
        { speaker: "B", es: "La última vez que lo vimos, todavía no sabía si iba a quedarse allá.", en: "The last time we saw him, he still didn't know if he was going to stay over there." },
        { speaker: "A", es: "Exacto. Estuvo seis meses en Chile y al final decidió volver.", en: "Exactly. He was six months in Chile and in the end decided to come back." },
        { speaker: "B", es: "¿Cómo se ve?", en: "How does he look?" },
        { speaker: "A", es: "Más delgado, con barba, y con una sonrisa enorme. Todos lo abrazaron.", en: "Thinner, with a beard, and a huge smile. Everyone hugged him." },
        { speaker: "B", es: "Menos mal. Extrañábamos a Diego.", en: "Thank goodness. We missed Diego." },
      ],
    },
  },
  {
    day: 163,
    themeEs: "Lo que extrañábamos",
    storyTitle: "El regreso de Diego",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el turno de café", en: "coffee duty", example: "Diego siempre hacía el turno de café." },
      { es: "animar", en: "to liven up", example: "Animaba las reuniones de lunes." },
      { es: "contar chistes", en: "to tell jokes", example: "Contaba chistes malos pero graciosos." },
      { es: "el ambiente", en: "the atmosphere", example: "El ambiente cambió sin él." },
      { es: "notar", en: "to notice", example: "Todos notamos su ausencia." },
    ],
    dialogue: {
      title: "Sin Diego",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "B", es: "¿Qué extrañabas más de Diego?", en: "What did you miss most about Diego?" },
        { speaker: "A", es: "Su turno de café, para empezar. Siempre traía galletas los viernes.", en: "His coffee duty, for starters. He always brought cookies on Fridays." },
        { speaker: "B", es: "Cierto. Mientras tanto, las reuniones de lunes eran un poco más aburridas.", en: "True. Meanwhile, Monday meetings were a little more boring." },
        { speaker: "A", es: "Él animaba todo. Contaba chistes malos justo cuando más lo necesitábamos.", en: "He livened everything up. He told bad jokes exactly when we needed them most." },
        { speaker: "B", es: "¿Notaste que el ambiente cambió?", en: "Did you notice the atmosphere changed?" },
        { speaker: "A", es: "Claro. Todos lo notamos. Desde entonces, el señor Ortiz hace el café — y no es lo mismo.", en: "Of course. We all noticed. Since then, Mr. Ortiz makes the coffee — and it's not the same." },
        { speaker: "B", es: "Al menos ya volvió.", en: "At least he's back now." },
        { speaker: "A", es: "Sí. Ayer se ofreció para retomar el turno esta semana.", en: "Yes. Yesterday he offered to take back the shift this week." },
      ],
    },
  },
  {
    day: 164,
    themeEs: "La primera clase",
    storyTitle: "El regreso de Diego",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "retomar", en: "to resume, pick back up", example: "Retomó sus clases de ciencias." },
      { es: "ponerse al día", en: "to catch up", example: "Todavía se está poniendo al día." },
      { es: "el plan de estudios", en: "the curriculum", example: "El plan de estudios cambió un poco." },
      { es: "adaptarse", en: "to adapt", example: "Se adapta rápido." },
      { es: "bromear", en: "to joke", example: "Bromeó con los estudiantes al entrar." },
    ],
    dialogue: {
      title: "De vuelta al salón",
      situation: "En la sala de maestros, después de la primera campana",
      lines: [
        { speaker: "A", es: "Diego ya retomó sus clases de ciencias.", en: "Diego already resumed his science classes." },
        { speaker: "B", es: "¿Cómo le fue la primera?", en: "How did his first one go?" },
        { speaker: "A", es: "Al día siguiente de llegar, ya estaba frente a sus estudiantes.", en: "The day after arriving, he was already in front of his students." },
        { speaker: "B", es: "¿Y cómo reaccionaron?", en: "And how did they react?" },
        { speaker: "A", es: "Lo recibieron con aplausos. Bromeó al entrar y se adaptó en minutos.", en: "They received him with applause. He joked as he walked in and adapted in minutes." },
        { speaker: "B", es: "¿Y el plan de estudios?", en: "And the curriculum?" },
        { speaker: "A", es: "Mientras tanto, el señor Ortiz le dejó notas de lo que cambió. Todavía se está poniendo al día.", en: "Meanwhile, Mr. Ortiz left him notes on what changed. He's still catching up." },
        { speaker: "B", es: "Normal. Seis meses fuera es mucho.", en: "Normal. Six months away is a lot." },
      ],
    },
  },
  {
    day: 165,
    themeEs: "Historias de Chile",
    storyTitle: "El regreso de Diego",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "contar anécdotas", en: "to tell anecdotes", example: "Contó anécdotas del mercado." },
      { es: "el mercado", en: "the market", example: "Compraba fruta en el mercado central." },
      { es: "el acento", en: "the accent", example: "Imita el acento chileno." },
      { es: "probar", en: "to try", example: "Probó comida que nunca había comido." },
      { es: "asombrado/a", en: "amazed", example: "Estaba asombrado con el océano." },
    ],
    dialogue: {
      title: "Diego cuenta",
      situation: "En la sala de maestros, durante el almuerzo",
      lines: [
        { speaker: "B", es: "¿Ya te contó historias de Chile?", en: "Did he already tell you stories from Chile?" },
        { speaker: "A", es: "Toda la hora del almuerzo. La última vez que comimos juntos, no paró.", en: "All lunch hour. The last time we ate together, he didn't stop." },
        { speaker: "B", es: "Cuéntame una.", en: "Tell me one." },
        { speaker: "A", es: "Dice que compraba fruta en el mercado central y probaba cosas que nunca había comido.", en: "He says he bought fruit at the central market and tried things he'd never eaten." },
        { speaker: "B", es: "¿En serio?", en: "Really?" },
        { speaker: "A", es: "Sí. Ahora resulta que imita el acento chileno — mal, pero con entusiasmo.", en: "Yes. Now it turns out he imitates the Chilean accent — badly, but with enthusiasm." },
        { speaker: "B", es: "Eso suena a Diego.", en: "That sounds like Diego." },
        { speaker: "A", es: "También trajo fotos del océano. Estaba asombrado con las olas.", en: "He also brought photos of the ocean. He was amazed by the waves." },
      ],
    },
  },
  {
    day: 166,
    themeEs: "El cambio",
    storyTitle: "El regreso de Diego",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "madurar", en: "to mature", example: "Regresó más maduro." },
      { es: "la perspectiva", en: "perspective", example: "Trae otra perspectiva al equipo." },
      { es: "proponer", en: "to propose", example: "Propuso un intercambio escolar." },
      { es: "entusiasmado/a", en: "enthusiastic", example: "Está entusiasmado con la idea." },
      { es: "apoyar", en: "to support", example: "La directora lo apoya." },
    ],
    dialogue: {
      title: "Un Diego diferente",
      situation: "En la sala de maestros, al final del día",
      lines: [
        { speaker: "A", es: "¿Notaste que Diego regresó un poco diferente?", en: "Did you notice Diego came back a little different?" },
        { speaker: "B", es: "¿En qué sentido?", en: "In what sense?" },
        { speaker: "A", es: "Más calmado, pero con más ideas. Trae otra perspectiva al equipo.", en: "Calmer, but with more ideas. He brings a different perspective to the team." },
        { speaker: "B", es: "¿Como qué?", en: "Like what?" },
        { speaker: "A", es: "Propuso un intercambio escolar con el colegio donde enseñó en Santiago.", en: "He proposed a school exchange with the school where he taught in Santiago." },
        { speaker: "B", es: "¡Qué ambicioso!", en: "How ambitious!" },
        { speaker: "A", es: "Desde entonces, está entusiasmado. La directora dijo que lo apoya en principio.", en: "Since then, he's been enthusiastic. The principal said she supports it in principle." },
        { speaker: "B", es: "Mientras tanto, nosotras tenemos que escuchar más anécdotas del mercado.", en: "Meanwhile, we have to listen to more market anecdotes." },
      ],
    },
  },
  {
    day: 167,
    themeEs: "La bienvenida",
    storyTitle: "El regreso de Diego",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "organizar", en: "to organize", example: "Organizamos una cena de bienvenida." },
      { es: "la cena", en: "dinner", example: "La cena fue el viernes." },
      { es: "brindar", en: "to toast", example: "Brindamos por Diego." },
      { es: "el regalo", en: "the gift", example: "Le dimos un regalo grupal." },
      { es: "de vuelta en casa", en: "back home", example: "Bienvenido de vuelta a casa." },
    ],
    dialogue: {
      title: "Bienvenido de vuelta",
      situation: "En la sala de maestros, el lunes después de la cena",
      lines: [
        { speaker: "B", es: "¿Cómo estuvo la cena de bienvenida?", en: "How was the welcome dinner?" },
        { speaker: "A", es: "Preciosa. Organizamos todo el viernes y casi todo el colegio vino.", en: "Beautiful. We organized everything on Friday and almost the whole school came." },
        { speaker: "B", es: "¿Qué hicieron?", en: "What did you do?" },
        { speaker: "A", es: "Brindamos por Diego, le dimos un regalo grupal y comimos demasiado.", en: "We toasted to Diego, gave him a group gift, and ate too much." },
        { speaker: "B", es: "¿Qué dijo él?", en: "What did he say?" },
        { speaker: "A", es: "Dijo que se sintió de vuelta en casa. Al día siguiente, retomó su turno de café sin que nadie se lo pidiera.", en: "He said he felt back home. The next day, he resumed his coffee shift without anyone asking." },
        { speaker: "B", es: "Ahora resulta que el lunes por la mañana vuelve a oler a café bueno.", en: "Now it turns out Monday mornings smell like good coffee again." },
        { speaker: "A", es: "Exacto. Seis meses fuera, pero Diego es Diego.", en: "Exactly. Six months away, but Diego is Diego." },
      ],
    },
  },
  {
    day: 168,
    themeEs: "Repaso: seguir la historia",
    isRecap: true,
    vocab: [
      { es: "retomar el hilo", en: "to pick up the thread", example: "Retomemos el hilo de Diego." },
      { es: "en resumen", en: "in summary", example: "En resumen, volvió transformado." },
      { es: "el arco", en: "the arc", example: "El arco completo duró seis meses." },
      { es: "encajar", en: "to fit in", example: "Encajó de inmediato." },
      { es: "quedarse", en: "to stay", example: "Al final se quedó aquí." },
    ],
    dialogue: {
      title: "La historia de Diego en cinco tiempos",
      situation: "En la sala de maestros, repasando la semana",
      lines: [
        { speaker: "B", es: "Oye, retomemos el hilo de Diego. ¿Me lo cuentas todo?", en: "Hey, let's pick up Diego's thread. Can you tell me the whole thing?" },
        { speaker: "A", es: "Claro. La última vez que lo vimos, no sabía si se quedaría en Chile.", en: "Sure. The last time we saw him, he didn't know if he'd stay in Chile." },
        { speaker: "B", es: "¿Y mientras tanto?", en: "And meanwhile?" },
        { speaker: "A", es: "Mientras tanto, extrañábamos su café y sus chistes. Al día siguiente de volver, ya estaba en clase.", en: "Meanwhile, we missed his coffee and his jokes. The day after returning, he was already in class." },
        { speaker: "B", es: "¿Qué más pasó?", en: "What else happened?" },
        { speaker: "A", es: "Ahora resulta que propuso un intercambio escolar. Desde entonces, la directora lo apoya.", en: "Now it turns out he proposed a school exchange. Since then, the principal supports it." },
        { speaker: "B", es: "¿Y la cena?", en: "And the dinner?" },
        { speaker: "A", es: "El viernes brindamos por él. Seis meses fuera — pero encajó como si nunca se hubiera ido.", en: "On Friday we toasted to him. Six months away — but he fit in as if he'd never left." },
      ],
    },
  },
];
