import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 8 — "La presentación de Priya" (days 141–147).
 * Priya prepares and delivers a staff meeting presentation; Marlana helps.
 */
export const week8ReadingDays: ReadingDay[] = [
  {
    day: 141,
    themeEs: "La tarea",
    storyTitle: "La presentación de Priya",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "presentar", en: "to present", example: "Tengo que presentar el proyecto." },
      { es: "el personal", en: "the staff", example: "Es la reunión de todo el personal." },
      { es: "los datos", en: "the data", example: "La directora pidió datos concretos." },
      { es: "el trimestre", en: "the quarter/trimester", example: "Propongo un plan para el trimestre." },
      { es: "convencer", en: "to convince", example: "Tengo diez minutos para convencer." },
    ],
    dialogue: {
      title: "Diez minutos",
      situation: "En la sala de maestros, después de la reunión de departamento",
      lines: [
        { speaker: "B", es: "Marlana, la directora me pidió presentar el proyecto de lectura.", en: "Marlana, the principal asked me to present the reading project." },
        { speaker: "A", es: "¿En la reunión de personal?", en: "At the staff meeting?" },
        { speaker: "B", es: "Sí. Primero que nada, tengo que presentar el proyecto de lectura. En cuanto al tiempo, solo tengo diez minutos.", en: "Yes. First of all, I have to present the reading project. As for time, I only have ten minutes." },
        { speaker: "A", es: "¿Y qué más?", en: "And what else?" },
        { speaker: "B", es: "En cuanto al público, son maestros de todos los grados. Por último, quiero proponer un plan para el trimestre.", en: "As for the audience, it's teachers from every grade. Lastly, I want to propose a plan for the quarter." },
        { speaker: "A", es: "Suena serio.", en: "That sounds serious." },
        { speaker: "B", es: "En resumen, tengo que convencer al personal en diez minutos. Necesito practicar mucho esta semana.", en: "In summary, I have to convince the staff in ten minutes. I need to practice a lot this week." },
        { speaker: "A", es: "Te ayudo. Volviendo a lo de la reunión, ¿es el jueves?", en: "I'll help you. Getting back to the meeting, is it Thursday?" },
      ],
    },
  },
  {
    day: 142,
    themeEs: "La investigación",
    storyTitle: "La presentación de Priya",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "las calificaciones", en: "the grades/scores", example: "Revisé las calificaciones de lectura." },
      { es: "el piloto", en: "the pilot (program)", example: "El grupo piloto leyó más." },
      { es: "la tendencia", en: "the trend", example: "La tendencia es positiva." },
      { es: "la encuesta", en: "the survey", example: "Las encuestas muestran entusiasmo." },
      { es: "comparar", en: "to compare", example: "Comparé con el año pasado." },
    ],
    dialogue: {
      title: "Los números",
      situation: "En la sala de maestros, Priya muestra gráficos impresos",
      lines: [
        { speaker: "B", es: "Mira lo que encontré. Primero que nada, revisé las calificaciones de lectura del trimestre.", en: "Look what I found. First of all, I reviewed the quarter's reading scores." },
        { speaker: "A", es: "¿Y qué dicen?", en: "And what do they say?" },
        { speaker: "B", es: "En cuanto a segundo grado, subieron ocho puntos. En cuanto al método, combinamos lectura en voz alta y parejas.", en: "As for second grade, they went up eight points. As for the method, we combined read-aloud and partner reading." },
        { speaker: "A", es: "Impresionante.", en: "Impressive." },
        { speaker: "B", es: "Por último, el grupo piloto leyó el doble de páginas. Volviendo a lo de las calificaciones, la tendencia es positiva.", en: "Lastly, the pilot group read twice as many pages. Getting back to the scores, the trend is positive." },
        { speaker: "A", es: "¿Conclusión?", en: "Conclusion?" },
        { speaker: "B", es: "En resumen, el proyecto de lectura está funcionando. En resumen, tenemos datos sólidos para presentar.", en: "In summary, the reading project is working. In summary, we have solid data to present." },
        { speaker: "A", es: "La directora va a quedar contenta.", en: "The principal is going to be pleased." },
      ],
    },
  },
  {
    day: 143,
    themeEs: "Ensayar",
    storyTitle: "La presentación de Priya",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "ensayar", en: "to rehearse", example: "Ensayamos juntas dos veces." },
      { es: "enganchar", en: "to hook, grab attention", example: "Tu introducción engancha bien." },
      { es: "el tono", en: "the tone", example: "Suenas segura." },
      { es: "el cierre", en: "the closing", example: "Falta un cierre más fuerte." },
      { es: "la transición", en: "the transition", example: "Practica la transición al plan." },
    ],
    dialogue: {
      title: "Práctica en la sala",
      situation: "En la sala de maestros, después de clases, solas",
      lines: [
        { speaker: "A", es: "Ok, empieza. Soy la directora.", en: "Ok, start. I'm the principal." },
        { speaker: "B", es: "Primero que nada… buenos días a todos…", en: "First of all… good morning everyone…" },
        { speaker: "A", es: "Para. Primero que nada, tu introducción engancha bien. En cuanto al tono, suenas segura.", en: "Stop. First of all, your introduction hooks well. As for tone, you sound confident." },
        { speaker: "B", es: "¿Qué cambio?", en: "What should I change?" },
        { speaker: "A", es: "En cuanto al final, falta un cierre más fuerte. Por último, practica la transición al plan del trimestre.", en: "As for the ending, you need a stronger close. Lastly, practice the transition to the quarter plan." },
        { speaker: "B", es: "Volviendo a lo del medio, ¿está bien?", en: "Getting back to the middle, is it okay?" },
        { speaker: "A", es: "Volviendo a lo de los datos, repite el número clave. En resumen, vas muy bien, solo afina el final.", en: "Getting back to the data, repeat the key number. In summary, you're doing great, just polish the ending." },
        { speaker: "B", es: "Gracias. Otra vez mañana.", en: "Thanks. Again tomorrow." },
      ],
    },
  },
  {
    day: 144,
    themeEs: "La estructura",
    storyTitle: "La presentación de Priya",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la estructura", en: "the structure", example: "La estructura funciona bien." },
      { es: "el gráfico", en: "the chart/graph", example: "Muestro tres gráficos." },
      { es: "la propuesta", en: "the proposal", example: "Propongo expandir el programa." },
      { es: "la resistencia", en: "resistance", example: "Hubo resistencia al principio." },
      { es: "escalar", en: "to scale up", example: "Necesitamos escalarlo." },
    ],
    dialogue: {
      title: "Intro, cuerpo, cierre",
      situation: "En la sala de maestros, revisando las diapositivas",
      lines: [
        { speaker: "B", es: "Armé la estructura en tres partes.", en: "I built the structure in three parts." },
        { speaker: "A", es: "Cuéntame.", en: "Tell me." },
        { speaker: "B", es: "Primero que nada, presento el problema de lectura en primaria. En cuanto a los resultados, muestro tres gráficos.", en: "First of all, I present the reading problem in elementary. As for the results, I show three charts." },
        { speaker: "A", es: "¿Y el final?", en: "And the end?" },
        { speaker: "B", es: "Por último, propongo expandir el programa al segundo trimestre. Volviendo a lo del problema inicial, estos datos lo confirman.", en: "Lastly, I propose expanding the program to the second quarter. Getting back to the initial problem, this data confirms it." },
        { speaker: "A", es: "¿Resumen en una frase?", en: "Summary in one sentence?" },
        { speaker: "B", es: "En resumen, leemos más, comprendemos mejor y los maestros están a bordo.", en: "In summary, we read more, understand better, and the teachers are on board." },
        { speaker: "A", es: "Perfecto. Eso cierra fuerte.", en: "Perfect. That closes strong." },
      ],
    },
  },
  {
    day: 145,
    themeEs: "La noche anterior",
    storyTitle: "La presentación de Priya",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "los nervios", en: "nerves", example: "En cuanto a los nervios, es normal." },
      { es: "el proyector", en: "the projector", example: "Verifico que el proyector funcione." },
      { es: "cronometrar", en: "to time", example: "Cronometré diez minutos exactos." },
      { es: "las diapositivas", en: "the slides", example: "Revisé las diapositivas tres veces." },
      { es: "preparada", en: "prepared (f.)", example: "Estoy preparada aunque nerviosa." },
    ],
    dialogue: {
      title: "Víspera",
      situation: "Mensaje de texto entre Priya y Marlana, la noche antes",
      lines: [
        { speaker: "B", es: "No puedo dormir. Mañana es la presentación.", en: "I can't sleep. Tomorrow is the presentation." },
        { speaker: "A", es: "Primero que nada, respira. En cuanto a los nervios, es normal.", en: "First of all, breathe. As for nerves, it's normal." },
        { speaker: "B", es: "Revisé las diapositivas tres veces. Cronometré diez minutos exactos.", en: "I reviewed the slides three times. I timed exactly ten minutes." },
        { speaker: "A", es: "Volviendo a lo de la práctica, salió bien ayer. Volviendo a lo de los datos, son sólidos.", en: "Getting back to yesterday's practice, it went well. Getting back to the data, it's solid." },
        { speaker: "B", es: "¿Y si me bloqueo?", en: "What if I freeze?" },
        { speaker: "A", es: "Por último, recuerda que sabes de lo que hablas. En resumen, estás preparada aunque nerviosa.", en: "Lastly, remember you know what you're talking about. In summary, you're prepared even if nervous." },
        { speaker: "B", es: "Gracias. En resumen, lo peor que puede pasar es una pregunta difícil.", en: "Thanks. In summary, the worst that can happen is a hard question." },
        { speaker: "A", es: "Y la respondes. Buenas noches, Priya.", en: "And you answer it. Good night, Priya." },
      ],
    },
  },
  {
    day: 146,
    themeEs: "El gran día",
    storyTitle: "La presentación de Priya",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "aplaudir", en: "to applaud", example: "La directora aplaudió." },
      { es: "el comité", en: "the committee", example: "Cinco personas levantaron la mano." },
      { es: "voluntario/a", en: "volunteer", example: "Se ofrecieron para el comité." },
      { es: "el presupuesto", en: "the budget", example: "Hubo preguntas sobre el presupuesto." },
      { es: "expandir", en: "to expand", example: "Aprobó expandir el programa." },
    ],
    dialogue: {
      title: "Diez minutos que valieron",
      situation: "En la sala de maestros, después de la reunión de personal",
      lines: [
        { speaker: "A", es: "¡Priya! ¿Cómo te fue?", en: "Priya! How did it go?" },
        { speaker: "B", es: "Creo que bien. Primero que nada, empecé con una pregunta al público.", en: "I think it went well. First of all, I started with a question to the audience." },
        { speaker: "A", es: "¿Y el medio?", en: "And the middle?" },
        { speaker: "B", es: "En cuanto a las preguntas, hubo dos sobre el presupuesto. En cuanto al público, parecían interesados.", en: "As for questions, there were two about the budget. As for the audience, they seemed interested." },
        { speaker: "A", es: "¿El cierre?", en: "The close?" },
        { speaker: "B", es: "Por último, la directora aplaudió y pidió el plan por escrito. Volviendo a lo del presupuesto, expliqué que el piloto costó poco.", en: "Lastly, the principal applauded and asked for the plan in writing. Getting back to the budget, I explained the pilot cost little." },
        { speaker: "A", es: "¿Resultado?", en: "Result?" },
        { speaker: "B", es: "En resumen, salió mejor de lo que esperaba. Por último, cinco colegas se ofrecieron para el comité.", en: "In summary, it went better than I expected. Lastly, five colleagues volunteered for the committee." },
        { speaker: "A", es: "Te lo dije. Diez minutos que valieron la pena.", en: "I told you. Ten minutes that were worth it." },
      ],
    },
  },
  {
    day: 147,
    themeEs: "Repaso: ordenar las ideas",
    isRecap: true,
    vocab: [
      { es: "organizar", en: "to organize", example: "Organizar las ideas salvó la presentación." },
      { es: "la evidencia", en: "the evidence", example: "Tenemos evidencia y un plan." },
      { es: "afinar", en: "to fine-tune", example: "Solo hay que afinar el final." },
      { es: "el esqueleto", en: "the skeleton (structure)", example: "El esqueleto del discurso funcionó." },
      { es: "contar de nuevo", en: "to tell again", example: "Cuéntame todo de nuevo." },
    ],
    dialogue: {
      title: "La semana de Priya",
      situation: "En la sala de maestros, una colega pide el resumen",
      lines: [
        { speaker: "A", es: "Oye, ¿qué pasó con la presentación de Priya? Me lo perdí.", en: "Hey, what happened with Priya's presentation? I missed it." },
        { speaker: "B", es: "Fue increíble. ¿Quieres el resumen?", en: "It was incredible. Do you want the summary?" },
        { speaker: "A", es: "Por favor.", en: "Please." },
        { speaker: "B", es: "Primero que nada, la directora le pidió presentar el proyecto de lectura. En cuanto a los datos, mostró una mejora clara en primaria.", en: "First of all, the principal asked her to present the reading project. As for the data, she showed clear improvement in elementary." },
        { speaker: "A", es: "¿Practicó?", en: "Did she practice?" },
        { speaker: "B", es: "En cuanto a la práctica, ensayamos juntas dos veces. Volviendo a lo de los nervios, desaparecieron al empezar.", en: "As for practice, we rehearsed together twice. Getting back to the nerves, they disappeared when she started." },
        { speaker: "A", es: "¿Y el resultado?", en: "And the result?" },
        { speaker: "B", es: "Por último, la directora aprobó expandir el programa. En resumen, Priya presentó, convenció y ya tienen plan para el trimestre.", en: "Lastly, the principal approved expanding the program. In summary, Priya presented, convinced, and they already have a plan for the quarter." },
      ],
    },
  },
];
