import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 9 — "Las noticias del barrio" (days 148–154).
 * Marlana shares neighborhood news and gossip with Priya in the teachers lounge.
 */
export const week9ReadingDays: ReadingDay[] = [
  {
    day: 148,
    themeEs: "El café nuevo",
    storyTitle: "Las noticias del barrio",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "inaugurar", en: "to inaugurate, open", example: "La inauguración es el sábado." },
      { es: "la esquina", en: "the corner", example: "Abren un café en la esquina." },
      { es: "la fachada", en: "the facade", example: "Pintaron la fachada de verde." },
      { es: "el barista", en: "the barista", example: "Buscan baristas del barrio." },
      { es: "el espresso", en: "espresso", example: "Instalaron una máquina enorme." },
    ],
    dialogue: {
      title: "Café en la esquina",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "Priya, ¿te enteraste de que abren un café en la esquina?", en: "Priya, did you hear they're opening a café on the corner?" },
        { speaker: "B", es: "¿En el local vacío? Llevaba años cerrado.", en: "In the empty storefront? It had been closed for years." },
        { speaker: "A", es: "Vi que ya pusieron letrero en la ventana. Vi que pintaron toda la fachada de verde.", en: "I saw they already put a sign in the window. I saw they painted the whole facade green." },
        { speaker: "B", es: "¿Quién lo maneja?", en: "Who's running it?" },
        { speaker: "A", es: "Resulta que la dueña es de Colombia y trae café de allá. Me contaron que antes tenía un café en Jamaica Plain.", en: "It turns out the owner is from Colombia and brings coffee from there. They told me she used to have a café in Jamaica Plain." },
        { speaker: "B", es: "Interesante.", en: "Interesting." },
        { speaker: "A", es: "Al parecer, van a tener pasteles de guayaba. Al parecer, la inauguración es el sábado.", en: "Apparently, they're going to have guava pastries. Apparently, the opening is Saturday." },
        { speaker: "B", es: "Tenemos que ir.", en: "We have to go." },
      ],
    },
  },
  {
    day: 149,
    themeEs: "El edificio",
    storyTitle: "Las noticias del barrio",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "vender", en: "to sell", example: "Van a vender el edificio." },
      { es: "el inquilino", en: "the tenant", example: "Los inquilinos están preocupados." },
      { es: "el casero", en: "the landlord", example: "El casero quiere jubilarse." },
      { es: "el condominio", en: "condo", example: "Quieren convertir pisos en condominios." },
      { es: "el lobby", en: "the lobby", example: "Hay un aviso de venta en el lobby." },
    ],
    dialogue: {
      title: "Van a vender",
      situation: "En la sala de maestros, entre clases",
      lines: [
        { speaker: "A", es: "¿Te enteraste de que van a vender mi edificio?", en: "Did you hear they're going to sell my building?" },
        { speaker: "B", es: "¿Qué? ¿Cuándo?", en: "What? When?" },
        { speaker: "A", es: "Vi que pusieron un aviso de venta en el lobby. Vi que vino un inspector ayer por la tarde.", en: "I saw they put a for-sale notice in the lobby. I saw an inspector came yesterday afternoon." },
        { speaker: "B", es: "¿Y tú?", en: "And you?" },
        { speaker: "A", es: "Resulta que llevan meses negociando en secreto. Resulta que el comprador quiere convertir dos pisos en condominios.", en: "It turns out they've been negotiating in secret for months. It turns out the buyer wants to convert two floors into condos." },
        { speaker: "B", es: "Eso suena preocupante.", en: "That sounds worrying." },
        { speaker: "A", es: "Al parecer, algunos inquilinos van a pelear legalmente. Me contaron que convocaron a un abogado de inquilinos.", en: "Apparently, some tenants are going to fight it legally. They told me they called a tenants' lawyer." },
        { speaker: "B", es: "Cuéntame más cuando sepas.", en: "Tell me more when you know." },
      ],
    },
  },
  {
    day: 150,
    themeEs: "La boda",
    storyTitle: "Las noticias del barrio",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la boda", en: "the wedding", example: "La boda es en el jardín botánico." },
      { es: "la novia", en: "the bride", example: "La novia probó un vestido." },
      { es: "el patio", en: "the courtyard", example: "Quieren fiesta en el patio." },
      { es: "el buzón", en: "the mailbox", example: "Me llegó una invitación al buzón." },
      { es: "contratar", en: "to hire", example: "Van a contratar al restaurante del barrio." },
    ],
    dialogue: {
      title: "Los del tercero",
      situation: "En la sala de maestros, un miércoles por la tarde",
      lines: [
        { speaker: "A", es: "¿Te enteraste de la boda de los del tercero piso?", en: "Did you hear about the third-floor couple's wedding?" },
        { speaker: "B", es: "¿Se casan? No sabía.", en: "They're getting married? I didn't know." },
        { speaker: "A", es: "Vi que me llegó una invitación al buzón. Resulta que la ceremonia es en el jardín botánico.", en: "I saw I got an invitation in my mailbox. It turns out the ceremony is at the botanical garden." },
        { speaker: "B", es: "Qué bonito.", en: "How lovely." },
        { speaker: "A", es: "Resulta que llevan juntos ocho años. Al parecer, invitaron a todo el edificio.", en: "It turns out they've been together eight years. Apparently, they invited the whole building." },
        { speaker: "B", es: "¿Y la fiesta?", en: "And the party?" },
        { speaker: "A", es: "Me contaron que pidieron permiso para usar el patio. Al parecer, van a contratar al restaurante del barrio.", en: "They told me they asked permission to use the courtyard. Apparently, they're going to hire the neighborhood restaurant." },
        { speaker: "B", es: "Tenemos que ir. ¿Nos invitaron a las dos?", en: "We have to go. Did they invite both of us?" },
        { speaker: "A", es: "Sí. ¿Te enteraste de que nos invitaron?", en: "Yes. Did you hear they invited us?" },
      ],
    },
  },
  {
    day: 151,
    themeEs: "La construcción",
    storyTitle: "Las noticias del barrio",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la construcción", en: "construction", example: "Empieza la construcción el lunes." },
      { es: "el cono", en: "the cone", example: "Dejaron conos naranjas anoche." },
      { es: "el desvío", en: "the detour", example: "El desvío pasa por la calle paralela." },
      { es: "la tubería", en: "the pipe", example: "Van a cambiar las tuberías de agua." },
      { es: "multar", en: "to fine", example: "Pueden multar si estacionas ahí." },
    ],
    dialogue: {
      title: "Conos naranjas",
      situation: "En la sala de maestros, antes de salir",
      lines: [
        { speaker: "A", es: "¿Te enteraste de la construcción en nuestra calle?", en: "Did you hear about the construction on our street?" },
        { speaker: "B", es: "¿Otra vez? ¿Cuánto tiempo?", en: "Again? How long?" },
        { speaker: "A", es: "Vi que dejaron conos naranjas desde anoche. Vi que pegaron un aviso de la ciudad en el poste.", en: "I saw they left orange cones since last night. I saw they posted a city notice on the pole." },
        { speaker: "B", es: "¿Qué van a hacer?", en: "What are they going to do?" },
        { speaker: "A", es: "Resulta que van a cambiar las tuberías de agua. Resulta que el proyecto dura seis semanas.", en: "It turns out they're going to replace the water pipes. It turns out the project lasts six weeks." },
        { speaker: "B", es: "Eso afecta tu ruta al colegio.", en: "That affects your route to school." },
        { speaker: "A", es: "Exacto. Al parecer, el desvío pasa por la calle paralela. Me contaron que pueden multar si estacionas ahí.", en: "Exactly. Apparently, the detour goes through the parallel street. They told me they can fine you if you park there." },
        { speaker: "B", es: "Qué semana para tu barrio.", en: "What a week for your neighborhood." },
      ],
    },
  },
  {
    day: 152,
    themeEs: "Vecinos nuevos",
    storyTitle: "Las noticias del barrio",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "la mudanza", en: "the move", example: "Llegó un camión de mudanzas." },
      { es: "el camión", en: "the truck", example: "El camión estuvo todo el sábado." },
      { es: "saludar", en: "to greet", example: "La mamá saludó a todos." },
      { es: "ladrar", en: "to bark", example: "El perro ladra cuando se quedan solos." },
      { es: "recomendar", en: "to recommend", example: "Buscan recomendaciones de restaurantes." },
    ],
    dialogue: {
      title: "Familia nueva",
      situation: "En la sala de maestros, el lunes por la mañana",
      lines: [
        { speaker: "A", es: "¿Te enteraste de la familia nueva del primer piso?", en: "Did you hear about the new family on the first floor?" },
        { speaker: "B", es: "¿Ya se mudaron?", en: "Did they already move in?" },
        { speaker: "A", es: "Vi que llegó un camión de mudanzas el sábado. Vi que la mamá saludó a todos en el pasillo.", en: "I saw a moving truck arrived Saturday. I saw the mom greeted everyone in the hallway." },
        { speaker: "B", es: "¿De dónde son?", en: "Where are they from?" },
        { speaker: "A", es: "Resulta que vienen de Chicago y se mudan por trabajo. Resulta que el papá es ingeniero en una startup.", en: "It turns out they're from Chicago and moved for work. It turns out the dad is an engineer at a startup." },
        { speaker: "B", es: "¿Niños?", en: "Kids?" },
        { speaker: "A", es: "Dos pequeños. Al parecer, buscan recomendaciones de restaurantes. Me contaron que quieren conocer a los vecinos.", en: "Two little ones. Apparently, they're looking for restaurant recommendations. They told me they want to meet the neighbors." },
        { speaker: "B", es: "Hay que darles la bienvenida.", en: "We should welcome them." },
      ],
    },
  },
  {
    day: 153,
    themeEs: "La reunión",
    storyTitle: "Las noticias del barrio",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "el concejal", en: "the city councilor", example: "Invitaron al concejal." },
      { es: "la agenda", en: "the agenda", example: "La agenda incluye la venta del edificio." },
      { es: "convocar", en: "to convene, call together", example: "Convocaron a una reunión." },
      { es: "la biblioteca comunitaria", en: "community library", example: "Reservaron la sala de la biblioteca." },
      { es: "asistir", en: "to attend", example: "El concejal confirma asistencia." },
    ],
    dialogue: {
      title: "Reunión del jueves",
      situation: "En la sala de maestros, un martes",
      lines: [
        { speaker: "A", es: "¿Te enteraste de la reunión del barrio el jueves?", en: "Did you hear about the neighborhood meeting on Thursday?" },
        { speaker: "B", es: "No. ¿De qué se trata?", en: "No. What's it about?" },
        { speaker: "A", es: "Vi que pegaron un flyer en la panadería. Vi que la lista de temas incluye la venta del edificio.", en: "I saw they posted a flyer at the bakery. I saw the topic list includes the building sale." },
        { speaker: "B", es: "Claro, con todo lo que pasa.", en: "Of course, with everything going on." },
        { speaker: "A", es: "Resulta que la organiza la vecina del quinto piso. Resulta que invitaron al concejal.", en: "It turns out the fifth-floor neighbor is organizing it. It turns out they invited the city councilor." },
        { speaker: "B", es: "¿Vas a ir?", en: "Are you going?" },
        { speaker: "A", es: "Al parecer, el tema más caliente es la venta. Me contaron que deberíamos ir las dos.", en: "Apparently, the hottest topic is the sale. They told me we should both go." },
        { speaker: "B", es: "Me apunto. Quiero enterarme de todo.", en: "I'm in. I want to hear everything." },
      ],
    },
  },
  {
    day: 154,
    themeEs: "Repaso: te enteraste",
    isRecap: true,
    vocab: [
      { es: "el chisme", en: "gossip", example: "Una semana de chisme del barrio." },
      { es: "enterarse", en: "to find out", example: "¿Te enteraste de todo?" },
      { es: "novedad", en: "news, novelty", example: "Hay novedades por todos lados." },
      { es: "organizarse", en: "to organize oneself", example: "Los vecinos se están organizando." },
      { es: "contar de nuevo", en: "to tell again", example: "Cuéntame todo de nuevo." },
    ],
    dialogue: {
      title: "Una semana de noticias",
      situation: "En la sala de maestros, Priya pide el resumen completo",
      lines: [
        { speaker: "B", es: "Marlana, estuve ocupada toda la semana. ¿Me pierdo de algo del barrio?", en: "Marlana, I was busy all week. Am I missing anything from the neighborhood?" },
        { speaker: "A", es: "¿Te enteraste de todo lo que pasó en el barrio esta semana?", en: "Did you hear about everything that happened in the neighborhood this week?" },
        { speaker: "B", es: "Solo lo del café. Cuéntame el resto.", en: "Only the café thing. Tell me the rest." },
        { speaker: "A", es: "Vi que hay letreros, conos, flyers y mudanzas por todos lados. Resulta que la dueña del café conoce a la novia del tercero.", en: "I saw there are signs, cones, flyers, and moves everywhere. It turns out the café owner knows the third-floor bride." },
        { speaker: "B", es: "¿En serio?", en: "Really?" },
        { speaker: "A", es: "Al parecer, el barrio se está despertando. Me contaron que deberíamos ir juntas a la reunión del jueves.", en: "Apparently, the neighborhood is waking up. They told me we should go together to Thursday's meeting." },
        { speaker: "B", es: "¿Te enteraste del edificio, la boda y la construcción?", en: "Did you hear about the building, the wedding, and the construction?" },
        { speaker: "A", es: "Todo conectado. En resumen: café, venta, boda, tuberías, vecinos nuevos y reunión. Una semana entera de noticias.", en: "All connected. In summary: café, sale, wedding, pipes, new neighbors, and a meeting. A whole week of news." },
      ],
    },
  },
];
