import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 12 draft — "Mi semana de práctica" (days 169–175).
 *
 * Append to content/readings/otono.ts. themeEs must match week12-prompts.ts.
 * Six installments (169–174) + fresh recap on 175 (isRecap: true).
 */
export const week12ReadingDays: ReadingDay[] = [
  {
    day: 169,
    themeEs: "El plan",
    storyTitle: "Mi semana de práctica",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el plan", en: "the plan", example: "Hice un plan para la semana." },
      { es: "practicar", en: "to practice", example: "Quiero practicar todos los días." },
      { es: "anotar", en: "to write down, note", example: "Anoté tres metas en mi cuaderno." },
      { es: "la meta", en: "the goal", example: "Mi meta es hablar un minuto." },
      { es: "comprometerse", en: "to commit", example: "Me comprometí con Priya." },
    ],
    dialogue: {
      title: "Una semana estructurada",
      situation: "En la sala de maestros, el lunes por la mañana",
      lines: [
        { speaker: "A", es: "Priya, esta semana quiero ser más intencional con mi español.", en: "Priya, this week I want to be more intentional with my Spanish." },
        { speaker: "B", es: "¿Qué tienes en mente?", en: "What do you have in mind?" },
        { speaker: "A", es: "Hoy quiero hablar de mi plan. Anoté tres metas en mi cuaderno.", en: "Today I want to talk about my plan. I wrote down three goals in my notebook." },
        { speaker: "B", es: "Cuéntame.", en: "Tell me." },
        { speaker: "A", es: "Hay tres cosas que quiero hacer: leer, escuchar y hablar en voz alta cada día.", en: "There are three things I want to do: read, listen, and speak out loud every day." },
        { speaker: "B", es: "Suena bien. ¿Me cuentas el viernes cómo te fue?", en: "Sounds good. Will you tell me Friday how it went?" },
        { speaker: "A", es: "Sí. Me comprometí contigo — eso me ayuda.", en: "Yes. I committed to you — that helps me." },
        { speaker: "B", es: "Entonces empieza hoy. Lo primero es decidir cuándo.", en: "Then start today. The first thing is deciding when." },
      ],
    },
  },
  {
    day: 170,
    themeEs: "La lectura",
    storyTitle: "Mi semana de práctica",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "antes de dormir", en: "before bed", example: "Leo antes de dormir." },
      { es: "en voz alta", en: "out loud", example: "Leo en voz alta un párrafo." },
      { es: "el párrafo", en: "the paragraph", example: "Elijo un párrafo corto." },
      { es: "subrayar", en: "to underline", example: "Subrayo palabras nuevas." },
      { es: "fijarse en", en: "to notice, pay attention to", example: "Me fijo en las frases." },
    ],
    dialogue: {
      title: "Martes de lectura",
      situation: "En la sala de maestros, el martes a la hora del almuerzo",
      lines: [
        { speaker: "B", es: "¿Cómo va el plan?", en: "How's the plan going?" },
        { speaker: "A", es: "Anoche cumplí la primera meta. Leí un párrafo en voz alta antes de dormir.", en: "Last night I met the first goal. I read a paragraph out loud before bed." },
        { speaker: "B", es: "¿Cómo te sentiste?", en: "How did you feel?" },
        { speaker: "A", es: "Nerviosa al principio, pero mejor al final. Subrayé tres palabras nuevas.", en: "Nervous at first, but better at the end. I underlined three new words." },
        { speaker: "B", es: "Lo primero es empezar — ya lo hiciste.", en: "The first thing is starting — you already did." },
        { speaker: "A", es: "Lo segundo es no saltarme la lectura mañana.", en: "The second thing is not skipping reading tomorrow." },
        { speaker: "B", es: "¿Qué vas a leer?", en: "What are you going to read?" },
        { speaker: "A", es: "Otra parte del artículo de educación bilingüe. Me fijo en las frases que ya practiqué.", en: "Another part of the bilingual education article. I'm paying attention to the sentences I already practiced." },
      ],
    },
  },
  {
    day: 171,
    themeEs: "Escuchar",
    storyTitle: "Mi semana de práctica",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el podcast", en: "the podcast", example: "Escucho un podcast corto." },
      { es: "el episodio", en: "the episode", example: "El episodio dura quince minutos." },
      { es: "repetir", en: "to repeat", example: "Repito la frase que escucho." },
      { es: "captar", en: "to catch, grasp", example: "Capté más de lo que pensaba." },
      { es: "a velocidad normal", en: "at normal speed", example: "Lo escucho a velocidad normal." },
    ],
    dialogue: {
      title: "Miércoles de oído",
      situation: "En la sala de maestros, camino al estacionamiento",
      lines: [
        { speaker: "A", es: "Hoy quiero hablar de escuchar. Esta mañana puse un podcast en el carro.", en: "Today I want to talk about listening. This morning I put on a podcast in the car." },
        { speaker: "B", es: "¿Cuál?", en: "Which one?" },
        { speaker: "A", es: "Un episodio de quince minutos sobre maestras bilingües. Lo escuché a velocidad normal.", en: "A fifteen-minute episode about bilingual teachers. I listened at normal speed." },
        { speaker: "B", es: "¿Entendiste todo?", en: "Did you understand everything?" },
        { speaker: "A", es: "No todo, pero capté más de lo que pensaba. Repetí algunas frases en voz baja.", en: "Not everything, but I caught more than I thought. I repeated some phrases quietly." },
        { speaker: "B", es: "Hay tres cosas que ayudan: escuchar, repetir y no rendirse.", en: "There are three things that help: listen, repeat, and don't give up." },
        { speaker: "A", es: "Lo primero es escuchar sin traducir. Lo segundo es repetir aunque suene raro.", en: "The first thing is listening without translating. The second is repeating even if it sounds weird." },
        { speaker: "B", es: "¿Y lo tercero?", en: "And the third?" },
        { speaker: "A", es: "Para terminar, volver mañana — aunque no entienda todo.", en: "To finish, come back tomorrow — even if I don't understand everything." },
      ],
    },
  },
  {
    day: 172,
    themeEs: "Hablar sola",
    storyTitle: "Mi semana de práctica",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "hablar sola", en: "to talk to oneself", example: "Hablar sola me da vergüenza." },
      { es: "el espejo", en: "the mirror", example: "Practiqué frente al espejo." },
      { es: "el cronómetro", en: "the timer", example: "Puse un cronómetro de un minuto." },
      { es: "tropezar", en: "to stumble", example: "Tropecé con una palabra." },
      { es: "seguir adelante", en: "to keep going", example: "Seguí adelante sin parar." },
    ],
    dialogue: {
      title: "El minuto frente al espejo",
      situation: "En la sala de maestros, el jueves después de clases",
      lines: [
        { speaker: "B", es: "¿Llegó el día de hablar sola?", en: "Did the day of talking alone arrive?" },
        { speaker: "A", es: "Sí. Anoche puse un cronómetro de un minuto frente al espejo.", en: "Yes. Last night I set a one-minute timer in front of the mirror." },
        { speaker: "B", es: "¿Cómo fue?", en: "How was it?" },
        { speaker: "A", es: "Tropecé con una palabra a los veinte segundos, pero seguí adelante.", en: "I stumbled on a word at twenty seconds, but I kept going." },
        { speaker: "B", es: "Eso es lo importante.", en: "That's what matters." },
        { speaker: "A", es: "Hoy quiero hablar de eso. Lo primero es no parar cuando tropiezas.", en: "Today I want to talk about that. The first thing is not stopping when you stumble." },
        { speaker: "A", es: "Lo segundo es hablar de algo que ya conozco — conté la historia de Diego.", en: "The second thing is talking about something you already know — I told Diego's story." },
        { speaker: "B", es: "¿Llegaste al minuto?", en: "Did you make it to a minute?" },
        { speaker: "A", es: "Casi. Cuarenta y cinco segundos. Para terminar, lo intento otra vez esta noche.", en: "Almost. Forty-five seconds. To finish, I'll try again tonight." },
      ],
    },
  },
  {
    day: 173,
    themeEs: "Escribir",
    storyTitle: "Mi semana de práctica",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "escribir", en: "to write", example: "Escribo tres frases cada noche." },
      { es: "la frase", en: "the sentence", example: "Cada frase usa un stem nuevo." },
      { es: "repasar", en: "to review", example: "Repaso lo que practiqué." },
      { es: "el cuaderno", en: "the notebook", example: "Lo anoto en mi cuaderno." },
      { es: "quedarse con", en: "to take away, remember", example: "Me quedo con la mejor frase." },
    ],
    dialogue: {
      title: "Viernes de tres frases",
      situation: "En la sala de maestros, el viernes al final del día",
      lines: [
        { speaker: "A", es: "Es viernes. Hay tres cosas que quiero contarte de esta semana.", en: "It's Friday. There are three things I want to tell you about this week." },
        { speaker: "B", es: "Te escucho.", en: "I'm listening." },
        { speaker: "A", es: "Lo primero es que leí en voz alta tres noches seguidas.", en: "The first thing is that I read out loud three nights in a row." },
        { speaker: "A", es: "Lo segundo es que hablé cuarenta y cinco segundos sin parar.", en: "The second thing is that I spoke forty-five seconds without stopping." },
        { speaker: "B", es: "¿Y lo tercero?", en: "And the third?" },
        { speaker: "A", es: "Escribí tres frases en mi cuaderno usando los stems de otoño.", en: "I wrote three sentences in my notebook using the fall stems." },
        { speaker: "B", es: "¿Cuál te gustó más?", en: "Which did you like most?" },
        { speaker: "A", es: "Me quedo con esta: «Ahora resulta que puedo contar la historia de Diego».", en: "I'm keeping this one: \"Now it turns out I can tell Diego's story.\"" },
      ],
    },
  },
  {
    day: 174,
    themeEs: "El balance",
    storyTitle: "Mi semana de práctica",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "el balance", en: "the balance, assessment", example: "Hago un balance el sábado." },
      { es: "lo que funcionó", en: "what worked", example: "Lo que funcionó fue leer en voz alta." },
      { es: "lo que faltó", en: "what was missing", example: "Lo que faltó fue más paciencia." },
      { es: "ajustar", en: "to adjust", example: "Voy a ajustar el plan." },
      { es: "seguir", en: "to continue", example: "Voy a seguir la próxima semana." },
    ],
    dialogue: {
      title: "Sábado de balance",
      situation: "En la sala de maestros, el lunes siguiente — Marlana repasa el fin de semana",
      lines: [
        { speaker: "B", es: "¿Hiciste el balance de tu semana de práctica?", en: "Did you do the assessment of your practice week?" },
        { speaker: "A", es: "Sí, el sábado en la mañana. Hoy quiero hablar del resultado.", en: "Yes, Saturday morning. Today I want to talk about the result." },
        { speaker: "B", es: "¿Qué funcionó?", en: "What worked?" },
        { speaker: "A", es: "Lo primero es leer antes de dormir — eso sí lo cumplí casi todos los días.", en: "The first thing is reading before bed — I did that almost every day." },
        { speaker: "A", es: "Lo segundo es hablar sola. Me da vergüenza, pero funciona.", en: "The second thing is talking alone. It's embarrassing, but it works." },
        { speaker: "B", es: "¿Qué faltó?", en: "What was missing?" },
        { speaker: "A", es: "Para terminar, diré lo que faltó: el minuto completo. Llegué a cuarenta y cinco segundos.", en: "To finish, I'll say what was missing: the full minute. I got to forty-five seconds." },
        { speaker: "B", es: "Eso no es poco. ¿Vas a seguir?", en: "That's not nothing. Are you going to continue?" },
        { speaker: "A", es: "Sí. Voy a ajustar el plan y seguir la próxima semana.", en: "Yes. I'm going to adjust the plan and continue next week." },
      ],
    },
  },
  {
    day: 175,
    themeEs: "Repaso: el minuto entero",
    isRecap: true,
    vocab: [
      { es: "el monólogo", en: "the monologue", example: "Practico un monólogo de un minuto." },
      { es: "la estructura", en: "the structure", example: "La estructura me ayuda a no parar." },
      { es: "el hilo", en: "the thread", example: "Sigo el hilo con los stems." },
      { es: "sostener", en: "to sustain", example: "Sostengo la conversación un minuto." },
      { es: "el repaso", en: "the review", example: "Hago un repaso de la semana entera." },
    ],
    dialogue: {
      title: "Un minuto sobre mi semana",
      situation: "En la sala de maestros — Marlana practica el monólogo completo para Priya",
      lines: [
        { speaker: "A", es: "Hoy quiero hablar de mi semana de práctica — el repaso entero.", en: "Today I want to talk about my practice week — the whole review." },
        { speaker: "B", es: "Adelante. Un minuto.", en: "Go ahead. One minute." },
        { speaker: "A", es: "Hay tres cosas que aprendí: leer en voz alta, escuchar sin traducir y hablar aunque tropiece.", en: "There are three things I learned: read out loud, listen without translating, and speak even when I stumble." },
        { speaker: "A", es: "Lo primero es que la lectura antes de dormir funciona. Lo segundo es que el espejo no muerde.", en: "The first thing is that reading before bed works. The second is that the mirror doesn't bite." },
        { speaker: "B", es: "Sigue.", en: "Keep going." },
        { speaker: "A", es: "Para terminar, llegué a cuarenta y cinco segundos — y voy a seguir hasta el minuto entero.", en: "To finish, I got to forty-five seconds — and I'm going to keep going until the full minute." },
        { speaker: "B", es: "Eso fue un minuto. Y medio.", en: "That was a minute. And a half." },
        { speaker: "A", es: "Entonces ya casi lo logro.", en: "Then I'm almost there." },
      ],
    },
  },
];
