import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 7 — "Por eso" (days 134–140).
 * Story: "La avería del coche" — Marlana's car breaks down; cause and effect chain.
 * prompt.spanish must stay verbatim with week7-frames.ts examples for the matching frameStem.
 */
export const week7SpeakDays: SpeakDay[] = [
  {
    day: 134,
    themeEs: "Se paró el coche",
    themeEn: "The car died",
    missionEs: "Cuenta la avería en la carretera con conectores de causa y efecto.",
    missionEn: "Tell about the breakdown on the highway using cause-and-effect connectors.",
    line: "Una luz en el tablero ignorada se convierte en una mañana en el arcén.",
    lineEn: "A dashboard light you ignored becomes a morning on the shoulder.",
    prompts: [
      {
        id: "d134-por-eso",
        frameStem: "Por eso…",
        english: "That's why I had to call Priya from the shoulder.",
        spanish: "Por eso tuve que llamar a Priya desde el arcén.",
        situationLabel: "Pidiendo ayuda en la carretera",
        why: "*Por eso* names the consequence of what you just said — the natural next sentence after the motor dies.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "call", es: "llamar" },
          { en: "shoulder", es: "el arcén" },
        ],
      },
      {
        id: "d134-asi-que",
        frameStem: "Así que…",
        english: "So I got out and opened the hood.",
        spanish: "Así que me bajé y abrí el capó.",
        situationLabel: "El primer paso",
        why: "*Así que* links a decision to what came before — what you do when the car stops.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "got out", es: "me bajé" },
          { en: "hood", es: "el capó" },
        ],
      },
      {
        id: "d134-como",
        frameStem: "Como…",
        english: "Since the check-engine light had been on for days, I wasn't surprised.",
        spanish: "Como la luz del motor llevaba días encendida, no me sorprendió.",
        situationLabel: "La señal que ignoré",
        why: "*Como* + past sets up the cause you already knew was coming — the warning you didn't act on.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "check-engine light", es: "la luz del motor" },
          { en: "days", es: "días" },
          { en: "wasn't surprised", es: "no me sorprendió" },
        ],
      },
      {
        id: "d134-debido-a",
        frameStem: "Debido a…",
        english: "Due to the breakdown, I missed first period.",
        spanish: "Debido a la avería, perdí la primera clase.",
        situationLabel: "El efecto en el colegio",
        why: "*Debido a la avería* — formal cause + noun, perfect for naming what the breakdown cost you.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "breakdown", es: "la avería" },
          { en: "missed", es: "perdí" },
          { en: "first period", es: "la primera clase" },
        ],
      },
      {
        id: "d134-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to Priya, I wasn't alone on the highway.",
        spanish: "Gracias a Priya, no me quedé sola en la carretera.",
        situationLabel: "No estar sola",
        why: "*Gracias a Priya* turns a crisis into a story about who showed up — the positive flip of cause and effect.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "alone", es: "sola" },
          { en: "highway", es: "la carretera" },
        ],
      },
    ],
  },
  {
    day: 135,
    themeEs: "Llegué tarde",
    themeEn: "I was late",
    missionEs: "Conecta la avería con el caos en el salón usando causa y efecto.",
    missionEn: "Connect the breakdown to classroom fallout using cause and effect.",
    line: "Llegar tarde no es solo perder minutos — es perder el ritmo de la mañana.",
    lineEn: "Being late isn't just losing minutes — it's losing the morning's rhythm.",
    prompts: [
      {
        id: "d135-por-eso",
        frameStem: "Por eso…",
        english: "That's why my students were waiting in the hallway.",
        spanish: "Por eso mis estudiantes esperaban en el pasillo.",
        situationLabel: "Estudiantes esperando",
        why: "*Esperaban en el pasillo* — past progressive for the scene Marlana walked into.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "students", es: "estudiantes" },
          { en: "waiting", es: "esperaban" },
          { en: "hallway", es: "el pasillo" },
        ],
      },
      {
        id: "d135-asi-que",
        frameStem: "Así que…",
        english: "So I started class straight with the review.",
        spanish: "Así que empecé la clase directo con el repaso.",
        situationLabel: "Recuperar el tiempo",
        why: "*Directo con el repaso* — the practical move when you've lost the opening activity.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "started class", es: "empecé la clase" },
          { en: "review", es: "el repaso" },
        ],
      },
      {
        id: "d135-como",
        frameStem: "Como…",
        english: "Since I arrived twenty minutes late, I missed the meeting.",
        spanish: "Como llegué veinte minutos tarde, perdí la reunión.",
        situationLabel: "Perder la reunión",
        why: "*Como llegué veinte minutos tarde* — the cause in one clause, the consequence in the next.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "twenty minutes late", es: "veinte minutos tarde" },
          { en: "missed", es: "perdí" },
          { en: "meeting", es: "la reunión" },
        ],
      },
      {
        id: "d135-debido-a",
        frameStem: "Debido a…",
        english: "Due to my delay, I didn't sign the attendance list on time.",
        spanish: "Debido a mi retraso, no firmé la lista a tiempo.",
        situationLabel: "La lista sin firmar",
        why: "*Debido a mi retraso* — the small admin task that becomes a headache when you're late.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "delay", es: "retraso" },
          { en: "sign", es: "firmé" },
          { en: "attendance list", es: "la lista" },
        ],
      },
      {
        id: "d135-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to my students, we got back on track quickly.",
        spanish: "Gracias a mis estudiantes, retomamos la clase rápido.",
        situationLabel: "Clase que se recupera",
        why: "*Retomamos la clase rápido* — gratitude for the class that didn't fall apart.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "students", es: "estudiantes" },
          { en: "got back on track", es: "retomamos la clase" },
          { en: "quickly", es: "rápido" },
        ],
      },
    ],
  },
  {
    day: 136,
    themeEs: "El transporte",
    themeEn: "Getting around",
    missionEs: "Cuenta la semana sin coche con Uber, bus y nuevas rutinas.",
    missionEn: "Tell about the carless week with Uber, bus, and new routines.",
    line: "Sin coche, cada mañana es un plan nuevo.",
    lineEn: "Without a car, every morning is a new plan.",
    prompts: [
      {
        id: "d136-por-eso",
        frameStem: "Por eso…",
        english: "That's why I'm spending more on transportation this week.",
        spanish: "Por eso esta semana gasto más en transporte.",
        situationLabel: "El presupuesto de la semana",
        why: "*Gasto más en transporte* — present tense for the ongoing drain on your wallet.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "spending more", es: "gasto más" },
          { en: "transportation", es: "transporte" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d136-asi-que",
        frameStem: "Así que…",
        english: "So I downloaded the bus app again.",
        spanish: "Así que descargué la app del autobús otra vez.",
        situationLabel: "Volver al bus",
        why: "*Descargué la app otra vez* — the small tech step that means you're serious about Plan B.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "downloaded", es: "descargué" },
          { en: "bus app", es: "app del autobús" },
          { en: "again", es: "otra vez" },
        ],
      },
      {
        id: "d136-como",
        frameStem: "Como…",
        english: "Since I don't have a car, I depend on Uber and the bus.",
        spanish: "Como no tengo coche, dependo del Uber y del bus.",
        situationLabel: "Sin coche, sin opción",
        why: "*Dependo del Uber y del bus* — the new reality stated plainly.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "don't have a car", es: "no tengo coche" },
          { en: "depend on", es: "dependo" },
          { en: "bus", es: "bus" },
        ],
      },
      {
        id: "d136-debido-a",
        frameStem: "Debido a…",
        english: "Due to public transit, I arrive more tired.",
        spanish: "Debido al transporte público, llego más cansada.",
        situationLabel: "Llegar agotada",
        why: "*Llego más cansada* — the hidden cost of a longer commute.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "public transit", es: "transporte público" },
          { en: "more tired", es: "más cansada" },
        ],
      },
      {
        id: "d136-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to the district bus pass, I save a little.",
        spanish: "Gracias al pase de autobús del distrito, ahorro algo.",
        situationLabel: "Un pequeño alivio",
        why: "*Ahorro algo* — not a fortune, but enough to mention in the teachers' lounge.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "bus pass", es: "pase de autobús" },
          { en: "district", es: "distrito" },
          { en: "save", es: "ahorro" },
        ],
      },
    ],
  },
  {
    day: 137,
    themeEs: "El taller",
    themeEn: "The mechanic",
    missionEs: "Cuenta el diagnóstico del taller y lo que cuesta arreglarlo.",
    missionEn: "Tell about the mechanic's diagnosis and what the repair costs.",
    line: "El mecánico habla y tu presupuesto se encoge.",
    lineEn: "The mechanic talks and your budget shrinks.",
    prompts: [
      {
        id: "d137-por-eso",
        frameStem: "Por eso…",
        english: "That's why I'm eating rice with whatever's in the pantry this week.",
        spanish: "Por eso esta semana como arroz con lo que hay.",
        situationLabel: "Ajustar el presupuesto",
        why: "*Como arroz con lo que hay* — the real-life budget cut after a car repair.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "this week", es: "esta semana" },
          { en: "rice", es: "arroz" },
          { en: "whatever's there", es: "lo que hay" },
        ],
      },
      {
        id: "d137-asi-que",
        frameStem: "Así que…",
        english: "So I approved the alternator repair.",
        spanish: "Así que aprobé la reparación del alternador.",
        situationLabel: "Decisión tomada",
        why: "*Aprobé la reparación* — past tense for the moment you said yes to the bill.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "approved", es: "aprobé" },
          { en: "repair", es: "reparación" },
          { en: "alternator", es: "alternador" },
        ],
      },
      {
        id: "d137-como",
        frameStem: "Como…",
        english: "Since the car is ten years old, these things happen.",
        spanish: "Como el coche tiene diez años, estas cosas pasan.",
        situationLabel: "Coche viejo, problemas viejos",
        why: "*Estas cosas pasan* — the resigned acceptance every car owner knows.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "ten years old", es: "diez años" },
          { en: "these things happen", es: "estas cosas pasan" },
        ],
      },
      {
        id: "d137-debido-a",
        frameStem: "Debido a…",
        english: "Due to the alternator, the bill exceeds five hundred.",
        spanish: "Debido al alternador, la factura supera los quinientos.",
        situationLabel: "La factura",
        why: "*Supera los quinientos* — the number that makes you catch your breath.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "alternator", es: "alternador" },
          { en: "bill", es: "factura" },
          { en: "exceeds five hundred", es: "supera los quinientos" },
        ],
      },
      {
        id: "d137-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to my trusted mechanic, he didn't overcharge me.",
        spanish: "Gracias al mecánico de confianza, no me cobró de más.",
        situationLabel: "Un mecánico honesto",
        why: "*No me cobró de más* — the relief when you find someone you can trust.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "trusted mechanic", es: "mecánico de confianza" },
          { en: "didn't overcharge", es: "no me cobró de más" },
        ],
      },
    ],
  },
  {
    day: 138,
    themeEs: "Priya al rescate",
    themeEn: "Priya to the rescue",
    missionEs: "Cuenta la ayuda de Priya con rides y favores esta semana.",
    missionEn: "Tell about Priya's help with rides and favors this week.",
    line: "Una buena amiga convierte una semana imposible en una semana sobrevivida.",
    lineEn: "A good friend turns an impossible week into a survived week.",
    prompts: [
      {
        id: "d138-por-eso",
        frameStem: "Por eso…",
        english: "That's why I bought her coffee all week.",
        spanish: "Por eso le compré el café toda la semana.",
        situationLabel: "Devolver el favor",
        why: "*Le compré el café toda la semana* — the small reciprocation that says thank you.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "bought her coffee", es: "le compré el café" },
          { en: "all week", es: "toda la semana" },
        ],
      },
      {
        id: "d138-asi-que",
        frameStem: "Así que…",
        english: "So we agreed to share the ride on rainy days.",
        spanish: "Así que acordamos compartir el viaje los días de lluvia.",
        situationLabel: "Plan de carpool",
        why: "*Los días de lluvia* — when a ride share matters most.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "agreed", es: "acordamos" },
          { en: "share the ride", es: "compartir el viaje" },
          { en: "rainy days", es: "días de lluvia" },
        ],
      },
      {
        id: "d138-como",
        frameStem: "Como…",
        english: "Since Priya lives nearby, the detour doesn't cost her much.",
        spanish: "Como Priya vive cerca, el desvío no le cuesta mucho.",
        situationLabel: "Cerca del colegio",
        why: "*El desvío no le cuesta mucho* — why accepting help feels less guilty.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "lives nearby", es: "vive cerca" },
          { en: "detour", es: "desvío" },
          { en: "doesn't cost much", es: "no le cuesta mucho" },
        ],
      },
      {
        id: "d138-debido-a",
        frameStem: "Debido a…",
        english: "Due to her rides, I didn't miss a single day.",
        spanish: "Debido a sus rides, no falté ni un día.",
        situationLabel: "Asistencia perfecta",
        why: "*No falté ni un día* — the concrete result of Priya's help.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "rides", es: "rides" },
          { en: "didn't miss a day", es: "no falté ni un día" },
        ],
      },
      {
        id: "d138-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to Priya, I made it on time Friday.",
        spanish: "Gracias a Priya, llegué a tiempo el viernes.",
        situationLabel: "Viernes a tiempo",
        why: "*Llegué a tiempo el viernes* — the win at the end of a hard week.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "on time", es: "a tiempo" },
          { en: "friday", es: "el viernes" },
        ],
      },
    ],
  },
  {
    day: 139,
    themeEs: "Arreglado",
    themeEn: "Fixed",
    missionEs: "Cuenta el alivio de recuperar el coche y lo que aprendiste.",
    missionEn: "Tell about the relief of getting the car back and what you learned.",
    line: "Encender el motor sin miedo es un lujo que no valorabas.",
    lineEn: "Starting the engine without fear is a luxury you didn't appreciate.",
    prompts: [
      {
        id: "d139-por-eso",
        frameStem: "Por eso…",
        english: "That's why I breathed easy when I started the engine today.",
        spanish: "Por eso hoy respiré al encender el motor.",
        situationLabel: "Alivio al encender",
        why: "*Respiré al encender el motor* — the physical relief of a working car.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "breathed easy", es: "respiré" },
          { en: "started the engine", es: "encender el motor" },
          { en: "today", es: "hoy" },
        ],
      },
      {
        id: "d139-asi-que",
        frameStem: "Así que…",
        english: "So I went to the shop Saturday morning.",
        spanish: "Así que fui al taller el sábado por la mañana.",
        situationLabel: "Recoger el coche",
        why: "*El sábado por la mañana* — the errand you've been waiting for all week.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "went to the shop", es: "fui al taller" },
          { en: "saturday morning", es: "sábado por la mañana" },
        ],
      },
      {
        id: "d139-como",
        frameStem: "Como…",
        english: "Since it's fixed now, I can forget the chaos.",
        spanish: "Como ya está arreglado, puedo olvidar el caos.",
        situationLabel: "Volver a la normalidad",
        why: "*Puedo olvidar el caos* — permission to move on after a stressful week.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "fixed", es: "arreglado" },
          { en: "forget", es: "olvidar" },
          { en: "chaos", es: "caos" },
        ],
      },
      {
        id: "d139-debido-a",
        frameStem: "Debido a…",
        english: "Due to the whole week, I was exhausted Sunday.",
        spanish: "Debido a toda la semana, estaba agotada el domingo.",
        situationLabel: "Agotamiento del domingo",
        why: "*Estaba agotada el domingo* — past tense for the crash after the ordeal.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "whole week", es: "toda la semana" },
          { en: "exhausted", es: "agotada" },
          { en: "sunday", es: "domingo" },
        ],
      },
      {
        id: "d139-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to everyone who helped, I survived.",
        spanish: "Gracias a todos los que me ayudaron, sobreviví.",
        situationLabel: "Gratitud final",
        why: "*Sobreviví* — past tense for a week that's finally over.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "everyone who helped", es: "todos los que me ayudaron" },
          { en: "survived", es: "sobreviví" },
        ],
      },
    ],
  },
  {
    day: 140,
    themeEs: "Repaso: por eso",
    themeEn: "Review: that's why…",
    missionEs: "Resume toda la semana del coche en cinco frases de causa y efecto.",
    missionEn: "Summarize the whole car week in five cause-and-effect sentences.",
    line: "Una avería cabe en cinco conectores, si cuentas bien la cadena.",
    lineEn: "A breakdown fits in five connectors, if you trace the chain right.",
    prompts: [
      {
        id: "d140-por-eso",
        frameStem: "Por eso…",
        english: "That's why I had a whole week of chaotic transportation.",
        spanish: "Por eso tuve una semana entera de transporte caótico.",
        situationLabel: "La semana resumida",
        why: "*Una semana entera de transporte caótico* — the headline of Marlana's week.",
        wordHints: [
          { en: "that's why", es: "por eso" },
          { en: "whole week", es: "semana entera" },
          { en: "chaotic transportation", es: "transporte caótico" },
        ],
      },
      {
        id: "d140-asi-que",
        frameStem: "Así que…",
        english: "So I took Uber, bus, favors, and patience.",
        spanish: "Así que pedí Uber, bus, favores y paciencia.",
        situationLabel: "Todo lo que hizo",
        why: "*Favores y paciencia* — the non-transport items on the list matter too.",
        wordHints: [
          { en: "so", es: "así que" },
          { en: "uber", es: "uber" },
          { en: "bus", es: "bus" },
          { en: "favors", es: "favores" },
          { en: "patience", es: "paciencia" },
        ],
      },
      {
        id: "d140-como",
        frameStem: "Como…",
        english: "Since I ignored the check-engine light, the car stopped.",
        spanish: "Como ignoré la luz del motor, el coche se paró.",
        situationLabel: "La causa raíz",
        why: "*Como ignoré la luz del motor* — the lesson that starts the whole story.",
        wordHints: [
          { en: "since", es: "como" },
          { en: "ignored", es: "ignoré" },
          { en: "check-engine light", es: "luz del motor" },
          { en: "stopped", es: "se paró" },
        ],
      },
      {
        id: "d140-debido-a",
        frameStem: "Debido a…",
        english: "Due to the breakdown, I spent more than planned.",
        spanish: "Debido a la avería, gasté más de lo planeado.",
        situationLabel: "El costo total",
        why: "*Gasté más de lo planeado* — the financial bottom line of the saga.",
        wordHints: [
          { en: "due to", es: "debido a" },
          { en: "breakdown", es: "avería" },
          { en: "spent more", es: "gasté más" },
          { en: "planned", es: "planeado" },
        ],
      },
      {
        id: "d140-gracias-a",
        frameStem: "Gracias a…",
        english: "Thanks to Priya, the insurance, and the mechanic, I figured it out.",
        spanish: "Gracias a Priya, al seguro y al mecánico, lo resolví.",
        situationLabel: "Quién la salvó",
        why: "*Lo resolví* — past tense for a problem that's finally solved.",
        wordHints: [
          { en: "thanks to", es: "gracias a" },
          { en: "insurance", es: "seguro" },
          { en: "mechanic", es: "mecánico" },
          { en: "figured it out", es: "lo resolví" },
        ],
      },
    ],
  },
];
