import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 6 — "El cambio de horario" (days 127–133).
 * Marlana and Priya navigate a disruptive school schedule change.
 */
export const week6ReadingDays: ReadingDay[] = [
  {
    day: 127,
    themeEs: "La noticia",
    storyTitle: "El cambio de horario",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el horario", en: "the schedule", example: "El horario nuevo empieza el lunes." },
      { es: "implementar", en: "to implement", example: "Van a implementarlo sin consultarnos." },
      { es: "apresurado/a", en: "rushed, hasty", example: "Me parece muy apresurado." },
      { es: "la directora", en: "the principal", example: "La directora lo anunció en la reunión." },
      { es: "consultar", en: "to consult", example: "Prometieron consultarnos antes." },
    ],
    dialogue: {
      title: "¿Ya escuchaste?",
      situation: "En la sala de maestros, después de la reunión de personal",
      lines: [
        { speaker: "A", es: "Priya, ¿viste el correo de la directora?", en: "Priya, did you see the principal's email?" },
        { speaker: "B", es: "¿Cuál? ¿Qué pasó?", en: "Which one? What happened?" },
        { speaker: "A", es: "Cambian todo el horario del colegio. Empieza el lunes.", en: "They're changing the whole school schedule. It starts Monday." },
        { speaker: "B", es: "¿En serio? ¿Nos avisaron con tiempo?", en: "Seriously? Did they give us enough notice?" },
        { speaker: "A", es: "Sin embargo, nadie nos avisó con tiempo. Aunque la directora lo explicó bien, quedaron dudas.", en: "However, nobody told us in time. Although the principal explained it well, questions remained." },
        { speaker: "B", es: "¿Y por qué lo hacen?", en: "And why are they doing it?" },
        { speaker: "A", es: "En cambio, las clases empiezan quince minutos antes. A pesar de las quejas, van a implementarlo igual.", en: "Instead, classes start fifteen minutes earlier. Despite the complaints, they're going to implement it anyway." },
        { speaker: "B", es: "Por otro lado, ¿hay algo bueno en todo esto?", en: "On the other hand, is there anything good about all this?" },
        { speaker: "A", es: "Por otro lado, los bloques largos pueden ayudar a los de ciencias. Pero todavía estoy procesando.", en: "On the other hand, longer blocks might help the science teachers. But I'm still processing." },
      ],
    },
  },
  {
    day: 128,
    themeEs: "El almuerzo",
    storyTitle: "El cambio de horario",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el almuerzo", en: "lunch", example: "El almuerzo ahora es a las once y media." },
      { es: "la fila", en: "the line", example: "La fila del comedor no bajó." },
      { es: "el comedor", en: "the cafeteria", example: "El comedor estaba lleno a las once." },
      { es: "el recreo", en: "recess", example: "La hora de recreo se acortó." },
      { es: "el snack", en: "snack", example: "Pidieron snack a media tarde." },
    ],
    dialogue: {
      title: "Hambre a las dos",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "¿Cómo va el almuerzo con el horario nuevo?", en: "How's lunch going with the new schedule?" },
        { speaker: "B", es: "Un desastre. ¿Qué está pasando?", en: "A disaster. What's happening?" },
        { speaker: "A", es: "En cambio, el almuerzo ahora es a las once y media. Sin embargo, la fila del comedor no bajó.", en: "Instead, lunch is now at eleven thirty. However, the cafeteria line didn't get shorter." },
        { speaker: "B", es: "¿Y los niños?", en: "And the kids?" },
        { speaker: "A", es: "Aunque comen más temprano, piden snack a media tarde. A pesar de los letreros nuevos, van al salón equivocado después.", en: "Although they eat earlier, they ask for a snack mid-afternoon. Despite the new signs, they go to the wrong room afterward." },
        { speaker: "B", es: "Suena agotador.", en: "That sounds exhausting." },
        { speaker: "A", es: "Por otro lado, la cafetería está más tranquila después de las doce. Pequeña victoria.", en: "On the other hand, the cafeteria is quieter after twelve. Small victory." },
        { speaker: "B", es: "Bueno, algo es algo.", en: "Well, something is something." },
      ],
    },
  },
  {
    day: 129,
    themeEs: "Los maestros",
    storyTitle: "El cambio de horario",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la planificación", en: "planning period", example: "Perdimos el tiempo compartido." },
      { es: "el bloque", en: "the block (period)", example: "Los bloques de noventa minutos ayudan." },
      { es: "el sindicato", en: "the union", example: "El sindicato mandó una petición." },
      { es: "rígido/a", en: "rigid", example: "El calendario es muy rígido." },
      { es: "adaptarse", en: "to adapt", example: "Tratamos de adaptarnos, pero cuesta." },
    ],
    dialogue: {
      title: "¿Cuándo planificamos?",
      situation: "En la sala de maestros, antes de la primera campana",
      lines: [
        { speaker: "A", es: "Perdí mi hora de planificación con el cambio.", en: "I lost my planning period with the change." },
        { speaker: "B", es: "¿En serio? ¿Cuándo te tocó?", en: "Seriously? When did you get?" },
        { speaker: "A", es: "Sin embargo, mi hora de planificación ahora es a las siete de la mañana. En cambio, ya no coincidimos en horario.", en: "However, my planning period is now at seven in the morning. Instead, we no longer overlap in schedule." },
        { speaker: "B", es: "Eso es brutal. ¿Y el departamento?", en: "That's brutal. And the department?" },
        { speaker: "A", es: "Aunque tratamos de adaptarnos, es difícil calificar con este horario. A pesar de la petición del sindicato, no hubo cambios.", en: "Although we're trying to adapt, it's hard to grade with this schedule. Despite the union's petition, there were no changes." },
        { speaker: "B", es: "¿Nada de nada?", en: "Nothing at all?" },
        { speaker: "A", es: "Por otro lado, los bloques de noventa minutos ayudan en laboratorio. Al menos eso.", en: "On the other hand, ninety-minute blocks help in the lab. At least that." },
        { speaker: "B", es: "Tendremos que encontrar otro momento para planificar juntas.", en: "We'll have to find another time to plan together." },
      ],
    },
  },
  {
    day: 130,
    themeEs: "Los estudiantes",
    storyTitle: "El cambio de horario",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "confundido/a", en: "confused", example: "Los de sexto siguen confundidos." },
      { es: "el salón", en: "the classroom", example: "Llegaron al salón viejo." },
      { es: "el mapa", en: "the map", example: "Hay mapas en cada pasillo." },
      { es: "el megáfono", en: "the megaphone", example: "Recordatorios por megáfono." },
      { es: "perderse", en: "to get lost", example: "Tres estudiantes se perdieron entre bloques." },
    ],
    dialogue: {
      title: "¿Este es el salón correcto?",
      situation: "En la sala de maestros, al final del día",
      lines: [
        { speaker: "A", es: "Hoy la mitad de mi clase llegó al salón viejo.", en: "Today half my class showed up at the old room." },
        { speaker: "B", es: "¿Otra vez? ¿No les dieron mapas?", en: "Again? Didn't they get maps?" },
        { speaker: "A", es: "Aunque hay mapas en cada pasillo, algunos no los leen. Sin embargo, tres estudiantes se perdieron entre bloques.", en: "Although there are maps on every hallway, some don't read them. However, three students got lost between blocks." },
        { speaker: "B", es: "¿Y los de octavo?", en: "And the eighth graders?" },
        { speaker: "A", es: "En cambio, la campana suena diez minutos antes. A pesar de los ayudantes en los pasillos, el caos continúa.", en: "Instead, the bell rings ten minutes earlier. Despite the helpers in the hallways, the chaos continues." },
        { speaker: "B", es: "Tiene que mejorar pronto.", en: "It has to get better soon." },
        { speaker: "A", es: "Por otro lado, los de octavo ya memorizaron el horario y ayudan a los pequeños.", en: "On the other hand, the eighth graders already memorized the schedule and help the little ones." },
        { speaker: "B", es: "Los grandes salvando el día, como siempre.", en: "The older kids saving the day, as always." },
      ],
    },
  },
  {
    day: 131,
    themeEs: "Las familias",
    storyTitle: "El cambio de horario",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "la recogida", en: "pickup", example: "Muchas familias llegaron tarde a la recogida." },
      { es: "el estacionamiento", en: "the parking lot", example: "La fila de carros era un caos." },
      { es: "el autobús", en: "the bus", example: "Los autobuses salen por la calle de atrás." },
      { es: "el letrero", en: "the sign", example: "Pusimos letreros en la entrada." },
      { es: "desorganizar", en: "to disorganize", example: "Quince minutos desorganizaron todo." },
    ],
    dialogue: {
      title: "La fila de carros",
      situation: "En la sala de maestros, después de la salida",
      lines: [
        { speaker: "A", es: "La recogida de hoy fue un caos total.", en: "Today's pickup was total chaos." },
        { speaker: "B", es: "¿Qué pasó?", en: "What happened?" },
        { speaker: "A", es: "Sin embargo, muchas familias llegaron tarde. En cambio, la salida de primaria ahora es a las dos y cuarto.", en: "However, many families arrived late. Instead, elementary dismissal is now at two fifteen." },
        { speaker: "B", es: "¿Mandaron aviso?", en: "Did they send notice?" },
        { speaker: "A", es: "Aunque mandamos un correo el viernes, muchos no lo leyeron. A pesar de los voluntarios en la puerta, la fila era un desastre.", en: "Although we sent an email on Friday, many didn't read it. Despite the volunteers at the door, the line was a mess." },
        { speaker: "B", es: "Los papás deben estar furiosos.", en: "The parents must be furious." },
        { speaker: "A", es: "Por otro lado, algunas mamás prefieren recoger más temprano. No todas se quejan.", en: "On the other hand, some moms prefer picking up earlier. Not everyone is complaining." },
        { speaker: "B", es: "Mañana tiene que ir mejor.", en: "Tomorrow has to go better." },
      ],
    },
  },
  {
    day: 132,
    themeEs: "Lo bueno",
    storyTitle: "El cambio de horario",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "adaptarse", en: "to adapt", example: "Los estudiantes se están adaptando." },
      { es: "la normalidad", en: "normalcy", example: "Esto va a ser la nueva normalidad." },
      { es: "tranquilo/a", en: "calm, quiet", example: "Las tardes están más calmadas." },
      { es: "revertir", en: "to reverse, undo", example: "La directora no va a revertir el cambio." },
      { es: "la ventaja", en: "the advantage", example: "Algunos maestros ya ven ventajas." },
    ],
    dialogue: {
      title: "Una semana después",
      situation: "En la sala de maestros, el viernes por la tarde",
      lines: [
        { speaker: "A", es: "Bueno, cumplimos una semana con el horario nuevo.", en: "Well, we completed one week with the new schedule." },
        { speaker: "B", es: "¿Sobreviviste?", en: "Did you survive?" },
        { speaker: "A", es: "Sin embargo, no todo salió mal como pensábamos. Aunque el primer día fue un desastre, hoy fue más tranquilo.", en: "However, not everything went as badly as we thought. Although the first day was a disaster, today was calmer." },
        { speaker: "B", es: "¿Algo mejoró de verdad?", en: "Did something actually improve?" },
        { speaker: "A", es: "En cambio, las tardes en el pasillo están más calmadas. A pesar de las quejas iniciales, la asistencia no bajó.", en: "Instead, afternoons in the hallway are calmer. Despite the initial complaints, attendance didn't drop." },
        { speaker: "B", es: "Eso es buena señal.", en: "That's a good sign." },
        { speaker: "A", es: "Por otro lado, nos obligó a hablar más entre departamentos. Puede que en un mes esto sea la nueva normalidad.", en: "On the other hand, it forced us to talk more across departments. Maybe in a month this will be the new normal." },
        { speaker: "B", es: "Ojalá. Ya me cansé del caos.", en: "I hope so. I'm tired of the chaos already." },
      ],
    },
  },
  {
    day: 133,
    themeEs: "Repaso: sin embargo",
    isRecap: true,
    vocab: [
      { es: "el contraste", en: "the contrast", example: "Sin embargo marca el contraste." },
      { es: "la queja", en: "the complaint", example: "Las quejas llegaron de todos lados." },
      { es: "implementar", en: "to implement", example: "Implementaron el cambio igual." },
      { es: "adaptarse", en: "to adapt", example: "Todos nos estamos adaptando." },
      { es: "resumir", en: "to summarize", example: "¿Puedes resumir la semana?" },
    ],
    dialogue: {
      title: "El resumen del horario",
      situation: "En la sala de maestros, la semana siguiente al cambio",
      lines: [
        { speaker: "A", es: "Oye, ¿me resumís toda la semana del horario? Me perdí un par de días.", en: "Hey, can you sum up the whole schedule week for me? I missed a couple of days." },
        { speaker: "B", es: "Claro. Empezó con un correo y terminó con filas de carros y niños perdidos.", en: "Sure. It started with an email and ended with car lines and lost kids." },
        { speaker: "A", es: "Suena terrible. ¿Qué pasó con la directora?", en: "That sounds terrible. What happened with the principal?" },
        { speaker: "B", es: "Sin embargo, la directora no va a revertir el horario. A pesar de las quejas de maestros, padres y estudiantes, el cambio se quedó.", en: "However, the principal isn't going to reverse the schedule. Despite complaints from teachers, parents, and students, the change stayed." },
        { speaker: "A", es: "¿Y ustedes?", en: "And you all?" },
        { speaker: "B", es: "Aunque entendemos la razón, el cambio fue muy brusco. En cambio, el almuerzo, la planificación y la salida quedaron distintos.", en: "Although we understand the reason, the change was very abrupt. Instead, lunch, planning, and dismissal all ended up different." },
        { speaker: "A", es: "¿Algo positivo?", en: "Anything positive?" },
        { speaker: "B", es: "Por otro lado, los bloques largos ya tienen defensores y el caos bajó. En un mes esto va a parecer normal.", en: "On the other hand, the longer blocks already have defenders and the chaos went down. In a month this will seem normal." },
      ],
    },
  },
];
