import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 4 draft — "El día del huracán" (days 113–119).
 *
 * Marlana shares installments from her abuela's cuaderno about surviving a
 * hurricane in Puerto Rico when Marlana was little. Merge into
 * content/readings/otono.ts when ready.
 */
export const week4ReadingDays: ReadingDay[] = [
  {
    day: 113,
    themeEs: "La advertencia",
    storyTitle: "El día del huracán",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la advertencia", en: "the warning", example: "Empezaron las advertencias en la radio." },
      { es: "oscurecer", en: "to get dark", example: "Oscureció el cielo muy rápido." },
      { es: "las velas", en: "the candles", example: "Mi abuela ya había comprado velas." },
      { es: "el barrio", en: "the neighborhood", example: "En el barrio de mi abuela todo estaba callado." },
      { es: "la alerta", en: "the alert", example: "Sonó otra alerta en la radio." },
    ],
    dialogue: {
      title: "Lo que escribió mi abuela",
      situation: "En la sala de maestros, Marlana lee un cuaderno viejo a Priya",
      lines: [
        { speaker: "A", es: "Priya, encontré el cuaderno de mi abuela. Escribió sobre un huracán en Puerto Rico.", en: "Priya, I found my grandmother's notebook. She wrote about a hurricane in Puerto Rico." },
        { speaker: "B", es: "¿Cuándo fue eso? ¿Tú estabas ahí?", en: "When was that? Were you there?" },
        { speaker: "A", es: "Era pequeña, de visita. Dice que ya había llovido toda la mañana cuando empezaron las advertencias.", en: "I was little, visiting. She says it had already been raining all morning when the warnings started." },
        { speaker: "B", es: "¿Y qué pasó después?", en: "And what happened after?" },
        { speaker: "A", es: "Oscureció el cielo a las tres de la tarde. Nunca había visto el cielo tan oscuro.", en: "The sky got dark at three in the afternoon. She had never seen the sky that dark." },
        { speaker: "B", es: "Qué fuerte. ¿Ya estaban preparados?", en: "That's intense. Were they already prepared?" },
        { speaker: "A", es: "Sí — ya había comprado velas y comida. Todavía no había empezado la tormenta de verdad.", en: "Yes — she had already bought candles and food. The storm hadn't really started yet." },
        { speaker: "B", es: "Suena como si supiera lo que venía.", en: "Sounds like she knew what was coming." },
      ],
    },
  },
  {
    day: 114,
    themeEs: "La tormenta",
    storyTitle: "El día del huracán",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la tormenta", en: "the storm", example: "La tormenta llegó de noche." },
      { es: "se fue la luz", en: "the power went out", example: "Se fue la luz de golpe." },
      { es: "el viento", en: "the wind", example: "El viento pegó muy fuerte." },
      { es: "el cuarto del medio", en: "the middle room", example: "Entramos al cuarto del medio." },
      { es: "la rama", en: "the branch", example: "Cayó una rama grande en el patio." },
    ],
    dialogue: {
      title: "Cuando llegó",
      situation: "En la sala de maestros, continuando la lectura del cuaderno",
      lines: [
        { speaker: "B", es: "¿Y cuándo llegó la tormenta de verdad?", en: "And when did the storm really hit?" },
        { speaker: "A", es: "De noche. Ya había empezado a llover fuerte cuando se fue la luz.", en: "At night. It had already started raining hard when the power went out." },
        { speaker: "B", es: "Ay, qué miedo.", en: "Oh, how scary." },
        { speaker: "A", es: "Ya habíamos entrado al cuarto del medio cuando golpeó el viento. Nunca había escuchado el viento tan fuerte.", en: "We had already gone into the middle room when the wind hit. I had never heard wind that loud." },
        { speaker: "B", es: "¿Estaban solos?", en: "Were they alone?" },
        { speaker: "A", es: "No — estaban mi abuela, mis tíos, mis primos y yo. Antes había tenido luz y veíamos las noticias.", en: "No — my grandmother, my aunts and uncles, my cousins, and I were there. Before that we had had power and were watching the news." },
        { speaker: "A", es: "Para entonces ya había caído el árbol del vecino sobre el garaje.", en: "By then the neighbor's tree had already fallen on the garage." },
        { speaker: "B", es: "Dios mío. ¿Siguieron despiertos toda la noche?", en: "Oh my God. Did they stay awake all night?" },
      ],
    },
  },
  {
    day: 115,
    themeEs: "La noche larga",
    storyTitle: "El día del huracán",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la noche larga", en: "the long night", example: "Fue la noche más larga de mi vida." },
      { es: "despierto/a", en: "awake", example: "Seguíamos despiertos a medianoche." },
      { es: "rezar", en: "to pray", example: "Mi abuela rezó en voz baja." },
      { es: "el cuento", en: "the story (tale)", example: "Contó un cuento para calmar a los niños." },
      { es: "la rendija", en: "the crack (gap)", example: "Miró por la rendija de la ventana." },
    ],
    dialogue: {
      title: "Sin dormir",
      situation: "En la sala de maestros, la noche del huracán en el cuaderno",
      lines: [
        { speaker: "A", es: "Mi abuela escribe que ya había pasado media noche y seguían despiertos.", en: "My grandmother writes that midnight had already passed and they were still awake." },
        { speaker: "B", es: "¿Qué hicieron para aguantar?", en: "What did they do to get through it?" },
        { speaker: "A", es: "Contó cuentos a los primos pequeños. Ya había rezado cuando el viento volvió a pegar.", en: "She told stories to the little cousins. She had already prayed when the wind hit again." },
        { speaker: "B", es: "¿Y los niños?", en: "And the kids?" },
        { speaker: "A", es: "Nunca había pasado una noche tan larga sin luz ni agua caliente. Antes había llorado mi prima, pero después se durmió.", en: "I had never spent such a long night without light or hot water. Before that my cousin had cried, but then she fell asleep." },
        { speaker: "B", es: "¿Cuándo paró?", en: "When did it stop?" },
        { speaker: "A", es: "Todavía no había amanecido cuando el viento empezó a bajar.", en: "It still hadn't dawned when the wind started to die down." },
        { speaker: "A", es: "Para entonces ya había amanecido y la lluvia sonaba más lejos.", en: "By then it had already dawned and the rain sounded farther away." },
      ],
    },
  },
  {
    day: 116,
    themeEs: "El día después",
    storyTitle: "El día del huracán",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "el daño", en: "the damage", example: "Vimos el daño al salir afuera." },
      { es: "caerse", en: "to fall down", example: "Se cayó un árbol en la calle." },
      { es: "el vecino/la vecina", en: "the neighbor", example: "Los vecinos salieron a ayudar." },
      { es: "la macheta", en: "the machete", example: "Prestamos la macheta a la vecina." },
      { es: "limpiar", en: "to clean, clear", example: "Empezamos a limpiar la acera." },
    ],
    dialogue: {
      title: "A la luz del día",
      situation: "En la sala de maestros, el amanecer después del huracán",
      lines: [
        { speaker: "B", es: "¿Cómo amaneció el barrio?", en: "What did the neighborhood look like at dawn?" },
        { speaker: "A", es: "Ya había caído un árbol grande en la calle. Ya habían salido los vecinos a ver qué pasó.", en: "A big tree had already fallen in the street. The neighbors had already come out to see what happened." },
        { speaker: "B", es: "¿Regresó la luz?", en: "Did the power come back?" },
        { speaker: "A", es: "Todavía no había regresado la electricidad. Todavía no habíamos podido salir del barrio.", en: "The electricity still hadn't come back. We still hadn't been able to leave the neighborhood." },
        { speaker: "A", es: "Nunca había visto tantas ramas en una sola calle. Antes había sombra de árboles en casi toda la acera.", en: "I had never seen so many branches on one street. Before that there had been shade from trees on almost the whole sidewalk." },
        { speaker: "B", es: "Qué tristeza.", en: "How sad." },
        { speaker: "A", es: "Pero para entonces ya había limpiado la acera el señor de la esquina. Prestamos la macheta a la vecina.", en: "But by then the man on the corner had already cleaned the sidewalk. We lent our machete to the neighbor." },
        { speaker: "B", es: "Al menos se ayudaron.", en: "At least they helped each other." },
      ],
    },
  },
  {
    day: 117,
    themeEs: "Sin luz",
    storyTitle: "El día del huracán",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "sin luz", en: "without power", example: "Pasamos una semana sin luz." },
      { es: "echarse a perder", en: "to spoil", example: "Se echó a perder la comida del refrigerador." },
      { es: "la fogata", en: "the bonfire, outdoor fire", example: "Cocinamos arroz en la fogata." },
      { es: "el refrigerador", en: "the refrigerator", example: "Abrió el refrigerador y todo estaba malo." },
      { es: "compartir", en: "to share", example: "Compartimos hielo con los vecinos." },
    ],
    dialogue: {
      title: "Una semana sin electricidad",
      situation: "En la sala de maestros, los días después del huracán",
      lines: [
        { speaker: "A", es: "Lo peor no fue solo una noche. Ya había pasado una semana entera sin electricidad.", en: "The worst wasn't just one night. A whole week had already gone by without electricity." },
        { speaker: "B", es: "¿Una semana? ¿Cómo comían?", en: "A week? How did they eat?" },
        { speaker: "A", es: "Ya había echado a perder la comida del refrigerador. Aprendimos a cocinar arroz en la fogata del patio.", en: "The food in the fridge had already spoiled. We learned to cook rice on the bonfire in the yard." },
        { speaker: "B", es: "¿La escuela?", en: "What about school?" },
        { speaker: "A", es: "Todavía no había regresado la luz cuando cerraron la escuela otra semana. Nunca había comido tantas veces con todos los vecinos en la calle.", en: "The power still hadn't come back when they closed school for another week. I had never eaten so many meals with all the neighbors in the street." },
        { speaker: "A", es: "Antes había hielo en el congelador y leche fría por las mañanas.", en: "Before that there had been ice in the freezer and cold milk in the mornings." },
        { speaker: "B", es: "Qué cambio tan grande.", en: "What a big change." },
        { speaker: "A", es: "Para entonces ya había una olla grande de sopa en la casa del vecino. Gente compartía hielo y baterías.", en: "By then there was already a big pot of soup at the neighbor's house. People were sharing ice and batteries." },
      ],
    },
  },
  {
    day: 118,
    themeEs: "La reconstrucción",
    storyTitle: "El día del huracán",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "reconstruir", en: "to rebuild", example: "El barrio empezó a reconstruirse." },
      { es: "el techo", en: "the roof", example: "Arreglaron tres techos en la cuadra." },
      { es: "los escombros", en: "the debris", example: "Limpiaron los escombros de la calle." },
      { es: "el orgullo", en: "pride", example: "Sentí orgullo por el barrio." },
      { es: "el cuaderno", en: "the notebook", example: "Mi abuela escribió todo en su cuaderno." },
    ],
    dialogue: {
      title: "Juntos otra vez",
      situation: "En la sala de maestros, el final del cuaderno de la abuela",
      lines: [
        { speaker: "B", es: "¿Termina bien la historia?", en: "Does the story end well?" },
        { speaker: "A", es: "Termina con fuerza. Ya habían arreglado tres techos en la cuadra. Ya había limpiado el barrio casi por completo.", en: "It ends on a strong note. They had already fixed three roofs on the block. The neighborhood had already been cleaned up almost completely." },
        { speaker: "B", es: "¿Cuándo volvió la luz?", en: "When did the power come back?" },
        { speaker: "A", es: "Ya habíamos vuelto a encender la luz en la casa de mi abuela. Todavía no había regresado todo a la normalidad cuando nos fuimos.", en: "We had already turned the lights back on at my grandmother's house. Everything still hadn't gone back to normal when we left." },
        { speaker: "A", es: "Nunca había visto tanta gente trabajar junta en tan poco tiempo.", en: "I had never seen so many people working together in so little time." },
        { speaker: "B", es: "Por eso guardaba el cuaderno.", en: "That's why she kept the notebook." },
        { speaker: "A", es: "Exacto. Antes había miedo en cada casa. Para entonces ya había flores nuevas en el jardín de mi abuela.", en: "Exactly. Before that there had been fear in every house. By then there were already new flowers in my grandmother's garden." },
        { speaker: "A", es: "Para entonces ya había escrito mi abuela todo esto en su cuaderno — para que yo no lo olvidara.", en: "By then my grandmother had already written all of this in her notebook — so I wouldn't forget." },
      ],
    },
  },
  {
    day: 119,
    themeEs: "Repaso: ya había pasado",
    isRecap: true,
    vocab: [
      { es: "el huracán", en: "the hurricane", example: "Sobrevivieron al huracán juntos." },
      { es: "sobrevivir", en: "to survive", example: "Mi abuela escribió cómo sobrevivieron." },
      { es: "recordar", en: "to remember", example: "Escribió para que lo recordara." },
      { es: "volver a contar", en: "to retell", example: "Voy a volver a contar la historia." },
      { es: "el cuaderno", en: "the notebook", example: "Encontré el cuaderno de mi abuela." },
    ],
    dialogue: {
      title: "La historia completa",
      situation: "En la sala de maestros, Marlana resume el cuaderno entero",
      lines: [
        { speaker: "B", es: "Ok, dame el resumen completo. ¿Qué pasó con el huracán de tu abuela?", en: "Okay, give me the full summary. What happened with your grandmother's hurricane?" },
        { speaker: "A", es: "Bueno: ya había llovido toda la mañana cuando llegaron las advertencias. Todavía no había empezado la tormenta cuando oscureció el cielo.", en: "Okay: it had already been raining all morning when the warnings came. The storm still hadn't started when the sky went dark." },
        { speaker: "B", es: "¿Y la noche?", en: "And the night?" },
        { speaker: "A", es: "Nunca había escuchado el viento tan fuerte. Pasaron la noche despiertos en el cuarto del medio.", en: "I had never heard wind that loud. They spent the night awake in the middle room." },
        { speaker: "A", es: "Al día siguiente, ya había caído un árbol en la calle. Los vecinos limpiaron juntos.", en: "The next day, a tree had already fallen in the street. The neighbors cleaned up together." },
        { speaker: "B", es: "¿Y después?", en: "And after?" },
        { speaker: "A", es: "Una semana sin luz. Antes había hielo en el congelador; para entonces ya habían arreglado techos y compartido comida.", en: "A week without power. Before that there had been ice in the freezer; by then they had already fixed roofs and shared food." },
        { speaker: "B", es: "Qué historia tan fuerte — y qué forma de contarla con *ya había*.", en: "What a powerful story — and what a way to tell it with *ya había*." },
      ],
    },
  },
];
