import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 5 draft — "Además" (days 120–126).
 *
 * Append to content/prompts/otono.ts. prompt.spanish must stay verbatim with
 * week5-frames.ts examples for the matching frameStem.
 */
export const week5SpeakDays: SpeakDay[] = [
  {
    day: 120,
    themeEs: "La idea",
    themeEn: "The idea",
    missionEs: "Cuenta la propuesta de la feria y suma detalles con conectores.",
    missionEn: "Tell about the fair proposal and add details with connectors.",
    line: "Una buena idea crece cuando le sumas el siguiente detalle.",
    lineEn: "A good idea grows when you add the next detail.",
    prompts: [
      {
        id: "d120-ademas",
        frameStem: "Además…",
        english: "What's more, the idea is to celebrate the school's diversity.",
        spanish: "Además, la idea es celebrar la diversidad del colegio.",
        situationLabel: "Explicando el propósito",
        why: "*Además* at the start of a sentence stacks a new fact without changing topic — the move you need when a plan keeps growing.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "idea", es: "la idea" },
          { en: "celebrate", es: "celebrar" },
          { en: "diversity", es: "la diversidad" },
          { en: "school", es: "del colegio" },
        ],
      },
      {
        id: "d120-tambien",
        frameStem: "También…",
        english: "They also want families to participate.",
        spanish: "También quieren que las familias participen.",
        situationLabel: "Sumando otro objetivo",
        why: "*También* before the verb is the simplest way to say “also” in Spanish — no comma needed after it.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "want", es: "quieren" },
          { en: "families", es: "las familias" },
          { en: "participate", es: "participen" },
        ],
      },
      {
        id: "d120-aparte",
        frameStem: "Aparte de eso…",
        english: "On top of that, each class is going to have a booth.",
        spanish: "Aparte de eso, cada clase va a tener un puesto.",
        situationLabel: "Otro detalle del plan",
        why: "*Aparte de eso* signals a related but separate detail — perfect when planning talk branches into logistics.",
        wordHints: [
          { en: "on top of that", es: "aparte de eso" },
          { en: "each", es: "cada" },
          { en: "class", es: "clase" },
          { en: "booth", es: "un puesto" },
        ],
      },
      {
        id: "d120-no-solo",
        frameStem: "No solo… sino también…",
        english: "They're not only going to eat, but also learn about other cultures.",
        spanish: "No solo van a comer, sino también van a aprender de otras culturas.",
        situationLabel: "Dos metas a la vez",
        why: "*No solo… sino también* pairs two truths that belong together — here, fun and learning at the same fair.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "eat", es: "comer" },
          { en: "but also", es: "sino también" },
          { en: "learn", es: "aprender" },
          { en: "cultures", es: "otras culturas" },
        ],
      },
      {
        id: "d120-encima",
        frameStem: "Encima…",
        english: "On top of that, the principal said she can get funding.",
        spanish: "Encima, la directora dijo que puede conseguir fondos.",
        situationLabel: "Una buena sorpresa",
        why: "*Encima* often adds something extra to the pile — here, money the team wasn't sure they'd have.",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "principal", es: "la directora" },
          { en: "funding", es: "fondos" },
          { en: "get", es: "conseguir" },
        ],
      },
    ],
  },
  {
    day: 121,
    themeEs: "La comida",
    themeEn: "The food",
    missionEs: "Describe la comida de la feria y sigue sumando detalles.",
    missionEn: "Describe the fair food and keep adding details.",
    line: "Cada plato es una historia — y cada conector, otra porción.",
    lineEn: "Every dish is a story — and every connector, another serving.",
    prompts: [
      {
        id: "d121-ademas",
        frameStem: "Además…",
        english: "What's more, one mom is going to bring arepas from Venezuela.",
        spanish: "Además, una mamá va a traer arepas de Venezuela.",
        situationLabel: "Otro plato en el menú",
        why: "*Arepas de Venezuela* — naming the country with the dish — is exactly how multicultural fairs sound in real life.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "mom", es: "una mamá" },
          { en: "bring", es: "traer" },
          { en: "arepas", es: "arepas" },
          { en: "venezuela", es: "de venezuela" },
        ],
      },
      {
        id: "d121-tambien",
        frameStem: "También…",
        english: "They're also going to bring Colombian empanadas.",
        spanish: "También van a traer empanadas colombianas.",
        situationLabel: "Más comida en camino",
        why: "*Empanadas colombianas* — adjective after the noun — is the natural order in Spanish.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "bring", es: "traer" },
          { en: "empanadas", es: "empanadas colombianas" },
        ],
      },
      {
        id: "d121-aparte",
        frameStem: "Aparte de eso…",
        english: "Besides that, each dish gets a card with its country.",
        spanish: "Aparte de eso, cada plato lleva una tarjeta con el país.",
        situationLabel: "Los detalles de servicio",
        why: "*Llevar* here means “to include” or “to come with” — a small verb that does a lot in food-talk.",
        wordHints: [
          { en: "besides that", es: "aparte de eso" },
          { en: "each", es: "cada" },
          { en: "dish", es: "plato" },
          { en: "card", es: "una tarjeta" },
          { en: "country", es: "el país" },
        ],
      },
      {
        id: "d121-no-solo",
        frameStem: "No solo… sino también…",
        english: "They're not only going to try new food, but also hear stories.",
        spanish: "No solo van a probar comida nueva, sino también van a escuchar historias.",
        situationLabel: "Comer y aprender",
        why: "*Probar comida nueva* — “try new food” — is the phrase you'd use at a fair, not *comer comida nueva*.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "try", es: "probar" },
          { en: "new food", es: "comida nueva" },
          { en: "but also", es: "sino también" },
          { en: "stories", es: "historias" },
        ],
      },
      {
        id: "d121-encima",
        frameStem: "Encima…",
        english: "On top of that, the corner restaurant wants to donate desserts.",
        spanish: "Encima, el restaurante de la esquina quiere donar postres.",
        situationLabel: "Una donación extra",
        why: "*El restaurante de la esquina* — “the corner restaurant” — is a concrete neighborhood detail that makes retelling feel real.",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "corner restaurant", es: "el restaurante de la esquina" },
          { en: "donate", es: "donar" },
          { en: "desserts", es: "postres" },
        ],
      },
    ],
  },
  {
    day: 122,
    themeEs: "La música",
    themeEn: "The music",
    missionEs: "Cuenta los planes de música y añade lo que falta.",
    missionEn: "Tell the music plans and add what's still missing.",
    line: "La feria suena mejor cuando cada detalle tiene su turno.",
    lineEn: "The fair sounds better when every detail gets its turn.",
    prompts: [
      {
        id: "d122-ademas",
        frameStem: "Además…",
        english: "What's more, a dad is going to play guitar live.",
        spanish: "Además, un papá va a tocar la guitarra en vivo.",
        situationLabel: "Otra presentación",
        why: "*En vivo* — “live” — is the standard phrase for a live performance, not *en directo* in most of Latin America.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "dad", es: "un papá" },
          { en: "play", es: "tocar" },
          { en: "guitar", es: "la guitarra" },
          { en: "live", es: "en vivo" },
        ],
      },
      {
        id: "d122-tambien",
        frameStem: "También…",
        english: "They're also going to play a playlist between performances.",
        spanish: "También van a poner una lista de canciones entre presentaciones.",
        situationLabel: "Entre una actuación y otra",
        why: "*Poner una lista* — literally “put on a list” — is how you'd say “play a playlist” in casual Spanish.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "playlist", es: "una lista de canciones" },
          { en: "between", es: "entre" },
          { en: "performances", es: "presentaciones" },
        ],
      },
      {
        id: "d122-aparte",
        frameStem: "Aparte de eso…",
        english: "On top of that, some girls want to dance folk dances.",
        spanish: "Aparte de eso, unas niñas quieren bailar folklore.",
        situationLabel: "Baile en el programa",
        why: "*Folklore* in Spanish often means folk dance or traditional music — context makes it clear here.",
        wordHints: [
          { en: "on top of that", es: "aparte de eso" },
          { en: "girls", es: "unas niñas" },
          { en: "dance", es: "bailar" },
          { en: "folk", es: "folklore" },
        ],
      },
      {
        id: "d122-no-solo",
        frameStem: "No solo… sino también…",
        english: "They're not only going to listen to music, but also play some themselves.",
        spanish: "No solo van a escuchar música, sino también van a tocar algunos.",
        situationLabel: "Escuchar y participar",
        why: "*Tocar algunos* — “play some” — lets the verb carry the object when the context is already clear.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "listen", es: "escuchar" },
          { en: "music", es: "música" },
          { en: "but also", es: "sino también" },
          { en: "play", es: "tocar" },
        ],
      },
      {
        id: "d122-encima",
        frameStem: "Encima…",
        english: "On top of that, a former student offered to play violin.",
        spanish: "Encima, una exalumna ofreció tocar el violín.",
        situationLabel: "Una oferta inesperada",
        why: "*Exalumna* — a former student — is school vocabulary you'll hear constantly in the teachers' lounge.",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "former student", es: "una exalumna" },
          { en: "offered", es: "ofreció" },
          { en: "violin", es: "el violín" },
        ],
      },
    ],
  },
  {
    day: 123,
    themeEs: "Los voluntarios",
    themeEn: "The volunteers",
    missionEs: "Cuenta quién se apuntó y qué falta por cubrir.",
    missionEn: "Tell who signed up and what still needs covering.",
    line: "Una feria grande se construye turno por turno.",
    lineEn: "A big fair gets built shift by shift.",
    prompts: [
      {
        id: "d123-ademas",
        frameStem: "Además…",
        english: "What's more, Mr. Ortiz signed up to set up the tables.",
        spanish: "Además, el señor Ortiz se apuntó para montar las mesas.",
        situationLabel: "Otro voluntario",
        why: "*Apuntarse para + infinitive* — “sign up to do something” — is the phrase for volunteering in school contexts.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "signed up", es: "se apuntó" },
          { en: "set up", es: "montar" },
          { en: "tables", es: "las mesas" },
        ],
      },
      {
        id: "d123-tambien",
        frameStem: "También…",
        english: "I also signed up for early setup.",
        spanish: "También me anoté para la configuración temprano.",
        situationLabel: "Tu turno",
        why: "*Me anoté* — reflexive — means you put your own name on the list.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "signed up", es: "me anoté" },
          { en: "early", es: "temprano" },
          { en: "setup", es: "la configuración" },
        ],
      },
      {
        id: "d123-aparte",
        frameStem: "Aparte de eso…",
        english: "Besides that, someone has to pick up the chairs at the end.",
        spanish: "Aparte de eso, alguien tiene que recoger las sillas al final.",
        situationLabel: "La limpieza",
        why: "*Al final* at the end of a sentence anchors the task in time — when the fair is over.",
        wordHints: [
          { en: "besides that", es: "aparte de eso" },
          { en: "someone", es: "alguien" },
          { en: "pick up", es: "recoger" },
          { en: "chairs", es: "las sillas" },
          { en: "at the end", es: "al final" },
        ],
      },
      {
        id: "d123-no-solo",
        frameStem: "No solo… sino también…",
        english: "We not only set up the event, but also supervise the students.",
        spanish: "No solo montamos el evento, sino también supervisamos a los estudiantes.",
        situationLabel: "Dos responsabilidades",
        why: "*Supervisamos a los estudiantes* — the personal *a* before *estudiantes* is required because they're people.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "set up", es: "montamos" },
          { en: "but also", es: "sino también" },
          { en: "supervise", es: "supervisamos" },
          { en: "students", es: "los estudiantes" },
        ],
      },
      {
        id: "d123-encima",
        frameStem: "Encima…",
        english: "On top of that, ten families offered to help.",
        spanish: "Encima, diez familias se ofrecieron a ayudar.",
        situationLabel: "Más ayuda de la esperada",
        why: "*Ofrecerse a + infinitive* — “offer to help” — is reflexive: the families volunteered themselves.",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "ten", es: "diez" },
          { en: "families", es: "familias" },
          { en: "offered", es: "se ofrecieron" },
          { en: "help", es: "ayudar" },
        ],
      },
    ],
  },
  {
    day: 124,
    themeEs: "Los estudiantes",
    themeEn: "The students",
    missionEs: "Cuenta qué hacen los estudiantes para la feria.",
    missionEn: "Tell what the students are doing for the fair.",
    line: "Cuando los estudiantes se emocionan, la feria ya empezó.",
    lineEn: "When the students get excited, the fair has already begun.",
    prompts: [
      {
        id: "d124-ademas",
        frameStem: "Además…",
        english: "What's more, my students are making a big world map.",
        spanish: "Además, mis estudiantes están haciendo un mapa grande del mundo.",
        situationLabel: "Un proyecto en clase",
        why: "*Están haciendo* — present progressive — marks work in progress, exactly what you'd report midweek.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "students", es: "mis estudiantes" },
          { en: "making", es: "haciendo" },
          { en: "world map", es: "un mapa grande del mundo" },
        ],
      },
      {
        id: "d124-tambien",
        frameStem: "También…",
        english: "They're also designing posters with phrases in several languages.",
        spanish: "También están diseñando pósters con frases en varios idiomas.",
        situationLabel: "Los pósters",
        why: "*Pósters* — borrowed from English — is what you'll hear in a Boston school; *carteles* works too.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "designing", es: "diseñando" },
          { en: "posters", es: "pósters" },
          { en: "languages", es: "varios idiomas" },
        ],
      },
      {
        id: "d124-aparte",
        frameStem: "Aparte de eso…",
        english: "On top of that, they won't stop talking about the big day.",
        spanish: "Aparte de eso, no paran de hablar del gran día.",
        situationLabel: "La emoción",
        why: "*No parar de + infinitive* — “can't stop doing something” — captures student excitement in one phrase.",
        wordHints: [
          { en: "on top of that", es: "aparte de eso" },
          { en: "won't stop", es: "no paran de" },
          { en: "talking", es: "hablar" },
          { en: "big day", es: "el gran día" },
        ],
      },
      {
        id: "d124-no-solo",
        frameStem: "No solo… sino también…",
        english: "They're not only excited, but also very proud.",
        spanish: "No solo están emocionados, sino también muy orgullosos.",
        situationLabel: "Emoción y orgullo",
        why: "*Orgullosos* agrees in masculine plural with *estudiantes* — the adjective matches the noun it describes.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "excited", es: "emocionados" },
          { en: "but also", es: "sino también" },
          { en: "proud", es: "orgullosos" },
        ],
      },
      {
        id: "d124-encima",
        frameStem: "Encima…",
        english: "On top of that, some students convinced their parents to cook.",
        spanish: "Encima, unos estudiantes convencieron a sus papás de cocinar.",
        situationLabel: "Reclutando familias",
        why: "*Convencer a alguien de + infinitive* — “convince someone to do something” — is the full pattern.",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "convinced", es: "convencieron" },
          { en: "parents", es: "sus papás" },
          { en: "cook", es: "cocinar" },
        ],
      },
    ],
  },
  {
    day: 125,
    themeEs: "El gran día",
    themeEn: "The big day",
    missionEs: "Cuenta cómo fue la feria y suma las sorpresas.",
    missionEn: "Tell how the fair went and add the surprises.",
    line: "El gran día siempre trae algo que no estaba en el plan.",
    lineEn: "The big day always brings something that wasn't in the plan.",
    prompts: [
      {
        id: "d125-ademas",
        frameStem: "Además…",
        english: "What's more, more families came than we expected.",
        spanish: "Además, vinieron más familias de las que esperábamos.",
        situationLabel: "La asistencia",
        why: "*Más… de las que* — “more than we…” — is the natural comparative when the thing compared is feminine plural.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "more", es: "más" },
          { en: "families", es: "familias" },
          { en: "expected", es: "esperábamos" },
        ],
      },
      {
        id: "d125-tambien",
        frameStem: "También…",
        english: "There was also a surprise: an improvised dance group.",
        spanish: "También hubo una sorpresa: un grupo de baile improvisado.",
        situationLabel: "Una sorpresa",
        why: "*Improvisado* — “impromptu/improvised” — is the word for something that wasn't on the schedule.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "surprise", es: "una sorpresa" },
          { en: "dance group", es: "un grupo de baile" },
          { en: "improvised", es: "improvisado" },
        ],
      },
      {
        id: "d125-aparte",
        frameStem: "Aparte de eso…",
        english: "On top of that, the courtyard felt like a little festival.",
        spanish: "Aparte de eso, el patio se sintió como un festival pequeño.",
        situationLabel: "El ambiente",
        why: "*Sentirse como* — “feel like” — works for atmosphere, not just physical sensation.",
        wordHints: [
          { en: "on top of that", es: "aparte de eso" },
          { en: "courtyard", es: "el patio" },
          { en: "felt like", es: "se sintió como" },
          { en: "festival", es: "un festival pequeño" },
        ],
      },
      {
        id: "d125-no-solo",
        frameStem: "No solo… sino también…",
        english: "The food not only worked, but the live music did too.",
        spanish: "No solo funcionó la comida, sino también la música en vivo.",
        situationLabel: "Todo salió bien",
        why: "Dropping the second verb (*funcionó*) is natural in Spanish when both halves share it — *sino también la música*.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "worked", es: "funcionó" },
          { en: "food", es: "la comida" },
          { en: "but also", es: "sino también" },
          { en: "live music", es: "la música en vivo" },
        ],
      },
      {
        id: "d125-encima",
        frameStem: "Encima…",
        english: "On top of that, the principal said she wants to repeat it next year.",
        spanish: "Encima, la directora dijo que quiere repetirlo el año que viene.",
        situationLabel: "El mejor final",
        why: "*Repetirlo* — the *lo* refers back to the whole fair — “do it again.”",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "principal", es: "la directora" },
          { en: "repeat", es: "repetirlo" },
          { en: "next year", es: "el año que viene" },
        ],
      },
    ],
  },
  {
    day: 126,
    themeEs: "Repaso: además",
    themeEn: "Review: what's more",
    missionEs: "Reconstruye toda la feria con los cinco conectores.",
    missionEn: "Rebuild the whole fair using all five connectors.",
    line: "Una semana de detalles cabe en cinco frases, si sabes conectarlas.",
    lineEn: "A week of details fits in five sentences, if you know how to connect them.",
    prompts: [
      {
        id: "d126-ademas",
        frameStem: "Además…",
        english: "What's more, we went from a loose idea to a fair full of people.",
        spanish: "Además, pasamos de una idea suelta a una feria llena de gente.",
        situationLabel: "El arco completo",
        why: "*Pasamos de… a…* — “we went from… to…” — is the cleanest way to span a whole story in one phrase.",
        wordHints: [
          { en: "what's more", es: "además" },
          { en: "went from", es: "pasamos de" },
          { en: "loose idea", es: "una idea suelta" },
          { en: "fair", es: "una feria" },
          { en: "full of people", es: "llena de gente" },
        ],
      },
      {
        id: "d126-tambien",
        frameStem: "También…",
        english: "There was also food from five continents and live music.",
        spanish: "También hubo comida de cinco continentes y música en vivo.",
        situationLabel: "Todo lo que se sumó",
        why: "*Hubo* — preterite of *haber* — is how you report what existed at a past event.",
        wordHints: [
          { en: "also", es: "también" },
          { en: "food", es: "comida" },
          { en: "continents", es: "cinco continentes" },
          { en: "live music", es: "música en vivo" },
        ],
      },
      {
        id: "d126-aparte",
        frameStem: "Aparte de eso…",
        english: "On top of that, the school felt more united afterward.",
        spanish: "Aparte de eso, el colegio se sintió más unido después.",
        situationLabel: "Lo que quedó",
        why: "*Más unido* — “more united” — names the community feeling that outlasts the event itself.",
        wordHints: [
          { en: "on top of that", es: "aparte de eso" },
          { en: "school", es: "el colegio" },
          { en: "united", es: "más unido" },
          { en: "afterward", es: "después" },
        ],
      },
      {
        id: "d126-no-solo",
        frameStem: "No solo… sino también…",
        english: "We not only celebrated diversity, but also built it together.",
        spanish: "No solo celebramos la diversidad, sino también la construimos juntos.",
        situationLabel: "El doble logro",
        why: "*La construimos* — the *la* refers to *diversidad* — turning celebration into something you actively made.",
        wordHints: [
          { en: "not only", es: "no solo" },
          { en: "celebrated", es: "celebramos" },
          { en: "diversity", es: "la diversidad" },
          { en: "but also", es: "sino también" },
          { en: "built", es: "construimos" },
          { en: "together", es: "juntos" },
        ],
      },
      {
        id: "d126-encima",
        frameStem: "Encima…",
        english: "On top of that, the principal already wants to make it a tradition.",
        spanish: "Encima, la directora ya quiere hacerlo tradición.",
        situationLabel: "Lo que sigue",
        why: "*Hacerlo tradición* — “make it a tradition” — closes the recap with what comes next.",
        wordHints: [
          { en: "on top of that", es: "encima" },
          { en: "principal", es: "la directora" },
          { en: "tradition", es: "tradición" },
          { en: "make", es: "hacerlo" },
        ],
      },
    ],
  },
];
