import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 10 draft — "Opinar sobre lo leído" (days 155–161).
 *
 * Append to content/prompts/otono.ts. prompt.spanish must stay verbatim with
 * week10-frames.ts examples for the matching frameStem.
 */
export const week10SpeakDays: SpeakDay[] = [
  {
    day: 155,
    themeEs: "El artículo",
    themeEn: "The article",
    missionEs: "Reacciona al artículo que leíste — qué te llamó la atención.",
    missionEn: "React to the article you read — what caught your attention.",
    line: "Leer es solo el primer paso. Opinar es el segundo.",
    lineEn: "Reading is only the first step. Reacting is the second.",
    prompts: [
      {
        id: "d155-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was the article's title.",
        spanish: "Lo que más me llamó la atención fue el título del artículo.",
        situationLabel: "La primera reacción",
        why: "*Lo que más me llamó la atención* is how you open a reaction — the hook before the detail.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "most", es: "más" },
          { en: "title", es: "el título" },
          { en: "article", es: "del artículo" },
        ],
      },
      {
        id: "d155-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is why I hadn't seen it before.",
        spanish: "Lo que no entiendo es por qué no lo había visto antes.",
        situationLabel: "La duda honesta",
        why: "*Lo que no entiendo es* names a gap without pretending you got everything — honest reacting.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "why", es: "por qué" },
          { en: "before", es: "antes" },
          { en: "seen", es: "visto" },
        ],
      },
      {
        id: "d155-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that someone from here published it.",
        spanish: "Me dio gusto leer que alguien de aquí lo publicó.",
        situationLabel: "Lo positivo",
        why: "*Me dio gusto leer que* + subjunctive marks something in the text that felt good to encounter.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "read", es: "leer" },
          { en: "someone", es: "alguien" },
          { en: "published", es: "publicó" },
        ],
      },
      {
        id: "d155-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised that it appeared this very week.",
        spanish: "Me sorprendió que apareciera justo esta semana.",
        situationLabel: "La sorpresa",
        why: "*Me sorprendió que* + subjunctive — the natural shape for surprise about something you read.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "appeared", es: "apareciera" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d155-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author knows bilingual classrooms for real.",
        spanish: "Creo que el autor conoce salones bilingües de verdad.",
        situationLabel: "Tu veredicto",
        why: "*Creo que el autor* lets you venture an opinion about the writer without needing to be certain.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "author", es: "el autor" },
          { en: "knows", es: "conoce" },
          { en: "classrooms", es: "salones bilingües" },
        ],
      },
    ],
  },
  {
    day: 156,
    themeEs: "Los argumentos",
    themeEn: "The arguments",
    missionEs: "Reacciona a los argumentos del autor sobre educación bilingüe.",
    missionEn: "React to the author's arguments about bilingual education.",
    line: "Un buen argumento merece una buena reacción.",
    lineEn: "A good argument deserves a good reaction.",
    prompts: [
      {
        id: "d156-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was the idea of \"they don't lose, they gain.\"",
        spanish: "Lo que más me llamó la atención fue la idea de «no pierden, ganan».",
        situationLabel: "El argumento central",
        why: "Quotation marks in Spanish use « » — *la idea de «no pierden, ganan»* retells the author's frame.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "idea", es: "la idea" },
          { en: "don't lose", es: "no pierden" },
          { en: "gain", es: "ganan" },
        ],
      },
      {
        id: "d156-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is why they don't teach this in college.",
        spanish: "Lo que no entiendo es por qué no lo enseñan en la universidad.",
        situationLabel: "Una laguna",
        why: "*Por qué no lo enseñan* — present tense for an ongoing gap you noticed in the text.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "why", es: "por qué" },
          { en: "teach", es: "enseñan" },
          { en: "college", es: "la universidad" },
        ],
      },
      {
        id: "d156-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that he explains it with examples, not just theory.",
        spanish: "Me dio gusto leer que lo explica con ejemplos, no solo con teoría.",
        situationLabel: "Lo que funcionó",
        why: "*No solo con teoría* — the contrast you appreciated in how the author writes.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "examples", es: "ejemplos" },
          { en: "theory", es: "teoría" },
          { en: "explains", es: "explica" },
        ],
      },
      {
        id: "d156-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised that he mentions mental flexibility as an advantage.",
        spanish: "Me sorprendió que mencione la flexibilidad mental como ventaja.",
        situationLabel: "Algo inesperado",
        why: "*Mencione* — subjunctive after *me sorprendió que* — the grammar matches the surprise.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "mentions", es: "mencione" },
          { en: "flexibility", es: "flexibilidad mental" },
          { en: "advantage", es: "ventaja" },
        ],
      },
      {
        id: "d156-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author defends dual programs very clearly.",
        spanish: "Creo que el autor defiende los programas duales con claridad.",
        situationLabel: "Tu lectura del autor",
        why: "*Defiende con claridad* — your verdict on how well the author makes the case.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "defends", es: "defiende" },
          { en: "dual programs", es: "programas duales" },
          { en: "clearly", es: "con claridad" },
        ],
      },
    ],
  },
  {
    day: 157,
    themeEs: "Los datos",
    themeEn: "The data",
    missionEs: "Reacciona a los datos y estudios del artículo.",
    missionEn: "React to the article's data and studies.",
    line: "Los números también cuentan una historia — reacciona a ella.",
    lineEn: "Numbers tell a story too — react to it.",
    prompts: [
      {
        id: "d157-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was that bilingual students got better reading grades.",
        spanish: "Lo que más me llamó la atención fue que los bilingües sacaron mejores notas.",
        situationLabel: "El dato clave",
        why: "*Sacaron mejores notas* — preterite for a result reported in the study you read.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "bilingual", es: "bilingües" },
          { en: "grades", es: "notas" },
          { en: "better", es: "mejores" },
        ],
      },
      {
        id: "d157-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is how they chose the comparison schools.",
        spanish: "Lo que no entiendo es cómo eligieron las escuelas de comparación.",
        situationLabel: "La metodología",
        why: "*Cómo eligieron* — preterite because the study already happened; you're reacting to what you read.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "how", es: "cómo" },
          { en: "chose", es: "eligieron" },
          { en: "comparison", es: "comparación" },
        ],
      },
      {
        id: "d157-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that they followed the children for five years.",
        spanish: "Me dio gusto leer que siguieron a los niños cinco años.",
        situationLabel: "El seguimiento",
        why: "*Siguieron a los niños* — personal *a* before people — the study design you appreciated.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "followed", es: "siguieron" },
          { en: "children", es: "los niños" },
          { en: "five years", es: "cinco años" },
        ],
      },
      {
        id: "d157-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised the difference was so clear in the end.",
        spanish: "Me sorprendió que la diferencia fuera tan clara al final.",
        situationLabel: "El resultado",
        why: "*Fuera* — imperfect subjunctive after past surprise — the result that stood out.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "difference", es: "la diferencia" },
          { en: "clear", es: "clara" },
          { en: "in the end", es: "al final" },
        ],
      },
      {
        id: "d157-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author uses that data to answer those who doubt.",
        spanish: "Creo que el autor usa esos datos para responder a los que dudan.",
        situationLabel: "La estrategia",
        why: "*Los que dudan* — \"those who doubt\" — the audience the author is trying to reach.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "uses", es: "usa" },
          { en: "data", es: "datos" },
          { en: "doubt", es: "dudan" },
        ],
      },
    ],
  },
  {
    day: 158,
    themeEs: "Las voces en contra",
    themeEn: "The critics",
    missionEs: "Reacciona a cómo el artículo enfrenta las críticas.",
    missionEn: "React to how the article handles criticism.",
    line: "Opinar también es decir qué no te convenció del todo.",
    lineEn: "Reacting also means saying what didn't fully convince you.",
    prompts: [
      {
        id: "d158-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was that he didn't ignore the criticisms.",
        spanish: "Lo que más me llamó la atención fue que no ignoró las críticas.",
        situationLabel: "Lo valiente",
        why: "*No ignoró las críticas* — preterite — naming what the author did that earned your respect.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "didn't ignore", es: "no ignoró" },
          { en: "criticisms", es: "las críticas" },
        ],
      },
      {
        id: "d158-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is why that idea is still so strong.",
        spanish: "Lo que no entiendo es por qué esa idea sigue tan fuerte.",
        situationLabel: "El mito persistente",
        why: "*Sigue tan fuerte* — present tense for something that persists beyond the article.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "why", es: "por qué" },
          { en: "still", es: "sigue" },
          { en: "strong", es: "fuerte" },
        ],
      },
      {
        id: "d158-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that he responds with evidence from schools right here.",
        spanish: "Me dio gusto leer que responde con evidencia de escuelas aquí mismo.",
        situationLabel: "Evidencia local",
        why: "*Aquí mismo* — \"right here\" — local evidence is what made the response feel grounded.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "responds", es: "responde" },
          { en: "evidence", es: "evidencia" },
          { en: "right here", es: "aquí mismo" },
        ],
      },
      {
        id: "d158-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised he quoted critics with respect.",
        spanish: "Me sorprendió que citara voces en contra con respeto.",
        situationLabel: "El tono",
        why: "*Citara* — subjunctive — surprise that the author treated opponents fairly.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "quoted", es: "citara" },
          { en: "critics", es: "voces en contra" },
          { en: "respect", es: "respeto" },
        ],
      },
      {
        id: "d158-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author understands why people doubt.",
        spanish: "Creo que el autor entiende por qué la gente duda.",
        situationLabel: "Empatía del autor",
        why: "*Entiende por qué la gente duda* — your read on the author's empathy, not just his data.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "understands", es: "entiende" },
          { en: "why", es: "por qué" },
          { en: "doubt", es: "duda" },
        ],
      },
    ],
  },
  {
    day: 159,
    themeEs: "Mi conexión",
    themeEn: "My connection",
    missionEs: "Reacciona a la parte del artículo que te conectó personalmente.",
    missionEn: "React to the part of the article that connected with you personally.",
    line: "La mejor lectura te devuelve una parte de ti.",
    lineEn: "The best reading sends back a piece of yourself.",
    prompts: [
      {
        id: "d159-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was the teacher in the final example.",
        spanish: "Lo que más me llamó la atención fue la maestra del ejemplo final.",
        situationLabel: "Tu espejo",
        why: "*La maestra del ejemplo final* — naming the person in the text who felt like you.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "teacher", es: "la maestra" },
          { en: "final", es: "final" },
          { en: "example", es: "ejemplo" },
        ],
      },
      {
        id: "d159-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is why that part moved me so much.",
        spanish: "Lo que no entiendo es por qué me conmovió tanto esa parte.",
        situationLabel: "La emoción",
        why: "*Me conmovió* — preterite — honest reaction to something that hit harder than expected.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "moved me", es: "me conmovió" },
          { en: "so much", es: "tanto" },
          { en: "part", es: "esa parte" },
        ],
      },
      {
        id: "d159-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that he put a teacher as the protagonist.",
        spanish: "Me dio gusto leer que pusiera a una maestra como protagonista.",
        situationLabel: "Reconocimiento",
        why: "*Pusiera a una maestra como protagonista* — subjunctive — gladness about a choice the author made.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "teacher", es: "maestra" },
          { en: "protagonist", es: "protagonista" },
          { en: "put", es: "pusiera" },
        ],
      },
      {
        id: "d159-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised the author ended with such a simple sentence.",
        spanish: "Me sorprendió que el autor terminara con una frase tan simple.",
        situationLabel: "El cierre",
        why: "*Terminara con una frase tan simple* — surprise at how quietly the article closed.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "ended", es: "terminara" },
          { en: "simple", es: "simple" },
          { en: "sentence", es: "frase" },
        ],
      },
      {
        id: "d159-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author knows what happens in an ESL classroom.",
        spanish: "Creo que el autor conoce lo que pasa en un salón de ESL.",
        situationLabel: "Credibilidad",
        why: "*Lo que pasa en un salón de ESL* — your test for whether the author has been there.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "knows", es: "conoce" },
          { en: "what happens", es: "lo que pasa" },
          { en: "esl classroom", es: "salón de ESL" },
        ],
      },
    ],
  },
  {
    day: 160,
    themeEs: "La conversación",
    themeEn: "The conversation",
    missionEs: "Comparte tu reacción final al artículo con Priya.",
    missionEn: "Share your final reaction to the article with Priya.",
    line: "Leer solo es la mitad. Hablar de lo leído es la otra.",
    lineEn: "Reading alone is half. Talking about what you read is the other.",
    prompts: [
      {
        id: "d160-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was the title and the data together.",
        spanish: "Lo que más me llamó la atención fue el título y los datos juntos.",
        situationLabel: "El conjunto",
        why: "*Juntos* — \"together\" — pairing two parts of the article into one reaction.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "title", es: "título" },
          { en: "data", es: "datos" },
          { en: "together", es: "juntos" },
        ],
      },
      {
        id: "d160-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is why more principals don't read it.",
        spanish: "Lo que no entiendo es por qué no lo leen más directores.",
        situationLabel: "La distribución",
        why: "*Más directores* — the gap between a good article and the people who need it.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "why", es: "por qué" },
          { en: "principals", es: "directores" },
          { en: "read", es: "leen" },
        ],
      },
      {
        id: "d160-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that he proposed workshops for new families.",
        spanish: "Me dio gusto leer que propusiera talleres para familias nuevas.",
        situationLabel: "La propuesta",
        why: "*Propusiera talleres* — subjunctive — gladness about a concrete suggestion at the end.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "proposed", es: "propusiera" },
          { en: "workshops", es: "talleres" },
          { en: "families", es: "familias nuevas" },
        ],
      },
      {
        id: "d160-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised that at the end he proposed workshops for families.",
        spanish: "Me sorprendió que al final propusiera talleres para familias.",
        situationLabel: "El final práctico",
        why: "*Al final propusiera* — surprise that the article ended with action, not just argument.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "in the end", es: "al final" },
          { en: "proposed", es: "propusiera" },
          { en: "workshops", es: "talleres" },
        ],
      },
      {
        id: "d160-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author writes for teachers like us.",
        spanish: "Creo que el autor escribe para maestros como nosotras.",
        situationLabel: "Para quién escribe",
        why: "*Maestros como nosotras* — feminine plural because you're talking about yourself and Priya.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "writes", es: "escribe" },
          { en: "teachers", es: "maestros" },
          { en: "like us", es: "como nosotras" },
        ],
      },
    ],
  },
  {
    day: 161,
    themeEs: "Repaso: opinar",
    themeEn: "Review: reacting",
    missionEs: "Reconstruye tu reacción al artículo con los cinco stems.",
    missionEn: "Rebuild your reaction to the article using all five stems.",
    line: "Un artículo, cinco reacciones. Eso es opinar sobre lo leído.",
    lineEn: "One article, five reactions. That's reacting to what you read.",
    prompts: [
      {
        id: "d161-llamo-atencion",
        frameStem: "Lo que más me llamó la atención fue…",
        english: "What caught my attention most was the title — and the data at the end.",
        spanish: "Lo que más me llamó la atención fue el título — y los datos al final.",
        situationLabel: "El arco completo",
        why: "Repaso: span the whole article in one opening reaction.",
        wordHints: [
          { en: "caught my attention", es: "me llamó la atención" },
          { en: "title", es: "título" },
          { en: "data", es: "datos" },
          { en: "at the end", es: "al final" },
        ],
      },
      {
        id: "d161-no-entiendo",
        frameStem: "Lo que no entiendo es…",
        english: "What I don't understand is why it doesn't circulate more among parents.",
        spanish: "Lo que no entiendo es por qué no circula más entre los padres.",
        situationLabel: "La pregunta que queda",
        why: "*Circula más entre los padres* — the gap that outlasts a good article.",
        wordHints: [
          { en: "don't understand", es: "no entiendo" },
          { en: "circulate", es: "circula" },
          { en: "parents", es: "los padres" },
          { en: "more", es: "más" },
        ],
      },
      {
        id: "d161-dio-gusto",
        frameStem: "Me dio gusto leer que…",
        english: "I was glad to read that he answered criticisms with real evidence.",
        spanish: "Me dio gusto leer que respondiera a las críticas con evidencia real.",
        situationLabel: "Lo mejor del texto",
        why: "*Respondiera con evidencia real* — subjunctive — the quality you want to remember.",
        wordHints: [
          { en: "glad", es: "me dio gusto" },
          { en: "answered", es: "respondiera" },
          { en: "criticisms", es: "críticas" },
          { en: "evidence", es: "evidencia real" },
        ],
      },
      {
        id: "d161-sorprendio",
        frameStem: "Me sorprendió que…",
        english: "I was surprised he answered with evidence, not slogans.",
        spanish: "Me sorprendió que respondiera con evidencia, no con slogans.",
        situationLabel: "La sorpresa de la semana",
        why: "*No con slogans* — the contrast that made the article feel serious.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "answered", es: "respondiera" },
          { en: "evidence", es: "evidencia" },
          { en: "not slogans", es: "no slogans" },
        ],
      },
      {
        id: "d161-creo-autor",
        frameStem: "Creo que el autor…",
        english: "I think the author writes for teachers like us.",
        spanish: "Creo que el autor escribe para maestros como nosotras.",
        situationLabel: "Tu veredicto final",
        why: "Repaso day: five reaction stems, one article — close with your verdict.",
        wordHints: [
          { en: "think", es: "creo" },
          { en: "author", es: "el autor" },
          { en: "writes", es: "escribe" },
          { en: "teachers like us", es: "maestros como nosotras" },
        ],
      },
    ],
  },
];
