import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 2 — "Dice que…" (days 99–105).
 * Story: "La carta de la abuela" — Marlana retells her grandmother's letter to Priya.
 */
export const week2SpeakDays: SpeakDay[] = [
  {
    day: 99,
    themeEs: "La carta llega",
    themeEn: "The letter arrives",
    missionEs: "Cuenta qué dice la carta de tu abuela.",
    missionEn: "Tell what your grandmother's letter says.",
    line: "Una carta lejana se convierte en conversación cuando sabes cómo contarla.",
    lineEn: "A distant letter becomes conversation when you know how to tell it.",
    prompts: [
      {
        id: "d99-dice-que",
        frameStem: "Dice que…",
        english: "She says she's in very good health.",
        spanish: "Dice que está muy bien de salud.",
        situationLabel: "Contándole a Priya",
        why: "*Dice que* + present tense is how you report what someone wrote or said — the core of this week's toolkit.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "very well", es: "muy bien" },
          { en: "health", es: "de salud" },
        ],
      },
      {
        id: "d99-segun",
        frameStem: "Según…",
        english: "According to the letter, winter in Puerto Rico has been mild.",
        spanish: "Según la carta, el invierno en Puerto Rico ha sido suave.",
        situationLabel: "Lo que dice la carta",
        why: "*Según* + source names where the information comes from — the letter, abuela, the news.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "letter", es: "la carta" },
          { en: "winter", es: "el invierno" },
          { en: "mild", es: "suave" },
        ],
      },
      {
        id: "d99-explica-que",
        frameStem: "Explica que…",
        english: "She explains that she prefers writing by hand to sending messages.",
        spanish: "Explica que prefiere escribir a mano que mandar mensajes.",
        situationLabel: "Por qué escribe cartas",
        why: "*Explica que* adds the reason or background behind what someone said — not just the fact, but the why.",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "prefers", es: "prefiere" },
          { en: "by hand", es: "a mano" },
          { en: "messages", es: "mensajes" },
        ],
      },
      {
        id: "d99-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about a long letter full of affection.",
        spanish: "Se trata de una carta larga y llena de cariño.",
        situationLabel: "De qué va la carta",
        why: "*Se trata de* names the topic before the details — the same opening move as *trata de*, but for reporting someone else's words.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "long letter", es: "una carta larga" },
          { en: "affection", es: "cariño" },
        ],
      },
      {
        id: "d99-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says she was very happy when I told her about my new job.",
        spanish: "Cuenta que se alegró mucho cuando le conté de mi trabajo nuevo.",
        situationLabel: "Una noticia que la emocionó",
        why: "*Cuenta que* is slightly more narrative than *dice que* — good for stories and emotional moments inside a letter.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "was happy", es: "se alegró" },
          { en: "new job", es: "mi trabajo nuevo" },
        ],
      },
    ],
  },
  {
    day: 100,
    themeEs: "Recuerdos de la infancia",
    themeEn: "Childhood memories",
    missionEs: "Cuenta los recuerdos de la infancia que escribe tu abuela.",
    missionEn: "Tell the childhood memories your grandmother writes about.",
    line: "Los recuerdos de otra persona se vuelven tuyos cuando los cuentas bien.",
    lineEn: "Someone else's memories become yours when you tell them well.",
    prompts: [
      {
        id: "d100-dice-que",
        frameStem: "Dice que…",
        english: "She says that as a girl she ran barefoot in the yard.",
        spanish: "Dice que de niña corría descalza por el patio.",
        situationLabel: "La abuela de joven",
        why: "*De niña* — “as a girl” — situates the memory in the past without switching to preterite in the reporting frame.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "as a girl", es: "de niña" },
          { en: "barefoot", es: "descalza" },
          { en: "yard", es: "el patio" },
        ],
      },
      {
        id: "d100-segun",
        frameStem: "Según…",
        english: "According to the letter, her grandmother's house had a huge mango tree.",
        spanish: "Según la carta, la casa de su abuela tenía un árbol de mango enorme.",
        situationLabel: "Lo que describe la carta",
        why: "*Tenía* stays in imperfect because you're describing how things used to be — a backdrop, not a single event.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "grandmother's house", es: "la casa de su abuela" },
          { en: "mango tree", es: "un árbol de mango" },
        ],
      },
      {
        id: "d100-explica-que",
        frameStem: "Explica que…",
        english: "She explains that the smell of coffee in the morning never leaves her.",
        spanish: "Explica que el olor a café en la mañana nunca se le olvida.",
        situationLabel: "Un recuerdo sensorial",
        why: "*Se le olvida* — the indirect object *le* — is the natural way to say something slips your mind (or doesn't).",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "smell of coffee", es: "el olor a café" },
          { en: "never forgets", es: "nunca se le olvida" },
        ],
      },
      {
        id: "d100-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about memories from when she was a child in Puerto Rico.",
        spanish: "Se trata de recuerdos de cuando era niña en Puerto Rico.",
        situationLabel: "Esta parte de la carta",
        why: "*Cuando era niña* uses imperfect to set the scene — who she was, not what she did once.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "memories", es: "recuerdos" },
          { en: "when she was a child", es: "cuando era niña" },
        ],
      },
      {
        id: "d100-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says I used to hide under the kitchen table.",
        spanish: "Cuenta que yo me escondía debajo de la mesa de la cocina.",
        situationLabel: "Un recuerdo de ti de niña",
        why: "*Me escondía* — imperfect — describes a habit, something you did over and over as a kid.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "hid", es: "me escondía" },
          { en: "kitchen table", es: "la mesa de la cocina" },
        ],
      },
    ],
  },
  {
    day: 101,
    themeEs: "La receta secreta",
    themeEn: "The secret recipe",
    missionEs: "Cuenta la receta familiar que comparte tu abuela.",
    missionEn: "Tell the family recipe your grandmother shares.",
    line: "Una receta contada en voz alta es casi tan buena como olerla cocinar.",
    lineEn: "A recipe told out loud is almost as good as smelling it cook.",
    prompts: [
      {
        id: "d101-dice-que",
        frameStem: "Dice que…",
        english: "She says the recipe calls for fresh pigeon peas, not canned.",
        spanish: "Dice que la receta lleva gandules frescos, no de lata.",
        situationLabel: "El ingrediente clave",
        why: "*Lleva* — “it calls for/takes” — is how recipes talk about ingredients in Spanish.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "recipe", es: "la receta" },
          { en: "fresh pigeon peas", es: "gandules frescos" },
          { en: "not canned", es: "no de lata" },
        ],
      },
      {
        id: "d101-segun",
        frameStem: "Según…",
        english: "According to the letter, the recipe comes from her own grandmother.",
        spanish: "Según la carta, la receta viene de su propia abuela.",
        situationLabel: "De dónde viene",
        why: "*Viene de* — “comes from” — traces the recipe back through generations in one clean phrase.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "comes from", es: "viene de" },
          { en: "own grandmother", es: "su propia abuela" },
        ],
      },
      {
        id: "d101-explica-que",
        frameStem: "Explica que…",
        english: "She explains that the rice has to come out loose, not sticky.",
        spanish: "Explica que el arroz tiene que quedar suelto, no pegado.",
        situationLabel: "El truco del arroz",
        why: "*Quedar suelto* — “to come out loose” — is kitchen Spanish you'll hear in any abuela's kitchen.",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "rice", es: "el arroz" },
          { en: "loose", es: "suelto" },
          { en: "sticky", es: "pegado" },
        ],
      },
      {
        id: "d101-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about the family's arroz con gandules recipe.",
        spanish: "Se trata de la receta de arroz con gandules de la familia.",
        situationLabel: "El plato de la familia",
        why: "*Arroz con gandules* is Puerto Rico on a plate — naming the dish anchors the whole retelling.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "family recipe", es: "la receta de la familia" },
          { en: "arroz con gandules", es: "arroz con gandules" },
        ],
      },
      {
        id: "d101-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says she makes it every Christmas without fail.",
        spanish: "Cuenta que lo prepara cada Navidad sin falta.",
        situationLabel: "Una tradición",
        why: "*Sin falta* — “without fail” — turns a habit into a promise, the way family traditions sound.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "makes it", es: "lo prepara" },
          { en: "every christmas", es: "cada navidad" },
          { en: "without fail", es: "sin falta" },
        ],
      },
    ],
  },
  {
    day: 102,
    themeEs: "Consejos de la abuela",
    themeEn: "Grandmother's advice",
    missionEs: "Cuenta los consejos que te da tu abuela en la carta.",
    missionEn: "Tell the advice your grandmother gives you in the letter.",
    line: "Los consejos de abuela suenan distintos cuando los repites en voz alta.",
    lineEn: "Grandmother's advice sounds different when you say it out loud.",
    prompts: [
      {
        id: "d102-dice-que",
        frameStem: "Dice que…",
        english: "She says I need to rest more on weekends.",
        spanish: "Dice que tengo que descansar más los fines de semana.",
        situationLabel: "Consejo directo",
        why: "*Tengo que* inside reported speech keeps abuela's tone — direct, loving, no negotiation.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "need to", es: "tengo que" },
          { en: "rest more", es: "descansar más" },
          { en: "weekends", es: "los fines de semana" },
        ],
      },
      {
        id: "d102-segun",
        frameStem: "Según…",
        english: "According to the letter, the most important thing is taking care of your health.",
        spanish: "Según la carta, lo más importante es cuidar la salud.",
        situationLabel: "Su prioridad",
        why: "*Lo más importante es* — “the most important thing is” — is how abuela frames advice so it sticks.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "most important", es: "lo más importante" },
          { en: "take care of health", es: "cuidar la salud" },
        ],
      },
      {
        id: "d102-explica-que",
        frameStem: "Explica que…",
        english: "She explains that she saw many young people burn out from working too much.",
        spanish: "Explica que vio a mucha gente joven quemarse por trabajar demasiado.",
        situationLabel: "Por qué le preocupa",
        why: "*Quemarse* — “to burn out” — is the word Marlana's students would recognize; abuela would too.",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "saw", es: "vio" },
          { en: "burn out", es: "quemarse" },
          { en: "working too much", es: "trabajar demasiado" },
        ],
      },
      {
        id: "d102-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about grandmother's advice, direct and without beating around the bush.",
        spanish: "Se trata de consejos de abuela, directos y sin rodeos.",
        situationLabel: "El tono de esta parte",
        why: "*Sin rodeos* — “without beating around the bush” — captures exactly how abuela writes.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "grandmother's advice", es: "consejos de abuela" },
          { en: "without beating around the bush", es: "sin rodeos" },
        ],
      },
      {
        id: "d102-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says she worries when I go weeks without writing to her.",
        spanish: "Cuenta que se preocupa cuando paso semanas sin escribirle.",
        situationLabel: "Lo que siente",
        why: "*Escribirle* attaches the pronoun to the infinitive — “writing to her” — one smooth word.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "worries", es: "se preocupa" },
          { en: "weeks without writing", es: "semanas sin escribirle" },
        ],
      },
    ],
  },
  {
    day: 103,
    themeEs: "La foto vieja",
    themeEn: "The old photo",
    missionEs: "Cuenta qué dice tu abuela sobre la foto vieja.",
    missionEn: "Tell what your grandmother says about the old photo.",
    line: "Una foto vieja cobra vida cuando alguien te cuenta lo que pasó ese día.",
    lineEn: "An old photo comes alive when someone tells you what happened that day.",
    prompts: [
      {
        id: "d103-dice-que",
        frameStem: "Dice que…",
        english: "She says the photo is about twenty years old.",
        spanish: "Dice que la foto tiene veinte años, más o menos.",
        situationLabel: "La foto que cayó del sobre",
        why: "*Más o menos* — “more or less” — softens the guess, the way you'd actually say it out loud.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "photo", es: "la foto" },
          { en: "twenty years old", es: "veinte años" },
          { en: "more or less", es: "más o menos" },
        ],
      },
      {
        id: "d103-segun",
        frameStem: "Según…",
        english: "According to the letter, the photo is from the summer I spent at her house.",
        spanish: "Según la carta, la foto es del verano que pasé en su casa.",
        situationLabel: "Cuándo fue",
        why: "*Del verano que pasé* — a relative clause in preterite — pins the photo to one specific summer.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "photo", es: "la foto" },
          { en: "summer i spent", es: "el verano que pasé" },
          { en: "her house", es: "su casa" },
        ],
      },
      {
        id: "d103-explica-que",
        frameStem: "Explica que…",
        english: "She explains that she kept the photo in her drawer of mementos.",
        spanish: "Explica que guardó la foto en su gaveta de recuerdos.",
        situationLabel: "Dónde la guardó",
        why: "*Gaveta de recuerdos* — “drawer of mementos” — is more poetic than *cajón*, and abuela would write it that way.",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "kept", es: "guardó" },
          { en: "drawer of mementos", es: "gaveta de recuerdos" },
        ],
      },
      {
        id: "d103-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about a photo of grandmother and me on her porch.",
        spanish: "Se trata de una foto de abuela y yo en su portal.",
        situationLabel: "Quién sale en la foto",
        why: "*Portal* — porch — is the Puerto Rican word for where abuela would sit in the afternoons.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "photo", es: "una foto" },
          { en: "porch", es: "su portal" },
        ],
      },
      {
        id: "d103-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says I didn't want to leave the beach when it got dark.",
        spanish: "Cuenta que yo no quería salir de la playa cuando anocheció.",
        situationLabel: "Lo que pasó ese día",
        why: "*Anocheció* — “it got dark” — is one verb for what English needs a whole clause to say.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "didn't want to leave", es: "no quería salir" },
          { en: "beach", es: "la playa" },
          { en: "got dark", es: "anocheció" },
        ],
      },
    ],
  },
  {
    day: 104,
    themeEs: "Quiere visitar",
    themeEn: "She wants to visit",
    missionEs: "Cuenta los planes de tu abuela para visitar Boston.",
    missionEn: "Tell your grandmother's plans to visit Boston.",
    line: "Contar los planes de alguien es casi como hacerlos realidad.",
    lineEn: "Telling someone's plans is almost like making them real.",
    prompts: [
      {
        id: "d104-dice-que",
        frameStem: "Dice que…",
        english: "She says she wants to visit me next year.",
        spanish: "Dice que quiere visitarme el próximo año.",
        situationLabel: "La noticia más emocionante",
        why: "*Visitarme* — object pronoun on the infinitive — is how you'd naturally report abuela's wish.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "wants to visit me", es: "quiere visitarme" },
          { en: "next year", es: "el próximo año" },
        ],
      },
      {
        id: "d104-segun",
        frameStem: "Según…",
        english: "According to the letter, she wants to come in spring, not winter.",
        spanish: "Según la carta, quiere venir en la primavera, no en invierno.",
        situationLabel: "Cuándo quiere venir",
        why: "*En la primavera, no en invierno* — the contrast is built into the sentence, no extra connector needed.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "spring", es: "la primavera" },
          { en: "winter", es: "invierno" },
        ],
      },
      {
        id: "d104-explica-que",
        frameStem: "Explica que…",
        english: "She explains that she wants to see with her own eyes how I live here.",
        spanish: "Explica que quiere ver con sus propios ojos cómo vivo aquí.",
        situationLabel: "Por qué quiere venir",
        why: "*Con sus propios ojos* — “with her own eyes” — is the phrase for seeing something firsthand.",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "with her own eyes", es: "con sus propios ojos" },
          { en: "how i live", es: "cómo vivo aquí" },
        ],
      },
      {
        id: "d104-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about a trip she's been planning for months.",
        spanish: "Se trata de un viaje que lleva meses planeando.",
        situationLabel: "El plan del viaje",
        why: "*Lleva meses planeando* — “she's been planning for months” — uses *llevar* + time for ongoing duration.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "trip", es: "un viaje" },
          { en: "been planning for months", es: "lleva meses planeando" },
        ],
      },
      {
        id: "d104-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says she already told the whole family about the plan.",
        spanish: "Cuenta que ya le contó a toda la familia del plan.",
        situationLabel: "Quién más sabe",
        why: "*Le contó a toda la familia* — the *le* marks who she told, even though *familia* is right there.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "already told", es: "ya le contó" },
          { en: "whole family", es: "toda la familia" },
          { en: "plan", es: "del plan" },
        ],
      },
    ],
  },
  {
    day: 105,
    themeEs: "Repaso: dice que",
    themeEn: "Review: she says that…",
    missionEs: "Cuenta toda la historia de la carta en cinco frases.",
    missionEn: "Tell the whole letter story in five sentences.",
    line: "Una carta entera cabe en cinco frases, si sabes cuáles elegir.",
    lineEn: "A whole letter fits into five sentences, if you know which ones to choose.",
    prompts: [
      {
        id: "d105-dice-que",
        frameStem: "Dice que…",
        english: "She says she's fine, she misses me, and she wants to visit me next year.",
        spanish: "Dice que está bien, que me extraña y que quiere visitarme el próximo año.",
        situationLabel: "El resumen en una frase",
        why: "Stacking three *que* clauses in one sentence is how native speakers compress a whole letter.",
        wordHints: [
          { en: "says", es: "dice que" },
          { en: "fine", es: "está bien" },
          { en: "misses me", es: "me extraña" },
          { en: "visit me", es: "visitarme" },
        ],
      },
      {
        id: "d105-segun",
        frameStem: "Según…",
        english: "According to the letter, she spent weeks writing it with great affection.",
        spanish: "Según la carta, pasó semanas escribiéndola con mucho cariño.",
        situationLabel: "Cómo la escribió",
        why: "*Escribiéndola* — gerund with attached pronoun — shows the effort behind the letter.",
        wordHints: [
          { en: "according to", es: "según" },
          { en: "spent weeks", es: "pasó semanas" },
          { en: "writing it", es: "escribiéndola" },
          { en: "affection", es: "cariño" },
        ],
      },
      {
        id: "d105-explica-que",
        frameStem: "Explica que…",
        english: "She explains that she wrote the letter to feel closer to me.",
        spanish: "Explica que escribió la carta para sentirse más cerca de mí.",
        situationLabel: "Por qué la mandó",
        why: "*Para sentirse más cerca* — purpose clause — gives the emotional reason behind six pages of handwriting.",
        wordHints: [
          { en: "explains", es: "explica que" },
          { en: "wrote the letter", es: "escribió la carta" },
          { en: "feel closer", es: "sentirse más cerca" },
        ],
      },
      {
        id: "d105-se-trata-de",
        frameStem: "Se trata de…",
        english: "It's about memories, food, advice, and plans for the future.",
        spanish: "Se trata de recuerdos, comida, consejos y planes de futuro.",
        situationLabel: "De qué va toda la carta",
        why: "Listing four nouns with commas is the fastest way to summarize six days of installments.",
        wordHints: [
          { en: "about", es: "se trata de" },
          { en: "memories", es: "recuerdos" },
          { en: "advice", es: "consejos" },
          { en: "future plans", es: "planes de futuro" },
        ],
      },
      {
        id: "d105-cuenta-que",
        frameStem: "Cuenta que…",
        english: "She says that no matter the distance, family is still family.",
        spanish: "Cuenta que no importa la distancia, la familia sigue siendo familia.",
        situationLabel: "El mensaje final",
        why: "*No importa la distancia* — a comma, not a *que* — is how this proverb-like line actually sounds spoken.",
        wordHints: [
          { en: "says/tells", es: "cuenta que" },
          { en: "no matter the distance", es: "no importa la distancia" },
          { en: "family", es: "la familia" },
        ],
      },
    ],
  },
];
