import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 7 — "La avería del coche" (days 134–140).
 * Marlana's car breaks down; cause-and-effect chain with Priya in the teachers lounge.
 */
export const week7ReadingDays: ReadingDay[] = [
  {
    day: 134,
    themeEs: "Se paró el coche",
    storyTitle: "La avería del coche",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la avería", en: "the breakdown", example: "Tuve una avería en la autopista." },
      { es: "el arcén", en: "the shoulder (of road)", example: "Me paré en el arcén." },
      { es: "el capó", en: "the hood", example: "Abrí el capó pero no vi nada." },
      { es: "la luz del motor", en: "check engine light", example: "La luz del motor llevaba días encendida." },
      { es: "la grúa", en: "the tow truck", example: "La grúa tardó media hora." },
    ],
    dialogue: {
      title: "En el arcén",
      situation: "En la sala de maestros, la mañana después de la avería",
      lines: [
        { speaker: "A", es: "Priya, ayer se me paró el coche en la autopista.", en: "Priya, yesterday my car died on the highway." },
        { speaker: "B", es: "¿En serio? ¿Estás bien?", en: "Seriously? Are you okay?" },
        { speaker: "A", es: "Sí, pero qué susto. Como la luz del motor llevaba días encendida, no me sorprendió del todo.", en: "Yes, but what a scare. Since the check engine light had been on for days, I wasn't entirely surprised." },
        { speaker: "B", es: "¿Qué hiciste?", en: "What did you do?" },
        { speaker: "A", es: "Así que apagué el motor y llamé desde el arcén. Por eso tuve que llamarte — necesitaba que alguien supiera dónde estaba.", en: "So I turned off the engine and called from the shoulder. That's why I had to call you — I needed someone to know where I was." },
        { speaker: "B", es: "Gracias por avisarme. ¿Vino la grúa?", en: "Thanks for letting me know. Did the tow truck come?" },
        { speaker: "A", es: "Sí. Gracias al seguro, la grúa salió gratis. Debido al tráfico, tardó un rato.", en: "Yes. Thanks to insurance, the tow was free. Due to traffic, it took a while." },
        { speaker: "B", es: "Menos mal. ¿Cómo llegaste al colegio?", en: "Thank goodness. How did you get to school?" },
      ],
    },
  },
  {
    day: 135,
    themeEs: "Llegué tarde",
    storyTitle: "La avería del coche",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "tarde", en: "late", example: "Llegué veinte minutos tarde." },
      { es: "improvisar", en: "to improvise", example: "Tuve que improvisar la actividad." },
      { es: "la lista", en: "the attendance list", example: "No firmé la lista a tiempo." },
      { es: "el retraso", en: "the delay", example: "Debido al retraso, perdí la reunión." },
      { es: "avisar", en: "to notify", example: "Avisé a la oficina por teléfono." },
    ],
    dialogue: {
      title: "Veinte minutos tarde",
      situation: "En la sala de maestros, durante el recreo",
      lines: [
        { speaker: "A", es: "Como llegué veinte minutos tarde, perdí la reunión de la mañana.", en: "Since I arrived twenty minutes late, I missed the morning meeting." },
        { speaker: "B", es: "¿Y tus estudiantes?", en: "And your students?" },
        { speaker: "A", es: "Por eso mis estudiantes esperaban en el pasillo. Por eso la directora me miró raro al entrar.", en: "That's why my students were waiting in the hallway. That's why the principal gave me a look when I walked in." },
        { speaker: "B", es: "Uf. ¿Qué hiciste en clase?", en: "Oof. What did you do in class?" },
        { speaker: "A", es: "Así que empecé directo con el repaso. Así que cancelé la prueba sorpresa.", en: "So I started straight with review. So I canceled the pop quiz." },
        { speaker: "B", es: "Buena decisión.", en: "Good call." },
        { speaker: "A", es: "Debido al caos de la mañana, olvidé el café. Gracias a la secretaria, avisaron a la directora.", en: "Due to the morning chaos, I forgot my coffee. Thanks to the secretary, they notified the principal." },
        { speaker: "B", es: "Gracias a ti por contarme ayer. Hoy te traigo uno.", en: "Thanks to you for telling me yesterday. Today I'm bringing you one." },
      ],
    },
  },
  {
    day: 136,
    themeEs: "El transporte",
    storyTitle: "La avería del coche",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el Uber", en: "Uber", example: "Pedí un Uber para llegar." },
      { es: "el autobús", en: "the bus", example: "Descargué la app del autobús." },
      { es: "la parada", en: "the bus stop", example: "Esperar en la parada es horrible con frío." },
      { es: "la hora pico", en: "rush hour", example: "En hora pico el Uber costó el doble." },
      { es: "el pase", en: "the pass", example: "Tengo un pase de autobús del distrito." },
    ],
    dialogue: {
      title: "Sin coche",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "Esta semana vivo en Uber y autobús.", en: "This week I'm living on Uber and the bus." },
        { speaker: "B", es: "¿Cuánto te está costando?", en: "How much is it costing you?" },
        { speaker: "A", es: "Como no tengo coche, dependo del Uber y del bus. Por eso esta semana gasto más en transporte.", en: "Since I don't have a car, I depend on Uber and the bus. That's why I'm spending more on transportation this week." },
        { speaker: "B", es: "¿Y el tiempo?", en: "And time?" },
        { speaker: "A", es: "Debido al transporte público, llego más cansada. Debido a la hora pico, el Uber costó el doble ayer.", en: "Due to public transit, I arrive more tired. Due to rush hour, the Uber cost double yesterday." },
        { speaker: "B", es: "Eso no es sostenible.", en: "That's not sustainable." },
        { speaker: "A", es: "Así que descargué la app del autobús otra vez. Gracias al pase del distrito, ahorro algo.", en: "So I downloaded the bus app again. Thanks to the district pass, I save a bit." },
        { speaker: "B", es: "Los martes podemos ir juntas. Así que acordemos eso.", en: "On Tuesdays we can go together. So let's agree on that." },
      ],
    },
  },
  {
    day: 137,
    themeEs: "El taller",
    storyTitle: "La avería del coche",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "el taller", en: "the repair shop", example: "El coche está en el taller." },
      { es: "el alternador", en: "the alternator", example: "Hay que cambiar el alternador." },
      { es: "la factura", en: "the bill", example: "La factura supera los quinientos." },
      { es: "el presupuesto", en: "the estimate", example: "Pedí presupuesto en otro taller." },
      { es: "el plan de pagos", en: "payment plan", example: "Gracias al plan de pagos, puedo respirar." },
    ],
    dialogue: {
      title: "La mala noticia",
      situation: "En la sala de maestros, después de clases",
      lines: [
        { speaker: "A", es: "Llamé al taller. No es buena noticia.", en: "I called the shop. It's not good news." },
        { speaker: "B", es: "¿Cuánto?", en: "How much?" },
        { speaker: "A", es: "Debido al alternador, la factura supera los quinientos. Como ignoré la luz del motor, empeoró.", en: "Due to the alternator, the bill is over five hundred. Since I ignored the check engine light, it got worse." },
        { speaker: "B", es: "Ay, Marlana.", en: "Oh, Marlana." },
        { speaker: "A", es: "Por eso esta semana como arroz con lo que hay. Por eso no voy a salir el fin de semana.", en: "That's why this week I'm eating rice with whatever's around. That's why I'm not going out this weekend." },
        { speaker: "B", es: "¿Vas a arreglarlo?", en: "Are you going to fix it?" },
        { speaker: "A", es: "Así que aprobé la reparación. Gracias al plan de pagos, puedo respirar un poco.", en: "So I approved the repair. Thanks to the payment plan, I can breathe a little." },
        { speaker: "B", es: "Gracias al mecánico de confianza, ¿no te cobró de más?", en: "Thanks to your trusted mechanic, he didn't overcharge you?" },
        { speaker: "A", es: "Exacto. Gracias a mi tío, lo encontré hace años.", en: "Exactly. Thanks to my uncle, I found him years ago." },
      ],
    },
  },
  {
    day: 138,
    themeEs: "Priya al rescate",
    storyTitle: "La avería del coche",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el favor", en: "the favor", example: "Le debo un favor grande." },
      { es: "compartir", en: "to share", example: "Compartimos el viaje los días de lluvia." },
      { es: "la gasolina", en: "the gas", example: "Le pagué la gasolina del miércoles." },
      { es: "el desvío", en: "the detour", example: "El desvío no le cuesta mucho." },
      { es: "la paciencia", en: "patience", example: "Gracias a su paciencia, sobreviví." },
    ],
    dialogue: {
      title: "Los rides de Priya",
      situation: "En la sala de maestros, un jueves lluvioso",
      lines: [
        { speaker: "A", es: "Priya, no sé qué haría sin ti esta semana.", en: "Priya, I don't know what I'd do without you this week." },
        { speaker: "B", es: "Para eso están las amigas. ¿Cómo vas?", en: "That's what friends are for. How are you doing?" },
        { speaker: "A", es: "Como vives cerca, el desvío no te cuesta mucho. Gracias a tus rides, no falté ni un día.", en: "Since you live nearby, the detour doesn't cost you much. Thanks to your rides, I didn't miss a single day." },
        { speaker: "B", es: "Me alegra.", en: "I'm glad." },
        { speaker: "A", es: "Debido a la lluvia de hoy, tu ayuda fue clave. Por eso le compré el café toda la semana.", en: "Due to today's rain, your help was key. That's why I bought you coffee all week." },
        { speaker: "B", es: "No hacía falta, pero gracias.", en: "You didn't have to, but thanks." },
        { speaker: "A", es: "Así que acordamos compartir el viaje los días de lluvia. Así que te debo un favor grande.", en: "So we agreed to share the ride on rainy days. So I owe you a big favor." },
        { speaker: "B", es: "Gracias a su compañía, el viaje se siente menos pesado, ¿no?", en: "Thanks to your company, the ride feels less heavy, right?" },
        { speaker: "A", es: "Mucho menos. Gracias a su paciencia, sobreviví la semana.", en: "Much less. Thanks to your patience, I survived the week." },
      ],
    },
  },
  {
    day: 139,
    themeEs: "Arreglado",
    storyTitle: "La avería del coche",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "arreglado/a", en: "fixed", example: "Ya está arreglado." },
      { es: "el fondo de emergencia", en: "emergency fund", example: "Usé el fondo de emergencia." },
      { es: "respirar", en: "to breathe (sigh of relief)", example: "Hoy respiré al encender el motor." },
      { es: "la rutina", en: "the routine", example: "Volví a mi rutina normal." },
      { es: "la lección", en: "the lesson", example: "Aprendí la lección." },
    ],
    dialogue: {
      title: "El coche vuelve",
      situation: "En la sala de maestros, el lunes siguiente",
      lines: [
        { speaker: "A", es: "¡Recogí el coche el sábado!", en: "I picked up the car on Saturday!" },
        { speaker: "B", es: "¡Por fin! ¿Funciona bien?", en: "Finally! Does it work well?" },
        { speaker: "A", es: "Como ya está arreglado, puedo olvidar el caos. Por eso hoy respiré al encender el motor.", en: "Since it's fixed now, I can forget the chaos. That's why I breathed a sigh of relief when I started the engine today." },
        { speaker: "B", es: "¿Qué aprendiste?", en: "What did you learn?" },
        { speaker: "A", es: "Por eso voy a revisar la luz del tablero enseguida. Como aprendí la lección, reviso el aceite cada mes.", en: "That's why I'm going to check the dashboard light right away. Since I learned my lesson, I check the oil every month." },
        { speaker: "B", es: "Bien. ¿Y yo?", en: "Good. And me?" },
        { speaker: "A", es: "Así que le llevé un pastel el lunes. Gracias a todos los que me ayudaron, sobreviví.", en: "So I brought you a cake on Monday. Thanks to everyone who helped me, I survived." },
        { speaker: "B", es: "El pastel era innecesario pero delicioso.", en: "The cake was unnecessary but delicious." },
        { speaker: "A", es: "Debido al gasto, cancelé el viaje de otoño. Pero gracias al fondo de emergencia, no me endeudé.", en: "Due to the expense, I canceled my fall trip. But thanks to the emergency fund, I didn't go into debt." },
      ],
    },
  },
  {
    day: 140,
    themeEs: "Repaso: por eso",
    isRecap: true,
    vocab: [
      { es: "la cadena", en: "the chain (of events)", example: "Fue una cadena de causas y efectos." },
      { es: "la consecuencia", en: "the consequence", example: "Por eso marca la consecuencia." },
      { es: "sobrevivir", en: "to survive", example: "Sobreviví la semana." },
      { es: "endeudarse", en: "to go into debt", example: "No me endeudé." },
      { es: "contar de nuevo", en: "to tell again", example: "Cuéntame todo de nuevo." },
    ],
    dialogue: {
      title: "La semana del coche",
      situation: "En la sala de maestros, contándole a una colega que estuvo ausente",
      lines: [
        { speaker: "A", es: "¿Te contó Priya lo del coche de Marlana?", en: "Did Priya tell you about Marlana's car?" },
        { speaker: "B", es: "No, cuéntame tú.", en: "No, you tell me." },
        { speaker: "A", es: "Como ignoró la luz del motor, el coche se paró en la autopista. Por eso tuvo una semana entera de transporte caótico.", en: "Since she ignored the check engine light, the car died on the highway. That's why she had a whole week of chaotic transportation." },
        { speaker: "B", es: "¿Y cómo resolvió?", en: "And how did she solve it?" },
        { speaker: "A", es: "Así que pidió Uber, bus y favores. Debido a la avería, gastó más de lo planeado. Gracias a Priya, al seguro y al mecánico, lo resolvió.", en: "So she took Uber, bus, and favors. Due to the breakdown, she spent more than planned. Thanks to Priya, insurance, and the mechanic, she solved it." },
        { speaker: "B", es: "Qué semana.", en: "What a week." },
        { speaker: "A", es: "Por eso no ignora las luces del tablero nunca más. En resumen: causa, efecto, amigas y fondo de emergencia.", en: "That's why she never ignores dashboard lights again. In summary: cause, effect, friends, and emergency fund." },
        { speaker: "B", es: "Lección aprendida.", en: "Lesson learned." },
      ],
    },
  },
];
