import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 13 draft — "Mi otoño en Pues" (days 176–182).
 *
 * Append to content/readings/otono.ts. themeEs must match week13-prompts.ts.
 * Six installments (176–181) + season repaso on 182 (isRecap: true).
 * Day 181 = day-90-equivalent season retrospective.
 */
export const week13ReadingDays: ReadingDay[] = [
  {
    day: 176,
    themeEs: "El comienzo",
    storyTitle: "Mi otoño en Pues",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "hace dos meses", en: "two months ago", example: "Hace dos meses empezó otoño." },
      { es: "resumir", en: "to summarize", example: "Aprendí a resumir historias." },
      { es: "el cuaderno", en: "the notebook", example: "Mi cuaderno tiene noventa páginas." },
      { es: "el hilo", en: "the thread", example: "Seguir el hilo era la meta." },
      { es: "empezar de nuevo", en: "to start again", example: "Otoño era empezar de nuevo." },
    ],
    dialogue: {
      title: "Hace dos meses",
      situation: "En la sala de maestros, reflexionando sobre el inicio del otoño",
      lines: [
        { speaker: "A", es: "Priya, hace dos meses apenas sabía resumir una noticia.", en: "Priya, two months ago I barely knew how to summarize a news item." },
        { speaker: "B", es: "¿Y ahora?", en: "And now?" },
        { speaker: "A", es: "Ahora puedo contarte la historia de Naty en cinco frases.", en: "Now I can tell you Naty's story in five sentences." },
        { speaker: "B", es: "Eso es un cambio grande.", en: "That's a big change." },
        { speaker: "A", es: "Hace dos meses, «Trata de…» me sonaba raro. Ahora lo uso sin pensar.", en: "Two months ago, \"It's about…\" sounded strange to me. Now I use it without thinking." },
        { speaker: "B", es: "¿Qué más recuerdas del inicio?", en: "What else do you remember from the start?" },
        { speaker: "A", es: "Lo más difícil fue confiar en que podía retell algo que acababa de leer.", en: "The hardest part was trusting I could retell something I'd just read." },
        { speaker: "B", es: "Y mira — ya llevas noventa días de otoño.", en: "And look — you already have ninety fall days." },
      ],
    },
  },
  {
    day: 177,
    themeEs: "Las historias",
    storyTitle: "Mi otoño en Pues",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "seguir la historia", en: "to follow the story", example: "Seguí la historia de Naty seis días." },
      { es: "la feria", en: "the fair", example: "La feria escolar fue enorme." },
      { es: "el artículo", en: "the article", example: "Reaccioné al artículo sobre bilingüismo." },
      { es: "el regreso", en: "the return", example: "El regreso de Diego me emocionó." },
      { es: "retomar el hilo", en: "to pick up the thread", example: "Retomé el hilo cada semana." },
    ],
    dialogue: {
      title: "Las historias que seguí",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "B", es: "Si tuvieras que nombrar las historias de otoño, ¿cuáles serían?", en: "If you had to name the fall stories, which would they be?" },
        { speaker: "A", es: "Naty se muda, la feria escolar, el artículo, Diego… y mi semana de práctica.", en: "Naty moves, the school fair, the article, Diego… and my practice week." },
        { speaker: "B", es: "Muchas.", en: "That's a lot." },
        { speaker: "A", es: "Lo que más me sorprendió fue cuánto recuerdo sin mirar el cuaderno.", en: "What surprised me most was how much I remember without looking at the notebook." },
        { speaker: "B", es: "¿Cuál te marcó más?", en: "Which one marked you most?" },
        { speaker: "A", es: "El artículo — porque reaccioné de verdad. Y Diego — porque seguí el hilo seis días.", en: "The article — because I really reacted. And Diego — because I followed the thread six days." },
        { speaker: "B", es: "Eso es seguir una historia varios días.", en: "That's following a story over several days." },
        { speaker: "A", es: "Exacto. Era la meta de la temporada.", en: "Exactly. That was the season goal." },
      ],
    },
  },
  {
    day: 178,
    themeEs: "Las herramientas",
    storyTitle: "Mi otoño en Pues",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el stem", en: "the stem", example: "Cada semana trae cinco stems." },
      { es: "reportar", en: "to report", example: "Aprendí a reportar lo que dijo alguien." },
      { es: "el conector", en: "the connector", example: "Además y sin embargo son conectores." },
      { es: "contrastar", en: "to contrast", example: "Contrasto ideas con sin embargo." },
      { es: "acumular", en: "to accumulate", example: "Acumulé más de sesenta stems." },
    ],
    dialogue: {
      title: "Lo que aprendí a decir",
      situation: "En la sala de maestros, revisando el cuaderno",
      lines: [
        { speaker: "A", es: "Abrí mi cuaderno y conté los stems. Son más de sesenta.", en: "I opened my notebook and counted the stems. There are more than sixty." },
        { speaker: "B", es: "¿Cuáles usas más?", en: "Which do you use most?" },
        { speaker: "A", es: "Dice que…, Además…, Por eso…, Lo que más me llamó la atención…", en: "\"He says that…,\" \"What's more…,\" \"That's why…,\" \"What caught my attention most…\"" },
        { speaker: "B", es: "Casi un toolkit completo.", en: "Almost a complete toolkit." },
        { speaker: "A", es: "Lo más difícil fue el subjuntivo en Me sorprendió que… — pero ya suena menos raro.", en: "The hardest part was the subjunctive in \"I was surprised that…\" — but it already sounds less strange." },
        { speaker: "B", es: "¿Y lo que más te sorprendió?", en: "And what surprised you most?" },
        { speaker: "A", es: "Lo que más me sorprendió fue que los conectores me salen solos — sin traducir.", en: "What surprised me most was that connectors come out on their own — without translating." },
        { speaker: "B", es: "Eso es progreso real.", en: "That's real progress." },
      ],
    },
  },
  {
    day: 179,
    themeEs: "Leer y reaccionar",
    storyTitle: "Mi otoño en Pues",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la lectura", en: "reading", example: "La lectura se volvió hábito." },
      { es: "el hábito", en: "the habit", example: "Tengo el hábito de leer antes de dormir." },
      { es: "reaccionar", en: "to react", example: "Reacciono a lo que leo." },
      { es: "retell", en: "to retell", example: "Retell es contar otra vez." },
      { es: "conectar", en: "to connect", example: "Conecto la lectura con la conversación." },
    ],
    dialogue: {
      title: "Leer ya no es extra",
      situation: "En la sala de maestros, al final del día",
      lines: [
        { speaker: "A", es: "En verano, la lectura era un extra antes de dormir. En otoño, es el centro.", en: "In summer, reading was an extra before bed. In fall, it's the center." },
        { speaker: "B", es: "¿Qué cambió?", en: "What changed?" },
        { speaker: "A", es: "Ahora leo y después hablo de lo que leí — con stems de verdad.", en: "Now I read and then I talk about what I read — with real stems." },
        { speaker: "B", es: "Como con el artículo.", en: "Like with the article." },
        { speaker: "A", es: "Exacto. Hace dos meses no sabía decir Me dio gusto leer que…", en: "Exactly. Two months ago I didn't know how to say \"I was glad to read that…\"" },
        { speaker: "B", es: "¿Y ahora?", en: "And now?" },
        { speaker: "A", es: "Ahora puedo leer, resumir, reaccionar y seguir la historia — todo en español.", en: "Now I can read, summarize, react, and follow the story — all in Spanish." },
        { speaker: "B", es: "Eso es otoño completo.", en: "That's fall complete." },
      ],
    },
  },
  {
    day: 180,
    themeEs: "Un minuto",
    storyTitle: "Mi otoño en Pues",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "sostener", en: "to sustain", example: "Sostengo un minuto de conversación." },
      { es: "el monólogo", en: "the monologue", example: "Practico un monólogo estructurado." },
      { es: "tropezar", en: "to stumble", example: "Tropiezo pero sigo." },
      { es: "la estructura", en: "the structure", example: "La estructura me salva." },
      { es: "sin pánico", en: "without panic", example: "Hablo sin pánico más seguido." },
    ],
    dialogue: {
      title: "Cuarenta y cinco segundos",
      situation: "En la sala de maestros — Marlana cuenta su progreso del minuto",
      lines: [
        { speaker: "B", es: "¿Llegaste al minuto entero?", en: "Did you make it to the full minute?" },
        { speaker: "A", es: "Todavía no — cuarenta y cinco segundos. Pero hace dos meses eran diez.", en: "Not yet — forty-five seconds. But two months ago it was ten." },
        { speaker: "B", es: "Eso es cuatro veces más.", en: "That's four times more." },
        { speaker: "A", es: "Lo primero es la estructura: Hoy quiero hablar de…, Hay tres cosas…, Para terminar…", en: "The first thing is structure: \"Today I want to talk about…,\" \"There are three things…,\" \"To finish…\"" },
        { speaker: "A", es: "Lo segundo es no parar cuando tropiezo.", en: "The second thing is not stopping when I stumble." },
        { speaker: "B", es: "¿Lo más difícil?", en: "The hardest part?" },
        { speaker: "A", es: "Lo más difícil fue hablar sola frente al espejo. Lo que más me sorprendió fue que funciona.", en: "The hardest part was talking alone in front of the mirror. What surprised me most was that it works." },
        { speaker: "B", es: "El próximo paso es el minuto completo.", en: "The next step is the full minute." },
      ],
    },
  },
  {
    day: 181,
    themeEs: "Mi otoño en Pues",
    storyTitle: "Mi otoño en Pues",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "hace dos meses", en: "two months ago", example: "Hace dos meses empezó otoño." },
      { es: "ahora puedo", en: "now I can", example: "Ahora puedo seguir una historia varios días." },
      { es: "lo más difícil fue", en: "the hardest part was", example: "Lo más difícil fue confiar en mis retells." },
      { es: "lo que más me sorprendió fue", en: "what surprised me most was", example: "Lo que más me sorprendió fue disfrutarlo." },
      { es: "el próximo paso es", en: "the next step is", example: "El próximo paso es invierno." },
    ],
    dialogue: {
      title: "Noventa días de otoño",
      situation: "Marlana sola, en la cama, repasando su temporada antes de dormir",
      lines: [
        { speaker: "A", es: "Hace dos meses no sabía retell lo que leía. Solo leía y ya.", en: "Two months ago I didn't know how to retell what I read. I just read and that was it." },
        { speaker: "B", es: "¿Y ahora?", en: "And now?" },
        { speaker: "A", es: "Ahora puedo resumir, reportar, conectar, reaccionar y seguir una historia varios días.", en: "Now I can summarize, report, connect, react, and follow a story over several days." },
        { speaker: "B", es: "Eso era la meta de otoño.", en: "That was fall's goal." },
        { speaker: "A", es: "Lo más difícil fue confiar en que entendía suficiente para hablar. Lo más difícil fue no rendirme en las semanas flojas.", en: "The hardest part was trusting I understood enough to speak. The hardest part was not giving up during the slow weeks." },
        { speaker: "A", es: "Lo que más me sorprendió fue cuánto recuerdo de las historias — Naty, la feria, Diego, el artículo.", en: "What surprised me most was how much I remember from the stories — Naty, the fair, Diego, the article." },
        { speaker: "B", es: "El próximo paso es invierno. Pero esta noche descansas — te lo ganaste.", en: "The next step is winter. But tonight you rest — you earned it." },
      ],
    },
  },
  {
    day: 182,
    themeEs: "Repaso: mi otoño",
    isRecap: true,
    vocab: [
      { es: "el repaso", en: "the review", example: "Hago un repaso de noventa días." },
      { es: "en un minuto", en: "in one minute", example: "Cuento mi otoño en un minuto." },
      { es: "retomar", en: "to pick back up", example: "Retomo cada historia." },
      { es: "el arco", en: "the arc", example: "El arco de la temporada." },
      { es: "seguir el hilo", en: "to follow the thread", example: "Seguí el hilo noventa días." },
    ],
    dialogue: {
      title: "Mi otoño en un minuto",
      situation: "En la sala de maestros — Marlana hace el repaso de temporada para Priya",
      lines: [
        { speaker: "B", es: "Último día de otoño. Cuéntame todo en un minuto.", en: "Last day of fall. Tell me everything in one minute." },
        { speaker: "A", es: "Hace dos meses empecé a resumir con Trata de… y La idea principal es que…", en: "Two months ago I started summarizing with \"It's about…\" and \"The main idea is that…\"" },
        { speaker: "A", es: "Seguí historias: Naty se muda, la feria, el artículo, Diego. Leí, retellé, reaccioné.", en: "I followed stories: Naty moves, the fair, the article, Diego. I read, retold, reacted." },
        { speaker: "B", es: "Sigue.", en: "Keep going." },
        { speaker: "A", es: "Ahora puedo conectar ideas, contrastar, opinar sobre lo leído y hablar casi un minuto sin parar.", en: "Now I can connect ideas, contrast, react to what I read, and speak almost a minute without stopping." },
        { speaker: "A", es: "Lo más difícil fue confiar. Lo que más me sorprendió fue disfrutarlo. El próximo paso es invierno.", en: "The hardest part was trusting. What surprised me most was enjoying it. The next step is winter." },
        { speaker: "B", es: "Eso fue un minuto de otoño. Completo.", en: "That was one minute of fall. Complete." },
        { speaker: "A", es: "Noventa y un días. Una temporada entera. Mía.", en: "Ninety-one days. A whole season. Mine." },
      ],
    },
  },
];
