import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 5 draft — "La feria escolar" (days 120–126).
 *
 * Append to content/readings/otono.ts. themeEs must match week5-prompts.ts.
 * Six installments (120–125) + fresh recap on 126 (isRecap: true).
 */
export const week5ReadingDays: ReadingDay[] = [
  {
    day: 120,
    themeEs: "La idea",
    storyTitle: "La feria escolar",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la feria", en: "the fair", example: "Quieren organizar una feria multicultural." },
      { es: "la diversidad", en: "diversity", example: "La idea es celebrar la diversidad del colegio." },
      { es: "proponer", en: "to propose", example: "La directora lo propuso en la reunión." },
      { es: "participar", en: "to participate", example: "Quieren que las familias participen." },
      { es: "el presupuesto", en: "the budget", example: "Necesitamos un presupuesto pequeño." },
    ],
    dialogue: {
      title: "¿Ya escuchaste?",
      situation: "En la sala de maestros, antes de la primera campana",
      lines: [
        { speaker: "A", es: "Priya, ¿ya escuchaste lo de la feria multicultural?", en: "Priya, did you already hear about the multicultural fair?" },
        { speaker: "B", es: "No, cuéntame. ¿De qué se trata?", en: "No, tell me. What's it about?" },
        { speaker: "A", es: "La directora lo propuso ayer. La idea es celebrar la diversidad del colegio.", en: "The principal proposed it yesterday. The idea is to celebrate the school's diversity." },
        { speaker: "B", es: "Qué bonito. ¿Cuándo sería?", en: "How nice. When would it be?" },
        { speaker: "A", es: "En la primavera. Además, quieren que las familias participen con comida y música.", en: "In the spring. What's more, they want families to participate with food and music." },
        { speaker: "B", es: "Aparte de eso, ¿cada clase tendría un puesto?", en: "On top of that, would each class have a booth?" },
        { speaker: "A", es: "Exacto. No solo van a comer, sino también van a aprender de otras culturas.", en: "Exactly. They're not only going to eat, but also learn about other cultures." },
        { speaker: "B", es: "Encima, la directora dijo que puede conseguir fondos. Suena prometedor.", en: "On top of that, the principal said she can get funding. Sounds promising." },
      ],
    },
  },
  {
    day: 121,
    themeEs: "La comida",
    storyTitle: "La feria escolar",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "las arepas", en: "arepas", example: "Una mamá va a traer arepas de Venezuela." },
      { es: "las empanadas", en: "empanadas", example: "También van empanadas colombianas." },
      { es: "los ingredientes", en: "the ingredients", example: "Necesitamos etiquetas con los ingredientes." },
      { es: "las alergias", en: "allergies", example: "Hay que pensar en las alergias." },
      { es: "donar", en: "to donate", example: "El restaurante quiere donar postres." },
    ],
    dialogue: {
      title: "El menú del mundo",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "¿Cómo va lo de la comida para la feria?", en: "How's the food planning for the fair going?" },
        { speaker: "B", es: "Increíble. Ya hay familias de seis países diferentes.", en: "Incredible. There are already families from six different countries." },
        { speaker: "A", es: "Además, una mamá va a traer arepas de Venezuela. También van empanadas colombianas.", en: "What's more, one mom is going to bring arepas from Venezuela. Colombian empanadas are coming too." },
        { speaker: "B", es: "¿Y la familia de Lin?", en: "And Lin's family?" },
        { speaker: "A", es: "Van a preparar dumplings. Aparte de eso, cada plato lleva una tarjeta con el país.", en: "They're going to make dumplings. Besides that, each dish gets a card with its country." },
        { speaker: "B", es: "Muy bien pensado. ¿Y las alergias?", en: "Well thought out. And allergies?" },
        { speaker: "A", es: "También hay que pensar en las alergias. No solo van a probar comida nueva, sino también escuchar historias.", en: "We also have to think about allergies. They're not only going to try new food, but also hear stories." },
        { speaker: "B", es: "Encima, el restaurante de la esquina quiere donar postres. Esto va a ser inolvidable.", en: "On top of that, the corner restaurant wants to donate desserts. This is going to be unforgettable." },
      ],
    },
  },
  {
    day: 122,
    themeEs: "La música",
    storyTitle: "La feria escolar",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "en vivo", en: "live", example: "Un papá va a tocar la guitarra en vivo." },
      { es: "el escenario", en: "the stage", example: "Reservaron el escenario del auditorio." },
      { es: "ensayar", en: "to rehearse", example: "Necesitamos ensayar el viernes." },
      { es: "el folklore", en: "folk dance/music", example: "Unas niñas quieren bailar folklore." },
      { es: "los altavoces", en: "the speakers", example: "Hay que pedir prestados los altavoces." },
    ],
    dialogue: {
      title: "El programa musical",
      situation: "En la sala de maestros, después de clases",
      lines: [
        { speaker: "A", es: "¿Ya viste el programa de música para la feria?", en: "Did you see the music program for the fair yet?" },
        { speaker: "B", es: "Todavía no. ¿Qué hay?", en: "Not yet. What's on it?" },
        { speaker: "A", es: "Además, un papá va a tocar la guitarra en vivo. También hay un grupo de estudiantes que canta en español.", en: "What's more, a dad is going to play guitar live. There's also a group of students who sing in Spanish." },
        { speaker: "B", es: "Qué bien. ¿Solo eso?", en: "That's great. Just that?" },
        { speaker: "A", es: "Aparte de eso, unas niñas quieren bailar folklore. También van a poner una lista de canciones entre presentaciones.", en: "On top of that, some girls want to dance folk dances. They're also going to play a playlist between performances." },
        { speaker: "B", es: "¿Y el equipo de sonido?", en: "And the sound equipment?" },
        { speaker: "A", es: "También hay que pedir prestados los altavoces. No solo van a escuchar música, sino también van a tocar algunos.", en: "We also need to borrow speakers. They're not only going to listen to music, but also play some themselves." },
        { speaker: "B", es: "Encima, una exalumna ofreció tocar el violín. El auditorio va a estar lleno.", en: "On top of that, a former student offered to play violin. The auditorium is going to be packed." },
      ],
    },
  },
  {
    day: 123,
    themeEs: "Los voluntarios",
    storyTitle: "La feria escolar",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "apuntarse", en: "to sign up", example: "El señor Ortiz se apuntó para montar mesas." },
      { es: "el turno", en: "the shift", example: "Hay turnos de mañana y de tarde." },
      { es: "montar", en: "to set up", example: "Alguien tiene que montar las mesas." },
      { es: "recoger", en: "to pick up, collect", example: "Hay que recoger las sillas al final." },
      { es: "ofrecerse", en: "to volunteer, offer oneself", example: "Diez familias se ofrecieron a ayudar." },
    ],
    dialogue: {
      title: "La lista de voluntarios",
      situation: "En la sala de maestros, revisando un papel en la pared",
      lines: [
        { speaker: "A", es: "Mira la lista de voluntarios. Casi se llenó en un día.", en: "Look at the volunteer list. It almost filled up in one day." },
        { speaker: "B", es: "¿Quién se apuntó?", en: "Who signed up?" },
        { speaker: "A", es: "Además, el señor Ortiz se apuntó para montar las mesas. También me anoté para la configuración temprano.", en: "What's more, Mr. Ortiz signed up to set up the tables. I also signed up for early setup." },
        { speaker: "B", es: "Yo puedo ayudar en la mesa de postres. ¿Qué falta?", en: "I can help at the dessert table. What's still missing?" },
        { speaker: "A", es: "Aparte de eso, alguien tiene que recoger las sillas al final. También necesitamos alguien para la entrada.", en: "Besides that, someone has to pick up the chairs at the end. We also need someone for the entrance." },
        { speaker: "B", es: "Pregunto en la reunión de mañana. ¿Solo maestros?", en: "I'll ask at tomorrow's meeting. Just teachers?" },
        { speaker: "A", es: "No solo ayudan los maestros, sino también el personal de la oficina. Encima, diez familias se ofrecieron a ayudar.", en: "Not only teachers help, but office staff too. On top of that, ten families offered to help." },
        { speaker: "B", es: "Con tanta gente, la feria va a salir redonda.", en: "With so many people, the fair is going to turn out great." },
      ],
    },
  },
  {
    day: 124,
    themeEs: "Los estudiantes",
    storyTitle: "La feria escolar",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el póster", en: "the poster", example: "Están diseñando pósters en varios idiomas." },
      { es: "presentar", en: "to present", example: "Varios van a presentar sus países." },
      { es: "la bandera", en: "the flag", example: "Pintaron banderas para el pasillo." },
      { es: "convencer", en: "to convince", example: "Convencieron a sus papás de cocinar." },
      { es: "orgulloso/a", en: "proud", example: "Están emocionados y muy orgullosos." },
    ],
    dialogue: {
      title: "La emoción en el aula",
      situation: "En la sala de maestros, calificando tareas",
      lines: [
        { speaker: "A", es: "Mis estudiantes no hablan de otra cosa que de la feria.", en: "My students don't talk about anything but the fair." },
        { speaker: "B", es: "Los míos tampoco. ¿Qué están haciendo?", en: "Mine neither. What are they doing?" },
        { speaker: "A", es: "Además, están haciendo un mapa grande del mundo. También diseñan pósters con frases en varios idiomas.", en: "What's more, they're making a big world map. They're also designing posters with phrases in several languages." },
        { speaker: "B", es: "Qué lindo. ¿Solo decoración?", en: "How nice. Just decorations?" },
        { speaker: "A", es: "Aparte de eso, varios van a presentar sus países en mini charlas. También practican en clase todos los días.", en: "Besides that, several are going to present their countries in mini talks. They also practice in class every day." },
        { speaker: "B", es: "Se nota la emoción.", en: "You can feel the excitement." },
        { speaker: "A", es: "No solo están emocionados, sino también muy orgullosos. Encima, unos convencieron a sus papás de cocinar.", en: "They're not only excited, but also very proud. On top of that, some convinced their parents to cook." },
        { speaker: "B", es: "Los estudiantes son el motor de todo esto.", en: "The students are the engine behind all of this." },
      ],
    },
  },
  {
    day: 125,
    themeEs: "El gran día",
    storyTitle: "La feria escolar",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "la asistencia", en: "attendance, turnout", example: "Vinieron más familias de las que esperábamos." },
      { es: "improvisado/a", en: "impromptu", example: "Hubo un grupo de baile improvisado." },
      { es: "recaudar", en: "to raise (funds)", example: "Recaudamos más fondos de los que pensábamos." },
      { es: "emotivo/a", en: "moving, emotional", example: "Fue divertido y muy emotivo." },
      { es: "la tradición", en: "tradition", example: "La directora quiere hacerlo tradición." },
    ],
    dialogue: {
      title: "Sábado de feria",
      situation: "En la sala de maestros, el lunes después de la feria",
      lines: [
        { speaker: "A", es: "Uf, qué fin de semana. ¿Estuviste en la feria?", en: "Wow, what a weekend. Were you at the fair?" },
        { speaker: "B", es: "Sí, todo el sábado. ¿Cómo te pareció?", en: "Yes, all Saturday. What did you think?" },
        { speaker: "A", es: "Increíble. Además, vinieron más familias de las que esperábamos. También hubo una sorpresa: un grupo de baile improvisado.", en: "Incredible. What's more, more families came than we expected. There was also a surprise: an improvised dance group." },
        { speaker: "B", es: "Vi eso. El patio estaba llenísimo.", en: "I saw that. The courtyard was packed." },
        { speaker: "A", es: "Aparte de eso, el patio se sintió como un festival pequeño. No solo funcionó la comida, sino también la música en vivo.", en: "On top of that, the courtyard felt like a little festival. The food not only worked, but the live music did too." },
        { speaker: "B", es: "¿Y la directora?", en: "And the principal?" },
        { speaker: "A", es: "Encima, la alcaldesa apareció sin avisar. Y la directora dijo que quiere repetirlo el año que viene.", en: "On top of that, the mayor showed up unannounced. And the principal said she wants to repeat it next year." },
        { speaker: "B", es: "Merecido. Fue el mejor sábado del colegio en mucho tiempo.", en: "Well deserved. It was the school's best Saturday in a long time." },
      ],
    },
  },
  {
    day: 126,
    themeEs: "Repaso: además",
    isRecap: true,
    vocab: [
      { es: "sumar", en: "to add", example: "Cada semana se sumó algo nuevo." },
      { es: "involucrarse", en: "to get involved", example: "Las familias se involucraron más de lo esperado." },
      { es: "unido/a", en: "united", example: "El colegio se sintió más unido." },
      { es: "construir", en: "to build", example: "Construimos la diversidad juntos." },
      { es: "repetir", en: "to repeat", example: "Quieren repetirlo el año que viene." },
    ],
    dialogue: {
      title: "El resumen de la feria",
      situation: "En la sala de maestros, una semana después del gran día",
      lines: [
        { speaker: "A", es: "Oye, ¿puedes resumirme toda la feria? Pasó tanto en pocas semanas.", en: "Hey, can you sum up the whole fair for me? So much happened in just a few weeks." },
        { speaker: "B", es: "Claro. Empezó con una idea en una reunión y terminó lleno de gente el sábado.", en: "Sure. It started with an idea at a meeting and ended packed with people on Saturday." },
        { speaker: "A", es: "¿Y qué se fue sumando?", en: "And what kept getting added?" },
        { speaker: "B", es: "Además, pasamos de una idea suelta a una feria llena de gente. También hubo comida de cinco continentes y música en vivo.", en: "What's more, we went from a loose idea to a fair full of people. There was also food from five continents and live music." },
        { speaker: "A", es: "Suena enorme.", en: "That sounds huge." },
        { speaker: "B", es: "Aparte de eso, el colegio se sintió más unido después. No solo celebramos la diversidad, sino también la construimos juntos.", en: "On top of that, the school felt more united afterward. We not only celebrated diversity, but also built it together." },
        { speaker: "A", es: "¿Y qué pasó el sábado?", en: "And what happened on Saturday?" },
        { speaker: "B", es: "Encima, la directora ya quiere hacerlo tradición. Los estudiantes preguntan cuándo es la próxima.", en: "On top of that, the principal already wants to make it a tradition. The students keep asking when the next one is." },
      ],
    },
  },
];
