import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 3 draft — Speak prompts (days 106–112).
 * Coupled to content/drafts/week3-frames.ts and week3-readings.ts.
 * Story: "La entrevista de Marcos"
 */
export const week3SpeakDays: SpeakDay[] = [
  {
    day: 106,
    themeEs: "Antes de la entrevista",
    themeEn: "Before the interview",
    missionEs: "Cuenta lo que Marcos te dijo la víspera de su entrevista.",
    missionEn: "Tell what Marcos said to you the day before his interview.",
    line: "A veces lo más difícil es contar lo que alguien te contó.",
    lineEn: "Sometimes the hardest part is retelling what someone told you.",
    prompts: [
      {
        id: "d106-dijo-que",
        frameStem: "Dijo que…",
        english: "He said he was very nervous.",
        spanish: "Dijo que estaba muy nervioso.",
        situationLabel: "Contándole a Priya",
        why: "*Estaba* (imperfect) replaces *está* when you report past speech — the classic tense shift after *dijo que*.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "very", es: "muy" },
          { en: "nervous", es: "nervioso" },
        ],
      },
      {
        id: "d106-me-conto",
        frameStem: "Me contó que…",
        english: "He told me he hadn't slept well last night.",
        spanish: "Me contó que no había dormido bien anoche.",
        situationLabel: "La noche anterior",
        why: "*No había dormido* is past perfect — one step back from *no durmió* in direct speech.",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "hadn't slept", es: "no había dormido" },
          { en: "well", es: "bien" },
          { en: "last night", es: "anoche" },
        ],
      },
      {
        id: "d106-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned the scholarship covered the full university.",
        spanish: "Mencionó que la beca cubría la universidad completa.",
        situationLabel: "Lo que estaba en juego",
        why: "*Mencionó que* is a softer reporting verb — good for details that came up in passing.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "scholarship", es: "la beca" },
          { en: "covered", es: "cubría" },
          { en: "university", es: "la universidad" },
        ],
      },
      {
        id: "d106-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if I thought he was ready.",
        spanish: "Preguntó si yo creía que estaba listo.",
        situationLabel: "Buscando tu opinión",
        why: "*Preguntó si* reports a yes/no question — *¿Crees que estoy listo?* becomes *preguntó si creía que estaba listo*.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "thought", es: "creía" },
          { en: "ready", es: "listo" },
        ],
      },
      {
        id: "d106-le-dijo",
        frameStem: "Le dijo que…",
        english: "His mom told him to trust everything he'd prepared.",
        spanish: "Le dijo que confiara en todo lo que había preparado.",
        situationLabel: "Lo que le dijo su mamá",
        why: "*Confiara* is imperfect subjunctive — the form you'd use after past reporting of advice (*confía* → *confiara*).",
        wordHints: [
          { en: "told him", es: "le dijo" },
          { en: "trust", es: "confiara" },
          { en: "prepared", es: "había preparado" },
        ],
      },
    ],
  },
  {
    day: 107,
    themeEs: "La entrevista",
    themeEn: "The interview",
    missionEs: "Cuenta cómo le fue a Marcos en la entrevista.",
    missionEn: "Tell how Marcos's interview went.",
    line: "Después de una entrevista, siempre hay una historia que contar.",
    lineEn: "After an interview, there's always a story to tell.",
    prompts: [
      {
        id: "d107-dijo-que",
        frameStem: "Dijo que…",
        english: "He said the interview had lasted about half an hour.",
        spanish: "Dijo que la entrevista había durado como media hora.",
        situationLabel: "Justo después de la entrevista",
        why: "*Había durado* (past perfect) reports something that was already finished when he spoke to you.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "interview", es: "la entrevista" },
          { en: "had lasted", es: "había durado" },
          { en: "half an hour", es: "media hora" },
        ],
      },
      {
        id: "d107-me-conto",
        frameStem: "Me contó que…",
        english: "He told me an evaluator asked him why he wanted the scholarship.",
        spanish: "Me contó que un evaluador le preguntó por qué quería la beca.",
        situationLabel: "La pregunta más difícil",
        why: "*Me contó que* invites a longer, more personal detail than *dijo que* alone.",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "evaluator", es: "un evaluador" },
          { en: "asked", es: "preguntó" },
          { en: "scholarship", es: "la beca" },
        ],
      },
      {
        id: "d107-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned they asked about his grades.",
        spanish: "Mencionó que le preguntaron sobre sus notas.",
        situationLabel: "Lo que le preguntaron",
        why: "*Le preguntaron* keeps the preterite — in everyday speech, finished events often stay in preterite even inside *dijo que*.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "asked", es: "preguntaron" },
          { en: "grades", es: "sus notas" },
        ],
      },
      {
        id: "d107-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if he'd answered the hardest question well.",
        spanish: "Preguntó si había respondido bien a la pregunta más difícil.",
        situationLabel: "Queriendo tu opinión",
        why: "*Había respondido* shifts the preterite *respondí* back one step in reported speech.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "had answered", es: "había respondido" },
          { en: "hardest", es: "más difícil" },
          { en: "question", es: "la pregunta" },
        ],
      },
      {
        id: "d107-le-dijo",
        frameStem: "Le dijo que…",
        english: "An evaluator told him he'd made a good impression.",
        spanish: "Le dijo que había hecho una buena impresión.",
        situationLabel: "Lo que le dijeron al salir",
        why: "*Le dijo que* works for anyone who spoke to Marcos — here, one of the evaluators at the end.",
        wordHints: [
          { en: "told him", es: "le dijo" },
          { en: "had made", es: "había hecho" },
          { en: "good impression", es: "una buena impresión" },
        ],
      },
    ],
  },
  {
    day: 108,
    themeEs: "La espera",
    themeEn: "The wait",
    missionEs: "Cuenta cómo describió Marcos la espera de la respuesta.",
    missionEn: "Tell how Marcos described waiting for the answer.",
    line: "Esperar también se cuenta en pasado — dijo que, me contó que.",
    lineEn: "Waiting gets told in the past too — he said that, he told me that.",
    prompts: [
      {
        id: "d108-dijo-que",
        frameStem: "Dijo que…",
        english: "He said he checked his email every day.",
        spanish: "Dijo que revisaba el correo todos los días.",
        situationLabel: "Durante la espera",
        why: "*Revisaba* (imperfect) reports a repeated habit — *reviso el correo* becomes *revisaba* in past reported speech.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "checked", es: "revisaba" },
          { en: "email", es: "el correo" },
          { en: "every day", es: "todos los días" },
        ],
      },
      {
        id: "d108-me-conto",
        frameStem: "Me contó que…",
        english: "He told me he'd dreamed about the acceptance letter.",
        spanish: "Me contó que había soñado con la carta de aceptación.",
        situationLabel: "Lo que no podía evitar",
        why: "*Había soñado* is past perfect — the dream happened before he told you about it.",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "had dreamed", es: "había soñado" },
          { en: "acceptance letter", es: "la carta de aceptación" },
        ],
      },
      {
        id: "d108-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned some friends had already gotten answers.",
        spanish: "Mencionó que algunos amigos ya habían recibido respuestas.",
        situationLabel: "Comparándose con otros",
        why: "*Ya habían recibido* — past perfect plural — shows others finished waiting before he did.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "friends", es: "amigos" },
          { en: "had gotten", es: "habían recibido" },
          { en: "answers", es: "respuestas" },
        ],
      },
      {
        id: "d108-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if it was normal to wait this long.",
        spanish: "Preguntó si era normal esperar tanto.",
        situationLabel: "Buscando tranquilidad",
        why: "*Era normal* shifts present *es normal* to imperfect in reported speech.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "normal", es: "era normal" },
          { en: "wait", es: "esperar" },
          { en: "this long", es: "tanto" },
        ],
      },
      {
        id: "d108-le-dijo",
        frameStem: "Le dijo que…",
        english: "His mom told him not to obsess over his email.",
        spanish: "Le dijo que no se obsesionara con el correo.",
        situationLabel: "Consejo de su mamá",
        why: "*No se obsesionara* — imperfect subjunctive — reports a gentle command in the past.",
        wordHints: [
          { en: "told him", es: "le dijo" },
          { en: "not to obsess", es: "no se obsesionara" },
          { en: "email", es: "el correo" },
        ],
      },
    ],
  },
  {
    day: 109,
    themeEs: "La respuesta",
    themeEn: "The answer",
    missionEs: "Cuenta la noticia que Marcos recibió esa mañana.",
    missionEn: "Tell the news Marcos got that morning.",
    line: "Las buenas noticias suenan aún mejor en estilo indirecto.",
    lineEn: "Good news sounds even better in reported speech.",
    prompts: [
      {
        id: "d109-dijo-que",
        frameStem: "Dijo que…",
        english: "He said they'd given him the scholarship.",
        spanish: "Dijo que le habían dado la beca.",
        situationLabel: "La mañana de la noticia",
        why: "*Le habían dado* — past perfect — reports something that happened before he spoke to you.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "had given", es: "habían dado" },
          { en: "scholarship", es: "la beca" },
        ],
      },
      {
        id: "d109-me-conto",
        frameStem: "Me contó que…",
        english: "He told me he shouted when he read the first line.",
        spanish: "Me contó que gritó cuando leyó la primera línea.",
        situationLabel: "El momento exacto",
        why: "*Gritó* stays in preterite — a single completed action often doesn't shift in casual reported speech.",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "shouted", es: "gritó" },
          { en: "read", es: "leyó" },
          { en: "first line", es: "la primera línea" },
        ],
      },
      {
        id: "d109-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned the letter also included books and a laptop.",
        spanish: "Mencionó que también incluía libros y una laptop.",
        situationLabel: "Los detalles de la beca",
        why: "*Incluía* (imperfect) describes what the letter contained — background detail, not a single event.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "included", es: "incluía" },
          { en: "books", es: "libros" },
          { en: "laptop", es: "una laptop" },
        ],
      },
      {
        id: "d109-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if this meant he was going to his dream university.",
        spanish: "Preguntó si esto significaba que iba a la universidad de sus sueños.",
        situationLabel: "Casi sin creerlo",
        why: "*Significaba* and *iba* both shift to imperfect — the dream becoming real, reported in the past.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "meant", es: "significaba" },
          { en: "dream university", es: "la universidad de sus sueños" },
        ],
      },
      {
        id: "d109-le-dijo",
        frameStem: "Le dijo que…",
        english: "His mom told him it was the happiest day of her life.",
        spanish: "Le dijo que era el día más feliz de su vida.",
        situationLabel: "Lo que le dijo su mamá",
        why: "*Era el día más feliz de su vida* — his mom's words, reported through Marcos — is pure past reported speech.",
        wordHints: [
          { en: "told her", es: "le dijo" },
          { en: "happiest day", es: "el día más feliz" },
          { en: "her life", es: "de su vida" },
        ],
      },
    ],
  },
  {
    day: 110,
    themeEs: "Contándole a su mamá",
    themeEn: "Telling his mom",
    missionEs: "Cuenta la conversación que Marcos tuvo con su mamá.",
    missionEn: "Tell about the conversation Marcos had with his mom.",
    line: "Una buena noticia crece cuando se la cuentas a quien más importa.",
    lineEn: "Good news grows when you tell the person who matters most.",
    prompts: [
      {
        id: "d110-dijo-que",
        frameStem: "Dijo que…",
        english: "He said he'd called his mom as soon as he got the letter.",
        spanish: "Dijo que le había llamado a su mamá en cuanto recibió la carta.",
        situationLabel: "Lo primero que hizo",
        why: "*Le había llamado* — past perfect — the call happened right after receiving the letter, before he told you.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "had called", es: "le había llamado" },
          { en: "mom", es: "su mamá" },
          { en: "got the letter", es: "recibió la carta" },
        ],
      },
      {
        id: "d110-me-conto",
        frameStem: "Me contó que…",
        english: "He told me his mom thought it was a joke at first.",
        spanish: "Me contó que su mamá pensó que era una broma.",
        situationLabel: "La reacción de su mamá",
        why: "*Pensó que era* — preterite + imperfect — a completed reaction (*pensó*) about ongoing disbelief (*era*).",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "mom", es: "su mamá" },
          { en: "thought", es: "pensó" },
          { en: "joke", es: "una broma" },
        ],
      },
      {
        id: "d110-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned his grandmother cried when she found out too.",
        spanish: "Mencionó que su abuela también lloró cuando se enteró.",
        situationLabel: "Toda la familia",
        why: "*Se enteró* — to find out — is the natural verb when news reaches someone.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "grandmother", es: "su abuela" },
          { en: "cried", es: "lloró" },
          { en: "found out", es: "se enteró" },
        ],
      },
      {
        id: "d110-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if he could invite his mom to the school someday.",
        spanish: "Preguntó si podía invitar a su mamá a la escuela algún día.",
        situationLabel: "Un deseo nuevo",
        why: "*Podía* replaces *puedo* in reported speech — *¿Puedo invitar…?* → *preguntó si podía invitar…*.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "could invite", es: "podía invitar" },
          { en: "mom", es: "su mamá" },
          { en: "school", es: "la escuela" },
        ],
      },
      {
        id: "d110-le-dijo",
        frameStem: "Le dijo que…",
        english: "He told his mom the scholarship covered four years of university.",
        spanish: "Le dijo que la beca cubría cuatro años de universidad.",
        situationLabel: "Compartiendo los detalles",
        why: "This is the classic *Le dijo que* shape — Marcos reporting what he told his *mamá*.",
        wordHints: [
          { en: "told her", es: "le dijo" },
          { en: "scholarship", es: "la beca" },
          { en: "covered", es: "cubría" },
          { en: "four years", es: "cuatro años" },
        ],
      },
    ],
  },
  {
    day: 111,
    themeEs: "El plan",
    themeEn: "The plan",
    missionEs: "Cuenta los planes que Marcos te compartió para la universidad.",
    missionEn: "Tell the plans Marcos shared with you for university.",
    line: "Una beca es noticia; un plan es el siguiente capítulo.",
    lineEn: "A scholarship is news; a plan is the next chapter.",
    prompts: [
      {
        id: "d111-dijo-que",
        frameStem: "Dijo que…",
        english: "He said he was going to study civil engineering.",
        spanish: "Dijo que iba a estudiar ingeniería civil.",
        situationLabel: "Su carrera",
        why: "*Iba a estudiar* shifts *voy a estudiar* to imperfect — future plans reported in the past.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "going to study", es: "iba a estudiar" },
          { en: "civil engineering", es: "ingeniería civil" },
        ],
      },
      {
        id: "d111-me-conto",
        frameStem: "Me contó que…",
        english: "He told me he wanted to save a little for emergencies.",
        spanish: "Me contó que quería guardar un poco para emergencias.",
        situationLabel: "Pensando en el futuro",
        why: "*Quería* (imperfect) reports an ongoing intention — *quiero guardar* → *quería guardar*.",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "wanted", es: "quería" },
          { en: "save", es: "guardar" },
          { en: "emergencies", es: "emergencias" },
        ],
      },
      {
        id: "d111-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned the program started in August.",
        spanish: "Mencionó que el programa empezaba en agosto.",
        situationLabel: "El calendario",
        why: "*Empezaba* (imperfect) describes a scheduled date from the letter — background information.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "program", es: "el programa" },
          { en: "started", es: "empezaba" },
          { en: "august", es: "agosto" },
        ],
      },
      {
        id: "d111-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if he could still come practice Spanish after graduating.",
        spanish: "Preguntó si todavía podía venir a practicar español después de graduarse.",
        situationLabel: "No quiere perder el contacto",
        why: "*Podía venir* — imperfect — keeps the open-ended future feeling in reported speech.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "could still come", es: "todavía podía venir" },
          { en: "practice", es: "practicar" },
          { en: "graduating", es: "graduarse" },
        ],
      },
      {
        id: "d111-le-dijo",
        frameStem: "Le dijo que…",
        english: "An advisor told him he had to confirm enrollment before June.",
        spanish: "Le dijo que tenía que confirmar su matrícula antes de junio.",
        situationLabel: "Los siguientes pasos",
        why: "*Tenía que* shifts *tiene que* to imperfect — an obligation reported in the past.",
        wordHints: [
          { en: "told him", es: "le dijo" },
          { en: "had to", es: "tenía que" },
          { en: "confirm", es: "confirmar" },
          { en: "enrollment", es: "su matrícula" },
          { en: "june", es: "junio" },
        ],
      },
    ],
  },
  {
    day: 112,
    themeEs: "Repaso: dijo que",
    themeEn: "Review: he said that",
    missionEs: "Resume toda la historia de Marcos en cinco frases de estilo indirecto.",
    missionEn: "Sum up Marcos's whole story in five reported-speech sentences.",
    line: "Una semana entera cabe en cinco frases, si sabes a quién contárselas.",
    lineEn: "A whole week fits into five sentences, if you know who told whom.",
    prompts: [
      {
        id: "d112-dijo-que",
        frameStem: "Dijo que…",
        english: "He said it all started with flashcards and a lot of nerves.",
        spanish: "Dijo que todo había empezado con tarjetas y muchos nervios.",
        situationLabel: "El comienzo",
        why: "*Había empezado* — past perfect — looks back to the very beginning of the arc from where he stands now.",
        wordHints: [
          { en: "said", es: "dijo" },
          { en: "had started", es: "había empezado" },
          { en: "flashcards", es: "tarjetas" },
          { en: "nerves", es: "nervios" },
        ],
      },
      {
        id: "d112-me-conto",
        frameStem: "Me contó que…",
        english: "He told me he shouted when he saw the word congratulations in the email.",
        spanish: "Me contó que gritó cuando vio la palabra felicitaciones en el correo.",
        situationLabel: "El momento clave",
        why: "The repaso day reuses the week's stems with fresh sentences — this one captures the turning point.",
        wordHints: [
          { en: "told me", es: "me contó" },
          { en: "shouted", es: "gritó" },
          { en: "congratulations", es: "felicitaciones" },
          { en: "email", es: "el correo" },
        ],
      },
      {
        id: "d112-menciono",
        frameStem: "Mencionó que…",
        english: "He mentioned the scholarship covered four full years.",
        spanish: "Mencionó que la beca cubría cuatro años completos.",
        situationLabel: "Lo que incluía",
        why: "*Cubría* ties back to day 106 and 110 — the same detail, now part of the whole summary.",
        wordHints: [
          { en: "mentioned", es: "mencionó" },
          { en: "scholarship", es: "la beca" },
          { en: "covered", es: "cubría" },
          { en: "four years", es: "cuatro años" },
        ],
      },
      {
        id: "d112-pregunto-si",
        frameStem: "Preguntó si…",
        english: "He asked if I remembered how nervous he was at the beginning.",
        spanish: "Preguntó si yo recordaba lo nervioso que estaba al principio.",
        situationLabel: "Mirando atrás",
        why: "*Recordaba* and *estaba* — both imperfect — frame the whole story as something you're both looking back on.",
        wordHints: [
          { en: "asked if", es: "preguntó si" },
          { en: "remembered", es: "recordaba" },
          { en: "nervous", es: "nervioso" },
          { en: "beginning", es: "al principio" },
        ],
      },
      {
        id: "d112-le-dijo",
        frameStem: "Le dijo que…",
        english: "He told his mom the whole effort had been worth it.",
        spanish: "Le dijo que todo el esfuerzo había valido la pena.",
        situationLabel: "El cierre de la historia",
        why: "Five prompts, five beats — this last one closes the arc with what Marcos told the person who believed in him first.",
        wordHints: [
          { en: "told her", es: "le dijo" },
          { en: "effort", es: "el esfuerzo" },
          { en: "had been worth it", es: "había valido la pena" },
        ],
      },
    ],
  },
];
