import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 11 draft — "Seguir la historia" (days 162–168).
 *
 * Append to content/prompts/otono.ts. prompt.spanish must stay verbatim with
 * week11-frames.ts examples for the matching frameStem.
 */
export const week11SpeakDays: SpeakDay[] = [
  {
    day: 162,
    themeEs: "El regreso",
    themeEn: "The return",
    missionEs: "Retoma la historia de Diego — cuéntale a Priya que volvió.",
    missionEn: "Pick up Diego's story — tell Priya he's back.",
    line: "Una historia que sigues necesita un «la última vez» para arrancar.",
    lineEn: "A story you follow needs a \"the last time\" to get started.",
    prompts: [
      {
        id: "d162-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time we saw him, he didn't know if he'd stay in Chile.",
        spanish: "La última vez que lo vimos, no sabía si se quedaría en Chile.",
        situationLabel: "El punto de partida",
        why: "*La última vez* anchors serialized retelling — where the story was when you last checked in.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "saw him", es: "lo vimos" },
          { en: "stay", es: "se quedaría" },
          { en: "chile", es: "en chile" },
        ],
      },
      {
        id: "d162-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, Mr. Ortiz covered his classes.",
        spanish: "Mientras tanto, el señor Ortiz cubrió sus clases.",
        situationLabel: "Lo que pasó aquí",
        why: "*Mientras tanto* covers the parallel track — what happened here while he was away.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "covered", es: "cubrió" },
          { en: "classes", es: "sus clases" },
        ],
      },
      {
        id: "d162-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The next day, he showed up in the teachers' lounge.",
        spanish: "Al día siguiente, apareció en la sala de maestros.",
        situationLabel: "El regreso",
        why: "*Al día siguiente* moves the timeline forward — the beat after the last time you saw him.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "showed up", es: "apareció" },
          { en: "teachers' lounge", es: "sala de maestros" },
        ],
      },
      {
        id: "d162-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out he came back with a beard and a full backpack.",
        spanish: "Ahora resulta que regresó con barba y una mochila llena.",
        situationLabel: "La sorpresa",
        why: "*Ahora resulta que* delivers the update that changes what you thought you knew.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "came back", es: "regresó" },
          { en: "beard", es: "barba" },
          { en: "backpack", es: "mochila" },
        ],
      },
      {
        id: "d162-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, the atmosphere in the lounge improved.",
        spanish: "Desde entonces, el ambiente en la sala mejoró.",
        situationLabel: "El cambio",
        why: "*Desde entonces* carries the story forward from the turning point to now.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "atmosphere", es: "el ambiente" },
          { en: "improved", es: "mejoró" },
        ],
      },
    ],
  },
  {
    day: 163,
    themeEs: "Lo que extrañábamos",
    themeEn: "What we missed",
    missionEs: "Cuenta qué extrañaban de Diego mientras estaba fuera.",
    missionEn: "Tell what you missed about Diego while he was away.",
    line: "Seguir una historia también es recordar lo que faltó.",
    lineEn: "Following a story also means remembering what was missing.",
    prompts: [
      {
        id: "d163-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time he made coffee, he left cookies for everyone.",
        spanish: "La última vez que hizo café, dejó galletas para todos.",
        situationLabel: "El recuerdo",
        why: "*La última vez que hizo café* — a specific last moment that makes the absence concrete.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "made coffee", es: "hizo café" },
          { en: "cookies", es: "galletas" },
          { en: "everyone", es: "todos" },
        ],
      },
      {
        id: "d163-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, Monday meetings were a little more boring.",
        spanish: "Mientras tanto, las reuniones de lunes eran más aburridas.",
        situationLabel: "Sin Diego",
        why: "*Eran más aburridas* — imperfect for ongoing state while he was gone.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "meetings", es: "reuniones" },
          { en: "boring", es: "aburridas" },
        ],
      },
      {
        id: "d163-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The day after he left, Mr. Ortiz took his shift.",
        spanish: "Al día siguiente de irse, el señor Ortiz tomó su turno.",
        situationLabel: "La transición",
        why: "*Al día siguiente de irse* — the immediate consequence of his departure.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "left", es: "irse" },
          { en: "shift", es: "turno" },
        ],
      },
      {
        id: "d163-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out he offered to take back the coffee shift.",
        spanish: "Ahora resulta que se ofreció para retomar el turno de café.",
        situationLabel: "Diego vuelve",
        why: "*Se ofreció para retomar* — volunteered to pick back up — the circle closing.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "offered", es: "se ofreció" },
          { en: "take back", es: "retomar" },
          { en: "coffee shift", es: "turno de café" },
        ],
      },
      {
        id: "d163-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, Mr. Ortiz makes the coffee — and it's not the same.",
        spanish: "Desde entonces, el señor Ortiz hace el café — y no es lo mismo.",
        situationLabel: "Lo que cambió",
        why: "*No es lo mismo* — the honest gap between substitute and the real thing.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "makes coffee", es: "hace el café" },
          { en: "not the same", es: "no es lo mismo" },
        ],
      },
    ],
  },
  {
    day: 164,
    themeEs: "La primera clase",
    themeEn: "The first class",
    missionEs: "Cuenta cómo fue la primera clase de Diego de vuelta.",
    missionEn: "Tell how Diego's first class back went.",
    line: "Al día siguiente de volver — y ya está en clase.",
    lineEn: "The day after returning — and he's already in class.",
    prompts: [
      {
        id: "d164-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time he taught, his students sent him off with letters.",
        spanish: "La última vez que enseñó, sus estudiantes lo despidieron con cartas.",
        situationLabel: "La despedida",
        why: "*Lo despidieron con cartas* — the farewell that sets up the return.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "taught", es: "enseñó" },
          { en: "sent off", es: "despidieron" },
          { en: "letters", es: "cartas" },
        ],
      },
      {
        id: "d164-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, Mr. Ortiz left him notes on what changed.",
        spanish: "Mientras tanto, el señor Ortiz le dejó notas de lo que cambió.",
        situationLabel: "Ponerse al día",
        why: "*Le dejó notas* — the bridge that helps Diego catch up on what he missed.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "left notes", es: "dejó notas" },
          { en: "changed", es: "cambió" },
        ],
      },
      {
        id: "d164-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The day after arriving, he was already in front of his students.",
        spanish: "Al día siguiente de llegar, ya estaba frente a sus estudiantes.",
        situationLabel: "De vuelta al salón",
        why: "*Ya estaba frente a* — imperfect for the scene when Priya found out — he was already there.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "arriving", es: "llegar" },
          { en: "in front of", es: "frente a" },
          { en: "students", es: "estudiantes" },
        ],
      },
      {
        id: "d164-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out he adapts faster than we thought.",
        spanish: "Ahora resulta que se adapta más rápido de lo que pensábamos.",
        situationLabel: "La sorpresa",
        why: "*Más rápido de lo que pensábamos* — the update that exceeds expectations.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "adapts", es: "se adapta" },
          { en: "faster", es: "más rápido" },
          { en: "thought", es: "pensábamos" },
        ],
      },
      {
        id: "d164-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, he's been catching up on the curriculum.",
        spanish: "Desde entonces, se está poniendo al día con el plan.",
        situationLabel: "El proceso",
        why: "*Se está poniendo al día* — present progressive — ongoing catch-up since day one back.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "catching up", es: "poniéndose al día" },
          { en: "curriculum", es: "el plan" },
        ],
      },
    ],
  },
  {
    day: 165,
    themeEs: "Historias de Chile",
    themeEn: "Stories from Chile",
    missionEs: "Retoma las historias que Diego cuenta del extranjero.",
    missionEn: "Pick up the stories Diego tells from abroad.",
    line: "Cada almuerzo, un capítulo nuevo de Chile.",
    lineEn: "Every lunch, a new chapter from Chile.",
    prompts: [
      {
        id: "d165-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time we ate together, he didn't stop telling anecdotes.",
        spanish: "La última vez que comimos juntos, no paró de contar anécdotas.",
        situationLabel: "El almuerzo",
        why: "*No paró de contar* — couldn't stop telling — captures Diego mid-story.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "ate together", es: "comimos juntos" },
          { en: "anecdotes", es: "anécdotas" },
          { en: "didn't stop", es: "no paró" },
        ],
      },
      {
        id: "d165-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, he was buying fruit at the central market.",
        spanish: "Mientras tanto, él compraba fruta en el mercado central.",
        situationLabel: "En Chile",
        why: "*Compraba* — imperfect — what he was doing over there while you were here.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "buying", es: "compraba" },
          { en: "fruit", es: "fruta" },
          { en: "market", es: "mercado central" },
        ],
      },
      {
        id: "d165-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The next day, he brought more photos of the ocean.",
        spanish: "Al día siguiente, trajo más fotos del océano.",
        situationLabel: "Más historias",
        why: "*Trajo más fotos* — preterite — each day back adds another chapter.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "brought", es: "trajo" },
          { en: "photos", es: "fotos" },
          { en: "ocean", es: "océano" },
        ],
      },
      {
        id: "d165-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out he imitates the Chilean accent at every lunch.",
        spanish: "Ahora resulta que imita el acento chileno en cada almuerzo.",
        situationLabel: "El acento",
        why: "*Imita el acento chileno* — the running joke that keeps the Chile thread alive.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "imitates", es: "imita" },
          { en: "accent", es: "acento chileno" },
          { en: "every lunch", es: "cada almuerzo" },
        ],
      },
      {
        id: "d165-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, lunch lasts twice as long.",
        spanish: "Desde entonces, el almuerzo dura el doble.",
        situationLabel: "El nuevo ritmo",
        why: "*Dura el doble* — a concrete measure of how Diego changed daily life.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "lunch", es: "almuerzo" },
          { en: "twice as long", es: "el doble" },
        ],
      },
    ],
  },
  {
    day: 166,
    themeEs: "El cambio",
    themeEn: "The change",
    missionEs: "Cuenta cómo regresó Diego — diferente pero igual.",
    missionEn: "Tell how Diego came back — different but the same.",
    line: "Seis meses fuera cambian a alguien. La historia sigue.",
    lineEn: "Six months away changes someone. The story continues.",
    prompts: [
      {
        id: "d166-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time, he wasn't talking about school exchanges.",
        spanish: "La última vez, no hablaba de intercambios escolares.",
        situationLabel: "Antes de irse",
        why: "*No hablaba de* — imperfect — what wasn't true then that is true now.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "wasn't talking", es: "no hablaba" },
          { en: "exchanges", es: "intercambios escolares" },
        ],
      },
      {
        id: "d166-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, he was teaching at a school in Santiago.",
        spanish: "Mientras tanto, enseñaba en un colegio de Santiago.",
        situationLabel: "Allá",
        why: "*Enseñaba en un colegio de Santiago* — the parallel life that changed him.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "teaching", es: "enseñaba" },
          { en: "school", es: "colegio" },
          { en: "santiago", es: "de santiago" },
        ],
      },
      {
        id: "d166-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The day after the proposal, the principal said she supported it.",
        spanish: "Al día siguiente de la propuesta, la directora dijo que lo apoyaba.",
        situationLabel: "La respuesta",
        why: "*Dijo que lo apoyaba* — reported speech — how the story moved after Diego's big idea.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "proposal", es: "propuesta" },
          { en: "supported", es: "apoyaba" },
          { en: "principal", es: "directora" },
        ],
      },
      {
        id: "d166-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out he proposed a school exchange with Santiago.",
        spanish: "Ahora resulta que propuso un intercambio escolar con Santiago.",
        situationLabel: "La propuesta",
        why: "*Propuso un intercambio escolar* — the plot twist that changes the team's future.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "proposed", es: "propuso" },
          { en: "exchange", es: "intercambio escolar" },
          { en: "santiago", es: "con santiago" },
        ],
      },
      {
        id: "d166-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, he's been enthusiastic about the exchange.",
        spanish: "Desde entonces, está entusiasmado con el intercambio.",
        situationLabel: "La energía nueva",
        why: "*Está entusiasmado con* — the ongoing state since the proposal landed.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "enthusiastic", es: "entusiasmado" },
          { en: "exchange", es: "intercambio" },
        ],
      },
    ],
  },
  {
    day: 167,
    themeEs: "La bienvenida",
    themeEn: "The welcome",
    missionEs: "Cuenta la cena de bienvenida y cómo cerró la semana.",
    missionEn: "Tell about the welcome dinner and how the week closed.",
    line: "Toda historia que sigues merece un final bonito.",
    lineEn: "Every story you follow deserves a good ending.",
    prompts: [
      {
        id: "d167-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time we celebrated with Diego, it was his farewell in May.",
        spanish: "La última vez que celebramos con Diego, fue su despedida en mayo.",
        situationLabel: "El contraste",
        why: "*Fue su despedida* — preterite — pairing the last celebration with this week's welcome.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "celebrated", es: "celebramos" },
          { en: "farewell", es: "despedida" },
          { en: "may", es: "mayo" },
        ],
      },
      {
        id: "d167-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, we organized the dinner all week.",
        spanish: "Mientras tanto, organizamos la cena toda la semana.",
        situationLabel: "La preparación",
        why: "*Organizamos la cena toda la semana* — the build-up before the welcome.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "organized", es: "organizamos" },
          { en: "dinner", es: "cena" },
          { en: "all week", es: "toda la semana" },
        ],
      },
      {
        id: "d167-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The next day, he resumed his coffee shift without anyone asking.",
        spanish: "Al día siguiente, retomó su turno de café sin que nadie se lo pidiera.",
        situationLabel: "Diego otra vez",
        why: "*Sin que nadie se lo pidiera* — without anyone asking — the detail that says he's truly back.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "resumed", es: "retomó" },
          { en: "coffee shift", es: "turno de café" },
          { en: "without asking", es: "sin que nadie se lo pidiera" },
        ],
      },
      {
        id: "d167-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out Monday mornings smell like good coffee again.",
        spanish: "Ahora resulta que el lunes por la mañana vuelve a oler a café bueno.",
        situationLabel: "La normalidad",
        why: "*Vuelve a oler a café bueno* — sensory detail that marks the story's happy close.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "monday morning", es: "lunes por la mañana" },
          { en: "smell", es: "oler" },
          { en: "good coffee", es: "café bueno" },
        ],
      },
      {
        id: "d167-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, the team feels complete again.",
        spanish: "Desde entonces, el equipo se siente completo otra vez.",
        situationLabel: "El cierre",
        why: "*Se siente completo otra vez* — the emotional resolution of a six-month arc.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "team", es: "equipo" },
          { en: "complete", es: "completo" },
          { en: "again", es: "otra vez" },
        ],
      },
    ],
  },
  {
    day: 168,
    themeEs: "Repaso: seguir la historia",
    themeEn: "Review: following the story",
    missionEs: "Reconstruye toda la historia de Diego con los cinco conectores.",
    missionEn: "Rebuild Diego's whole story using all five connectors.",
    line: "Seis meses, cinco conectores, una historia. Eso es seguir el hilo.",
    lineEn: "Six months, five connectors, one story. That's following the thread.",
    prompts: [
      {
        id: "d168-ultima-vez",
        frameStem: "La última vez…",
        english: "The last time we saw him, he didn't know if he'd stay in Chile.",
        spanish: "La última vez que lo vimos, no sabía si se quedaría en Chile.",
        situationLabel: "El inicio del repaso",
        why: "Repaso: start the whole arc where the story paused — *la última vez*.",
        wordHints: [
          { en: "last time", es: "la última vez" },
          { en: "saw him", es: "lo vimos" },
          { en: "stay", es: "se quedaría" },
          { en: "chile", es: "en chile" },
        ],
      },
      {
        id: "d168-mientras-tanto",
        frameStem: "Mientras tanto…",
        english: "Meanwhile, we missed his coffee and his jokes.",
        spanish: "Mientras tanto, extrañábamos su café y sus chistes.",
        situationLabel: "Lo que pasó aquí",
        why: "*Extrañábamos* — imperfect — the parallel track while he was abroad.",
        wordHints: [
          { en: "meanwhile", es: "mientras tanto" },
          { en: "missed", es: "extrañábamos" },
          { en: "coffee", es: "café" },
          { en: "jokes", es: "chistes" },
        ],
      },
      {
        id: "d168-al-dia-siguiente",
        frameStem: "Al día siguiente…",
        english: "The day after returning, he was already in class.",
        spanish: "Al día siguiente de volver, ya estaba frente a sus estudiantes.",
        situationLabel: "El regreso",
        why: "*Al día siguiente de volver* — the pivot from absence to presence.",
        wordHints: [
          { en: "next day", es: "al día siguiente" },
          { en: "returning", es: "volver" },
          { en: "in class", es: "en clase" },
        ],
      },
      {
        id: "d168-ahora-resulta",
        frameStem: "Ahora resulta que…",
        english: "Now it turns out he proposed a school exchange.",
        spanish: "Ahora resulta que propuso un intercambio escolar.",
        situationLabel: "El giro",
        why: "*Ahora resulta que propuso* — the update that changed the story's direction.",
        wordHints: [
          { en: "now it turns out", es: "ahora resulta" },
          { en: "proposed", es: "propuso" },
          { en: "exchange", es: "intercambio escolar" },
        ],
      },
      {
        id: "d168-desde-entonces",
        frameStem: "Desde entonces…",
        english: "Since then, the principal supports the exchange.",
        spanish: "Desde entonces, la directora apoya el intercambio.",
        situationLabel: "Lo que sigue",
        why: "Repaso day: five time connectors, one story — close with what continues.",
        wordHints: [
          { en: "since then", es: "desde entonces" },
          { en: "principal", es: "directora" },
          { en: "supports", es: "apoya" },
          { en: "exchange", es: "intercambio" },
        ],
      },
    ],
  },
];
