import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 8 — "Ordenar las ideas" (days 141–147).
 * Story: "La presentación de Priya" — Priya prepares a staff meeting presentation.
 * prompt.spanish must stay verbatim with week8-frames.ts examples for the matching frameStem.
 */
export const week8SpeakDays: SpeakDay[] = [
  {
    day: 141,
    themeEs: "La tarea",
    themeEn: "The assignment",
    missionEs: "Cuenta la tarea de Priya con conectores para ordenar ideas.",
    missionEn: "Tell about Priya's assignment using connectors to organize ideas.",
    line: "Diez minutos delante de todo el personal empiezan con una buena estructura.",
    lineEn: "Ten minutes in front of the whole staff start with good structure.",
    prompts: [
      {
        id: "d141-primero",
        frameStem: "Primero que nada…",
        english: "First of all, I have to present the reading project.",
        spanish: "Primero que nada, tengo que presentar el proyecto de lectura.",
        situationLabel: "Lo primero que importa",
        why: "*Primero que nada* signals the opening move — what comes before any detail.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "present", es: "presentar" },
          { en: "reading project", es: "proyecto de lectura" },
        ],
      },
      {
        id: "d141-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for time, I only have ten minutes.",
        spanish: "En cuanto al tiempo, solo tengo diez minutos.",
        situationLabel: "El límite de tiempo",
        why: "*En cuanto al tiempo* narrows the topic to one dimension — here, the clock.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "time", es: "tiempo" },
          { en: "ten minutes", es: "diez minutos" },
        ],
      },
      {
        id: "d141-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, I want to propose a plan for the quarter.",
        spanish: "Por último, quiero proponer un plan para el trimestre.",
        situationLabel: "El cierre del esquema",
        why: "*Por último* closes the outline — where you land after the data.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "propose", es: "proponer" },
          { en: "quarter", es: "trimestre" },
        ],
      },
      {
        id: "d141-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the data, I have three charts.",
        spanish: "Volviendo a lo de los datos, tengo tres gráficos.",
        situationLabel: "Volver al hilo",
        why: "*Volviendo a lo de los datos* pulls the conversation back after a tangent.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "data", es: "datos" },
          { en: "charts", es: "gráficos" },
        ],
      },
      {
        id: "d141-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, I have to convince the staff in ten minutes.",
        spanish: "En resumen, tengo que convencer al personal en diez minutos.",
        situationLabel: "La tarea en una frase",
        why: "*En resumen* compresses the whole task into one sentence.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "convince", es: "convencer" },
          { en: "staff", es: "personal" },
        ],
      },
    ],
  },
  {
    day: 142,
    themeEs: "La investigación",
    themeEn: "The research",
    missionEs: "Organiza los hallazgos de Priya antes de las diapositivas.",
    missionEn: "Organize Priya's findings before the slides.",
    line: "Los datos hablan solos — si los ordenas antes de presentarlos.",
    lineEn: "The data speaks for itself — if you organize it before presenting.",
    prompts: [
      {
        id: "d142-primero",
        frameStem: "Primero que nada…",
        english: "First of all, I reviewed the reading grades for the quarter.",
        spanish: "Primero que nada, revisé las calificaciones de lectura del trimestre.",
        situationLabel: "Empezar con los números",
        why: "*Revisé las calificaciones* — past tense for research already done.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "reviewed", es: "revisé" },
          { en: "reading grades", es: "calificaciones de lectura" },
        ],
      },
      {
        id: "d142-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for second grade, they went up eight points.",
        spanish: "En cuanto a segundo grado, subieron ocho puntos.",
        situationLabel: "Un grado concreto",
        why: "*En cuanto a segundo grado* zooms into one group within the data.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "second grade", es: "segundo grado" },
          { en: "went up", es: "subieron" },
          { en: "eight points", es: "ocho puntos" },
        ],
      },
      {
        id: "d142-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, the pilot group read twice as many pages.",
        spanish: "Por último, el grupo piloto leyó el doble de páginas.",
        situationLabel: "El dato más fuerte",
        why: "*El doble de páginas* — the stat you save for the end of the research section.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "pilot group", es: "grupo piloto" },
          { en: "twice as many", es: "el doble" },
          { en: "pages", es: "páginas" },
        ],
      },
      {
        id: "d142-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the grades, the trend is positive.",
        spanish: "Volviendo a lo de las calificaciones, la tendencia es positiva.",
        situationLabel: "Retomar el hilo principal",
        why: "*La tendencia es positiva* — the headline after refocusing on grades.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "grades", es: "calificaciones" },
          { en: "trend", es: "tendencia" },
          { en: "positive", es: "positiva" },
        ],
      },
      {
        id: "d142-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, the reading project is working.",
        spanish: "En resumen, el proyecto de lectura está funcionando.",
        situationLabel: "Conclusión de la investigación",
        why: "*Está funcionando* — present tense for a conclusion you're confident about.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "reading project", es: "proyecto de lectura" },
          { en: "working", es: "funcionando" },
        ],
      },
    ],
  },
  {
    day: 143,
    themeEs: "Ensayar",
    themeEn: "Rehearsing",
    missionEs: "Organiza el feedback de la práctica con Marlana en secciones.",
    missionEn: "Organize rehearsal feedback from Marlana into sections.",
    line: "Practicar en voz alta revela lo que las diapositivas esconden.",
    lineEn: "Practicing out loud reveals what the slides hide.",
    prompts: [
      {
        id: "d143-primero",
        frameStem: "Primero que nada…",
        english: "First of all, your introduction hooks well.",
        spanish: "Primero que nada, tu introducción engancha bien.",
        situationLabel: "Lo que funciona",
        why: "*Engancha bien* — the compliment Marlana leads with before the fixes.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "introduction", es: "introducción" },
          { en: "hooks well", es: "engancha bien" },
        ],
      },
      {
        id: "d143-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for the charts, they're clear but there are too many.",
        spanish: "En cuanto a los gráficos, son claros pero hay muchos.",
        situationLabel: "Feedback sobre diapositivas",
        why: "*Son claros pero hay muchos* — praise plus the cut you need to make.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "charts", es: "gráficos" },
          { en: "clear", es: "claros" },
          { en: "too many", es: "muchos" },
        ],
      },
      {
        id: "d143-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, practice the transition to the quarter plan.",
        spanish: "Por último, practica la transición al plan del trimestre.",
        situationLabel: "El último consejo",
        why: "*Practica la transición* — imperative for the move that needs the most work.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "practice", es: "practica" },
          { en: "transition", es: "transición" },
          { en: "quarter plan", es: "plan del trimestre" },
        ],
      },
      {
        id: "d143-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the middle, you shortened that part too much.",
        spanish: "Volviendo a lo del medio, acortaste demasiado esa parte.",
        situationLabel: "Revisar el centro",
        why: "*Acortaste demasiado* — past tense feedback on a section already run.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "middle", es: "medio" },
          { en: "shortened too much", es: "acortaste demasiado" },
        ],
      },
      {
        id: "d143-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, you're doing well — just tighten the ending.",
        spanish: "En resumen, vas muy bien, solo afina el final.",
        situationLabel: "Veredicto de la práctica",
        why: "*Vas muy bien, solo afina el final* — the balanced verdict Marlana gives.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "doing well", es: "vas muy bien" },
          { en: "tighten", es: "afina" },
          { en: "ending", es: "final" },
        ],
      },
    ],
  },
  {
    day: 144,
    themeEs: "La estructura",
    themeEn: "The structure",
    missionEs: "Presenta el esqueleto de tres partes: intro, cuerpo, cierre.",
    missionEn: "Present the three-part skeleton: intro, body, conclusion.",
    line: "Intro, resultados, propuesta — tres bloques, diez minutos.",
    lineEn: "Intro, results, proposal — three blocks, ten minutes.",
    prompts: [
      {
        id: "d144-primero",
        frameStem: "Primero que nada…",
        english: "First of all, I present the reading problem in elementary.",
        spanish: "Primero que nada, presento el problema de lectura en primaria.",
        situationLabel: "La introducción",
        why: "*Presento el problema* — present tense for the script Priya is building.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "present", es: "presento" },
          { en: "reading problem", es: "problema de lectura" },
          { en: "elementary", es: "primaria" },
        ],
      },
      {
        id: "d144-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for the results, I show three charts.",
        spanish: "En cuanto a los resultados, muestro tres gráficos.",
        situationLabel: "El cuerpo",
        why: "*Muestro tres gráficos* — the middle section in one sentence.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "results", es: "resultados" },
          { en: "show", es: "muestro" },
          { en: "charts", es: "gráficos" },
        ],
      },
      {
        id: "d144-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, I propose expanding the program next quarter.",
        spanish: "Por último, propongo expandir el programa al segundo trimestre.",
        situationLabel: "El cierre",
        why: "*Propongo expandir* — the call to action that closes the arc.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "propose", es: "propongo" },
          { en: "expand", es: "expandir" },
          { en: "next quarter", es: "segundo trimestre" },
        ],
      },
      {
        id: "d144-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the initial problem, this data confirms it.",
        spanish: "Volviendo a lo del problema inicial, estos datos lo confirman.",
        situationLabel: "Conectar intro y cuerpo",
        why: "*Estos datos lo confirman* — the callback that ties sections together.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "initial problem", es: "problema inicial" },
          { en: "confirms", es: "confirman" },
          { en: "data", es: "datos" },
        ],
      },
      {
        id: "d144-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, we read more, understand better, and teachers are on board.",
        spanish: "En resumen, leemos más, comprendemos mejor y los maestros están a bordo.",
        situationLabel: "Recapitulación a mitad",
        why: "Three verbs after *en resumen* compress the whole middle into one breath.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "read more", es: "leemos más" },
          { en: "understand better", es: "comprendemos mejor" },
          { en: "on board", es: "a bordo" },
        ],
      },
    ],
  },
  {
    day: 145,
    themeEs: "La noche anterior",
    themeEn: "The night before",
    missionEs: "Ordena los pensamientos de Priya la noche antes de presentar.",
    missionEn: "Organize Priya's thoughts the night before presenting.",
    line: "La noche antes de hablar, la estructura es tu ancla.",
    lineEn: "The night before you speak, structure is your anchor.",
    prompts: [
      {
        id: "d145-primero",
        frameStem: "Primero que nada…",
        english: "First of all, I'll review the introduction one more time.",
        spanish: "Primero que nada, repaso la introducción una vez más.",
        situationLabel: "Checklist de la noche",
        why: "*Repaso la introducción* — present tense for the ritual before bed.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "review", es: "repaso" },
          { en: "introduction", es: "introducción" },
          { en: "one more time", es: "una vez más" },
        ],
      },
      {
        id: "d145-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for nerves, Marlana says it's normal.",
        spanish: "En cuanto a los nervios, Marlana dice que es normal.",
        situationLabel: "Los nervios",
        why: "*Marlana dice que es normal* — the reassurance that belongs in this section.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "nerves", es: "nervios" },
          { en: "normal", es: "normal" },
        ],
      },
      {
        id: "d145-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, I leave my notes by the door.",
        spanish: "Por último, dejo las notas junto a la puerta.",
        situationLabel: "Antes de dormir",
        why: "*Junto a la puerta* — the practical detail that means you're ready.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "leave", es: "dejo" },
          { en: "notes", es: "notas" },
          { en: "by the door", es: "junto a la puerta" },
        ],
      },
      {
        id: "d145-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the practice, it went well yesterday.",
        spanish: "Volviendo a lo de la práctica, salió bien ayer.",
        situationLabel: "Recordar la práctica",
        why: "*Salió bien ayer* — past tense to calm the looping worry.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "practice", es: "práctica" },
          { en: "went well", es: "salió bien" },
          { en: "yesterday", es: "ayer" },
        ],
      },
      {
        id: "d145-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, I'm prepared even though I'm nervous.",
        spanish: "En resumen, estoy preparada aunque nerviosa.",
        situationLabel: "Autoánimo",
        why: "*Preparada aunque nerviosa* — the honest pep talk before sleep.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "prepared", es: "preparada" },
          { en: "nervous", es: "nerviosa" },
        ],
      },
    ],
  },
  {
    day: 146,
    themeEs: "El gran día",
    themeEn: "The big day",
    missionEs: "Cuenta la presentación en vivo con conectores de estructura.",
    missionEn: "Retell the live presentation using structure connectors.",
    line: "Diez minutos frente al personal — y la estructura te sostiene.",
    lineEn: "Ten minutes in front of the staff — and structure holds you up.",
    prompts: [
      {
        id: "d146-primero",
        frameStem: "Primero que nada…",
        english: "First of all, I started with a question to the audience.",
        spanish: "Primero que nada, empecé con una pregunta al público.",
        situationLabel: "Cómo abrió",
        why: "*Empecé con una pregunta* — past tense for how the live talk opened.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "started", es: "empecé" },
          { en: "question", es: "pregunta" },
          { en: "audience", es: "público" },
        ],
      },
      {
        id: "d146-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for the questions, there were two about the budget.",
        spanish: "En cuanto a las preguntas, hubo dos sobre el presupuesto.",
        situationLabel: "La sesión de preguntas",
        why: "*Hubo dos sobre el presupuesto* — the Q&A section in one line.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "questions", es: "preguntas" },
          { en: "budget", es: "presupuesto" },
        ],
      },
      {
        id: "d146-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, the principal applauded and asked for the plan in writing.",
        spanish: "Por último, la directora aplaudió y pidió el plan por escrito.",
        situationLabel: "Cómo cerró",
        why: "*Pidió el plan por escrito* — the win that closes the story.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "principal", es: "directora" },
          { en: "applauded", es: "aplaudió" },
          { en: "in writing", es: "por escrito" },
        ],
      },
      {
        id: "d146-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the budget, I explained the pilot cost little.",
        spanish: "Volviendo a lo del presupuesto, expliqué que el piloto costó poco.",
        situationLabel: "Responder en la Q&A",
        why: "*Explique que el piloto costó poco* — the callback answer during questions.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "budget", es: "presupuesto" },
          { en: "explained", es: "expliqué" },
          { en: "pilot", es: "piloto" },
        ],
      },
      {
        id: "d146-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, it went better than I expected.",
        spanish: "En resumen, salió mejor de lo que esperaba.",
        situationLabel: "Debrief después",
        why: "*Salió mejor de lo que esperaba* — the post-presentation relief.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "went better", es: "salió mejor" },
          { en: "expected", es: "esperaba" },
        ],
      },
    ],
  },
  {
    day: 147,
    themeEs: "Repaso: ordenar las ideas",
    themeEn: "Review: organizing ideas",
    missionEs: "Resume toda la semana de la presentación en cinco frases estructuradas.",
    missionEn: "Summarize the whole presentation week in five structured sentences.",
    line: "Una semana de preparación cabe en cinco conectores, si ordenas bien.",
    lineEn: "A week of prep fits in five connectors, if you organize well.",
    prompts: [
      {
        id: "d147-primero",
        frameStem: "Primero que nada…",
        english: "First of all, the principal asked her to present the reading project.",
        spanish: "Primero que nada, la directora le pidió presentar el proyecto de lectura.",
        situationLabel: "Dónde empezó todo",
        why: "*Le pidió presentar* — the assignment that started the whole arc.",
        wordHints: [
          { en: "first of all", es: "primero que nada" },
          { en: "principal", es: "directora" },
          { en: "present", es: "presentar" },
          { en: "reading project", es: "proyecto de lectura" },
        ],
      },
      {
        id: "d147-en-cuanto",
        frameStem: "En cuanto a…",
        english: "As for the data, she showed a clear improvement in elementary.",
        spanish: "En cuanto a los datos, mostró una mejora clara en primaria.",
        situationLabel: "Lo que presentó",
        why: "*Mostró una mejora clara* — past tense recap of the core content.",
        wordHints: [
          { en: "as for", es: "en cuanto a" },
          { en: "data", es: "datos" },
          { en: "improvement", es: "mejora" },
          { en: "elementary", es: "primaria" },
        ],
      },
      {
        id: "d147-por-ultimo",
        frameStem: "Por último…",
        english: "Lastly, the principal approved expanding the program.",
        spanish: "Por último, la directora aprobó expandir el programa.",
        situationLabel: "El resultado",
        why: "*Aprobó expandir el programa* — the outcome that makes the week worth it.",
        wordHints: [
          { en: "lastly", es: "por último" },
          { en: "approved", es: "aprobó" },
          { en: "expanding", es: "expandir" },
          { en: "program", es: "programa" },
        ],
      },
      {
        id: "d147-volviendo",
        frameStem: "Volviendo a lo de…",
        english: "Getting back to the nerves, they disappeared when she started.",
        spanish: "Volviendo a lo de los nervios, desaparecieron al empezar.",
        situationLabel: "El hilo de la semana",
        why: "*Desaparecieron al empezar* — the thread from night-before worry to live relief.",
        wordHints: [
          { en: "getting back to", es: "volviendo a lo de" },
          { en: "nerves", es: "nervios" },
          { en: "disappeared", es: "desaparecieron" },
          { en: "started", es: "empezar" },
        ],
      },
      {
        id: "d147-en-resumen",
        frameStem: "En resumen…",
        english: "In summary, Priya presented, convinced, and they already have a plan for the quarter.",
        spanish: "En resumen, Priya presentó, convenció y ya tienen plan para el trimestre.",
        situationLabel: "Titular de la semana",
        why: "Three past-tense verbs after *en resumen* compress six days into one headline.",
        wordHints: [
          { en: "in summary", es: "en resumen" },
          { en: "presented", es: "presentó" },
          { en: "convinced", es: "convenció" },
          { en: "quarter plan", es: "plan para el trimestre" },
        ],
      },
    ],
  },
];
