import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 4 draft — "Ya había pasado" (days 113–119).
 *
 * Each day retells that day's installment of "El día del huracán" from
 * content/drafts/week4-readings.ts. `spanish` copied verbatim from
 * content/drafts/week4-frames.ts. Merge into content/prompts/otono.ts when ready.
 */
export const week4SpeakDays: SpeakDay[] = [
  {
    day: 113,
    themeEs: "La advertencia",
    themeEn: "The warning",
    missionEs: "Cuenta lo que ya había pasado antes de que llegara la tormenta.",
    missionEn: "Tell what had already happened before the storm arrived.",
    line: "Antes del huracán, muchas cosas ya habían pasado.",
    lineEn: "Before the hurricane, many things had already happened.",
    prompts: [
      {
        id: "d113-ya-habia",
        frameStem: "Ya había…",
        english: "It had already been raining all morning when the warnings started.",
        spanish: "Ya había llovido toda la mañana cuando empezaron las advertencias.",
        situationLabel: "Contándole a Priya",
        why: "*Había llovido* is the past perfect of *llover* — rain that had already happened before the warnings.",
        wordHints: [
          { en: "already", es: "ya había" },
          { en: "raining", es: "llovido" },
          { en: "morning", es: "toda la mañana" },
          { en: "warnings", es: "las advertencias" },
        ],
      },
      {
        id: "d113-todavia-no",
        frameStem: "Todavía no había…",
        english: "The storm still hadn't started when the sky got dark.",
        spanish: "Todavía no había empezado la tormenta cuando oscureció el cielo.",
        situationLabel: "El cielo se oscurece",
        why: "*Todavía no había* + past participle = something that still hadn't happened yet at that moment.",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "started", es: "empezado" },
          { en: "storm", es: "la tormenta" },
          { en: "got dark", es: "oscureció" },
          { en: "sky", es: "el cielo" },
        ],
      },
      {
        id: "d113-nunca-habia",
        frameStem: "Nunca había…",
        english: "She had never seen the sky that dark at three in the afternoon.",
        spanish: "Nunca había visto el cielo tan oscuro a las tres de la tarde.",
        situationLabel: "Algo nunca visto",
        why: "*Nunca había visto* — had never seen — puts a lifetime first before this one afternoon.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "seen", es: "visto" },
          { en: "sky", es: "el cielo" },
          { en: "dark", es: "oscuro" },
          { en: "afternoon", es: "de la tarde" },
        ],
      },
      {
        id: "d113-antes-habia",
        frameStem: "Antes había…",
        english: "Before that, it had been sunny almost all day.",
        spanish: "Antes había hecho sol casi todo el día.",
        situationLabel: "La mañana normal",
        why: "*Antes había hecho sol* — before, it had been sunny — sets up the contrast with the dark sky.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "sunny", es: "hecho sol" },
          { en: "all day", es: "todo el día" },
        ],
      },
      {
        id: "d113-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then it had already rained a little and the wind was starting.",
        spanish: "Para entonces ya había llovido un poco y el viento empezaba.",
        situationLabel: "El momento de cambio",
        why: "*Para entonces* — by then — marks a turning point: what had already happened right before what came next.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "rained", es: "llovido" },
          { en: "wind", es: "el viento" },
          { en: "starting", es: "empezaba" },
        ],
      },
    ],
  },
  {
    day: 114,
    themeEs: "La tormenta",
    themeEn: "The storm",
    missionEs: "Cuenta lo que ya había pasado cuando llegó la tormenta de verdad.",
    missionEn: "Tell what had already happened when the storm really hit.",
    line: "Cuando la tormenta llegó, muchas cosas ya habían empezado.",
    lineEn: "When the storm arrived, many things had already started.",
    prompts: [
      {
        id: "d114-ya-habia",
        frameStem: "Ya había…",
        english: "It had already started raining hard when the power went out.",
        spanish: "Ya había empezado a llover fuerte cuando se fue la luz.",
        situationLabel: "Se va la luz",
        why: "*Se fue la luz* — the light went away — is how Puerto Rico and much of Latin America says the power went out.",
        wordHints: [
          { en: "already", es: "ya había" },
          { en: "raining hard", es: "llover fuerte" },
          { en: "power went out", es: "se fue la luz" },
        ],
      },
      {
        id: "d114-todavia-no",
        frameStem: "Todavía no había…",
        english: "It still hadn't stopped raining when all the lights went out.",
        spanish: "Todavía no había parado de llover cuando se apagaron todas las luces.",
        situationLabel: "Todo oscuro",
        why: "*Parado de llover* — stopped raining — uses *parar de + infinitive*, the same pattern as English “stopped raining.”",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "stopped", es: "parado" },
          { en: "raining", es: "de llover" },
          { en: "lights went out", es: "se apagaron todas las luces" },
        ],
      },
      {
        id: "d114-nunca-habia",
        frameStem: "Nunca había…",
        english: "I had never heard wind that loud in my whole life.",
        spanish: "Nunca había escuchado el viento tan fuerte en toda mi vida.",
        situationLabel: "El viento más fuerte",
        why: "*En toda mi vida* anchors *nunca había* — not just today, but ever.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "heard", es: "escuchado" },
          { en: "wind", es: "el viento" },
          { en: "loud", es: "tan fuerte" },
          { en: "whole life", es: "toda mi vida" },
        ],
      },
      {
        id: "d114-antes-habia",
        frameStem: "Antes había…",
        english: "Before that we had had power and could watch the news on TV.",
        spanish: "Antes había tenido luz y podíamos ver la tele con las noticias.",
        situationLabel: "Antes de apagarse todo",
        why: "*Había tenido luz* — had had power — is past perfect; *podíamos* shifts to imperfect for the ongoing ability to watch.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "power", es: "luz" },
          { en: "watch", es: "ver" },
          { en: "news", es: "las noticias" },
        ],
      },
      {
        id: "d114-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then water had already come in under the door.",
        spanish: "Para entonces ya había entrado agua por debajo de la puerta.",
        situationLabel: "Agua adentro",
        why: "*Por debajo de la puerta* — under the door — is a small, concrete detail that makes the retelling feel real.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "water", es: "agua" },
          { en: "come in", es: "entrado" },
          { en: "under the door", es: "por debajo de la puerta" },
        ],
      },
    ],
  },
  {
    day: 115,
    themeEs: "La noche larga",
    themeEn: "The long night",
    missionEs: "Cuenta lo que ya había pasado durante la noche más larga.",
    missionEn: "Tell what had already happened during the longest night.",
    line: "Esa noche, el pasado perfecto cuenta la historia entera.",
    lineEn: "That night, the past perfect tells the whole story.",
    prompts: [
      {
        id: "d115-ya-habia",
        frameStem: "Ya había…",
        english: "Midnight had already passed and they were still awake.",
        spanish: "Ya había pasado media noche y seguíamos despiertos.",
        situationLabel: "Media noche pasada",
        why: "*Seguíamos despiertos* — we were still awake — uses imperfect for an ongoing state that night.",
        wordHints: [
          { en: "already", es: "ya había" },
          { en: "midnight", es: "media noche" },
          { en: "passed", es: "pasado" },
          { en: "still awake", es: "seguíamos despiertos" },
        ],
      },
      {
        id: "d115-todavia-no",
        frameStem: "Todavía no había…",
        english: "It still hadn't dawned when the wind started to die down.",
        spanish: "Todavía no había amanecido cuando el viento empezó a bajar.",
        situationLabel: "Antes del amanecer",
        why: "*Amanecer* works as a verb — *no había amanecido* — “it hadn't dawned yet.”",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "dawned", es: "amanecido" },
          { en: "wind", es: "el viento" },
          { en: "die down", es: "empezó a bajar" },
        ],
      },
      {
        id: "d115-nunca-habia",
        frameStem: "Nunca había…",
        english: "I had never spent such a long night without light or hot water.",
        spanish: "Nunca había pasado una noche tan larga sin luz ni agua caliente.",
        situationLabel: "La noche más larga",
        why: "*Pasar una noche* — to spend a night — is the natural verb for getting through hours awake.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "spent", es: "pasado" },
          { en: "long night", es: "una noche tan larga" },
          { en: "without light", es: "sin luz" },
          { en: "hot water", es: "agua caliente" },
        ],
      },
      {
        id: "d115-antes-habia",
        frameStem: "Antes había…",
        english: "Before that my little cousin had cried, but then she fell asleep.",
        spanish: "Antes había llorado mi prima pequeña, pero después se quedó dormida.",
        situationLabel: "Los niños en la noche",
        why: "*Se quedó dormida* — she fell asleep — is softer than *durmió* for a child finally settling down.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "cried", es: "llorado" },
          { en: "cousin", es: "mi prima" },
          { en: "fell asleep", es: "se quedó dormida" },
        ],
      },
      {
        id: "d115-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then it had already dawned and the rain sounded farther away.",
        spanish: "Para entonces ya había amanecido y la lluvia sonaba más lejos.",
        situationLabel: "El amanecer",
        why: "*Sonaba más lejos* — sounded farther away — imperfect for how the rain seemed as morning came.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "dawned", es: "amanecido" },
          { en: "rain", es: "la lluvia" },
          { en: "farther away", es: "más lejos" },
        ],
      },
    ],
  },
  {
    day: 116,
    themeEs: "El día después",
    themeEn: "The day after",
    missionEs: "Cuenta lo que ya había pasado cuando amaneció el día después.",
    missionEn: "Tell what had already happened when dawn came the next day.",
    line: "A la mañana siguiente, el barrio ya no era el mismo.",
    lineEn: "The next morning, the neighborhood was no longer the same.",
    prompts: [
      {
        id: "d116-ya-habia",
        frameStem: "Ya había…",
        english: "A big tree had already fallen in my grandmother's street.",
        spanish: "Ya había caído un árbol grande en la calle de mi abuela.",
        situationLabel: "El daño visible",
        why: "*Había caído* — had fallen — past perfect of *caerse*, already done before they stepped outside.",
        wordHints: [
          { en: "already", es: "ya había" },
          { en: "fallen", es: "caído" },
          { en: "tree", es: "un árbol grande" },
          { en: "street", es: "la calle" },
        ],
      },
      {
        id: "d116-todavia-no",
        frameStem: "Todavía no había…",
        english: "The electricity still hadn't come back when we went outside.",
        spanish: "Todavía no había regresado la electricidad cuando salimos afuera.",
        situationLabel: "Sin electricidad",
        why: "*Regresar* — to return — is the everyday verb for power coming back on.",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "come back", es: "regresado" },
          { en: "electricity", es: "la electricidad" },
          { en: "went outside", es: "salimos afuera" },
        ],
      },
      {
        id: "d116-nunca-habia",
        frameStem: "Nunca había…",
        english: "I had never seen so many branches on one street.",
        spanish: "Nunca había visto tantas ramas y hojas en una sola calle.",
        situationLabel: "Una calle irreconocible",
        why: "*Tantas ramas* — so many branches — is the kind of specific image that makes a retelling land.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "seen", es: "visto" },
          { en: "branches", es: "ramas" },
          { en: "one street", es: "una sola calle" },
        ],
      },
      {
        id: "d116-antes-habia",
        frameStem: "Antes había…",
        english: "Before that there had been shade from trees on almost the whole sidewalk.",
        spanish: "Antes había sombra de árboles en casi toda la acera.",
        situationLabel: "Antes del huracán",
        why: "*Antes había sombra* — before, there had been shade — past perfect for a world already gone.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "shade", es: "sombra" },
          { en: "trees", es: "árboles" },
          { en: "sidewalk", es: "la acera" },
        ],
      },
      {
        id: "d116-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then the man on the corner had already cleaned the sidewalk.",
        spanish: "Para entonces ya había limpiado la acera el señor de la esquina.",
        situationLabel: "Los vecinos ayudan",
        why: "Subject after the verb (*…el señor de la esquina*) is natural when you're naming who had already done something.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "cleaned", es: "limpiado" },
          { en: "sidewalk", es: "la acera" },
          { en: "corner", es: "la esquina" },
        ],
      },
    ],
  },
  {
    day: 117,
    themeEs: "Sin luz",
    themeEn: "Without power",
    missionEs: "Cuenta lo que ya había pasado durante los días sin electricidad.",
    missionEn: "Tell what had already happened during the days without electricity.",
    line: "Una semana sin luz cambia lo que ya habías hecho antes.",
    lineEn: "A week without power changes what you had already done before.",
    prompts: [
      {
        id: "d117-ya-habia",
        frameStem: "Ya había…",
        english: "A whole week had already gone by without electricity.",
        spanish: "Ya había pasado una semana entera sin electricidad.",
        situationLabel: "Una semana entera",
        why: "*Una semana entera* — a whole week — makes the duration feel real, not abstract.",
        wordHints: [
          { en: "already", es: "ya había" },
          { en: "gone by", es: "pasado" },
          { en: "whole week", es: "una semana entera" },
          { en: "electricity", es: "electricidad" },
        ],
      },
      {
        id: "d117-todavia-no",
        frameStem: "Todavía no había…",
        english: "The power still hadn't come back when they closed school for another week.",
        spanish: "Todavía no había regresado la luz cuando cerraron la escuela otra semana.",
        situationLabel: "La escuela cerrada",
        why: "*Otra semana* — another week — stacks time: still no power, and school closed again.",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "come back", es: "regresado" },
          { en: "power", es: "la luz" },
          { en: "closed school", es: "cerraron la escuela" },
        ],
      },
      {
        id: "d117-nunca-habia",
        frameStem: "Nunca había…",
        english: "I had never eaten so many meals with all the neighbors in the street.",
        spanish: "Nunca había comido tantas veces con todos los vecinos en la calle.",
        situationLabel: "Comida en la calle",
        why: "*Tantas veces* — so many times — counts repeated meals, not just one shared dinner.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "eaten", es: "comido" },
          { en: "neighbors", es: "los vecinos" },
          { en: "street", es: "en la calle" },
        ],
      },
      {
        id: "d117-antes-habia",
        frameStem: "Antes había…",
        english: "Before that there had been ice in the freezer and cold milk in the mornings.",
        spanish: "Antes había hielo en el congelador y leche fría por las mañanas.",
        situationLabel: "Antes del apagón",
        why: "*Leche fría por las mañanas* — cold milk in the mornings — is a small luxury you only miss once it's gone.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "ice", es: "hielo" },
          { en: "freezer", es: "el congelador" },
          { en: "cold milk", es: "leche fría" },
        ],
      },
      {
        id: "d117-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then there was already a big pot of soup at the neighbor's house.",
        spanish: "Para entonces ya había una olla grande de sopa en la casa del vecino.",
        situationLabel: "Comida compartida",
        why: "*Una olla grande de sopa* — a big pot of soup — is how a barrio feeds itself when the fridge is empty.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "big pot", es: "una olla grande" },
          { en: "soup", es: "de sopa" },
          { en: "neighbor", es: "del vecino" },
        ],
      },
    ],
  },
  {
    day: 118,
    themeEs: "La reconstrucción",
    themeEn: "Rebuilding",
    missionEs: "Cuenta lo que ya había pasado cuando el barrio empezó a reconstruirse.",
    missionEn: "Tell what had already happened when the neighborhood started to rebuild.",
    line: "Reconstruir también se cuenta con *ya había*.",
    lineEn: "Rebuilding gets told with *ya había* too.",
    prompts: [
      {
        id: "d118-ya-habia",
        frameStem: "Ya había…",
        english: "They had already fixed three roofs on the block.",
        spanish: "Ya habían arreglado tres techos en la cuadra con ayuda de todos.",
        situationLabel: "Techos arreglados",
        why: "*Habían arreglado* — they had fixed — plural *habían* because the whole block worked together.",
        wordHints: [
          { en: "already", es: "ya habían" },
          { en: "fixed", es: "arreglado" },
          { en: "roofs", es: "tres techos" },
          { en: "block", es: "la cuadra" },
        ],
      },
      {
        id: "d118-todavia-no",
        frameStem: "Todavía no había…",
        english: "Everything still hadn't gone back to normal when we left.",
        spanish: "Todavía no había regresado todo a la normalidad cuando nos fuimos.",
        situationLabel: "Antes de irse",
        why: "*Regresar a la normalidad* — return to normal — names what still hadn't happened when Marlana's visit ended.",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "normal", es: "la normalidad" },
          { en: "left", es: "nos fuimos" },
        ],
      },
      {
        id: "d118-nunca-habia",
        frameStem: "Nunca había…",
        english: "I had never seen so many people working together in so little time.",
        spanish: "Nunca había visto tanta gente trabajar junta en tan poco tiempo.",
        situationLabel: "El barrio unido",
        why: "*Tanta gente trabajar junta* — so many people working together — is the emotional center of the whole week.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "seen", es: "visto" },
          { en: "working together", es: "trabajar junta" },
          { en: "little time", es: "tan poco tiempo" },
        ],
      },
      {
        id: "d118-antes-habia",
        frameStem: "Antes había…",
        english: "Before that there had been fear in every house on the street.",
        spanish: "Antes había miedo en cada casa de la calle.",
        situationLabel: "Después de la tormenta",
        why: "*En cada casa de la calle* — in every house on the street — makes the fear feel shared, not private.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "fear", es: "miedo" },
          { en: "every house", es: "cada casa" },
          { en: "street", es: "de la calle" },
        ],
      },
      {
        id: "d118-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then my grandmother had already written all of this in her notebook.",
        spanish: "Para entonces ya había escrito mi abuela todo esto en su cuaderno.",
        situationLabel: "El cuaderno",
        why: "*Para que yo no lo olvidara* lives in the reading — here, *ya había escrito* closes the arc: the story was already on the page.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "written", es: "escrito" },
          { en: "grandmother", es: "mi abuela" },
          { en: "notebook", es: "su cuaderno" },
        ],
      },
    ],
  },
  {
    day: 119,
    themeEs: "Repaso: ya había pasado",
    themeEn: "Review: it had already happened",
    missionEs: "Resume la historia del huracán en cinco frases con los stems de la semana.",
    missionEn: "Sum up the hurricane story in five sentences using the week's stems.",
    line: "Toda la semana cabe en cinco frases, si sabes qué había pasado antes.",
    lineEn: "The whole week fits in five sentences, if you know what had happened before.",
    prompts: [
      {
        id: "d119-ya-habia",
        frameStem: "Ya había…",
        english: "The radio had already warned when the sky turned black.",
        spanish: "Ya había advertido la radio cuando el cielo se puso negro.",
        situationLabel: "Resumiendo el inicio",
        why: "Day 119's five prompts are beats of ONE story — abuela's hurricane, start to finish.",
        wordHints: [
          { en: "already", es: "ya había" },
          { en: "warned", es: "advertido" },
          { en: "radio", es: "la radio" },
          { en: "sky", es: "el cielo" },
          { en: "black", es: "negro" },
        ],
      },
      {
        id: "d119-todavia-no",
        frameStem: "Todavía no había…",
        english: "My grandmother still hadn't put away the candles when the sky got dark.",
        spanish: "Todavía no había empezado la tormenta cuando mi abuela guardó las velas.",
        situationLabel: "Antes de la tormenta",
        why: "Repaso day: fresh sentences, same five stems — the week's toolkit applied to the whole arc.",
        wordHints: [
          { en: "still hadn't", es: "todavía no había" },
          { en: "started", es: "empezado" },
          { en: "storm", es: "la tormenta" },
          { en: "put away", es: "guardó" },
          { en: "candles", es: "las velas" },
        ],
      },
      {
        id: "d119-nunca-habia",
        frameStem: "Nunca había…",
        english: "I had never seen the sky that dark or felt that much fear.",
        spanish: "Nunca había visto el cielo tan oscuro ni sentido tanto miedo.",
        situationLabel: "Lo que nunca había pasado",
        why: "*Ni* links two things never experienced before — the dark sky and the fear together.",
        wordHints: [
          { en: "never", es: "nunca había" },
          { en: "seen", es: "visto" },
          { en: "dark", es: "oscuro" },
          { en: "fear", es: "miedo" },
        ],
      },
      {
        id: "d119-antes-habia",
        frameStem: "Antes había…",
        english: "Before that it had been sunny and my cousins and I had played outside.",
        spanish: "Antes había hecho sol y mis primos y yo habíamos jugado afuera.",
        situationLabel: "La mañana tranquila",
        why: "*Habíamos jugado* — we had played — past perfect plural, same family group from the reading.",
        wordHints: [
          { en: "before", es: "antes había" },
          { en: "sunny", es: "hecho sol" },
          { en: "played", es: "habíamos jugado" },
          { en: "outside", es: "afuera" },
        ],
      },
      {
        id: "d119-para-entonces",
        frameStem: "Para entonces ya había…",
        english: "By then everything my grandmother wrote in her pages had already happened.",
        spanish: "Para entonces ya había pasado todo lo que mi abuela escribió en sus páginas.",
        situationLabel: "Cerrando la historia",
        why: "*Todo lo que mi abuela escribió* ties the grammar week back to why Marlana found the cuaderno in the first place.",
        wordHints: [
          { en: "by then", es: "para entonces" },
          { en: "already", es: "ya había" },
          { en: "happened", es: "pasado" },
          { en: "grandmother", es: "mi abuela" },
          { en: "wrote", es: "escribió" },
        ],
      },
    ],
  },
];
