import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 3 draft — La Lectura (days 106–112).
 * Story: "La entrevista de Marcos" — six installments + repaso recap.
 */
export const week3ReadingDays: ReadingDay[] = [
  {
    day: 106,
    themeEs: "Antes de la entrevista",
    storyTitle: "La entrevista de Marcos",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la beca", en: "the scholarship", example: "La beca cubre la universidad completa." },
      { es: "nervioso/a", en: "nervous", example: "Dijo que estaba muy nervioso." },
      { es: "las tarjetas", en: "the flashcards", example: "Había preparado tarjetas con preguntas posibles." },
      { es: "la entrevista", en: "the interview", example: "Tenía la entrevista al día siguiente." },
      { es: "confiar en", en: "to trust, believe in", example: "Su mamá le dijo que confiara en él." },
    ],
    dialogue: {
      title: "La víspera",
      situation: "En la sala de maestros, al final del día",
      lines: [
        { speaker: "A", es: "Priya, necesito contarte lo de Marcos.", en: "Priya, I need to tell you about Marcos." },
        { speaker: "B", es: "¿Qué pasó? ¿Está bien?", en: "What happened? Is he okay?" },
        { speaker: "A", es: "Sí, solo está muy nervioso. Mañana tiene la entrevista para la beca.", en: "Yes, he's just very nervous. Tomorrow he has the interview for the scholarship." },
        { speaker: "B", es: "¿La que cubre la universidad completa?", en: "The one that covers the full university?" },
        { speaker: "A", es: "Esa misma. Me contó que no durmió bien anoche y que llevaba meses preparándose.", en: "That same one. He told me he didn't sleep well last night and that he'd been preparing for months." },
        { speaker: "B", es: "¿Con tarjetas y todo?", en: "With flashcards and everything?" },
        { speaker: "A", es: "Sí, mencionó que había hecho tarjetas con preguntas posibles. Preguntó si yo creía que estaba listo.", en: "Yes, he mentioned he'd made flashcards with possible questions. He asked if I thought he was ready." },
        { speaker: "B", es: "Claro que está listo. ¿Qué le dijiste?", en: "Of course he's ready. What did you tell him?" },
        { speaker: "A", es: "Le dije que confiara en todo lo que había preparado. Con o sin beca, estoy orgullosa de él.", en: "I told him to trust everything he'd prepared. Scholarship or not, I'm proud of him." },
      ],
    },
  },
  {
    day: 107,
    themeEs: "La entrevista",
    storyTitle: "La entrevista de Marcos",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el evaluador", en: "the evaluator", example: "Un evaluador le preguntó por qué quería la beca." },
      { es: "quedarse en blanco", en: "to blank", example: "Al principio se quedó en blanco." },
      { es: "la impresión", en: "the impression", example: "Le dijeron que había hecho una buena impresión." },
      { es: "responder", en: "to answer", example: "Había respondido con calma al final." },
      { es: "avisar", en: "to notify", example: "Le avisarían en unas semanas." },
    ],
    dialogue: {
      title: "Después de la entrevista",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "¿Ya pasó la entrevista de Marcos?", en: "Did Marcos's interview already happen?" },
        { speaker: "B", es: "Sí, vino a contarme apenas terminó. Dijo que había durado como media hora.", en: "Yes, he came to tell me right after it ended. He said it had lasted about half an hour." },
        { speaker: "A", es: "¿Y cómo le fue?", en: "And how did it go?" },
        { speaker: "B", es: "Bien, creo. Me contó que al principio se quedó en blanco, pero que un evaluador le preguntó por qué quería la beca y respondió con calma.", en: "Well, I think. He told me at first he blanked, but an evaluator asked him why he wanted the scholarship and he answered calmly." },
        { speaker: "A", es: "Eso es buena señal.", en: "That's a good sign." },
        { speaker: "B", es: "Mencionó que le preguntaron sobre sus notas y sobre su familia. Preguntó si había respondido bien a la pregunta más difícil.", en: "He mentioned they asked about his grades and his family. He asked if he'd answered the hardest question well." },
        { speaker: "A", es: "¿Qué le dijiste?", en: "What did you tell him?" },
        { speaker: "B", es: "Le dije que había hecho un buen trabajo. También me dijo que al salir le dijeron que había hecho una buena impresión y que le avisarían en unas semanas.", en: "I told him he'd done a good job. He also told me that when he left they told him he'd made a good impression and that they'd notify him in a few weeks." },
      ],
    },
  },
  {
    day: 108,
    themeEs: "La espera",
    storyTitle: "La entrevista de Marcos",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la espera", en: "the wait", example: "Dijo que la espera era lo más difícil." },
      { es: "el correo", en: "the email", example: "Revisaba el correo todos los días." },
      { es: "ansioso/a", en: "anxious", example: "Su mamá también estaba ansiosa." },
      { es: "la fecha límite", en: "the deadline", example: "Faltaban cinco días para la fecha límite." },
      { es: "obsesionarse", en: "to obsess", example: "Su mamá le dijo que no se obsesionara con el correo." },
    ],
    dialogue: {
      title: "Dos semanas sin noticias",
      situation: "En la sala de maestros, entre clases",
      lines: [
        { speaker: "A", es: "¿Marcos ya sabe algo de la beca?", en: "Does Marcos know anything about the scholarship yet?" },
        { speaker: "B", es: "Todavía no. Dijo que revisaba el correo todos los días y que cada día sin noticias se le hacía más largo.", en: "Not yet. He said he checked his email every day and that each day without news felt longer." },
        { speaker: "A", es: "Uf, qué difícil es esperar.", en: "Ugh, waiting is so hard." },
        { speaker: "B", es: "Me contó que había soñado con la carta de aceptación y que su mamá también estaba ansiosa.", en: "He told me he'd dreamed about the acceptance letter and that his mom was anxious too." },
        { speaker: "A", es: "¿Le queda mucho tiempo?", en: "Does he have much time left?" },
        { speaker: "B", es: "Mencionó que faltaban solo cinco días para la fecha límite. Algunos amigos ya habían recibido respuestas.", en: "He mentioned there were only five days left until the deadline. Some friends had already gotten answers." },
        { speaker: "A", es: "Pobre Marcos.", en: "Poor Marcos." },
        { speaker: "B", es: "Preguntó si era normal esperar tanto. Le dije que sí, y que su mamá le había dicho que no se obsesionara con el correo.", en: "He asked if it was normal to wait this long. I told him yes, and that his mom had told him not to obsess over his email." },
      ],
    },
  },
  {
    day: 109,
    themeEs: "La respuesta",
    storyTitle: "La entrevista de Marcos",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "felicitaciones", en: "congratulations", example: "Vio la palabra felicitaciones en el correo." },
      { es: "la aceptación", en: "the acceptance", example: "Soñó con la carta de aceptación." },
      { es: "firmar", en: "to sign", example: "Tenía que firmar antes del viernes." },
      { es: "la emoción", en: "the excitement", example: "Había llorado de la emoción." },
      { es: "creer", en: "to believe", example: "Casi no podía creerlo." },
    ],
    dialogue: {
      title: "¡Lo logró!",
      situation: "En la sala de maestros, a primera hora",
      lines: [
        { speaker: "A", es: "Priya, ¡tengo noticias de Marcos!", en: "Priya, I have news about Marcos!" },
        { speaker: "B", es: "¿Qué pasó? ¿Ya respondieron?", en: "What happened? Did they respond already?" },
        { speaker: "A", es: "Sí. Dijo que había recibido el correo esa mañana y que le habían dado la beca.", en: "Yes. He said he'd gotten the email that morning and that they'd given him the scholarship." },
        { speaker: "B", es: "¡No me digas! ¿Cómo reaccionó?", en: "No way! How did he react?" },
        { speaker: "A", es: "Me contó que gritó cuando leyó la primera línea. Mencionó que la carta también incluía libros y una laptop.", en: "He told me he shouted when he read the first line. He mentioned the letter also included books and a laptop." },
        { speaker: "B", es: "Se lo merece completamente.", en: "He completely deserves it." },
        { speaker: "A", es: "Preguntó si esto significaba que iba a la universidad de sus sueños. Casi no podía creerlo.", en: "He asked if this meant he was going to his dream university. He could hardly believe it." },
        { speaker: "B", es: "¿Ya le contó a su mamá?", en: "Did he already tell his mom?" },
        { speaker: "A", es: "Sí, enseguida. Me dijo que ella le dijo que era el día más feliz de su vida.", en: "Yes, right away. He told me she told him it was the happiest day of her life." },
      ],
    },
  },
  {
    day: 110,
    themeEs: "Contándole a su mamá",
    storyTitle: "La entrevista de Marcos",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "llorar", en: "to cry", example: "Su abuela también lloró." },
      { es: "una broma", en: "a joke", example: "Su mamá pensó que era una broma." },
      { es: "enterarse", en: "to find out", example: "Cuando se enteró, lloró de alegría." },
      { es: "festejar", en: "to celebrate", example: "Su papá iba a faltar al trabajo para festejar." },
      { es: "ingeniería", en: "engineering", example: "Le dijo que iba a estudiar ingeniería." },
    ],
    dialogue: {
      title: "Una llamada larga",
      situation: "En la sala de maestros, calificando tareas",
      lines: [
        { speaker: "A", es: "Marcos me contó más sobre la llamada con su mamá.", en: "Marcos told me more about the call with his mom." },
        { speaker: "B", es: "Apuesto a que fue emocionante.", en: "I bet it was emotional." },
        { speaker: "A", es: "Mucho. Dijo que le había llamado en cuanto recibió la carta. Me contó que su mamá pensó que era una broma al principio.", en: "Very. He said he'd called her as soon as he got the letter. He told me his mom thought it was a joke at first." },
        { speaker: "B", es: "¿Tuvo que repetir la noticia?", en: "Did he have to repeat the news?" },
        { speaker: "A", es: "Tres veces, dijo. Mencionó que su abuela también lloró cuando se enteró, y que su papá dijo que iba a faltar al trabajo para festejar.", en: "Three times, he said. He mentioned his grandmother cried when she found out too, and that his dad said he was going to miss work to celebrate." },
        { speaker: "B", es: "Qué bonito.", en: "How lovely." },
        { speaker: "A", es: "Le dijo a su mamá que la beca cubría cuatro años de universidad y que iba a estudiar ingeniería.", en: "He told his mom the scholarship covered four years of university and that he was going to study engineering." },
        { speaker: "B", es: "¿Quiere traerla a la escuela?", en: "Does he want to bring her to school?" },
        { speaker: "A", es: "Preguntó si podía invitarla algún día. Dije que por supuesto.", en: "He asked if he could invite her someday. I said of course." },
      ],
    },
  },
  {
    day: 111,
    themeEs: "El plan",
    storyTitle: "La entrevista de Marcos",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "ingeniería civil", en: "civil engineering", example: "Va a estudiar ingeniería civil." },
      { es: "el dormitorio", en: "the dorm", example: "Ya había mirado los dormitorios del campus." },
      { es: "la matrícula", en: "enrollment, tuition", example: "Tenía que confirmar su matrícula antes de junio." },
      { es: "el orientador", en: "the advisor", example: "Un orientador lo iba a contactar." },
      { es: "emergencias", en: "emergencies", example: "Quería guardar un poco para emergencias." },
    ],
    dialogue: {
      title: "Más allá de la beca",
      situation: "En la sala de maestros, un viernes por la tarde",
      lines: [
        { speaker: "A", es: "Marcos ya no habla solo de la beca — ahora habla de planes.", en: "Marcos doesn't just talk about the scholarship anymore — now he talks about plans." },
        { speaker: "B", es: "Me gusta eso. ¿Qué dijo?", en: "I like that. What did he say?" },
        { speaker: "A", es: "Dijo que iba a estudiar ingeniería civil y que la beca pagaba matrícula, libros y computadora.", en: "He said he was going to study civil engineering and that the scholarship paid tuition, books, and a computer." },
        { speaker: "B", es: "¿Ya pensó en dónde va a vivir?", en: "Has he already thought about where he'll live?" },
        { speaker: "A", es: "Me contó que ya había mirado los dormitorios del campus y que quería guardar un poco para emergencias.", en: "He told me he'd already looked at the campus dorms and that he wanted to save a little for emergencies." },
        { speaker: "B", es: "Qué responsable.", en: "How responsible." },
        { speaker: "A", es: "Mencionó que el programa empezaba en agosto. Un orientador le dijo que tenía que confirmar su matrícula antes de junio.", en: "He mentioned the program started in August. An advisor told him he had to confirm his enrollment before June." },
        { speaker: "B", es: "¿Va a seguir practicando español con nosotros?", en: "Is he going to keep practicing Spanish with us?" },
        { speaker: "A", es: "Preguntó si todavía podía venir después de graduarse. Le dije que esta sala siempre iba a ser suya.", en: "He asked if he could still come after graduating. I told him this lounge would always be his." },
      ],
    },
  },
  {
    day: 112,
    themeEs: "Repaso: dijo que",
    isRecap: true,
    vocab: [
      { es: "estilo indirecto", en: "reported speech", example: "Lo cuento en estilo indirecto." },
      { es: "valer la pena", en: "to be worth it", example: "Todo el esfuerzo había valido la pena." },
      { es: "el esfuerzo", en: "the effort", example: "Meses de preparación." },
      { es: "orgulloso/a", en: "proud", example: "Estoy muy orgullosa de él." },
      { es: "el capítulo", en: "the chapter", example: "Empieza un capítulo nuevo." },
    ],
    dialogue: {
      title: "La historia completa",
      situation: "En la sala de maestros, repasando la semana",
      lines: [
        { speaker: "A", es: "Oye, ¿me haces un resumen de Marcos? Quiero contárselo a mi hermana.", en: "Hey, can you give me a summary of Marcos? I want to tell my sister." },
        { speaker: "B", es: "Claro. ¿Quieres la versión corta o la completa?", en: "Sure. Do you want the short version or the full one?" },
        { speaker: "A", es: "La completa, pero en estilo indirecto — como si alguien te lo contara.", en: "The full one, but in reported speech — like someone told it to you." },
        { speaker: "B", es: "Bueno: dijo que todo había empezado con tarjetas y nervios. Me contó que casi no durmió la noche anterior a la entrevista.", en: "Okay: he said it all started with flashcards and nerves. He told me he hardly slept the night before the interview." },
        { speaker: "A", es: "¿Y la entrevista?", en: "And the interview?" },
        { speaker: "B", es: "Mencionó que le hicieron preguntas difíciles, pero que al salir le dijeron que había hecho buena impresión. Luego vino la espera — dijo que revisaba el correo todos los días.", en: "He mentioned they asked him hard questions, but that when he left they told him he'd made a good impression. Then came the wait — he said he checked his email every day." },
        { speaker: "A", es: "¿Y al final?", en: "And in the end?" },
        { speaker: "B", es: "Me contó que gritó cuando vio felicitaciones en el correo. Le dijo a su mamá que todo el esfuerzo había valido la pena. Mencionó que ya tiene un plan para la universidad.", en: "He told me he shouted when he saw congratulations in the email. He told his mom the whole effort had been worth it. He mentioned he already has a plan for university." },
        { speaker: "A", es: "Qué historia tan bonita.", en: "What a beautiful story." },
        { speaker: "B", es: "Sí. Y yo estoy muy orgullosa de él.", en: "Yes. And I'm very proud of him." },
      ],
    },
  },
];
