import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 2 — "La carta de la abuela" (days 99–105).
 * Marlana retells her grandmother's letter from Puerto Rico to Priya.
 */
export const week2ReadingDays: ReadingDay[] = [
  {
    day: 99,
    themeEs: "La carta llega",
    storyTitle: "La carta de la abuela",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la carta", en: "the letter", example: "Hoy me llegó una carta de mi abuela." },
      { es: "extrañar", en: "to miss", example: "Dice que me extraña mucho." },
      { es: "a mano", en: "by hand", example: "Prefiere escribir a mano." },
      { es: "el sobre", en: "the envelope", example: "El sobre venía con sello de Puerto Rico." },
      { es: "de salud", en: "in health (doing well)", example: "Está muy bien de salud." },
    ],
    dialogue: {
      title: "Llegó la carta",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "Priya, mira lo que me llegó hoy.", en: "Priya, look what I got today." },
        { speaker: "B", es: "¿Una carta? ¿De quién?", en: "A letter? From who?" },
        { speaker: "A", es: "De mi abuela, desde Puerto Rico. Hacía meses que no recibía una.", en: "From my grandmother, from Puerto Rico. It had been months since I got one." },
        { speaker: "B", es: "Qué lindo. ¿Qué dice?", en: "How sweet. What does it say?" },
        { speaker: "A", es: "Dice que está muy bien de salud y que me extraña mucho.", en: "She says she's in very good health and that she misses me a lot." },
        { speaker: "B", es: "Ay, qué bonito. ¿Y por qué carta y no mensaje?", en: "Oh, how lovely. And why a letter and not a message?" },
        { speaker: "A", es: "Explica que prefiere escribir a mano. Dice que las cartas duran más que los mensajes.", en: "She explains that she prefers writing by hand. She says letters last longer than messages." },
        { speaker: "B", es: "Tiene razón. ¿Qué más trae?", en: "She's right. What else does it have?" },
      ],
    },
  },
  {
    day: 100,
    themeEs: "Recuerdos de la infancia",
    storyTitle: "La carta de la abuela",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "de niña/de niño", en: "as a girl/boy", example: "De niña corría descalza por el patio." },
      { es: "el patio", en: "the yard", example: "El patio tenía un árbol de mango." },
      { es: "descalzo/a", en: "barefoot", example: "Corría descalza por el patio." },
      { es: "el recuerdo", en: "the memory", example: "Es un recuerdo que casi había olvidado." },
      { es: "el balcón", en: "the balcony", example: "Pasábamos las tardes en el balcón." },
    ],
    dialogue: {
      title: "Recuerdos del patio",
      situation: "En la sala de maestros, entre clases",
      lines: [
        { speaker: "A", es: "Hoy leí la segunda parte de la carta. Es sobre sus recuerdos de niña.", en: "Today I read the second part of the letter. It's about her childhood memories." },
        { speaker: "B", es: "¿Qué cuenta?", en: "What does she tell?" },
        { speaker: "A", es: "Dice que de niña corría descalza por el patio de su abuela.", en: "She says that as a girl she ran barefoot in her grandmother's yard." },
        { speaker: "B", es: "Qué imagen tan linda.", en: "What a lovely image." },
        { speaker: "A", es: "Según la carta, había un árbol de mango enorme y toda la familia se reunía los domingos.", en: "According to the letter, there was a huge mango tree and the whole family got together on Sundays." },
        { speaker: "B", es: "¿Y tú sales en esa parte?", en: "And do you appear in that part?" },
        { speaker: "A", es: "Sí. Cuenta que yo me escondía debajo de la mesa de la cocina cuando era pequeña.", en: "Yes. She says I used to hide under the kitchen table when I was little." },
        { speaker: "B", es: "Me encanta. Suena a que la carta es un álbum de recuerdos.", en: "I love it. It sounds like the letter is a photo album of memories." },
      ],
    },
  },
  {
    day: 101,
    themeEs: "La receta secreta",
    storyTitle: "La carta de la abuela",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la receta", en: "the recipe", example: "Comparte la receta de arroz con gandules." },
      { es: "el sofrito", en: "sofrito (sauce base)", example: "El sofrito es lo más importante." },
      { es: "los gandules", en: "pigeon peas", example: "Lleva gandules frescos, no de lata." },
      { es: "el culantro", en: "culantro (herb)", example: "El culantro fresco hace la diferencia." },
      { es: "sin falta", en: "without fail", example: "Lo prepara cada Navidad sin falta." },
    ],
    dialogue: {
      title: "La receta en la carta",
      situation: "En la sala de maestros, calificando exámenes",
      lines: [
        { speaker: "A", es: "La tercera parte de la carta es toda una receta.", en: "The third part of the letter is an entire recipe." },
        { speaker: "B", es: "¿En serio? ¿De qué?", en: "Really? Of what?" },
        { speaker: "A", es: "Se trata de arroz con gandules. Dice que la receta lleva gandules frescos, no de lata.", en: "It's about arroz con gandules. She says the recipe calls for fresh pigeon peas, not canned." },
        { speaker: "B", es: "Suena delicioso. ¿Te da las medidas?", en: "That sounds delicious. Does she give you measurements?" },
        { speaker: "A", es: "No exactamente. Explica que el sofrito es lo más importante y que el arroz tiene que quedar suelto.", en: "Not exactly. She explains that the sofrito is the most important thing and that the rice has to come out loose." },
        { speaker: "B", es: "Como toda abuela — a ojo.", en: "Like every grandmother — by eye." },
        { speaker: "A", es: "Exacto. Según la carta, la receta viene de su propia abuela.", en: "Exactly. According to the letter, the recipe comes from her own grandmother." },
        { speaker: "B", es: "Eso no se puede comprar en ninguna tienda.", en: "You can't buy that in any store." },
      ],
    },
  },
  {
    day: 102,
    themeEs: "Consejos de la abuela",
    storyTitle: "La carta de la abuela",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "el consejo", en: "advice", example: "Sus consejos son directos y sin rodeos." },
      { es: "descansar", en: "to rest", example: "Dice que tengo que descansar más." },
      { es: "quemarse", en: "to burn out", example: "Vio a mucha gente joven quemarse." },
      { es: "sin rodeos", en: "without beating around the bush", example: "Sus consejos van sin rodeos." },
      { es: "cuidar", en: "to take care of", example: "Lo más importante es cuidar la salud." },
    ],
    dialogue: {
      title: "Consejos sin rodeos",
      situation: "En la sala de maestros, después de clases",
      lines: [
        { speaker: "A", es: "La cuarta parte son consejos de abuela, directos y sin rodeos.", en: "The fourth part is grandmother's advice, direct and without beating around the bush." },
        { speaker: "B", es: "Déjame adivinar: come más, descansa más.", en: "Let me guess: eat more, rest more." },
        { speaker: "A", es: "Exactamente. Dice que tengo que descansar más los fines de semana.", en: "Exactly. She says I need to rest more on weekends." },
        { speaker: "B", es: "Tiene razón. ¿Qué más?", en: "She's right. What else?" },
        { speaker: "A", es: "Según la carta, lo más importante es cuidar la salud. Explica que vio a mucha gente joven quemarse por trabajar demasiado.", en: "According to the letter, the most important thing is taking care of your health. She explains that she saw many young people burn out from working too much." },
        { speaker: "B", es: "Uf, eso me suena familiar.", en: "Oof, that sounds familiar." },
        { speaker: "A", es: "Cuenta que se preocupa cuando paso semanas sin escribirle.", en: "She says she worries when I go weeks without writing to her." },
        { speaker: "B", es: "Bueno, ya estás contándome la carta entera. Eso cuenta, ¿no?", en: "Well, you're telling me the whole letter. That counts, right?" },
      ],
    },
  },
  {
    day: 103,
    themeEs: "La foto vieja",
    storyTitle: "La carta de la abuela",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "la foto", en: "the photo", example: "Cayó una foto vieja del sobre." },
      { es: "el portal", en: "the porch", example: "Estamos en su portal en la foto." },
      { es: "la gaveta", en: "the drawer", example: "La guardó en su gaveta de recuerdos." },
      { es: "anochecer", en: "to get dark", example: "No quería irme cuando anocheció." },
      { es: "el caracol", en: "the seashell", example: "Me enseñó a buscar caracoles en la arena." },
    ],
    dialogue: {
      title: "Una sorpresa en el sobre",
      situation: "En la sala de maestros, un viernes por la tarde",
      lines: [
        { speaker: "A", es: "Cuando abrí la quinta parte, se me cayó una foto del sobre.", en: "When I opened the fifth part, a photo fell out of the envelope." },
        { speaker: "B", es: "¿Una foto? ¿De cuándo?", en: "A photo? From when?" },
        { speaker: "A", es: "Dice que tiene veinte años, más o menos. En la foto yo tengo cinco años.", en: "She says it's about twenty years old, more or less. In the photo I'm five years old." },
        { speaker: "B", es: "¿Dónde fue?", en: "Where was it taken?" },
        { speaker: "A", es: "Según la carta, es del verano que pasé en su casa. Estamos abuela y yo en su portal.", en: "According to the letter, it's from the summer I spent at her house. Grandmother and I are on her porch." },
        { speaker: "B", es: "Qué tesoro.", en: "What a treasure." },
        { speaker: "A", es: "Explica que la guardó en su gaveta de recuerdos. Cuenta que ese día fuimos a la playa y yo no quería irme cuando anocheció.", en: "She explains that she kept it in her drawer of mementos. She says that day we went to the beach and I didn't want to leave when it got dark." },
        { speaker: "B", es: "No me extraña nada. Suena exactamente a ti de niña.", en: "I'm not surprised at all. It sounds exactly like you as a kid." },
      ],
    },
  },
  {
    day: 104,
    themeEs: "Quiere visitar",
    storyTitle: "La carta de la abuela",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "visitar", en: "to visit", example: "Quiere visitarme el próximo año." },
      { es: "la nieve", en: "the snow", example: "Nunca ha visto nieve en persona." },
      { es: "ahorrar", en: "to save (money)", example: "Ya está ahorrando para el viaje." },
      { es: "el avión", en: "the plane", example: "Su sobrina la acompañaría en el avión." },
      { es: "el puerto", en: "the harbor", example: "Sueña con caminar por el puerto de Boston." },
    ],
    dialogue: {
      title: "Quiere venir a Boston",
      situation: "En la sala de maestros, antes de salir",
      lines: [
        { speaker: "A", es: "La última parte de la carta es la que más me emocionó.", en: "The last part of the letter is the one that moved me the most." },
        { speaker: "B", es: "¿Qué dice?", en: "What does it say?" },
        { speaker: "A", es: "Dice que quiere visitarme el próximo año. Dice que nunca ha visto nieve.", en: "She says she wants to visit me next year. She says she's never seen snow." },
        { speaker: "B", es: "¡Qué emoción! ¿Cuándo quiere venir?", en: "How exciting! When does she want to come?" },
        { speaker: "A", es: "Según la carta, en la primavera, no en invierno. Explica que le da miedo el frío de Boston.", en: "According to the letter, in spring, not winter. She explains that Boston's cold scares her a little." },
        { speaker: "B", es: "Con razón. ¿Viene sola?", en: "Makes sense. Is she coming alone?" },
        { speaker: "A", es: "No. Cuenta que su sobrina la acompañaría en el avión. Ya le contó a toda la familia del plan.", en: "No. She says her niece would accompany her on the plane. She already told the whole family about the plan." },
        { speaker: "B", es: "Marlana, eso es lo más bonito de toda la carta.", en: "Marlana, that's the loveliest part of the whole letter." },
      ],
    },
  },
  {
    day: 105,
    themeEs: "Repaso: dice que",
    isRecap: true,
    vocab: [
      { es: "contar", en: "to tell, recount", example: "Cuéntame toda la carta." },
      { es: "la distancia", en: "the distance", example: "No importa la distancia." },
      { es: "las raíces", en: "roots", example: "Tengo raíces en dos lugares." },
      { es: "el cariño", en: "affection", example: "La carta está llena de cariño." },
      { es: "contar de nuevo", en: "to tell again", example: "Voy a contarte todo de nuevo." },
    ],
    dialogue: {
      title: "La carta entera",
      situation: "En la sala de maestros, una semana después de que llegó la carta",
      lines: [
        { speaker: "A", es: "Oye, ¿qué pasó con la carta de tu abuela? ¿Ya la terminaste?", en: "Hey, what happened with your grandmother's letter? Did you finish it?" },
        { speaker: "B", es: "Sí, toda. ¿Quieres el resumen completo?", en: "Yes, all of it. Do you want the full summary?" },
        { speaker: "A", es: "Por favor. Cuéntame todo, pero rápido.", en: "Please. Tell me everything, but fast." },
        { speaker: "B", es: "Bueno: dice que está bien, que me extraña, y que quiere visitarme el próximo año.", en: "Okay: she says she's fine, she misses me, and she wants to visit me next year." },
        { speaker: "A", es: "Eso ya lo sé. ¿Qué más trae?", en: "I already know that. What else does it have?" },
        { speaker: "B", es: "Recuerdos de su infancia, la receta de arroz con gandules, consejos sin rodeos, y una foto vieja de cuando yo tenía cinco años.", en: "Memories from her childhood, the arroz con gandules recipe, advice without beating around the bush, and an old photo of me when I was five." },
        { speaker: "A", es: "Wow. Se trata de mucho más que una carta.", en: "Wow. It's about much more than a letter." },
        { speaker: "B", es: "Exacto. Cuenta que no importa la distancia, la familia sigue siendo familia.", en: "Exactly. She says that no matter the distance, family is still family." },
      ],
    },
  },
];
