import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 13 draft — Capstone "Mi otoño en Pues" (days 176–182).
 *
 * Append to content/prompts/otono.ts. prompt.spanish must stay verbatim with
 * week13-frames.ts examples for the matching frameStem.
 */
export const week13SpeakDays: SpeakDay[] = [
  {
    day: 176,
    themeEs: "El comienzo",
    themeEn: "The beginning",
    missionEs: "Compara hace dos meses con ahora — empieza tu repaso de temporada.",
    missionEn: "Compare two months ago with now — start your season lookback.",
    line: "Hace dos meses… Ahora puedo… Eso es otoño.",
    lineEn: "Two months ago… Now I can… That's fall.",
    prompts: [
      {
        id: "d176-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago I barely knew how to summarize a news item.",
        spanish: "Hace dos meses apenas sabía resumir una noticia.",
        situationLabel: "El punto de partida",
        why: "*Hace dos meses* opens the season retrospective — where you were when fall began.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "barely", es: "apenas" },
          { en: "summarize", es: "resumir" },
          { en: "news", es: "noticia" },
        ],
      },
      {
        id: "d176-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can tell you Naty's story in five sentences.",
        spanish: "Ahora puedo contarte la historia de Naty en cinco frases.",
        situationLabel: "El progreso",
        why: "*Contarte la historia de Naty en cinco frases* — measurable proof of fall's first toolkit.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "can", es: "puedo" },
          { en: "tell", es: "contarte" },
          { en: "story", es: "historia" },
          { en: "five sentences", es: "cinco frases" },
        ],
      },
      {
        id: "d176-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was trusting I could retell what I'd just read.",
        spanish: "Lo más difícil fue confiar en que podía retell lo que leía.",
        situationLabel: "La verdad",
        why: "*Confiar en que podía retell* — the internal hurdle behind every read → speak loop.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "trusting", es: "confiar" },
          { en: "retell", es: "retell" },
          { en: "read", es: "leía" },
        ],
      },
      {
        id: "d176-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was how natural it started to sound.",
        spanish: "Lo que más me sorprendió fue lo rápido que sonó natural.",
        situationLabel: "La sorpresa",
        why: "*Lo rápido que sonó natural* — surprise at speed, not perfection.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "how fast", es: "lo rápido" },
          { en: "natural", es: "natural" },
        ],
      },
      {
        id: "d176-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is closing fall with a complete review.",
        spanish: "El próximo paso es cerrar otoño con un repaso completo.",
        situationLabel: "Hacia el cierre",
        why: "*Cerrar otoño con un repaso completo* — meta before the meta — you're building toward day 182.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "close", es: "cerrar" },
          { en: "fall", es: "otoño" },
          { en: "review", es: "repaso completo" },
        ],
      },
    ],
  },
  {
    day: 177,
    themeEs: "Las historias",
    themeEn: "The stories",
    missionEs: "Nombra las historias que seguiste este otoño.",
    missionEn: "Name the stories you followed this fall.",
    line: "Naty, la feria, el artículo, Diego — tu otoño en historias.",
    lineEn: "Naty, the fair, the article, Diego — your fall in stories.",
    prompts: [
      {
        id: "d177-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago I didn't follow a thread six days in a row.",
        spanish: "Hace dos meses no seguía un hilo seis días seguidos.",
        situationLabel: "Antes",
        why: "*No seguía un hilo seis días seguidos* — the skill you didn't have yet.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "follow a thread", es: "seguía un hilo" },
          { en: "six days", es: "seis días seguidos" },
        ],
      },
      {
        id: "d177-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can name five fall stories.",
        spanish: "Ahora puedo nombrar cinco historias de otoño.",
        situationLabel: "El inventario",
        why: "*Nombrar cinco historias de otoño* — inventory what you followed.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "name", es: "nombrar" },
          { en: "five stories", es: "cinco historias" },
          { en: "fall", es: "otoño" },
        ],
      },
      {
        id: "d177-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was picking up the thread each morning.",
        spanish: "Lo más difícil fue retomar el hilo cada mañana.",
        situationLabel: "Cada mañana",
        why: "*Retomar el hilo cada mañana* — the daily discipline of serialized retelling.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "pick up the thread", es: "retomar el hilo" },
          { en: "each morning", es: "cada mañana" },
        ],
      },
      {
        id: "d177-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was how much I remember without the notebook.",
        spanish: "Lo que más me sorprendió fue cuánto recuerdo sin mirar el cuaderno.",
        situationLabel: "La memoria",
        why: "*Cuánto recuerdo sin mirar el cuaderno* — stories stick when you retell them daily.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "how much", es: "cuánto" },
          { en: "remember", es: "recuerdo" },
          { en: "notebook", es: "cuaderno" },
        ],
      },
      {
        id: "d177-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is following longer stories in winter.",
        spanish: "El próximo paso es seguir historias más largas en invierno.",
        situationLabel: "Invierno",
        why: "*Historias más largas en invierno* — the thread continues into the next season.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "longer stories", es: "historias más largas" },
          { en: "winter", es: "invierno" },
        ],
      },
    ],
  },
  {
    day: 178,
    themeEs: "Las herramientas",
    themeEn: "The tools",
    missionEs: "Haz inventario de los stems que aprendiste en otoño.",
    missionEn: "Take inventory of the stems you learned in fall.",
    line: "Sesenta stems. Un toolkit de verdad.",
    lineEn: "Sixty stems. A real toolkit.",
    prompts: [
      {
        id: "d178-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago I only had five summarizing stems.",
        spanish: "Hace dos meses solo tenía cinco stems de resumir.",
        situationLabel: "El toolkit inicial",
        why: "*Solo tenía cinco stems de resumir* — week one vs. week thirteen.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "only", es: "solo" },
          { en: "five stems", es: "cinco stems" },
          { en: "summarizing", es: "resumir" },
        ],
      },
      {
        id: "d178-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can use more than sixty stems.",
        spanish: "Ahora puedo usar más de sesenta stems.",
        situationLabel: "El inventario",
        why: "*Más de sesenta stems* — the number that makes the season tangible.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "use", es: "usar" },
          { en: "sixty", es: "sesenta" },
          { en: "stems", es: "stems" },
        ],
      },
      {
        id: "d178-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was the subjunctive in \"I was surprised that…\"",
        spanish: "Lo más difícil fue el subjuntivo en Me sorprendió que…",
        situationLabel: "El subjuntivo",
        why: "*El subjuntivo en Me sorprendió que* — naming the grammar hill you climbed.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "subjunctive", es: "subjuntivo" },
          { en: "surprised", es: "me sorprendió" },
        ],
      },
      {
        id: "d178-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was that connectors come out on their own.",
        spanish: "Lo que más me sorprendió fue que los conectores me salen solos.",
        situationLabel: "Sin traducir",
        why: "*Me salen solos* — they come out on their own — the goal behind every stem drill.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "connectors", es: "conectores" },
          { en: "on their own", es: "salen solos" },
        ],
      },
      {
        id: "d178-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is mixing summer and fall stems freely.",
        spanish: "El próximo paso es mezclar stems de verano y otoño.",
        situationLabel: "Mezclar",
        why: "*Mezclar stems de verano y otoño* — the capstone move: toolkits become one.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "mix", es: "mezclar" },
          { en: "summer", es: "verano" },
          { en: "fall", es: "otoño" },
        ],
      },
    ],
  },
  {
    day: 179,
    themeEs: "Leer y reaccionar",
    themeEn: "Read and react",
    missionEs: "Cuenta cómo la lectura se volvió el centro de otoño.",
    missionEn: "Tell how reading became the center of fall.",
    line: "Leer → retell → reaccionar. El loop de otoño.",
    lineEn: "Read → retell → react. Fall's loop.",
    prompts: [
      {
        id: "d179-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago reading was an extra before bed.",
        spanish: "Hace dos meses la lectura era un extra antes de dormir.",
        situationLabel: "Extra, no centro",
        why: "*Era un extra* — imperfect — reading's old role before fall restructured it.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "reading", es: "lectura" },
          { en: "extra", es: "extra" },
          { en: "before bed", es: "antes de dormir" },
        ],
      },
      {
        id: "d179-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can read, summarize, react, and follow the story — all in Spanish.",
        spanish: "Ahora puedo leer, resumir, reaccionar y seguir la historia.",
        situationLabel: "El loop completo",
        why: "*Todo en español* — the full read → retell → react loop in one breath.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "read", es: "leer" },
          { en: "summarize", es: "resumir" },
          { en: "react", es: "reaccionar" },
          { en: "follow", es: "seguir" },
        ],
      },
      {
        id: "d179-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was trusting I understood enough to speak.",
        spanish: "Lo más difícil fue confiar en que entendí suficiente.",
        situationLabel: "Confiar",
        why: "*Entendía suficiente para hablar* — the gap between comprehension and confidence.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "trusting", es: "confiar" },
          { en: "enough", es: "suficiente" },
          { en: "speak", es: "hablar" },
        ],
      },
      {
        id: "d179-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was that reading became the center.",
        spanish: "Lo que más me sorprendió fue que la lectura se volvió el centro.",
        situationLabel: "El centro",
        why: "*Se volvió el centro* — La Lectura graduated from extra to backbone.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "reading", es: "lectura" },
          { en: "became the center", es: "se volvió el centro" },
        ],
      },
      {
        id: "d179-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is winter — back-and-forth conversation.",
        spanish: "El próximo paso es invierno — charla de ida y vuelta.",
        situationLabel: "Invierno",
        why: "*Charla de ida y vuelta* — winter's name in the curriculum — conversation both ways.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "winter", es: "invierno" },
          { en: "back-and-forth", es: "ida y vuelta" },
          { en: "conversation", es: "charla" },
        ],
      },
    ],
  },
  {
    day: 180,
    themeEs: "Un minuto",
    themeEn: "One minute",
    missionEs: "Mide tu progreso de sostener — de diez segundos a cuarenta y cinco.",
    missionEn: "Measure your sustain progress — from ten seconds to forty-five.",
    line: "Diez segundos hace dos meses. Cuarenta y cinco ahora.",
    lineEn: "Ten seconds two months ago. Forty-five now.",
    prompts: [
      {
        id: "d180-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago I spoke ten seconds and stopped.",
        spanish: "Hace dos meses hablaba diez segundos y paraba.",
        situationLabel: "Diez segundos",
        why: "*Hablaba diez segundos y paraba* — imperfect — the old limit, measured.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "ten seconds", es: "diez segundos" },
          { en: "stopped", es: "paraba" },
        ],
      },
      {
        id: "d180-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can speak forty-five seconds without stopping.",
        spanish: "Ahora puedo hablar cuarenta y cinco segundos sin parar.",
        situationLabel: "Cuarenta y cinco",
        why: "*Cuarenta y cinco segundos sin parar* — four times longer — say the number out loud.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "forty-five seconds", es: "cuarenta y cinco segundos" },
          { en: "without stopping", es: "sin parar" },
        ],
      },
      {
        id: "d180-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was talking alone in front of the mirror.",
        spanish: "Lo más difícil fue hablar sola frente al espejo.",
        situationLabel: "El espejo",
        why: "*Hablar sola frente al espejo* — the practice that works and embarrasses.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "talking alone", es: "hablar sola" },
          { en: "mirror", es: "espejo" },
        ],
      },
      {
        id: "d180-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was going from ten to forty-five seconds.",
        spanish: "Lo que más me sorprendió fue pasar de diez a cuarenta y cinco segundos.",
        situationLabel: "Cuatro veces más",
        why: "*Pasar de diez a cuarenta y cinco* — the math of a season's sustain work.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "going from", es: "pasar de" },
          { en: "ten", es: "diez" },
          { en: "forty-five", es: "cuarenta y cinco" },
        ],
      },
      {
        id: "d180-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is the full minute.",
        spanish: "El próximo paso es el minuto entero.",
        situationLabel: "El minuto",
        why: "*El minuto entero* — the sustain goal that winter will push further.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "full minute", es: "minuto entero" },
        ],
      },
    ],
  },
  {
    day: 181,
    themeEs: "Mi otoño en Pues",
    themeEn: "My fall in Pues",
    missionEs: "Cuenta tu otoño: antes, ahora, después.",
    missionEn: "Tell your fall: before, now, next.",
    line: "Mírate: hablas de otoño en español.",
    lineEn: "Look at you: talking about fall, in Spanish.",
    prompts: [
      {
        id: "d181-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago I didn't know how to retell what I read.",
        spanish: "Hace dos meses no sabía retell lo que leía.",
        situationLabel: "El punto de partida",
        why: "Day-90 equivalent. Say it slowly. *No sabía retell lo que leía* — where fall found you.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "didn't know", es: "no sabía" },
          { en: "retell", es: "retell" },
          { en: "read", es: "leía" },
        ],
      },
      {
        id: "d181-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can summarize, report, connect, react, and follow a story over several days.",
        spanish: "Ahora puedo resumir, reportar, conectar, reaccionar y seguir una historia varios días.",
        situationLabel: "La meta de otoño",
        why: "This was Otoño's goal. Say it slowly.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "summarize", es: "resumir" },
          { en: "report", es: "reportar" },
          { en: "connect", es: "conectar" },
          { en: "follow a story", es: "seguir una historia" },
        ],
      },
      {
        id: "d181-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was not giving up during the slow weeks.",
        spanish: "Lo más difícil fue no rendirme en las semanas flojas.",
        situationLabel: "Las semanas flojas",
        why: "*Las semanas flojas* — the slow weeks — every learner on earth nods.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "not giving up", es: "no rendirme" },
          { en: "slow weeks", es: "semanas flojas" },
        ],
      },
      {
        id: "d181-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was how much I remember from the stories.",
        spanish: "Lo que más me sorprendió fue cuánto recuerdo de las historias.",
        situationLabel: "Las historias",
        why: "*Cuánto recuerdo de las historias* — Naty, la feria, Diego, el artículo — measure it out loud.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "how much", es: "cuánto" },
          { en: "remember", es: "recuerdo" },
          { en: "stories", es: "historias" },
        ],
      },
      {
        id: "d181-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is winter.",
        spanish: "El próximo paso es invierno.",
        situationLabel: "Temporada tres",
        why: "*Invierno* — the thread continues. But tonight you rest.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "winter", es: "invierno" },
        ],
      },
    ],
  },
  {
    day: 182,
    themeEs: "Repaso: mi otoño",
    themeEn: "Review: my fall",
    missionEs: "Cuenta tu otoño entero en un minuto — repaso de temporada.",
    missionEn: "Tell your whole fall in one minute — season review.",
    line: "Noventa y un días. Una temporada entera. Tuya.",
    lineEn: "Ninety-one days. A whole season. Yours.",
    prompts: [
      {
        id: "d182-hace-dos-meses",
        frameStem: "Hace dos meses…",
        english: "Two months ago I started summarizing with \"It's about…\"",
        spanish: "Hace dos meses empecé a resumir con Trata de…",
        situationLabel: "Semana uno",
        why: "Repaso: open the one-minute season retell where fall began — *Trata de…*.",
        wordHints: [
          { en: "two months ago", es: "hace dos meses" },
          { en: "started", es: "empecé" },
          { en: "summarizing", es: "resumir" },
          { en: "it's about", es: "trata de" },
        ],
      },
      {
        id: "d182-ahora-puedo",
        frameStem: "Ahora puedo…",
        english: "Now I can connect, contrast, react, and follow stories.",
        spanish: "Ahora puedo conectar, contrastar, reaccionar y seguir historias.",
        situationLabel: "El toolkit completo",
        why: "*Conectar, contrastar, reaccionar y seguir* — four verbs, one season's growth.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "connect", es: "conectar" },
          { en: "contrast", es: "contrastar" },
          { en: "react", es: "reaccionar" },
          { en: "follow", es: "seguir" },
        ],
      },
      {
        id: "d182-lo-mas-dificil",
        frameStem: "Lo más difícil fue…",
        english: "The hardest part was trusting my retells.",
        spanish: "Lo más difícil fue confiar en mis retells.",
        situationLabel: "Confiar",
        why: "*Confiar en mis retells* — the through-line of the whole season.",
        wordHints: [
          { en: "hardest", es: "lo más difícil" },
          { en: "trusting", es: "confiar" },
          { en: "retells", es: "retells" },
        ],
      },
      {
        id: "d182-me-sorprendio",
        frameStem: "Lo que más me sorprendió fue…",
        english: "What surprised me most was enjoying it.",
        spanish: "Lo que más me sorprendió fue disfrutarlo.",
        situationLabel: "Disfrutarlo",
        why: "*Disfrutarlo* — enjoying it — the surprise Verano promised and Otoño delivered.",
        wordHints: [
          { en: "surprised", es: "me sorprendió" },
          { en: "enjoying", es: "disfrutarlo" },
        ],
      },
      {
        id: "d182-el-proximo-paso",
        frameStem: "El próximo paso es…",
        english: "The next step is winter.",
        spanish: "El próximo paso es invierno.",
        situationLabel: "Seguir",
        why: "Repaso day: one minute, five stems, whole season — close with what's next.",
        wordHints: [
          { en: "next step", es: "el próximo paso" },
          { en: "winter", es: "invierno" },
        ],
      },
    ],
  },
];
