import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 6 — "Sin embargo" (days 127–133).
 * Story: "El cambio de horario" — Marlana and Priya navigate a disruptive schedule change.
 */
export const week6SpeakDays: SpeakDay[] = [
  {
    day: 127,
    themeEs: "La noticia",
    themeEn: "The announcement",
    missionEs: "Cuenta el anuncio del horario nuevo con conectores de contraste.",
    missionEn: "Tell about the new schedule announcement using contrast connectors.",
    line: "Un cambio grande se cuenta mejor cuando marcas lo que esperabas y lo que pasó.",
    lineEn: "A big change is easier to tell when you mark what you expected and what happened.",
    prompts: [
      {
        id: "d127-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, the new schedule starts Monday.",
        spanish: "Sin embargo, el horario nuevo empieza el lunes.",
        situationLabel: "Lo que nadie esperaba",
        why: "*Sin embargo* marks a sharp turn — the announcement landed, but not the way anyone hoped.",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "new schedule", es: "el horario nuevo" },
          { en: "starts", es: "empieza" },
          { en: "monday", es: "el lunes" },
        ],
      },
      {
        id: "d127-aunque",
        frameStem: "Aunque…",
        english: "Although I understand the reason, it seems very rushed to me.",
        spanish: "Aunque entiendo la razón, me parece muy apresurado.",
        situationLabel: "Entender sin estar de acuerdo",
        why: "*Aunque* lets you agree with part of the story while pushing back on the rest — perfect for staff-room talk.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "understand", es: "entiendo" },
          { en: "reason", es: "la razón" },
          { en: "rushed", es: "apresurado" },
        ],
      },
      {
        id: "d127-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, lunch is now at eleven thirty.",
        spanish: "En cambio, el almuerzo ahora es a las once y media.",
        situationLabel: "Lo que cambió concretamente",
        why: "*En cambio* swaps old reality for new — here, the lunch block that moved.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "lunch", es: "el almuerzo" },
          { en: "now", es: "ahora" },
          { en: "eleven thirty", es: "las once y media" },
        ],
      },
      {
        id: "d127-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite the complaints, they're going to implement it anyway.",
        spanish: "A pesar de las quejas, van a implementarlo igual.",
        situationLabel: "Quejas que no sirvieron",
        why: "*A pesar de* + noun names what didn't stop the decision — the pushback that went nowhere.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "complaints", es: "las quejas" },
          { en: "implement", es: "implementarlo" },
          { en: "anyway", es: "igual" },
        ],
      },
      {
        id: "d127-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, the longer blocks might help the science teachers.",
        spanish: "Por otro lado, los bloques largos pueden ayudar a los de ciencias.",
        situationLabel: "Un posible lado bueno",
        why: "*Por otro lado* opens a second perspective without canceling the first — the fair counterpoint.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "longer blocks", es: "los bloques largos" },
          { en: "help", es: "pueden ayudar" },
          { en: "science", es: "ciencias" },
        ],
      },
    ],
  },
  {
    day: 128,
    themeEs: "El almuerzo",
    themeEn: "Lunch",
    missionEs: "Describe el caos del almuerzo nuevo con conectores de contraste.",
    missionEn: "Describe the new lunch chaos using contrast connectors.",
    line: "El almuerzo temprano suena simple hasta que ves la fila.",
    lineEn: "Early lunch sounds simple until you see the line.",
    prompts: [
      {
        id: "d128-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, the cafeteria line didn't get shorter.",
        spanish: "Sin embargo, la fila del comedor no bajó.",
        situationLabel: "La promesa vs. la realidad",
        why: "*Sin embargo* after a schedule change often means “they said it would help, but…”",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "line", es: "la fila" },
          { en: "cafeteria", es: "el comedor" },
          { en: "didn't get shorter", es: "no bajó" },
        ],
      },
      {
        id: "d128-aunque",
        frameStem: "Aunque…",
        english: "Although they eat earlier, they ask for a snack mid-afternoon.",
        spanish: "Aunque comen más temprano, piden snack a media tarde.",
        situationLabel: "Comer temprano no basta",
        why: "*Aunque* + present sets up the irony — early lunch, late hunger.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "eat earlier", es: "comen más temprano" },
          { en: "ask for", es: "piden" },
          { en: "mid-afternoon", es: "a media tarde" },
        ],
      },
      {
        id: "d128-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, recess got ten minutes shorter.",
        spanish: "En cambio, la hora de recreo se acortó diez minutos.",
        situationLabel: "Lo que se perdió",
        why: "*En cambio* names what was traded away when lunch moved — recess time.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "recess", es: "la hora de recreo" },
          { en: "got shorter", es: "se acortó" },
          { en: "ten minutes", es: "diez minutos" },
        ],
      },
      {
        id: "d128-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite the new signs, the kids go to the wrong room.",
        spanish: "A pesar de los letreros nuevos, los niños van al salón equivocado.",
        situationLabel: "Letreros que no alcanzan",
        why: "*A pesar de los letreros* — the fix that didn't fix anything.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "new signs", es: "letreros nuevos" },
          { en: "kids", es: "los niños" },
          { en: "wrong room", es: "salón equivocado" },
        ],
      },
      {
        id: "d128-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, the cafeteria is quieter after twelve.",
        spanish: "Por otro lado, la cafetería está más tranquila después de las doce.",
        situationLabel: "Una mejora pequeña",
        why: "*Por otro lado* finds the silver lining without pretending the chaos didn't happen.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "cafeteria", es: "la cafetería" },
          { en: "quieter", es: "más tranquila" },
          { en: "after twelve", es: "después de las doce" },
        ],
      },
    ],
  },
  {
    day: 129,
    themeEs: "Los maestros",
    themeEn: "The teachers",
    missionEs: "Cuenta cómo afectó el cambio a los maestros con conectores de contraste.",
    missionEn: "Tell how the change affected teachers using contrast connectors.",
    line: "Perder la hora de planificación duele más que mover el almuerzo.",
    lineEn: "Losing your planning period hurts more than moving lunch.",
    prompts: [
      {
        id: "d129-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, my planning period is now at seven in the morning.",
        spanish: "Sin embargo, mi hora de planificación ahora es a las siete de la mañana.",
        situationLabel: "La hora imposible",
        why: "*Sin embargo* after “they reassigned everyone” — the punch line nobody wanted.",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "planning period", es: "hora de planificación" },
          { en: "seven in the morning", es: "las siete de la mañana" },
        ],
      },
      {
        id: "d129-aunque",
        frameStem: "Aunque…",
        english: "Although we're trying to adapt, it's hard to grade with this schedule.",
        spanish: "Aunque tratamos de adaptarnos, es difícil calificar con este horario.",
        situationLabel: "Adaptarse con límites",
        why: "*Tratamos de adaptarnos* — we're trying — but *aunque* keeps the honest complaint.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "trying to adapt", es: "tratamos de adaptarnos" },
          { en: "hard", es: "difícil" },
          { en: "grade", es: "calificar" },
        ],
      },
      {
        id: "d129-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, we no longer overlap in schedule.",
        spanish: "En cambio, ahora planifico en la tarde, cuando estoy agotada.",
        situationLabel: "Perder el tiempo juntas",
        why: "*Ya no coincidimos* — a small sentence for a big loss between colleagues.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "no longer", es: "ya no" },
          { en: "overlap", es: "coincidimos" },
          { en: "schedule", es: "en horario" },
        ],
      },
      {
        id: "d129-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite the union's petition, there were no changes.",
        spanish: "A pesar de la petición del sindicato, no hubo cambios.",
        situationLabel: "La petición ignorada",
        why: "*A pesar de la petición* — formal pushback that still didn't move the needle.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "union", es: "sindicato" },
          { en: "petition", es: "petición" },
          { en: "no changes", es: "no hubo cambios" },
        ],
      },
      {
        id: "d129-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, ninety-minute blocks help in the lab.",
        spanish: "Por otro lado, los bloques de noventa minutos ayudan en laboratorio.",
        situationLabel: "Algo que sí funciona",
        why: "*En laboratorio* — where longer blocks actually earn their keep.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "ninety-minute blocks", es: "bloques de noventa minutos" },
          { en: "help", es: "ayudan" },
          { en: "lab", es: "laboratorio" },
        ],
      },
    ],
  },
  {
    day: 130,
    themeEs: "Los estudiantes",
    themeEn: "The students",
    missionEs: "Cuenta la confusión de los estudiantes con conectores de contraste.",
    missionEn: "Tell about student confusion using contrast connectors.",
    line: "Un mapa nuevo no sirve si nadie lo mira.",
    lineEn: "A new map doesn't help if nobody looks at it.",
    prompts: [
      {
        id: "d130-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, three students got lost between blocks.",
        spanish: "Sin embargo, tres estudiantes se perdieron entre bloques.",
        situationLabel: "Perdidos en el pasillo",
        why: "*Se perdieron entre bloques* — the human cost of a schedule shuffle.",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "got lost", es: "se perdieron" },
          { en: "between blocks", es: "entre bloques" },
          { en: "students", es: "estudiantes" },
        ],
      },
      {
        id: "d130-aunque",
        frameStem: "Aunque…",
        english: "Although there are maps on every hallway, some don't read them.",
        spanish: "Aunque hay mapas en cada pasillo, algunos no los leen.",
        situationLabel: "Mapas ignorados",
        why: "*Algunos no los leen* — the gentle blame that every teacher recognizes.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "maps", es: "mapas" },
          { en: "every hallway", es: "cada pasillo" },
          { en: "don't read them", es: "no los leen" },
        ],
      },
      {
        id: "d130-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, the bell rings ten minutes earlier.",
        spanish: "En cambio, la campana suena diez minutos antes.",
        situationLabel: "Una campana distinta",
        why: "*Suena diez minutos antes* — a small shift that throws off everyone's timing.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "bell", es: "la campana" },
          { en: "rings", es: "suena" },
          { en: "ten minutes earlier", es: "diez minutos antes" },
        ],
      },
      {
        id: "d130-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite the helpers in the hallways, the chaos continues.",
        spanish: "A pesar de los ayudantes en los pasillos, el caos continúa.",
        situationLabel: "Ayuda que no alcanza",
        why: "*El caos continúa* — the honest ending after every attempted fix.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "helpers", es: "ayudantes" },
          { en: "hallways", es: "pasillos" },
          { en: "chaos continues", es: "el caos continúa" },
        ],
      },
      {
        id: "d130-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, the eighth graders already memorized the new schedule.",
        spanish: "Por otro lado, los de octavo ya memorizaron el horario nuevo.",
        situationLabel: "Los grandes se adaptan",
        why: "*Los de octavo* — the grade that always figures it out first.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "eighth graders", es: "los de octavo" },
          { en: "memorized", es: "memorizaron" },
          { en: "new schedule", es: "horario nuevo" },
        ],
      },
    ],
  },
  {
    day: 131,
    themeEs: "Las familias",
    themeEn: "The families",
    missionEs: "Cuenta el caos de la recogida con conectores de contraste.",
    missionEn: "Tell about pickup chaos using contrast connectors.",
    line: "Quince minutos parecen poco hasta que estás en la fila de carros.",
    lineEn: "Fifteen minutes seems small until you're in the car line.",
    prompts: [
      {
        id: "d131-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, many families arrived late to pickup yesterday.",
        spanish: "Sin embargo, muchas familias llegaron tarde a la recogida ayer.",
        situationLabel: "Familias desorientadas",
        why: "*Llegaron tarde a la recogida* — the ripple effect of a schedule nobody fully absorbed.",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "families", es: "familias" },
          { en: "arrived late", es: "llegaron tarde" },
          { en: "pickup", es: "la recogida" },
        ],
      },
      {
        id: "d131-aunque",
        frameStem: "Aunque…",
        english: "Although we sent an email on Friday, many didn't read it.",
        spanish: "Aunque mandamos un correo el viernes, muchos no lo leyeron.",
        situationLabel: "Correo ignorado",
        why: "*Mandamos un correo* — we did our part; *aunque* carries the frustration.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "sent an email", es: "mandamos un correo" },
          { en: "friday", es: "el viernes" },
          { en: "didn't read it", es: "no lo leyeron" },
        ],
      },
      {
        id: "d131-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, elementary dismissal is now at two fifteen.",
        spanish: "En cambio, la salida de primaria ahora es a las dos y cuarto.",
        situationLabel: "Salida más temprana",
        why: "*La salida de primaria* — the concrete time families have to learn.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "elementary dismissal", es: "salida de primaria" },
          { en: "now", es: "ahora" },
          { en: "two fifteen", es: "las dos y cuarto" },
        ],
      },
      {
        id: "d131-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite the volunteers at the door, the line was a mess.",
        spanish: "A pesar de los voluntarios en la puerta, la fila era un caos.",
        situationLabel: "Voluntarios vs. fila",
        why: "*Era un caos* — past tense for yesterday's pickup disaster.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "volunteers", es: "voluntarios" },
          { en: "door", es: "puerta" },
          { en: "mess", es: "un caos" },
        ],
      },
      {
        id: "d131-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, some moms prefer picking up earlier.",
        spanish: "Por otro lado, algunas mamás prefieren recoger más temprano.",
        situationLabel: "No todos se quejan",
        why: "*Prefieren recoger más temprano* — the minority opinion worth naming.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "some moms", es: "algunas mamás" },
          { en: "prefer", es: "prefieren" },
          { en: "earlier", es: "más temprano" },
        ],
      },
    ],
  },
  {
    day: 132,
    themeEs: "Lo bueno",
    themeEn: "The upside",
    missionEs: "Cuenta lo que mejoró después de una semana con conectores de contraste.",
    missionEn: "Tell what improved after a week using contrast connectors.",
    line: "Después del caos viene la adaptación — y a veces, una sorpresa.",
    lineEn: "After chaos comes adaptation — and sometimes, a surprise.",
    prompts: [
      {
        id: "d132-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, not everything went as badly as we thought.",
        spanish: "Sin embargo, no todo salió mal como pensábamos.",
        situationLabel: "Mejor de lo esperado",
        why: "*No todo salió mal* — the relief after bracing for the worst.",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "not everything", es: "no todo" },
          { en: "went badly", es: "salió mal" },
          { en: "we thought", es: "pensábamos" },
        ],
      },
      {
        id: "d132-aunque",
        frameStem: "Aunque…",
        english: "Although the first day was a disaster, today was calmer.",
        spanish: "Aunque el primer día fue un desastre, hoy fue más tranquilo.",
        situationLabel: "De desastre a calma",
        why: "*Fue un desastre* vs. *fue más tranquilo* — the arc of a rough week.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "first day", es: "el primer día" },
          { en: "disaster", es: "un desastre" },
          { en: "calmer", es: "más tranquilo" },
        ],
      },
      {
        id: "d132-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, afternoons in the hallway are calmer.",
        spanish: "En cambio, las tardes en el pasillo están más calmadas.",
        situationLabel: "Pasillos más tranquilos",
        why: "*Están más calmadas* — present tense for a trend that's holding.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "afternoons", es: "las tardes" },
          { en: "hallway", es: "el pasillo" },
          { en: "calmer", es: "más calmadas" },
        ],
      },
      {
        id: "d132-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite the initial complaints, attendance didn't drop.",
        spanish: "A pesar de las quejas iniciales, la asistencia no bajó.",
        situationLabel: "Quejas sin consecuencias",
        why: "*La asistencia no bajó* — the metric that matters most to admin.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "initial complaints", es: "quejas iniciales" },
          { en: "attendance", es: "la asistencia" },
          { en: "didn't drop", es: "no bajó" },
        ],
      },
      {
        id: "d132-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, it forced us to talk more across departments.",
        spanish: "Por otro lado, nos obligó a hablar más entre departamentos.",
        situationLabel: "Un efecto colateral bueno",
        why: "*Nos obligó a hablar* — crisis as accidental team-building.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "forced us", es: "nos obligó" },
          { en: "talk more", es: "hablar más" },
          { en: "departments", es: "departamentos" },
        ],
      },
    ],
  },
  {
    day: 133,
    themeEs: "Repaso: sin embargo",
    themeEn: "Review: however…",
    missionEs: "Resume toda la semana del horario en cinco frases con contraste.",
    missionEn: "Summarize the whole schedule week in five contrasting sentences.",
    line: "Una semana de caos cabe en cinco conectores, si eliges bien.",
    lineEn: "A week of chaos fits in five connectors, if you choose well.",
    prompts: [
      {
        id: "d133-sin-embargo",
        frameStem: "Sin embargo…",
        english: "However, the principal isn't going to reverse the schedule.",
        spanish: "Sin embargo, la directora no va a revertir el horario.",
        situationLabel: "La decisión final",
        why: "*No va a revertir* — the bottom line after a week of noise.",
        wordHints: [
          { en: "however", es: "sin embargo" },
          { en: "principal", es: "la directora" },
          { en: "reverse", es: "revertir" },
          { en: "schedule", es: "el horario" },
        ],
      },
      {
        id: "d133-aunque",
        frameStem: "Aunque…",
        english: "Although we understand the reason, the change was very abrupt.",
        spanish: "Aunque entendemos la razón, el cambio fue muy brusco.",
        situationLabel: "Entender sin perdonar",
        why: "*Fue muy brusco* — past tense for a change that's already done.",
        wordHints: [
          { en: "although", es: "aunque" },
          { en: "understand", es: "entendemos" },
          { en: "reason", es: "la razón" },
          { en: "abrupt", es: "brusco" },
        ],
      },
      {
        id: "d133-en-cambio",
        frameStem: "En cambio…",
        english: "Instead, lunch, planning, and dismissal all ended up different.",
        spanish: "En cambio, el almuerzo, la planificación y la salida quedaron distintos.",
        situationLabel: "Tres cosas que cambiaron",
        why: "Listing three nouns after *en cambio* compresses six days into one sentence.",
        wordHints: [
          { en: "instead", es: "en cambio" },
          { en: "lunch", es: "el almuerzo" },
          { en: "planning", es: "la planificación" },
          { en: "dismissal", es: "la salida" },
        ],
      },
      {
        id: "d133-a-pesar",
        frameStem: "A pesar de…",
        english: "Despite complaints from teachers, parents, and students, the change stayed.",
        spanish: "A pesar de las quejas de maestros, padres y estudiantes, el cambio se quedó.",
        situationLabel: "Quejas de todos lados",
        why: "*Se quedó* — “it stayed” — simple past for a decision that held.",
        wordHints: [
          { en: "despite", es: "a pesar de" },
          { en: "complaints", es: "quejas" },
          { en: "teachers", es: "maestros" },
          { en: "stayed", es: "se quedó" },
        ],
      },
      {
        id: "d133-por-otro-lado",
        frameStem: "Por otro lado…",
        english: "On the other hand, the longer blocks already have defenders.",
        spanish: "Por otro lado, los bloques largos ya tienen defensores.",
        situationLabel: "Algo que se queda",
        why: "*Ya tienen defensores* — the unexpected allies of a hated change.",
        wordHints: [
          { en: "on the other hand", es: "por otro lado" },
          { en: "longer blocks", es: "bloques largos" },
          { en: "already", es: "ya" },
          { en: "defenders", es: "defensores" },
        ],
      },
    ],
  },
];
