import type { ReadingDay } from "../readings/types";

/**
 * Otoño Week 10 draft — "El artículo" (days 155–161).
 *
 * Append to content/readings/otono.ts. themeEs must match week10-prompts.ts.
 * Six installments (155–160) + fresh recap on 161 (isRecap: true).
 */
export const week10ReadingDays: ReadingDay[] = [
  {
    day: 155,
    themeEs: "El artículo",
    storyTitle: "El artículo",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el artículo", en: "the article", example: "Leí un artículo sobre educación bilingüe." },
      { es: "la educación bilingüe", en: "bilingual education", example: "El artículo habla de programas bilingües." },
      { es: "encontrarse con", en: "to come across", example: "Me encontré con el artículo anoche." },
      { es: "llamar la atención", en: "to catch one's attention", example: "Me llamó la atención el título." },
      { es: "antes de dormir", en: "before bed", example: "Lo leí antes de dormir." },
    ],
    dialogue: {
      title: "Algo para comentar",
      situation: "En la sala de maestros, antes de la primera campana",
      lines: [
        { speaker: "A", es: "Priya, anoche me encontré con un artículo que me dejó pensando.", en: "Priya, last night I came across an article that left me thinking." },
        { speaker: "B", es: "¿De qué trataba?", en: "What was it about?" },
        { speaker: "A", es: "De educación bilingüe en Massachusetts. Lo leí antes de dormir.", en: "About bilingual education in Massachusetts. I read it before bed." },
        { speaker: "B", es: "¿Y qué te llamó la atención?", en: "And what caught your attention?" },
        { speaker: "A", es: "Lo que más me llamó la atención fue el título: «Los niños bilingües no pierden, ganan».", en: "What caught my attention most was the title: \"Bilingual children don't lose, they gain.\"" },
        { speaker: "B", es: "Suena directo. ¿De dónde lo sacaste?", en: "That sounds direct. Where did you get it?" },
        { speaker: "A", es: "Una exalumna lo compartió en una red social. Me dio gusto leer que alguien de aquí lo publicó.", en: "An alum shared it on social media. I was glad to read that someone from here published it." },
        { speaker: "B", es: "Cuéntame más cuando termines de leerlo.", en: "Tell me more when you finish reading it." },
      ],
    },
  },
  {
    day: 156,
    themeEs: "Los argumentos",
    storyTitle: "El artículo",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el argumento", en: "the argument", example: "El autor presenta tres argumentos claros." },
      { es: "desarrollar", en: "to develop", example: "Los niños desarrollan dos idiomas a la vez." },
      { es: "la flexibilidad mental", en: "mental flexibility", example: "Ganan flexibilidad mental." },
      { es: "a la vez", en: "at the same time", example: "Aprenden dos idiomas a la vez." },
      { es: "defender", en: "to defend, advocate", example: "Defiende los programas duales." },
    ],
    dialogue: {
      title: "Lo que defiende el autor",
      situation: "En la sala de maestros, a la hora del almuerzo",
      lines: [
        { speaker: "A", es: "Seguí leyendo el artículo. Creo que el autor defiende los programas duales con mucha claridad.", en: "I kept reading the article. I think the author defends dual programs very clearly." },
        { speaker: "B", es: "¿Qué argumentos usa?", en: "What arguments does he use?" },
        { speaker: "A", es: "Dice que los niños no «pierden» inglés — desarrollan dos idiomas a la vez.", en: "He says children don't \"lose\" English — they develop two languages at once." },
        { speaker: "B", es: "Eso lo escucho mucho en el colegio.", en: "I hear that a lot at school." },
        { speaker: "A", es: "Me dio gusto leer que lo explica con ejemplos de salones reales, no solo con teoría.", en: "I was glad to read that he explains it with examples from real classrooms, not just theory." },
        { speaker: "B", es: "¿Algo te sorprendió?", en: "Did anything surprise you?" },
        { speaker: "A", es: "Me sorprendió que mencione la flexibilidad mental como una ventaja concreta.", en: "I was surprised that he mentions mental flexibility as a concrete advantage." },
        { speaker: "B", es: "Suena como algo que podríamos compartir con las familias.", en: "Sounds like something we could share with families." },
      ],
    },
  },
  {
    day: 157,
    themeEs: "Los datos",
    storyTitle: "El artículo",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el dato", en: "the data point, fact", example: "El artículo cita varios datos." },
      { es: "citar", en: "to cite", example: "Cita un estudio de la universidad." },
      { es: "el estudio", en: "the study", example: "Un estudio siguió a mil estudiantes." },
      { es: "seguir", en: "to follow (over time)", example: "Siguieron a los niños cinco años." },
      { es: "comparar", en: "to compare", example: "Comparan dos grupos de escuelas." },
    ],
    dialogue: {
      title: "Números y estudios",
      situation: "En la sala de maestros, revisando papeles",
      lines: [
        { speaker: "A", es: "La parte de los datos me pareció la más fuerte del artículo.", en: "The data section seemed the strongest part of the article to me." },
        { speaker: "B", es: "¿Qué números trae?", en: "What numbers does it bring?" },
        { speaker: "A", es: "Cita un estudio que siguió a mil estudiantes durante cinco años.", en: "It cites a study that followed a thousand students for five years." },
        { speaker: "B", es: "Eso es bastante seguimiento.", en: "That's quite a bit of follow-up." },
        { speaker: "A", es: "Lo que más me llamó la atención fue que los bilingües sacaron mejores notas en lectura al final.", en: "What caught my attention most was that bilingual students got better reading grades in the end." },
        { speaker: "B", es: "¿Comparados con quién?", en: "Compared to whom?" },
        { speaker: "A", es: "Con un grupo similar en escuelas solo en inglés. Me sorprendió que la diferencia fuera tan clara.", en: "With a similar group in English-only schools. I was surprised the difference was so clear." },
        { speaker: "B", es: "Creo que el autor usa esos datos para responder a los que dudan.", en: "I think the author uses that data to answer those who doubt." },
      ],
    },
  },
  {
    day: 158,
    themeEs: "Las voces en contra",
    storyTitle: "El artículo",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la crítica", en: "the criticism", example: "El artículo incluye críticas comunes." },
      { es: "preocuparse", en: "to worry", example: "Algunos padres se preocupan por el inglés." },
      { es: "confundir", en: "to confuse", example: "Dicen que dos idiomas confunden." },
      { es: "responder a", en: "to respond to", example: "El autor responde a cada crítica." },
      { es: "la evidencia", en: "the evidence", example: "Presenta evidencia de varios países." },
    ],
    dialogue: {
      title: "Lo que dicen los detractores",
      situation: "En la sala de maestros, después de clases",
      lines: [
        { speaker: "A", es: "El artículo no ignora las críticas — las pone en la mesa.", en: "The article doesn't ignore the criticisms — it puts them on the table." },
        { speaker: "B", es: "¿Cuáles menciona?", en: "Which ones does it mention?" },
        { speaker: "A", es: "Que dos idiomas confunden a los niños y que el inglés se retrasa.", en: "That two languages confuse children and that English gets delayed." },
        { speaker: "B", es: "Lo que no entiendo es por qué esa idea sigue tan fuerte.", en: "What I don't understand is why that idea is still so strong." },
        { speaker: "A", es: "Creo que el autor lo explica: mucha gente no ha visto un salón bilingüe funcionando.", en: "I think the author explains it: a lot of people haven't seen a bilingual classroom working." },
        { speaker: "B", es: "Tiene sentido.", en: "That makes sense." },
        { speaker: "A", es: "Me dio gusto leer que responde con evidencia de Canadá y de escuelas aquí mismo.", en: "I was glad to read that he responds with evidence from Canada and from schools right here." },
        { speaker: "B", es: "Eso le da peso al artículo.", en: "That gives the article weight." },
      ],
    },
  },
  {
    day: 159,
    themeEs: "Mi conexión",
    storyTitle: "El artículo",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "conectar con", en: "to connect with", example: "Me conecté con la última parte." },
      { es: "el salón de ESL", en: "the ESL classroom", example: "Trabajo en un salón de ESL." },
      { es: "identificarse", en: "to identify", example: "Me identifiqué con la maestra del ejemplo." },
      { es: "la paciencia", en: "patience", example: "Habla de la paciencia que se necesita." },
      { es: "orgulloso/a", en: "proud", example: "Los padres se sienten orgullosos." },
    ],
    dialogue: {
      title: "Lo que me tocó",
      situation: "En la sala de maestros, casi vacía al final del día",
      lines: [
        { speaker: "A", es: "La última sección del artículo me conectó de verdad.", en: "The last section of the article really connected with me." },
        { speaker: "B", es: "¿De qué habla?", en: "What's it about?" },
        { speaker: "A", es: "De una maestra bilingüe en un salón como el nuestro. Me identifiqué con ella.", en: "About a bilingual teacher in a classroom like ours. I identified with her." },
        { speaker: "B", es: "¿Qué hace diferente?", en: "What does she do differently?" },
        { speaker: "A", es: "Lo que más me llamó la atención fue cómo explica a los padres que el proceso lleva tiempo.", en: "What caught my attention most was how she explains to parents that the process takes time." },
        { speaker: "B", es: "Eso lo vivimos cada semestre.", en: "We live that every semester." },
        { speaker: "A", es: "Me sorprendió que el autor terminara con una frase tan simple: «La paciencia también se enseña».", en: "I was surprised the author ended with such a simple sentence: \"Patience is taught too.\"" },
        { speaker: "B", es: "Me gustaría leerlo yo también.", en: "I'd like to read it too." },
      ],
    },
  },
  {
    day: 160,
    themeEs: "La conversación",
    storyTitle: "El artículo",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "compartir", en: "to share", example: "Te lo comparto por mensaje." },
      { es: "mandar el enlace", en: "to send the link", example: "Te mando el enlace ahora." },
      { es: "la reunión de padres", en: "the parent meeting", example: "Podríamos usarlo en la reunión de padres." },
      { es: "de acuerdo", en: "in agreement", example: "Estoy de acuerdo contigo." },
      { es: "quedarse con", en: "to take away, remember", example: "Me quedo con la idea de la paciencia." },
    ],
    dialogue: {
      title: "¿Lo leíste?",
      situation: "En la sala de maestros, Priya ya leyó el artículo",
      lines: [
        { speaker: "B", es: "Marlana, ya leí el artículo que me mandaste.", en: "Marlana, I already read the article you sent me." },
        { speaker: "A", es: "¿Qué te pareció?", en: "What did you think?" },
        { speaker: "B", es: "Me dio gusto leer que alguien lo explica tan claro. Creo que el autor conoce salones reales.", en: "I was glad to read someone explaining it so clearly. I think the author knows real classrooms." },
        { speaker: "A", es: "Lo que no entiendo es por qué no lo leen más directores.", en: "What I don't understand is why more principals don't read it." },
        { speaker: "B", es: "Tal vez porque no llega a sus manos. Podríamos compartirlo en la reunión de padres.", en: "Maybe because it doesn't reach their hands. We could share it at the parent meeting." },
        { speaker: "A", es: "Me sorprendió que al final proponga talleres para familias nuevas.", en: "I was surprised that at the end he proposes workshops for new families." },
        { speaker: "B", es: "Buena idea. Yo me quedo con lo de la paciencia.", en: "Good idea. I'm taking away the patience part." },
        { speaker: "A", es: "Yo también. Fue un buen artículo para empezar la semana.", en: "Me too. It was a good article to start the week." },
      ],
    },
  },
  {
    day: 161,
    themeEs: "Repaso: opinar",
    isRecap: true,
    vocab: [
      { es: "reaccionar", en: "to react", example: "Reaccioné leyendo en voz alta." },
      { es: "resumir", en: "to summarize", example: "Resumí el artículo en cinco frases." },
      { es: "la conclusión", en: "the conclusion", example: "La conclusión me pareció justa." },
      { es: "recomendar", en: "to recommend", example: "Lo recomendaría a cualquier maestro." },
      { es: "quedarse pensando", en: "to be left thinking", example: "Me dejó pensando toda la noche." },
    ],
    dialogue: {
      title: "El artículo en cinco reacciones",
      situation: "En la sala de maestros, repasando la semana de lectura",
      lines: [
        { speaker: "B", es: "Oye, ¿puedes resumirme tu reacción al artículo? Solo escuché partes.", en: "Hey, can you sum up your reaction to the article? I only heard parts." },
        { speaker: "A", es: "Claro. Lo que más me llamó la atención fue el título — y los datos al final.", en: "Sure. What caught my attention most was the title — and the data at the end." },
        { speaker: "B", es: "¿Y qué te sorprendió?", en: "And what surprised you?" },
        { speaker: "A", es: "Me sorprendió que respondiera a las críticas con evidencia real, no con slogans.", en: "I was surprised he answered the criticisms with real evidence, not slogans." },
        { speaker: "B", es: "¿Algo que no entendiste?", en: "Anything you didn't understand?" },
        { speaker: "A", es: "Lo que no entiendo es por qué no circula más entre los padres. Me dio gusto leer que propone talleres.", en: "What I don't understand is why it doesn't circulate more among parents. I was glad to read that he proposes workshops." },
        { speaker: "B", es: "¿Tu veredicto?", en: "Your verdict?" },
        { speaker: "A", es: "Creo que el autor escribe para maestros como nosotras. Lo compartiría en cualquier reunión.", en: "I think the author writes for teachers like us. I'd share it at any meeting." },
      ],
    },
  },
];
