import type { SpeakDay } from "../prompts/types";

/**
 * Otoño Week 9 — "¿Te enteraste?" (days 148–154).
 * Story: "Las noticias del barrio" — neighborhood news Marlana heard and shares.
 * prompt.spanish must stay verbatim with week9-frames.ts examples for the matching frameStem.
 */
export const week9SpeakDays: SpeakDay[] = [
  {
    day: 148,
    themeEs: "El café nuevo",
    themeEn: "The new café",
    missionEs: "Comparte la noticia del café nuevo con conectores de chisme y rumor.",
    missionEn: "Share the new café news using gossip and hearsay connectors.",
    line: "Un local vacío por fin con dueño — eso merece contarlo en la sala de maestros.",
    lineEn: "An empty storefront finally has an owner — that's worth telling in the teachers' lounge.",
    prompts: [
      {
        id: "d148-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear that they're opening a café on the corner?",
        spanish: "¿Te enteraste de que abren un café en la esquina?",
        situationLabel: "La noticia del rincón",
        why: "*¿Te enteraste de…?* opens gossip and neighborhood news — the natural way to share something you just learned.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "opening", es: "abren" },
          { en: "café", es: "café" },
          { en: "corner", es: "esquina" },
        ],
      },
      {
        id: "d148-vi-que",
        frameStem: "Vi que…",
        english: "I saw they already put a sign in the window.",
        spanish: "Vi que ya pusieron letrero en la ventana.",
        situationLabel: "Lo que vi con mis ojos",
        why: "*Vi que* grounds the gossip in something you actually witnessed.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "sign", es: "letrero" },
          { en: "window", es: "ventana" },
        ],
      },
      {
        id: "d148-resulta",
        frameStem: "Resulta que…",
        english: "It turns out the owner is from Colombia and brings coffee from there.",
        spanish: "Resulta que la dueña es de Colombia y trae café de allá.",
        situationLabel: "El detalle sorpresa",
        why: "*Resulta que* adds the surprising detail that makes the gossip worth repeating.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "owner", es: "dueña" },
          { en: "colombia", es: "colombia" },
          { en: "coffee", es: "café" },
        ],
      },
      {
        id: "d148-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently they're going to have guava pastries.",
        spanish: "Al parecer, van a tener pasteles de guayaba.",
        situationLabel: "Rumor sin confirmar",
        why: "*Al parecer* softens what you haven't verified — perfect for neighborhood speculation.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "guava", es: "guayaba" },
          { en: "pastries", es: "pasteles" },
        ],
      },
      {
        id: "d148-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me the owner used to have a café in Jamaica Plain.",
        spanish: "Me contaron que la dueña antes tenía un café en Jamaica Plain.",
        situationLabel: "Chisme de segunda mano",
        why: "*Me contaron que* names your source without claiming you saw it yourself.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "owner", es: "dueña" },
          { en: "used to have", es: "antes tenía" },
          { en: "café", es: "café" },
        ],
      },
    ],
  },
  {
    day: 149,
    themeEs: "El edificio",
    themeEn: "The building",
    missionEs: "Cuenta el rumor de la venta del edificio con conectores de noticia.",
    missionEn: "Tell about the building sale rumor using news connectors.",
    line: "Un aviso en el lobby cambia la conversación de toda la semana.",
    lineEn: "A notice in the lobby changes the conversation for the whole week.",
    prompts: [
      {
        id: "d149-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear they're going to sell the building?",
        spanish: "¿Te enteraste de que van a vender el edificio?",
        situationLabel: "La noticia que preocupa",
        why: "*Van a vender el edificio* — the headline that stops every neighbor in the hallway.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "sell", es: "vender" },
          { en: "building", es: "edificio" },
        ],
      },
      {
        id: "d149-vi-que",
        frameStem: "Vi que…",
        english: "I saw they put a for-sale notice in the lobby.",
        spanish: "Vi que pusieron un aviso de venta en el lobby.",
        situationLabel: "Prueba en el lobby",
        why: "*Un aviso de venta en el lobby* — the physical evidence behind the rumor.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "for-sale notice", es: "aviso de venta" },
          { en: "lobby", es: "lobby" },
        ],
      },
      {
        id: "d149-resulta",
        frameStem: "Resulta que…",
        english: "It turns out they've been negotiating in secret for months.",
        spanish: "Resulta que llevan meses negociando en secreto.",
        situationLabel: "Lo que no sabíamos",
        why: "*Llevan meses negociando en secreto* — the reveal that makes tenants feel blindsided.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "months", es: "meses" },
          { en: "negotiating", es: "negociando" },
          { en: "secret", es: "secreto" },
        ],
      },
      {
        id: "d149-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently some tenants are going to fight it legally.",
        spanish: "Al parecer, algunos inquilinos van a pelear legalmente.",
        situationLabel: "La reacción del edificio",
        why: "*Van a pelear legalmente* — the response you're hearing but haven't confirmed.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "tenants", es: "inquilinos" },
          { en: "fight legally", es: "pelear legalmente" },
        ],
      },
      {
        id: "d149-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me they called a tenants' lawyer.",
        spanish: "Me contaron que convocaron a un abogado de inquilinos.",
        situationLabel: "Organizándose",
        why: "*Convocaron a un abogado* — secondhand news about tenants getting organized.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "called", es: "convocaron" },
          { en: "tenants' lawyer", es: "abogado de inquilinos" },
        ],
      },
    ],
  },
  {
    day: 150,
    themeEs: "La boda",
    themeEn: "The wedding",
    missionEs: "Comparte la noticia de la boda del tercero con conectores de chisme.",
    missionEn: "Share the third-floor wedding news using gossip connectors.",
    line: "Una boda en el edificio es chisme garantizado.",
    lineEn: "A wedding in the building is guaranteed gossip.",
    prompts: [
      {
        id: "d150-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear about the third-floor couple's wedding?",
        spanish: "¿Te enteraste de la boda de los del tercero?",
        situationLabel: "La boda del edificio",
        why: "*Los del tercero* — how neighbors refer to each other without names.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "wedding", es: "boda" },
          { en: "third floor", es: "tercero" },
        ],
      },
      {
        id: "d150-vi-que",
        frameStem: "Vi que…",
        english: "I saw a huge decoration package arrived for them.",
        spanish: "Vi que les llegó un paquete enorme de decoración.",
        situationLabel: "Paquete en la puerta",
        why: "*Un paquete enorme de decoración* — visual proof the wedding is real.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "huge package", es: "paquete enorme" },
          { en: "decoration", es: "decoración" },
        ],
      },
      {
        id: "d150-resulta",
        frameStem: "Resulta que…",
        english: "It turns out the ceremony is at the botanical garden.",
        spanish: "Resulta que la ceremonia es en el jardín botánico.",
        situationLabel: "El lugar de la ceremonia",
        why: "*El jardín botánico* — the detail that makes the gossip more interesting.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "ceremony", es: "ceremonia" },
          { en: "botanical garden", es: "jardín botánico" },
        ],
      },
      {
        id: "d150-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently they're going to hire the neighborhood restaurant.",
        spanish: "Al parecer, van a contratar al restaurante del barrio.",
        situationLabel: "El catering",
        why: "*El restaurante del barrio* — local detail that connects gossip to community.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "hire", es: "contratar" },
          { en: "neighborhood restaurant", es: "restaurante del barrio" },
        ],
      },
      {
        id: "d150-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me they asked permission to use the courtyard.",
        spanish: "Me contaron que pidieron permiso para usar el patio.",
        situationLabel: "Fiesta en el patio",
        why: "*Pidieron permiso para usar el patio* — the part that affects everyone in the building.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "permission", es: "permiso" },
          { en: "courtyard", es: "patio" },
        ],
      },
    ],
  },
  {
    day: 151,
    themeEs: "La construcción",
    themeEn: "The construction",
    missionEs: "Comparte lo que sabes de la obra en la calle con conectores de noticia.",
    missionEn: "Share what you know about the street work using news connectors.",
    line: "Conos naranjas en la acera — eso es noticia antes del lunes.",
    lineEn: "Orange cones on the sidewalk — that's news before Monday.",
    prompts: [
      {
        id: "d151-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear about the construction on our street?",
        spanish: "¿Te enteraste de la construcción en nuestra calle?",
        situationLabel: "Obra en la cuadra",
        why: "*Nuestra calle* — construction news hits different when it's outside your door.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "construction", es: "construcción" },
          { en: "our street", es: "nuestra calle" },
        ],
      },
      {
        id: "d151-vi-que",
        frameStem: "Vi que…",
        english: "I saw they left orange cones there since last night.",
        spanish: "Vi que dejaron conos naranjas desde anoche.",
        situationLabel: "Conos desde anoche",
        why: "*Desde anoche* — the timing detail that means Monday will be rough.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "orange cones", es: "conos naranjas" },
          { en: "since last night", es: "desde anoche" },
        ],
      },
      {
        id: "d151-resulta",
        frameStem: "Resulta que…",
        english: "It turns out they're going to replace the water pipes.",
        spanish: "Resulta que van a cambiar las tuberías de agua.",
        situationLabel: "Qué van a hacer",
        why: "*Cambiar las tuberías de agua* — the scope that explains six weeks of noise.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "replace", es: "cambiar" },
          { en: "water pipes", es: "tuberías de agua" },
        ],
      },
      {
        id: "d151-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently the detour goes through the parallel street.",
        spanish: "Al parecer, el desvío pasa por la calle paralela.",
        situationLabel: "La ruta alterna",
        why: "*La calle paralela* — the detour detail every commuter needs.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "detour", es: "desvío" },
          { en: "parallel street", es: "calle paralela" },
        ],
      },
      {
        id: "d151-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me last time it took twice as long.",
        spanish: "Me contaron que la última vez tardaron el doble.",
        situationLabel: "Experiencia pasada",
        why: "*Tardaron el doble* — secondhand warning from neighbors who've been through it.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "last time", es: "última vez" },
          { en: "twice as long", es: "el doble" },
        ],
      },
    ],
  },
  {
    day: 152,
    themeEs: "Vecinos nuevos",
    themeEn: "New neighbors",
    missionEs: "Cuenta la mudanza de la familia nueva con conectores de chisme.",
    missionEn: "Tell about the new family's move using gossip connectors.",
    line: "Un camión de mudanzas en el edificio despierta la curiosidad de todos.",
    lineEn: "A moving truck in the building wakes everyone's curiosity.",
    prompts: [
      {
        id: "d152-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear about the new family on the first floor?",
        spanish: "¿Te enteraste de la familia nueva del primer piso?",
        situationLabel: "Familia nueva",
        why: "*La familia nueva del primer piso* — how building gossip always starts.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "new family", es: "familia nueva" },
          { en: "first floor", es: "primer piso" },
        ],
      },
      {
        id: "d152-vi-que",
        frameStem: "Vi que…",
        english: "I saw a moving truck arrived Saturday.",
        spanish: "Vi que llegó un camión de mudanzas el sábado.",
        situationLabel: "Camión el sábado",
        why: "*El sábado* — past tense for the move you witnessed.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "moving truck", es: "camión de mudanzas" },
          { en: "saturday", es: "sábado" },
        ],
      },
      {
        id: "d152-resulta",
        frameStem: "Resulta que…",
        english: "It turns out they're from Chicago and moved for work.",
        spanish: "Resulta que vienen de Chicago y se mudan por trabajo.",
        situationLabel: "De dónde vienen",
        why: "*Se mudan por trabajo* — the backstory that makes new neighbors less mysterious.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "chicago", es: "chicago" },
          { en: "moved for work", es: "por trabajo" },
        ],
      },
      {
        id: "d152-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently they're very friendly.",
        spanish: "Al parecer, son muy amables.",
        situationLabel: "Primera impresión",
        why: "*Son muy amables* — the soft judgment based on one hallway encounter.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "friendly", es: "amables" },
        ],
      },
      {
        id: "d152-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me the building manager gave them keys Friday.",
        spanish: "Me contaron que el administrador les dio las llaves el viernes.",
        situationLabel: "Detalle del administrador",
        why: "*El administrador les dio las llaves* — the kind of detail only building gossip carries.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "building manager", es: "administrador" },
          { en: "keys", es: "llaves" },
          { en: "friday", es: "viernes" },
        ],
      },
    ],
  },
  {
    day: 153,
    themeEs: "La reunión",
    themeEn: "The meeting",
    missionEs: "Comparte la noticia de la reunión del barrio con conectores de chisme.",
    missionEn: "Share the neighborhood meeting news using gossip connectors.",
    line: "Un flyer en la panadería vale más que un correo que nadie lee.",
    lineEn: "A flyer at the bakery is worth more than an email nobody reads.",
    prompts: [
      {
        id: "d153-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear about the neighborhood meeting Thursday?",
        spanish: "¿Te enteraste de la reunión del barrio el jueves?",
        situationLabel: "Reunión del jueves",
        why: "*La reunión del barrio el jueves* — the event that ties all the week's news together.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "neighborhood meeting", es: "reunión del barrio" },
          { en: "thursday", es: "jueves" },
        ],
      },
      {
        id: "d153-vi-que",
        frameStem: "Vi que…",
        english: "I saw they posted a flyer at the bakery.",
        spanish: "Vi que pegaron un flyer en la panadería.",
        situationLabel: "Flyer en la panadería",
        why: "*La panadería* — where neighborhood news actually reaches people.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "flyer", es: "flyer" },
          { en: "bakery", es: "panadería" },
        ],
      },
      {
        id: "d153-resulta",
        frameStem: "Resulta que…",
        english: "It turns out the fifth-floor neighbor is organizing it.",
        spanish: "Resulta que la organiza la vecina del quinto piso.",
        situationLabel: "Quién organiza",
        why: "*La vecina del quinto piso* — naming the organizer makes the gossip personal.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "organizing", es: "organiza" },
          { en: "fifth floor", es: "quinto piso" },
        ],
      },
      {
        id: "d153-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently the hottest topic is the building sale.",
        spanish: "Al parecer, el tema más caliente es la venta del edificio.",
        situationLabel: "Tema principal",
        why: "*El tema más caliente* — the agenda item everyone will show up for.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "hottest topic", es: "tema más caliente" },
          { en: "building sale", es: "venta del edificio" },
        ],
      },
      {
        id: "d153-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me we should both go.",
        spanish: "Me contaron que deberíamos ir las dos.",
        situationLabel: "Invitación indirecta",
        why: "*Deberíamos ir las dos* — secondhand encouragement to show up together.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "we should go", es: "deberíamos ir" },
          { en: "both", es: "las dos" },
        ],
      },
    ],
  },
  {
    day: 154,
    themeEs: "Repaso: te enteraste",
    themeEn: "Review: did you hear…",
    missionEs: "Resume toda la semana del barrio en cinco frases de chisme y noticia.",
    missionEn: "Summarize the whole neighborhood week in five gossip and news sentences.",
    line: "Una semana de noticias del barrio cabe en cinco conectores, si eliges bien.",
    lineEn: "A week of neighborhood news fits in five connectors, if you choose well.",
    prompts: [
      {
        id: "d154-te-enteraste",
        frameStem: "¿Te enteraste de…?",
        english: "Did you hear about everything that happened in the neighborhood this week?",
        spanish: "¿Te enteraste de todo lo que pasó en el barrio esta semana?",
        situationLabel: "Toda la semana",
        why: "*Todo lo que pasó en el barrio* — the opening hook for a week of gossip.",
        wordHints: [
          { en: "did you hear", es: "te enteraste" },
          { en: "everything", es: "todo" },
          { en: "neighborhood", es: "barrio" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d154-vi-que",
        frameStem: "Vi que…",
        english: "I saw the neighborhood changed more in a week than in a year.",
        spanish: "Vi que el barrio cambió más en una semana que en un año.",
        situationLabel: "Cambio visible",
        why: "*Más en una semana que en un año* — the visual summary of a busy week.",
        wordHints: [
          { en: "i saw", es: "vi que" },
          { en: "neighborhood", es: "barrio" },
          { en: "changed", es: "cambió" },
          { en: "a week", es: "una semana" },
        ],
      },
      {
        id: "d154-resulta",
        frameStem: "Resulta que…",
        english: "It turns out the café owner knows the bride from the third floor.",
        spanish: "Resulta que la dueña del café conoce a la novia del tercero.",
        situationLabel: "Todo conectado",
        why: "*Conoce a la novia del tercero* — the surprising link that makes neighborhood gossip satisfying.",
        wordHints: [
          { en: "it turns out", es: "resulta que" },
          { en: "café owner", es: "dueña del café" },
          { en: "bride", es: "novia" },
          { en: "third floor", es: "tercero" },
        ],
      },
      {
        id: "d154-al-parecer",
        frameStem: "Al parecer…",
        english: "Apparently the neighborhood is waking up.",
        spanish: "Al parecer, el barrio se está despertando.",
        situationLabel: "El ánimo del barrio",
        why: "*Se está despertando* — present progressive for a trend you're sensing.",
        wordHints: [
          { en: "apparently", es: "al parecer" },
          { en: "neighborhood", es: "barrio" },
          { en: "waking up", es: "despertando" },
        ],
      },
      {
        id: "d154-me-contaron",
        frameStem: "Me contaron que…",
        english: "They told me we should go together Thursday.",
        spanish: "Me contaron que deberíamos ir juntas el jueves.",
        situationLabel: "Ir juntas",
        why: "*Ir juntas el jueves* — the call to action that closes the week's gossip arc.",
        wordHints: [
          { en: "they told me", es: "me contaron que" },
          { en: "go together", es: "ir juntas" },
          { en: "thursday", es: "jueves" },
        ],
      },
    ],
  },
];
