import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 1 — "Muletillas I" (days 183–189).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week1-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek1SpeakDays: SpeakDay[] = [
  {
    day: 183,
    themeEs: "El primer intercambio",
    themeEn: "The first exchange",
    missionEs: "Preséntate sin pedir perdón ni una vez.",
    missionEn: "Introduce yourself without apologizing once.",
    line: "El silencio se llena con una palabra, no con una disculpa.",
    lineEn: "Silence gets filled with a word, not an apology.",
    prompts: [
      {
        id: "d183-pues",
        frameStem: "Pues…",
        english: "Well — honestly, I'd never done a language exchange before.",
        spanish: "Pues, la verdad es que nunca había hecho un intercambio.",
        situationLabel: "Primer café con Camila",
        why: "*Pues* is what this app is named after: it costs nothing and buys you a whole second before the sentence has to exist.",
        wordHints: [
          { en: "honestly", es: "la verdad es que" },
          { en: "never", es: "nunca" },
          { en: "had done", es: "había hecho" },
          { en: "exchange", es: "un intercambio" },
        ],
      },
      {
        id: "d183-bueno",
        frameStem: "Bueno…",
        english: "Okay, let's start with something easy.",
        spanish: "Bueno, empecemos por algo fácil.",
        situationLabel: "Acordando las reglas",
        why: "*Bueno* nudges a conversation forward without shoving it — the gentlest possible transition.",
        wordHints: [
          { en: "let's start", es: "empecemos" },
          { en: "with", es: "por" },
          { en: "something easy", es: "algo fácil" },
        ],
      },
      {
        id: "d183-o-sea",
        frameStem: "O sea…",
        english: "I mean, I teach adults, not kids.",
        spanish: "O sea, doy clases a adultos, no a niños.",
        situationLabel: "Explicando tu trabajo",
        why: "*O sea* is the second attempt at a sentence you already started — the most common repair move in spoken Spanish.",
        wordHints: [
          { en: "i teach", es: "doy clases" },
          { en: "adults", es: "adultos" },
          { en: "kids", es: "niños" },
        ],
      },
      {
        id: "d183-es-que",
        frameStem: "Es que…",
        english: "The thing is, I understand everything and then I go quiet.",
        spanish: "Es que entiendo todo y luego me quedo callada.",
        situationLabel: "La confesión de siempre",
        why: "*Es que* gives the reason behind something — much warmer and far more spoken than opening with *porque*.",
        wordHints: [
          { en: "i understand", es: "entiendo" },
          { en: "everything", es: "todo" },
          { en: "then", es: "luego" },
          { en: "i go quiet", es: "me quedo callada" },
        ],
      },
      {
        id: "d183-a-ver",
        frameStem: "A ver…",
        english: "Let's see — where do I start?",
        spanish: "A ver, ¿por dónde empiezo?",
        situationLabel: "Antes de la primera respuesta",
        why: "*A ver* is thinking out loud with the door open — it tells Camila you're working on it, not lost.",
        wordHints: [
          { en: "where", es: "por dónde" },
          { en: "do i start", es: "empiezo" },
        ],
      },
    ],
  },
  {
    day: 184,
    themeEs: "Ganar tiempo",
    themeEn: "Buying time",
    missionEs: "Contesta una pregunta difícil sin quedarte en blanco.",
    missionEn: "Answer a hard question without going blank.",
    line: "No necesitas la respuesta ya. Necesitas un segundo.",
    lineEn: "You don't need the answer yet. You need a second.",
    prompts: [
      {
        id: "d184-pues",
        frameStem: "Pues…",
        english: "Well, it depends on the day, honestly.",
        spanish: "Pues, depende del día, la verdad.",
        situationLabel: "Una pregunta sin respuesta corta",
        why: "*Pues* at the front and *la verdad* at the back — you've wrapped a four-word answer in two stalls and it sounds thoughtful.",
        wordHints: [
          { en: "it depends", es: "depende" },
          { en: "on the day", es: "del día" },
          { en: "honestly", es: "la verdad" },
        ],
      },
      {
        id: "d184-bueno",
        frameStem: "Bueno…",
        english: "Okay, let me think about it for a second.",
        spanish: "Bueno, déjame pensarlo un segundo.",
        situationLabel: "Pidiendo un momento",
        why: "Asking for the second out loud is better than taking it silently — the pause stops feeling like a failure.",
        wordHints: [
          { en: "let me", es: "déjame" },
          { en: "think about it", es: "pensarlo" },
          { en: "a second", es: "un segundo" },
        ],
      },
      {
        id: "d184-o-sea",
        frameStem: "O sea…",
        english: "I mean, the problem isn't understanding, it's answering.",
        spanish: "O sea, el problema no es entender, es contestar.",
        situationLabel: "Nombrando el problema real",
        why: "This is the whole reason you're doing this — worth being able to say it in Spanish, out loud, to someone.",
        wordHints: [
          { en: "the problem", es: "el problema" },
          { en: "understanding", es: "entender" },
          { en: "answering", es: "contestar" },
        ],
      },
      {
        id: "d184-es-que",
        frameStem: "Es que…",
        english: "The thing is, in my head the sentence is already finished.",
        spanish: "Es que en mi cabeza la frase ya está lista.",
        situationLabel: "Por qué se siente tan lento",
        why: "*Ya está lista* — already ready. The gap between the sentence inside and the sentence out loud is exactly what fillers cover.",
        wordHints: [
          { en: "in my head", es: "en mi cabeza" },
          { en: "the sentence", es: "la frase" },
          { en: "already", es: "ya" },
          { en: "is ready", es: "está lista" },
        ],
      },
      {
        id: "d184-a-ver",
        frameStem: "A ver…",
        english: "Let's see — give me a second and I'll answer you.",
        spanish: "A ver, dame un segundo y te contesto.",
        situationLabel: "Sosteniendo tu turno",
        why: "This is a complete, polite answer all by itself. It holds your turn while you build the real one.",
        wordHints: [
          { en: "give me", es: "dame" },
          { en: "a second", es: "un segundo" },
          { en: "i'll answer you", es: "te contesto" },
        ],
      },
    ],
  },
  {
    day: 185,
    themeEs: "No encuentro la palabra",
    themeEn: "I can't find the word",
    missionEs: "Describe algo sin saber cómo se llama.",
    missionEn: "Describe something without knowing its name.",
    line: "Si no te sale la palabra, dale la vuelta.",
    lineEn: "If the word won't come, go around it.",
    prompts: [
      {
        id: "d185-pues",
        frameStem: "Pues…",
        english: "Well, the word just left me.",
        spanish: "Pues, se me fue la palabra.",
        situationLabel: "En blanco a media frase",
        why: "*Se me fue la palabra* — the word left, on its own. Spanish blames the word, not you.",
        wordHints: [
          { en: "left me", es: "se me fue" },
          { en: "the word", es: "la palabra" },
        ],
      },
      {
        id: "d185-bueno",
        frameStem: "Bueno…",
        english: "Okay, I forgot the name, but I know what it's for.",
        spanish: "Bueno, olvidé el nombre, pero sé para qué sirve.",
        situationLabel: "Cambiando de estrategia",
        why: "Knowing what something is *for* is usually enough to get the word handed to you.",
        wordHints: [
          { en: "i forgot", es: "olvidé" },
          { en: "the name", es: "el nombre" },
          { en: "i know", es: "sé" },
          { en: "what it's for", es: "para qué sirve" },
        ],
      },
      {
        id: "d185-o-sea",
        frameStem: "O sea…",
        english: "I mean, it's the thing you use to put pages together.",
        spanish: "O sea, es lo que usas para unir hojas.",
        situationLabel: "Describiendo la engrapadora",
        why: "Talking around an object you can't name is a real skill, not a failure — *o sea* announces the description is coming.",
        wordHints: [
          { en: "it's the thing", es: "es lo que" },
          { en: "you use", es: "usas" },
          { en: "to put together", es: "para unir" },
          { en: "pages", es: "hojas" },
        ],
      },
      {
        id: "d185-es-que",
        frameStem: "Es que…",
        english: "The thing is, I use it every day and I don't know its name.",
        spanish: "Es que la uso todos los días y no sé su nombre.",
        situationLabel: "La ironía del salón",
        why: "This happens to every adult learner — the most familiar objects are the ones you never looked up.",
        wordHints: [
          { en: "i use it", es: "la uso" },
          { en: "every day", es: "todos los días" },
          { en: "i don't know", es: "no sé" },
          { en: "its name", es: "su nombre" },
        ],
      },
      {
        id: "d185-a-ver",
        frameStem: "A ver…",
        english: "Let's see — how do you say \"stapler\" in Spanish?",
        spanish: "A ver, ¿cómo se dice stapler en español?",
        situationLabel: "Preguntando directamente",
        why: "Dropping the English word inside a Spanish question is what real bilinguals do. Ask, take the word, keep going.",
        wordHints: [
          { en: "how do you say", es: "cómo se dice" },
          { en: "in spanish", es: "en español" },
        ],
      },
    ],
  },
  {
    day: 186,
    themeEs: "Explicarlo de otra manera",
    themeEn: "Explaining it another way",
    missionEs: "Explica tu trabajo dos veces, de dos formas distintas.",
    missionEn: "Explain your job twice, two different ways.",
    line: "Si no te entendieron, no repitas — reformula.",
    lineEn: "If they didn't understand, don't repeat — rephrase.",
    prompts: [
      {
        id: "d186-pues",
        frameStem: "Pues…",
        english: "Well, my students are adults who just arrived.",
        spanish: "Pues, mis estudiantes son adultos que acaban de llegar.",
        situationLabel: "Contándole del salón",
        why: "*Acabar de + infinitive* is the everyday way to say something just happened — no perfect tense needed.",
        wordHints: [
          { en: "my students", es: "mis estudiantes" },
          { en: "adults", es: "adultos" },
          { en: "just arrived", es: "acaban de llegar" },
        ],
      },
      {
        id: "d186-bueno",
        frameStem: "Bueno…",
        english: "Okay, I didn't explain it well, let me say it again.",
        spanish: "Bueno, no me expliqué bien, lo repito.",
        situationLabel: "Volviendo a intentarlo",
        why: "*No me expliqué bien* puts the work on you instead of on the listener — the gracious version of \"you didn't get it\".",
        wordHints: [
          { en: "i didn't explain", es: "no me expliqué" },
          { en: "well", es: "bien" },
          { en: "i'll say it again", es: "lo repito" },
        ],
      },
      {
        id: "d186-o-sea",
        frameStem: "O sea…",
        english: "I mean, I don't teach grammar, I teach getting through the day.",
        spanish: "O sea, no enseño gramática, enseño a sobrevivir el día.",
        situationLabel: "Lo que de verdad haces",
        why: "*No X, sino Y* by way of a plain comma — the fastest way to sharpen a definition mid-sentence.",
        wordHints: [
          { en: "i don't teach", es: "no enseño" },
          { en: "grammar", es: "gramática" },
          { en: "to get through", es: "a sobrevivir" },
          { en: "the day", es: "el día" },
        ],
      },
      {
        id: "d186-es-que",
        frameStem: "Es que…",
        english: "The thing is, I go quiet in another language too.",
        spanish: "Es que yo también me quedo callada en otro idioma.",
        situationLabel: "Del otro lado del salón",
        why: "The sentence that connects your two lives — teacher and student, same room, different chair.",
        wordHints: [
          { en: "i too", es: "yo también" },
          { en: "i go quiet", es: "me quedo callada" },
          { en: "another language", es: "otro idioma" },
        ],
      },
      {
        id: "d186-a-ver",
        frameStem: "A ver…",
        english: "Let's see — do you follow me if I put it like that?",
        spanish: "A ver, ¿me entiendes si lo digo así?",
        situationLabel: "Comprobando que llegó",
        why: "Checking in mid-explanation keeps the other person with you instead of politely lost.",
        wordHints: [
          { en: "do you follow me", es: "me entiendes" },
          { en: "if i put it", es: "si lo digo" },
          { en: "like that", es: "así" },
        ],
      },
    ],
  },
  {
    day: 187,
    themeEs: "Cuando me trabo",
    themeEn: "When I get stuck",
    missionEs: "Trábate a propósito y arréglalo en español.",
    missionEn: "Get stuck on purpose and fix it in Spanish.",
    line: "Empezar de nuevo en español ya es ganar.",
    lineEn: "Starting over in Spanish is already the win.",
    prompts: [
      {
        id: "d187-pues",
        frameStem: "Pues…",
        english: "Well, I got tangled up — I'll start again.",
        spanish: "Pues, me enredé, empiezo otra vez.",
        situationLabel: "A mitad de la frase",
        why: "*Enredarse* is exactly the feeling: tangled, not broken. You untangle and continue.",
        wordHints: [
          { en: "i got tangled", es: "me enredé" },
          { en: "i'll start", es: "empiezo" },
          { en: "again", es: "otra vez" },
        ],
      },
      {
        id: "d187-bueno",
        frameStem: "Bueno…",
        english: "Okay, I've lost the thread now.",
        spanish: "Bueno, ya perdí el hilo.",
        situationLabel: "Admitiéndolo en voz alta",
        why: "Say *ya perdí el hilo* out loud and the other person helps you find it. Say nothing and you're alone with it.",
        wordHints: [
          { en: "i lost", es: "perdí" },
          { en: "the thread", es: "el hilo" },
        ],
      },
      {
        id: "d187-o-sea",
        frameStem: "O sea…",
        english: "I mean, it wasn't that — it was the opposite.",
        spanish: "O sea, no era eso, era lo contrario.",
        situationLabel: "Corrigiendo el rumbo",
        why: "You're allowed to reverse yourself mid-thought. *O sea* is the signal that a correction is coming.",
        wordHints: [
          { en: "it wasn't that", es: "no era eso" },
          { en: "the opposite", es: "lo contrario" },
        ],
      },
      {
        id: "d187-es-que",
        frameStem: "Es que…",
        english: "The thing is, I started the sentence without knowing how to end it.",
        spanish: "Es que empecé la frase sin saber cómo terminarla.",
        situationLabel: "Diagnóstico honesto",
        why: "Naming the habit is how it loosens. *Sin + infinitive* is the compact way to say \"without doing\".",
        wordHints: [
          { en: "i started", es: "empecé" },
          { en: "the sentence", es: "la frase" },
          { en: "without knowing", es: "sin saber" },
          { en: "how to end it", es: "cómo terminarla" },
        ],
      },
      {
        id: "d187-a-ver",
        frameStem: "A ver…",
        english: "Let's see — let me start over.",
        spanish: "A ver, déjame empezar de nuevo.",
        situationLabel: "El reinicio limpio",
        why: "This is the most valuable sentence of the week: it restarts you *inside* Spanish instead of dropping you into English.",
        wordHints: [
          { en: "let me", es: "déjame" },
          { en: "start over", es: "empezar de nuevo" },
        ],
      },
    ],
  },
  {
    day: 188,
    themeEs: "Ya no pido perdón",
    themeEn: "I stopped apologizing",
    missionEs: "Habla media hora sin disculparte una sola vez.",
    missionEn: "Talk for half an hour without apologizing once.",
    line: "No hablas mejor. Dejaste de frenar.",
    lineEn: "You're not speaking better. You stopped braking.",
    prompts: [
      {
        id: "d188-pues",
        frameStem: "Pues…",
        english: "Well, today I didn't apologize once.",
        spanish: "Pues, hoy no me disculpé ni una vez.",
        situationLabel: "Lo que notó Camila",
        why: "*Ni una vez* — not even once. The small intensifier that makes the claim land.",
        wordHints: [
          { en: "today", es: "hoy" },
          { en: "i didn't apologize", es: "no me disculpé" },
          { en: "not once", es: "ni una vez" },
        ],
      },
      {
        id: "d188-bueno",
        frameStem: "Bueno…",
        english: "Okay, it wasn't perfect and it doesn't matter.",
        spanish: "Bueno, no fue perfecto y no importa.",
        situationLabel: "Cerrando la sesión",
        why: "Worth saying out loud, in Spanish, until you believe it.",
        wordHints: [
          { en: "it wasn't", es: "no fue" },
          { en: "perfect", es: "perfecto" },
          { en: "it doesn't matter", es: "no importa" },
        ],
      },
      {
        id: "d188-o-sea",
        frameStem: "O sea…",
        english: "I mean, I don't speak better — I speak without braking.",
        spanish: "O sea, no hablo mejor, hablo sin frenar.",
        situationLabel: "Nombrando el cambio",
        why: "The real diagnosis of the week, in nine words. Fluency showed up as *not stopping*, not as new vocabulary.",
        wordHints: [
          { en: "i don't speak", es: "no hablo" },
          { en: "better", es: "mejor" },
          { en: "without braking", es: "sin frenar" },
        ],
      },
      {
        id: "d188-es-que",
        frameStem: "Es que…",
        english: "The thing is, every apology pulled me out of Spanish.",
        spanish: "Es que cada disculpa me sacaba del español.",
        situationLabel: "Por qué dejaste de hacerlo",
        why: "The imperfect *sacaba* makes it a repeated habit, not a single event — exactly what it was.",
        wordHints: [
          { en: "every", es: "cada" },
          { en: "apology", es: "disculpa" },
          { en: "pulled me out of", es: "me sacaba de" },
        ],
      },
      {
        id: "d188-a-ver",
        frameStem: "A ver…",
        english: "Let's see if next Thursday I talk for forty minutes.",
        spanish: "A ver si el próximo jueves hablo cuarenta minutos.",
        situationLabel: "Poniendo la próxima meta",
        why: "*A ver si…* points at something you hope for without promising it — the softest way to set a goal out loud.",
        wordHints: [
          { en: "let's see if", es: "a ver si" },
          { en: "next thursday", es: "el próximo jueves" },
          { en: "i talk", es: "hablo" },
          { en: "forty minutes", es: "cuarenta minutos" },
        ],
      },
    ],
  },
  {
    day: 189,
    themeEs: "Repaso: Muletillas I",
    themeEn: "Review: Fillers I",
    missionEs: "Usa las cinco muletillas en una sola charla.",
    missionEn: "Use all five fillers in a single conversation.",
    line: "Cinco palabras que no significan nada y lo cambian todo.",
    lineEn: "Five words that mean nothing and change everything.",
    prompts: [
      {
        id: "d189-pues",
        frameStem: "Pues…",
        english: "Well, what helped me most was not going quiet.",
        spanish: "Pues, lo que más me sirvió fue no callarme.",
        situationLabel: "El repaso de la semana",
        why: "*Lo que más me sirvió* — what helped me most. A frame you'll reuse every time you look back on something.",
        wordHints: [
          { en: "what", es: "lo que" },
          { en: "helped me most", es: "más me sirvió" },
          { en: "not going quiet", es: "no callarme" },
        ],
      },
      {
        id: "d189-bueno",
        frameStem: "Bueno…",
        english: "Okay, five words and everything changes.",
        spanish: "Bueno, cinco palabras y ya cambia todo.",
        situationLabel: "El balance",
        why: "That *ya* does real work — it means the change has already happened, not that it might.",
        wordHints: [
          { en: "five words", es: "cinco palabras" },
          { en: "changes", es: "cambia" },
          { en: "everything", es: "todo" },
        ],
      },
      {
        id: "d189-o-sea",
        frameStem: "O sea…",
        english: "I mean, I didn't gain vocabulary — I gained time.",
        spanish: "O sea, no gané vocabulario, gané tiempo.",
        situationLabel: "La lección de la semana",
        why: "The whole week in six words. Keep it — it's the argument for every filler you'll learn next week.",
        wordHints: [
          { en: "i didn't gain", es: "no gané" },
          { en: "vocabulary", es: "vocabulario" },
          { en: "i gained", es: "gané" },
          { en: "time", es: "tiempo" },
        ],
      },
      {
        id: "d189-es-que",
        frameStem: "Es que…",
        english: "The thing is, I had them in my head without using them.",
        spanish: "Es que las tenía en la cabeza sin usarlas.",
        situationLabel: "Lo que ya sabías",
        why: "This is true of most of your Spanish. Recognition was never the problem.",
        wordHints: [
          { en: "i had them", es: "las tenía" },
          { en: "in my head", es: "en la cabeza" },
          { en: "without using them", es: "sin usarlas" },
        ],
      },
      {
        id: "d189-a-ver",
        frameStem: "A ver…",
        english: "Let's see — which one do I still need to practice most?",
        spanish: "A ver, ¿cuál me falta practicar más?",
        situationLabel: "Preparando la semana dos",
        why: "*Me falta* + infinitive — what I still have left to do. Softer and far more common than *necesito*.",
        wordHints: [
          { en: "which one", es: "cuál" },
          { en: "i still need", es: "me falta" },
          { en: "to practice", es: "practicar" },
          { en: "most", es: "más" },
        ],
      },
    ],
  },
];
