import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 9 — "La junta del comité" (days 239–245).
 * A community planning meeting run entirely in Spanish, five people talking at
 * once. Marlana understands every word and can't get a single one in. The
 * real-time phase opens on the thing recognition can't solve: timing.
 */
export const invWeek9ReadingDays: ReadingDay[] = [
  {
    day: 239,
    themeEs: "No logro entrar",
    storyTitle: "La junta del comité",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la junta", en: "the meeting", example: "La junta duró noventa minutos." },
      { es: "meter la cuchara", en: "to get a word in", example: "No logré meter la cuchara ni una vez." },
      { es: "el comité", en: "the committee", example: "El comité se reúne cada dos semanas." },
      { es: "a la vez", en: "at the same time", example: "Hablaban tres a la vez." },
      { es: "quedarse con las ganas", en: "to be left wanting to", example: "Me quedé con las ganas de decirlo." },
    ],
    dialogue: {
      title: "Noventa minutos callada",
      situation: "Marlana le cuenta a Camila después de su primera junta del comité",
      lines: [
        { speaker: "A", es: "Camila, salí de esa junta con tres cosas guardadas y no dije ninguna.", en: "Camila, I left that meeting with three things saved up and I said none of them." },
        { speaker: "B", es: "¿No entendiste?", en: "Did you not understand?" },
        { speaker: "A", es: "Entendí todo. Los noventa minutos, palabra por palabra.", en: "I understood everything. All ninety minutes, word for word." },
        { speaker: "B", es: "Entonces el problema no es el español.", en: "Then the problem isn't the Spanish." },
        { speaker: "A", es: "Es que hablaban tres a la vez. Yo esperaba una pausa y no hubo ninguna en toda la tarde.", en: "The thing is, three of them were talking at once. I was waiting for a pause and there wasn't one all afternoon." },
        { speaker: "B", es: "Ay, Marlana. Nadie hace pausas. Hay que meterse.", en: "Oh, Marlana. Nobody makes pauses. You have to jump in." },
        { speaker: "A", es: "Es que me parece grosero.", en: "It seems rude to me." },
        { speaker: "B", es: "Es lo contrario. Si no te metes, los demás piensan que no te interesa. Apúntate estas cinco.", en: "It's the opposite. If you don't jump in, everyone assumes you're not interested. Write down these five." },
        { speaker: "A", es: "Dime.", en: "Tell me." },
        { speaker: "B", es: "Perdona que te interrumpa. Espera, espera. Antes de que se me olvide. Una cosa. Y sí, sí, pero.", en: "Perdona que te interrumpa. Espera, espera. Antes de que se me olvide. Una cosa. And sí, sí, pero." },
      ],
    },
  },
  {
    day: 240,
    themeEs: "Perdona que te interrumpa",
    storyTitle: "La junta del comité",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el dato", en: "the piece of information", example: "Creo que nos falta un dato." },
      { es: "la directora", en: "the principal", example: "Perdone que la interrumpa, directora." },
      { es: "el voto", en: "the vote", example: "Quiero decir algo antes del voto." },
      { es: "salir caro", en: "to be expensive", example: "Eso sale caro para el comité." },
      { es: "el presupuesto", en: "the budget", example: "Me perdí en la parte del presupuesto." },
    ],
    dialogue: {
      title: "El salón se detuvo",
      situation: "Segunda junta; Marlana lo intenta por primera vez",
      lines: [
        { speaker: "B", es: "…entonces yo digo que lo hagamos el veinte, porque el trece está el otro evento y—", en: "…so I say we do it on the twentieth, because the thirteenth is the other event and—" },
        { speaker: "A", es: "Perdona que te interrumpa, pero creo que nos falta un dato.", en: "Sorry to interrupt, but I think we're missing a piece of information." },
        { speaker: "B", es: "Dinos.", en: "Go ahead." },
        { speaker: "A", es: "Antes de que se me olvide: son cuarenta familias, no veinte. Ya confirmaron cuarenta.", en: "Before I forget: it's forty families, not twenty. Forty have already confirmed." },
        { speaker: "B", es: "¿Cuarenta? Entonces el salón chico no sirve.", en: "Forty? Then the small room won't do." },
        { speaker: "A", es: "Exacto. Y una cosa: ¿la comida la ponemos nosotros?", en: "Exactly. And one thing: are we providing the food?" },
        { speaker: "B", es: "Buena pregunta. Nadie la había hecho.", en: "Good question. Nobody had asked it." },
        { speaker: "A", es: "Sí, sí, pero en marzo nadie va a tener tiempo de cocinar. Ahí sí prefiero pedirla.", en: "Yes, yes, but in March nobody's going to have time to cook. There I'd rather we ordered it." },
        { speaker: "B", es: "Marlana, llevas cuatro intervenciones en diez minutos. La semana pasada fueron cero.", en: "Marlana, that's four contributions in ten minutes. Last week it was zero." },
      ],
    },
  },
  {
    day: 241,
    themeEs: "Espera, espera",
    storyTitle: "La junta del comité",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la convocatoria", en: "the call-out, the public notice", example: "¿Qué significa \"convocatoria\"?" },
      { es: "captar", en: "to catch (a word)", example: "No capté esa palabra." },
      { es: "quedar pendiente", en: "to be left outstanding", example: "Quedó pendiente lo de los volantes." },
      { es: "chocar", en: "to clash", example: "Ese día chocan las dos actividades." },
      { es: "asentir", en: "to nod along", example: "Dejé de asentir sin entender." },
    ],
    dialogue: {
      title: "Vas rapidísimo",
      situation: "Delia, del centro comunitario, habla muy rápido",
      lines: [
        { speaker: "B", es: "Y la convocatoria sale el lunes, con la lista, y ya para el miércoles tenemos que tener la respuesta de—", en: "And the call-out goes out Monday, with the list, and by Wednesday we have to have the answer from—" },
        { speaker: "A", es: "Espera, espera, vas rapidísimo.", en: "Hang on, hang on, you're going really fast." },
        { speaker: "B", es: "Ay, perdón. Me pasa siempre.", en: "Oh, sorry. It always happens to me." },
        { speaker: "A", es: "Perdona que te interrumpa, ¿qué significa \"convocatoria\"?", en: "Sorry to interrupt, what does \"convocatoria\" mean?" },
        { speaker: "B", es: "El aviso que mandamos para que la gente se apunte. La invitación abierta.", en: "The notice we send out for people to sign up. The open invitation." },
        { speaker: "A", es: "Gracias. Espera, espera, dijiste tres cosas juntas. Vamos una por una.", en: "Thanks. Hang on, hang on, you said three things at once. Let's go one at a time." },
        { speaker: "B", es: "Tienes razón. Empiezo de nuevo, más despacio.", en: "You're right. I'll start again, more slowly." },
        { speaker: "A", es: "Y una cosa: ¿dijiste quince o cincuenta?", en: "And one thing: did you say fifteen or fifty?" },
        { speaker: "B", es: "Cincuenta. Esa siempre confunde a todo el mundo, no solo a ti.", en: "Fifty. That one always confuses everybody, not just you." },
      ],
    },
  },
  {
    day: 242,
    themeEs: "Antes de que se me olvide",
    storyTitle: "La junta del comité",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "sumar a", en: "to add to", example: "Quiero sumar a lo que dijiste." },
      { es: "el transporte", en: "transportation", example: "Nadie ha hablado del transporte." },
      { es: "saltarse algo", en: "to skip something", example: "Nos saltamos la parte del horario." },
      { es: "cerrar un punto", en: "to close an item", example: "No cerremos ese punto todavía." },
      { es: "guardarse algo", en: "to keep something to oneself", example: "Me guardé la frase cuarenta minutos." },
    ],
    dialogue: {
      title: "Cuarenta minutos guardándola",
      situation: "Marlana lleva media junta con una frase en la cabeza",
      lines: [
        { speaker: "A", es: "Espera, espera, no cerremos ese punto todavía.", en: "Hang on, hang on, let's not close that point yet." },
        { speaker: "B", es: "Dime, Marlana.", en: "Go ahead, Marlana." },
        { speaker: "A", es: "Antes de que se me olvide: las familias pidieron que fuera más temprano. Me lo dijeron seis, no una.", en: "Before I forget: the families asked for it to be earlier. Six of them told me, not one." },
        { speaker: "B", es: "¿Seis? Eso cambia la hora entera.", en: "Six? That changes the whole time." },
        { speaker: "A", es: "Y una cosa que nadie ha mencionado: el transporte. La mitad no tiene carro.", en: "And one thing nobody has mentioned: transportation. Half of them don't have a car." },
        { speaker: "B", es: "Ay. Es verdad. Y estábamos por votar.", en: "Oh. That's true. And we were about to vote." },
        { speaker: "A", es: "Sí, sí, pero yo hablé con seis familias y dicen otra cosa. Por eso interrumpí.", en: "Yes, yes, but I talked to six families and they say otherwise. That's why I interrupted." },
        { speaker: "B", es: "Hiciste bien. ¿Y cuánto llevabas con eso adentro?", en: "You did the right thing. And how long had you been sitting on that?" },
        { speaker: "A", es: "Cuarenta minutos. Y en esos cuarenta minutos no escuché nada de lo demás.", en: "Forty minutes. And in those forty minutes I didn't hear a thing anyone else said." },
      ],
    },
  },
  {
    day: 243,
    themeEs: "Una cosa",
    storyTitle: "La junta del comité",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "encargarse de", en: "to take charge of", example: "Yo puedo encargarme de eso." },
      { es: "meterse", en: "to butt in, to jump in", example: "Perdón por meterme." },
      { es: "dejar fuera", en: "to leave out", example: "Eso deja fuera a la mitad." },
      { es: "lo que quedamos", en: "what we agreed", example: "Eso no fue lo que quedamos." },
      { es: "votar", en: "to vote", example: "Antes de votar, léelo otra vez." },
    ],
    dialogue: {
      title: "Dos palabras y ya estás dentro",
      situation: "Tercera junta; la conversación va muy rápido y nadie hace pausas",
      lines: [
        { speaker: "B", es: "—y entonces mandamos el aviso el viernes y quien conteste, contesta, y los demás—", en: "—and so we send the notice Friday and whoever answers, answers, and the rest—" },
        { speaker: "A", es: "Una cosa: yo puedo encargarme de eso.", en: "One thing: I can take care of that." },
        { speaker: "B", es: "¿De los avisos? Perfecto, gracias.", en: "The notices? Perfect, thank you." },
        { speaker: "A", es: "Una cosa más y me callo: falta decidir la hora.", en: "One more thing and I'll shut up: we still need to decide the time." },
        { speaker: "B", es: "Cierto. ¿A las seis?", en: "True. Six o'clock?" },
        { speaker: "A", es: "Sí, sí, pero eso deja fuera a la mitad. Las que salen del turno a las seis y media no llegan.", en: "Yes, yes, but that leaves half of them out. The ones who finish their shift at six thirty won't make it." },
        { speaker: "B", es: "Entonces siete.", en: "Seven, then." },
        { speaker: "A", es: "Espera, espera, Rocío, eso no fue lo que quedamos el martes. Quedamos en seis y media.", en: "Hang on, hang on, Rocío, that's not what we agreed on Tuesday. We settled on six thirty." },
        { speaker: "B", es: "Es verdad. Y fíjate: hoy no dijiste \"perdona que te interrumpa\" ni una vez. Entraste con \"una cosa\" y ya.", en: "That's true. And look: today you didn't say \"sorry to interrupt\" once. You came in with \"una cosa\" and that was it." },
      ],
    },
  },
  {
    day: 244,
    themeEs: "Sí, sí, pero",
    storyTitle: "La junta del comité",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "clave", en: "key, crucial", example: "Eso que dices es clave." },
      { es: "apoyar", en: "to back up, to support", example: "Quiero apoyar lo de Delia." },
      { es: "sostener", en: "to sustain, to keep going", example: "La parte difícil es sostenerlo cada mes." },
      { es: "en vivo", en: "live, in real time", example: "Necesitamos a alguien que traduzca en vivo." },
      { es: "comprometerse", en: "to commit", example: "Yo me comprometo a llamar a diez." },
    ],
    dialogue: {
      title: "Interrumpir para estar de acuerdo",
      situation: "Delia propone algo bueno y nadie reacciona",
      lines: [
        { speaker: "B", es: "…yo pensaba que una persona por salón podría llamar a sus familias, así nadie carga con cuarenta.", en: "…I was thinking one person per classroom could call their families, that way nobody carries forty." },
        { speaker: "A", es: "Perdona que te interrumpa, pero eso que dices es clave.", en: "Sorry to interrupt, but what you're saying is the key thing." },
        { speaker: "B", es: "¿Sí?", en: "Really?" },
        { speaker: "A", es: "Espera, espera, esa idea sí me gustó. Repítelo para que quede anotado.", en: "Hang on, hang on, I did like that idea. Say it again so it gets written down." },
        { speaker: "B", es: "Una persona por salón. Ocho llamadas cada una.", en: "One person per classroom. Eight calls each." },
        { speaker: "A", es: "Antes de que se me olvide: la idea fue de Delia, no mía. Que quede claro en el resumen.", en: "Before I forget: the idea was Delia's, not mine. Let that be clear in the summary." },
        { speaker: "B", es: "Gracias, Marlana.", en: "Thank you, Marlana." },
        { speaker: "A", es: "Sí, sí, pero la parte difícil es sostenerlo cada mes. Y una cosa: que quede claro quién llama a quién.", en: "Yes, yes, but the hard part is keeping it going every month. And one thing: let's be clear who calls whom." },
        { speaker: "B", es: "Anotado. Oye, ¿y tú no eras la que no decía nada?", en: "Noted. Hey, weren't you the one who didn't say anything?" },
      ],
    },
  },
  {
    day: 245,
    themeEs: "Repaso: Interrumpir",
    isRecap: true,
    vocab: [
      { es: "la puerta de entrada", en: "the way in", example: "Esa frase fue mi puerta de entrada." },
      { es: "la intervención", en: "the contribution (in a meeting)", example: "Nueve intervenciones en una junta." },
      { es: "grosera", en: "rude", example: "Suena grosera y no lo es." },
      { es: "de ahora en adelante", en: "from now on", example: "La voy a usar más de ahora en adelante." },
      { es: "salvarse de", en: "to be saved from", example: "Me salvó de asentir sin entender." },
    ],
    dialogue: {
      title: "Nueve veces",
      situation: "Jueves; Camila de vuelta en el café, con la cuenta de la semana",
      lines: [
        { speaker: "B", es: "A ver, cuéntame. ¿Cuántas veces hablaste en la última junta?", en: "Okay, tell me. How many times did you speak in the last meeting?" },
        { speaker: "A", es: "Nueve. Rocío las contó y me lo dijo al final.", en: "Nine. Rocío counted them and told me at the end." },
        { speaker: "B", es: "De cero a nueve en tres semanas. ¿Y cuál te sirvió más?", en: "From zero to nine in three weeks. And which one helped most?" },
        { speaker: "A", es: "Una cosa. Dos palabras y ya estás dentro. Es la que me llevo de esta semana.", en: "\"Una cosa.\" Two words and you're already in. It's the one I'm keeping from this week." },
        { speaker: "B", es: "Es la que usamos todos, sí. ¿Y la más fácil?", en: "It's the one we all use, yes. And the easiest?" },
        { speaker: "A", es: "Antes de que se me olvide resultó la más fácil de todas. Nadie te la niega nunca.", en: "\"Before I forget\" turned out the easiest of them all. Nobody ever refuses it." },
        { speaker: "B", es: "Exacto. ¿Y cuál te costó?", en: "Exactly. And which one was hard?" },
        { speaker: "A", es: "Sí, sí, pero fue la que más me costó decir. Suena grosera y no lo es.", en: "\"Yes, yes, but\" was the hardest one to say. It sounds rude and it isn't." },
        { speaker: "B", es: "Nunca lo es. Y fíjate qué semana: entendías todo desde el principio. Lo que te faltaba era el momento.", en: "It never is. And look what kind of week that was: you understood everything from the start. What you were missing was the timing." },
      ],
    },
  },
];
