import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 8 — "Es mejor que…" (days 232–238). Subjunctive chunk 4: advice.
 * Each `spanish` is copied verbatim from content/drafts/invierno/week8-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek8SpeakDays: SpeakDay[] = [
  {
    day: 232,
    themeEs: "La estudiante nueva",
    themeEn: "The new student",
    missionEs: "Dale cinco consejos a alguien que empieza de cero.",
    missionEn: "Give five pieces of advice to someone starting from zero.",
    line: "Ocho meses aquí y ni una frase en inglés. Te suena.",
    lineEn: "Eight months here and not one English sentence. Sound familiar.",
    prompts: [
      {
        id: "d232-es-mejor",
        frameStem: "Es mejor que…",
        english: "You'd be better off starting with short sentences.",
        spanish: "Es mejor que empiece con frases cortas.",
        situationLabel: "Primer día de Yesenia",
        why: "Today is usted — a new adult student, first day. Watch what happens Wednesday when she asks to be spoken to as tú.",
        wordHints: [
          { en: "it's better if", es: "es mejor que" },
          { en: "you start", es: "empiece" },
          { en: "short sentences", es: "frases cortas" },
        ],
      },
      {
        id: "d232-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that you know you're not behind.",
        spanish: "Es importante que sepa que no está atrasada.",
        situationLabel: "Lo primero que necesita oír",
        why: "*Atrasada* — behind, running late. The fear every adult beginner arrives with, named and dismissed in one line.",
        wordHints: [
          { en: "you know", es: "sepa" },
          { en: "you're not", es: "no está" },
          { en: "behind", es: "atrasada" },
        ],
      },
      {
        id: "d232-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "There's no need to apologize for arriving late.",
        spanish: "No hace falta que se disculpe por llegar tarde.",
        situationLabel: "Llegó veinte minutos tarde",
        why: "*No hace falta que* is the kindest sentence in this family — it removes an obligation the other person invented for themselves.",
        wordHints: [
          { en: "there's no need", es: "no hace falta" },
          { en: "you apologize", es: "se disculpe" },
          { en: "for arriving late", es: "por llegar tarde" },
        ],
      },
      {
        id: "d232-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest you learn one word a day, nothing more.",
        spanish: "Te sugiero que aprendas una palabra al día, nada más.",
        situationLabel: "Bajando el listón a propósito",
        why: "*Te sugiero* is softer than *te recomiendo* and much softer than *tienes que*. Advice you can turn down without awkwardness.",
        wordHints: [
          { en: "i suggest", es: "te sugiero" },
          { en: "you learn", es: "aprendas" },
          { en: "one word a day", es: "una palabra al día" },
        ],
      },
      {
        id: "d232-mas-vale",
        frameStem: "Más vale que…",
        english: "You'd better get it wrong out loud than stay silent.",
        spanish: "Más vale que te equivoques hablando que quedarte callada.",
        situationLabel: "El consejo que más te costó",
        why: "You needed a year to believe this. She gets it on day one, which is the point of having a teacher.",
        wordHints: [
          { en: "you'd better", es: "más vale que" },
          { en: "you get it wrong", es: "te equivoques" },
          { en: "speaking", es: "hablando" },
          { en: "stay silent", es: "quedarte callada" },
        ],
      },
    ],
  },
  {
    day: 233,
    themeEs: "No hace falta que te disculpes",
    themeEn: "There's no need to apologize",
    missionEs: "Quítale a alguien una obligación que se inventó.",
    missionEn: "Take away an obligation someone invented for themselves.",
    line: "Once disculpas en una hora. Las contaste porque tú hacías igual.",
    lineEn: "Eleven apologies in one hour. You counted, because you used to do the same.",
    prompts: [
      {
        id: "d233-es-mejor",
        frameStem: "Es mejor que…",
        english: "You're better off saying \"pues\" and carrying on.",
        spanish: "Es mejor que digas \"pues\" y sigas.",
        situationLabel: "El consejo de enero",
        why: "Week 1, handed on intact. You're teaching the exact thing you were taught in a café in January.",
        wordHints: [
          { en: "you say", es: "digas" },
          { en: "and you keep going", es: "y sigas" },
        ],
      },
      {
        id: "d233-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that you know nobody's grading you here.",
        spanish: "Es importante que sepas que aquí nadie te califica.",
        situationLabel: "Cambiando a tú",
        why: "Note the shift: *sepas*, not *sepa*. Yesenia asked to be spoken to as tú, and everything softens by one letter.",
        wordHints: [
          { en: "you know", es: "sepas" },
          { en: "nobody", es: "nadie" },
          { en: "grades you", es: "te califica" },
        ],
      },
      {
        id: "d233-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "There's no need to apologize every time you get something wrong.",
        spanish: "No hace falta que te disculpes cada vez que te equivocas.",
        situationLabel: "Después de la disculpa número once",
        why: "Eleven apologies in an hour. The sentence that fixes it is one that had to be said to you, once.",
        wordHints: [
          { en: "you apologize", es: "te disculpes" },
          { en: "every time", es: "cada vez que" },
          { en: "you get it wrong", es: "te equivocas" },
        ],
      },
      {
        id: "d233-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest swapping the \"sorry\" for a \"pues\".",
        spanish: "Te sugiero que cambies el \"sorry\" por un \"pues\".",
        situationLabel: "Un intercambio concreto",
        why: "Concrete beats encouraging. Replace the habit with another habit, not with a feeling.",
        wordHints: [
          { en: "you change", es: "cambies" },
          { en: "for a", es: "por un" },
        ],
      },
      {
        id: "d233-mas-vale",
        frameStem: "Más vale que…",
        english: "You'd better speak badly and loudly than well and quietly.",
        spanish: "Más vale que hables mal y fuerte que bien y bajito.",
        situationLabel: "La regla del salón",
        why: "*Bajito* — the diminutive makes quiet sound small and apologetic, which is exactly the problem being described.",
        wordHints: [
          { en: "you speak", es: "hables" },
          { en: "badly and loudly", es: "mal y fuerte" },
          { en: "well and quietly", es: "bien y bajito" },
        ],
      },
    ],
  },
  {
    day: 234,
    themeEs: "Es importante que hables mal",
    themeEn: "It's important that you speak badly",
    missionEs: "Dale permiso a alguien de hacer algo mal.",
    missionEn: "Give someone permission to be bad at something.",
    line: "Dar permiso de equivocarse es casi todo el trabajo.",
    lineEn: "Giving permission to get it wrong is most of the job.",
    prompts: [
      {
        id: "d234-es-mejor",
        frameStem: "Es mejor que…",
        english: "You're better off speaking badly today and better next month.",
        spanish: "Es mejor que hables mal hoy y mejor el mes que viene.",
        situationLabel: "Poniéndolo en orden",
        why: "The order matters and it's counterintuitive. Badly first is not a concession — it's the route.",
        wordHints: [
          { en: "you speak badly", es: "hables mal" },
          { en: "today", es: "hoy" },
          { en: "next month", es: "el mes que viene" },
        ],
      },
      {
        id: "d234-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that they understand you, not that you speak perfectly.",
        spanish: "Es importante que te entiendan, no que hables perfecto.",
        situationLabel: "La regla de la clase",
        why: "The whole method of this app, said out loud to someone else. That's how you find out you believe it.",
        wordHints: [
          { en: "they understand you", es: "te entiendan" },
          { en: "you speak", es: "hables" },
          { en: "perfectly", es: "perfecto" },
        ],
      },
      {
        id: "d234-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "There's no need to be ready in order to start.",
        spanish: "No hace falta que estés lista para empezar.",
        situationLabel: "El miedo de siempre",
        why: "Nobody is ever ready. Worth saying to a student, and worth hearing yourself say it.",
        wordHints: [
          { en: "you are ready", es: "estés lista" },
          { en: "to start", es: "para empezar" },
        ],
      },
      {
        id: "d234-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest you say five sentences a day, out loud.",
        spanish: "Te sugiero que digas cinco frases al día, en voz alta.",
        situationLabel: "La tarea más pequeña posible",
        why: "Five sentences a day is exactly what you've been doing since June. The number wasn't arbitrary.",
        wordHints: [
          { en: "you say", es: "digas" },
          { en: "five sentences", es: "cinco frases" },
          { en: "out loud", es: "en voz alta" },
        ],
      },
      {
        id: "d234-mas-vale",
        frameStem: "Más vale que…",
        english: "You'd better be misunderstood than say nothing at all.",
        spanish: "Más vale que te entiendan mal a que no digas nada.",
        situationLabel: "Cerrando la clase",
        why: "*Más vale X a que Y* — the comparison takes *a que* on the second half. Say it a few times and it stops feeling odd.",
        wordHints: [
          { en: "they misunderstand you", es: "te entiendan mal" },
          { en: "than", es: "a que" },
          { en: "you say nothing", es: "no digas nada" },
        ],
      },
    ],
  },
  {
    day: 235,
    themeEs: "Te sugiero que grabes",
    themeEn: "I'd suggest you record",
    missionEs: "Enseña un truco que a ti te funcionó.",
    missionEn: "Teach a trick that worked on you.",
    line: "Le pasas la grabadora. A ti te la pasaron hace seis semanas.",
    lineEn: "You hand her the recorder. It was handed to you six weeks ago.",
    prompts: [
      {
        id: "d235-es-mejor",
        frameStem: "Es mejor que…",
        english: "You're better off recording a voice note than writing a text.",
        spanish: "Es mejor que grabes un audio a que escribas un texto.",
        situationLabel: "Pasando el truco",
        why: "Week 4's discovery, now advice. The only thing that changed is who's saying it.",
        wordHints: [
          { en: "you record", es: "grabes" },
          { en: "a voice note", es: "un audio" },
          { en: "you write", es: "escribas" },
        ],
      },
      {
        id: "d235-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that you keep the first recording so you can compare.",
        spanish: "Es importante que guardes el primer audio para comparar.",
        situationLabel: "Para dentro de tres meses",
        why: "You have your own January recording saved. In March it becomes evidence rather than a memory.",
        wordHints: [
          { en: "you keep", es: "guardes" },
          { en: "the first voice note", es: "el primer audio" },
          { en: "to compare", es: "para comparar" },
        ],
      },
      {
        id: "d235-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "There's no need to send it to anybody.",
        spanish: "No hace falta que se lo mandes a nadie.",
        situationLabel: "Quitándole el público",
        why: "The permission that made week 4 work: nobody has to hear it. The microphone doesn't judge anybody.",
        wordHints: [
          { en: "you send it", es: "se lo mandes" },
          { en: "to anybody", es: "a nadie" },
        ],
      },
      {
        id: "d235-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest you don't delete any of them, even when you're embarrassed.",
        spanish: "Te sugiero que no borres ninguno, aunque te dé pena.",
        situationLabel: "La parte difícil",
        why: "*Aunque te dé pena* — even if it embarrasses you. Naming the feeling in advance takes most of its power away.",
        wordHints: [
          { en: "you don't delete", es: "no borres" },
          { en: "any of them", es: "ninguno" },
          { en: "even if you're embarrassed", es: "aunque te dé pena" },
        ],
      },
      {
        id: "d235-mas-vale",
        frameStem: "Más vale que…",
        english: "You'd better record thirty seconds daily than an hour on Sunday.",
        spanish: "Más vale que grabes treinta segundos diarios que una hora el domingo.",
        situationLabel: "El ritmo correcto",
        why: "The argument for a daily app in one sentence — and now she can say it to someone else too.",
        wordHints: [
          { en: "thirty seconds", es: "treinta segundos" },
          { en: "daily", es: "diarios" },
          { en: "an hour", es: "una hora" },
        ],
      },
    ],
  },
  {
    day: 236,
    themeEs: "Más vale que empieces hoy",
    themeEn: "You'd better start today",
    missionEs: "Apura a alguien sin presionarlo.",
    missionEn: "Hurry someone along without pressuring them.",
    line: "Hay una manera de decir \"apúrate\" que ayuda.",
    lineEn: "There's a way of saying \"hurry up\" that helps.",
    prompts: [
      {
        id: "d236-es-mejor",
        frameStem: "Es mejor que…",
        english: "You're better off doing a tiny bit every day.",
        spanish: "Es mejor que hagas poquito todos los días.",
        situationLabel: "Bajando la meta",
        why: "*Poquito* — the diminutive does the persuading. *Poco* sounds like a limit; *poquito* sounds like a kindness.",
        wordHints: [
          { en: "you do", es: "hagas" },
          { en: "a tiny bit", es: "poquito" },
          { en: "every day", es: "todos los días" },
        ],
      },
      {
        id: "d236-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that you forgive yourself the day you slip.",
        spanish: "Es importante que te perdones el día que falles.",
        situationLabel: "Lo que nadie dice",
        why: "Both halves matter. Keep the streak, and forgive breaking it. Say only the first and people quit at the first miss.",
        wordHints: [
          { en: "you forgive yourself", es: "te perdones" },
          { en: "the day", es: "el día" },
          { en: "you slip", es: "falles" },
        ],
      },
      {
        id: "d236-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "You don't need to do a lot — you need to do it often.",
        spanish: "No hace falta que hagas mucho, hace falta que lo hagas seguido.",
        situationLabel: "La corrección importante",
        why: "The same construction twice, negative then positive. A tidy rhetorical move you can reuse anywhere.",
        wordHints: [
          { en: "you do a lot", es: "hagas mucho" },
          { en: "you do it", es: "lo hagas" },
          { en: "often", es: "seguido" },
        ],
      },
      {
        id: "d236-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest you tell someone, so that it's real.",
        spanish: "Te sugiero que se lo cuentes a alguien, para que sea real.",
        situationLabel: "Haciéndolo público",
        why: "*Para que* takes the same shifted verb. It's the fifth family in four weeks and it needs no introduction now.",
        wordHints: [
          { en: "you tell it", es: "se lo cuentes" },
          { en: "to someone", es: "a alguien" },
          { en: "so that it's real", es: "para que sea real" },
        ],
      },
      {
        id: "d236-mas-vale",
        frameStem: "Más vale que…",
        english: "One sentence today beats a whole plan on Sunday.",
        spanish: "Más vale una frase hoy que un plan entero el domingo.",
        situationLabel: "Contra los planes",
        why: "*Más vale* + a bare noun works too. No verb needed when the comparison is obvious.",
        wordHints: [
          { en: "one sentence", es: "una frase" },
          { en: "a whole plan", es: "un plan entero" },
          { en: "on sunday", es: "el domingo" },
        ],
      },
    ],
  },
  {
    day: 237,
    themeEs: "Lo que me dijo Camila",
    themeEn: "What Camila told me",
    missionEs: "Cuenta de dónde salió un consejo que estás dando.",
    missionEn: "Say where a piece of advice you're giving came from.",
    line: "A mitad de la frase te das cuenta de quién habla.",
    lineEn: "Halfway through the sentence you realize whose words these are.",
    prompts: [
      {
        id: "d237-es-mejor",
        frameStem: "Es mejor que…",
        english: "It's better that I tell someone else than keep it to myself.",
        spanish: "Es mejor que se lo diga a alguien más y no que se me quede.",
        situationLabel: "El consejo que circula",
        why: "*Que se me quede* — that it stay stuck with me. The reflexive makes it something that happens to the advice, not to you.",
        wordHints: [
          { en: "i tell it", es: "se lo diga" },
          { en: "to someone else", es: "a alguien más" },
          { en: "it stays with me", es: "se me quede" },
        ],
      },
      {
        id: "d237-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that she knows it worked on me first.",
        spanish: "Es importante que sepa que a mí me funcionó primero.",
        situationLabel: "Diciendo la verdad",
        why: "Advice is worth more with the story attached. It stops being a rule and becomes something that happened to a person.",
        wordHints: [
          { en: "she knows", es: "sepa" },
          { en: "it worked for me", es: "me funcionó" },
          { en: "first", es: "primero" },
        ],
      },
      {
        id: "d237-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "I don't have to be finished to help someone who's starting.",
        spanish: "No hace falta que yo haya terminado para ayudar a alguien que empieza.",
        situationLabel: "Enseñando a medio camino",
        why: "The impostor feeling, answered in one line. Being three months ahead is enough to be useful.",
        wordHints: [
          { en: "i have finished", es: "yo haya terminado" },
          { en: "to help", es: "para ayudar" },
          { en: "someone who's starting", es: "alguien que empieza" },
        ],
      },
      {
        id: "d237-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest you teach it to someone else — that's how it sticks.",
        spanish: "Te sugiero que se lo enseñes a otra persona, así se te queda.",
        situationLabel: "Pasándolo adelante",
        why: "*Así se te queda* — that way it stays with you. The same reflexive as Monday's, now doing the opposite job.",
        wordHints: [
          { en: "you teach it", es: "se lo enseñes" },
          { en: "to another person", es: "a otra persona" },
          { en: "that way it sticks with you", es: "así se te queda" },
        ],
      },
      {
        id: "d237-mas-vale",
        frameStem: "Más vale que…",
        english: "I'd rather tell her about my January than hand her a rule.",
        spanish: "Más vale contarle mi enero que darle una regla.",
        situationLabel: "Enseñando con la propia historia",
        why: "Two bare infinitives compared. Once *más vale* is yours, it takes whatever shape the sentence needs.",
        wordHints: [
          { en: "tell her", es: "contarle" },
          { en: "my january", es: "mi enero" },
          { en: "give her a rule", es: "darle una regla" },
        ],
      },
    ],
  },
  {
    day: 238,
    themeEs: "Repaso: Es mejor que…",
    themeEn: "Review: It's better if…",
    missionEs: "Da consejo cinco veces sin nombrar ninguna regla.",
    missionEn: "Give advice five times without naming a single rule.",
    line: "Cuatro semanas, veinte trozos, ninguna tabla.",
    lineEn: "Four weeks, twenty chunks, no tables.",
    prompts: [
      {
        id: "d238-es-mejor",
        frameStem: "Es mejor que…",
        english: "It's better to use it twenty times than to study it for an hour.",
        spanish: "Es mejor que lo use veinte veces a que lo estudie una hora.",
        situationLabel: "El método, en una frase",
        why: "Twenty uses beat one hour. That ratio is the difference between recognizing Spanish and speaking it.",
        wordHints: [
          { en: "i use it", es: "lo use" },
          { en: "twenty times", es: "veinte veces" },
          { en: "i study it", es: "lo estudie" },
        ],
      },
      {
        id: "d238-es-importante",
        frameStem: "Es importante que…",
        english: "It's important that I notice I don't assemble these sentences anymore.",
        spanish: "Es importante que note que ya no armo estas frases.",
        situationLabel: "El cambio de la temporada",
        why: "Eight weeks ago every one of these took visible effort. The absence of effort is the result.",
        wordHints: [
          { en: "i notice", es: "note" },
          { en: "i don't assemble anymore", es: "ya no armo" },
          { en: "these sentences", es: "estas frases" },
        ],
      },
      {
        id: "d238-no-hace-falta",
        frameStem: "No hace falta que…",
        english: "I don't need to know what it's called in order to use it.",
        spanish: "No hace falta que sepa cómo se llama para usarlo.",
        situationLabel: "Sin nombrar el subjuntivo",
        why: "Four weeks, four openers a week, twenty chunks. Not one of them arrived as a conjugation.",
        wordHints: [
          { en: "i know", es: "sepa" },
          { en: "what it's called", es: "cómo se llama" },
          { en: "to use it", es: "para usarlo" },
        ],
      },
      {
        id: "d238-te-sugiero",
        frameStem: "Te sugiero que…",
        english: "I'd suggest you keep the January recording and the March one.",
        spanish: "Te sugiero que guardes los audios de enero y de marzo.",
        situationLabel: "Consejo para ti misma",
        why: "The advice pointed back at yourself. Two recordings, two months apart, and no argument possible.",
        wordHints: [
          { en: "you keep", es: "guardes" },
          { en: "the voice notes", es: "los audios" },
          { en: "january's and march's", es: "de enero y de marzo" },
        ],
      },
      {
        id: "d238-mas-vale",
        frameStem: "Más vale que…",
        english: "Better this winter is useful to somebody else too.",
        spanish: "Más vale que este invierno le sirva a alguien más.",
        situationLabel: "Cerrando la mitad de la temporada",
        why: "Half the season done. The closing move of four subjunctive weeks turns out to be giving them away.",
        wordHints: [
          { en: "this winter", es: "este invierno" },
          { en: "is useful", es: "le sirva" },
          { en: "to someone else", es: "a alguien más" },
        ],
      },
    ],
  },
];
