import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 4 — "Notas de voz" (days 204–210).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week4-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek4SpeakDays: SpeakDay[] = [
  {
    day: 204,
    themeEs: "El primer audio",
    themeEn: "The first voice note",
    missionEs: "Graba un audio de treinta segundos y mándalo.",
    missionEn: "Record a thirty-second voice note and send it.",
    line: "Hablar sola es más fácil que conversar. Empieza por ahí.",
    lineEn: "Talking alone is easier than conversing. Start there.",
    prompts: [
      {
        id: "d204-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because typing it takes me half an hour.",
        spanish: "Te mando un audio porque escribirlo me toma media hora.",
        situationLabel: "Primer audio a Camila",
        why: "*Un audio* is what a voice note is called — not *un mensaje de voz*, and certainly not *un mensaje de texto*.",
        wordHints: [
          { en: "i'm sending you", es: "te mando" },
          { en: "a voice note", es: "un audio" },
          { en: "typing it", es: "escribirlo" },
          { en: "takes me", es: "me toma" },
        ],
      },
      {
        id: "d204-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that I deleted it four times.",
        spanish: "Era para decirte que lo borré cuatro veces.",
        situationLabel: "La confesión del final",
        why: "The imperfect *era* softens everything: I *was* going to say — as if the message were already half-abandoned. Very spoken.",
        wordHints: [
          { en: "i was going to tell you", es: "era para decirte" },
          { en: "i deleted it", es: "lo borré" },
          { en: "four times", es: "cuatro veces" },
        ],
      },
      {
        id: "d204-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: I hit record and went mute.",
        spanish: "Te cuento rapidito: apreté grabar y me quedé muda.",
        situationLabel: "Lo que pasó al grabar",
        why: "*Rapidito* — the diminutive makes it friendlier and shorter-sounding than *rápido*. Pure spoken Latin American.",
        wordHints: [
          { en: "quick rundown", es: "te cuento rapidito" },
          { en: "i hit", es: "apreté" },
          { en: "record", es: "grabar" },
          { en: "i went mute", es: "me quedé muda" },
        ],
      },
      {
        id: "d204-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can whether any of it makes sense.",
        spanish: "Avísame cuando puedas si se entiende algo.",
        situationLabel: "Pidiendo opinión",
        why: "*Cuando puedas* is already a subjunctive, learned here as one whole piece. Week 6 comes back and takes it apart.",
        wordHints: [
          { en: "let me know", es: "avísame" },
          { en: "when you can", es: "cuando puedas" },
          { en: "if it's understandable", es: "si se entiende" },
        ],
      },
      {
        id: "d204-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, just message me and I'll do it over.",
        spanish: "Cualquier cosa, me escribes y lo repito.",
        situationLabel: "Cerrando el audio",
        why: "The go-to sign-off. That present tense *me escribes* is doing the work of a command — gentler than *escríbeme*.",
        wordHints: [
          { en: "anything at all", es: "cualquier cosa" },
          { en: "message me", es: "me escribes" },
          { en: "i'll do it over", es: "lo repito" },
        ],
      },
    ],
  },
  {
    day: 205,
    themeEs: "Sin borrar",
    themeEn: "Without deleting",
    missionEs: "Manda la primera toma, con errores y todo.",
    missionEn: "Send the first take, mistakes and all.",
    line: "Borrar era lo que te frenaba, no los errores.",
    lineEn: "Deleting was what slowed you down, not the mistakes.",
    prompts: [
      {
        id: "d205-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because this time I didn't delete it.",
        spanish: "Te mando un audio porque esta vez no lo borré.",
        situationLabel: "La primera toma, entera",
        why: "One sentence, one whole habit reversed. Notice you had to change nothing about your Spanish to do it.",
        wordHints: [
          { en: "this time", es: "esta vez" },
          { en: "i didn't delete it", es: "no lo borré" },
        ],
      },
      {
        id: "d205-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that this one has mistakes and I sent it anyway.",
        spanish: "Era para decirte que este tiene errores y lo mandé igual.",
        situationLabel: "Avisando de los errores",
        why: "*Lo mandé igual* — I sent it anyway. *Igual* here means \"all the same\", not \"equally\".",
        wordHints: [
          { en: "this one has", es: "este tiene" },
          { en: "mistakes", es: "errores" },
          { en: "i sent it anyway", es: "lo mandé igual" },
        ],
      },
      {
        id: "d205-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: there's a dog barking in the background.",
        spanish: "Te cuento rapidito: se oye un perro ladrando al fondo.",
        situationLabel: "Lo que quedó grabado",
        why: "Real voice notes have dogs in them. The imperfect audio is part of why they're easier than a phone call.",
        wordHints: [
          { en: "you can hear", es: "se oye" },
          { en: "a dog barking", es: "un perro ladrando" },
          { en: "in the background", es: "al fondo" },
        ],
      },
      {
        id: "d205-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can whether it sounds natural like this.",
        spanish: "Avísame cuando puedas si suena natural así.",
        situationLabel: "La pregunta de siempre",
        why: "Asking about *natural* rather than *correcto* is the right question for this season.",
        wordHints: [
          { en: "if it sounds", es: "si suena" },
          { en: "natural", es: "natural" },
          { en: "like this", es: "así" },
        ],
      },
      {
        id: "d205-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, just message me — I won't be offended.",
        spanish: "Cualquier cosa, me escribes y no me ofendo.",
        situationLabel: "Abriendo la puerta a la corrección",
        why: "Saying it out loud makes the correction easier for both of you.",
        wordHints: [
          { en: "and i won't be offended", es: "y no me ofendo" },
        ],
      },
    ],
  },
  {
    day: 206,
    themeEs: "Dos minutos seguidos",
    themeEn: "Two straight minutes",
    missionEs: "Graba dos minutos sin parar ni una vez.",
    missionEn: "Record two minutes without stopping once.",
    line: "Dos minutos era la meta del otoño. Hoy los tienes, sola.",
    lineEn: "Two minutes was the fall's goal. Today you have them, alone.",
    prompts: [
      {
        id: "d206-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because today two straight minutes came out.",
        spanish: "Te mando un audio porque hoy me salieron dos minutos seguidos.",
        situationLabel: "El audio largo",
        why: "*Me salieron* — they came out of me. Spanish lets the achievement happen *to* you, which is honest about how it feels.",
        wordHints: [
          { en: "came out for me", es: "me salieron" },
          { en: "two minutes", es: "dos minutos" },
          { en: "straight", es: "seguidos" },
        ],
      },
      {
        id: "d206-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that I didn't stop once.",
        spanish: "Era para decirte que no paré ni una vez.",
        situationLabel: "Lo importante del audio",
        why: "Two uninterrupted minutes is Otoño's whole goal, reached alone, into a phone. Worth noticing out loud.",
        wordHints: [
          { en: "i didn't stop", es: "no paré" },
          { en: "not once", es: "ni una vez" },
        ],
      },
      {
        id: "d206-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: I used all ten fillers in two minutes.",
        spanish: "Te cuento rapidito: usé las diez muletillas en dos minutos.",
        situationLabel: "El inventario",
        why: "Three weeks of fillers, all of them showing up unprompted in a single unbroken stretch.",
        wordHints: [
          { en: "i used", es: "usé" },
          { en: "the ten fillers", es: "las diez muletillas" },
        ],
      },
      {
        id: "d206-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can how far you got listening.",
        spanish: "Avísame cuando puedas hasta dónde llegaste escuchando.",
        situationLabel: "Preguntando si aguantó",
        why: "*Hasta dónde llegaste* — how far you got. Useful for stories, meetings, books, and long voice notes.",
        wordHints: [
          { en: "how far", es: "hasta dónde" },
          { en: "you got", es: "llegaste" },
          { en: "listening", es: "escuchando" },
        ],
      },
      {
        id: "d206-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, just message me if I went off on tangents.",
        spanish: "Cualquier cosa, me escribes si me fui por las ramas.",
        situationLabel: "Por si te fuiste del tema",
        why: "*Irse por las ramas* — to go off on tangents, literally \"to go off into the branches\".",
        wordHints: [
          { en: "if i went off on tangents", es: "si me fui por las ramas" },
        ],
      },
    ],
  },
  {
    day: 207,
    themeEs: "Escucharme a mí misma",
    themeEn: "Hearing myself",
    missionEs: "Escucha un audio tuyo entero y descríbelo.",
    missionEn: "Listen to a whole recording of yourself and describe it.",
    line: "El pánico está por dentro. Por fuera suenas tranquila.",
    lineEn: "The panic is on the inside. On the outside you sound calm.",
    prompts: [
      {
        id: "d207-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because I just listened to myself and I want to tell you.",
        spanish: "Te mando un audio porque acabo de escucharme y quiero contarte.",
        situationLabel: "Después de darle play",
        why: "*Acabo de + infinitive* — I've just done it. The freshest possible past in Spanish.",
        wordHints: [
          { en: "i just", es: "acabo de" },
          { en: "listened to myself", es: "escucharme" },
          { en: "i want to tell you", es: "quiero contarte" },
        ],
      },
      {
        id: "d207-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that I sound slower than I thought.",
        spanish: "Era para decirte que sueno más lenta de lo que creía.",
        situationLabel: "La primera sorpresa",
        why: "*Más … de lo que creía* — more … than I thought. A comparison against your own expectation.",
        wordHints: [
          { en: "i sound", es: "sueno" },
          { en: "slower", es: "más lenta" },
          { en: "than i thought", es: "de lo que creía" },
        ],
      },
      {
        id: "d207-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: my accent isn't as bad as I thought.",
        spanish: "Te cuento rapidito: mi acento no es tan malo como pensaba.",
        situationLabel: "La segunda sorpresa",
        why: "Nobody hears their own accent accurately until they record it. Almost always, it's better news than expected.",
        wordHints: [
          { en: "my accent", es: "mi acento" },
          { en: "isn't as bad", es: "no es tan malo" },
          { en: "as i thought", es: "como pensaba" },
        ],
      },
      {
        id: "d207-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can what sounds odd to you.",
        spanish: "Avísame cuando puedas qué te suena raro a ti.",
        situationLabel: "Pidiendo otro oído",
        why: "You can't hear your own habits. Someone else can, in about four seconds.",
        wordHints: [
          { en: "what sounds", es: "qué suena" },
          { en: "odd", es: "raro" },
          { en: "to you", es: "a ti" },
        ],
      },
      {
        id: "d207-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, just message me your honest opinion.",
        spanish: "Cualquier cosa, me escribes tu opinión sincera.",
        situationLabel: "Pidiendo la verdad",
        why: "*Sincera* rather than *honesta* — the more natural adjective here.",
        wordHints: [
          { en: "your opinion", es: "tu opinión" },
          { en: "honest", es: "sincera" },
        ],
      },
    ],
  },
  {
    day: 208,
    themeEs: "Audios del colegio",
    themeEn: "Voice notes at school",
    missionEs: "Mándale un audio en español a alguien del trabajo.",
    missionEn: "Send a Spanish voice note to someone from work.",
    line: "La persona que habla español siempre estuvo ahí.",
    lineEn: "The Spanish speaker was always there.",
    prompts: [
      {
        id: "d208-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because today I sent one to a colleague at school.",
        spanish: "Te mando un audio porque hoy le mandé uno a una compañera del colegio.",
        situationLabel: "Contándole a Camila",
        why: "*Una compañera* is a coworker or classmate — warmer and more common than *colega* in most of Latin America.",
        wordHints: [
          { en: "i sent one", es: "le mandé uno" },
          { en: "a colleague", es: "una compañera" },
          { en: "from school", es: "del colegio" },
        ],
      },
      {
        id: "d208-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that Rocío answered with another voice note.",
        spanish: "Era para decirte que Rocío me contestó con otro audio.",
        situationLabel: "La respuesta de Rocío",
        why: "A reply in kind means the door is open. That's a practice partner you didn't have to find.",
        wordHints: [
          { en: "answered me", es: "me contestó" },
          { en: "with another", es: "con otro" },
          { en: "voice note", es: "audio" },
        ],
      },
      {
        id: "d208-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: we'd never spoken Spanish at school before.",
        spanish: "Te cuento rapidito: nunca habíamos hablado en español en el colegio.",
        situationLabel: "Ocho años en el mismo edificio",
        why: "The Spanish speaker two doors down had always been there. What changed was you opening your mouth.",
        wordHints: [
          { en: "we had never", es: "nunca habíamos" },
          { en: "spoken", es: "hablado" },
          { en: "at school", es: "en el colegio" },
        ],
      },
      {
        id: "d208-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can — I know you're on shift.",
        spanish: "Avísame cuando puedas, sé que estás en turno.",
        situationLabel: "Sin presionar a Camila",
        why: "*Estar en turno* — to be on shift. Worth having when your practice partner works nights.",
        wordHints: [
          { en: "i know", es: "sé" },
          { en: "you're on shift", es: "estás en turno" },
        ],
      },
      {
        id: "d208-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, just message me when you get out of the hospital.",
        spanish: "Cualquier cosa, me escribes cuando salgas del hospital.",
        situationLabel: "Cerrando sin apuro",
        why: "*Cuando salgas* — another subjunctive chunk, arriving before the grammar lesson does. Learn the phrase, not the rule.",
        wordHints: [
          { en: "when you get out", es: "cuando salgas" },
          { en: "the hospital", es: "el hospital" },
        ],
      },
    ],
  },
  {
    day: 209,
    themeEs: "Ya no escribo, mando audio",
    themeEn: "I don't type anymore, I send audio",
    missionEs: "Contesta todo en audio hoy, nada escrito.",
    missionEn: "Answer everything in audio today, nothing typed.",
    line: "El hábito cambió sin que te dieras cuenta.",
    lineEn: "The habit changed without you noticing.",
    prompts: [
      {
        id: "d209-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because it comes out faster than typing now.",
        spanish: "Te mando un audio porque ya me sale más rápido que escribir.",
        situationLabel: "El cambio de hábito",
        why: "Four weeks ago speaking was the hard option. It's now the easy one, and nothing else changed.",
        wordHints: [
          { en: "it comes out for me", es: "me sale" },
          { en: "faster", es: "más rápido" },
          { en: "than typing", es: "que escribir" },
        ],
      },
      {
        id: "d209-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that I changed the habit without realizing.",
        spanish: "Era para decirte que cambié el hábito sin darme cuenta.",
        situationLabel: "Notándolo tarde",
        why: "*Sin darme cuenta* — without realizing. The best kind of habit change is the one you notice afterward.",
        wordHints: [
          { en: "i changed", es: "cambié" },
          { en: "the habit", es: "el hábito" },
          { en: "without realizing", es: "sin darme cuenta" },
        ],
      },
      {
        id: "d209-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: I sent four voice notes and didn't redo a single one.",
        spanish: "Te cuento rapidito: mandé cuatro audios y ninguno lo repetí.",
        situationLabel: "El día completo",
        why: "Zero retakes is the actual metric. Not accuracy — willingness.",
        wordHints: [
          { en: "i sent", es: "mandé" },
          { en: "four voice notes", es: "cuatro audios" },
          { en: "not one did i redo", es: "ninguno lo repetí" },
        ],
      },
      {
        id: "d209-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can if you notice the difference.",
        spanish: "Avísame cuando puedas si notas la diferencia.",
        situationLabel: "Buscando confirmación",
        why: "Four weeks is long enough for someone else to hear it before you do.",
        wordHints: [
          { en: "if you notice", es: "si notas" },
          { en: "the difference", es: "la diferencia" },
        ],
      },
      {
        id: "d209-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, message me or send audio, whichever you like.",
        spanish: "Cualquier cosa, me escribes o me mandas audio, como quieras.",
        situationLabel: "Dejándole elegir",
        why: "*Como quieras* — however you like. A one-phrase way to hand someone the choice.",
        wordHints: [
          { en: "or send me audio", es: "o me mandas audio" },
          { en: "however you like", es: "como quieras" },
        ],
      },
    ],
  },
  {
    day: 210,
    themeEs: "Repaso: Notas de voz",
    themeEn: "Review: Voice notes",
    missionEs: "Graba el resumen de la semana en un solo audio.",
    missionEn: "Record the week's recap in a single voice note.",
    line: "Dieciocho audios. El primero duró once segundos.",
    lineEn: "Eighteen voice notes. The first lasted eleven seconds.",
    prompts: [
      {
        id: "d210-te-mando",
        frameStem: "Te mando un audio porque…",
        english: "I'm sending you a voice note because it's my normal way of answering now.",
        spanish: "Te mando un audio porque ya es mi forma normal de contestar.",
        situationLabel: "Cerrando la semana",
        why: "*Mi forma normal de* + infinitive — my normal way of doing something. The sentence that marks a habit as settled.",
        wordHints: [
          { en: "my normal way", es: "mi forma normal" },
          { en: "of answering", es: "de contestar" },
        ],
      },
      {
        id: "d210-era-para",
        frameStem: "Era para decirte que…",
        english: "I was just going to say that I recorded eighteen voice notes in seven days.",
        spanish: "Era para decirte que grabé dieciocho audios en siete días.",
        situationLabel: "La cuenta de la semana",
        why: "Worth counting once. Then stop counting — that's how you know it worked.",
        wordHints: [
          { en: "i recorded", es: "grabé" },
          { en: "eighteen", es: "dieciocho" },
          { en: "in seven days", es: "en siete días" },
        ],
      },
      {
        id: "d210-te-cuento",
        frameStem: "Te cuento rapidito:…",
        english: "Quick rundown: the microphone doesn't judge anybody.",
        spanish: "Te cuento rapidito: el micrófono no juzga a nadie.",
        situationLabel: "La lección de la semana",
        why: "The whole point of the *Graba* step, said out loud: nothing on the other end is keeping score.",
        wordHints: [
          { en: "the microphone", es: "el micrófono" },
          { en: "doesn't judge", es: "no juzga" },
          { en: "anybody", es: "a nadie" },
        ],
      },
      {
        id: "d210-avisame",
        frameStem: "Avísame cuando puedas…",
        english: "Let me know when you can whether you're back at the café on Thursday.",
        spanish: "Avísame cuando puedas si vuelves al café el jueves.",
        situationLabel: "Preguntando por el jueves",
        why: "Four weeks in, *cuando puedas* comes out without you assembling it. That's the chunk doing its job.",
        wordHints: [
          { en: "if you're coming back", es: "si vuelves" },
          { en: "to the café", es: "al café" },
          { en: "on thursday", es: "el jueves" },
        ],
      },
      {
        id: "d210-cualquier-cosa",
        frameStem: "Cualquier cosa, me escribes…",
        english: "Anything at all, just message me — I've lost the embarrassment.",
        spanish: "Cualquier cosa, me escribes, que ya perdí la vergüenza.",
        situationLabel: "El balance de cuatro semanas",
        why: "That *que* is doing causal work — \"because I've lost the embarrassment\". Extremely common, almost never taught.",
        wordHints: [
          { en: "because", es: "que" },
          { en: "i already lost", es: "ya perdí" },
          { en: "the embarrassment", es: "la vergüenza" },
        ],
      },
    ],
  },
];
