import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 7 — "La abuela de Camila" (days 225–231).
 * Camila's grandmother in Bogotá is hospitalized. A week of the phrases people
 * reach for when there is nothing to be done — which is exactly where *ojalá*,
 * *espero que*, *que te vaya bien* and *que descanses* live.
 */
export const invWeek7ReadingDays: ReadingDay[] = [
  {
    day: 225,
    themeEs: "La llamada de Camila",
    storyTitle: "La abuela de Camila",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "grave", en: "serious (of an illness)", example: "Ojalá no sea nada grave." },
      { es: "los resultados", en: "the test results", example: "Espero que los resultados salgan bien." },
      { es: "el turno", en: "the shift", example: "Que te vaya bien esta noche en el turno." },
      { es: "acompañar", en: "to be with someone, to keep company", example: "Ojalá pudiera estar cerca para acompañarte." },
      { es: "a cualquier hora", en: "at any hour", example: "Espero que me llames a cualquier hora." },
    ],
    dialogue: {
      title: "Once de la noche",
      situation: "Camila llama sin avisar, cosa que nunca hace",
      lines: [
        { speaker: "B", es: "Marlana, perdón por la hora. Mi abuela está en el hospital, en Bogotá.", en: "Marlana, sorry about the hour. My grandmother's in the hospital, in Bogotá." },
        { speaker: "A", es: "Ay, Camila. Ojalá no sea nada grave. ¿Qué te dijeron?", en: "Oh, Camila. I hope it's nothing serious. What did they tell you?" },
        { speaker: "B", es: "Nada todavía. Están esperando resultados. Mi mamá está allá con ella.", en: "Nothing yet. They're waiting on results. My mom's there with her." },
        { speaker: "A", es: "Ojalá tu mamá esté con ella toda la noche. Espero que los resultados salgan bien.", en: "I hope your mom's with her all night. I hope the results come back fine." },
        { speaker: "B", es: "Gracias. No sé ni por qué te llamé, la verdad. No hay nada que hacer.", en: "Thanks. I don't even know why I called you, honestly. There's nothing to do." },
        { speaker: "A", es: "Por eso mismo. Espero que puedas dormir algo esta noche. Y espero que me llames a cualquier hora.", en: "That's exactly why. I hope you can get some sleep tonight. And I hope you call me at any hour." },
        { speaker: "B", es: "Tengo turno en dos horas. No voy a dormir nada.", en: "I've got a shift in two hours. I won't sleep at all." },
        { speaker: "A", es: "Que te vaya bien esta noche en el turno. Que descanses, aunque sea un rato.", en: "Hope tonight goes okay on your shift. Get some rest, even a little." },
        { speaker: "A", es: "Y ojalá pudiera hacer algo más que escribirte. Ojalá supiera qué decir en estos casos.", en: "And I wish I could do something more than write to you. I wish I knew what to say in these situations." },
      ],
    },
  },
  {
    day: 226,
    themeEs: "Espero que no sea grave",
    storyTitle: "La abuela de Camila",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "nada de cuidado", en: "nothing to worry about", example: "Espero que no sea nada de cuidado." },
      { es: "aguantar", en: "to hold up, to endure", example: "Espero que tu mamá esté aguantando bien." },
      { es: "tocarle a alguien", en: "for someone to get, to be assigned", example: "Ojalá le toque un buen médico." },
      { es: "con calma", en: "calmly, unhurriedly", example: "Espero que les expliquen todo con calma." },
      { es: "cubrir un turno", en: "to cover a shift", example: "Ojalá pudiera cubrirte un turno." },
    ],
    dialogue: {
      title: "Dos días esperando",
      situation: "Jueves; siguen sin resultados",
      lines: [
        { speaker: "A", es: "¿Algo hoy?", en: "Anything today?" },
        { speaker: "B", es: "Nada. Dicen que mañana. Llevo dos días con el teléfono en la mano.", en: "Nothing. They say tomorrow. I've had my phone in my hand for two days." },
        { speaker: "A", es: "Ojalá salgan hoy los resultados. Ojalá le toque un buen médico.", en: "I hope the results come today. I hope she gets a good doctor." },
        { speaker: "B", es: "Es un hospital bueno, eso sí. Pero uno nunca sabe.", en: "It's a good hospital, at least. But you never know." },
        { speaker: "A", es: "Espero que no sea nada de cuidado. Y espero que les expliquen todo con calma.", en: "I hope it's nothing to worry about. And I hope they explain everything calmly." },
        { speaker: "B", es: "Eso es lo peor: hablan rápido y uno no entiende la mitad.", en: "That's the worst of it: they talk fast and you don't understand half." },
        { speaker: "A", es: "Espero que tu mamá esté aguantando bien. Que te vaya bien en la llamada con el doctor.", en: "I hope your mom's holding up okay. Hope the call with the doctor goes well." },
        { speaker: "B", es: "Es a las tres. Después te cuento.", en: "It's at three. I'll tell you after." },
        { speaker: "A", es: "Que descanses y no me contestes hoy. Ojalá pudiera esperar contigo esos resultados.", en: "Get some rest and don't answer me today. I wish I could wait for those results with you." },
      ],
    },
  },
  {
    day: 227,
    themeEs: "Que te vaya bien",
    storyTitle: "La abuela de Camila",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el vuelo", en: "the flight", example: "Ojalá encuentres vuelo para el viernes." },
      { es: "llegar con bien", en: "to arrive safely", example: "Que llegues con bien." },
      { es: "aterrizar", en: "to land", example: "Me escribes al aterrizar." },
      { es: "la maleta", en: "the suitcase", example: "Deja la maleta para mañana." },
      { es: "de madrugada", en: "in the small hours", example: "Llega de madrugada a Bogotá." },
    ],
    dialogue: {
      title: "Se va el viernes",
      situation: "Marlana la lleva al aeropuerto de Logan",
      lines: [
        { speaker: "B", es: "Conseguí vuelo. Sale el viernes a las seis de la tarde.", en: "I got a flight. It leaves Friday at six in the evening." },
        { speaker: "A", es: "Menos mal. Ojalá llegues a tiempo. Ojalá te dejen entrar a verla.", en: "Thank goodness. I hope you get there in time. I hope they let you in to see her." },
        { speaker: "B", es: "Mi tía dice que sí, que ya arregló eso. Llego de madrugada.", en: "My aunt says yes, she's sorted that out. I land in the small hours." },
        { speaker: "A", es: "Espero que el viaje sea tranquilo. Espero que duermas algo en el avión.", en: "I hope the trip is an easy one. I hope you sleep a bit on the plane." },
        { speaker: "B", es: "Nunca duermo en aviones. Pero bueno.", en: "I never sleep on planes. But okay." },
        { speaker: "A", es: "Que descanses en el vuelo, son seis horas. Y que descanses al llegar, no hagas nada más.", en: "Get some rest on the flight, it's six hours. And rest when you arrive, don't do anything else." },
        { speaker: "B", es: "Gracias por traerme. De verdad.", en: "Thanks for driving me. Really." },
        { speaker: "A", es: "Que te vaya bien, Camila. De verdad. Que llegues con bien y abraces a tu abuela por mí.", en: "Take care, Camila. Truly. Get there safely and hug your grandmother for me." },
        { speaker: "A", es: "Y ojalá pudiera ir contigo. Ojalá tuviera cómo ayudarte desde aquí.", en: "And I wish I could go with you. I wish I had some way to help you from here." },
      ],
    },
  },
  {
    day: 228,
    themeEs: "Ojalá pudiera ir contigo",
    storyTitle: "La abuela de Camila",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "turnarse", en: "to take turns", example: "Espero que se turnen entre todos." },
      { es: "la preocupación", en: "the worry", example: "Ojalá pudiera quitarte un poco de la preocupación." },
      { es: "relevar", en: "to relieve, to take over from", example: "Ojalá alguien te releve unas horas." },
      { es: "quitarle algo a alguien", en: "to take something off someone", example: "Ojalá pudiera quitarte eso de encima." },
      { es: "dar de alta", en: "to discharge (from hospital)", example: "Ojalá le den de alta pronto." },
    ],
    dialogue: {
      title: "Cinco mil kilómetros",
      situation: "Domingo; Camila lleva dos días en el hospital de Bogotá",
      lines: [
        { speaker: "A", es: "Ojalá ya hayas llegado. No supe nada desde el aeropuerto.", en: "I hope you've already arrived. I heard nothing after the airport." },
        { speaker: "B", es: "Llegué el sábado. Estoy en el hospital desde entonces. Perdón por no escribir.", en: "I got here Saturday. I've been at the hospital since. Sorry for not writing." },
        { speaker: "A", es: "No pidas perdón. Espero que no estés sola en el hospital. Espero que se turnen entre todos.", en: "Don't apologize. I hope you're not alone at the hospital. I hope you all take turns." },
        { speaker: "B", es: "Somos cuatro. Pero yo soy la enfermera, entonces todos me preguntan a mí.", en: "There are four of us. But I'm the nurse, so everyone asks me." },
        { speaker: "A", es: "Claro. Espero que pidas ayuda si la necesitas. Ojalá alguien te releve unas horas.", en: "Of course. I hope you ask for help if you need it. I hope someone relieves you for a few hours." },
        { speaker: "B", es: "Estoy bien. Cansada, pero bien.", en: "I'm okay. Tired, but okay." },
        { speaker: "A", es: "Que te vaya bien con los médicos hoy. Que descanses cuando puedas, no cuando debas.", en: "Hope it goes well with the doctors today. Get some rest when you can, not when you should." },
        { speaker: "B", es: "Esa frase me la voy a guardar.", en: "I'm keeping that sentence." },
        { speaker: "A", es: "Ojalá pudiera quitarte un poco de la preocupación. Ojalá hablara lo bastante bien para decirte esto mejor.", en: "I wish I could take a little of the worry off you. I wish I spoke well enough to say this better." },
      ],
    },
  },
  {
    day: 229,
    themeEs: "Que descanses",
    storyTitle: "La abuela de Camila",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "por compromiso", en: "out of obligation", example: "Espero que no me contestes por compromiso." },
      { es: "la diferencia de horas", en: "the time difference", example: "Hay siete horas de diferencia." },
      { es: "servir de algo", en: "to help somehow", example: "Ojalá te sirva de algo leerme." },
      { es: "y ya", en: "and that's it", example: "Que te vaya bien y ya, no digo más." },
      { es: "de guardia", en: "on call", example: "Ojalá pudiera estar de guardia yo esta noche." },
    ],
    dialogue: {
      title: "Siete horas de diferencia",
      situation: "Mensajes de noche, cuando en Bogotá ya es de madrugada",
      lines: [
        { speaker: "A", es: "Ojalá estés durmiendo cuando te llegue esto. Aquí son las cuatro y allá ya son las once.", en: "I hope you're asleep when this reaches you. It's four here and eleven there." },
        { speaker: "A", es: "Espero que no me contestes por compromiso. En serio, no hace falta.", en: "I hope you're not answering me out of obligation. Really, there's no need." },
        { speaker: "A", es: "Que te vaya bien hoy y ya, no digo más. Que descanses.", en: "Hope today goes well and that's it, I'll stop there. Sleep well." },
        { speaker: "B", es: "Marlana. Son las once y estoy despierta. Y sí me sirve leerte.", en: "Marlana. It's eleven and I'm awake. And reading you does help." },
        { speaker: "A", es: "¿Sí? Nunca sé si estoy diciendo lo correcto.", en: "Really? I never know if I'm saying the right thing." },
        { speaker: "B", es: "Me mandas lo mismo cada noche y me gusta que sea lo mismo. No quiero novedad, quiero que alguien esté.", en: "You send me the same thing every night and I like that it's the same. I don't want novelty, I want someone to be there." },
        { speaker: "A", es: "Entonces te lo voy a decir todas las noches. Que descanses, es lo único que puedo mandarte desde aquí.", en: "Then I'm going to say it to you every night. Sleep well — it's the only thing I can send you from here." },
        { speaker: "B", es: "Es suficiente. Y en español, además.", en: "It's enough. And in Spanish, on top of that." },
        { speaker: "A", es: "Ojalá pudiera sentarme un rato contigo, sin hablar. Ojalá no hubiera siete horas de diferencia.", en: "I wish I could sit with you a while, without talking. I wish there weren't seven hours between us." },
      ],
    },
  },
  {
    day: 230,
    themeEs: "Ojalá la hubieras conocido",
    storyTitle: "La abuela de Camila",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "mejorar", en: "to get better", example: "Ojalá siga mejorando así de rápido." },
      { es: "el alivio", en: "the relief", example: "Espero que te caiga el alivio de golpe." },
      { es: "de golpe", en: "all at once", example: "Me cayó el alivio de golpe." },
      { es: "a medias", en: "halfway, partly", example: "Que descanses de verdad, no a medias." },
      { es: "haber conocido", en: "to have met", example: "Ojalá la hubiera conocido." },
    ],
    dialogue: {
      title: "Quién es mi abuela",
      situation: "Miércoles; la abuela mejora y Camila por fin puede hablar de otra cosa",
      lines: [
        { speaker: "B", es: "Marlana. Está mejor. Comió sola hoy y se quejó del almuerzo.", en: "Marlana. She's better. She ate on her own today and complained about the lunch." },
        { speaker: "A", es: "¡Se quejó del almuerzo! Ojalá siga mejorando así de rápido.", en: "She complained about the lunch! I hope she keeps improving this fast." },
        { speaker: "B", es: "Ojalá. Dicen que si sigue así, le dan de alta la semana que viene.", en: "Hopefully. They say if she keeps this up, they'll discharge her next week." },
        { speaker: "A", es: "Espero que te caiga el alivio de golpe. Espero que ahora sí duermas ocho horas.", en: "I hope the relief hits you all at once. I hope you actually sleep eight hours now." },
        { speaker: "B", es: "Anoche dormí seis. Récord. Oye, ¿te cuento algo de ella?", en: "Last night I slept six. A record. Hey, can I tell you something about her?" },
        { speaker: "A", es: "Cuéntame todo.", en: "Tell me everything." },
        { speaker: "B", es: "Fue maestra cuarenta años en un pueblo del Tolima. Enseñó a leer a media familia mía.", en: "She was a teacher for forty years in a town in Tolima. She taught half my family to read." },
        { speaker: "A", es: "¿Maestra? Camila. Ojalá la hubiera conocido.", en: "A teacher? Camila. I wish I'd met her." },
        { speaker: "B", es: "Le hablé de ti. Le dije que hay una maestra en Boston aprendiendo español a los cuarenta. Se rió y dijo que ojalá tuviera más estudiantes así.", en: "I told her about you. I said there's a teacher in Boston learning Spanish at forty. She laughed and said she wished she'd had more students like that." },
      ],
    },
  },
  {
    day: 231,
    themeEs: "Repaso: Ojalá",
    isRecap: true,
    vocab: [
      { es: "acompañada", en: "accompanied, not alone", example: "Espero que te hayas sentido acompañada." },
      { es: "pesar", en: "to weigh on someone", example: "Espero que mis mensajes no te hayan pesado." },
      { es: "hacer falta", en: "to be needed", example: "Puedo repetirlo cuando haga falta." },
      { es: "la fórmula", en: "the set phrase, the formula", example: "Espero que no te haya sonado a fórmula." },
      { es: "alcanzar", en: "to be enough", example: "Resultó que alcanzaba." },
    ],
    dialogue: {
      title: "Y resultó que alcanzaba",
      situation: "Jueves; Camila llama desde Bogotá a la hora del café de siempre",
      lines: [
        { speaker: "B", es: "Son las cuatro allá. Hora del café. No quise perderme el jueves.", en: "It's four there. Coffee time. I didn't want to miss Thursday." },
        { speaker: "A", es: "Ojalá esta semana termine tan bien como va. ¿Cómo sigue tu abuela?", en: "I hope this week ends as well as it's going. How's your grandmother doing?" },
        { speaker: "B", es: "Bien. Oye, quiero decirte algo. Espero que sepas lo que hiciste esta semana.", en: "Well. Hey, I want to tell you something. I hope you know what you did this week." },
        { speaker: "A", es: "¿Qué hice? Nada. Mandé mensajes.", en: "What did I do? Nothing. I sent messages." },
        { speaker: "B", es: "Me acompañaste ocho días en español, sin cambiar al inglés ni una vez. En la peor semana del año.", en: "You were with me for eight days in Spanish, without switching to English once. In the worst week of the year." },
        { speaker: "A", es: "Espero que te hayas sentido acompañada. Espero que mis mensajes no te hayan pesado.", en: "I hope you felt accompanied. I hope my messages weren't a burden." },
        { speaker: "B", es: "Al revés. Y usaste siempre las mismas cuatro frases. ¿Sabes por qué eso está bien?", en: "The opposite. And you always used the same four phrases. Do you know why that's fine?" },
        { speaker: "A", es: "Que descanses fue mi frase de la semana. Cuatro palabras, siete noches. Y resultó que alcanzaba.", en: "\"Que descanses\" was my phrase of the week. Four words, seven nights. And it turned out to be enough." },
        { speaker: "B", es: "Exacto. Ojalá hubieras tenido estas frases hace diez años. Pero las tienes ahora, y ya no se te van.", en: "Exactly. I wish you'd had these phrases ten years ago. But you have them now, and they're not going anywhere." },
      ],
    },
  },
];
