import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 3 — "Al teléfono" (days 197–203).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week3-frames.ts
 * for the matching `frameStem` (convention 2).
 *
 * Day 198 is deliberately usted; its `why` notes name the shift (convention 3).
 */
export const invWeek3SpeakDays: SpeakDay[] = [
  {
    day: 197,
    themeEs: "Sin cara, solo voz",
    themeEn: "No face, just voice",
    missionEs: "Habla por teléfono cinco minutos sin ver a nadie.",
    missionEn: "Talk on the phone for five minutes without seeing anyone.",
    line: "Por teléfono no hay labios ni manos. Solo tu voz y tus muletillas.",
    lineEn: "On the phone there are no lips and no hands. Just your voice and your fillers.",
    prompts: [
      {
        id: "d197-alo",
        frameStem: "¿Aló?",
        english: "Hello? Camila, is that you?",
        spanish: "¿Aló? Camila, ¿eres tú?",
        situationLabel: "Contestando el celular",
        why: "*¿Aló?* is the standard Latin American way to answer. Mexico says *¿Bueno?* — both current, neither is Spain's *¿Diga?*",
        wordHints: [
          { en: "hello", es: "aló" },
          { en: "is that you", es: "eres tú" },
        ],
      },
      {
        id: "d197-le-habla",
        frameStem: "Le habla…",
        english: "This is Marlana Creed, from the English program.",
        spanish: "Le habla Marlana Creed, del programa de inglés.",
        situationLabel: "Ensayando la llamada del colegio",
        why: "*Le habla X* is how you identify yourself on a work call — automatically usted, and still exactly what people say.",
        wordHints: [
          { en: "this is speaking", es: "le habla" },
          { en: "from the program", es: "del programa" },
          { en: "english", es: "inglés" },
        ],
      },
      {
        id: "d197-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who's calling, please?",
        spanish: "¿De parte de quién, por favor?",
        situationLabel: "Cuando contestas por otra persona",
        why: "You'll be asked this on every formal call you make. Having the answer ready means the pause never happens.",
        wordHints: [
          { en: "who's calling", es: "de parte de quién" },
          { en: "please", es: "por favor" },
        ],
      },
      {
        id: "d197-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me? I think the line's bad.",
        spanish: "¿Me escuchas? Creo que se escucha mal.",
        situationLabel: "Arreglando la llamada",
        why: "On the phone this is the most useful sentence you own — it buys you time *and* fixes the actual problem.",
        wordHints: [
          { en: "can you hear me", es: "me escuchas" },
          { en: "i think", es: "creo que" },
          { en: "it sounds bad", es: "se escucha mal" },
        ],
      },
      {
        id: "d197-se-corto",
        frameStem: "Se cortó…",
        english: "The call dropped, sorry.",
        spanish: "Se cortó la llamada, perdona.",
        situationLabel: "Después de volver a llamar",
        why: "*Se cortó* blames the connection, not either person. No apology needed beyond the word itself.",
        wordHints: [
          { en: "it dropped", es: "se cortó" },
          { en: "the call", es: "la llamada" },
          { en: "sorry", es: "perdona" },
        ],
      },
    ],
  },
  {
    day: 198,
    themeEs: "La mamá de Yusuf",
    themeEn: "Yusuf's mother",
    missionEs: "Haz una llamada entera en usted, sin cambiar al inglés.",
    missionEn: "Make a whole call in usted, without switching to English.",
    line: "Hoy hablas de usted. Es la misma persona, otro tono.",
    lineEn: "Today you're on usted. Same person, different register.",
    prompts: [
      {
        id: "d198-alo",
        frameStem: "¿Aló?",
        english: "Hello? Good afternoon, am I speaking with Mrs. Amina?",
        spanish: "¿Aló? Buenas tardes, ¿hablo con la señora Amina?",
        situationLabel: "Llamando a la mamá de un estudiante",
        why: "*¿Hablo con…?* confirms you reached the right person without demanding a name — the polite opener.",
        wordHints: [
          { en: "good afternoon", es: "buenas tardes" },
          { en: "am i speaking with", es: "hablo con" },
          { en: "mrs", es: "la señora" },
        ],
      },
      {
        id: "d198-le-habla",
        frameStem: "Le habla…",
        english: "This is the school calling — it's nothing serious.",
        spanish: "Le habla del colegio, no es nada grave.",
        situationLabel: "Tranquilizándola primero",
        why: "*No es nada grave* early in a school call is a kindness. A parent's first thought is always the worst one.",
        wordHints: [
          { en: "this is calling", es: "le habla" },
          { en: "from the school", es: "del colegio" },
          { en: "nothing serious", es: "nada grave" },
        ],
      },
      {
        id: "d198-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who should I say called?",
        spanish: "¿De parte de quién le digo que llamé?",
        situationLabel: "Dejando tu nombre",
        why: "Usted throughout: *le digo* — I'll tell you. The same sentence in tú would be *te digo*.",
        wordHints: [
          { en: "who's calling", es: "de parte de quién" },
          { en: "should i tell you", es: "le digo" },
          { en: "that i called", es: "que llamé" },
        ],
      },
      {
        id: "d198-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me, ma'am? You're coming through a bit choppy.",
        spanish: "¿Me escucha, señora? Se escucha un poco cortado.",
        situationLabel: "Comprobando la línea, en usted",
        why: "Today the stem loses its *s*: **¿Me escucha?** That single letter is the whole tú→usted shift on this call.",
        wordHints: [
          { en: "can you hear me", es: "me escucha" },
          { en: "ma'am", es: "señora" },
          { en: "it sounds choppy", es: "se escucha cortado" },
        ],
      },
      {
        id: "d198-se-corto",
        frameStem: "Se cortó…",
        english: "It cut out while I was explaining the schedule to her.",
        spanish: "Se cortó cuando le estaba explicando el horario.",
        situationLabel: "Contándole a Camila después",
        why: "*Le estaba explicando* — the past progressive with an usted object pronoun, mid-action when the call died.",
        wordHints: [
          { en: "it cut out", es: "se cortó" },
          { en: "i was explaining to her", es: "le estaba explicando" },
          { en: "the schedule", es: "el horario" },
        ],
      },
    ],
  },
  {
    day: 199,
    themeEs: "La persona que contesta",
    themeEn: "Whoever picks up",
    missionEs: "Pide que te comuniquen con la persona correcta.",
    missionEn: "Ask to be put through to the right person.",
    line: "Quien contesta casi nunca es quien necesitas.",
    lineEn: "Whoever answers is almost never who you need.",
    prompts: [
      {
        id: "d199-alo",
        frameStem: "¿Aló?",
        english: "Hello? Could you put me through to the person who schedules appointments?",
        spanish: "¿Aló? ¿Me puede comunicar con la persona que agenda las citas?",
        situationLabel: "Llamando a la clínica",
        why: "*Comunicar con* is the neutral Latin American verb for putting a call through — no switchboard vocabulary needed.",
        wordHints: [
          { en: "could you put me through", es: "me puede comunicar" },
          { en: "the person who", es: "la persona que" },
          { en: "schedules", es: "agenda" },
          { en: "appointments", es: "las citas" },
        ],
      },
      {
        id: "d199-le-habla",
        frameStem: "Le habla…",
        english: "This is a teacher who helps the family with the language.",
        spanish: "Le habla una maestra que ayuda a la familia con el idioma.",
        situationLabel: "Explicando quién eres",
        why: "Naming your role instead of your title is what actually gets you through — it explains why you're calling for someone else.",
        wordHints: [
          { en: "a teacher", es: "una maestra" },
          { en: "who helps", es: "que ayuda" },
          { en: "the family", es: "la familia" },
          { en: "the language", es: "el idioma" },
        ],
      },
      {
        id: "d199-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who's calling? From the teacher, not from the family.",
        spanish: "¿De parte de quién? De la maestra, no de la familia.",
        situationLabel: "Aclarando que no eres familiar",
        why: "The distinction matters on this kind of call, and it's two words — worth saying before you're asked twice.",
        wordHints: [
          { en: "who's calling", es: "de parte de quién" },
          { en: "from the teacher", es: "de la maestra" },
          { en: "from the family", es: "de la familia" },
        ],
      },
      {
        id: "d199-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me? Everything went silent.",
        spanish: "¿Me escuchas? Se quedó todo en silencio.",
        situationLabel: "En espera, sin saber si sigues ahí",
        why: "*Se quedó todo en silencio* — everything went quiet. The exact feeling of being put on hold and forgotten.",
        wordHints: [
          { en: "everything went", es: "se quedó todo" },
          { en: "silent", es: "en silencio" },
        ],
      },
      {
        id: "d199-se-corto",
        frameStem: "Se cortó…",
        english: "It dropped while they had me on hold.",
        spanish: "Se cortó mientras me tenían en espera.",
        situationLabel: "La llamada que no llegó a nada",
        why: "*Me tenían en espera* — they had me on hold. The imperfect makes it a stretch of time, which is what it felt like.",
        wordHints: [
          { en: "while", es: "mientras" },
          { en: "they had me", es: "me tenían" },
          { en: "on hold", es: "en espera" },
        ],
      },
    ],
  },
  {
    day: 200,
    themeEs: "No te escucho",
    themeEn: "I can't hear you",
    missionEs: "Arregla una llamada mala sin colgar.",
    missionEn: "Fix a bad call without hanging up.",
    line: "La señal se arregla hablando, no colgando.",
    lineEn: "You fix the signal by talking, not by hanging up.",
    prompts: [
      {
        id: "d200-alo",
        frameStem: "¿Aló?",
        english: "Hello? Hang on, I'm coming out of the hallway.",
        spanish: "¿Aló? Espérame, voy saliendo del pasillo.",
        situationLabel: "Contestando en el colegio",
        why: "*Voy saliendo* — I'm on my way out. The progressive with *ir* means it's happening as you speak.",
        wordHints: [
          { en: "hang on", es: "espérame" },
          { en: "i'm coming out", es: "voy saliendo" },
          { en: "the hallway", es: "el pasillo" },
        ],
      },
      {
        id: "d200-le-habla",
        frameStem: "Le habla…",
        english: "This is Marlana again — we got cut off.",
        spanish: "Le habla Marlana otra vez, se nos cortó.",
        situationLabel: "Volviendo a llamar",
        why: "*Se nos cortó* — it cut out on us. That *nos* makes it something that happened to both of you, so nobody's at fault.",
        wordHints: [
          { en: "again", es: "otra vez" },
          { en: "we got cut off", es: "se nos cortó" },
        ],
      },
      {
        id: "d200-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who's calling? I didn't catch the name.",
        spanish: "¿De parte de quién? No le entendí el nombre.",
        situationLabel: "Cuando no captas el nombre",
        why: "*No le entendí* is honest and neutral — it doesn't accuse anyone of mumbling.",
        wordHints: [
          { en: "i didn't catch", es: "no le entendí" },
          { en: "the name", es: "el nombre" },
        ],
      },
      {
        id: "d200-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me? I've got you on speaker.",
        spanish: "¿Me escuchas? Te puse en altavoz.",
        situationLabel: "Cambiando a altavoz",
        why: "*El altavoz* is speakerphone. This is the actual vocabulary of a 2026 phone call, not a 1998 one.",
        wordHints: [
          { en: "i put you", es: "te puse" },
          { en: "on speaker", es: "en altavoz" },
        ],
      },
      {
        id: "d200-se-corto",
        frameStem: "Se cortó…",
        english: "It cut out — I'd better call you on video instead.",
        spanish: "Se cortó, mejor te marco por videollamada.",
        situationLabel: "Cambiando de canal",
        why: "*Te marco* is the everyday Latin American way to say \"I'll call you\" — more common than *te llamo* in many places.",
        wordHints: [
          { en: "better", es: "mejor" },
          { en: "i'll call you", es: "te marco" },
          { en: "by video call", es: "por videollamada" },
        ],
      },
    ],
  },
  {
    day: 201,
    themeEs: "Se cortó",
    themeEn: "It dropped",
    missionEs: "Retoma una llamada cortada sin empezar de cero.",
    missionEn: "Pick up a dropped call without starting from scratch.",
    line: "Una llamada cortada no borra lo que ya dijiste.",
    lineEn: "A dropped call doesn't erase what you already said.",
    prompts: [
      {
        id: "d201-alo",
        frameStem: "¿Aló?",
        english: "Hello? Where were we?",
        spanish: "¿Aló? ¿En qué estábamos?",
        situationLabel: "Retomando el hilo",
        why: "*¿En qué estábamos?* — where were we? The one sentence that rescues a dropped call without starting over.",
        wordHints: [
          { en: "where", es: "en qué" },
          { en: "were we", es: "estábamos" },
        ],
      },
      {
        id: "d201-le-habla",
        frameStem: "Le habla…",
        english: "This is Marlana — it's the third time now, I'm sorry.",
        spanish: "Le habla Marlana, ya es la tercera vez, perdón.",
        situationLabel: "Tercera llamada seguida",
        why: "Three calls in a row is a normal Tuesday. Naming it lightly keeps it from being awkward.",
        wordHints: [
          { en: "it's already", es: "ya es" },
          { en: "the third time", es: "la tercera vez" },
          { en: "sorry", es: "perdón" },
        ],
      },
      {
        id: "d201-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who's calling? I didn't recognize the voice.",
        spanish: "¿De parte de quién? No reconocí la voz.",
        situationLabel: "Un número que no conoces",
        why: "Voices without faces are their own skill. Saying you didn't recognize it is better than guessing wrong.",
        wordHints: [
          { en: "i didn't recognize", es: "no reconocí" },
          { en: "the voice", es: "la voz" },
        ],
      },
      {
        id: "d201-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me? I'll repeat the last thing I said.",
        spanish: "¿Me escuchas? Repito lo último que dije.",
        situationLabel: "Rehaciendo la frase perdida",
        why: "*Lo último que dije* — the last thing I said. A phrase that lets you rewind exactly one sentence, not the whole call.",
        wordHints: [
          { en: "i'll repeat", es: "repito" },
          { en: "the last thing", es: "lo último" },
          { en: "that i said", es: "que dije" },
        ],
      },
      {
        id: "d201-se-corto",
        frameStem: "Se cortó…",
        english: "It dropped — it wasn't you and it wasn't me.",
        spanish: "Se cortó, no fuiste tú ni fui yo.",
        situationLabel: "Quitándole culpa a nadie",
        why: "*Se cortó* is impersonal on purpose. The connection did it. Nobody has to be sorry.",
        wordHints: [
          { en: "it wasn't you", es: "no fuiste tú" },
          { en: "nor was it me", es: "ni fui yo" },
        ],
      },
    ],
  },
  {
    day: 202,
    themeEs: "Dejar un recado",
    themeEn: "Leaving a message",
    missionEs: "Deja un recado completo: quién, por qué y cuándo.",
    missionEn: "Leave a complete message: who, why, and when.",
    line: "Un buen recado tiene tres partes y ninguna sobra.",
    lineEn: "A good message has three parts and none of them is spare.",
    prompts: [
      {
        id: "d202-alo",
        frameStem: "¿Aló?",
        english: "Hello? Thanks for calling me back.",
        spanish: "¿Aló? Gracias por devolverme la llamada.",
        situationLabel: "Cuando por fin te devuelven la llamada",
        why: "*Devolver la llamada* — to return the call. One verb for the whole idea.",
        wordHints: [
          { en: "thanks for", es: "gracias por" },
          { en: "returning my call", es: "devolverme la llamada" },
        ],
      },
      {
        id: "d202-le-habla",
        frameStem: "Le habla…",
        english: "This is Marlana — you can reach me until four.",
        spanish: "Le habla Marlana, puede llamarme hasta las cuatro.",
        situationLabel: "Dejando un mensaje en el buzón",
        why: "A voicemail in Spanish follows the same three beats as in English: who you are, why you called, when you're reachable.",
        wordHints: [
          { en: "you can call me", es: "puede llamarme" },
          { en: "until four", es: "hasta las cuatro" },
        ],
      },
      {
        id: "d202-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who's calling? Tell her it's from Marlana, the teacher.",
        spanish: "¿De parte de quién? Dígale que de la maestra Marlana.",
        situationLabel: "Dejando recado con otra persona",
        why: "*Dígale que…* — tell her that. The usted command plus an indirect object, which is most of what a phone message is.",
        wordHints: [
          { en: "tell her", es: "dígale" },
          { en: "from the teacher", es: "de la maestra" },
        ],
      },
      {
        id: "d202-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me? I already left the message — tell me how I did.",
        spanish: "¿Me escuchas? Ya dejé el recado, cuéntame cómo lo hice.",
        situationLabel: "Reportándote con Camila",
        why: "Back to tú the second the formal call ends. Switching register mid-afternoon is the actual skill.",
        wordHints: [
          { en: "i already left", es: "ya dejé" },
          { en: "the message", es: "el recado" },
          { en: "tell me", es: "cuéntame" },
          { en: "how i did", es: "cómo lo hice" },
        ],
      },
      {
        id: "d202-se-corto",
        frameStem: "Se cortó…",
        english: "The voicemail cut out halfway through the message.",
        spanish: "Se cortó el buzón de voz a mitad del recado.",
        situationLabel: "Cuando el buzón te corta",
        why: "*El buzón de voz* is voicemail; *me mandó al buzón* — it sent me to voicemail — is how you say it in one breath.",
        wordHints: [
          { en: "the voicemail", es: "el buzón de voz" },
          { en: "halfway through", es: "a mitad de" },
          { en: "the message", es: "el recado" },
        ],
      },
    ],
  },
  {
    day: 203,
    themeEs: "Repaso: Al teléfono",
    themeEn: "Review: On the phone",
    missionEs: "Cuenta las cuatro llamadas de la semana, una por una.",
    missionEn: "Tell all four calls from this week, one by one.",
    line: "Cuatro llamadas, ninguna en inglés.",
    lineEn: "Four calls, none of them in English.",
    prompts: [
      {
        id: "d203-alo",
        frameStem: "¿Aló?",
        english: "Hello? I answer without looking at who's calling now.",
        spanish: "¿Aló? Contesto sin mirar quién llama.",
        situationLabel: "El hábito nuevo",
        why: "Answering before you know who it is means you've stopped pre-translating. That's the week's quiet win.",
        wordHints: [
          { en: "i answer", es: "contesto" },
          { en: "without looking", es: "sin mirar" },
          { en: "who's calling", es: "quién llama" },
        ],
      },
      {
        id: "d203-le-habla",
        frameStem: "Le habla…",
        english: "This is Marlana — I said it four times this week.",
        spanish: "Le habla Marlana: lo dije cuatro veces esta semana.",
        situationLabel: "Contando las llamadas",
        why: "The line you rehearsed on Monday is the line that came out automatically by Friday.",
        wordHints: [
          { en: "i said it", es: "lo dije" },
          { en: "four times", es: "cuatro veces" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d203-de-parte",
        frameStem: "¿De parte de quién?",
        english: "Who's calling? That question used to freeze me.",
        spanish: "¿De parte de quién? Antes esa pregunta me congelaba.",
        situationLabel: "Lo que ya no te asusta",
        why: "*Me congelaba* — it used to freeze me. The imperfect marks it as a thing that's over.",
        wordHints: [
          { en: "before", es: "antes" },
          { en: "that question", es: "esa pregunta" },
          { en: "used to freeze me", es: "me congelaba" },
        ],
      },
      {
        id: "d203-me-escuchas",
        frameStem: "¿Me escuchas?",
        english: "Can you hear me? And in usted — can you hear me? Both come out now.",
        spanish: "¿Me escuchas? Y con usted, ¿me escucha? Las dos me salen.",
        situationLabel: "Las dos formas, sin pensar",
        why: "Holding both forms of the same sentence, and picking one by who's on the line — that's register control, and you have it.",
        wordHints: [
          { en: "and with usted", es: "y con usted" },
          { en: "both", es: "las dos" },
          { en: "come out for me", es: "me salen" },
        ],
      },
      {
        id: "d203-se-corto",
        frameStem: "Se cortó…",
        english: "It dropped five times and five times I called back.",
        spanish: "Se cortó cinco veces y cinco veces volví a llamar.",
        situationLabel: "El resumen de la semana",
        why: "The week's real lesson: a dropped call is a technical problem, not a language failure. You call back and continue.",
        wordHints: [
          { en: "five times", es: "cinco veces" },
          { en: "i called back", es: "volví a llamar" },
        ],
      },
    ],
  },
];
