import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 10 — "El turno" (days 246–252).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week10-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek10SpeakDays: SpeakDay[] = [
  {
    day: 246,
    themeEs: "Tres al mismo tiempo",
    themeEn: "Three at once",
    missionEs: "Habla en una conversación de tres sin quedarte fuera.",
    missionEn: "Talk in a three-way conversation without getting left out.",
    line: "Dos personas se turnan solas. Tres personas tienen que reclamar.",
    lineEn: "Two people take turns by themselves. Three have to claim.",
    prompts: [
      {
        id: "d246-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think? You've been quiet a while.",
        spanish: "¿Y tú qué opinas? Llevas rato callada.",
        situationLabel: "Primera conversación de tres",
        why: "The most generous four words in a three-way conversation. Someone always gets left out, and this is how you fix it.",
        wordHints: [
          { en: "what do you think", es: "qué opinas" },
          { en: "you've been", es: "llevas" },
          { en: "a while", es: "rato" },
          { en: "quiet", es: "callada" },
        ],
      },
      {
        id: "d246-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "Let me finish, because otherwise I'll lose it.",
        spanish: "Déjame terminar, que si no se me va.",
        situationLabel: "Sosteniendo tu turno",
        why: "*Que si no se me va* — because otherwise I'll lose it. The honest reason works better than insisting.",
        wordHints: [
          { en: "let me finish", es: "déjame terminar" },
          { en: "because otherwise", es: "que si no" },
          { en: "i'll lose it", es: "se me va" },
        ],
      },
      {
        id: "d246-a-eso-voy",
        frameStem: "A eso voy…",
        english: "I'm getting to that — give me a second.",
        spanish: "A eso voy, dame un segundo.",
        situationLabel: "Cuando te apuran",
        why: "Three words that buy you the rest of your story without conceding the floor.",
        wordHints: [
          { en: "i'm getting to that", es: "a eso voy" },
          { en: "give me", es: "dame" },
          { en: "a second", es: "un segundo" },
        ],
      },
      {
        id: "d246-como-te-decia",
        frameStem: "Como te decía…",
        english: "As I was saying, the families want it earlier.",
        spanish: "Como te decía, las familias quieren más temprano.",
        situationLabel: "Retomando después de la interrupción",
        why: "Zero resentment in this phrase. It just picks the sentence up where it fell and keeps going.",
        wordHints: [
          { en: "as i was saying", es: "como te decía" },
          { en: "the families want", es: "las familias quieren" },
          { en: "earlier", es: "más temprano" },
        ],
      },
      {
        id: "d246-aja-claro",
        frameStem: "Ajá, claro…",
        english: "Mm-hm, right — and then what did you do?",
        spanish: "Ajá, claro, y entonces qué hiciste.",
        situationLabel: "Mientras habla otra persona",
        why: "The whole family: *ajá · claro · ya · exacto · entiendo · sí, sí*. In Spanish the listener makes noise.",
        wordHints: [
          { en: "mm-hm", es: "ajá" },
          { en: "right", es: "claro" },
          { en: "and then", es: "y entonces" },
          { en: "what did you do", es: "qué hiciste" },
        ],
      },
    ],
  },
  {
    day: 247,
    themeEs: "Déjame terminar",
    themeEn: "Let me finish",
    missionEs: "Termina una frase que alguien interrumpió.",
    missionEn: "Finish a sentence someone interrupted.",
    line: "Puedes decirlo sin filo. El tono hace todo el trabajo.",
    lineEn: "You can say it without an edge. Tone does all the work.",
    prompts: [
      {
        id: "d247-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think? I might be wrong.",
        spanish: "¿Y tú qué opinas? Puede que esté equivocada.",
        situationLabel: "Después de decir lo tuyo",
        why: "*Puede que* + shifted verb — one more member of the family you've had since week 5, and it slid in unannounced.",
        wordHints: [
          { en: "it might be that", es: "puede que" },
          { en: "i'm wrong", es: "esté equivocada" },
        ],
      },
      {
        id: "d247-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "Let me finish, it's two more sentences.",
        spanish: "Déjame terminar, son dos frases más.",
        situationLabel: "Cuando se te meten",
        why: "Naming how much is left turns a demand into a deal. Almost nobody refuses two sentences.",
        wordHints: [
          { en: "it's two", es: "son dos" },
          { en: "more sentences", es: "frases más" },
        ],
      },
      {
        id: "d247-a-eso-voy",
        frameStem: "A eso voy…",
        english: "I'm getting to that, but you need to know what came before.",
        spanish: "A eso voy, pero necesitas saber lo de antes.",
        situationLabel: "El contexto primero",
        why: "*Lo de antes* — the earlier business. *Lo de* + anything is how Spanish refers to a whole situation in two words.",
        wordHints: [
          { en: "you need to know", es: "necesitas saber" },
          { en: "what came before", es: "lo de antes" },
        ],
      },
      {
        id: "d247-como-te-decia",
        frameStem: "Como te decía…",
        english: "As I was saying, the problem is the schedule.",
        spanish: "Como te decía, el problema es el horario.",
        situationLabel: "Volviendo al punto",
        why: "One phrase and the interruption is erased. Nobody has to acknowledge that it happened.",
        wordHints: [
          { en: "the problem", es: "el problema" },
          { en: "the schedule", es: "el horario" },
        ],
      },
      {
        id: "d247-aja-claro",
        frameStem: "Ajá, claro…",
        english: "Mm-hm, right — I see where you're going.",
        spanish: "Ajá, ya, ya veo por dónde vas.",
        situationLabel: "Siguiéndole el hilo a Rocío",
        why: "*Ya, ya* doubled means \"I've got it, keep going\" — not \"hurry up\". Tone again.",
        wordHints: [
          { en: "i see", es: "ya veo" },
          { en: "where you're going", es: "por dónde vas" },
        ],
      },
    ],
  },
  {
    day: 248,
    themeEs: "A eso voy",
    themeEn: "I'm getting to that",
    missionEs: "Cuenta una historia larga sin que te apuren.",
    missionEn: "Tell a long story without being rushed.",
    line: "Tres palabras y la gente espera.",
    lineEn: "Three words and people wait.",
    prompts: [
      {
        id: "d248-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think? Maybe I'm seeing it wrong.",
        spanish: "¿Y tú qué opinas? A lo mejor lo estoy viendo mal.",
        situationLabel: "Abriendo de verdad",
        why: "*A lo mejor* — maybe. Unlike *quizás*, it takes the plain present, so there's nothing to shift.",
        wordHints: [
          { en: "maybe", es: "a lo mejor" },
          { en: "i'm seeing it", es: "lo estoy viendo" },
          { en: "wrong", es: "mal" },
        ],
      },
      {
        id: "d248-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "Let me finish the context and it'll explain itself.",
        spanish: "Déjame terminar el contexto y se entiende solo.",
        situationLabel: "Defendiendo el rodeo",
        why: "*Se entiende solo* — it explains itself. A promise that buys you the setup you need.",
        wordHints: [
          { en: "the context", es: "el contexto" },
          { en: "it explains itself", es: "se entiende solo" },
        ],
      },
      {
        id: "d248-a-eso-voy",
        frameStem: "A eso voy…",
        english: "I'm getting to that — I'm going the long way but I'll arrive.",
        spanish: "A eso voy, voy dando la vuelta pero llego.",
        situationLabel: "Pidiendo paciencia",
        why: "*Dar la vuelta* — to go the long way round. Admitting the detour is what earns you the right to take it.",
        wordHints: [
          { en: "i'm going around", es: "voy dando la vuelta" },
          { en: "but i'll arrive", es: "pero llego" },
        ],
      },
      {
        id: "d248-como-te-decia",
        frameStem: "Como te decía…",
        english: "As I was saying, it all started on Tuesday.",
        spanish: "Como te decía, todo empezó el martes.",
        situationLabel: "Retomando desde el principio",
        why: "The narrative reset. Two words and you're back at the top of the story with nobody objecting.",
        wordHints: [
          { en: "everything started", es: "todo empezó" },
          { en: "on tuesday", es: "el martes" },
        ],
      },
      {
        id: "d248-aja-claro",
        frameStem: "Ajá, claro…",
        english: "Mm-hm, right — go ahead.",
        spanish: "Ajá, claro, dale.",
        situationLabel: "Cediéndole el espacio",
        why: "*Dale* is go ahead / go on across most of Latin America. Two syllables that hand someone the floor.",
        wordHints: [
          { en: "go ahead", es: "dale" },
        ],
      },
    ],
  },
  {
    day: 249,
    themeEs: "¿Y tú qué opinas?",
    themeEn: "And what do you think?",
    missionEs: "Regala el turno tres veces a propósito.",
    missionEn: "Give the floor away three times on purpose.",
    line: "Nadie regala el turno. Por eso funciona tanto.",
    lineEn: "Nobody gives the floor away. That's exactly why it works.",
    prompts: [
      {
        id: "d249-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think? You haven't said anything in twenty minutes.",
        spanish: "¿Y tú qué opinas? No has dicho nada en veinte minutos.",
        situationLabel: "Trayendo a Rocío de vuelta",
        why: "Handing over deliberately is a skill nobody teaches. In a three-way it's the difference between two people talking and three.",
        wordHints: [
          { en: "you haven't said", es: "no has dicho" },
          { en: "anything", es: "nada" },
          { en: "in twenty minutes", es: "en veinte minutos" },
        ],
      },
      {
        id: "d249-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "Let me finish and then you two weigh in.",
        spanish: "Déjame terminar y después opinan ustedes dos.",
        situationLabel: "Prometiendo el turno",
        why: "Holding the floor and promising to release it, in one sentence. That's the whole negotiation.",
        wordHints: [
          { en: "and afterwards", es: "y después" },
          { en: "you two weigh in", es: "opinan ustedes dos" },
        ],
      },
      {
        id: "d249-a-eso-voy",
        frameStem: "A eso voy…",
        english: "I'm getting to that — in a second I'll ask you two.",
        spanish: "A eso voy, ahorita les pregunto a ustedes.",
        situationLabel: "Anunciando que vas a preguntar",
        why: "*Ahorita* is in a moment across most of Latin America — sometimes now, sometimes soon, always vague and always used.",
        wordHints: [
          { en: "in a moment", es: "ahorita" },
          { en: "i'll ask you", es: "les pregunto" },
        ],
      },
      {
        id: "d249-como-te-decia",
        frameStem: "Como te decía…",
        english: "As I was saying, that's my part — now yours.",
        spanish: "Como te decía, esa es mi parte, ahora la tuya.",
        situationLabel: "El traspaso limpio",
        why: "Closing your own turn out loud makes the handover unmistakable. Nobody has to guess whether you're done.",
        wordHints: [
          { en: "that's my part", es: "esa es mi parte" },
          { en: "now yours", es: "ahora la tuya" },
        ],
      },
      {
        id: "d249-aja-claro",
        frameStem: "Ajá, claro…",
        english: "Mm-hm, right — tell me more.",
        spanish: "Ajá, claro, cuéntame más.",
        situationLabel: "Manteniéndola hablando",
        why: "Once you've handed over the floor, these are the only sounds you make. They keep the other person going without taking it back.",
        wordHints: [
          { en: "tell me", es: "cuéntame" },
          { en: "more", es: "más" },
        ],
      },
    ],
  },
  {
    day: 250,
    themeEs: "Como te decía",
    themeEn: "As I was saying",
    missionEs: "Que te interrumpan tres veces y vuelve las tres.",
    missionEn: "Get interrupted three times and come back all three.",
    line: "La frase se cayó. Recógela y sigue.",
    lineEn: "The sentence fell. Pick it up and keep going.",
    prompts: [
      {
        id: "d250-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "Right, I finally finished. And what do you think?",
        spanish: "Ya, por fin terminé. ¿Y tú qué opinas?",
        situationLabel: "Después de la tercera interrupción",
        why: "Ending with the handover rather than a complaint. The story got told and nobody had to be scolded.",
        wordHints: [
          { en: "finally", es: "por fin" },
          { en: "i finished", es: "terminé" },
        ],
      },
      {
        id: "d250-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "Let me finish, for the third time.",
        spanish: "Déjame terminar, por tercera vez.",
        situationLabel: "Con humor, no con enojo",
        why: "Said lightly, this is a joke everyone's in on. Said heavily, it ends the evening. Same six words.",
        wordHints: [
          { en: "for the third time", es: "por tercera vez" },
        ],
      },
      {
        id: "d250-a-eso-voy",
        frameStem: "A eso voy…",
        english: "I'm getting to that — don't spoil the ending for me.",
        spanish: "A eso voy, no me adelantes el final.",
        situationLabel: "Cuando adivinan el final",
        why: "*Adelantar el final* — to jump ahead to the ending. Useful for stories, films, and anyone who does this constantly.",
        wordHints: [
          { en: "don't jump ahead for me", es: "no me adelantes" },
          { en: "the ending", es: "el final" },
        ],
      },
      {
        id: "d250-como-te-decia",
        frameStem: "Como te decía…",
        english: "As I was saying, and the third one I never got to say.",
        spanish: "Como te decía, y el tercero no lo dije nunca.",
        situationLabel: "El punto que se te quedó",
        why: "Three uses in one story and none of them sound annoyed. That's the phrase doing its job.",
        wordHints: [
          { en: "the third one", es: "el tercero" },
          { en: "i never said it", es: "no lo dije nunca" },
        ],
      },
      {
        id: "d250-aja-claro",
        frameStem: "Ajá, claro…",
        english: "Mm-hm, right — now I get where you were going.",
        spanish: "Ajá, ya entendí por dónde ibas.",
        situationLabel: "Devolviéndoles el turno",
        why: "Admitting you've only just followed them is generous, and it invites them to keep going.",
        wordHints: [
          { en: "now i understood", es: "ya entendí" },
          { en: "where you were going", es: "por dónde ibas" },
        ],
      },
    ],
  },
  {
    day: 251,
    themeEs: "Ajá, claro",
    themeEn: "Mm-hm, right",
    missionEs: "Escucha diez minutos haciendo ruido.",
    missionEn: "Listen for ten minutes, making noise.",
    line: "Día 195 fue el problema. Hoy es un hábito.",
    lineEn: "Day 195 was the problem. Today it's a habit.",
    prompts: [
      {
        id: "d251-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you really think — not the polite answer?",
        spanish: "¿Y tú qué opinas de verdad, no lo educado?",
        situationLabel: "Pidiendo la respuesta real",
        why: "*Lo educado* — the polite thing. *Lo* + adjective turns any quality into a noun, and it's everywhere in speech.",
        wordHints: [
          { en: "really", es: "de verdad" },
          { en: "the polite thing", es: "lo educado" },
        ],
      },
      {
        id: "d251-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "I didn't need to say \"let me finish\" today.",
        spanish: "Hoy no me hizo falta decir \"déjame terminar\".",
        situationLabel: "Notando lo que no pasó",
        why: "Noticing what you didn't need is its own progress. Some weeks the win is a phrase going unused.",
        wordHints: [
          { en: "i didn't need", es: "no me hizo falta" },
          { en: "to say", es: "decir" },
        ],
      },
      {
        id: "d251-a-eso-voy",
        frameStem: "A eso voy…",
        english: "\"I'm getting to that\" is for when they push you, and today nobody did.",
        spanish: "A eso voy es para cuando te empujan, y hoy no.",
        situationLabel: "La herramienta que no usaste",
        why: "Knowing which tool a situation calls for — and that this one didn't — is what fluency in a conversation looks like.",
        wordHints: [
          { en: "for when", es: "para cuando" },
          { en: "they push you", es: "te empujan" },
        ],
      },
      {
        id: "d251-como-te-decia",
        frameStem: "Como te decía…",
        english: "As I was saying, and this time I actually got to the end.",
        spanish: "Como te decía, y esta vez sí llegué al final.",
        situationLabel: "La historia entera",
        why: "The whole story, start to finish, in Spanish, among three people. That's the season's goal arriving quietly.",
        wordHints: [
          { en: "this time", es: "esta vez" },
          { en: "i did get", es: "sí llegué" },
          { en: "to the end", es: "al final" },
        ],
      },
      {
        id: "d251-aja-claro",
        frameStem: "Ajá, claro…",
        english: "Mm-hm, right — and what did your grandmother say?",
        spanish: "Ajá, claro, y tu abuela qué dijo.",
        situationLabel: "Diez minutos escuchando a Camila",
        why: "Day 195 taught this as a problem. Ten weeks later it's a habit, and Camila never had to ask if you were still there.",
        wordHints: [
          { en: "your grandmother", es: "tu abuela" },
          { en: "what did she say", es: "qué dijo" },
        ],
      },
    ],
  },
  {
    day: 252,
    themeEs: "Repaso: El turno",
    themeEn: "Review: Taking turns",
    missionEs: "Una conversación de tres donde hablaron las tres.",
    missionEn: "A conversation among three where all three talked.",
    line: "Ninguna de las cinco es vocabulario. Todas son tiempo.",
    lineEn: "None of the five is vocabulary. All of them are timing.",
    prompts: [
      {
        id: "d252-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "\"And what do you think?\" changes an entire conversation.",
        spanish: "¿Y tú qué opinas? cambia una conversación entera.",
        situationLabel: "La más generosa",
        why: "The one you'll use for the rest of your life, in both languages, and it costs four words.",
        wordHints: [
          { en: "changes", es: "cambia" },
          { en: "a whole conversation", es: "una conversación entera" },
        ],
      },
      {
        id: "d252-dejame-terminar",
        frameStem: "Déjame terminar…",
        english: "\"Let me finish\" was hard to say without sounding annoyed.",
        spanish: "Déjame terminar me costó decirlo sin sonar molesta.",
        situationLabel: "La que más te costó",
        why: "The words were never the problem. Saying them without an edge took the whole week.",
        wordHints: [
          { en: "was hard for me", es: "me costó" },
          { en: "to say it", es: "decirlo" },
          { en: "without sounding annoyed", es: "sin sonar molesta" },
        ],
      },
      {
        id: "d252-a-eso-voy",
        frameStem: "A eso voy…",
        english: "\"I'm getting to that\" bought me the whole story.",
        spanish: "A eso voy me compró la historia entera.",
        situationLabel: "La más eficiente",
        why: "Three words, and a story that would have been cut in half got told all the way through.",
        wordHints: [
          { en: "bought me", es: "me compró" },
          { en: "the whole story", es: "la historia entera" },
        ],
      },
      {
        id: "d252-como-te-decia",
        frameStem: "Como te decía…",
        english: "\"As I was saying\" picks the sentence up where it fell.",
        spanish: "Como te decía recoge la frase donde se cayó.",
        situationLabel: "La más elegante",
        why: "No resentment, no accusation, no lost content. Three problems solved by two words.",
        wordHints: [
          { en: "picks up", es: "recoge" },
          { en: "the sentence", es: "la frase" },
          { en: "where it fell", es: "donde se cayó" },
        ],
      },
      {
        id: "d252-aja-claro",
        frameStem: "Ajá, claro…",
        english: "\"Mm-hm, right\" turned out to be the other half of talking.",
        spanish: "Ajá, claro resultó ser la otra mitad de conversar.",
        situationLabel: "La que más tardó",
        why: "Five phrases and the shape of a conversation changes. None of them is new vocabulary — all of them are timing.",
        wordHints: [
          { en: "turned out to be", es: "resultó ser" },
          { en: "the other half", es: "la otra mitad" },
          { en: "of conversing", es: "de conversar" },
        ],
      },
    ],
  },
];
