import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 13 — "Ida y vuelta" (days 267–273). The season capstone.
 * Each `spanish` is copied verbatim from content/drafts/invierno/week13-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek13SpeakDays: SpeakDay[] = [
  {
    day: 267,
    themeEs: "La última semana",
    themeEn: "The last week",
    missionEs: "Habla del invierno entero, en presente.",
    missionEn: "Talk about the whole winter, in the present.",
    line: "Hace noventa y un días no sabías llenar un silencio.",
    lineEn: "Ninety-one days ago you couldn't fill a silence.",
    prompts: [
      {
        id: "d267-pues",
        frameStem: "Pues…",
        english: "Well, winter's ending and I didn't feel it go by.",
        spanish: "Pues, se acaba el invierno y ni lo sentí pasar.",
        situationLabel: "Lunes de la última semana",
        why: "Ninety-one days ago this word was a lifeline. Now it's just how you start a sentence — which is exactly what was supposed to happen.",
        wordHints: [
          { en: "winter's ending", es: "se acaba el invierno" },
          { en: "i didn't even feel it", es: "ni lo sentí" },
          { en: "go by", es: "pasar" },
        ],
      },
      {
        id: "d267-quiero-que",
        frameStem: "Quiero que…",
        english: "I want Camila to hear the January one with me.",
        spanish: "Quiero que Camila oiga lo de enero conmigo.",
        situationLabel: "El plan de la semana",
        why: "*Lo de enero* — the January business. Two words for a whole recording, a whole month, and a whole version of yourself.",
        wordHints: [
          { en: "camila hears", es: "camila oiga" },
          { en: "the january one", es: "lo de enero" },
          { en: "with me", es: "conmigo" },
        ],
      },
      {
        id: "d267-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt, but this can't wait until Thursday.",
        spanish: "Perdona que te interrumpa, pero esto no puede esperar al jueves.",
        situationLabel: "Escribiéndole un martes",
        why: "Interrupting the week itself. Four months ago you'd have saved it, and then never said it.",
        wordHints: [
          { en: "this can't wait", es: "esto no puede esperar" },
          { en: "until thursday", es: "al jueves" },
        ],
      },
      {
        id: "d267-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think? You heard me from the very start.",
        spanish: "¿Y tú qué opinas? Tú me oíste desde el principio.",
        situationLabel: "Preguntándole a la testigo",
        why: "The one person who has the before and the after in her ears. Her answer is worth more than your own memory.",
        wordHints: [
          { en: "you heard me", es: "tú me oíste" },
          { en: "from the start", es: "desde el principio" },
        ],
      },
      {
        id: "d267-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that winter wasn't about grammar.",
        spanish: "Más o menos entendí que el invierno no era de gramática.",
        situationLabel: "El balance que empieza",
        why: "Four weeks of subjunctive and not one table. Worth being able to say that plainly.",
        wordHints: [
          { en: "the winter", es: "el invierno" },
          { en: "wasn't about", es: "no era de" },
          { en: "grammar", es: "gramática" },
        ],
      },
    ],
  },
  {
    day: 268,
    themeEs: "El audio de enero",
    themeEn: "The January recording",
    missionEs: "Escucha quién eras y descríbelo sin ser cruel.",
    missionEn: "Listen to who you were and describe her without being cruel.",
    line: "Once segundos, grabados el día 204. Los guardaste para esto.",
    lineEn: "Eleven seconds, recorded on day 204. You kept them for this.",
    prompts: [
      {
        id: "d268-pues",
        frameStem: "Pues…",
        english: "Well, here it is: eleven seconds and three pauses.",
        spanish: "Pues, aquí está: once segundos y tres pausas.",
        situationLabel: "Dándole play",
        why: "You counted the pauses. That's the same instinct as counting holes — but this time it's measurement, not judgment.",
        wordHints: [
          { en: "here it is", es: "aquí está" },
          { en: "eleven seconds", es: "once segundos" },
          { en: "three pauses", es: "tres pausas" },
        ],
      },
      {
        id: "d268-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to hear it without me saying anything first.",
        spanish: "Quiero que lo oigas sin que te diga nada antes.",
        situationLabel: "Sin condicionar la respuesta",
        why: "Two shifted verbs stacked — *oigas* and *diga* — built in real time without a pause. That's the whole subjunctive month, spent.",
        wordHints: [
          { en: "you hear it", es: "lo oigas" },
          { en: "without me telling you", es: "sin que te diga" },
          { en: "anything first", es: "nada antes" },
        ],
      },
      {
        id: "d268-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt — did I really sound like that?",
        spanish: "Perdona que te interrumpa, ¿de verdad sonaba así?",
        situationLabel: "A mitad de la grabación",
        why: "Nobody recognizes their own recording. That gap between how you sound and how you thought you sounded is the whole point of keeping it.",
        wordHints: [
          { en: "really", es: "de verdad" },
          { en: "did i sound", es: "sonaba" },
          { en: "like that", es: "así" },
        ],
      },
      {
        id: "d268-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think — without humoring me?",
        spanish: "¿Y tú qué opinas, sin consentirme?",
        situationLabel: "Pidiendo la versión honesta",
        why: "You've learned to ask for the unflattering answer. That's a harder skill than any of the grammar.",
        wordHints: [
          { en: "without humoring me", es: "sin consentirme" },
        ],
      },
      {
        id: "d268-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that the January one was asking permission.",
        spanish: "Más o menos entendí que la de enero estaba pidiendo permiso.",
        situationLabel: "El diagnóstico honesto",
        why: "Two recordings, two months apart, and no argument possible. This is why week 4 told you to keep the first one.",
        wordHints: [
          { en: "the january one", es: "la de enero" },
          { en: "was asking", es: "estaba pidiendo" },
          { en: "permission", es: "permiso" },
        ],
      },
    ],
  },
  {
    day: 269,
    themeEs: "Lo que cambió",
    themeEn: "What changed",
    missionEs: "Explica el cambio sin decir \"mejoré\".",
    missionEn: "Explain the change without saying \"I got better\".",
    line: "\"Mejoré\" no explica nada y no se puede repetir.",
    lineEn: "\"I got better\" explains nothing and can't be repeated.",
    prompts: [
      {
        id: "d269-pues",
        frameStem: "Pues…",
        english: "Well, what changed wasn't the vocabulary.",
        spanish: "Pues, lo que cambió no fue el vocabulario.",
        situationLabel: "El inventario honesto",
        why: "\"I got better\" explains nothing and can't be repeated. Naming the specific thing is what lets you do it again in spring.",
        wordHints: [
          { en: "what changed", es: "lo que cambió" },
          { en: "wasn't", es: "no fue" },
          { en: "the vocabulary", es: "el vocabulario" },
        ],
      },
      {
        id: "d269-quiero-que",
        frameStem: "Quiero que…",
        english: "I want my students to have this without waiting ten years.",
        spanish: "Quiero que mis estudiantes tengan esto sin esperar diez años.",
        situationLabel: "Lo que harás con ello",
        why: "The season keeps ending up here. Everything you learned goes back into a classroom, which is why it stuck.",
        wordHints: [
          { en: "my students have", es: "mis estudiantes tengan" },
          { en: "without waiting", es: "sin esperar" },
          { en: "ten years", es: "diez años" },
        ],
      },
      {
        id: "d269-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt: it was ninety-one days in a row.",
        spanish: "Perdona que te interrumpa: fueron noventa y un días seguidos.",
        situationLabel: "Corrigiendo el cumplido",
        why: "Interrupting to refuse the word *talent*. The real answer is duller and far more useful.",
        wordHints: [
          { en: "it was", es: "fueron" },
          { en: "ninety-one days", es: "noventa y un días" },
          { en: "in a row", es: "seguidos" },
        ],
      },
      {
        id: "d269-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think was the first thing that changed?",
        spanish: "¿Y tú qué opinas que fue lo primero que cambió?",
        situationLabel: "Desde afuera",
        why: "You can't see your own first change. Someone who watched it happen can name it in one sentence.",
        wordHints: [
          { en: "what was", es: "qué fue" },
          { en: "the first thing", es: "lo primero" },
          { en: "that changed", es: "que cambió" },
        ],
      },
      {
        id: "d269-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that what works is speaking every day, a little.",
        spanish: "Más o menos entendí que lo que sirve es hablar todos los días, poquito.",
        situationLabel: "La conclusión repetible",
        why: "The whole method in nine words, and the only version of it you'll still remember in a year.",
        wordHints: [
          { en: "what works", es: "lo que sirve" },
          { en: "speaking every day", es: "hablar todos los días" },
          { en: "a little", es: "poquito" },
        ],
      },
    ],
  },
  {
    day: 270,
    themeEs: "Yesenia en el café",
    themeEn: "Yesenia at the café",
    missionEs: "Presenta a dos personas y sostén la conversación entre las cuatro.",
    missionEn: "Introduce two people and hold a conversation among four.",
    line: "Trajiste a tu estudiante al café. En enero la estudiante eras tú.",
    lineEn: "You brought your student to the café. In January you were the student.",
    prompts: [
      {
        id: "d270-pues",
        frameStem: "Pues…",
        english: "Well, Yesenia, this is Camila — she's responsible for all of it.",
        spanish: "Pues, Yesenia, esta es Camila, la culpable de todo.",
        situationLabel: "Presentándolas",
        why: "*La culpable* — the guilty party. Used affectionately, and there's no neat English equivalent for the warmth in it.",
        wordHints: [
          { en: "this is", es: "esta es" },
          { en: "the one responsible", es: "la culpable" },
          { en: "for everything", es: "de todo" },
        ],
      },
      {
        id: "d270-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to know I used to apologize eleven times an hour too.",
        spanish: "Quiero que sepas que yo también me disculpaba once veces por hora.",
        situationLabel: "Quitándole la vergüenza",
        why: "Week 8 gave the advice; this is the advice arriving with the person attached, which is the version that works.",
        wordHints: [
          { en: "you know", es: "sepas" },
          { en: "i too apologized", es: "yo también me disculpaba" },
          { en: "eleven times an hour", es: "once veces por hora" },
        ],
      },
      {
        id: "d270-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt: it really was that bad.",
        spanish: "Perdona que te interrumpa: sí era tan malo.",
        situationLabel: "Cuando Camila te defiende de más",
        why: "Interrupting to insist your own beginning was as rough as it was. That honesty is the useful part of the story.",
        wordHints: [
          { en: "it really was", es: "sí era" },
          { en: "that bad", es: "tan malo" },
        ],
      },
      {
        id: "d270-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think, Yesenia? You've been listening to us for half an hour.",
        spanish: "¿Y tú qué opinas, Yesenia? Llevas media hora oyéndonos.",
        situationLabel: "Trayéndola a la mesa",
        why: "Someone did this for you in a café in January. Doing it for someone else is how a season closes properly.",
        wordHints: [
          { en: "you've been", es: "llevas" },
          { en: "half an hour", es: "media hora" },
          { en: "listening to us", es: "oyéndonos" },
        ],
      },
      {
        id: "d270-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that it isn't the English that worries you, it's the embarrassment.",
        spanish: "Más o menos entendí que no te preocupa el inglés, te preocupa la pena.",
        situationLabel: "Reconociéndolo desde dentro",
        why: "You can name it because you had it. That's the only qualification this conversation needs.",
        wordHints: [
          { en: "it doesn't worry you", es: "no te preocupa" },
          { en: "the embarrassment", es: "la pena" },
        ],
      },
    ],
  },
  {
    day: 271,
    themeEs: "Una charla de ida y vuelta",
    themeEn: "A proper back-and-forth",
    missionEs: "Las cinco frases de hoy son una sola conversación. Dilas seguidas.",
    missionEn: "Today's five sentences are one conversation. Say them as one stretch.",
    line: "Dos horas, cuatro personas, un idioma.",
    lineEn: "Two hours, four people, one language.",
    prompts: [
      {
        id: "d271-pues",
        frameStem: "Pues…",
        english: "Well, let me tell you how it actually went.",
        spanish: "Pues, te cuento cómo fue de verdad.",
        situationLabel: "Beat 1 — abriendo la historia",
        why: "Today's five prompts are the beats of one conversation, in order. Say them as a single stretch, not as five exercises.",
        wordHints: [
          { en: "i'll tell you", es: "te cuento" },
          { en: "how it went", es: "cómo fue" },
          { en: "really", es: "de verdad" },
        ],
      },
      {
        id: "d271-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to let me get to the end before weighing in.",
        spanish: "Quiero que me dejen llegar al final antes de opinar.",
        situationLabel: "Beat 2 — pidiendo el turno largo",
        why: "Week 5's chunk doing week 10's job. By now the two are indistinguishable, which is the point.",
        wordHints: [
          { en: "you let me", es: "me dejen" },
          { en: "get to the end", es: "llegar al final" },
          { en: "before weighing in", es: "antes de opinar" },
        ],
      },
      {
        id: "d271-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt, but half of that story is missing.",
        spanish: "Perdona que te interrumpa, falta la mitad de esa historia.",
        situationLabel: "Beat 3 — entrando cuando habla otra",
        why: "Holding the floor and taking it, in the same conversation, without either one feeling like a fight.",
        wordHints: [
          { en: "half is missing", es: "falta la mitad" },
          { en: "of that story", es: "de esa historia" },
        ],
      },
      {
        id: "d271-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think, now that you've heard the whole winter at once?",
        spanish: "¿Y tú qué opinas, ahora que oíste todo el invierno de golpe?",
        situationLabel: "Beat 4 — devolviendo el turno",
        why: "*De golpe* — all at once. Two hours of talking, and the sentence that ends it is a question.",
        wordHints: [
          { en: "now that", es: "ahora que" },
          { en: "you heard", es: "oíste" },
          { en: "all at once", es: "de golpe" },
        ],
      },
      {
        id: "d271-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that the hard part comes now, not before.",
        spanish: "Más o menos entendí que lo difícil viene ahora, no antes.",
        situationLabel: "Beat 5 — cerrando lo que te dijeron",
        why: "Catching what they said back to you and checking it. The conversation closes its own loop.",
        wordHints: [
          { en: "the hard part", es: "lo difícil" },
          { en: "comes now", es: "viene ahora" },
          { en: "not before", es: "no antes" },
        ],
      },
    ],
  },
  {
    day: 272,
    themeEs: "Lo que viene",
    themeEn: "What comes next",
    missionEs: "Nombra lo que todavía te falta, sin quitarle mérito a lo hecho.",
    missionEn: "Name what you still lack, without discounting what you did.",
    line: "El invierno hizo lo que prometió. La primavera quiere algo más difícil.",
    lineEn: "Winter did what it promised. Spring wants something harder.",
    prompts: [
      {
        id: "d272-pues",
        frameStem: "Pues…",
        english: "Well, I'm missing my humor. In English I'm funny.",
        spanish: "Pues, me falta el humor. En inglés soy graciosa.",
        situationLabel: "El hueco que queda",
        why: "The gap the spring season exists for, named from inside winter: you sound natural, but you don't yet sound like *you*.",
        wordHints: [
          { en: "i'm missing", es: "me falta" },
          { en: "humor", es: "el humor" },
          { en: "i'm funny", es: "soy graciosa" },
        ],
      },
      {
        id: "d272-quiero-que",
        frameStem: "Quiero que…",
        english: "I want spring to be about personality, not technique.",
        spanish: "Quiero que la primavera sea de personalidad, no de técnica.",
        situationLabel: "La meta siguiente",
        why: "A goal stated precisely enough to work toward. Vague goals produce vague seasons.",
        wordHints: [
          { en: "spring is", es: "la primavera sea" },
          { en: "about personality", es: "de personalidad" },
          { en: "technique", es: "técnica" },
        ],
      },
      {
        id: "d272-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt: five sentences a day, nothing more.",
        spanish: "Perdona que te interrumpa: cinco frases al día, nada más.",
        situationLabel: "Frenando los planes grandes",
        why: "Interrupting a plan before it gets ambitious enough to fail. The small version is the one that survived winter.",
        wordHints: [
          { en: "five sentences", es: "cinco frases" },
          { en: "a day", es: "al día" },
          { en: "nothing more", es: "nada más" },
        ],
      },
      {
        id: "d272-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think I'm actually missing?",
        spanish: "¿Y tú qué opinas que me falta de verdad?",
        situationLabel: "Pidiendo el diagnóstico",
        why: "Asking someone to name your weakness out loud. Harder than any sentence in this season, and you can do it now.",
        wordHints: [
          { en: "i'm missing", es: "me falta" },
          { en: "really", es: "de verdad" },
        ],
      },
      {
        id: "d272-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that sounding natural and sounding like me aren't the same thing.",
        spanish: "Más o menos entendí que sonar natural y sonar como yo no es lo mismo.",
        situationLabel: "La distinción que importa",
        why: "The sentence that separates this season from the next one. Winter got you to natural; spring is for the rest.",
        wordHints: [
          { en: "sounding natural", es: "sonar natural" },
          { en: "sounding like me", es: "sonar como yo" },
          { en: "the same thing", es: "lo mismo" },
        ],
      },
    ],
  },
  {
    day: 273,
    themeEs: "Repaso: El invierno entero",
    themeEn: "Review: The whole winter",
    missionEs: "Di el invierno entero en cinco frases.",
    missionEn: "Say the whole winter in five sentences.",
    line: "Día noventa y uno. El último.",
    lineEn: "Day ninety-one. The last one.",
    prompts: [
      {
        id: "d273-pues",
        frameStem: "Pues…",
        english: "Well, day ninety-one, and I'm still here.",
        spanish: "Pues, día noventa y uno, y sigo aquí.",
        situationLabel: "El último día",
        why: "The app's name, the season's first frame, and the last sentence of the last day. *Pues* was never filler — it was permission to keep going.",
        wordHints: [
          { en: "day ninety-one", es: "día noventa y uno" },
          { en: "i'm still here", es: "sigo aquí" },
        ],
      },
      {
        id: "d273-quiero-que",
        frameStem: "Quiero que…",
        english: "I want Camila to know what she did without meaning to.",
        spanish: "Quiero que Camila sepa lo que hizo sin proponérselo.",
        situationLabel: "Lo que hay que decir en voz alta",
        why: "*Sin proponérselo* — without setting out to. The thing worth saying to anyone who taught you something by accident.",
        wordHints: [
          { en: "camila knows", es: "camila sepa" },
          { en: "what she did", es: "lo que hizo" },
          { en: "without meaning to", es: "sin proponérselo" },
        ],
      },
      {
        id: "d273-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt: thank you, and that's all.",
        spanish: "Perdona que te interrumpa: gracias, y ya está.",
        situationLabel: "La última interrupción del invierno",
        why: "Interrupting to say thank you, which is the only reason worth interrupting anyone. And *y ya está* — and that's it.",
        wordHints: [
          { en: "thank you", es: "gracias" },
          { en: "and that's it", es: "y ya está" },
        ],
      },
      {
        id: "d273-y-tu-que-opinas",
        frameStem: "¿Y tú qué opinas?",
        english: "And what do you think? Last question of the winter.",
        spanish: "¿Y tú qué opinas? Última pregunta del invierno.",
        situationLabel: "Cerrando como empezaste",
        why: "The season ends by handing the floor away. That's not a flourish — it's the skill you spent thirteen weeks learning.",
        wordHints: [
          { en: "last question", es: "última pregunta" },
          { en: "of the winter", es: "del invierno" },
        ],
      },
      {
        id: "d273-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that speaking is a habit, not a talent.",
        spanish: "Más o menos entendí que hablar es un hábito, no un talento.",
        situationLabel: "El invierno, en una frase",
        why: "Ninety-one days for one sentence. The season's goals were \"watch something without subtitles\" and \"a back-and-forth conversation\". Both happened, on ordinary days, without ceremony.",
        wordHints: [
          { en: "speaking", es: "hablar" },
          { en: "a habit", es: "un hábito" },
          { en: "a talent", es: "un talento" },
        ],
      },
    ],
  },
];
