import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 12 — "La panadería" (days 260–266).
 * Camila takes Marlana to a Colombian bakery in East Boston where nobody slows
 * down for anybody. The week's discovery is that the problem was never
 * pronunciation — it was rhythm, and rhythm is copied rather than studied.
 */
export const invWeek12ReadingDays: ReadingDay[] = [
  {
    day: 260,
    themeEs: "En la panadería",
    storyTitle: "La panadería",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el pan de bono", en: "pan de bono (Colombian cheese bread)", example: "¿Todavía queda pan de bono?" },
      { es: "quiubo", en: "hey, what's up (from ¿qué hubo?)", example: "Quiubo, ¿cómo va todo?" },
      { es: "el mostrador", en: "the counter", example: "Pedí en el mostrador sin ayuda." },
      { es: "acomodarse a alguien", en: "to adjust to someone", example: "Aquí nadie se acomoda a ti." },
      { es: "el ritmo", en: "the rhythm", example: "El problema no era el acento, era el ritmo." },
    ],
    dialogue: {
      title: "Aquí nadie baja el ritmo",
      situation: "Camila lleva a Marlana a una panadería colombiana en East Boston",
      lines: [
        { speaker: "B", es: "Te advierto: aquí nadie te va a hablar despacio. Ni por educación.", en: "Fair warning: nobody here is going to talk to you slowly. Not even out of politeness." },
        { speaker: "A", es: "Perfecto. Eso es justo lo que necesito.", en: "Perfect. That's exactly what I need." },
        { speaker: "B", es: "Quiubo, doña Marta. ¿Cómo amaneció?", en: "Hey, Doña Marta. How did you wake up?" },
        { speaker: "A", es: "¿Qué hubo? ¿Todavía queda pan de bono?", en: "Hey — is there still any pan de bono?" },
        { speaker: "B", es: "Espera. ¿Dijiste \"quiubo\"?", en: "Hang on. Did you just say \"quiubo\"?" },
        { speaker: "A", es: "Te lo copié hace tres segundos. Voy a llevar dos de estos y un café.", en: "I copied it off you three seconds ago. I'm going to take two of these and a coffee." },
        { speaker: "B", es: "¿Y eso? Nunca pides tú.", en: "How come? You never order." },
        { speaker: "A", es: "Para que lo prueben en la casa. Y para que la próxima venga sola.", en: "So they can try it at home. And so next time I come on my own." },
        { speaker: "B", es: "Está bien. Pero fíjate: llevas cuatro frases y en todas te comiste algo.", en: "All right. But notice: that's four sentences and in every one you swallowed something." },
      ],
    },
  },
  {
    day: 261,
    themeEs: "Quiubo",
    storyTitle: "La panadería",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "amanecer", en: "to wake up, to greet the morning", example: "¿Cómo amaneció, doña Marta?" },
      { es: "el saludo", en: "the greeting", example: "Los saludos del libro no son los de la calle." },
      { es: "reconocer", en: "to recognize", example: "Ya me reconoce la señora." },
      { es: "arreglarse con algo", en: "to make do with something", example: "Con eso me arreglo." },
      { es: "la costumbre", en: "the habit", example: "Para que se me haga costumbre venir." },
    ],
    dialogue: {
      title: "Los saludos que no vienen en el libro",
      situation: "Segunda visita; Marlana viene sola",
      lines: [
        { speaker: "A", es: "¿Qué hubo, doña Marta? ¿Cómo amaneció?", en: "Hey, Doña Marta. How did you wake up?" },
        { speaker: "B", es: "¡Bien, mija! ¿Y su amiga?", en: "Well, dear! And your friend?" },
        { speaker: "A", es: "Trabajando. Vine sola. Voy a pedir lo mismo de la otra vez.", en: "Working. I came alone. I'm going to order the same as last time." },
        { speaker: "B", es: "El de queso. Se acabó hace media hora, mi amor.", en: "The cheese one. It sold out half an hour ago, love." },
        { speaker: "A", es: "¿Y eso? ¿Se acabó tan temprano?", en: "How come? It sold out that early?" },
        { speaker: "B", es: "Sábado. Aquí a las nueve ya no queda nada de eso.", en: "Saturday. By nine there's none of that left here." },
        { speaker: "A", es: "Está bien, entonces me llevo otra cosa. Voy a llevarme uno de esos que no conozco.", en: "That's fine, then I'll take something else. I'll take one of those I don't know." },
        { speaker: "B", es: "Ese es almojábana. Lleve dos, para que los pruebe bien.", en: "That's almojábana. Take two, so you can properly try them." },
        { speaker: "A", es: "Para que me aprenda los nombres de todo. Uno por semana, doña Marta.", en: "So I learn the names of everything. One a week, Doña Marta." },
      ],
    },
  },
  {
    day: 262,
    themeEs: "Pa' que",
    storyTitle: "La panadería",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "pegársele a alguien", en: "to rub off on someone", example: "Se me pegó el acento colombiano." },
      { es: "a propósito", en: "on purpose", example: "Voy a hablar rápido a propósito." },
      { es: "la reducción", en: "the reduction", example: "\"Pa' que\" es una reducción de \"para que\"." },
      { es: "sonar a", en: "to sound like", example: "Quiero sonar a persona, no a libro." },
      { es: "el examen", en: "the exam, the test", example: "No quiero que suene a examen." },
    ],
    dialogue: {
      title: "Tres meses oyéndolo",
      situation: "Marlana se da cuenta de algo en el salón de maestros",
      lines: [
        { speaker: "A", es: "¿Qué hubo, Rocío? Te traje algo de la panadería.", en: "Hey, Rocío. I brought you something from the bakery." },
        { speaker: "B", es: "¡Ay, qué rico! ¿Y eso? ¿Desde cuándo hablas así?", en: "Oh, lovely! How come? Since when do you talk like that?" },
        { speaker: "A", es: "¿Así cómo?", en: "Like how?" },
        { speaker: "B", es: "Dijiste \"quiubo\" y te comiste medio \"qué hubo\". Suena bien.", en: "You said \"quiubo\" and swallowed half of \"qué hubo\". It sounds good." },
        { speaker: "A", es: "Es lo que estoy practicando. Voy a copiarle el ritmo a Camila toda la semana.", en: "That's what I'm practicing. I'm going to copy Camila's rhythm all week." },
        { speaker: "B", es: "Pues ya te está funcionando.", en: "Well, it's working already." },
        { speaker: "A", es: "Oye, una cosa: tú dices \"pa' que\", ¿verdad? Llevo tres meses oyéndolo y creía que era otra palabra.", en: "Hey, one thing: you say \"pa' que\", right? I've spent three months hearing it and thought it was a different word." },
        { speaker: "B", es: "Ja. Todo el mundo dice \"pa' que\". \"Para que\" es de escribir.", en: "Ha. Everybody says \"pa' que\". \"Para que\" is for writing." },
        { speaker: "A", es: "Para que suene como conversación y no como examen. Eso es todo lo que quiero.", en: "So that it sounds like conversation and not like an exam. That's all I want." },
      ],
    },
  },
  {
    day: 263,
    themeEs: "Tá bien",
    storyTitle: "La panadería",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "comerse las sílabas", en: "to swallow syllables", example: "Todos se comen sílabas al hablar." },
      { es: "esperar despiertos", en: "to wait up", example: "Que no me esperen despiertos." },
      { es: "la sílaba", en: "the syllable", example: "\"Voy a estar\" son tres reducciones seguidas." },
      { es: "tranquila", en: "calm, at ease", example: "Ya estoy más tranquila." },
      { es: "el día libre", en: "the day off", example: "¿Te dieron el día libre?" },
    ],
    dialogue: {
      title: "Voy'a'tar",
      situation: "Audios de ida y vuelta un miércoles cualquiera",
      lines: [
        { speaker: "A", es: "¿Qué hubo? Te mando un audio rapidito. Voy a estar en la casa como a las seis.", en: "Hey — sending you a quick voice note. I'm going to be home around six." },
        { speaker: "B", es: "Marlana. Reproduce tu propio audio y escucha esa frase.", en: "Marlana. Play your own voice note back and listen to that sentence." },
        { speaker: "A", es: "…Dije \"voy'a'tar\". Tres palabras en una.", en: "…I said \"voy'a'tar\". Three words in one." },
        { speaker: "B", es: "Exacto. Nadie dice \"voy a estar\" entero. Nadie.", en: "Exactly. Nobody says \"voy a estar\" in full. Nobody." },
        { speaker: "A", es: "Y yo llevaba ocho meses diciéndolo entero como una locutora de radio.", en: "And I spent eight months saying it in full like a radio announcer." },
        { speaker: "B", es: "Por eso se te notaba. No era el acento, era que decías todo completo.", en: "That's why it showed. It wasn't your accent, it was that you said everything complete." },
        { speaker: "A", es: "Está bien, ya lo sé. Y \"está bien\" tampoco lo digo entero, ¿verdad?", en: "That's fine, I know now. And I don't say \"está bien\" in full either, do I?" },
        { speaker: "B", es: "\"Tá bien\". Igual que \"toy\" y \"tamos\". La primera sílaba de \"estar\" es opcional.", en: "\"Tá bien\". Same as \"toy\" and \"tamos\". The first syllable of \"estar\" is optional." },
        { speaker: "A", es: "Para que no me esperen despiertos, entonces. Voy a estar ocupada hasta las cuatro.", en: "So nobody waits up for me, then. I'm going to be busy until four." },
      ],
    },
  },
  {
    day: 264,
    themeEs: "A uno y medio",
    storyTitle: "La panadería",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "acelerar", en: "to speed up", example: "Aceleré el pódcast a uno y medio." },
      { es: "uno y medio", en: "one and a half (1.5× speed)", example: "Lo dejé a uno y medio toda la semana." },
      { es: "acostumbrarse", en: "to get used to", example: "El oído se acostumbra solo." },
      { es: "costarle trabajo a alguien", en: "to be hard work for someone", example: "Para que deje de costarme trabajo." },
      { es: "ocurrírsele a alguien", en: "for something to occur to someone", example: "¿A quién se le ocurre acelerarlo?" },
    ],
    dialogue: {
      title: "El chaleco con pesas",
      situation: "Marlana le cuenta a Camila su experimento con el pódcast",
      lines: [
        { speaker: "A", es: "¿Qué hubo? Hice algo raro y te tengo que contar.", en: "Hey — I did something odd and I have to tell you." },
        { speaker: "B", es: "Cuéntame.", en: "Tell me." },
        { speaker: "A", es: "Puse el pódcast a uno y medio. A propósito. Y aguanté el episodio entero.", en: "I put the podcast at one and a half. On purpose. And I made it through the whole episode." },
        { speaker: "B", es: "¿Y eso? ¿A quién se le ocurre acelerarlo? ¿No era ya bastante difícil?", en: "How come? Who thinks to speed it up? Wasn't it hard enough already?" },
        { speaker: "A", es: "Para que la velocidad normal me parezca lenta. Como correr con pesas.", en: "So that normal speed feels slow to me. Like running with weights." },
        { speaker: "B", es: "¿Y funcionó?", en: "And did it work?" },
        { speaker: "A", es: "Al día siguiente puse la serie a velocidad normal y me pareció que hablaban despacísimo.", en: "The next day I put the series on at normal speed and it sounded like they were talking incredibly slowly." },
        { speaker: "B", es: "Eso es exactamente lo que pasa. Nosotros lo hacemos con el inglés.", en: "That's exactly what happens. We do that with English." },
        { speaker: "A", es: "Está bien perder algunas palabras si sigo el hilo. Voy a dejarlo a uno y medio toda la semana.", en: "It's fine to lose some words if I follow the thread. I'm going to leave it at one and a half all week." },
      ],
    },
  },
  {
    day: 265,
    themeEs: "Ya no me hablan despacio",
    storyTitle: "La panadería",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "el cumplido", en: "the compliment", example: "Voy a tomármelo como cumplido." },
      { es: "consentir a alguien", en: "to humor someone", example: "Dime la verdad, no me consientas." },
      { es: "la excepción", en: "the exception", example: "Ya no soy la excepción en la mesa." },
      { es: "tratar a alguien", en: "to treat someone", example: "Para que me traten como a cualquiera." },
      { es: "hablar raro", en: "to talk strangely", example: "Prefiero perderme algo a que me hablen raro." },
    ],
    dialogue: {
      title: "Nadie baja el ritmo por mí",
      situation: "Marlana nota algo y no sabe si le gusta",
      lines: [
        { speaker: "A", es: "¿Qué hubo? Hoy me saludaron ellos primero en la panadería.", en: "Hey — today they greeted me first at the bakery." },
        { speaker: "B", es: "¡Ya eres de la casa!", en: "You're one of the regulars now!" },
        { speaker: "A", es: "Sí, pero pasó otra cosa. ¿Y eso? ¿Ya no me hablan despacio o me lo imagino?", en: "Yes, but something else happened. How come? Do they not slow down for me anymore, or am I imagining it?" },
        { speaker: "B", es: "No te lo imaginas. Yo también dejé de hacerlo, como en enero.", en: "You're not imagining it. I stopped doing it too, around January." },
        { speaker: "A", es: "¿En enero? ¿Y no me dijiste?", en: "In January? And you didn't tell me?" },
        { speaker: "B", es: "Si te lo digo, te pones nerviosa y hablas peor. Lo hice a propósito.", en: "If I'd told you, you'd have got nervous and spoken worse. I did it on purpose." },
        { speaker: "A", es: "Dime la verdad, no me consientas: ¿es bueno o me estoy perdiendo cosas?", en: "Tell me the truth, don't humor me: is it good, or am I missing things?" },
        { speaker: "B", es: "Te pierdes cosas. Y aun así entiendes más que en octubre. Las dos cosas son ciertas.", en: "You do miss things. And you still understand more than in October. Both are true." },
        { speaker: "A", es: "Está bien, prefiero perderme algo a que me hablen raro. Para que dejen de acomodarse a mí.", en: "That's fine — I'd rather miss something than be spoken to strangely. So they stop adjusting to me." },
      ],
    },
  },
  {
    day: 266,
    themeEs: "Repaso: A velocidad real",
    isRecap: true,
    vocab: [
      { es: "la sílaba", en: "the syllable", example: "Las mismas palabras, la mitad de las sílabas." },
      { es: "copiarse el ritmo", en: "to copy the rhythm", example: "El ritmo se copia, no se estudia." },
      { es: "volvérsele a alguien", en: "to turn into, for someone", example: "\"Voy a\" se me volvió una sola sílaba." },
      { es: "entero", en: "whole, in full", example: "Ya no lo digo entero nunca." },
      { es: "la pronunciación", en: "pronunciation", example: "No era problema de pronunciación." },
    ],
    dialogue: {
      title: "Nada nuevo se aprendió esta semana",
      situation: "Jueves; balance de la penúltima semana del invierno",
      lines: [
        { speaker: "B", es: "Repaso. ¿Cuántas palabras nuevas aprendiste esta semana?", en: "Recap. How many new words did you learn this week?" },
        { speaker: "A", es: "Como cuatro. Almojábana, pan de bono, y un par más de la panadería.", en: "About four. Almojábana, pan de bono, and a couple more from the bakery." },
        { speaker: "B", es: "Cuatro. ¿Y suenas distinta o no?", en: "Four. And do you sound different or not?" },
        { speaker: "A", es: "Muy distinta. Y esa es la parte rara: no aprendí casi nada.", en: "Very different. And that's the strange part: I barely learned anything." },
        { speaker: "B", es: "Aprendiste una sola cosa: a decir menos sílabas de las que trae la palabra.", en: "You learned one thing: to say fewer syllables than the word comes with." },
        { speaker: "A", es: "Voy a se me volvió una sola sílaba. Y ya no lo digo entero nunca.", en: "\"Voy a\" turned into one syllable for me. And I never say it in full anymore." },
        { speaker: "B", es: "Ni deberías. Fíjate lo importante: no era problema de pronunciación.", en: "Nor should you. Notice the important thing: it wasn't a pronunciation problem." },
        { speaker: "A", es: "Está bien: era problema de ritmo, y el ritmo se copia. Nadie me lo había dicho así.", en: "That's it: it was a rhythm problem, and rhythm gets copied. Nobody had put it to me that way." },
        { speaker: "B", es: "Bueno. Falta una semana. ¿Sabes qué toca?", en: "Right. One week left. Do you know what's next?" },
      ],
    },
  },
];
