import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 2 — "Las muletillas de Camila" (days 190–196).
 * Camila hands over her own fillers; Marlana starts catching herself using
 * them at school. Day 195 is the listener-signals beat (ajá · claro · ya ·
 * exacto), folded in from CURRICULUM's old week 2.5.
 */
export const invWeek2ReadingDays: ReadingDay[] = [
  {
    day: 190,
    themeEs: "Las muletillas de Camila",
    storyTitle: "Las muletillas de Camila",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "fíjate que", en: "get this, you know", example: "Fíjate que nunca me habían enseñado esto." },
      { es: "el relleno", en: "filler", example: "No es relleno vacío, es tiempo." },
      { es: "apuntar", en: "to jot down, to write down", example: "Apunté las cinco en el celular." },
      { es: "servir para", en: "to be good for", example: "Estas palabras sirven para no parar." },
      { es: "la costumbre", en: "the habit", example: "No es una regla, es una costumbre." },
    ],
    dialogue: {
      title: "Las mías son más largas",
      situation: "Segundo jueves de la temporada, con el cuaderno abierto",
      lines: [
        { speaker: "B", es: "Te prometí las mías. Anota: fíjate que, la verdad es que, digo, ¿me entiendes?, total que.", en: "I promised you mine. Write these down: fíjate que, la verdad es que, digo, ¿me entiendes?, total que." },
        { speaker: "A", es: "Son más largas que las de la semana pasada.", en: "They're longer than last week's." },
        { speaker: "B", es: "Exacto. Por eso son mejores. Te dan tres segundos, no uno.", en: "Exactly. That's why they're better. They give you three seconds, not one." },
        { speaker: "A", es: "La verdad es que tu muletilla favorita me sirve más que la mía.", en: "Honestly, your favorite filler is more useful to me than mine." },
        { speaker: "B", es: "¿Ya la usaste? Acabas de usarla.", en: "Did you already use it? You just used it." },
        { speaker: "A", es: "Fíjate que yo también estudié sola muchos años y nadie me enseñó esto.", en: "Get this — I studied alone for years too and nobody taught me this." },
        { speaker: "B", es: "Porque no está en los libros. Está en los cafés.", en: "Because it's not in books. It's in cafés." },
        { speaker: "A", es: "Digo, no es una regla, es una costumbre. ¿Me entiendes? Es como respirar antes de hablar.", en: "I mean, it's not a rule, it's a habit. You know what I mean? It's like breathing before you speak." },
        { speaker: "B", es: "Total, que ya tienes diez. Cinco para pensar y cinco para pensar más despacio.", en: "So in the end, you've got ten now. Five to think with and five to think more slowly with." },
      ],
    },
  },
  {
    day: 191,
    themeEs: "La mejor hora de la semana",
    storyTitle: "Las muletillas de Camila",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "fingir", en: "to pretend", example: "Aquí no tengo que fingir nada." },
      { es: "agotada", en: "exhausted", example: "Llegué agotada y ya me siento distinta." },
      { es: "hacer falta", en: "to be needed, to be missing", example: "Me hacía falta esto." },
      { es: "volverse", en: "to turn into, to become", example: "El jueves se volvió mi día favorito." },
      { es: "agradecer", en: "to be grateful, to thank", example: "Te agradezco más de lo que parece." },
    ],
    dialogue: {
      title: "Aquí no soy la maestra",
      situation: "Camila pregunta por qué Marlana nunca falta",
      lines: [
        { speaker: "B", es: "Llevas seis semanas sin faltar un jueves. ¿Tan bien te cae el café?", en: "Six weeks and you haven't missed a Thursday. Do you like the coffee that much?" },
        { speaker: "A", es: "La verdad es que esta hora es la mejor de mi semana.", en: "Honestly, this hour is the best one of my week." },
        { speaker: "B", es: "¿En serio? Cuéntame por qué.", en: "Really? Tell me why." },
        { speaker: "A", es: "Fíjate que en el colegio nadie me pregunta cómo voy. Yo soy la que pregunta.", en: "You know, at school nobody asks me how I'm doing. I'm the one who asks." },
        { speaker: "B", es: "Ya. Claro.", en: "Right. Of course." },
        { speaker: "A", es: "Digo, no es solo el español, es hablar con alguien. ¿Me entiendes? Con mis estudiantes soy la fuerte.", en: "I mean, it's not just the Spanish, it's talking to someone. You know what I mean? With my students I'm the strong one." },
        { speaker: "B", es: "Y aquí puedes ser la que no sabe. Eso descansa.", en: "And here you get to be the one who doesn't know. That's restful." },
        { speaker: "A", es: "Total, que el jueves se volvió mi día favorito. La verdad es que me da miedo dejar de venir.", en: "So in the end, Thursday turned into my favorite day. Honestly, I'm afraid of stopping." },
        { speaker: "B", es: "Entonces no dejes de venir. Yo tampoco pienso faltar.", en: "Then don't stop. I don't plan on missing it either." },
      ],
    },
  },
  {
    day: 192,
    themeEs: "Enfermera, no enfermero",
    storyTitle: "Las muletillas de Camila",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el género", en: "grammatical gender", example: "El género me traiciona cada vez." },
      { es: "traicionar", en: "to betray", example: "En español el género me traiciona." },
      { es: "corregirse", en: "to correct oneself", example: "Me corrijo sin cortar la frase." },
      { es: "al revés", en: "in reverse, the other way round", example: "Mis estudiantes hacen lo mismo al revés." },
      { es: "quise decir", en: "I meant", example: "Digo, quise decir el turno de noche." },
    ],
    dialogue: {
      title: "Un digo y sigues",
      situation: "Marlana habla del trabajo de Camila y se equivoca",
      lines: [
        { speaker: "A", es: "Entonces tú eres enfermero en el hospital y trabajas de noche…", en: "So you're a nurse — masculine — at the hospital and you work nights…" },
        { speaker: "A", es: "Digo, enfermera, no enfermero. Sigo: y trabajas el turno de noche.", en: "I mean — nurse, feminine, not masculine. Continuing: and you work the night shift." },
        { speaker: "B", es: "¿Viste lo que hiciste? No paraste. Un \"digo\" y seguiste.", en: "Did you see what you did? You didn't stop. One \"digo\" and you kept going." },
        { speaker: "A", es: "Fíjate que en inglés no tengo que pensar en el género. Ahí no existe.", en: "You know, in English I don't have to think about gender. It doesn't exist there." },
        { speaker: "B", es: "Ajá. Y por eso se te va.", en: "Mm-hm. And that's why it slips." },
        { speaker: "A", es: "La verdad es que lo pienso después de decirlo. Siempre un segundo tarde.", en: "Honestly, I think about it after I've said it. Always one second late." },
        { speaker: "B", es: "Ese segundo tarde está bien. Corriges y ya. Nadie se ofende.", en: "That one second late is fine. You correct it and that's it. Nobody's offended." },
        { speaker: "A", es: "¿Me entiendes? Lo corrijo para no repetirlo, no para quedar bien.", en: "You know what I mean? I fix it so I don't repeat it, not to look good." },
        { speaker: "B", es: "Total, que ya no vuelves al principio de la frase. Eso es enorme.", en: "So in the end, you don't go back to the start of the sentence anymore. That's huge." },
      ],
    },
  },
  {
    day: 193,
    themeEs: "El salón vacío",
    storyTitle: "Las muletillas de Camila",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "avisar", en: "to give warning, to let know", example: "Cambiaron el horario sin avisarnos." },
      { es: "enterarse", en: "to find out", example: "La directora se enteró por mí." },
      { es: "quejarse", en: "to complain", example: "No me quejé, lo reporté." },
      { es: "resolverse", en: "to get sorted out", example: "Se resolvió, pero mal." },
      { es: "el aviso", en: "the heads-up, the notice", example: "Un aviso a tiempo lo resolvía todo." },
    ],
    dialogue: {
      title: "Nadie avisó",
      situation: "Marlana cuenta el lío del lunes en el colegio",
      lines: [
        { speaker: "A", es: "Fíjate que cambiaron el horario sin avisarnos. Mis estudiantes llegaron a un salón vacío.", en: "Get this — they changed the schedule without telling us. My students arrived to an empty classroom." },
        { speaker: "B", es: "¿Y tú dónde estabas?", en: "And where were you?" },
        { speaker: "A", es: "En el salón de siempre, esperando. Digo, no fue el horario, fue el salón. Nos movieron.", en: "In the usual room, waiting. I mean, it wasn't the schedule, it was the room. They moved us." },
        { speaker: "B", es: "Ah, ya te entiendo. Y nadie mandó un correo.", en: "Ah, now I get you. And nobody sent an email." },
        { speaker: "A", es: "La verdad es que nadie me dijo nada hasta el lunes. ¿Me entiendes? El problema no era el cambio.", en: "Honestly, nobody told me anything until Monday. You know what I mean? The problem wasn't the change." },
        { speaker: "B", es: "Claro. Era que nadie avisó.", en: "Of course. It was that nobody gave any warning." },
        { speaker: "A", es: "Exacto. Digo, no me quejé, lo reporté. Hay una diferencia.", en: "Exactly. I mean, I didn't complain, I reported it. There's a difference." },
        { speaker: "B", es: "Hay una diferencia grande. En el hospital es igual: avisar o no avisar.", en: "There's a big difference. At the hospital it's the same: warn people or don't." },
        { speaker: "A", es: "Total, que dimos la clase en la biblioteca y ahora reviso el horario cada mañana.", en: "So in the end, we taught the class in the library and now I check the schedule every morning." },
      ],
    },
  },
  {
    day: 194,
    themeEs: "Dos horas para nada",
    storyTitle: "Las muletillas de Camila",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el presupuesto", en: "the budget", example: "Empezaron hablando del presupuesto." },
      { es: "distraerse", en: "to get distracted, to drift off", example: "Me distraí a los veinte minutos." },
      { es: "para ser exacta", en: "to be exact", example: "Dos horas y media, para ser exacta." },
      { es: "aprovechar", en: "to make the most of", example: "Aproveché para pensar en español." },
      { es: "para nada", en: "for nothing at all", example: "La reunión duró dos horas para nada." },
    ],
    dialogue: {
      title: "Podría haber sido un correo",
      situation: "Marlana llega tarde al café y explica por qué",
      lines: [
        { speaker: "A", es: "Perdona el retraso. Fíjate que la reunión duró dos horas para nada.", en: "Sorry I'm late. Get this — the meeting lasted two hours for nothing." },
        { speaker: "B", es: "¿Dos horas? ¿De qué hablaron tanto?", en: "Two hours? What did you talk about for so long?" },
        { speaker: "A", es: "Empezaron con el presupuesto. Digo, no era el presupuesto, era el calendario.", en: "They started with the budget. I mean, it wasn't the budget, it was the calendar." },
        { speaker: "B", es: "Ajá.", en: "Mm-hm." },
        { speaker: "A", es: "La verdad es que me distraí a los veinte minutos. Aproveché para pensar en español.", en: "Honestly, I drifted off after twenty minutes. I took advantage of it to think in Spanish." },
        { speaker: "B", es: "¡Eso sí me gusta! Dos horas de práctica gratis.", en: "Now that I like! Two hours of free practice." },
        { speaker: "A", es: "¿Me entiendes? Nadie quería hablar primero. Todos esperaban a la directora.", en: "You know what I mean? Nobody wanted to speak first. Everyone was waiting for the principal." },
        { speaker: "B", es: "Ya, ya. Eso pasa en todos los trabajos del mundo.", en: "Right, right. That happens in every job in the world." },
        { speaker: "A", es: "Total, que salí de ahí con más preguntas que al entrar. Y vamos a repetirla el jueves.", en: "So in the end, I left with more questions than I went in with. And we're doing it again on Thursday." },
      ],
    },
  },
  {
    day: 195,
    themeEs: "Escuchar en voz alta",
    storyTitle: "Las muletillas de Camila",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "los ruiditos", en: "the little noises (listener sounds)", example: "En inglés hago ruiditos todo el tiempo." },
      { es: "acompañar", en: "to keep company, to stay with someone", example: "Aprendí a hablar antes que a acompañar." },
      { es: "atenta", en: "attentive, paying attention", example: "Estaba muy atenta, aunque no lo dije." },
      { es: "a tiempo", en: "on time, at the right moment", example: "Un \"ajá\" a tiempo cambia todo." },
      { es: "más seguido", en: "more often", example: "Voy a decir \"claro\" más seguido." },
    ],
    dialogue: {
      title: "Ajá, claro, ya, exacto",
      situation: "Camila habla diez minutos seguidos y Marlana no dice nada",
      lines: [
        { speaker: "B", es: "…y por eso cambié de hospital. Marlana, ¿estás ahí?", en: "…and that's why I changed hospitals. Marlana, are you there?" },
        { speaker: "A", es: "Sí, sí, aquí estoy. Digo, sí te seguía, solo estaba en silencio.", en: "Yes, yes, I'm here. I mean, I was following you, I was just quiet." },
        { speaker: "B", es: "Es que en español el que escucha también habla. Un poquito. Ajá, claro, ya, exacto.", en: "The thing is, in Spanish the listener talks too. A little bit. Ajá, claro, ya, exacto." },
        { speaker: "A", es: "Fíjate que yo callada parezco aburrida y no lo estoy. La verdad es que estaba muy atenta.", en: "You know, when I'm quiet I look bored and I'm not. Honestly, I was paying close attention." },
        { speaker: "B", es: "Te creo. Pero yo no puedo verlo. Yo solo oigo el silencio.", en: "I believe you. But I can't see it. All I hear is the silence." },
        { speaker: "A", es: "¿Me entiendes? Escuchar callada no es escuchar mal. Pero tú no puedes saberlo.", en: "You know what I mean? Listening quietly isn't listening badly. But you can't know that." },
        { speaker: "B", es: "Exacto. Entonces házmelo saber. Prueba: yo hablo y tú metes un \"ya\".", en: "Exactly. So let me know. Try it: I'll talk and you drop in a \"ya\"." },
        { speaker: "A", es: "Ya. Claro. Ajá. Se siente raro decirlo a propósito.", en: "Ya. Claro. Ajá. It feels strange saying it on purpose." },
        { speaker: "B", es: "Dos semanas y ya no. Total, que ahora tienes muletillas para hablar y para escuchar.", en: "Two weeks and it won't. So in the end, now you've got fillers for talking and for listening." },
      ],
    },
  },
  {
    day: 196,
    themeEs: "Repaso: Muletillas II",
    isRecap: true,
    vocab: [
      { es: "la muletilla", en: "the filler word", example: "Ya llevo diez muletillas." },
      { es: "salir solas", en: "to come out by themselves", example: "Ya no las cuento, me salen solas." },
      { es: "la soltura", en: "ease, fluency of movement", example: "No es fluidez todavía, es soltura." },
      { es: "conversar", en: "to converse, to chat", example: "Sueno como alguien que conversa." },
      { es: "tocar", en: "to be someone's turn", example: "La próxima toca el teléfono." },
    ],
    dialogue: {
      title: "Diez herramientas",
      situation: "Repaso de la semana, contando lo que ya sale solo",
      lines: [
        { speaker: "B", es: "Bueno, repaso. ¿Cuántas muletillas llevas ya?", en: "Okay, recap. How many fillers are you up to now?" },
        { speaker: "A", es: "Fíjate que ya no las cuento, me salen solas. Pero son diez.", en: "Get this — I don't count them anymore, they just come out. But it's ten." },
        { speaker: "B", es: "Diez. ¿Y cuál te gusta más?", en: "Ten. And which do you like best?" },
        { speaker: "A", es: "La verdad es que \"total, que\" es mi favorita. Me deja terminar cualquier historia.", en: "Honestly, \"total, que\" is my favorite. It lets me end any story." },
        { speaker: "B", es: "Ya. Es la que más se oye en la calle, también.", en: "Right. It's also the one you hear most on the street." },
        { speaker: "A", es: "Digo, no diez palabras, diez herramientas. ¿Me entiendes? Ya no busco la palabra perfecta.", en: "I mean, not ten words, ten tools. You know what I mean? I'm not hunting for the perfect word anymore." },
        { speaker: "B", es: "Exacto. Y esta semana aprendiste algo más: a hacer ruido cuando yo hablo.", en: "Exactly. And this week you learned something else: to make noise while I talk." },
        { speaker: "A", es: "La verdad es que sueno como alguien que conversa, no que traduce.", en: "Honestly, I sound like someone having a conversation, not translating one." },
        { speaker: "B", es: "Total, que la próxima toca el teléfono. Y ahí no hay cara, solo voz. Prepárate.", en: "So in the end, next up is the phone. And there's no face there, only voice. Get ready." },
      ],
    },
  },
];
