import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 4 — "Un audio de dos minutos" (days 204–210).
 * Camila's shifts get worse, so the exchange becomes voice notes — and Marlana
 * finds that talking alone into a phone is easier than conversing. Introduces
 * Rocío, a Guatemalan colleague who's been two doors down for eight years.
 */
export const invWeek4ReadingDays: ReadingDay[] = [
  {
    day: 204,
    themeEs: "El primer audio",
    storyTitle: "Un audio de dos minutos",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el audio", en: "the voice note", example: "Te mando un audio porque es más rápido." },
      { es: "grabar", en: "to record", example: "Apreté grabar y me quedé muda." },
      { es: "borrar", en: "to delete", example: "Lo borré cuatro veces antes de mandarlo." },
      { es: "quedarse muda", en: "to go mute", example: "Empecé a grabar y me quedé muda." },
      { es: "rapidito", en: "real quick", example: "Te cuento rapidito qué pasó." },
    ],
    dialogue: {
      title: "Apreté grabar y me quedé muda",
      situation: "Camila propone cambiar las llamadas por audios",
      lines: [
        { speaker: "B", es: "Marlana, esta semana no puedo ni contestar el teléfono. ¿Y si nos mandamos audios?", en: "Marlana, this week I can't even answer the phone. What if we send each other voice notes?" },
        { speaker: "A", es: "¿Audios? O sea, ¿yo hablando sola al celular?", en: "Voice notes? I mean, me talking alone into my phone?" },
        { speaker: "B", es: "Exacto. Y es más fácil, ya verás. Nadie te interrumpe, nadie te apura.", en: "Exactly. And it's easier, you'll see. Nobody interrupts you, nobody rushes you." },
        { speaker: "A", es: "Bueno, lo intento hoy mismo.", en: "Okay, I'll try it today." },
        { speaker: "B", es: "Perfecto. Un audio, treinta segundos, lo que sea. Y no lo borres.", en: "Perfect. One voice note, thirty seconds, whatever. And don't delete it." },
        { speaker: "A", es: "Te cuento rapidito: apreté grabar y me quedé muda. Dos frases y ya no supe seguir.", en: "Quick rundown: I hit record and went mute. Two sentences and I didn't know how to go on." },
        { speaker: "B", es: "Ajá, y lo borraste.", en: "Mm-hm, and you deleted it." },
        { speaker: "A", es: "Era para decirte que lo borré cuatro veces. La cuarta versión quedó igual que la primera.", en: "I was just going to say that I deleted it four times. The fourth version came out the same as the first." },
        { speaker: "B", es: "Entonces el problema no es el español. Es el botón de borrar. Mañana lo mandas sin escucharlo.", en: "So the problem isn't the Spanish. It's the delete button. Tomorrow you send it without listening to it." },
      ],
    },
  },
  {
    day: 205,
    themeEs: "Sin borrar",
    storyTitle: "Un audio de dos minutos",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la toma", en: "the take", example: "Prefiero la primera toma, con errores y todo." },
      { es: "mandar igual", en: "to send anyway", example: "Tiene errores y lo mandé igual." },
      { es: "frenar", en: "to hold back, to brake", example: "Borrar me estaba frenando." },
      { es: "al fondo", en: "in the background", example: "Se oye un perro ladrando al fondo." },
      { es: "editarse", en: "to edit oneself", example: "Hoy decidí no editarme." },
    ],
    dialogue: {
      title: "La primera toma",
      situation: "Marlana manda el audio sin volver a grabarlo",
      lines: [
        { speaker: "A", es: "Te mando un audio porque esta vez no lo borré. Hoy decidí no editarme.", en: "I'm sending you a voice note because this time I didn't delete it. Today I decided not to edit myself." },
        { speaker: "A", es: "Era para decirte que este tiene errores y lo mandé igual. Me trabé dos veces y seguí.", en: "I was just going to say that this one has mistakes and I sent it anyway. I got stuck twice and kept going." },
        { speaker: "A", es: "Te cuento rapidito: se oye un perro ladrando al fondo y me equivoqué en el género otra vez.", en: "Quick rundown: there's a dog barking in the background and I got the gender wrong again." },
        { speaker: "B", es: "Lo escuché tres veces. ¿Sabes qué? Es el mejor audio que me has mandado.", en: "I listened to it three times. You know what? It's the best voice note you've sent me." },
        { speaker: "A", es: "¿El que tiene errores y un perro?", en: "The one with mistakes and a dog?" },
        { speaker: "B", es: "Ese. Porque suena a una persona hablando, no a alguien leyendo.", en: "That one. Because it sounds like a person talking, not someone reading." },
        { speaker: "A", es: "Era para decirte que borrar me estaba frenando. Grabar cinco veces no me hacía mejor.", en: "I was just going to say that deleting was slowing me down. Recording five times wasn't making me better." },
        { speaker: "B", es: "Nunca. Te hacía más lenta y más miedosa. Cualquier cosa, me escribes, pero no borres.", en: "Never. It made you slower and more afraid. Anything at all, message me, but don't delete." },
      ],
    },
  },
  {
    day: 206,
    themeEs: "Dos minutos seguidos",
    storyTitle: "Un audio de dos minutos",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "seguidos", en: "in a row, straight", example: "Hoy me salieron dos minutos seguidos." },
      { es: "irse por las ramas", en: "to go off on tangents", example: "Me escribes si me fui por las ramas." },
      { es: "sobrar", en: "to be left over, to be more than enough", example: "Al final me sobraba qué decir." },
      { es: "no caber", en: "not to fit", example: "En texto no cabía la historia." },
      { es: "a mitad de", en: "halfway through", example: "Se me fue el miedo a mitad del audio." },
    ],
    dialogue: {
      title: "No paré ni una vez",
      situation: "El audio más largo hasta ahora, y la respuesta de Camila",
      lines: [
        { speaker: "A", es: "Te mando un audio porque hoy me salieron dos minutos seguidos. En texto no cabía.", en: "I'm sending you a voice note because today two straight minutes came out. It wouldn't fit in text." },
        { speaker: "A", es: "Era para decirte que no paré ni una vez. Se me fue el miedo a mitad del audio.", en: "I was just going to say that I didn't stop once. The fear left me halfway through." },
        { speaker: "A", es: "Te cuento rapidito: usé las diez muletillas en dos minutos. Al final me sobraba qué decir.", en: "Quick rundown: I used all ten fillers in two minutes. By the end I had more to say, not less." },
        { speaker: "B", es: "Marlana. ¿Te acuerdas de la meta del otoño?", en: "Marlana. Do you remember the fall's goal?" },
        { speaker: "A", es: "Hablar un minuto sin parar. ¿Por qué?", en: "To speak for a minute without stopping. Why?" },
        { speaker: "B", es: "Acabas de hablar dos. Sola, sin nadie ayudándote, y sin darte cuenta.", en: "You just spoke for two. Alone, with nobody helping you, and without noticing." },
        { speaker: "A", es: "No lo había pensado así.", en: "I hadn't thought of it that way." },
        { speaker: "B", es: "Piénsalo. Y avísame cuando puedas: ¿subimos a tres la semana que viene?", en: "Think about it. And let me know when you can: shall we go up to three next week?" },
        { speaker: "A", es: "Cualquier cosa, me escribes si me fui por las ramas. Pero sí, subimos a tres.", en: "Anything at all, message me if I went off on tangents. But yes, let's go up to three." },
      ],
    },
  },
  {
    day: 207,
    themeEs: "Escucharme a mí misma",
    storyTitle: "Un audio de dos minutos",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "escucharse", en: "to listen to oneself", example: "Me escuché por primera vez en español." },
      { es: "el acento", en: "the accent", example: "Mi acento no es tan malo como pensaba." },
      { es: "la pausa", en: "the pause", example: "Las pausas casi no se notan." },
      { es: "notarse", en: "to be noticeable", example: "El pánico no se nota en la grabación." },
      { es: "sincera", en: "honest, sincere", example: "Me escribes tu opinión sincera." },
    ],
    dialogue: {
      title: "¿Esa voz es mía?",
      situation: "Marlana se escucha por primera vez y le cuenta a Camila",
      lines: [
        { speaker: "A", es: "Te mando un audio porque acabo de escucharme y quiero contarte. No sé si esa voz es mía.", en: "I'm sending you a voice note because I just listened to myself and I want to tell you. I don't know if that voice is mine." },
        { speaker: "B", es: "Ay, la primera vez es rarísimo. ¿Y qué te pareció?", en: "Oh, the first time is so strange. And what did you think?" },
        { speaker: "A", es: "Era para decirte que sueno más lenta de lo que creía. Pero también sueno más tranquila.", en: "I was just going to say that I sound slower than I thought. But I also sound calmer." },
        { speaker: "B", es: "Exacto. Por dentro sentías pánico, ¿verdad? Y en la grabación no se oye nada de eso.", en: "Exactly. Inside you felt panic, right? And in the recording you can't hear any of that." },
        { speaker: "A", es: "Nada. Te cuento rapidito: mi acento no es tan malo como pensaba. Las pausas casi no se notan.", en: "None. Quick rundown: my accent isn't as bad as I thought. The pauses are barely noticeable." },
        { speaker: "B", es: "Ya. El pánico es privado. Nadie lo escucha menos tú.", en: "Right. The panic is private. Nobody hears it except you." },
        { speaker: "A", es: "Y dije \"o sea\" nueve veces. Las conté.", en: "And I said \"o sea\" nine times. I counted them." },
        { speaker: "B", es: "Nueve está perfecto. Yo digo más. Avísame cuando puedas qué te suena raro a ti.", en: "Nine is perfect. I say more. Let me know when you can what sounds odd to you." },
        { speaker: "A", es: "Cualquier cosa, me escribes tu opinión sincera. Guardo el audio para comparar en marzo.", en: "Anything at all, message me your honest opinion. I'm keeping the recording to compare in March." },
      ],
    },
  },
  {
    day: 208,
    themeEs: "Audios del colegio",
    storyTitle: "Un audio de dos minutos",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "la compañera", en: "the coworker, the colleague", example: "Le mandé un audio a una compañera del colegio." },
      { es: "llevar años", en: "to have spent years", example: "Rocío lleva ocho años aquí." },
      { es: "entre clases", en: "between classes", example: "Nos mandamos audios entre clases." },
      { es: "estar de turno", en: "to be on shift", example: "Avísame cuando puedas, sé que estás de turno." },
      { es: "agradecer", en: "to thank, to be grateful for", example: "Me corrigió y se lo agradecí." },
    ],
    dialogue: {
      title: "Rocío, dos puertas más allá",
      situation: "Marlana descubre que había una hispanohablante en su propio pasillo",
      lines: [
        { speaker: "A", es: "Te mando un audio porque hoy le mandé uno a una compañera del colegio.", en: "I'm sending you a voice note because today I sent one to a colleague at school." },
        { speaker: "B", es: "¿A quién? Cuéntame.", en: "To whom? Tell me." },
        { speaker: "A", es: "Te cuento rapidito: Rocío es de Guatemala y lleva ocho años aquí. Su salón está a dos puertas del mío.", en: "Quick rundown: Rocío is from Guatemala and has been here eight years. Her classroom is two doors from mine." },
        { speaker: "B", es: "¡Ocho años! ¿Y nunca habían hablado en español?", en: "Eight years! And you'd never spoken Spanish?" },
        { speaker: "A", es: "Nunca. Era para decirte eso justamente: nunca habíamos hablado en español en el colegio.", en: "Never. That's exactly what I was going to tell you: we'd never spoken Spanish at school." },
        { speaker: "B", es: "Y ahora, ¿qué cambió?", en: "And now, what changed?" },
        { speaker: "A", es: "Yo. Le mandé un audio y me contestó con otro. Ahora nos mandamos audios entre clases.", en: "Me. I sent her a voice note and she answered with another. Now we send each other voice notes between classes." },
        { speaker: "B", es: "Ay, Marlana. Eso vale más que el café de los jueves.", en: "Oh, Marlana. That's worth more than the Thursday coffee." },
        { speaker: "A", es: "No digas eso. Avísame cuando puedas, sé que estás de turno. Cualquier cosa, me escribes cuando salgas del hospital.", en: "Don't say that. Let me know when you can, I know you're on shift. Anything at all, message me when you get out of the hospital." },
      ],
    },
  },
  {
    day: 209,
    themeEs: "Ya no escribo, mando audio",
    storyTitle: "Un audio de dos minutos",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "el hábito", en: "the habit", example: "Cambié el hábito sin darme cuenta." },
      { es: "sin darse cuenta", en: "without realizing", example: "Lo cambié sin darme cuenta." },
      { es: "llevar seis días", en: "to have been six days", example: "Llevo seis días mandando audios." },
      { es: "repetir", en: "to redo, to do again", example: "Mandé cuatro y ninguno lo repetí." },
      { es: "como quieras", en: "however you like", example: "Me escribes o me mandas audio, como quieras." },
    ],
    dialogue: {
      title: "El botón dejó de asustarme",
      situation: "Sexto día seguido de audios, y Camila nota el cambio",
      lines: [
        { speaker: "A", es: "Te mando un audio porque ya me sale más rápido que escribir. El texto me hacía pensar demasiado.", en: "I'm sending you a voice note because it comes out faster than typing now. Text made me overthink." },
        { speaker: "B", es: "Espera, ¿escuchaste lo que dijiste? Que hablar es más fácil que escribir.", en: "Wait, did you hear what you said? That speaking is easier than writing." },
        { speaker: "A", es: "Era para decirte que cambié el hábito sin darme cuenta. Llevo seis días mandando audios.", en: "I was just going to say that I changed the habit without realizing. I've been sending voice notes for six days." },
        { speaker: "B", es: "Seis días. Y hace un mes no querías ni contestar el teléfono.", en: "Six days. And a month ago you didn't even want to answer the phone." },
        { speaker: "A", es: "Te cuento rapidito: hoy grabé mientras cocinaba. Mandé cuatro audios y ninguno lo repetí.", en: "Quick rundown: today I recorded while cooking. I sent four voice notes and didn't redo one." },
        { speaker: "B", es: "Ninguno. Ese es el dato importante, no cuántos mandaste.", en: "Not one. That's the important number, not how many you sent." },
        { speaker: "A", es: "Y ya no preparo lo que voy a decir. El botón de grabar dejó de asustarme.", en: "And I don't prepare what I'm going to say anymore. The record button stopped scaring me." },
        { speaker: "B", es: "Avísame cuando puedas si notas la diferencia tú misma, no solo yo.", en: "Let me know when you can if you notice the difference yourself, not just me." },
        { speaker: "A", es: "La noto. Cualquier cosa, me escribes o me mandas audio, como quieras.", en: "I notice it. Anything at all, message me or send audio, however you like." },
      ],
    },
  },
  {
    day: 210,
    themeEs: "Repaso: Notas de voz",
    isRecap: true,
    vocab: [
      { es: "el resumen", en: "the recap", example: "Te mando un audio porque es el resumen de la semana." },
      { es: "durar", en: "to last", example: "El primero duró once segundos." },
      { es: "juzgar", en: "to judge", example: "El micrófono no juzga a nadie." },
      { es: "la vergüenza", en: "embarrassment, shame", example: "Ya perdí la vergüenza." },
      { es: "resultar", en: "to turn out", example: "Hablar sola resultó más fácil que conversar." },
    ],
    dialogue: {
      title: "Dieciocho audios",
      situation: "Cierre de la cuarta semana, y el primer mes completo",
      lines: [
        { speaker: "B", es: "Bueno, repaso. Es el cierre de la cuarta semana. ¿Cuántos audios en total?", en: "Okay, recap. It's the end of the fourth week. How many voice notes in total?" },
        { speaker: "A", es: "Era para decirte que grabé dieciocho audios en siete días.", en: "I was just going to say that I recorded eighteen voice notes in seven days." },
        { speaker: "B", es: "Dieciocho. ¿Y el primero?", en: "Eighteen. And the first one?" },
        { speaker: "A", es: "El primero duró once segundos. El último duró tres minutos.", en: "The first lasted eleven seconds. The last lasted three minutes." },
        { speaker: "B", es: "Once segundos a tres minutos en una semana. ¿Y qué cambió, según tú?", en: "Eleven seconds to three minutes in a week. And what changed, in your view?" },
        { speaker: "A", es: "Te cuento rapidito: lo que cambió fue no borrar. Nada más.", en: "Quick rundown: what changed was not deleting. Nothing else." },
        { speaker: "B", es: "Exacto. Y algo más que dijiste el martes y me quedó grabado.", en: "Exactly. And something else you said on Tuesday that stuck with me." },
        { speaker: "A", es: "Que hablar sola resultó más fácil que conversar. Y que el micrófono no juzga a nadie.", en: "That talking alone turned out easier than conversing. And that the microphone doesn't judge anybody." },
        { speaker: "B", es: "Guárdate esa frase. En fin, ya llevas un mes de invierno. Ahora empieza lo bueno: el subjuntivo.", en: "Keep that sentence. So in the end, that's a full month of winter. Now the good part starts: the subjunctive." },
      ],
    },
  },
];
