import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 12 — "A velocidad real" (days 260–266).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week12-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek12SpeakDays: SpeakDay[] = [
  {
    day: 260,
    themeEs: "En la panadería",
    themeEn: "At the bakery",
    missionEs: "Pide algo sin que nadie te hable más despacio.",
    missionEn: "Order something without anyone slowing down for you.",
    line: "Aquí nadie baja el ritmo por ti. Esa es la buena noticia.",
    lineEn: "Nobody here slows down for you. That's the good news.",
    prompts: [
      {
        id: "d260-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "Hey — is there still any pan de bono?",
        spanish: "¿Qué hubo? ¿Todavía queda pan de bono?",
        situationLabel: "Entrando a la panadería",
        why: "Said fast this is one word: **quiubo**. Two on paper, two syllables in the mouth — and in Colombia you'll hear it more than *hola*.",
        wordHints: [
          { en: "hey, how's it going", es: "qué hubo" },
          { en: "is there still", es: "todavía queda" },
        ],
      },
      {
        id: "d260-voy-a",
        frameStem: "Voy a…",
        english: "I'm going to take two of these and a coffee.",
        spanish: "Voy a llevar dos de estos y un café.",
        situationLabel: "Pidiendo en el mostrador",
        why: "*Voy a* collapses to **voy'a**, and at full speed to something like *vua*. The most common reduction in spoken Spanish.",
        wordHints: [
          { en: "i'm going to take", es: "voy a llevar" },
          { en: "two of these", es: "dos de estos" },
          { en: "a coffee", es: "un café" },
        ],
      },
      {
        id: "d260-para-que",
        frameStem: "Para que…",
        english: "So they can try it at home.",
        spanish: "Para que lo prueben en la casa.",
        situationLabel: "Explicando por qué llevas de más",
        why: "Everyone says **pa' que**. The full *para* survives in writing; in a bakery on a Saturday morning it does not.",
        wordHints: [
          { en: "so that", es: "para que" },
          { en: "they try it", es: "lo prueben" },
          { en: "at home", es: "en la casa" },
        ],
      },
      {
        id: "d260-esta-bien",
        frameStem: "Está bien…",
        english: "That's fine like that, thank you.",
        spanish: "Está bien así, gracias.",
        situationLabel: "Aceptando lo que hay",
        why: "The first syllable disappears: **tá bien**. Same with *estoy* → *toy*. Nobody thinks they're dropping anything.",
        wordHints: [
          { en: "that's fine", es: "está bien" },
          { en: "like that", es: "así" },
        ],
      },
      {
        id: "d260-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? You never come around here.",
        spanish: "¿Y eso? Nunca vienes por aquí.",
        situationLabel: "Lo que le dicen a Camila",
        why: "Two words, one glide: **yeso**. Pure sinalefa — and the most useful two-word question in the language.",
        wordHints: [
          { en: "how come", es: "y eso" },
          { en: "you never come", es: "nunca vienes" },
          { en: "around here", es: "por aquí" },
        ],
      },
    ],
  },
  {
    day: 261,
    themeEs: "Quiubo",
    themeEn: "Quiubo",
    missionEs: "Saluda como saluda la gente, no como el libro.",
    missionEn: "Greet people the way people greet, not the way the book does.",
    line: "Los saludos del libro no son los saludos del salón.",
    lineEn: "The greetings in the textbook are not the greetings in the room.",
    prompts: [
      {
        id: "d261-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "Hey, Doña Marta — how did you wake up?",
        spanish: "¿Qué hubo, doña Marta? ¿Cómo amaneció?",
        situationLabel: "Saludando a la de siempre",
        why: "*¿Cómo amaneció?* — how did you wake up? A morning greeting with no English equivalent, and much warmer than *¿cómo está?*",
        wordHints: [
          { en: "how did you wake up", es: "cómo amaneció" },
        ],
      },
      {
        id: "d261-voy-a",
        frameStem: "Voy a…",
        english: "I'm going to take one of those I don't know.",
        spanish: "Voy a llevarme uno de esos que no conozco.",
        situationLabel: "Probando algo nuevo",
        why: "*Llevarme* with the pronoun attached — I'll take one for myself. The *me* is doing warmth, not grammar.",
        wordHints: [
          { en: "i'm going to take", es: "voy a llevarme" },
          { en: "one of those", es: "uno de esos" },
          { en: "i don't know", es: "no conozco" },
        ],
      },
      {
        id: "d261-para-que",
        frameStem: "Para que…",
        english: "So that next time I come on my own.",
        spanish: "Para que la próxima venga sola.",
        situationLabel: "El plan de verdad",
        why: "Coming back alone is the actual test. Camila brought you once so that you'd never need her to again.",
        wordHints: [
          { en: "next time", es: "la próxima" },
          { en: "i come", es: "venga" },
          { en: "on my own", es: "sola" },
        ],
      },
      {
        id: "d261-esta-bien",
        frameStem: "Está bien…",
        english: "That's fine, then I'll take something else.",
        spanish: "Está bien, entonces me llevo otra cosa.",
        situationLabel: "Cuando ya se acabó",
        why: "The whole exchange when they're out of something, in seven words, with no fuss and no apology.",
        wordHints: [
          { en: "then", es: "entonces" },
          { en: "i'll take", es: "me llevo" },
          { en: "something else", es: "otra cosa" },
        ],
      },
      {
        id: "d261-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? It's packed today.",
        spanish: "¿Y eso? Está lleno hoy.",
        situationLabel: "Un sábado distinto",
        why: "*¿Y eso?* works as a whole question, a whole reaction, and a whole invitation to explain. Three jobs, two words.",
        wordHints: [
          { en: "it's full", es: "está lleno" },
          { en: "today", es: "hoy" },
        ],
      },
    ],
  },
  {
    day: 262,
    themeEs: "Pa' que",
    themeEn: "Pa' que",
    missionEs: "Usa una reducción a propósito y a tiempo.",
    missionEn: "Use a reduction on purpose and on time.",
    line: "Lo oíste tres meses antes de saber qué era.",
    lineEn: "You heard it for three months before you knew what it was.",
    prompts: [
      {
        id: "d262-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "Hey Rocío — I brought you something from the bakery.",
        spanish: "¿Qué hubo? Te traje algo de la panadería.",
        situationLabel: "Llegando al colegio",
        why: "Bringing the register back to school with you. The greeting travels further than the bread does.",
        wordHints: [
          { en: "i brought you", es: "te traje" },
          { en: "something", es: "algo" },
          { en: "from the bakery", es: "de la panadería" },
        ],
      },
      {
        id: "d262-voy-a",
        frameStem: "Voy a…",
        english: "I'm going to copy Camila's rhythm.",
        spanish: "Voy a copiarle el ritmo a Camila.",
        situationLabel: "El plan de la semana",
        why: "Rhythm is copied, not studied. Pick one person who sounds right and imitate the shape of their sentences.",
        wordHints: [
          { en: "i'm going to copy", es: "voy a copiarle" },
          { en: "the rhythm", es: "el ritmo" },
        ],
      },
      {
        id: "d262-para-que",
        frameStem: "Para que…",
        english: "So that it sounds like conversation and not like an exam.",
        spanish: "Para que suene como conversación y no como examen.",
        situationLabel: "Lo que buscas de verdad",
        why: "Notice you now hear **pa' que** as one thing, not as a mistake. Recognizing a reduction is the step before producing one.",
        wordHints: [
          { en: "it sounds", es: "suene" },
          { en: "like conversation", es: "como conversación" },
          { en: "an exam", es: "examen" },
        ],
      },
      {
        id: "d262-esta-bien",
        frameStem: "Está bien…",
        english: "It's fine if I pick up the Colombian accent.",
        spanish: "Está bien que se me pegue el acento colombiano.",
        situationLabel: "Sin pedir permiso",
        why: "*Pegársele a alguien* — for something to rub off on you. Accents are caught, not chosen, and that's fine.",
        wordHints: [
          { en: "that it rubs off on me", es: "que se me pegue" },
          { en: "the accent", es: "el acento" },
        ],
      },
      {
        id: "d262-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? Since when do you talk like that?",
        spanish: "¿Y eso? ¿Desde cuándo hablas así?",
        situationLabel: "Lo que te pregunta Rocío",
        why: "The first time someone asks you this, it means it's working. Enjoy it.",
        wordHints: [
          { en: "since when", es: "desde cuándo" },
          { en: "do you talk", es: "hablas" },
          { en: "like that", es: "así" },
        ],
      },
    ],
  },
  {
    day: 263,
    themeEs: "Tá bien",
    themeEn: "Tá bien",
    missionEs: "Habla una hora comiéndote las sílabas que se comen todos.",
    missionEn: "Talk for an hour swallowing the syllables everyone swallows.",
    line: "Sílabas caídas por todas partes, y nadie cree que se le caiga nada.",
    lineEn: "Dropped syllables everywhere, and nobody thinks they're dropping anything.",
    prompts: [
      {
        id: "d263-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "Hey — I'm sending you a quick voice note.",
        spanish: "¿Qué hubo? Te mando un audio rapidito.",
        situationLabel: "Abriendo un audio",
        why: "Week 4's habit with week 12's greeting. The season keeps folding back into itself.",
        wordHints: [
          { en: "i'm sending you", es: "te mando" },
          { en: "a voice note", es: "un audio" },
          { en: "quick", es: "rapidito" },
        ],
      },
      {
        id: "d263-voy-a",
        frameStem: "Voy a…",
        english: "I'm going to be home around six.",
        spanish: "Voy a estar en la casa como a las seis.",
        situationLabel: "Diciendo dónde vas a estar",
        why: "*Voy a estar* is three reductions in a row: **voy'a'tar**. Say it slowly once, then never again.",
        wordHints: [
          { en: "i'm going to be", es: "voy a estar" },
          { en: "at home", es: "en la casa" },
          { en: "around six", es: "como a las seis" },
        ],
      },
      {
        id: "d263-para-que",
        frameStem: "Para que…",
        english: "So nobody waits up for me.",
        spanish: "Para que no me esperen despiertos.",
        situationLabel: "Avisando en casa",
        why: "*Esperar despiertos* — to wait up. Spanish puts the state on the people, not on the verb.",
        wordHints: [
          { en: "they don't wait for me", es: "no me esperen" },
          { en: "awake", es: "despiertos" },
        ],
      },
      {
        id: "d263-esta-bien",
        frameStem: "Está bien…",
        english: "It's all fine here, don't worry.",
        spanish: "Está bien todo por aquí, no te preocupes.",
        situationLabel: "Tranquilizando a Camila",
        why: "**Tá bien** is what you'll hear. *Estoy* becomes *toy*, *estamos* becomes *tamos*. That first syllable is optional everywhere.",
        wordHints: [
          { en: "everything's fine", es: "está bien todo" },
          { en: "around here", es: "por aquí" },
          { en: "don't worry", es: "no te preocupes" },
        ],
      },
      {
        id: "d263-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? Did they give you the day off?",
        spanish: "¿Y eso? ¿Te dieron el día libre?",
        situationLabel: "Reaccionando a una sorpresa",
        why: "*El día libre* — the day off. And *¿y eso?* doing what it always does: asking for the story without asking for it.",
        wordHints: [
          { en: "did they give you", es: "te dieron" },
          { en: "the day off", es: "el día libre" },
        ],
      },
    ],
  },
  {
    day: 264,
    themeEs: "A uno y medio",
    themeEn: "At one and a half",
    missionEs: "Escucha algo más rápido de lo cómodo.",
    missionEn: "Listen to something faster than is comfortable.",
    line: "Aceleraste el pódcast a propósito. Y funcionó.",
    lineEn: "You sped the podcast up on purpose. And it worked.",
    prompts: [
      {
        id: "d264-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "Hey — I did something odd and I have to tell you.",
        spanish: "¿Qué hubo? Hice algo raro y te tengo que contar.",
        situationLabel: "Empezando el audio",
        why: "The opener you now use by default, with no decision involved. That's what week 12 was for.",
        wordHints: [
          { en: "i did", es: "hice" },
          { en: "something odd", es: "algo raro" },
          { en: "i have to tell you", es: "te tengo que contar" },
        ],
      },
      {
        id: "d264-voy-a",
        frameStem: "Voy a…",
        english: "I'm going to leave it at one and a half all week.",
        spanish: "Voy a dejarlo a uno y medio toda la semana.",
        situationLabel: "El experimento",
        why: "*Uno y medio* is how you say 1.5× speed. Useful and slightly absurd, which is most vocabulary.",
        wordHints: [
          { en: "i'm going to leave it", es: "voy a dejarlo" },
          { en: "at one and a half", es: "a uno y medio" },
          { en: "all week", es: "toda la semana" },
        ],
      },
      {
        id: "d264-para-que",
        frameStem: "Para que…",
        english: "So that normal speed feels slow to me.",
        spanish: "Para que la velocidad normal me parezca lenta.",
        situationLabel: "La lógica del truco",
        why: "The same trick as running in a weighted vest. Normal speed afterward feels like a favor.",
        wordHints: [
          { en: "normal speed", es: "la velocidad normal" },
          { en: "feels to me", es: "me parezca" },
          { en: "slow", es: "lenta" },
        ],
      },
      {
        id: "d264-esta-bien",
        frameStem: "Está bien…",
        english: "It's fine to lose some words if I follow the thread.",
        spanish: "Está bien perder algunas palabras si sigo el hilo.",
        situationLabel: "El trato que aceptas",
        why: "Week 11's whole lesson, now being applied as a deliberate strategy rather than a consolation.",
        wordHints: [
          { en: "to lose", es: "perder" },
          { en: "some words", es: "algunas palabras" },
          { en: "if i follow the thread", es: "si sigo el hilo" },
        ],
      },
      {
        id: "d264-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? Who thinks to speed it up?",
        spanish: "¿Y eso? ¿A quién se le ocurre acelerarlo?",
        situationLabel: "La reacción de Camila",
        why: "*A quién se le ocurre* — who would think of that. Affectionate disbelief, and a very common construction.",
        wordHints: [
          { en: "who thinks of", es: "a quién se le ocurre" },
          { en: "speeding it up", es: "acelerarlo" },
        ],
      },
    ],
  },
  {
    day: 265,
    themeEs: "Ya no me hablan despacio",
    themeEn: "Nobody slows down for me anymore",
    missionEs: "Cuenta algo que te pasó y que todavía no sabes cómo tomarte.",
    missionEn: "Tell something that happened that you're not sure how to take.",
    line: "Dejaron de acomodarse a ti. Tarda un segundo en sonar a cumplido.",
    lineEn: "They stopped accommodating you. It takes a second to sound like a compliment.",
    prompts: [
      {
        id: "d265-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "Hey — today they greeted me first.",
        spanish: "¿Qué hubo? Hoy me saludaron ellos primero.",
        situationLabel: "En la panadería, ya como cliente",
        why: "Being greeted first is the smallest possible sign of belonging somewhere. Worth noticing.",
        wordHints: [
          { en: "they greeted me", es: "me saludaron" },
          { en: "they, first", es: "ellos primero" },
        ],
      },
      {
        id: "d265-voy-a",
        frameStem: "Voy a…",
        english: "I'm going to take it as a compliment.",
        spanish: "Voy a tomármelo como cumplido.",
        situationLabel: "Después de pensarlo",
        why: "*Tomárselo como* — to take it as. The double pronoun is doing nothing except sounding right.",
        wordHints: [
          { en: "i'm going to take it", es: "voy a tomármelo" },
          { en: "as a compliment", es: "como cumplido" },
        ],
      },
      {
        id: "d265-para-que",
        frameStem: "Para que…",
        english: "So they stop adjusting themselves to me.",
        spanish: "Para que dejen de acomodarse a mí.",
        situationLabel: "Lo que querías desde junio",
        why: "The moment people stop accommodating you is the moment you stopped needing it. It arrives without an announcement.",
        wordHints: [
          { en: "they stop", es: "dejen de" },
          { en: "adjusting themselves", es: "acomodarse" },
          { en: "to me", es: "a mí" },
        ],
      },
      {
        id: "d265-esta-bien",
        frameStem: "Está bien…",
        english: "It's fine — I'd rather miss something than be spoken to strangely.",
        spanish: "Está bien, prefiero perderme algo a que me hablen raro.",
        situationLabel: "La elección que haces",
        why: "*Prefiero X a que Y* — the same shape as week 8's advice chunk, arriving now with no effort at all.",
        wordHints: [
          { en: "i'd rather miss", es: "prefiero perderme" },
          { en: "something", es: "algo" },
          { en: "they talk to me strangely", es: "me hablen raro" },
        ],
      },
      {
        id: "d265-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? Tell me the truth, don't humor me.",
        spanish: "¿Y eso? Dime la verdad, no me consientas.",
        situationLabel: "Pidiéndole honestidad a Camila",
        why: "*No me consientas* — don't humor me. The exact request you need from the one person who'd let you off easy.",
        wordHints: [
          { en: "tell me the truth", es: "dime la verdad" },
          { en: "don't humor me", es: "no me consientas" },
        ],
      },
    ],
  },
  {
    day: 266,
    themeEs: "Repaso: A velocidad real",
    themeEn: "Review: At real speed",
    missionEs: "Di lo mismo de siempre en la mitad de las sílabas.",
    missionEn: "Say the same things as always in half the syllables.",
    line: "Las mismas palabras. La mitad de las sílabas.",
    lineEn: "The same words. Half the syllables.",
    prompts: [
      {
        id: "d266-que-hubo",
        frameStem: "¿Qué hubo?…",
        english: "\"Quiubo\" comes out before \"hola\" does now.",
        spanish: "¿Qué hubo? me sale antes que \"hola\".",
        situationLabel: "El saludo que ganó",
        why: "You didn't decide this. It happened somewhere around Tuesday, which is how register actually changes.",
        wordHints: [
          { en: "comes out for me", es: "me sale" },
          { en: "before", es: "antes que" },
        ],
      },
      {
        id: "d266-voy-a",
        frameStem: "Voy a…",
        english: "\"Voy a\" turned into a single syllable for me.",
        spanish: "Voy a se me volvió una sola sílaba.",
        situationLabel: "La medida del cambio",
        why: "*Se me volvió* — it turned into, on me. The change happened to you rather than being performed by you.",
        wordHints: [
          { en: "turned into for me", es: "se me volvió" },
          { en: "a single syllable", es: "una sola sílaba" },
        ],
      },
      {
        id: "d266-para-que",
        frameStem: "Para que…",
        english: "So that it stopped sounding like a book and started sounding like a person.",
        spanish: "Para que dejara de sonar a libro y sonara a persona.",
        situationLabel: "El objetivo de la semana",
        why: "*Sonar a* — to sound like. And two shifted verbs in a row that you built without noticing you built them.",
        wordHints: [
          { en: "it stopped", es: "dejara de" },
          { en: "sounding like a book", es: "sonar a libro" },
          { en: "sounded like a person", es: "sonara a persona" },
        ],
      },
      {
        id: "d266-esta-bien",
        frameStem: "Está bien…",
        english: "It's fine — it was a rhythm problem, and rhythm is copied.",
        spanish: "Está bien: era problema de ritmo, y el ritmo se copia.",
        situationLabel: "El diagnóstico correcto",
        why: "Nothing this week was new vocabulary or grammar. The words were all ones you had; what changed was how many syllables you gave them.",
        wordHints: [
          { en: "it was a problem", es: "era problema" },
          { en: "of rhythm", es: "de ritmo" },
          { en: "rhythm gets copied", es: "el ritmo se copia" },
        ],
      },
      {
        id: "d266-y-eso",
        frameStem: "¿Y eso?…",
        english: "How come? Well — twelve weeks, that's how.",
        spanish: "¿Y eso? Pues doce semanas, eso.",
        situationLabel: "Mirando enero desde aquí",
        why: "The season's first word answering the season's smallest question. One week of winter left.",
        wordHints: [
          { en: "well", es: "pues" },
          { en: "twelve weeks", es: "doce semanas" },
        ],
      },
    ],
  },
];
