import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 11 — "Sin subtítulos" (days 253–259).
 * Marlana turns the subtitles off on a Colombian series and finds that the
 * season's stated goal — "ver algo sin subtítulos" — arrives the moment she
 * decides that missing words is allowed.
 */
export const invWeek11ReadingDays: ReadingDay[] = [
  {
    day: 253,
    themeEs: "Quitar los subtítulos",
    storyTitle: "Sin subtítulos",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "los subtítulos", en: "the subtitles", example: "Quité los subtítulos y aguanté." },
      { es: "el control remoto", en: "the remote", example: "Busqué el control y no lo apreté." },
      { es: "escapársele a alguien", en: "to slip past someone", example: "Se me escapó la parte de la llamada." },
      { es: "el hueco", en: "the gap", example: "Contaba huecos en vez de contar lo que entendía." },
      { es: "captar", en: "to catch, to pick up", example: "No hace falta captarlo todo." },
    ],
    dialogue: {
      title: "Doce minutos",
      situation: "Marlana y Camila ven una serie colombiana por videollamada",
      lines: [
        { speaker: "B", es: "Hoy la vemos sin subtítulos. Te toca.", en: "Today we're watching it without subtitles. Your turn." },
        { speaker: "A", es: "Ay, no. ¿Y si me pierdo?", en: "Oh no. And if I get lost?" },
        { speaker: "B", es: "Te pierdes. Y después me preguntas. Dale.", en: "Then you get lost. And afterward you ask me. Go on." },
        { speaker: "A", es: "…A los doce minutos busqué el control remoto. No lo apreté, pero lo busqué.", en: "…Twelve minutes in I reached for the remote. I didn't press it, but I reached." },
        { speaker: "B", es: "Ese es el momento importante. ¿Y qué pasó después?", en: "That's the important moment. And what happened after?" },
        { speaker: "A", es: "Más o menos entendí que se están peleando por la casa. Y lo que sí entendí fue que ella se va el domingo.", en: "I more or less got that they're fighting over the house. And what I did catch was that she's leaving on Sunday." },
        { speaker: "B", es: "Correcto. ¿Ves? Eso es el capítulo.", en: "Correct. See? That's the episode." },
        { speaker: "A", es: "Se me escapó la parte de la llamada. Y ¿dijiste que son hermanos?", en: "I missed the part about the phone call. And did you say they're siblings?" },
        { speaker: "B", es: "Primos. Pero por el contexto se entiende igual, ¿no?", en: "Cousins. But from the context it reads the same, doesn't it?" },
      ],
    },
  },
  {
    day: 254,
    themeEs: "Más o menos entendí",
    storyTitle: "Sin subtítulos",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la finca", en: "the country property, the farm", example: "¿Qué es una finca?" },
      { es: "el chiste", en: "the joke", example: "Entendí el chiste y me reí a tiempo." },
      { es: "a la vez", en: "at the same time", example: "Hablan los dos a la vez." },
      { es: "el capítulo", en: "the episode", example: "Entendí el capítulo entero." },
      { es: "perdonar", en: "to forgive", example: "Más o menos entendí que lo perdonó." },
    ],
    dialogue: {
      title: "Me reí a tiempo",
      situation: "Segundo capítulo, y algo cambia",
      lines: [
        { speaker: "A", es: "Camila. Pasó algo raro. Me reí antes que tú.", en: "Camila. Something odd happened. I laughed before you did." },
        { speaker: "B", es: "¡Ja! ¿Del chiste de la tía?", en: "Ha! At the aunt's joke?" },
        { speaker: "A", es: "De ese. Lo que sí entendí fue el chiste, y me reí a tiempo. Sin pensarlo.", en: "That one. What I did catch was the joke, and I laughed on time. Without thinking." },
        { speaker: "B", es: "Eso no se puede fingir. Ese es el examen de verdad.", en: "You can't fake that. That's the real test." },
        { speaker: "A", es: "Más o menos entendí el capítulo entero. Más o menos entendí que lo perdonó al final.", en: "I more or less understood the whole episode. I more or less got that she forgave him in the end." },
        { speaker: "B", es: "Todo correcto. ¿Y qué te faltó?", en: "All correct. And what did you miss?" },
        { speaker: "A", es: "Se me escapó la parte de cuando hablan los dos a la vez. Y ¿dijiste \"finca\"? ¿Qué es una finca?", en: "I missed the part where they both talk at once. And did you say \"finca\"? What's a finca?" },
        { speaker: "B", es: "Una casa en el campo, con tierra. Sale en toda la serie.", en: "A house in the country, with land. It's all over the series." },
        { speaker: "A", es: "Ah, entonces por el contexto entiendo que la pelea es por eso. Ya tiene sentido todo.", en: "Ah, so from the context I gather the fight is over that. Now it all makes sense." },
      ],
    },
  },
  {
    day: 255,
    themeEs: "Lo que sí entendí",
    storyTitle: "Sin subtítulos",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el papel", en: "the form, the document", example: "Necesita el papel para el viernes." },
      { es: "mandar de un lado a otro", en: "to send from place to place", example: "La mandaron de una oficina a otra." },
      { es: "urgente", en: "urgent", example: "Por el contexto entiendo que es urgente." },
      { es: "hacer falta", en: "to be needed", example: "El resto no hacía falta." },
      { es: "el pasillo", en: "the hallway", example: "Me habló rapidísimo en el pasillo." },
    ],
    dialogue: {
      title: "Una mamá en el pasillo",
      situation: "Una madre habla muy rápido y Marlana entiende a medias",
      lines: [
        { speaker: "B", es: "Maestra, disculpe, es que me dijeron en la otra oficina que viniera aquí y necesito el papel de mi hija porque el viernes—", en: "Teacher, excuse me, they told me at the other office to come here and I need my daughter's form because on Friday—" },
        { speaker: "A", es: "Más o menos entendí lo que necesitaba. Lo que sí entendí fue que necesita el papel para el viernes.", en: "I more or less got what she needed. What I did catch was that she needs the form by Friday." },
        { speaker: "B", es: "Sí, sí, para el viernes.", en: "Yes, yes, by Friday." },
        { speaker: "A", es: "¿Dijiste que ya vino dos veces?", en: "Did you say you've already come twice?" },
        { speaker: "B", es: "Tres. Nadie me explica nada.", en: "Three. Nobody explains anything to me." },
        { speaker: "A", es: "Se me escapó la parte de por qué lo necesita. ¿Me la repite?", en: "I missed the part about why you need it. Could you repeat that?" },
        { speaker: "B", es: "Para el programa de verano. Se cierra el viernes.", en: "For the summer program. It closes on Friday." },
        { speaker: "A", es: "Ya. Por el contexto entiendo que es urgente y que la mandaron de una oficina a otra. Se lo consigo hoy.", en: "Right. From the context I gather it's urgent and they sent you from one office to another. I'll get it for you today." },
        { speaker: "B", es: "Gracias, maestra. Usted es la primera que me entiende.", en: "Thank you, teacher. You're the first person who's understood me." },
      ],
    },
  },
  {
    day: 256,
    themeEs: "¿Dijiste que…?",
    storyTitle: "Sin subtítulos",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "el pódcast", en: "the podcast", example: "Escucho un pódcast en el metro." },
      { es: "desplazados", en: "displaced people", example: "\"Desplazados\" es gente que tuvo que irse." },
      { es: "adivinar", en: "to guess", example: "Adivinar en voz alta cuesta cuatro segundos." },
      { es: "la entrevista", en: "the interview", example: "Lo que sí entendí fue la entrevista." },
      { es: "el hilo", en: "the thread, the through-line", example: "Entendí el hilo aunque perdí ejemplos." },
    ],
    dialogue: {
      title: "Cuatro segundos",
      situation: "Marlana escucha un pódcast colombiano en el metro y le pregunta a Camila",
      lines: [
        { speaker: "A", es: "Más o menos entendí que hablaban de la migración. Perdí como la mitad.", en: "I more or less got that they were talking about migration. I lost about half." },
        { speaker: "B", es: "Un pódcast es más difícil que la tele. No hay caras.", en: "A podcast is harder than TV. There are no faces." },
        { speaker: "A", es: "¿Dijiste \"desplazados\"? Esa palabra la oí tres veces y no la sé.", en: "Did you say \"desplazados\"? I heard that word three times and I don't know it." },
        { speaker: "B", es: "Gente que tuvo que dejar su casa por la violencia. Es una palabra muy nuestra.", en: "People who had to leave their homes because of violence. It's a very Colombian word." },
        { speaker: "A", es: "Por el contexto entiendo que \"desplazados\" es gente que tuvo que irse. Lo adiviné.", en: "From the context I gather that \"desplazados\" is people who had to leave. I guessed it." },
        { speaker: "B", es: "Lo adivinaste bien. ¿Y por qué no lo buscaste en el diccionario?", en: "You guessed right. And why didn't you look it up?" },
        { speaker: "A", es: "Porque iba en el metro y porque quería seguir. Se me escapó la parte de los números, eso sí.", en: "Because I was on the train and because I wanted to keep going. I did miss the part with the numbers, though." },
        { speaker: "B", es: "Los números se le escapan a todo el mundo. ¿Y lo que sí entendiste?", en: "Numbers slip past everybody. And what you did catch?" },
        { speaker: "A", es: "Lo que sí entendí fue la historia de la señora de Cúcuta. Esa completa.", en: "What I did catch was the story of the woman from Cúcuta. That one whole." },
      ],
    },
  },
  {
    day: 257,
    themeEs: "Se me escapó la parte de",
    storyTitle: "Sin subtítulos",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el conserje", en: "the caretaker", example: "El conserje abre el salón." },
      { es: "confirmar", en: "to confirm", example: "¿Dijiste que confirmara antes del miércoles?" },
      { es: "repetir", en: "to repeat", example: "Solo esa parte, no todo." },
      { es: "lo suficiente", en: "enough", example: "Entendí lo suficiente para no preguntar más." },
      { es: "colgar", en: "to hang up", example: "Antes de colgar, le repetí el plan." },
    ],
    dialogue: {
      title: "Solo esa parte",
      situation: "Una llamada rápida de Rocío sobre la junta de marzo",
      lines: [
        { speaker: "B", es: "Marlana, cambio de planes: es el once, a las siete, en el salón grande, y llevas tú las sillas, ¿ok?", en: "Marlana, change of plan: it's the eleventh, at seven, in the big room, and you're bringing the chairs, okay?" },
        { speaker: "A", es: "Lo que sí entendí fue el día y la hora. ¿Dijiste que a las siete en el salón grande?", en: "What I did catch was the day and the time. Did you say seven o'clock in the big room?" },
        { speaker: "B", es: "Correcto.", en: "Correct." },
        { speaker: "A", es: "¿Dijiste que yo llevo las sillas?", en: "Did you say I'm bringing the chairs?" },
        { speaker: "B", es: "Sí, tú.", en: "Yes, you." },
        { speaker: "A", es: "Se me escapó la parte de la comida, solo esa.", en: "I missed the part about the food, just that bit." },
        { speaker: "B", es: "Cada familia trae algo. Nada de comprar.", en: "Each family brings something. Nothing bought." },
        { speaker: "A", es: "Perfecto. Por el contexto entiendo que no hace falta confirmar. Más o menos entendí lo suficiente para no preguntar más.", en: "Perfect. From the context I gather there's no need to confirm. I more or less understood enough not to ask anything else." },
        { speaker: "B", es: "Qué eficiente. Antes esta llamada nos tomaba diez minutos.", en: "How efficient. This call used to take us ten minutes." },
      ],
    },
  },
  {
    day: 258,
    themeEs: "Por el contexto",
    storyTitle: "Sin subtítulos",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "chévere", en: "great, cool (Colombia, Venezuela, Caribbean)", example: "Por el contexto entendí que \"chévere\" es \"qué bueno\"." },
      { es: "para variar", en: "for a change", example: "Entendí casi todo, para variar." },
      { es: "consentir", en: "to humor, to indulge someone", example: "¿Lo dices en serio o me estás consintiendo?" },
      { es: "el apodo", en: "the nickname", example: "Se me escapan los apodos." },
      { es: "deducir", en: "to infer", example: "Deducir es más rápido que traducir." },
    ],
    dialogue: {
      title: "Cuatro palabras nuevas",
      situation: "Cena de las tres; Camila lleva la cuenta sin decirlo",
      lines: [
        { speaker: "B", es: "Marlana. ¿Sabes cuántas veces preguntaste esta noche?", en: "Marlana. Do you know how many times you asked tonight?" },
        { speaker: "A", es: "Ni idea. ¿Muchas?", en: "No idea. A lot?" },
        { speaker: "B", es: "Dos. En tres horas.", en: "Two. In three hours." },
        { speaker: "A", es: "¿Dijiste que solo pregunté dos veces? ¿Lo dices en serio o me estás consintiendo?", en: "Did you say I only asked twice? Do you mean that or are you humoring me?" },
        { speaker: "B", es: "En serio. Y las dos veces adivinaste antes de preguntar. Lo vi.", en: "Seriously. And both times you guessed before asking. I watched you." },
        { speaker: "A", es: "Más o menos entendí toda la noche. Y sin traducir nada, eso es lo raro.", en: "I more or less understood the whole evening. And without translating anything, that's the strange part." },
        { speaker: "B", es: "¿Y las palabras que no sabías?", en: "And the words you didn't know?" },
        { speaker: "A", es: "Por el contexto entiendo que \"chévere\" es como \"qué bueno\". Y así cuatro más.", en: "From the context I gather that \"chévere\" is like \"how great\". And four more like that." },
        { speaker: "B", es: "Chévere es de aquí, de Colombia y por el Caribe. Y sí: adivinar bien también es saber.", en: "Chévere is from here, Colombia and around the Caribbean. And yes: guessing right is also knowing." },
      ],
    },
  },
  {
    day: 259,
    themeEs: "Repaso: Sin captar todo",
    isRecap: true,
    vocab: [
      { es: "el cien por ciento", en: "a hundred percent", example: "Nadie capta el cien por ciento." },
      { es: "contar huecos", en: "to count the gaps", example: "Yo contaba huecos en vez de lo que entendía." },
      { es: "entrar en pánico", en: "to panic", example: "Se me fue la parte de entrar en pánico." },
      { es: "la meta", en: "the goal", example: "Esta era la meta de la temporada." },
      { es: "sin darse cuenta", en: "without noticing", example: "Llegué sin darme cuenta." },
    ],
    dialogue: {
      title: "La meta llegó un martes",
      situation: "Jueves; Camila le enseña a Marlana lo que escribió en junio",
      lines: [
        { speaker: "B", es: "Te voy a leer algo. Las metas del invierno, escritas en junio: \"ver algo sin subtítulos\".", en: "I'm going to read you something. The winter goals, written in June: \"watch something without subtitles\"." },
        { speaker: "A", es: "Ay. Eso lo hice el martes y ni me di cuenta.", en: "Oh. I did that on Tuesday and didn't even notice." },
        { speaker: "B", es: "Por eso te lo leo. ¿Y qué cambió, según tú?", en: "That's why I'm reading it to you. And what changed, in your view?" },
        { speaker: "A", es: "Lo que sí entendí fue que cuento mal: contaba huecos. Contaba lo que se me escapaba.", en: "What I did catch was that I count wrong: I was counting holes. I was counting what slipped past me." },
        { speaker: "B", es: "Y ahora cuentas lo que llega.", en: "And now you count what lands." },
        { speaker: "A", es: "Más o menos entendí que nadie capta el cien por ciento. Ni en inglés. Eso fue lo grande.", en: "I more or less got that nobody catches a hundred percent. Not even in English. That was the big one." },
        { speaker: "B", es: "Nadie. Yo tampoco, y llevo doce años aquí oyendo inglés.", en: "Nobody. Me neither, and I've been here twelve years listening to English." },
        { speaker: "A", es: "Se me escapó la parte de entrar en pánico, esa sí se me fue del todo.", en: "What I lost was the panicking part — that one really did go completely." },
        { speaker: "B", es: "Guárdate esa frase. Por el contexto entiendo que ya casi termina el invierno. Falta lo rápido y el cierre.", en: "Keep that sentence. From the context I gather winter is nearly over. What's left is the fast stuff and the close." },
      ],
    },
  },
];
