import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 9 — "Interrumpir" (days 239–245).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week9-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek9SpeakDays: SpeakDay[] = [
  {
    day: 239,
    themeEs: "No logro entrar",
    themeEn: "I can't get in",
    missionEs: "Entra en una conversación que no te está esperando.",
    missionEn: "Get into a conversation that isn't waiting for you.",
    line: "Entendiste los noventa minutos. No dijiste nada.",
    lineEn: "You understood all ninety minutes. You said nothing.",
    prompts: [
      {
        id: "d239-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt, but it's really quick.",
        spanish: "Perdona que te interrumpa, pero es rapidísimo.",
        situationLabel: "Primera junta del comité",
        why: "The formula buys the floor by apologizing for taking it. Say it fast — the whole point is that it's short.",
        wordHints: [
          { en: "sorry to interrupt you", es: "perdona que te interrumpa" },
          { en: "it's really quick", es: "es rapidísimo" },
        ],
      },
      {
        id: "d239-espera",
        frameStem: "Espera, espera…",
        english: "Hang on, hang on — what date are we talking about?",
        spanish: "Espera, espera, ¿de qué fecha estamos hablando?",
        situationLabel: "Perdiendo el hilo",
        why: "Doubling the word is the point. *Espera* alone sounds like a request; *espera, espera* actually stops the room.",
        wordHints: [
          { en: "hang on", es: "espera" },
          { en: "what date", es: "qué fecha" },
          { en: "are we talking about", es: "estamos hablando" },
        ],
      },
      {
        id: "d239-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — we're missing the night-shift families.",
        spanish: "Antes de que se me olvide, faltan las familias del turno de noche.",
        situationLabel: "Tu punto de la noche",
        why: "The most socially bulletproof interruption there is. Nobody refuses someone who's about to forget something.",
        wordHints: [
          { en: "before i forget", es: "antes de que se me olvide" },
          { en: "we're missing", es: "faltan" },
          { en: "the night shift", es: "el turno de noche" },
        ],
      },
      {
        id: "d239-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing: who sends the invitation?",
        spanish: "Una cosa: ¿quién manda la invitación?",
        situationLabel: "La pregunta que nadie hizo",
        why: "Two words and a colon. In a fast Spanish conversation this gets you in more reliably than the polite formula.",
        wordHints: [
          { en: "one thing", es: "una cosa" },
          { en: "who sends", es: "quién manda" },
          { en: "the invitation", es: "la invitación" },
        ],
      },
      {
        id: "d239-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but we already tried that last year.",
        spanish: "Sí, sí, pero eso ya lo intentamos el año pasado.",
        situationLabel: "Sin sonar grosera",
        why: "Agree first, then turn. Two *síes* signal you were listening, which is what earns you the *pero*.",
        wordHints: [
          { en: "we already tried it", es: "ya lo intentamos" },
          { en: "last year", es: "el año pasado" },
        ],
      },
    ],
  },
  {
    day: 240,
    themeEs: "Perdona que te interrumpa",
    themeEn: "Sorry to interrupt",
    missionEs: "Interrumpe cinco veces y que nadie se moleste.",
    missionEn: "Interrupt five times and have nobody mind.",
    line: "Lo dijiste una vez y el salón se detuvo.",
    lineEn: "You said it once and the room stopped.",
    prompts: [
      {
        id: "d240-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt you, principal — it'll take a minute.",
        spanish: "Perdone que la interrumpa, directora, es un minuto.",
        situationLabel: "Con la directora, en usted",
        why: "Same formula, one letter, for the person running the meeting. That's register control, not new grammar.",
        wordHints: [
          { en: "sorry to interrupt you", es: "perdone que la interrumpa" },
          { en: "principal", es: "directora" },
          { en: "it's one minute", es: "es un minuto" },
        ],
      },
      {
        id: "d240-espera",
        frameStem: "Espera, espera…",
        english: "Hang on, hang on — two people are talking at once.",
        spanish: "Espera, espera, están hablando dos a la vez.",
        situationLabel: "Cuando se cruzan",
        why: "*A la vez* — at the same time. Naming the overlap is usually enough to fix it.",
        wordHints: [
          { en: "they're talking", es: "están hablando" },
          { en: "two people", es: "dos" },
          { en: "at once", es: "a la vez" },
        ],
      },
      {
        id: "d240-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — it's forty families, not twenty.",
        spanish: "Antes de que se me olvide, son cuarenta familias, no veinte.",
        situationLabel: "Corrigiendo el número",
        why: "You had the real number and sat on it for an hour. This phrase is the shortest route from knowing to saying.",
        wordHints: [
          { en: "it's forty", es: "son cuarenta" },
          { en: "families", es: "familias" },
          { en: "not twenty", es: "no veinte" },
        ],
      },
      {
        id: "d240-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing: are we providing the food?",
        spanish: "Una cosa: ¿la comida la ponemos nosotros?",
        situationLabel: "Lo práctico",
        why: "*La comida la ponemos* — the object stated first, then repeated as a pronoun. Extremely spoken, and it puts the emphasis where you want it.",
        wordHints: [
          { en: "the food", es: "la comida" },
          { en: "do we provide it", es: "la ponemos nosotros" },
        ],
      },
      {
        id: "d240-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but in March nobody's going to have time.",
        spanish: "Sí, sí, pero en marzo nadie va a tener tiempo.",
        situationLabel: "La objeción real",
        why: "Agreeing with the plan while objecting to the timing. That distinction is most of what meetings are.",
        wordHints: [
          { en: "in march", es: "en marzo" },
          { en: "nobody", es: "nadie" },
          { en: "is going to have time", es: "va a tener tiempo" },
        ],
      },
    ],
  },
  {
    day: 241,
    themeEs: "Espera, espera",
    themeEn: "Hang on, hang on",
    missionEs: "Detén a alguien que va demasiado rápido.",
    missionEn: "Stop someone who's going too fast.",
    line: "Parar a alguien no es grosero. Asentir sin entender sí lo es.",
    lineEn: "Stopping someone isn't rude. Nodding along while lost is worse.",
    prompts: [
      {
        id: "d241-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt — what does \"convocatoria\" mean?",
        spanish: "Perdona que te interrumpa, ¿qué significa \"convocatoria\"?",
        situationLabel: "Una palabra que no conoces",
        why: "Asking mid-meeting for a word is faster than guessing, and it's what the fluent people in the room do too.",
        wordHints: [
          { en: "what does it mean", es: "qué significa" },
        ],
      },
      {
        id: "d241-espera",
        frameStem: "Espera, espera…",
        english: "Hang on, hang on — you're going really fast.",
        spanish: "Espera, espera, vas rapidísimo.",
        situationLabel: "Sin fingir que entendiste",
        why: "*Vas rapidísimo* isn't a complaint, it's information. Give it early and people slow down without minding.",
        wordHints: [
          { en: "you're going", es: "vas" },
          { en: "really fast", es: "rapidísimo" },
        ],
      },
      {
        id: "d241-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — the flyers are still outstanding.",
        spanish: "Antes de que se me olvide, quedó pendiente lo de los volantes.",
        situationLabel: "De la junta pasada",
        why: "*Quedó pendiente lo de…* — the business of X is still outstanding. Meeting Spanish in four words.",
        wordHints: [
          { en: "it's still outstanding", es: "quedó pendiente" },
          { en: "the business of", es: "lo de" },
          { en: "the flyers", es: "los volantes" },
        ],
      },
      {
        id: "d241-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing: did you say fifteen or fifty?",
        spanish: "Una cosa, ¿dijiste quince o cincuenta?",
        situationLabel: "Los números por teléfono",
        why: "Fifteen and fifty are the pair that catch everyone. Asking is faster than deciding wrong.",
        wordHints: [
          { en: "did you say", es: "dijiste" },
          { en: "fifteen", es: "quince" },
          { en: "fifty", es: "cincuenta" },
        ],
      },
      {
        id: "d241-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but our families work nights.",
        spanish: "Sí, sí, pero nuestras familias trabajan de noche.",
        situationLabel: "El dato que solo tú tienes",
        why: "You're the one who talks to these families. That's the whole reason your interruption is worth something.",
        wordHints: [
          { en: "our families", es: "nuestras familias" },
          { en: "work", es: "trabajan" },
          { en: "nights", es: "de noche" },
        ],
      },
    ],
  },
  {
    day: 242,
    themeEs: "Antes de que se me olvide",
    themeEn: "Before I forget",
    missionEs: "Suelta un punto que llevas guardando.",
    missionEn: "Put down a point you've been holding.",
    line: "Cuarenta minutos guardando una frase es cuarenta minutos sin escuchar.",
    lineEn: "Forty minutes holding a sentence is forty minutes of not listening.",
    prompts: [
      {
        id: "d242-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt — I want to add to what you said.",
        spanish: "Perdona que te interrumpa, quiero sumar a lo que dijiste.",
        situationLabel: "Construyendo sobre otro",
        why: "*Sumar a* — to add to. The friendliest possible reason to cut in, and it makes the next one easier.",
        wordHints: [
          { en: "i want to add", es: "quiero sumar" },
          { en: "to what you said", es: "a lo que dijiste" },
        ],
      },
      {
        id: "d242-espera",
        frameStem: "Espera, espera…",
        english: "Hang on, hang on — let's not close that point yet.",
        spanish: "Espera, espera, no cerremos ese punto todavía.",
        situationLabel: "Antes de pasar de tema",
        why: "*No cerremos* — the *we* form, so it's a proposal rather than an order. Week 5's chunk, still working.",
        wordHints: [
          { en: "let's not close", es: "no cerremos" },
          { en: "that point", es: "ese punto" },
          { en: "yet", es: "todavía" },
        ],
      },
      {
        id: "d242-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — the families asked for it to be earlier.",
        spanish: "Antes de que se me olvide, las familias pidieron que fuera más temprano.",
        situationLabel: "Lo que llevabas cuarenta minutos guardando",
        why: "*Pidieron que fuera* — a past request takes the older verb form. Nothing new to learn; it's the same shape you've had since week 5.",
        wordHints: [
          { en: "they asked", es: "pidieron" },
          { en: "that it be", es: "que fuera" },
          { en: "earlier", es: "más temprano" },
        ],
      },
      {
        id: "d242-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing nobody's mentioned: transportation.",
        spanish: "Una cosa que nadie ha mencionado: el transporte.",
        situationLabel: "El hueco en el plan",
        why: "Naming a gap is the highest-value interruption in any meeting, and it takes six words.",
        wordHints: [
          { en: "nobody has mentioned", es: "nadie ha mencionado" },
          { en: "transportation", es: "el transporte" },
        ],
      },
      {
        id: "d242-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but I talked to six families and they say otherwise.",
        spanish: "Sí, sí, pero yo hablé con seis familias y dicen otra cosa.",
        situationLabel: "Con la autoridad que sí tienes",
        why: "Six months ago this sentence existed only in English. It's the same sentence; you just can carry it across now.",
        wordHints: [
          { en: "i talked", es: "yo hablé" },
          { en: "with six families", es: "con seis familias" },
          { en: "they say otherwise", es: "dicen otra cosa" },
        ],
      },
    ],
  },
  {
    day: 243,
    themeEs: "Una cosa",
    themeEn: "One thing",
    missionEs: "Entra con dos palabras, sin pedir permiso.",
    missionEn: "Get in with two words, without asking permission.",
    line: "La entrada más pequeña funciona mejor que la más educada.",
    lineEn: "The smallest opener works better than the politest one.",
    prompts: [
      {
        id: "d243-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt — we haven't met, I'm Marlana.",
        spanish: "Perdona que te interrumpa, no nos conocemos, soy Marlana.",
        situationLabel: "Con alguien nuevo del comité",
        why: "Interrupting and introducing yourself in one breath. It's the fastest way into a room you don't know.",
        wordHints: [
          { en: "we don't know each other", es: "no nos conocemos" },
          { en: "i'm", es: "soy" },
        ],
      },
      {
        id: "d243-espera",
        frameStem: "Espera, espera…",
        english: "Hang on, hang on — Rocío, that's not what we agreed.",
        spanish: "Espera, espera, Rocío, eso no fue lo que quedamos.",
        situationLabel: "Con alguien de confianza",
        why: "*Lo que quedamos* — what we settled on. With someone you know, you drop the apology entirely.",
        wordHints: [
          { en: "that wasn't", es: "eso no fue" },
          { en: "what we agreed", es: "lo que quedamos" },
        ],
      },
      {
        id: "d243-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — thanks for bringing the coffee.",
        spanish: "Antes de que se me olvide, gracias por traer el café.",
        situationLabel: "Lo pequeño también cuenta",
        why: "The same phrase for logistics and for kindness. Most of what gets forgotten in meetings is the thanking.",
        wordHints: [
          { en: "thanks for", es: "gracias por" },
          { en: "bringing", es: "traer" },
          { en: "the coffee", es: "el café" },
        ],
      },
      {
        id: "d243-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing: I can take care of that.",
        spanish: "Una cosa: yo puedo encargarme de eso.",
        situationLabel: "Ofreciéndote sin rodeos",
        why: "Two words and a colon, then you've volunteered. The whole exchange takes three seconds.",
        wordHints: [
          { en: "i can", es: "yo puedo" },
          { en: "take care of", es: "encargarme de" },
        ],
      },
      {
        id: "d243-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but that leaves half of them out.",
        spanish: "Sí, sí, pero eso deja fuera a la mitad.",
        situationLabel: "Cuando acuerdan demasiado rápido",
        why: "*Dejar fuera a* — to leave someone out. The objection worth learning if you work with families.",
        wordHints: [
          { en: "that leaves out", es: "eso deja fuera" },
          { en: "half of them", es: "a la mitad" },
        ],
      },
    ],
  },
  {
    day: 244,
    themeEs: "Sí, sí, pero",
    themeEn: "Yes, yes, but",
    missionEs: "Está de acuerdo en voz alta y luego añade lo tuyo.",
    missionEn: "Agree out loud, then add your own.",
    line: "No se trata de contradecir. Se trata de ganarse el turno.",
    lineEn: "It isn't about disagreeing. It's about earning the turn.",
    prompts: [
      {
        id: "d244-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "Sorry to interrupt, but what you're saying is the key thing.",
        spanish: "Perdona que te interrumpa, pero eso que dices es clave.",
        situationLabel: "Interrumpir para apoyar",
        why: "Interrupting to agree is the friendliest use of all of these — and it makes the next interruption easier.",
        wordHints: [
          { en: "what you're saying", es: "eso que dices" },
          { en: "is key", es: "es clave" },
        ],
      },
      {
        id: "d244-espera",
        frameStem: "Espera, espera…",
        english: "Hang on, hang on — I did like that idea.",
        spanish: "Espera, espera, esa idea sí me gustó.",
        situationLabel: "Rescatando algo bueno",
        why: "That *sí* before the verb is emphasis: I *did* like it. Rescuing an idea before the room moves past it.",
        wordHints: [
          { en: "that idea", es: "esa idea" },
          { en: "i did like", es: "sí me gustó" },
        ],
      },
      {
        id: "d244-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — the idea was Rocío's, not mine.",
        spanish: "Antes de que se me olvide, la idea fue de Rocío, no mía.",
        situationLabel: "Dando el crédito",
        why: "Credit given in public and in Spanish. Worth the interruption every time.",
        wordHints: [
          { en: "the idea was", es: "la idea fue" },
          { en: "rocío's", es: "de rocío" },
          { en: "not mine", es: "no mía" },
        ],
      },
      {
        id: "d244-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing: let's be clear who's calling whom.",
        spanish: "Una cosa: que quede claro quién llama a quién.",
        situationLabel: "Cerrando con lo práctico",
        why: "*Que quede claro* — let it be clear. A bare *que* + shifted verb, used as a mild command to the whole room.",
        wordHints: [
          { en: "let it be clear", es: "que quede claro" },
          { en: "who calls whom", es: "quién llama a quién" },
        ],
      },
      {
        id: "d244-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but the hard part is keeping it going every month.",
        spanish: "Sí, sí, pero la parte difícil es sostenerlo cada mes.",
        situationLabel: "El problema de verdad",
        why: "*Sí, sí, pero* is not disagreement. It's the sound of a conversation being built by more than one person.",
        wordHints: [
          { en: "the hard part", es: "la parte difícil" },
          { en: "keeping it going", es: "sostenerlo" },
          { en: "every month", es: "cada mes" },
        ],
      },
    ],
  },
  {
    day: 245,
    themeEs: "Repaso: Interrumpir",
    themeEn: "Review: Interrupting",
    missionEs: "Cuenta cuántas veces hablaste, no cuántas entendiste.",
    missionEn: "Count how many times you spoke, not how many you understood.",
    line: "Segunda junta: hablaste nueve veces.",
    lineEn: "Second meeting: you spoke nine times.",
    prompts: [
      {
        id: "d245-perdona",
        frameStem: "Perdona que te interrumpa…",
        english: "\"Sorry to interrupt\" was my way in.",
        spanish: "Perdona que te interrumpa fue mi puerta de entrada.",
        situationLabel: "La frase que abrió todo",
        why: "*La puerta de entrada* — the way in. One phrase turned a room you sat in into a room you're part of.",
        wordHints: [
          { en: "was", es: "fue" },
          { en: "my way in", es: "mi puerta de entrada" },
        ],
      },
      {
        id: "d245-espera",
        frameStem: "Espera, espera…",
        english: "\"Hang on, hang on\" saved me from nodding without understanding.",
        spanish: "Espera, espera me salvó de asentir sin entender.",
        situationLabel: "Lo que ya no haces",
        why: "*Asentir sin entender* — nodding without understanding. The habit this whole week was built to break.",
        wordHints: [
          { en: "saved me from", es: "me salvó de" },
          { en: "nodding", es: "asentir" },
          { en: "without understanding", es: "sin entender" },
        ],
      },
      {
        id: "d245-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "\"Before I forget\" turned out to be the easiest of them all.",
        spanish: "Antes de que se me olvide resultó la más fácil de todas.",
        situationLabel: "La sorpresa de la semana",
        why: "Longest phrase, easiest to use. Nobody in any language refuses someone about to forget something.",
        wordHints: [
          { en: "turned out", es: "resultó" },
          { en: "the easiest", es: "la más fácil" },
          { en: "of them all", es: "de todas" },
        ],
      },
      {
        id: "d245-una-cosa",
        frameStem: "Una cosa…",
        english: "One thing: two words and you're already in.",
        spanish: "Una cosa: dos palabras y ya estás dentro.",
        situationLabel: "La que te llevas",
        why: "The smallest opener beat the politest one all week. Worth remembering the next time you're waiting for a gap.",
        wordHints: [
          { en: "two words", es: "dos palabras" },
          { en: "you're already in", es: "ya estás dentro" },
        ],
      },
      {
        id: "d245-si-si-pero",
        frameStem: "Sí, sí, pero…",
        english: "Yes, yes, but that was the hardest one to say.",
        spanish: "Sí, sí, pero fue la que más me costó decir.",
        situationLabel: "La que sigue costando",
        why: "Understanding was never the problem in that room. Timing was — and timing is five phrases you can now say without thinking.",
        wordHints: [
          { en: "it was the one", es: "fue la que" },
          { en: "was hardest for me", es: "más me costó" },
          { en: "to say", es: "decir" },
        ],
      },
    ],
  },
];
