import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 7 — "Ojalá" (days 225–231). Subjunctive chunk 3: wishes.
 * Each `spanish` is copied verbatim from content/drafts/invierno/week7-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek7SpeakDays: SpeakDay[] = [
  {
    day: 225,
    themeEs: "La llamada de Camila",
    themeEn: "Camila's call",
    missionEs: "Acompaña a alguien con palabras, no con soluciones.",
    missionEn: "Be with someone using words, not solutions.",
    line: "A veces no hay nada que hacer, y sí algo que decir.",
    lineEn: "Sometimes there's nothing to do, and there is something to say.",
    prompts: [
      {
        id: "d225-ojala",
        frameStem: "Ojalá…",
        english: "I hope it's nothing serious.",
        spanish: "Ojalá no sea nada grave.",
        situationLabel: "Las once de la noche",
        why: "*Ojalá* came from Arabic — *law šā' Allāh*, if God wills. It takes no subject and always shifts the verb after it.",
        wordHints: [
          { en: "i hope", es: "ojalá" },
          { en: "it isn't", es: "no sea" },
          { en: "anything serious", es: "nada grave" },
        ],
      },
      {
        id: "d225-espero-que",
        frameStem: "Espero que…",
        english: "I hope you can get some sleep tonight.",
        spanish: "Espero que puedas dormir algo esta noche.",
        situationLabel: "Antes de colgar",
        why: "*Espero que* is the same wish with a person attached — slightly more personal than *ojalá*, and just as automatic.",
        wordHints: [
          { en: "you can", es: "puedas" },
          { en: "sleep", es: "dormir" },
          { en: "a bit", es: "algo" },
          { en: "tonight", es: "esta noche" },
        ],
      },
      {
        id: "d225-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Hope tonight goes okay on your shift.",
        spanish: "Que te vaya bien esta noche en el turno.",
        situationLabel: "Ella sigue trabajando",
        why: "A complete goodbye on its own. Nobody parses it — it just gets said, the way \"take care\" does.",
        wordHints: [
          { en: "hope it goes well", es: "que te vaya bien" },
          { en: "tonight", es: "esta noche" },
          { en: "on your shift", es: "en el turno" },
        ],
      },
      {
        id: "d225-que-descanses",
        frameStem: "Que descanses…",
        english: "Get some rest, even a little.",
        spanish: "Que descanses, aunque sea un rato.",
        situationLabel: "El último mensaje del día",
        why: "*Aunque sea* — even if it's only. Two words that soften any request down to something possible.",
        wordHints: [
          { en: "get some rest", es: "que descanses" },
          { en: "even if it's", es: "aunque sea" },
          { en: "a little while", es: "un rato" },
        ],
      },
      {
        id: "d225-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I could do something more than write to you.",
        spanish: "Ojalá pudiera hacer algo más que escribirte.",
        situationLabel: "La verdad incómoda",
        why: "*Ojalá pueda* is still possible; *ojalá pudiera* is a wish you already know won't come true. One vowel apart.",
        wordHints: [
          { en: "i wish i could", es: "ojalá pudiera" },
          { en: "do something more", es: "hacer algo más" },
          { en: "than write to you", es: "que escribirte" },
        ],
      },
    ],
  },
  {
    day: 226,
    themeEs: "Espero que no sea grave",
    themeEn: "I hope it isn't serious",
    missionEs: "Habla de una espera sin llenarla de consejos.",
    missionEn: "Talk about a wait without filling it with advice.",
    line: "Esperar también tiene sus frases.",
    lineEn: "Waiting has its own phrases too.",
    prompts: [
      {
        id: "d226-ojala",
        frameStem: "Ojalá…",
        english: "I hope the results come today.",
        spanish: "Ojalá salgan hoy los resultados.",
        situationLabel: "Segundo día de espera",
        why: "*Salir* for results coming out — the same verb as leaving, doing completely different work.",
        wordHints: [
          { en: "they come out", es: "salgan" },
          { en: "today", es: "hoy" },
          { en: "the results", es: "los resultados" },
        ],
      },
      {
        id: "d226-espero-que",
        frameStem: "Espero que…",
        english: "I hope it's nothing to worry about.",
        spanish: "Espero que no sea nada de cuidado.",
        situationLabel: "Lo que todos dicen",
        why: "*Nada de cuidado* — nothing to worry about. The gentler, more common way to say it than *nada grave*.",
        wordHints: [
          { en: "it isn't", es: "no sea" },
          { en: "anything to worry about", es: "nada de cuidado" },
        ],
      },
      {
        id: "d226-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Hope the call with the doctor goes well.",
        spanish: "Que te vaya bien en la llamada con el doctor.",
        situationLabel: "Antes de la llamada",
        why: "The formula takes any *en* + situation. That's why one phrase covers a whole week of different days.",
        wordHints: [
          { en: "on the call", es: "en la llamada" },
          { en: "with the doctor", es: "con el doctor" },
        ],
      },
      {
        id: "d226-que-descanses",
        frameStem: "Que descanses…",
        english: "Get some rest — and don't answer me today.",
        spanish: "Que descanses y no me contestes hoy.",
        situationLabel: "Quitándole una obligación",
        why: "*No me contestes hoy* is its own kindness. Giving someone permission not to reply is worth being able to say.",
        wordHints: [
          { en: "don't answer me", es: "no me contestes" },
          { en: "today", es: "hoy" },
        ],
      },
      {
        id: "d226-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I could wait for those results with you.",
        spanish: "Ojalá pudiera esperar contigo esos resultados.",
        situationLabel: "A cinco mil kilómetros",
        why: "The whole point of *ojalá pudiera*: naming the thing you'd do if distance weren't distance.",
        wordHints: [
          { en: "wait", es: "esperar" },
          { en: "with you", es: "contigo" },
          { en: "those results", es: "esos resultados" },
        ],
      },
    ],
  },
  {
    day: 227,
    themeEs: "Que te vaya bien",
    themeEn: "Safe travels",
    missionEs: "Despide a alguien de cinco maneras distintas.",
    missionEn: "See someone off five different ways.",
    line: "Se va el viernes. Todo lo que digas ahora es una despedida.",
    lineEn: "She flies Friday. Everything you say now is a goodbye.",
    prompts: [
      {
        id: "d227-ojala",
        frameStem: "Ojalá…",
        english: "I hope you find a flight for Friday.",
        spanish: "Ojalá encuentres vuelo para el viernes.",
        situationLabel: "Buscando vuelos a Bogotá",
        why: "*Encontrar vuelo*, no article. Spanish drops it when the thing is generic — any flight, not a specific one.",
        wordHints: [
          { en: "you find", es: "encuentres" },
          { en: "a flight", es: "vuelo" },
          { en: "for friday", es: "para el viernes" },
        ],
      },
      {
        id: "d227-espero-que",
        frameStem: "Espero que…",
        english: "I hope the trip is an easy one.",
        spanish: "Espero que el viaje sea tranquilo.",
        situationLabel: "El día antes",
        why: "*Tranquilo* for a trip means uneventful, not calm. Uneventful is what you want from a flight.",
        wordHints: [
          { en: "the trip", es: "el viaje" },
          { en: "is", es: "sea" },
          { en: "easy, uneventful", es: "tranquilo" },
        ],
      },
      {
        id: "d227-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Get there safely, and hug your grandmother for me.",
        spanish: "Que llegues con bien y abraces a tu abuela por mí.",
        situationLabel: "En el aeropuerto",
        why: "*Que llegues con bien* — that you arrive safely. Older, warmer, and heard at every airport and bus station in Latin America.",
        wordHints: [
          { en: "that you arrive", es: "que llegues" },
          { en: "safely", es: "con bien" },
          { en: "you hug", es: "abraces" },
          { en: "for me", es: "por mí" },
        ],
      },
      {
        id: "d227-que-descanses",
        frameStem: "Que descanses…",
        english: "Get some rest on the flight, it's six hours.",
        spanish: "Que descanses en el vuelo, son seis horas.",
        situationLabel: "Antes de despegar",
        why: "The formula plus a plain fact. That combination is most of what comfort sounds like in any language.",
        wordHints: [
          { en: "on the flight", es: "en el vuelo" },
          { en: "it's", es: "son" },
          { en: "six hours", es: "seis horas" },
        ],
      },
      {
        id: "d227-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I could go with you.",
        spanish: "Ojalá pudiera ir contigo.",
        situationLabel: "Lo que de verdad querrías",
        why: "Four words, and there is no version of them that isn't true. Say it plainly.",
        wordHints: [
          { en: "i wish i could", es: "ojalá pudiera" },
          { en: "go", es: "ir" },
          { en: "with you", es: "contigo" },
        ],
      },
    ],
  },
  {
    day: 228,
    themeEs: "Ojalá pudiera ir contigo",
    themeEn: "I wish I could go with you",
    missionEs: "Di algo que no puedes hacer, sin disculparte por no poder.",
    missionEn: "Say something you can't do, without apologizing for not being able to.",
    line: "El deseo imposible también se dice en voz alta.",
    lineEn: "The impossible wish gets said out loud too.",
    prompts: [
      {
        id: "d228-ojala",
        frameStem: "Ojalá…",
        english: "I hope you've already landed.",
        spanish: "Ojalá ya hayas llegado.",
        situationLabel: "Sin noticias desde el despegue",
        why: "*Ojalá ya hayas llegado* — hopefully you've already arrived. A wish about something that may already be true.",
        wordHints: [
          { en: "already", es: "ya" },
          { en: "you have arrived", es: "hayas llegado" },
        ],
      },
      {
        id: "d228-espero-que",
        frameStem: "Espero que…",
        english: "I hope you're not alone at the hospital.",
        spanish: "Espero que no estés sola en el hospital.",
        situationLabel: "Lo que más te preocupa",
        why: "*Estés* — the shifted *estar*, one of maybe five forms carrying half of this grammar. Learn it as a word.",
        wordHints: [
          { en: "you're not", es: "no estés" },
          { en: "alone", es: "sola" },
          { en: "at the hospital", es: "en el hospital" },
        ],
      },
      {
        id: "d228-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Hope it goes well with the doctors today.",
        spanish: "Que te vaya bien con los médicos hoy.",
        situationLabel: "El mensaje de la mañana",
        why: "Same four words, seventh different situation. That's what a formula buys you.",
        wordHints: [
          { en: "with the doctors", es: "con los médicos" },
          { en: "today", es: "hoy" },
        ],
      },
      {
        id: "d228-que-descanses",
        frameStem: "Que descanses…",
        english: "Get some rest, whenever you can, not when you're supposed to.",
        spanish: "Que descanses cuando puedas, no cuando debas.",
        situationLabel: "Sin horarios",
        why: "Two week-6 chunks folded into a week-7 formula, and neither one needed building.",
        wordHints: [
          { en: "when you can", es: "cuando puedas" },
          { en: "when you should", es: "cuando debas" },
        ],
      },
      {
        id: "d228-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I could take a little of the worry off you.",
        spanish: "Ojalá pudiera quitarte un poco de la preocupación.",
        situationLabel: "Lo más honesto que puedes decir",
        why: "The hardest thing to say all winter, and she said it without switching languages. The Spanish was enough.",
        wordHints: [
          { en: "take off you", es: "quitarte" },
          { en: "a little", es: "un poco" },
          { en: "the worry", es: "la preocupación" },
        ],
      },
    ],
  },
  {
    day: 229,
    themeEs: "Que descanses",
    themeEn: "Sleep well",
    missionEs: "Manda el mismo deseo siete veces y que no suene igual.",
    missionEn: "Send the same wish seven times and make it land each time.",
    line: "Siete husos horarios. Tus mensajes le llegan dormida.",
    lineEn: "Seven time zones. Your messages arrive while she's asleep.",
    prompts: [
      {
        id: "d229-ojala",
        frameStem: "Ojalá…",
        english: "I hope you're asleep when this reaches you.",
        spanish: "Ojalá estés durmiendo cuando te llegue esto.",
        situationLabel: "Escribiendo a medianoche",
        why: "Two shifted verbs in one sentence — *estés* and *llegue* — and neither one required a decision.",
        wordHints: [
          { en: "you're sleeping", es: "estés durmiendo" },
          { en: "when it reaches you", es: "cuando te llegue" },
        ],
      },
      {
        id: "d229-espero-que",
        frameStem: "Espero que…",
        english: "I hope you're not answering me out of obligation.",
        spanish: "Espero que no me contestes por compromiso.",
        situationLabel: "Dándole salida",
        why: "*Por compromiso* — out of obligation, because it would be rude not to. There's no one-word English for it.",
        wordHints: [
          { en: "you don't answer me", es: "no me contestes" },
          { en: "out of obligation", es: "por compromiso" },
        ],
      },
      {
        id: "d229-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Hope today goes well, and that's all — I'll stop there.",
        spanish: "Que te vaya bien hoy y ya, no digo más.",
        situationLabel: "Sin agobiar",
        why: "*Y ya* — and that's it. The most useful two words for ending a message before it gets heavy.",
        wordHints: [
          { en: "and that's it", es: "y ya" },
          { en: "i won't say more", es: "no digo más" },
        ],
      },
      {
        id: "d229-que-descanses",
        frameStem: "Que descanses…",
        english: "Sleep well — it's the only thing I can send you from here.",
        spanish: "Que descanses, es lo único que puedo mandarte desde aquí.",
        situationLabel: "La séptima noche",
        why: "The same four words every night for a week. Not poverty of vocabulary — that's exactly what these phrases are for.",
        wordHints: [
          { en: "the only thing", es: "lo único" },
          { en: "i can send you", es: "puedo mandarte" },
          { en: "from here", es: "desde aquí" },
        ],
      },
      {
        id: "d229-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I could sit with you a while, without talking.",
        spanish: "Ojalá pudiera sentarme un rato contigo, sin hablar.",
        situationLabel: "Lo que harías si estuvieras",
        why: "A whole season about speaking, and the truest sentence in it is about sitting quietly. Both are Spanish.",
        wordHints: [
          { en: "sit", es: "sentarme" },
          { en: "a while", es: "un rato" },
          { en: "without talking", es: "sin hablar" },
        ],
      },
    ],
  },
  {
    day: 230,
    themeEs: "Ojalá la hubieras conocido",
    themeEn: "I wish you'd met her",
    missionEs: "Recibe una buena noticia y responde con alegría, no con alivio.",
    missionEn: "Take good news and answer with joy, not relief.",
    line: "Mejoró. Ahora Camila te cuenta quién es.",
    lineEn: "She's better. Now Camila tells you who she is.",
    prompts: [
      {
        id: "d230-ojala",
        frameStem: "Ojalá…",
        english: "I hope she keeps improving this fast.",
        spanish: "Ojalá siga mejorando así de rápido.",
        situationLabel: "La primera buena noticia",
        why: "*Así de rápido* — this fast. *Así de* + adjective is how Spanish points at a degree you can both see.",
        wordHints: [
          { en: "she keeps", es: "siga" },
          { en: "improving", es: "mejorando" },
          { en: "this fast", es: "así de rápido" },
        ],
      },
      {
        id: "d230-espero-que",
        frameStem: "Espero que…",
        english: "I hope the relief hits you all at once.",
        spanish: "Espero que te caiga el alivio de golpe.",
        situationLabel: "Después de ocho días",
        why: "*Caer* for a feeling arriving — *me cayó el veinte*, *me cayó mal*. Emotions land on you in Spanish.",
        wordHints: [
          { en: "hits you", es: "te caiga" },
          { en: "the relief", es: "el alivio" },
          { en: "all at once", es: "de golpe" },
        ],
      },
      {
        id: "d230-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Hope these last few days there go well.",
        spanish: "Que te vaya bien en estos últimos días allá.",
        situationLabel: "Antes de que vuelva",
        why: "*Allá* rather than *ahí* — over there, far away, where she is and you aren't.",
        wordHints: [
          { en: "these last days", es: "estos últimos días" },
          { en: "over there", es: "allá" },
        ],
      },
      {
        id: "d230-que-descanses",
        frameStem: "Que descanses…",
        english: "Sleep with no alarm for the first time.",
        spanish: "Que descanses sin alarma por primera vez.",
        situationLabel: "La primera noche tranquila",
        why: "Eight days of the same phrase, and this is the first time it's a celebration rather than a comfort.",
        wordHints: [
          { en: "without an alarm", es: "sin alarma" },
          { en: "for the first time", es: "por primera vez" },
        ],
      },
      {
        id: "d230-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I'd met her.",
        spanish: "Ojalá la hubiera conocido.",
        situationLabel: "Después de oír las historias",
        why: "The same past-wish shape as week 5's *hubieras estado*. By now it comes out whole, with nothing to assemble.",
        wordHints: [
          { en: "i wish", es: "ojalá" },
          { en: "i had met her", es: "la hubiera conocido" },
        ],
      },
    ],
  },
  {
    day: 231,
    themeEs: "Repaso: Ojalá",
    themeEn: "Review: I hope",
    missionEs: "Repite las cinco frases de la semana, cada una en serio.",
    missionEn: "Say the week's five phrases again, each one meant.",
    line: "Cuatro palabras, siete noches, y alcanzaron.",
    lineEn: "Four words, seven nights, and they were enough.",
    prompts: [
      {
        id: "d231-ojala",
        frameStem: "Ojalá…",
        english: "I hope I don't have to use these phrases very often.",
        spanish: "Ojalá no tenga que usar estas frases muy seguido.",
        situationLabel: "El deseo del repaso",
        why: "*Tener que* inside the chunk: *ojalá no tenga que*. The most-used verb in Spanish, in the shifted form, without any effort.",
        wordHints: [
          { en: "i don't have to", es: "no tenga que" },
          { en: "use", es: "usar" },
          { en: "very often", es: "muy seguido" },
        ],
      },
      {
        id: "d231-espero-que",
        frameStem: "Espero que…",
        english: "I hope you felt accompanied.",
        spanish: "Espero que te hayas sentido acompañada.",
        situationLabel: "Lo que querías lograr",
        why: "*Espero que te hayas sentido* — a wish about how something already went. The past keeps sliding into these phrases without changing them.",
        wordHints: [
          { en: "you have felt", es: "te hayas sentido" },
          { en: "accompanied", es: "acompañada" },
        ],
      },
      {
        id: "d231-que-te-vaya",
        frameStem: "Que te vaya bien…",
        english: "Hope it goes well — I said it twelve times this week.",
        spanish: "Que te vaya bien: lo dije doce veces esta semana.",
        situationLabel: "Contando la semana",
        why: "Twelve repetitions of one formula. That's not a small vocabulary; that's a phrase doing the job it exists for.",
        wordHints: [
          { en: "i said it", es: "lo dije" },
          { en: "twelve times", es: "doce veces" },
        ],
      },
      {
        id: "d231-que-descanses",
        frameStem: "Que descanses…",
        english: "Sleep well: four words, seven nights.",
        spanish: "Que descanses: cuatro palabras, siete noches.",
        situationLabel: "El balance",
        why: "Worth noticing what you actually needed this week — and how little of it was new grammar.",
        wordHints: [
          { en: "four words", es: "cuatro palabras" },
          { en: "seven nights", es: "siete noches" },
        ],
      },
      {
        id: "d231-ojala-pudiera",
        frameStem: "Ojalá pudiera…",
        english: "I wish I'd had these phrases ten years ago.",
        spanish: "Ojalá hubiera tenido estas frases hace diez años.",
        situationLabel: "Mirando atrás",
        why: "The most useful Spanish of the whole winter, learned in the worst possible week. That's usually how it goes.",
        wordHints: [
          { en: "i had had", es: "hubiera tenido" },
          { en: "these phrases", es: "estas frases" },
          { en: "ten years ago", es: "hace diez años" },
        ],
      },
    ],
  },
];
