import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 6 — "Cuando llegues…" (days 218–224). Subjunctive chunk 2:
 * future time. Each `spanish` is copied verbatim from
 * content/drafts/invierno/week6-frames.ts (convention 2).
 */
export const invWeek6SpeakDays: SpeakDay[] = [
  {
    day: 218,
    themeEs: "Cuando pare la nieve",
    themeEn: "When the snow stops",
    missionEs: "Habla de mañana usando cinco veces \"todavía no ha pasado\".",
    missionEn: "Talk about tomorrow five times over, all of it not-yet-happened.",
    line: "Si todavía no pasó, el verbo cambia. Eso es todo.",
    lineEn: "If it hasn't happened yet, the verb changes. That's the whole thing.",
    prompts: [
      {
        id: "d218-cuando",
        frameStem: "Cuando…",
        english: "When I get home, I'll send you a voice note.",
        spanish: "Cuando llegue a casa, te mando un audio.",
        situationLabel: "Saliendo del colegio",
        why: "*Cuando llegue* — you haven't arrived yet, so the verb shifts. *Cuando llego* would mean every day, as a habit.",
        wordHints: [
          { en: "when i get", es: "cuando llegue" },
          { en: "home", es: "a casa" },
          { en: "i'll send you", es: "te mando" },
        ],
      },
      {
        id: "d218-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as it starts snowing, they close the schools.",
        spanish: "En cuanto empiece a nevar, cierran las escuelas.",
        situationLabel: "Lo que todos esperan",
        why: "*En cuanto* is *cuando* with urgency — the very moment it happens, not sometime after.",
        wordHints: [
          { en: "as soon as", es: "en cuanto" },
          { en: "it starts", es: "empiece" },
          { en: "to snow", es: "a nevar" },
          { en: "they close", es: "cierran" },
        ],
      },
      {
        id: "d218-hasta-que",
        frameStem: "Hasta que…",
        english: "I'm not going out until the storm passes.",
        spanish: "No salgo hasta que pase la tormenta.",
        situationLabel: "El plan del jueves",
        why: "Same logic on the other end: the storm hasn't passed, so *pase*. Say *pasó* and you're telling a story about last winter.",
        wordHints: [
          { en: "i'm not going out", es: "no salgo" },
          { en: "until", es: "hasta que" },
          { en: "passes", es: "pase" },
          { en: "the storm", es: "la tormenta" },
        ],
      },
      {
        id: "d218-antes-de-que",
        frameStem: "Antes de que…",
        english: "I want to get home before it starts.",
        spanish: "Quiero llegar a casa antes de que empiece.",
        situationLabel: "Ganándole a la tormenta",
        why: "*Antes de que* always shifts the verb. But *antes de* with no *que* takes a plain infinitive: *antes de salir*. One word, two grammars.",
        wordHints: [
          { en: "i want to get", es: "quiero llegar" },
          { en: "before", es: "antes de que" },
          { en: "it starts", es: "empiece" },
        ],
      },
      {
        id: "d218-apenas",
        frameStem: "Apenas…",
        english: "The moment the sun's out, this turns to ice.",
        spanish: "Apenas salga el sol, esto se convierte en hielo.",
        situationLabel: "Advirtiéndole a un vecino",
        why: "*Apenas* is the colloquial Latin American twin of *en cuanto* — same job, half the syllables, far more common out loud.",
        wordHints: [
          { en: "the moment", es: "apenas" },
          { en: "the sun comes out", es: "salga el sol" },
          { en: "turns into", es: "se convierte en" },
          { en: "ice", es: "hielo" },
        ],
      },
    ],
  },
  {
    day: 219,
    themeEs: "En cuanto cancelen",
    themeEn: "As soon as they cancel",
    missionEs: "Cuenta una espera entera sin saber la hora.",
    missionEn: "Narrate a whole wait without knowing the time.",
    line: "Nadie duerme la noche antes de un día de nieve.",
    lineEn: "Nobody sleeps the night before a snow day.",
    prompts: [
      {
        id: "d219-cuando",
        frameStem: "Cuando…",
        english: "When they announce the closure, the uncertainty ends.",
        spanish: "Cuando anuncien el cierre, se acaba la incertidumbre.",
        situationLabel: "Esperando el anuncio",
        why: "*Anuncien* — they, unnamed. Spanish uses the third person plural where English says \"they\" without meaning anyone in particular.",
        wordHints: [
          { en: "they announce", es: "anuncien" },
          { en: "the closure", es: "el cierre" },
          { en: "ends", es: "se acaba" },
          { en: "the uncertainty", es: "la incertidumbre" },
        ],
      },
      {
        id: "d219-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as they cancel, I'll send the message to the group.",
        spanish: "En cuanto cancelen, mando el mensaje al grupo.",
        situationLabel: "A las cinco de la mañana",
        why: "The main clause stays in plain present — *mando*. Only the *en cuanto* half shifts.",
        wordHints: [
          { en: "they cancel", es: "cancelen" },
          { en: "i'll send", es: "mando" },
          { en: "to the group", es: "al grupo" },
        ],
      },
      {
        id: "d219-hasta-que",
        frameStem: "Hasta que…",
        english: "I'm not preparing anything until they say something.",
        spanish: "No preparo nada hasta que digan algo.",
        situationLabel: "En pausa",
        why: "Two negatives that aren't fighting: *no preparo nada* is standard Spanish, not a double negative to fix.",
        wordHints: [
          { en: "i'm not preparing", es: "no preparo" },
          { en: "anything", es: "nada" },
          { en: "they say", es: "digan" },
        ],
      },
      {
        id: "d219-antes-de-que",
        frameStem: "Antes de que…",
        english: "I'm going to write to them before they ask me.",
        spanish: "Voy a escribirles antes de que me pregunten.",
        situationLabel: "Adelantándote a las familias",
        why: "Getting ahead of the question is most of a teacher's job. Worth having the phrase ready.",
        wordHints: [
          { en: "i'm going to write to them", es: "voy a escribirles" },
          { en: "they ask me", es: "me pregunten" },
        ],
      },
      {
        id: "d219-apenas",
        frameStem: "Apenas…",
        english: "The moment they confirm it, I'll let you know.",
        spanish: "Apenas lo confirmen, te aviso.",
        situationLabel: "Prometiendo avisar",
        why: "Four words that end almost every practical exchange in Spanish. Say it enough and it stops being a sentence.",
        wordHints: [
          { en: "they confirm it", es: "lo confirmen" },
          { en: "i'll let you know", es: "te aviso" },
        ],
      },
    ],
  },
  {
    day: 220,
    themeEs: "Hasta que pase la tormenta",
    themeEn: "Until the storm passes",
    missionEs: "Describe un día entero encerrada, todo en futuro.",
    missionEn: "Describe a whole day snowed in, all of it in the future.",
    line: "Dos pies de nieve y una lista de cosas que todavía no pasan.",
    lineEn: "Two feet of snow and a list of things that haven't happened yet.",
    prompts: [
      {
        id: "d220-cuando",
        frameStem: "Cuando…",
        english: "When the power comes back, I'll put coffee on.",
        spanish: "Cuando vuelva la luz, pongo café.",
        situationLabel: "Sin electricidad",
        why: "*La luz* is the electricity, not just the light. *Se fue la luz* — the power's out.",
        wordHints: [
          { en: "comes back", es: "vuelva" },
          { en: "the power", es: "la luz" },
          { en: "i'll put on", es: "pongo" },
        ],
      },
      {
        id: "d220-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as they clear the street, I'll go out for a walk.",
        spanish: "En cuanto limpien la calle, salgo a caminar.",
        situationLabel: "Mirando por la ventana",
        why: "*Limpiar la calle* is what everyone actually says for clearing snow — no special vocabulary needed.",
        wordHints: [
          { en: "they clear", es: "limpien" },
          { en: "the street", es: "la calle" },
          { en: "i'll go out", es: "salgo" },
        ],
      },
      {
        id: "d220-hasta-que",
        frameStem: "Hasta que…",
        english: "Nobody drives until they say it's safe.",
        spanish: "Nadie maneja hasta que digan que es seguro.",
        situationLabel: "La regla del día",
        why: "*Manejar* is to drive across Latin America; *conducir* is the formal or Spanish one. Use *manejar*.",
        wordHints: [
          { en: "nobody drives", es: "nadie maneja" },
          { en: "they say", es: "digan" },
          { en: "it's safe", es: "es seguro" },
        ],
      },
      {
        id: "d220-antes-de-que",
        frameStem: "Antes de que…",
        english: "We should put salt down before it gets dark.",
        spanish: "Hay que echar sal antes de que se haga de noche.",
        situationLabel: "En la entrada de la casa",
        why: "*Hacerse de noche* — for night to fall. A little idiom that saves you inventing a longer sentence.",
        wordHints: [
          { en: "we should", es: "hay que" },
          { en: "put down salt", es: "echar sal" },
          { en: "it gets dark", es: "se haga de noche" },
        ],
      },
      {
        id: "d220-apenas",
        frameStem: "Apenas…",
        english: "The moment the plow goes by, we'll move the car.",
        spanish: "Apenas pase la máquina, movemos el carro.",
        situationLabel: "Esperando la quitanieve",
        why: "*El carro* in most of Latin America, *el auto* in the Southern Cone. Not *el coche*, which reads as Spain.",
        wordHints: [
          { en: "goes by", es: "pase" },
          { en: "the plow", es: "la máquina" },
          { en: "we'll move", es: "movemos" },
          { en: "the car", es: "el carro" },
        ],
      },
    ],
  },
  {
    day: 221,
    themeEs: "Antes de que se congelen las tuberías",
    themeEn: "Before the pipes freeze",
    missionEs: "Llama por algo urgente y explícalo sin volver al inglés.",
    missionEn: "Call about something urgent and explain it without going back to English.",
    line: "Lo urgente no espera a que tengas las palabras.",
    lineEn: "Urgent things don't wait until you have the words.",
    prompts: [
      {
        id: "d221-cuando",
        frameStem: "Cuando…",
        english: "When he calls me back, I'll explain everything.",
        spanish: "Cuando me devuelva la llamada, le explico todo.",
        situationLabel: "Esperando al casero",
        why: "*Devolver la llamada* came from week 3 and lands here without being taught twice. That's the plan working.",
        wordHints: [
          { en: "he calls me back", es: "me devuelva la llamada" },
          { en: "i'll explain to him", es: "le explico" },
        ],
      },
      {
        id: "d221-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as he answers, I'll tell him it's urgent.",
        spanish: "En cuanto conteste, le digo que es urgente.",
        situationLabel: "Con el teléfono en la mano",
        why: "*Le digo que* — the reported-speech pattern from Otoño, now feeding a future-time chunk.",
        wordHints: [
          { en: "he answers", es: "conteste" },
          { en: "i'll tell him", es: "le digo" },
          { en: "it's urgent", es: "es urgente" },
        ],
      },
      {
        id: "d221-hasta-que",
        frameStem: "Hasta que…",
        english: "I'm going to keep at it until they give me a time.",
        spanish: "Voy a insistir hasta que me den una hora.",
        situationLabel: "Sin colgar",
        why: "*Insistir* without apology. This is a sentence you may need, and it's better learned before the pipes freeze.",
        wordHints: [
          { en: "i'm going to keep at it", es: "voy a insistir" },
          { en: "they give me", es: "me den" },
          { en: "a time", es: "una hora" },
        ],
      },
      {
        id: "d221-antes-de-que",
        frameStem: "Antes de que…",
        english: "I'm calling before the pipes freeze.",
        spanish: "Llamo antes de que se congelen las tuberías.",
        situationLabel: "Diez de la noche, menos ocho grados",
        why: "This is why the chunk exists: the whole point of the sentence is that it hasn't happened and you'd like to keep it that way.",
        wordHints: [
          { en: "i'm calling", es: "llamo" },
          { en: "they freeze", es: "se congelen" },
          { en: "the pipes", es: "las tuberías" },
        ],
      },
      {
        id: "d221-apenas",
        frameStem: "Apenas…",
        english: "The moment he gets back to me, I'll let you know.",
        spanish: "Apenas me responda, te aviso.",
        situationLabel: "Escribiéndole a Camila",
        why: "Two chunks welded together, said without assembling either one. Six weeks ago this was three separate problems.",
        wordHints: [
          { en: "he gets back to me", es: "me responda" },
          { en: "i'll let you know", es: "te aviso" },
        ],
      },
    ],
  },
  {
    day: 222,
    themeEs: "Apenas abran las calles",
    themeEn: "The moment the streets open",
    missionEs: "Habla con un vecino mientras trabajan, sin parar.",
    missionEn: "Talk with a neighbor while you work, without stopping.",
    line: "Media cuadra habla español. Siempre lo hizo.",
    lineEn: "Half the block speaks Spanish. It always did.",
    prompts: [
      {
        id: "d222-cuando",
        frameStem: "Cuando…",
        english: "When I get mine out, I'll help you with yours.",
        spanish: "Cuando saque el mío, te ayudo con el tuyo.",
        situationLabel: "Paleando con el vecino",
        why: "*El mío* / *el tuyo* — mine and yours, both agreeing with *el carro*. No noun needed twice.",
        wordHints: [
          { en: "i get out", es: "saque" },
          { en: "mine", es: "el mío" },
          { en: "i'll help you", es: "te ayudo" },
          { en: "yours", es: "el tuyo" },
        ],
      },
      {
        id: "d222-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as they open the road, I'll go get food.",
        spanish: "En cuanto abran la calle, voy por comida.",
        situationLabel: "Planeando la salida",
        why: "*Ir por* — to go get something. *Ir para* would mean heading toward it instead.",
        wordHints: [
          { en: "they open", es: "abran" },
          { en: "i'll go get", es: "voy por" },
          { en: "food", es: "comida" },
        ],
      },
      {
        id: "d222-hasta-que",
        frameStem: "Hasta que…",
        english: "Nobody goes in until we all finish.",
        spanish: "Nadie entra hasta que terminemos todos.",
        situationLabel: "La regla de la cuadra",
        why: "*Terminemos* — the *we* form. The neighborly version of this whole grammar.",
        wordHints: [
          { en: "nobody goes in", es: "nadie entra" },
          { en: "we finish", es: "terminemos" },
          { en: "all of us", es: "todos" },
        ],
      },
      {
        id: "d222-antes-de-que",
        frameStem: "Antes de que…",
        english: "We have to clear it before it turns to ice.",
        spanish: "Hay que quitarla antes de que se haga hielo.",
        situationLabel: "Contra el reloj",
        why: "*Hacerse hielo*, like *hacerse de noche* yesterday. *Hacerse* is Spanish's verb for turning into something.",
        wordHints: [
          { en: "we have to clear it", es: "hay que quitarla" },
          { en: "it turns to ice", es: "se haga hielo" },
        ],
      },
      {
        id: "d222-apenas",
        frameStem: "Apenas…",
        english: "The moment the streets open, I'm driving to school.",
        spanish: "Apenas abran las calles, manejo al colegio.",
        situationLabel: "Lista para volver",
        why: "Three days of being stuck, one sentence to end it. *Apenas* carries all the impatience.",
        wordHints: [
          { en: "they open", es: "abran" },
          { en: "the streets", es: "las calles" },
          { en: "i'll drive", es: "manejo" },
        ],
      },
    ],
  },
  {
    day: 223,
    themeEs: "Cuando volvamos",
    themeEn: "When we're back",
    missionEs: "Planea una semana entera de recuperación, hablando.",
    missionEn: "Plan a whole catch-up week out loud.",
    line: "Tres días perdidos y todo empieza con \"cuando volvamos\".",
    lineEn: "Three days lost, and everything starts with \"when we're back\".",
    prompts: [
      {
        id: "d223-cuando",
        frameStem: "Cuando…",
        english: "When we're back, we have to make up three days.",
        spanish: "Cuando volvamos, hay que recuperar tres días.",
        situationLabel: "En el grupo del colegio",
        why: "*Recuperar días* is exactly what schools say. No need to build a longer phrase.",
        wordHints: [
          { en: "we're back", es: "volvamos" },
          { en: "we have to", es: "hay que" },
          { en: "make up", es: "recuperar" },
          { en: "three days", es: "tres días" },
        ],
      },
      {
        id: "d223-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as I walk into school, I'll find Rocío.",
        spanish: "En cuanto entre al colegio, busco a Rocío.",
        situationLabel: "El lunes por la mañana",
        why: "*Buscar a* + person — the *a* is required before a person, and it's the thing most learners drop.",
        wordHints: [
          { en: "i walk into", es: "entre a" },
          { en: "the school", es: "el colegio" },
          { en: "i'll find", es: "busco" },
        ],
      },
      {
        id: "d223-hasta-que",
        frameStem: "Hasta que…",
        english: "I'm not changing anything until we're all back.",
        spanish: "No cambio nada hasta que estemos todos.",
        situationLabel: "Sin decidir nada todavía",
        why: "*Estemos* — from *estar*, one of the four or five shifted forms you'll use daily. Learn it as a word.",
        wordHints: [
          { en: "i'm not changing", es: "no cambio" },
          { en: "anything", es: "nada" },
          { en: "we're all here", es: "estemos todos" },
        ],
      },
      {
        id: "d223-antes-de-que",
        frameStem: "Antes de que…",
        english: "I explain the plan before they ask me about it.",
        spanish: "Explico el plan antes de que me lo pregunten.",
        situationLabel: "Con los estudiantes",
        why: "*Me lo pregunten* — two pronouns stacked before the verb, in the order that always feels backwards until it doesn't.",
        wordHints: [
          { en: "i explain", es: "explico" },
          { en: "the plan", es: "el plan" },
          { en: "they ask me about it", es: "me lo pregunten" },
        ],
      },
      {
        id: "d223-apenas",
        frameStem: "Apenas…",
        english: "The moment class starts, they forget about the snow.",
        spanish: "Apenas empiece la clase, se les olvida la nieve.",
        situationLabel: "Lo que ya sabes de tus estudiantes",
        why: "*Se les olvida* — it forgets itself to them. Spanish puts forgetting on the thing forgotten, not on the person.",
        wordHints: [
          { en: "class starts", es: "empiece la clase" },
          { en: "they forget", es: "se les olvida" },
          { en: "the snow", es: "la nieve" },
        ],
      },
    ],
  },
  {
    day: 224,
    themeEs: "Repaso: Cuando llegues…",
    themeEn: "Review: When you arrive…",
    missionEs: "Habla del futuro cinco veces sin pensar en la forma.",
    missionEn: "Talk about the future five times without thinking about the form.",
    line: "Una semana donde nada había pasado todavía.",
    lineEn: "A week in which nothing had happened yet.",
    prompts: [
      {
        id: "d224-cuando",
        frameStem: "Cuando…",
        english: "When spring comes, I'm going to remember this week.",
        spanish: "Cuando llegue la primavera, me voy a acordar de esta semana.",
        situationLabel: "Mirando hacia marzo",
        why: "*Acordarse de* always takes its *de*. Drop it and the sentence limps.",
        wordHints: [
          { en: "spring comes", es: "llegue la primavera" },
          { en: "i'm going to remember", es: "me voy a acordar" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d224-en-cuanto",
        frameStem: "En cuanto…",
        english: "As soon as I have the recording, I'll compare it with January's.",
        spanish: "En cuanto tenga la grabación, la comparo con la de enero.",
        situationLabel: "El experimento de la temporada",
        why: "*La de enero* — January's one. Spanish drops the repeated noun and keeps the article.",
        wordHints: [
          { en: "i have", es: "tenga" },
          { en: "the recording", es: "la grabación" },
          { en: "i'll compare it", es: "la comparo" },
          { en: "january's", es: "la de enero" },
        ],
      },
      {
        id: "d224-hasta-que",
        frameStem: "Hasta que…",
        english: "I'm going to repeat them until they come out by themselves.",
        spanish: "Voy a repetirlas hasta que me salgan solas.",
        situationLabel: "La meta, en una frase",
        why: "The goal named out loud: *hasta que me salgan solas* — until they come out by themselves. That's what a chunk is for.",
        wordHints: [
          { en: "i'm going to repeat them", es: "voy a repetirlas" },
          { en: "they come out for me", es: "me salgan" },
          { en: "by themselves", es: "solas" },
        ],
      },
      {
        id: "d224-antes-de-que",
        frameStem: "Antes de que…",
        english: "I'm writing it down before I forget.",
        spanish: "Lo escribo antes de que se me olvide.",
        situationLabel: "Guardando la semana",
        why: "*Se me olvide* — the same forgetting-happens-to-you shape as Monday's, now in a chunk. Twice in a week is how it sticks.",
        wordHints: [
          { en: "i'm writing it", es: "lo escribo" },
          { en: "i forget", es: "se me olvide" },
        ],
      },
      {
        id: "d224-apenas",
        frameStem: "Apenas…",
        english: "The moment someone says \"cuando puedas\", I know what's coming next.",
        spanish: "Apenas alguien diga \"cuando puedas\", ya sé qué viene después.",
        situationLabel: "Reconociéndolo en la calle",
        why: "Week 4 taught *cuando puedas* as a blind chunk. This week you found out why it was shaped that way.",
        wordHints: [
          { en: "someone says", es: "alguien diga" },
          { en: "i already know", es: "ya sé" },
          { en: "what comes next", es: "qué viene después" },
        ],
      },
    ],
  },
];
