import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 5 — "Quiero que…" (days 211–217). Subjunctive chunk 1: wanting.
 * Each `spanish` is copied verbatim from content/drafts/invierno/week5-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek5SpeakDays: SpeakDay[] = [
  {
    day: 211,
    themeEs: "Lo que quiero de esta noche",
    themeEn: "What I want from this night",
    missionEs: "Di cinco cosas que quieres que pasen.",
    missionEn: "Say five things you want to happen.",
    line: "Cinco frases para pedir. Ninguna tabla que memorizar.",
    lineEn: "Five sentences for asking. No table to memorize.",
    prompts: [
      {
        id: "d211-quiero-que",
        frameStem: "Quiero que…",
        english: "I want the families to talk, not just listen.",
        spanish: "Quiero que las familias hablen, no que solo escuchen.",
        situationLabel: "Planeando con Rocío",
        why: "One shape, all week: opener + *que* + a person + a verb that ends a little differently. Learn the shape, not the table.",
        wordHints: [
          { en: "i want", es: "quiero" },
          { en: "the families", es: "las familias" },
          { en: "to talk", es: "hablen" },
          { en: "only listen", es: "solo escuchen" },
        ],
      },
      {
        id: "d211-necesito-que",
        frameStem: "Necesito que…",
        english: "I need you to confirm the date for me this week.",
        spanish: "Necesito que me confirmes la fecha esta semana.",
        situationLabel: "Pidiéndole a Rocío",
        why: "*Necesito que* is more direct than *quiero que* without being rude — the register you want with colleagues.",
        wordHints: [
          { en: "i need", es: "necesito" },
          { en: "you to confirm for me", es: "me confirmes" },
          { en: "the date", es: "la fecha" },
        ],
      },
      {
        id: "d211-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather it be a Thursday, not a Friday.",
        spanish: "Prefiero que sea un jueves, no un viernes.",
        situationLabel: "Escogiendo el día",
        why: "*Que sea* is one of the two you'll reach for most. Store it as a word, not as a form of *ser*.",
        wordHints: [
          { en: "i'd rather", es: "prefiero" },
          { en: "it be", es: "sea" },
          { en: "a thursday", es: "un jueves" },
        ],
      },
      {
        id: "d211-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I'd love it if nobody felt like a guest.",
        spanish: "Me gustaría que nadie se sintiera de visita.",
        situationLabel: "Lo que de verdad quieres",
        why: "*Me gustaría que* takes a softer, older-sounding verb (*se sintiera*). It's the politest of the five — a wish, not a request.",
        wordHints: [
          { en: "i'd love it if", es: "me gustaría que" },
          { en: "nobody", es: "nadie" },
          { en: "felt", es: "se sintiera" },
          { en: "like a guest", es: "de visita" },
        ],
      },
      {
        id: "d211-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want me to speak first?",
        spanish: "¿Quieres que hable yo primero?",
        situationLabel: "Ofreciéndote",
        why: "The same chunk turned into a question. *¿Quieres que…?* is how you offer help in Spanish — there's no separate \"shall I\".",
        wordHints: [
          { en: "do you want", es: "quieres" },
          { en: "me to speak", es: "que hable yo" },
          { en: "first", es: "primero" },
        ],
      },
    ],
  },
  {
    day: 212,
    themeEs: "Lo que necesito de ti",
    themeEn: "What I need from you",
    missionEs: "Reparte un trabajo entero pidiendo, no mandando.",
    missionEn: "Divide a whole job by asking, not ordering.",
    line: "Pedir bien es la mitad de trabajar con alguien.",
    lineEn: "Asking well is half of working with someone.",
    prompts: [
      {
        id: "d212-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to take the Spanish part and me the English one.",
        spanish: "Quiero que tú lleves la parte en español y yo la de inglés.",
        situationLabel: "Repartiendo el trabajo",
        why: "*Llevar* here means to be in charge of something — the everyday verb for owning a piece of work.",
        wordHints: [
          { en: "you to take", es: "tú lleves" },
          { en: "the part", es: "la parte" },
          { en: "in spanish", es: "en español" },
        ],
      },
      {
        id: "d212-necesito-que",
        frameStem: "Necesito que…",
        english: "I need you to check the flyer before printing it.",
        spanish: "Necesito que revises el volante antes de imprimirlo.",
        situationLabel: "Antes de imprimir",
        why: "*El volante* is a flyer across most of Latin America. *Antes de + infinitive* needs no subjunctive — only *antes de que* does.",
        wordHints: [
          { en: "you to check", es: "revises" },
          { en: "the flyer", es: "el volante" },
          { en: "before printing it", es: "antes de imprimirlo" },
        ],
      },
      {
        id: "d212-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather we split the work in writing.",
        spanish: "Prefiero que dividamos el trabajo por escrito.",
        situationLabel: "Dejándolo claro",
        why: "*Dividamos* — the *we* form. Same chunk, and it turns a request into a proposal.",
        wordHints: [
          { en: "we split", es: "dividamos" },
          { en: "the work", es: "el trabajo" },
          { en: "in writing", es: "por escrito" },
        ],
      },
      {
        id: "d212-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I'd love it if we worked together more often.",
        spanish: "Me gustaría que trabajáramos juntas más seguido.",
        situationLabel: "Diciéndolo de verdad",
        why: "The kind of sentence that changes a working relationship, and it costs one softened verb.",
        wordHints: [
          { en: "we worked", es: "trabajáramos" },
          { en: "together", es: "juntas" },
          { en: "more often", es: "más seguido" },
        ],
      },
      {
        id: "d212-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want me to talk to the principal?",
        spanish: "¿Quieres que yo hable con la directora?",
        situationLabel: "Quitándole un peso",
        why: "Offering to take the hard conversation is the most useful thing this stem does.",
        wordHints: [
          { en: "me to talk", es: "yo hable" },
          { en: "with the principal", es: "con la directora" },
        ],
      },
    ],
  },
  {
    day: 213,
    themeEs: "Prefiero que sea sencillo",
    themeEn: "I'd rather it be simple",
    missionEs: "Corta un plan a la mitad, en voz alta.",
    missionEn: "Cut a plan in half, out loud.",
    line: "La mejor versión es la que cabe en una hora.",
    lineEn: "The best version is the one that fits in an hour.",
    prompts: [
      {
        id: "d213-quiero-que",
        frameStem: "Quiero que…",
        english: "I want us to drop the long presentations.",
        spanish: "Quiero que quitemos las presentaciones largas.",
        situationLabel: "Recortando el plan",
        why: "*Quitemos* — let's take out. The *we* form makes a cut feel joint rather than imposed.",
        wordHints: [
          { en: "we take out", es: "quitemos" },
          { en: "the presentations", es: "las presentaciones" },
          { en: "long", es: "largas" },
        ],
      },
      {
        id: "d213-necesito-que",
        frameStem: "Necesito que…",
        english: "I need it all to fit in one hour.",
        spanish: "Necesito que quepa todo en una hora.",
        situationLabel: "El límite real",
        why: "*Quepa*, from *caber* — to fit. An ugly little form worth owning outright, because you'll want it weekly.",
        wordHints: [
          { en: "it fits", es: "quepa" },
          { en: "everything", es: "todo" },
          { en: "in one hour", es: "en una hora" },
        ],
      },
      {
        id: "d213-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather it be simple and go well.",
        spanish: "Prefiero que sea sencillo y salga bien.",
        situationLabel: "La decisión de la semana",
        why: "Two chunks chained on one *que* — *que sea* and *que salga*. Say it once and both are yours.",
        wordHints: [
          { en: "it be", es: "sea" },
          { en: "simple", es: "sencillo" },
          { en: "it goes well", es: "salga bien" },
        ],
      },
      {
        id: "d213-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I'd love it if it felt like a dinner, not a meeting.",
        spanish: "Me gustaría que se sintiera como una cena, no como una junta.",
        situationLabel: "El tono que buscas",
        why: "*Una junta* is a meeting in most of Latin America — a word you'll use far more than you'd like.",
        wordHints: [
          { en: "it felt", es: "se sintiera" },
          { en: "like a dinner", es: "como una cena" },
          { en: "a meeting", es: "una junta" },
        ],
      },
      {
        id: "d213-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want us to order food or have everyone bring something?",
        spanish: "¿Quieres que pidamos comida o que cada quien traiga algo?",
        situationLabel: "Decidiendo la comida",
        why: "*Cada quien* — each person. The spoken Latin American version of *cada uno*.",
        wordHints: [
          { en: "we order", es: "pidamos" },
          { en: "food", es: "comida" },
          { en: "each person", es: "cada quien" },
          { en: "brings", es: "traiga" },
        ],
      },
    ],
  },
  {
    day: 214,
    themeEs: "Me gustaría que vinieran",
    themeEn: "I'd love it if they came",
    missionEs: "Escribe una invitación entera hablando.",
    missionEn: "Write a whole invitation by speaking it.",
    line: "Una invitación es una lista de deseos con fecha.",
    lineEn: "An invitation is a wish list with a date on it.",
    prompts: [
      {
        id: "d214-quiero-que",
        frameStem: "Quiero que…",
        english: "I want them to know it isn't a complaints meeting.",
        spanish: "Quiero que sepan que no es una reunión de quejas.",
        situationLabel: "Lo primero que deben saber",
        why: "*Que sepan* — that they know. The single most useful thing to say before any school invitation.",
        wordHints: [
          { en: "they know", es: "sepan" },
          { en: "a meeting", es: "una reunión" },
          { en: "of complaints", es: "de quejas" },
        ],
      },
      {
        id: "d214-necesito-que",
        frameStem: "Necesito que…",
        english: "I need you to help me translate the invitation.",
        spanish: "Necesito que me ayudes a traducir la invitación.",
        situationLabel: "Pidiéndole ayuda a Rocío",
        why: "Asking for help in the language you're learning, about the language you're learning. That's the week.",
        wordHints: [
          { en: "you help me", es: "me ayudes" },
          { en: "to translate", es: "a traducir" },
          { en: "the invitation", es: "la invitación" },
        ],
      },
      {
        id: "d214-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather we didn't put the word \"mandatory\" on it.",
        spanish: "Prefiero que no pongamos la palabra \"obligatorio\".",
        situationLabel: "Cuidando el tono",
        why: "*Que no pongamos* — the negative sits before the verb, and nothing else changes.",
        wordHints: [
          { en: "we don't put", es: "no pongamos" },
          { en: "the word", es: "la palabra" },
          { en: "mandatory", es: "obligatorio" },
        ],
      },
      {
        id: "d214-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I'd love it if they came even if they don't speak English.",
        spanish: "Me gustaría que vinieran aunque no hablen inglés.",
        situationLabel: "El corazón de la invitación",
        why: "This is what the whole night is for, in one sentence. Worth being able to say without assembling it.",
        wordHints: [
          { en: "they came", es: "vinieran" },
          { en: "even if", es: "aunque" },
          { en: "they don't speak", es: "no hablen" },
        ],
      },
      {
        id: "d214-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want us to record a voice note inviting them?",
        spanish: "¿Quieres que grabemos un audio invitándolos?",
        situationLabel: "Usando lo de la semana pasada",
        why: "Last week's habit becomes this week's tool — a voice note reaches families that a flyer never will.",
        wordHints: [
          { en: "we record", es: "grabemos" },
          { en: "a voice note", es: "un audio" },
          { en: "inviting them", es: "invitándolos" },
        ],
      },
    ],
  },
  {
    day: 215,
    themeEs: "¿Quieres que te ayude?",
    themeEn: "Do you want me to help?",
    missionEs: "Ofrece ayuda tres veces sin que te la pidan.",
    missionEn: "Offer help three times before being asked.",
    line: "El mismo trozo, apuntando hacia afuera.",
    lineEn: "The same chunk, pointed outward.",
    prompts: [
      {
        id: "d215-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to lean on me, not carry it alone.",
        spanish: "Quiero que te apoyes en mí, no que cargues sola.",
        situationLabel: "Rocío está desbordada",
        why: "*Apoyarse en* — to lean on someone. Physical and emotional at once, exactly like in English.",
        wordHints: [
          { en: "you lean", es: "te apoyes" },
          { en: "on me", es: "en mí" },
          { en: "you carry", es: "cargues" },
          { en: "alone", es: "sola" },
        ],
      },
      {
        id: "d215-necesito-que",
        frameStem: "Necesito que…",
        english: "I need you to let me know if you're short on time.",
        spanish: "Necesito que me avises si te falta tiempo.",
        situationLabel: "Poniendo la puerta abierta",
        why: "*Avisar* — to give a heads-up. Week 2's grievance becomes week 5's kindness.",
        wordHints: [
          { en: "you let me know", es: "me avises" },
          { en: "you're short on", es: "te falta" },
          { en: "time", es: "tiempo" },
        ],
      },
      {
        id: "d215-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather we change the plan than have it go badly.",
        spanish: "Prefiero que cambiemos el plan a que salga mal.",
        situationLabel: "Dándole permiso de cambiar",
        why: "*Prefiero que X a que Y* — I'd rather X than Y. Both halves take the same chunk.",
        wordHints: [
          { en: "we change", es: "cambiemos" },
          { en: "the plan", es: "el plan" },
          { en: "than it going badly", es: "a que salga mal" },
        ],
      },
      {
        id: "d215-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I'd love it if you learned to ask for help without apologizing.",
        spanish: "Me gustaría que aprendieras a pedir ayuda sin disculparte.",
        situationLabel: "El consejo que tú necesitabas",
        why: "Marlana giving Rocío the advice she spent all of week 1 needing. Notice who's the teacher now.",
        wordHints: [
          { en: "you learned", es: "aprendieras" },
          { en: "to ask for help", es: "a pedir ayuda" },
          { en: "without apologizing", es: "sin disculparte" },
        ],
      },
      {
        id: "d215-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want me to help you with the translations?",
        spanish: "¿Quieres que te ayude con las traducciones?",
        situationLabel: "La oferta directa",
        why: "The plainest possible offer of help in Spanish. Five words, no hedging needed.",
        wordHints: [
          { en: "i help you", es: "te ayude" },
          { en: "with the translations", es: "con las traducciones" },
        ],
      },
    ],
  },
  {
    day: 216,
    themeEs: "La noche",
    themeEn: "The night",
    missionEs: "Cuenta cómo salió, entero, sin volver al inglés.",
    missionEn: "Tell how it went, all of it, without going back to English.",
    line: "Cuarenta personas, tres idiomas, y tú hablando español toda la noche.",
    lineEn: "Forty people, three languages, and you speaking Spanish all evening.",
    prompts: [
      {
        id: "d216-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to know it went better than we thought.",
        spanish: "Quiero que sepas que salió mejor de lo que pensábamos.",
        situationLabel: "El primer mensaje a Camila",
        why: "*Salir* for how something turned out — *salió bien*, *salió mal*. Nothing to do with leaving.",
        wordHints: [
          { en: "you know", es: "sepas" },
          { en: "it turned out", es: "salió" },
          { en: "better than", es: "mejor de lo que" },
          { en: "we thought", es: "pensábamos" },
        ],
      },
      {
        id: "d216-necesito-que",
        frameStem: "Necesito que…",
        english: "I need you to believe me: I spoke Spanish all evening.",
        spanish: "Necesito que me creas: hablé toda la noche en español.",
        situationLabel: "Lo que no te crees ni tú",
        why: "Six months ago this sentence would have been the unbelievable part. Now the unbelievable part is that it's ordinary.",
        wordHints: [
          { en: "you believe me", es: "me creas" },
          { en: "i spoke", es: "hablé" },
          { en: "all evening", es: "toda la noche" },
        ],
      },
      {
        id: "d216-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather Rocío told it — she tells it better.",
        spanish: "Prefiero que lo cuente Rocío, que lo dice mejor.",
        situationLabel: "Cediéndole el crédito",
        why: "The subject can follow the verb: *que lo cuente Rocío*. Spanish moves the person to the end for emphasis.",
        wordHints: [
          { en: "rocío tells it", es: "lo cuente rocío" },
          { en: "she says it", es: "lo dice" },
          { en: "better", es: "mejor" },
        ],
      },
      {
        id: "d216-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I wish you'd been there.",
        spanish: "Me gustaría que hubieras estado ahí.",
        situationLabel: "Lo que le dices a Camila",
        why: "*Me gustaría que hubieras estado* is a wish about the past — I wish you'd been there. One phrase, and it comes up constantly.",
        wordHints: [
          { en: "you had been", es: "hubieras estado" },
          { en: "there", es: "ahí" },
        ],
      },
      {
        id: "d216-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want me to send you the voice note I recorded at the end?",
        spanish: "¿Quieres que te mande el audio que grabé al final?",
        situationLabel: "Compartiendo la noche",
        why: "Week 4's habit, week 5's chunk, one sentence. That's what a season looks like when it's working.",
        wordHints: [
          { en: "i send you", es: "te mande" },
          { en: "the voice note", es: "el audio" },
          { en: "i recorded", es: "grabé" },
          { en: "at the end", es: "al final" },
        ],
      },
    ],
  },
  {
    day: 217,
    themeEs: "Repaso: Quiero que…",
    themeEn: "Review: I want you to…",
    missionEs: "Pide cinco cosas seguidas, sin pensar en la forma.",
    missionEn: "Ask for five things in a row, without thinking about the form.",
    line: "Una semana entera pidiendo, y nadie mencionó el subjuntivo.",
    lineEn: "A whole week of asking, and nobody mentioned the subjunctive.",
    prompts: [
      {
        id: "d217-quiero-que",
        frameStem: "Quiero que…",
        english: "I want you to tell me if you notice the change.",
        spanish: "Quiero que me digas si notas el cambio.",
        situationLabel: "El repaso del jueves",
        why: "*Que me digas* is probably the single most-used chunk in this whole family. It'll be automatic by March.",
        wordHints: [
          { en: "you tell me", es: "me digas" },
          { en: "you notice", es: "notas" },
          { en: "the change", es: "el cambio" },
        ],
      },
      {
        id: "d217-necesito-que",
        frameStem: "Necesito que…",
        english: "I need you to explain to me why this doesn't feel hard anymore.",
        spanish: "Necesito que me expliques por qué esto ya no me cuesta.",
        situationLabel: "La pregunta honesta",
        why: "*Costar* for difficulty — *me cuesta* means it's hard for me, nothing to do with price.",
        wordHints: [
          { en: "you explain to me", es: "me expliques" },
          { en: "this", es: "esto" },
          { en: "isn't hard for me anymore", es: "ya no me cuesta" },
        ],
      },
      {
        id: "d217-prefiero-que",
        frameStem: "Prefiero que…",
        english: "I'd rather we kept going with phrases and not rules.",
        spanish: "Prefiero que sigamos con frases y no con reglas.",
        situationLabel: "Cómo quieres aprender",
        why: "This is the method, stated by the person it worked on. No table appeared once this week.",
        wordHints: [
          { en: "we keep going", es: "sigamos" },
          { en: "with phrases", es: "con frases" },
          { en: "rules", es: "reglas" },
        ],
      },
      {
        id: "d217-me-gustaria-que",
        frameStem: "Me gustaría que…",
        english: "I wish someone had taught me this way earlier.",
        spanish: "Me gustaría que alguien me hubiera enseñado esto así antes.",
        situationLabel: "Mirando atrás",
        why: "The same past-wish shape as Tuesday's. Two uses in one week is how a chunk stops being a lesson.",
        wordHints: [
          { en: "someone", es: "alguien" },
          { en: "had taught me", es: "me hubiera enseñado" },
          { en: "this way", es: "esto así" },
        ],
      },
      {
        id: "d217-quieres-que",
        frameStem: "¿Quieres que…?",
        english: "Do you want me to count how many times I used the subjunctive?",
        spanish: "¿Quieres que cuente cuántas veces usé el subjuntivo?",
        situationLabel: "La broma del final",
        why: "The joke only lands because you did it all week without noticing. That was the point.",
        wordHints: [
          { en: "i count", es: "cuente" },
          { en: "how many times", es: "cuántas veces" },
          { en: "i used", es: "usé" },
        ],
      },
    ],
  },
];
