import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 2 — "Muletillas II" (days 190–196).
 * Each `spanish` is copied verbatim from content/drafts/invierno/week2-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek2SpeakDays: SpeakDay[] = [
  {
    day: 190,
    themeEs: "Las muletillas de Camila",
    themeEn: "Camila's fillers",
    missionEs: "Usa las cinco muletillas nuevas en cinco frases.",
    missionEn: "Use the five new fillers in five sentences.",
    line: "Las muletillas largas dan más tiempo que las cortas.",
    lineEn: "Long fillers buy more time than short ones.",
    prompts: [
      {
        id: "d190-fijate-que",
        frameStem: "Fíjate que…",
        english: "Look — I studied alone for years too.",
        spanish: "Fíjate que yo también estudié sola muchos años.",
        situationLabel: "Camila comparte su lista",
        why: "*Fíjate que* asks the other person to lean in — a filler that also frames what's coming as worth hearing.",
        wordHints: [
          { en: "i too", es: "yo también" },
          { en: "i studied", es: "estudié" },
          { en: "alone", es: "sola" },
          { en: "for years", es: "muchos años" },
        ],
      },
      {
        id: "d190-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, your favorite filler is more useful to me than mine.",
        spanish: "La verdad es que tu muletilla favorita me sirve más que la mía.",
        situationLabel: "Comparando listas",
        why: "Five syllables of runway before the content has to arrive — that's the whole job of *la verdad es que*.",
        wordHints: [
          { en: "your", es: "tu" },
          { en: "filler", es: "muletilla" },
          { en: "is useful to me", es: "me sirve" },
          { en: "than mine", es: "que la mía" },
        ],
      },
      {
        id: "d190-digo",
        frameStem: "Digo…",
        english: "I mean, it's not a rule, it's a habit.",
        spanish: "Digo, no es una regla, es una costumbre.",
        situationLabel: "Precisando la idea",
        why: "*Digo* is the surgical version of *o sea*: one word out, one word in, sentence continues.",
        wordHints: [
          { en: "a rule", es: "una regla" },
          { en: "a habit", es: "una costumbre" },
        ],
      },
      {
        id: "d190-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? It's like breathing before you speak.",
        spanish: "¿Me entiendes? Es como respirar antes de hablar.",
        situationLabel: "Explicando para qué sirven",
        why: "Ask it, then keep going. *¿Me entiendes?* hands Camila a moment to nod without giving up your turn.",
        wordHints: [
          { en: "it's like", es: "es como" },
          { en: "breathing", es: "respirar" },
          { en: "before speaking", es: "antes de hablar" },
        ],
      },
      {
        id: "d190-total-que",
        frameStem: "En fin…",
        english: "Anyway, now I've got five new words.",
        spanish: "En fin, ya tengo cinco palabras nuevas.",
        situationLabel: "Cerrando la sesión",
        why: "*En fin,* is the exit door from a long story. Say it and everyone knows the ending has started.",
        wordHints: [
          { en: "now i have", es: "ya tengo" },
          { en: "five words", es: "cinco palabras" },
          { en: "new", es: "nuevas" },
        ],
      },
    ],
  },
  {
    day: 191,
    themeEs: "La mejor hora de la semana",
    themeEn: "The best hour of the week",
    missionEs: "Di algo verdadero, no algo cortés.",
    missionEn: "Say something true, not something polite.",
    line: "Las muletillas también sirven para decir lo difícil.",
    lineEn: "Fillers are also for saying the hard thing.",
    prompts: [
      {
        id: "d191-fijate-que",
        frameStem: "Fíjate que…",
        english: "You know, I wait for Thursday all week.",
        spanish: "Fíjate que espero el jueves toda la semana.",
        situationLabel: "Confesión de jueves",
        why: "The filler softens a sentence that would otherwise feel too direct to say out loud.",
        wordHints: [
          { en: "i wait for", es: "espero" },
          { en: "thursday", es: "el jueves" },
          { en: "all week", es: "toda la semana" },
        ],
      },
      {
        id: "d191-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, this hour is the best one of my week.",
        spanish: "La verdad es que esta hora es la mejor de mi semana.",
        situationLabel: "Diciéndolo en voz alta",
        why: "Worth being able to say the real thing in Spanish, not just the safe thing.",
        wordHints: [
          { en: "this hour", es: "esta hora" },
          { en: "the best", es: "la mejor" },
          { en: "of my week", es: "de mi semana" },
        ],
      },
      {
        id: "d191-digo",
        frameStem: "Digo…",
        english: "I mean, it's not just the Spanish, it's talking to someone.",
        spanish: "Digo, no es solo el español, es hablar con alguien.",
        situationLabel: "Corrigiendo la razón",
        why: "*Digo* lets you upgrade a half-true sentence into the true one without starting over.",
        wordHints: [
          { en: "not just", es: "no es solo" },
          { en: "talking", es: "hablar" },
          { en: "to someone", es: "con alguien" },
        ],
      },
      {
        id: "d191-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? With my students I'm the strong one.",
        spanish: "¿Me entiendes? Con mis estudiantes soy la fuerte.",
        situationLabel: "Por qué importa este café",
        why: "*La fuerte* — the strong one. Spanish lets an adjective stand alone as a role you're playing.",
        wordHints: [
          { en: "with my students", es: "con mis estudiantes" },
          { en: "i'm", es: "soy" },
          { en: "the strong one", es: "la fuerte" },
        ],
      },
      {
        id: "d191-total-que",
        frameStem: "En fin…",
        english: "Anyway, Thursday turned into my favorite day.",
        spanish: "En fin, el jueves se volvió mi día favorito.",
        situationLabel: "El resumen honesto",
        why: "*Volverse* is the change that happened to you rather than one you chose — exactly right here.",
        wordHints: [
          { en: "turned into", es: "se volvió" },
          { en: "my day", es: "mi día" },
          { en: "favorite", es: "favorito" },
        ],
      },
    ],
  },
  {
    day: 192,
    themeEs: "Enfermera, no enfermero",
    themeEn: "Nurse, not nurse",
    missionEs: "Equivócate y corrígete sin parar la frase.",
    missionEn: "Make a mistake and fix it without stopping the sentence.",
    line: "Una palabra basta para arreglar la frase entera.",
    lineEn: "One word is enough to fix the whole sentence.",
    prompts: [
      {
        id: "d192-fijate-que",
        frameStem: "Fíjate que…",
        english: "You know, in English I don't have to think about gender.",
        spanish: "Fíjate que en inglés no tengo que pensar en el género.",
        situationLabel: "Después del error",
        why: "Naming why an error happens is more useful than being embarrassed by it.",
        wordHints: [
          { en: "in english", es: "en inglés" },
          { en: "i don't have to", es: "no tengo que" },
          { en: "think about", es: "pensar en" },
          { en: "gender", es: "el género" },
        ],
      },
      {
        id: "d192-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, I think about it after I've already said it.",
        spanish: "La verdad es que lo pienso después de decirlo.",
        situationLabel: "El error de siempre",
        why: "*Después de + infinitive* — after doing something. Compact, and no conjugation needed.",
        wordHints: [
          { en: "i think about it", es: "lo pienso" },
          { en: "after", es: "después de" },
          { en: "saying it", es: "decirlo" },
        ],
      },
      {
        id: "d192-digo",
        frameStem: "Digo…",
        english: "I mean — nurse, feminine, not masculine.",
        spanish: "Digo, enfermera, no enfermero.",
        situationLabel: "La corrección de una palabra",
        why: "This is the whole point of *digo*: you don't restart the sentence, you swap the one wrong word and carry on.",
        wordHints: [
          { en: "nurse", es: "enfermera" },
        ],
      },
      {
        id: "d192-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? I fix it so I don't repeat it.",
        spanish: "¿Me entiendes? Lo corrijo para no repetirlo.",
        situationLabel: "Por qué te corriges",
        why: "*Para no + infinitive* — so as not to. The cleanest way to state a purpose in the negative.",
        wordHints: [
          { en: "i fix it", es: "lo corrijo" },
          { en: "so as not to", es: "para no" },
          { en: "repeat it", es: "repetirlo" },
        ],
      },
      {
        id: "d192-total-que",
        frameStem: "En fin…",
        english: "Anyway, I correct myself without cutting off the conversation.",
        spanish: "En fin, corrijo sin cortar la conversación.",
        situationLabel: "Lo que cambió",
        why: "The old habit was stopping to apologize. The new one is a single word mid-flight.",
        wordHints: [
          { en: "i correct myself", es: "corrijo" },
          { en: "without cutting off", es: "sin cortar" },
          { en: "the conversation", es: "la conversación" },
        ],
      },
    ],
  },
  {
    day: 193,
    themeEs: "El salón vacío",
    themeEn: "The empty classroom",
    missionEs: "Cuenta un problema del trabajo y comprueba que te siguen.",
    missionEn: "Tell a work problem and check they're following you.",
    line: "Una frase que se apaga suena perdida. Pregunta en vez de apagarte.",
    lineEn: "A sentence that fades sounds lost. Ask instead of fading.",
    prompts: [
      {
        id: "d193-fijate-que",
        frameStem: "Fíjate que…",
        english: "Look — they changed the schedule without telling us.",
        spanish: "Fíjate que cambiaron el horario sin avisarnos.",
        situationLabel: "Contando el lío del lunes",
        why: "*Sin avisarnos* — without warning us. One phrase carries the whole grievance.",
        wordHints: [
          { en: "they changed", es: "cambiaron" },
          { en: "the schedule", es: "el horario" },
          { en: "without telling us", es: "sin avisarnos" },
        ],
      },
      {
        id: "d193-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, it bothered me more than I let on.",
        spanish: "La verdad es que me molestó más de lo que mostré.",
        situationLabel: "Lo que no dijiste en el colegio",
        why: "*Más de lo que* + verb — more than what I did. A comparison against your own behavior.",
        wordHints: [
          { en: "it bothered me", es: "me molestó" },
          { en: "more than", es: "más de lo que" },
          { en: "i let on", es: "mostré" },
        ],
      },
      {
        id: "d193-digo",
        frameStem: "Digo…",
        english: "I mean, I didn't complain — I reported it.",
        spanish: "Digo, no me quejé, lo reporté.",
        situationLabel: "Precisando lo que hiciste",
        why: "The distinction matters to you, so it's worth the *digo* to get it right.",
        wordHints: [
          { en: "i didn't complain", es: "no me quejé" },
          { en: "i reported it", es: "lo reporté" },
        ],
      },
      {
        id: "d193-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? The problem wasn't the change.",
        spanish: "¿Me entiendes? El problema no era el cambio.",
        situationLabel: "Llegando al punto",
        why: "Checking in beats trailing off — a fading sentence sounds lost, this one sounds like someone still driving.",
        wordHints: [
          { en: "the problem", es: "el problema" },
          { en: "wasn't", es: "no era" },
          { en: "the change", es: "el cambio" },
        ],
      },
      {
        id: "d193-total-que",
        frameStem: "En fin…",
        english: "Anyway, we ended up teaching the class in the library.",
        spanish: "En fin, dimos la clase en la biblioteca.",
        situationLabel: "Cómo terminó",
        why: "*Dar la clase* is what teachers actually say — not *enseñar la clase*.",
        wordHints: [
          { en: "we taught", es: "dimos" },
          { en: "the class", es: "la clase" },
          { en: "in the library", es: "en la biblioteca" },
        ],
      },
    ],
  },
  {
    day: 194,
    themeEs: "Dos horas para nada",
    themeEn: "Two hours for nothing",
    missionEs: "Cuenta una historia larga y aterriza el final.",
    missionEn: "Tell a long story and land the ending.",
    line: "Una historia puede ser larga si el final es limpio.",
    lineEn: "A story can be long if the landing is clean.",
    prompts: [
      {
        id: "d194-fijate-que",
        frameStem: "Fíjate que…",
        english: "Look — the meeting lasted two hours for nothing.",
        spanish: "Fíjate que la reunión duró dos horas para nada.",
        situationLabel: "La reunión del jueves",
        why: "*Para nada* at the end of a sentence means \"for nothing at all\" — it does the complaining for you.",
        wordHints: [
          { en: "the meeting", es: "la reunión" },
          { en: "lasted", es: "duró" },
          { en: "two hours", es: "dos horas" },
          { en: "for nothing", es: "para nada" },
        ],
      },
      {
        id: "d194-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, these meetings could be an email.",
        spanish: "La verdad es que estas reuniones podrían ser un correo.",
        situationLabel: "La opinión sincera",
        why: "*Podrían ser* — could be. The conditional lets you complain without accusing anyone.",
        wordHints: [
          { en: "these meetings", es: "estas reuniones" },
          { en: "could be", es: "podrían ser" },
          { en: "an email", es: "un correo" },
        ],
      },
      {
        id: "d194-digo",
        frameStem: "Digo…",
        english: "I mean, two and a half hours, to be exact.",
        spanish: "Digo, dos horas y media, para ser exacta.",
        situationLabel: "Ajustando el dato",
        why: "*Para ser exacta* agrees in the feminine — Marlana correcting her own number.",
        wordHints: [
          { en: "two and a half hours", es: "dos horas y media" },
          { en: "to be exact", es: "para ser exacta" },
        ],
      },
      {
        id: "d194-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? Nobody wanted to speak first.",
        spanish: "¿Me entiendes? Nadie quería hablar primero.",
        situationLabel: "Por qué no avanzó",
        why: "The imperfect *quería* describes the whole room's mood, not one moment.",
        wordHints: [
          { en: "nobody", es: "nadie" },
          { en: "wanted", es: "quería" },
          { en: "to speak first", es: "hablar primero" },
        ],
      },
      {
        id: "d194-total-que",
        frameStem: "En fin…",
        english: "Anyway, I left there with more questions than I walked in with.",
        spanish: "En fin, salí de ahí con más preguntas que al entrar.",
        situationLabel: "El aterrizaje",
        why: "A long story can be long if the landing is clean. This is the landing.",
        wordHints: [
          { en: "i left", es: "salí" },
          { en: "from there", es: "de ahí" },
          { en: "more questions", es: "más preguntas" },
          { en: "than when i went in", es: "que al entrar" },
        ],
      },
    ],
  },
  {
    day: 195,
    themeEs: "Escuchar en voz alta",
    themeEn: "Listening out loud",
    missionEs: "Acompaña a quien habla con la voz, no con el silencio.",
    missionEn: "Keep the speaker company with your voice, not your silence.",
    line: "En español, quien escucha también hace ruido.",
    lineEn: "In Spanish, the listener makes noise too.",
    prompts: [
      {
        id: "d195-fijate-que",
        frameStem: "Fíjate que…",
        english: "You know, when I'm quiet I look bored and I'm not.",
        spanish: "Fíjate que yo callada parezco aburrida y no lo estoy.",
        situationLabel: "Lo que notó Camila",
        why: "Spanish conversation expects noise from the listener — *ajá · claro · ya · exacto*. Silence reads as absence, not respect.",
        wordHints: [
          { en: "quiet", es: "callada" },
          { en: "i look", es: "parezco" },
          { en: "bored", es: "aburrida" },
          { en: "i'm not", es: "no lo estoy" },
        ],
      },
      {
        id: "d195-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, a well-timed \"ajá\" changes everything.",
        spanish: "La verdad es que un \"ajá\" a tiempo cambia todo.",
        situationLabel: "La lección del día",
        why: "*A tiempo* — on time, at the right moment. The timing is the whole skill.",
        wordHints: [
          { en: "on time", es: "a tiempo" },
          { en: "changes", es: "cambia" },
          { en: "everything", es: "todo" },
        ],
      },
      {
        id: "d195-digo",
        frameStem: "Digo…",
        english: "I mean, I was following you — I was just quiet.",
        spanish: "Digo, sí te seguía, solo estaba en silencio.",
        situationLabel: "Aclarando el malentendido",
        why: "That *sí* before the verb is emphasis: I *was* following. It contradicts without arguing.",
        wordHints: [
          { en: "i was following you", es: "te seguía" },
          { en: "only", es: "solo" },
          { en: "in silence", es: "en silencio" },
        ],
      },
      {
        id: "d195-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? But you can't know that.",
        spanish: "¿Me entiendes? Pero tú no puedes saberlo.",
        situationLabel: "El problema del silencio",
        why: "The point of listener noises in one sentence: what you feel is invisible unless you make a sound.",
        wordHints: [
          { en: "but", es: "pero" },
          { en: "you can't", es: "no puedes" },
          { en: "know it", es: "saberlo" },
        ],
      },
      {
        id: "d195-total-que",
        frameStem: "En fin…",
        english: "Anyway, I'm going to say \"claro\" and \"exacto\" more often.",
        spanish: "En fin, voy a decir \"claro\" y \"exacto\" más seguido.",
        situationLabel: "El nuevo hábito",
        why: "*Más seguido* is the everyday Latin American way to say \"more often\".",
        wordHints: [
          { en: "i'm going to say", es: "voy a decir" },
          { en: "more often", es: "más seguido" },
        ],
      },
    ],
  },
  {
    day: 196,
    themeEs: "Repaso: Muletillas II",
    themeEn: "Review: Fillers II",
    missionEs: "Diez muletillas en una charla, sin contarlas.",
    missionEn: "Ten fillers in one conversation, without counting them.",
    line: "Cinco para pensar y cinco para acompañar.",
    lineEn: "Five to think with, five to keep company with.",
    prompts: [
      {
        id: "d196-fijate-que",
        frameStem: "Fíjate que…",
        english: "Look — I don't count them anymore, they just come out.",
        spanish: "Fíjate que ya no las cuento, me salen solas.",
        situationLabel: "El repaso de la semana",
        why: "*Me salen solas* — they come out by themselves. The exact moment something stops being studied and starts being yours.",
        wordHints: [
          { en: "i don't count them", es: "no las cuento" },
          { en: "they come out", es: "me salen" },
          { en: "by themselves", es: "solas" },
        ],
      },
      {
        id: "d196-la-verdad",
        frameStem: "La verdad es que…",
        english: "Honestly, I sound like someone having a conversation, not translating one.",
        spanish: "La verdad es que sueno como alguien que conversa, no que traduce.",
        situationLabel: "El balance de dos semanas",
        why: "The whole aim of the season, in one sentence you can now say out loud.",
        wordHints: [
          { en: "i sound like", es: "sueno como" },
          { en: "someone who", es: "alguien que" },
          { en: "converses", es: "conversa" },
          { en: "translates", es: "traduce" },
        ],
      },
      {
        id: "d196-digo",
        frameStem: "Digo…",
        english: "I mean, not ten words — ten tools.",
        spanish: "Digo, no diez palabras, diez herramientas.",
        situationLabel: "Reformulando el logro",
        why: "A *digo* used to sharpen a point, not to fix an error — its other job.",
        wordHints: [
          { en: "ten words", es: "diez palabras" },
          { en: "tools", es: "herramientas" },
        ],
      },
      {
        id: "d196-me-entiendes",
        frameStem: "¿Me entiendes?",
        english: "You know what I mean? I'm not hunting for the perfect word anymore.",
        spanish: "¿Me entiendes? Ya no busco la palabra perfecta.",
        situationLabel: "Lo que de verdad cambió",
        why: "*Ya no* + verb — not anymore. The compact way to mark a habit you've dropped.",
        wordHints: [
          { en: "not anymore", es: "ya no" },
          { en: "i look for", es: "busco" },
          { en: "the perfect word", es: "la palabra perfecta" },
        ],
      },
      {
        id: "d196-total-que",
        frameStem: "En fin…",
        english: "Anyway, next up is the phone.",
        spanish: "En fin, la próxima toca el teléfono.",
        situationLabel: "Lo que viene",
        why: "*Tocar* here means \"it's the turn of\" — *la próxima toca X* is how you announce what's next.",
        wordHints: [
          { en: "next time", es: "la próxima" },
          { en: "it's the turn of", es: "toca" },
          { en: "the phone", es: "el teléfono" },
        ],
      },
    ],
  },
];
