import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 13 — "El invierno entero" (days 267–273). The season capstone.
 * The last Thursday of winter: the January recording played next to the March
 * one, Yesenia at the café, and one long conversation that uses the whole
 * season at once. Day 273 is the last day of Temporada 3.
 */
export const invWeek13ReadingDays: ReadingDay[] = [
  {
    day: 267,
    themeEs: "La última semana",
    storyTitle: "El invierno entero",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "acabarse", en: "to come to an end", example: "Se acaba el invierno." },
      { es: "pasarle por encima a alguien", en: "to wash over someone", example: "Que esta semana no se me pase por encima." },
      { es: "lo de enero", en: "the January business", example: "Quiero que oigas lo de enero." },
      { es: "desde el principio", en: "from the very start", example: "Tú me oíste desde el principio." },
      { es: "volver atrás", en: "to go back", example: "Ya no vuelvo atrás." },
    ],
    dialogue: {
      title: "Quedan siete días",
      situation: "Lunes; Marlana se da cuenta de qué semana es",
      lines: [
        { speaker: "A", es: "Camila, ¿sabes qué? Quedan siete días de invierno.", en: "Camila, do you know what? There are seven days of winter left." },
        { speaker: "B", es: "Ya lo había contado. ¿Y cómo te sientes?", en: "I'd already counted. And how do you feel?" },
        { speaker: "A", es: "Pues, se acaba el invierno y ni lo sentí pasar. Empecé esto en enero sin creérmelo.", en: "Well, winter's ending and I didn't feel it go by. I started this in January without believing it." },
        { speaker: "B", es: "Yo sí me lo creía. Desde la tercera semana.", en: "I believed it. From the third week." },
        { speaker: "A", es: "Perdona que te interrumpa, pero esto no puede esperar al jueves. Quiero que oigas lo de enero conmigo.", en: "Sorry to interrupt, but this can't wait until Thursday. I want you to hear the January one with me." },
        { speaker: "B", es: "¿El primer audio? ¿Lo guardaste?", en: "The first recording? You kept it?" },
        { speaker: "A", es: "Me dijiste que lo guardara. Está ahí desde el día doscientos cuatro.", en: "You told me to keep it. It's been there since day two hundred and four." },
        { speaker: "B", es: "Entonces el jueves lo oímos. ¿Y tú qué opinas de cómo salió el invierno?", en: "Then we'll listen to it Thursday. And what do you think about how the winter turned out?" },
        { speaker: "A", es: "Más o menos entendí que el invierno no era de gramática. Era de dejar de frenar.", en: "I more or less got that winter wasn't about grammar. It was about not braking." },
      ],
    },
  },
  {
    day: 268,
    themeEs: "El audio de enero",
    storyTitle: "El invierno entero",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la pausa", en: "the pause", example: "Once segundos y tres pausas." },
      { es: "pedir permiso", en: "to ask permission", example: "La de enero estaba pidiendo permiso." },
      { es: "consentir", en: "to humor someone", example: "Dime qué opinas, sin consentirme." },
      { es: "sonar a alguien", en: "to sound like someone", example: "Ya no me suena a mí." },
      { es: "comparar", en: "to compare", example: "Comparamos los dos audios seguidos." },
    ],
    dialogue: {
      title: "Once segundos",
      situation: "Jueves; suenan los dos audios uno detrás del otro",
      lines: [
        { speaker: "A", es: "Pues, aquí está: once segundos y tres pausas. Quiero que lo oigas sin que te diga nada antes.", en: "Well, here it is: eleven seconds and three pauses. I want you to hear it without me saying anything first." },
        { speaker: "B", es: "Dale.", en: "Go on." },
        { speaker: "A", es: "Perdona que te interrumpa, para el audio un segundo. ¿De verdad sonaba así?", en: "Sorry to interrupt, stop the recording a second. Did I really sound like that?" },
        { speaker: "B", es: "Sonabas así. Y ahora pon el de esta semana.", en: "You sounded like that. Now play this week's." },
        { speaker: "A", es: "…", en: "…" },
        { speaker: "B", es: "¿Ves la diferencia? No es el acento. Es que en enero pedías permiso para cada frase.", en: "Do you see the difference? It isn't the accent. It's that in January you asked permission for every sentence." },
        { speaker: "A", es: "Más o menos entendí que la de enero estaba pidiendo permiso. Se disculpaba dos veces en once segundos.", en: "I more or less got that the January one was asking permission. She apologized twice in eleven seconds." },
        { speaker: "B", es: "Dos veces. Las conté yo también.", en: "Twice. I counted them too." },
        { speaker: "A", es: "¿Y tú qué opinas, sin consentirme? ¿Qué cambió más, el ritmo o la cara?", en: "And what do you think, without humoring me? What changed more, the rhythm or the face?" },
      ],
    },
  },
  {
    day: 269,
    themeEs: "Lo que cambió",
    storyTitle: "El invierno entero",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el talento", en: "talent", example: "No fue talento, fueron días seguidos." },
      { es: "seguidos", en: "in a row", example: "Noventa y un días seguidos." },
      { es: "repetirse", en: "to be repeatable", example: "Quiero que el método se pueda repetir." },
      { es: "el don", en: "the gift, the knack", example: "Si lo llamas don, nadie lo copia." },
      { es: "el trozo", en: "the chunk", example: "Los trozos se pegan y las reglas no." },
    ],
    dialogue: {
      title: "No fue talento",
      situation: "Camila intenta hacerle un cumplido y Marlana lo corrige",
      lines: [
        { speaker: "B", es: "Es que tú tienes facilidad, Marlana. Se te da.", en: "The thing is you have a knack, Marlana. It comes easily to you." },
        { speaker: "A", es: "Perdona que te interrumpa, pero no fue talento. Fueron noventa y un días seguidos.", en: "Sorry to interrupt, but it wasn't talent. It was ninety-one days in a row." },
        { speaker: "B", es: "Bueno, las dos cosas.", en: "Well, both things." },
        { speaker: "A", es: "No. Y no lo digo por modestia. Si lo llamas don, nadie lo copia.", en: "No. And I'm not saying it out of modesty. If you call it a gift, nobody copies it." },
        { speaker: "B", es: "Ah. Ahí tienes razón.", en: "Ah. There you're right." },
        { speaker: "A", es: "Pues, lo que cambió no fue el vocabulario. Sé casi las mismas palabras de enero.", en: "Well, what changed wasn't the vocabulary. I know almost the same words as January." },
        { speaker: "B", es: "¿Entonces qué?", en: "So what was it?" },
        { speaker: "A", es: "Más o menos entendí que lo que sirve es hablar todos los días, poquito. Las tablas nunca hicieron nada.", en: "I more or less got that what works is speaking every day, a little. The tables never did anything." },
        { speaker: "B", es: "Y algo más, que tú no dices: hacía falta alguien al otro lado.", en: "And something else you're not saying: there had to be someone on the other end." },
      ],
    },
  },
  {
    day: 270,
    themeEs: "Yesenia en el café",
    storyTitle: "El invierno entero",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la culpable", en: "the one to blame (affectionate)", example: "Camila es la culpable de todo." },
      { es: "la pena", en: "embarrassment, shyness", example: "No te preocupa el idioma, te preocupa la pena." },
      { es: "dar permiso", en: "to give permission", example: "Necesitas que alguien te dé permiso." },
      { es: "el intercambio", en: "the language exchange", example: "Así empezó todo: un intercambio los jueves." },
      { es: "exagerar", en: "to exaggerate", example: "Exageras, no era tan malo." },
    ],
    dialogue: {
      title: "Ahora somos cuatro",
      situation: "Marlana lleva a Yesenia al café; Camila y Rocío ya están ahí",
      lines: [
        { speaker: "A", es: "Pues, Yesenia, esta es Camila, la culpable de todo. Y a Rocío ya la conoces.", en: "Well, Yesenia, this is Camila, the one responsible for all of it. And you already know Rocío." },
        { speaker: "B", es: "Mucho gusto. Marlana me habló de usted.", en: "Nice to meet you. Marlana told me about you." },
        { speaker: "A", es: "De tú, Camila, que aquí nadie es de usted. Quiero que Camila te cuente cómo hablaba yo en enero.", en: "It's tú, Camila, nobody's usted here. I want Camila to tell you how I spoke in January." },
        { speaker: "B", es: "Ay, no era para tanto—", en: "Oh, it wasn't that bad—" },
        { speaker: "A", es: "Perdona que te interrumpa: sí era tan malo. Quiero que sepas que yo también me disculpaba once veces por hora.", en: "Sorry to interrupt: it really was that bad. I want you to know I apologized eleven times an hour too." },
        { speaker: "B", es: "¿Usted? Pero si habla perfecto.", en: "You? But you speak perfectly." },
        { speaker: "A", es: "Hablo entendible, que es otra cosa. Y hace catorce semanas no decía ni una frase entera.", en: "I speak understandably, which is different. And fourteen weeks ago I couldn't say one full sentence." },
        { speaker: "B", es: "Yo llevo ocho meses sin decir una en inglés.", en: "I've gone eight months without saying one in English." },
        { speaker: "A", es: "Más o menos entendí que no te preocupa el inglés, te preocupa la pena. ¿Y tú qué opinas, Yesenia? Llevas media hora oyéndonos.", en: "I more or less got that it isn't the English that worries you, it's the embarrassment. And what do you think, Yesenia? You've been listening to us for half an hour." },
      ],
    },
  },
  {
    day: 271,
    themeEs: "Una charla de ida y vuelta",
    storyTitle: "El invierno entero",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "de ida y vuelta", en: "back-and-forth", example: "Una charla de ida y vuelta, por fin." },
      { es: "de golpe", en: "all at once", example: "Oíste todo el invierno de golpe." },
      { es: "irse por las ramas", en: "to go off on tangents", example: "Párenme si me voy por las ramas." },
      { es: "meterse", en: "to jump in", example: "Ahí sí tengo que meterme." },
      { es: "quedarse con algo", en: "to take something away", example: "Quiero que se queden con una cosa." },
    ],
    dialogue: {
      title: "Dos horas",
      situation: "La charla larga: cuatro personas, un idioma, ninguna traducción",
      lines: [
        { speaker: "A", es: "Pues, te cuento cómo fue de verdad. Mira, empezó fatal y terminó bien.", en: "Well, let me tell you how it really went. Look, it started terribly and ended well." },
        { speaker: "B", es: "Empieza por enero.", en: "Start from January." },
        { speaker: "A", es: "Quiero que me dejen llegar al final antes de opinar. Son dos horas de historia, aviso.", en: "I want you to let me get to the end before weighing in. It's two hours of story, fair warning." },
        { speaker: "B", es: "Tenemos toda la tarde.", en: "We have all afternoon." },
        { speaker: "B", es: "…y ahí fue cuando Marlana llamó al casero y le habló diez minutos en español—", en: "…and that was when Marlana called the landlord and talked to him for ten minutes in Spanish—" },
        { speaker: "A", es: "Perdona que te interrumpa, falta la mitad de esa historia. Se cortó cinco veces.", en: "Sorry to interrupt, half of that story is missing. It dropped five times." },
        { speaker: "B", es: "Cinco veces, y volviste a llamar cinco veces. Esa es la historia.", en: "Five times, and you called back five times. That's the story." },
        { speaker: "A", es: "¿Y tú qué opinas, ahora que oíste todo el invierno de golpe? Llevo hablando media hora.", en: "And what do you think, now that you've heard the whole winter at once? I've been talking half an hour." },
        { speaker: "B", es: "Que lo difícil viene ahora. Sonar natural ya lo tienes; ahora falta sonar como tú.", en: "That the hard part comes now. Sounding natural you've got; now you need to sound like you." },
      ],
    },
  },
  {
    day: 272,
    themeEs: "Lo que viene",
    storyTitle: "El invierno entero",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "la personalidad", en: "personality", example: "La primavera es de personalidad." },
      { es: "graciosa", en: "funny", example: "En inglés soy graciosa." },
      { es: "la broma", en: "the joke", example: "Quiero que me salga una broma sin planearla." },
      { es: "medir", en: "to measure", example: "Lo que viene es más difícil de medir." },
      { es: "sin rodeos", en: "without beating around the bush", example: "Me falta decir que no sin rodeos." },
    ],
    dialogue: {
      title: "Sonar como yo",
      situation: "Planeando la primavera sin planear demasiado",
      lines: [
        { speaker: "B", es: "Bueno. ¿Qué te falta? Dilo en una frase.", en: "All right. What are you missing? Say it in one sentence." },
        { speaker: "A", es: "Pues, me falta el humor. En inglés soy graciosa y en español soy correcta.", en: "Well, I'm missing my humor. In English I'm funny and in Spanish I'm correct." },
        { speaker: "B", es: "Correcta es aburrido.", en: "Correct is boring." },
        { speaker: "A", es: "Exacto. Quiero que la primavera sea de personalidad, no de técnica. Quiero que me salga una broma sin planearla.", en: "Exactly. I want spring to be about personality, not technique. I want a joke to come out without me planning it." },
        { speaker: "B", es: "Entonces hay que hacer un plan distinto, con más—", en: "Then we need a different plan, with more—" },
        { speaker: "A", es: "Perdona que te interrumpa: no hagamos un plan enorme. Lo pequeño es lo que funcionó.", en: "Sorry to interrupt: let's not make a huge plan. The small version is what worked." },
        { speaker: "B", es: "Tienes razón. Cinco frases al día y los jueves.", en: "You're right. Five sentences a day and Thursdays." },
        { speaker: "A", es: "Eso. ¿Y tú qué opinas que me falta de verdad? Aparte del humor.", en: "That's it. And what do you think I'm really missing? Apart from the humor." },
        { speaker: "B", es: "Discutir. Cuando alguien te lleva la contraria, todavía te encoges un poco.", en: "Arguing. When someone contradicts you, you still shrink a little." },
      ],
    },
  },
  {
    day: 273,
    themeEs: "Repaso: El invierno entero",
    isRecap: true,
    vocab: [
      { es: "el hábito", en: "the habit", example: "Hablar es un hábito, no un talento." },
      { es: "sin proponérselo", en: "without meaning to", example: "Camila hizo esto sin proponérselo." },
      { es: "y ya está", en: "and that's it", example: "Gracias, y ya está." },
      { es: "quitársele a alguien", en: "to go away from someone", example: "Esto ya no se me quita." },
      { es: "la temporada", en: "the season", example: "Última pregunta de la temporada." },
    ],
    dialogue: {
      title: "Día noventa y uno",
      situation: "El último día del invierno; las cuatro en el café",
      lines: [
        { speaker: "B", es: "Bueno. Día noventa y uno. ¿Alguien quiere decir algo antes de que se acabe?", en: "All right. Day ninety-one. Does anyone want to say something before it ends?" },
        { speaker: "A", es: "Pues, día noventa y uno, y sigo aquí. La palabra con la que empecé sigue siendo la primera que digo.", en: "Well, day ninety-one, and I'm still here. The word I started with is still the first one I say." },
        { speaker: "B", es: "\"Pues\".", en: "\"Pues\"." },
        { speaker: "A", es: "Pues. Perdona que te interrumpa una última vez este invierno: gracias, y ya está.", en: "Pues. Sorry to interrupt one last time this winter: thank you, and that's it." },
        { speaker: "B", es: "No hice nada. Vine a tomar café los jueves.", en: "I didn't do anything. I came for coffee on Thursdays." },
        { speaker: "A", es: "Quiero que Camila sepa lo que hizo sin proponérselo. Y quiero que el año siga igual de sencillo: hablar todos los días.", en: "I want Camila to know what she did without meaning to. And I want the year to stay this simple: speak every day." },
        { speaker: "B", es: "Eso sí lo firmo. ¿Y qué te llevas del invierno, en una frase?", en: "That I'll sign up to. And what do you take from the winter, in one sentence?" },
        { speaker: "A", es: "Más o menos entendí que hablar es un hábito, no un talento. Y que noventa y un días cambian a una persona.", en: "I more or less got that speaking is a habit, not a talent. And that ninety-one days change a person." },
        { speaker: "A", es: "¿Y tú qué opinas? Última pregunta del invierno. Y ahora sí, escucho.", en: "And what do you think? Last question of the winter. And now, I'm listening." },
      ],
    },
  },
];
