import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 6 — "La tormenta" (days 218–224).
 * A Boston snowstorm shuts the school for three days. Everything anyone says
 * all week hangs on when something else happens — which is future-time
 * subjunctive, arriving as weather rather than as grammar.
 */
export const invWeek6ReadingDays: ReadingDay[] = [
  {
    day: 218,
    themeEs: "Cuando pare la nieve",
    storyTitle: "La tormenta",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la tormenta", en: "the storm", example: "No salgo hasta que pase la tormenta." },
      { es: "nevar", en: "to snow", example: "En cuanto empiece a nevar, cierran las escuelas." },
      { es: "la pala", en: "the shovel", example: "Traigan la pala antes de que oscurezca." },
      { es: "la máquina quitanieve", en: "the snowplow", example: "Estamos encerrados hasta que llegue la máquina quitanieve." },
      { es: "oscurecer", en: "to get dark", example: "Hay que terminar antes de que oscurezca." },
    ],
    dialogue: {
      title: "Viene el jueves",
      situation: "Miércoles por la tarde, audio de Camila desde el hospital",
      lines: [
        { speaker: "B", es: "Marlana, ¿viste el pronóstico? Dicen dos pies para mañana.", en: "Marlana, did you see the forecast? They're saying two feet for tomorrow." },
        { speaker: "A", es: "Lo vi. En cuanto empiece a nevar, cierran las escuelas. Siempre es así.", en: "I saw it. As soon as it starts snowing, they close the schools. It's always like that." },
        { speaker: "B", es: "Yo no. El hospital no cierra nunca. Me toca turno igual.", en: "Not me. The hospital never closes. I've got my shift regardless." },
        { speaker: "A", es: "Es verdad. Bueno, cuando llegue a casa, te mando un audio.", en: "That's true. Okay, when I get home, I'll send you a voice note." },
        { speaker: "B", es: "Hazlo. ¿Y tienes comida?", en: "Do that. And do you have food?" },
        { speaker: "A", es: "Hay que comprar algo antes de que cierren las tiendas. Voy saliendo ahorita.", en: "I need to buy something before the stores close. I'm heading out right now." },
        { speaker: "B", es: "Ve. Y no salgas después. Quédate hasta que pase la tormenta.", en: "Go. And don't go out afterward. Stay in until the storm passes." },
        { speaker: "A", es: "No pienso salir. Apenas salga el sol, esto se convierte en hielo y ahí es peor.", en: "I don't plan to. The moment the sun's out, this turns to ice and that's worse." },
        { speaker: "B", es: "Exacto. Apenas pueda, te llamo desde el hospital.", en: "Exactly. The moment I can, I'll call you from the hospital." },
      ],
    },
  },
  {
    day: 219,
    themeEs: "En cuanto cancelen",
    storyTitle: "La tormenta",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el cierre", en: "the closure", example: "Cuando anuncien el cierre, aviso a las familias." },
      { es: "cancelar", en: "to cancel", example: "En cuanto cancelen, mando el mensaje." },
      { es: "enterarse", en: "to find out", example: "En cuanto me entere, te escribo." },
      { es: "la incertidumbre", en: "the uncertainty", example: "Se acaba la incertidumbre cuando lo anuncian." },
      { es: "confirmarse", en: "to be confirmed", example: "Los papás no organizan nada hasta que se confirme." },
    ],
    dialogue: {
      title: "Las cinco de la mañana",
      situation: "Rocío y Marlana, por audio, sin poder dormir",
      lines: [
        { speaker: "B", es: "Marlana, son las once y todavía no dicen nada. ¿Tú crees que cancelen?", en: "Marlana, it's eleven and they still haven't said anything. Do you think they'll cancel?" },
        { speaker: "A", es: "Seguro. Pero no lo van a decir hasta que sean las cinco. Siempre a las cinco.", en: "Definitely. But they won't say it until five o'clock. Always at five." },
        { speaker: "B", es: "Entonces no me duermo. Necesito saber si preparo la clase o no.", en: "Then I'm not sleeping. I need to know whether to prepare the class or not." },
        { speaker: "A", es: "No prepares nada hasta que digan algo. En serio, duérmete.", en: "Don't prepare anything until they say something. Seriously, go to sleep." },
        { speaker: "B", es: "¿Y las familias?", en: "And the families?" },
        { speaker: "A", es: "Voy a escribirles antes de que me pregunten. Ya tengo el mensaje listo, en los dos idiomas.", en: "I'm going to write to them before they ask me. I've already got the message ready, in both languages." },
        { speaker: "B", es: "Qué organizada. ¿Y lo mandas ya?", en: "So organized. And you'll send it now?" },
        { speaker: "A", es: "No. En cuanto cancelen, mando el mensaje al grupo. Apenas lo confirmen, te aviso a ti también.", en: "No. As soon as they cancel, I'll send the message to the group. The moment they confirm it, I'll let you know too." },
        { speaker: "B", es: "Perfecto. Cuando suene el teléfono a las cinco, ya sabemos qué es.", en: "Perfect. When the phone rings at five, we'll already know what it is." },
      ],
    },
  },
  {
    day: 220,
    themeEs: "Hasta que pase la tormenta",
    storyTitle: "La tormenta",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la luz", en: "the electricity, the power", example: "Cuando vuelva la luz, pongo café." },
      { es: "encerrada", en: "shut in, stuck indoors", example: "Vamos a estar encerrados dos días." },
      { es: "echar sal", en: "to put salt down", example: "Hay que echar sal antes de que se haga de noche." },
      { es: "hacerse de noche", en: "for night to fall", example: "Se hace de noche a las cuatro y media." },
      { es: "resbaloso", en: "slippery", example: "Apenas pegue el sol se pone resbaloso." },
    ],
    dialogue: {
      title: "Dos pies afuera",
      situation: "Jueves. Sin luz desde las nueve de la mañana",
      lines: [
        { speaker: "A", es: "Camila, se fue la luz. Estoy con una vela y el celular al cuarenta por ciento.", en: "Camila, the power's out. I'm here with a candle and my phone at forty percent." },
        { speaker: "B", es: "Ay, no. ¿Tienes frío?", en: "Oh no. Are you cold?" },
        { speaker: "A", es: "Todavía no. Cuando vuelva la luz, pongo café. Es lo único que quiero.", en: "Not yet. When the power comes back, I'll put coffee on. It's the only thing I want." },
        { speaker: "B", es: "¿Y afuera cómo está?", en: "And how is it outside?" },
        { speaker: "A", es: "No se ve nada. No me muevo de aquí hasta que pase la tormenta. Nadie maneja hasta que digan que es seguro.", en: "You can't see a thing. I'm not moving from here until the storm passes. Nobody drives until they say it's safe." },
        { speaker: "B", es: "Bien. Pero échale sal a la escalera antes de que se haga de noche, ¿sí?", en: "Good. But put salt on the steps before it gets dark, okay?" },
        { speaker: "A", es: "Ahorita lo hago. En cuanto limpien la calle, salgo a caminar, aunque sea diez minutos.", en: "I'll do it in a minute. As soon as they clear the street, I'll go out for a walk, even ten minutes." },
        { speaker: "B", es: "Apenas pase la máquina, avísame. Y muévete el carro.", en: "The moment the plow goes by, let me know. And move your car." },
        { speaker: "A", es: "Apenas pase la máquina, movemos el carro. Mi vecino ya me lo dijo tres veces.", en: "The moment the plow goes by, we'll move the car. My neighbor's already told me three times." },
      ],
    },
  },
  {
    day: 221,
    themeEs: "Antes de que se congelen las tuberías",
    storyTitle: "La tormenta",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "las tuberías", en: "the pipes", example: "Llamo antes de que se congelen las tuberías." },
      { es: "el casero", en: "the landlord", example: "El casero no me devuelve la llamada." },
      { es: "gotear", en: "to drip", example: "Le muestro dónde gotea." },
      { es: "insistir", en: "to keep at it, to insist", example: "Voy a insistir hasta que me den una hora." },
      { es: "tibia", en: "lukewarm", example: "Dejo el agua corriendo hasta que salga tibia." },
    ],
    dialogue: {
      title: "Diez de la noche, menos ocho grados",
      situation: "Marlana llama al casero y le cuenta a Camila entre llamadas",
      lines: [
        { speaker: "A", es: "Camila, el agua sale helada y hay un ruido raro en la pared. Llamo antes de que se congelen las tuberías.", en: "Camila, the water's coming out freezing and there's a strange noise in the wall. I'm calling before the pipes freeze." },
        { speaker: "B", es: "Llama ya. ¿Sabes qué decirle?", en: "Call now. Do you know what to say to him?" },
        { speaker: "A", es: "Creo que sí. En cuanto conteste, le digo que es urgente. Y cuando me devuelva la llamada, le explico todo.", en: "I think so. As soon as he answers, I'll tell him it's urgent. And when he calls me back, I'll explain everything." },
        { speaker: "B", es: "Y no cuelgues sin una hora concreta.", en: "And don't hang up without a specific time." },
        { speaker: "A", es: "No. Voy a insistir hasta que me den una hora. No me quedo tranquila hasta que venga alguien.", en: "No. I'm going to keep at it until they give me a time. I won't relax until someone comes." },
        { speaker: "B", es: "Mientras tanto, deja el agua corriendo un poquito. Eso ayuda.", en: "In the meantime, leave the water running a little. That helps." },
        { speaker: "A", es: "Ya lo hice. Dejo el agua corriendo hasta que salga tibia.", en: "Already did. I'm leaving the water running until it runs warm." },
        { speaker: "B", es: "Perfecto. Y todo esto en español, ¿no? Ni una palabra en inglés.", en: "Perfect. And all of this in Spanish, right? Not a word in English." },
        { speaker: "A", es: "Ni una. Apenas me responda, te aviso. Quiero resolverlo antes de que llegue el fin de semana.", en: "Not one. The moment he gets back to me, I'll let you know. I want it sorted before the weekend comes." },
      ],
    },
  },
  {
    day: 222,
    themeEs: "Apenas abran las calles",
    storyTitle: "La tormenta",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "palear", en: "to shovel", example: "Palear hasta que se me congelen las manos." },
      { es: "la banqueta", en: "the sidewalk", example: "Seguimos hasta que quede libre la banqueta." },
      { es: "sacar el carro", en: "to get the car out", example: "Cuando saque el mío, te ayudo con el tuyo." },
      { es: "entrar en calor", en: "to warm up", example: "Apenas entre en calor, sigo." },
      { es: "la cuadra", en: "the block", example: "Media cuadra salió a palear." },
    ],
    dialogue: {
      title: "Media cuadra hablando español",
      situation: "Sábado por la mañana, todos afuera con palas",
      lines: [
        { speaker: "B", es: "Buenos días, vecina. ¿Le ayudo con la entrada?", en: "Good morning, neighbor. Shall I help you with the driveway?" },
        { speaker: "A", es: "¡Buenos días! Cuando saque el mío, te ayudo con el tuyo, ¿te parece?", en: "Good morning! When I get mine out, I'll help you with yours, sound good?" },
        { speaker: "B", es: "Trato hecho. Hay que quitarla antes de que se haga hielo, esa es la clave.", en: "Deal. We have to clear it before it turns to ice, that's the key." },
        { speaker: "A", es: "Eso mismo me dijo mi mamá por teléfono desde Atlanta, y ella nunca vio nieve.", en: "That's exactly what my mother told me on the phone from Atlanta, and she's never seen snow." },
        { speaker: "B", es: "Las mamás saben. ¿Y usted hablaba español? Llevo dos años aquí y nunca supe.", en: "Mothers know. And you speak Spanish? I've been here two years and I never knew." },
        { speaker: "A", es: "Estoy aprendiendo. Bueno — aprendiendo desde hace mucho, hablando desde hace poco.", en: "I'm learning. Well — learning for a long time, speaking for a short time." },
        { speaker: "B", es: "Pues se le entiende todo. Seguimos hasta que quede libre la banqueta y ya.", en: "Well, you're perfectly understandable. Let's keep going until the sidewalk's clear and that's it." },
        { speaker: "A", es: "Nadie entra hasta que terminemos todos. Y apenas haya café, invito a todos.", en: "Nobody goes in until we all finish. And the moment there's coffee, I'm inviting everyone." },
        { speaker: "B", es: "Ahí sí que terminamos rápido.", en: "Now that'll get us done fast." },
      ],
    },
  },
  {
    day: 223,
    themeEs: "Cuando volvamos",
    storyTitle: "La tormenta",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "recuperar días", en: "to make up days", example: "Cuando volvamos, hay que recuperar tres días." },
      { es: "ponerse al día", en: "to catch up", example: "Seguimos igual hasta que nos pongamos al día." },
      { es: "el calendario", en: "the calendar, the schedule", example: "No prometo fechas hasta que salga el calendario nuevo." },
      { es: "olvidársele a alguien", en: "for someone to forget", example: "Apenas empiece la clase, se les olvida la nieve." },
      { es: "quedarse donde", en: "to leave off where", example: "Empezamos donde quedamos." },
    ],
    dialogue: {
      title: "Tres días perdidos",
      situation: "Domingo, planeando la vuelta con Rocío",
      lines: [
        { speaker: "B", es: "Mañana volvemos. ¿Y los tres días que perdimos?", en: "We're back tomorrow. What about the three days we lost?" },
        { speaker: "A", es: "Cuando volvamos, hay que recuperar tres días. Pero no cambio nada hasta que estemos todos.", en: "When we're back, we have to make up three days. But I'm not changing anything until we're all there." },
        { speaker: "B", es: "Va a faltar gente. Siempre falta alguien la semana después de una tormenta.", en: "People will be missing. Someone's always missing the week after a storm." },
        { speaker: "A", es: "Por eso. Seguimos con lo mismo hasta que nos pongamos al día.", en: "Exactly. We'll stay on the same thing until we catch up." },
        { speaker: "B", es: "¿Y les explicas el plan a los estudiantes?", en: "And will you explain the plan to the students?" },
        { speaker: "A", es: "Explico el plan antes de que me lo pregunten. Y en cuanto entre al colegio, te busco a ti.", en: "I explain the plan before they ask me about it. And as soon as I walk into school, I'll find you." },
        { speaker: "B", es: "Aquí estaré. ¿Y lo de marzo?", en: "I'll be here. And the March thing?" },
        { speaker: "A", es: "En cuanto tengamos un rato, planeamos lo de marzo. Pero no prometo fechas hasta que salga el calendario nuevo.", en: "As soon as we have a moment, we'll plan the March thing. But I won't promise dates until the new calendar comes out." },
        { speaker: "B", es: "Sabia. Y apenas empiece la clase, a los chicos se les olvida la nieve. Ya verás.", en: "Wise. And the moment class starts, the kids forget about the snow. You'll see." },
      ],
    },
  },
  {
    day: 224,
    themeEs: "Repaso: Cuando llegues…",
    isRecap: true,
    vocab: [
      { es: "salir solas", en: "to come out by themselves", example: "Repito hasta que me salgan solas." },
      { es: "fijarse en", en: "to focus on, to notice", example: "Practico hasta que deje de fijarme en la forma." },
      { es: "la grabación", en: "the recording", example: "Comparo la grabación con la de enero." },
      { es: "reconocer", en: "to recognize", example: "Apenas la oiga, la voy a reconocer." },
      { es: "armar una frase", en: "to build a sentence", example: "Contesto sin armar la frase." },
    ],
    dialogue: {
      title: "Nada había pasado todavía",
      situation: "Jueves, de vuelta en el café, con la nieve derritiéndose afuera",
      lines: [
        { speaker: "B", es: "Volvimos al café. ¿Sabes qué semana acabas de tener?", en: "We're back at the café. Do you know what kind of week you just had?" },
        { speaker: "A", es: "Una semana en la que nada había pasado todavía. Todo era \"cuando\", \"hasta que\", \"antes de que\".", en: "A week in which nothing had happened yet. It was all \"when\", \"until\", \"before\"." },
        { speaker: "B", es: "Exacto. Y por eso lo aprendiste. No por la regla, por la nieve.", en: "Exactly. And that's why you learned it. Not because of the rule, because of the snow." },
        { speaker: "A", es: "Cuando llegue la primavera, me voy a acordar de esta semana. Le hablé al casero, al vecino, a Rocío, a ti.", en: "When spring comes, I'm going to remember this week. I talked to the landlord, the neighbor, Rocío, you." },
        { speaker: "B", es: "En español todo. ¿Y ahora qué?", en: "All in Spanish. And now what?" },
        { speaker: "A", es: "Voy a repetirlas hasta que me salgan solas. Practico hasta que deje de fijarme en la forma.", en: "I'm going to repeat them until they come out by themselves. I'll practice until I stop noticing the form." },
        { speaker: "B", es: "Ya casi. Fíjate: apenas alguien dice \"cuando puedas\", tú ya sabes qué viene después.", en: "Almost there. Look: the moment someone says \"cuando puedas\", you already know what comes next." },
        { speaker: "A", es: "Es verdad. Eso lo aprendí hace dos semanas sin saber por qué era así.", en: "That's true. I learned that two weeks ago without knowing why it was shaped that way." },
        { speaker: "B", es: "Y ahora lo sabes. En fin, ya llevas dos de cuatro semanas de subjuntivo. La próxima: ojalá.", en: "And now you know. So in the end, that's two of four subjunctive weeks. Next up: ojalá." },
      ],
    },
  },
];
