import type { SpeakDay } from "../../prompts/types";

/**
 * Invierno Week 11 — "Sin captar todo" (days 253–259). The gist toolkit.
 * Each `spanish` is copied verbatim from content/drafts/invierno/week11-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const invWeek11SpeakDays: SpeakDay[] = [
  {
    day: 253,
    themeEs: "Quitar los subtítulos",
    themeEn: "Turning the subtitles off",
    missionEs: "Cuenta algo que entendiste a medias, sin disculparte.",
    missionEn: "Describe something you half-understood, without apologizing.",
    line: "A los doce minutos buscaste el control. No lo apretaste.",
    lineEn: "Twelve minutes in you reached for the remote. You didn't press it.",
    prompts: [
      {
        id: "d253-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that they're fighting over the house.",
        spanish: "Más o menos entendí que se están peleando por la casa.",
        situationLabel: "Primer capítulo sin subtítulos",
        why: "*Más o menos* is not an apology. It's an accurate report of how much of any conversation anyone catches, in any language.",
        wordHints: [
          { en: "i more or less got", es: "más o menos entendí" },
          { en: "they're fighting", es: "se están peleando" },
          { en: "over the house", es: "por la casa" },
        ],
      },
      {
        id: "d253-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was that she's leaving on Sunday.",
        spanish: "Lo que sí entendí fue que ella se va el domingo.",
        situationLabel: "Lo que sí quedó claro",
        why: "Counting what landed instead of what didn't. Same scene, completely different feeling about it.",
        wordHints: [
          { en: "what i did catch", es: "lo que sí entendí" },
          { en: "she's leaving", es: "se va" },
          { en: "on sunday", es: "el domingo" },
        ],
      },
      {
        id: "d253-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say they're siblings?",
        spanish: "¿Dijiste que son hermanos?",
        situationLabel: "Comprobando con Camila",
        why: "Guess out loud and let someone confirm. It's faster than rewinding and it keeps you in the conversation.",
        wordHints: [
          { en: "did you say", es: "dijiste" },
          { en: "they are", es: "son" },
          { en: "siblings", es: "hermanos" },
        ],
      },
      {
        id: "d253-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "I missed the part about the phone call.",
        spanish: "Se me escapó la parte de la llamada.",
        situationLabel: "Nombrando el hueco",
        why: "Naming the gap precisely gets you a two-sentence answer. Saying \"no entendí\" gets you the whole scene again.",
        wordHints: [
          { en: "i missed", es: "se me escapó" },
          { en: "the part about", es: "la parte de" },
          { en: "the phone call", es: "la llamada" },
        ],
      },
      {
        id: "d253-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather that she's the mother.",
        spanish: "Por el contexto entiendo que es la mamá.",
        situationLabel: "Deduciendo sin traducir",
        why: "This is what fluent listeners do constantly and never mention. Most of comprehension is inference, not vocabulary.",
        wordHints: [
          { en: "from the context", es: "por el contexto" },
          { en: "i gather", es: "entiendo" },
          { en: "she's the mother", es: "es la mamá" },
        ],
      },
    ],
  },
  {
    day: 254,
    themeEs: "Más o menos entendí",
    themeEn: "I more or less got it",
    missionEs: "Cuenta un capítulo entero con lo que captaste.",
    missionEn: "Retell a whole episode from what you caught.",
    line: "Seguiste un capítulo entero con el sesenta por ciento de las palabras.",
    lineEn: "You followed a whole episode on sixty percent of the words.",
    prompts: [
      {
        id: "d254-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that she forgave him in the end.",
        spanish: "Más o menos entendí que lo perdonó al final.",
        situationLabel: "El giro del capítulo",
        why: "Following a plot turn without subtitles means you're processing meaning, not decoding words. That's a different activity.",
        wordHints: [
          { en: "she forgave him", es: "lo perdonó" },
          { en: "in the end", es: "al final" },
        ],
      },
      {
        id: "d254-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was the joke, and I laughed on time.",
        spanish: "Lo que sí entendí fue el chiste, y me reí a tiempo.",
        situationLabel: "La prueba de verdad",
        why: "Laughing at the right moment is a comprehension test you can't fake and can't study for. You passed it.",
        wordHints: [
          { en: "the joke", es: "el chiste" },
          { en: "i laughed", es: "me reí" },
          { en: "on time", es: "a tiempo" },
        ],
      },
      {
        id: "d254-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say \"finca\"? What's a finca?",
        spanish: "¿Dijiste \"finca\"? ¿Qué es una finca?",
        situationLabel: "Una palabra nueva",
        why: "Asking about one word mid-episode costs three seconds. Guessing wrong for four scenes costs the plot.",
        wordHints: [
          { en: "did you say", es: "dijiste" },
          { en: "what is", es: "qué es" },
        ],
      },
      {
        id: "d254-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "I missed the part where they both talk at once.",
        spanish: "Se me escapó la parte de cuando hablan los dos a la vez.",
        situationLabel: "Voces encimadas",
        why: "Overlapping voices are hard in your first language too. Worth remembering before you blame your Spanish.",
        wordHints: [
          { en: "when they talk", es: "cuando hablan" },
          { en: "both of them", es: "los dos" },
          { en: "at once", es: "a la vez" },
        ],
      },
      {
        id: "d254-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather that the news was bad.",
        spanish: "Por el contexto entiendo que la noticia era mala.",
        situationLabel: "Leyendo la cara, no las palabras",
        why: "Faces, music, and what everyone does next carry more information than the dialogue. Use all of it.",
        wordHints: [
          { en: "the news", es: "la noticia" },
          { en: "was bad", es: "era mala" },
        ],
      },
    ],
  },
  {
    day: 255,
    themeEs: "Lo que sí entendí",
    themeEn: "What I did catch",
    missionEs: "Ayuda a alguien sin haber entendido todo lo que dijo.",
    missionEn: "Help someone without having understood everything they said.",
    line: "Deja de contar los huecos. Cuenta lo que llegó.",
    lineEn: "Stop counting the holes. Count what landed.",
    prompts: [
      {
        id: "d255-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got what she needed.",
        spanish: "Más o menos entendí lo que necesitaba.",
        situationLabel: "Una mamá hablando rápido",
        why: "In a hallway conversation, more or less is the whole job. Nobody needs a transcript.",
        wordHints: [
          { en: "what she needed", es: "lo que necesitaba" },
        ],
      },
      {
        id: "d255-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was that she needs the form by Friday.",
        spanish: "Lo que sí entendí fue que necesita el papel para el viernes.",
        situationLabel: "Lo único que cambia lo que haces",
        why: "You only ever need the part that changes what you do. The rest is decoration, in any language.",
        wordHints: [
          { en: "she needs", es: "necesita" },
          { en: "the form", es: "el papel" },
          { en: "by friday", es: "para el viernes" },
        ],
      },
      {
        id: "d255-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say it was for Friday?",
        spanish: "¿Dijiste que era para el viernes?",
        situationLabel: "Repitiéndoselo de vuelta",
        why: "Repeating a guess back is the single most useful listening move there is. It's also what interpreters do all day.",
        wordHints: [
          { en: "it was", es: "era" },
          { en: "for friday", es: "para el viernes" },
        ],
      },
      {
        id: "d255-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "I missed the part about why she needs it.",
        spanish: "Se me escapó la parte de por qué lo necesita.",
        situationLabel: "Pidiendo solo lo que falta",
        why: "Precision is a kindness to the other person. \"Which part?\" is the question you've saved them from asking.",
        wordHints: [
          { en: "why", es: "por qué" },
          { en: "she needs it", es: "lo necesita" },
        ],
      },
      {
        id: "d255-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather they sent her from one office to another.",
        spanish: "Por el contexto entiendo que la mandaron de una oficina a otra.",
        situationLabel: "Leyendo la situación entera",
        why: "You've worked in schools long enough to read this without any Spanish at all. Use what you already know.",
        wordHints: [
          { en: "they sent her", es: "la mandaron" },
          { en: "from one office", es: "de una oficina" },
          { en: "to another", es: "a otra" },
        ],
      },
    ],
  },
  {
    day: 256,
    themeEs: "¿Dijiste que…?",
    themeEn: "Did you say that…?",
    missionEs: "Adivina en voz alta cinco veces.",
    missionEn: "Guess out loud five times.",
    line: "Adivinar mal cuesta cuatro segundos. Callarse cuesta la conversación.",
    lineEn: "A wrong guess costs four seconds. Silence costs the conversation.",
    prompts: [
      {
        id: "d256-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that they were talking about migration.",
        spanish: "Más o menos entendí que hablaban de la migración.",
        situationLabel: "Un pódcast en el metro",
        why: "A podcast is harder than television — no faces, no context. Getting the topic is already a win.",
        wordHints: [
          { en: "they were talking", es: "hablaban" },
          { en: "about migration", es: "de la migración" },
        ],
      },
      {
        id: "d256-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was the story about the woman from Cúcuta.",
        spanish: "Lo que sí entendí fue la historia de la señora de Cúcuta.",
        situationLabel: "La parte que se quedó contigo",
        why: "Stories stick when statistics don't, in every language. That's not a comprehension problem.",
        wordHints: [
          { en: "the story", es: "la historia" },
          { en: "the woman", es: "la señora" },
          { en: "from cúcuta", es: "de cúcuta" },
        ],
      },
      {
        id: "d256-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say \"desplazados\"? I heard that word three times.",
        spanish: "¿Dijiste \"desplazados\"? Esa palabra la oí tres veces.",
        situationLabel: "Cazando una palabra repetida",
        why: "A word you hear three times is worth asking about. That's your brain already telling you it matters.",
        wordHints: [
          { en: "that word", es: "esa palabra" },
          { en: "i heard it", es: "la oí" },
          { en: "three times", es: "tres veces" },
        ],
      },
      {
        id: "d256-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "I missed the part with the numbers.",
        spanish: "Se me escapó la parte de los números.",
        situationLabel: "Los datos siempre se van",
        why: "Numbers are the first thing to go in a second language and the last thing to come back. Everyone's the same here.",
        wordHints: [
          { en: "the numbers", es: "los números" },
        ],
      },
      {
        id: "d256-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather that \"desplazados\" means people who had to leave.",
        spanish: "Por el contexto entiendo que \"desplazados\" es gente que tuvo que irse.",
        situationLabel: "Deduciendo la palabra",
        why: "Working out a word from its neighbors, mid-listen, without stopping. That's the skill this whole week is for.",
        wordHints: [
          { en: "is people", es: "es gente" },
          { en: "who had to", es: "que tuvo que" },
          { en: "leave", es: "irse" },
        ],
      },
    ],
  },
  {
    day: 257,
    themeEs: "Se me escapó la parte de",
    themeEn: "I missed the part about",
    missionEs: "Pide exactamente lo que te falta, ni más ni menos.",
    missionEn: "Ask for exactly what you're missing, no more and no less.",
    line: "Nombra el hueco y te dan dos frases. Di \"no entendí\" y te repiten todo.",
    lineEn: "Name the hole and you get two sentences. Say \"I didn't understand\" and you get the whole thing again.",
    prompts: [
      {
        id: "d257-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less understood enough not to ask anything else.",
        spanish: "Más o menos entendí lo suficiente para no preguntar más.",
        situationLabel: "Una llamada rápida",
        why: "Knowing when you have enough is a skill of its own. Not every gap needs filling.",
        wordHints: [
          { en: "enough", es: "lo suficiente" },
          { en: "not to ask", es: "para no preguntar" },
          { en: "more", es: "más" },
        ],
      },
      {
        id: "d257-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was the day and the time.",
        spanish: "Lo que sí entendí fue el día y la hora.",
        situationLabel: "Lo esencial",
        why: "Day, time, place, person. Get those four and you can act; everything else can be asked later.",
        wordHints: [
          { en: "the day", es: "el día" },
          { en: "the time", es: "la hora" },
        ],
      },
      {
        id: "d257-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say I'm bringing the chairs?",
        spanish: "¿Dijiste que yo llevo las sillas?",
        situationLabel: "Antes de colgar",
        why: "Reading the plan back before you hang up. Ten seconds that prevent a Thursday's worth of confusion.",
        wordHints: [
          { en: "i bring", es: "yo llevo" },
          { en: "the chairs", es: "las sillas" },
        ],
      },
      {
        id: "d257-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "I missed the part about the food, just that bit.",
        spanish: "Se me escapó la parte de la comida, solo esa.",
        situationLabel: "Pidiendo un trozo exacto",
        why: "*Solo esa* — just that one. It stops the other person from starting over, which they were about to do.",
        wordHints: [
          { en: "the food", es: "la comida" },
          { en: "just that one", es: "solo esa" },
        ],
      },
      {
        id: "d257-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather that each family brings the food.",
        spanish: "Por el contexto entiendo que la comida la trae cada familia.",
        situationLabel: "Rellenando tú el hueco",
        why: "Often you can fill the gap yourself and just check it. That's faster than asking, and it's what you'd do in English.",
        wordHints: [
          { en: "the food", es: "la comida" },
          { en: "each family brings it", es: "la trae cada familia" },
        ],
      },
    ],
  },
  {
    day: 258,
    themeEs: "Por el contexto",
    themeEn: "From the context",
    missionEs: "Adivina cuatro palabras nuevas sin parar a preguntarlas.",
    missionEn: "Work out four new words without stopping to ask.",
    line: "Deducir en vez de traducir. Eso es escuchar de verdad.",
    lineEn: "Inferring instead of translating. That's what listening actually is.",
    prompts: [
      {
        id: "d258-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less understood the whole evening.",
        spanish: "Más o menos entendí toda la noche.",
        situationLabel: "Cena con las tres",
        why: "A whole evening, three speakers, no English. Six months ago this sentence would have been a lie.",
        wordHints: [
          { en: "the whole", es: "toda" },
          { en: "evening", es: "la noche" },
        ],
      },
      {
        id: "d258-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was almost all of it, for a change.",
        spanish: "Lo que sí entendí fue casi todo, para variar.",
        situationLabel: "Notando el cambio",
        why: "*Para variar* — for a change. Used sincerely here, though it's usually sarcastic. Tone decides.",
        wordHints: [
          { en: "almost all", es: "casi todo" },
          { en: "for a change", es: "para variar" },
        ],
      },
      {
        id: "d258-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say I only asked twice?",
        spanish: "¿Dijiste que solo pregunté dos veces?",
        situationLabel: "Camila llevando la cuenta",
        why: "Two clarification questions in an entire evening. Worth having someone else count so you believe it.",
        wordHints: [
          { en: "only", es: "solo" },
          { en: "i asked", es: "pregunté" },
          { en: "twice", es: "dos veces" },
        ],
      },
      {
        id: "d258-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "I missed one single minute in the whole evening.",
        spanish: "Se me escapó la parte de un solo minuto en toda la noche.",
        situationLabel: "El inventario honesto",
        why: "One minute out of three hours. That's a normal rate of attention in any language, including your first.",
        wordHints: [
          { en: "one single minute", es: "un solo minuto" },
          { en: "in the whole evening", es: "en toda la noche" },
        ],
      },
      {
        id: "d258-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather that \"chévere\" is like \"how great\".",
        spanish: "Por el contexto entiendo que \"chévere\" es como \"qué bueno\".",
        situationLabel: "Cazando una palabra al vuelo",
        why: "*Chévere* is Colombian, Venezuelan and Caribbean; elsewhere it's *bacán* or *padre*. Guessing it from context is the win, not the word.",
        wordHints: [
          { en: "is like", es: "es como" },
          { en: "how great", es: "qué bueno" },
        ],
      },
    ],
  },
  {
    day: 259,
    themeEs: "Repaso: Sin captar todo",
    themeEn: "Review: Without catching it all",
    missionEs: "Di qué cambió esta semana, y no fue tu vocabulario.",
    missionEn: "Say what changed this week, and it wasn't your vocabulary.",
    line: "La meta de la temporada llegó un martes, sin ceremonia.",
    lineEn: "The season's goal arrived on a Tuesday, with no ceremony.",
    prompts: [
      {
        id: "d259-mas-o-menos",
        frameStem: "Más o menos entendí que…",
        english: "I more or less got that nobody catches a hundred percent.",
        spanish: "Más o menos entendí que nadie capta el cien por ciento.",
        situationLabel: "El descubrimiento de la semana",
        why: "Nobody catches everything in their first language either. The week's whole discovery, and it isn't about Spanish.",
        wordHints: [
          { en: "nobody catches", es: "nadie capta" },
          { en: "a hundred percent", es: "el cien por ciento" },
        ],
      },
      {
        id: "d259-lo-que-si",
        frameStem: "Lo que sí entendí fue…",
        english: "What I did catch was that I was counting wrong — I was counting holes.",
        spanish: "Lo que sí entendí fue que cuento mal: contaba huecos.",
        situationLabel: "Cambiando la cuenta",
        why: "Same evening, same words, different arithmetic. That's the entire intervention this week performed.",
        wordHints: [
          { en: "i count wrong", es: "cuento mal" },
          { en: "i was counting", es: "contaba" },
          { en: "holes", es: "huecos" },
        ],
      },
      {
        id: "d259-dijiste-que",
        frameStem: "¿Dijiste que…?",
        english: "Did you say I ask better, not less?",
        spanish: "¿Dijiste que pregunto mejor, no menos?",
        situationLabel: "La corrección de Camila",
        why: "Not fewer questions — better-aimed ones. That distinction is the difference between hiding and listening.",
        wordHints: [
          { en: "i ask", es: "pregunto" },
          { en: "better", es: "mejor" },
          { en: "not less", es: "no menos" },
        ],
      },
      {
        id: "d259-se-me-escapo",
        frameStem: "Se me escapó la parte de…",
        english: "What I lost was the panicking part — that one's gone.",
        spanish: "Se me escapó la parte de entrar en pánico, esa sí se me fue.",
        situationLabel: "Lo que de verdad perdiste",
        why: "The phrase turned on itself. The only thing that actually went missing this week was the panic.",
        wordHints: [
          { en: "to panic", es: "entrar en pánico" },
          { en: "that one did leave me", es: "esa sí se me fue" },
        ],
      },
      {
        id: "d259-por-el-contexto",
        frameStem: "Por el contexto entiendo que…",
        english: "From the context I gather that this was the season's goal.",
        spanish: "Por el contexto entiendo que esto era la meta de la temporada.",
        situationLabel: "Dándote cuenta tarde",
        why: "\"Watch something without subtitles\" was written into this season's goals back in June. It arrived quietly, on a Tuesday.",
        wordHints: [
          { en: "this was", es: "esto era" },
          { en: "the goal", es: "la meta" },
          { en: "of the season", es: "de la temporada" },
        ],
      },
    ],
  },
];
