import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 8 — "La estudiante nueva" (days 232–238).
 * Yesenia joins the ESOL class in February after eight months of silence, and
 * Marlana hands her, one by one, every piece of advice she was given in
 * January. The season's first half closes by giving itself away.
 */
export const invWeek8ReadingDays: ReadingDay[] = [
  {
    day: 232,
    themeEs: "La estudiante nueva",
    storyTitle: "La estudiante nueva",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "atrasada", en: "behind", example: "Es importante que sepa que no está atrasada." },
      { es: "el salón", en: "the classroom", example: "Nadie del salón la va a corregir." },
      { es: "disculparse", en: "to apologize", example: "No hace falta que se disculpe." },
      { es: "el cuaderno", en: "the notebook", example: "Te sugiero que traigas un cuaderno cualquiera." },
      { es: "calificar", en: "to grade", example: "Aquí nadie te califica." },
    ],
    dialogue: {
      title: "Ocho meses callada",
      situation: "Yesenia llega tarde a su primera clase de inglés",
      lines: [
        { speaker: "B", es: "Disculpe, maestra. Perdón, es que me perdí. Disculpe de verdad.", en: "Excuse me, teacher. Sorry, I got lost. I'm really sorry." },
        { speaker: "A", es: "No hace falta que se disculpe por llegar tarde. Pase, siéntese.", en: "There's no need to apologize for arriving late. Come in, sit down." },
        { speaker: "B", es: "No traje nada. Ni cuaderno ni nada. Perdón.", en: "I didn't bring anything. No notebook, nothing. Sorry." },
        { speaker: "A", es: "No hace falta que traiga nada, aquí hay de todo. ¿Cuánto lleva en el país?", en: "There's no need to bring anything, we have everything here. How long have you been in the country?" },
        { speaker: "B", es: "Ocho meses. Y no he dicho ni una frase en inglés. Ni una, maestra.", en: "Eight months. And I haven't said one sentence in English. Not one, teacher." },
        { speaker: "A", es: "Es importante que sepa que no está atrasada. Aquí llega gente con dos años igual que usted.", en: "It's important that you know you're not behind. People come here after two years in exactly the same place." },
        { speaker: "B", es: "¿En serio?", en: "Really?" },
        { speaker: "A", es: "En serio. Es mejor que empiece con frases cortas. Y más vale que te equivoques hablando que quedarte callada.", en: "Really. You'd be better off starting with short sentences. And you'd better get it wrong out loud than stay silent." },
        { speaker: "B", es: "Me trató de usted y luego de tú.", en: "You used usted with me and then tú." },
        { speaker: "A", es: "Perdón, se me fue. ¿Prefiere usted?", en: "Sorry, it slipped. Do you prefer usted?" },
      ],
    },
  },
  {
    day: 233,
    themeEs: "No hace falta que te disculpes",
    storyTitle: "La estudiante nueva",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "háblame de tú", en: "use tú with me", example: "Háblame de tú, maestra, por favor." },
      { es: "pedir perdón", en: "to say sorry", example: "No hace falta que pidas perdón cada vez." },
      { es: "a medias", en: "half-finished", example: "Es mejor que no dejes la frase a medias." },
      { es: "bajito", en: "quietly, in a small voice", example: "Habla fuerte, no bajito." },
      { es: "la muletilla", en: "the filler word", example: "Cambia el sorry por una muletilla." },
    ],
    dialogue: {
      title: "Once veces en una hora",
      situation: "Segunda clase; Marlana lleva la cuenta",
      lines: [
        { speaker: "B", es: "Háblame de tú, maestra, por favor. Me hace sentir vieja el usted.", en: "Use tú with me, teacher, please. The usted makes me feel old." },
        { speaker: "A", es: "Hecho. Entonces: es importante que sepas que aquí nadie te califica.", en: "Done. So: it's important that you know nobody grades you here." },
        { speaker: "B", es: "Es que hablo muy mal. Perdón. Ay, perdón otra vez.", en: "It's just that I speak so badly. Sorry. Oh, sorry again." },
        { speaker: "A", es: "Once.", en: "Eleven." },
        { speaker: "B", es: "¿Once qué?", en: "Eleven what?" },
        { speaker: "A", es: "Once veces que pides perdón en una hora. Las conté. No hace falta que te disculpes cada vez que te equivocas.", en: "Eleven times you've apologized in an hour. I counted. There's no need to apologize every time you get something wrong." },
        { speaker: "B", es: "Nunca me había fijado.", en: "I'd never noticed." },
        { speaker: "A", es: "Te sugiero que cambies el \"sorry\" por un \"pues\". Es mejor que digas \"pues\" y sigas.", en: "I'd suggest swapping the \"sorry\" for a \"pues\". You're better off saying \"pues\" and carrying on." },
        { speaker: "B", es: "Pues… no sé qué decir después.", en: "Well… I don't know what to say after." },
        { speaker: "A", es: "Perfecto. Eso ya fue. Más vale que hables mal y fuerte que bien y bajito.", en: "Perfect. That was it. You'd better speak badly and loudly than well and quietly." },
      ],
    },
  },
  {
    day: 234,
    themeEs: "Es importante que hables mal",
    storyTitle: "La estudiante nueva",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "esconder", en: "to hide", example: "No hace falta que escondas el acento." },
      { es: "sentirse lista", en: "to feel ready", example: "No esperes a sentirte lista." },
      { es: "en voz alta", en: "out loud", example: "Di cinco frases al día en voz alta." },
      { es: "el permiso", en: "permission", example: "Dar permiso de equivocarse es casi todo." },
      { es: "entenderse", en: "to be understood", example: "Lo importante es que te entiendan." },
    ],
    dialogue: {
      title: "Permiso de hacerlo mal",
      situation: "Yesenia no quiere hablar delante del grupo",
      lines: [
        { speaker: "B", es: "Cuando esté más lista hablo delante de todos. Todavía no.", en: "When I'm more ready I'll speak in front of everyone. Not yet." },
        { speaker: "A", es: "No hace falta que estés lista para empezar. Nadie está listo nunca, Yesenia.", en: "There's no need to be ready in order to start. Nobody's ever ready, Yesenia." },
        { speaker: "B", es: "Es que me da pena el acento.", en: "It's just that my accent embarrasses me." },
        { speaker: "A", es: "No hace falta que escondas el acento, aquí todos tenemos uno. Óyeme a mí en español.", en: "There's no need to hide your accent, we all have one here. Listen to me in Spanish." },
        { speaker: "B", es: "Usted habla bien.", en: "You speak well." },
        { speaker: "A", es: "Hablo entendible. Es distinto. Es importante que te entiendan, no que hables perfecto.", en: "I speak understandably. That's different. It's important that they understand you, not that you speak perfectly." },
        { speaker: "B", es: "¿Y cómo empiezo?", en: "And how do I start?" },
        { speaker: "A", es: "Te sugiero que digas cinco frases al día, en voz alta. Cinco. Ni una más.", en: "I'd suggest you say five sentences a day, out loud. Five. Not one more." },
        { speaker: "B", es: "Cinco sí puedo.", en: "Five I can do." },
        { speaker: "A", es: "Es mejor que hables mal hoy y mejor el mes que viene. Más vale que te entiendan mal a que no digas nada.", en: "You're better off speaking badly today and better next month. You'd better be misunderstood than say nothing at all." },
      ],
    },
  },
  {
    day: 235,
    themeEs: "Te sugiero que grabes",
    storyTitle: "La estudiante nueva",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "grabar", en: "to record", example: "Te sugiero que grabes un audio cada noche." },
      { es: "borrar", en: "to delete", example: "No borres ninguno, aunque te dé pena." },
      { es: "darle pena a alguien", en: "to embarrass someone", example: "Aunque te dé pena, no lo borres." },
      { es: "comparar", en: "to compare", example: "Guarda el primero para comparar." },
      { es: "juzgar", en: "to judge", example: "El micrófono no juzga a nadie." },
    ],
    dialogue: {
      title: "El micrófono no juzga",
      situation: "Marlana le pasa el truco de las notas de voz",
      lines: [
        { speaker: "A", es: "Te voy a dar un truco que a mí me sirvió muchísimo. Te sugiero que grabes un audio cada noche.", en: "I'm going to give you a trick that helped me enormously. I'd suggest you record a voice note every night." },
        { speaker: "B", es: "¿Y se lo mando a quién?", en: "And who do I send it to?" },
        { speaker: "A", es: "A nadie. No hace falta que se lo mandes a nadie. Es para ti.", en: "Nobody. There's no need to send it to anybody. It's for you." },
        { speaker: "B", es: "Ah. Entonces, ¿para qué sirve?", en: "Ah. Then what's it for?" },
        { speaker: "A", es: "Para oírte. Es importante que te escuches una vez a la semana. Y es importante que guardes el primer audio para comparar.", en: "To hear yourself. It's important that you listen to yourself once a week. And it's important that you keep the first one to compare." },
        { speaker: "B", es: "Me va a dar pena oírme.", en: "It's going to embarrass me to hear myself." },
        { speaker: "A", es: "A mí me dio. Y sonaba mejor de lo que pensaba. Te sugiero que no borres ninguno, aunque te dé pena.", en: "It did me. And I sounded better than I thought. I'd suggest you don't delete any of them, even when you're embarrassed." },
        { speaker: "B", es: "¿Cuánto tienen que durar?", en: "How long do they have to be?" },
        { speaker: "A", es: "No hace falta que duren más de treinta segundos. Más vale que grabes treinta segundos diarios que una hora el domingo.", en: "There's no need for them to last more than thirty seconds. You'd better record thirty seconds daily than an hour on Sunday." },
      ],
    },
  },
  {
    day: 236,
    themeEs: "Más vale que empieces hoy",
    storyTitle: "La estudiante nueva",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "la racha", en: "the streak", example: "No rompas la racha por un día malo." },
      { es: "perdonarse", en: "to forgive oneself", example: "Es importante que te perdones el día que falles." },
      { es: "acomodarse", en: "to settle in", example: "Empieza antes de que el miedo se acomode." },
      { es: "seguido", en: "often", example: "No hace falta hacer mucho, hace falta hacerlo seguido." },
      { es: "poquito", en: "a tiny bit", example: "Es mejor que hagas poquito todos los días." },
    ],
    dialogue: {
      title: "Empieza hoy, mal",
      situation: "Viernes; Yesenia quiere esperar a marzo para empezar en serio",
      lines: [
        { speaker: "B", es: "Estaba pensando empezar bien en marzo, cuando tenga más tiempo.", en: "I was thinking of starting properly in March, when I have more time." },
        { speaker: "A", es: "Es mejor que sea ahora y no en la primavera. Es mejor que empieces antes de que el miedo se acomode.", en: "You're better off it being now and not in the spring. Better to start before the fear settles in." },
        { speaker: "B", es: "Es que en marzo tendría media hora diaria.", en: "It's just that in March I'd have half an hour a day." },
        { speaker: "A", es: "No hace falta que hagas mucho, hace falta que lo hagas seguido. Es mejor que hagas poquito todos los días.", en: "You don't need to do a lot, you need to do it often. Better to do a tiny bit every day." },
        { speaker: "B", es: "¿Y si un día no puedo?", en: "And if one day I can't?" },
        { speaker: "A", es: "Es importante que no rompas la racha por un día malo. Y es importante que te perdones el día que falles.", en: "It's important that you don't break the streak over one bad day. And it's important that you forgive yourself the day you slip." },
        { speaker: "B", es: "Las dos cosas suenan contrarias.", en: "Those two things sound contradictory." },
        { speaker: "A", es: "Van juntas. Si solo dices la primera, la gente abandona el primer martes que falla.", en: "They go together. If you only say the first one, people quit the first Tuesday they miss." },
        { speaker: "B", es: "Está bien. Empiezo hoy.", en: "All right. I'll start today." },
        { speaker: "A", es: "Más vale que empieces hoy mal a que empieces nunca bien. Más vale una frase hoy que un plan entero el domingo.", en: "You'd better start today badly than start never well. One sentence today beats a whole plan on Sunday." },
      ],
    },
  },
  {
    day: 237,
    themeEs: "Lo que me dijo Camila",
    storyTitle: "La estudiante nueva",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "quedársele a alguien", en: "to stay with someone, to stick", example: "Enséñaselo a otro, así se te queda." },
      { es: "circular", en: "to circulate, to get passed around", example: "Más vale que el consejo circule." },
      { es: "la experta", en: "the expert", example: "No hace falta que sea experta." },
      { es: "el consejo", en: "the piece of advice", example: "Le conté de dónde salió el consejo." },
      { es: "pasar adelante", en: "to pass on", example: "Lo que me dieron, lo paso adelante." },
    ],
    dialogue: {
      title: "Una enfermera colombiana",
      situation: "Marlana le cuenta a Camila lo que ha estado diciendo toda la semana",
      lines: [
        { speaker: "A", es: "Camila, esta semana me oí decirle a una estudiante nueva exactamente lo que tú me dijiste en enero.", en: "Camila, this week I heard myself telling a new student exactly what you told me in January." },
        { speaker: "B", es: "¿Sí? ¿Qué le dijiste?", en: "Really? What did you tell her?" },
        { speaker: "A", es: "Que no hace falta que se disculpe. Que diga \"pues\" y siga. Palabra por palabra, Camila.", en: "That there's no need to apologize. That she should say \"pues\" and carry on. Word for word, Camila." },
        { speaker: "B", es: "Y funcionó, seguro.", en: "And it worked, I bet." },
        { speaker: "A", es: "A la segunda clase. Es importante que sepa que a mí me funcionó primero, eso también se lo dije.", en: "By the second class. It's important that she knows it worked on me first — I told her that too." },
        { speaker: "B", es: "Eso está bien. El consejo solo pesa si viene con la historia.", en: "That's good. Advice only carries weight if it comes with the story." },
        { speaker: "A", es: "Le dije que a mí me lo dijo una enfermera colombiana en un café de Jamaica Plain.", en: "I told her a Colombian nurse said it to me in a café in Jamaica Plain." },
        { speaker: "B", es: "Ay, no. ¿En serio?", en: "Oh no. Really?" },
        { speaker: "A", es: "En serio. No hace falta que yo haya terminado para ayudar a alguien que empieza. Más vale que el consejo circule a que se quede conmigo.", en: "Really. I don't have to be finished to help someone who's starting. Better the advice circulates than stays with me." },
      ],
    },
  },
  {
    day: 238,
    themeEs: "Repaso: Es mejor que…",
    isRecap: true,
    vocab: [
      { es: "el trozo", en: "the chunk", example: "Es mejor que lo aprenda en trozos." },
      { es: "armar una frase", en: "to assemble a sentence", example: "Ya no armo estas frases." },
      { es: "la tabla", en: "the conjugation table", example: "Cuatro semanas y ninguna tabla." },
      { es: "servirle a alguien", en: "to be useful to someone", example: "Más vale que le sirva a alguien más." },
      { es: "adelante", en: "onward, ahead", example: "Más vale seguir adelante." },
    ],
    dialogue: {
      title: "Veinte trozos, ninguna tabla",
      situation: "Jueves; cierre de las cuatro semanas de subjuntivo",
      lines: [
        { speaker: "B", es: "Cuatro semanas de subjuntivo. ¿Cuántas tablas viste?", en: "Four weeks of subjunctive. How many tables did you see?" },
        { speaker: "A", es: "Ninguna. Ni una sola. Y ya no armo estas frases, me salen enteras.", en: "None. Not one. And I don't assemble these sentences anymore, they come out whole." },
        { speaker: "B", es: "Veinte comienzos, cinco por semana. Eso fue todo.", en: "Twenty openers, five a week. That was all of it." },
        { speaker: "A", es: "No hace falta que sepa cómo se llama para usarlo. Eso me quedó clarísimo.", en: "I don't need to know what it's called in order to use it. That much is completely clear." },
        { speaker: "B", es: "¿Y ahora qué sigue?", en: "And what comes next?" },
        { speaker: "A", es: "Conversación de verdad. Interrumpir, tomar el turno, entender a medias sin entrar en pánico.", en: "Real conversation. Interrupting, taking a turn, half-understanding without panicking." },
        { speaker: "B", es: "Ahí sí que vas a necesitar todo lo del invierno junto.", en: "Now there you're going to need everything from this winter at once." },
        { speaker: "A", es: "Te sugiero que guardes los audios de enero y de marzo, me dijiste. Ya los tengo separados los dos.", en: "\"Keep January's and March's recordings,\" you told me. I've already got them both saved separately." },
        { speaker: "B", es: "Bien. Y más vale que este invierno le sirva a alguien más. Yesenia ya va por ahí.", en: "Good. And better this winter is useful to somebody else too. Yesenia's already on her way." },
      ],
    },
  },
];
