import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 10 — "La conversación de tres" (days 246–252).
 * Camila is back from Bogotá and the Thursday café becomes a three: Camila,
 * Marlana, Rocío. Two people take turns by default; three people have to claim.
 * Day 251 pays off the listener-signals beat from day 195.
 */
export const invWeek10ReadingDays: ReadingDay[] = [
  {
    day: 246,
    themeEs: "Tres al mismo tiempo",
    storyTitle: "La conversación de tres",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el turno", en: "the turn (to speak)", example: "En una conversación de tres hay que pedir el turno." },
      { es: "llevar rato", en: "to have been a while", example: "Llevas rato callada." },
      { es: "pasarle la palabra a alguien", en: "to hand someone the floor", example: "Déjame terminar y ya te la paso." },
      { es: "írsele a alguien", en: "for something to slip away", example: "Déjame terminar, que si no se me va." },
      { es: "opinar", en: "to weigh in", example: "¿Y tú qué opinas, Rocío?" },
    ],
    dialogue: {
      title: "Ahora somos tres",
      situation: "Camila volvió de Bogotá y trae a Rocío al café de los jueves",
      lines: [
        { speaker: "B", es: "Bueno, ahora somos tres. Rocío, Camila. Camila, Rocío.", en: "Okay, now there are three of us. Rocío, Camila. Camila, Rocío." },
        { speaker: "A", es: "Por fin. Llevo meses hablándoles a las dos de la otra.", en: "Finally. I've spent months telling each of you about the other." },
        { speaker: "B", es: "Y ya me contó Marlana lo de tu abuela. Cómo sigue—", en: "And Marlana already told me about your grandmother. How is she—" },
        { speaker: "A", es: "Espera, déjame terminar, que si no se me va. Quiero decir algo antes de que empecemos.", en: "Hang on, let me finish, because otherwise I'll lose it. I want to say something before we start." },
        { speaker: "B", es: "Dale.", en: "Go ahead." },
        { speaker: "A", es: "Que en enero yo no habría podido hacer esto. Tres personas en español, hablando encima.", en: "That in January I couldn't have done this. Three people in Spanish, talking over each other." },
        { speaker: "B", es: "Ajá, claro. Con dos es fácil, uno habla y el otro escucha.", en: "Mm-hm, right. With two it's easy, one talks and the other listens." },
        { speaker: "A", es: "Con tres hay que meterse. Como te decía, eso es lo que me faltaba.", en: "With three you have to jump in. As I was saying, that's what I was missing." },
        { speaker: "B", es: "Pues aquí lo vas a practicar. ¿Y tú qué opinas, Rocío? Llevas rato callada.", en: "Well, you'll get practice here. And what do you think, Rocío? You've been quiet a while." },
      ],
    },
  },
  {
    day: 247,
    themeEs: "Déjame terminar",
    storyTitle: "La conversación de tres",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "meterse", en: "to jump in, to cut in", example: "Se me metió a mitad de frase." },
      { es: "sin filo", en: "without an edge", example: "Aprendí a decirlo sin filo." },
      { es: "el tono", en: "the tone", example: "El tono hace todo el trabajo." },
      { es: "enojarse", en: "to get annoyed", example: "No te enojes, es que se me va." },
      { es: "lo de antes", en: "what came before", example: "Necesitas saber lo de antes." },
    ],
    dialogue: {
      title: "Sin sonar molesta",
      situation: "Rocío interrumpe a Marlana tres veces sin darse cuenta",
      lines: [
        { speaker: "A", es: "El martes en la junta les dije lo del transporte y entonces Delia—", en: "On Tuesday at the meeting I told them about the transportation and then Delia—" },
        { speaker: "B", es: "¡Ay, Delia! Esa señora habla hasta por los codos.", en: "Oh, Delia! That woman could talk the hind legs off a donkey." },
        { speaker: "A", es: "Déjame terminar, son dos frases más.", en: "Let me finish, it's two more sentences." },
        { speaker: "B", es: "Perdón, perdón. Sigue.", en: "Sorry, sorry. Go on." },
        { speaker: "A", es: "Como te decía, el problema es el horario, no Delia. Ella tenía razón.", en: "As I was saying, the problem is the schedule, not Delia. She was right." },
        { speaker: "B", es: "Ah, ¿sí? ¿En qué?", en: "Oh, really? About what?" },
        { speaker: "A", es: "A eso voy, pero necesitas saber lo de antes. Hace dos semanas votamos las seis.", en: "I'm getting to that, but you need to know what came before. Two weeks ago we voted for six o'clock." },
        { speaker: "B", es: "Ajá, ya, ya veo por dónde vas.", en: "Mm-hm, right, I see where you're going." },
        { speaker: "A", es: "Fíjate lo que acabo de hacer tres veces sin enojarme. En enero me habría callado y ya.", en: "Notice what I just did three times without getting annoyed. In January I'd have gone quiet and that would've been that." },
      ],
    },
  },
  {
    day: 248,
    themeEs: "A eso voy",
    storyTitle: "La conversación de tres",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "dar la vuelta", en: "to go the long way round", example: "Voy dando la vuelta pero llego." },
      { es: "el rodeo", en: "the detour, the roundabout way", example: "El rodeo tiene sentido." },
      { es: "apurar a alguien", en: "to rush someone", example: "No me apures, ya casi." },
      { es: "entenderse solo", en: "to explain itself", example: "Déjame terminar y se entiende solo." },
      { es: "el contexto", en: "the background", example: "Primero el contexto y luego el punto." },
    ],
    dialogue: {
      title: "Voy dando la vuelta pero llego",
      situation: "Camila quiere la conclusión y Marlana quiere contar la historia",
      lines: [
        { speaker: "B", es: "Marlana, dime nada más si al final cambiaron la hora o no.", en: "Marlana, just tell me whether they changed the time in the end or not." },
        { speaker: "A", es: "A eso voy, voy dando la vuelta pero llego.", en: "I'm getting to that, I'm going the long way but I'll arrive." },
        { speaker: "B", es: "Es que me tienes en suspenso.", en: "You've got me in suspense." },
        { speaker: "A", es: "Déjame terminar el contexto y se entiende solo. Si te digo el final ahorita, no significa nada.", en: "Let me finish the context and it'll explain itself. If I tell you the ending now, it means nothing." },
        { speaker: "B", es: "Ajá, claro, dale.", en: "Mm-hm, right, go ahead." },
        { speaker: "A", es: "Como te decía, todo empezó el martes. Yo llevaba cuarenta minutos con una frase guardada.", en: "As I was saying, it all started on Tuesday. I'd been sitting on one sentence for forty minutes." },
        { speaker: "B", es: "Cuarenta minutos. ¿Y por qué no la dijiste?", en: "Forty minutes. And why didn't you say it?" },
        { speaker: "A", es: "A eso voy, dame treinta segundos. Porque estaba esperando una pausa que nunca llegó.", en: "I'm getting to that, give me thirty seconds. Because I was waiting for a pause that never came." },
        { speaker: "B", es: "Ay, eso lo conozco. Nunca llega. Nunca.", en: "Oh, I know that one. It never comes. Never." },
      ],
    },
  },
  {
    day: 249,
    themeEs: "¿Y tú qué opinas?",
    storyTitle: "La conversación de tres",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "regalar el turno", en: "to give the floor away", example: "Nadie regala el turno." },
      { es: "acomodarse", en: "to go along with, to fit in", example: "Tú decides y yo me acomodo." },
      { es: "por educación", en: "out of politeness", example: "No me digas que sí por educación." },
      { es: "adelante", en: "go ahead", example: "Ya terminé, adelante." },
      { es: "a lo mejor", en: "maybe", example: "A lo mejor lo estoy viendo mal." },
    ],
    dialogue: {
      title: "Llevas veinte minutos callada",
      situation: "Rocío no ha dicho nada y Marlana lo nota",
      lines: [
        { speaker: "A", es: "Como te decía, esa es mi parte, ahora la tuya. ¿Y tú qué opinas? No has dicho nada en veinte minutos.", en: "As I was saying, that's my part, now yours. And what do you think? You haven't said anything in twenty minutes." },
        { speaker: "B", es: "No, no, ustedes sigan, yo escucho.", en: "No, no, you two carry on, I'm listening." },
        { speaker: "A", es: "Rocío. En serio. Yo llevo hablando demasiado. ¿Y tú qué opinas de verdad, no lo educado?", en: "Rocío. Seriously. I've been talking too much. And what do you really think — not the polite answer?" },
        { speaker: "B", es: "Pues… creo que estás pensando en el comité y no en las familias.", en: "Well… I think you're thinking about the committee and not the families." },
        { speaker: "A", es: "Ajá, claro. Sigue, no te apures.", en: "Mm-hm, right. Go on, take your time." },
        { speaker: "B", es: "Las familias no quieren una hora buena. Quieren saber que si llegan tarde no pasa nada.", en: "The families don't want a good time slot. They want to know that if they arrive late it's fine." },
        { speaker: "A", es: "Ay. Eso no se me había ocurrido. A lo mejor lo estoy viendo mal desde el principio.", en: "Oh. That hadn't occurred to me. Maybe I've been seeing it wrong from the start." },
        { speaker: "B", es: "Y por eso me preguntaste. Nadie me pregunta nunca, Marlana.", en: "And that's why you asked me. Nobody ever asks me, Marlana." },
        { speaker: "A", es: "Pues ya somos dos que no preguntábamos. Ajá, claro, cuéntame más.", en: "Well, that makes two of us who didn't ask. Mm-hm, right, tell me more." },
      ],
    },
  },
  {
    day: 250,
    themeEs: "Como te decía",
    storyTitle: "La conversación de tres",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "adelantar el final", en: "to spoil the ending", example: "No me adelantes el final." },
      { es: "recoger", en: "to pick up", example: "La frase se cayó y la recogí." },
      { es: "el reproche", en: "the reproach", example: "Nunca suena a reproche." },
      { es: "caerse", en: "to fall, to drop", example: "La frase se cayó a mitad." },
      { es: "por tercera vez", en: "for the third time", example: "Déjame terminar, por tercera vez." },
    ],
    dialogue: {
      title: "Tres interrupciones, tres regresos",
      situation: "Una historia larga que sobrevive a todo",
      lines: [
        { speaker: "A", es: "Como te decía, llegué a la junta con tres puntos. El primero era el horario—", en: "As I was saying, I came to the meeting with three points. The first was the schedule—" },
        { speaker: "B", es: "Ese ya lo sabemos.", en: "We already know that one." },
        { speaker: "A", es: "Déjame terminar, por tercera vez. Como te decía, el segundo era el del transporte.", en: "Let me finish, for the third time. As I was saying, the second was the transportation one." },
        { speaker: "B", es: "¡Y ahí ganaste! Porque nadie lo había pensado.", en: "And that's where you won! Because nobody had thought of it." },
        { speaker: "A", es: "A eso voy, no me adelantes el final.", en: "I'm getting to that, don't spoil the ending for me." },
        { speaker: "B", es: "Perdón, perdón. Sigue.", en: "Sorry, sorry. Go on." },
        { speaker: "A", es: "Como te decía, y el tercero no lo dije nunca. Se acabó la junta y me lo llevé a casa.", en: "As I was saying, and the third one I never got to say. The meeting ended and I took it home with me." },
        { speaker: "B", es: "¿Y cuál era?", en: "And what was it?" },
        { speaker: "A", es: "Ya, por fin terminé. ¿Y tú qué opinas? Ese era mi punto: que se me quedó adentro.", en: "Right, I finally finished. And what do you think? That was my point: it stayed inside me." },
      ],
    },
  },
  {
    day: 251,
    themeEs: "Ajá, claro",
    storyTitle: "La conversación de tres",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "hacer ruido", en: "to make noise", example: "En español el que escucha hace ruido." },
      { es: "hacerle falta a alguien", en: "for someone to need", example: "Hoy no me hizo falta decirlo." },
      { es: "empujar", en: "to push", example: "A eso voy es para cuando te empujan." },
      { es: "salir entera", en: "to come out whole", example: "La historia salió entera." },
      { es: "acompañar", en: "to keep company", example: "Escuchar también es acompañar." },
    ],
    dialogue: {
      title: "Diez minutos escuchando",
      situation: "Camila cuenta lo de Bogotá entero y Marlana no la interrumpe una sola vez",
      lines: [
        { speaker: "B", es: "…y cuando llegué al hospital ella estaba sentada, hablando con la enfermera del turno.", en: "…and when I got to the hospital she was sitting up, talking to the shift nurse." },
        { speaker: "A", es: "Ajá, claro, y tu abuela qué dijo.", en: "Mm-hm, right, and what did your grandmother say?" },
        { speaker: "B", es: "Me dijo: \"tú también eres enfermera, no me trates como paciente\". Y se rió.", en: "She said to me: \"you're a nurse too, don't treat me like a patient\". And she laughed." },
        { speaker: "A", es: "Ajá, ya, ya, cuéntame esa parte otra vez.", en: "Mm-hm, right, right, tell me that part again." },
        { speaker: "B", es: "Que no la tratara como paciente. Cuarenta años de maestra y sigue dando clase desde la cama.", en: "That I shouldn't treat her like a patient. Forty years a teacher and she's still teaching from the bed." },
        { speaker: "A", es: "Ajá, exacto, eso es lo que yo pensaba cuando me contaste de ella.", en: "Mm-hm, exactly, that's what I was thinking when you told me about her." },
        { speaker: "B", es: "Marlana. Llevas diez minutos oyéndome y no has dicho una frase entera.", en: "Marlana. You've been listening to me for ten minutes and haven't said a full sentence." },
        { speaker: "A", es: "Ya sé. Como te decía la semana pasada, esa es la parte que me faltaba.", en: "I know. As I was saying last week, that's the part I was missing." },
        { speaker: "B", es: "Pues ya no te falta. En enero te quedabas muda y yo no sabía si seguías ahí.", en: "Well, you're not missing it anymore. In January you'd go silent and I didn't know if you were still there." },
      ],
    },
  },
  {
    day: 252,
    themeEs: "Repaso: El turno",
    isRecap: true,
    vocab: [
      { es: "conversar", en: "to converse, to chat", example: "Escuchar es la otra mitad de conversar." },
      { es: "generosa", en: "generous", example: "Es la frase más generosa de las cinco." },
      { es: "elegante", en: "elegant", example: "Como te decía es la más elegante." },
      { es: "el filo", en: "the edge", example: "Ya lo digo sin filo." },
      { es: "la mitad", en: "the half", example: "Me faltaba la otra mitad." },
    ],
    dialogue: {
      title: "Las tres hablamos",
      situation: "Cierre de la semana; las tres hacen cuentas",
      lines: [
        { speaker: "B", es: "Repaso. En esta mesa hoy hablaron las tres. ¿Cuándo fue la última vez que eso pasó?", en: "Recap. At this table today, all three of us talked. When was the last time that happened?" },
        { speaker: "A", es: "Nunca, con tres personas. Con dos sí, pero con tres nunca.", en: "Never, with three people. With two yes, but with three never." },
        { speaker: "B", es: "¿Y cuál de las cinco frases te sirvió más?", en: "And which of the five phrases helped most?" },
        { speaker: "A", es: "¿Y tú qué opinas? es la que más digo ahora. Cambia una conversación entera.", en: "\"And what do you think?\" is the one I say most now. It changes a whole conversation." },
        { speaker: "B", es: "Ajá, claro. Y a Rocío se le nota.", en: "Mm-hm, right. And you can tell with Rocío." },
        { speaker: "A", es: "Déjame terminar me costó decirlo sin sonar molesta. Esa todavía la estoy aprendiendo.", en: "\"Let me finish\" was hard to say without sounding annoyed. That one I'm still learning." },
        { speaker: "B", es: "Esa se aprende con los años, no con las semanas.", en: "That one takes years, not weeks." },
        { speaker: "A", es: "Y ajá, claro fue la que más tardé en sentir natural. Resultó ser la otra mitad de conversar.", en: "And \"mm-hm, right\" took me longest to feel natural. It turned out to be the other half of talking." },
        { speaker: "B", es: "Esa es la lección de la semana. Total, que ninguna de las cinco era vocabulario. Todas eran tiempo.", en: "That's the lesson of the week. So in the end, none of the five was vocabulary. All of them were timing." },
      ],
    },
  },
];
