import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 5 — "La noche de las familias" (days 211–217).
 * Marlana and Rocío plan a bilingual family night at the school. A week of
 * asking people for things, which is a week of the subjunctive without anyone
 * ever saying the word.
 */
export const invWeek5ReadingDays: ReadingDay[] = [
  {
    day: 211,
    themeEs: "Lo que quiero de esta noche",
    storyTitle: "La noche de las familias",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el volante", en: "the flyer", example: "Necesito que revises el volante." },
      { es: "de visita", en: "like a guest, like a visitor", example: "Me gustaría que nadie se sintiera de visita." },
      { es: "salir sencillo", en: "to come out simple", example: "Quiero que salga sencillo y cálido." },
      { es: "confirmar", en: "to confirm", example: "Necesito que me confirmes la fecha." },
      { es: "el salón", en: "the classroom, the hall", example: "La directora nos dio el salón grande." },
    ],
    dialogue: {
      title: "Una noche para las familias",
      situation: "Rocío y Marlana, en la sala de maestros, después de clases",
      lines: [
        { speaker: "B", es: "Marlana, se me ocurrió algo. Una noche para las familias, en los dos idiomas.", en: "Marlana, I had an idea. A night for the families, in both languages." },
        { speaker: "A", es: "Me encanta. Quiero que las familias hablen, no que solo escuchen.", en: "I love it. I want the families to talk, not just listen." },
        { speaker: "B", es: "Exacto. Nada de presentaciones. ¿Y cuándo la hacemos?", en: "Exactly. No presentations. And when do we do it?" },
        { speaker: "A", es: "Prefiero que sea un jueves, no un viernes. Y prefiero que no dure más de una hora.", en: "I'd rather it be a Thursday, not a Friday. And I'd rather it didn't last more than an hour." },
        { speaker: "B", es: "De acuerdo. Necesito que la directora nos dé el salón grande, eso sí.", en: "Agreed. I do need the principal to give us the big room, though." },
        { speaker: "A", es: "¿Quieres que yo hable con ella? Y quiero que Rocío… digo, quiero que tú me ayudes con la parte en español.", en: "Do you want me to talk to her? And I want Rocío… I mean, I want you to help me with the Spanish part." },
        { speaker: "B", es: "Claro. Oye, ¿te diste cuenta de lo que acabas de hacer?", en: "Of course. Hey, did you notice what you just did?" },
        { speaker: "A", es: "¿Qué? Me corregí con un \"digo\".", en: "What? I corrected myself with a \"digo\"." },
        { speaker: "B", es: "Eso, y llevas cinco frases seguidas en subjuntivo sin pestañear. Me gustaría que nadie te lo hubiera dicho nunca.", en: "That, and you've done five sentences in a row in the subjunctive without blinking. I'd rather nobody had ever told you about it." },
      ],
    },
  },
  {
    day: 212,
    themeEs: "Lo que necesito de ti",
    storyTitle: "La noche de las familias",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "llevar una parte", en: "to be in charge of a part", example: "Quiero que tú lleves la parte en español." },
      { es: "por escrito", en: "in writing", example: "Prefiero que dividamos el trabajo por escrito." },
      { es: "encargarse de", en: "to take charge of", example: "Necesito que alguien se encargue del café." },
      { es: "repartirse", en: "to divide between yourselves", example: "Nos repartimos las llamadas." },
      { es: "más seguido", en: "more often", example: "Me gustaría que trabajáramos juntas más seguido." },
    ],
    dialogue: {
      title: "Quién hace qué",
      situation: "Repartiendo el trabajo, con una hoja en la mesa",
      lines: [
        { speaker: "A", es: "Quiero que quede claro quién hace qué. Prefiero que dividamos el trabajo por escrito.", en: "I want it to be clear who does what. I'd rather we split the work in writing." },
        { speaker: "B", es: "Buena idea. Yo llevo el español, tú el inglés. ¿Te parece?", en: "Good idea. I'll take the Spanish, you the English. Sound good?" },
        { speaker: "A", es: "Sí. Y necesito que me digas cuántas familias confirmaron. Necesito que llegues media hora antes.", en: "Yes. And I need you to tell me how many families confirmed. I need you to arrive half an hour early." },
        { speaker: "B", es: "Media hora antes, anotado. ¿Y quién recibe en la puerta?", en: "Half an hour early, noted. And who greets at the door?" },
        { speaker: "A", es: "Prefiero que tú recibas a las familias en la puerta. Tú las conoces mejor.", en: "I'd rather you greeted the families at the door. You know them better." },
        { speaker: "B", es: "Está bien. ¿Quieres que lo dividamos por salones para las llamadas?", en: "All right. Do you want us to split it by classroom for the calls?" },
        { speaker: "A", es: "Perfecto. Necesito que revises el volante antes de imprimirlo, por favor.", en: "Perfect. I need you to check the flyer before printing it, please." },
        { speaker: "B", es: "Hecho. Oye, una cosa.", en: "Done. Hey, one thing." },
        { speaker: "A", es: "Dime. Me gustaría que trabajáramos juntas más seguido, la verdad.", en: "Tell me. Honestly, I'd love it if we worked together more often." },
      ],
    },
  },
  {
    day: 213,
    themeEs: "Prefiero que sea sencillo",
    storyTitle: "La noche de las familias",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "caber", en: "to fit", example: "Necesito que quepa todo en una hora." },
      { es: "la junta", en: "the meeting", example: "Me gustaría que no se sintiera como una junta." },
      { es: "cada quien", en: "each person", example: "¿Quieres que cada quien traiga algo?" },
      { es: "reducir", en: "to cut down", example: "Necesito que reduzcamos la lista." },
      { es: "en círculo", en: "in a circle", example: "Quiero que el salón esté puesto en círculo." },
    ],
    dialogue: {
      title: "Tres actividades, no siete",
      situation: "El plan se hizo demasiado grande y hay que recortarlo",
      lines: [
        { speaker: "B", es: "Marlana, mira la lista. Tenemos siete actividades y una hora.", en: "Marlana, look at the list. We have seven activities and one hour." },
        { speaker: "A", es: "Ya lo vi. Necesito que reduzcamos la lista a tres actividades. Necesito que quepa todo en una hora.", en: "I saw. I need us to cut the list to three activities. I need it all to fit in one hour." },
        { speaker: "B", es: "¿Cuáles quitamos?", en: "Which ones do we drop?" },
        { speaker: "A", es: "Quiero que quitemos las presentaciones largas. Quiero que la gente coma y hable, nada más.", en: "I want us to drop the long presentations. I want people to eat and talk, nothing more." },
        { speaker: "B", es: "Ajá. ¿Y el proyector?", en: "Mm-hm. And the projector?" },
        { speaker: "A", es: "Prefiero que no haya proyector. Prefiero que sea sencillo y salga bien.", en: "I'd rather there was no projector. I'd rather it was simple and went well." },
        { speaker: "B", es: "Claro. Menos cosas, más conversación.", en: "Of course. Fewer things, more conversation." },
        { speaker: "A", es: "Me gustaría que se sintiera como una cena, no como una junta. Que las mesas estén juntas y ya.", en: "I'd love it if it felt like a dinner, not a meeting. Tables pushed together and that's it." },
        { speaker: "B", es: "¿Quieres que pidamos comida o que cada quien traiga algo?", en: "Do you want us to order food or have everyone bring something?" },
      ],
    },
  },
  {
    day: 214,
    themeEs: "Me gustaría que vinieran",
    storyTitle: "La noche de las familias",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la queja", en: "the complaint", example: "No es una reunión de quejas." },
      { es: "obligatorio", en: "mandatory", example: "Prefiero que no pongamos la palabra obligatorio." },
      { es: "traducir", en: "to translate", example: "Necesito que me ayudes a traducir la invitación." },
      { es: "firmar", en: "to sign", example: "Prefiero que la firmemos las dos." },
      { es: "aunque", en: "even if, even though", example: "Me gustaría que vinieran aunque no hablen inglés." },
    ],
    dialogue: {
      title: "La invitación",
      situation: "Escribiendo el volante en los dos idiomas",
      lines: [
        { speaker: "A", es: "Quiero que sepan que no es una reunión de quejas. Eso primero, arriba de todo.", en: "I want them to know it isn't a complaints meeting. That first, at the very top." },
        { speaker: "B", es: "De acuerdo. Y prefiero que la invitación sea corta. Nadie lee media página.", en: "Agreed. And I'd rather the invitation was short. Nobody reads half a page." },
        { speaker: "A", es: "Corta y en los dos idiomas. Prefiero que no pongamos la palabra \"obligatorio\".", en: "Short and in both languages. I'd rather we didn't put the word \"mandatory\"." },
        { speaker: "B", es: "Nunca. Esa palabra vacía un salón.", en: "Never. That word empties a room." },
        { speaker: "A", es: "Necesito que me ayudes a traducir la invitación. Mi español escrito todavía es rígido.", en: "I need you to help me translate the invitation. My written Spanish is still stiff." },
        { speaker: "B", es: "Con gusto. ¿Quieres que lo escribas tú en español y yo lo reviso?", en: "Gladly. Do you want to write it in Spanish and I'll check it?" },
        { speaker: "A", es: "Eso me gusta más. Y me gustaría que vinieran aunque no hablen inglés. ¿Cómo lo digo sin que suene raro?", en: "I like that better. And I'd love it if they came even if they don't speak English. How do I say that without it sounding odd?" },
        { speaker: "B", es: "Así como lo dijiste. Está perfecto. Ponlo tal cual.", en: "Just like you said it. It's perfect. Put it exactly that way." },
        { speaker: "A", es: "¿Quieres que grabemos un audio invitándolos también? Hay familias que no leen los mensajes.", en: "Do you want us to record a voice note inviting them too? There are families who don't read the messages." },
      ],
    },
  },
  {
    day: 215,
    themeEs: "¿Quieres que te ayude?",
    storyTitle: "La noche de las familias",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "apoyarse en", en: "to lean on", example: "Quiero que te apoyes en mí." },
      { es: "quedarle grande a alguien", en: "to be too much for someone", example: "Di cuando algo te quede grande." },
      { es: "avisar", en: "to give a heads-up", example: "Necesito que me avises si te falta tiempo." },
      { es: "darse crédito", en: "to give oneself credit", example: "Me gustaría que te dieras crédito por esto." },
      { es: "ordenar", en: "to tidy up", example: "¿Quieres que me quede después a ordenar?" },
    ],
    dialogue: {
      title: "No cargues sola",
      situation: "Martes por la noche; Rocío sigue en el colegio a las nueve",
      lines: [
        { speaker: "A", es: "Rocío, son las nueve. ¿Qué haces todavía aquí?", en: "Rocío, it's nine o'clock. What are you still doing here?" },
        { speaker: "B", es: "Me faltan las traducciones y las llamadas. Ya casi.", en: "I still have the translations and the calls. Almost there." },
        { speaker: "A", es: "Quiero que te apoyes en mí, no que cargues sola. ¿Quieres que te ayude con las traducciones?", en: "I want you to lean on me, not carry it alone. Do you want me to help you with the translations?" },
        { speaker: "B", es: "No, no, tranquila, yo puedo.", en: "No, no, don't worry, I've got it." },
        { speaker: "A", es: "Necesito que me avises si te falta tiempo. Prefiero que me pidas ayuda temprano.", en: "I need you to let me know if you're short on time. I'd rather you asked me for help early." },
        { speaker: "B", es: "Es que no quiero molestar.", en: "It's just that I don't want to be a bother." },
        { speaker: "A", es: "Me gustaría que aprendieras a pedir ayuda sin disculparte. Alguien me lo dijo a mí hace un mes.", en: "I'd love it if you learned to ask for help without apologizing. Someone said that to me a month ago." },
        { speaker: "B", es: "¿Quién?", en: "Who?" },
        { speaker: "A", es: "Una enfermera colombiana, en un café. Bueno: prefiero que cambiemos el plan a que salga mal. Dame las traducciones.", en: "A Colombian nurse, in a café. Okay: I'd rather we changed the plan than have it go badly. Give me the translations." },
      ],
    },
  },
  {
    day: 216,
    themeEs: "La noche",
    storyTitle: "La noche de las familias",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "salir bien", en: "to go well, to turn out well", example: "Salió mejor de lo que pensábamos." },
      { es: "quedarse conversando", en: "to stay talking", example: "Se quedaron conversando hasta tarde." },
      { es: "el evento", en: "the event", example: "Prefiero que no lo llamemos evento." },
      { es: "hubieras estado", en: "you had been", example: "Me gustaría que hubieras estado ahí." },
      { es: "repetir", en: "to do again", example: "Quiero que lo repitamos en marzo." },
    ],
    dialogue: {
      title: "Cuarenta personas",
      situation: "Jueves, once de la noche, audio para Camila desde el carro",
      lines: [
        { speaker: "A", es: "Camila, quiero que sepas que salió mejor de lo que pensábamos. Vinieron cuarenta personas.", en: "Camila, I want you to know it went better than we thought. Forty people came." },
        { speaker: "B", es: "¡Cuarenta! ¿Y cómo estuvo?", en: "Forty! And how was it?" },
        { speaker: "A", es: "Necesito que me creas: hablé toda la noche en español. Toda. No cambié ni una vez.", en: "I need you to believe me: I spoke Spanish all evening. All of it. I didn't switch once." },
        { speaker: "B", es: "Te creo. ¿Y las familias?", en: "I believe you. And the families?" },
        { speaker: "A", es: "Me gustaría que vieras cómo se quedaron conversando. Tuvimos que sacarlos a las nueve y media.", en: "I'd love it if you could see how they stayed talking. We had to get them out at half past nine." },
        { speaker: "B", es: "Ay, Marlana, qué bonito.", en: "Oh, Marlana, how lovely." },
        { speaker: "A", es: "Me gustaría que hubieras estado ahí. En serio. ¿Quieres que te mande el audio que grabé al final?", en: "I wish you'd been there. Really. Do you want me to send you the voice note I recorded at the end?" },
        { speaker: "B", es: "Mándamelo ya. Y prefiero que lo escuches tú también dentro de un mes.", en: "Send it now. And I'd rather you listened to it yourself in a month too." },
        { speaker: "A", es: "Quiero que lo repitamos en marzo. Y prefiero que no lo llamemos \"evento\", suena frío.", en: "I want us to do it again in March. And I'd rather we didn't call it an \"event\", it sounds cold." },
      ],
    },
  },
  {
    day: 217,
    themeEs: "Repaso: Quiero que…",
    isRecap: true,
    vocab: [
      { es: "costarle a alguien", en: "to be hard for someone", example: "Esto ya no me cuesta." },
      { es: "la regla", en: "the rule", example: "Prefiero que sigamos con frases y no con reglas." },
      { es: "el trozo", en: "the chunk, the piece", example: "Aprendí trozos, no tablas." },
      { es: "notarse", en: "to show, to be noticeable", example: "Quiero que me digas si notas el cambio." },
      { es: "el subjuntivo", en: "the subjunctive", example: "Usé el subjuntivo toda la semana sin saberlo." },
    ],
    dialogue: {
      title: "Nadie dijo la palabra",
      situation: "Repaso del jueves, con las cinco frases de la semana en la mesa",
      lines: [
        { speaker: "B", es: "Bueno, repaso. ¿Sabes qué hiciste esta semana?", en: "Okay, recap. Do you know what you did this week?" },
        { speaker: "A", es: "Organicé una noche para cuarenta personas. Y pedí muchísimas cosas.", en: "I organized a night for forty people. And I asked for a huge number of things." },
        { speaker: "B", es: "Usaste el subjuntivo unas doscientas veces. ¿En algún momento pensaste en la conjugación?", en: "You used the subjunctive about two hundred times. Did you think about the conjugation at any point?" },
        { speaker: "A", es: "Ni una vez. Necesito que me expliques por qué esto ya no me cuesta.", en: "Not once. I need you to explain to me why this doesn't feel hard anymore." },
        { speaker: "B", es: "Porque no aprendiste una tabla. Aprendiste cinco comienzos y los usaste todo el día.", en: "Because you didn't learn a table. You learned five openers and used them all day." },
        { speaker: "A", es: "Prefiero que sigamos con frases y no con reglas. De verdad.", en: "I'd rather we kept going with phrases and not rules. Really." },
        { speaker: "B", es: "Ese es el plan de todo el invierno. Cuatro semanas de subjuntivo y ninguna tabla.", en: "That's the plan for all of winter. Four weeks of subjunctive and not one table." },
        { speaker: "A", es: "Me gustaría que alguien me hubiera enseñado esto así antes. Y me gustaría que mis estudiantes tuvieran algo parecido.", en: "I wish someone had taught me this way earlier. And I'd love it if my students had something similar." },
        { speaker: "B", es: "Constrúyeselo. ¿Quieres que empecemos la próxima con el tiempo futuro? Cuando llegues, en cuanto termines, hasta que pase.", en: "Build it for them. Do you want us to start next week with future time? When you arrive, as soon as you finish, until it happens." },
      ],
    },
  },
];
