import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 1 — "El intercambio" (days 183–189).
 *
 * New cast for the season: Camila, a Colombian nurse who works nights at a
 * hospital in Boston and wants to practice her English. They meet Thursdays at
 * a café — thirty minutes in Spanish, thirty in English. Six installments,
 * then a fresh recap on the repaso day.
 */
export const invWeek1ReadingDays: ReadingDay[] = [
  {
    day: 183,
    themeEs: "El primer intercambio",
    storyTitle: "El intercambio",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el intercambio", en: "the language exchange", example: "Quedamos en hacer un intercambio los jueves." },
      { es: "quedarse callada", en: "to go quiet", example: "Entiendo la pregunta y me quedo callada." },
      { es: "el turno de noche", en: "the night shift", example: "Camila trabaja el turno de noche en el hospital." },
      { es: "por turnos", en: "taking turns", example: "Hablamos por turnos: media hora cada idioma." },
      { es: "la muletilla", en: "the filler word", example: "Una muletilla no significa nada y sirve para todo." },
    ],
    dialogue: {
      title: "Media hora cada una",
      situation: "En un café, la primera tarde de jueves",
      lines: [
        { speaker: "B", es: "¿Marlana? Soy Camila. Qué bueno conocerte por fin.", en: "Marlana? I'm Camila. So good to finally meet you." },
        { speaker: "A", es: "Igualmente. Pues, la verdad es que nunca había hecho un intercambio.", en: "Likewise. Well, honestly, I'd never done a language exchange before." },
        { speaker: "B", es: "Tranquila, es fácil. Media hora en español, media hora en inglés. ¿Te parece?", en: "Relax, it's easy. Half an hour in Spanish, half an hour in English. Sound good?" },
        { speaker: "A", es: "Bueno, empecemos por algo fácil. Yo soy maestra de inglés aquí en Boston.", en: "Okay, let's start with something easy. I'm an English teacher here in Boston." },
        { speaker: "B", es: "Ah, mira. Entonces sabes lo que es tener la cabeza llena y la boca cerrada.", en: "Oh, look at that. So you know what it's like to have a full head and a closed mouth." },
        { speaker: "A", es: "Exacto. Es que entiendo todo y luego me quedo callada. Perdón, es que…", en: "Exactly. The thing is, I understand everything and then I go quiet. Sorry, it's just…" },
        { speaker: "B", es: "No, no. Aquí no se pide perdón. Cuando no te salga algo, di \"pues\" y sigue.", en: "No, no. We don't apologize here. When something won't come out, say \"pues\" and keep going." },
        { speaker: "A", es: "¿Solo eso? ¿\"Pues\"?", en: "Just that? \"Pues\"?" },
        { speaker: "B", es: "Solo eso. Es una muletilla: no significa nada y te regala un segundo entero.", en: "Just that. It's a filler: it means nothing and it gives you a whole second." },
      ],
    },
  },
  {
    day: 184,
    themeEs: "Ganar tiempo",
    storyTitle: "El intercambio",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "quedarse en blanco", en: "to go blank", example: "Me hizo una pregunta y me quedé en blanco." },
      { es: "apurarse", en: "to rush", example: "Si me apuro, se me olvida todo." },
      { es: "por partes", en: "in pieces, bit by bit", example: "Te lo cuento por partes para no enredarme." },
      { es: "contestar", en: "to answer", example: "El problema no es entender, es contestar." },
      { es: "estar acostumbrada a", en: "to be used to", example: "Estoy acostumbrada a leer, no a hablar." },
    ],
    dialogue: {
      title: "Dame un segundo",
      situation: "El segundo jueves, mismo café, misma mesa",
      lines: [
        { speaker: "B", es: "Cuéntame algo de verdad. ¿Qué haces cuando sales del colegio?", en: "Tell me something real. What do you do when you leave school?" },
        { speaker: "A", es: "…", en: "…" },
        { speaker: "B", es: "Te quedaste en blanco.", en: "You went blank." },
        { speaker: "A", es: "A ver, dame un segundo y te contesto. Pues, depende del día, la verdad.", en: "Let's see, give me a second and I'll answer you. Well, it depends on the day, honestly." },
        { speaker: "B", es: "¡Eso! Mucho mejor. No te callaste, ganaste tiempo.", en: "There! Much better. You didn't go quiet, you bought time." },
        { speaker: "A", es: "Es que en mi cabeza la frase ya está lista, pero tarda en salir.", en: "The thing is, in my head the sentence is already finished, but it takes a while to come out." },
        { speaker: "B", es: "Entonces no te apures. Empieza con \"bueno\" y armas la frase mientras hablas.", en: "Then don't rush. Start with \"bueno\" and build the sentence while you talk." },
        { speaker: "A", es: "Bueno, déjame pensarlo un segundo… ahora mismo estoy con un proyecto de código.", en: "Okay, let me think about it for a second… right now I'm working on a coding project." },
        { speaker: "B", es: "¿Ves? Ahí no hubo silencio. Hubo una persona pensando en voz alta.", en: "See? There was no silence there. There was a person thinking out loud." },
      ],
    },
  },
  {
    day: 185,
    themeEs: "No encuentro la palabra",
    storyTitle: "El intercambio",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "se me fue la palabra", en: "the word left me", example: "Iba a decirlo y se me fue la palabra." },
      { es: "rodear una palabra", en: "to talk around a word", example: "Si no me sale, la rodeo y sigo hablando." },
      { es: "la engrapadora", en: "the stapler", example: "La engrapadora está en el escritorio, junto a las hojas." },
      { es: "para qué sirve", en: "what it's for", example: "Olvidé el nombre, pero sé para qué sirve." },
      { es: "unir hojas", en: "to put pages together", example: "Es lo que usas para unir hojas." },
    ],
    dialogue: {
      title: "Esa cosa del escritorio",
      situation: "Marlana cuenta cómo prepara sus clases",
      lines: [
        { speaker: "A", es: "El domingo imprimo todo y después uso… pues, se me fue la palabra.", en: "On Sunday I print everything and then I use… well, the word left me." },
        { speaker: "B", es: "No importa. Descríbemela.", en: "Doesn't matter. Describe it to me." },
        { speaker: "A", es: "Bueno, olvidé el nombre, pero sé para qué sirve. O sea, es lo que usas para unir hojas.", en: "Okay, I forgot the name, but I know what it's for. I mean, it's what you use to put pages together." },
        { speaker: "B", es: "Ajá, sigue.", en: "Mm-hm, go on." },
        { speaker: "A", es: "O sea, no es una grapa, es lo que pone las grapas. A ver, ¿cómo se llama eso en español?", en: "I mean, it's not a staple, it's what puts the staples in. Let's see, what do you call that in Spanish?" },
        { speaker: "B", es: "La engrapadora. Aunque en España dicen grapadora, y en otros lados también.", en: "La engrapadora. Though in Spain they say grapadora, and in some other places too." },
        { speaker: "A", es: "Es que la uso todos los días y no sé su nombre. Qué vergüenza.", en: "The thing is, I use it every day and I don't know its name. How embarrassing." },
        { speaker: "B", es: "Nada de vergüenza. Me la describiste completa y yo te di la palabra. Así funciona.", en: "Nothing embarrassing about it. You described it fully and I gave you the word. That's how it works." },
      ],
    },
  },
  {
    day: 186,
    themeEs: "Explicarlo de otra manera",
    storyTitle: "El intercambio",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "acabar de llegar", en: "to have just arrived", example: "Mis estudiantes son adultos que acaban de llegar." },
      { es: "reformular", en: "to rephrase", example: "Si no me entienden, reformulo en vez de repetir." },
      { es: "sobrevivir el día", en: "to get through the day", example: "No enseño gramática, enseño a sobrevivir el día." },
      { es: "al revés", en: "backwards, the other way around", example: "Enseñar y aprender son lo mismo visto al revés." },
      { es: "explicarse bien", en: "to explain oneself well", example: "No me expliqué bien, lo repito." },
    ],
    dialogue: {
      title: "Del otro lado de la misma clase",
      situation: "Camila no entiende bien en qué consiste el trabajo de Marlana",
      lines: [
        { speaker: "B", es: "Espera. ¿Les enseñas inglés a personas que ya son adultas? ¿Como en la universidad?", en: "Wait. You teach English to people who are already adults? Like at a university?" },
        { speaker: "A", es: "Bueno, no me expliqué bien, lo repito. Pues, mis estudiantes son adultos que acaban de llegar.", en: "Okay, I didn't explain it well, let me say it again. Well, my students are adults who just arrived." },
        { speaker: "B", es: "Ah, o sea, gente recién llegada al país.", en: "Ah, I mean, people who've just arrived in the country." },
        { speaker: "A", es: "Exacto. O sea, no enseño gramática, enseño a sobrevivir el día.", en: "Exactly. I mean, I don't teach grammar, I teach getting through the day." },
        { speaker: "B", es: "Ya te entiendo. Como cuando yo llegué y no sabía pedir una cita médica.", en: "Now I get you. Like when I arrived and didn't know how to make a doctor's appointment." },
        { speaker: "A", es: "Eso mismo. Es que yo también me quedo callada en otro idioma. Por eso los entiendo.", en: "That's it exactly. The thing is, I go quiet in another language too. That's why I understand them." },
        { speaker: "B", es: "Entonces esto que hacemos aquí es tu propia clase, pero al revés.", en: "So what we're doing here is your own class, but backwards." },
        { speaker: "A", es: "A ver, ¿me entiendes si lo digo así? O sea, yo estoy del otro lado de la misma clase.", en: "Let's see, do you follow me if I put it like that? I mean, I'm on the other side of the same class." },
        { speaker: "B", es: "Perfectamente. Y ahora sí lo dijiste en tres frases, no en diez.", en: "Perfectly. And this time you said it in three sentences, not ten." },
      ],
    },
  },
  {
    day: 187,
    themeEs: "Cuando me trabo",
    storyTitle: "El intercambio",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "trabarse", en: "to get stuck (mid-sentence)", example: "Me trabo justo en la parte importante." },
      { es: "enredarse", en: "to get tangled up", example: "Me enredé y tuve que empezar otra vez." },
      { es: "perder el hilo", en: "to lose the thread", example: "Bueno, ya perdí el hilo." },
      { es: "empezar de nuevo", en: "to start over", example: "A ver, déjame empezar de nuevo." },
      { es: "sin saber", en: "without knowing", example: "Empecé la frase sin saber cómo terminarla." },
    ],
    dialogue: {
      title: "Borrón y cuenta nueva",
      situation: "A mitad de una historia larga sobre el colegio",
      lines: [
        { speaker: "A", es: "El martes la directora me dijo que los materiales que yo había pedido para la clase que…", en: "On Tuesday the principal told me that the materials I had ordered for the class that…" },
        { speaker: "A", es: "Bueno, ya perdí el hilo. Es que empecé la frase sin saber cómo terminarla.", en: "Okay, I've lost the thread. The thing is, I started the sentence without knowing how to end it." },
        { speaker: "B", es: "Y ahí normalmente te pasarías al inglés, ¿verdad?", en: "And normally that's where you'd switch to English, right?" },
        { speaker: "A", es: "Normalmente sí. Hoy no. A ver, déjame empezar de nuevo.", en: "Normally yes. Not today. Let's see, let me start over." },
        { speaker: "B", es: "Eso. Borrón y cuenta nueva, en español.", en: "That's it. Clean slate, in Spanish." },
        { speaker: "A", es: "Pedí materiales. No llegaron. La directora me avisó el martes. Fin.", en: "I ordered materials. They didn't arrive. The principal told me on Tuesday. The end." },
        { speaker: "B", es: "¡Cuatro frases cortas! Se entendió todo.", en: "Four short sentences! It was all clear." },
        { speaker: "A", es: "Es que cuando me pongo nerviosa, hablo más rápido y me enredo.", en: "The thing is, when I get nervous, I talk faster and I get tangled." },
        { speaker: "B", es: "Entonces frases cortas. Y si te trabas, \"a ver\" y otra vez. Nunca inglés.", en: "So short sentences. And if you get stuck, \"a ver\" and again. Never English." },
      ],
    },
  },
  {
    day: 188,
    themeEs: "Ya no pido perdón",
    storyTitle: "El intercambio",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "disculparse", en: "to apologize", example: "Hoy no me disculpé ni una vez." },
      { es: "ni una vez", en: "not even once", example: "No dijiste perdón ni una vez." },
      { es: "frenar", en: "to brake, to slow to a stop", example: "No hablo mejor, hablo sin frenar." },
      { es: "llenar la pausa", en: "to fill the pause", example: "Aprendí a llenar la pausa con una palabra." },
      { es: "darse cuenta", en: "to realize, to notice", example: "No me di cuenta hasta que Camila lo dijo." },
    ],
    dialogue: {
      title: "Nadie te estaba corrigiendo",
      situation: "Al final de la sexta sesión, guardando las cosas",
      lines: [
        { speaker: "B", es: "Marlana, ¿te diste cuenta de algo hoy?", en: "Marlana, did you notice something today?" },
        { speaker: "A", es: "A ver… no sé. ¿Hablé más?", en: "Let's see… I don't know. Did I talk more?" },
        { speaker: "B", es: "No dijiste \"perdón\" ni una vez. En media hora entera, ni una.", en: "You didn't say \"sorry\" once. In a whole half hour, not one." },
        { speaker: "A", es: "Pues, hoy no me disculpé ni una vez. No me había dado cuenta.", en: "Well, today I didn't apologize once. I hadn't realized." },
        { speaker: "B", es: "Y sonaste mucho más suelta. ¿Sabes por qué?", en: "And you sounded much freer. Do you know why?" },
        { speaker: "A", es: "O sea, no hablo mejor, hablo sin frenar. Es que cada disculpa me sacaba del español.", en: "I mean, I don't speak better, I speak without braking. The thing is, every apology pulled me out of Spanish." },
        { speaker: "B", es: "Exacto. Y es que nadie te estaba corrigiendo. Solo tú.", en: "Exactly. And the thing is, nobody was correcting you. Only you." },
        { speaker: "A", es: "Bueno, no fue perfecto y no importa. A ver si el próximo jueves hablo cuarenta minutos.", en: "Okay, it wasn't perfect and it doesn't matter. Let's see if next Thursday I talk for forty minutes." },
        { speaker: "B", es: "Trato hecho. Y la próxima te enseño las muletillas que uso yo.", en: "Deal. And next time I'll teach you the fillers I use." },
      ],
    },
  },
  {
    day: 189,
    themeEs: "Repaso: Muletillas I",
    isRecap: true,
    vocab: [
      { es: "el resumen", en: "the recap, the summary", example: "Bueno, hagamos el resumen de la semana." },
      { es: "servir", en: "to be useful, to help", example: "Lo que más me sirvió fue no callarme." },
      { es: "el hueco", en: "the gap", example: "Sonar natural es no dejar huecos." },
      { es: "la fluidez", en: "fluency", example: "La fluidez empieza por no parar." },
      { es: "subir el nivel", en: "to raise the level", example: "La próxima semana subo el nivel." },
    ],
    dialogue: {
      title: "Cinco palabras",
      situation: "Repaso de la semana, con las cinco muletillas sobre la mesa",
      lines: [
        { speaker: "B", es: "Bueno, hagamos el resumen de la semana. ¿Qué te llevas?", en: "Okay, let's do the week's recap. What are you taking away?" },
        { speaker: "A", es: "Pues, lo que más me sirvió fue no callarme.", en: "Well, what helped me most was not going quiet." },
        { speaker: "B", es: "¿Y las cinco palabritas? Pues, bueno, o sea, es que, a ver.", en: "And the five little words? Pues, bueno, o sea, es que, a ver." },
        { speaker: "A", es: "Es que estas palabritas no significan nada y sirven para todo.", en: "The thing is, these little words mean nothing and are good for everything." },
        { speaker: "B", es: "Y ya las usas sin pensar. Llevas cuatro en esta conversación.", en: "And you use them without thinking now. You've used four in this conversation." },
        { speaker: "A", es: "O sea, no gané vocabulario, gané tiempo.", en: "I mean, I didn't gain vocabulary, I gained time." },
        { speaker: "B", es: "Esa es la lección entera. La fluidez empieza por no parar, no por hablar rápido.", en: "That's the whole lesson. Fluency starts with not stopping, not with talking fast." },
        { speaker: "A", es: "A ver, ¿cuál me falta practicar más?", en: "Let's see, which one do I still need to practice most?" },
        { speaker: "B", es: "\"O sea\". La usas para corregirte, pero también sirve para explicar mejor. Eso viene la próxima.", en: "\"O sea.\" You use it to correct yourself, but it also works to explain better. That's coming next time." },
      ],
    },
  },
];
