import type { ReadingDay } from "../../readings/types";

/**
 * Invierno Week 3 — "Sin cara, solo voz" (days 197–203).
 * Camila's night shifts move the exchange onto the phone, and Marlana finally
 * makes the school calls she'd been putting off. Cell-phone Spanish throughout:
 * dropped signal, speakerphone, voicemail, calling back.
 */
export const invWeek3ReadingDays: ReadingDay[] = [
  {
    day: 197,
    themeEs: "Sin cara, solo voz",
    storyTitle: "Sin cara, solo voz",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la señal", en: "the signal", example: "Aquí adentro no entra bien la señal." },
      { es: "el altavoz", en: "the speakerphone", example: "Te puse en altavoz para escucharte mejor." },
      { es: "cortarse", en: "to drop, to cut out", example: "Se cortó la llamada dos veces." },
      { es: "los audífonos", en: "headphones, earbuds", example: "Espera, me pongo los audífonos." },
      { es: "de corrido", en: "in one go, without stopping", example: "Ya me sale de corrido." },
    ],
    dialogue: {
      title: "Esta semana por teléfono",
      situation: "Camila llama desde el hospital antes de su turno",
      lines: [
        { speaker: "A", es: "¿Aló? Camila, ¿eres tú?", en: "Hello? Camila, is that you?" },
        { speaker: "B", es: "Soy yo. Esta semana me cambiaron todos los turnos, así que nos toca por teléfono.", en: "It's me. They changed all my shifts this week, so we're doing it by phone." },
        { speaker: "A", es: "Ay, no. Por teléfono es distinto. No te veo la boca.", en: "Oh no. The phone is different. I can't see your mouth." },
        { speaker: "B", es: "Exacto, y por eso es la mejor práctica. Sin cara, solo voz.", en: "Exactly, and that's why it's the best practice. No face, just voice." },
        { speaker: "A", es: "¿Me escuchas? Creo que se escucha mal.", en: "Can you hear me? I think the line's bad." },
        { speaker: "B", es: "Te escucho bien. Y mira, ya usaste la frase más útil del teléfono.", en: "I can hear you fine. And look, you already used the most useful phone sentence there is." },
        { speaker: "A", es: "¿Esa? Pero es que de verdad no sabía si me oías.", en: "That one? But I really didn't know if you could hear me." },
        { speaker: "B", es: "Por eso sirve. Te da tiempo y arregla la llamada. Ahora dime: ¿qué llamadas tienes que hacer esta semana?", en: "That's why it works. It buys you time and fixes the call. Now tell me: what calls do you have to make this week?" },
        { speaker: "A", es: "Tengo que llamar a la mamá de un estudiante. Llevo tres semanas evitándolo.", en: "I have to call a student's mother. I've been avoiding it for three weeks." },
      ],
    },
  },
  {
    day: 198,
    themeEs: "La mamá de Yusuf",
    storyTitle: "Sin cara, solo voz",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "hablo con", en: "am I speaking with", example: "¿Aló? ¿Hablo con la señora Amina?" },
      { es: "nada grave", en: "nothing serious", example: "Le habla del colegio, no es nada grave." },
      { es: "colgar", en: "to hang up", example: "Ya colgué con ella, te cuento." },
      { es: "el horario", en: "the schedule", example: "La llamé por el horario nuevo." },
      { es: "de usted", en: "on formal terms", example: "Con ella hablo de usted, no de tú." },
    ],
    dialogue: {
      title: "Le habla la maestra de su hijo",
      situation: "Marlana llama a la mamá de Yusuf y le cuenta a Camila después",
      lines: [
        { speaker: "A", es: "La llamé. Empecé así: ¿Aló? Buenas tardes, ¿hablo con la señora Amina?", en: "I called her. I started like this: Hello? Good afternoon, am I speaking with Mrs. Amina?" },
        { speaker: "B", es: "Perfecto. Y de usted, ¿verdad? Con una mamá siempre de usted.", en: "Perfect. And on usted, right? With a mother, always usted." },
        { speaker: "A", es: "De usted todo el tiempo. Le habla del colegio, no es nada grave, le dije primero.", en: "Usted the whole time. \"This is the school calling, it's nothing serious,\" I said first." },
        { speaker: "B", es: "Ay, qué bien. Eso se agradece. Una mamá siempre piensa lo peor.", en: "Oh, that's good. That's appreciated. A mother always thinks the worst." },
        { speaker: "A", es: "Y a mitad de la llamada se cortó cuando le estaba explicando el horario.", en: "And halfway through, it cut out while I was explaining the schedule to her." },
        { speaker: "B", es: "¿Y qué hiciste?", en: "And what did you do?" },
        { speaker: "A", es: "La volví a llamar enseguida. Y le pregunté: ¿me escucha, señora? Se oye un poco cortado.", en: "I called her right back. And I asked: can you hear me, ma'am? You're coming through a bit choppy." },
        { speaker: "B", es: "¡Ahí está! Escucha**s** con tú, escucha con usted. Una letra menos y ya.", en: "There it is! *Escuchas* with tú, *escucha* with usted. One letter less and that's it." },
        { speaker: "A", es: "Y funcionó. Hablamos siete minutos. Ni una palabra en inglés.", en: "And it worked. We talked for seven minutes. Not one word in English." },
      ],
    },
  },
  {
    day: 199,
    themeEs: "La persona que contesta",
    storyTitle: "Sin cara, solo voz",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "comunicar con", en: "to put through to", example: "¿Me puede comunicar con la persona que agenda?" },
      { es: "agendar una cita", en: "to schedule an appointment", example: "Llamé para agendar una cita." },
      { es: "en espera", en: "on hold", example: "Me tuvieron veinte minutos en espera." },
      { es: "de parte de", en: "on behalf of", example: "Llamo de parte de una familia." },
      { es: "el consultorio", en: "the doctor's office", example: "El consultorio cierra a las cinco." },
    ],
    dialogue: {
      title: "No soy familiar, soy la maestra",
      situation: "Marlana llama a una clínica para ayudar a una familia",
      lines: [
        { speaker: "A", es: "Hoy llamé a la clínica por la familia de Yusuf. Y ahí aprendí algo nuevo.", en: "Today I called the clinic for Yusuf's family. And I learned something new there." },
        { speaker: "B", es: "Ajá, cuéntame.", en: "Mm-hm, tell me." },
        { speaker: "A", es: "Dije: ¿Aló? ¿Me puede comunicar con la persona que agenda las citas?", en: "I said: Hello? Could you put me through to the person who schedules appointments?" },
        { speaker: "B", es: "Muy bien. \"Comunicar con\" es exactamente eso. ¿Y te pasaron?", en: "Very good. \"Comunicar con\" is exactly it. And did they put you through?" },
        { speaker: "A", es: "Primero me preguntaron dos veces: ¿de parte de quién? Y ahí me trabé.", en: "First they asked me twice: who's calling? And that's where I got stuck." },
        { speaker: "B", es: "Claro, porque tú no eres la familia.", en: "Of course, because you're not the family." },
        { speaker: "A", es: "Exacto. Al final dije: de la maestra, no de la familia. Le habla una maestra que ayuda a la familia con el idioma.", en: "Exactly. In the end I said: from the teacher, not from the family. This is a teacher who helps the family with the language." },
        { speaker: "B", es: "Perfecto. Eso abre puertas. ¿Y funcionó?", en: "Perfect. That opens doors. And did it work?" },
        { speaker: "A", es: "Se cortó mientras me tenían en espera. Volví a llamar y la tercera vez ya me dio risa.", en: "It dropped while they had me on hold. I called back and by the third time it made me laugh." },
      ],
    },
  },
  {
    day: 200,
    themeEs: "No te escucho",
    storyTitle: "Sin cara, solo voz",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la barra de señal", en: "the signal bar", example: "Tengo una sola barra de señal." },
      { es: "el pasillo", en: "the hallway", example: "En el pasillo no entra la señal." },
      { es: "deletrear", en: "to spell out", example: "Le deletreé mi apellido letra por letra." },
      { es: "la videollamada", en: "the video call", example: "Mejor te marco por videollamada." },
      { es: "marcar", en: "to call, to dial", example: "Te marco en cinco minutos." },
    ],
    dialogue: {
      title: "M de mamá",
      situation: "Camila llama mientras Marlana camina por el colegio",
      lines: [
        { speaker: "B", es: "¿Marlana? Se te oye horrible.", en: "Marlana? You sound terrible." },
        { speaker: "A", es: "¿Aló? Espérame, voy saliendo del pasillo. Aquí adentro no entra bien la señal.", en: "Hello? Hang on, I'm coming out of the hallway. The signal doesn't come in well in here." },
        { speaker: "B", es: "Ya. Avísame cuando salgas.", en: "Okay. Let me know when you're out." },
        { speaker: "A", es: "Ya salí. ¿Me escuchas? Te puse en altavoz.", en: "I'm out. Can you hear me? I've got you on speaker." },
        { speaker: "B", es: "Ahora sí, clarito. Oye, ¿y la llamada de la clínica?", en: "Now yes, crystal clear. Hey, what about the clinic call?" },
        { speaker: "A", es: "Tuve que deletrear mi apellido. Dije: le habla Marlana, M de mamá, a-r-l.", en: "I had to spell my last name. I said: this is Marlana, M as in mamá, a-r-l." },
        { speaker: "B", es: "¡Perfecto! Así se hace en español. Una palabra por letra.", en: "Perfect! That's how it's done in Spanish. One word per letter." },
        { speaker: "A", es: "Se cortó tres veces en el mismo pasillo. Ya sé exactamente dónde pasa.", en: "It dropped three times in the same hallway. Now I know exactly where it happens." },
        { speaker: "B", es: "Entonces ya no es problema del idioma. Es problema del edificio.", en: "So it's not a language problem anymore. It's a building problem." },
      ],
    },
  },
  {
    day: 201,
    themeEs: "Se cortó",
    storyTitle: "Sin cara, solo voz",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "¿en qué estábamos?", en: "where were we?", example: "¿Aló? ¿En qué estábamos?" },
      { es: "volver a llamar", en: "to call back", example: "Se cortó y volví a llamar enseguida." },
      { es: "reconocer la voz", en: "to recognize the voice", example: "No reconocí la voz al principio." },
      { es: "lo último que dije", en: "the last thing I said", example: "Repito lo último que dije." },
      { es: "sin pena", en: "without embarrassment", example: "Ya vuelvo a marcar sin pena." },
    ],
    dialogue: {
      title: "No fuiste tú ni fui yo",
      situation: "Cuarta llamada de la semana, y la línea vuelve a caerse",
      lines: [
        { speaker: "A", es: "…y entonces la directora dijo que el salón nuevo iba a estar listo el—", en: "…and then the principal said the new room was going to be ready on—" },
        { speaker: "B", es: "¿Aló? ¿Marlana?", en: "Hello? Marlana?" },
        { speaker: "A", es: "¿Aló? ¿En qué estábamos?", en: "Hello? Where were we?" },
        { speaker: "B", es: "Te perdí en \"el salón nuevo\". Se cortó.", en: "I lost you at \"the new room\". It dropped." },
        { speaker: "A", es: "Se cortó, no fuiste tú ni fui yo. ¿Me escuchas? Repito lo último que dije.", en: "It dropped — it wasn't you and it wasn't me. Can you hear me? I'll repeat the last thing I said." },
        { speaker: "B", es: "Fíjate lo que acabas de hacer. Antes habrías empezado la historia desde el principio.", en: "Notice what you just did. Before, you'd have started the story from the beginning." },
        { speaker: "A", es: "Es verdad. Antes hasta habría cambiado al inglés.", en: "That's true. Before, I'd even have switched to English." },
        { speaker: "B", es: "Y ahora vuelves a marcar sin pena y sigues donde estabas. Eso es teléfono de verdad.", en: "And now you call back without embarrassment and pick up where you were. That's real phone talk." },
        { speaker: "A", es: "Se cortó cinco veces esta semana y cinco veces volví a llamar.", en: "It dropped five times this week and five times I called back." },
      ],
    },
  },
  {
    day: 202,
    themeEs: "Dejar un recado",
    storyTitle: "Sin cara, solo voz",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "el buzón de voz", en: "the voicemail", example: "Se cortó el buzón de voz a mitad del recado." },
      { es: "el recado", en: "the message", example: "Le dejé un recado con su nombre y mi número." },
      { es: "devolver la llamada", en: "to call back, to return a call", example: "Gracias por devolverme la llamada." },
      { es: "mandar al buzón", en: "to send to voicemail", example: "Me mandó directo al buzón." },
      { es: "dígale que", en: "tell her/him that", example: "Dígale que llamó la maestra." },
    ],
    dialogue: {
      title: "Quién, por qué y cuándo",
      situation: "Nadie contesta y Marlana tiene que dejar un mensaje",
      lines: [
        { speaker: "A", es: "Nadie contestó. Me mandó directo al buzón de voz y me quedé congelada.", en: "Nobody answered. It sent me straight to voicemail and I froze." },
        { speaker: "B", es: "Es normal. Un recado da más miedo que una llamada, porque no hay nadie ayudándote.", en: "That's normal. A message is scarier than a call, because there's nobody helping you." },
        { speaker: "A", es: "¿Y qué se dice? No sabía por dónde empezar.", en: "And what do you say? I didn't know where to start." },
        { speaker: "B", es: "Tres partes: quién eres, por qué llamas, y cuándo te pueden encontrar. Nada más.", en: "Three parts: who you are, why you're calling, and when they can reach you. Nothing else." },
        { speaker: "A", es: "Entonces: Le habla Marlana Creed, del colegio de su hijo. Llamo por el horario nuevo.", en: "So: This is Marlana Creed, from your son's school. I'm calling about the new schedule." },
        { speaker: "B", es: "Exacto. Y la tercera parte.", en: "Exactly. And the third part." },
        { speaker: "A", es: "Le habla Marlana, puede llamarme hasta las cuatro. ¡Se cortó el buzón de voz a mitad del recado!", en: "This is Marlana, you can reach me until four. And the voicemail cut out halfway through the message!" },
        { speaker: "B", es: "Ajá, siempre pasa. ¿Y qué hiciste?", en: "Mm-hm, that always happens. And what did you do?" },
        { speaker: "A", es: "Llamé otra vez y lo dejé completo. Tres partes, treinta segundos, en español.", en: "I called again and left it complete. Three parts, thirty seconds, in Spanish." },
      ],
    },
  },
  {
    day: 203,
    themeEs: "Repaso: Al teléfono",
    isRecap: true,
    vocab: [
      { es: "congelarse", en: "to freeze up", example: "Antes esa pregunta me congelaba." },
      { es: "salir de corrido", en: "to come out in one go", example: "Ya me sale de corrido, sin ensayar." },
      { es: "sin ensayar", en: "without rehearsing", example: "Lo dije sin ensayar antes." },
      { es: "el desastre", en: "the disaster", example: "Ya no lo viví como un desastre." },
      { es: "quitar", en: "to take away", example: "Una llamada cortada no me quita el español." },
    ],
    dialogue: {
      title: "Cuatro llamadas, ninguna en inglés",
      situation: "Repaso del jueves, contando las llamadas de la semana",
      lines: [
        { speaker: "B", es: "Bueno, repaso. ¿Cuántas llamadas hiciste en español esta semana?", en: "Okay, recap. How many calls did you make in Spanish this week?" },
        { speaker: "A", es: "Cuatro. Y ninguna en inglés. ¿Aló? Contesto sin mirar quién llama.", en: "Four. And none in English. Hello? I answer without looking at who's calling." },
        { speaker: "B", es: "Eso es lo grande. Antes revisabas el nombre primero para prepararte.", en: "That's the big thing. Before, you'd check the name first to prepare yourself." },
        { speaker: "A", es: "Le habla Marlana: lo dije cuatro veces esta semana. Y ya me sale de corrido.", en: "This is Marlana: I said it four times this week. And it comes out in one go now." },
        { speaker: "B", es: "¿Y la pregunta que te congelaba?", en: "And the question that used to freeze you?" },
        { speaker: "A", es: "¿De parte de quién? Antes esa pregunta me congelaba. Ahora contesto sin pensar.", en: "Who's calling? That question used to freeze me. Now I answer without thinking." },
        { speaker: "B", es: "Ya. Y tu frase estrella de la semana, ¿cuál fue?", en: "Right. And your star sentence of the week, which was it?" },
        { speaker: "A", es: "¿Me escuchas? Fue mi frase más usada de la semana. Y con usted, ¿me escucha? Las dos me salen.", en: "Can you hear me? It was my most-used sentence of the week. And in usted, can you hear me? Both come out now." },
        { speaker: "B", es: "Se cortó cinco veces y volviste cinco veces. Eso es todo lo que el teléfono te iba a enseñar. La próxima: notas de voz.", en: "It dropped five times and you came back five times. That's everything the phone was going to teach you. Next up: voice notes." },
      ],
    },
  },
];
