import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 9 — "El problema de Rocío" (days 330–336).
 * Camila and Marlana keep one topic alive with follow-up chains while
 * Marlana learns what happened to Rocío at a parent conference.
 */
export const priWeek9ReadingDays: ReadingDay[] = [
  {
    day: 330,
    themeEs: "El problema de Rocío",
    storyTitle: "El problema de Rocío",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "profundizar", en: "to go deeper", example: "Esta semana toca profundizar, no soltar el tema." },
      { es: "el hilo", en: "the thread (of conversation)", example: "No dejes morir el hilo con solo \"qué mal.\"" },
      { es: "la reunión de padres", en: "the parent conference", example: "Rocío tuvo un problema en la reunión de padres." },
      { es: "qué mal", en: "that's too bad, what a shame", example: "Solo dije \"qué mal\" y la dejé ir." },
      { es: "soltar el tema", en: "to drop the subject", example: "Camila dice que suelto el tema demasiado rápido." },
    ],
    dialogue: {
      title: "En el pasillo",
      situation: "Jueves en el café — Marlana cuenta lo que pasó el martes",
      lines: [
        { speaker: "A", es: "El martes Rocío me paró en el pasillo. Cara de funeral. Dijo: \"Tuve un problema en la reunión de padres.\" Yo dije \"ay, qué mal\" y seguí a clase.", en: "Tuesday Rocío stopped me in the hallway. Funeral face. She said: \"I had a problem at the parent conference.\" I said \"oh, that's too bad\" and went on to class." },
        { speaker: "B", es: "¿Y eso? ¿Qué pasó en la reunión?", en: "And that? What happened at the meeting?" },
        { speaker: "A", es: "No lo sé. No pregunté.", en: "I don't know. I didn't ask." },
        { speaker: "B", es: "Marlana. Eso no es ser educada. Eso es soltar el hilo.", en: "Marlana. That's not being polite. That's dropping the thread." },
        { speaker: "A", es: "Tenía treinta segundos entre campanas.", en: "I had thirty seconds between bells." },
        { speaker: "B", es: "Treinta segundos bastan para *¿y eso?* Esta semana profundizas: ¿Y eso? · ¿Cómo así? · ¿Y qué pasó con…? · ¿Y después? · ¿En serio?", en: "Thirty seconds is enough for *and that?* This week you go deeper: And that? · How so? · And what happened with…? · And then? · Seriously?" },
        { speaker: "A", es: "Suena a entrometida.", en: "It sounds nosy." },
        { speaker: "B", es: "Suena a amiga. Rocío no te contó un dato, te contó un problema. Eso es una invitación.", en: "It sounds like a friend. Rocío didn't tell you a fact, she told you a problem. That's an invitation." },
        { speaker: "A", es: "Le mando un mensaje hoy.", en: "I'll text her today." },
        { speaker: "B", es: "No le mandes \"¿estás bien?\" Mandale *¿y eso? ¿Qué pasó en la reunión?*", en: "Don't send her \"are you okay?\" Send her *and that? what happened at the meeting?*" },
      ],
    },
  },
  {
    day: 331,
    themeEs: "¿Y eso?",
    storyTitle: "El problema de Rocío",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "¿y eso?", en: "and that? / how come?", example: "¿Y eso? ¿Qué problema tuvo Rocío?" },
      { es: "traducir", en: "to translate", example: "Le pidieron traducir sin avisar." },
      { es: "sin avisar", en: "without warning", example: "La metieron sin avisar." },
      { es: "el audio", en: "the voice note", example: "Rocío me mandó un audio de dos minutos." },
      { es: "quedarse con la culpa", en: "to be left feeling guilty", example: "Me quedé con la culpa de no preguntar." },
    ],
    dialogue: {
      title: "El audio de Rocío",
      situation: "Miércoles — Rocío responde; Marlana lo trae al café",
      lines: [
        { speaker: "A", es: "Rocío me mandó un audio. Dijo que le pidieron traducir en la reunión de padres.", en: "Rocío sent me a voice note. She said they asked her to translate at the parent conference." },
        { speaker: "B", es: "¿Y eso? ¿Te pidieron traducir en la reunión?", en: "And that? They asked you to translate at the meeting?" },
        { speaker: "A", es: "A ella. Sin avisar. Yo practiqué: *¿Y eso? ¿Qué problema tuvo Rocío?*", en: "Her. Without warning. I practiced: *And that? What problem did Rocío have?*" },
        { speaker: "B", es: "Bien. ¿Y qué más dijo?", en: "Good. And what else did she say?" },
        { speaker: "A", es: "Solo eso por ahora. Se cortó porque entró una maestra al baño.", en: "Just that for now. It cut off because a teacher walked into the bathroom." },
        { speaker: "B", es: "¿Cómo así? ¿Te dijo solo eso y ya?", en: "How so? She only told you that and left?" },
        { speaker: "A", es: "Sí. Y yo el martes hice lo mismo — solo \"qué mal.\"", en: "Yes. And Tuesday I did the same — just \"that's too bad.\"" },
        { speaker: "B", es: "¿En serio? ¿Solo dijiste \"qué mal\"?", en: "Seriously? You only said \"that's too bad\"?" },
        { speaker: "A", es: "¿En serio? Sí. Me quedé con la culpa toda la semana.", en: "Seriously? Yes. I've felt guilty all week." },
        { speaker: "B", es: "Hoy le mandas: *¿Y eso? ¿Sin avisarte antes?* Y esperas.", en: "Today you send her: *And that? Without telling you first?* And you wait." },
      ],
    },
  },
  {
    day: 332,
    themeEs: "¿Cómo así?",
    storyTitle: "El problema de Rocío",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "¿cómo así?", en: "how so? / how come?", example: "¿Cómo así? ¿La directora la agarró en la copiadora?" },
      { es: "la copiadora", en: "the copier", example: "Rocío estaba en la copiadora cuando la agarraron." },
      { es: "sin contexto", en: "without context", example: "La metieron a traducir sin contexto." },
      { es: "decir que no", en: "to say no", example: "Rocío no pudo decir que no." },
      { es: "el estipendio", en: "the stipend", example: "Le preocupa el estipendio bilingüe." },
    ],
    dialogue: {
      title: "En la copiadora",
      situation: "Rocío manda más audio; Marlana cuenta en el café",
      lines: [
        { speaker: "A", es: "Rocío contó el cómo. Estaba en la copiadora. La directora la agarró del brazo y dijo: \"Necesito que traduzcas, ya.\"", en: "Rocío told the how. She was at the copier. The principal grabbed her arm and said: \"I need you to translate, now.\"" },
        { speaker: "B", es: "¿Cómo así? ¿La directora la agarró en la copiadora?", en: "How so? The principal grabbed her at the copier?" },
        { speaker: "A", es: "Sin decirle de qué era la reunión. Sin la carpeta. Sin la maestra del salón.", en: "Without telling her what the meeting was about. No folder. No classroom teacher." },
        { speaker: "B", es: "¿En serio? ¿La meten así, sin preparación?", en: "Seriously? They pull her in like that, with no prep?" },
        { speaker: "A", es: "Rocío dice que no pudo decir que no. Que la directora ya estaba abriendo la puerta.", en: "Rocío says she couldn't say no. The principal was already opening the door." },
        { speaker: "B", es: "¿Y qué pasó con el papá cuando oyó la respuesta?", en: "And what happened with the dad when he heard the answer?" },
        { speaker: "A", es: "Eso viene en el próximo audio. Todavía no sé.", en: "That comes in the next voice note. I don't know yet." },
        { speaker: "B", es: "¿Y después? ¿Qué preguntó el papá?", en: "And then? What did the dad ask?" },
        { speaker: "A", es: "Mañana le pregunto. Hoy practiqué el *cómo así* y me salió natural.", en: "Tomorrow I'll ask her. Today I practiced *how so* and it came out natural." },
        { speaker: "B", es: "El cómo es donde vive la historia. Bien.", en: "The how is where the story lives. Good." },
      ],
    },
  },
  {
    day: 333,
    themeEs: "¿Y qué pasó con…?",
    storyTitle: "El problema de Rocío",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "¿y qué pasó con…?", en: "and what happened with…?", example: "¿Y qué pasó con el papá cuando leyó el correo?" },
      { es: "bajar de grupo", en: "to move down a group", example: "Bajaron a la niña de grupo de lectura." },
      { es: "sonar a", en: "to sound like", example: "Sonó a castigo para la niña." },
      { es: "el historial", en: "the history, the record", example: "Rocío no tenía el historial." },
      { es: "echar la culpa", en: "to blame", example: "¿Le echaron la culpa a Rocío?" },
    ],
    dialogue: {
      title: "La queja del papá",
      situation: "Rocío cuenta la reunión; Marlana no suelta el hilo",
      lines: [
        { speaker: "A", es: "Ya sé la parte del papá. Preguntó por qué bajaron a su hija de grupo de lectura.", en: "I know the dad part now. He asked why they moved his daughter down a reading group." },
        { speaker: "B", es: "¿Y eso? ¿Movieron a la niña de grupo?", en: "And that? They moved the girl down a group?" },
        { speaker: "A", es: "Sí. Rocío tradujo la pregunta sin saber que era apoyo extra, no castigo.", en: "Yes. Rocío translated the question without knowing it was extra support, not punishment." },
        { speaker: "B", es: "¿Cómo así? ¿Sonó a castigo para la niña?", en: "How so? Did it sound like punishment for the girl?" },
        { speaker: "A", es: "Exacto. El papá se puso furioso. Dijo que la escuela estaba humillando a su hija.", en: "Exactly. The dad got furious. He said the school was humiliating his daughter." },
        { speaker: "B", es: "¿Y qué pasó con la maestra que pidió el cambio de grupo?", en: "And what happened with the teacher who requested the group change?" },
        { speaker: "A", es: "Nunca entró a la reunión. Rocío tradujo sola.", en: "She never came into the meeting. Rocío translated alone." },
        { speaker: "B", es: "¿En serio? ¿Le echaron la culpa a Rocío?", en: "Seriously? They blamed Rocío?" },
        { speaker: "A", es: "Todavía no sé eso. Pero suena a usar a alguien, no a pedir un favor.", en: "I don't know that yet. But it sounds like using someone, not asking a favor." },
        { speaker: "B", es: "Pregúntale *¿y después?* Esa es la que falta.", en: "Ask her *and then?* That's the one you're missing." },
      ],
    },
  },
  {
    day: 334,
    themeEs: "¿Y después?",
    storyTitle: "El problema de Rocío",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "¿y después?", en: "and then? / what happened next?", example: "¿Y después? ¿Te mandaron un correo?" },
      { es: "pasarse de la raya", en: "to overstep, to go too far", example: "Le dijeron que se pasó de la raya." },
      { es: "por escrito", en: "in writing", example: "¿Te mandaron eso por escrito?" },
      { es: "el estipendio bilingüe", en: "the bilingual stipend", example: "Rocío pensó que le quitarían el estipendio." },
      { es: "la versión", en: "the version (of events)", example: "Nadie le preguntó su versión." },
    ],
    dialogue: {
      title: "El correo del miércoles",
      situation: "Marlana por fin habla con Rocío en la sala de maestros",
      lines: [
        { speaker: "A", es: "Hoy le pregunté en persona. *¿Y después?* Rocío bajó la voz: el miércoles le mandaron un correo.", en: "Today I asked her in person. *And then?* Rocío lowered her voice: Wednesday they sent her an email." },
        { speaker: "B", es: "¿Y eso? ¿Le mandaron un correo el mismo día?", en: "And that? They sent her an email the same day?" },
        { speaker: "A", es: "Diciendo que se pasó de la raya al traducir. Que \"excedió su rol.\"", en: "Saying she overstepped when she translated. That she \"exceeded her role.\"" },
        { speaker: "B", es: "¿Cómo así? ¿Le dijeron que \"se pasó de la raya\"?", en: "How so? They told her she \"overstepped\"?" },
        { speaker: "A", es: "Por correo. Sin reunión. Rocío pensó que le quitarían el estipendio bilingüe.", en: "By email. No meeting. Rocío thought they'd take away her bilingual stipend." },
        { speaker: "B", es: "¿En serio? ¿Te mandaron eso por escrito?", en: "Seriously? They sent you that in writing?" },
        { speaker: "A", es: "Se lo dije a Rocío tal cual. Se rió un poco — la primera risa de la semana.", en: "I said it to Rocío exactly like that. She laughed a little — the first laugh of the week." },
        { speaker: "B", es: "¿Y qué pasó con la directora después del correo?", en: "And what happened with the principal after the email?" },
        { speaker: "A", es: "Eso viene mañana. Rocío dijo que hay más.", en: "That comes tomorrow. Rocío said there's more." },
        { speaker: "B", es: "Ves. *¿Y después?* y la historia sigue.", en: "See. *And then?* and the story keeps going." },
      ],
    },
  },
  {
    day: 335,
    themeEs: "¿En serio?",
    storyTitle: "El problema de Rocío",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "¿en serio?", en: "seriously? / for real?", example: "¿En serio? Rocío, eso no está bien." },
      { es: "pedir disculpas", en: "to apologize", example: "La directora pidió disculpas." },
      { es: "el sistema", en: "the system", example: "Perdón pero mismo sistema." },
      { es: "quedarse hablando", en: "to keep talking", example: "Se quedaron hablando diez minutos." },
      { es: "sigue contando", en: "keep going, keep telling", example: "¿En serio? no es duda — es sigue contando." },
    ],
    dialogue: {
      title: "Diez minutos en el pasillo",
      situation: "Rocío cuenta el final; Marlana no cambia de tema",
      lines: [
        { speaker: "A", es: "Rocío me contó el final en el pasillo — diez minutos, campana sonando, nadie se movió.", en: "Rocío told me the ending in the hallway — ten minutes, bell ringing, nobody moved." },
        { speaker: "B", es: "¿Y eso? ¿La directora pidió disculpas?", en: "And that? The principal apologized?" },
        { speaker: "A", es: "El jueves. En persona. Pero *¿cómo así?* — perdón, mismo sistema. Ayer le volvieron a pedir traducir.", en: "Thursday. In person. But *how so?* — sorry, same system. Yesterday they asked her to translate again." },
        { speaker: "B", es: "¿En serio? ¿Te volvieron a pedir sin avisar?", en: "Seriously? They asked you again without warning?" },
        { speaker: "A", es: "Se lo dije tal cual. Rocío dijo: \"¿En serio? Marlana, eso no está bien.\" Y se rió otra vez.", en: "I said it exactly like that. Rocío said: \"Seriously? Marlana, that's not okay.\" And she laughed again." },
        { speaker: "B", es: "¿Y qué pasó con el grupo de lectura de la niña?", en: "And what happened with the girl's reading group?" },
        { speaker: "A", es: "La dejaron donde está. El papá recibió una carta explicando el apoyo.", en: "They left her where she is. The dad got a letter explaining the support." },
        { speaker: "B", es: "¿Y después? ¿Le ofreciste hablar con la directora?", en: "And then? Did you offer to talk to the principal?" },
        { speaker: "A", es: "Sí. Rocío dijo que no por ahora. Pero que nadie le había preguntado tanto en años.", en: "Yes. Rocío said not for now. But that nobody had asked her so much in years." },
        { speaker: "B", es: "Eso es profundizar. No entrometida — presente.", en: "That's going deeper. Not nosy — present." },
      ],
    },
  },
  {
    day: 336,
    themeEs: "Repaso: Profundizar",
    isRecap: true,
    vocab: [
      { es: "la misma historia, mejor", en: "the same story, better", example: "La misma historia, mejor — con más detalle." },
      { es: "cinco preguntas", en: "five questions", example: "Cinco preguntas y la historia completa." },
      { es: "no cambiar de tema", en: "not to change the subject", example: "Una semana entera sin cambiar de tema." },
      { es: "quedarse", en: "to stay (on a topic)", example: "Profundizar es quedarte, no ser entrometida." },
      { es: "el beat", en: "the beat (story moment)", example: "Cinco stems, cinco beats de una historia." },
    ],
    dialogue: {
      title: "La misma historia, mejor",
      situation: "Repaso en el café — Marlana retells Rocío's week with full detail",
      lines: [
        { speaker: "B", es: "Repaso. Cuéntame el problema de Rocío otra vez — entero.", en: "Recap. Tell me Rocío's problem again — the whole thing." },
        { speaker: "A", es: "¿Y eso? Rocío tuvo un problema en la reunión de padres. Me lo dijo en el pasillo y yo solo dije \"qué mal.\"", en: "And that? Rocío had a problem at the parent conference. She told me in the hallway and I only said \"that's too bad.\"" },
        { speaker: "B", es: "Sigue. ¿Cómo así?", en: "Go on. How so?" },
        { speaker: "A", es: "¿Cómo así? La directora la agarró en la copiadora sin contexto. La metieron a traducir una queja de un papá. Rocío no tenía la carpeta ni el historial.", en: "How so? The principal grabbed her at the copier with no context. They pulled her in to translate a father's complaint. Rocío didn't have the folder or the history." },
        { speaker: "B", es: "¿Y qué pasó con el papá?", en: "And what happened with the dad?" },
        { speaker: "A", es: "¿Y qué pasó con el papá? Preguntó por qué bajaron a la niña de grupo. Rocío tradujo sin saber que era apoyo, no castigo. Sonó a humillación.", en: "And what happened with the dad? He asked why they moved the girl down a group. Rocío translated without knowing it was support, not punishment. It sounded like humiliation." },
        { speaker: "B", es: "¿Y después?", en: "And then?" },
        { speaker: "A", es: "¿Y después? Le mandaron un correo diciendo que se pasó de la raya. Rocío pensó que le quitarían el estipendio bilingüe. La directora pidió disculpas, pero el sistema sigue igual.", en: "And then? They sent her an email saying she overstepped. Rocío thought they'd take away her bilingual stipend. The principal apologized, but the system is still the same." },
        { speaker: "B", es: "¿En serio? ¿Una semana entera y nunca cambiaste de tema?", en: "Seriously? A whole week and you never changed subject?" },
        { speaker: "A", es: "¿En serio? Cinco preguntas y la historia completa. Profundizar es quedarte, no ser entrometida.", en: "Seriously? Five questions and the whole story. Going deeper is staying, not being nosy." },
      ],
    },
  },
];
