import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 13 — "La última clase" (days 358–364). The year capstone.
 * Each `spanish` is copied verbatim from content/drafts/primavera/week13-frames.ts
 * for the matching `frameStem` (convention 2).
 *
 * The end-of-year potluck for the evening class the district tried to cut in
 * week 8. Five stems, one from each movement of the season. The year is the
 * subtext of this week and never its topic — not one sentence here is about
 * having practiced.
 */
export const priWeek13SpeakDays: SpeakDay[] = [
  {
    day: 358,
    themeEs: "El salón a las seis",
    themeEn: "The classroom at six",
    missionEs: "Una hora antes. Organiza el salón discutiendo con Rocío.",
    missionEn: "One hour to go. Set up the room by arguing with Rocío about it.",
    line: "Cuarenta sillas, dos maestras, y nadie sabe cuánta gente viene.",
    lineEn: "Forty chairs, two teachers, and nobody knows how many are coming.",
    prompts: [
      {
        id: "d358-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I've never done one of these and I don't know how many people are coming.",
        spanish: "La verdad es que nunca he hecho una de estas y no sé cuánta gente viene.",
        situationLabel: "Una hora antes",
        why: "*Cuánta gente* — *gente* is singular in Spanish, so the adjective agrees with it and not with the crowd.",
        wordHints: [
          { en: "i've never done", es: "nunca he hecho" },
          { en: "one of these", es: "una de estas" },
          { en: "how many people", es: "cuánta gente" },
        ],
      },
      {
        id: "d358-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — the tablecloth looks fine.",
        spanish: "Te estoy tomando el pelo, el mantel se ve bien.",
        situationLabel: "Rocío y el mantel",
        why: "*Se ve bien* rather than *está bien* — how it looks, not whether it's acceptable. Gentler, and more spoken.",
        wordHints: [
          { en: "the tablecloth", es: "el mantel" },
          { en: "looks fine", es: "se ve bien" },
        ],
      },
      {
        id: "d358-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but if we put the chairs in rows nobody's going to talk.",
        spanish: "Entiendo tu punto, pero si ponemos las sillas en filas nadie va a hablar.",
        situationLabel: "Cómo poner las sillas",
        why: "A real disagreement about a real thing, an hour before people arrive. That's what week 5 was for.",
        wordHints: [
          { en: "if we put", es: "si ponemos" },
          { en: "in rows", es: "en filas" },
          { en: "nobody's going to talk", es: "nadie va a hablar" },
        ],
      },
      {
        id: "d358-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is putting the food in the middle and letting them organize themselves.",
        spanish: "Lo primero que se me ocurre es poner la comida en el centro y que ellos se organicen.",
        situationLabel: "Resolviéndolo en el momento",
        why: "*Y que ellos se organicen* — the subjunctive slides in without ceremony once *lo primero es* has set up a plan.",
        wordHints: [
          { en: "putting the food", es: "poner la comida" },
          { en: "in the middle", es: "en el centro" },
          { en: "let them organize themselves", es: "que ellos se organicen" },
        ],
      },
      {
        id: "d358-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about the coordinator — did she ever get back to you?",
        spanish: "Volviendo a lo que dijiste de la coordinadora, ¿al final te contestó?",
        situationLabel: "Un hilo de hace semanas",
        why: "*Volviendo a lo que dijiste…* reaches back across weeks, not just minutes. It's how you show someone you kept their sentence.",
        wordHints: [
          { en: "about the coordinator", es: "de la coordinadora" },
          { en: "in the end", es: "al final" },
          { en: "did she get back to you", es: "te contestó" },
        ],
      },
    ],
  },
  {
    day: 359,
    themeEs: "Yesenia llega con la olla",
    themeEn: "Yesenia arrives with the pot",
    missionEs: "Yesenia llegó primero y con comida. Contéstale la pregunta de marzo.",
    missionEn: "Yesenia got here first, and with food. Answer her question from March.",
    line: "Cuarenta minutos antes, con comida para todos, y una pregunta de marzo sin contestar.",
    lineEn: "Forty minutes early, with food for everyone, and a question from March still unanswered.",
    prompts: [
      {
        id: "d359-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I didn't think anyone was going to bring anything.",
        spanish: "La verdad es que no pensé que alguien fuera a traer algo.",
        situationLabel: "Cuando entra con la olla",
        why: "*No pensé que… fuera a* — a negated thought in the past pulls the imperfect subjunctive after it.",
        wordHints: [
          { en: "i didn't think", es: "no pensé" },
          { en: "anyone was going to bring", es: "alguien fuera a traer" },
        ],
      },
      {
        id: "d359-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Yesenia — of course the pot fits.",
        spanish: "Te estoy tomando el pelo, Yesenia, claro que cabe la olla.",
        situationLabel: "La olla no cabe (sí cabe)",
        why: "Teasing a student you've taught for a year is its own register — week 2 built it, this is where it gets used.",
        wordHints: [
          { en: "of course", es: "claro que" },
          { en: "the pot fits", es: "cabe la olla" },
        ],
      },
      {
        id: "d359-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but tonight you're not serving everyone by yourself.",
        spanish: "Entiendo tu punto, pero esta noche no vas a servir tú sola a todos.",
        situationLabel: "Quiere servir a todos",
        why: "Arguing with someone who's being generous is harder than arguing with someone who's wrong.",
        wordHints: [
          { en: "tonight", es: "esta noche" },
          { en: "serve", es: "servir" },
          { en: "by yourself", es: "tú sola" },
        ],
      },
      {
        id: "d359-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is asking you what you'd tell somebody starting in September.",
        spanish: "Lo primero que se me ocurre es preguntarte qué le dirías a alguien que empieza en septiembre.",
        situationLabel: "Devolviéndole la pregunta",
        why: "Conditional *dirías* inside an embedded question — and the whole sentence is a way of not answering first.",
        wordHints: [
          { en: "asking you", es: "preguntarte" },
          { en: "what you'd tell", es: "qué le dirías" },
          { en: "somebody starting", es: "alguien que empieza" },
        ],
      },
      {
        id: "d359-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you asked me in March — what English is for. Can I answer you now?",
        spanish: "Volviendo a lo que me preguntaste en marzo, lo del inglés para qué sirve, ¿te puedo contestar ahora?",
        situationLabel: "La pregunta de marzo",
        why: "The question that opened week 8 gets its answer here, two months later, in person. That's what the bridge stems are for.",
        wordHints: [
          { en: "what you asked me", es: "lo que me preguntaste" },
          { en: "the thing about", es: "lo de" },
          { en: "can i answer you", es: "te puedo contestar" },
        ],
      },
    ],
  },
  {
    day: 360,
    themeEs: "Camila conoce a la clase",
    themeEn: "Camila meets the class",
    missionEs: "Los dos mundos en el mismo salón. Preséntalos sin explicarte.",
    missionEn: "Both worlds in one room. Introduce them without explaining yourself.",
    line: "El café de los jueves y el salón de los martes acaban en el mismo cuarto.",
    lineEn: "The Thursday café and the Tuesday classroom end up in the same room.",
    prompts: [
      {
        id: "d360-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I was nervous about you two meeting.",
        spanish: "La verdad es que me daba nervios que ustedes dos se conocieran.",
        situationLabel: "En la puerta, antes de entrar",
        why: "*Me daba nervios que… se conocieran* — the imperfect on both halves, because the nerves lasted as long as the worry did.",
        wordHints: [
          { en: "i was nervous", es: "me daba nervios" },
          { en: "you two", es: "ustedes dos" },
          { en: "meeting", es: "se conocieran" },
        ],
      },
      {
        id: "d360-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — nobody here believes I was ever bad at this.",
        spanish: "Te estoy tomando el pelo, aquí nadie cree que yo fuera mala para esto.",
        situationLabel: "Delante de la clase",
        why: "A joke told to one person in front of eleven others is a different skill than a joke at a two-person table.",
        wordHints: [
          { en: "nobody believes", es: "nadie cree" },
          { en: "i was bad at this", es: "yo fuera mala para esto" },
        ],
      },
      {
        id: "d360-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but don't tell them the elevator story yet.",
        spanish: "Entiendo tu punto, pero no les cuentes todavía lo del ascensor.",
        situationLabel: "Protegiendo el salón",
        why: "*Lo del ascensor* — *lo de* + noun turns any shared reference into shorthand. Enormously useful and completely invisible.",
        wordHints: [
          { en: "don't tell them", es: "no les cuentes" },
          { en: "yet", es: "todavía" },
          { en: "the elevator thing", es: "lo del ascensor" },
        ],
      },
      {
        id: "d360-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is that you two are going to get along far too well.",
        spanish: "Lo primero que se me ocurre es que ustedes dos se van a llevar demasiado bien.",
        situationLabel: "Viéndolas hablar",
        why: "*Llevarse bien* — to get along. With *demasiado* it becomes a complaint you don't mean.",
        wordHints: [
          { en: "get along", es: "llevarse bien" },
          { en: "far too well", es: "demasiado bien" },
        ],
      },
      {
        id: "d360-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said at the door — yes, this is the room.",
        spanish: "Volviendo a lo que dijiste en la puerta, sí, este es el salón.",
        situationLabel: "Confirmándole lo que adivinó",
        why: "Four words of answer after a long setup. The bridge does the work; the answer can be tiny.",
        wordHints: [
          { en: "at the door", es: "en la puerta" },
          { en: "this is the room", es: "este es el salón" },
        ],
      },
    ],
  },
  {
    day: 361,
    themeEs: "La mamá de Diego",
    themeEn: "Diego's mom",
    missionEs: "Ella vino. Usted toda la conversación, y termina lo del otoño.",
    missionEn: "She came. Usted the whole way through, and finish what started in the fall.",
    line: "Vino. Usted de principio a fin, y una conversación del otoño que por fin se cierra.",
    lineEn: "She came. Usted from start to finish, and a conversation from the fall that finally closes.",
    prompts: [
      {
        id: "d361-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I wasn't expecting you to come.",
        spanish: "La verdad es que no esperaba que usted viniera.",
        situationLabel: "Cuando la ve en la puerta",
        why: "**Usted day.** Diego's mother gets *usted* throughout, the way week 7 practiced — everyone else in the room stays *tú*.",
        wordHints: [
          { en: "i wasn't expecting", es: "no esperaba" },
          { en: "you to come", es: "que usted viniera" },
        ],
      },
      {
        id: "d361-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — Diego told me you'd say exactly that.",
        spanish: "Le estoy tomando el pelo, Diego me dijo que usted iba a decir exactamente eso.",
        situationLabel: "Bromeando en usted",
        why: "*Te* → *le*. The phrase survives the register change intact; only the pronoun moves. That's week 7 in one word.",
        wordHints: [
          { en: "i'm teasing you", es: "le estoy tomando el pelo" },
          { en: "you were going to say", es: "usted iba a decir" },
          { en: "exactly that", es: "exactamente eso" },
        ],
      },
      {
        id: "d361-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I understand your point, but Diego reads better in both languages.",
        spanish: "Entiendo su punto, pero Diego lee mejor en los dos idiomas.",
        situationLabel: "Lo del inglés en casa",
        why: "*Tu* → *su*. Same disagreement you practiced in week 5, moved into the register you practiced in week 7.",
        wordHints: [
          { en: "your point", es: "su punto" },
          { en: "reads better", es: "lee mejor" },
          { en: "in both languages", es: "en los dos idiomas" },
        ],
      },
      {
        id: "d361-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is asking him to read to you in Spanish tonight.",
        spanish: "Lo primero que se me ocurre es que esta noche le pida que le lea en español.",
        situationLabel: "Una sola cosa concreta",
        why: "One concrete suggestion instead of a speech about bilingualism — and two subjunctives to carry it politely.",
        wordHints: [
          { en: "tonight", es: "esta noche" },
          { en: "ask him", es: "le pida" },
          { en: "to read to you", es: "que le lea" },
        ],
      },
      {
        id: "d361-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said in the fall — that you were afraid of being left out. You're not out.",
        spanish: "Volviendo a lo que dijo en el otoño, que tenía miedo de quedarse afuera. Usted no está afuera.",
        situationLabel: "Cerrando lo del otoño",
        why: "*Dijiste* → *dijo*. The bridge reaches back seven months, and the three words at the end are the whole point.",
        wordHints: [
          { en: "what you said", es: "lo que dijo" },
          { en: "in the fall", es: "en el otoño" },
          { en: "being left out", es: "quedarse afuera" },
        ],
      },
    ],
  },
  {
    day: 362,
    themeEs: "Los que no vuelven",
    themeEn: "The ones who aren't coming back",
    missionEs: "Tres no vuelven. Dilo sin adornarlo y sin rendirte.",
    missionEn: "Three aren't coming back. Say it without dressing it up and without giving up.",
    line: "Tres no vuelven en septiembre, y ya sabes cuáles tres.",
    lineEn: "Three aren't coming back in September, and you already know which three.",
    prompts: [
      {
        id: "d362-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, three of them aren't coming back and I already know which three.",
        spanish: "La verdad es que tres no vuelven y yo ya sé cuáles tres.",
        situationLabel: "La parte difícil de la noche",
        why: "No softening, no explanation. *La verdad es que* earns the right to say a hard number flatly.",
        wordHints: [
          { en: "aren't coming back", es: "no vuelven" },
          { en: "i already know", es: "yo ya sé" },
          { en: "which three", es: "cuáles tres" },
        ],
      },
      {
        id: "d362-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — you're not getting rid of me that easy.",
        spanish: "Te estoy tomando el pelo, de mí no te libras tan fácil.",
        situationLabel: "A la que sí vuelve",
        why: "*Librarse de alguien* — to get rid of someone. Fronting *de mí* is what makes it sound like a threat and a promise at once.",
        wordHints: [
          { en: "you're not getting rid of me", es: "de mí no te libras" },
          { en: "that easy", es: "tan fácil" },
        ],
      },
      {
        id: "d362-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but leaving isn't the same as failing.",
        spanish: "Entiendo tu punto, pero irse no es lo mismo que fracasar.",
        situationLabel: "Cuando Camila lo llama pérdida",
        why: "Two bare infinitives on either side of the comparison. Nothing extra, because nothing extra is needed.",
        wordHints: [
          { en: "leaving", es: "irse" },
          { en: "the same as", es: "lo mismo que" },
          { en: "failing", es: "fracasar" },
        ],
      },
      {
        id: "d362-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is giving them my number and meaning it.",
        spanish: "Lo primero que se me ocurre es darles mi número y decirlo en serio.",
        situationLabel: "Algo pequeño y real",
        why: "*Decirlo en serio* — the second half is what makes the first half not a gesture.",
        wordHints: [
          { en: "giving them", es: "darles" },
          { en: "my number", es: "mi número" },
          { en: "meaning it", es: "decirlo en serio" },
        ],
      },
      {
        id: "d362-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about the night shift — that's why they can't come, not because they don't want to.",
        spanish: "Volviendo a lo que dijiste del turno de noche, por eso no pueden venir, no porque no quieran.",
        situationLabel: "Corrigiendo la versión fácil",
        why: "*No porque no quieran* — subjunctive after a rejected reason. It's the difference between a fact and a judgment.",
        wordHints: [
          { en: "about the night shift", es: "del turno de noche" },
          { en: "that's why", es: "por eso" },
          { en: "not because they don't want to", es: "no porque no quieran" },
        ],
      },
    ],
  },
  {
    day: 363,
    themeEs: "Una conversación entera",
    themeEn: "One whole conversation",
    missionEs: "Cinco frases, una sola conversación. Dilas seguidas, sin parar.",
    missionEn: "Five sentences, one conversation. Say them back to back, without stopping.",
    line: "8:40. Cuatro personas, una mesa, las sobras, y una sola conversación en cinco tiempos.",
    lineEn: "8:40. Four people, one table, the leftovers, and one conversation in five beats.",
    prompts: [
      {
        id: "d363-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I don't want to be the one who ends this.",
        spanish: "La verdad es que no quiero ser yo la que termine esto.",
        situationLabel: "Tiempo 1 — nadie se quiere ir",
        why: "*Ser yo la que* + subjunctive. Five beats start here — say all five in order and it should sound like one night.",
        wordHints: [
          { en: "i don't want to be", es: "no quiero ser" },
          { en: "the one who", es: "la que" },
          { en: "ends this", es: "termine esto" },
        ],
      },
      {
        id: "d363-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Rocío — take the leftovers, all of them.",
        spanish: "Te estoy tomando el pelo, Rocío, llévate las sobras, todas.",
        situationLabel: "Tiempo 2 — las sobras",
        why: "*Todas* alone at the end, after a comma. Spoken Spanish adds the emphasis last, almost as an afterthought.",
        wordHints: [
          { en: "take", es: "llévate" },
          { en: "the leftovers", es: "las sobras" },
          { en: "all of them", es: "todas" },
        ],
      },
      {
        id: "d363-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but September is five months away and I'd rather decide in August.",
        spanish: "Entiendo tu punto, pero septiembre está a cinco meses y prefiero decidir en agosto.",
        situationLabel: "Tiempo 3 — septiembre",
        why: "*Estar a* + a length of time — the ordinary way to put distance between now and something coming.",
        wordHints: [
          { en: "is five months away", es: "está a cinco meses" },
          { en: "i'd rather decide", es: "prefiero decidir" },
        ],
      },
      {
        id: "d363-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is: same room, same hour, and we ask them what they want.",
        spanish: "Lo primero que se me ocurre es el mismo salón, la misma hora, y les preguntamos a ellos qué quieren.",
        situationLabel: "Tiempo 4 — la idea nueva",
        why: "Two noun phrases and then a whole clause. Real speech doesn't keep its lists parallel and neither should this.",
        wordHints: [
          { en: "the same room", es: "el mismo salón" },
          { en: "the same hour", es: "la misma hora" },
          { en: "we ask them", es: "les preguntamos" },
        ],
      },
      {
        id: "d363-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said an hour ago — yes. Let's do it again.",
        spanish: "Volviendo a lo que dijiste hace una hora, sí. Hagámoslo otra vez.",
        situationLabel: "Tiempo 5 — la respuesta",
        why: "An hour is a long time to hold someone's question. *Hagámoslo* is the answer, and it costs one word.",
        wordHints: [
          { en: "an hour ago", es: "hace una hora" },
          { en: "let's do it", es: "hagámoslo" },
          { en: "again", es: "otra vez" },
        ],
      },
    ],
  },
  {
    day: 364,
    themeEs: "Repaso: La última clase",
    themeEn: "Review: The last class",
    missionEs: "Nueve de la noche. Cierren el salón hablando de cosas pequeñas.",
    missionEn: "Nine at night. Close up the room while talking about small things.",
    line: "Sillas apiladas, luces apagadas, y lo último que se dice en el año se dice en un pasillo.",
    lineEn: "Chairs stacked, lights off, and the last thing said all year gets said in a hallway.",
    prompts: [
      {
        id: "d364-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I'm not going to be able to sleep tonight.",
        spanish: "La verdad es que esta noche no voy a poder dormir.",
        situationLabel: "Apilando sillas",
        why: "No summing up. Just the true, ordinary state of a person at nine at night.",
        wordHints: [
          { en: "tonight", es: "esta noche" },
          { en: "i'm not going to be able", es: "no voy a poder" },
          { en: "to sleep", es: "dormir" },
        ],
      },
      {
        id: "d364-te-estoy-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — you take the chairs and I'll take out the trash.",
        spanish: "Te estoy tomando el pelo, tú llevas las sillas y yo saco la basura.",
        situationLabel: "Repartiendo la limpieza",
        why: "The last joke of the year is about garbage. That's exactly right.",
        wordHints: [
          { en: "you take", es: "tú llevas" },
          { en: "the chairs", es: "las sillas" },
          { en: "i'll take out the trash", es: "yo saco la basura" },
        ],
      },
      {
        id: "d364-entiendo-tu-punto-pero",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but I'm not leaving the pot here until Monday.",
        spanish: "Entiendo tu punto, pero no voy a dejar la olla aquí hasta el lunes.",
        situationLabel: "La olla de Yesenia",
        why: "Still disagreeing at nine at night about a pot. Gentle debate isn't for big topics — it's for Mondays.",
        wordHints: [
          { en: "i'm not going to leave", es: "no voy a dejar" },
          { en: "the pot", es: "la olla" },
          { en: "until monday", es: "hasta el lunes" },
        ],
      },
      {
        id: "d364-lo-primero-que-se-me-ocurre-es",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is that I need to write down Yesenia's mom's name before I forget it.",
        spanish: "Lo primero que se me ocurre es que tengo que apuntar el nombre de la mamá de Yesenia antes de que se me olvide.",
        situationLabel: "Antes de que se te olvide",
        why: "*Antes de que* always takes the subjunctive, and *se me olvide* puts the forgetting on the name rather than on you.",
        wordHints: [
          { en: "write down", es: "apuntar" },
          { en: "before", es: "antes de que" },
          { en: "i forget it", es: "se me olvide" },
        ],
      },
      {
        id: "d364-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said by the copier in April — you were right. Two of us was enough.",
        spanish: "Volviendo a lo que dijiste junto a la copiadora en abril, tenías razón. Con dos alcanzaba.",
        situationLabel: "En el pasillo, con la luz apagada",
        why: "The last sentence of the year is *you were right* — said to a colleague, in a dark hallway, about something that actually happened.",
        wordHints: [
          { en: "by the copier", es: "junto a la copiadora" },
          { en: "you were right", es: "tenías razón" },
          { en: "two was enough", es: "con dos alcanzaba" },
        ],
      },
    ],
  },
];
