import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 3 — "Exagerar con gracia" (days 288–294).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week3-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek3SpeakDays: SpeakDay[] = [
  {
    day: 288,
    themeEs: "Mil años en el metro",
    themeEn: "A thousand years on the T",
    missionEs: "Describe tu viaje de hoy con color, no con minutos.",
    missionEn: "Describe today's commute with color, not minutes.",
    line: "El metro no se cuenta con reloj. Se cuenta con drama.",
    lineEn: "The subway isn't measured with a clock. It's measured with drama.",
    prompts: [
      {
        id: "d288-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying of sleep when I get off at Park Street.",
        spanish: "Me muero de sueño cuando bajo en Park Street.",
        situationLabel: "Describiendo el viaje",
        why: "*Me muero de…* sells the feeling, not the facts. Nobody checks your pulse — they check if they believe you.",
        wordHints: [
          { en: "i'm dying of", es: "me muero de" },
          { en: "sleep", es: "sueño" },
          { en: "when i get off", es: "cuando bajo" },
        ],
      },
      {
        id: "d288-mil-anos",
        frameStem: "Tardé mil años",
        english: "It took me forever to get to school today.",
        spanish: "Tardé mil años en llegar al colegio hoy.",
        situationLabel: "Contando el trayecto",
        why: "*Mil años* turns clock time into story time. The number is wrong on purpose — that's the whole move.",
        wordHints: [
          { en: "it took me forever", es: "tardé mil años" },
          { en: "to get to", es: "en llegar" },
          { en: "school", es: "el colegio" },
        ],
      },
      {
        id: "d288-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "An empty seat is the best thing in the world.",
        spanish: "Un asiento vacío es lo mejor del mundo.",
        situationLabel: "La pequeña victoria",
        why: "The smaller the mercy, the bigger the phrase. That's the joke — and the warmth.",
        wordHints: [
          { en: "an empty seat", es: "un asiento vacío" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d288-peor",
        frameStem: "Es lo peor del mundo",
        english: "Waiting on the wet platform is the worst thing in the world.",
        spanish: "Esperar en el andén mojado es lo peor del mundo.",
        situationLabel: "La queja con estilo",
        why: "*Lo peor del mundo* gives your complaint a stage. You're not filing a report — you're telling a story.",
        wordHints: [
          { en: "waiting", es: "esperar" },
          { en: "on the platform", es: "en el andén" },
          { en: "wet", es: "mojado" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
        ],
      },
      {
        id: "d288-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous what the monthly pass costs.",
        spanish: "Es una barbaridad lo que cuesta la tarjeta del mes.",
        situationLabel: "Quejándose del sistema",
        why: "*Una barbaridad* is outrage with a smile — you're complaining, but you're also performing.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "what it costs", es: "lo que cuesta" },
          { en: "the monthly pass", es: "la tarjeta del mes" },
        ],
      },
    ],
  },
  {
    day: 289,
    themeEs: "Me muero de…",
    themeEn: "I'm dying of…",
    missionEs: "Di cómo te sientes en el tren, no cuánto tardaste.",
    missionEn: "Say how you feel on the train, not how long it took.",
    line: "Tu cuerpo en el metro merece su propio drama.",
    lineEn: "Your body on the subway deserves its own drama.",
    prompts: [
      {
        id: "d289-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying of hunger and I still have two stops left.",
        spanish: "Me muero de hambre y todavía me faltan dos paradas.",
        situationLabel: "En el vagón, sin desayuno",
        why: "Three endings, same stem. Pick the one that matches your face, not your watch.",
        wordHints: [
          { en: "i'm dying of hunger", es: "me muero de hambre" },
          { en: "i still have", es: "todavía me faltan" },
          { en: "two stops", es: "dos paradas" },
        ],
      },
      {
        id: "d289-mil-anos",
        frameStem: "Tardé mil años",
        english: "It took me forever from Davis to Jamaica Plain.",
        spanish: "Tardé mil años desde Davis hasta Jamaica Plain.",
        situationLabel: "La línea roja entera",
        why: "Named stops make the exaggeration real. You're not making up the trip — you're making up the century count.",
        wordHints: [
          { en: "from", es: "desde" },
          { en: "to", es: "hasta" },
        ],
      },
      {
        id: "d289-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "The smell of coffee at the station is the best thing in the world.",
        spanish: "El olor del café en la estación es lo mejor del mundo.",
        situationLabel: "La pequeña misericordia",
        why: "Sincere hyperbole is still hyperbole. You're allowed to mean it *and* oversell it.",
        wordHints: [
          { en: "the smell of coffee", es: "el olor del café" },
          { en: "at the station", es: "en la estación" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d289-peor",
        frameStem: "Es lo peor del mundo",
        english: "Standing the whole way is the worst thing in the world.",
        spanish: "Ir de pie todo el trayecto es lo peor del mundo.",
        situationLabel: "Sin asiento otra vez",
        why: "*Todo el trayecto* — the whole ride. The exaggeration lands because the annoyance is real.",
        wordHints: [
          { en: "standing", es: "ir de pie" },
          { en: "the whole ride", es: "todo el trayecto" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
        ],
      },
      {
        id: "d289-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous how many people there are at this hour.",
        spanish: "Es una barbaridad la cantidad de gente a esta hora.",
        situationLabel: "Hora pico",
        why: "*La cantidad de* — the amount of. A clean way to exaggerate a crowd without counting heads.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "the amount of people", es: "la cantidad de gente" },
          { en: "at this hour", es: "a esta hora" },
        ],
      },
    ],
  },
  {
    day: 290,
    themeEs: "Tardé mil años",
    themeEn: "It took me forever",
    missionEs: "Convierte los minutos de espera en historia.",
    missionEn: "Turn waiting minutes into a story.",
    line: "Un retraso se cuenta en siglos, no en minutos.",
    lineEn: "A delay is measured in centuries, not minutes.",
    prompts: [
      {
        id: "d290-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying of boredom on this platform.",
        spanish: "Me muero de aburrimiento en este andén.",
        situationLabel: "Esperando el tren",
        why: "*Me muero de aburrimiento* — boredom counts. Hyperbole isn't only for disasters.",
        wordHints: [
          { en: "i'm dying of boredom", es: "me muero de aburrimiento" },
          { en: "on this platform", es: "en este andén" },
        ],
      },
      {
        id: "d290-mil-anos",
        frameStem: "Tardé mil años",
        english: "It took me forever because they sent us on a shuttle bus.",
        spanish: "Tardé mil años porque nos mandaron en bus de reemplazo.",
        situationLabel: "Bus de reemplazo",
        why: "*Bus de reemplazo* — shuttle bus. Boston vocabulary, Latin American sentence.",
        wordHints: [
          { en: "because", es: "porque" },
          { en: "they sent us", es: "nos mandaron" },
          { en: "shuttle bus", es: "bus de reemplazo" },
        ],
      },
      {
        id: "d290-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "Seeing the train arrive is the best thing in the world.",
        spanish: "Ver llegar el tren es lo mejor del mundo.",
        situationLabel: "Cuando por fin aparece",
        why: "The smallest relief deserves the biggest phrase. That's how hyperbole earns its keep.",
        wordHints: [
          { en: "seeing", es: "ver" },
          { en: "arrive", es: "llegar" },
          { en: "the train", es: "el tren" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d290-peor",
        frameStem: "Es lo peor del mundo",
        english: "Missing the connection at Park Street is the worst thing in the world.",
        spanish: "Perder la conexión en Park Street es lo peor del mundo.",
        situationLabel: "Transbordo fallido",
        why: "Named places anchor the drama. Everyone who's missed a connection knows this isn't really exaggeration.",
        wordHints: [
          { en: "missing the connection", es: "perder la conexión" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
        ],
      },
      {
        id: "d290-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous when they say \"minor delay\" and it's twenty minutes.",
        spanish: "Es una barbaridad que digan \"demora menor\" y sean veinte minutos.",
        situationLabel: "El anuncio mentiroso",
        why: "*Demora menor* in quotes — you're quoting the system against itself. That's the whole complaint.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "minor delay", es: "demora menor" },
          { en: "twenty minutes", es: "veinte minutos" },
        ],
      },
    ],
  },
  {
    day: 291,
    themeEs: "Es lo mejor del mundo",
    themeEn: "It's the best thing in the world",
    missionEs: "Elogia la cosa pequeña que salvó tu viaje.",
    missionEn: "Praise the small thing that saved your commute.",
    line: "Lo mejor del mundo casi nunca es grande.",
    lineEn: "The best thing in the world is almost never big.",
    prompts: [
      {
        id: "d291-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying of laughter at your exaggerations.",
        spanish: "Me muero de risa con tus exageraciones.",
        situationLabel: "En el café con Camila",
        why: "*Me muero de risa* — you're dying of laughter. Hyperbole about hyperbole is the meta move.",
        wordHints: [
          { en: "i'm dying of laughter", es: "me muero de risa" },
          { en: "your exaggerations", es: "tus exageraciones" },
        ],
      },
      {
        id: "d291-mil-anos",
        frameStem: "Tardé mil años",
        english: "It took me forever, but I got here before yesterday.",
        spanish: "Tardé mil años, pero llegué antes que ayer.",
        situationLabel: "Comparando con ayer",
        why: "*Antes que ayer* — before yesterday did. The contrast makes both days into a story.",
        wordHints: [
          { en: "but", es: "pero" },
          { en: "i got here before", es: "llegué antes que" },
          { en: "yesterday", es: "ayer" },
        ],
      },
      {
        id: "d291-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "Finding you at the café is the best thing in the world.",
        spanish: "Encontrarte en el café es lo mejor del mundo.",
        situationLabel: "El premio del jueves",
        why: "Sincere hyperbole is still hyperbole. You're allowed to mean it *and* oversell it.",
        wordHints: [
          { en: "finding you", es: "encontrarte" },
          { en: "at the café", es: "en el café" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d291-peor",
        frameStem: "Es lo peor del mundo",
        english: "Yesterday was the worst thing in the world, not today.",
        spanish: "Ayer fue lo peor del mundo, hoy no.",
        situationLabel: "Contraste de días",
        why: "Hyperbole needs contrast. Yesterday's disaster makes today's mercy land harder.",
        wordHints: [
          { en: "yesterday", es: "ayer" },
          { en: "was", es: "fue" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
          { en: "not today", es: "hoy no" },
        ],
      },
      {
        id: "d291-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous how good I felt over one seat.",
        spanish: "Es una barbaridad lo bien que me sentí por un asiento.",
        situationLabel: "Emoción desproporcionada",
        why: "*Lo bien que me sentí* — how good I felt. You're exaggerating your own reaction, and that's the charm.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "how good i felt", es: "lo bien que me sentí" },
          { en: "over one seat", es: "por un asiento" },
        ],
      },
    ],
  },
  {
    day: 292,
    themeEs: "Es lo peor del mundo",
    themeEn: "It's the worst thing in the world",
    missionEs: "Cuenta el desastre de hoy como tragedia, no como reporte.",
    missionEn: "Tell today's disaster as tragedy, not as a report.",
    line: "Lo peor del mundo merece su propio acto.",
    lineEn: "The worst thing in the world deserves its own act.",
    prompts: [
      {
        id: "d292-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying of embarrassment — I was late again.",
        spanish: "Me muero de vergüenza, llegué tarde otra vez.",
        situationLabel: "Llegando tarde otra vez",
        why: "*Me muero de vergüenza* — the feeling is real even when the death isn't. That's hyperbole doing its job.",
        wordHints: [
          { en: "i'm dying of embarrassment", es: "me muero de vergüenza" },
          { en: "i was late again", es: "llegué tarde otra vez" },
        ],
      },
      {
        id: "d292-mil-anos",
        frameStem: "Tardé mil años",
        english: "It took me forever and the principal was already at the door.",
        spanish: "Tardé mil años y la directora ya estaba en la puerta.",
        situationLabel: "El peor timing",
        why: "Stack the exaggeration onto the consequence. The century count and the principal in the same breath.",
        wordHints: [
          { en: "the principal", es: "la directora" },
          { en: "was already", es: "ya estaba" },
          { en: "at the door", es: "en la puerta" },
        ],
      },
      {
        id: "d292-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "The one good thing: it's the best thing in the world that you listen to me.",
        spanish: "Lo único bueno: es lo mejor del mundo que tú me escuchas.",
        situationLabel: "Camila al rescate",
        why: "Even on the worst day, hyperbole finds the one mercy. That's not toxic positivity — it's survival.",
        wordHints: [
          { en: "the one good thing", es: "lo único bueno" },
          { en: "that you listen to me", es: "que tú me escuchas" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d292-peor",
        frameStem: "Es lo peor del mundo",
        english: "Getting stuck in the tunnel is the worst thing in the world.",
        spanish: "Quedarse parada en el túnel es lo peor del mundo.",
        situationLabel: "Parada en el túnel",
        why: "*Demora indefinida* is the phrase every Boston commuter learns to dread — and *lo peor del mundo* is how you survive it.",
        wordHints: [
          { en: "getting stuck", es: "quedarse parada" },
          { en: "in the tunnel", es: "en el túnel" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
        ],
      },
      {
        id: "d292-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous, and tomorrow I'll try again anyway.",
        spanish: "Es una barbaridad y mañana lo vuelvo a intentar.",
        situationLabel: "Resignación con color",
        why: "The comma before *y mañana* is the whole Boston commute story in one breath.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "tomorrow", es: "mañana" },
          { en: "i'll try again", es: "lo vuelvo a intentar" },
        ],
      },
    ],
  },
  {
    day: 293,
    themeEs: "Es una barbaridad",
    themeEn: "It's outrageous",
    missionEs: "Compara sufrimientos de viaje con Rocío — en voz alta.",
    missionEn: "Compare commute suffering with Rocío — out loud.",
    line: "Tres trayectos, tres barbaridades, una mesa.",
    lineEn: "Three commutes, three outrages, one table.",
    prompts: [
      {
        id: "d293-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying of laughter listening to you two.",
        spanish: "Me muero de risa escuchándolas a las dos.",
        situationLabel: "Las tres en el café",
        why: "*Escuchándolas a las dos* — listening to both of you. Hyperbole as group sport.",
        wordHints: [
          { en: "i'm dying of laughter", es: "me muero de risa" },
          { en: "listening to both of you", es: "escuchándolas a las dos" },
        ],
      },
      {
        id: "d293-mil-anos",
        frameStem: "Tardé mil años",
        english: "Rocío says it took her forever on the 39 bus.",
        spanish: "Rocío dice que tardó mil años en el bus 39.",
        situationLabel: "El trayecto de Rocío",
        why: "Reporting someone else's exaggeration is its own skill — you're lending them your Spanish stage.",
        wordHints: [
          { en: "she says", es: "dice que" },
          { en: "it took her forever", es: "tardó mil años" },
          { en: "the bus", es: "el bus" },
        ],
      },
      {
        id: "d293-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "This café on Thursdays is the best thing in the world.",
        spanish: "Este café los jueves es lo mejor del mundo.",
        situationLabel: "El ritual del jueves",
        why: "The commute week ends where it always ends — at the table where exaggeration is welcome.",
        wordHints: [
          { en: "this café", es: "este café" },
          { en: "on thursdays", es: "los jueves" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d293-peor",
        frameStem: "Es lo peor del mundo",
        english: "Rocío's bus is the worst thing in the world, she says.",
        spanish: "El bus de Rocío es lo peor del mundo, dice ella.",
        situationLabel: "Compitiendo por el peor viaje",
        why: "*Dice ella* at the end — she says. You're quoting Rocío's hyperbole, not claiming it yourself.",
        wordHints: [
          { en: "rocío's bus", es: "el bus de rocío" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
          { en: "she says", es: "dice ella" },
        ],
      },
      {
        id: "d293-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous, and we stay anyway.",
        spanish: "Es una barbaridad, y aun así nos quedamos.",
        situationLabel: "Amor a Boston, con drama",
        why: "*Y aun así nos quedamos* — and we stay anyway. The punchline of every Boston commute story.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "and still", es: "aun así" },
          { en: "we stay", es: "nos quedamos" },
        ],
      },
    ],
  },
  {
    day: 294,
    themeEs: "Repaso: Exagerar con gracia",
    themeEn: "Review: Exaggerating with grace",
    missionEs: "Cuenta la semana del metro: qué cambió cuando dejaste de contar minutos.",
    missionEn: "Tell the subway week: what changed when you stopped counting minutes.",
    line: "Seis días de color. Cero mentiras.",
    lineEn: "Six days of color. Zero lies.",
    prompts: [
      {
        id: "d294-me-muero",
        frameStem: "Me muero de…",
        english: "I'm dying to use this in real life.",
        spanish: "Me muero de ganas de usar esto en la vida real.",
        situationLabel: "Lo que se quedó",
        why: "*Me muero de ganas de* — you're dying to. The stem that started as complaint ended as appetite.",
        wordHints: [
          { en: "i'm dying to", es: "me muero de ganas de" },
          { en: "use this", es: "usar esto" },
          { en: "in real life", es: "en la vida real" },
        ],
      },
      {
        id: "d294-mil-anos",
        frameStem: "Tardé mil años",
        english: "\"It took me forever\" became my way of telling time.",
        spanish: "Tardé mil años se convirtió en mi forma de contar el tiempo.",
        situationLabel: "El resumen de la semana",
        why: "Naming the shift — from clock to story — is the week's real takeaway.",
        wordHints: [
          { en: "became", es: "se convirtió en" },
          { en: "my way of telling time", es: "mi forma de contar el tiempo" },
        ],
      },
      {
        id: "d294-mejor",
        frameStem: "Es lo mejor del mundo",
        english: "It's the best thing in the world to exaggerate without lying.",
        spanish: "Es lo mejor del mundo exagerar sin mentir.",
        situationLabel: "La lección",
        why: "Hyperbole isn't lying — it's giving the feeling the size it actually had inside you.",
        wordHints: [
          { en: "to exaggerate", es: "exagerar" },
          { en: "without lying", es: "sin mentir" },
          { en: "the best thing in the world", es: "lo mejor del mundo" },
        ],
      },
      {
        id: "d294-peor",
        frameStem: "Es lo peor del mundo",
        english: "It's the worst thing in the world, and it's okay to say it that way.",
        spanish: "Es lo peor del mundo, y está bien decirlo así.",
        situationLabel: "Permiso para exagerar",
        why: "*Está bien decirlo así* — permission you didn't know you needed until Camila gave it to you.",
        wordHints: [
          { en: "it's okay", es: "está bien" },
          { en: "to say it that way", es: "decirlo así" },
          { en: "the worst thing in the world", es: "lo peor del mundo" },
        ],
      },
      {
        id: "d294-barbaridad",
        frameStem: "Es una barbaridad",
        english: "It's outrageous — and that's why I like it.",
        spanish: "Es una barbaridad, y por eso me gusta.",
        situationLabel: "El cierre de la semana",
        why: "Rocío's energy in one sentence: outrage as personality, not complaint.",
        wordHints: [
          { en: "it's outrageous", es: "es una barbaridad" },
          { en: "that's why", es: "por eso" },
          { en: "i like it", es: "me gusta" },
        ],
      },
    ],
  },
];
