import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 5 — "Debate suave I" (days 302–308).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week5-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek5SpeakDays: SpeakDay[] = [
  {
    day: 302,
    themeEs: "El tema sale solo",
    themeEn: "The topic comes up on its own",
    missionEs: "Discrepa con calma cinco veces sobre el celular en clase.",
    missionEn: "Disagree gently five times about phones in class.",
    line: "Un teléfono suena y empieza la conversación de verdad.",
    lineEn: "A phone rings and the real conversation starts.",
    prompts: [
      {
        id: "d302-entiendo-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but it wasn't laziness — it was daycare.",
        spanish: "Entiendo tu punto, pero no fue por flojera — era la guardería.",
        situationLabel: "Después del timbre en clase",
        why: "*Entiendo tu punto, pero…* opens with credit — the listener stays in the room because you heard them first.",
        wordHints: [
          { en: "i get your point", es: "entiendo tu punto" },
          { en: "it wasn't laziness", es: "no fue por flojera" },
          { en: "daycare", es: "la guardería" },
        ],
      },
      {
        id: "d302-yo-lo-veo",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently: a phone can be a dictionary and translator.",
        spanish: "Yo lo veo distinto: un celular puede ser diccionario y traductor.",
        situationLabel: "El celular como herramienta",
        why: "Flat disagreement without *pero* — useful when you want to stand your ground without stacking concessions.",
        wordHints: [
          { en: "i see it differently", es: "yo lo veo distinto" },
          { en: "phone", es: "celular" },
          { en: "dictionary", es: "diccionario" },
        ],
      },
      {
        id: "d302-no-crees",
        frameStem: "¿No crees que…?",
        english: "Don't you think banning everything sounds like high school?",
        spanish: "¿No crees que prohibirlo todo suena a prepa?",
        situationLabel: "Desafío suave",
        why: "A disagreement shaped as a question — the other person gets to answer instead of defend.",
        wordHints: [
          { en: "don't you think", es: "¿no crees que" },
          { en: "banning everything", es: "prohibirlo todo" },
          { en: "high school", es: "prepa" },
        ],
      },
      {
        id: "d302-puede-ser",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but yesterday mine rang right in the middle of the lesson.",
        spanish: "Puede ser, pero ayer sonó el mío en plena lección.",
        situationLabel: "Medio de acuerdo",
        why: "*Puede ser* buys you a beat of fairness before the *pero* — softer than *estás equivocada*.",
        wordHints: [
          { en: "maybe", es: "puede ser" },
          { en: "mine rang", es: "sonó el mío" },
          { en: "in the middle of the lesson", es: "en plena lección" },
        ],
      },
      {
        id: "d302-no-estoy-segura",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure taking away the phone improves learning.",
        spanish: "No estoy segura de que quitar el celular mejore el aprendizaje.",
        situationLabel: "Duda sin atacar",
        why: "Soft doubt with subjunctive (*de que mejore*) — you're questioning the idea, not attacking the person.",
        wordHints: [
          { en: "i'm not sure", es: "no estoy segura de que" },
          { en: "taking away the phone", es: "quitar el celular" },
          { en: "improves learning", es: "mejore el aprendizaje" },
        ],
      },
    ],
  },
  {
    day: 303,
    themeEs: "Los adultos tienen vidas",
    themeEn: "Adults have lives",
    missionEs: "Defiende el lado de tus estudiantes con los cinco stems.",
    missionEn: "Defend your students' side using all five stems.",
    line: "Guardería, turno de noche, un mensaje urgente — no son adolescentes.",
    lineEn: "Daycare, night shift, an urgent text — they're not teenagers.",
    prompts: [
      {
        id: "d303-entiendo-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but my students have kids in daycare.",
        spanish: "Entiendo tu punto, pero mis estudiantes tienen hijos en guardería.",
        situationLabel: "Vidas fuera del salón",
        why: "Adult ESOL is different from K–12 — *hijos en guardería* is the detail that changes the debate.",
        wordHints: [
          { en: "my students", es: "mis estudiantes" },
          { en: "have kids", es: "tienen hijos" },
          { en: "in daycare", es: "en guardería" },
        ],
      },
      {
        id: "d303-yo-lo-veo",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently: if you trust them, they respect you more.",
        spanish: "Yo lo veo distinto: si confías en ellos, te respetan más.",
        situationLabel: "Confianza vs control",
        why: "*Si confías en ellos* — conditional, not subjunctive. The trust argument lands in plain Spanish.",
        wordHints: [
          { en: "if you trust them", es: "si confías en ellos" },
          { en: "they respect you", es: "te respetan" },
          { en: "more", es: "más" },
        ],
      },
      {
        id: "d303-no-crees",
        frameStem: "¿No crees que…?",
        english: "Don't you think you'd look at your phone too if your kid were sick?",
        spanish: "¿No crees que tú también mirarías el teléfono si tu hijo está enfermo?",
        situationLabel: "Poniéndola en tu lugar",
        why: "Camila is a nurse and a mom — *si tu hijo está enfermo* makes the debate personal without being mean.",
        wordHints: [
          { en: "you'd look too", es: "tú también mirarías" },
          { en: "your phone", es: "el teléfono" },
          { en: "your kid is sick", es: "tu hijo está enfermo" },
        ],
      },
      {
        id: "d303-puede-ser",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but most of them use it to translate, not for TikTok.",
        spanish: "Puede ser, pero la mayoría lo usa para traducir, no para TikTok.",
        situationLabel: "No todo es scroll",
        why: "*La mayoría* — you're not denying the problem, you're widening the picture.",
        wordHints: [
          { en: "most of them", es: "la mayoría" },
          { en: "to translate", es: "para traducir" },
          { en: "not for tiktok", es: "no para tiktok" },
        ],
      },
      {
        id: "d303-no-estoy-segura",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure a strict rule makes them more present.",
        spanish: "No estoy segura de que una regla rígida los haga más presentes.",
        situationLabel: "Dudando la solución dura",
        why: "*Los haga más presentes* — subjunctive after *de que* without naming it. Third use this week.",
        wordHints: [
          { en: "a strict rule", es: "una regla rígida" },
          { en: "makes them", es: "los haga" },
          { en: "more present", es: "más presentes" },
        ],
      },
    ],
  },
  {
    day: 304,
    themeEs: "En clase es en clase",
    themeEn: "In class is class",
    missionEs: "Defiende el foco y el respeto — sin pelear con Marlana.",
    missionEn: "Defend focus and respect — without fighting with Marlana.",
    line: "Camila hace turnos de noche. Tú tienes adultos que ya trabajaron ocho horas.",
    lineEn: "Camila works night shifts. You have adults who already worked eight hours.",
    prompts: [
      {
        id: "d304-entiendo-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but at the hospital a second of distraction matters.",
        spanish: "Entiendo tu punto, pero en el hospital un segundo de distracción importa.",
        situationLabel: "Camila trae su mundo",
        why: "Camila's hospital frame isn't a trump card — it's her lens. *Un segundo importa* is how she sees focus.",
        wordHints: [
          { en: "at the hospital", es: "en el hospital" },
          { en: "a second", es: "un segundo" },
          { en: "distraction", es: "distracción" },
        ],
      },
      {
        id: "d304-yo-lo-veo",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently: a clear limit gives them permission to put the phone down.",
        spanish: "Yo lo veo distinto: un límite claro les da permiso de soltar el teléfono.",
        situationLabel: "Límites que liberan",
        why: "*Permiso de soltar* reframes rules as relief, not punishment — Camila's strongest move.",
        wordHints: [
          { en: "a clear limit", es: "un límite claro" },
          { en: "gives them permission", es: "les da permiso" },
          { en: "to put down the phone", es: "de soltar el teléfono" },
        ],
      },
      {
        id: "d304-no-crees",
        frameStem: "¿No crees que…?",
        english: "Don't you think if they leave it face-up on the table, temptation wins?",
        spanish: "¿No crees que si lo dejan en la mesa boca arriba, la tentación gana?",
        situationLabel: "La mesa boca arriba",
        why: "*Boca arriba* — face up. A concrete image beats an abstract rule every time.",
        wordHints: [
          { en: "face-up on the table", es: "en la mesa boca arriba" },
          { en: "temptation", es: "la tentación" },
          { en: "wins", es: "gana" },
        ],
      },
      {
        id: "d304-puede-ser",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but I saw three people looking at screens in your classroom yesterday.",
        spanish: "Puede ser, pero vi a tres personas mirando pantallas ayer en tu salón.",
        situationLabel: "La evidencia de ayer",
        why: "Camila was there — *vi a tres personas* is observation, not accusation. Debate suave still uses facts.",
        wordHints: [
          { en: "i saw", es: "vi" },
          { en: "three people", es: "tres personas" },
          { en: "looking at screens", es: "mirando pantallas" },
        ],
      },
      {
        id: "d304-no-estoy-segura",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure \"trusting them\" means not having any rules.",
        spanish: "No estoy segura de que \"confiar\" signifique no poner reglas.",
        situationLabel: "Confianza no es ausencia",
        why: "Camila questions Marlana's word without attacking Marlana — *signifique* carries the doubt.",
        wordHints: [
          { en: "trusting", es: "confiar" },
          { en: "means", es: "signifique" },
          { en: "not having rules", es: "no poner reglas" },
        ],
      },
    ],
  },
  {
    day: 305,
    themeEs: "Rocío opina",
    themeEn: "Rocío's take",
    missionEs: "Usa lo que dijo Rocío para negociar — sin copiar su escuela.",
    missionEn: "Use what Rocío said to negotiate — without copying her school.",
    line: "Un audio de veinte minutos y de pronto hay tres opiniones.",
    lineEn: "A twenty-minute voice note and suddenly there are three opinions.",
    prompts: [
      {
        id: "d305-entiendo-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but Rocío works with kids — I work with adults.",
        spanish: "Entiendo tu punto, pero Rocío trabaja con niños, yo con adultos.",
        situationLabel: "Contexto distinto",
        why: "*Rocío trabaja con niños* — borrowing a colleague's idea without importing her whole context.",
        wordHints: [
          { en: "works with kids", es: "trabaja con niños" },
          { en: "i work with adults", es: "yo con adultos" },
        ],
      },
      {
        id: "d305-yo-lo-veo",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently: we don't need to take the phone away — we need to agree when.",
        spanish: "Yo lo veo distinto: no hace falta quitar el celular, hace falta acordar cuándo.",
        situationLabel: "Cuándo, no si",
        why: "*Hace falta acordar cuándo* — the week's best sentence. Shifts the debate from ban to agreement.",
        wordHints: [
          { en: "we don't need to take it away", es: "no hace falta quitar el celular" },
          { en: "we need to agree when", es: "hace falta acordar cuándo" },
        ],
      },
      {
        id: "d305-no-crees",
        frameStem: "¿No crees que…?",
        english: "Don't you think \"face down on the table\" is more reasonable than the basket?",
        spanish: "¿No crees que lo de \"boca abajo en la mesa\" es más razonable que la cesta?",
        situationLabel: "Robando lo bueno",
        why: "Rocío's basket becomes Marlana's *boca abajo* — same spirit, adult register.",
        wordHints: [
          { en: "face down on the table", es: "boca abajo en la mesa" },
          { en: "more reasonable", es: "más razonable" },
          { en: "the basket", es: "la cesta" },
        ],
      },
      {
        id: "d305-puede-ser",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but Rocío sent a twenty-minute voice note — not all of it applies.",
        spanish: "Puede ser, pero Rocío mandó un audio de veinte minutos — no todo aplica.",
        situationLabel: "El audio de Rocío",
        why: "Week 4's voice-note habit meets week 5's debate — Rocío talks; Marlana and Camila filter.",
        wordHints: [
          { en: "sent a voice note", es: "mandó un audio" },
          { en: "twenty minutes", es: "veinte minutos" },
          { en: "not all of it applies", es: "no todo aplica" },
        ],
      },
      {
        id: "d305-no-estoy-segura",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure the basket works for people coming straight from work.",
        spanish: "No estoy segura de que la cesta funcione con gente que viene del trabajo.",
        situationLabel: "Adultos después del turno",
        why: "*Viene del trabajo* — night ESOL students arrive tired. Policy has to fit their hour, not Rocío's morning.",
        wordHints: [
          { en: "the basket works", es: "la cesta funcione" },
          { en: "people coming from work", es: "gente que viene del trabajo" },
        ],
      },
    ],
  },
  {
    day: 306,
    themeEs: "Un punto medio",
    themeEn: "A middle ground",
    missionEs: "Arma un acuerdo en cinco frases — una por stem.",
    missionEn: "Build an agreement in five sentences — one per stem.",
    line: "Boca abajo hasta el descanso, con excepción para el traductor.",
    lineEn: "Face down until the break, with an exception for the translator.",
    prompts: [
      {
        id: "d306-entiendo-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but \"silenced and face down\" seems fair to me.",
        spanish: "Entiendo tu punto, pero \"silenciado y boca abajo\" me parece justo.",
        situationLabel: "La regla propuesta",
        why: "*Silenciado y boca abajo* — two words, one rule. The compromise in four syllables of policy.",
        wordHints: [
          { en: "silenced", es: "silenciado" },
          { en: "face down", es: "boca abajo" },
          { en: "seems fair", es: "me parece justo" },
        ],
      },
      {
        id: "d306-yo-lo-veo",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently: we're not banning — we're agreeing on three clear things.",
        spanish: "Yo lo veo distinto: no es prohibir, es acordar tres cosas claras.",
        situationLabel: "Prohibir vs acordar",
        why: "*Tres cosas claras* — small enough to remember, big enough to hold a whole class.",
        wordHints: [
          { en: "we're not banning", es: "no es prohibir" },
          { en: "we're agreeing", es: "es acordar" },
          { en: "three clear things", es: "tres cosas claras" },
        ],
      },
      {
        id: "d306-no-crees",
        frameStem: "¿No crees que…?",
        english: "Don't you think \"face down until break\" is easy to remember?",
        spanish: "¿No crees que \"boca abajo hasta el descanso\" es fácil de recordar?",
        situationLabel: "¿Simple enough?",
        why: "*Hasta el descanso* — a time boundary everyone can see on the clock, not a vague \"during class.\"",
        wordHints: [
          { en: "face down until break", es: "boca abajo hasta el descanso" },
          { en: "easy to remember", es: "fácil de recordar" },
        ],
      },
      {
        id: "d306-puede-ser",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but I want an explicit exception for translator and dictionary.",
        spanish: "Puede ser, pero quiero una excepción explícita para traductor y diccionario.",
        situationLabel: "Excepciones por escrito",
        why: "*Excepción explícita* — Marlana's non-negotiable. Tools stay; scroll goes.",
        wordHints: [
          { en: "explicit exception", es: "excepción explícita" },
          { en: "translator", es: "traductor" },
          { en: "dictionary", es: "diccionario" },
        ],
      },
      {
        id: "d306-no-estoy-segura",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure it'll work the first week without stumbles.",
        spanish: "No estoy segura de que funcione la primera semana sin tropiezos.",
        situationLabel: "Antes de probarlo",
        why: "Honest doubt before trying — *sin tropiezos* lowers the stakes so they can actually test it.",
        wordHints: [
          { en: "it'll work", es: "funcione" },
          { en: "the first week", es: "la primera semana" },
          { en: "without stumbles", es: "sin tropiezos" },
        ],
      },
    ],
  },
  {
    day: 307,
    themeEs: "Lo probamos en clase",
    themeEn: "We tried it in class",
    missionEs: "Cuenta cómo salió — con debate suave, no con informe.",
    missionEn: "Say how it went — with gentle debate, not a report.",
    line: "Lo dijeron en voz alta el lunes y funcionó.",
    lineEn: "They said it out loud on Monday and it worked.",
    prompts: [
      {
        id: "d307-entiendo-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but today went better than I thought.",
        spanish: "Entiendo tu punto, pero hoy salió mejor de lo que pensaba.",
        situationLabel: "Debrief del martes",
        why: "*Salió mejor* — same *salir* as invierno week 5's family night. How things turn out, not how they leave.",
        wordHints: [
          { en: "today went", es: "hoy salió" },
          { en: "better than", es: "mejor de lo que" },
          { en: "i thought", es: "pensaba" },
        ],
      },
      {
        id: "d307-yo-lo-veo",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently now: it wasn't trust vs rules — it was clarity.",
        spanish: "Yo lo veo distinto ahora: no era confianza vs reglas, era claridad.",
        situationLabel: "Lo que aprendió",
        why: "*Era claridad* — Marlana reframes the whole week in one noun. Debate suave can end in synthesis.",
        wordHints: [
          { en: "i see it differently now", es: "yo lo veo distinto ahora" },
          { en: "trust vs rules", es: "confianza vs reglas" },
          { en: "it was clarity", es: "era claridad" },
        ],
      },
      {
        id: "d307-no-crees",
        frameStem: "¿No crees que…?",
        english: "Don't you think saying it together at the start is what worked?",
        spanish: "¿No crees que decirlo juntos al inicio fue lo que funcionó?",
        situationLabel: "El ritual",
        why: "*Decirlo juntos al inicio* — co-created rules stick because everyone heard their voice in them.",
        wordHints: [
          { en: "saying it together", es: "decirlo juntos" },
          { en: "at the start", es: "al inicio" },
          { en: "what worked", es: "lo que funcionó" },
        ],
      },
      {
        id: "d307-puede-ser",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but arguing like this with you helped more than any manual.",
        spanish: "Puede ser, pero discutir así contigo me ayudó más que cualquier manual.",
        situationLabel: "El debate valió",
        why: "Meta moment — the week's real product isn't phone policy, it's *discutir así*.",
        wordHints: [
          { en: "arguing like this", es: "discutir así" },
          { en: "with you", es: "contigo" },
          { en: "more than any manual", es: "más que cualquier manual" },
        ],
      },
      {
        id: "d307-no-estoy-segura",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure this counts as debate, but we didn't fight.",
        spanish: "No estoy segura de que esto cuente como debate, pero no peleamos.",
        situationLabel: "Suave de verdad",
        why: "*No peleamos* — the success metric for Debate suave I. Policy optional; tone mandatory.",
        wordHints: [
          { en: "counts as debate", es: "cuente como debate" },
          { en: "we didn't fight", es: "no peleamos" },
        ],
      },
    ],
  },
  {
    day: 308,
    themeEs: "Repaso: Debate suave I",
    themeEn: "Review: Gentle debate I",
    missionEs: "Rocío te quiere en el grupo del sábado. Di que no sin cerrar la puerta.",
    missionEn: "Rocío wants you in the Saturday group. Say no without shutting the door.",
    line: "Rocío quiere empezar un grupo los sábados. Y te quiere a ti dentro.",
    lineEn: "Rocío wants to start a Saturday group. And she wants you in it.",
    prompts: [
      {
        id: "d308-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but Saturday is the one day those kids get to sleep.",
        spanish: "Entiendo tu punto, pero el sábado es el único día que esos chicos duermen.",
        situationLabel: "En el estacionamiento, viernes",
        why: "Arguing for the students instead of for yourself is the strongest version of the same *no*.",
        wordHints: [
          { en: "the one day", es: "el único día" },
          { en: "those kids", es: "esos chicos" },
          { en: "sleep", es: "duermen" },
        ],
      },
      {
        id: "d308-yo-lo-veo-distinto",
        frameStem: "Yo lo veo distinto",
        english: "I see it differently: if it's free, more people come.",
        spanish: "Yo lo veo distinto: si es gratis, viene más gente.",
        situationLabel: "Si cobran o no",
        why: "A colon instead of a *que* — the second half lands harder when nothing connects it.",
        wordHints: [
          { en: "i see it differently", es: "yo lo veo distinto" },
          { en: "if it's free", es: "si es gratis" },
          { en: "more people come", es: "viene más gente" },
        ],
      },
      {
        id: "d308-no-crees-que",
        frameStem: "¿No crees que…?",
        english: "Don't you think two hours is a lot for a Saturday morning?",
        spanish: "¿No crees que dos horas es mucho para un sábado por la mañana?",
        situationLabel: "La duración",
        why: "*Dos horas es* — a stretch of time counts as one thing, so the verb stays singular.",
        wordHints: [
          { en: "don't you think", es: "no crees que" },
          { en: "two hours", es: "dos horas" },
          { en: "a saturday morning", es: "un sábado por la mañana" },
        ],
      },
      {
        id: "d308-puede-ser-pero",
        frameStem: "Puede ser, pero…",
        english: "Maybe, but I'm not going to be the one who tells them their kid has to come.",
        spanish: "Puede ser, pero yo no voy a ser la que les diga que el niño tiene que venir.",
        situationLabel: "Dónde está tu línea",
        why: "*La que les diga* — subjunctive, because the person doesn't exist yet and you're refusing to become her.",
        wordHints: [
          { en: "the one who tells them", es: "la que les diga" },
          { en: "has to come", es: "tiene que venir" },
        ],
      },
      {
        id: "d308-no-estoy-segura-de-que",
        frameStem: "No estoy segura de que…",
        english: "I'm not sure we can keep this going past May.",
        spanish: "No estoy segura de que podamos seguir con esto después de mayo.",
        situationLabel: "La duda de verdad",
        why: "Doubt takes the subjunctive — *podamos*. Naming the real worry is more useful than five polite objections.",
        wordHints: [
          { en: "we can keep going", es: "podamos seguir" },
          { en: "past may", es: "después de mayo" },
        ],
      },
    ],
  },
];
