import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 7 — "Cambiar de registro" (days 316–322).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week7-frames.ts
 * for the matching `frameStem`.
 */
export const priWeek7SpeakDays: SpeakDay[] = [
  {
    day: 316,
    themeEs: "Ensayando con Rocío",
    themeEn: "Rehearsing with Rocío",
    missionEs: "Practica las cinco frases en usted hasta que suenen tuyas.",
    missionEn: "Practice the five phrases in usted until they sound like yours.",
    line: "Mañana hablas con mamás y papás. Hoy ensayas con Rocío.",
    lineEn: "Tomorrow you talk to mothers and fathers. Today you rehearse with Rocío.",
    prompts: [
      {
        id: "d316-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment before the line starts?",
        spanish: "Disculpe, ¿tendría un momento antes de que empiece la fila?",
        situationLabel: "Ensayo con Rocío",
        why: "With usted: **Disculpe** instead of *Oye*, and **¿tendría?** instead of *¿tienes?* — the conditional softens the ask.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "would you have", es: "tendría" },
          { en: "a moment", es: "un momento" },
          { en: "before the line starts", es: "antes de que empiece la fila" },
        ],
      },
      {
        id: "d316-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that Yusuf has improved a lot in participating.",
        spanish: "Le quería comentar que Yusuf ha mejorado mucho en participar.",
        situationLabel: "Buenas noticias primero",
        why: "*Te quería* becomes **Le quería** with usted — the indirect object shifts. The rest of the sentence stays the same.",
        wordHints: [
          { en: "i wanted to tell you", es: "le quería comentar" },
          { en: "has improved a lot", es: "ha mejorado mucho" },
          { en: "participating", es: "participar" },
        ],
      },
      {
        id: "d316-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain to you why we changed the schedule?",
        spanish: "¿Me permite explicarle por qué cambiamos el horario?",
        situationLabel: "Pidiendo permiso",
        why: "*¿Me dejas?* → **¿Me permite?** Same idea — asking permission — but the verb switches to usted form.",
        wordHints: [
          { en: "may i", es: "me permite" },
          { en: "explain to you", es: "explicarle" },
          { en: "why we changed", es: "por qué cambiamos" },
          { en: "the schedule", es: "el horario" },
        ],
      },
      {
        id: "d316-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time, Mrs. Martínez.",
        spanish: "Muchas gracias por su tiempo, señora Martínez.",
        situationLabel: "Cerrando la conferencia",
        why: "*Tu tiempo* → **su tiempo**. One syllable, whole register.",
        wordHints: [
          { en: "thank you so much", es: "muchas gracias" },
          { en: "your time", es: "su tiempo" },
          { en: "mrs.", es: "señora" },
        ],
      },
      {
        id: "d316-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me… would you have a moment?",
        spanish: "Con permiso… ¿tendría un momento?",
        situationLabel: "Interrumpir con respeto",
        why: "*Oye, perdona* with a friend; **Con permiso** with a parent. Different door, same job.",
        wordHints: [
          { en: "excuse me", es: "con permiso" },
          { en: "would you have", es: "tendría" },
          { en: "a moment", es: "un momento" },
        ],
      },
    ],
  },
  {
    day: 317,
    themeEs: "La primera madre",
    themeEn: "The first mother",
    missionEs: "Abre la primera conferencia en usted y no cambies al inglés.",
    missionEn: "Open the first conference in usted and don't switch to English.",
    line: "La primera se sienta. Empiezas.",
    lineEn: "The first one sits down. You begin.",
    prompts: [
      {
        id: "d317-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment? The table is over here.",
        spanish: "Disculpe, ¿tendría un momento? La mesa está por aquí.",
        situationLabel: "En la puerta",
        why: "Same conditional *tendría* — polite with a parent you just met, not a friend in the hallway.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "would you have", es: "tendría" },
          { en: "the table is over here", es: "la mesa está por aquí" },
        ],
      },
      {
        id: "d317-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that Mateo reads aloud without fear now.",
        spanish: "Le quería comentar que Mateo lee en voz alta sin miedo ahora.",
        situationLabel: "Algo positivo primero",
        why: "*Le quería comentar que* opens with strength before anything harder — same stem, usted form.",
        wordHints: [
          { en: "i wanted to tell you", es: "le quería comentar" },
          { en: "reads aloud", es: "lee en voz alta" },
          { en: "without fear", es: "sin miedo" },
        ],
      },
      {
        id: "d317-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain to you how we read here? It's not like in your country.",
        spanish: "¿Me permite explicarle cómo leemos aquí? No es como en su país.",
        situationLabel: "Antes de la carpeta",
        why: "*¿Me permite explicarle?* — the *le* is usted. With Camila it would be *explicarte*.",
        wordHints: [
          { en: "may i explain", es: "me permite explicarle" },
          { en: "how we read here", es: "cómo leemos aquí" },
          { en: "your country", es: "su país" },
        ],
      },
      {
        id: "d317-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — I know you have another child in third grade.",
        spanish: "Muchas gracias por su tiempo — sé que tiene otro hijo en tercero.",
        situationLabel: "Mira el reloj",
        why: "*Su tiempo* and *tiene* — both usted. The parent hears consistency, not a costume.",
        wordHints: [
          { en: "your time", es: "su tiempo" },
          { en: "you have", es: "tiene" },
          { en: "another child in third", es: "otro hijo en tercero" },
        ],
      },
      {
        id: "d317-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me, how do you pronounce your last name?",
        spanish: "Disculpe, ¿cómo se pronuncia su apellido?",
        situationLabel: "El nombre",
        why: "*Disculpe* before asking something personal — usted keeps the distance that *oye, perdona* would collapse.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "how is it pronounced", es: "cómo se pronuncia" },
          { en: "your last name", es: "su apellido" },
        ],
      },
    ],
  },
  {
    day: 318,
    themeEs: "Un momento difícil",
    themeEn: "A difficult moment",
    missionEs: "Di la verdad en usted aunque te cueste.",
    missionEn: "Tell the truth in usted even when it's hard.",
    line: "Pregunta por qué su hijo reprueba. Sigues en usted.",
    lineEn: "She asks why her son is failing. You stay in usted.",
    prompts: [
      {
        id: "d318-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment more? We haven't finished.",
        spanish: "Disculpe, ¿tendría un momento más? No hemos terminado.",
        situationLabel: "Necesita más tiempo",
        why: "*Un momento más* — asking for more time politely. The conditional *tendría* keeps it soft even when the topic is heavy.",
        wordHints: [
          { en: "would you have", es: "tendría" },
          { en: "a moment more", es: "un momento más" },
          { en: "we haven't finished", es: "no hemos terminado" },
        ],
      },
      {
        id: "d318-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that your son isn't lazy — English reading is hard for him.",
        spanish: "Le quería comentar que su hijo no es vago — le cuesta la lectura en inglés.",
        situationLabel: "Antes de los números",
        why: "Same stem, harder content. *Le quería comentar que* works for good news and for news that's hard to hear.",
        wordHints: [
          { en: "your son isn't lazy", es: "su hijo no es vago" },
          { en: "reading is hard for him", es: "le cuesta la lectura" },
          { en: "in english", es: "en inglés" },
        ],
      },
      {
        id: "d318-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain to you how we calculate the grade?",
        spanish: "¿Me permite explicarle cómo calculamos la nota?",
        situationLabel: "El sistema de notas",
        why: "*¿Me permite explicarle?* buys you thirty seconds to organize a hard answer — permission before explanation.",
        wordHints: [
          { en: "may i explain", es: "me permite explicarle" },
          { en: "how we calculate", es: "cómo calculamos" },
          { en: "the grade", es: "la nota" },
        ],
      },
      {
        id: "d318-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — I understand this isn't easy.",
        spanish: "Muchas gracias por su tiempo — entiendo que esto no es fácil.",
        situationLabel: "Después del silencio",
        why: "Closing with *su tiempo* and empathy — the register stays formal even when the room was emotional.",
        wordHints: [
          { en: "your time", es: "su tiempo" },
          { en: "i understand", es: "entiendo" },
          { en: "this isn't easy", es: "esto no es fácil" },
        ],
      },
      {
        id: "d318-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me, let me say it another way.",
        spanish: "Disculpe, déjeme decirlo de otra forma.",
        situationLabel: "Empezar de nuevo",
        why: "*Déjeme* — usted imperative. You're asking permission to restart without dropping register.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "let me say it", es: "déjeme decirlo" },
          { en: "another way", es: "de otra forma" },
        ],
      },
    ],
  },
  {
    day: 319,
    themeEs: "La misma frase, en tú",
    themeEn: "The same phrase, in tú",
    missionEs: "Cuenta la conferencia a Camila con los mismos stems en tú.",
    missionEn: "Tell Camila about the conference with the same stems in tú.",
    line: "Con la mamá: usted. Contigo: tú. Mismo mensaje.",
    lineEn: "With the mother: usted. With you: tú. Same message.",
    prompts: [
      {
        id: "d319-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Hey, do you have a moment? I need to tell you about the conference.",
        spanish: "Oye, ¿tienes un momento? Necesito contarte la conferencia.",
        situationLabel: "En el café",
        why: "Same message, two doors. With the parent: *Disculpe, ¿tendría?* With Camila: *Oye, ¿tienes?*",
        wordHints: [
          { en: "hey", es: "oye" },
          { en: "do you have", es: "tienes" },
          { en: "a moment", es: "un momento" },
          { en: "i need to tell you", es: "necesito contarte" },
        ],
      },
      {
        id: "d319-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that I almost cried with the third mother.",
        spanish: "Te quería comentar que casi lloro con la tercera madre.",
        situationLabel: "Desahogo",
        why: "*Le quería* with the parent, *te quería* with Camila — same stem, different pronoun.",
        wordHints: [
          { en: "i wanted to tell you", es: "te quería comentar" },
          { en: "i almost cried", es: "casi lloro" },
          { en: "the third mother", es: "la tercera madre" },
        ],
      },
      {
        id: "d319-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain to you what I told her about the grades?",
        spanish: "¿Me dejas explicarte lo que le dije sobre las notas?",
        situationLabel: "Retelling",
        why: "With the mother: *¿me permite explicarle?* With you: *¿me dejas explicarte?* — side by side.",
        wordHints: [
          { en: "can i explain", es: "me dejas explicarte" },
          { en: "what i told her", es: "lo que le dije" },
          { en: "about the grades", es: "sobre las notas" },
        ],
      },
      {
        id: "d319-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — you listened for half an hour.",
        spanish: "Muchas gracias por tu tiempo — me escuchaste media hora.",
        situationLabel: "A Camila",
        why: "*Por tu tiempo* with a friend. *Por su tiempo* with a parent. Same gratitude, different register.",
        wordHints: [
          { en: "your time", es: "tu tiempo" },
          { en: "you listened", es: "me escuchaste" },
          { en: "half an hour", es: "media hora" },
        ],
      },
      {
        id: "d319-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — I almost said *con permiso* to the waiter.",
        spanish: "Oye, perdona — casi le digo *con permiso* al mesero.",
        situationLabel: "Risa de registro",
        why: "*Con permiso* with parents; *oye, perdona* with Camila. When you've been in usted all day, the switch takes a beat.",
        wordHints: [
          { en: "hey, sorry", es: "oye, perdona" },
          { en: "i almost said", es: "casi le digo" },
          { en: "to the waiter", es: "al mesero" },
        ],
      },
    ],
  },
  {
    day: 320,
    themeEs: "Cambiando en seco",
    themeEn: "Switching cold",
    missionEs: "Sale la mamá, entra Camila. Cambia de registro sin pensarlo.",
    missionEn: "The mother leaves, Camila arrives. Switch register without thinking about it.",
    line: "Sale la mamá. Entra Camila. Mismo pasillo, treinta segundos de diferencia.",
    lineEn: "The mother leaves. Camila arrives. Same hallway, thirty seconds apart.",
    prompts: [
      {
        id: "d320-oye-tienes-un-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Hey, do you have a minute? I just came out of a rough one.",
        spanish: "Oye, ¿tienes un momento? Acabo de salir de una difícil.",
        situationLabel: "Camila en el pasillo",
        why: "*Una difícil* — the noun is gone and everyone still knows what you mean. That's fluency, not shortcut.",
        wordHints: [
          { en: "do you have a minute", es: "tienes un momento" },
          { en: "i just came out of", es: "acabo de salir de" },
          { en: "a rough one", es: "una difícil" },
        ],
      },
      {
        id: "d320-te-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that I called a mother \"usted\" and then almost did it to you.",
        spanish: "Te quería comentar que le hablé de usted a una mamá y casi te lo hago a ti.",
        situationLabel: "El casi-error",
        why: "*Hablarle de usted a alguien* is the set phrase for addressing someone formally — and *casi te lo hago* is the whole day in four words.",
        wordHints: [
          { en: "i addressed her formally", es: "le hablé de usted" },
          { en: "almost", es: "casi" },
          { en: "did it to you", es: "te lo hago a ti" },
        ],
      },
      {
        id: "d320-me-dejas-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain? Because it sounds worse than it was.",
        spanish: "¿Me dejas explicarte? Porque suena peor de lo que fue.",
        situationLabel: "Antes de que opine",
        why: "*Peor de lo que fue* — comparing against a clause needs *de lo que*, not *que*.",
        wordHints: [
          { en: "can i explain", es: "me dejas explicarte" },
          { en: "it sounds worse", es: "suena peor" },
          { en: "than it was", es: "de lo que fue" },
        ],
      },
      {
        id: "d320-gracias-por-tu-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — and I mean it differently than I did in there.",
        spanish: "Muchas gracias por tu tiempo, y te lo digo distinto que allá adentro.",
        situationLabel: "La misma frase, otro peso",
        why: "The identical sentence in *tú* and in *usted* does not mean the same thing. This is the day you get to feel that.",
        wordHints: [
          { en: "for your time", es: "por tu tiempo" },
          { en: "i mean it differently", es: "te lo digo distinto" },
          { en: "in there", es: "allá adentro" },
        ],
      },
      {
        id: "d320-oye-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — I still have the conference voice on.",
        spanish: "Oye, perdona, todavía tengo la voz de la conferencia puesta.",
        situationLabel: "La voz que no se apaga",
        why: "*Tener puesta* a voice the way you'd have on a coat. Spanish lets you wear a register.",
        wordHints: [
          { en: "i still have on", es: "todavía tengo puesta" },
          { en: "the conference voice", es: "la voz de la conferencia" },
        ],
      },
    ],
  },
  {
    day: 321,
    themeEs: "La conferencia entera",
    themeEn: "The whole conference",
    missionEs: "Seis horas de usted. Vuelve al tú y cuéntale el día.",
    missionEn: "Six hours of usted. Come back to tú and tell her the day.",
    line: "Seis horas. Once familias. Usted todo el día. Tú a las cuatro.",
    lineEn: "Six hours. Eleven families. Usted all day. Tú at four.",
    prompts: [
      {
        id: "d321-oye-tienes-un-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Hey, do you have a minute? I've been on my feet since one.",
        spanish: "Oye, ¿tienes un momento? Llevo de pie desde la una.",
        situationLabel: "Camila llega con café",
        why: "*Llevo de pie desde…* — *llevar* plus a state is how Spanish counts how long something has been going on.",
        wordHints: [
          { en: "i've been on my feet", es: "llevo de pie" },
          { en: "since one", es: "desde la una" },
        ],
      },
      {
        id: "d321-te-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that today I didn't switch to English once.",
        spanish: "Te quería comentar que hoy no me cambié al inglés ni una vez.",
        situationLabel: "El número del día",
        why: "*Ni una vez* at the end. The whole achievement fits in three words and none of them are about learning.",
        wordHints: [
          { en: "i didn't switch", es: "no me cambié" },
          { en: "to english", es: "al inglés" },
          { en: "not once", es: "ni una vez" },
        ],
      },
      {
        id: "d321-me-dejas-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain? The last father asked me the same question three times.",
        spanish: "¿Me dejas explicarte? El último papá me hizo la misma pregunta tres veces.",
        situationLabel: "El último papá",
        why: "*Hacer una pregunta* — you make a question in Spanish, you don't ask one.",
        wordHints: [
          { en: "the last father", es: "el último papá" },
          { en: "asked me", es: "me hizo" },
          { en: "three times", es: "tres veces" },
        ],
      },
      {
        id: "d321-gracias-por-tu-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time, Camila. You helped me rehearse.",
        spanish: "Muchas gracias por tu tiempo, Camila. Me ayudaste a ensayar.",
        situationLabel: "A ella sí, de verdad",
        why: "You said this phrase eleven times today in *usted*. Say it once in *tú* and hear what changes.",
        wordHints: [
          { en: "for your time", es: "por tu tiempo" },
          { en: "you helped me", es: "me ayudaste" },
          { en: "rehearse", es: "ensayar" },
        ],
      },
      {
        id: "d321-oye-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — I grabbed the wrong folder and just kept going.",
        spanish: "Oye, perdona, agarré la carpeta equivocada y seguí como si nada.",
        situationLabel: "El error que no te frenó",
        why: "*Como si nada* — as if it were nothing. The recovery, not the mistake, is the thing worth practicing.",
        wordHints: [
          { en: "i grabbed", es: "agarré" },
          { en: "the wrong folder", es: "la carpeta equivocada" },
          { en: "just kept going", es: "seguí como si nada" },
        ],
      },
    ],
  },
  {
    day: 322,
    themeEs: "Repaso: Cambiar de registro",
    themeEn: "Review: Switching register",
    missionEs: "Usted con la farmacéutica, tú con Camila. En el mismo cuarto.",
    missionEn: "Usted with the pharmacist, tú with Camila. In the same room.",
    line: "Una receta mal puesta, una farmacéutica sola en el mostrador, y Camila esperando.",
    lineEn: "A prescription filled wrong, one pharmacist alone at the counter, and Camila waiting.",
    prompts: [
      {
        id: "d322-oye-tienes-un-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment? It's about a prescription from last week.",
        spanish: "Disculpe, ¿tendría un momento? Es por una receta de la semana pasada.",
        situationLabel: "En el mostrador",
        why: "The usted form of the week's first stem, used on a stranger who has no idea you practiced it.",
        wordHints: [
          { en: "would you have a moment", es: "tendría un momento" },
          { en: "it's about", es: "es por" },
          { en: "a prescription", es: "una receta" },
        ],
      },
      {
        id: "d322-te-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to mention that the doctor changed the dose and it isn't on the label.",
        spanish: "Le quería comentar que el doctor cambió la dosis y no está en la etiqueta.",
        situationLabel: "El problema, sin acusar",
        why: "*Le quería comentar* softens a complaint into a mention. Nobody gets blamed and the problem still gets said.",
        wordHints: [
          { en: "i wanted to mention", es: "le quería comentar" },
          { en: "changed the dose", es: "cambió la dosis" },
          { en: "the label", es: "la etiqueta" },
        ],
      },
      {
        id: "d322-me-dejas-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain? I have the message from the clinic on my phone.",
        spanish: "¿Me permite explicarle? Tengo el mensaje de la clínica en el teléfono.",
        situationLabel: "Con la prueba en la mano",
        why: "*¿Me permite explicarle?* buys you thirty seconds from someone who has a line behind you.",
        wordHints: [
          { en: "may i explain", es: "me permite explicarle" },
          { en: "the message", es: "el mensaje" },
          { en: "from the clinic", es: "de la clínica" },
        ],
      },
      {
        id: "d322-gracias-por-tu-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you very much for your time — you saved me a trip.",
        spanish: "Muchas gracias por su tiempo, me ahorró un viaje.",
        situationLabel: "Cerrando en usted",
        why: "*Ahorrarle un viaje a alguien* — the concrete thanks always lands better than the general one.",
        wordHints: [
          { en: "for your time", es: "por su tiempo" },
          { en: "you saved me", es: "me ahorró" },
          { en: "a trip", es: "un viaje" },
        ],
      },
      {
        id: "d322-oye-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — I kept you waiting twenty minutes for a box of pills.",
        spanish: "Oye, perdona, te tuve veinte minutos esperando por una caja de pastillas.",
        situationLabel: "Y de vuelta al tú",
        why: "One step toward the door and the register flips back. That switch, made without thinking, is the whole week.",
        wordHints: [
          { en: "i kept you waiting", es: "te tuve esperando" },
          { en: "twenty minutes", es: "veinte minutos" },
          { en: "a box of pills", es: "una caja de pastillas" },
        ],
      },
    ],
  },
];
