import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 2 — "La broma que salió sola" (days 281–287).
 * Marlana tries light teasing with Camila and learns to give and take a joke
 * without losing the thread — at the café, at school, and in the family chat.
 */
export const priWeek2ReadingDays: ReadingDay[] = [
  {
    day: 281,
    themeEs: "El primer intento",
    storyTitle: "La broma que salió sola",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "tomar el pelo", en: "to tease, to pull someone's leg", example: "Te estoy tomando el pelo, no te enojes." },
      { es: "exagerar", en: "to exaggerate", example: "No exageres, fue una broma pequeña." },
      { es: "tomarse a pecho", en: "to take something to heart", example: "¿Te lo tomaste a pecho?" },
      { es: "mira quién habla", en: "look who's talking", example: "Mira quién habla, la reina del café." },
      { es: "en serio", en: "seriously, for real", example: "¿En serio? ¿Crees que me enojé?" },
    ],
    dialogue: {
      title: "La reina del café",
      situation: "Primer jueves de primavera; Camila llega con dos tazas",
      lines: [
        { speaker: "B", es: "Hoy practicamos humor. Nada pesado, nada cruel. Bromas suaves.", en: "Today we practice humor. Nothing heavy, nothing cruel. Light teasing." },
        { speaker: "A", es: "Eso me da más miedo que el subjuntivo.", en: "That scares me more than the subjunctive." },
        { speaker: "B", es: "Empieza tú. Dime algo sobre mí que no sea un cumplido.", en: "You start. Tell me something about me that isn't a compliment." },
        { speaker: "A", es: "Camila… tú llegas tan temprano que parece que vives aquí.", en: "Camila… you arrive so early it looks like you live here." },
        { speaker: "B", es: "¿En serio? ¿Eso fue la broma?", en: "Seriously? That was the joke?" },
        { speaker: "A", es: "Te estoy tomando el pelo, no te enojes. ¡Qué va! Tú eres la que siempre trae postre.", en: "I'm teasing you, don't get mad. No way! You're the one who always brings dessert." },
        { speaker: "B", es: "No exageres, fue una broma pequeña. Mira quién habla, la que se pone roja antes de terminar la frase.", en: "Don't exaggerate, it was a small joke. Look who's talking — the one who turns red before finishing the sentence." },
        { speaker: "A", es: "¿En serio? ¿Te lo tomaste a pecho?", en: "Seriously? Did you take it to heart?" },
        { speaker: "B", es: "No. Pero casi. Eso es lo que hay que practicar: decir la broma y decir que es broma.", en: "No. But almost. That's what you have to practice: say the joke and say it's a joke." },
      ],
    },
  },
  {
    day: 282,
    themeEs: "Camila devuelve la broma",
    storyTitle: "La broma que salió sola",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "devolver", en: "to give back, to return", example: "Te devuelven la broma y te quedas callada." },
      { es: "ponerse roja", en: "to turn red, to blush", example: "Te estoy tomando el pelo y tú te pones roja." },
      { es: "miss", en: "miss (as in Miss Punctuality)", example: "Mira quién habla, miss puntualidad." },
      { es: "de verdad", en: "for real, truly", example: "Nunca te he visto enojada de verdad." },
      { es: "empezar", en: "to start, to begin", example: "Te estoy tomando el pelo, pero tú empezaste." },
    ],
    dialogue: {
      title: "Miss puntualidad",
      situation: "Camila no deja pasar la de ayer",
      lines: [
        { speaker: "B", es: "Ayer me dijiste que llego temprano. Hoy te toca recibir.", en: "Yesterday you told me I arrive early. Today it's your turn to receive." },
        { speaker: "A", es: "¡Qué va! Tú eres la maestra estricta.", en: "No way! You're the strict teacher." },
        { speaker: "B", es: "Te estoy tomando el pelo, Marlana, no corras. Tú llegaste quince minutos antes ayer.", en: "I'm teasing you, Marlana, don't run. You got here fifteen minutes early yesterday." },
        { speaker: "A", es: "No exageres, solo dije que llegas temprano.", en: "Don't exaggerate, I only said you arrive early." },
        { speaker: "B", es: "Mira quién habla, miss puntualidad. ¿En serio? ¿Así te quedas cuando te devuelven la broma?", en: "Look who's talking, Miss Punctuality. Seriously? Is that how you freeze when someone teases you back?" },
        { speaker: "A", es: "Me quedé en blanco. No me enojé.", en: "I went blank. I didn't get mad." },
        { speaker: "B", es: "Ya. Eso también cuenta. Tomarse la broma es la mitad.", en: "Right. That counts too. Taking the joke is half of it." },
        { speaker: "A", es: "¿En serio? ¿Nunca bromeaste con tus estudiantes?", en: "Seriously? You never joked with your students?" },
        { speaker: "B", es: "Con los que ya me conocen, sí. Con los nuevos, espero un mes. Tú ya me conoces.", en: "With the ones who already know me, yes. With new ones, I wait a month. You already know me." },
      ],
    },
  },
  {
    day: 283,
    themeEs: "En el colegio con Rocío",
    storyTitle: "La broma que salió sola",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la queja", en: "the complaint", example: "No es queja formal, es broma." },
      { es: "el lunes", en: "Monday (as in Monday mood)", example: "Tú sabes cómo es el lunes." },
      { es: "odio", en: "I hate (colloquial)", example: "Tú también odias las reuniones." },
      { es: "entre nosotras", en: "between us (women)", example: "Fue un comentario entre nosotras." },
      { es: "la reina de", en: "the queen of (teasing title)", example: "Mira quién habla, la reina de las quejas." },
    ],
    dialogue: {
      title: "Entre nosotras",
      situation: "Marlana le cuenta a Camila lo que pasó con Rocío en el colegio",
      lines: [
        { speaker: "A", es: "Hoy probé una broma con Rocío en la sala de maestras.", en: "Today I tried a joke with Rocío in the teachers' lounge." },
        { speaker: "B", es: "¿Y?", en: "And?" },
        { speaker: "A", es: "Le dije que parecía la reina de las quejas los lunes. Te estoy tomando el pelo, Rocío, tranquila — bueno, se lo dije en voz baja.", en: "I told her she looks like the queen of complaints on Mondays. I'm teasing you, Rocío, relax — well, I said it quietly." },
        { speaker: "B", es: "¿Se rió?", en: "Did she laugh?" },
        { speaker: "A", es: "Se rió. Dijo: ¡Qué va! Yo no me quejo tanto. Y yo: Mira quién habla, la que trae tres tazas de café.", en: "She laughed. She said: No way! I don't complain that much. And I said: Look who's talking, the one who brings three cups of coffee." },
        { speaker: "B", es: "Bien. ¿Alguien más escuchó?", en: "Good. Did anyone else hear?" },
        { speaker: "A", es: "Delia pasó y sonrió. Rocío dijo: No exageres, Marlana, fue un comentario entre nosotras.", en: "Delia walked by and smiled. Rocío said: Don't exaggerate, Marlana, it was a comment between us." },
        { speaker: "B", es: "¿En serio? ¿Así reaccionan todas en el colegio?", en: "Seriously? Is that how everyone reacts at school?" },
        { speaker: "A", es: "No sé. Pero con Rocío funcionó. Mismo tono que contigo, otro público.", en: "I don't know. But with Rocío it worked. Same tone as with you, different audience." },
      ],
    },
  },
  {
    day: 284,
    themeEs: "El grupo de la familia",
    storyTitle: "La broma que salió sola",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "el grupo", en: "the group chat", example: "En el grupo de la familia pasa todo." },
      { es: "contestar", en: "to reply, to answer", example: "El que no contesta nunca." },
      { es: "quemar", en: "to burn (food)", example: "Tú eres el que quema el arroz." },
      { es: "competencia", en: "competition", example: "No es competencia, Kevin." },
      { es: "ofensivo", en: "offensive", example: "¿Eso les pareció ofensivo?" },
    ],
    dialogue: {
      title: "Mamá y los stickers",
      situation: "Marlana le enseña a Camila el grupo de WhatsApp de su familia",
      lines: [
        { speaker: "A", es: "Mira el grupo de mi familia. Mamá mandó: \"¿Llegaste bien, mija?\" Yo: \"Sí, tarde pero bien.\"", en: "Look at my family group chat. Mom sent: \"Did you get there okay, honey?\" Me: \"Yes, late but okay.\"" },
        { speaker: "B", es: "Normal.", en: "Normal." },
        { speaker: "A", es: "Kevin: \"Tres horas tarde otra vez.\" Yo: No exageres, fue media hora, no tres horas.", en: "Kevin: \"Three hours late again.\" Me: Don't exaggerate, it was half an hour, not three hours." },
        { speaker: "B", es: "Ajá.", en: "Mm-hm." },
        { speaker: "A", es: "Después dije: Mira quién habla, el que no contesta nunca. Kevin: ¡Qué va! Tú eres el que quema el arroz.", en: "Then I said: Look who's talking, the one who never replies. Kevin: No way! You're the one who burns the rice." },
        { speaker: "B", es: "Suena a mi familia, pero en español.", en: "Sounds like my family, but in Spanish." },
        { speaker: "A", es: "Mamá: \"No peleen.\" Y manda stickers a las tres de la mañana. Yo: Mira quién habla, la que manda stickers a las tres de la mañana.", en: "Mom: \"Don't fight.\" And sends stickers at three in the morning. Me: Look who's talking, the one who sends stickers at three in the morning." },
        { speaker: "B", es: "¿En serio? ¿Eso les pareció ofensivo?", en: "Seriously? Did they find that offensive?" },
        { speaker: "A", es: "No. Mamá mandó un corazón. Kevin un emoji de fuego. Te estoy tomando el pelo, mamá, no llores — eso lo uso yo, no ella.", en: "No. Mom sent a heart. Kevin a fire emoji. I'm teasing you, Mom, don't cry — that's my line, not hers." },
      ],
    },
  },
  {
    day: 285,
    themeEs: "La broma que sale sola",
    storyTitle: "La broma que salió sola",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "salir solo", en: "to come out on its own", example: "¿Salió solo?" },
      { es: "natural", en: "natural, effortless", example: "Salió natural." },
      { es: "planear", en: "to plan", example: "No planifiqué nada." },
      { es: "gracioso", en: "funny", example: "¿Te pareció gracioso?" },
      { es: "miss seria", en: "Miss Serious (teasing nickname)", example: "Mira quién habla, miss seria de enero." },
    ],
    dialogue: {
      title: "Sin planearlo",
      situation: "Camila se levanta a pedir más café y tropieza con su bolsa",
      lines: [
        { speaker: "A", es: "Camila, tu bolsa tiene más cosas que mi salón de clases.", en: "Camila, your bag has more stuff than my classroom." },
        { speaker: "B", es: "¿En serio? ¿Te pareció gracioso?", en: "Seriously? Did you think that was funny?" },
        { speaker: "A", es: "Te estoy tomando el pelo, ¿viste? No planifiqué nada. Salió solo.", en: "I'm teasing you, see? I didn't plan anything. It came out on its own." },
        { speaker: "B", es: "Me reí antes de pensarlo. ¡Qué va! No estaba nerviosa esta vez — tú.", en: "I laughed before I thought about it. No way! I wasn't nervous this time — you." },
        { speaker: "A", es: "No exageres, fue una frase nada más.", en: "Don't exaggerate, it was just one sentence." },
        { speaker: "B", es: "Mira quién habla, la que decía que no podía bromear. Miss seria de enero.", en: "Look who's talking, the one who said she couldn't joke. Miss Serious from January." },
        { speaker: "A", es: "¿En serio? ¿Así de fácil era?", en: "Seriously? Was it that easy?" },
        { speaker: "B", es: "No siempre. Pero hoy sí. Por eso se llama humor ligero — no pesa.", en: "Not always. But today yes. That's why it's called light humor — it doesn't weigh you down." },
        { speaker: "A", es: "Te estoy tomando el pelo y esta vez te reíste. Eso es nuevo.", en: "I'm teasing you and this time you laughed. That's new." },
      ],
    },
  },
  {
    day: 286,
    themeEs: "Cuando no cae",
    storyTitle: "La broma que salió sola",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "caer", en: "to land (a joke), to go over well", example: "El chiste no cayó." },
      { es: "quedarse en blanco", en: "to go blank", example: "No me enojé, me quedé en blanco." },
      { es: "incómodo", en: "awkward, uncomfortable", example: "Solo hubo silencio incómodo." },
      { es: "arreglar", en: "to fix, to patch up", example: "Lo arreglé con otra frase." },
      { es: "reírse de", en: "to laugh at (oneself)", example: "Me enseñaste a reírme de mis errores." },
    ],
    dialogue: {
      title: "Tal vez no",
      situation: "Marlana intenta una broma sobre el café de Camila y cae un silencio",
      lines: [
        { speaker: "A", es: "Este café sabe a agua de hospital…", en: "This coffee tastes like hospital water…" },
        { speaker: "B", es: "…", en: "…" },
        { speaker: "A", es: "Te estoy tomando el pelo… bueno, tal vez no. Perdón, fue malo.", en: "I'm teasing you… well, maybe not. Sorry, that was bad." },
        { speaker: "B", es: "No fue malo. Solo no cayó. Hay diferencia.", en: "It wasn't bad. It just didn't land. There's a difference." },
        { speaker: "A", es: "¡Qué va! No me enojé, me quedé en blanco.", en: "No way! I didn't get mad, I went blank." },
        { speaker: "B", es: "No exageres, no fue un desastre. Solo hubo silencio incómodo.", en: "Don't exaggerate, it wasn't a disaster. There was just an awkward silence." },
        { speaker: "A", es: "Lo arreglé con otra frase. ¿En serio? ¿Así se arregla, diciendo la verdad?", en: "I fixed it with another sentence. Seriously? Is that how you fix it — by saying the truth?" },
        { speaker: "B", es: "Exacto. Mira quién habla, la que me enseñó a reírme de mis errores.", en: "Exactly. Look who's talking, the one who taught me to laugh at my mistakes." },
        { speaker: "A", es: "Entonces la broma que salió sola y la que no cayó — las dos cuentan.", en: "So the joke that came out on its own and the one that didn't land — both count." },
      ],
    },
  },
  {
    day: 287,
    themeEs: "Repaso: Humor ligero",
    isRecap: true,
    vocab: [
      { es: "el pastel", en: "the cake", example: "Alguien trajo pastel a la sala de maestros." },
      { es: "las velas", en: "the candles", example: "Tú eres la que olvidó las velas." },
      { es: "la nevera", en: "the fridge", example: "Lo metieron en la nevera al lado del pescado." },
      { es: "el cumpleaños", en: "the birthday", example: "Es un cumpleaños, no una boda." },
      { es: "delante de todos", en: "in front of everybody", example: "Yo no canto delante de todos." },
    ],
    dialogue: {
      title: "Pastel en la sala de maestros",
      situation: "Viernes por la tarde — cumpleaños de la señora Ortiz",
      lines: [
        { speaker: "B", es: "Mira el pastel. Las letras me quedaron torcidas.", en: "Look at the cake. The lettering came out crooked." },
        { speaker: "A", es: "Te estoy tomando el pelo, el pastel está bien, nadie va a mirar las letras.", en: "I'm teasing you, the cake is fine, nobody's going to look at the letters." },
        { speaker: "B", es: "Bueno. Entonces tú empiezas la canción.", en: "Fine. Then you start the song." },
        { speaker: "A", es: "¡Qué va! Yo no canto delante de todos.", en: "No way! I'm not singing in front of everybody." },
        { speaker: "B", es: "Hay que hacerlo bien. Faltan las velas, los platos, servilletas de color…", en: "We have to do it right. We're missing the candles, the plates, colored napkins…" },
        { speaker: "A", es: "No exageres, es un cumpleaños, no una boda.", en: "Don't exaggerate, it's a birthday, not a wedding." },
        { speaker: "B", es: "Dice la que llegó a las once y media.", en: "Says the one who got here at eleven thirty." },
        { speaker: "A", es: "Mira quién habla, tú eres la que olvidó las velas.", en: "Look who's talking, you're the one who forgot the candles." },
        { speaker: "B", es: "Ay. Es verdad. Y otra cosa: el pastel estaba en la nevera de abajo.", en: "Oh. That's true. And another thing: the cake was in the downstairs fridge." },
        { speaker: "A", es: "¿En serio? ¿Alguien lo metió en la nevera al lado del pescado?", en: "Seriously? Somebody put it in the fridge next to the fish?" },
        { speaker: "B", es: "Nadie diga nada. Que entre la señora Ortiz y cantamos.", en: "Nobody say a word. Let Mrs. Ortiz come in and we'll sing." },
      ],
    },
  },
];
