import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 11 — "Conversación larga I" (days 344–350).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week11-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek11SpeakDays: SpeakDay[] = [
  {
    day: 344,
    themeEs: "Cuarenta minutos",
    themeEn: "Forty minutes",
    missionEs: "Practica los cinco puentes: vuelve, retoma, recuerda, no olvides, regresa.",
    missionEn: "Practice the five bridges: return, resume, remember, don't forget, get back.",
    line: "Camila pone el temporizador — cuarenta minutos, sin teléfono, sin inglés.",
    lineEn: "Camila sets the timer — forty minutes, no phone, no English.",
    prompts: [
      {
        id: "d344-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about the hospital — is it still as chaotic?",
        spanish: "Volviendo a lo que dijiste del hospital, ¿sigue igual de caótico?",
        situationLabel: "El primer puente",
        why: "*Volviendo a lo que dijiste* is a bridge, not a topic change — you're picking up their thread, not starting yours.",
        wordHints: [
          { en: "going back to", es: "volviendo a" },
          { en: "what you said", es: "lo que dijiste" },
          { en: "the hospital", es: "del hospital" },
        ],
      },
      {
        id: "d344-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, the meeting started well and ended weird.",
        spanish: "Como te contaba, la reunión empezó bien y terminó raro.",
        situationLabel: "Retomar el hilo",
        why: "*Como te contaba* assumes the other person remembers — and in a long talk, they usually do.",
        wordHints: [
          { en: "as i was telling you", es: "como te contaba" },
          { en: "started well", es: "empezó bien" },
          { en: "ended weird", es: "terminó raro" },
        ],
      },
      {
        id: "d344-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me what happened with Diego's mom.",
        spanish: "Eso me recuerda lo que pasó con la mamá de Diego.",
        situationLabel: "Tangente conectada",
        why: "*Eso me recuerda* opens a side door — useful only if you know how to come back.",
        wordHints: [
          { en: "that reminds me", es: "eso me recuerda" },
          { en: "what happened", es: "lo que pasó" },
          { en: "diego's mom", es: "la mamá de diego" },
        ],
      },
      {
        id: "d344-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Rocío says hi.",
        spanish: "Antes de que se me olvide, Rocío te manda saludos.",
        situationLabel: "Lo pequeño que importa",
        why: "*Antes de que se me olvide* is how small things survive a long conversation — you flag them before they vanish.",
        wordHints: [
          { en: "before i forget", es: "antes de que se me olvide" },
          { en: "says hi", es: "manda saludos" },
        ],
      },
      {
        id: "d344-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — you were saying silence is conversation too.",
        spanish: "Donde íbamos, tú decías que el silencio también es conversación.",
        situationLabel: "Volver al hilo",
        why: "*Donde íbamos* is the gentlest way to end a tangent — no apology, just a hand on the shoulder of the talk.",
        wordHints: [
          { en: "where we were", es: "donde íbamos" },
          { en: "you were saying", es: "tú decías" },
          { en: "silence is conversation too", es: "el silencio también es conversación" },
        ],
      },
    ],
  },
  {
    day: 345,
    themeEs: "Volviendo a lo que dijiste",
    themeEn: "Going back to what you said",
    missionEs: "Responde algo que dijeron hace quince minutos — eso demuestra que escuchaste.",
    missionEn: "Answer something they said fifteen minutes ago — that proves you were listening.",
    line: "Minuto veintitrés — y por fin respondes lo del minuto ocho.",
    lineEn: "Minute twenty-three — and you finally answer what she said at minute eight.",
    prompts: [
      {
        id: "d345-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about tired nurses — that happens at school too.",
        spanish: "Volviendo a lo que dijiste de las enfermeras cansadas, eso pasa en la escuela también.",
        situationLabel: "La respuesta tardía",
        why: "Answering something from fifteen minutes ago proves you were listening the whole time — that's what makes a long talk feel like one thing.",
        wordHints: [
          { en: "tired nurses", es: "enfermeras cansadas" },
          { en: "at school too", es: "en la escuela también" },
        ],
      },
      {
        id: "d345-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, yesterday a teacher asked me for help and I didn't know how to say no.",
        spanish: "Como te contaba, ayer una maestra me pidió ayuda y no supe decir que no.",
        situationLabel: "Antes del callback",
        why: "The school parallel sets up the callback — two workplaces, same exhaustion.",
        wordHints: [
          { en: "a teacher asked me", es: "una maestra me pidió" },
          { en: "i didn't know how to say no", es: "no supe decir que no" },
        ],
      },
      {
        id: "d345-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me what you said about translating when you're tired.",
        spanish: "Eso me recuerda lo que dijiste de traducir cuando estás cansada.",
        situationLabel: "Paralelo",
        why: "Camila's tired nurse opens Marlana's tired teacher — *eso me recuerda* connects them.",
        wordHints: [
          { en: "translating", es: "traducir" },
          { en: "when you're tired", es: "cuando estás cansada" },
        ],
      },
      {
        id: "d345-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — I wrote down your idea about silence in the notebook.",
        spanish: "Antes de que se me olvide, anoté tu idea del silencio en el cuaderno.",
        situationLabel: "Guardando la idea",
        why: "Good ideas in long talks need capturing — *anoté* is the verb for not losing them.",
        wordHints: [
          { en: "i wrote down", es: "anoté" },
          { en: "your idea about silence", es: "tu idea del silencio" },
          { en: "in the notebook", es: "en el cuaderno" },
        ],
      },
      {
        id: "d345-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — we were comparing the hospital and the school.",
        spanish: "Donde íbamos, comparábamos el hospital y la escuela.",
        situationLabel: "El hilo principal",
        why: "After the callback lands, *donde íbamos* keeps the forty minutes moving forward.",
        wordHints: [
          { en: "we were comparing", es: "comparábamos" },
          { en: "the hospital", es: "el hospital" },
          { en: "the school", es: "la escuela" },
        ],
      },
    ],
  },
  {
    day: 346,
    themeEs: "Como te contaba",
    themeEn: "As I was telling you",
    missionEs: "Retoma una historia exactamente donde la dejaste — después de una interrupción.",
    missionEn: "Pick up a story exactly where you left off — after an interruption.",
    line: "Pasa el mesero — y retomas justo donde lo dejaste.",
    lineEn: "The waiter passes — and you pick up exactly where you left off.",
    prompts: [
      {
        id: "d346-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said before the waiter came — yes, the same thing happens to me.",
        spanish: "Volviendo a lo que dijiste antes de que viniera el mesero, sí, me pasa igual.",
        situationLabel: "Después del mesero",
        why: "The callback survives the interruption — proof the talk never actually broke.",
        wordHints: [
          { en: "before the waiter came", es: "antes de que viniera el mesero" },
          { en: "the same thing happens to me", es: "me pasa igual" },
        ],
      },
      {
        id: "d346-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, the mother sat down and I had two versions in my head.",
        spanish: "Como te contaba, la madre se sentó y yo tenía dos versiones en la cabeza.",
        situationLabel: "La reunión retomada",
        why: "*Como te contaba* after an interruption is a fluency test — if you can resume, the talk never broke.",
        wordHints: [
          { en: "the mother sat down", es: "la madre se sentó" },
          { en: "two versions in my head", es: "dos versiones en la cabeza" },
        ],
      },
      {
        id: "d346-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me usted week, when I was rehearsing with Rocío.",
        spanish: "Eso me recuerda la semana de usted, cuando ensayaba con Rocío.",
        situationLabel: "Semana 7",
        why: "Two versions in your head — tú and usted — is Week 7 paying off in a long talk.",
        wordHints: [
          { en: "usted week", es: "la semana de usted" },
          { en: "i was rehearsing", es: "ensayaba" },
        ],
      },
      {
        id: "d346-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Yusuf smiled when I mentioned him.",
        spanish: "Antes de que se me olvide, Yusuf sonrió cuando lo mencioné.",
        situationLabel: "El detalle que importa",
        why: "Conference stories have small wins — *sonrió* is the one worth saving.",
        wordHints: [
          { en: "yusuf smiled", es: "yusuf sonrió" },
          { en: "when i mentioned him", es: "cuando lo mencioné" },
        ],
      },
      {
        id: "d346-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — I was telling the meeting with Yusuf's mom.",
        spanish: "Donde íbamos, yo contaba la reunión con la madre de Yusuf.",
        situationLabel: "Veinticinco minutos",
        why: "*Donde íbamos* after the usted tangent — back to the parent conference, still one conversation.",
        wordHints: [
          { en: "i was telling", es: "yo contaba" },
          { en: "yusuf's mom", es: "la madre de yusuf" },
        ],
      },
    ],
  },
  {
    day: 347,
    themeEs: "Eso me recuerda",
    themeEn: "That reminds me",
    missionEs: "Sigue un tangente — y vuelve con donde íbamos.",
    missionEn: "Follow a tangent — and come back with \"where we were.\"",
    line: "Una tangente sobre la mamá de Diego, y sale mejor que el plan.",
    lineEn: "A tangent about Diego's mom, and it goes better than the plan.",
    prompts: [
      {
        id: "d347-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about the woman who translated for her mom — that's Diego again.",
        spanish: "Volviendo a lo que dijiste de la señora que traducía para su mamá, eso es Diego otra vez.",
        situationLabel: "El cierre del tangente",
        why: "The tangent earns its keep when *volviendo a lo que dijiste* ties hospital and school together.",
        wordHints: [
          { en: "the woman who translated", es: "la señora que traducía" },
          { en: "for her mom", es: "para su mamá" },
          { en: "that's diego again", es: "eso es diego otra vez" },
        ],
      },
      {
        id: "d347-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, Diego's mom wanted English only at home.",
        spanish: "Como te contaba, la mamá de Diego quería solo inglés en casa.",
        situationLabel: "Temas grandes, semana 8",
        why: "Week 8's language thread resurfaces naturally in a long talk — that's a callback working.",
        wordHints: [
          { en: "diego's mom", es: "la mamá de diego" },
          { en: "english only at home", es: "solo inglés en casa" },
        ],
      },
      {
        id: "d347-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me Diego's mom and the meeting I never finished.",
        spanish: "Eso me recuerda lo de la mamá de Diego y la reunión que no terminé.",
        situationLabel: "El tangente",
        why: "*Eso me recuerda* is permission to leave the main road — if you come back with *donde íbamos*, the tangent was worth it.",
        wordHints: [
          { en: "diego's mom", es: "la mamá de diego" },
          { en: "the meeting i never finished", es: "la reunión que no terminé" },
        ],
      },
      {
        id: "d347-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Diego read in both languages this weekend.",
        spanish: "Antes de que se me olvide, Diego leyó en los dos idiomas este fin de semana.",
        situationLabel: "Buena noticia",
        why: "Long talks need good news too — *antes de que se me olvide* saves it from the tangent.",
        wordHints: [
          { en: "diego read", es: "diego leyó" },
          { en: "in both languages", es: "en los dos idiomas" },
          { en: "this weekend", es: "este fin de semana" },
        ],
      },
      {
        id: "d347-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — you were telling the hospital story and I connected it to school.",
        spanish: "Donde íbamos, tú contabas lo del hospital y yo conecté con la escuela.",
        situationLabel: "Diez minutos restantes",
        why: "*Faltaban diez minutos y no se sentía* — the tangent didn't cost time, it added thread.",
        wordHints: [
          { en: "you were telling", es: "tú contabas" },
          { en: "i connected it to school", es: "yo conecté con la escuela" },
        ],
      },
    ],
  },
  {
    day: 348,
    themeEs: "Tres cosas que casi se pierden",
    themeEn: "Three things that almost got lost",
    missionEs: "Tres hilos abiertos. Recupéralos todos antes de que se enfríe el café.",
    missionEn: "Three open threads. Get all of them back before the coffee goes cold.",
    line: "Minuto treinta y uno. Tres cosas quedaron a medias.",
    lineEn: "Minute thirty-one. Three things got left half-finished.",
    prompts: [
      {
        id: "d348-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about your brother — did he buy the ticket yet?",
        spanish: "Volviendo a lo que dijiste de tu hermano, ¿ya compró el pasaje?",
        situationLabel: "El hilo de hace diez minutos",
        why: "*El pasaje* rather than *el billete* — the Latin American word, and the one Camila would use.",
        wordHints: [
          { en: "about your brother", es: "de tu hermano" },
          { en: "did he buy", es: "ya compró" },
          { en: "the ticket", es: "el pasaje" },
        ],
      },
      {
        id: "d348-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, Rocío heard me talking with a parent and didn't step in.",
        spanish: "Como te contaba, Rocío me oyó hablar con un papá y no se metió.",
        situationLabel: "Retomando lo tuyo",
        why: "*Meterse* — to butt in. That she didn't is the whole point of the story.",
        wordHints: [
          { en: "heard me talking", es: "me oyó hablar" },
          { en: "with a parent", es: "con un papá" },
          { en: "didn't step in", es: "no se metió" },
        ],
      },
      {
        id: "d348-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me — Diego's mom asked about you.",
        spanish: "Eso me recuerda que la mamá de Diego preguntó por ti.",
        situationLabel: "La tangente que sí vale",
        why: "*Preguntar por alguien* — to ask after someone, not to ask them a question. The preposition changes everything.",
        wordHints: [
          { en: "that reminds me", es: "eso me recuerda" },
          { en: "asked about you", es: "preguntó por ti" },
        ],
      },
      {
        id: "d348-antes-de-que-se-me-olvide",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — I need your address for something.",
        spanish: "Antes de que se me olvide, necesito tu dirección para una cosa.",
        situationLabel: "Lo práctico, ya",
        why: "One clean sentence, no explanation. *Para una cosa* is allowed to stay mysterious.",
        wordHints: [
          { en: "before i forget", es: "antes de que se me olvide" },
          { en: "your address", es: "tu dirección" },
          { en: "for something", es: "para una cosa" },
        ],
      },
      {
        id: "d348-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where were we — you were telling me why she didn't step in.",
        spanish: "Donde íbamos, me estabas contando por qué no se metió.",
        situationLabel: "Devolviéndole el hilo",
        why: "Handing the thread back after your own tangent is the politest move in a long conversation.",
        wordHints: [
          { en: "where were we", es: "donde íbamos" },
          { en: "you were telling me", es: "me estabas contando" },
          { en: "why she didn't step in", es: "por qué no se metió" },
        ],
      },
    ],
  },
  {
    day: 349,
    themeEs: "Cuando se acaba el café",
    themeEn: "When the coffee runs out",
    missionEs: "Las tazas están vacías y nadie se ha levantado. Sigue.",
    missionEn: "The cups are empty and nobody has stood up. Keep going.",
    line: "Las tazas vacías, la mesa todavía llena, y una parte sin terminar.",
    lineEn: "Empty cups, the table still full, and one part unfinished.",
    prompts: [
      {
        id: "d349-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about your brother — where is he going to sleep?",
        spanish: "Volviendo a lo que dijiste de tu hermano, ¿dónde va a dormir?",
        situationLabel: "La pregunta práctica",
        why: "After forty minutes of the interesting parts, the practical question is the one that shows you were listening.",
        wordHints: [
          { en: "about your brother", es: "de tu hermano" },
          { en: "where", es: "dónde" },
          { en: "is he going to sleep", es: "va a dormir" },
        ],
      },
      {
        id: "d349-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, Rocío wants me in the Saturday group and I still haven't answered her.",
        spanish: "Como te contaba, Rocío me quiere en el grupo del sábado y no le he contestado.",
        situationLabel: "Lo tuyo sin resolver",
        why: "*No le he contestado* — present perfect for the silence that's still going on right now.",
        wordHints: [
          { en: "wants me in", es: "me quiere en" },
          { en: "the saturday group", es: "el grupo del sábado" },
          { en: "i haven't answered her", es: "no le he contestado" },
        ],
      },
      {
        id: "d349-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me I have to be at school at seven tomorrow.",
        spanish: "Eso me recuerda que mañana tengo que estar en el colegio a las siete.",
        situationLabel: "La realidad se mete",
        why: "The bridge that lets tomorrow into the conversation without ending it.",
        wordHints: [
          { en: "that reminds me", es: "eso me recuerda" },
          { en: "i have to be", es: "tengo que estar" },
          { en: "at seven", es: "a las siete" },
        ],
      },
      {
        id: "d349-antes-de-que-se-me-olvide",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — thanks for not looking at your phone once.",
        spanish: "Antes de que se me olvide, gracias por no mirar el teléfono ni una vez.",
        situationLabel: "Lo que sí querías decir",
        why: "*Por no mirar* — thanking someone for something they didn't do is a very specific kindness.",
        wordHints: [
          { en: "thanks for not looking at", es: "gracias por no mirar" },
          { en: "the phone", es: "el teléfono" },
          { en: "not once", es: "ni una vez" },
        ],
      },
      {
        id: "d349-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where were we — you hadn't finished the part about your mom.",
        spanish: "Donde íbamos, no habías terminado lo de tu mamá.",
        situationLabel: "Lo que falta",
        why: "*Lo de tu mamá* — two words for a whole subplot. This is why *lo de* is worth owning.",
        wordHints: [
          { en: "you hadn't finished", es: "no habías terminado" },
          { en: "the thing about your mom", es: "lo de tu mamá" },
        ],
      },
    ],
  },
  {
    day: 350,
    themeEs: "Repaso: Conversación larga I",
    themeEn: "Review: The long conversation I",
    missionEs: "Domingo con mamá. Que la llamada pase de la hora sin que se note.",
    missionEn: "Sunday with Mom. Let the call pass an hour without either of you noticing.",
    line: "Domingo por la noche, Atlanta al teléfono, y la llamada pasó de la hora.",
    lineEn: "Sunday night, Atlanta on the phone, and the call went past an hour.",
    prompts: [
      {
        id: "d350-volviendo-a-lo-que-dijiste",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about my aunt — is she actually coming in March or not?",
        spanish: "Volviendo a lo que dijiste de la tía, ¿al final viene en marzo o no?",
        situationLabel: "Fijando la fecha",
        why: "*Al final* — in the end, when all the going back and forth is done. It's how you ask for a decision without saying \"decide.\"",
        wordHints: [
          { en: "about my aunt", es: "de la tía" },
          { en: "in the end", es: "al final" },
          { en: "is she coming", es: "viene" },
        ],
      },
      {
        id: "d350-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, in the end they're not cutting the class.",
        spanish: "Como te contaba, al final no cortan la clase.",
        situationLabel: "Las noticias del colegio",
        why: "Present tense for a decision already made. Spanish uses it for settled facts about the future all the time.",
        wordHints: [
          { en: "in the end", es: "al final" },
          { en: "they're not cutting", es: "no cortan" },
          { en: "the class", es: "la clase" },
        ],
      },
      {
        id: "d350-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me — you never told me how the appointment went.",
        spanish: "Eso me recuerda que nunca me contaste cómo te fue en la cita.",
        situationLabel: "Lo que ella no te contó",
        why: "*¿Cómo te fue?* — how did it go for you. The reflexive is doing the work no English verb does here.",
        wordHints: [
          { en: "you never told me", es: "nunca me contaste" },
          { en: "how it went for you", es: "cómo te fue" },
          { en: "the appointment", es: "la cita" },
        ],
      },
      {
        id: "d350-antes-de-que-se-me-olvide",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Kevin's birthday is Thursday, don't let me forget it.",
        spanish: "Antes de que se me olvide, el cumpleaños de Kevin es el jueves, no me dejes olvidarlo.",
        situationLabel: "El jueves de Kevin",
        why: "Two forgettings in one sentence: the one you're heading off, and the one you're handing to someone else.",
        wordHints: [
          { en: "kevin's birthday", es: "el cumpleaños de Kevin" },
          { en: "don't let me", es: "no me dejes" },
          { en: "forget it", es: "olvidarlo" },
        ],
      },
      {
        id: "d350-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where were we — you were telling me about the neighbor and the tree.",
        spanish: "Donde íbamos, me estabas contando lo de la vecina y el árbol.",
        situationLabel: "La vecina y el árbol",
        why: "An hour in, the phrase that keeps a phone call alive is the one that proves you were still there ten minutes ago.",
        wordHints: [
          { en: "you were telling me", es: "me estabas contando" },
          { en: "the neighbor", es: "la vecina" },
          { en: "the tree", es: "el árbol" },
        ],
      },
    ],
  },
];
