import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 4 — "Lo del ascensor" (days 295–301).
 * Marlana, Rocío, and Doña Carmen get stuck between floors with a crock pot
 * of soup; Marlana retells the incident at parent night and Thursday café
 * with growing drama and the week's five storytelling stems.
 */
export const priWeek4ReadingDays: ReadingDay[] = [
  {
    day: 295,
    themeEs: "El ascensor se paró",
    storyTitle: "Lo del ascensor",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el ascensor", en: "the elevator", example: "No te vas a creer lo que pasó en el ascensor hoy." },
      { es: "para colmo", en: "on top of that, as if that weren't enough", example: "Para colmo, la noche de padres empezaba en veinte minutos." },
      { es: "de golpe", en: "suddenly, all at once", example: "El ascensor se paró de golpe entre dos pisos." },
      { es: "la olla", en: "the pot", example: "Doña Carmen llevaba una olla de sopa." },
      { es: "atrapado/a", en: "trapped", example: "Estamos atrapadas entre el quinto y el sexto piso." },
    ],
    dialogue: {
      title: "Entre el quinto y el sexto",
      situation: "Marlana le cuenta a Camila por audio cómo empezó todo",
      lines: [
        { speaker: "A", es: "Camila, no te vas a creer lo que pasó en el ascensor hoy. Rocío, Doña Carmen y yo.", en: "Camila, you're not going to believe what happened in the elevator today. Rocío, Doña Carmen, and me." },
        { speaker: "B", es: "¿Doña Carmen? ¿La mamá de Sofía?", en: "Doña Carmen? Sofía's mom?" },
        { speaker: "A", es: "Esa. Venía con una olla de sopa para la noche de padres. Subimos los tres al ascensor y, de golpe, se paró.", en: "That one. She was carrying a pot of soup for parent night. The three of us got in the elevator and suddenly it stopped." },
        { speaker: "B", es: "Ay, no. ¿Dónde se quedaron?", en: "Oh no. Where did you get stuck?" },
        { speaker: "A", es: "Imagínate que estamos atrapadas entre el quinto y el sexto piso. Para colmo, la noche de padres empezaba en veinte minutos.", en: "Picture us trapped between the fifth and sixth floor. And on top of that, parent night started in twenty minutes." },
        { speaker: "B", es: "¿Y Rocío?", en: "And Rocío?" },
        { speaker: "A", es: "Rocío respiraba hondo. Doña Carmen apretaba la olla. Y de repente, ¡pum!, el ascensor se movió un centímetro y todas gritamos.", en: "Rocío was breathing deep. Doña Carmen was clutching the pot. And suddenly, bam — the elevator moved an inch and we all screamed." },
        { speaker: "B", es: "Marlana. Sigue. Esto apenas empieza.", en: "Marlana. Keep going. This is just getting started." },
      ],
    },
  },
  {
    day: 296,
    themeEs: "Atrapadas con la olla",
    storyTitle: "Lo del ascensor",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "derramarse", en: "to spill", example: "Para colmo, se derramó un poco de caldo." },
      { es: "el botón de emergencia", en: "the emergency button", example: "Alguien apretó el botón de emergencia otra vez." },
      { es: "como si nada", en: "as if nothing were happening", example: "Tuve que sonreír como si nada pasara." },
      { es: "respirar hondo", en: "to breathe deeply", example: "Rocío dijo: \"Respiremos.\"" },
      { es: "el intercom", en: "the intercom", example: "El intercom no funcionaba." },
    ],
    dialogue: {
      title: "Diez minutos y una olla",
      situation: "Los minutos dentro del ascensor",
      lines: [
        { speaker: "A", es: "No te vas a creer lo que dijo Rocío para calmar a Doña Carmen: \"Respiremos, ya van a venir.\"", en: "You won't believe what Rocío said to calm Doña Carmen: \"Let's breathe, they'll come soon.\"" },
        { speaker: "B", es: "Suena muy Rocío.", en: "Sounds very Rocío." },
        { speaker: "A", es: "Para colmo, la tapa de la olla se movió y se derramó un poco. El olor a sopa llenó todo.", en: "And on top of that, the pot lid shifted and a little spilled. The smell of soup filled everything." },
        { speaker: "A", es: "Para colmo, el celular de Doña Carmen no tenía señal. Y lo peor es que tuve que sonreír como si nada pasara.", en: "On top of that, Doña Carmen's phone had no signal. And the worst part is I had to smile like nothing was happening." },
        { speaker: "B", es: "¿Y tú por dentro?", en: "And you on the inside?" },
        { speaker: "A", es: "Imagínate que Rocío dice \"respiremos\" y yo traduzco al inglés en mi cabeza porque no sé qué decir en español.", en: "Picture Rocío saying \"let's breathe\" and me translating to English in my head because I don't know what to say in Spanish." },
        { speaker: "A", es: "Y de repente, ¡pum!, alguien apretó el botón de emergencia otra vez y pasó un estudiante por el pasillo.", en: "And suddenly, bam — someone pressed the emergency button again and a student walked by in the hallway." },
        { speaker: "B", es: "¿Te oyó?", en: "Did they hear you?" },
        { speaker: "A", es: "Seguro que sí. Mañana te cuento cómo salimos.", en: "Probably. Tomorrow I'll tell you how we got out." },
      ],
    },
  },
  {
    day: 297,
    themeEs: "Las luces se apagaron",
    storyTitle: "Lo del ascensor",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el caldo", en: "the broth", example: "Vimos el caldo en el piso." },
      { es: "la alarma", en: "the alarm", example: "La alarma no paraba de sonar." },
      { es: "los bomberos", en: "the firefighters", example: "Escuchamos: \"¿Hay alguien adentro?\"" },
      { es: "a medias", en: "halfway, partway", example: "Las puertas se abrieron a medias en el quinto piso." },
      { es: "frente a", en: "in front of", example: "Salimos frente a un grupo de quinto grado." },
    ],
    dialogue: {
      title: "¡Pum! y las luces",
      situation: "La parte oscura y la salida",
      lines: [
        { speaker: "A", es: "No te vas a creer lo que pasó cuando se apagaron las luces. Doña Carmen empezó a rezar en voz baja.", en: "You won't believe what happened when the lights went out. Doña Carmen started praying quietly." },
        { speaker: "B", es: "Marlana…", en: "Marlana…" },
        { speaker: "A", es: "Para colmo, mi celular tenía dos por ciento de batería. Para colmo, la alarma no paraba.", en: "On top of that, my phone had two percent battery. On top of that, the alarm wouldn't stop." },
        { speaker: "A", es: "Y de repente, ¡pum!, volvieron las luces y vimos el caldo en el piso. Y de repente, ¡pum!, las puertas se abrieron a medias en el quinto piso.", en: "And suddenly, bam — the lights came back and we saw the broth on the floor. And suddenly, bam — the doors opened halfway on the fifth floor." },
        { speaker: "B", es: "¿Cómo salieron?", en: "How did you get out?" },
        { speaker: "A", es: "Un bombero nos dio la mano. Y lo peor es que salimos frente a un grupo de quinto grado que preguntaba: \"¿Qué les pasó?\"", en: "A firefighter gave us his hand. And the worst part is we got out in front of a fifth-grade group asking: \"What happened to you?\"" },
        { speaker: "A", es: "Imagínate que sales del ascensor y la directora ya te está esperando con una carpeta.", en: "Picture stepping out of the elevator and the principal already waiting with a folder." },
        { speaker: "B", es: "¿Y la sopa?", en: "And the soup?" },
        { speaker: "A", es: "Esa sobrevivió. Yo no tanto.", en: "That survived. I didn't, quite." },
      ],
    },
  },
  {
    day: 298,
    themeEs: "Contárselo en la noche de padres",
    storyTitle: "Lo del ascensor",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "contarlo", en: "to tell it, to recount it", example: "Me gustó contarlo." },
      { es: "sin darse cuenta", en: "without realizing", example: "Usé las cinco muletillas sin darme cuenta." },
      { es: "la mesa", en: "the table", example: "Toda la mesa se rió." },
      { es: "desmayarse", en: "to faint", example: "Yo me hubiera desmayado." },
      { es: "el cardigan", en: "the cardigan", example: "Me manché el cardigan de caldo." },
    ],
    dialogue: {
      title: "La mesa de galletas",
      situation: "Marlana cuenta la historia en la noche de padres",
      lines: [
        { speaker: "A", es: "Camila, no te vas a creer lo que le conté a una mamá en la noche de padres. Empecé con el ascensor y terminé con el cardigan manchado.", en: "Camila, you won't believe what I told a mom at parent night. I started with the elevator and ended with the stained cardigan." },
        { speaker: "B", es: "¿Y usaste los stems?", en: "And did you use the stems?" },
        { speaker: "A", es: "Para colmo, usé las cinco muletillas sin darme cuenta. Para colmo, otra maestra dijo: \"A mí también me pasó, pero sin sopa.\"", en: "On top of that, I used all five stems without realizing. On top of that, another teacher said: \"It happened to me too, but without soup.\"" },
        { speaker: "A", es: "Y de repente, ¡pum!, toda la mesa se rió cuando dije \"¡pum!\" en voz alta.", en: "And suddenly, bam — the whole table laughed when I said \"bam!\" out loud." },
        { speaker: "B", es: "Jajaja. Muy bien.", en: "Haha. Very good." },
        { speaker: "A", es: "Y lo peor es que me gustó contarlo. Imagínate que cuentas la historia y todos dejan de comer galletas.", en: "And the worst part is I enjoyed telling it. Picture telling the story and everyone stops eating cookies." },
        { speaker: "B", es: "Eso es señal de que la historia funciona.", en: "That's a sign the story works." },
        { speaker: "A", es: "Una mamá dijo: \"Yo me hubiera desmayado.\" Y alguien preguntó por la olla, no por nosotras.", en: "One mom said: \"I would have fainted.\" And someone asked about the pot, not about us." },
        { speaker: "B", es: "El jueves quiero la versión completa. Con drama.", en: "Thursday I want the full version. With drama." },
      ],
    },
  },
  {
    day: 299,
    themeEs: "En el café del jueves",
    storyTitle: "Lo del ascensor",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el drama", en: "drama", example: "Le falta más drama al final." },
      { es: "golpear la mesa", en: "to hit the table", example: "Camila golpea la mesa cuando digo \"¡pum!\"" },
      { es: "cuéntame otra vez", en: "tell me again", example: "Cuéntame otra vez desde el ascensor." },
      { es: "peor", en: "worse", example: "Camila tiene una historia peor." },
      { es: "inclinarse", en: "to lean in", example: "La mesa de al lado se inclinó a escuchar." },
    ],
    dialogue: {
      title: "Versión café",
      situation: "Jueves en el café — la historia completa con Camila",
      lines: [
        { speaker: "A", es: "No te vas a creer lo que me pasó el martes en el colegio. ¿Recuerdas que te mandé el audio?", en: "You won't believe what happened to me Tuesday at school. Remember I sent you the voice note?" },
        { speaker: "B", es: "Recuerdo el grito. Cuéntame otra vez. Desde el ascensor.", en: "I remember the scream. Tell me again. From the elevator." },
        { speaker: "A", es: "Imagínate que estamos atrapadas con una olla de sopa y para colmo no hay señal. Y de repente, ¡pum!, se apagan las luces.", en: "Picture us trapped with a pot of soup and on top of that there's no signal. And suddenly, bam — the lights go out." },
        { speaker: "B", es: "¡Pum!", en: "Bam!" },
        { speaker: "A", es: "Exacto. Y lo peor es que tuve que quedarme tranquila delante de Doña Carmen.", en: "Exactly. And the worst part is I had to stay calm in front of Doña Carmen." },
        { speaker: "B", es: "Bien. Pero para colmo, yo tengo una peor. En el hospital, con una camilla y un residente nuevo.", en: "Good. But on top of that, I have a worse one. At the hospital, with a gurney and a new resident." },
        { speaker: "A", es: "Para colmo, Camila tiene una historia del ascensor del hospital peor. Y de repente, ¡pum!, Camila golpea la mesa.", en: "On top of that, Camila has a worse hospital elevator story. And suddenly, bam — Camila hits the table." },
        { speaker: "B", es: "Porque te falta más drama al final. Di algo peor que el cardigan manchado.", en: "Because your ending needs more drama. Say something worse than the stained cardigan." },
        { speaker: "A", es: "Y lo peor es que Camila tiene razón.", en: "And the worst part is Camila is right." },
      ],
    },
  },
  {
    day: 300,
    themeEs: "Con todo el drama",
    storyTitle: "Lo del ascensor",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "hecha en casa", en: "homemade", example: "Doña Carmen me trajo sopa hecha en casa." },
      { es: "el letrero", en: "the sign", example: "Pusieron un letrero en el ascensor." },
      { es: "exagerar", en: "to exaggerate", example: "Me daba vergüenza exagerar." },
      { es: "el momento exacto", en: "the exact moment", example: "Ya lo digo en el momento exacto." },
      { es: "el epílogo", en: "the epilogue", example: "Para colmo, al día siguiente Doña Carmen me trajo sopa." },
    ],
    dialogue: {
      title: "Tercera vez, mejor",
      situation: "Marlana cierra la historia con el epílogo y la lección",
      lines: [
        { speaker: "A", es: "Bueno, versión final. No te vas a creer lo que aprendí contando esta historia.", en: "Okay, final version. You won't believe what I learned telling this story." },
        { speaker: "B", es: "Dime.", en: "Tell me." },
        { speaker: "A", es: "Que casi no la cuento porque me daba vergüenza exagerar. Y lo peor es que la parte más mala fue quedarme callada diez minutos.", en: "That I almost didn't tell it because I was embarrassed to exaggerate. And the worst part is the worst moment was staying quiet for ten minutes." },
        { speaker: "A", es: "Imagínate que cierras los ojos y estás ahí con nosotras y la olla. Y de repente, ¡pum!, ya lo digo en el momento exacto.", en: "Picture closing your eyes and being there with us and the pot. And suddenly, bam — I say it at the exact right moment now." },
        { speaker: "B", es: "Mucho mejor. ¿Y qué pasó después?", en: "Much better. And what happened after?" },
        { speaker: "A", es: "Para colmo, Doña Carmen me trajo sopa hecha en casa al día siguiente. Para colmo, pusieron un letrero: \"Máximo dos personas o una olla.\"", en: "On top of that, Doña Carmen brought me homemade soup the next day. On top of that, they put up a sign: \"Maximum two people or one pot.\"" },
        { speaker: "B", es: "El letrero vale oro.", en: "That sign is gold." },
        { speaker: "A", es: "Ahora me piden que la cuente en la sala de maestros. Rocío dice que le debo una: ella no puede usar el ascensor nunca más.", en: "Now they ask me to tell it in the teachers' lounge. Rocío says I owe her one: she can't use the elevator ever again." },
        { speaker: "B", es: "Historia con sabor. Guardada.", en: "Story with flavor. Saved." },
      ],
    },
  },
  {
    day: 301,
    themeEs: "Repaso: Historias con sabor",
    isRecap: true,
    vocab: [
      { es: "el gancho", en: "the hook", example: "No te vas a creer lo que… es el gancho." },
      { es: "apilar", en: "to stack, to pile on", example: "Puedo apilar tres cosas malas seguidas." },
      { es: "el suspenso", en: "suspense", example: "Y de repente, ¡pum!, despierta el suspenso." },
      { es: "subjetivo", en: "subjective", example: "Lo peor no siempre es lo obvio." },
      { es: "con sabor", en: "with flavor, with personality", example: "Una historia con sabor se cuenta mejor cada vez." },
    ],
    dialogue: {
      title: "Lo del ascensor, resumido",
      situation: "Repaso de la semana — los cinco stems y la historia entera",
      lines: [
        { speaker: "B", es: "Repaso. Cuatro semanas de primavera y ya estás en historias con drama. ¿Qué aprendiste?", en: "Recap. Four weeks of spring and you're already at stories with drama. What did you learn?" },
        { speaker: "A", es: "No te vas a creer lo que mejoró esta semana. Antes contaba hechos. Ahora cuento escenas.", en: "You won't believe what improved this week. Before I reported facts. Now I tell scenes." },
        { speaker: "B", es: "Dame los cinco stems en orden.", en: "Give me the five stems in order." },
        { speaker: "A", es: "Gancho: no te vas a creer lo que… Apilar: para colmo… Giro: y de repente, ¡pum! Peor parte: y lo peor es que… Invitar: imagínate que…", en: "Hook: you're not going to believe what… Pile-on: on top of that… Turn: and suddenly, bam! Worst part: and the worst part is… Invite: just imagine…" },
        { speaker: "B", es: "Ahora la historia en una frase.", en: "Now the story in one sentence." },
        { speaker: "A", es: "Tres mujeres, una olla, un ascensor roto, bomberos, quinto grado, cardigan manchado, letrero nuevo.", en: "Three women, one pot, a broken elevator, firefighters, fifth grade, stained cardigan, new sign." },
        { speaker: "B", es: "Y lo peor es que lo peor no fue el ascensor.", en: "And the worst part isn't the elevator." },
        { speaker: "A", es: "Exacto. Fue quedarme callada diez minutos cuando tenía algo que decir.", en: "Exactly. It was staying quiet ten minutes when I had something to say." },
        { speaker: "B", es: "Imagínate que la próxima semana discutes con alguien y no te quedas callada. Eso es debate suave.", en: "Picture next week disagreeing with someone and not going quiet. That's gentle debate." },
      ],
    },
  },
];
