import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 1 — "Tu estilo" (days 274–280).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week1-frames.ts
 * for the matching `frameStem`.
 */
export const priWeek1SpeakDays: SpeakDay[] = [
  {
    day: 274,
    themeEs: "El primer jueves de primavera",
    themeEn: "The first Thursday of spring",
    missionEs: "Preséntate con personalidad, no con tu cargo.",
    missionEn: "Introduce yourself with personality, not your job title.",
    line: "No eres tu currículum. Eres la anécdota que lo cuenta.",
    lineEn: "You're not your résumé. You're the anecdote that tells it.",
    prompts: [
      {
        id: "d274-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who introduces herself with an anecdote, not a résumé.",
        spanish: "Soy de las que se presentan con una anécdota, no con un currículum.",
        situationLabel: "Primer jueves de primavera",
        why: "*Soy de las que…* opens a self-portrait without sounding like a LinkedIn headline — personality first, credentials second.",
        wordHints: [
          { en: "introduce themselves", es: "se presentan" },
          { en: "an anecdote", es: "una anécdota" },
          { en: "not", es: "no" },
          { en: "a résumé", es: "un currículum" },
        ],
      },
      {
        id: "d274-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is telling stories and getting lost in the details.",
        spanish: "Lo mío es contar historias y perderme en los detalles.",
        situationLabel: "Lo que Camila quiere oír",
        why: "*Lo mío es…* names your lane in one breath — what you'd do even if nobody paid you for it.",
        wordHints: [
          { en: "telling stories", es: "contar historias" },
          { en: "getting lost", es: "perderme" },
          { en: "the details", es: "los detalles" },
        ],
      },
      {
        id: "d274-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I never give the short answer.",
        spanish: "Si algo me define es que nunca doy la respuesta corta.",
        situationLabel: "Un rasgo que lo dice todo",
        why: "*Si algo me define es…* picks one trait and lets it stand for the whole person — no list needed.",
        wordHints: [
          { en: "defines me", es: "me define" },
          { en: "never", es: "nunca" },
          { en: "the short answer", es: "la respuesta corta" },
        ],
      },
      {
        id: "d274-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who listens first and talks after.",
        spanish: "Yo soy más bien de las que escuchan primero y hablan después.",
        situationLabel: "Suavizando el retrato",
        why: "*Más bien* keeps the self-portrait honest — you're not claiming to be the only type, just yours.",
        wordHints: [
          { en: "listen first", es: "escuchan primero" },
          { en: "talk after", es: "hablan después" },
        ],
      },
      {
        id: "d274-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for arriving early and staying late.",
        spanish: "Me conocen por llegar temprano y quedarme tarde.",
        situationLabel: "Cómo te ven los demás",
        why: "*Me conocen por…* shifts the camera — how you look from outside, not how you feel inside.",
        wordHints: [
          { en: "they know me for", es: "me conocen por" },
          { en: "arriving early", es: "llegar temprano" },
          { en: "staying late", es: "quedarme tarde" },
        ],
      },
    ],
  },
  {
    day: 275,
    themeEs: "En el pasillo",
    themeEn: "In the hallway",
    missionEs: "Di quién eres en treinta segundos, sin mencionar tu cargo.",
    missionEn: "Say who you are in thirty seconds, without mentioning your job title.",
    line: "En el pasillo no hay tiempo para un currículum.",
    lineEn: "In the hallway there's no time for a résumé.",
    prompts: [
      {
        id: "d275-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who answers in the hallway with the truth, not the job title.",
        spanish: "Soy de las que en el pasillo responden con la verdad, no con el cargo.",
        situationLabel: "Rocío en el pasillo",
        why: "Rocío asked a real question between bells — *en el pasillo* tells her this answer is the fast, honest version.",
        wordHints: [
          { en: "in the hallway", es: "en el pasillo" },
          { en: "the truth", es: "la verdad" },
          { en: "the job title", es: "el cargo" },
        ],
      },
      {
        id: "d275-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is that students tell me real things.",
        spanish: "Lo mío es que los estudiantes me cuenten cosas de verdad.",
        situationLabel: "Lo que importa en el colegio",
        why: "*Cosas de verdad* — real things, not textbook answers. That's the teacher Marlana actually is.",
        wordHints: [
          { en: "students", es: "los estudiantes" },
          { en: "tell me", es: "me cuenten" },
          { en: "real things", es: "cosas de verdad" },
        ],
      },
      {
        id: "d275-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I'm always in a hurry but never late.",
        spanish: "Si algo me define es que siempre tengo prisa y nunca llego tarde.",
        situationLabel: "La versión del pasillo",
        why: "A contradiction inside one sentence — *prisa* and *nunca llego tarde* — is exactly how a person sounds alive.",
        wordHints: [
          { en: "always in a hurry", es: "siempre tengo prisa" },
          { en: "never late", es: "nunca llego tarde" },
        ],
      },
      {
        id: "d275-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who helps without making a show of it.",
        spanish: "Yo soy más bien de las que ayudan sin hacer show.",
        situationLabel: "Con Rocío",
        why: "*Sin hacer show* — without making a show. Borrowed from English, understood everywhere, very Marlana.",
        wordHints: [
          { en: "help", es: "ayudan" },
          { en: "without making a show", es: "sin hacer show" },
        ],
      },
      {
        id: "d275-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for always having an extra marker.",
        spanish: "Me conocen por tener siempre un marcador extra.",
        situationLabel: "Tu reputación en el colegio",
        why: "Small, specific, true — *un marcador extra* is a whole personality in three words.",
        wordHints: [
          { en: "always", es: "siempre" },
          { en: "an extra marker", es: "un marcador extra" },
        ],
      },
    ],
  },
  {
    day: 276,
    themeEs: "La videollamada",
    themeEn: "The video call",
    missionEs: "Cuéntale a mamá quién eres, no qué has logrado.",
    missionEn: "Tell Mom who you are, not what you've accomplished.",
    line: "A mamá no le cuentas el progreso. Le cuentas la versión con alma.",
    lineEn: "You don't tell Mom about progress. You tell her the version with a soul.",
    prompts: [
      {
        id: "d276-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who tells Mom the version with a joke included.",
        spanish: "Soy de las que le cuentan a mamá la versión con chiste incluido.",
        situationLabel: "Videollamada con Atlanta",
        why: "The Atlanta call gets the warm version — *con chiste incluido* is how you say you're still you, just farther away.",
        wordHints: [
          { en: "tell mom", es: "le cuentan a mamá" },
          { en: "the version", es: "la versión" },
          { en: "joke included", es: "chiste incluido" },
        ],
      },
      {
        id: "d276-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is still being the daughter who calls on Sundays.",
        spanish: "Lo mío es seguir siendo la hija que llama los domingos.",
        situationLabel: "Lo que mamá reconoce",
        why: "*Seguir siendo* — still being. Some things don't change with distance or Spanish level.",
        wordHints: [
          { en: "still being", es: "seguir siendo" },
          { en: "the daughter", es: "la hija" },
          { en: "calls on sundays", es: "llama los domingos" },
        ],
      },
      {
        id: "d276-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I miss Atlanta and I'm not leaving.",
        spanish: "Si algo me define es que extraño Atlanta y no me voy.",
        situationLabel: "Distancia y raíces",
        why: "Two truths in one sentence — missing home and choosing Boston. That's a whole life in twelve words.",
        wordHints: [
          { en: "i miss", es: "extraño" },
          { en: "i'm not leaving", es: "no me voy" },
        ],
      },
      {
        id: "d276-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who goes far away but never leaves completely.",
        spanish: "Yo soy más bien de las que se van lejos pero no se van del todo.",
        situationLabel: "Cómo te ve mamá",
        why: "*No se van del todo* — they never leave completely. Mom will understand that one immediately.",
        wordHints: [
          { en: "go far away", es: "se van lejos" },
          { en: "never leave completely", es: "no se van del todo" },
        ],
      },
      {
        id: "d276-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for being the aunt who sends too many photos.",
        spanish: "Me conocen por ser la tía que manda fotos de más.",
        situationLabel: "En la familia",
        why: "*Fotos de más* — too many photos. Family lore, not a brag.",
        wordHints: [
          { en: "the aunt", es: "la tía" },
          { en: "sends", es: "manda" },
          { en: "too many photos", es: "fotos de más" },
        ],
      },
    ],
  },
  {
    day: 277,
    themeEs: "El código",
    themeEn: "The code",
    missionEs: "Descríbete como alguien que construye cosas, no solo que enseña.",
    missionEn: "Describe yourself as someone who builds things, not just someone who teaches.",
    line: "Enseñas de día. Construyes de noche. Las dos cosas eres tú.",
    lineEn: "You teach by day. You build by night. Both are you.",
    prompts: [
      {
        id: "d277-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who codes at night after grading papers.",
        spanish: "Soy de las que programan de noche después de corregir papeles.",
        situationLabel: "La otra mitad de Marlana",
        why: "Two jobs, one person — *después de corregir papeles* puts the teacher life and the builder life in the same sentence.",
        wordHints: [
          { en: "code", es: "programan" },
          { en: "at night", es: "de noche" },
          { en: "grading papers", es: "corregir papeles" },
        ],
      },
      {
        id: "d277-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is building tools that save other teachers time.",
        spanish: "Lo mío es armar herramientas que le ahorren tiempo a otros maestros.",
        situationLabel: "Lo que construyes",
        why: "*Armar herramientas* — building tools. Not software engineer on a business card, just someone who makes useful things.",
        wordHints: [
          { en: "building tools", es: "armar herramientas" },
          { en: "save time", es: "ahorren tiempo" },
          { en: "other teachers", es: "otros maestros" },
        ],
      },
      {
        id: "d277-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I can't see a problem without wanting to fix it.",
        spanish: "Si algo me define es que no puedo ver un problema sin querer arreglarlo.",
        situationLabel: "La mente de una constructora",
        why: "This sentence works for code, for classrooms, for everything — one trait, two careers.",
        wordHints: [
          { en: "a problem", es: "un problema" },
          { en: "wanting to fix it", es: "querer arreglarlo" },
        ],
      },
      {
        id: "d277-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who tries, fails, and tries again.",
        spanish: "Yo soy más bien de las que prueban, fallan y vuelven a probar.",
        situationLabel: "Cómo programas",
        why: "The real developer loop in one phrase — no degree required.",
        wordHints: [
          { en: "try", es: "prueban" },
          { en: "fail", es: "fallan" },
          { en: "try again", es: "vuelven a probar" },
        ],
      },
      {
        id: "d277-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for being the teacher who also knows about technology.",
        spanish: "Me conocen por ser la maestra que también sabe de tecnología.",
        situationLabel: "Tu reputación doble",
        why: "*También sabe de tecnología* — also knows about technology. The *also* does all the work.",
        wordHints: [
          { en: "the teacher", es: "la maestra" },
          { en: "also", es: "también" },
          { en: "technology", es: "tecnología" },
        ],
      },
    ],
  },
  {
    day: 278,
    themeEs: "Lo que ve Camila",
    themeEn: "What Camila sees",
    missionEs: "Escúchate a ti misma a través de los ojos de una amiga.",
    missionEn: "Hear yourself through a friend's eyes.",
    line: "A veces necesitas que alguien te devuelva tu propia voz.",
    lineEn: "Sometimes you need someone to hand your own voice back to you.",
    prompts: [
      {
        id: "d278-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who doesn't realize how funny she is.",
        spanish: "Soy de las que no se dan cuenta de lo graciosas que son.",
        situationLabel: "El espejo de Camila",
        why: "Camila said this out loud — repeating it back is how you accept a compliment without deflecting.",
        wordHints: [
          { en: "don't realize", es: "no se dan cuenta" },
          { en: "how funny", es: "lo graciosas" },
        ],
      },
      {
        id: "d278-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is that people relax around you without knowing why.",
        spanish: "Lo mío es que la gente se relaje contigo sin saber por qué.",
        situationLabel: "Lo que Camila nombra",
        why: "This one is harder to say about yourself — which is exactly why a friend has to say it first.",
        wordHints: [
          { en: "people relax", es: "la gente se relaje" },
          { en: "without knowing why", es: "sin saber por qué" },
        ],
      },
      {
        id: "d278-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I show up when someone needs you.",
        spanish: "Si algo me define es que aparezco cuando alguien lo necesita.",
        situationLabel: "Lo que te devuelve Camila",
        why: "Camila said this about you out loud — repeating it back in first person is how you accept what a friend sees.",
        wordHints: [
          { en: "i show up", es: "aparezco" },
          { en: "someone needs me", es: "alguien lo necesita" },
        ],
      },
      {
        id: "d278-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who convinces without raising her voice.",
        spanish: "Yo soy más bien de las que convencen sin levantar la voz.",
        situationLabel: "Más suave de lo que crees",
        why: "A preview of debate week — you already persuade; you just don't call it arguing yet.",
        wordHints: [
          { en: "convince", es: "convencen" },
          { en: "without raising her voice", es: "sin levantar la voz" },
        ],
      },
      {
        id: "d278-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for being the gringa who actually speaks Spanish.",
        spanish: "Me conocen por ser la gringa que habla español de verdad.",
        situationLabel: "Tu reputación en el café",
        why: "*De verdad* — for real. Not textbook Spanish. The compliment Camila would give a stranger.",
        wordHints: [
          { en: "the gringa", es: "la gringa" },
          { en: "for real", es: "de verdad" },
          { en: "speaks spanish", es: "habla español" },
        ],
      },
    ],
  },
  {
    day: 279,
    themeEs: "Cuando me llevan la contraria",
    themeEn: "When someone contradicts me",
    missionEs: "Nombra el hábito que te queda: encogerte cuando te contradicen.",
    missionEn: "Name the habit you still have: shrinking when someone contradicts you.",
    line: "Sonar como tú incluye quedarte cuando no están de acuerdo.",
    lineEn: "Sounding like you includes staying when they disagree.",
    prompts: [
      {
        id: "d279-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who says \"you're right\" before thinking about it.",
        spanish: "Soy de las que dicen \"tienes razón\" antes de pensarlo.",
        situationLabel: "El hábito que Camila nombra",
        why: "Honest self-description is the bridge to debate week — you can't fix a habit you won't name.",
        wordHints: [
          { en: "you're right", es: "tienes razón" },
          { en: "before thinking", es: "antes de pensarlo" },
        ],
      },
      {
        id: "d279-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is looking for agreement, not a fight.",
        spanish: "Lo mío es buscar el acuerdo, no la pelea.",
        situationLabel: "Por qué te encoges",
        why: "*Buscar el acuerdo* isn't weakness — but Camila wants you to know when it costs you your opinion.",
        wordHints: [
          { en: "looking for agreement", es: "buscar el acuerdo" },
          { en: "not a fight", es: "no la pelea" },
        ],
      },
      {
        id: "d279-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I avoid confrontation until it explodes.",
        spanish: "Si algo me define es que evito la confrontación hasta que explota.",
        situationLabel: "La confesión honesta",
        why: "*Hasta que explota* — until it blows up. The cost of always agreeing too fast.",
        wordHints: [
          { en: "avoid confrontation", es: "evito la confrontación" },
          { en: "until it blows up", es: "hasta que explota" },
        ],
      },
      {
        id: "d279-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who gives in before finishing the sentence.",
        spanish: "Yo soy más bien de las que ceden antes de terminar la frase.",
        situationLabel: "Lo que quieres cambiar",
        why: "*Ceden antes de terminar la frase* — give in before finishing the sentence. That's the habit spring wants to fix.",
        wordHints: [
          { en: "give in", es: "ceden" },
          { en: "before finishing", es: "antes de terminar" },
          { en: "the sentence", es: "la frase" },
        ],
      },
      {
        id: "d279-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for always looking for the diplomatic way out.",
        spanish: "Me conocen por ser la que siempre busca la salida diplomática.",
        situationLabel: "La pacificadora",
        why: "Camila says *diplomática* like it's a compliment with a footnote — kind, but incomplete.",
        wordHints: [
          { en: "always", es: "siempre" },
          { en: "looks for", es: "busca" },
          { en: "the diplomatic way out", es: "la salida diplomática" },
        ],
      },
    ],
  },
  {
    day: 280,
    themeEs: "Repaso: Tu estilo",
    themeEn: "Review: Your style",
    missionEs: "Di la semana entera en cinco frases.",
    missionEn: "Say the whole week in five sentences.",
    line: "Cinco formas de hablar de ti. Una semana de práctica.",
    lineEn: "Five ways to talk about yourself. One week of practice.",
    prompts: [
      {
        id: "d280-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who doesn't lead with the job title anymore.",
        spanish: "Soy de las que ya no se presentan con el cargo primero.",
        situationLabel: "El repaso de la semana",
        why: "*Ya no* — not anymore. The whole week in three words.",
        wordHints: [
          { en: "not anymore", es: "ya no" },
          { en: "the job title first", es: "el cargo primero" },
        ],
      },
      {
        id: "d280-lo-mio-es",
        frameStem: "Lo mío es…",
        english: "My thing is telling who I am, not what I do.",
        spanish: "Lo mío es contar quién soy, no qué hago.",
        situationLabel: "La lección de la semana",
        why: "*Quién soy, no qué hago* — who I am, not what I do. Spring's whole thesis in one line.",
        wordHints: [
          { en: "who i am", es: "quién soy" },
          { en: "not what i do", es: "no qué hago" },
        ],
      },
      {
        id: "d280-si-algo-me-define",
        frameStem: "Si algo me define es…",
        english: "If something defines me, it's that I don't hide behind work anymore.",
        spanish: "Si algo me define es que ya no me escondo detrás del trabajo.",
        situationLabel: "Tu estilo, en una frase",
        why: "*Detrás del trabajo* — behind work. The old Marlana lived there. The new one doesn't.",
        wordHints: [
          { en: "not anymore", es: "ya no" },
          { en: "hide behind work", es: "me escondo detrás del trabajo" },
        ],
      },
      {
        id: "d280-yo-soy-mas-bien",
        frameStem: "Yo soy más bien…",
        english: "I'm more the type who describes herself without bragging.",
        spanish: "Yo soy más bien de las que se describen sin presumir.",
        situationLabel: "Retrato suave",
        why: "*Sin presumir* — without bragging. Self-description with warmth, not a sales pitch.",
        wordHints: [
          { en: "describe themselves", es: "se describen" },
          { en: "without bragging", es: "sin presumir" },
        ],
      },
      {
        id: "d280-me-conocen-por",
        frameStem: "Me conocen por…",
        english: "People know me for being the one who speaks Spanish with soul.",
        spanish: "Me conocen por ser la que habla español con alma.",
        situationLabel: "Cómo quieres que te vean",
        why: "*Con alma* — with soul. Technique got you here. Personality keeps you.",
        wordHints: [
          { en: "speaks spanish", es: "habla español" },
          { en: "with soul", es: "con alma" },
        ],
      },
    ],
  },
];
