import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 2 — "Humor ligero" (days 281–287).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week2-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek2SpeakDays: SpeakDay[] = [
  {
    day: 281,
    themeEs: "El primer intento",
    themeEn: "The first attempt",
    missionEs: "Haz una broma suave y di que estás tomando el pelo.",
    missionEn: "Make a light tease and say you're pulling their leg.",
    line: "Un chiste empieza diciendo que es broma.",
    lineEn: "A joke starts by saying it's a joke.",
    prompts: [
      {
        id: "d281-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — don't get mad.",
        spanish: "Te estoy tomando el pelo, no te enojes.",
        situationLabel: "Antes de que se lo tome en serio",
        why: "*Te estoy tomando el pelo* is the safety line — say it while you're smiling and nobody has to guess.",
        wordHints: [
          { en: "don't get mad", es: "no te enojes" },
        ],
      },
      {
        id: "d281-que-va",
        frameStem: "¡Qué va!",
        english: "No way! I'm never late.",
        spanish: "¡Qué va! Yo nunca llego tarde.",
        situationLabel: "Camila dice que siempre llegas tarde",
        why: "*¡Qué va!* is a whole sentence of denial — sharper and warmer than a plain *no*.",
        wordHints: [
          { en: "no way", es: "¡qué va!" },
          { en: "i'm never", es: "nunca" },
          { en: "late", es: "tarde" },
        ],
      },
      {
        id: "d281-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate — it was just a small joke.",
        spanish: "No exageres, fue una broma pequeña.",
        situationLabel: "Camila dramatiza tu comentario",
        why: "*No exageres* calls out the drama without shutting down the conversation.",
        wordHints: [
          { en: "don't exaggerate", es: "no exageres" },
          { en: "a small joke", es: "una broma pequeña" },
        ],
      },
      {
        id: "d281-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the queen of coffee.",
        spanish: "Mira quién habla, la reina del café.",
        situationLabel: "Devolviéndole la broma",
        why: "*Mira quién habla* only works between people who already trust each other — the tone does the rest.",
        wordHints: [
          { en: "look who's talking", es: "mira quién habla" },
          { en: "queen", es: "la reina" },
        ],
      },
      {
        id: "d281-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? Did you take it to heart?",
        spanish: "¿En serio? ¿Te lo tomaste a pecho?",
        situationLabel: "Viendo si se enojó",
        why: "*¿En serio?* buys you a second to read the room before you keep going.",
        wordHints: [
          { en: "seriously", es: "¿en serio?" },
          { en: "take it to heart", es: "tomarse a pecho" },
        ],
      },
    ],
  },
  {
    day: 282,
    themeEs: "Camila devuelve la broma",
    themeEn: "Camila teases back",
    missionEs: "Recibe la broma sin cerrarte — devuélvela con calma.",
    missionEn: "Take the tease without shutting down — give it back calmly.",
    line: "Tomarse una broma es la mitad de hacer una.",
    lineEn: "Taking a joke is half of making one.",
    prompts: [
      {
        id: "d282-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Marlana — don't run.",
        spanish: "Te estoy tomando el pelo, Marlana, no corras.",
        situationLabel: "Camila te devuelve la broma",
        why: "Using her name mid-tease keeps it warm — this is between friends, not a fight.",
        wordHints: [
          { en: "don't run", es: "no corras" },
        ],
      },
      {
        id: "d282-que-va",
        frameStem: "¡Qué va!",
        english: "No way! You're the strict teacher.",
        spanish: "¡Qué va! Tú eres la maestra estricta.",
        situationLabel: "Negando su etiqueta",
        why: "Turning her label back on her is the whole game — *¡qué va!* opens the door.",
        wordHints: [
          { en: "strict teacher", es: "la maestra estricta" },
        ],
      },
      {
        id: "d282-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate — practicing humor was your idea.",
        spanish: "No exageres, fue tu idea practicar humor.",
        situationLabel: "Ella dramatiza tu reacción",
        why: "*Fue tu idea* — it was your idea. A gentle reminder that she started this.",
        wordHints: [
          { en: "your idea", es: "tu idea" },
          { en: "practice humor", es: "practicar humor" },
        ],
      },
      {
        id: "d282-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the one who gets nervous over a joke.",
        spanish: "Mira quién habla, la que se pone nerviosa con una broma.",
        situationLabel: "Devolviéndole el espejo",
        why: "*La que se pone nerviosa* — the one who gets nervous. Spanish lets the adjective stand in for the whole person.",
        wordHints: [
          { en: "gets nervous", es: "se pone nerviosa" },
          { en: "a joke", es: "una broma" },
        ],
      },
      {
        id: "d282-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? Is that how you freeze when someone teases you back?",
        spanish: "¿En serio? ¿Así te quedas cuando te devuelven la broma?",
        situationLabel: "Sorprendida de tu reacción",
        why: "*Te devuelven la broma* — they give the joke back to you. The reciprocal form does the work.",
        wordHints: [
          { en: "they give back", es: "te devuelven" },
          { en: "the joke", es: "la broma" },
        ],
      },
    ],
  },
  {
    day: 283,
    themeEs: "En el colegio con Rocío",
    themeEn: "At school with Rocío",
    missionEs: "Prueba una broma ligera con una colega — mismo tono, otro público.",
    missionEn: "Try a light tease with a coworker — same tone, different audience.",
    line: "Entre colegas también hay espacio para una broma.",
    lineEn: "Between coworkers there's room for a joke too.",
    prompts: [
      {
        id: "d283-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Rocío — relax.",
        spanish: "Te estoy tomando el pelo, Rocío, tranquila.",
        situationLabel: "En la sala de maestras",
        why: "Adding her name and *tranquila* signals this isn't a formal complaint.",
        wordHints: [
          { en: "relax", es: "tranquila" },
        ],
      },
      {
        id: "d283-que-va",
        frameStem: "¡Qué va!",
        english: "No way! The principal didn't say that.",
        spanish: "¡Qué va! La directora no dijo eso.",
        situationLabel: "Negando el rumor",
        why: "*La directora no dijo eso* — flat denial of workplace gossip, no drama needed.",
        wordHints: [
          { en: "the principal", es: "la directora" },
          { en: "didn't say that", es: "no dijo eso" },
        ],
      },
      {
        id: "d283-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate, Rocío — it was just a comment between us.",
        spanish: "No exageres, Rocío, fue un comentario entre nosotras.",
        situationLabel: "Rocío lo infla",
        why: "*Entre nosotras* marks it as off-the-record — not for the whole staff room.",
        wordHints: [
          { en: "between us", es: "entre nosotras" },
          { en: "a comment", es: "un comentario" },
        ],
      },
      {
        id: "d283-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the one who brings three cups of coffee.",
        spanish: "Mira quién habla, la que trae tres tazas de café.",
        situationLabel: "Rocío se queja del lunes",
        why: "*La que trae* — the one who brings. Specific detail makes the tease land.",
        wordHints: [
          { en: "brings", es: "trae" },
          { en: "three cups", es: "tres tazas" },
          { en: "coffee", es: "café" },
        ],
      },
      {
        id: "d283-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? Did you take it the wrong way?",
        spanish: "¿En serio? ¿Te lo tomaste mal?",
        situationLabel: "Leyendo la reacción",
        why: "*¿Te lo tomaste mal?* — did you take it badly? The fastest way to check if you crossed a line.",
        wordHints: [
          { en: "take it badly", es: "tomarse mal" },
        ],
      },
    ],
  },
  {
    day: 284,
    themeEs: "El grupo de la familia",
    themeEn: "The family group chat",
    missionEs: "Lee el tono del grupo de WhatsApp — broma o drama.",
    missionEn: "Read the tone of the group chat — joke or drama.",
    line: "En familia, exagerar también es parte del chiste.",
    lineEn: "In a family, exaggerating is part of the joke too.",
    prompts: [
      {
        id: "d284-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Mom — don't cry.",
        spanish: "Te estoy tomando el pelo, mamá, no llores.",
        situationLabel: "En el grupo de WhatsApp",
        why: "*No llores* sounds dramatic on purpose — family humor often pushes one step further.",
        wordHints: [
          { en: "mom", es: "mamá" },
          { en: "don't cry", es: "no llores" },
        ],
      },
      {
        id: "d284-que-va",
        frameStem: "¡Qué va!",
        english: "No way! You're the one who burns the rice.",
        spanish: "¡Qué va! Tú eres el que quema el arroz.",
        situationLabel: "Kevin ataca tu cocina",
        why: "*El que quema el arroz* — turning Kevin's tease back with *mira quién habla* energy.",
        wordHints: [
          { en: "burns", es: "quema" },
          { en: "the rice", es: "el arroz" },
        ],
      },
      {
        id: "d284-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate, Kevin — it's not a competition.",
        spanish: "No exageres, Kevin, no es competencia.",
        situationLabel: "Kevin infla la historia",
        why: "*No es competencia* shuts down the escalation without leaving the chat.",
        wordHints: [
          { en: "it's not a competition", es: "no es competencia" },
        ],
      },
      {
        id: "d284-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the one who never replies.",
        spanish: "Mira quién habla, el que no contesta nunca.",
        situationLabel: "Kevin critica tu respuesta tardía",
        why: "*El que no contesta nunca* — the pot calling the kettle black in one phrase.",
        wordHints: [
          { en: "never replies", es: "no contesta nunca" },
        ],
      },
      {
        id: "d284-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? Did Kevin get mad about that?",
        spanish: "¿En serio? ¿Kevin se enojó por eso?",
        situationLabel: "Le cuentas a Camila el drama",
        why: "Reading family chat tone from a distance — sometimes *¿en serio?* is all you need.",
        wordHints: [
          { en: "got mad", es: "se enojó" },
          { en: "about that", es: "por eso" },
        ],
      },
    ],
  },
  {
    day: 285,
    themeEs: "La broma que sale sola",
    themeEn: "The joke that came out on its own",
    missionEs: "Nota cuando la broma sale sin planearla.",
    missionEn: "Notice when the joke comes out without planning it.",
    line: "Lo natural también se puede practicar.",
    lineEn: "Naturalness can be practiced too.",
    prompts: [
      {
        id: "d285-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — see? I didn't plan anything.",
        spanish: "Te estoy tomando el pelo, ¿viste? No planifiqué nada.",
        situationLabel: "La broma que salió sola",
        why: "*¿Viste?* — see? — marks the moment you notice it worked without a script.",
        wordHints: [
          { en: "see", es: "¿viste?" },
          { en: "i didn't plan", es: "no planifiqué" },
        ],
      },
      {
        id: "d285-que-va",
        frameStem: "¡Qué va!",
        english: "No way! I wasn't nervous this time.",
        spanish: "¡Qué va! No estaba nerviosa esta vez.",
        situationLabel: "Camila dice que lo notó",
        why: "*Esta vez* — this time. The contrast with every earlier attempt is the whole point.",
        wordHints: [
          { en: "this time", es: "esta vez" },
          { en: "nervous", es: "nerviosa" },
        ],
      },
      {
        id: "d285-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate — it was just one sentence.",
        spanish: "No exageres, fue una frase nada más.",
        situationLabel: "Camila lo celebra de más",
        why: "*Nada más* at the end downplays it — you don't need a perfect joke, just one line.",
        wordHints: [
          { en: "just one sentence", es: "una frase nada más" },
        ],
      },
      {
        id: "d285-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the one who said she couldn't joke.",
        spanish: "Mira quién habla, la que decía que no podía bromear.",
        situationLabel: "Camila recuerda enero",
        why: "*La que decía* — the one who used to say. Past habit held up against today.",
        wordHints: [
          { en: "used to say", es: "decía" },
          { en: "couldn't joke", es: "no podía bromear" },
        ],
      },
      {
        id: "d285-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? It came out on its own?",
        spanish: "¿En serio? ¿Salió solo?",
        situationLabel: "Todavía no lo crees",
        why: "*¿Salió solo?* — did it come out by itself? The title of the week's story in four words.",
        wordHints: [
          { en: "came out on its own", es: "salió solo" },
        ],
      },
    ],
  },
  {
    day: 286,
    themeEs: "Cuando no cae",
    themeEn: "When it doesn't land",
    missionEs: "Si el chiste no cae, nómbralo y sigue.",
    missionEn: "If the joke doesn't land, name it and move on.",
    line: "Un silencio incómodo no es el final de la conversación.",
    lineEn: "An awkward silence isn't the end of the conversation.",
    prompts: [
      {
        id: "d286-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you… well, maybe not.",
        spanish: "Te estoy tomando el pelo… bueno, tal vez no.",
        situationLabel: "Retirándote a mitad de broma",
        why: "*Bueno, tal vez no* is a clean exit when you feel the joke isn't landing.",
        wordHints: [
          { en: "well", es: "bueno" },
          { en: "maybe not", es: "tal vez no" },
        ],
      },
      {
        id: "d286-que-va",
        frameStem: "¡Qué va!",
        english: "No way! I didn't get mad — I just went blank.",
        spanish: "¡Qué va! No me enojé, me quedé en blanco.",
        situationLabel: "Camila pensó que te ofendiste",
        why: "*Me quedé en blanco* — I went blank. Honest and specific beats pretending it was fine.",
        wordHints: [
          { en: "i didn't get mad", es: "no me enojé" },
          { en: "went blank", es: "me quedé en blanco" },
        ],
      },
      {
        id: "d286-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate — there was just an awkward silence.",
        spanish: "No exageres, solo hubo silencio incómodo.",
        situationLabel: "Camila dramatiza el momento",
        why: "Naming *silencio incómodo* honestly is often enough to break it.",
        wordHints: [
          { en: "awkward silence", es: "silencio incómodo" },
        ],
      },
      {
        id: "d286-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the one who taught me to laugh at my mistakes.",
        spanish: "Mira quién habla, la que me enseñó a reírme de mis errores.",
        situationLabel: "Devolviéndole la lección",
        why: "Turning her own teaching back with warmth — not accusation.",
        wordHints: [
          { en: "taught me", es: "me enseñó" },
          { en: "laugh at my mistakes", es: "reírme de mis errores" },
        ],
      },
      {
        id: "d286-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? Is that how you fix it — by saying the truth?",
        spanish: "¿En serio? ¿Así se arregla, diciendo la verdad?",
        situationLabel: "La lección del día",
        why: "When humor fails, honesty is the recovery move — and it works in Spanish too.",
        wordHints: [
          { en: "saying the truth", es: "diciendo la verdad" },
          { en: "fix it", es: "se arregla" },
        ],
      },
    ],
  },
  {
    day: 287,
    themeEs: "Repaso: Humor ligero",
    themeEn: "Review: Light humor",
    missionEs: "Cinco frases para bromear y recibir la broma sin perder el hilo.",
    missionEn: "Five phrases for teasing and taking a joke without losing the thread.",
    line: "Dar y recibir la broma es conversación también.",
    lineEn: "Giving and taking a joke is conversation too.",
    prompts: [
      {
        id: "d287-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — saying it doesn't scare me anymore.",
        spanish: "Te estoy tomando el pelo, ya no me da miedo decirlo.",
        situationLabel: "El repaso de la semana",
        why: "*Ya no me da miedo* — it doesn't scare me anymore. The week's real win in one phrase.",
        wordHints: [
          { en: "doesn't scare me", es: "no me da miedo" },
          { en: "anymore", es: "ya no" },
        ],
      },
      {
        id: "d287-que-va",
        frameStem: "¡Qué va!",
        english: "No way! I'm not the same person as January.",
        spanish: "¡Qué va! No soy la misma de enero.",
        situationLabel: "Dos semanas de primavera",
        why: "*No soy la misma de enero* — tying the week's humor to the year's growth.",
        wordHints: [
          { en: "not the same", es: "no soy la misma" },
          { en: "january", es: "enero" },
        ],
      },
      {
        id: "d287-no-exageres",
        frameStem: "No exageres",
        english: "Don't exaggerate — I only learned five new phrases.",
        spanish: "No exageres, solo aprendí cinco frases nuevas.",
        situationLabel: "Camila celebra de más",
        why: "Downplaying the win while still claiming it — very on-brand for Marlana.",
        wordHints: [
          { en: "i only learned", es: "solo aprendí" },
          { en: "five phrases", es: "cinco frases" },
        ],
      },
      {
        id: "d287-mira-quien-habla",
        frameStem: "Mira quién habla",
        english: "Look who's talking — the one who couldn't take a joke.",
        spanish: "Mira quién habla, la que no podía tomarse una broma.",
        situationLabel: "El contraste con enero",
        why: "*Tomarse una broma* — to take a joke. The reciprocal you couldn't do at the start of the week.",
        wordHints: [
          { en: "take a joke", es: "tomarse una broma" },
        ],
      },
      {
        id: "d287-en-serio",
        frameStem: "¿En serio?",
        english: "Seriously? Two weeks of spring already?",
        spanish: "¿En serio? ¿Ya llevo dos semanas de primavera?",
        situationLabel: "Mirando atrás",
        why: "*¿Ya llevo…?* — am I already up to…? Surprise at your own progress.",
        wordHints: [
          { en: "already", es: "ya" },
          { en: "two weeks of spring", es: "dos semanas de primavera" },
        ],
      },
    ],
  },
];
