import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 7 — "La misma frase, dos formas" (days 316–322).
 * Parent conference week: Marlana speaks usted with families all day, then
 * retells the same conversations in tú with Camila — the year's third
 * intentional usted week.
 */
export const priWeek7ReadingDays: ReadingDay[] = [
  {
    day: 316,
    themeEs: "Ensayando con Rocío",
    storyTitle: "La misma frase, dos formas",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "ensayar", en: "to rehearse", example: "Rocío me hace ensayar en usted." },
      { es: "la conferencia de padres", en: "the parent conference", example: "Mañana empiezan las conferencias de padres." },
      { es: "de usted", en: "on formal terms (usted)", example: "Con las mamás hablo de usted." },
      { es: "el registro", en: "register (formal/informal)", example: "Cambiar de registro no es cambiar de idioma." },
      { es: "¿tendría?", en: "would you have? (usted conditional)", example: "Disculpe, ¿tendría un momento?" },
    ],
    dialogue: {
      title: "Mañana hablas con mamás",
      situation: "Rocío cierra la puerta del salón después de clase",
      lines: [
        { speaker: "B", es: "Mañana conferencias. ¿Ya ensayaste en usted?", en: "Tomorrow, conferences. Have you rehearsed in usted yet?" },
        { speaker: "A", es: "Un poco. Pero suena a disfraz.", en: "A little. But it sounds like a costume." },
        { speaker: "B", es: "Por eso ensayamos. Repite: Disculpe, ¿tendría un momento antes de que empiece la fila?", en: "That's why we rehearse. Repeat: Excuse me, would you have a moment before the line starts?" },
        { speaker: "A", es: "Disculpe, ¿tendría un momento antes de que empiece la fila.", en: "Excuse me, would you have a moment before the line starts." },
        { speaker: "B", es: "Bien. Ahora: Le quería comentar que… — siempre *le*, no *te*, con una mamá.", en: "Good. Now: I wanted to tell you that… — always *le*, not *te*, with a mother." },
        { speaker: "A", es: "Le quería comentar que su hijo participa más. ¿Me permite explicarle? Muchas gracias por su tiempo.", en: "I wanted to tell you that her son participates more. May I explain to you? Thank you so much for your time." },
        { speaker: "B", es: "¿Ves? *Te* con Camila. *Le* con la señora López. Mismo mensaje.", en: "See? *Te* with Camila. *Le* with Mrs. López. Same message." },
        { speaker: "A", es: "Con permiso… ¿tendría un momento? — eso abre. Oye, perdona — eso es contigo.", en: "Excuse me… would you have a moment? — that opens. Hey, sorry — that's with you." },
        { speaker: "B", es: "Exacto. La misma frase, dos formas. Mañana usas la de usted. El jueves me cuentas en tú.", en: "Exactly. The same phrase, two forms. Tomorrow you use the usted one. Thursday you tell me in tú." },
      ],
    },
  },
  {
    day: 317,
    themeEs: "La primera madre",
    storyTitle: "La misma frase, dos formas",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "sentarse", en: "to sit down", example: "La mesa está por aquí, siéntese." },
      { es: "en voz alta", en: "aloud", example: "Mateo lee en voz alta sin miedo." },
      { es: "la carpeta", en: "the folder", example: "Busco la carpeta de Mateo." },
      { es: "el apellido", en: "the last name", example: "¿Cómo se pronuncia su apellido?" },
      { es: "tercero", en: "third grade", example: "Tiene otro hijo en tercero." },
    ],
    dialogue: {
      title: "La señora López se sienta",
      situation: "Primera conferencia del día; Marlana no cambia al inglés",
      lines: [
        { speaker: "A", es: "Disculpe, ¿tendría un momento? La mesa está por aquí.", en: "Excuse me, would you have a moment? The table is over here." },
        { speaker: "B", es: "Sí, claro. Perdón por llegar tarde.", en: "Yes, of course. Sorry for arriving late." },
        { speaker: "A", es: "No se preocupe. Le quería comentar que Mateo lee en voz alta sin miedo ahora.", en: "Don't worry. I wanted to tell you that Mateo reads aloud without fear now." },
        { speaker: "B", es: "¿De verdad? En casa no quiere leer.", en: "Really? At home he doesn't want to read." },
        { speaker: "A", es: "¿Me permite explicarle cómo leemos aquí? No es como en su país.", en: "May I explain to you how we read here? It's not like in your country." },
        { speaker: "B", es: "Por favor. A veces no entiendo la tarea.", en: "Please. Sometimes I don't understand the homework." },
        { speaker: "A", es: "Le explico. Y si quiere, le mando un resumen por correo.", en: "I'll explain. And if you'd like, I'll send you a summary by email." },
        { speaker: "B", es: "Muchas gracias. Usted habla despacio y eso ayuda.", en: "Thank you very much. You speak slowly and that helps." },
        { speaker: "A", es: "Muchas gracias por su tiempo — sé que tiene otro hijo en tercero. Disculpe, ¿cómo se pronuncia su apellido? Quiero escribirlo bien.", en: "Thank you so much for your time — I know you have another child in third grade. Excuse me, how do you pronounce your last name? I want to write it correctly." },
      ],
    },
  },
  {
    day: 318,
    themeEs: "Un momento difícil",
    storyTitle: "La misma frase, dos formas",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "reprueba", en: "failing (a class)", example: "Pregunta por qué su hijo reprueba." },
      { es: "vago", en: "lazy", example: "Su hijo no es vago — le cuesta leer." },
      { es: "le cuesta", en: "it's hard for him/her", example: "Le cuesta la lectura en inglés." },
      { es: "calcular la nota", en: "to calculate the grade", example: "¿Me permite explicarle cómo calculamos la nota?" },
      { es: "de otra forma", en: "another way", example: "Disculpe, déjeme decirlo de otra forma." },
    ],
    dialogue: {
      title: "¿Por qué reprueba?",
      situation: "Tercera conferencia; la mamá de Daniela llega con una carpeta de papeles",
      lines: [
        { speaker: "B", es: "Disculpe — ¿por qué mi hija reprueba? Ella estudia todas las noches.", en: "Excuse me — why is my daughter failing? She studies every night." },
        { speaker: "A", es: "Disculpe, ¿tendría un momento más? Preferiría que nos sentáramos.", en: "Excuse me, would you have a moment more? I'd prefer we sit down." },
        { speaker: "A", es: "Le quería comentar que su hija no es vaga — le cuesta la lectura en inglés.", en: "I wanted to tell you that your daughter isn't lazy — English reading is hard for her." },
        { speaker: "B", es: "Entonces ¿por qué la nota es tan baja?", en: "Then why is the grade so low?" },
        { speaker: "A", es: "¿Me permite explicarle cómo calculamos la nota? No es que no quiera aprender.", en: "May I explain to you how we calculate the grade? It's not that she doesn't want to learn." },
        { speaker: "B", es: "Sí. Por favor.", en: "Yes. Please." },
        { speaker: "A", es: "Disculpe, déjeme decirlo de otra forma. Ella entiende cuando le leo en voz alta. Sola, se traba.", en: "Excuse me, let me say it another way. She understands when I read aloud to her. Alone, she gets stuck." },
        { speaker: "B", es: "Nadie me había explicado eso.", en: "Nobody had explained that to me." },
        { speaker: "A", es: "Muchas gracias por su tiempo — entiendo que esto no es fácil. La llamo la semana que viene.", en: "Thank you so much for your time — I understand this isn't easy. I'll call you next week." },
      ],
    },
  },
  {
    day: 319,
    themeEs: "La misma frase, en tú",
    storyTitle: "La misma frase, dos formas",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "desahogarse", en: "to vent, to unburden oneself", example: "Necesitaba desahogarme contigo." },
      { es: "contigo", en: "with you (informal)", example: "Contigo digo *te quería comentar*." },
      { es: "el mesero", en: "the waiter", example: "Casi le digo *con permiso* al mesero." },
      { es: "de verdad", en: "really, truly", example: "¿En serio casi lloraste?" },
      { es: "media hora", en: "half an hour", example: "Me escuchaste media hora." },
    ],
    dialogue: {
      title: "Oye, ¿tienes un momento?",
      situation: "Jueves en el café; Marlana acaba de terminar el segundo día de conferencias",
      lines: [
        { speaker: "A", es: "Oye, ¿tienes un momento? Necesito contarte la conferencia.", en: "Hey, do you have a moment? I need to tell you about the conference." },
        { speaker: "B", es: "Siempre. ¿Qué pasó?", en: "Always. What happened?" },
        { speaker: "A", es: "Te quería comentar que casi lloro con la tercera madre. Con ella dije *le quería comentar* — contigo digo *te quería comentar*.", en: "I wanted to tell you that I almost cried with the third mother. With her I said *le quería comentar* — with you I say *te quería comentar*." },
        { speaker: "B", es: "¿Y funcionó el usted?", en: "And did the usted work?" },
        { speaker: "A", es: "¿Me dejas explicarte lo que le dije sobre las notas? Con la mamá: *¿me permite explicarle?* Contigo: *¿me dejas explicarte?*", en: "Can I explain to you what I told her about the grades? With the mother: *may I explain to you?* With you: *can I explain to you?*" },
        { speaker: "B", es: "Misma frase. Dos formas.", en: "Same phrase. Two forms." },
        { speaker: "A", es: "Exacto. A las mamás: *muchas gracias por su tiempo.* A ti: *por tu tiempo.*", en: "Exactly. To the mothers: *thank you so much for your time.* To you: *for your time.*" },
        { speaker: "B", es: "Muchas gracias por tu tiempo — me escuchaste media hora.", en: "Thank you so much for your time — you listened for half an hour." },
        { speaker: "A", es: "Oye, perdona — casi le digo *con permiso* al mesero. Llevo usted en la cabeza.", en: "Hey, sorry — I almost said *excuse me* to the waiter. I've got usted stuck in my head." },
      ],
    },
  },
  {
    day: 320,
    themeEs: "Cambiando en seco",
    storyTitle: "La misma frase, dos formas",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "hablarle de usted a alguien", en: "to address someone formally", example: "Le hablé de usted a la mamá." },
      { es: "una difícil", en: "a rough one (noun dropped)", example: "Acabo de salir de una difícil." },
      { es: "de lo que", en: "than (comparing with a clause)", example: "Suena peor de lo que fue." },
      { es: "tener puesta", en: "to have on (like a coat)", example: "Todavía tengo la voz de la conferencia puesta." },
      { es: "allá adentro", en: "in there", example: "Te lo digo distinto que allá adentro." },
    ],
    dialogue: {
      title: "Treinta segundos de diferencia",
      situation: "Sale la mamá de Mateo, entra Camila, mismo pasillo",
      lines: [
        { speaker: "A", es: "Muchas gracias por su tiempo, señora. Que llegue bien.", en: "Thank you very much for your time, ma'am. Get home safe." },
        { speaker: "B", es: "¿Esa era la última?", en: "Was that the last one?" },
        { speaker: "A", es: "Oye, ¿tienes un momento? Acabo de salir de una difícil.", en: "Hey, do you have a minute? I just came out of a rough one." },
        { speaker: "B", es: "Se te nota en la cara.", en: "It shows on your face." },
        { speaker: "A", es: "Te quería comentar que le hablé de usted a una mamá y casi te lo hago a ti.", en: "I wanted to tell you that I called a mother \"usted\" and then almost did it to you." },
        { speaker: "B", es: "Ja. ¿Y qué pasó adentro?", en: "Ha. And what happened in there?" },
        { speaker: "A", es: "¿Me dejas explicarte? Porque suena peor de lo que fue.", en: "Can I explain? Because it sounds worse than it was." },
        { speaker: "B", es: "Te dejo. Pero siéntate primero.", en: "Go ahead. But sit down first." },
        { speaker: "A", es: "Muchas gracias por tu tiempo, y te lo digo distinto que allá adentro.", en: "Thank you so much for your time — and I mean it differently than I did in there." },
        { speaker: "B", es: "Ya sé. Se oye distinto en tú.", en: "I know. It sounds different in tú." },
        { speaker: "A", es: "Oye, perdona, todavía tengo la voz de la conferencia puesta.", en: "Hey, sorry — I still have the conference voice on." },
      ],
    },
  },
  {
    day: 321,
    themeEs: "La conferencia entera",
    storyTitle: "La misma frase, dos formas",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "llevar de pie", en: "to have been on your feet", example: "Llevo de pie desde la una." },
      { es: "ni una vez", en: "not once", example: "Hoy no me cambié al inglés ni una vez." },
      { es: "hacer una pregunta", en: "to ask a question", example: "Me hizo la misma pregunta tres veces." },
      { es: "la carpeta equivocada", en: "the wrong folder", example: "Agarré la carpeta equivocada." },
      { es: "como si nada", en: "as if it were nothing", example: "Seguí como si nada." },
    ],
    dialogue: {
      title: "Las cuatro de la tarde",
      situation: "Camila llega al colegio con café al final de la conferencia",
      lines: [
        { speaker: "B", es: "Te traje café. ¿Cuántas van?", en: "I brought you coffee. How many so far?" },
        { speaker: "A", es: "Oye, ¿tienes un momento? Llevo de pie desde la una.", en: "Hey, do you have a minute? I've been on my feet since one." },
        { speaker: "B", es: "Siéntate. Cuéntame.", en: "Sit down. Tell me." },
        { speaker: "A", es: "Te quería comentar que hoy no me cambié al inglés ni una vez.", en: "I wanted to tell you that today I didn't switch to English once." },
        { speaker: "B", es: "¿Once familias enteras en español?", en: "Eleven whole families in Spanish?" },
        { speaker: "A", es: "Once. ¿Me dejas explicarte? El último papá me hizo la misma pregunta tres veces.", en: "Eleven. Can I explain? The last father asked me the same question three times." },
        { speaker: "B", es: "¿Y tú qué hiciste?", en: "And what did you do?" },
        { speaker: "A", es: "Se la contesté distinto las tres. Y a la tercera entendió.", en: "I answered it differently all three times. And on the third he got it." },
        { speaker: "B", es: "Eso no se aprende en un libro.", en: "You don't learn that in a book." },
        { speaker: "A", es: "Oye, perdona, agarré la carpeta equivocada y seguí como si nada.", en: "Hey, sorry — I grabbed the wrong folder and just kept going." },
        { speaker: "A", es: "Muchas gracias por tu tiempo, Camila. Me ayudaste a ensayar.", en: "Thank you so much for your time, Camila. You helped me rehearse." },
      ],
    },
  },
  {
    day: 322,
    themeEs: "Repaso: Cambiar de registro",
    isRecap: true,
    vocab: [
      { es: "la receta", en: "the prescription", example: "Es por una receta de la semana pasada." },
      { es: "la dosis", en: "the dose", example: "El doctor cambió la dosis." },
      { es: "la etiqueta", en: "the label", example: "No está en la etiqueta." },
      { es: "ahorrarle un viaje a alguien", en: "to save someone a trip", example: "Me ahorró un viaje." },
      { es: "el mostrador", en: "the counter", example: "Estaba sola en el mostrador." },
    ],
    dialogue: {
      title: "En la farmacia",
      situation: "Sábado — Camila la acompañó y espera dos pasos atrás",
      lines: [
        { speaker: "A", es: "Disculpe, ¿tendría un momento? Es por una receta de la semana pasada.", en: "Excuse me, would you have a moment? It's about a prescription from last week." },
        { speaker: "B", es: "Dígame. ¿Nombre?", en: "Go ahead. Name?" },
        { speaker: "A", es: "Le quería comentar que el doctor cambió la dosis y no está en la etiqueta.", en: "I wanted to mention that the doctor changed the dose and it isn't on the label." },
        { speaker: "B", es: "Aquí me sale la dosis vieja. Tendría que llamar a la clínica.", en: "The old dose is what I have here. I'd have to call the clinic." },
        { speaker: "A", es: "¿Me permite explicarle? Tengo el mensaje de la clínica en el teléfono.", en: "May I explain? I have the message from the clinic on my phone." },
        { speaker: "B", es: "Ah, perfecto. Con eso lo cambio ahora mismo. Deme cinco minutos.", en: "Ah, perfect. With that I can change it right now. Give me five minutes." },
        { speaker: "A", es: "Muchas gracias por su tiempo, me ahorró un viaje.", en: "Thank you very much for your time — you saved me a trip." },
        { speaker: "B", es: "Para eso estamos.", en: "That's what we're here for." },
        { speaker: "A", es: "Oye, perdona, te tuve veinte minutos esperando por una caja de pastillas.", en: "Hey, sorry — I kept you waiting twenty minutes for a box of pills." },
        { speaker: "B", es: "Yo estaba mirando los champús. No te preocupes.", en: "I was looking at the shampoos. Don't worry about it." },
        { speaker: "A", es: "Usted allá, tú acá, y las dos en el mismo cuarto.", en: "Usted over there, tú over here, and both in the same room." },
      ],
    },
  },
];
