import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 5 — "El celular en clase" (days 302–308).
 * Marlana and Camila disagree warmly about phones in adult ESOL class;
 * Rocío weighs in from elementary school. Five debate stems across the week.
 */
export const priWeek5ReadingDays: ReadingDay[] = [
  {
    day: 302,
    themeEs: "El tema sale solo",
    storyTitle: "El celular en clase",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "flojera", en: "laziness, not bothering", example: "No fue por flojera — era la guardería." },
      { es: "la guardería", en: "daycare", example: "Mis estudiantes tienen hijos en guardería." },
      { es: "el scroll", en: "scrolling (social media)", example: "El problema es el scroll y no el aparato." },
      { es: "prohibir", en: "to ban, to prohibit", example: "¿No crees que prohibirlo todo suena a prepa?" },
      { es: "el traductor", en: "the translator (app)", example: "Un celular puede ser diccionario y traductor." },
    ],
    dialogue: {
      title: "Sonó en plena lección",
      situation: "Jueves en el café — Marlana cuenta lo que pasó en ESOL anoche",
      lines: [
        { speaker: "A", es: "Camila, no te vas a creer: ayer sonó un celular en plena lección y casi perdemos veinte minutos hablando de eso.", en: "Camila, you won't believe it: yesterday a phone rang right in the middle of the lesson and we almost spent twenty minutes talking about it." },
        { speaker: "B", es: "¿Y tú qué hiciste?", en: "And what did you do?" },
        { speaker: "A", es: "Entiendo tu punto, pero no fue por flojera — era la guardería. La mamá de Rosa necesitaba confirmar quién recogía al niño.", en: "I get your point, but it wasn't laziness — it was daycare. Rosa's mom needed to confirm who was picking up the kid." },
        { speaker: "B", es: "Yo lo veo distinto: si suena en clase, distrae a todos.", en: "I see it differently: if it rings in class, it distracts everyone." },
        { speaker: "A", es: "¿No crees que prohibirlo todo suena a prepa? Mis estudiantes son adultos.", en: "Don't you think banning everything sounds like high school? My students are adults." },
        { speaker: "B", es: "Puede ser, pero ayer vi pantallas cuando creías que escuchaban.", en: "Maybe, but yesterday I saw screens when you thought they were listening." },
        { speaker: "A", es: "No estoy segura de que quitar el celular mejore el aprendizaje. Yo lo veo distinto: a veces es herramienta.", en: "I'm not sure taking away the phone improves learning. I see it differently: sometimes it's a tool." },
        { speaker: "B", es: "Bueno. Esto no se acaba en un café. Sigue mañana.", en: "Okay. This doesn't end at a café. Continue tomorrow." },
      ],
    },
  },
  {
    day: 303,
    themeEs: "Los adultos tienen vidas",
    storyTitle: "El celular en clase",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el turno de noche", en: "the night shift", example: "Algunos trabajan de noche y esperan un mensaje." },
      { es: "la tranquilidad", en: "peace of mind, calm", example: "Quitarles el celular les quita tranquilidad." },
      { es: "confiar en", en: "to trust", example: "Si confías en ellos, te respetan más." },
      { es: "traducir", en: "to translate", example: "La mayoría lo usa para traducir." },
      { es: "regla rígida", en: "strict rule", example: "No estoy segura de que una regla rígida funcione." },
    ],
    dialogue: {
      title: "No son adolescentes",
      situation: "Marlana defiende a su grupo de ESOL nocturno",
      lines: [
        { speaker: "A", es: "Entiendo tu punto, pero mis estudiantes tienen hijos en guardería. Algunos trabajan de noche y esperan un mensaje del hospital o de la jefa.", en: "I get your point, but my students have kids in daycare. Some work night shifts and wait for a message from the hospital or their boss." },
        { speaker: "B", es: "¿Y en clase?", en: "And in class?" },
        { speaker: "A", es: "Yo lo veo distinto: si confías en ellos, te respetan más. Esto es ESOL para adultos, no silencio forzado.", en: "I see it differently: if you trust them, they respect you more. This is ESOL for adults, not forced silence." },
        { speaker: "B", es: "¿No crees que tú también mirarías el teléfono si tu hijo está enfermo?", en: "Don't you think you'd look at your phone too if your kid were sick?" },
        { speaker: "A", es: "Claro que sí. Por eso no quiero quitarles el celular — les quita tranquilidad.", en: "Of course I would. That's why I don't want to take their phones away — it takes away their peace of mind." },
        { speaker: "B", es: "Puede ser, pero la mayoría no está mirando la guardería — está en TikTok.", en: "Maybe, but most aren't checking daycare — they're on TikTok." },
        { speaker: "A", es: "Puede ser, pero la mayoría lo usa para traducir, no para TikTok. Ayer Carlos me mostró una foto de su nieto y seguimos con la lección.", en: "Maybe, but most use it to translate, not for TikTok. Yesterday Carlos showed me a photo of his grandson and we kept going with the lesson." },
        { speaker: "B", es: "No estoy segura de que una regla rígida los haga más presentes. Pero tampoco estoy segura de que el scroll sea raro.", en: "I'm not sure a strict rule makes them more present. But I'm also not sure scrolling is rare." },
      ],
    },
  },
  {
    day: 304,
    themeEs: "En clase es en clase",
    storyTitle: "El celular en clase",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la distracción", en: "distraction", example: "En el hospital un segundo de distracción importa." },
      { es: "boca arriba", en: "face up (screen visible)", example: "Si lo dejan en la mesa boca arriba, la tentación gana." },
      { es: "la tentación", en: "temptation", example: "Un límite claro les da permiso de soltar el teléfono." },
      { es: "el ambiente", en: "the atmosphere, the vibe", example: "No es desconfianza, es crear un ambiente." },
      { es: "pair work", en: "pair work, partner activity", example: "Vi pantallas durante el pair work." },
    ],
    dialogue: {
      title: "Camila no cede",
      situation: "Camila trae su experiencia del hospital al debate",
      lines: [
        { speaker: "B", es: "Entiendo tu punto, pero en el hospital un segundo de distracción importa. Si miran la pantalla, no te escuchan.", en: "I get your point, but at the hospital a second of distraction matters. If they're looking at the screen, they're not listening to you." },
        { speaker: "A", es: "Yo lo veo distinto — la clase es el único espacio donde practican sin interrupciones.", en: "I see it differently — class is the only space where they practice without interruptions." },
        { speaker: "B", es: "Yo lo veo distinto: un límite claro les da permiso de soltar el teléfono. No es castigo, es ambiente.", en: "I see it differently: a clear limit gives them permission to put the phone down. It's not punishment, it's atmosphere." },
        { speaker: "A", es: "¿No crees que castigar a un adulto lo hace dejar de venir?", en: "Don't you think punishing an adult makes them stop coming?" },
        { speaker: "B", es: "¿No crees que si lo dejan en la mesa boca arriba, la tentación gana? ¿No crees que \"solo un segundo\" se convierte en cinco minutos?", en: "Don't you think if they leave it face-up on the table, temptation wins? Don't you think \"just a second\" turns into five minutes?" },
        { speaker: "A", es: "Puede ser…", en: "Maybe…" },
        { speaker: "B", es: "Puede ser, pero vi a tres personas mirando pantallas ayer en tu salón. Durante el pair work.", en: "Maybe, but I saw three people looking at screens yesterday in your classroom. During pair work." },
        { speaker: "A", es: "No estoy segura de que \"confiar\" signifique no poner reglas. Tú tienes razón en una parte.", en: "I'm not sure \"trusting\" means not having any rules. You're right about one part." },
      ],
    },
  },
  {
    day: 305,
    themeEs: "Rocío opina",
    storyTitle: "El celular en clase",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la cesta", en: "the basket", example: "En su escuela hay una cesta en la puerta." },
      { es: "hace falta", en: "it's necessary, you need to", example: "No hace falta quitar el celular, hace falta acordar cuándo." },
      { es: "boca abajo", en: "face down", example: "¿No crees que boca abajo en la mesa es más razonable?" },
      { es: "el acuerdo", en: "the agreement", example: "Sin acuerdo cada quien hace lo que quiere." },
      { es: "aplicar", en: "to apply, to be relevant", example: "Rocío mandó un audio — no todo aplica." },
    ],
    dialogue: {
      title: "El audio de Rocío",
      situation: "Rocío manda un audio desde la sala de maestros; Marlana lo resume en el café",
      lines: [
        { speaker: "A", es: "Rocío mandó un audio de veinte minutos sobre celulares. En su escuela hay una cesta en la puerta.", en: "Rocío sent a twenty-minute voice note about phones. At her school there's a basket by the door." },
        { speaker: "B", es: "¿Y tú qué piensas?", en: "And what do you think?" },
        { speaker: "A", es: "Entiendo tu punto, pero Rocío trabaja con niños, yo con adultos. Una cesta suena duro para un curso nocturno.", en: "I get your point, but Rocío works with kids, I work with adults. A basket sounds harsh for a night class." },
        { speaker: "B", es: "Yo lo veo distinto: no hace falta quitar el celular, hace falta acordar cuándo.", en: "I see it differently: we don't need to take the phone away, we need to agree when." },
        { speaker: "A", es: "¡Exacto! ¿No crees que lo de \"boca abajo en la mesa\" es más razonable que la cesta?", en: "Exactly! Don't you think \"face down on the table\" is more reasonable than the basket?" },
        { speaker: "B", es: "Puede ser, pero Rocío también dijo que el problema es el scroll, no el aparato. Eso sí me convence.", en: "Maybe, but Rocío also said the problem is scrolling, not the device. That I buy." },
        { speaker: "A", es: "Puede ser, pero en su salón hay veinte niños; en el mío hay ocho adultos que vienen del trabajo.", en: "Maybe, but she has twenty kids in her room; I have eight adults coming from work." },
        { speaker: "B", es: "No estoy segura de que la cesta funcione aquí. Pero estoy segura de que necesitamos un acuerdo explícito.", en: "I'm not sure the basket works here. But I'm sure we need an explicit agreement." },
      ],
    },
  },
  {
    day: 306,
    themeEs: "Un punto medio",
    storyTitle: "El celular en clase",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "silenciado", en: "silenced, on silent", example: "Silenciado y boca abajo me parece justo." },
      { es: "la excepción", en: "the exception", example: "Quiero una excepción para traductor y diccionario." },
      { es: "el descanso", en: "the break", example: "Boca abajo hasta el descanso." },
      { es: "imponer", en: "to impose", example: "La regla la escribimos con ellos, no se la imponemos." },
      { es: "tropiezo", en: "stumble, misstep", example: "No estoy segura de que funcione sin tropiezos." },
    ],
    dialogue: {
      title: "Tres cosas claras",
      situation: "Marlana y Camila redactan el acuerdo antes del martes",
      lines: [
        { speaker: "A", es: "Entiendo tu punto, pero \"silenciado y boca abajo\" me parece justo. ¿Te late?", en: "I get your point, but \"silenced and face down\" seems fair to me. Does that work for you?" },
        { speaker: "B", es: "Me late. ¿Y las emergencias?", en: "Works for me. And emergencies?" },
        { speaker: "A", es: "Yo lo veo distinto: no es prohibir, es acordar tres cosas claras. Silenciado, boca abajo, y si hay emergencia, levantas la mano primero.", en: "I see it differently: we're not banning, we're agreeing on three clear things. Silenced, face down, and if there's an emergency, you raise your hand first." },
        { speaker: "B", es: "¿No crees que \"boca abajo hasta el descanso\" es fácil de recordar?", en: "Don't you think \"face down until break\" is easy to remember?" },
        { speaker: "A", es: "Sí. Y lo explicamos en español y en inglés mañana.", en: "Yes. And we explain it in Spanish and English tomorrow." },
        { speaker: "B", es: "Puede ser, pero Instagram en clase sigue fuera.", en: "Maybe, but Instagram in class is still off the table." },
        { speaker: "A", es: "Puede ser, pero quiero una excepción explícita para traductor y diccionario. Eso no negocio.", en: "Maybe, but I want an explicit exception for translator and dictionary. I won't negotiate that." },
        { speaker: "B", es: "Trato hecho. No estoy segura de que funcione la primera semana sin tropiezos — pero lo probamos.", en: "Deal. I'm not sure it'll work the first week without stumbles — but we'll try it." },
      ],
    },
  },
  {
    day: 307,
    themeEs: "Lo probamos en clase",
    storyTitle: "El celular en clase",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "claridad", en: "clarity", example: "No era confianza vs reglas, era claridad." },
      { es: "debrief", en: "debrief (discussion after)", example: "Marlana hace debrief con Camila por audio." },
      { es: "dramas", en: "drama, fuss", example: "La clase entera lo aceptó sin dramas." },
      { es: "a medias", en: "halfway, partially", example: "Capaz las dos teníamos razón a medias." },
      { es: "discutir", en: "to argue, to debate", example: "Discutir así contigo me ayudó más que cualquier manual." },
    ],
    dialogue: {
      title: "El martes en la noche",
      situation: "Audio de Marlana para Camila después de la primera clase con el acuerdo nuevo",
      lines: [
        { speaker: "A", es: "Camila, entiendo tu punto, pero hoy salió mejor de lo que pensaba. Lo dijimos juntos al inicio y la clase entera lo aceptó sin dramas.", en: "Camila, I get your point, but today went better than I thought. We said it together at the start and the whole class accepted it without drama." },
        { speaker: "B", es: "¿Alguien se quejó?", en: "Did anyone complain?" },
        { speaker: "A", es: "Luis dijo que necesita el celular por su hija — y tiene razón. Le dije: emergencia, mano arriba, sin problema.", en: "Luis said he needs his phone for his daughter — and he's right. I told him: emergency, hand up, no problem." },
        { speaker: "A", es: "Yo lo veo distinto ahora: no era confianza vs reglas, era claridad.", en: "I see it differently now: it wasn't trust vs rules, it was clarity." },
        { speaker: "B", es: "¿No crees que Rocío tenía razón en lo del acuerdo explícito?", en: "Don't you think Rocío was right about the explicit agreement?" },
        { speaker: "A", es: "Totalmente. Puede ser, pero discutir así contigo me ayudó más que cualquier manual.", en: "Totally. Maybe, but arguing like this with you helped more than any manual." },
        { speaker: "B", es: "No peleamos. Eso cuenta.", en: "We didn't fight. That counts." },
        { speaker: "A", es: "No estoy segura de que esto cuente como debate, pero no peleamos. Y eso — creo que es personalidad.", en: "I'm not sure this counts as debate, but we didn't fight. And that — I think that's personality." },
      ],
    },
  },
  {
    day: 308,
    themeEs: "Repaso: Debate suave I",
    isRecap: true,
    vocab: [
      { es: "gratis", en: "free (of charge)", example: "Si es gratis, viene más gente." },
      { es: "apuntarse", en: "to sign up", example: "Yo no me apunto todas las semanas." },
      { es: "el salón", en: "the room, the classroom", example: "¿Nos prestan el salón un sábado?" },
      { es: "aguantar", en: "to hold up, to keep it up", example: "No sé si aguantamos hasta junio." },
      { es: "no estoy segura de que", en: "i'm not sure that (+ subjunctive)", example: "No estoy segura de que podamos seguir." },
    ],
    dialogue: {
      title: "El grupo del sábado",
      situation: "Viernes en el estacionamiento — Rocío tiene una idea",
      lines: [
        { speaker: "B", es: "Quiero abrir un grupo los sábados. Dos horas, gratis, para los que van atrasados.", en: "I want to start a Saturday group. Two hours, free, for the kids who are behind." },
        { speaker: "A", es: "Entiendo tu punto, pero el sábado es el único día que esos chicos duermen.", en: "I get your point, but Saturday is the one day those kids get to sleep." },
        { speaker: "B", es: "Los que quieran vienen. Y si cobramos poquito, valoran más.", en: "Whoever wants to comes. And if we charge a little, they value it more." },
        { speaker: "A", es: "Yo lo veo distinto: si es gratis, viene más gente.", en: "I see it differently: if it's free, more people come." },
        { speaker: "B", es: "Bueno, gratis. De nueve a once.", en: "Fine, free. Nine to eleven." },
        { speaker: "A", es: "¿No crees que dos horas es mucho para un sábado por la mañana?", en: "Don't you think two hours is a lot for a Saturday morning?" },
        { speaker: "B", es: "Con hora y media no da tiempo a nada.", en: "An hour and a half isn't enough time for anything." },
        { speaker: "A", es: "Puede ser, pero yo no voy a ser la que les diga que el niño tiene que venir.", en: "Maybe, but I'm not going to be the one who tells them their kid has to come." },
        { speaker: "B", es: "Nadie va a obligar a nadie, Marlana.", en: "Nobody's going to force anyone, Marlana." },
        { speaker: "A", es: "Ya. No estoy segura de que podamos seguir con esto después de mayo.", en: "Okay. I'm not sure we can keep this going past May." },
        { speaker: "B", es: "Piénsalo el fin de semana. No te estoy pidiendo el año entero.", en: "Think about it this weekend. I'm not asking you for the whole year." },
      ],
    },
  },
];
