import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 8 — "Temas grandes" (days 323–329).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week8-frames.ts
 * for the matching `frameStem` (convention 2).
 *
 * Authored English-first: the thought Marlana would actually have came first,
 * the Spanish second. Big topics arrive attached to people with names —
 * Yesenia, Diego, Rocío — never as ideas floating on their own.
 */
export const priWeek8SpeakDays: SpeakDay[] = [
  {
    day: 323,
    themeEs: "La pregunta de Yesenia",
    themeEn: "Yesenia's question",
    missionEs: "Cuenta la pregunta que no supiste contestar.",
    missionEn: "Tell the story of the question you couldn't answer.",
    line: "Yesenia preguntó para qué. Tú diste la respuesta de folleto.",
    lineEn: "Yesenia asked what for. You gave the brochure answer.",
    prompts: [
      {
        id: "d323-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me is that I gave her the brochure answer.",
        spanish: "A mí lo que me molesta es que le di la respuesta de folleto.",
        situationLabel: "Jueves en el café",
        why: "*A mí lo que me molesta es…* leads with the feeling, which is how the sentence actually arrives in your head.",
        wordHints: [
          { en: "what bugs me", es: "lo que me molesta" },
          { en: "i gave her", es: "le di" },
          { en: "the brochure answer", es: "la respuesta de folleto" },
        ],
      },
      {
        id: "d323-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: she's not asking about English, she's asking whether it's worth four hours.",
        spanish: "Lo que pasa es que no pregunta por el inglés, pregunta si vale las cuatro horas.",
        situationLabel: "Lo que Yesenia preguntó de verdad",
        why: "*Lo que pasa es que…* sets up the real situation before anyone can argue about the wrong one.",
        wordHints: [
          { en: "here's what's going on", es: "lo que pasa es que" },
          { en: "she's not asking about", es: "no pregunta por" },
          { en: "it's worth", es: "vale" },
          { en: "four hours", es: "las cuatro horas" },
        ],
      },
      {
        id: "d323-no-es-que",
        frameStem: "No es que…",
        english: "It's not that she doesn't want to learn — she's exhausted and she's doing the math.",
        spanish: "No es que no quiera aprender, es que está agotada y está haciendo cuentas.",
        situationLabel: "Corrigiendo la versión fácil",
        why: "*No es que* + subjunctive waves off the wrong version; *es que* + indicative lands the true one.",
        wordHints: [
          { en: "it's not that", es: "no es que" },
          { en: "she wants to learn", es: "quiera aprender" },
          { en: "exhausted", es: "agotada" },
          { en: "doing the math", es: "haciendo cuentas" },
        ],
      },
      {
        id: "d323-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is a woman who cleans offices all day and still shows up at seven.",
        spanish: "Yo lo que veo es una mujer que limpia oficinas todo el día y aun así llega a las siete.",
        situationLabel: "La clase de las siete",
        why: "*Yo lo que veo es…* answers a big question with one person you actually watched — no statistics required.",
        wordHints: [
          { en: "what i see is", es: "yo lo que veo es" },
          { en: "cleans offices", es: "limpia oficinas" },
          { en: "and still", es: "y aun así" },
          { en: "shows up", es: "llega" },
        ],
      },
      {
        id: "d323-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do? Because \"opportunities\" isn't going to be enough for her.",
        spanish: "¿Tú qué harías? Porque \"oportunidades\" no le va a alcanzar.",
        situationLabel: "Pasándole la pregunta a Camila",
        why: "Handing the question over is what keeps a big topic from turning into a speech.",
        wordHints: [
          { en: "what would you do", es: "tú qué harías" },
          { en: "isn't going to be enough for her", es: "no le va a alcanzar" },
        ],
      },
    ],
  },
  {
    day: 324,
    themeEs: "La tarea que no escribió",
    themeEn: "The homework he didn't write",
    missionEs: "Explica por qué el párrafo perfecto te preocupa.",
    missionEn: "Explain why the perfect paragraph worries you.",
    line: "Un párrafo perfecto de un chico que nunca termina una frase.",
    lineEn: "A perfect paragraph from a kid who never finishes a sentence.",
    prompts: [
      {
        id: "d324-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me isn't the app — it's that he thought I wouldn't notice.",
        spanish: "A mí lo que me molesta no es la app, es que pensó que yo no me iba a dar cuenta.",
        situationLabel: "El párrafo del lunes",
        why: "Naming what does *not* bother you first makes the real objection land harder.",
        wordHints: [
          { en: "what bugs me", es: "lo que me molesta" },
          { en: "he thought", es: "pensó" },
          { en: "i wouldn't notice", es: "yo no me iba a dar cuenta" },
        ],
      },
      {
        id: "d324-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: he can talk about the book, what he can't do is write it.",
        spanish: "Lo que pasa es que él sí puede hablar del libro, lo que no puede es escribirlo.",
        situationLabel: "Lo que sí sabe hacer",
        why: "The *sí… lo que no…* pairing holds both halves of a problem in one breath.",
        wordHints: [
          { en: "he can talk about", es: "él sí puede hablar de" },
          { en: "what he can't do", es: "lo que no puede" },
          { en: "write it", es: "escribirlo" },
        ],
      },
      {
        id: "d324-no-es-que",
        frameStem: "No es que…",
        english: "It's not that he cheated — nobody ever showed him what a first draft looks like.",
        spanish: "No es que haya hecho trampa, es que nadie le enseñó cómo se ve un primer borrador.",
        situationLabel: "Antes de castigar",
        why: "*No es que haya…* — the perfect subjunctive, because you're dismissing something already done.",
        wordHints: [
          { en: "he cheated", es: "haya hecho trampa" },
          { en: "nobody showed him", es: "nadie le enseñó" },
          { en: "a first draft", es: "un primer borrador" },
        ],
      },
      {
        id: "d324-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is a kid who's afraid to hand in something ugly.",
        spanish: "Yo lo que veo es un chico con miedo de entregar algo feo.",
        situationLabel: "Detrás del párrafo",
        why: "*Con miedo de…* is lighter and more spoken than *que tiene miedo de que…* — say the short one.",
        wordHints: [
          { en: "afraid to", es: "con miedo de" },
          { en: "hand in", es: "entregar" },
          { en: "something ugly", es: "algo feo" },
        ],
      },
      {
        id: "d324-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do Monday? Because I'm not failing him over this.",
        spanish: "¿Tú qué harías el lunes? Porque yo no lo voy a reprobar por eso.",
        situationLabel: "El lunes por la mañana",
        why: "You can ask for advice and rule out an option in the same breath — that's how people actually ask.",
        wordHints: [
          { en: "what would you do", es: "tú qué harías" },
          { en: "fail him", es: "reprobarlo" },
          { en: "over this", es: "por eso" },
        ],
      },
    ],
  },
  {
    day: 325,
    themeEs: "Solo inglés en casa",
    themeEn: "English only at home",
    missionEs: "Defiende el español de la casa sin dar un sermón.",
    missionEn: "Defend the home language without giving a lecture.",
    line: "La mamá de Diego pide solo inglés. Alguien se lo dijo antes que tú.",
    lineEn: "Diego's mom asks for English only. Somebody told her that before you did.",
    prompts: [
      {
        id: "d325-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me is that somebody told her Spanish was the problem.",
        spanish: "A mí lo que me molesta es que alguien le dijo que el español era el problema.",
        situationLabel: "Después de la reunión",
        why: "The irritation isn't aimed at the mother — say who it *is* aimed at and it stops sounding like judgment.",
        wordHints: [
          { en: "somebody told her", es: "alguien le dijo" },
          { en: "was the problem", es: "era el problema" },
        ],
      },
      {
        id: "d325-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: she's not asking me to take away Spanish, she's asking me to fix her son.",
        spanish: "Lo que pasa es que no me pide quitar el español, me pide arreglar a su hijo.",
        situationLabel: "Lo que pedía de verdad",
        why: "Two clauses, same verb — the contrast does the work without a single connector.",
        wordHints: [
          { en: "she's not asking me to", es: "no me pide" },
          { en: "take away", es: "quitar" },
          { en: "fix", es: "arreglar" },
        ],
      },
      {
        id: "d325-no-es-que",
        frameStem: "No es que…",
        english: "It's not that she's ashamed of the language — she's tired of not understanding the school.",
        spanish: "No es que le dé pena el idioma, es que está cansada de no entender a la escuela.",
        situationLabel: "El miedo debajo",
        why: "*Darle pena* is the everyday way to say embarrassed — softer and far more common than *avergonzarse*.",
        wordHints: [
          { en: "she's ashamed of", es: "le dé pena" },
          { en: "tired of", es: "cansada de" },
          { en: "not understanding", es: "no entender" },
        ],
      },
      {
        id: "d325-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is an eight-year-old translating a doctor's appointment.",
        spanish: "Yo lo que veo es una niña de ocho años traduciendo una cita médica.",
        situationLabel: "Lo que Camila también ha visto",
        why: "One image beats a paragraph of argument — and Camila has the hospital version of the same one.",
        wordHints: [
          { en: "an eight-year-old", es: "una niña de ocho años" },
          { en: "translating", es: "traduciendo" },
          { en: "a doctor's appointment", es: "una cita médica" },
        ],
      },
      {
        id: "d325-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do? You've been on her side of that conversation.",
        spanish: "¿Tú qué harías? Tú has estado del lado de ella en esa conversación.",
        situationLabel: "Camila sabe de esto",
        why: "Asking someone with lived experience isn't the same as asking for an opinion — name the difference out loud.",
        wordHints: [
          { en: "you've been", es: "tú has estado" },
          { en: "on her side", es: "del lado de ella" },
        ],
      },
    ],
  },
  {
    day: 326,
    themeEs: "Cortan la clase de la noche",
    themeEn: "They're cutting the night class",
    missionEs: "Cuenta el recorte y por qué el motivo oficial no es el real.",
    missionEn: "Tell them about the cut and why the official reason isn't the real one.",
    line: "Cortaron la clase de las siete. Yesenia está en esa clase.",
    lineEn: "They cut the seven o'clock class. Yesenia is in that class.",
    prompts: [
      {
        id: "d326-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me is they cut the night class and called it \"low enrollment.\"",
        spanish: "A mí lo que me molesta es que cortaron la clase de la noche y lo llamaron \"poca inscripción\".",
        situationLabel: "El correo del viernes",
        why: "Quoting their words back is a whole argument in two words — you don't have to add anything.",
        wordHints: [
          { en: "they cut", es: "cortaron" },
          { en: "the night class", es: "la clase de la noche" },
          { en: "they called it", es: "lo llamaron" },
          { en: "low enrollment", es: "poca inscripción" },
        ],
      },
      {
        id: "d326-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: eleven people can't come at four in the afternoon because they're working.",
        spanish: "Lo que pasa es que once personas no pueden venir a las cuatro de la tarde porque están trabajando.",
        situationLabel: "Por qué no van a las cuatro",
        why: "A number plus a reason is the most persuasive shape a spoken sentence has.",
        wordHints: [
          { en: "eleven people", es: "once personas" },
          { en: "at four in the afternoon", es: "a las cuatro de la tarde" },
          { en: "they're working", es: "están trabajando" },
        ],
      },
      {
        id: "d326-no-es-que",
        frameStem: "No es que…",
        english: "It's not that there's no money — we're the easiest line to cut.",
        spanish: "No es que no haya dinero, es que somos la línea más fácil de cortar.",
        situationLabel: "El motivo real",
        why: "*No es que no haya…* — double negative, subjunctive, and completely normal in speech.",
        wordHints: [
          { en: "there's no money", es: "no haya dinero" },
          { en: "the easiest line", es: "la línea más fácil" },
          { en: "to cut", es: "de cortar" },
        ],
      },
      {
        id: "d326-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is that the class that fills up is the one they're closing.",
        spanish: "Yo lo que veo es que la clase que se llena es la que están cerrando.",
        situationLabel: "La contradicción",
        why: "State the contradiction flatly and let the other person be the one who says it's absurd.",
        wordHints: [
          { en: "fills up", es: "se llena" },
          { en: "the one", es: "la que" },
          { en: "they're closing", es: "están cerrando" },
        ],
      },
      {
        id: "d326-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do — write to them or show up at the meeting?",
        spanish: "¿Tú qué harías? ¿Escribirles o presentarte en la reunión?",
        situationLabel: "Dos opciones, ninguna cómoda",
        why: "Offering the two options you're stuck between is faster than describing being stuck.",
        wordHints: [
          { en: "write to them", es: "escribirles" },
          { en: "show up", es: "presentarte" },
          { en: "at the meeting", es: "en la reunión" },
        ],
      },
    ],
  },
  {
    day: 327,
    themeEs: "El examen del estado",
    themeEn: "The state test",
    missionEs: "Explica qué mide el examen y qué no.",
    missionEn: "Explain what the test measures and what it doesn't.",
    line: "Diego explica fracciones perfecto. Diego saca un dos.",
    lineEn: "Diego explains fractions perfectly. Diego scores a two.",
    prompts: [
      {
        id: "d327-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me is they test them in English on things they already know in Spanish.",
        spanish: "A mí lo que me molesta es que los evalúan en inglés sobre cosas que ya saben en español.",
        situationLabel: "La semana del examen",
        why: "The whole objection fits in one sentence once you put the two languages side by side.",
        wordHints: [
          { en: "they test them", es: "los evalúan" },
          { en: "on things", es: "sobre cosas" },
          { en: "they already know", es: "ya saben" },
        ],
      },
      {
        id: "d327-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: the score measures the English, and then they read it as if it measured the kid.",
        spanish: "Lo que pasa es que la nota mide el inglés, y después la leen como si midiera al niño.",
        situationLabel: "Lo que la nota dice de verdad",
        why: "*Como si* + imperfect subjunctive is exactly \"as though it were\" — and it belongs in ordinary speech, not an essay.",
        wordHints: [
          { en: "the score", es: "la nota" },
          { en: "measures", es: "mide" },
          { en: "as if it measured", es: "como si midiera" },
        ],
      },
      {
        id: "d327-no-es-que",
        frameStem: "No es que…",
        english: "It's not that I'm against tests — this one tells me nothing I didn't know in October.",
        spanish: "No es que yo esté en contra de los exámenes, es que este no me dice nada que no supiera en octubre.",
        situationLabel: "Precisando la queja",
        why: "Ruling out the caricature of your own position keeps a disagreement from collapsing into sides.",
        wordHints: [
          { en: "i'm against", es: "yo esté en contra de" },
          { en: "tells me nothing", es: "no me dice nada" },
          { en: "i didn't know", es: "no supiera" },
        ],
      },
      {
        id: "d327-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is Diego explaining fractions perfectly and scoring a two.",
        spanish: "Yo lo que veo es a Diego explicando fracciones perfecto y sacando un dos.",
        situationLabel: "Diego y las fracciones",
        why: "Two gerunds hung off one *veo* — the sentence shows the contradiction instead of arguing it.",
        wordHints: [
          { en: "explaining", es: "explicando" },
          { en: "fractions", es: "fracciones" },
          { en: "scoring", es: "sacando" },
        ],
      },
      {
        id: "d327-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do if they graded your shift with a test in a language you were still learning?",
        spanish: "¿Tú qué harías si calificaran tu turno con un examen en un idioma que todavía estás aprendiendo?",
        situationLabel: "El turno de Camila",
        why: "Moving the problem into the other person's world is the fastest way to be understood — *si* + imperfect subjunctive carries it.",
        wordHints: [
          { en: "they graded", es: "calificaran" },
          { en: "your shift", es: "tu turno" },
          { en: "you were still learning", es: "todavía estás aprendiendo" },
        ],
      },
    ],
  },
  {
    day: 328,
    themeEs: "Lo que voy a decir el martes",
    themeEn: "What I'm going to say Tuesday",
    missionEs: "Ensaya tus tres minutos y deja que te interrumpan.",
    missionEn: "Rehearse your three minutes and let yourself be interrupted.",
    line: "Tres minutos en la junta escolar. Camila es el público de práctica.",
    lineEn: "Three minutes at the school board. Camila is the practice audience.",
    prompts: [
      {
        id: "d328-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me is I have three minutes and I've already spent two on my job title.",
        spanish: "A mí lo que me molesta es que tengo tres minutos y ya gasté dos en mi cargo.",
        situationLabel: "Ensayando en el café",
        why: "Being annoyed at your own draft is a real thing to say out loud — and it's the fastest way to fix it.",
        wordHints: [
          { en: "i have three minutes", es: "tengo tres minutos" },
          { en: "i've already spent", es: "ya gasté" },
          { en: "my job title", es: "mi cargo" },
        ],
      },
      {
        id: "d328-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: if I give them numbers, they answer me with numbers.",
        spanish: "Lo que pasa es que si yo digo números, ellos me contestan con números.",
        situationLabel: "La trampa del borrador",
        why: "Present indicative in both halves — Spanish doesn't need a future tense to state what always happens.",
        wordHints: [
          { en: "if i give them numbers", es: "si yo digo números" },
          { en: "they answer me", es: "ellos me contestan" },
        ],
      },
      {
        id: "d328-no-es-que",
        frameStem: "No es que…",
        english: "It's not that I want them to feel bad — I want them to move the class to seven.",
        spanish: "No es que quiera que se sientan mal, es que quiero que muevan la clase a las siete.",
        situationLabel: "La petición concreta",
        why: "Three subjunctives in one sentence, and not one of them is a grammar exercise.",
        wordHints: [
          { en: "i want them to feel bad", es: "quiera que se sientan mal" },
          { en: "move the class", es: "muevan la clase" },
        ],
      },
      {
        id: "d328-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is they'll listen to me if I bring Yesenia and not a chart.",
        spanish: "Yo lo que veo es que me van a escuchar si llevo a Yesenia y no una gráfica.",
        situationLabel: "Qué va a funcionar",
        why: "*Yo lo que veo es que…* lets you predict without claiming certainty — the opinion stays an opinion.",
        wordHints: [
          { en: "they'll listen to me", es: "me van a escuchar" },
          { en: "if i bring", es: "si llevo" },
          { en: "a chart", es: "una gráfica" },
        ],
      },
      {
        id: "d328-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do? Stop me if I start sounding like a report.",
        spanish: "¿Tú qué harías? Párame si empiezo a sonar a informe.",
        situationLabel: "Pidiéndole que te corte",
        why: "*Sonar a…* takes no article: *sonar a informe*, *sonar a folleto*, *sonar a queja*.",
        wordHints: [
          { en: "stop me", es: "párame" },
          { en: "i start", es: "empiezo a" },
          { en: "sounding like a report", es: "sonar a informe" },
        ],
      },
    ],
  },
  {
    day: 329,
    themeEs: "Repaso: Temas grandes",
    themeEn: "Review: Big topics",
    missionEs: "Los mismos cinco stems, en el pasillo, en cuatro minutos.",
    missionEn: "The same five stems, in the hallway, in four minutes.",
    line: "Lunes, 7:40, junto a la copiadora. Rocío ya pasó por esto.",
    lineEn: "Monday, 7:40, by the copier. Rocío has been through this before.",
    prompts: [
      {
        id: "d329-a-mi-lo-que-me-molesta",
        frameStem: "A mí lo que me molesta es…",
        english: "What bugs me is that you found out from the newsletter and not from them.",
        spanish: "A mí lo que me molesta es que te enteraste por el boletín y no por ellos.",
        situationLabel: "Junto a la copiadora",
        why: "*Enterarse por…* is the everyday verb for news that reached you sideways.",
        wordHints: [
          { en: "you found out", es: "te enteraste" },
          { en: "from the newsletter", es: "por el boletín" },
        ],
      },
      {
        id: "d329-lo-que-pasa-es-que",
        frameStem: "Lo que pasa es que…",
        english: "Here's what's going on: nobody from the night class is going to be free at that hour either.",
        spanish: "Lo que pasa es que nadie de la clase de la noche va a estar libre a esa hora tampoco.",
        situationLabel: "La hora de la reunión",
        why: "The same problem twice — and *tampoco* at the very end is where it lands.",
        wordHints: [
          { en: "nobody from", es: "nadie de" },
          { en: "to be free", es: "estar libre" },
          { en: "either", es: "tampoco" },
        ],
      },
      {
        id: "d329-no-es-que",
        frameStem: "No es que…",
        english: "It's not that I don't want to go alone — alone I'm just one teacher complaining.",
        spanish: "No es que no quiera ir sola, es que sola soy una maestra quejándose.",
        situationLabel: "Por qué quiere compañía",
        why: "Saying the unflattering version of yourself out loud is usually what convinces someone to come with you.",
        wordHints: [
          { en: "i don't want to go alone", es: "no quiera ir sola" },
          { en: "one teacher", es: "una maestra" },
          { en: "complaining", es: "quejándose" },
        ],
      },
      {
        id: "d329-yo-lo-que-veo-es",
        frameStem: "Yo lo que veo es…",
        english: "What I see is that you've done this before and you know who to talk to first.",
        spanish: "Yo lo que veo es que tú ya hiciste esto antes y sabes con quién hablar primero.",
        situationLabel: "Rocío ya pasó por esto",
        why: "Pointing at what someone else can do is an opinion too — and it's the kind that gets you help.",
        wordHints: [
          { en: "you've done this before", es: "tú ya hiciste esto antes" },
          { en: "who to talk to", es: "con quién hablar" },
        ],
      },
      {
        id: "d329-tu-que-harias",
        frameStem: "¿Tú qué harías?",
        english: "What would you do — go Tuesday or wait for the vote?",
        spanish: "¿Tú qué harías? ¿Ir el martes o esperar la votación?",
        situationLabel: "Cuatro minutos antes del timbre",
        why: "Two infinitives are all a question needs when the other person already knows the situation.",
        wordHints: [
          { en: "go tuesday", es: "ir el martes" },
          { en: "wait for", es: "esperar" },
          { en: "the vote", es: "la votación" },
        ],
      },
    ],
  },
];
