import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 8 — "Temas grandes" (days 323–329).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week8-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek8SpeakDays: SpeakDay[] = [
  {
    day: 323,
    themeEs: "La pregunta de Yesenia",
    themeEn: "Yesenia's question",
    missionEs: "Responde a una pregunta grande sobre la escuela con en el fondo y la cosa es que.",
    missionEn: "Answer a big question about school using \"deep down\" and \"the thing is.\"",
    line: "Los temas grandes empiezan con una pregunta honesta.",
    lineEn: "Big topics start with an honest question.",
    prompts: [
      {
        id: "d323-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, teaching isn't filling heads, it's opening doors.",
        spanish: "En el fondo, enseñar no es llenar la cabeza, es abrir la puerta.",
        situationLabel: "La respuesta que buscas",
        why: "*En el fondo* is spoken philosophy — you say it leaning on the table, not standing at a podium.",
        wordHints: [
          { en: "deep down", es: "en el fondo" },
          { en: "teaching", es: "enseñar" },
          { en: "open the door", es: "abrir la puerta" },
        ],
      },
      {
        id: "d323-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days everyone opines about school without ever having been in one.",
        spanish: "Hoy en día todo el mundo opina de la escuela sin haber entrado a una.",
        situationLabel: "El presente",
        why: "*Hoy en día* marks the present moment — not nostalgia, not a trend piece.",
        wordHints: [
          { en: "these days", es: "hoy en día" },
          { en: "everyone opines", es: "todo el mundo opina" },
          { en: "without having been in one", es: "sin haber entrado a una" },
        ],
      },
      {
        id: "d323-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more families want two languages and one life.",
        spanish: "Cada vez más familias quieren dos idiomas y una sola vida.",
        situationLabel: "Lo que ves",
        why: "*Cada vez más* stacks evidence — you're counting what you see, not theorizing.",
        wordHints: [
          { en: "more and more", es: "cada vez más" },
          { en: "families", es: "familias" },
          { en: "two languages", es: "dos idiomas" },
        ],
      },
      {
        id: "d323-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, what matters is that the kid wants to come back.",
        spanish: "Al final del día, lo que importa es que el niño quiera volver.",
        situationLabel: "Lo que cuenta",
        why: "*Al final del día* closes the argument without closing the talk — opinion, not verdict.",
        wordHints: [
          { en: "at the end of the day", es: "al final del día" },
          { en: "what matters", es: "lo que importa" },
          { en: "wants to come back", es: "quiera volver" },
        ],
      },
      {
        id: "d323-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is I didn't have a ready answer for Yesenia.",
        spanish: "La cosa es que no tenía una respuesta lista para Yesenia.",
        situationLabel: "La verdad",
        why: "*La cosa es que* is how you start the sentence you were avoiding — the real point, not the polished one.",
        wordHints: [
          { en: "the thing is", es: "la cosa es que" },
          { en: "i didn't have", es: "no tenía" },
          { en: "a ready answer", es: "una respuesta lista" },
        ],
      },
    ],
  },
  {
    day: 324,
    themeEs: "La tarea que no escribió",
    themeEn: "The assignment he didn't write",
    missionEs: "Habla de tecnología en la escuela con hoy en día y al final del día.",
    missionEn: "Talk about technology at school using \"these days\" and \"at the end of the day.\"",
    line: "Un párrafo perfecto puede ser la señal más clara.",
    lineEn: "A perfect paragraph can be the clearest signal.",
    prompts: [
      {
        id: "d324-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, the kid didn't want to look bad, he wanted to look good.",
        spanish: "En el fondo, el chico no quería quedar mal, quería quedar bien.",
        situationLabel: "Por qué lo hizo",
        why: "Technology stories are people stories — *en el fondo* names the kid's motive, not the app's.",
        wordHints: [
          { en: "deep down", es: "en el fondo" },
          { en: "look bad", es: "quedar mal" },
          { en: "look good", es: "quedar bien" },
        ],
      },
      {
        id: "d324-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days a student can write the assignment in the elevator.",
        spanish: "Hoy en día un estudiante puede escribir la tarea en el ascensor.",
        situationLabel: "La velocidad nueva",
        why: "*Hoy en día* marks what's different right now — thirty seconds changes the whole classroom.",
        wordHints: [
          { en: "these days", es: "hoy en día" },
          { en: "a student", es: "un estudiante" },
          { en: "the assignment", es: "la tarea" },
        ],
      },
      {
        id: "d324-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more teachers don't know what to allow and what to ban.",
        spanish: "Cada vez más maestros no saben qué permitir y qué prohibir.",
        situationLabel: "La duda compartida",
        why: "You're not alone in the confusion — *cada vez más* makes it collective, not personal failure.",
        wordHints: [
          { en: "more and more teachers", es: "cada vez más maestros" },
          { en: "what to allow", es: "qué permitir" },
          { en: "what to ban", es: "qué prohibir" },
        ],
      },
      {
        id: "d324-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, I don't want a cop in the classroom, I want a guide.",
        spanish: "Al final del día, no quiero un policía en el salón, quiero un guía.",
        situationLabel: "Tu rol",
        why: "*Policía* vs *guía* — the week's technology answer in one comparison.",
        wordHints: [
          { en: "at the end of the day", es: "al final del día" },
          { en: "a cop", es: "un policía" },
          { en: "a guide", es: "un guía" },
        ],
      },
      {
        id: "d324-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is I use translation too when I'm tired.",
        spanish: "La cosa es que yo también uso traducción cuando estoy cansada.",
        situationLabel: "Honestidad primero",
        why: "Before you judge the kid, *la cosa es que* admits your own shortcut — that's how the talk stays human.",
        wordHints: [
          { en: "the thing is", es: "la cosa es que" },
          { en: "i also use", es: "yo también uso" },
          { en: "translation", es: "traducción" },
        ],
      },
    ],
  },
  {
    day: 325,
    themeEs: "Solo inglés en casa",
    themeEn: "English only at home",
    missionEs: "Defiende el bilingüismo en casa con cada vez más y al final del día.",
    missionEn: "Defend home bilingualism using \"more and more\" and \"at the end of the day.\"",
    line: "Quitar un idioma no acelera el otro.",
    lineEn: "Taking away one language doesn't speed up the other.",
    prompts: [
      {
        id: "d325-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, the mom doesn't hate Spanish, she hates feeling left out.",
        spanish: "En el fondo, la mamá no odia el español, odia sentirse fuera.",
        situationLabel: "El miedo de la mamá",
        why: "*En el fondo* reframes the parent — fear, not hatred. That's how you stay gentle in the meeting.",
        wordHints: [
          { en: "deep down", es: "en el fondo" },
          { en: "she hates feeling left out", es: "odia sentirse fuera" },
          { en: "spanish", es: "el español" },
        ],
      },
      {
        id: "d325-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days bilingualism gets sold on posters and punished at home.",
        spanish: "Hoy en día el bilingüismo se vende en carteles y se castiga en casa.",
        situationLabel: "La contradicción",
        why: "*Se vende* and *se castiga* — passive voice for systems, not people. Spoken, not essay.",
        wordHints: [
          { en: "bilingualism", es: "el bilingüismo" },
          { en: "on posters", es: "en carteles" },
          { en: "at home", es: "en casa" },
        ],
      },
      {
        id: "d325-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more kids translate bills before homework.",
        spanish: "Cada vez más niños traducen facturas antes de los deberes.",
        situationLabel: "Lo que ya hacen",
        why: "Concrete image beats abstract argument — *facturas antes de los deberes* is the whole case.",
        wordHints: [
          { en: "more and more kids", es: "cada vez más niños" },
          { en: "translate bills", es: "traducen facturas" },
          { en: "before homework", es: "antes de los deberes" },
        ],
      },
      {
        id: "d325-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, taking away Spanish doesn't speed up English.",
        spanish: "Al final del día, quitar el español no acelera el inglés.",
        situationLabel: "La respuesta simple",
        why: "One line the parent can hear — *no acelera* is plain and firm without sounding like a lecture.",
        wordHints: [
          { en: "taking away spanish", es: "quitar el español" },
          { en: "doesn't speed up", es: "no acelera" },
          { en: "english", es: "el inglés" },
        ],
      },
      {
        id: "d325-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is I didn't say everything I was thinking at the meeting.",
        spanish: "La cosa es que no le dije todo lo que pensaba en la reunión.",
        situationLabel: "Lo que guardaste",
        why: "Meetings have limits; the café doesn't — *la cosa es que* opens the honest version.",
        wordHints: [
          { en: "i didn't tell her", es: "no le dije" },
          { en: "everything i was thinking", es: "todo lo que pensaba" },
          { en: "at the meeting", es: "en la reunión" },
        ],
      },
    ],
  },
  {
    day: 326,
    themeEs: "Para qué sirve",
    themeEn: "What it's for",
    missionEs: "Une educación, tecnología e idioma con en el fondo y al final del día.",
    missionEn: "Connect education, technology, and language using \"deep down\" and \"at the end of the day.\"",
    line: "Tres temas, una pregunta: ¿para qué?",
    lineEn: "Three topics, one question: what for?",
    prompts: [
      {
        id: "d326-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, we both chose jobs where people arrive scared.",
        spanish: "En el fondo, los dos elegimos trabajos donde la gente llega asustada.",
        situationLabel: "Marlana y Camila",
        why: "Abstract week, concrete bond — *los dos elegimos* makes the philosophy personal.",
        wordHints: [
          { en: "deep down", es: "en el fondo" },
          { en: "we both chose", es: "los dos elegimos" },
          { en: "people arrive scared", es: "la gente llega asustada" },
        ],
      },
      {
        id: "d326-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days they measure everything except whether someone feels seen.",
        spanish: "Hoy en día miden todo excepto si alguien se siente visto.",
        situationLabel: "Lo que no miden",
        why: "*Se siente visto* — seen, noticed. The metric schools skip.",
        wordHints: [
          { en: "they measure everything", es: "miden todo" },
          { en: "except", es: "excepto" },
          { en: "feels seen", es: "se siente visto" },
        ],
      },
      {
        id: "d326-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more I can say this in Spanish without looking for the word in English.",
        spanish: "Cada vez más puedo decir esto en español sin buscar la palabra en inglés.",
        situationLabel: "Tu progreso",
        why: "Big topics in Spanish are a skill — name your own shift with *cada vez más*.",
        wordHints: [
          { en: "more and more i can", es: "cada vez más puedo" },
          { en: "say this in spanish", es: "decir esto en español" },
          { en: "without looking for the word", es: "sin buscar la palabra" },
        ],
      },
      {
        id: "d326-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, it works if someone leaves with more doors open.",
        spanish: "Al final del día, sirve si alguien se va con más puertas abiertas.",
        situationLabel: "Para qué sirve",
        why: "*Más puertas abiertas* — the week's answer for education, tech, and language in one image.",
        wordHints: [
          { en: "at the end of the day", es: "al final del día" },
          { en: "it works if", es: "sirve si" },
          { en: "more doors open", es: "más puertas abiertas" },
        ],
      },
      {
        id: "d326-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is these topics scared me because they sounded like essays.",
        spanish: "La cosa es que estos temas me asustaban porque sonaban a ensayo.",
        situationLabel: "El miedo al registro",
        why: "Naming the fear is half the win — *sonaban a ensayo* is why this week exists.",
        wordHints: [
          { en: "these topics scared me", es: "estos temas me asustaban" },
          { en: "they sounded like", es: "sonaban a" },
          { en: "essays", es: "ensayo" },
        ],
      },
    ],
  },
  {
    day: 327,
    themeEs: "El teléfono en la mochila",
    themeEn: "The phone in the backpack",
    missionEs: "Discrepa con alguien usando la cosa es que y aun así en tu respuesta.",
    missionEn: "Disagree with someone using \"the thing is\" and \"even so\" in your reply.",
    line: "Puedes pensar distinto y seguir en la misma mesa.",
    lineEn: "You can think differently and stay at the same table.",
    prompts: [
      {
        id: "d327-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, we both fear losing the kids to the screen.",
        spanish: "En el fondo, los dos tenemos miedo a perder a los chicos en la pantalla.",
        situationLabel: "Lo que comparten",
        why: "Debate suave starts with shared ground — *los dos tenemos miedo* before the *pero*.",
        wordHints: [
          { en: "deep down", es: "en el fondo" },
          { en: "we both fear", es: "los dos tenemos miedo" },
          { en: "the screen", es: "la pantalla" },
        ],
      },
      {
        id: "d327-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days a phone is translator, map, calendar, and friend.",
        spanish: "Hoy en día un teléfono es traductor, mapa, calendario y amigo.",
        situationLabel: "Qué es ahora",
        why: "List three jobs the phone does — spoken rhythm, not bullet points on a slide.",
        wordHints: [
          { en: "these days", es: "hoy en día" },
          { en: "a phone is", es: "un teléfono es" },
          { en: "translator, map, calendar", es: "traductor, mapa, calendario" },
        ],
      },
      {
        id: "d327-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more I see that my example matters more than the rule.",
        spanish: "Cada vez más veo que el ejemplo mío importa más que la norma.",
        situationLabel: "Tu posición",
        why: "*El ejemplo mío* — holding ground without banning everything.",
        wordHints: [
          { en: "more and more i see", es: "cada vez más veo" },
          { en: "my example", es: "el ejemplo mío" },
          { en: "matters more than the rule", es: "importa más que la norma" },
        ],
      },
      {
        id: "d327-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, I want attention, not blind obedience.",
        spanish: "Al final del día, quiero atención, no obediencia ciega.",
        situationLabel: "Lo que pides",
        why: "*Atención* vs *obediencia ciega* — the classroom goal in one contrast.",
        wordHints: [
          { en: "attention", es: "atención" },
          { en: "not", es: "no" },
          { en: "blind obedience", es: "obediencia ciega" },
        ],
      },
      {
        id: "d327-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is I get your point, but my classroom isn't your night shift.",
        spanish: "La cosa es que entiendo tu punto, pero mi salón no es tu turno de noche.",
        situationLabel: "Debate suave",
        why: "*La cosa es que* + *pero* is gentle disagreement — you name their view, then you stay standing.",
        wordHints: [
          { en: "the thing is", es: "la cosa es que" },
          { en: "i get your point", es: "entiendo tu punto" },
          { en: "but my classroom", es: "pero mi salón" },
        ],
      },
    ],
  },
  {
    day: 328,
    themeEs: "Tres temas, una mesa",
    themeEn: "Three topics, one table",
    missionEs: "Cierra la semana: opina de los tres temas sin sonar a folleto.",
    missionEn: "Close the week: give your take on all three topics without sounding like a brochure.",
    line: "Los temas grandes caben en una mesa pequeña.",
    lineEn: "Big topics fit on a small table.",
    prompts: [
      {
        id: "d328-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, all three topics are the same thing: how people live.",
        spanish: "En el fondo, los tres temas son lo mismo: cómo vive la gente.",
        situationLabel: "El hilo",
        why: "Education, technology, language — *cómo vive la gente* ties the week together.",
        wordHints: [
          { en: "all three topics", es: "los tres temas" },
          { en: "the same thing", es: "lo mismo" },
          { en: "how people live", es: "cómo vive la gente" },
        ],
      },
      {
        id: "d328-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days I can give an opinion without sounding like a brochure.",
        spanish: "Hoy en día puedo opinar sin sonar como folleto.",
        situationLabel: "El registro",
        why: "*Sin sonar como folleto* — the week's register win, said out loud.",
        wordHints: [
          { en: "these days i can", es: "hoy en día puedo" },
          { en: "give an opinion", es: "opinar" },
          { en: "without sounding like a brochure", es: "sin sonar como folleto" },
        ],
      },
      {
        id: "d328-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more I hold three minutes on an abstract topic.",
        spanish: "Cada vez más aguanto tres minutos en un tema abstracto.",
        situationLabel: "Conversación larga",
        why: "*Aguanto tres minutos* — measurable fluency for abstract talk.",
        wordHints: [
          { en: "more and more i hold", es: "cada vez más aguanto" },
          { en: "three minutes", es: "tres minutos" },
          { en: "abstract topic", es: "tema abstracto" },
        ],
      },
      {
        id: "d328-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, big topics fit on a small table.",
        spanish: "Al final del día, los temas grandes caben en una mesa pequeña.",
        situationLabel: "Cierre de la historia",
        why: "The story title in one stem — café scale, not conference scale.",
        wordHints: [
          { en: "big topics", es: "los temas grandes" },
          { en: "fit on", es: "caben en" },
          { en: "a small table", es: "una mesa pequeña" },
        ],
      },
      {
        id: "d328-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is I don't need permission to have an opinion anymore.",
        spanish: "La cosa es que ya no necesito permiso para tener una opinión.",
        situationLabel: "Lo que cambió",
        why: "Primavera phase — *ya no necesito permiso* is personality, not grammar.",
        wordHints: [
          { en: "i don't need permission", es: "no necesito permiso" },
          { en: "to have an opinion", es: "para tener una opinión" },
          { en: "anymore", es: "ya no" },
        ],
      },
    ],
  },
  {
    day: 329,
    themeEs: "Repaso: Temas grandes",
    themeEn: "Review: Big topics",
    missionEs: "Repasa los cinco stems con educación, tecnología e idioma.",
    missionEn: "Review all five stems with education, technology, and language.",
    line: "Cinco stems, tres temas, una mesa.",
    lineEn: "Five stems, three topics, one table.",
    prompts: [
      {
        id: "d329-en-el-fondo",
        frameStem: "En el fondo…",
        english: "Deep down, this week was talking about people, not loose ideas.",
        spanish: "En el fondo, esta semana fue hablar de gente, no de ideas.",
        situationLabel: "Balance de la semana",
        why: "Repaso *en el fondo* looks back at the method — people first, abstractions second.",
        wordHints: [
          { en: "this week was", es: "esta semana fue" },
          { en: "talking about people", es: "hablar de gente" },
          { en: "not loose ideas", es: "no de ideas" },
        ],
      },
      {
        id: "d329-hoy-en-dia",
        frameStem: "Hoy en día…",
        english: "These days I can name what's happening without writing an essay.",
        spanish: "Hoy en día puedo nombrar lo que pasa sin escribir un ensayo.",
        situationLabel: "Registro hablado",
        why: "*Nombrar lo que pasa* — the skill the week built.",
        wordHints: [
          { en: "i can name", es: "puedo nombrar" },
          { en: "what's happening", es: "lo que pasa" },
          { en: "without writing an essay", es: "sin escribir un ensayo" },
        ],
      },
      {
        id: "d329-cada-vez-mas",
        frameStem: "Cada vez más…",
        english: "More and more I trust an incomplete opinion said in Spanish.",
        spanish: "Cada vez más confío en una opinión incompleta dicha en español.",
        situationLabel: "Fluidez abstracta",
        why: "*Opinión incompleta* — you don't need the perfect paragraph to have the conversation.",
        wordHints: [
          { en: "i trust", es: "confío en" },
          { en: "incomplete opinion", es: "opinión incompleta" },
          { en: "said in spanish", es: "dicha en español" },
        ],
      },
      {
        id: "d329-al-final",
        frameStem: "Al final del día…",
        english: "At the end of the day, teaching, translating, and learning use the same patience.",
        spanish: "Al final del día, enseñar, traducir y aprender usan la misma paciencia.",
        situationLabel: "Los tres temas",
        why: "Education · technology · language — one patience at the bottom.",
        wordHints: [
          { en: "teaching", es: "enseñar" },
          { en: "translating", es: "traducir" },
          { en: "the same patience", es: "la misma paciencia" },
        ],
      },
      {
        id: "d329-la-cosa",
        frameStem: "La cosa es que…",
        english: "The thing is *pero* and *aun así* get you further than *however* at a table.",
        spanish: "La cosa es que *pero* y *aun así* llevan más lejos que *sin embargo*.",
        situationLabel: "Conectores hablados",
        why: "Five stems for big topics — and spoken connectors all week. Not once *debido a*.",
        wordHints: [
          { en: "pero", es: "pero" },
          { en: "aun así", es: "aun así" },
          { en: "however", es: "sin embargo" },
        ],
      },
    ],
  },
];
