import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 1 — "Sonar como yo" (days 274–280).
 *
 * Marlana and Camila pick the Thursday café exchange back up. Spring is about
 * personality — but personality doesn't live in self-description, it lives in
 * how you react. Six installments, then a Saturday nobody planned.
 */
export const priWeek1ReadingDays: ReadingDay[] = [
  {
    day: 274,
    themeEs: "El primer jueves de primavera",
    storyTitle: "Sonar como yo",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "ay, no", en: "oh no, ugh (protest + affection)", example: "Ay, no, dame un café primero." },
      { es: "te juro que", en: "i swear (that)", example: "Te juro que nunca me he descrito en voz alta." },
      { es: "la verdad es que", en: "honestly, the truth is", example: "La verdad es que prefiero contarte una historia." },
      { es: "me da una cosa", en: "it gives me a feeling (no exact English)", example: "Me da una cosa cuando me preguntan a qué me dedico." },
      { es: "darle a alguien por", en: "to get into doing something", example: "A mí la primavera me da por hablar más." },
    ],
    dialogue: {
      title: "La pregunta imposible",
      situation: "En el café, el primer jueves de primavera",
      lines: [
        { speaker: "B", es: "Primavera. Empecemos fácil: ¿cómo eres tú?", en: "Spring. Let's start easy: what are you like?" },
        { speaker: "A", es: "Ay, no, no me preguntes cómo soy, pregúntame algo que sepa contestar.", en: "Oh no, don't ask me what I'm like — ask me something I can actually answer." },
        { speaker: "B", es: "Es la pregunta más fácil del mundo.", en: "It's the easiest question in the world." },
        { speaker: "A", es: "Te juro que nunca en mi vida me he descrito en voz alta.", en: "I swear I have never described myself out loud in my life." },
        { speaker: "B", es: "¿Ni en inglés?", en: "Not even in English?" },
        { speaker: "A", es: "Ni en inglés. La verdad es que prefiero contarte una historia antes que decirte quién soy.", en: "Not even in English. Honestly, I'd rather tell you a story than tell you who I am." },
        { speaker: "B", es: "Entonces cuéntame la historia y yo saco la conclusión.", en: "Then tell me the story and I'll draw the conclusion." },
        { speaker: "A", es: "Me da una cosa cuando alguien me pregunta a qué me dedico. Se me va la voz.", en: "It makes me squirm when someone asks me what I do for a living. My voice goes." },
        { speaker: "B", es: "Pues ahorita llevas cuatro frases seguidas. Algo te pasó.", en: "Well, right now you're four sentences in a row. Something happened to you." },
        { speaker: "A", es: "No sé, a mí la primavera me da por hablar más.", en: "I don't know, spring just makes me talk more." },
        { speaker: "B", es: "Perfecto. Esta semana no te describes. Solo reaccionas.", en: "Perfect. This week you don't describe yourself. You just react." },
      ],
    },
  },
  {
    day: 275,
    themeEs: "En el pasillo",
    storyTitle: "Sonar como yo",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la copiadora", en: "the copier", example: "No me digas que la copiadora se dañó otra vez." },
      { es: "dañarse", en: "to break down", example: "Se dañó a primera hora." },
      { es: "la carpeta", en: "the folder", example: "Te juro que tenía esa carpeta en la mano." },
      { es: "la sala de maestros", en: "the staff room", example: "Me gusta más este pasillo que la sala de maestros." },
      { es: "cundir", en: "to be productive, to go a long way", example: "A mí las mañanas me cunden más." },
    ],
    dialogue: {
      title: "Cuatro minutos",
      situation: "En el pasillo del colegio, entre clases",
      lines: [
        { speaker: "B", es: "Marlana. Malas noticias.", en: "Marlana. Bad news." },
        { speaker: "A", es: "Ay, no, no me digas que la copiadora se dañó otra vez.", en: "Oh no, don't tell me the copier broke again." },
        { speaker: "B", es: "A primera hora. ¿Tenías algo para imprimir?", en: "First thing this morning. Did you have something to print?" },
        { speaker: "A", es: "Te juro que tenía esa carpeta en la mano hace dos minutos. Y ahora no está.", en: "I swear I had that folder in my hand two minutes ago. And now it's gone." },
        { speaker: "B", es: "Estás corriendo desde las siete. ¿Comiste algo?", en: "You've been running since seven. Did you eat anything?" },
        { speaker: "A", es: "La verdad es que no he comido desde las siete.", en: "Honestly, I haven't eaten since seven." },
        { speaker: "B", es: "Ay, Marlana.", en: "Oh, Marlana." },
        { speaker: "A", es: "Espérate. Hay alguien esperándome en la puerta del salón.", en: "Hang on. There's someone waiting for me at the classroom door." },
        { speaker: "A", es: "Me da una cosa cuando un estudiante me espera afuera del salón. Siempre es algo.", en: "It gets to me when a student is waiting for me outside the classroom. It's always something." },
        { speaker: "B", es: "Ve. Después hablamos en la sala de maestros.", en: "Go. We'll talk in the staff room later." },
        { speaker: "A", es: "No sé, a mí me gusta más este pasillo que la sala de maestros. Aquí sí hablamos.", en: "I don't know, I like this hallway better than the staff room. Here we actually talk." },
      ],
    },
  },
  {
    day: 276,
    themeEs: "La videollamada",
    storyTitle: "Sonar como yo",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "marcar", en: "to call (someone) on the phone", example: "Te juro que te iba a marcar." },
      { es: "extrañar", en: "to miss (a person/place)", example: "Extraño más el calor que la casa." },
      { es: "pegar", en: "to hit, to land (of a feeling)", example: "A mí los domingos me pegan más." },
      { es: "colgar", en: "to hang up", example: "Me da una cosa colgar y quedarme en silencio." },
      { es: "de fondo", en: "in the background", example: "Se oye la cocina de fondo." },
    ],
    dialogue: {
      title: "Domingo por la noche",
      situation: "Videollamada con mamá en Atlanta",
      lines: [
        { speaker: "B", es: "Mija, ¿supiste que la hija de la vecina se compró casa?", en: "Honey, did you hear the neighbor's daughter bought a house?" },
        { speaker: "A", es: "Ay, no, mamá, no empieces con la hija de la vecina.", en: "Oh no, Mom, don't start with the neighbor's daughter." },
        { speaker: "B", es: "Solo digo. Hace tres semanas que no llamas.", en: "I'm just saying. You haven't called in three weeks." },
        { speaker: "A", es: "Te juro que te iba a marcar, tenía el teléfono en la mano.", en: "I swear I was about to call you — I had the phone in my hand." },
        { speaker: "B", es: "Eso dices siempre. ¿Cómo está el frío por allá?", en: "You always say that. How's the cold up there?" },
        { speaker: "A", es: "La verdad es que extraño más el calor que la casa.", en: "Honestly, I miss the heat more than I miss the house." },
        { speaker: "B", es: "Espérate, déjame bajar la olla. Ya vengo.", en: "Hold on, let me take the pot off. Be right back." },
        { speaker: "A", es: "Me da una cosa cuando te oigo en la cocina detrás del teléfono.", en: "Something happens to me when I hear you in the kitchen behind the phone." },
        { speaker: "B", es: "¿Una cosa buena o mala?", en: "A good something or a bad one?" },
        { speaker: "A", es: "Las dos. No sé, a mí los domingos me pegan más que las fiestas.", en: "Both. I don't know, Sundays hit me harder than the holidays do." },
        { speaker: "B", es: "Entonces llámame los domingos, mija. Para eso estoy.", en: "Then call me on Sundays, honey. That's what I'm here for." },
      ],
    },
  },
  {
    day: 277,
    themeEs: "El código",
    storyTitle: "Sonar como yo",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "pegado con cinta", en: "held together with tape", example: "No mires el código, está pegado con cinta." },
      { es: "funcionar", en: "to work, to run", example: "Anoche a medianoche sí funcionaba." },
      { es: "corregir papeles", en: "to grade papers", example: "Programo después de corregir papeles." },
      { es: "se me hace", en: "it strikes me as, i find it", example: "Se me hace más fácil arreglar un error." },
      { es: "por fin", en: "finally, at last", example: "Algo que hice yo por fin funciona." },
    ],
    dialogue: {
      title: "Once de la noche",
      situation: "Marlana le enseña a Camila lo que construye de noche",
      lines: [
        { speaker: "B", es: "Dijiste que tenías un proyecto. Enséñamelo.", en: "You said you had a project. Show me." },
        { speaker: "A", es: "Ay, no, no mires el código, está pegado con cinta.", en: "Oh no, don't look at the code — it's held together with tape." },
        { speaker: "B", es: "Yo no entiendo código. Solo quiero ver qué hace.", en: "I don't understand code. I just want to see what it does." },
        { speaker: "A", es: "Bueno… mira. Ay. Te juro que anoche a medianoche sí funcionaba.", en: "Okay… look. Ugh. I swear it was working last night at midnight." },
        { speaker: "B", es: "¿Y para qué es? ¿Te lo pidió la escuela?", en: "And what's it for? Did the school ask you for it?" },
        { speaker: "A", es: "La verdad es que construyo estas cosas para no pensar en el colegio.", en: "Honestly, I build these things so I don't have to think about school." },
        { speaker: "B", es: "Eso no me lo esperaba.", en: "I didn't expect that." },
        { speaker: "A", es: "Espera. Mira. Ya. Ahí está.", en: "Wait. Look. There. There it is." },
        { speaker: "A", es: "Me da una cosa cuando algo que hice yo por fin funciona.", en: "I get a feeling when something I made finally works." },
        { speaker: "B", es: "Se te nota en la cara. ¿Y no te cansa, después de todo el día?", en: "It shows on your face. And it doesn't wear you out, after the whole day?" },
        { speaker: "A", es: "No sé, a mí se me hace más fácil arreglar un error que corregir papeles.", en: "I don't know, I find it easier to fix a bug than to grade papers." },
      ],
    },
  },
  {
    day: 278,
    themeEs: "Lo que ve Camila",
    storyTitle: "Sonar como yo",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "para nada", en: "not at all (always last)", example: "Yo no me veo así para nada." },
      { es: "oírtelo decir", en: "to hear you say it", example: "Me da una cosa oírtelo decir en español." },
      { es: "la callada", en: "the quiet one", example: "Siempre me pareció que yo era la callada." },
      { es: "hace años", en: "for years, in years", example: "Nadie me dice eso hace años." },
      { es: "bajar la guardia", en: "to let your guard down", example: "Es difícil bajar la guardia en otro idioma." },
    ],
    dialogue: {
      title: "Lo que yo veo",
      situation: "Camila le devuelve a Marlana lo que ve en ella",
      lines: [
        { speaker: "B", es: "Llevas cuatro días reaccionando a todo. ¿Quieres saber lo que yo veo?", en: "You've spent four days reacting to everything. Want to know what I see?" },
        { speaker: "A", es: "Ay, no, para, que me vas a hacer llorar por un café.", en: "Oh no, stop, you're going to make me cry over a coffee." },
        { speaker: "B", es: "Todavía no he dicho nada. Veo a alguien que hace que la gente se relaje sin darse cuenta.", en: "I haven't said anything yet. I see someone who makes people relax without noticing." },
        { speaker: "A", es: "Te juro que yo no me veo así para nada.", en: "I swear I don't see myself that way at all." },
        { speaker: "B", es: "Ya lo sé. Por eso te lo digo yo.", en: "I know. That's why I'm the one saying it." },
        { speaker: "A", es: "La verdad es que nadie me dice eso hace años.", en: "Honestly, nobody has said that to me in years." },
        { speaker: "B", es: "Pues acostúmbrate, porque lo voy a repetir.", en: "Well, get used to it, because I'm going to say it again." },
        { speaker: "A", es: "Me da una cosa oírtelo decir en español. En inglés no me habría pegado igual.", en: "It does something to me to hear you say it in Spanish. In English it wouldn't have landed the same." },
        { speaker: "B", es: "¿Por qué crees que espero al jueves?", en: "Why do you think I wait for Thursday?" },
        { speaker: "A", es: "No sé, a mí siempre me pareció que yo era la callada de la mesa.", en: "I don't know, I always thought I was the quiet one at the table." },
        { speaker: "B", es: "La callada escucha. Tú escuchas y después contestas. No es lo mismo.", en: "The quiet one listens. You listen and then you answer. Not the same thing." },
      ],
    },
  },
  {
    day: 279,
    themeEs: "Cuando me llevan la contraria",
    storyTitle: "Sonar como yo",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "llevar la contraria", en: "to contradict, to disagree with", example: "Camila me lleva la contraria en voz alta." },
      { es: "seguir pensando", en: "to still think", example: "Yo sigo pensando que tengo razón." },
      { es: "de frente", en: "straight, to your face", example: "Prefiero que me lo digas de frente." },
      { es: "hacer falta", en: "to be needed, to be necessary", example: "No me hace falta que estemos de acuerdo." },
      { es: "delante de otros", en: "in front of other people", example: "Me da una cosa que me corrijan delante de otros." },
    ],
    dialogue: {
      title: "En medio del café",
      situation: "Camila no está de acuerdo y no lo dice bajito",
      lines: [
        { speaker: "B", es: "Yo creo que le diste demasiada libertad a ese grupo y por eso se te fue de las manos.", en: "I think you gave that group too much freedom and that's why it got away from you." },
        { speaker: "A", es: "Ay, no, ahora suenas como mi tía.", en: "Oh no, now you sound like my aunt." },
        { speaker: "B", es: "Tu tía a veces tiene razón. Tú misma lo dijiste en enero.", en: "Your aunt is sometimes right. You said so yourself in January." },
        { speaker: "A", es: "Te juro que eso no fue lo que dije.", en: "I swear that's not what I said." },
        { speaker: "B", es: "Dijiste que la clase estaba descontrolada.", en: "You said the class was out of control." },
        { speaker: "A", es: "Dije que estaba ruidosa. La verdad es que yo sigo pensando que tengo razón.", en: "I said it was loud. Honestly, I still think I'm right." },
        { speaker: "B", es: "Bueno. Yo también.", en: "Fine. So do I." },
        { speaker: "A", es: "Me da una cosa cuando alguien me corrige delante de otros. Pero contigo aguanto.", en: "It gets to me when someone corrects me in front of other people. But with you I can take it." },
        { speaker: "B", es: "¿Aguantas o cedes? Porque no es lo mismo.", en: "You take it or you give in? Because they're not the same." },
        { speaker: "A", es: "Hoy aguanto. No sé, a mí no me hace falta que estemos de acuerdo hoy.", en: "Today I take it. I don't know, I don't need us to agree today." },
        { speaker: "B", es: "Eso. Eso es lo que llevo un año esperando oírte decir.", en: "That. That's what I've spent a year waiting to hear you say." },
      ],
    },
  },
  {
    day: 280,
    themeEs: "Repaso: Cómo reacciono",
    isRecap: true,
    vocab: [
      { es: "la lavandería", en: "the laundromat", example: "Nos encontramos en la lavandería un sábado." },
      { es: "la secadora", en: "the dryer", example: "Llevo cuarenta minutos esperando esa secadora." },
      { es: "el día libre", en: "the day off", example: "¿Tú también vienes en tu día libre?" },
      { es: "doblar", en: "to fold", example: "Yesenia está doblando toallas." },
      { es: "reconocer", en: "to recognize", example: "No te reconocí sin el uniforme." },
    ],
    dialogue: {
      title: "Sábado en la lavandería",
      situation: "Sábado por la mañana — Yesenia está dos máquinas más allá",
      lines: [
        { speaker: "B", es: "¿Maestra? ¿Maestra Marlana?", en: "Teacher? Teacher Marlana?" },
        { speaker: "A", es: "Ay, no, Yesenia, no me digas que tú también vienes a lavar en tu día libre.", en: "Oh no, Yesenia, don't tell me you come do laundry on your day off too." },
        { speaker: "B", es: "El sábado es el único día. ¿Usted también?", en: "Saturday is the only day. You too?" },
        { speaker: "A", es: "Yo también. Te juro que no te reconocí sin el uniforme.", en: "Me too. I swear I didn't recognize you without the uniform." },
        { speaker: "B", es: "Nadie me reconoce. ¿Y cómo va su semana?", en: "Nobody recognizes me. And how's your week going?" },
        { speaker: "A", es: "La verdad es que este es el primer sábado que no trabajo en un mes.", en: "Honestly, this is the first Saturday I haven't worked in a month." },
        { speaker: "B", es: "Uy. Entonces siéntese, que esa secadora tarda.", en: "Wow. Then sit down, that dryer takes a while." },
        { speaker: "A", es: "Me da una cosa encontrarte fuera de la clase.", en: "It does something to me to run into you outside of class." },
        { speaker: "B", es: "¿Buena o mala?", en: "Good or bad?" },
        { speaker: "A", es: "Buena. No sé, a mí me gusta más hablar contigo aquí que en el salón.", en: "Good. I don't know, I like talking to you here better than in the classroom." },
        { speaker: "B", es: "Aquí usted no tiene que enseñarme nada. Por eso.", en: "Here you don't have to teach me anything. That's why." },
      ],
    },
  },
];
