import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 11 — "Conversación larga I" (days 344–350).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week11-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek11SpeakDays: SpeakDay[] = [
  {
    day: 344,
    themeEs: "Cuarenta minutos",
    themeEn: "Forty minutes",
    missionEs: "Practica los cinco puentes: vuelve, retoma, recuerda, no olvides, regresa.",
    missionEn: "Practice the five bridges: return, resume, remember, don't forget, get back.",
    line: "Camila pone el temporizador — cuarenta minutos, sin teléfono, sin inglés.",
    lineEn: "Camila sets the timer — forty minutes, no phone, no English.",
    prompts: [
      {
        id: "d344-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about the hospital — is it still as chaotic?",
        spanish: "Volviendo a lo que dijiste del hospital, ¿sigue igual de caótico?",
        situationLabel: "El primer puente",
        why: "*Volviendo a lo que dijiste* is a bridge, not a topic change — you're picking up their thread, not starting yours.",
        wordHints: [
          { en: "going back to", es: "volviendo a" },
          { en: "what you said", es: "lo que dijiste" },
          { en: "the hospital", es: "del hospital" },
        ],
      },
      {
        id: "d344-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, the meeting started well and ended weird.",
        spanish: "Como te contaba, la reunión empezó bien y terminó raro.",
        situationLabel: "Retomar el hilo",
        why: "*Como te contaba* assumes the other person remembers — and in a long talk, they usually do.",
        wordHints: [
          { en: "as i was telling you", es: "como te contaba" },
          { en: "started well", es: "empezó bien" },
          { en: "ended weird", es: "terminó raro" },
        ],
      },
      {
        id: "d344-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me what happened with Diego's mom.",
        spanish: "Eso me recuerda lo que pasó con la mamá de Diego.",
        situationLabel: "Tangente conectada",
        why: "*Eso me recuerda* opens a side door — useful only if you know how to come back.",
        wordHints: [
          { en: "that reminds me", es: "eso me recuerda" },
          { en: "what happened", es: "lo que pasó" },
          { en: "diego's mom", es: "la mamá de diego" },
        ],
      },
      {
        id: "d344-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Rocío says hi.",
        spanish: "Antes de que se me olvide, Rocío te manda saludos.",
        situationLabel: "Lo pequeño que importa",
        why: "*Antes de que se me olvide* is how small things survive a long conversation — you flag them before they vanish.",
        wordHints: [
          { en: "before i forget", es: "antes de que se me olvide" },
          { en: "says hi", es: "manda saludos" },
        ],
      },
      {
        id: "d344-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — you were saying silence is conversation too.",
        spanish: "Donde íbamos, tú decías que el silencio también es conversación.",
        situationLabel: "Volver al hilo",
        why: "*Donde íbamos* is the gentlest way to end a tangent — no apology, just a hand on the shoulder of the talk.",
        wordHints: [
          { en: "where we were", es: "donde íbamos" },
          { en: "you were saying", es: "tú decías" },
          { en: "silence is conversation too", es: "el silencio también es conversación" },
        ],
      },
    ],
  },
  {
    day: 345,
    themeEs: "Volviendo a lo que dijiste",
    themeEn: "Going back to what you said",
    missionEs: "Responde algo que dijeron hace quince minutos — eso demuestra que escuchaste.",
    missionEn: "Answer something they said fifteen minutes ago — that proves you were listening.",
    line: "Minuto veintitrés — y por fin respondes lo del minuto ocho.",
    lineEn: "Minute twenty-three — and you finally answer what she said at minute eight.",
    prompts: [
      {
        id: "d345-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about tired nurses — that happens at school too.",
        spanish: "Volviendo a lo que dijiste de las enfermeras cansadas, eso pasa en la escuela también.",
        situationLabel: "La respuesta tardía",
        why: "Answering something from fifteen minutes ago proves you were listening the whole time — that's what makes a long talk feel like one thing.",
        wordHints: [
          { en: "tired nurses", es: "enfermeras cansadas" },
          { en: "at school too", es: "en la escuela también" },
        ],
      },
      {
        id: "d345-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, yesterday a teacher asked me for help and I didn't know how to say no.",
        spanish: "Como te contaba, ayer una maestra me pidió ayuda y no supe decir que no.",
        situationLabel: "Antes del callback",
        why: "The school parallel sets up the callback — two workplaces, same exhaustion.",
        wordHints: [
          { en: "a teacher asked me", es: "una maestra me pidió" },
          { en: "i didn't know how to say no", es: "no supe decir que no" },
        ],
      },
      {
        id: "d345-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me what you said about translating when you're tired.",
        spanish: "Eso me recuerda lo que dijiste de traducir cuando estás cansada.",
        situationLabel: "Paralelo",
        why: "Camila's tired nurse opens Marlana's tired teacher — *eso me recuerda* connects them.",
        wordHints: [
          { en: "translating", es: "traducir" },
          { en: "when you're tired", es: "cuando estás cansada" },
        ],
      },
      {
        id: "d345-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — I wrote down your idea about silence in the notebook.",
        spanish: "Antes de que se me olvide, anoté tu idea del silencio en el cuaderno.",
        situationLabel: "Guardando la idea",
        why: "Good ideas in long talks need capturing — *anoté* is the verb for not losing them.",
        wordHints: [
          { en: "i wrote down", es: "anoté" },
          { en: "your idea about silence", es: "tu idea del silencio" },
          { en: "in the notebook", es: "en el cuaderno" },
        ],
      },
      {
        id: "d345-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — we were comparing the hospital and the school.",
        spanish: "Donde íbamos, comparábamos el hospital y la escuela.",
        situationLabel: "El hilo principal",
        why: "After the callback lands, *donde íbamos* keeps the forty minutes moving forward.",
        wordHints: [
          { en: "we were comparing", es: "comparábamos" },
          { en: "the hospital", es: "el hospital" },
          { en: "the school", es: "la escuela" },
        ],
      },
    ],
  },
  {
    day: 346,
    themeEs: "Como te contaba",
    themeEn: "As I was telling you",
    missionEs: "Retoma una historia exactamente donde la dejaste — después de una interrupción.",
    missionEn: "Pick up a story exactly where you left off — after an interruption.",
    line: "Pasa el mesero — y retomas justo donde lo dejaste.",
    lineEn: "The waiter passes — and you pick up exactly where you left off.",
    prompts: [
      {
        id: "d346-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said before the waiter came — yes, the same thing happens to me.",
        spanish: "Volviendo a lo que dijiste antes de que viniera el mesero, sí, me pasa igual.",
        situationLabel: "Después del mesero",
        why: "The callback survives the interruption — proof the talk never actually broke.",
        wordHints: [
          { en: "before the waiter came", es: "antes de que viniera el mesero" },
          { en: "the same thing happens to me", es: "me pasa igual" },
        ],
      },
      {
        id: "d346-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, the mother sat down and I had two versions in my head.",
        spanish: "Como te contaba, la madre se sentó y yo tenía dos versiones en la cabeza.",
        situationLabel: "La reunión retomada",
        why: "*Como te contaba* after an interruption is a fluency test — if you can resume, the talk never broke.",
        wordHints: [
          { en: "the mother sat down", es: "la madre se sentó" },
          { en: "two versions in my head", es: "dos versiones en la cabeza" },
        ],
      },
      {
        id: "d346-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me usted week, when I was rehearsing with Rocío.",
        spanish: "Eso me recuerda la semana de usted, cuando ensayaba con Rocío.",
        situationLabel: "Semana 7",
        why: "Two versions in your head — tú and usted — is Week 7 paying off in a long talk.",
        wordHints: [
          { en: "usted week", es: "la semana de usted" },
          { en: "i was rehearsing", es: "ensayaba" },
        ],
      },
      {
        id: "d346-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Yusuf smiled when I mentioned him.",
        spanish: "Antes de que se me olvide, Yusuf sonrió cuando lo mencioné.",
        situationLabel: "El detalle que importa",
        why: "Conference stories have small wins — *sonrió* is the one worth saving.",
        wordHints: [
          { en: "yusuf smiled", es: "yusuf sonrió" },
          { en: "when i mentioned him", es: "cuando lo mencioné" },
        ],
      },
      {
        id: "d346-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — I was telling the meeting with Yusuf's mom.",
        spanish: "Donde íbamos, yo contaba la reunión con la madre de Yusuf.",
        situationLabel: "Veinticinco minutos",
        why: "*Donde íbamos* after the usted tangent — back to the parent conference, still one conversation.",
        wordHints: [
          { en: "i was telling", es: "yo contaba" },
          { en: "yusuf's mom", es: "la madre de yusuf" },
        ],
      },
    ],
  },
  {
    day: 347,
    themeEs: "Eso me recuerda",
    themeEn: "That reminds me",
    missionEs: "Sigue un tangente — y vuelve con donde íbamos.",
    missionEn: "Follow a tangent — and come back with \"where we were.\"",
    line: "Un tangente que vale la pena abre una puerta que no planeaste.",
    lineEn: "A tangent worth taking opens a door you didn't plan.",
    prompts: [
      {
        id: "d347-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about the woman who translated for her mom — that's Diego again.",
        spanish: "Volviendo a lo que dijiste de la señora que traducía para su mamá, eso es Diego otra vez.",
        situationLabel: "El cierre del tangente",
        why: "The tangent earns its keep when *volviendo a lo que dijiste* ties hospital and school together.",
        wordHints: [
          { en: "the woman who translated", es: "la señora que traducía" },
          { en: "for her mom", es: "para su mamá" },
          { en: "that's diego again", es: "eso es diego otra vez" },
        ],
      },
      {
        id: "d347-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, Diego's mom wanted English only at home.",
        spanish: "Como te contaba, la mamá de Diego quería solo inglés en casa.",
        situationLabel: "Temas grandes, semana 8",
        why: "Week 8's language thread resurfaces naturally in a long talk — that's a callback working.",
        wordHints: [
          { en: "diego's mom", es: "la mamá de diego" },
          { en: "english only at home", es: "solo inglés en casa" },
        ],
      },
      {
        id: "d347-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me Diego's mom and the meeting I never finished.",
        spanish: "Eso me recuerda lo de la mamá de Diego y la reunión que no terminé.",
        situationLabel: "El tangente",
        why: "*Eso me recuerda* is permission to leave the main road — if you come back with *donde íbamos*, the tangent was worth it.",
        wordHints: [
          { en: "diego's mom", es: "la mamá de diego" },
          { en: "the meeting i never finished", es: "la reunión que no terminé" },
        ],
      },
      {
        id: "d347-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — Diego read in both languages this weekend.",
        spanish: "Antes de que se me olvide, Diego leyó en los dos idiomas este fin de semana.",
        situationLabel: "Buena noticia",
        why: "Long talks need good news too — *antes de que se me olvide* saves it from the tangent.",
        wordHints: [
          { en: "diego read", es: "diego leyó" },
          { en: "in both languages", es: "en los dos idiomas" },
          { en: "this weekend", es: "este fin de semana" },
        ],
      },
      {
        id: "d347-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — you were telling the hospital story and I connected it to school.",
        spanish: "Donde íbamos, tú contabas lo del hospital y yo conecté con la escuela.",
        situationLabel: "Diez minutos restantes",
        why: "*Faltaban diez minutos y no se sentía* — the tangent didn't cost time, it added thread.",
        wordHints: [
          { en: "you were telling", es: "tú contabas" },
          { en: "i connected it to school", es: "yo conecté con la escuela" },
        ],
      },
    ],
  },
  {
    day: 348,
    themeEs: "Antes de que se me olvide",
    themeEn: "Before I forget",
    missionEs: "Di tres cosas pequeñas antes de que se pierdan en la charla.",
    missionEn: "Say three small things before they get lost in the talk.",
    line: "Tres cosas que casi pierdes — y el stem que las salva.",
    lineEn: "Three things you almost lost — and the stem that saves them.",
    prompts: [
      {
        id: "d348-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said about me sounding different — I think I know why now.",
        spanish: "Volviendo a lo que dijiste de que sueno distinta, creo que ya sé por qué.",
        situationLabel: "El cumplido tardío",
        why: "Compliments in long talks need answering — even fifteen minutes late.",
        wordHints: [
          { en: "i sound different", es: "sueno distinta" },
          { en: "i think i know why", es: "creo que ya sé por qué" },
        ],
      },
      {
        id: "d348-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, Rocío listened to me talk with a parent and didn't step in.",
        spanish: "Como te contaba, Rocío me escuchó hablar con una madre y no intervino.",
        situationLabel: "Rocío cambió",
        why: "*No intervino* — in otoño Rocío stepped in. That's progress you resume into.",
        wordHints: [
          { en: "rocío listened to me", es: "rocío me escuchó" },
          { en: "didn't step in", es: "no intervino" },
        ],
      },
      {
        id: "d348-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me winter, when I was counting holes.",
        spanish: "Eso me recuerda el invierno, cuando contaba huecos.",
        situationLabel: "Invierno",
        why: "Not interrupting is the inverse of counting holes — same arc, different season.",
        wordHints: [
          { en: "winter", es: "el invierno" },
          { en: "counting holes", es: "contaba huecos" },
        ],
      },
      {
        id: "d348-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — I wanted to tell you this — forty minutes — is the best part of Thursday.",
        spanish: "Antes de que se me olvide, quería decirte que esto — cuarenta minutos — es lo mejor del jueves.",
        situationLabel: "Lo que casi no dijiste",
        why: "In a long talk, the small things die first — names, favors, compliments. *Antes de que se me olvide* is their life raft.",
        wordHints: [
          { en: "i wanted to tell you", es: "quería decirte" },
          { en: "forty minutes", es: "cuarenta minutos" },
          { en: "the best part of thursday", es: "lo mejor del jueves" },
        ],
      },
      {
        id: "d348-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — we were talking about why I sound different.",
        spanish: "Donde íbamos, hablábamos de por qué sueno distinta.",
        situationLabel: "Cinco minutos",
        why: "*Faltaban cinco minutos y no quería que acabara* — the stem that names the feeling.",
        wordHints: [
          { en: "we were talking about", es: "hablábamos de" },
          { en: "why i sound different", es: "por qué sueno distinta" },
        ],
      },
    ],
  },
  {
    day: 349,
    themeEs: "Donde íbamos",
    themeEn: "Where we were",
    missionEs: "Aterriza la conversación — el temporizador sonó y pides dos minutos más.",
    missionEn: "Land the conversation — the timer beeped and you ask for two more minutes.",
    line: "Suena el temporizador — y pides dos minutos para aterrizar.",
    lineEn: "The timer goes off — and you ask for two more minutes to land.",
    prompts: [
      {
        id: "d349-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said at the start — forty minutes don't scare me anymore.",
        spanish: "Volviendo a lo que dijiste al empezar, cuarenta minutos no asustan ya.",
        situationLabel: "Cierre del arco",
        why: "The opening challenge answered at the end — that's how long talks close loops.",
        wordHints: [
          { en: "at the start", es: "al empezar" },
          { en: "don't scare me anymore", es: "no asustan ya" },
        ],
      },
      {
        id: "d349-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you at the start of the year, I wanted to sound like myself.",
        spanish: "Como te contaba al principio del año, quería sonar como yo.",
        situationLabel: "Primavera entera",
        why: "Week 1's goal, resumed at minute thirty-eight — *como te contaba* spans months.",
        wordHints: [
          { en: "at the start of the year", es: "al principio del año" },
          { en: "sound like myself", es: "sonar como yo" },
        ],
      },
      {
        id: "d349-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me a year ago I couldn't hold ten minutes.",
        spanish: "Eso me recuerda que hace un año no podía aguantar diez minutos.",
        situationLabel: "El contraste",
        why: "Forty minutes landed because the year built the scaffolding — name the contrast.",
        wordHints: [
          { en: "a year ago", es: "hace un año" },
          { en: "couldn't hold ten minutes", es: "no podía aguantar diez minutos" },
        ],
      },
      {
        id: "d349-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — thanks for not looking at your phone either.",
        spanish: "Antes de que se me olvide, gracias por no mirar el teléfono tampoco.",
        situationLabel: "Gracias",
        why: "Long talks are mutual — acknowledging Camila's phone discipline closes the ritual.",
        wordHints: [
          { en: "thanks for", es: "gracias por" },
          { en: "not looking at your phone", es: "no mirar el teléfono" },
        ],
      },
      {
        id: "d349-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — we were talking about forty straight minutes — and we did it.",
        spanish: "Donde íbamos, hablábamos de cuarenta minutos seguidos — y los cumplimos.",
        situationLabel: "Aterrizaje",
        why: "*Donde íbamos* at the end of a long talk is how you land — one last thread, tied off.",
        wordHints: [
          { en: "forty straight minutes", es: "cuarenta minutos seguidos" },
          { en: "we did it", es: "los cumplimos" },
        ],
      },
    ],
  },
  {
    day: 350,
    themeEs: "Repaso: Conversación larga I",
    themeEn: "Review: Long conversation I",
    missionEs: "Repasa los cinco puentes — y di qué cambió en cuarenta minutos.",
    missionEn: "Review the five bridges — and say what changed in forty minutes.",
    line: "Cinco puentes, una charla de cuarenta minutos — la arquitectura de quedarse.",
    lineEn: "Five bridges, one forty-minute talk — the architecture of staying in one conversation.",
    prompts: [
      {
        id: "d350-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said all week — forty minutes is training, not luck.",
        spanish: "Volviendo a lo que dijiste toda la semana, cuarenta minutos es entrenamiento, no suerte.",
        situationLabel: "El descubrimiento",
        why: "Long conversation is architecture you practice — the week's whole point.",
        wordHints: [
          { en: "all week", es: "toda la semana" },
          { en: "training, not luck", es: "entrenamiento, no suerte" },
        ],
      },
      {
        id: "d350-como-te-contaba",
        frameStem: "Como te contaba…",
        english: "As I was telling you, resuming is harder than starting — and more useful.",
        spanish: "Como te contaba, retomar es más difícil que empezar — y más útil.",
        situationLabel: "Como te contaba",
        why: "*Como te contaba* assumes the other person is still with you — that's trust in a long talk.",
        wordHints: [
          { en: "resuming", es: "retomar" },
          { en: "harder than starting", es: "más difícil que empezar" },
          { en: "more useful", es: "más útil" },
        ],
      },
      {
        id: "d350-eso-me-recuerda",
        frameStem: "Eso me recuerda…",
        english: "That reminds me Diego, Yesenia, the hospital — all at one table.",
        spanish: "Eso me recuerda Diego, Yesenia, el hospital — todo en una mesa.",
        situationLabel: "Una mesa, todo el año",
        why: "Callbacks across seasons prove the talk is one life, not seven separate lessons.",
        wordHints: [
          { en: "all at one table", es: "todo en una mesa" },
        ],
      },
      {
        id: "d350-antes-de-que",
        frameStem: "Antes de que se me olvide…",
        english: "Before I forget — forty straight minutes was the goal, and it arrived.",
        spanish: "Antes de que se me olvide, cuarenta minutos seguidos fue la meta — y llegó.",
        situationLabel: "La meta",
        why: "Primavera's goal written in temporadas.ts — *llegó* without ceremony, like invierno's subtitles.",
        wordHints: [
          { en: "forty straight minutes", es: "cuarenta minutos seguidos" },
          { en: "was the goal", es: "fue la meta" },
          { en: "it arrived", es: "llegó" },
        ],
      },
      {
        id: "d350-donde-ibamos",
        frameStem: "Donde íbamos…",
        english: "Where we were — we were talking about bridges — and we crossed forty minutes.",
        spanish: "Donde íbamos, hablábamos de puentes — y cruzamos cuarenta minutos.",
        situationLabel: "Repaso final",
        why: "Five stems for long talk I: *volviendo* · *como te contaba* · *eso me recuerda* · *antes de que se me olvide* · *donde íbamos*.",
        wordHints: [
          { en: "we were talking about bridges", es: "hablábamos de puentes" },
          { en: "we crossed forty minutes", es: "cruzamos cuarenta minutos" },
        ],
      },
    ],
  },
];
