import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 1 — "Cómo reacciono" (days 274–280).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week1-frames.ts
 * for the matching `frameStem` (convention 2).
 *
 * Authored English-first. The week's premise: you don't sound like yourself by
 * announcing what you're like — you sound like yourself in how you react.
 * Every prompt is a response to something someone else just said or did.
 */
export const priWeek1SpeakDays: SpeakDay[] = [
  {
    day: 274,
    themeEs: "El primer jueves de primavera",
    themeEn: "The first Thursday of spring",
    missionEs: "Camila te pregunta cómo eres. Reacciona en vez de contestar.",
    missionEn: "Camila asks what you're like. React instead of answering.",
    line: "Camila pregunta cómo eres. Tú pides un café primero.",
    lineEn: "Camila asks what you're like. You ask for a coffee first.",
    prompts: [
      {
        id: "d274-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, don't ask me what I'm like — ask me something I can actually answer.",
        spanish: "Ay, no, no me preguntes cómo soy, pregúntame algo que sepa contestar.",
        situationLabel: "Primer jueves de primavera",
        why: "*Ay, no* is protest and affection at once. The tone does everything — the words barely matter.",
        wordHints: [
          { en: "don't ask me", es: "no me preguntes" },
          { en: "what i'm like", es: "cómo soy" },
          { en: "i know how to answer", es: "sepa contestar" },
        ],
      },
      {
        id: "d274-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear I have never described myself out loud in my life.",
        spanish: "Te juro que nunca en mi vida me he descrito en voz alta.",
        situationLabel: "La pregunta imposible",
        why: "*Te juro que…* is everyday emphasis, not an oath — you'll hear it four times in one conversation.",
        wordHints: [
          { en: "i swear", es: "te juro" },
          { en: "never in my life", es: "nunca en mi vida" },
          { en: "described myself", es: "me he descrito" },
        ],
      },
      {
        id: "d274-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I'd rather tell you a story than tell you who I am.",
        spanish: "La verdad es que prefiero contarte una historia antes que decirte quién soy.",
        situationLabel: "Cambiando de táctica",
        why: "*La verdad es que…* is the switch from the polite answer to the real one — and it buys you a second to think.",
        wordHints: [
          { en: "honestly", es: "la verdad es que" },
          { en: "i'd rather", es: "prefiero" },
          { en: "rather than", es: "antes que" },
        ],
      },
      {
        id: "d274-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "It makes me squirm when someone asks me what I do for a living.",
        spanish: "Me da una cosa cuando alguien me pregunta a qué me dedico.",
        situationLabel: "La pregunta del trabajo",
        why: "*Me da una cosa* names a feeling by refusing to name it. There's no clean English for it, which is exactly why it's worth owning.",
        wordHints: [
          { en: "it makes me squirm", es: "me da una cosa" },
          { en: "what i do for a living", es: "a qué me dedico" },
        ],
      },
      {
        id: "d274-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, spring just makes me talk more.",
        spanish: "No sé, a mí la primavera me da por hablar más.",
        situationLabel: "Sin querer, una respuesta",
        why: "*Darle a alguien por* + infinitive — to get into doing something. And *no sé* up front means you're not claiming to be right.",
        wordHints: [
          { en: "i don't know", es: "no sé" },
          { en: "makes me", es: "me da por" },
          { en: "talk more", es: "hablar más" },
        ],
      },
    ],
  },
  {
    day: 275,
    themeEs: "En el pasillo",
    themeEn: "In the hallway",
    missionEs: "Cuatro minutos entre clases. Reacciona rápido, sin pensarlo.",
    missionEn: "Four minutes between classes. React fast, without thinking about it.",
    line: "Cuatro minutos entre clases y Rocío tiene noticias de la copiadora.",
    lineEn: "Four minutes between classes and Rocío has news about the copier.",
    prompts: [
      {
        id: "d275-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, don't tell me the copier broke again.",
        spanish: "Ay, no, no me digas que la copiadora se dañó otra vez.",
        situationLabel: "Junto a la copiadora",
        why: "*No me digas que…* follows *Ay, no* about half the time — pair them and you sound like you've worked there for years.",
        wordHints: [
          { en: "don't tell me", es: "no me digas" },
          { en: "the copier", es: "la copiadora" },
          { en: "broke", es: "se dañó" },
        ],
      },
      {
        id: "d275-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear I had that folder in my hand two minutes ago.",
        spanish: "Te juro que tenía esa carpeta en la mano hace dos minutos.",
        situationLabel: "La carpeta que desapareció",
        why: "Imperfect *tenía* for a state that was true right up until things went wrong.",
        wordHints: [
          { en: "i had", es: "tenía" },
          { en: "that folder", es: "esa carpeta" },
          { en: "two minutes ago", es: "hace dos minutos" },
        ],
      },
      {
        id: "d275-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I haven't eaten since seven.",
        spanish: "La verdad es que no he comido desde las siete.",
        situationLabel: "Cuando te preguntan cómo vas",
        why: "The honest answer to \"how's your day\" is usually one flat fact. Give that instead of *bien*.",
        wordHints: [
          { en: "i haven't eaten", es: "no he comido" },
          { en: "since seven", es: "desde las siete" },
        ],
      },
      {
        id: "d275-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "It gets to me when a student is waiting for me outside the classroom.",
        spanish: "Me da una cosa cuando un estudiante me espera afuera del salón.",
        situationLabel: "El que espera en la puerta",
        why: "Same stem as yesterday's dread, opposite feeling — *una cosa* covers the whole range and context sorts it out.",
        wordHints: [
          { en: "it gets to me", es: "me da una cosa" },
          { en: "is waiting for me", es: "me espera" },
          { en: "outside the classroom", es: "afuera del salón" },
        ],
      },
      {
        id: "d275-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, I like this hallway better than the staff room.",
        spanish: "No sé, a mí me gusta más este pasillo que la sala de maestros.",
        situationLabel: "Por qué siempre hablan aquí",
        why: "A small honest preference, offered without an argument attached. That's the whole job of this stem.",
        wordHints: [
          { en: "i like better", es: "me gusta más" },
          { en: "this hallway", es: "este pasillo" },
          { en: "the staff room", es: "la sala de maestros" },
        ],
      },
    ],
  },
  {
    day: 276,
    themeEs: "La videollamada",
    themeEn: "The video call",
    missionEs: "Domingo por la noche con mamá. Reacciona como hija, no como maestra.",
    missionEn: "Sunday night with Mom. React like a daughter, not like a teacher.",
    line: "Domingo, Atlanta en la pantalla, y mamá empieza con la hija de la vecina.",
    lineEn: "Sunday, Atlanta on the screen, and Mom opens with the neighbor's daughter.",
    prompts: [
      {
        id: "d276-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, Mom, don't start with the neighbor's daughter.",
        spanish: "Ay, no, mamá, no empieces con la hija de la vecina.",
        situationLabel: "El clásico de mamá",
        why: "Dropping *mamá* into the middle is what makes it affectionate instead of sharp.",
        wordHints: [
          { en: "don't start", es: "no empieces" },
          { en: "the neighbor's daughter", es: "la hija de la vecina" },
        ],
      },
      {
        id: "d276-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear I was about to call you — I had the phone in my hand.",
        spanish: "Te juro que te iba a marcar, tenía el teléfono en la mano.",
        situationLabel: "La excusa que sí es verdad",
        why: "*Marcar* is the ordinary Latin American verb for calling someone — and *iba a* is the imperfect of good intentions.",
        wordHints: [
          { en: "i was about to call you", es: "te iba a marcar" },
          { en: "i had", es: "tenía" },
          { en: "in my hand", es: "en la mano" },
        ],
      },
      {
        id: "d276-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I miss the heat more than I miss the house.",
        spanish: "La verdad es que extraño más el calor que la casa.",
        situationLabel: "Lo que de verdad extrañas",
        why: "The unexpected half of a comparison is where the honesty actually lands.",
        wordHints: [
          { en: "i miss", es: "extraño" },
          { en: "the heat", es: "el calor" },
          { en: "more than", es: "más que" },
        ],
      },
      {
        id: "d276-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "Something happens to me when I hear you in the kitchen behind the phone.",
        spanish: "Me da una cosa cuando te oigo en la cocina detrás del teléfono.",
        situationLabel: "El ruido de fondo",
        why: "\"Something happens to me\" is as close as English gets — and it's still not it.",
        wordHints: [
          { en: "i hear you", es: "te oigo" },
          { en: "in the kitchen", es: "en la cocina" },
          { en: "behind the phone", es: "detrás del teléfono" },
        ],
      },
      {
        id: "d276-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, Sundays hit me harder than the holidays do.",
        spanish: "No sé, a mí los domingos me pegan más que las fiestas.",
        situationLabel: "Por qué los domingos",
        why: "*Pegar* here isn't hitting — it's the way a feeling lands on you. Common, and entirely idiomatic.",
        wordHints: [
          { en: "sundays", es: "los domingos" },
          { en: "hit me harder", es: "me pegan más" },
          { en: "the holidays", es: "las fiestas" },
        ],
      },
    ],
  },
  {
    day: 277,
    themeEs: "El código",
    themeEn: "The code",
    missionEs: "Camila quiere ver tu proyecto. Reacciona antes de enseñárselo.",
    missionEn: "Camila wants to see your project. React before you show her.",
    line: "Once de la noche, la cosa que construiste, y Camila quiere verla.",
    lineEn: "Eleven at night, the thing you built, and Camila wants to see it.",
    prompts: [
      {
        id: "d277-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, don't look at the code — it's held together with tape.",
        spanish: "Ay, no, no mires el código, está pegado con cinta.",
        situationLabel: "Antes de enseñarlo",
        why: "*Pegado con cinta* — taped together. The image survives the trip between languages, which is rarer than you'd think.",
        wordHints: [
          { en: "don't look at", es: "no mires" },
          { en: "held together with tape", es: "pegado con cinta" },
        ],
      },
      {
        id: "d277-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear it was working last night at midnight.",
        spanish: "Te juro que anoche a medianoche sí funcionaba.",
        situationLabel: "La defensa de siempre",
        why: "That emphatic *sí* before the verb does the work of an italic — *it WAS working*.",
        wordHints: [
          { en: "last night", es: "anoche" },
          { en: "at midnight", es: "a medianoche" },
          { en: "it was working", es: "sí funcionaba" },
        ],
      },
      {
        id: "d277-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I build these things so I don't have to think about school.",
        spanish: "La verdad es que construyo estas cosas para no pensar en el colegio.",
        situationLabel: "El motivo de verdad",
        why: "*Para no* + infinitive — the cleanest way to say what you're avoiding.",
        wordHints: [
          { en: "i build", es: "construyo" },
          { en: "so i don't have to think about", es: "para no pensar en" },
        ],
      },
      {
        id: "d277-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "I get a feeling when something I made finally works.",
        spanish: "Me da una cosa cuando algo que hice yo por fin funciona.",
        situationLabel: "Cuando por fin corre",
        why: "*Que hice yo* — the *yo* is grammatically unnecessary and that's the point. It's what makes it yours.",
        wordHints: [
          { en: "something i made", es: "algo que hice yo" },
          { en: "finally", es: "por fin" },
          { en: "works", es: "funciona" },
        ],
      },
      {
        id: "d277-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, I find it easier to fix a bug than to grade papers.",
        spanish: "No sé, a mí se me hace más fácil arreglar un error que corregir papeles.",
        situationLabel: "Las dos mitades de tu vida",
        why: "*Se me hace* — how something strikes you. Different from *es*, and much more spoken.",
        wordHints: [
          { en: "i find it easier", es: "se me hace más fácil" },
          { en: "fix a bug", es: "arreglar un error" },
          { en: "grade papers", es: "corregir papeles" },
        ],
      },
    ],
  },
  {
    day: 278,
    themeEs: "Lo que ve Camila",
    themeEn: "What Camila sees",
    missionEs: "Camila te describe a ti. Tú solo puedes reaccionar.",
    missionEn: "Camila describes you. All you can do is react.",
    line: "Camila te describe en voz alta. Te toca quedarte sentada y aguantarlo.",
    lineEn: "Camila describes you out loud. Your job is to sit there and take it.",
    prompts: [
      {
        id: "d278-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, stop, you're going to make me cry over a coffee.",
        spanish: "Ay, no, para, que me vas a hacer llorar por un café.",
        situationLabel: "Cuando dice algo bonito",
        why: "That *que* after the comma is a spoken *because* — it links the protest to the reason without weighing anything down.",
        wordHints: [
          { en: "stop", es: "para" },
          { en: "you're going to make me cry", es: "me vas a hacer llorar" },
        ],
      },
      {
        id: "d278-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear I don't see myself that way at all.",
        spanish: "Te juro que yo no me veo así para nada.",
        situationLabel: "No estás de acuerdo",
        why: "*Para nada* at the end is the emphatic *not at all* — and it always goes last.",
        wordHints: [
          { en: "i don't see myself", es: "yo no me veo" },
          { en: "that way", es: "así" },
          { en: "at all", es: "para nada" },
        ],
      },
      {
        id: "d278-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, nobody has said that to me in years.",
        spanish: "La verdad es que nadie me dice eso hace años.",
        situationLabel: "Bajando la guardia",
        why: "Present tense with *hace años* — Spanish keeps it in the present because the silence is still going on.",
        wordHints: [
          { en: "nobody says that to me", es: "nadie me dice eso" },
          { en: "in years", es: "hace años" },
        ],
      },
      {
        id: "d278-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "It does something to me to hear you say it in Spanish.",
        spanish: "Me da una cosa oírtelo decir en español.",
        situationLabel: "En español pega distinto",
        why: "*Oírtelo decir* — three pronouns fused onto one infinitive. Say it a few times and it stops looking impossible.",
        wordHints: [
          { en: "to hear you say it", es: "oírtelo decir" },
          { en: "in spanish", es: "en español" },
        ],
      },
      {
        id: "d278-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, I always thought I was the quiet one at the table.",
        spanish: "No sé, a mí siempre me pareció que yo era la callada de la mesa.",
        situationLabel: "Tu propia versión de ti",
        why: "*Me pareció* — how it seemed to you. You can disagree with a compliment without rejecting it.",
        wordHints: [
          { en: "i always thought", es: "siempre me pareció" },
          { en: "the quiet one", es: "la callada" },
          { en: "at the table", es: "de la mesa" },
        ],
      },
    ],
  },
  {
    day: 279,
    themeEs: "Cuando me llevan la contraria",
    themeEn: "When someone contradicts me",
    missionEs: "Camila no está de acuerdo. Reacciona y quédate.",
    missionEn: "Camila disagrees. React, and stay in it.",
    line: "Camila no está de acuerdo, en voz alta, en medio del café.",
    lineEn: "Camila disagrees, out loud, in the middle of the café.",
    prompts: [
      {
        id: "d279-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, now you sound like my aunt.",
        spanish: "Ay, no, ahora suenas como mi tía.",
        situationLabel: "Empujando de vuelta",
        why: "Pushing back with a joke is still pushing back — and it keeps the table warm.",
        wordHints: [
          { en: "now", es: "ahora" },
          { en: "you sound like", es: "suenas como" },
          { en: "my aunt", es: "mi tía" },
        ],
      },
      {
        id: "d279-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear that's not what I said.",
        spanish: "Te juro que eso no fue lo que dije.",
        situationLabel: "Corrigiendo el registro",
        why: "*Eso no fue lo que dije* puts the weight on *what*, not on *I* — less accusatory, more precise.",
        wordHints: [
          { en: "that's not", es: "eso no fue" },
          { en: "what i said", es: "lo que dije" },
        ],
      },
      {
        id: "d279-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, I still think I'm right.",
        spanish: "La verdad es que yo sigo pensando que tengo razón.",
        situationLabel: "Sin ceder",
        why: "*Sigo pensando* — I'm still thinking it. The most useful way to hold a position without escalating.",
        wordHints: [
          { en: "i still think", es: "yo sigo pensando" },
          { en: "i'm right", es: "tengo razón" },
        ],
      },
      {
        id: "d279-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "It gets to me when someone corrects me in front of other people.",
        spanish: "Me da una cosa cuando alguien me corrige delante de otros.",
        situationLabel: "Nombrando lo que te cuesta",
        why: "Naming the discomfort out loud is not the same as apologizing for it.",
        wordHints: [
          { en: "corrects me", es: "me corrige" },
          { en: "in front of", es: "delante de" },
          { en: "other people", es: "otros" },
        ],
      },
      {
        id: "d279-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, I don't need us to agree today.",
        spanish: "No sé, a mí no me hace falta que estemos de acuerdo hoy.",
        situationLabel: "Dejándolo abierto",
        why: "*Hacer falta* + subjunctive — you can end a disagreement without either person losing it.",
        wordHints: [
          { en: "i don't need", es: "no me hace falta" },
          { en: "us to agree", es: "que estemos de acuerdo" },
        ],
      },
    ],
  },
  {
    day: 280,
    themeEs: "Repaso: Cómo reacciono",
    themeEn: "Review: How I react",
    missionEs: "Las mismas cinco reacciones, en la lavandería, sin avisar.",
    missionEn: "The same five reactions, at the laundromat, with no warning.",
    line: "Sábado en la lavandería. Yesenia está doblando toallas dos máquinas más allá.",
    lineEn: "Saturday at the laundromat. Yesenia is folding towels two machines down.",
    prompts: [
      {
        id: "d280-ay-no",
        frameStem: "Ay, no…",
        english: "Oh no, Yesenia, don't tell me you come do laundry on your day off too.",
        spanish: "Ay, no, Yesenia, no me digas que tú también vienes a lavar en tu día libre.",
        situationLabel: "Encontrarse un sábado",
        why: "Running into someone is the most reliable source of real reactions there is — nobody rehearses for it.",
        wordHints: [
          { en: "you too", es: "tú también" },
          { en: "come do laundry", es: "vienes a lavar" },
          { en: "on your day off", es: "en tu día libre" },
        ],
      },
      {
        id: "d280-te-juro-que",
        frameStem: "Te juro que…",
        english: "I swear I didn't recognize you without the uniform.",
        spanish: "Te juro que no te reconocí sin el uniforme.",
        situationLabel: "Sin el uniforme",
        why: "Preterite *reconocí* — one completed moment, the second you looked up.",
        wordHints: [
          { en: "i didn't recognize you", es: "no te reconocí" },
          { en: "without the uniform", es: "sin el uniforme" },
        ],
      },
      {
        id: "d280-la-verdad-es-que",
        frameStem: "La verdad es que…",
        english: "Honestly, this is the first Saturday I haven't worked in a month.",
        spanish: "La verdad es que este es el primer sábado que no trabajo en un mes.",
        situationLabel: "Cómo va el mes",
        why: "She asked how you're doing. Give her the real number instead of *bien*.",
        wordHints: [
          { en: "the first saturday", es: "el primer sábado" },
          { en: "i haven't worked", es: "no trabajo" },
          { en: "in a month", es: "en un mes" },
        ],
      },
      {
        id: "d280-me-da-una-cosa",
        frameStem: "Me da una cosa…",
        english: "It does something to me to run into you outside of class.",
        spanish: "Me da una cosa encontrarte fuera de la clase.",
        situationLabel: "Los dos mundos se tocan",
        why: "The bare infinitive after *me da una cosa* is tighter than *cuando…* — use it when the thing is happening right now.",
        wordHints: [
          { en: "to run into you", es: "encontrarte" },
          { en: "outside of class", es: "fuera de la clase" },
        ],
      },
      {
        id: "d280-no-se-a-mi",
        frameStem: "No sé, a mí…",
        english: "I don't know, I like talking to you here better than in the classroom.",
        spanish: "No sé, a mí me gusta más hablar contigo aquí que en el salón.",
        situationLabel: "Sin la silla de la clase",
        why: "Said to a student, off the clock, in her language. That's the whole week in one sentence.",
        wordHints: [
          { en: "i like better", es: "me gusta más" },
          { en: "talking to you", es: "hablar contigo" },
          { en: "in the classroom", es: "en el salón" },
        ],
      },
    ],
  },
];
