import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 13 — "El año entero" (days 358–364). The year capstone.
 * Each `spanish` is copied verbatim from content/drafts/primavera/week13-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek13SpeakDays: SpeakDay[] = [
  {
    day: 358,
    themeEs: "La última semana",
    themeEn: "The last week",
    missionEs: "Habla del año entero, en presente.",
    missionEn: "Talk about the whole year, in the present.",
    line: "Hace un año no sabías llenar un silencio. Quedan siete días.",
    lineEn: "A year ago you couldn't fill a silence. Seven days left.",
    prompts: [
      {
        id: "d358-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who's been speaking every day for a year.",
        spanish: "Soy de las que llevan un año hablando todos los días.",
        situationLabel: "Lunes de la última semana",
        why: "Three hundred and sixty-four days ago *soy de las que…* was a grammar exercise. Now it's a self-portrait — which is what week 1 was for.",
        wordHints: [
          { en: "a year", es: "un año" },
          { en: "speaking every day", es: "hablando todos los días" },
        ],
      },
      {
        id: "d358-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — don't cry yet.",
        spanish: "Te estoy tomando el pelo, no llores todavía.",
        situationLabel: "Antes de que se ponga sentimental",
        why: "Week 2's safety line, still doing its job on day three hundred and fifty-eight — say you're joking before the room gets heavy.",
        wordHints: [
          { en: "don't cry yet", es: "no llores todavía" },
        ],
      },
      {
        id: "d358-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but I don't want this week to fly by.",
        spanish: "Entiendo tu punto, pero no quiero que esta semana se me pase volando.",
        situationLabel: "Frenando el final",
        why: "Week 5's credit-first disagreement — you heard Camila, and you're still pushing back gently.",
        wordHints: [
          { en: "this week", es: "esta semana" },
          { en: "fly by", es: "se me pase volando" },
        ],
      },
      {
        id: "d358-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is that I started without believing it.",
        spanish: "Lo primero que se me ocurre es que empecé sin creérmelo.",
        situationLabel: "Sin preparación",
        why: "Week 10's cold prompt — no essay, no edit. The first thing is usually the truest.",
        wordHints: [
          { en: "i started", es: "empecé" },
          { en: "without believing it", es: "sin creérmelo" },
        ],
      },
      {
        id: "d358-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said in March: sounding natural wasn't the end.",
        spanish: "Volviendo a lo que dijiste en marzo: sonar natural no era el final.",
        situationLabel: "El hilo del invierno",
        why: "Week 11's callback — *volviendo a lo que dijiste* pulls a thread from months ago and keeps the conversation alive.",
        wordHints: [
          { en: "going back to", es: "volviendo a" },
          { en: "in march", es: "en marzo" },
          { en: "wasn't the end", es: "no era el final" },
        ],
      },
    ],
  },
  {
    day: 359,
    themeEs: "Hace un año",
    themeEn: "A year ago",
    missionEs: "Escucha quién eras en junio y descríbelo sin ser cruel.",
    missionEn: "Listen to who you were in June and describe her without being cruel.",
    line: "Día uno, grabado en junio. Lo guardaste para esto.",
    lineEn: "Day one, recorded in June. You kept it for this.",
    prompts: [
      {
        id: "d359-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who doesn't recognize her June voice anymore.",
        spanish: "Soy de las que ya no reconocen su voz de junio.",
        situationLabel: "Después del audio",
        why: "*Hace un año no podía…* is the sentence this day is built around. Listen first, then name what changed.",
        wordHints: [
          { en: "don't recognize anymore", es: "ya no reconocen" },
          { en: "june voice", es: "voz de junio" },
        ],
      },
      {
        id: "d359-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — well, yes, it really was that bad.",
        spanish: "Te estoy tomando el pelo — bueno, sí era tan horrible.",
        situationLabel: "La reacción honesta",
        why: "The tease that gives up halfway — week 2 learned you can soften and still tell the truth.",
        wordHints: [
          { en: "it really was", es: "sí era" },
          { en: "that bad", es: "tan horrible" },
        ],
      },
      {
        id: "d359-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but a year ago I couldn't order a coffee.",
        spanish: "Entiendo tu punto, pero hace un año no podía pedir un café.",
        situationLabel: "Hace un año no podía…",
        why: "The year retrospective in one line — credit first, then the gap that actually matters.",
        wordHints: [
          { en: "a year ago", es: "hace un año" },
          { en: "couldn't order", es: "no podía pedir" },
          { en: "a coffee", es: "un café" },
        ],
      },
      {
        id: "d359-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is that I was afraid of the pause.",
        spanish: "Lo primero que se me ocurre es que tenía miedo de la pausa.",
        situationLabel: "El diagnóstico de junio",
        why: "Cold and immediate — the pause was the enemy before it became just breathing.",
        wordHints: [
          { en: "i was afraid", es: "tenía miedo" },
          { en: "the pause", es: "la pausa" },
        ],
      },
      {
        id: "d359-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said in winter: keep the first one.",
        spanish: "Volviendo a lo que dijiste en invierno: guarda el primero.",
        situationLabel: "Camila tenía razón",
        why: "Two recordings, twelve months apart — week 11's callback makes the comparison possible.",
        wordHints: [
          { en: "in winter", es: "en invierno" },
          { en: "keep the first one", es: "guarda el primero" },
        ],
      },
    ],
  },
  {
    day: 360,
    themeEs: "Lo que cambió",
    themeEn: "What changed",
    missionEs: "Explica el cambio sin decir \"mejoré\".",
    missionEn: "Explain the change without saying \"I got better\".",
    line: "\"Mejoré\" no explica nada y no se puede repetir.",
    lineEn: "\"I got better\" explains nothing and can't be repeated.",
    prompts: [
      {
        id: "d360-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who speaks every day, a little, for a whole year.",
        spanish: "Soy de las que hablan todos los días, poquito, un año entero.",
        situationLabel: "El inventario honesto",
        why: "\"I got better\" explains nothing. Four seasons, one mechanism: show up, say five sentences, keep the Thursday.",
        wordHints: [
          { en: "every day", es: "todos los días" },
          { en: "a little", es: "poquito" },
          { en: "a whole year", es: "un año entero" },
        ],
      },
      {
        id: "d360-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — well, no, it wasn't talent.",
        spanish: "Te estoy tomando el pelo — bueno, no, no fue talento.",
        situationLabel: "Corrigiendo el cumplido",
        why: "The tease that refuses the compliment — interrupting *don* before it sticks.",
        wordHints: [
          { en: "it wasn't", es: "no fue" },
          { en: "talent", es: "talento" },
        ],
      },
      {
        id: "d360-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but winter wasn't about grammar — it was about not braking.",
        spanish: "Entiendo tu punto, pero invierno no fue gramática, fue dejar de frenar.",
        situationLabel: "Cuatro temporadas",
        why: "Each season had a job. Naming them precisely is what lets someone else copy the method.",
        wordHints: [
          { en: "wasn't about", es: "no fue" },
          { en: "grammar", es: "gramática" },
          { en: "not braking", es: "dejar de frenar" },
        ],
      },
      {
        id: "d360-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is that the fear of the pause is gone.",
        spanish: "Lo primero que se me ocurre es que el miedo a la pausa se fue.",
        situationLabel: "La conclusión repetible",
        why: "Zero prep, maximum precision — the thing you can say again in a year.",
        wordHints: [
          { en: "fear of the pause", es: "miedo a la pausa" },
          { en: "is gone", es: "se fue" },
        ],
      },
      {
        id: "d360-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said last week: it already sounds like you.",
        spanish: "Volviendo a lo que dijiste la semana pasada: ya suena a ti.",
        situationLabel: "Desde afuera",
        why: "Someone who watched the year can name the change in four words. You needed the callback to hear it.",
        wordHints: [
          { en: "last week", es: "la semana pasada" },
          { en: "already sounds like you", es: "ya suena a ti" },
        ],
      },
    ],
  },
  {
    day: 361,
    themeEs: "La mesa entera",
    themeEn: "The whole table",
    missionEs: "Presenta a todos y sostén la conversación entre las cuatro.",
    missionEn: "Introduce everyone and hold a conversation among four.",
    line: "Cuatro personas, un idioma, un año.",
    lineEn: "Four people, one language, one year.",
    prompts: [
      {
        id: "d361-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who brought someone new to the café every season.",
        spanish: "Soy de las que trajeron a alguien nuevo al café cada temporada.",
        situationLabel: "Presentando la mesa",
        why: "Yesenia arrived in winter. Rocío was always there. The table grew because Marlana kept showing up.",
        wordHints: [
          { en: "brought someone new", es: "trajeron a alguien nuevo" },
          { en: "every season", es: "cada temporada" },
        ],
      },
      {
        id: "d361-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Yesenia — I didn't plan any of these Thursdays.",
        spanish: "Te estoy tomando el pelo, Yesenia, no planifiqué ninguno de estos jueves.",
        situationLabel: "La versión humilde",
        why: "The origin story doesn't need myth — week 2's humor keeps Yesenia from thinking it's out of reach.",
        wordHints: [
          { en: "didn't plan", es: "no planifiqué" },
          { en: "these thursdays", es: "estos jueves" },
        ],
      },
      {
        id: "d361-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but a year ago I didn't believe it was possible either.",
        spanish: "Entiendo tu punto, pero hace un año yo tampoco creía que fuera posible.",
        situationLabel: "Quitándole la vergüenza",
        why: "Yesenia's disbelief gets credit — and then the honest counter from someone who had it too.",
        wordHints: [
          { en: "a year ago", es: "hace un año" },
          { en: "didn't believe either", es: "tampoco creía" },
        ],
      },
      {
        id: "d361-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is: five sentences a day, nothing more.",
        spanish: "Lo primero que se me ocurre es: cinco frases al día, nada más.",
        situationLabel: "El consejo sin discurso",
        why: "Week 10's cold answer is the best advice — because it sounds like a person, not a method.",
        wordHints: [
          { en: "five sentences", es: "cinco frases" },
          { en: "a day", es: "al día" },
          { en: "nothing more", es: "nada más" },
        ],
      },
      {
        id: "d361-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said: it isn't the English that worries you, it's the embarrassment.",
        spanish: "Volviendo a lo que dijiste: no te preocupa el inglés, te preocupa la pena.",
        situationLabel: "Reconociéndolo desde dentro",
        why: "Invierno day 270's insight, called back with week 11's bridge — you can name it because you had it.",
        wordHints: [
          { en: "doesn't worry you", es: "no te preocupa" },
          { en: "the embarrassment", es: "la pena" },
        ],
      },
    ],
  },
  {
    day: 362,
    themeEs: "Lo que me llevo",
    themeEn: "What I'm taking with me",
    missionEs: "Nombra lo que te llevas de cada temporada.",
    missionEn: "Name what you're taking from each season.",
    line: "Cuatro temporadas, cuatro frases — y una cosa que las atraviesa.",
    lineEn: "Four seasons, four sentences — and one thing that runs through all of them.",
    prompts: [
      {
        id: "d362-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who can have a long conversation without preparing it.",
        spanish: "Soy de las que pueden tener una conversación larga sin prepararla.",
        situationLabel: "Retrato de fin de año",
        why: "Primavera's thesis in one stem — not level, not accent, conversation as yourself.",
        wordHints: [
          { en: "long conversation", es: "conversación larga" },
          { en: "without preparing", es: "sin prepararla" },
        ],
      },
      {
        id: "d362-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you — I'm not going to cry. Well, maybe a little.",
        spanish: "Te estoy tomando el pelo, no voy a llorar — bueno, tal vez un poco.",
        situationLabel: "Antes de lo sentimental",
        why: "Humor as deflector, still — and the honest crack in the middle.",
        wordHints: [
          { en: "i'm not going to cry", es: "no voy a llorar" },
          { en: "maybe a little", es: "tal vez un poco" },
        ],
      },
      {
        id: "d362-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but the year doesn't end in perfect.",
        spanish: "Entiendo tu punto, pero el año no acaba en perfecto.",
        situationLabel: "El hueco que queda",
        why: "Credit first, then the honest gap — you still shrink sometimes, and that's fine.",
        wordHints: [
          { en: "doesn't end", es: "no acaba" },
          { en: "in perfect", es: "en perfecto" },
        ],
      },
      {
        id: "d362-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind about spring is: I sound like me.",
        spanish: "Lo primero que se me ocurre de primavera es: sueno como yo.",
        situationLabel: "Primavera, en una frase",
        why: "Cold prompt as season summary — *sueno como yo* is the whole spring arc in four words.",
        wordHints: [
          { en: "about spring", es: "de primavera" },
          { en: "i sound like me", es: "sueno como yo" },
        ],
      },
      {
        id: "d362-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said: speaking is a habit, not a talent.",
        spanish: "Volviendo a lo que dijiste: hablar es un hábito, no un talento.",
        situationLabel: "El hilo del año",
        why: "Invierno day 273's sentence, called back — the through-line that survived four seasons.",
        wordHints: [
          { en: "speaking", es: "hablar" },
          { en: "a habit", es: "un hábito" },
          { en: "a talent", es: "un talento" },
        ],
      },
    ],
  },
  {
    day: 363,
    themeEs: "Una conversación entera",
    themeEn: "A whole conversation",
    missionEs: "Las cinco frases de hoy son una sola conversación. Dilas seguidas.",
    missionEn: "Today's five sentences are one conversation. Say them as one stretch.",
    line: "Dos horas, cuatro personas, un idioma.",
    lineEn: "Two hours, four people, one language.",
    prompts: [
      {
        id: "d363-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who counts the year in Thursdays, not months.",
        spanish: "Soy de las que cuentan el año en jueves, no en meses.",
        situationLabel: "Beat 1 — abriendo la historia",
        why: "Today's five prompts are the beats of one conversation, in order. Say them as a single stretch, not as five exercises.",
        wordHints: [
          { en: "count the year", es: "cuentan el año" },
          { en: "in thursdays", es: "en jueves" },
          { en: "not months", es: "no en meses" },
        ],
      },
      {
        id: "d363-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you, Camila — you weren't the teacher, you were the table.",
        spanish: "Te estoy tomando el pelo, Camila, no fuiste la profesora — fuiste la mesa.",
        situationLabel: "Beat 2 — una broma en medio",
        why: "Week 2 in the middle of week 11's long talk — humor keeps two hours from turning into a speech.",
        wordHints: [
          { en: "you weren't the teacher", es: "no fuiste la profesora" },
          { en: "you were the table", es: "fuiste la mesa" },
        ],
      },
      {
        id: "d363-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but half of that story is missing.",
        spanish: "Entiendo tu punto, pero falta la mitad de esa historia.",
        situationLabel: "Beat 3 — entrando cuando habla otra",
        why: "Week 5's gentle correction mid-story — holding the floor without a fight.",
        wordHints: [
          { en: "half is missing", es: "falta la mitad" },
          { en: "of that story", es: "de esa historia" },
        ],
      },
      {
        id: "d363-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is the landlord call — ten minutes, five drops.",
        spanish: "Lo primero que se me ocurre es la llamada al casero — diez minutos, cinco cortes.",
        situationLabel: "Beat 4 — sin preparación, en vivo",
        why: "Cold prompt as story beat — the casero call is invierno's ordinary miracle, remembered without planning.",
        wordHints: [
          { en: "landlord call", es: "llamada al casero" },
          { en: "ten minutes", es: "diez minutos" },
          { en: "five drops", es: "cinco cortes" },
        ],
      },
      {
        id: "d363-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said at the start: this doesn't end tomorrow.",
        spanish: "Volviendo a lo que dijiste al principio: esto no se acaba mañana.",
        situationLabel: "Beat 5 — cerrando el bucle",
        why: "The conversation closes its own loop — callback, check, handover. The year keeps going.",
        wordHints: [
          { en: "at the start", es: "al principio" },
          { en: "doesn't end tomorrow", es: "no se acaba mañana" },
        ],
      },
    ],
  },
  {
    day: 364,
    themeEs: "Repaso: El año entero",
    themeEn: "Review: The whole year",
    missionEs: "Di el año entero en cinco frases.",
    missionEn: "Say the whole year in five sentences.",
    line: "Día trescientos sesenta y cuatro. El último.",
    lineEn: "Day three hundred and sixty-four. The last one.",
    prompts: [
      {
        id: "d364-soy-de-las-que",
        frameStem: "Soy de las que…",
        english: "I'm the kind of person who started without believing and finished without stopping.",
        spanish: "Soy de las que empezaron sin creer y terminaron sin parar.",
        situationLabel: "El último día",
        why: "*Hace un año no podía…* opens the retrospective; *soy de las que…* closes it as identity.",
        wordHints: [
          { en: "started without believing", es: "empezaron sin creer" },
          { en: "finished without stopping", es: "terminaron sin parar" },
        ],
      },
      {
        id: "d364-tomando-el-pelo",
        frameStem: "Te estoy tomando el pelo",
        english: "I'm teasing you one last time this year — well, thank you, and that's it.",
        spanish: "Te estoy tomando el pelo, Camila — bueno, gracias, y ya está.",
        situationLabel: "La última broma del año",
        why: "Interrupting to say thank you through a tease — week 2 and invierno day 273 in one line.",
        wordHints: [
          { en: "thank you", es: "gracias" },
          { en: "and that's it", es: "y ya está" },
        ],
      },
      {
        id: "d364-entiendo-tu-punto",
        frameStem: "Entiendo tu punto, pero…",
        english: "I get your point, but you came for coffee on Thursdays and changed a year.",
        spanish: "Entiendo tu punto, pero viniste a tomar café los jueves y cambiaste un año.",
        situationLabel: "Lo que hay que decir en voz alta",
        why: "*Sin proponérselo* energy without the subjunctive — gratitude with credit-first disagreement.",
        wordHints: [
          { en: "came for coffee", es: "vine a tomar café" },
          { en: "on thursdays", es: "los jueves" },
          { en: "changed a year", es: "cambiaste un año" },
        ],
      },
      {
        id: "d364-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is thank you.",
        spanish: "Lo primero que se me ocurre es gracias.",
        situationLabel: "Sin preparación, al final",
        why: "Week 10's cold prompt on the last day — no edit, no polish. The first thing is the truest.",
        wordHints: [
          { en: "thank you", es: "gracias" },
        ],
      },
      {
        id: "d364-volviendo",
        frameStem: "Volviendo a lo que dijiste…",
        english: "Going back to what you said — last question of the year. And now, I'm listening.",
        spanish: "Volviendo a lo que dijiste — última pregunta del año.",
        situationLabel: "Cerrando como empezaste",
        why: "The year ends by handing the floor away. That's not a flourish — it's the skill you spent fifty-two weeks learning.",
        wordHints: [
          { en: "last question", es: "última pregunta" },
          { en: "of the year", es: "del año" },
          { en: "now i'm listening", es: "ahora sí, escucho" },
        ],
      },
    ],
  },
];
