import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 7 — "Cambiar de registro" (days 316–322).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week7-frames.ts
 * for the matching `frameStem`.
 */
export const priWeek7SpeakDays: SpeakDay[] = [
  {
    day: 316,
    themeEs: "Ensayando con Rocío",
    themeEn: "Rehearsing with Rocío",
    missionEs: "Practica las cinco frases en usted hasta que suenen tuyas.",
    missionEn: "Practice the five phrases in usted until they sound like yours.",
    line: "Mañana hablas con mamás y papás. Hoy ensayas con Rocío.",
    lineEn: "Tomorrow you talk to mothers and fathers. Today you rehearse with Rocío.",
    prompts: [
      {
        id: "d316-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment before the line starts?",
        spanish: "Disculpe, ¿tendría un momento antes de que empiece la fila?",
        situationLabel: "Ensayo con Rocío",
        why: "With usted: **Disculpe** instead of *Oye*, and **¿tendría?** instead of *¿tienes?* — the conditional softens the ask.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "would you have", es: "tendría" },
          { en: "a moment", es: "un momento" },
          { en: "before the line starts", es: "antes de que empiece la fila" },
        ],
      },
      {
        id: "d316-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that Yusuf has improved a lot in participating.",
        spanish: "Le quería comentar que Yusuf ha mejorado mucho en participar.",
        situationLabel: "Buenas noticias primero",
        why: "*Te quería* becomes **Le quería** with usted — the indirect object shifts. The rest of the sentence stays the same.",
        wordHints: [
          { en: "i wanted to tell you", es: "le quería comentar" },
          { en: "has improved a lot", es: "ha mejorado mucho" },
          { en: "participating", es: "participar" },
        ],
      },
      {
        id: "d316-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain to you why we changed the schedule?",
        spanish: "¿Me permite explicarle por qué cambiamos el horario?",
        situationLabel: "Pidiendo permiso",
        why: "*¿Me dejas?* → **¿Me permite?** Same idea — asking permission — but the verb switches to usted form.",
        wordHints: [
          { en: "may i", es: "me permite" },
          { en: "explain to you", es: "explicarle" },
          { en: "why we changed", es: "por qué cambiamos" },
          { en: "the schedule", es: "el horario" },
        ],
      },
      {
        id: "d316-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time, Mrs. Martínez.",
        spanish: "Muchas gracias por su tiempo, señora Martínez.",
        situationLabel: "Cerrando la conferencia",
        why: "*Tu tiempo* → **su tiempo**. One syllable, whole register.",
        wordHints: [
          { en: "thank you so much", es: "muchas gracias" },
          { en: "your time", es: "su tiempo" },
          { en: "mrs.", es: "señora" },
        ],
      },
      {
        id: "d316-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me… would you have a moment?",
        spanish: "Con permiso… ¿tendría un momento?",
        situationLabel: "Interrumpir con respeto",
        why: "*Oye, perdona* with a friend; **Con permiso** with a parent. Different door, same job.",
        wordHints: [
          { en: "excuse me", es: "con permiso" },
          { en: "would you have", es: "tendría" },
          { en: "a moment", es: "un momento" },
        ],
      },
    ],
  },
  {
    day: 317,
    themeEs: "La primera madre",
    themeEn: "The first mother",
    missionEs: "Abre la primera conferencia en usted y no cambies al inglés.",
    missionEn: "Open the first conference in usted and don't switch to English.",
    line: "La primera se sienta. Empiezas.",
    lineEn: "The first one sits down. You begin.",
    prompts: [
      {
        id: "d317-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment? The table is over here.",
        spanish: "Disculpe, ¿tendría un momento? La mesa está por aquí.",
        situationLabel: "En la puerta",
        why: "Same conditional *tendría* — polite with a parent you just met, not a friend in the hallway.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "would you have", es: "tendría" },
          { en: "the table is over here", es: "la mesa está por aquí" },
        ],
      },
      {
        id: "d317-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that Mateo reads aloud without fear now.",
        spanish: "Le quería comentar que Mateo lee en voz alta sin miedo ahora.",
        situationLabel: "Algo positivo primero",
        why: "*Le quería comentar que* opens with strength before anything harder — same stem, usted form.",
        wordHints: [
          { en: "i wanted to tell you", es: "le quería comentar" },
          { en: "reads aloud", es: "lee en voz alta" },
          { en: "without fear", es: "sin miedo" },
        ],
      },
      {
        id: "d317-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain to you how we read here? It's not like in your country.",
        spanish: "¿Me permite explicarle cómo leemos aquí? No es como en su país.",
        situationLabel: "Antes de la carpeta",
        why: "*¿Me permite explicarle?* — the *le* is usted. With Camila it would be *explicarte*.",
        wordHints: [
          { en: "may i explain", es: "me permite explicarle" },
          { en: "how we read here", es: "cómo leemos aquí" },
          { en: "your country", es: "su país" },
        ],
      },
      {
        id: "d317-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — I know you have another child in third grade.",
        spanish: "Muchas gracias por su tiempo — sé que tiene otro hijo en tercero.",
        situationLabel: "Mira el reloj",
        why: "*Su tiempo* and *tiene* — both usted. The parent hears consistency, not a costume.",
        wordHints: [
          { en: "your time", es: "su tiempo" },
          { en: "you have", es: "tiene" },
          { en: "another child in third", es: "otro hijo en tercero" },
        ],
      },
      {
        id: "d317-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me, how do you pronounce your last name?",
        spanish: "Disculpe, ¿cómo se pronuncia su apellido?",
        situationLabel: "El nombre",
        why: "*Disculpe* before asking something personal — usted keeps the distance that *oye, perdona* would collapse.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "how is it pronounced", es: "cómo se pronuncia" },
          { en: "your last name", es: "su apellido" },
        ],
      },
    ],
  },
  {
    day: 318,
    themeEs: "Un momento difícil",
    themeEn: "A difficult moment",
    missionEs: "Di la verdad en usted aunque te cueste.",
    missionEn: "Tell the truth in usted even when it's hard.",
    line: "Pregunta por qué su hijo reprueba. Sigues en usted.",
    lineEn: "She asks why her son is failing. You stay in usted.",
    prompts: [
      {
        id: "d318-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment more? We haven't finished.",
        spanish: "Disculpe, ¿tendría un momento más? No hemos terminado.",
        situationLabel: "Necesita más tiempo",
        why: "*Un momento más* — asking for more time politely. The conditional *tendría* keeps it soft even when the topic is heavy.",
        wordHints: [
          { en: "would you have", es: "tendría" },
          { en: "a moment more", es: "un momento más" },
          { en: "we haven't finished", es: "no hemos terminado" },
        ],
      },
      {
        id: "d318-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that your son isn't lazy — English reading is hard for him.",
        spanish: "Le quería comentar que su hijo no es vago — le cuesta la lectura en inglés.",
        situationLabel: "Antes de los números",
        why: "Same stem, harder content. *Le quería comentar que* works for good news and for news that's hard to hear.",
        wordHints: [
          { en: "your son isn't lazy", es: "su hijo no es vago" },
          { en: "reading is hard for him", es: "le cuesta la lectura" },
          { en: "in english", es: "en inglés" },
        ],
      },
      {
        id: "d318-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "May I explain to you how we calculate the grade?",
        spanish: "¿Me permite explicarle cómo calculamos la nota?",
        situationLabel: "El sistema de notas",
        why: "*¿Me permite explicarle?* buys you thirty seconds to organize a hard answer — permission before explanation.",
        wordHints: [
          { en: "may i explain", es: "me permite explicarle" },
          { en: "how we calculate", es: "cómo calculamos" },
          { en: "the grade", es: "la nota" },
        ],
      },
      {
        id: "d318-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — I understand this isn't easy.",
        spanish: "Muchas gracias por su tiempo — entiendo que esto no es fácil.",
        situationLabel: "Después del silencio",
        why: "Closing with *su tiempo* and empathy — the register stays formal even when the room was emotional.",
        wordHints: [
          { en: "your time", es: "su tiempo" },
          { en: "i understand", es: "entiendo" },
          { en: "this isn't easy", es: "esto no es fácil" },
        ],
      },
      {
        id: "d318-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me, let me say it another way.",
        spanish: "Disculpe, déjeme decirlo de otra forma.",
        situationLabel: "Empezar de nuevo",
        why: "*Déjeme* — usted imperative. You're asking permission to restart without dropping register.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "let me say it", es: "déjeme decirlo" },
          { en: "another way", es: "de otra forma" },
        ],
      },
    ],
  },
  {
    day: 319,
    themeEs: "La misma frase, en tú",
    themeEn: "The same phrase, in tú",
    missionEs: "Cuenta la conferencia a Camila con los mismos stems en tú.",
    missionEn: "Tell Camila about the conference with the same stems in tú.",
    line: "Con la mamá: usted. Contigo: tú. Mismo mensaje.",
    lineEn: "With the mother: usted. With you: tú. Same message.",
    prompts: [
      {
        id: "d319-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Hey, do you have a moment? I need to tell you about the conference.",
        spanish: "Oye, ¿tienes un momento? Necesito contarte la conferencia.",
        situationLabel: "En el café",
        why: "Same message, two doors. With the parent: *Disculpe, ¿tendría?* With Camila: *Oye, ¿tienes?*",
        wordHints: [
          { en: "hey", es: "oye" },
          { en: "do you have", es: "tienes" },
          { en: "a moment", es: "un momento" },
          { en: "i need to tell you", es: "necesito contarte" },
        ],
      },
      {
        id: "d319-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that I almost cried with the third mother.",
        spanish: "Te quería comentar que casi lloro con la tercera madre.",
        situationLabel: "Desahogo",
        why: "*Le quería* with the parent, *te quería* with Camila — same stem, different pronoun.",
        wordHints: [
          { en: "i wanted to tell you", es: "te quería comentar" },
          { en: "i almost cried", es: "casi lloro" },
          { en: "the third mother", es: "la tercera madre" },
        ],
      },
      {
        id: "d319-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain to you what I told her about the grades?",
        spanish: "¿Me dejas explicarte lo que le dije sobre las notas?",
        situationLabel: "Retelling",
        why: "With the mother: *¿me permite explicarle?* With you: *¿me dejas explicarte?* — side by side.",
        wordHints: [
          { en: "can i explain", es: "me dejas explicarte" },
          { en: "what i told her", es: "lo que le dije" },
          { en: "about the grades", es: "sobre las notas" },
        ],
      },
      {
        id: "d319-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — you listened for half an hour.",
        spanish: "Muchas gracias por tu tiempo — me escuchaste media hora.",
        situationLabel: "A Camila",
        why: "*Por tu tiempo* with a friend. *Por su tiempo* with a parent. Same gratitude, different register.",
        wordHints: [
          { en: "your time", es: "tu tiempo" },
          { en: "you listened", es: "me escuchaste" },
          { en: "half an hour", es: "media hora" },
        ],
      },
      {
        id: "d319-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — I almost said *con permiso* to the waiter.",
        spanish: "Oye, perdona — casi le digo *con permiso* al mesero.",
        situationLabel: "Risa de registro",
        why: "*Con permiso* with parents; *oye, perdona* with Camila. When you've been in usted all day, the switch takes a beat.",
        wordHints: [
          { en: "hey, sorry", es: "oye, perdona" },
          { en: "i almost said", es: "casi le digo" },
          { en: "to the waiter", es: "al mesero" },
        ],
      },
    ],
  },
  {
    day: 320,
    themeEs: "Cambiando en seco",
    themeEn: "Switching on a dime",
    missionEs: "Cambia de usted a tú en el pasillo sin parar.",
    missionEn: "Switch from usted to tú in the hallway without stopping.",
    line: "Sale la mamá. Entra Camila. Mismo pasillo, otro registro.",
    lineEn: "The mother leaves. Camila arrives. Same hallway, different register.",
    prompts: [
      {
        id: "d320-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment? — oh, Camila, do you have a moment?",
        spanish: "Disculpe, ¿tendría un momento? — ah, Camila, ¿tienes un momento?",
        situationLabel: "En el pasillo",
        why: "The switch isn't a pause to think — *disculpe* to the parent, *oye* to the friend. Same hallway.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "would you have", es: "tendría" },
          { en: "do you have", es: "tienes" },
        ],
      },
      {
        id: "d320-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you the same phrase sounds different in usted.",
        spanish: "Te quería comentar que la misma frase suena distinta en usted.",
        situationLabel: "Meta-registro",
        why: "*Le quería* to the parent, *te quería* to Camila — and now you can hear the difference.",
        wordHints: [
          { en: "the same phrase", es: "la misma frase" },
          { en: "sounds different", es: "suena distinta" },
          { en: "in usted", es: "en usted" },
        ],
      },
      {
        id: "d320-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain to you what happened with Mateo's grade?",
        spanish: "¿Me dejas explicarte lo de la nota de Mateo?",
        situationLabel: "Camila pregunta",
        why: "*¿Me permite explicarle?* with the mother. *¿Me dejas explicarte?* with Camila. Same hallway, one minute apart.",
        wordHints: [
          { en: "can i explain", es: "me dejas explicarte" },
          { en: "what happened", es: "lo de" },
          { en: "mateo's grade", es: "la nota de mateo" },
        ],
      },
      {
        id: "d320-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "I said *su tiempo* eight times today. *Tu tiempo* once, with you.",
        spanish: "Dije *su tiempo* ocho veces hoy. *Tu tiempo* una, contigo.",
        situationLabel: "Contando",
        why: "Eight formal closings, one informal — and you kept track without switching languages.",
        wordHints: [
          { en: "i said", es: "dije" },
          { en: "your time (formal)", es: "su tiempo" },
          { en: "your time (informal)", es: "tu tiempo" },
          { en: "with you", es: "contigo" },
        ],
      },
      {
        id: "d320-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — I almost said *oye* to the principal.",
        spanish: "Oye, perdona — casi le digo *oye* a la directora.",
        situationLabel: "Casi un error",
        why: "When usted is in your muscles all day, *oye* to the wrong person is the mistake you're learning to catch.",
        wordHints: [
          { en: "hey, sorry", es: "oye, perdona" },
          { en: "i almost said", es: "casi le digo" },
          { en: "the principal", es: "la directora" },
        ],
      },
    ],
  },
  {
    day: 321,
    themeEs: "La conferencia entera",
    themeEn: "The full conference",
    missionEs: "Once conferencias, once cierre con Camila — los cinco stems en los dos registros.",
    missionEn: "Eleven conferences, one debrief with Camila — all five stems in both registers.",
    line: "Seis horas. Once familias. Usted todo el día. Tú a las cuatro.",
    lineEn: "Six hours. Eleven families. Usted all day. Tú at four.",
    prompts: [
      {
        id: "d321-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Excuse me, would you have a moment? — she opened with it eleven times today.",
        spanish: "Disculpe, ¿tendría un momento? — la abrió once veces hoy.",
        situationLabel: "Once veces",
        why: "The opener that started every conference — *disculpe, ¿tendría?* — until it stopped being rehearsal.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "would you have", es: "tendría" },
          { en: "eleven times", es: "once veces" },
        ],
      },
      {
        id: "d321-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that today I didn't switch to English once.",
        spanish: "Te quería comentar que hoy no cambié al inglés ni una vez.",
        situationLabel: "A las cuatro",
        why: "*Le quería comentar que…* eleven times with parents. *Te quería comentar que…* once with Camila — and that one counts just as much.",
        wordHints: [
          { en: "i wanted to tell you", es: "te quería comentar" },
          { en: "i didn't switch", es: "no cambié" },
          { en: "to english", es: "al inglés" },
          { en: "not once", es: "ni una vez" },
        ],
      },
      {
        id: "d321-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain to you why that phrase saved me?",
        spanish: "¿Me dejas explicarte por qué esa frase me salvó?",
        situationLabel: "La frase que compró tiempo",
        why: "*¿Me permite explicarle?* when you didn't know what to say next. Permission before explanation — eleven times.",
        wordHints: [
          { en: "can i explain", es: "me dejas explicarte" },
          { en: "why", es: "por qué" },
          { en: "that phrase saved me", es: "esa frase me salvó" },
        ],
      },
      {
        id: "d321-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time, Camila. You helped me rehearse.",
        spanish: "Muchas gracias por tu tiempo, Camila. Me ayudaste a ensayar.",
        situationLabel: "Después de once *su tiempo*",
        why: "*Su tiempo* closed every conference. *Tu tiempo* closes the day with the person who made usted practice possible.",
        wordHints: [
          { en: "your time", es: "tu tiempo" },
          { en: "you helped me", es: "me ayudaste" },
          { en: "rehearse", es: "ensayar" },
        ],
      },
      {
        id: "d321-perdona",
        frameStem: "Oye, perdona…",
        english: "Excuse me, I grabbed the wrong folder — I corrected myself and kept going.",
        spanish: "Disculpe, me equivoqué de carpeta — me corregí y seguí.",
        situationLabel: "Error y seguir",
        why: "*Disculpe* mid-conference, then back to usted — a mistake doesn't mean switching to English.",
        wordHints: [
          { en: "excuse me", es: "disculpe" },
          { en: "i grabbed the wrong", es: "me equivoqué de" },
          { en: "folder", es: "carpeta" },
          { en: "i kept going", es: "seguí" },
        ],
      },
    ],
  },
  {
    day: 322,
    themeEs: "Repaso: Cambiar de registro",
    themeEn: "Review: Switching register",
    missionEs: "Repite los cinco stems en tú y en usted, cada uno en serio.",
    missionEn: "Say the week's five stems in tú and usted, each one meant.",
    line: "La misma frase, dos formas — y las dos son tuyas.",
    lineEn: "The same phrase, two forms — and both are yours now.",
    prompts: [
      {
        id: "d322-momento",
        frameStem: "Oye, ¿tienes un momento?",
        english: "Hey, do you have a moment? — with you. Excuse me, would you? — with a mother.",
        spanish: "Oye, ¿tienes un momento? — contigo. Disculpe, ¿tendría? — con una mamá.",
        situationLabel: "Stem 1 repaso",
        why: "Stem 1: *Oye / ¿tienes?* ↔ **Disculpe / ¿tendría?** — opener and verb both shift.",
        wordHints: [
          { en: "with you", es: "contigo" },
          { en: "with a mother", es: "con una mamá" },
          { en: "would you have", es: "tendría" },
        ],
      },
      {
        id: "d322-queria-comentar",
        frameStem: "Te quería comentar que…",
        english: "I wanted to tell you that I learned to switch without thinking.",
        spanish: "Te quería comentar que aprendí a cambiar sin pensar.",
        situationLabel: "Stem 2 repaso",
        why: "*Te quería* → **Le quería**. The rest of the sentence doesn't care which register you picked.",
        wordHints: [
          { en: "i wanted to tell you", es: "te quería comentar" },
          { en: "i learned to switch", es: "aprendí a cambiar" },
          { en: "without thinking", es: "sin pensar" },
        ],
      },
      {
        id: "d322-explicarte",
        frameStem: "¿Me dejas explicarte?",
        english: "Can I explain to you? With you. May I explain to you? With a family.",
        spanish: "¿Me dejas explicarte? Contigo. ¿Me permite explicarle? Con una familia.",
        situationLabel: "Stem 3 repaso",
        why: "*¿Me dejas explicarte?* ↔ **¿Me permite explicarle?** — verb and pronoun, same permission.",
        wordHints: [
          { en: "with you", es: "contigo" },
          { en: "with a family", es: "con una familia" },
          { en: "may i explain", es: "me permite explicarle" },
        ],
      },
      {
        id: "d322-gracias-tiempo",
        frameStem: "Muchas gracias por tu tiempo",
        english: "Thank you so much for your time — Camila. Thank you so much for your time — ma'am.",
        spanish: "Muchas gracias por tu tiempo — Camila. Muchas gracias por su tiempo — señora.",
        situationLabel: "Stem 4 repaso",
        why: "*Tu* → **su**. One word, and the listener knows which world they're in.",
        wordHints: [
          { en: "your time (informal)", es: "tu tiempo" },
          { en: "your time (formal)", es: "su tiempo" },
          { en: "ma'am", es: "señora" },
        ],
      },
      {
        id: "d322-perdona",
        frameStem: "Oye, perdona…",
        english: "Hey, sorry — with you. Excuse me — with a father in the hallway.",
        spanish: "Oye, perdona — contigo. Con permiso — con un padre en el pasillo.",
        situationLabel: "Stem 5 repaso",
        why: "Five stems, two registers each. La misma frase, dos formas — and neither one is a translation from English.",
        wordHints: [
          { en: "with you", es: "contigo" },
          { en: "excuse me", es: "con permiso" },
          { en: "in the hallway", es: "en el pasillo" },
        ],
      },
    ],
  },
];
