import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 13 — "La última clase" (days 358–364). The year capstone.
 * The end-of-year potluck for the evening ESOL class — the one the district
 * tried to cut in week 8 and the board moved to seven instead. Six
 * installments, then a hallway with the lights off.
 * Day 364 is the last day of Temporada 4.
 */
export const priWeek13ReadingDays: ReadingDay[] = [
  {
    day: 358,
    themeEs: "El salón a las seis",
    storyTitle: "La última clase",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el mantel", en: "the tablecloth", example: "El mantel se ve bien, no lo muevas." },
      { es: "en filas", en: "in rows", example: "Si ponemos las sillas en filas nadie va a hablar." },
      { es: "cuánta gente", en: "how many people (gente is singular)", example: "No sé cuánta gente viene." },
      { es: "organizarse", en: "to sort themselves out", example: "Que ellos se organicen." },
      { es: "la coordinadora", en: "the coordinator", example: "¿Al final te contestó la coordinadora?" },
    ],
    dialogue: {
      title: "Cuarenta sillas",
      situation: "Seis de la tarde, una hora antes de que llegue nadie",
      lines: [
        { speaker: "B", es: "¿Dónde quieres las sillas? Yo las pongo en filas y listo.", en: "Where do you want the chairs? I'll put them in rows and be done." },
        { speaker: "A", es: "Entiendo tu punto, pero si ponemos las sillas en filas nadie va a hablar.", en: "I get your point, but if we put the chairs in rows nobody's going to talk." },
        { speaker: "B", es: "Entonces círculo. ¿Y la comida?", en: "Circle, then. And the food?" },
        { speaker: "A", es: "Lo primero que se me ocurre es poner la comida en el centro y que ellos se organicen.", en: "The first thing that comes to mind is putting the food in the middle and letting them organize themselves." },
        { speaker: "B", es: "El mantel está torcido.", en: "The tablecloth is crooked." },
        { speaker: "A", es: "Te estoy tomando el pelo, el mantel se ve bien. Déjalo.", en: "I'm teasing you, the tablecloth looks fine. Leave it." },
        { speaker: "B", es: "¿Cuántos crees que vengan?", en: "How many do you think will come?" },
        { speaker: "A", es: "La verdad es que nunca he hecho una de estas y no sé cuánta gente viene.", en: "Honestly, I've never done one of these and I don't know how many people are coming." },
        { speaker: "B", es: "Compraste para veinte. Lo vi en la bolsa.", en: "You bought for twenty. I saw it in the bag." },
        { speaker: "A", es: "Volviendo a lo que dijiste de la coordinadora, ¿al final te contestó?", en: "Going back to what you said about the coordinator — did she ever get back to you?" },
        { speaker: "B", es: "El viernes. Dijo que el horario de las siete se queda. Un año más, por lo menos.", en: "On Friday. She said the seven o'clock slot stays. One more year, at least." },
      ],
    },
  },
  {
    day: 359,
    themeEs: "Yesenia llega con la olla",
    storyTitle: "La última clase",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la olla", en: "the pot", example: "Yesenia llegó con una olla enorme." },
      { es: "caber", en: "to fit", example: "Claro que cabe la olla." },
      { es: "servir", en: "to serve (food)", example: "No vas a servir tú sola a todos." },
      { es: "dar pena", en: "to make someone feel bad", example: "Me da pena que hayas cocinado después del turno." },
      { es: "valer la pena", en: "to be worth it", example: "Explica tú por qué vale la pena." },
    ],
    dialogue: {
      title: "Cuarenta minutos antes",
      situation: "Yesenia entra con una olla y directo a la mesa",
      lines: [
        { speaker: "B", es: "Maestra, ¿dónde la pongo? Está pesada.", en: "Teacher, where do I put it? It's heavy." },
        { speaker: "A", es: "La verdad es que no pensé que alguien fuera a traer algo.", en: "Honestly, I didn't think anyone was going to bring anything." },
        { speaker: "B", es: "¿Cómo no voy a traer nada? Es la última.", en: "How could I not bring anything? It's the last one." },
        { speaker: "A", es: "No cabe en la mesa. Bueno… te estoy tomando el pelo, Yesenia, claro que cabe la olla.", en: "It doesn't fit on the table. Okay… I'm teasing you, Yesenia, of course the pot fits." },
        { speaker: "B", es: "Yo sirvo. Usted siéntese, que ha trabajado todo el día.", en: "I'll serve. You sit down, you've worked all day." },
        { speaker: "A", es: "Entiendo tu punto, pero esta noche no vas a servir tú sola a todos.", en: "I get your point, but tonight you're not serving everyone by yourself." },
        { speaker: "B", es: "Bueno. Las dos entonces.", en: "Fine. Both of us, then." },
        { speaker: "A", es: "Lo primero que se me ocurre es preguntarte qué le dirías a alguien que empieza en septiembre.", en: "The first thing that comes to mind is asking you what you'd tell somebody starting in September." },
        { speaker: "B", es: "Que no falte los primeros dos meses. Después ya no puede dejarlo.", en: "Not to miss the first two months. After that they won't be able to quit." },
        { speaker: "A", es: "Volviendo a lo que me preguntaste en marzo, lo del inglés para qué sirve, ¿te puedo contestar ahora?", en: "Going back to what you asked me in March — what English is for. Can I answer you now?" },
        { speaker: "B", es: "Ya me contestó, maestra. En marzo no, pero ya.", en: "You already answered me, teacher. Not in March, but you did." },
      ],
    },
  },
  {
    day: 360,
    themeEs: "Camila conoce a la clase",
    storyTitle: "La última clase",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "dar nervios", en: "to make someone nervous", example: "Me daba nervios que se conocieran." },
      { es: "llevarse bien", en: "to get along", example: "Se van a llevar demasiado bien." },
      { es: "lo del ascensor", en: "the elevator thing", example: "No les cuentes lo del ascensor." },
      { es: "el invitado de honor", en: "the guest of honor", example: "No eres la invitada de honor." },
      { es: "a la vez", en: "at the same time", example: "Así suena cuando hablan todos a la vez." },
    ],
    dialogue: {
      title: "Los dos mundos",
      situation: "Camila llega con pan y se queda parada en la puerta",
      lines: [
        { speaker: "B", es: "¿Este es el salón? Yo me lo imaginaba más grande.", en: "Is this the room? I imagined it bigger." },
        { speaker: "A", es: "Volviendo a lo que dijiste en la puerta, sí, este es el salón.", en: "Going back to what you said at the door — yes, this is the room." },
        { speaker: "B", es: "Hay más gente de la que me contaste.", en: "There are more people than you told me about." },
        { speaker: "A", es: "La verdad es que me daba nervios que ustedes dos se conocieran.", en: "Honestly, I was nervous about you two meeting." },
        { speaker: "B", es: "¿Nervios de qué? Yo llevo un año oyendo hablar de Yesenia.", en: "Nervous about what? I've spent a year hearing about Yesenia." },
        { speaker: "A", es: "Lo primero que se me ocurre es que ustedes dos se van a llevar demasiado bien.", en: "The first thing that comes to mind is that you two are going to get along far too well." },
        { speaker: "B", es: "Voy a contarles cómo hablabas en septiembre.", en: "I'm going to tell them how you talked in September." },
        { speaker: "A", es: "Ay. Te estoy tomando el pelo, aquí nadie cree que yo fuera mala para esto.", en: "Oh no. I'm teasing you, nobody here believes I was ever bad at this." },
        { speaker: "B", es: "Entonces les cuento lo del ascensor.", en: "Then I'll tell them about the elevator." },
        { speaker: "A", es: "Entiendo tu punto, pero no les cuentes todavía lo del ascensor.", en: "I get your point, but don't tell them the elevator story yet." },
        { speaker: "B", es: "Todavía. Bueno. Me siento con Rocío entonces.", en: "Yet. Fine. I'll sit with Rocío then." },
      ],
    },
  },
  {
    day: 361,
    themeEs: "La mamá de Diego",
    storyTitle: "La última clase",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "quedarse afuera", en: "to be left out", example: "Tenía miedo de quedarse afuera." },
      { es: "en los dos idiomas", en: "in both languages", example: "Diego lee mejor en los dos idiomas." },
      { es: "pedirle a alguien que", en: "to ask someone to (+ subjunctive)", example: "Pídale que le lea en español." },
      { es: "esperar que", en: "to expect that (+ subjunctive)", example: "No esperaba que usted viniera." },
      { es: "el otoño", en: "the fall, autumn", example: "Volviendo a lo que dijo en el otoño." },
    ],
    dialogue: {
      title: "Usted, de principio a fin",
      situation: "La mamá de Diego llega a las ocho — usted toda la conversación",
      lines: [
        { speaker: "B", es: "Buenas noches, maestra. Diego insistió toda la semana.", en: "Good evening, teacher. Diego insisted all week." },
        { speaker: "A", es: "La verdad es que no esperaba que usted viniera. Me alegra mucho.", en: "Honestly, I wasn't expecting you to come. I'm very glad." },
        { speaker: "B", es: "Él dijo que usted iba a decir eso.", en: "He said you were going to say that." },
        { speaker: "A", es: "Le estoy tomando el pelo, Diego me dijo que usted iba a decir exactamente eso.", en: "I'm teasing you — Diego told me you'd say exactly that." },
        { speaker: "B", es: "Maestra, yo sigo pensando en lo del inglés en la casa.", en: "Teacher, I'm still thinking about the English at home thing." },
        { speaker: "A", es: "Entiendo su punto, pero Diego lee mejor en los dos idiomas. Yo lo he visto.", en: "I understand your point, but Diego reads better in both languages. I've seen it." },
        { speaker: "B", es: "¿Y qué hago entonces?", en: "So what do I do?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que esta noche le pida que le lea en español.", en: "The first thing that comes to mind is asking him to read to you in Spanish tonight." },
        { speaker: "B", es: "¿En español? ¿Y el inglés?", en: "In Spanish? And the English?" },
        { speaker: "A", es: "El inglés lo tiene todo el día en la escuela. Usted déle lo otro.", en: "He has English all day at school. You give him the other thing." },
        { speaker: "A", es: "Volviendo a lo que dijo en el otoño, que tenía miedo de quedarse afuera. Usted no está afuera.", en: "Going back to what you said in the fall — that you were afraid of being left out. You're not out." },
        { speaker: "B", es: "Estoy aquí, ¿no?", en: "I'm here, aren't I?" },
      ],
    },
  },
  {
    day: 362,
    themeEs: "Los que no vuelven",
    storyTitle: "La última clase",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "fracasar", en: "to fail", example: "Irse no es lo mismo que fracasar." },
      { es: "librarse de", en: "to get rid of", example: "De mí no te libras tan fácil." },
      { es: "en serio", en: "seriously, and meaning it", example: "Darles mi número y decirlo en serio." },
      { es: "rendirse", en: "to give up", example: "No todos los que se van se rinden." },
      { es: "el turno de noche", en: "the night shift", example: "Por el turno de noche no pueden venir." },
    ],
    dialogue: {
      title: "Tres sillas en septiembre",
      situation: "Camila y Marlana, aparte, cerca de la ventana",
      lines: [
        { speaker: "B", es: "Se ve lleno. ¿Vuelven todos en septiembre?", en: "It looks full. Are they all coming back in September?" },
        { speaker: "A", es: "La verdad es que tres no vuelven y yo ya sé cuáles tres.", en: "Honestly, three of them aren't coming back and I already know which three." },
        { speaker: "B", es: "Ay, Marlana. Después de todo el año.", en: "Oh, Marlana. After the whole year." },
        { speaker: "A", es: "Entiendo tu punto, pero irse no es lo mismo que fracasar.", en: "I get your point, but leaving isn't the same as failing." },
        { speaker: "B", es: "¿Y no te da rabia?", en: "And it doesn't make you angry?" },
        { speaker: "A", es: "Volviendo a lo que dijiste del turno de noche, por eso no pueden venir, no porque no quieran.", en: "Going back to what you said about the night shift — that's why they can't come, not because they don't want to." },
        { speaker: "B", es: "¿Y qué vas a hacer?", en: "And what are you going to do?" },
        { speaker: "A", es: "Lo primero que se me ocurre es darles mi número y decirlo en serio.", en: "The first thing that comes to mind is giving them my number and meaning it." },
        { speaker: "B", es: "Eso lo dice todo el mundo y nadie lo cumple.", en: "Everybody says that and nobody follows through." },
        { speaker: "A", es: "Yo sí. Y a ti, te estoy tomando el pelo, de mí no te libras tan fácil.", en: "I will. And you — I'm teasing you, you're not getting rid of me that easy." },
        { speaker: "B", es: "Ni tú de mí. Los jueves siguen.", en: "Nor you of me. Thursdays continue." },
      ],
    },
  },
  {
    day: 363,
    themeEs: "Una conversación entera",
    storyTitle: "La última clase",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "las sobras", en: "the leftovers", example: "Llévate las sobras, todas." },
      { es: "el conserje", en: "the custodian", example: "El conserje ya pasó dos veces." },
      { es: "estar a (cinco meses)", en: "to be (five months) away", example: "Septiembre está a cinco meses." },
      { es: "hagámoslo", en: "let's do it", example: "Sí. Hagámoslo otra vez." },
      { es: "de nuevo", en: "again, anew", example: "Empezar de nuevo en septiembre." },
    ],
    dialogue: {
      title: "8:40",
      situation: "Casi todos se fueron — quedan cuatro en una mesa con las sobras",
      lines: [
        { speaker: "B", es: "Alguien tiene que decir que ya nos vamos.", en: "Somebody has to say we're leaving." },
        { speaker: "A", es: "La verdad es que no quiero ser yo la que termine esto.", en: "Honestly, I don't want to be the one who ends this." },
        { speaker: "B", es: "Yo tampoco. ¿Y toda esta comida?", en: "Me neither. And all this food?" },
        { speaker: "A", es: "Te estoy tomando el pelo, Rocío, llévate las sobras, todas.", en: "I'm teasing you, Rocío — take the leftovers, all of them." },
        { speaker: "B", es: "Entonces decidamos ya lo de septiembre. Aquí, ahora, las cuatro.", en: "Then let's decide the September thing now. Here, now, the four of us." },
        { speaker: "A", es: "Entiendo tu punto, pero septiembre está a cinco meses y prefiero decidir en agosto.", en: "I get your point, but September is five months away and I'd rather decide in August." },
        { speaker: "B", es: "Bueno, pero dime cómo te lo imaginas.", en: "Fine, but tell me how you picture it." },
        { speaker: "A", es: "Lo primero que se me ocurre es el mismo salón, la misma hora, y les preguntamos a ellos qué quieren.", en: "The first thing that comes to mind is: same room, same hour, and we ask them what they want." },
        { speaker: "B", es: "Entonces sí hay septiembre.", en: "So there is a September." },
        { speaker: "A", es: "Volviendo a lo que dijiste hace una hora, sí. Hagámoslo otra vez.", en: "Going back to what you said an hour ago — yes. Let's do it again." },
        { speaker: "B", es: "Ya está. Y ahora sí, a apilar sillas.", en: "There it is. And now, chairs." },
      ],
    },
  },
  {
    day: 364,
    themeEs: "Repaso: La última clase",
    isRecap: true,
    vocab: [
      { es: "apilar", en: "to stack", example: "Apilamos las sillas contra la pared." },
      { es: "apagar las luces", en: "to turn off the lights", example: "Yo apago las luces y tú cierras." },
      { es: "apuntar", en: "to write down, to jot down", example: "Tengo que apuntar el nombre." },
      { es: "antes de que", en: "before (+ subjunctive)", example: "Antes de que se me olvide." },
      { es: "alcanzar", en: "to be enough", example: "Con dos alcanzaba." },
    ],
    dialogue: {
      title: "Nueve de la noche",
      situation: "Sillas apiladas, luces apagadas, las dos en el pasillo",
      lines: [
        { speaker: "B", es: "Listo. ¿Nos vamos?", en: "Done. Shall we go?" },
        { speaker: "A", es: "La verdad es que esta noche no voy a poder dormir.", en: "Honestly, I'm not going to be able to sleep tonight." },
        { speaker: "B", es: "Yo tampoco. Deja la olla, la recoges el lunes.", en: "Me neither. Leave the pot, you can get it Monday." },
        { speaker: "A", es: "Entiendo tu punto, pero no voy a dejar la olla aquí hasta el lunes. Es de Yesenia.", en: "I get your point, but I'm not leaving the pot here until Monday. It's Yesenia's." },
        { speaker: "B", es: "Bueno. Entonces tú cargas la olla y yo las bolsas.", en: "Fine. Then you carry the pot and I'll take the bags." },
        { speaker: "A", es: "Te estoy tomando el pelo, tú llevas las sillas y yo saco la basura.", en: "I'm teasing you — you take the chairs and I'll take out the trash." },
        { speaker: "B", es: "Las sillas ya están. Espera, ¿apagaste el fondo?", en: "The chairs are done already. Wait, did you turn off the back light?" },
        { speaker: "A", es: "Ya. Lo primero que se me ocurre es que tengo que apuntar el nombre de la mamá de Yesenia antes de que se me olvide.", en: "Done. The first thing that comes to mind is that I need to write down Yesenia's mom's name before I forget it." },
        { speaker: "B", es: "Rosalía. Te lo digo yo y no lo apuntas.", en: "Rosalía. I'm telling you and you're not writing it down." },
        { speaker: "A", es: "Rosalía. Ya está.", en: "Rosalía. Got it." },
        { speaker: "A", es: "Volviendo a lo que dijiste junto a la copiadora en abril, tenías razón. Con dos alcanzaba.", en: "Going back to what you said by the copier in April — you were right. Two of us was enough." },
        { speaker: "B", es: "Te lo dije. Apaga y vámonos, que es viernes mañana.", en: "I told you. Turn it off and let's go, tomorrow's Friday." },
      ],
    },
  },
];
