import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 13 — "El año entero" (days 358–364). The year capstone.
 * The last week of Pues: the June recording played next to today's, the whole
 * table at the café, and one long conversation that uses the whole year at once.
 * Day 364 is the last day of Temporada 4.
 */
export const priWeek13ReadingDays: ReadingDay[] = [
  {
    day: 358,
    themeEs: "La última semana",
    storyTitle: "El año entero",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "acabarse", en: "to come to an end", example: "Se acaba el año." },
      { es: "pasarle volando a alguien", en: "to fly by for someone", example: "No quiero que esta semana se me pase volando." },
      { es: "sin creérmelo", en: "without believing it", example: "Empecé sin creérmelo." },
      { es: "el hilo", en: "the thread", example: "Volviendo a lo que dijiste en marzo." },
      { es: "sonar natural", en: "to sound natural", example: "Sonar natural no era el final." },
    ],
    dialogue: {
      title: "Quedan siete días",
      situation: "Lunes; Marlana se da cuenta de qué semana es",
      lines: [
        { speaker: "A", es: "Camila, ¿sabes qué? Quedan siete días de año.", en: "Camila, do you know what? There are seven days of the year left." },
        { speaker: "B", es: "Ya lo había contado. ¿Y cómo te sientes?", en: "I'd already counted. And how do you feel?" },
        { speaker: "A", es: "Soy de las que se dan cuenta tarde de lo lejos que llegaron. Empecé en junio sin creérmelo.", en: "I'm the kind of person who realizes late how far they've come. I started in June without believing it." },
        { speaker: "B", es: "Yo sí me lo creía. Desde septiembre.", en: "I believed it. Since September." },
        { speaker: "A", es: "Entiendo tu punto, pero no quiero que esta semana se me pase volando. Quiero oír el audio de junio conmigo.", en: "I get your point, but I don't want this week to fly by. I want to hear the June recording with me." },
        { speaker: "B", es: "¿El primer audio? ¿Lo guardaste?", en: "The first recording? You kept it?" },
        { speaker: "A", es: "Me dijiste que lo guardara. Está ahí desde el día uno.", en: "You told me to keep it. It's been there since day one." },
        { speaker: "B", es: "Entonces el jueves lo oímos. Lo primero que se me ocurre es el primer jueves en el café.", en: "Then we'll listen to it Thursday. The first thing that comes to mind is the first Thursday at the café." },
        { speaker: "A", es: "Volviendo a lo que dijiste en marzo: sonar natural no era el final. Tenías razón.", en: "Going back to what you said in March: sounding natural wasn't the end. You were right." },
      ],
    },
  },
  {
    day: 359,
    themeEs: "Hace un año",
    storyTitle: "El año entero",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "hace un año", en: "a year ago", example: "Hace un año no podía pedir un café." },
      { es: "reconocerse", en: "to recognize oneself", example: "Ya no reconozco mi voz de junio." },
      { es: "la pausa", en: "the pause", example: "Tenía miedo de la pausa." },
      { es: "pedir permiso", en: "to ask permission", example: "En junio pedía permiso para cada frase." },
      { es: "guardar", en: "to keep, to save", example: "Guarda el primero." },
    ],
    dialogue: {
      title: "Día uno",
      situation: "Jueves; suenan los dos audios — junio y hoy",
      lines: [
        { speaker: "A", es: "Pues, aquí está: ocho segundos de junio y cuatro pausas.", en: "Well, here it is: eight seconds from June and four pauses." },
        { speaker: "B", es: "Dale.", en: "Go on." },
        { speaker: "A", es: "Soy de las que ya no reconocen su voz de junio. ¿De verdad sonaba así?", en: "I'm the kind of person who doesn't recognize her June voice anymore. Did I really sound like that?" },
        { speaker: "B", es: "Sonabas así. Y ahora pon el de esta semana.", en: "You sounded like that. Now play this week's." },
        { speaker: "A", es: "Te estoy tomando el pelo — bueno, sí era tan horrible. Entiendo tu punto, pero hace un año no podía pedir un café.", en: "I'm teasing you — well, yes, it really was that bad. I get your point, but a year ago I couldn't order a coffee." },
        { speaker: "B", es: "No te compadezcas. Esa persona tenía valor también.", en: "Don't feel sorry for her. That person had value too." },
        { speaker: "A", es: "Lo primero que se me ocurre es que tenía miedo de la pausa. Decía \"perdón\" dos veces por frase.", en: "The first thing that comes to mind is that I was afraid of the pause. I said \"sorry\" twice per sentence." },
        { speaker: "B", es: "Dos veces. Las conté yo también.", en: "Twice. I counted them too." },
        { speaker: "A", es: "Volviendo a lo que dijiste en invierno: guarda el primero. Tenías razón.", en: "Going back to what you said in winter: keep the first one. You were right." },
      ],
    },
  },
  {
    day: 360,
    themeEs: "Lo que cambió",
    storyTitle: "El año entero",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el talento", en: "talent", example: "No fue talento, fue constancia." },
      { es: "constancia", en: "consistency", example: "Un año entero de constancia." },
      { es: "repetirse", en: "to be repeatable", example: "El método se puede repetir." },
      { es: "dejar de frenar", en: "to stop braking", example: "Invierno fue dejar de frenar." },
      { es: "sonar a alguien", en: "to sound like someone", example: "Ya suena a ti." },
    ],
    dialogue: {
      title: "No fue talento",
      situation: "Camila intenta hacerle un cumplido y Marlana lo corrige",
      lines: [
        { speaker: "B", es: "Es que tú tienes facilidad, Marlana. Se te da.", en: "The thing is you have a knack, Marlana. It comes easily to you." },
        { speaker: "A", es: "Te estoy tomando el pelo — bueno, no, no fue talento. Fueron trescientos sesenta y cuatro días seguidos.", en: "I'm teasing you — well, no, it wasn't talent. It was three hundred and sixty-four days in a row." },
        { speaker: "B", es: "Bueno, las dos cosas.", en: "Well, both things." },
        { speaker: "A", es: "No. Si lo llamas don, nadie lo copia. Soy de las que hablan todos los días, poquito, un año entero.", en: "No. If you call it a gift, nobody copies it. I'm the kind of person who speaks every day, a little, for a whole year." },
        { speaker: "B", es: "¿Entonces qué cambió?", en: "So what changed?" },
        { speaker: "A", es: "Entiendo tu punto, pero invierno no fue gramática, fue dejar de frenar. Verano fue sobrevivir. Primavera fue personalidad.", en: "I get your point, but winter wasn't grammar, it was not braking. Summer was survival. Spring was personality." },
        { speaker: "B", es: "Lo primero que se me ocurre es que el miedo a la pausa se fue.", en: "The first thing that comes to mind is that the fear of the pause is gone." },
        { speaker: "A", es: "Eso. Y que ahora interrumpo sin disculparme tanto.", en: "That. And that now I interrupt without apologizing so much." },
        { speaker: "B", es: "Volviendo a lo que dijiste la semana pasada: ya suena a ti.", en: "Going back to what you said last week: it already sounds like you." },
      ],
    },
  },
  {
    day: 361,
    themeEs: "La mesa entera",
    storyTitle: "El año entero",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la pena", en: "embarrassment, shyness", example: "No te preocupa el inglés, te preocupa la pena." },
      { es: "el intercambio", en: "the language exchange", example: "Así empezó todo: un intercambio los jueves." },
      { es: "planificar", en: "to plan", example: "No planifiqué ninguno de estos jueves." },
      { es: "feo/a", en: "ugly, rough", example: "Empieza feo y sigue." },
      { es: "al otro lado", en: "on the other end", example: "Alguien al otro lado hace falta." },
    ],
    dialogue: {
      title: "Ahora somos cuatro",
      situation: "Marlana lleva a Yesenia al café; Camila y Rocío ya están ahí",
      lines: [
        { speaker: "A", es: "Pues, Yesenia, esta es Camila. Y a Rocío ya la conoces. Soy de las que ya no son la única en la mesa.", en: "Well, Yesenia, this is Camila. And you already know Rocío. I'm the kind of person who's not the only one at the table anymore." },
        { speaker: "B", es: "Mucho gusto. Marlana me habló de usted.", en: "Nice to meet you. Marlana told me about you." },
        { speaker: "A", es: "De tú, Camila, que aquí nadie es de usted. Te estoy tomando el pelo, Yesenia, no planifiqué ninguno de estos jueves.", en: "It's tú, Camila, nobody's usted here. I'm teasing you, Yesenia, I didn't plan any of these Thursdays." },
        { speaker: "B", es: "¿Usted? Pero si habla perfecto.", en: "You? But you speak perfectly." },
        { speaker: "A", es: "Entiendo tu punto, pero hace un año yo tampoco creía que fuera posible. Hablo entendible, que es otra cosa.", en: "I get your point, but a year ago I didn't believe it was possible either. I speak understandably, which is different." },
        { speaker: "B", es: "Yo llevo ocho meses sin decir una frase en inglés.", en: "I've gone eight months without saying a sentence in English." },
        { speaker: "A", es: "Lo primero que se me ocurre es: cinco frases al día, nada más. Y alguien al otro lado.", en: "The first thing that comes to mind is: five sentences a day, nothing more. And someone on the other end." },
        { speaker: "B", es: "¿Y si empiezo mal?", en: "What if I start badly?" },
        { speaker: "A", es: "Empieza feo y sigue. Volviendo a lo que dijiste: no te preocupa el inglés, te preocupa la pena.", en: "Start rough and keep going. Going back to what you said: it isn't the English that worries you, it's the embarrassment." },
      ],
    },
  },
  {
    day: 362,
    themeEs: "Lo que me llevo",
    storyTitle: "El año entero",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el hábito", en: "the habit", example: "Hablar es un hábito, no un talento." },
      { es: "encogerse", en: "to shrink, to pull back", example: "Todavía me encojo cuando me contradicen." },
      { es: "en perfecto", en: "in perfect", example: "El año no acaba en perfecto." },
      { es: "suenar como uno/a", en: "to sound like oneself", example: "Primavera fue suenar como yo." },
      { es: "firmar", en: "to sign up to, to endorse", example: "Eso sí lo firmo." },
    ],
    dialogue: {
      title: "Cuatro temporadas",
      situation: "Marlana nombra lo que se lleva de cada estación",
      lines: [
        { speaker: "B", es: "Bueno. Un año. ¿Qué te llevas, en cuatro frases?", en: "All right. One year. What are you taking with you, in four sentences?" },
        { speaker: "A", es: "Lo primero que se me ocurre de verano es: sobreviví. De otoño: conté una historia. De invierno: dejé de frenar.", en: "The first thing that comes to mind about summer is: I survived. About fall: I told a story. About winter: I stopped braking." },
        { speaker: "B", es: "¿Y primavera?", en: "And spring?" },
        { speaker: "A", es: "Lo primero que se me ocurre de primavera es: sueno como yo. Soy de las que pueden tener una conversación larga sin prepararla.", en: "The first thing that comes to mind about spring is: I sound like me. I'm the kind of person who can have a long conversation without preparing it." },
        { speaker: "B", es: "¿Y lo que falta?", en: "And what's missing?" },
        { speaker: "A", es: "Entiendo tu punto, pero el año no acaba en perfecto. Todavía me encojo cuando me contradicen fuerte.", en: "I get your point, but the year doesn't end in perfect. I still shrink when someone contradicts me hard." },
        { speaker: "B", es: "Eso es honesto.", en: "That's honest." },
        { speaker: "A", es: "Te estoy tomando el pelo, no voy a llorar — bueno, tal vez un poco.", en: "I'm teasing you, I'm not going to cry — well, maybe a little." },
        { speaker: "B", es: "Volviendo a lo que dijiste en marzo: hablar es un hábito, no un talento. Eso sí lo firmo.", en: "Going back to what you said in March: speaking is a habit, not a talent. That I'll sign up to." },
      ],
    },
  },
  {
    day: 363,
    themeEs: "Una conversación entera",
    storyTitle: "El año entero",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "de golpe", en: "all at once", example: "Oíste todo el año de golpe." },
      { es: "el casero", en: "the landlord", example: "La llamada al casero — diez minutos, cinco cortes." },
      { es: "meterse", en: "to jump in", example: "Ahí sí tengo que meterme." },
      { es: "cerrar el bucle", en: "to close the loop", example: "Volviendo a lo que dijiste al principio." },
      { es: "la mesa", en: "the table", example: "No fuiste la profesora — fuiste la mesa." },
    ],
    dialogue: {
      title: "Dos horas",
      situation: "La charla larga: cuatro personas, un idioma, ninguna traducción",
      lines: [
        { speaker: "A", es: "Soy de las que cuentan el año en jueves, no en meses. Mira, empezó fatal y terminó bien.", en: "I'm the kind of person who counts the year in Thursdays, not months. Look, it started terribly and ended well." },
        { speaker: "B", es: "Empieza por junio.", en: "Start from June." },
        { speaker: "A", es: "Te estoy tomando el pelo, Camila, no fuiste la profesora — fuiste la mesa.", en: "I'm teasing you, Camila, you weren't the teacher — you were the table." },
        { speaker: "B", es: "…", en: "…" },
        { speaker: "B", es: "…y ahí fue cuando Marlana llamó al casero y le habló diez minutos en español—", en: "…and that was when Marlana called the landlord and talked to him for ten minutes in Spanish—" },
        { speaker: "A", es: "Entiendo tu punto, pero falta la mitad de esa historia. Se cortó cinco veces.", en: "I get your point, but half of that story is missing. It dropped five times." },
        { speaker: "B", es: "Cinco veces, y volviste a llamar cinco veces. Esa es la historia.", en: "Five times, and you called back five times. That's the story." },
        { speaker: "A", es: "Lo primero que se me ocurre es la llamada al casero — diez minutos, cinco cortes. Nunca pensé que aguantaría un año.", en: "The first thing that comes to mind is the landlord call — ten minutes, five drops. I never thought I'd last a year." },
        { speaker: "B", es: "Volviendo a lo que dijiste al principio: esto no se acaba mañana.", en: "Going back to what you said at the start: this doesn't end tomorrow." },
      ],
    },
  },
  {
    day: 364,
    themeEs: "Repaso: El año entero",
    isRecap: true,
    vocab: [
      { es: "hace un año no podía", en: "a year ago I couldn't", example: "Hace un año no podía pedir un café." },
      { es: "sin proponérselo", en: "without meaning to", example: "Camila hizo esto sin proponérselo." },
      { es: "y ya está", en: "and that's it", example: "Gracias, y ya está." },
      { es: "quitársele a alguien", en: "to go away from someone", example: "Esto ya no se me quita." },
      { es: "el año entero", en: "the whole year", example: "Última pregunta del año entero." },
    ],
    dialogue: {
      title: "Día trescientos sesenta y cuatro",
      situation: "El último día del año; las cuatro en el café",
      lines: [
        { speaker: "B", es: "Bueno. Día trescientos sesenta y cuatro. ¿Alguien quiere decir algo antes de que se acabe?", en: "All right. Day three hundred and sixty-four. Does anyone want to say something before it ends?" },
        { speaker: "A", es: "Hace un año no podía pedir un café sin traducir en la cabeza. Soy de las que empezaron sin creer y terminaron sin parar.", en: "A year ago I couldn't order a coffee without translating in my head. I'm the kind of person who started without believing and finished without stopping." },
        { speaker: "B", es: "¿Y Camila?", en: "And Camila?" },
        { speaker: "A", es: "Te estoy tomando el pelo, Camila — bueno, gracias, y ya está.", en: "I'm teasing you, Camila — well, thank you, and that's it." },
        { speaker: "B", es: "No hice nada. Vine a tomar café los jueves.", en: "I didn't do anything. I came for coffee on Thursdays." },
        { speaker: "A", es: "Entiendo tu punto, pero viniste a tomar café los jueves y cambiaste un año. Lo primero que se me ocurre es gracias.", en: "I get your point, but you came for coffee on Thursdays and changed a year. The first thing that comes to mind is thank you." },
        { speaker: "B", es: "Eso sí lo firmo. ¿Y qué te llevas del año, en una frase?", en: "That I'll sign up to. And what do you take from the year, in one sentence?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que hablar es un hábito, no un talento. Y que trescientos sesenta y cuatro días cambian a una persona.", en: "The first thing that comes to mind is that speaking is a habit, not a talent. And that three hundred and sixty-four days change a person." },
        { speaker: "A", es: "Volviendo a lo que dijiste — última pregunta del año. Y ahora sí, escucho.", en: "Going back to what you said — last question of the year. And now, I'm listening." },
      ],
    },
  },
];
