import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 12 — "Cuando se enfría" (days 351–357).
 * A long Sunday call runs out of steam; Marlana learns the relaunch stems
 * that keep a conversation alive when the thread dies.
 */
export const priWeek12ReadingDays: ReadingDay[] = [
  {
    day: 351,
    themeEs: "El silencio",
    storyTitle: "Cuando se enfría",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "enfriarse", en: "to cool down, to go cold (fig.)", example: "La conversación se enfría a los cuarenta minutos." },
      { es: "colgar", en: "to hang up (the phone)", example: "No me dejes colgada con ese silencio." },
      { es: "el hilo", en: "the thread (of conversation)", example: "Se acabó el hilo y nadie supo qué decir." },
      { es: "relanzar", en: "to relaunch, to restart", example: "Hoy aprendí a relanzar una conversación." },
      { es: "¿y qué más?", en: "what else?, anything else?", example: "Bueno, ¿y qué más? No es pereza, es invitación." },
    ],
    dialogue: {
      title: "Cuarenta minutos",
      situation: "Domingo por la tarde — llamada larga entre Marlana y Camila",
      lines: [
        { speaker: "A", es: "…Entonces sí, el jueves fue normal. Bueno.", en: "…So yeah, Thursday was normal. Well." },
        { speaker: "B", es: "Bueno.", en: "Well." },
        { speaker: "A", es: "Silencio. Llevamos cuarenta minutos y se acabó el hilo.", en: "Silence. We've been on forty minutes and the thread ran out." },
        { speaker: "B", es: "Pasa. Siempre pasa.", en: "It happens. It always happens." },
        { speaker: "A", es: "Me da pánico. Siento que si no digo algo inteligente, la llamada muere.", en: "It panics me. I feel like if I don't say something smart, the call dies." },
        { speaker: "B", es: "No necesitas algo inteligente. Necesitas una puerta abierta.", en: "You don't need something smart. You need an open door." },
        { speaker: "A", es: "Bueno, ¿y qué más? ¿Qué más te pasó esta semana?", en: "Well, what else? What else happened to you this week?" },
        { speaker: "B", es: "Ahí. Eso no es pereza — es invitación. Suena vacía y no lo es.", en: "There. That's not laziness — it's an invitation. It sounds empty and it isn't." },
        { speaker: "A", es: "Se me olvidaba contarte lo de la mamá de Diego. Casi cuelgo sin decirte.", en: "I forgot to tell you about Diego's mom. I almost hung up without telling you." },
        { speaker: "B", es: "Ves. El silencio no te mató. Te obligó a buscar lo que casi olvidaste.", en: "See. The silence didn't kill you. It made you find what you almost forgot." },
      ],
    },
  },
  {
    day: 352,
    themeEs: "Bueno, ¿y qué más?",
    storyTitle: "Cuando se enfría",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "la invitación", en: "the invitation", example: "¿Y qué más? es invitación, no pregunta vacía." },
      { es: "el susto", en: "the scare, the fright", example: "Anoche hubo un susto en el hospital." },
      { es: "rondar", en: "to go around in (one's head)", example: "¿Qué más te ronda la cabeza?" },
      { es: "importante", en: "important", example: "No tiene que ser importante." },
      { es: "colgada", en: "left hanging (on the phone)", example: "No me dejes colgada." },
    ],
    dialogue: {
      title: "La puerta abierta",
      situation: "Camila enseña el stem — Marlana practica en vivo",
      lines: [
        { speaker: "B", es: "Prueba otra vez. Como si de verdad quisieras saber.", en: "Try again. Like you really want to know." },
        { speaker: "A", es: "Bueno, ¿y qué más? No tiene que ser importante.", en: "Well, what else? It doesn't have to be important." },
        { speaker: "B", es: "Mejor. El \"bueno\" te compra un respiro. La pregunta le deja el piso a la otra.", en: "Better. The \"well\" buys you a breath. The question leaves the floor to the other person." },
        { speaker: "A", es: "¿Y si no cae?", en: "And if it doesn't land?" },
        { speaker: "B", es: "Entonces cambias. Se me olvidaba contarte que anoche hubo un susto en el hospital.", en: "Then you switch. I forgot to tell you — there was a scare at the hospital last night." },
        { speaker: "A", es: "¿Qué pasó?", en: "What happened?" },
        { speaker: "B", es: "Nada grave. Pero me acordé porque tú preguntaste \"¿y qué más?\" y eso abrió la puerta.", en: "Nothing serious. But I remembered because you asked \"what else?\" and that opened the door." },
        { speaker: "A", es: "Oye, y cambiando de tema — ¿tú sigues yendo al café los jueves?", en: "Hey, and changing the subject — are you still going to the café on Thursdays?" },
        { speaker: "B", es: "Sigo. Por cierto, tu alumna me escribió anoche. Preguntó por ti.", en: "I am. By the way, your student wrote to me last night. She asked about you." },
        { speaker: "A", es: "Ah, y otra cosa — mañana llámame temprano. Todavía no cuelgo.", en: "Oh, and one more thing — call me early tomorrow. I'm not hanging up yet." },
      ],
    },
  },
  {
    day: 353,
    themeEs: "Se me olvidaba contarte",
    storyTitle: "Cuando se enfría",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "olvidarse", en: "to forget, to slip one's mind", example: "Se me olvidaba contarte lo de Yesenia." },
      { es: "enterrar", en: "to bury (fig.)", example: "Casi lo enterré con el silencio." },
      { es: "volvió", en: "she/he came back", example: "Yesenia volvió el jueves." },
      { es: "amanecer", en: "to wake up, to start (shift/day)", example: "¿Cómo amaneció tu turno?" },
      { es: "balance", en: "balance", example: "Ya hablé mucho de mi semana — tu turno." },
    ],
    dialogue: {
      title: "Lo que casi se pierde",
      situation: "Marlana relanza con algo de la escuela",
      lines: [
        { speaker: "A", es: "Se me olvidaba contarte que Yesenia volvió el jueves.", en: "I forgot to tell you Yesenia came back Thursday." },
        { speaker: "B", es: "¿Volvió sola?", en: "Did she come back on her own?" },
        { speaker: "A", es: "Sola. Se me olvidaba contarte lo que me dijo la mamá al final — casi lo enterré con el silencio.", en: "On her own. I forgot to tell you what her mom said at the end — I almost buried it with the silence." },
        { speaker: "B", es: "Bueno, ¿y qué más pasó con la mamá de Diego?", en: "Well, what else happened with Diego's mom?" },
        { speaker: "A", es: "Dijo que el inglés le abrió una puerta en la cocina. No un folleto — una puerta.", en: "She said English opened a door for her in the kitchen. Not a brochure — a door." },
        { speaker: "B", es: "Bien. Oye, y cambiando de tema, ¿cómo amaneció tu turno?", en: "Good. Hey, and changing the subject — how did your shift start?" },
        { speaker: "A", es: "Por cierto, la mamá de Diego trabaja cerca del hospital.", en: "By the way, Diego's mom works near the hospital." },
        { speaker: "B", es: "Mira — se conecta todo. Ah, y otra cosa: el jueves tengo reunión de padres.", en: "Look — it all connects. Oh, and one more thing: I have parent conferences Thursday." },
        { speaker: "A", es: "¿Quieres que te ayude a practicar?", en: "Want me to help you practice?" },
        { speaker: "B", es: "Quiero. Pero primero termina la historia de Yesenia. Llevamos hora y diez.", en: "I do. But finish Yesenia's story first. We're at an hour and ten." },
      ],
    },
  },
  {
    day: 354,
    themeEs: "Cambiando de tema",
    storyTitle: "Cuando se enfría",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "cambiar de tema", en: "to change the subject", example: "No revivas lo muerto — cambia de tema." },
      { es: "el ascensor", en: "the elevator", example: "Lo que pasó con el ascensor." },
      { es: "spoilear", en: "to spoil (a plot)", example: "No me spoilees la serie." },
      { es: "pivotar", en: "to pivot", example: "Cuando un hilo muere, pivotas." },
      { es: "el cumpleaños", en: "the birthday", example: "Rocío preguntó si vienes al cumpleaños." },
    ],
    dialogue: {
      title: "No revivas lo muerto",
      situation: "El hilo del hospital se acaba — Marlana practica el giro",
      lines: [
        { speaker: "B", es: "…y el ascensor se quedó parado entre el tercero y el cuarto. Bueno.", en: "…and the elevator got stuck between three and four. Well." },
        { speaker: "A", es: "Bueno, ¿y qué más sobre el turno? ¿O ya fue todo?", en: "Well, what else about the shift? Or was that everything?" },
        { speaker: "B", es: "Ya fue todo del turno.", en: "That was everything about the shift." },
        { speaker: "A", es: "Entonces no lo revivo. Oye, y cambiando de tema, ¿viste la serie que me recomendaste?", en: "Then I won't revive it. Hey, and changing the subject — did you watch the series you recommended?" },
        { speaker: "B", es: "Vi dos capítulos. Se me olvidaba contarte lo del ascensor — iba justo con lo del turno.", en: "I watched two episodes. I forgot to tell you about the elevator — it went with the shift story." },
        { speaker: "A", es: "Perdón, te interrumpí.", en: "Sorry, I interrupted you." },
        { speaker: "B", es: "No. El turno ya no daba más. Cambiaste a tiempo.", en: "No. The shift had nothing left. You switched in time." },
        { speaker: "A", es: "Por cierto, Rocío preguntó si vienes al cumpleaños.", en: "By the way, Rocío asked if you're coming to the birthday." },
        { speaker: "B", es: "Voy. Ah, y otra cosa sobre la serie — no me spoilees.", en: "I'm going. Oh, and one more thing about the series — don't spoil it." },
        { speaker: "A", es: "No spoileo. Pero el cumpleaños es en español, ¿verdad?", en: "I won't spoil. But the birthday's in Spanish, right?" },
      ],
    },
  },
  {
    day: 355,
    themeEs: "Por cierto",
    storyTitle: "Cuando se enfría",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "por cierto", en: "by the way, incidentally", example: "Por cierto — el relanzamiento más suave." },
      { es: "la tangente", en: "the tangent", example: "La tangente de doña Marta duró veinte minutos." },
      { es: "la vecina", en: "the neighbor (female)", example: "Vi a tu vecina en la panadería." },
      { es: "sidebar", en: "sidebar (loanword in context)", example: "Lo tangencial abre la mejor parte." },
      { es: "te vas a morir", en: "you're going to die (laughing)", example: "Te vas a morir con lo de doña Marta." },
    ],
    dialogue: {
      title: "Veinte minutos de panadería",
      situation: "Por cierto abre la tangente más larga de la llamada",
      lines: [
        { speaker: "A", es: "Por cierto, oí a alguien decir \"pa' que\" en la tienda.", en: "By the way, I heard someone say \"pa' que\" at the store." },
        { speaker: "B", es: "¿Y?", en: "And?" },
        { speaker: "A", es: "Por cierto, vi a tu vecina en la panadería. Es de Medellín.", en: "By the way, I saw your neighbor at the bakery. She's from Medellín." },
        { speaker: "B", es: "Bueno, ¿y qué más? Eso suena a historia larga.", en: "Well, what else? That sounds like a long story." },
        { speaker: "A", es: "Se me olvidaba contarte — por eso me acordé de tu tía. Y de doña Marta.", en: "I forgot to tell you — that's why I thought of your aunt. And Doña Marta." },
        { speaker: "B", es: "Llevamos veinte minutos en la panadería. Oye, y cambiando de tema — ¿tú qué harías con Yesenia?", en: "We've been on the bakery for twenty minutes. Hey, and changing the subject — what would you do with Yesenia?" },
        { speaker: "A", es: "Le diría la verdad incompleta. Como en el café.", en: "I'd tell her the incomplete truth. Like at the café." },
        { speaker: "B", es: "Bien. Ah, y otra cosa sobre doña Marta — te vas a morir.", en: "Good. Oh, and one more thing about Doña Marta — you're going to die." },
        { speaker: "A", es: "¿Qué hizo?", en: "What did she do?" },
        { speaker: "B", es: "Me guardó pan de bono sin que yo pidiera. Por cierto — eso es pertenecer.", en: "She saved me pan de bono without my asking. By the way — that's belonging." },
      ],
    },
  },
  {
    day: 356,
    themeEs: "Ah, y otra cosa",
    storyTitle: "Cuando se enfría",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "apilar", en: "to stack", example: "Dijiste \"ah, y otra cosa\" tres veces." },
      { es: "el capstone", en: "the capstone (final project)", example: "¿Aguanto una hora entera para el capstone?" },
      { es: "calentarse", en: "to warm up (fig.)", example: "Así se calienta cuando se enfría." },
      { es: "colgar", en: "to hang up", example: "Iba a colgar sin decirte." },
      { es: "hora y media", en: "an hour and a half", example: "Llevamos hora y media y nadie cuelga." },
    ],
    dialogue: {
      title: "Hora y media",
      situation: "Dijeron que colgaban hace veinte minutos — el stack sigue",
      lines: [
        { speaker: "A", es: "Bueno, ¿y qué más? Dijiste \"ah, y otra cosa\" tres veces.", en: "Well, what else? You said \"oh, and one more thing\" three times." },
        { speaker: "B", es: "Y tú también. Llevamos hora y media.", en: "You too. We're at an hour and a half." },
        { speaker: "A", es: "Se me olvidaba contarte lo del regalo de Rocío — iba a colgar sin decirte.", en: "I forgot to tell you about Rocío's gift — I was about to hang up without telling you." },
        { speaker: "B", es: "Oye, y cambiando de tema, ¿tú crees que aguanto una hora entera?", en: "Hey, and changing the subject — do you think I can hold a full hour?" },
        { speaker: "A", es: "Aguantas hora y media de panadería y hospital. Una hora entera te sobra.", en: "You held an hour and a half of bakery and hospital. A full hour is easy." },
        { speaker: "B", es: "Por cierto, el domingo que viene igual, ¿sí?", en: "By the way, same time next Sunday, right?" },
        { speaker: "A", es: "Igual. Ah, y otra cosa: hoy aprendí a relanzar una conversación.", en: "Same. Oh, and one more thing: today I learned to relaunch a conversation." },
        { speaker: "B", es: "¿Cuándo se enfrió?", en: "When did it go cold?" },
        { speaker: "A", es: "A los cuarenta minutos. Y se calentó con cinco stems.", en: "At forty minutes. And it warmed up with five stems." },
        { speaker: "B", es: "Ah, y otra cosa, y otra, y otra — así funciona. Ahora sí cuelgo. Mañana temprano.", en: "Oh, and one more thing, and another, and another — that's how it works. Now I'll hang up. Early tomorrow." },
      ],
    },
  },
  {
    day: 357,
    themeEs: "Repaso: Conversación larga II",
    isRecap: true,
    vocab: [
      { es: "quedarnos (tiempo)", en: "to have (time) left", example: "Nos quedan veinte minutos de tráfico." },
      { es: "el casero", en: "the landlord", example: "¿Cómo te fue con el casero?" },
      { es: "el camino", en: "the way, the route", example: "Este no es el camino a mi casa." },
      { es: "la esquina", en: "the corner", example: "No me dejes en la esquina." },
      { es: "por fin", en: "finally, at last", example: "Por fin arreglaron la copiadora." },
    ],
    dialogue: {
      title: "En el carro de Rocío",
      situation: "Viernes, tráfico, veinte minutos hasta la casa",
      lines: [
        { speaker: "B", es: "Uf. Esto no se mueve.", en: "Ugh. This isn't moving." },
        { speaker: "A", es: "Bueno, ¿y qué más? Todavía nos quedan veinte minutos de tráfico.", en: "Okay, what else? We still have twenty minutes of traffic." },
        { speaker: "B", es: "No sé. Ya te conté todo hoy.", en: "I don't know. I already told you everything today." },
        { speaker: "A", es: "Se me olvidaba contarte que por fin arreglaron la copiadora.", en: "I forgot to tell you — they finally fixed the copier." },
        { speaker: "B", es: "¡No! ¿Después de seis semanas?", en: "No! After six weeks?" },
        { speaker: "A", es: "Seis. Oye, y cambiando de tema, ¿cómo te fue con el casero?", en: "Six. Hey, changing the subject — how did it go with your landlord?" },
        { speaker: "B", es: "Nada. Dice que en mayo. Lleva diciendo mayo desde enero.", en: "Nothing. He says May. He's been saying May since January." },
        { speaker: "A", es: "Ese hombre. Por cierto, este no es el camino a mi casa.", en: "That man. By the way, this isn't the way to my house." },
        { speaker: "B", es: "Ya sé. Voy por la avenida, que en el puente está peor.", en: "I know. I'm taking the avenue, the bridge is worse." },
        { speaker: "A", es: "Ah, bueno. Ah, y otra cosa, no me dejes en la esquina, que está lloviendo.", en: "Ah, okay. Oh, and one more thing — don't drop me at the corner, it's raining." },
        { speaker: "B", es: "Te dejo en la puerta. Pero entonces me cuentas lo de Yesenia.", en: "I'll drop you at the door. But then you tell me the Yesenia thing." },
      ],
    },
  },
];
