import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 11 — "Cuarenta minutos seguidos" (days 344–350).
 * Marlana and Camila's first intentional long Thursday session — bridges
 * and callbacks that hold forty minutes together without a script.
 */
export const priWeek11ReadingDays: ReadingDay[] = [
  {
    day: 344,
    themeEs: "Cuarenta minutos",
    storyTitle: "Cuarenta minutos seguidos",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el temporizador", en: "the timer", example: "Camila pone el temporizador en cuarenta minutos." },
      { es: "seguidos", en: "in a row, straight", example: "Cuarenta minutos seguidos, sin parar." },
      { es: "el puente", en: "the bridge (fig.)", example: "Los puentes sostienen una charla larga." },
      { es: "el callback", en: "the callback", example: "Volviendo a lo que dijiste es un callback." },
      { es: "el hilo", en: "the thread", example: "Donde íbamos retoma el hilo." },
    ],
    dialogue: {
      title: "El reto del jueves",
      situation: "Camila llega al café con un plan — cuarenta minutos seguidos",
      lines: [
        { speaker: "B", es: "Hoy no es un café normal. Hoy son cuarenta minutos seguidos. Sin teléfono. Sin inglés.", en: "Today isn't a normal coffee. Today is forty straight minutes. No phone. No English." },
        { speaker: "A", es: "¿Cuarenta? La semana pasada aguantamos veinticinco y ya me sentí orgullosa.", en: "Forty? Last week we held twenty-five and I already felt proud." },
        { speaker: "B", es: "Veinticinco fue profundizar. Cuarenta es arquitectura: puentes, callbacks, volver al hilo.", en: "Twenty-five was going deeper. Forty is architecture: bridges, callbacks, getting back to the thread." },
        { speaker: "A", es: "Suena a clase.", en: "Sounds like class." },
        { speaker: "B", es: "Suena a conversación de verdad. Te doy cinco stems y un temporizador.", en: "Sounds like a real conversation. I'll give you five stems and a timer." },
        { speaker: "A", es: "Volviendo a lo que dijiste del hospital, ¿sigue igual de caótico?", en: "Going back to what you said about the hospital — is it still as chaotic?" },
        { speaker: "B", es: "Bien. Ese es el primero. Callback. ¿Y si me interrumpo?", en: "Good. That's the first one. Callback. And if I interrupt?" },
        { speaker: "A", es: "Como te contaba, retomas. Eso me recuerda lo de la mamá de Diego. Antes de que se me olvide, Rocío te manda saludos.", en: "As I was telling you, you resume. That reminds me Diego's mom. Before I forget, Rocío says hi." },
        { speaker: "B", es: "Donde íbamos, yo explicaba los cinco stems. Empezamos. Temporizador en marcha.", en: "Where we were, I was explaining the five stems. Let's start. Timer running." },
      ],
    },
  },
  {
    day: 345,
    themeEs: "Volviendo a lo que dijiste",
    storyTitle: "Cuarenta minutos seguidos",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "cansado/a", en: "tired", example: "Las enfermeras cansadas, las maestras cansadas." },
      { es: "hace un rato", en: "a little while ago", example: "Dijiste eso hace un rato." },
      { es: "cerrar el círculo", en: "to close the loop", example: "Volviendo a lo que dijiste cierra el círculo." },
      { es: "demostrar", en: "to prove, to show", example: "Responder tarde demuestra que escuchaste." },
      { es: "el turno de noche", en: "the night shift", example: "Llegas tarde por el turno de noche." },
    ],
    dialogue: {
      title: "Minuto ocho, minuto veintitrés",
      situation: "Camila habla de enfermeras; Marlana responde quince minutos después",
      lines: [
        { speaker: "B", es: "En el hospital hay turnos donde las enfermeras no paran. Hablan rápido, comen mal, se olvidan de beber agua.", en: "At the hospital there are shifts where the nurses don't stop. They talk fast, eat badly, forget to drink water." },
        { speaker: "A", es: "Como te contaba, ayer una maestra me pidió ayuda y no supe decir que no.", en: "As I was telling you, yesterday a teacher asked me for help and I didn't know how to say no." },
        { speaker: "B", es: "¿Eso es callback o tangente?", en: "Is that a callback or a tangent?" },
        { speaker: "A", es: "Todavía no sé. Sigo…", en: "I don't know yet. I'm still…" },
        { speaker: "B", es: "Sigue. Estamos en el minuto doce.", en: "Keep going. We're at minute twelve." },
        { speaker: "A", es: "Eso me recuerda lo que dijiste de traducir cuando estás cansada. En la escuela pasa igual.", en: "That reminds me what you said about translating when you're tired. The same thing happens at school." },
        { speaker: "B", es: "Bien. Tangente que conecta. ¿Y lo de las enfermeras?", en: "Good. Tangent that connects. And the nurses?" },
        { speaker: "A", es: "Volviendo a lo que dijiste de las enfermeras cansadas, eso pasa en la escuela también. Perdón por tardar.", en: "Going back to what you said about tired nurses — that happens at school too. Sorry for taking so long." },
        { speaker: "B", es: "No pidas perdón. Tardar en responder demuestra que escuchaste todo el rato.", en: "Don't apologize. Answering late proves you were listening the whole time." },
        { speaker: "A", es: "Antes de que se me olvide, anoté tu idea del silencio en el cuaderno. Donde íbamos, comparábamos hospital y escuela.", en: "Before I forget, I wrote down your idea about silence in the notebook. Where we were, we were comparing hospital and school." },
      ],
    },
  },
  {
    day: 346,
    themeEs: "Como te contaba",
    storyTitle: "Cuarenta minutos seguidos",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el mesero", en: "the waiter", example: "Antes de que viniera el mesero." },
      { es: "interrumpir", en: "to interrupt", example: "El mesero interrumpe y retomas con como te contaba." },
      { es: "retomar", en: "to pick up again, to resume", example: "Retomar es más difícil que empezar." },
      { es: "le quería comentar", en: "I wanted to tell you (usted)", example: "Dije le quería comentar, no te quería comentar." },
      { es: "en la cabeza", en: "in one's head", example: "Tenía dos versiones en la cabeza." },
    ],
    dialogue: {
      title: "Pasa el mesero",
      situation: "Una interrupción — y Marlana retoma la historia de Yusuf",
      lines: [
        { speaker: "A", es: "Como te contaba, la madre se sentó y yo tenía dos versiones en la cabeza.", en: "As I was telling you, the mother sat down and I had two versions in my head." },
        { speaker: "B", es: "¿Tú y usted otra vez?", en: "Tú and usted again?" },
        { speaker: "A", es: "Otra vez. Dije \"le quería comentar\" y no \"te quería comentar.\" Funcionó.", en: "Again. I said \"le quería comentar\" and not \"te quería comentar.\" It worked." },
        { speaker: "B", es: "¿Café?", en: "Coffee?" },
        { speaker: "A", es: "Sí, gracias. Volviendo a lo que dijiste antes de que viniera el mesero, sí, me pasa igual con el silencio incómodo.", en: "Yes, thanks. Going back to what you said before the waiter came — yes, the same thing happens to me with awkward silence." },
        { speaker: "B", es: "Bien retomado. ¿Y Yusuf?", en: "Well resumed. And Yusuf?" },
        { speaker: "A", es: "Eso me recuerda la semana de usted, cuando ensayaba con Rocío. Yusuf sonrió cuando lo mencioné.", en: "That reminds me usted week, when I was rehearsing with Rocío. Yusuf smiled when I mentioned him." },
        { speaker: "B", es: "Antes de que se me olvide — eso va en el cuaderno también.", en: "Before I forget — that goes in the notebook too." },
        { speaker: "A", es: "Donde íbamos, yo contaba la reunión con la madre de Yusuf. Llevamos veinticinco minutos sin mirar el reloj.", en: "Where we were, I was telling the meeting with Yusuf's mom. We've gone twenty-five minutes without looking at the clock." },
        { speaker: "B", es: "Eso es señal.", en: "That's a sign." },
      ],
    },
  },
  {
    day: 347,
    themeEs: "Eso me recuerda",
    storyTitle: "Cuarenta minutos seguidos",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "traducir", en: "to translate", example: "La niña traducía para su mamá." },
      { es: "el tangente", en: "the tangent", example: "Un tangente bien cerrado no rompe la charla." },
      { es: "enlazar", en: "to link, to connect", example: "Los recuerdos no interrumpen, enlazan." },
      { es: "solo inglés en casa", en: "English only at home", example: "La mamá de Diego quería solo inglés en casa." },
      { es: "los dos idiomas", en: "both languages", example: "Diego leyó en los dos idiomas." },
    ],
    dialogue: {
      title: "La niña de ocho años",
      situation: "Camila cuenta un hospital; Marlana conecta con la escuela",
      lines: [
        { speaker: "B", es: "Ayer una señora no entendía a la doctora. La niña tenía ocho años y tradujo el diagnóstico mejor que nosotras.", en: "Yesterday a woman didn't understand the doctor. The girl was eight and translated the diagnosis better than we did." },
        { speaker: "A", es: "Eso me recuerda lo de la mamá de Diego y la reunión que no terminé.", en: "That reminds me Diego's mom and the meeting I never finished." },
        { speaker: "B", es: "Tangente. ¿Lo sigues?", en: "Tangent. Are you going to follow it?" },
        { speaker: "A", es: "Como te contaba, la mamá de Diego quería solo inglés en casa. En el café dijimos que quitar el español no acelera nada.", en: "As I was telling you, Diego's mom wanted English only at home. At the café we said taking away Spanish doesn't speed anything up." },
        { speaker: "B", es: "Semana ocho. Buen callback.", en: "Week eight. Good callback." },
        { speaker: "A", es: "Volviendo a lo que dijiste de la señora que traducía para su mamá, eso es Diego otra vez.", en: "Going back to what you said about the woman who translated for her mom — that's Diego again." },
        { speaker: "B", es: "Exacto. Hospital y escuela, un hilo.", en: "Exactly. Hospital and school, one thread." },
        { speaker: "A", es: "Antes de que se me olvide, Diego leyó en los dos idiomas este fin de semana.", en: "Before I forget, Diego read in both languages this weekend." },
        { speaker: "B", es: "Donde íbamos, tú contabas lo del hospital y yo conecté con la escuela. Faltan diez minutos y no se siente.", en: "Where we were, you were telling the hospital story and I connected it to school. Ten minutes left and it doesn't feel like it." },
        { speaker: "A", es: "Eso me recuerda por qué pusimos conversación larga en las metas.", en: "That reminds me why we put long conversation on the goals." },
      ],
    },
  },
  {
    day: 348,
    themeEs: "Tres cosas que casi se pierden",
    storyTitle: "Cuarenta minutos seguidos",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "el pasaje", en: "the ticket (travel)", example: "¿Ya compró el pasaje?" },
      { es: "meterse", en: "to butt in, to step in", example: "Rocío no se metió." },
      { es: "preguntar por alguien", en: "to ask after someone", example: "La mamá de Diego preguntó por ti." },
      { es: "para una cosa", en: "for something (unspecified)", example: "Necesito tu dirección para una cosa." },
      { es: "donde íbamos", en: "where were we", example: "Donde íbamos, no habías terminado." },
    ],
    dialogue: {
      title: "Minuto treinta y uno",
      situation: "Tres hilos abiertos y el café todavía caliente",
      lines: [
        { speaker: "A", es: "Volviendo a lo que dijiste de tu hermano, ¿ya compró el pasaje?", en: "Going back to what you said about your brother — did he buy the ticket yet?" },
        { speaker: "B", es: "Todavía no. Está esperando la entrevista.", en: "Not yet. He's waiting on the interview." },
        { speaker: "A", es: "Como te contaba, Rocío me oyó hablar con un papá y no se metió.", en: "As I was telling you, Rocío heard me talking with a parent and didn't step in." },
        { speaker: "B", es: "¿Y antes sí se metía?", en: "And before she used to?" },
        { speaker: "A", es: "Antes terminaba mis frases. Ayer se quedó callada hasta el final.", en: "She used to finish my sentences. Yesterday she stayed quiet till the end." },
        { speaker: "B", es: "Eso es confianza.", en: "That's trust." },
        { speaker: "A", es: "Eso me recuerda que la mamá de Diego preguntó por ti.", en: "That reminds me — Diego's mom asked about you." },
        { speaker: "B", es: "¿Por mí? Si no me conoce.", en: "About me? She doesn't even know me." },
        { speaker: "A", es: "Le hablé de ti. Ah — antes de que se me olvide, necesito tu dirección para una cosa.", en: "I told her about you. Oh — before I forget, I need your address for something." },
        { speaker: "B", es: "¿Para qué cosa?", en: "For what something?" },
        { speaker: "A", es: "Ya lo sabrás. Donde íbamos, me estabas contando por qué no se metió.", en: "You'll find out. Where were we — you were telling me why she didn't step in." },
      ],
    },
  },
  {
    day: 349,
    themeEs: "Cuando se acaba el café",
    storyTitle: "Cuarenta minutos seguidos",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "no le he contestado", en: "i haven't answered her", example: "Rocío me escribió y no le he contestado." },
      { es: "el grupo del sábado", en: "the saturday group", example: "Me quiere en el grupo del sábado." },
      { es: "ni una vez", en: "not once", example: "No miraste el teléfono ni una vez." },
      { es: "lo de tu mamá", en: "the thing about your mom", example: "No habías terminado lo de tu mamá." },
      { es: "las tazas", en: "the cups", example: "Las tazas ya están vacías." },
    ],
    dialogue: {
      title: "Tazas vacías",
      situation: "Nadie se ha levantado y la mesa sigue llena",
      lines: [
        { speaker: "A", es: "Volviendo a lo que dijiste de tu hermano, ¿dónde va a dormir?", en: "Going back to what you said about your brother — where is he going to sleep?" },
        { speaker: "B", es: "En mi sala. Dos meses, dice él.", en: "In my living room. Two months, he says." },
        { speaker: "A", es: "Dos meses de un hermano son seis.", en: "Two months of a brother is six." },
        { speaker: "B", es: "No me lo digas. ¿Y tú? ¿Le contestaste a Rocío?", en: "Don't tell me. And you? Did you answer Rocío?" },
        { speaker: "A", es: "Como te contaba, Rocío me quiere en el grupo del sábado y no le he contestado.", en: "As I was telling you, Rocío wants me in the Saturday group and I still haven't answered her." },
        { speaker: "B", es: "Llevas cuatro días.", en: "It's been four days." },
        { speaker: "A", es: "Ya sé. Eso me recuerda que mañana tengo que estar en el colegio a las siete.", en: "I know. That reminds me I have to be at school at seven tomorrow." },
        { speaker: "B", es: "Entonces nos vamos.", en: "Then let's go." },
        { speaker: "A", es: "Todavía no. Antes de que se me olvide, gracias por no mirar el teléfono ni una vez.", en: "Not yet. Before I forget — thanks for not looking at your phone once." },
        { speaker: "B", es: "Cuarenta y tres minutos. Los conté.", en: "Forty-three minutes. I counted." },
        { speaker: "A", es: "Donde íbamos, no habías terminado lo de tu mamá.", en: "Where were we — you hadn't finished the part about your mom." },
      ],
    },
  },
  {
    day: 350,
    themeEs: "Repaso: Conversación larga I",
    isRecap: true,
    vocab: [
      { es: "al final", en: "in the end, after all", example: "¿Al final viene en marzo o no?" },
      { es: "cómo te fue", en: "how did it go for you", example: "Nunca me contaste cómo te fue." },
      { es: "la cita", en: "the appointment", example: "La cita con el doctor era el jueves." },
      { es: "no me dejes olvidarlo", en: "don't let me forget it", example: "El jueves, no me dejes olvidarlo." },
      { es: "el camino", en: "the way, the route", example: "Este no es el camino a mi casa." },
    ],
    dialogue: {
      title: "Una hora con mamá",
      situation: "Domingo por la noche — la llamada pasó de la hora sin que nadie se diera cuenta",
      lines: [
        { speaker: "A", es: "Volviendo a lo que dijiste de la tía, ¿al final viene en marzo o no?", en: "Going back to what you said about my aunt — is she actually coming in March or not?" },
        { speaker: "B", es: "Dice que sí. Pero ya sabes cómo es.", en: "She says yes. But you know how she is." },
        { speaker: "A", es: "Que compre el pasaje y ahí sí le creo.", en: "Let her buy the ticket and then I'll believe her." },
        { speaker: "B", es: "Eso mismo le dije yo. ¿Y tú cómo vas con lo del colegio?", en: "That's exactly what I told her. And how are you doing with the school thing?" },
        { speaker: "A", es: "Como te contaba, al final no cortan la clase.", en: "As I was telling you, in the end they're not cutting the class." },
        { speaker: "B", es: "Ay, mija, qué bueno. ¿Y eso cómo pasó?", en: "Oh, honey, that's wonderful. And how did that happen?" },
        { speaker: "A", es: "Fuimos dos a la junta en vez de una. Eso me recuerda que nunca me contaste cómo te fue en la cita.", en: "Two of us went to the meeting instead of one. That reminds me — you never told me how the appointment went." },
        { speaker: "B", es: "Bien. Todo bien. No me cambies el tema.", en: "Fine. Everything's fine. Don't change the subject on me." },
        { speaker: "A", es: "\"Bien\" no es una respuesta, mamá. Antes de que se me olvide, el cumpleaños de Kevin es el jueves, no me dejes olvidarlo.", en: "\"Fine\" isn't an answer, Mom. Before I forget — Kevin's birthday is Thursday, don't let me forget it." },
        { speaker: "B", es: "Yo te escribo el miércoles. Bueno, y la vecina…", en: "I'll text you Wednesday. Anyway, and the neighbor…" },
        { speaker: "A", es: "Donde íbamos, me estabas contando lo de la vecina y el árbol.", en: "Where were we — you were telling me about the neighbor and the tree." },
      ],
    },
  },
];
