import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 9 — "Profundizar" (days 330–336).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week9-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek9SpeakDays: SpeakDay[] = [
  {
    day: 330,
    themeEs: "El problema de Rocío",
    themeEn: "Rocío's problem",
    missionEs: "No dejes morir un tema con solo \"qué mal.\"",
    missionEn: "Don't kill a topic with just \"that's too bad.\"",
    line: "Rocío dijo que tuvo un problema. Tú dijiste lo siento y la dejaste ir.",
    lineEn: "Rocío said she had a problem. You said you were sorry and let her go.",
    prompts: [
      {
        id: "d330-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? What happened at the meeting?",
        spanish: "¿Y eso? ¿Qué pasó en la reunión?",
        situationLabel: "El hilo que sueltas",
        why: "Two words that refuse to let the topic die — you say them like you mean to stay.",
        wordHints: [
          { en: "and that", es: "y eso" },
          { en: "what happened", es: "qué pasó" },
          { en: "at the meeting", es: "en la reunión" },
        ],
      },
      {
        id: "d330-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? They pulled you in without warning?",
        spanish: "¿Cómo así? ¿Te metieron sin avisar?",
        situationLabel: "Pidiendo el cómo",
        why: "*¿Cómo así?* asks for the machinery — not whether it happened, but how on earth it happened.",
        wordHints: [
          { en: "how so", es: "cómo así" },
          { en: "they pulled you in", es: "te metieron" },
          { en: "without warning", es: "sin avisar" },
        ],
      },
      {
        id: "d330-y-que-paso",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the dad afterward?",
        spanish: "¿Y qué pasó con el papá después?",
        situationLabel: "Un hilo con nombre",
        why: "Name the person — *el papá* — and the vague problem becomes a scene.",
        wordHints: [
          { en: "what happened with", es: "qué pasó con" },
          { en: "the dad", es: "el papá" },
          { en: "afterward", es: "después" },
        ],
      },
      {
        id: "d330-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? Did they send you an email?",
        spanish: "¿Y después? ¿Te mandaron un correo?",
        situationLabel: "El beat que falta",
        why: "*¿Y después?* is for the part people skip when they're being polite.",
        wordHints: [
          { en: "and then", es: "y después" },
          { en: "did they send you", es: "te mandaron" },
          { en: "an email", es: "un correo" },
        ],
      },
      {
        id: "d330-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? They blamed you?",
        spanish: "¿En serio? ¿Te echaron la culpa a ti?",
        situationLabel: "Reacción que sigue",
        why: "Sounds like disbelief — works like a follow-up. The story keeps going because you won't accept the short version.",
        wordHints: [
          { en: "seriously", es: "en serio" },
          { en: "they blamed you", es: "te echaron la culpa" },
        ],
      },
    ],
  },
  {
    day: 331,
    themeEs: "¿Y eso?",
    themeEn: "And that?",
    missionEs: "Practica la pregunta más corta que mantiene vivo un tema.",
    missionEn: "Practice the shortest question that keeps a topic alive.",
    line: "Te dio una frase. Detrás había cinco más.",
    lineEn: "She gave you one sentence. There were five more behind it.",
    prompts: [
      {
        id: "d331-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? What problem did Rocío have?",
        spanish: "¿Y eso? ¿Qué problema tuvo Rocío?",
        situationLabel: "En el café con Camila",
        why: "*¿Y eso?* is the cheapest follow-up there is — and the hardest to skip once you know it works.",
        wordHints: [
          { en: "what problem", es: "qué problema" },
          { en: "did rocío have", es: "tuvo rocío" },
        ],
      },
      {
        id: "d331-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? She only told you that and left?",
        spanish: "¿Cómo así? ¿Te dijo solo eso y ya?",
        situationLabel: "Reconstruyendo el pasillo",
        why: "*¿Te dijo solo eso y ya?* — the whole missed moment in six words.",
        wordHints: [
          { en: "she only told you that", es: "te dijo solo eso" },
          { en: "and left", es: "y ya" },
        ],
      },
      {
        id: "d331-y-que-paso",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the girl's reading group?",
        spanish: "¿Y qué pasó con la niña del grupo de lectura?",
        situationLabel: "El detalle que viene",
        why: "You're guessing the thread before you have it — that's what follow-ups train.",
        wordHints: [
          { en: "what happened with", es: "qué pasó con" },
          { en: "the girl", es: "la niña" },
          { en: "reading group", es: "grupo de lectura" },
        ],
      },
      {
        id: "d331-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? Did you look for her in the hallway?",
        spanish: "¿Y después? ¿La buscaste en el pasillo?",
        situationLabel: "Lo que no hiciste",
        why: "Practicing on yourself first — *¿La buscaste?* is the follow-up you owe Rocío tomorrow.",
        wordHints: [
          { en: "did you look for her", es: "la buscaste" },
          { en: "in the hallway", es: "en el pasillo" },
        ],
      },
      {
        id: "d331-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? You only said \"that's too bad\"?",
        spanish: "¿En serio? ¿Solo dijiste \"qué mal\"?",
        situationLabel: "Camila te empuja",
        why: "Camila's *¿En serio?* isn't judgment — it's *sigue, cuenta más*.",
        wordHints: [
          { en: "you only said", es: "solo dijiste" },
          { en: "that's too bad", es: "qué mal" },
        ],
      },
    ],
  },
  {
    day: 332,
    themeEs: "¿Cómo así?",
    themeEn: "How so?",
    missionEs: "Pregunta cómo pasó, no solo qué pasó.",
    missionEn: "Ask how it happened, not just what happened.",
    line: "La directora la agarró en la copiadora, sin avisar, entre clases.",
    lineEn: "The principal grabbed her at the copier, with no warning, between classes.",
    prompts: [
      {
        id: "d332-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? They asked you to translate at the parent meeting?",
        spanish: "¿Y eso? ¿Te pidieron traducir en la reunión?",
        situationLabel: "El audio de Rocío",
        why: "Rocío's text arrives — *¿Y eso?* keeps you on the same thread instead of starting over.",
        wordHints: [
          { en: "they asked you", es: "te pidieron" },
          { en: "to translate", es: "traducir" },
          { en: "at the meeting", es: "en la reunión" },
        ],
      },
      {
        id: "d332-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? The principal grabbed her at the copier?",
        spanish: "¿Cómo así? ¿La directora la agarró en la copiadora?",
        situationLabel: "La maquinaria",
        why: "*¿Cómo así?* asks for the machinery — *en la copiadora* is the detail that makes it real.",
        wordHints: [
          { en: "the principal", es: "la directora" },
          { en: "grabbed her", es: "la agarró" },
          { en: "at the copier", es: "en la copiadora" },
        ],
      },
      {
        id: "d332-y-que-paso",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the dad when he heard the answer?",
        spanish: "¿Y qué pasó con el papá cuando oyó la respuesta?",
        situationLabel: "Dentro de la reunión",
        why: "*Cuando oyó la respuesta* — you're already inside the scene, not summarizing from outside.",
        wordHints: [
          { en: "when he heard", es: "cuando oyó" },
          { en: "the answer", es: "la respuesta" },
        ],
      },
      {
        id: "d332-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? What did the dad ask?",
        spanish: "¿Y después? ¿Qué preguntó el papá?",
        situationLabel: "Rocío cuenta",
        why: "One beat at a time — *¿Qué preguntó?* pulls the next sentence out of her.",
        wordHints: [
          { en: "what did he ask", es: "qué preguntó" },
          { en: "the dad", es: "el papá" },
        ],
      },
      {
        id: "d332-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? They pull her in like that, with no prep?",
        spanish: "¿En serio? ¿La meten así, sin preparación?",
        situationLabel: "Tu indignación",
        why: "*Sin preparación* — your reaction keeps the talk going and tells Rocío you're on her side.",
        wordHints: [
          { en: "they pull her in", es: "la meten" },
          { en: "like that", es: "así" },
          { en: "with no prep", es: "sin preparación" },
        ],
      },
    ],
  },
  {
    day: 333,
    themeEs: "¿Y qué pasó con…?",
    themeEn: "And what happened with…?",
    missionEs: "Elige un hilo — el papá, la niña, el correo — y no lo sueltes.",
    missionEn: "Pick one thread — the dad, the kid, the email — and don't let go.",
    line: "Bajaron a la niña de grupo de lectura y nadie le dijo al papá.",
    lineEn: "They moved the girl down a reading group and nobody told her dad.",
    prompts: [
      {
        id: "d333-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? They moved the girl down a reading group?",
        spanish: "¿Y eso? ¿Movieron a la niña de grupo?",
        situationLabel: "La queja del papá",
        why: "New detail lands — *¿Y eso?* catches it without changing subject.",
        wordHints: [
          { en: "they moved", es: "movieron" },
          { en: "the girl", es: "la niña" },
          { en: "down a group", es: "de grupo" },
        ],
      },
      {
        id: "d333-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? Did it sound like punishment for the girl?",
        spanish: "¿Cómo así? ¿Sonó a castigo para la niña?",
        situationLabel: "Por qué sonó mal",
        why: "*Sonó a castigo* — translation without context sounds like blame. That's the whole problem.",
        wordHints: [
          { en: "did it sound like", es: "sonó a" },
          { en: "punishment", es: "castigo" },
          { en: "for the girl", es: "para la niña" },
        ],
      },
      {
        id: "d333-y-que-paso",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the dad when he read the email?",
        spanish: "¿Y qué pasó con el papá cuando leyó el correo?",
        situationLabel: "Hilo con nombre",
        why: "Name the person — *el papá* — and the vague problem becomes a scene you can see.",
        wordHints: [
          { en: "what happened with", es: "qué pasó con" },
          { en: "when he read", es: "cuando leyó" },
          { en: "the email", es: "el correo" },
        ],
      },
      {
        id: "d333-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? Did the dad talk to the principal?",
        spanish: "¿Y después? ¿El papá habló con la directora?",
        situationLabel: "Después de la reunión",
        why: "The meeting ended — *¿Y después?* is where half the story usually gets lost.",
        wordHints: [
          { en: "did he talk to", es: "habló con" },
          { en: "the principal", es: "la directora" },
        ],
      },
      {
        id: "d333-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? They blamed Rocío?",
        spanish: "¿En serio? ¿Le echaron la culpa a Rocío?",
        situationLabel: "En el café",
        why: "*¿En serio?* at the café table — disbelief that keeps you listening, not performing shock.",
        wordHints: [
          { en: "they blamed", es: "le echaron la culpa" },
          { en: "rocío", es: "rocío" },
        ],
      },
    ],
  },
  {
    day: 334,
    themeEs: "¿Y después?",
    themeEn: "And then?",
    missionEs: "Pregunta qué pasó cuando terminó la reunión.",
    missionEn: "Ask what happened after the meeting ended.",
    line: "La reunión terminó. Ahí se pierde la mitad de la historia.",
    lineEn: "The meeting ended. That's when half the story usually gets lost.",
    prompts: [
      {
        id: "d334-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? They sent her an email the same day?",
        spanish: "¿Y eso? ¿Le mandaron un correo el mismo día?",
        situationLabel: "El correo",
        why: "The email is a new beat on the same thread — not a new topic.",
        wordHints: [
          { en: "they sent her", es: "le mandaron" },
          { en: "an email", es: "un correo" },
          { en: "the same day", es: "el mismo día" },
        ],
      },
      {
        id: "d334-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? They told her she \"overstepped\"?",
        spanish: "¿Cómo así? ¿Le dijeron que \"se pasó de la raya\"?",
        situationLabel: "Las palabras del correo",
        why: "*Se pasó de la raya* — blame by email, not in person. The how matters as much as the what.",
        wordHints: [
          { en: "they told her", es: "le dijeron" },
          { en: "she overstepped", es: "se pasó de la raya" },
        ],
      },
      {
        id: "d334-y-que-paso",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the bilingual coordinator stipend?",
        spanish: "¿Y qué pasó con el coordinador bilingüe?",
        situationLabel: "Lo que Rocío temía",
        why: "*El coordinador bilingüe* — the role Rocío thought she was about to lose.",
        wordHints: [
          { en: "what happened with", es: "qué pasó con" },
          { en: "bilingual coordinator", es: "coordinador bilingüe" },
        ],
      },
      {
        id: "d334-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? Did someone tell her it wasn't her fault?",
        spanish: "¿Y después? ¿Alguien le dijo que no fue su culpa?",
        situationLabel: "El beat después",
        why: "*¿Y después?* is for the beat after the beat — the part people skip when they're being polite.",
        wordHints: [
          { en: "did someone tell her", es: "alguien le dijo" },
          { en: "it wasn't her fault", es: "no fue su culpa" },
        ],
      },
      {
        id: "d334-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? They sent you that in writing?",
        spanish: "¿En serio? ¿Te mandaron eso por escrito?",
        situationLabel: "Con Rocío en persona",
        why: "Marlana finally asks Rocío directly — *¿En serio?* opens the door instead of closing it.",
        wordHints: [
          { en: "they sent you that", es: "te mandaron eso" },
          { en: "in writing", es: "por escrito" },
        ],
      },
    ],
  },
  {
    day: 335,
    themeEs: "¿En serio?",
    themeEn: "Seriously?",
    missionEs: "La incredulidad no cambia de tema. Lo mantiene más fuerte.",
    missionEn: "Disbelief isn't changing the subject. It's staying on it harder.",
    line: "La directora pidió perdón. El sistema quedó igual.",
    lineEn: "The principal apologized. The system stayed the same.",
    prompts: [
      {
        id: "d335-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? The principal apologized?",
        spanish: "¿Y eso? ¿La directora pidió disculpas?",
        situationLabel: "El giro",
        why: "Plot twist on the same thread — *¿Y eso?* catches it without starting a new conversation.",
        wordHints: [
          { en: "the principal", es: "la directora" },
          { en: "apologized", es: "pidió disculpas" },
        ],
      },
      {
        id: "d335-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? Sorry but the same system?",
        spanish: "¿Cómo así? ¿Perdón pero mismo sistema?",
        situationLabel: "Apology without change",
        why: "*Perdón pero mismo sistema* — the follow-up that names what an apology didn't fix.",
        wordHints: [
          { en: "sorry", es: "perdón" },
          { en: "but same system", es: "pero mismo sistema" },
        ],
      },
      {
        id: "d335-y-que-paso",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the girl's reading group?",
        spanish: "¿Y qué pasó con el grupo de lectura de la niña?",
        situationLabel: "El hilo original",
        why: "Five turns in and you're still on the kid — that's profundizar, not gossip.",
        wordHints: [
          { en: "reading group", es: "grupo de lectura" },
          { en: "the girl's", es: "de la niña" },
        ],
      },
      {
        id: "d335-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? Did you offer to talk to the principal?",
        spanish: "¿Y después? ¿Le ofreciste hablar con la directora?",
        situationLabel: "Lo que ofreciste",
        why: "*¿Le ofreciste?* — the follow-up turns into action, still on the same story.",
        wordHints: [
          { en: "did you offer", es: "le ofreciste" },
          { en: "to talk to", es: "hablar con" },
          { en: "the principal", es: "la directora" },
        ],
      },
      {
        id: "d335-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? Rocío, that's not okay.",
        spanish: "¿En serio? Rocío, eso no está bien.",
        situationLabel: "Con Rocío, en persona",
        why: "*¿En serio?* said to a friend isn't doubt — it's *sigue contando*. You're holding the door open.",
        wordHints: [
          { en: "that's not okay", es: "eso no está bien" },
        ],
      },
    ],
  },
  {
    day: 336,
    themeEs: "Repaso: Profundizar",
    themeEn: "Review: Going deeper",
    missionEs: "Camila soltó una frase. Sácale la historia entera.",
    missionEn: "Camila dropped one sentence. Get the whole story out of her.",
    line: "Camila dijo \"mi hermano se viene en agosto\" y siguió tomando café.",
    lineEn: "Camila said \"my brother's coming in August\" and went back to her coffee.",
    prompts: [
      {
        id: "d336-y-eso",
        frameStem: "¿Y eso?…",
        english: "And that? Your brother is moving here?",
        spanish: "¿Y eso? ¿Tu hermano se viene para acá?",
        situationLabel: "La frase que soltó",
        why: "*Venirse* rather than *venir* — the reflexive is what makes it a move, not a visit.",
        wordHints: [
          { en: "and that", es: "y eso" },
          { en: "is moving here", es: "se viene para acá" },
        ],
      },
      {
        id: "d336-como-asi",
        frameStem: "¿Cómo así?…",
        english: "How so? Did he get the job, or is he coming with nothing?",
        spanish: "¿Cómo así? ¿Consiguió el trabajo o se viene sin nada?",
        situationLabel: "La parte que no cuadra",
        why: "Offering two versions is a faster way to get the real one than asking an open question.",
        wordHints: [
          { en: "how so", es: "cómo así" },
          { en: "did he get", es: "consiguió" },
          { en: "with nothing", es: "sin nada" },
        ],
      },
      {
        id: "d336-y-que-paso-con",
        frameStem: "¿Y qué pasó con…?",
        english: "And what happened with the apartment he had in Medellín?",
        spanish: "¿Y qué pasó con el apartamento que tenía en Medellín?",
        situationLabel: "Lo que deja atrás",
        why: "Asking about what someone left behind gets you more of a story than asking about where they're going.",
        wordHints: [
          { en: "what happened with", es: "qué pasó con" },
          { en: "the apartment", es: "el apartamento" },
          { en: "he had", es: "que tenía" },
        ],
      },
      {
        id: "d336-y-despues",
        frameStem: "¿Y después?…",
        english: "And then? Did he tell your mom, or did that fall to you?",
        spanish: "¿Y después? ¿Le dijo a tu mamá o te tocó a ti?",
        situationLabel: "Quién se lo dijo a la mamá",
        why: "*Tocarle a alguien* — for a job to fall to you. There's no volunteering in it, which is the point.",
        wordHints: [
          { en: "and then", es: "y después" },
          { en: "did he tell", es: "le dijo" },
          { en: "did it fall to you", es: "te tocó a ti" },
        ],
      },
      {
        id: "d336-en-serio",
        frameStem: "¿En serio?…",
        english: "Seriously? He's staying with you?",
        spanish: "¿En serio? ¿Se va a quedar contigo?",
        situationLabel: "La parte que no esperabas",
        why: "*¿En serio?* isn't doubt here — it's the sound of you wanting the next sentence.",
        wordHints: [
          { en: "seriously", es: "en serio" },
          { en: "he's staying", es: "se va a quedar" },
          { en: "with you", es: "contigo" },
        ],
      },
    ],
  },
];
