import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 10 — "Sin preparación" (days 337–343).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week10-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek10SpeakDays: SpeakDay[] = [
  {
    day: 337,
    themeEs: "El juego de Camila",
    themeEn: "Camila's game",
    missionEs: "Responde la primera pregunta sin aviso con lo primero que se te ocurra.",
    missionEn: "Answer the first surprise question with whatever comes first.",
    line: "Sin preparación. Sin notas. Sin tiempo para pensar en inglés.",
    lineEn: "No prep. No notes. No time to think in English.",
    prompts: [
      {
        id: "d337-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is Atlanta, not Boston.",
        spanish: "Lo primero que se me ocurre es Atlanta, no Boston.",
        situationLabel: "Primera pregunta sin aviso",
        why: "*Lo primero que se me ocurre* buys you a real answer without pretending you had one ready — the stem is the prep.",
        wordHints: [
          { en: "the first thing that comes to mind", es: "lo primero que se me ocurre" },
          { en: "atlanta", es: "atlanta" },
          { en: "not boston", es: "no boston" },
        ],
      },
      {
        id: "d337-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "Let's see what comes out — don't judge me yet.",
        spanish: "A ver qué sale — no me juzgues todavía.",
        situationLabel: "Empezando a hablar",
        why: "*A ver qué sale* is permission to be messy. You say it and then you talk.",
        wordHints: [
          { en: "let's see what comes out", es: "a ver qué sale" },
          { en: "don't judge me yet", es: "no me juzgues todavía" },
        ],
      },
      {
        id: "d337-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "No idea, but it sounds like something from my childhood.",
        spanish: "Ni idea, pero suena a algo de mi infancia.",
        situationLabel: "Sin respuesta lista",
        why: "*Ni idea, pero…* keeps you in the conversation when a flat *no sé* would shut it down.",
        wordHints: [
          { en: "no idea", es: "ni idea" },
          { en: "but it sounds like", es: "pero suena a" },
          { en: "something from my childhood", es: "algo de mi infancia" },
        ],
      },
      {
        id: "d337-depende",
        frameStem: "Depende, creo que…",
        english: "It depends, I think on Monday and Friday I'm not the same person.",
        spanish: "Depende, creo que el lunes y el viernes no soy la misma.",
        situationLabel: "Sin sí o no",
        why: "*Depende, creo que…* is how adults actually answer — not evasive, just honest about context.",
        wordHints: [
          { en: "it depends", es: "depende" },
          { en: "i think", es: "creo que" },
          { en: "monday and friday", es: "el lunes y el viernes" },
          { en: "i'm not the same", es: "no soy la misma" },
        ],
      },
      {
        id: "d337-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say that fear is normal and you keep going anyway.",
        spanish: "Creo que diría que el miedo es normal y sigue igual.",
        situationLabel: "Respuesta hipotética",
        why: "*Creo que diría que…* lets you rehearse kindness without claiming you've mastered it.",
        wordHints: [
          { en: "i think i'd say", es: "creo que diría que" },
          { en: "fear is normal", es: "el miedo es normal" },
          { en: "you keep going anyway", es: "sigue igual" },
        ],
      },
    ],
  },
  {
    day: 338,
    themeEs: "A ver qué sale",
    themeEn: "Let's see what comes out",
    missionEs: "Empieza a hablar sin orden y encuentra el punto en el camino.",
    missionEn: "Start talking without a plan and find the point on the way.",
    line: "No necesitas la versión pulida para quedarte en español.",
    lineEn: "You don't need the polished version to stay in Spanish.",
    prompts: [
      {
        id: "d338-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is my grandmother in the kitchen.",
        spanish: "Lo primero que se me ocurre es mi abuela en la cocina.",
        situationLabel: "Asociación rápida",
        why: "Gut first, polish later — *lo primero que se me ocurre* is the gut.",
        wordHints: [
          { en: "my grandmother", es: "mi abuela" },
          { en: "in the kitchen", es: "en la cocina" },
        ],
      },
      {
        id: "d338-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "Let's see what comes out — I'll start and you stop me if I get lost.",
        spanish: "A ver qué sale — empiezo y tú me paras si me pierdo.",
        situationLabel: "Improvisando en vivo",
        why: "Naming the improv out loud makes it a game, not a failure.",
        wordHints: [
          { en: "i'll start", es: "empiezo" },
          { en: "you stop me", es: "tú me paras" },
          { en: "if i get lost", es: "si me pierdo" },
        ],
      },
      {
        id: "d338-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "No idea, but I remember the color of the wall.",
        spanish: "Ni idea, pero me acuerdo del color de la pared.",
        situationLabel: "Memoria parcial",
        why: "One detail is enough to stay in the story — you don't need the whole picture.",
        wordHints: [
          { en: "i remember", es: "me acuerdo" },
          { en: "the color of the wall", es: "del color de la pared" },
        ],
      },
      {
        id: "d338-depende",
        frameStem: "Depende, creo que…",
        english: "It depends, I think if you ask me in English I think differently.",
        spanish: "Depende, creo que si me preguntas en inglés pienso distinto.",
        situationLabel: "Dos versiones de ti",
        why: "*Pienso distinto* — not wrong, just different. Bilingual honesty without apology.",
        wordHints: [
          { en: "if you ask me", es: "si me preguntas" },
          { en: "in english", es: "en inglés" },
          { en: "i think differently", es: "pienso distinto" },
        ],
      },
      {
        id: "d338-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say you don't have to sound good the first time.",
        spanish: "Creo que diría que no tiene que sonar bien la primera vez.",
        situationLabel: "Consejo sin guion",
        why: "Advice you'd give a student — rehearsed out loud, not read from a card.",
        wordHints: [
          { en: "doesn't have to sound good", es: "no tiene que sonar bien" },
          { en: "the first time", es: "la primera vez" },
        ],
      },
    ],
  },
  {
    day: 339,
    themeEs: "Ni idea, pero",
    themeEn: "No idea, but",
    missionEs: "Di que no sabes — y sigue en la conversación.",
    missionEn: "Say you don't know — and stay in the conversation.",
    line: "La honestidad también es respuesta.",
    lineEn: "Honesty is an answer too.",
    prompts: [
      {
        id: "d339-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is that I don't know anything about that.",
        spanish: "Lo primero que se me ocurre es que no sé nada de eso.",
        situationLabel: "Después de una pausa",
        why: "Even the blank has a first thought — and sometimes it's *no sé nada*.",
        wordHints: [
          { en: "i don't know anything", es: "no sé nada" },
          { en: "about that", es: "de eso" },
        ],
      },
      {
        id: "d339-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "Let's see what comes out if I look at it from my job.",
        spanish: "A ver qué sale si lo miro desde mi trabajo.",
        situationLabel: "Intentando igual",
        why: "*Desde mi trabajo* — when you don't know the topic, you know your angle.",
        wordHints: [
          { en: "if i look at it", es: "si lo miro" },
          { en: "from my job", es: "desde mi trabajo" },
        ],
      },
      {
        id: "d339-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "No idea, but I care what you think.",
        spanish: "Ni idea, pero me importa lo que piensas tú.",
        situationLabel: "La respuesta valiente",
        why: "*Ni idea, pero…* keeps you in the conversation when *no sé* would shut it down.",
        wordHints: [
          { en: "i care", es: "me importa" },
          { en: "what you think", es: "lo que piensas tú" },
        ],
      },
      {
        id: "d339-depende",
        frameStem: "Depende, creo que…",
        english: "It depends, I think I don't know the facts but I do know how I feel.",
        spanish: "Depende, creo que no sé los datos pero sí cómo me siento.",
        situationLabel: "Dos tipos de no saber",
        why: "*Los datos* vs *cómo me siento* — you can answer one even when the other is blank.",
        wordHints: [
          { en: "the facts", es: "los datos" },
          { en: "how i feel", es: "cómo me siento" },
        ],
      },
      {
        id: "d339-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say I don't know and we'll look it up together.",
        spanish: "Creo que diría que no lo sé y que buscamos juntos.",
        situationLabel: "Lo que le dirías a un estudiante",
        why: "*Buscamos juntos* — the classroom version of *ni idea, pero*.",
        wordHints: [
          { en: "i don't know", es: "no lo sé" },
          { en: "we'll look it up together", es: "buscamos juntos" },
        ],
      },
    ],
  },
  {
    day: 340,
    themeEs: "Depende, creo que",
    themeEn: "It depends, I think",
    missionEs: "Responde en matices, no en sí o no.",
    missionEn: "Answer in shades, not yes or no.",
    line: "Camila no acepta respuestas de una palabra.",
    lineEn: "Camila won't take one-word answers.",
    prompts: [
      {
        id: "d340-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is yes, but not entirely.",
        spanish: "Lo primero que se me ocurre es que sí, pero no del todo.",
        situationLabel: "Antes del matiz",
        why: "Gut first, then *depende* — you don't have to pick one.",
        wordHints: [
          { en: "yes", es: "sí" },
          { en: "but not entirely", es: "pero no del todo" },
        ],
      },
      {
        id: "d340-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "Let's see what comes out if I split it into two scenarios.",
        spanish: "A ver qué sale si lo parto en dos escenarios.",
        situationLabel: "Razonando en voz alta",
        why: "*Parto en dos escenarios* — nuance as structure, not as essay.",
        wordHints: [
          { en: "if i split it", es: "si lo parto" },
          { en: "into two scenarios", es: "en dos escenarios" },
        ],
      },
      {
        id: "d340-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "No idea, but in my classroom it works one way.",
        spanish: "Ni idea, pero en mi salón funciona de una forma.",
        situationLabel: "Un lado claro",
        why: "You don't know the whole answer — you know your corner of it.",
        wordHints: [
          { en: "in my classroom", es: "en mi salón" },
          { en: "it works one way", es: "funciona de una forma" },
        ],
      },
      {
        id: "d340-depende",
        frameStem: "Depende, creo que…",
        english: "It depends, I think teaching adults is slower and deeper.",
        spanish: "Depende, creo que enseñar adultos es más lento y más profundo.",
        situationLabel: "Adultos vs niños",
        why: "*Depende, creo que…* is how adults actually answer — not evasive, just honest about context.",
        wordHints: [
          { en: "teaching adults", es: "enseñar adultos" },
          { en: "slower", es: "más lento" },
          { en: "deeper", es: "más profundo" },
        ],
      },
      {
        id: "d340-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say both things can be true at once.",
        spanish: "Creo que diría que las dos cosas pueden ser verdad.",
        situationLabel: "Dos verdades",
        why: "*Las dos cosas pueden ser verdad* — the answer Camila was fishing for.",
        wordHints: [
          { en: "both things", es: "las dos cosas" },
          { en: "can be true", es: "pueden ser verdad" },
        ],
      },
    ],
  },
  {
    day: 341,
    themeEs: "Creo que diría que",
    themeEn: "I think I'd say that",
    missionEs: "Imagina la conversación con Yesenia — sin folleto, sin guion.",
    missionEn: "Picture the conversation with Yesenia — no brochure, no script.",
    line: "¿Qué le dirías si volviera a preguntar?",
    lineEn: "What would you tell her if she asked again?",
    prompts: [
      {
        id: "d341-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is I'd tell her to come back Thursday.",
        spanish: "Lo primero que se me ocurre es que le diría que vuelva el jueves.",
        situationLabel: "Antes de la respuesta cuidadosa",
        why: "Heart first — *vuelva el jueves* is the whole job in four words.",
        wordHints: [
          { en: "i'd tell her", es: "le diría" },
          { en: "to come back", es: "que vuelva" },
          { en: "thursday", es: "el jueves" },
        ],
      },
      {
        id: "d341-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "Let's see what comes out if I say it like to a friend.",
        spanish: "A ver qué sale si se lo digo como a una amiga.",
        situationLabel: "Practicando en voz alta",
        why: "*Como a una amiga* — register shift without changing language.",
        wordHints: [
          { en: "if i tell her", es: "si se lo digo" },
          { en: "like to a friend", es: "como a una amiga" },
        ],
      },
      {
        id: "d341-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "No idea, but I think she needs to hear she's not alone.",
        spanish: "Ni idea, pero creo que necesita oír que no está sola.",
        situationLabel: "Sin certeza",
        why: "*No está sola* — sometimes the honest guess is the truest answer.",
        wordHints: [
          { en: "she needs to hear", es: "necesita oír" },
          { en: "she's not alone", es: "no está sola" },
        ],
      },
      {
        id: "d341-depende",
        frameStem: "Depende, creo que…",
        english: "It depends, I think sometimes she needs information and sometimes company.",
        spanish: "Depende, creo que a veces necesita información y a veces compañía.",
        situationLabel: "Qué necesita Yesenia",
        why: "*Información y compañía* — two different Thursdays, two different answers.",
        wordHints: [
          { en: "sometimes", es: "a veces" },
          { en: "information", es: "información" },
          { en: "company", es: "compañía" },
        ],
      },
      {
        id: "d341-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say English isn't the prize, it's the tool.",
        spanish: "Creo que diría que el inglés no es el premio, es la herramienta.",
        situationLabel: "Sin folleto",
        why: "*Creo que diría que…* lets you rehearse kindness without claiming you've mastered it.",
        wordHints: [
          { en: "english isn't the prize", es: "el inglés no es el premio" },
          { en: "it's the tool", es: "es la herramienta" },
        ],
      },
    ],
  },
  {
    day: 342,
    themeEs: "Sin aviso otra vez",
    themeEn: "Surprise again",
    missionEs: "Cinco preguntas seguidas — un stem por respuesta, sin parar.",
    missionEn: "Five questions in a row — one stem per answer, no stopping.",
    line: "Rápido. Sin cambiar a inglés.",
    lineEn: "Fast. No switching to English.",
    prompts: [
      {
        id: "d342-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is I miss Atlanta heat.",
        spanish: "Lo primero que se me ocurre es que extraño el calor de Atlanta.",
        situationLabel: "Pregunta uno",
        why: "Fast and personal — *extraño el calor* needs no polish.",
        wordHints: [
          { en: "i miss", es: "extraño" },
          { en: "atlanta heat", es: "el calor de atlanta" },
        ],
      },
      {
        id: "d342-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "Let's see what comes out — I've never talked about this in Spanish.",
        spanish: "A ver qué sale — nunca hablé de esto en español.",
        situationLabel: "Pregunta dos",
        why: "Naming the first time out loud is its own stem doing double duty.",
        wordHints: [
          { en: "i've never talked", es: "nunca hablé" },
          { en: "about this in spanish", es: "de esto en español" },
        ],
      },
      {
        id: "d342-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "No idea, but thanks for asking.",
        spanish: "Ni idea, pero gracias por preguntarlo.",
        situationLabel: "Pregunta tres",
        why: "*Gracias por preguntarlo* — gratitude as bridge when the answer is empty.",
        wordHints: [
          { en: "thanks for asking", es: "gracias por preguntarlo" },
        ],
      },
      {
        id: "d342-depende",
        frameStem: "Depende, creo que…",
        english: "It depends, I think I'm braver on Thursdays than on Mondays.",
        spanish: "Depende, creo que los jueves soy más valiente que los lunes.",
        situationLabel: "Pregunta cuatro",
        why: "*Los jueves* — the café day as personality marker.",
        wordHints: [
          { en: "on thursdays", es: "los jueves" },
          { en: "i'm braver", es: "soy más valiente" },
          { en: "than on mondays", es: "que los lunes" },
        ],
      },
      {
        id: "d342-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say Spanish changed the way I listen.",
        spanish: "Creo que diría que el español me cambió la forma de escuchar.",
        situationLabel: "Pregunta cinco",
        why: "The last rapid-fire answer — and the year's quietest truth.",
        wordHints: [
          { en: "spanish changed", es: "el español me cambió" },
          { en: "the way i listen", es: "la forma de escuchar" },
        ],
      },
    ],
  },
  {
    day: 343,
    themeEs: "Repaso: Sin preparación",
    themeEn: "Review: Zero prep",
    missionEs: "Repasa los cinco stems de respuesta en frío.",
    missionEn: "Review all five cold-answer stems.",
    line: "Cinco stems, siete días, cero guion.",
    lineEn: "Five stems, seven days, zero script.",
    prompts: [
      {
        id: "d343-lo-primero",
        frameStem: "Lo primero que se me ocurre es…",
        english: "The first thing that comes to mind is I'm not frozen anymore.",
        spanish: "Lo primero que se me ocurre es que ya no me paralizo.",
        situationLabel: "Lo que cambió",
        why: "*Ya no me paralizo* — the week's real win, said without prep.",
        wordHints: [
          { en: "i'm not frozen anymore", es: "ya no me paralizo" },
        ],
      },
      {
        id: "d343-a-ver-que-sale",
        frameStem: "A ver qué sale…",
        english: "\"Let's see what comes out\" was the phrase I used most this week.",
        spanish: "A ver qué sale fue la frase que más usé esta semana.",
        situationLabel: "La más usada",
        why: "*A ver qué sale* taught you to start before you're ready.",
        wordHints: [
          { en: "the phrase i used most", es: "la frase que más usé" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d343-ni-idea",
        frameStem: "Ni idea, pero…",
        english: "\"No idea, but\" was the answer that opened the most conversation.",
        spanish: "Ni idea, pero fue la respuesta que más abrió conversación.",
        situationLabel: "La más honesta",
        why: "Admitting ignorance without leaving — the stem that surprised you.",
        wordHints: [
          { en: "opened the most conversation", es: "más abrió conversación" },
        ],
      },
      {
        id: "d343-depende",
        frameStem: "Depende, creo que…",
        english: "\"It depends, I think\" is the most honest of the five.",
        spanish: "Depende, creo que es la más honesta de las cinco.",
        situationLabel: "La más adulta",
        why: "*La más honesta* — nuance without essay register.",
        wordHints: [
          { en: "the most honest", es: "la más honesta" },
          { en: "of the five", es: "de las cinco" },
        ],
      },
      {
        id: "d343-creo-que-diria",
        frameStem: "Creo que diría que…",
        english: "I think I'd say practicing out loud changes the real answer.",
        spanish: "Creo que diría que practicar en voz alta cambia la respuesta real.",
        situationLabel: "Cierre de la semana",
        why: "Five stems for zero prep — and the real conversation is still ahead.",
        wordHints: [
          { en: "practicing out loud", es: "practicar en voz alta" },
          { en: "changes the real answer", es: "cambia la respuesta real" },
        ],
      },
    ],
  },
];
