import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 6 — "La tía en Atlanta" (days 309–315).
 * Tía Lucía wants to visit Boston in winter; Marlana, mamá, and a week of
 * gentle debate land on late March — conceding without collapsing.
 */
export const priWeek6ReadingDays: ReadingDay[] = [
  {
    day: 309,
    themeEs: "Puede que tengas razón en el invierno",
    storyTitle: "La tía en Atlanta",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "la tía", en: "the aunt", example: "Mi tía Lucía vive en Atlanta." },
      { es: "febrero", en: "February", example: "Puede que tengas razón en que febrero sale más barato." },
      { es: "reservar", en: "to book, to reserve", example: "Tienes un punto con lo de reservar temprano." },
      { es: "la primavera", en: "spring", example: "Aun así, prefiero que vengas en primavera." },
      { es: "ceder", en: "to give in, to yield", example: "Ceder un poco no es perder." },
    ],
    dialogue: {
      title: "La llamada de febrero",
      situation: "Domingo por la noche — Tía Lucía llama desde Atlanta",
      lines: [
        { speaker: "B", es: "Marlana, ¿qué tal si vengo en febrero? Vi vuelos baratos.", en: "Marlana, what if I come in February? I saw cheap flights." },
        { speaker: "A", es: "Tía… febrero aquí es otra cosa. Puede que tengas razón en que febrero sale más barato.", en: "Aunt… February here is something else. You might be right that February is cheaper." },
        { speaker: "B", es: "¿Entonces sí?", en: "So yes?" },
        { speaker: "A", es: "Aun así, febrero aquí no es lo que imaginas. Es nieve, frío y yo saliendo del colegio agotada.", en: "Even so, February here isn't what you imagine. It's snow, cold, and me leaving school exhausted." },
        { speaker: "B", es: "Pero quiero ver la nieve de verdad. En Atlanta casi no cae.", en: "But I want to see real snow. In Atlanta it barely falls." },
        { speaker: "A", es: "Tienes un punto: quieres ver la nieve de verdad. No había pensado en que tus vacaciones son solo en enero.", en: "You have a point — you want to see real snow. I hadn't thought your vacation is only in January." },
        { speaker: "B", es: "Exacto. Por eso febrero me conviene.", en: "Exactly. That's why February works for me." },
        { speaker: "A", es: "Me convenzo hasta cierto punto con lo de febrero. Pero prefiero hablar de fechas contigo y con mamá.", en: "You convince me up to a point about February. But I'd rather talk dates with you and mom." },
        { speaker: "B", es: "Bueno. Mañana te mando fotos de Boston en invierno. A ver si cambias de opinión.", en: "Okay. Tomorrow I'll send you photos of Boston in winter. Let's see if you change your mind." },
      ],
    },
  },
  {
    day: 310,
    themeEs: "Aun así no es mi temporada",
    storyTitle: "La tía en Atlanta",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "precioso/a", en: "beautiful", example: "Puede que tengas razón en que se ve precioso en las fotos." },
      { es: "la tormenta de nieve", en: "the snowstorm", example: "Tú nunca has visto una tormenta de nieve." },
      { es: "agotada", en: "exhausted", example: "Febrero me deja agotada después del colegio." },
      { es: "un fin de semana largo", en: "a long weekend", example: "Me convenzo hasta cierto punto con un fin de semana largo." },
      { es: "dramática", en: "dramatic", example: "Puede que tengas razón en que me estoy poniendo dramática." },
    ],
    dialogue: {
      title: "Las fotos de nieve",
      situation: "Lunes — la tía manda un álbum entero por mensaje",
      lines: [
        { speaker: "B", es: "¿Viste? Boston en febrero es un cuento.", en: "Did you see? Boston in February is a fairy tale." },
        { speaker: "A", es: "Puede que tengas razón en que se ve precioso en las fotos. Dan ganas de ir.", en: "You might be right that it looks beautiful in the photos. They make you want to go." },
        { speaker: "B", es: "¡Sabía!", en: "I knew it!" },
        { speaker: "A", es: "Aun así, febrero aquí es trabajo, nieve y más nieve. No había pensado en que tú nunca has visto una tormenta de nieve.", en: "Even so, February here is work, snow, and more snow. I hadn't thought you've never seen a snowstorm." },
        { speaker: "B", es: "Por eso quiero ir. Para vivirlo, no para mirarlo en Instagram.", en: "That's why I want to go. To live it, not to look at it on Instagram." },
        { speaker: "A", es: "Tienes un punto con las fotos — dan ganas de ir. Tienes un punto: necesitas salir de Atlanta un rato.", en: "You have a point with the photos — they make you want to go. You have a point — you need to get out of Atlanta for a while." },
        { speaker: "B", es: "Entonces ¿febrero?", en: "So February?" },
        { speaker: "A", es: "Me convenzo hasta cierto punto con un fin de semana largo. Aun así, no prometo toda la semana en pleno invierno.", en: "You convince me up to a point about a long weekend. Even so, I'm not promising a whole week in deep winter." },
        { speaker: "B", es: "Vamos avanzando. Eso suena casi como un sí.", en: "We're getting somewhere. That almost sounds like a yes." },
      ],
    },
  },
  {
    day: 311,
    themeEs: "No había pensado en eso",
    storyTitle: "La tía en Atlanta",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el vuelo guardado", en: "the saved flight", example: "No había pensado en que ya tienes un vuelo guardado." },
      { es: "respaldar", en: "to back someone up, to support", example: "Mamá te respaldaría tan rápido." },
      { es: "recibir", en: "to host, to welcome", example: "Quiero poder recibirte bien." },
      { es: "revisar fechas", en: "to look at dates", example: "Me convenzo de revisar fechas contigo." },
      { es: "entre tormentas", en: "between storms", example: "No quiero recibirte entre tormentas." },
    ],
    dialogue: {
      title: "El vuelo marcado",
      situation: "Martes — la tía manda captura de pantalla de un vuelo",
      lines: [
        { speaker: "B", es: "Mira, tengo este vuelo guardado. Sale en tres semanas si lo compro hoy.", en: "Look, I have this flight saved. It leaves in three weeks if I buy it today." },
        { speaker: "A", es: "Tía… No había pensado en que ya tienes un vuelo guardado.", en: "Aunt… I hadn't thought you already had a flight saved." },
        { speaker: "B", es: "Tu mamá dice que yo debería venir ya. Puede que tengas razón en que mamá extraña verte pronto.", en: "Your mom says I should come now. You might be right that mom misses seeing you soon." },
        { speaker: "A", es: "Puede que tengas razón en eso. Aun así, quiero poder recibirte bien, no entre tormentas.", en: "You might be right about that. Even so, I want to be able to host you well, not between storms." },
        { speaker: "B", es: "¿Y si compro el vuelo y ya?", en: "What if I just buy the flight?" },
        { speaker: "A", es: "Tienes un punto con lo del vuelo — los precios suben. Pero me convenzo hasta cierto punto de revisar fechas contigo, no de comprar hoy.", en: "You have a point about the flight — prices go up. But I'm convinced up to a point to look at dates with you, not to buy today." },
        { speaker: "B", es: "Voy a llamar a tu mamá. A ver qué dice ella.", en: "I'm going to call your mom. Let's see what she says." },
        { speaker: "A", es: "No había pensado en que mamá te respaldaría tan rápido. Bueno — hacemos videollamada las tres mañana.", en: "I hadn't thought mom would back you up so fast. Fine — the three of us on video call tomorrow." },
        { speaker: "B", es: "Perfecto. Traigo mi mejor argumento.", en: "Perfect. I'll bring my best argument." },
      ],
    },
  },
  {
    day: 312,
    themeEs: "Tienes un punto, tía",
    storyTitle: "La tía en Atlanta",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "terca", en: "stubborn", example: "Puede que tengas razón en que estoy siendo terca." },
      { es: "la videollamada", en: "the video call", example: "Hacemos videollamada las tres mañana." },
      { es: "finales de marzo", en: "late March", example: "Me convenzo hasta cierto punto con finales de marzo." },
      { es: "modo supervivencia", en: "survival mode", example: "No quiero estar en modo supervivencia." },
      { es: "la sopa", en: "the soup", example: "Mamá tiene razón con lo de la sopa." },
    ],
    dialogue: {
      title: "Las tres en pantalla",
      situation: "Miércoles — videollamada con mamá en Atlanta y la tía",
      lines: [
        { speaker: "B", es: "Marlana, mamá dice que yo extraño Boston y ella extraña verlas juntas.", en: "Marlana, mom says I miss Boston and she misses seeing you together." },
        { speaker: "A", es: "Puede que tengas razón en que febrero les conviene a ustedes dos. Aun así, febrero me deja agotada después del colegio.", en: "You might be right that February works for you two. Even so, February leaves me exhausted after school." },
        { speaker: "B", es: "Y mamá quiere cocinar conmigo en invierno. Sopa, pan, la mesa llena.", en: "And mom wants to cook with me in winter. Soup, bread, the table full." },
        { speaker: "A", es: "No había pensado en que mamá quiere cocinar contigo en invierno. Tienes un punto, tía — mamá tiene razón con lo de la sopa.", en: "I hadn't thought mom wants to cook with you in winter. You have a point, aunt — mom is right about the soup." },
        { speaker: "B", es: "¿Entonces febrero con sopa?", en: "So February with soup?" },
        { speaker: "A", es: "Aun así, prefiero una visita buena a una visita rápida. Me convenzo hasta cierto punto con finales de marzo — cuatro días, no siete.", en: "Even so, I'd rather a good visit than a rushed one. I'm convinced up to a point about late March — four days, not seven." },
        { speaker: "B", es: "Mamá dice que marzo suena razonable. Bueno, tía cede un poco: finales de marzo. Pero quiero ver nieve antes de irme.", en: "Mom says March sounds reasonable. Fine, I'll give a little: late March. But I want to see snow before I leave." },
      ],
    },
  },
  {
    day: 313,
    themeEs: "Me convenzo hasta cierto punto",
    storyTitle: "La tía en Atlanta",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "confirmar", en: "to confirm", example: "Necesito que confirmes antes de comprar." },
      { es: "el trato", en: "the deal", example: "Ahí se cierra el trato." },
      { es: "los vuelos baratos", en: "cheap flights", example: "Marzo también tiene vuelos baratos." },
      { es: "la última semana", en: "the last week", example: "Quedamos en la última semana de marzo." },
      { es: "negociar", en: "to negotiate", example: "Discutir así es mejor que ceder de golpe." },
    ],
    dialogue: {
      title: "El trato de marzo",
      situation: "Jueves por la mañana — mensajes con la tía y mamá",
      lines: [
        { speaker: "B", es: "Encontré vuelos para la última semana de marzo. Más baratos que febrero, mira.", en: "I found flights for the last week of March. Cheaper than February, look." },
        { speaker: "A", es: "No había pensado en que marzo también tiene vuelos baratos. Puede que tengas razón en que a finales de marzo aún hay nieve.", en: "I hadn't thought March also has cheap flights. You might be right there's still snow in late March." },
        { speaker: "B", es: "¿Entonces lo compro?", en: "So I buy it?" },
        { speaker: "A", es: "Me convenzo hasta cierto punto — quedamos en la última semana de marzo. Aun así, necesito que confirmes conmigo antes de comprar.", en: "You convince me up to a point — we're set for the last week of March. Even so, I need you to confirm with me before you buy." },
        { speaker: "B", es: "Trato hecho. Cuatro días. Nieve, caminatas y tu famosa sopa… bueno, la de tu mamá.", en: "Deal. Four days. Snow, walks, and your famous soup… well, your mom's." },
        { speaker: "A", es: "Tienes un punto — finales de marzo suena bien. Puede que tengas razón en que valió la pena discutirlo.", en: "You have a point — late March sounds good. You might be right it was worth arguing about." },
        { speaker: "B", es: "Discutir con cariño, dijiste ayer. Me gustó eso.", en: "Arguing with warmth, you said yesterday. I liked that." },
        { speaker: "A", es: "Tú ves nieve, yo no me congelo. Me convenzo hasta cierto punto: tú ganaste un poco, yo gané un poco.", en: "You get snow, I don't freeze. I'm convinced up to a point: you won a little, I won a little." },
        { speaker: "B", es: "Eso es familia. Te quiero. Aviso a tu mamá.", en: "That's family. Love you. I'll tell your mom." },
      ],
    },
  },
  {
    day: 314,
    themeEs: "Sin colapsar",
    storyTitle: "La tía en Atlanta",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "sin colapsar", en: "without collapsing, without giving in completely", example: "Ceder sin colapsar." },
      { es: "negociar", en: "to negotiate", example: "No cediste — negociaste." },
      { es: "inflexible", en: "inflexible", example: "Al principio fui inflexible." },
      { es: "grabar", en: "to record", example: "Me convenzo de grabar la próxima videollamada." },
      { es: "discutir con cariño", en: "to argue with warmth", example: "Discutir con cariño suena mejor que pelear." },
    ],
    dialogue: {
      title: "En el café del jueves",
      situation: "Camila quiere saber si Marlana cedió — spoiler: no del todo",
      lines: [
        { speaker: "B", es: "¿Y la tía? ¿Viene en febrero como quería?", en: "And your aunt? Is she coming in February like she wanted?" },
        { speaker: "A", es: "No. Finales de marzo. Cuatro días. Aun así, no dije que sí a febrero.", en: "No. Late March. Four days. Even so, I didn't say yes to February." },
        { speaker: "B", es: "¿Y cómo sonó? ¿Pelearon?", en: "And how did it sound? Did you fight?" },
        { speaker: "A", es: "Puede que tengas razón en que sueno muy formal con mi tía. Pero usé los cinco stems sin darme cuenta.", en: "You might be right I sound too formal with my aunt. But I used all five stems without realizing." },
        { speaker: "B", es: "Dame un ejemplo.", en: "Give me an example." },
        { speaker: "A", es: "Le dije: \"Tienes un punto con las fotos. Aun así, febrero no es mi temporada. Me convenzo hasta cierto punto con marzo.\" Mamá estaba en la llamada.", en: "I told her: \"You have a point about the photos. Even so, February isn't my season. You convince me up to a point about March.\" Mom was on the call." },
        { speaker: "B", es: "Tienes un punto — suena distinto a la semana pasada. Menos \"pero\", más \"hasta cierto punto\".", en: "You have a point — it sounds different from last week. Less \"but,\" more \"up to a point.\"" },
        { speaker: "A", es: "No había pensado en que discutir en español me cansaba menos que ceder en inglés. Me convenzo hasta cierto punto de grabar la próxima videollamada.", en: "I hadn't thought arguing in Spanish tired me out less than giving in in English. You convince me up to a point to record the next video call." },
        { speaker: "B", es: "Negociaste. Eso no es ceder. Bien.", en: "You negotiated. That's not giving in. Good." },
      ],
    },
  },
  {
    day: 315,
    themeEs: "Repaso: Debate suave II",
    isRecap: true,
    vocab: [
      { es: "conceder", en: "to concede, to grant", example: "Conceder no es perder." },
      { es: "hasta cierto punto", en: "up to a point", example: "Me convenzo hasta cierto punto." },
      { es: "sostener", en: "to hold (one's ground)", example: "Conceder y sostener." },
      { es: "colapsar", en: "to collapse, to give in completely", example: "Ceder sin colapsar." },
      { es: "debate suave", en: "gentle debate", example: "Discutir con cariño." },
    ],
    dialogue: {
      title: "La tía, resumida",
      situation: "Repaso — los cinco stems y la negociación entera",
      lines: [
        { speaker: "B", es: "Repaso. Semana seis. ¿Qué aprendiste con la tía?", en: "Recap. Week six. What did you learn with your aunt?" },
        { speaker: "A", es: "Que puedo decir que la otra persona tiene razón en algo y no perder la discusión entera.", en: "That I can say the other person is right about something and not lose the whole argument." },
        { speaker: "B", es: "Los cinco stems.", en: "The five stems." },
        { speaker: "A", es: "Conceder: puede que tengas razón en… Sostener: aun así… Sorpresa: no había pensado en eso. Corto: tienes un punto. Trato: me convenzo hasta cierto punto.", en: "Concede: you might be right about… Hold: even so… Surprise: I hadn't thought of that. Short: you have a point. Deal: you convince me up to a point." },
        { speaker: "B", es: "¿Y la historia en una frase?", en: "And the story in one sentence?" },
        { speaker: "A", es: "Tía Lucía quería febrero, yo quería primavera, mamá quería sopa, y quedamos en finales de marzo con cuatro días y nieve incluida.", en: "Aunt Lucía wanted February, I wanted spring, mom wanted soup, and we landed on late March with four days and snow included." },
        { speaker: "B", es: "Puede que tengas razón en que suena simple cuando lo cuentas así.", en: "You might be right it sounds simple when you tell it like that." },
        { speaker: "A", es: "Aun así, costó tres llamadas. No había pensado en lo bien que se siente no colapsar.", en: "Even so, it took three calls. I hadn't thought how good it feels not to collapse." },
        { speaker: "B", es: "Semana siete: tú y usted. Otra forma de sostener — con otra persona.", en: "Week seven: tú and usted. Another way to hold ground — with a different person." },
      ],
    },
  },
];
