import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 12 — "Conversación larga II" (days 351–357).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week12-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek12SpeakDays: SpeakDay[] = [
  {
    day: 351,
    themeEs: "El silencio",
    themeEn: "The silence",
    missionEs: "Nombra el silencio y relanza con bueno, ¿y qué más?",
    missionEn: "Name the silence and relaunch with \"well, what else?\"",
    line: "Cuarenta minutos y se acabó el hilo.",
    lineEn: "Forty minutes in and the thread ran out.",
    prompts: [
      {
        id: "d351-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else happened to you this week?",
        spanish: "Bueno, ¿y qué más? ¿Qué más te pasó esta semana?",
        situationLabel: "Después del silencio",
        why: "*¿Y qué más?* sounds lazy in a textbook and generous in a kitchen — it means I still want to hear you.",
        wordHints: [
          { en: "what else", es: "qué más" },
          { en: "happened to you", es: "te pasó" },
          { en: "this week", es: "esta semana" },
        ],
      },
      {
        id: "d351-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you about Diego's mom.",
        spanish: "Se me olvidaba contarte lo de la mamá de Diego.",
        situationLabel: "Algo que casi se pierde",
        why: "*Se me olvidaba* — the imperfect — means it was slipping away while you talked about other things.",
        wordHints: [
          { en: "i forgot to tell you", es: "se me olvidaba contarte" },
          { en: "diego's mom", es: "la mamá de diego" },
        ],
      },
      {
        id: "d351-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — how's the new shift going?",
        spanish: "Oye, y cambiando de tema, ¿cómo va lo del turno nuevo?",
        situationLabel: "Aire fresco",
        why: "*Cambiando de tema* announces the move without apologizing — you're steering, not failing.",
        wordHints: [
          { en: "changing the subject", es: "cambiando de tema" },
          { en: "how's it going", es: "cómo va" },
          { en: "the new shift", es: "lo del turno nuevo" },
        ],
      },
      {
        id: "d351-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way, I saw your neighbor at the bakery.",
        spanish: "Por cierto, vi a tu vecina en la panadería.",
        situationLabel: "Relanzamiento suave",
        why: "*Por cierto* is the gentlest relaunch — you're not announcing a topic change, you're letting one arrive.",
        wordHints: [
          { en: "by the way", es: "por cierto" },
          { en: "i saw", es: "vi" },
          { en: "your neighbor", es: "tu vecina" },
          { en: "at the bakery", es: "en la panadería" },
        ],
      },
      {
        id: "d351-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing — don't hang up yet.",
        spanish: "Ah, y otra cosa — no cuelgues todavía.",
        situationLabel: "Antes de colgar",
        why: "The stack at the end is warmth, not rudeness — *ah, y otra cosa* means you're not ready to let go.",
        wordHints: [
          { en: "one more thing", es: "otra cosa" },
          { en: "don't hang up yet", es: "no cuelgues todavía" },
        ],
      },
    ],
  },
  {
    day: 352,
    themeEs: "Bueno, ¿y qué más?",
    themeEn: "Well, what else?",
    missionEs: "Usa bueno, ¿y qué más? como invitación, no como pregunta vacía.",
    missionEn: "Use \"well, what else?\" as an invitation, not an empty question.",
    line: "Suena vacía y no lo es.",
    lineEn: "It sounds empty and it isn't.",
    prompts: [
      {
        id: "d352-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else? It doesn't have to be important.",
        spanish: "Bueno, ¿y qué más? No tiene que ser importante.",
        situationLabel: "La lección de Camila",
        why: "You're not asking for a report — the *bueno* buys a breath and the floor stays theirs.",
        wordHints: [
          { en: "it doesn't have to be", es: "no tiene que ser" },
          { en: "important", es: "importante" },
        ],
      },
      {
        id: "d352-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you — there was a scare at the hospital last night.",
        spanish: "Se me olvidaba contarte que anoche hubo un susto en el hospital.",
        situationLabel: "La respuesta de Camila",
        why: "Camila answers the lull with something she held back — small news, big door.",
        wordHints: [
          { en: "last night", es: "anoche" },
          { en: "there was a scare", es: "hubo un susto" },
          { en: "at the hospital", es: "en el hospital" },
        ],
      },
      {
        id: "d352-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — are you still going to the café on Thursdays?",
        spanish: "Oye, y cambiando de tema, ¿tú sigues yendo al café los jueves?",
        situationLabel: "Cuando no cae",
        why: "When *¿y qué más?* doesn't land, pivot — fresh angle, no apology.",
        wordHints: [
          { en: "are you still going", es: "sigues yendo" },
          { en: "on thursdays", es: "los jueves" },
        ],
      },
      {
        id: "d352-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way, your student wrote to me last night.",
        spanish: "Por cierto, tu alumna me escribió anoche.",
        situationLabel: "Conectando hilos",
        why: "*Por cierto* connects worlds — school and hospital in one sidebar.",
        wordHints: [
          { en: "your student", es: "tu alumna" },
          { en: "wrote to me", es: "me escribió" },
          { en: "last night", es: "anoche" },
        ],
      },
      {
        id: "d352-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing — call me early tomorrow.",
        spanish: "Ah, y otra cosa — mañana llámame temprano.",
        situationLabel: "La llamada sigue",
        why: "Stack after relaunch — the call continues because neither of you is done.",
        wordHints: [
          { en: "call me", es: "llámame" },
          { en: "early", es: "temprano" },
          { en: "tomorrow", es: "mañana" },
        ],
      },
    ],
  },
  {
    day: 353,
    themeEs: "Se me olvidaba contarte",
    themeEn: "I forgot to tell you",
    missionEs: "Relanza con algo que casi no dijiste — se me olvidaba contarte.",
    missionEn: "Relaunch with something you almost didn't say — \"I forgot to tell you.\"",
    line: "Lo que casi se pierde con el silencio.",
    lineEn: "What almost gets lost in the silence.",
    prompts: [
      {
        id: "d353-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else happened with Diego's mom?",
        spanish: "Bueno, ¿y qué más pasó con la mamá de Diego?",
        situationLabel: "Después de contar",
        why: "*¿Y qué más?* keeps the ball rolling after your relaunch lands.",
        wordHints: [
          { en: "what else happened", es: "qué más pasó" },
          { en: "with", es: "con" },
        ],
      },
      {
        id: "d353-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you that Yesenia came back Thursday.",
        spanish: "Se me olvidaba contarte que Yesenia volvió el jueves.",
        situationLabel: "El relanzamiento de Marlana",
        why: "The imperfect names what was slipping away — perfect mid-conversation rescue.",
        wordHints: [
          { en: "yesenia came back", es: "yesenia volvió" },
          { en: "thursday", es: "el jueves" },
        ],
      },
      {
        id: "d353-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — how did your shift start?",
        spanish: "Oye, y cambiando de tema, ¿cómo amaneció tu turno?",
        situationLabel: "Balance en la llamada",
        why: "*¿Cómo amaneció?* — how did it wake up? — pivots to Camila's world with warmth.",
        wordHints: [
          { en: "how did it wake up", es: "cómo amaneció" },
          { en: "your shift", es: "tu turno" },
        ],
      },
      {
        id: "d353-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way, Diego's mom works near the hospital.",
        spanish: "Por cierto, la mamá de Diego trabaja cerca del hospital.",
        situationLabel: "Un hilo conecta",
        why: "The sidebar links school to hospital — conversations grow webs, not lists.",
        wordHints: [
          { en: "works near", es: "trabaja cerca de" },
          { en: "the hospital", es: "el hospital" },
        ],
      },
      {
        id: "d353-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing — I have parent conferences Thursday.",
        spanish: "Ah, y otra cosa — el jueves tengo reunión de padres.",
        situationLabel: "Un hilo más",
        why: "One thread spawns another — the stack is how Sunday calls reach ninety minutes.",
        wordHints: [
          { en: "thursday", es: "el jueves" },
          { en: "parent conference", es: "reunión de padres" },
        ],
      },
    ],
  },
  {
    day: 354,
    themeEs: "Cambiando de tema",
    themeEn: "Changing the subject",
    missionEs: "Cuando un hilo muere, no lo revivas — cambia de tema.",
    missionEn: "When a thread dies, don't revive it — change the subject.",
    line: "No revivas lo muerto. Abre otra puerta.",
    lineEn: "Don't revive what's dead. Open another door.",
    prompts: [
      {
        id: "d354-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else about the shift? Or was that everything?",
        spanish: "Bueno, ¿y qué más sobre el turno? ¿O ya fue todo?",
        situationLabel: "Una última prueba",
        why: "One last *¿y qué más?* to test if a topic has life — then pivot without guilt.",
        wordHints: [
          { en: "about the shift", es: "sobre el turno" },
          { en: "or was that everything", es: "o ya fue todo" },
        ],
      },
      {
        id: "d354-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you what happened with the elevator.",
        spanish: "Se me olvidaba contarte lo que pasó con el ascensor.",
        situationLabel: "Historia del hospital",
        why: "After the pivot, memory delivers — the elevator story was waiting for its moment.",
        wordHints: [
          { en: "what happened", es: "lo que pasó" },
          { en: "with the elevator", es: "con el ascensor" },
        ],
      },
      {
        id: "d354-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — did you watch the series you recommended?",
        spanish: "Oye, y cambiando de tema, ¿viste la serie que me recomendaste?",
        situationLabel: "Marlana lo intenta",
        why: "*Cambiando de tema* — permission to move on, announced without apology.",
        wordHints: [
          { en: "did you watch", es: "viste" },
          { en: "the series", es: "la serie" },
          { en: "you recommended", es: "me recomendaste" },
        ],
      },
      {
        id: "d354-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way, Rocío asked if you're coming to the birthday.",
        spanish: "Por cierto, Rocío preguntó si vienes al cumpleaños.",
        situationLabel: "Pivot más ligero",
        why: "*Por cierto* is a lighter pivot — Rocío opens a whole new room in the call.",
        wordHints: [
          { en: "rocío asked", es: "rocío preguntó" },
          { en: "if you're coming", es: "si vienes" },
          { en: "to the birthday", es: "al cumpleaños" },
        ],
      },
      {
        id: "d354-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing about the series — don't spoil it.",
        spanish: "Ah, y otra cosa sobre la serie — no me spoilees.",
        situationLabel: "El stack empieza",
        why: "New topic spawns another — *ah, y otra cosa* and you're nowhere near hanging up.",
        wordHints: [
          { en: "about the series", es: "sobre la serie" },
          { en: "don't spoil it", es: "no me spoilees" },
        ],
      },
    ],
  },
  {
    day: 355,
    themeEs: "Por cierto",
    themeEn: "By the way",
    missionEs: "Relanza con por cierto — lo tangencial que abre la mejor parte.",
    missionEn: "Relaunch with \"by the way\" — the tangent that opens the best part.",
    line: "Lo que no estaba en la agenda.",
    lineEn: "What wasn't on the agenda.",
    prompts: [
      {
        id: "d355-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else? That sounds like a long story.",
        spanish: "Bueno, ¿y qué más? Eso suena a historia larga.",
        situationLabel: "Siguiendo la tangente",
        why: "When *por cierto* opens a door, *¿y qué más?* walks through it.",
        wordHints: [
          { en: "that sounds like", es: "eso suena a" },
          { en: "a long story", es: "historia larga" },
        ],
      },
      {
        id: "d355-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you — the neighbor is from Medellín.",
        spanish: "Se me olvidaba contarte que la vecina es de Medellín.",
        situationLabel: "La tangente conecta",
        why: "The sidebar triggers memory — Medellín connects to Camila's aunt, and the web grows.",
        wordHints: [
          { en: "the neighbor", es: "la vecina" },
          { en: "is from medellín", es: "es de medellín" },
        ],
      },
      {
        id: "d355-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — we've been on the bakery for an hour.",
        spanish: "Oye, y cambiando de tema — llevamos una hora en la panadería.",
        situationLabel: "Cuando la tangente se acaba",
        why: "Even tangents end — *cambiando de tema* steers back without killing the warmth.",
        wordHints: [
          { en: "we've been on", es: "llevamos" },
          { en: "an hour", es: "una hora" },
          { en: "the bakery", es: "la panadería" },
        ],
      },
      {
        id: "d355-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way, I heard someone say \"pa' que\" at the store.",
        spanish: "Por cierto, oí a alguien decir \"pa' que\" en la tienda.",
        situationLabel: "El turno de Marlana",
        why: "*Por cierto* doesn't demand attention — low pressure, high reward. The other person picks it up or lets it pass.",
        wordHints: [
          { en: "i heard someone say", es: "oí a alguien decir" },
          { en: "at the store", es: "en la tienda" },
        ],
      },
      {
        id: "d355-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing about Doña Marta — you're going to die.",
        spanish: "Ah, y otra cosa sobre doña Marta, te vas a morir.",
        situationLabel: "La tangente crece",
        why: "*Te vas a morir* — you're going to die (laughing) — the hyperbole week paying off in a sidebar.",
        wordHints: [
          { en: "about doña marta", es: "sobre doña marta" },
          { en: "you're going to die", es: "te vas a morir" },
        ],
      },
    ],
  },
  {
    day: 356,
    themeEs: "Ah, y otra cosa",
    themeEn: "Oh, and one more thing",
    missionEs: "Apila con ah, y otra cosa — calor antes de colgar.",
    missionEn: "Stack with \"oh, and one more thing\" — warmth before hanging up.",
    line: "Dijiste que colgabas hace veinte minutos.",
    lineEn: "You said you'd hang up twenty minutes ago.",
    prompts: [
      {
        id: "d356-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else? You said \"oh, and one more thing\" three times.",
        spanish: "Bueno, ¿y qué más? Dijiste \"ah, y otra cosa\" tres veces.",
        situationLabel: "Hora y media",
        why: "Ninety minutes in and neither hangs up — the stack is the compliment.",
        wordHints: [
          { en: "you said", es: "dijiste" },
          { en: "three times", es: "tres veces" },
        ],
      },
      {
        id: "d356-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you — I was about to hang up without saying it.",
        spanish: "Se me olvidaba contarte — iba a colgar sin decirte.",
        situationLabel: "El salvamento final",
        why: "The last save before goodbye — what almost died with the click.",
        wordHints: [
          { en: "i was going to hang up", es: "iba a colgar" },
          { en: "without telling you", es: "sin decirte" },
        ],
      },
      {
        id: "d356-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — do you think I can hold a full hour?",
        spanish: "Oye, y cambiando de tema, ¿tú crees que aguanto una hora entera?",
        situationLabel: "Mirando al capstone",
        why: "Final pivot toward what's next — the capstone conversation is one week away.",
        wordHints: [
          { en: "do you think", es: "tú crees que" },
          { en: "i can hold", es: "aguanto" },
          { en: "a full hour", es: "una hora entera" },
        ],
      },
      {
        id: "d356-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way, same time next Sunday, right?",
        spanish: "Por cierto, el domingo que viene igual, ¿sí?",
        situationLabel: "Cierre cálido",
        why: "*El domingo que viene igual* — same next Sunday — schedules the next long call without ending this one.",
        wordHints: [
          { en: "next sunday", es: "el domingo que viene" },
          { en: "same", es: "igual" },
        ],
      },
      {
        id: "d356-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing — today I learned to relaunch a conversation.",
        spanish: "Ah, y otra cosa: hoy aprendí a relanzar una conversación.",
        situationLabel: "La conversación revive",
        why: "The stack at the end is warmth — *ah, y otra cosa* means I'm not ready to let you go yet.",
        wordHints: [
          { en: "today i learned", es: "hoy aprendí" },
          { en: "to relaunch a conversation", es: "a relanzar una conversación" },
        ],
      },
    ],
  },
  {
    day: 357,
    themeEs: "Repaso: Conversación larga II",
    themeEn: "Review: Long conversation II",
    missionEs: "Repasa los cinco stems para cuando se enfría la charla.",
    missionEn: "Review the five stems for when the talk goes cold.",
    line: "Así se enfría y así se calienta.",
    lineEn: "That's how it cools and that's how you warm it up.",
    prompts: [
      {
        id: "d357-y-que-mas",
        frameStem: "Bueno, ¿y qué más?…",
        english: "Well, what else? — the simplest stem and the most useful.",
        spanish: "Bueno, ¿y qué más? — el stem más simple y el más útil.",
        situationLabel: "La puerta abierta",
        why: "*¿Y qué más?* is not laziness — it's invitation. Week 11 gave you bridges; week 12 gives you relaunches.",
        wordHints: [
          { en: "the simplest", es: "el más simple" },
          { en: "the most useful", es: "el más útil" },
        ],
      },
      {
        id: "d357-se-me-olvidaba",
        frameStem: "Se me olvidaba contarte…",
        english: "I forgot to tell you — it rescues what almost gets lost.",
        spanish: "Se me olvidaba contarte — rescata lo que casi se pierde.",
        situationLabel: "Memoria",
        why: "The imperfect avisa — it signals what was slipping away while you talked about other things.",
        wordHints: [
          { en: "it rescues", es: "rescata" },
          { en: "what almost gets lost", es: "lo que casi se pierde" },
        ],
      },
      {
        id: "d357-cambiando-tema",
        frameStem: "Oye, y cambiando de tema…",
        english: "Hey, and changing the subject — don't revive what's dead, open another.",
        spanish: "Oye, y cambiando de tema — no revivas lo muerto, abre otro.",
        situationLabel: "Giro deliberado",
        why: "Dead thread? Pivot. *Cambiando de tema* is permission without apology.",
        wordHints: [
          { en: "don't revive what's dead", es: "no revivas lo muerto" },
          { en: "open another", es: "abre otro" },
        ],
      },
      {
        id: "d357-por-cierto",
        frameStem: "Por cierto…",
        english: "By the way — the gentlest relaunch of the five.",
        spanish: "Por cierto — el relanzamiento más suave de los cinco.",
        situationLabel: "Tangente",
        why: "Doña Marta opened twenty minutes of talk with two words at the bakery.",
        wordHints: [
          { en: "the gentlest relaunch", es: "el relanzamiento más suave" },
          { en: "of the five", es: "de los cinco" },
        ],
      },
      {
        id: "d357-otra-cosa",
        frameStem: "Ah, y otra cosa…",
        english: "Oh, and one more thing — that's how it warms up when it cools down.",
        spanish: "Ah, y otra cosa: así se calienta cuando se enfría.",
        situationLabel: "El título de la semana",
        why: "*Cuando se enfría* — when it cools — and five stems to relaunch. One week until the capstone.",
        wordHints: [
          { en: "that's how it warms up", es: "así se calienta" },
          { en: "when it cools down", es: "cuando se enfría" },
        ],
      },
    ],
  },
];
