import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 10 — "La pregunta sin aviso" (days 337–343).
 * Camila turns Thursday café into an improv game: unexpected questions,
 * zero prep. Marlana answers with whatever comes first — cold-prompt stems
 * as survival gear.
 */
export const priWeek10ReadingDays: ReadingDay[] = [
  {
    day: 337,
    themeEs: "El juego de Camila",
    storyTitle: "La pregunta sin aviso",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "sin aviso", en: "without warning", example: "Camila pregunta sin aviso, sin preparación." },
      { es: "ocurrirse", en: "to come to mind", example: "Lo primero que se me ocurre es Atlanta." },
      { es: "a ver qué sale", en: "let's see what comes out", example: "A ver qué sale si empiezo sin orden." },
      { es: "paralizarse", en: "to freeze up", example: "Antes me paralizaba cuando no tenía respuesta." },
      { es: "el guion", en: "the script", example: "Hoy no hay guion, hay preguntas." },
    ],
    dialogue: {
      title: "Nuevo juego",
      situation: "Jueves en el café — Camila trae un cuaderno y una sonrisa",
      lines: [
        { speaker: "B", es: "Hoy empieza un juego nuevo. Te pregunto cosas sin aviso. Tú respondes con lo primero que se te ocurra.", en: "Today a new game starts. I ask you things without warning. You answer with whatever comes first." },
        { speaker: "A", es: "¿Sin preparación? ¿Ni un minuto?", en: "No prep? Not even a minute?" },
        { speaker: "B", es: "Ni un minuto. Si te quedas muda, pierdes un punto. Si inventas en español, ganas dos.", en: "Not even a minute. If you go silent, you lose a point. If you improvise in Spanish, you win two." },
        { speaker: "A", es: "Odio los juegos donde pierdo.", en: "I hate games where I lose." },
        { speaker: "B", es: "Primera pregunta: si mañana te fueras de Boston, ¿qué extrañarías primero?", en: "First question: if you left Boston tomorrow, what would you miss first?" },
        { speaker: "A", es: "Lo primero que se me ocurre es… el café de los jueves contigo.", en: "The first thing that comes to mind is… Thursday coffee with you." },
        { speaker: "B", es: "Eso no cuenta, es trampa emocional.", en: "That doesn't count, that's emotional cheating." },
        { speaker: "A", es: "Tú preguntaste lo primero que se me ocurre. A ver qué sale con la segunda pregunta.", en: "You asked for the first thing that came to mind. Let's see what comes out with the second question." },
        { speaker: "B", es: "Bien. Segunda: ¿Atlanta o Boston?", en: "Good. Second: Atlanta or Boston?" },
        { speaker: "A", es: "Lo primero que se me ocurre es Atlanta, no Boston. Depende, creo que el lunes y el viernes no soy la misma.", en: "The first thing that comes to mind is Atlanta, not Boston. It depends, I think on Monday and Friday I'm not the same person." },
      ],
    },
  },
  {
    day: 338,
    themeEs: "A ver qué sale",
    storyTitle: "La pregunta sin aviso",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "improvisar", en: "to improvise", example: "Improvisar en español vale dos puntos." },
      { es: "sin orden", en: "without order, out of sequence", example: "Empiezo sin orden y encuentro el punto." },
      { es: "parar a alguien", en: "to stop someone", example: "Empiezo y tú me paras si me pierdo." },
      { es: "perderse", en: "to get lost (in speech)", example: "Me paras si me pierdo en la historia." },
      { es: "la versión pulida", en: "the polished version", example: "No necesito la versión pulida para quedarme." },
    ],
    dialogue: {
      title: "Hablando a ciegas",
      situation: "Segunda ronda — Camila aprieta el ritmo",
      lines: [
        { speaker: "B", es: "Tercera pregunta: ¿qué olor te devuelve a la infancia?", en: "Third question: what smell takes you back to childhood?" },
        { speaker: "A", es: "Lo primero que se me ocurre es mi abuela en la cocina.", en: "The first thing that comes to mind is my grandmother in the kitchen." },
        { speaker: "B", es: "¿Y cuál era el olor?", en: "And what was the smell?" },
        { speaker: "A", es: "A ver qué sale — empiezo y tú me paras si me pierdo. Era… canela y algo dulce que no sé nombrar.", en: "Let's see what comes out — I'll start and you stop me if I get lost. It was… cinnamon and something sweet I can't name." },
        { speaker: "B", es: "Nombraste canela. Punto.", en: "You named cinnamon. Point." },
        { speaker: "A", es: "Ni idea, pero me acuerdo del color de la pared. Amarillo viejo.", en: "No idea, but I remember the color of the wall. Old yellow." },
        { speaker: "B", es: "Cuarta pregunta: ¿prefieres enseñar de día o corregir papeles de noche?", en: "Fourth question: do you prefer teaching by day or grading papers at night?" },
        { speaker: "A", es: "Depende, creo que si me preguntas en inglés pienso distinto.", en: "It depends, I think if you ask me in English I think differently." },
        { speaker: "B", es: "Estamos en español. Responde en español.", en: "We're in Spanish. Answer in Spanish." },
        { speaker: "A", es: "Creo que diría que de día enseño y de noche me pregunto si enseñé bien.", en: "I think I'd say by day I teach and at night I wonder if I taught well." },
      ],
    },
  },
  {
    day: 339,
    themeEs: "Ni idea, pero",
    storyTitle: "La pregunta sin aviso",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "conjetura", en: "guess, conjecture", example: "Capaz conecto algo tarde, aunque suene a conjetura." },
      { es: "quedarse callado/a", en: "to go silent, stay quiet", example: "Lo primero que se me ocurre es quedarme callada, pero no." },
      { es: "los datos", en: "the facts, the data", example: "No sé los datos pero sí cómo me siento." },
      { es: "buscar juntos", en: "to look it up together", example: "Creo que diría que buscamos juntos." },
      { es: "merecer", en: "to deserve", example: "Esa pregunta merece más de un minuto." },
    ],
    dialogue: {
      title: "La que no sabes",
      situation: "Camila pregunta algo de Colombia que Marlana no conoce",
      lines: [
        { speaker: "B", es: "Quinta pregunta: ¿cuál es la diferencia entre *chévere* y *bacano*?", en: "Fifth question: what's the difference between *chévere* and *bacano*?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que no sé nada de eso.", en: "The first thing that comes to mind is that I don't know anything about that." },
        { speaker: "B", es: "¿Te rindes?", en: "You give up?" },
        { speaker: "A", es: "Ni idea, pero me importa lo que piensas tú. Nunca me habían preguntado eso.", en: "No idea, but I care what you think. Nobody's ever asked me that." },
        { speaker: "B", es: "Bacano es más Bogotá. Chévere es más Caribe. Las dos significan bueno.", en: "Bacano is more Bogotá. Chévere is more Caribbean. Both mean good." },
        { speaker: "A", es: "A ver qué sale si lo miro desde mi trabajo: en mi salón no uso ninguna de las dos.", en: "Let's see what comes out if I look at it from my job: in my classroom I don't use either one." },
        { speaker: "B", es: "Sexta pregunta: ¿cuándo fue la última vez que mentiste en clase?", en: "Sixth question: when was the last time you lied in class?" },
        { speaker: "A", es: "Depende, creo que no sé los datos pero sí cómo me siento. Me sentí mal ayer cuando dije que entendía un horario que no entendía.", en: "It depends, I think I don't know the facts but I do know how I feel. I felt bad yesterday when I said I understood a schedule I didn't understand." },
        { speaker: "B", es: "Eso no fue mentira, fue cansancio.", en: "That wasn't a lie, that was exhaustion." },
        { speaker: "A", es: "Creo que diría que no lo sé y que buscamos juntos cuando un estudiante pregunta algo que no sé.", en: "I think I'd say I don't know and we'll look it up together when a student asks something I don't know." },
      ],
    },
  },
  {
    day: 340,
    themeEs: "Depende, creo que",
    storyTitle: "La pregunta sin aviso",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "matiz", en: "shade, nuance", example: "Camila no acepta respuestas sin matices." },
      { es: "el binario", en: "the binary, either-or", example: "No elijo un bando del binario." },
      { es: "escenario", en: "scenario", example: "Lo parto en dos escenarios." },
      { es: "lento/a", en: "slow", example: "Enseñar adultos es más lento y más profundo." },
      { es: "ser verdad", en: "to be true", example: "Las dos cosas pueden ser verdad." },
    ],
    dialogue: {
      title: "Sin sí o no",
      situation: "Camila rechaza respuestas de una palabra",
      lines: [
        { speaker: "B", es: "Séptima: ¿es mejor enseñar adultos o niños?", en: "Seventh: is it better to teach adults or kids?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que sí, pero no del todo.", en: "The first thing that comes to mind is yes, but not entirely." },
        { speaker: "B", es: "Eso no es respuesta. Depende de qué.", en: "That's not an answer. Depends on what." },
        { speaker: "A", es: "Depende, creo que enseñar adultos es más lento y más profundo.", en: "It depends, I think teaching adults is slower and deeper." },
        { speaker: "B", es: "¿Y los niños?", en: "And kids?" },
        { speaker: "A", es: "A ver qué sale si lo parto en dos escenarios. Con niños enseño juego. Con adultos enseño vida.", en: "Let's see what comes out if I split it into two scenarios. With kids I teach play. With adults I teach life." },
        { speaker: "B", es: "Octava: ¿el código o la escuela?", en: "Eighth: coding or school?" },
        { speaker: "A", es: "Depende, creo que el código me enseña paciencia y la escuela me enseña gente.", en: "It depends, I think coding teaches me patience and school teaches me people." },
        { speaker: "B", es: "¿Tienes que elegir?", en: "Do you have to choose?" },
        { speaker: "A", es: "Creo que diría que las dos cosas pueden ser verdad. Ni idea, pero en mi salón funciona de una forma y en mi laptop de otra.", en: "I think I'd say both things can be true. No idea, but in my classroom it works one way and on my laptop another." },
      ],
    },
  },
  {
    day: 341,
    themeEs: "Creo que diría que",
    storyTitle: "La pregunta sin aviso",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "hipotético/a", en: "hypothetical", example: "Creo que diría que… es respuesta hipotética." },
      { es: "el folleto", en: "the brochure", example: "El folleto no le sirve a Yesenia." },
      { es: "compañía", en: "company, companionship", example: "A veces necesita compañía, no información." },
      { es: "la herramienta", en: "the tool", example: "El inglés es la herramienta, no el premio." },
      { es: "practicar en voz alta", en: "to practice out loud", example: "Practicar en voz alta cambia la respuesta real." },
    ],
    dialogue: {
      title: "La pregunta de Yesenia otra vez",
      situation: "Camila vuelve al tema de la semana 8 — sin folleto esta vez",
      lines: [
        { speaker: "B", es: "Novena: Yesenia vuelve mañana y repite la pregunta. ¿Qué le dices?", en: "Ninth: Yesenia comes back tomorrow and asks again. What do you tell her?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que le diría que vuelva el jueves.", en: "The first thing that comes to mind is I'd tell her to come back Thursday." },
        { speaker: "B", es: "Eso no responde la pregunta.", en: "That doesn't answer the question." },
        { speaker: "A", es: "A ver qué sale si se lo digo como a una amiga. Creo que diría que el inglés no es el premio, es la herramienta.", en: "Let's see what comes out if I say it like to a friend. I think I'd say English isn't the prize, it's the tool." },
        { speaker: "B", es: "¿Y si te dice que la herramienta no le sirve en cocina?", en: "And if she says the tool doesn't help her in a kitchen?" },
        { speaker: "A", es: "Depende, creo que a veces necesita información y a veces compañía.", en: "It depends, I think sometimes she needs information and sometimes company." },
        { speaker: "B", es: "¿Cuál es hoy?", en: "Which is it today?" },
        { speaker: "A", es: "Ni idea, pero creo que necesita oír que no está sola.", en: "No idea, but I think she needs to hear she's not alone." },
        { speaker: "B", es: "Eso suena a respuesta de verdad, no a folleto.", en: "That sounds like a real answer, not a brochure." },
        { speaker: "A", es: "Creo que diría que hace un año yo tampoco tenía respuesta. Y volví igual.", en: "I think I'd say a year ago I didn't have an answer either. And I came back anyway." },
      ],
    },
  },
  {
    day: 342,
    themeEs: "Sin aviso otra vez",
    storyTitle: "La pregunta sin aviso",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "en ráfaga", en: "in rapid succession", example: "Camila hace preguntas en ráfaga." },
      { es: "valiente", en: "brave", example: "Los jueves soy más valiente que los lunes." },
      { es: "extrañar", en: "to miss", example: "Extraño el calor de Atlanta." },
      { es: "escuchar", en: "to listen", example: "El español me cambió la forma de escuchar." },
      { es: "quedarse", en: "to stay, remain", example: "Siete días respondí sin guion y me quedé en español." },
    ],
    dialogue: {
      title: "Cinco preguntas seguidas",
      situation: "Camila cierra el juego con ronda rápida",
      lines: [
        { speaker: "B", es: "Última ronda. Cinco preguntas. Sin pensar. ¿Lista?", en: "Last round. Five questions. No thinking. Ready?" },
        { speaker: "A", es: "No. Dale.", en: "No. Go." },
        { speaker: "B", es: "Uno: ¿qué extrañas de Atlanta?", en: "One: what do you miss about Atlanta?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que extraño el calor de Atlanta.", en: "The first thing that comes to mind is I miss Atlanta heat." },
        { speaker: "B", es: "Dos: ¿alguna vez mentiste sobre tu nivel de español?", en: "Two: have you ever lied about your Spanish level?" },
        { speaker: "A", es: "A ver qué sale — nunca hablé de esto en español. Creo que minimicé lo que sí entendía.", en: "Let's see what comes out — I've never talked about this in Spanish. I think I downplayed what I did understand." },
        { speaker: "B", es: "Tres: ¿qué sabe Rocío de ti que yo no?", en: "Three: what does Rocío know about you that I don't?" },
        { speaker: "A", es: "Ni idea, pero gracias por preguntarlo.", en: "No idea, but thanks for asking." },
        { speaker: "B", es: "Cuatro: ¿cuándo hablas mejor español?", en: "Four: when do you speak better Spanish?" },
        { speaker: "A", es: "Depende, creo que los jueves soy más valiente que los lunes.", en: "It depends, I think I'm braver on Thursdays than on Mondays." },
        { speaker: "B", es: "Cinco: ¿qué le dirías a alguien que empieza mañana?", en: "Five: what would you tell someone starting tomorrow?" },
        { speaker: "A", es: "Creo que diría que el español me cambió la forma de escuchar.", en: "I think I'd say Spanish changed the way I listen." },
      ],
    },
  },
  {
    day: 343,
    themeEs: "Repaso: Sin preparación",
    isRecap: true,
    vocab: [
      { es: "el programa de verano", en: "the summer program", example: "¿Te quedas con el programa de verano?" },
      { es: "sin pensar", en: "without thinking", example: "Pregúnteme y contesto sin pensar." },
      { es: "necesitaría", en: "i would need (conditional)", example: "Necesitaría saber cuántas semanas son." },
      { es: "de entrada", en: "right off the bat", example: "No digo que no de entrada." },
      { es: "el timbre", en: "the bell", example: "El timbre suena en dos minutos." },
    ],
    dialogue: {
      title: "La directora en el pasillo",
      situation: "Sin aviso, entre clases, con el timbre a dos minutos",
      lines: [
        { speaker: "B", es: "Marlana, rápido: ¿te quedas con el programa de verano?", en: "Marlana, quick: will you take the summer program?" },
        { speaker: "A", es: "Lo primero que se me ocurre es que ya dije que no a esto en enero.", en: "The first thing that comes to mind is that I already said no to this in January." },
        { speaker: "B", es: "En enero era otro programa. Este es más corto.", en: "In January it was a different program. This one is shorter." },
        { speaker: "A", es: "A ver qué sale, pregúnteme otra vez y contesto sin pensar.", en: "Let's see what comes out — ask me again and I'll answer without thinking." },
        { speaker: "B", es: "¿Te quedas con el programa de verano?", en: "Will you take the summer program?" },
        { speaker: "A", es: "Ni idea, pero necesitaría saber cuántas semanas son primero.", en: "No idea, but I'd need to know how many weeks it is first." },
        { speaker: "B", es: "Seis. De finales de junio a principios de agosto.", en: "Six. Late June to early August." },
        { speaker: "A", es: "Depende, creo que si es solo por la mañana sí podría.", en: "It depends, I think if it's mornings only I could." },
        { speaker: "B", es: "Mañanas. De ocho a doce.", en: "Mornings. Eight to twelve." },
        { speaker: "A", es: "Creo que diría que me dé hasta el viernes.", en: "I think I'd say give me until Friday." },
        { speaker: "B", es: "El viernes. Hecho. Ahí viene tu grupo.", en: "Friday. Done. Here comes your group." },
      ],
    },
  },
];
