import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 8 — "Tres temas en el café" (days 323–329).
 * Marlana and Camila talk education, technology, and language over Thursday
 * coffee — abstract ideas in spoken Spanish, with *pero* and *aun así*, not
 * essay connectors.
 */
export const priWeek8ReadingDays: ReadingDay[] = [
  {
    day: 323,
    themeEs: "La pregunta de Yesenia",
    storyTitle: "Tres temas en el café",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "en el fondo", en: "deep down, at bottom", example: "En el fondo, Yesenia no pregunta por el inglés, pregunta por su futuro." },
      { es: "la cosa es que", en: "the thing is, here's the thing", example: "La cosa es que no tenía una respuesta lista." },
      { es: "al final del día", en: "at the end of the day", example: "Al final del día, lo que importa es que quiera volver." },
      { es: "opinar", en: "to opine, to give an opinion", example: "Hoy en día todo el mundo opina de la escuela." },
      { es: "abrir la puerta", en: "to open the door (fig.)", example: "Enseñar es abrir la puerta, no llenar la cabeza." },
    ],
    dialogue: {
      title: "¿Para qué sirve el inglés?",
      situation: "Jueves en el café — Marlana llega después de clase de ESOL",
      lines: [
        { speaker: "A", es: "Yesenia me preguntó hoy: \"¿Para qué inglés si yo trabajo en cocina?\" Y me quedé muda.", en: "Yesenia asked me today: \"What do I need English for if I work in a kitchen?\" And I went silent." },
        { speaker: "B", es: "Buena pregunta. ¿Qué le dijiste?", en: "Good question. What did you tell her?" },
        { speaker: "A", es: "Le dije algo sobre oportunidades. Suena bien, pero suena a folleto.", en: "I told her something about opportunities. It sounds fine, but it sounds like a brochure." },
        { speaker: "B", es: "En el fondo, ella no pregunta por el inglés, pregunta por su futuro.", en: "Deep down, she's not asking about English, she's asking about her future." },
        { speaker: "A", es: "Exacto. La cosa es que no tenía una respuesta lista.", en: "Exactly. The thing is I didn't have a ready answer." },
        { speaker: "B", es: "Hoy en día todo el mundo opina de la escuela sin haber entrado a una. Tú sí entraste.", en: "These days everyone opines about school without ever having been in one. You have." },
        { speaker: "A", es: "Cada vez más adultos llegan a clase después del turno de noche. Ella limpia oficinas de día.", en: "More and more adults come to class after the night shift. She cleans offices during the day." },
        { speaker: "B", es: "Al final del día, lo que importa es que quiera volver el jueves.", en: "At the end of the day, what matters is that she wants to come back Thursday." },
        { speaker: "A", es: "Aun así me duele no haberle dicho la verdad completa.", en: "Still, it hurts that I didn't tell her the whole truth." },
        { speaker: "B", es: "Entonces cuéntamela aquí. Sin folleto.", en: "Then tell me here. No brochure." },
      ],
    },
  },
  {
    day: 324,
    themeEs: "La tarea que no escribió",
    storyTitle: "Tres temas en el café",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "hoy en día", en: "these days, nowadays", example: "Hoy en día un estudiante puede escribir la tarea en el ascensor." },
      { es: "la herramienta", en: "the tool", example: "La herramienta no es el enemigo, es la excusa." },
      { es: "a mano", en: "by hand", example: "Confío en una frase fea escrita a mano." },
      { es: "quedar bien", en: "to look good, to come off well", example: "El chico no quería quedar mal, quería quedar bien." },
      { es: "el guía", en: "the guide", example: "No quiero un policía en el salón, quiero un guía." },
    ],
    dialogue: {
      title: "El párrafo perfecto",
      situation: "Marlana trae un caso del colegio — tecnología en el salón",
      lines: [
        { speaker: "A", es: "Un chico entregó un párrafo perfecto. Nunca termina una frase en clase. Hoy en día eso ya es señal.", en: "A kid turned in a perfect paragraph. He never finishes a sentence in class. These days that's already a sign." },
        { speaker: "B", es: "¿Y era de él?", en: "And was it his?" },
        { speaker: "A", es: "No. Lo escribió con una app en el pasillo. En el fondo, no quería quedar mal, quería quedar bien.", en: "No. He wrote it with an app in the hallway. Deep down, he didn't want to look bad, he wanted to look good." },
        { speaker: "B", es: "Eso pasa en el hospital también. La cosa es que prohibirlo todo es fácil y no enseña nada.", en: "That happens at the hospital too. The thing is banning everything is easy and teaches nothing." },
        { speaker: "A", es: "Cada vez más tareas perfectas llegan de estudiantes callados. Pero cada vez más confío en una frase fea escrita a mano.", en: "More and more perfect assignments come from quiet students. But I trust an ugly sentence written by hand more and more." },
        { speaker: "B", es: "¿Qué vas a hacer el lunes?", en: "What are you going to do Monday?" },
        { speaker: "A", es: "Al final del día, no quiero un policía en el salón, quiero un guía. Quiero que sepa por qué importa escribir él.", en: "At the end of the day, I don't want a cop in the classroom, I want a guide. I want him to know why it matters that he writes it himself." },
        { speaker: "B", es: "Yo también uso traducción cuando estoy cansada. Aun así en mi turno no puedo delegar el cuidado.", en: "I use translation when I'm tired too. Still, on my shift I can't delegate the care." },
        { speaker: "A", es: "La cosa es que el salón no es tu cocina, Camila. Pero tienes razón en la parte de enseñar, no solo castigar.", en: "The thing is the classroom isn't your kitchen, Camila. But you're right about teaching, not just punishing." },
        { speaker: "B", es: "Bien. Segundo tema anotado. ¿Siguiente?", en: "Good. Second topic noted. Next?" },
      ],
    },
  },
  {
    day: 325,
    themeEs: "Solo inglés en casa",
    storyTitle: "Tres temas en el café",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "cada vez más", en: "more and more, increasingly", example: "Cada vez más niños traducen facturas antes de los deberes." },
      { es: "el bilingüismo", en: "bilingualism", example: "Hoy en día el bilingüismo se vende en carteles." },
      { es: "spanglish", en: "Spanglish", example: "Escucho spanglish en el pasillo y me gusta." },
      { es: "quitar", en: "to take away, to remove", example: "Quitar el español no acelera el inglés." },
      { es: "sin miedo", en: "without fear", example: "Hablar de idioma sin miedo suena distinto." },
    ],
    dialogue: {
      title: "La mamá de Diego",
      situation: "Una reunión de padres deja a Marlana pensando en idioma y casa",
      lines: [
        { speaker: "A", es: "La mamá de Diego me pidió que le recomiende \"solo inglés en casa.\" Dijo que el español lo retrasa.", en: "Diego's mom asked me to recommend \"English only at home.\" She said Spanish holds him back." },
        { speaker: "B", es: "Ay. ¿Qué respondiste?", en: "Oh. What did you answer?" },
        { speaker: "A", es: "Algo suave. Que lea en los dos. Pero en el fondo, la mamá no odia el español, odia sentirse fuera.", en: "Something soft. That he read in both. But deep down, the mom doesn't hate Spanish, she hates feeling left out." },
        { speaker: "B", es: "En el hospital veo lo mismo. Cada vez más niños traducen facturas antes de los deberes.", en: "I see the same thing at the hospital. More and more kids translate bills before homework." },
        { speaker: "A", es: "Hoy en día el bilingüismo se vende en carteles y se castiga en casa. Es raro.", en: "These days bilingualism gets sold on posters and punished at home. It's strange." },
        { speaker: "B", es: "Al final del día, quitar el español no acelera el inglés. La casa no es un salón.", en: "At the end of the day, taking away Spanish doesn't speed up English. Home isn't a classroom." },
        { speaker: "A", es: "La cosa es que no le dije todo lo que pensaba en la reunión. Sonaba a discurso.", en: "The thing is I didn't say everything I was thinking at the meeting. It would've sounded like a speech." },
        { speaker: "B", es: "Una vez una señora no entendía a la doctora y la niña tenía ocho años. La niña explicó el diagnóstico mejor que nosotras.", en: "Once a woman didn't understand the doctor and the girl was eight. The girl explained the diagnosis better than we did." },
        { speaker: "A", es: "Eso sí que es hablar de idioma sin miedo.", en: "That's talking about language without fear." },
        { speaker: "B", es: "Aun así la mamá de Diego quiere una solución rápida. Eso también es miedo.", en: "Still, Diego's mom wants a quick fix. That's fear too." },
      ],
    },
  },
  {
    day: 326,
    themeEs: "Para qué sirve",
    storyTitle: "Tres temas en el café",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "ocupado/a", en: "busy", example: "Confunden ocupados con útiles." },
      { es: "visto/a", en: "seen, noticed", example: "Miden todo excepto si alguien se siente visto." },
      { es: "puente", en: "bridge", example: "El idioma es puente, no premio." },
      { es: "prestado/a", en: "borrowed", example: "Los temas grandes suenan míos, no prestados." },
      { es: "pensar en voz alta", en: "to think out loud", example: "Sueno como alguien que piensa en voz alta." },
    ],
    dialogue: {
      title: "Educación, tecnología, idioma",
      situation: "Camila junta los tres temas de la semana",
      lines: [
        { speaker: "B", es: "Repasemos. Yesenia, el chico con la app, la mamá de Diego. Tres temas.", en: "Let's recap. Yesenia, the kid with the app, Diego's mom. Three topics." },
        { speaker: "A", es: "En el fondo, los tres temas son lo mismo: cómo vive la gente.", en: "Deep down, all three topics are the same thing: how people live." },
        { speaker: "B", es: "Hoy en día miden todo excepto si alguien se siente visto.", en: "These days they measure everything except whether someone feels seen." },
        { speaker: "A", es: "Cada vez más puedo decir esto en español sin buscar la palabra en inglés. Eso me sorprende.", en: "More and more I can say this in Spanish without looking for the word in English. That surprises me." },
        { speaker: "B", es: "¿Para qué sirve, entonces, todo lo que haces?", en: "So what is everything you do for?" },
        { speaker: "A", es: "Al final del día, sirve si alguien se va con más puertas abiertas. Yesenia, el chico, Diego.", en: "At the end of the day, it works if someone leaves with more doors open. Yesenia, the kid, Diego." },
        { speaker: "B", es: "En el hospital es igual. En el fondo, enseñar y cuidar es lo mismo.", en: "At the hospital it's the same. Deep down, teaching and caring are the same thing." },
        { speaker: "A", es: "La cosa es que estos temas me asustaban porque sonaban a ensayo. Pero hoy suenan a mesa de café.", en: "The thing is these topics scared me because they sounded like essays. But today they sound like a café table." },
        { speaker: "B", es: "Porque hablas de gente, no de ideas sueltas.", en: "Because you're talking about people, not loose ideas." },
        { speaker: "A", es: "Aun así mañana vuelvo al salón y no a la mesa. Quiero llevarme esto.", en: "Still, tomorrow I'm back in the classroom, not at the table. I want to take this with me." },
      ],
    },
  },
  {
    day: 327,
    themeEs: "El teléfono en la mochila",
    storyTitle: "Tres temas en el café",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "aun así", en: "even so, still", example: "Entiendo tu punto, pero aun así mi salón es distinto." },
      { es: "la pantalla", en: "the screen", example: "Tenemos miedo a perder a los chicos en la pantalla." },
      { es: "prohibir", en: "to ban, to forbid", example: "Prohibir no enseña límites, enseña a esconderse." },
      { es: "la curiosidad", en: "curiosity", example: "Yo quiero proteger la curiosidad." },
      { es: "pensar distinto", en: "to think differently", example: "Podemos pensar distinto y seguir tomando café." },
    ],
    dialogue: {
      title: "¿Prohibir los teléfonos?",
      situation: "Camila y Marlana no piensan igual — debate suave",
      lines: [
        { speaker: "B", es: "En mi turno quitaría todos los teléfonos. En serio.", en: "On my shift I'd take away all the phones. Seriously." },
        { speaker: "A", es: "En el fondo, los dos tenemos miedo a perder a los chicos en la pantalla.", en: "Deep down, we both fear losing the kids to the screen." },
        { speaker: "B", es: "Hoy en día un teléfono es traductor, mapa y calendario. Pero en el hospital una notificación puede matar un turno.", en: "These days a phone is translator, map, and calendar. But at the hospital one notification can wreck a shift." },
        { speaker: "A", es: "La cosa es que entiendo tu punto, pero mi salón no es tu turno de noche.", en: "The thing is I get your point, but my classroom isn't your night shift." },
        { speaker: "B", es: "Cada vez más prefiero reglas claras a discursos largos. Eso te suena.", en: "I prefer clear rules to long speeches more and more. That sound like you?" },
        { speaker: "A", es: "Me suena. Pero cada vez más veo que el ejemplo mío importa más que la norma.", en: "It does. But I see more and more that my example matters more than the rule." },
        { speaker: "B", es: "Al final del día, Camila tiene razón en el hospital y tú en el salón.", en: "At the end of the day, Camila is right at the hospital and you are in the classroom." },
        { speaker: "A", es: "Al final del día, quiero atención, no obediencia ciega. Quiero enseñar cuándo mirar y cuándo soltar.", en: "At the end of the day, I want attention, not blind obedience. I want to teach when to look and when to let go." },
        { speaker: "B", es: "Aun así yo los quitaría cinco minutos. Solo cinco.", en: "Even so, I'd take them away for five minutes. Just five." },
        { speaker: "A", es: "Eso sí puedo probarlo el lunes. La cosa es que podemos pensar distinto y seguir tomando café.", en: "I can try that Monday. The thing is we can think differently and keep having coffee." },
      ],
    },
  },
  {
    day: 328,
    themeEs: "Tres temas, una mesa",
    storyTitle: "Tres temas en el café",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "folleto", en: "brochure, pamphlet", example: "Hoy en día puedo opinar sin sonar como folleto." },
      { es: "el hilo", en: "the thread (of conversation)", example: "Uno puede cambiar de tema sin perder el hilo." },
      { es: "profundizar", en: "to go deeper", example: "La próxima semana toca profundizar." },
      { es: "vestirse de gala", en: "to dress up formally", example: "El español aguanta ideas grandes sin vestirse de gala." },
      { es: "sueltos", en: "loose, separate", example: "La conversación larga empieza con tres temas sueltos." },
    ],
    dialogue: {
      title: "Sin sonar a ensayo",
      situation: "Cierran la semana — registro hablado, temas grandes",
      lines: [
        { speaker: "A", es: "Si me grabaras hace tres meses hablando de educación, sonaba a traducción del inglés.", en: "If you recorded me three months ago talking about education, I sounded like translation from English." },
        { speaker: "B", es: "¿Y ahora?", en: "And now?" },
        { speaker: "A", es: "Hoy en día puedo opinar sin sonar como folleto. Digo \"en el fondo\" y no me río.", en: "These days I can give an opinion without sounding like a brochure. I say \"deep down\" and I don't laugh." },
        { speaker: "B", es: "Cada vez más aguantas tres minutos en un tema abstracto. Eso es conversación de verdad.", en: "More and more you hold three minutes on an abstract topic. That's a real conversation." },
        { speaker: "A", es: "Al final del día, los temas grandes caben en una mesa pequeña. Yesenia, el chico y la mamá son la teoría.", en: "At the end of the day, big topics fit on a small table. Yesenia, the kid, and the mom are the theory." },
        { speaker: "B", es: "En el fondo, hablar de escuela es hablar de miedo y de futuro.", en: "Deep down, talking about school is talking about fear and future." },
        { speaker: "A", es: "La cosa es que ya no necesito permiso para tener una opinión.", en: "The thing is I don't need permission to have an opinion anymore." },
        { speaker: "B", es: "El español aguanta ideas grandes sin vestirse de gala. Usaste *pero* y *aun así* toda la semana.", en: "Spanish can hold big ideas without dressing up. You used *pero* and *aun así* all week." },
        { speaker: "A", es: "Nunca dije *sin embargo* en voz alta. Gracias a Dios.", en: "I never said *however* out loud. Thank God." },
        { speaker: "B", es: "La cosa es que la conversación larga empieza así, con tres temas sueltos y un café.", en: "The thing is a long conversation starts like this, with three loose topics and a coffee." },
      ],
    },
  },
  {
    day: 329,
    themeEs: "Repaso: Temas grandes",
    isRecap: true,
    vocab: [
      { es: "abstracto/a", en: "abstract", example: "Aguanto tres minutos en un tema abstracto." },
      { es: "concreto/a", en: "concrete", example: "Mezclo lo concreto y lo grande en la misma frase." },
      { es: "el registro", en: "register, tone", example: "Hablar sin folleto es cambio de registro." },
      { es: "profundizar", en: "to go deeper", example: "La próxima semana toca profundizar." },
      { es: "opinión incompleta", en: "incomplete opinion", example: "Confío en una opinión incompleta dicha en español." },
    ],
    dialogue: {
      title: "Cinco stems, tres temas",
      situation: "Repaso de la semana — educación, tecnología, idioma",
      lines: [
        { speaker: "B", es: "Repaso. Tres temas en el café. ¿Qué aprendiste?", en: "Recap. Three topics at the café. What did you learn?" },
        { speaker: "A", es: "En el fondo, esta semana fue hablar de gente, no de ideas sueltas.", en: "Deep down, this week was talking about people, not loose ideas." },
        { speaker: "B", es: "Dame los cinco stems en orden.", en: "Give me the five stems in order." },
        { speaker: "A", es: "Verdad: en el fondo… Presente: hoy en día… Tendencia: cada vez más… Cierre: al final del día… Honestidad: la cosa es que…", en: "Truth: deep down… Present: these days… Trend: more and more… Close: at the end of the day… Honesty: the thing is…" },
        { speaker: "B", es: "¿Y los tres temas?", en: "And the three topics?" },
        { speaker: "A", es: "Educación con Yesenia. Tecnología con el chico del párrafo perfecto. Idioma con la mamá de Diego.", en: "Education with Yesenia. Technology with the kid and the perfect paragraph. Language with Diego's mom." },
        { speaker: "B", es: "Al final del día, enseñar, traducir y aprender usan la misma paciencia.", en: "At the end of the day, teaching, translating, and learning use the same patience." },
        { speaker: "A", es: "La cosa es que *pero* y *aun así* llevan más lejos que *sin embargo* en una mesa.", en: "The thing is *pero* and *aun así* get you further than *however* at a table." },
        { speaker: "B", es: "Cada vez más suena a ti. La próxima semana profundizas: *¿Y eso?* · *¿Cómo así?*", en: "More and more it sounds like you. Next week you go deeper: *And that?* · *How so?*" },
        { speaker: "A", es: "Bien. Pero hoy me quedo con el café.", en: "Good. But today I'm staying with the coffee." },
      ],
    },
  },
];
