import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 3 — "Mil años en el metro" (days 288–294).
 * Marlana's Boston commute becomes the canvas for hyperbole with color.
 * Cast: Marlana (A), Camila (B); Rocío joins on day 293.
 */
export const priWeek3ReadingDays: ReadingDay[] = [
  {
    day: 288,
    themeEs: "Mil años en el metro",
    storyTitle: "Mil años en el metro",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "exagerar", en: "to exaggerate", example: "Camila me enseñó a exagerar con gracia." },
      { es: "el andén", en: "the platform", example: "Esperé en el andén veinte minutos." },
      { es: "el trayecto", en: "the commute, the route", example: "Mi trayecto tiene dos transbordos." },
      { es: "con color", en: "with color, vividly", example: "Cuéntalo con color, no con minutos." },
      { es: "la tarjeta del mes", en: "the monthly pass", example: "Es una barbaridad lo que cuesta la tarjeta del mes." },
    ],
    dialogue: {
      title: "No con minutos, con drama",
      situation: "Camila llama mientras Marlana baja del tren",
      lines: [
        { speaker: "A", es: "Llegué. Tardé cuarenta y tres minutos desde Davis.", en: "I'm here. It took forty-three minutes from Davis." },
        { speaker: "B", es: "¿Cuarenta y tres? Marlana, eso suena a reporte.", en: "Forty-three? Marlana, that sounds like a report." },
        { speaker: "A", es: "¿Y cómo más lo digo?", en: "And how else am I supposed to say it?" },
        { speaker: "B", es: "Con color. Di: tardé mil años. Me muero de sueño. Es lo peor del mundo ese andén mojado.", en: "With color. Say: it took me forever. I'm dying of sleep. That wet platform is the worst thing in the world." },
        { speaker: "A", es: "Pero si fueron cuarenta y tres…", en: "But it really was forty-three…" },
        { speaker: "B", es: "Nadie te va a revisar el reloj. Te van a creer el sentimiento.", en: "Nobody's going to check your watch. They'll believe the feeling." },
        { speaker: "A", es: "Es una barbaridad lo que cuesta la tarjeta del mes, eso sí es verdad.", en: "It's outrageous what the monthly pass costs — that part is true." },
        { speaker: "B", es: "Exacto. Esta semana entera: exagerar con gracia. El metro te va a dar material de sobra.", en: "Exactly. This whole week: exaggerating with grace. The subway's going to give you more than enough material." },
        { speaker: "A", es: "Bueno. Mañana no digo cuarenta y tres. Digo mil años.", en: "Fine. Tomorrow I won't say forty-three. I'll say a thousand years." },
      ],
    },
  },
  {
    day: 289,
    themeEs: "Me muero de…",
    storyTitle: "Mil años en el metro",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "me muero de", en: "I'm dying of (hyperbolic)", example: "Me muero de hambre en el vagón." },
      { es: "de pie", en: "standing", example: "Fui de pie todo el trayecto." },
      { es: "el aire acondicionado", en: "the air conditioning", example: "El aire acondicionado no sirve." },
      { es: "ceder el asiento", en: "to give up one's seat", example: "Alguien me cedió el asiento." },
      { es: "la parada", en: "the stop", example: "Todavía me faltan dos paradas." },
    ],
    dialogue: {
      title: "El cuerpo en el tren",
      situation: "Marlana cuenta su mañana sin desayuno",
      lines: [
        { speaker: "A", es: "Me muero de hambre y todavía me faltan dos paradas.", en: "I'm dying of hunger and I still have two stops left." },
        { speaker: "B", es: "¿Ves? Eso suena a persona, no a horario.", en: "See? That sounds like a person, not a schedule." },
        { speaker: "A", es: "Me muero de calor, el aire acondicionado no sirve.", en: "I'm dying of heat — the air conditioning doesn't work." },
        { speaker: "B", es: "Mejor. Sigue.", en: "Better. Keep going." },
        { speaker: "A", es: "Fui de pie todo el trayecto. Es lo peor del mundo.", en: "I stood the whole way. It's the worst thing in the world." },
        { speaker: "B", es: "¿Y algo bueno?", en: "And something good?" },
        { speaker: "A", es: "El olor del café en la estación es lo mejor del mundo.", en: "The smell of coffee at the station is the best thing in the world." },
        { speaker: "B", es: "¡Ahí está! Lo pequeño, la frase grande.", en: "There it is! Small thing, big phrase." },
        { speaker: "A", es: "Es una barbaridad la cantidad de gente a las siete.", en: "It's outrageous how many people there are at seven." },
      ],
    },
  },
  {
    day: 290,
    themeEs: "Tardé mil años",
    storyTitle: "Mil años en el metro",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el bus de reemplazo", en: "the shuttle bus", example: "Nos mandaron en bus de reemplazo." },
      { es: "el transbordo", en: "the transfer", example: "Perdí el transbordo en Park Street." },
      { es: "demora menor", en: "minor delay", example: "Dijeron demora menor y fueron veinte minutos." },
      { es: "la señal", en: "the signal (train service)", example: "Hubo un problema de señal en la línea roja." },
      { es: "la campana", en: "the bell (train chime)", example: "Cuando suena la campana, corro." },
    ],
    dialogue: {
      title: "Siglos en el andén",
      situation: "Una mañana de bus de reemplazo y dos transbordos",
      lines: [
        { speaker: "A", es: "Hoy sí tardé mil años. Nos mandaron en bus de reemplazo.", en: "Today I really did take forever. They sent us on a shuttle bus." },
        { speaker: "B", es: "¿Y cómo te sentiste esperando?", en: "And how did you feel waiting?" },
        { speaker: "A", es: "Me muero de aburrimiento en el andén.", en: "I'm dying of boredom on the platform." },
        { speaker: "B", es: "Bien. El aburrimiento también cuenta.", en: "Good. Boredom counts too." },
        { speaker: "A", es: "Perdí la conexión en Park Street. Es lo peor del mundo.", en: "I missed the connection at Park Street. It's the worst thing in the world." },
        { speaker: "B", es: "¿Y cuando llegó el tren?", en: "And when the train finally came?" },
        { speaker: "A", es: "Ver llegar el tren es lo mejor del mundo.", en: "Seeing the train arrive is the best thing in the world." },
        { speaker: "B", es: "Lo sabía. Siempre hay un momento bueno escondido.", en: "I knew it. There's always a good moment hiding in there." },
        { speaker: "A", es: "Es una barbaridad que digan \"demora menor\" y sean veinte minutos.", en: "It's outrageous when they say \"minor delay\" and it's twenty minutes." },
      ],
    },
  },
  {
    day: 291,
    themeEs: "Es lo mejor del mundo",
    storyTitle: "Mil años en el metro",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "el alivio", en: "the relief", example: "Me muero de alivio porque hubo asiento." },
      { es: "valer la pena", en: "to be worth it", example: "Tardé mil años, pero valió la pena." },
      { es: "de corrido", en: "in one go, straight through", example: "El transbordo salió de corrido." },
      { es: "exageración", en: "exaggeration", example: "Me muero de risa con tus exageraciones." },
      { es: "desproporcionado", en: "disproportionate", example: "Es una barbaridad lo emocionada que me puse." },
    ],
    dialogue: {
      title: "Lo pequeño que salva el día",
      situation: "Jueves en el café — un buen viaje por fin",
      lines: [
        { speaker: "B", es: "¿Cómo estuvo el metro hoy?", en: "How was the subway today?" },
        { speaker: "A", es: "Tardé mil años, pero llegué antes que ayer.", en: "It took me forever, but I got here before yesterday." },
        { speaker: "B", es: "Comparar con ayer. Me gusta.", en: "Comparing with yesterday. I like it." },
        { speaker: "A", es: "Encontrarte en el café es lo mejor del mundo.", en: "Finding you at the café is the best thing in the world." },
        { speaker: "B", es: "Ay, qué exagerada. Pero gracias.", en: "Oh, you're so dramatic. But thank you." },
        { speaker: "A", es: "Me muero de risa con tus exageraciones, Camila.", en: "I'm dying of laughter at your exaggerations, Camila." },
        { speaker: "B", es: "Es lo mejor del mundo exagerar sin mentir.", en: "It's the best thing in the world to exaggerate without lying." },
        { speaker: "A", es: "Es una barbaridad lo bien que me sentí por un asiento.", en: "It's outrageous how good I felt over one seat." },
        { speaker: "B", es: "Eso es exagerar con gracia. Sigue mañana.", en: "That's exaggerating with grace. Keep going tomorrow." },
      ],
    },
  },
  {
    day: 292,
    themeEs: "Es lo peor del mundo",
    storyTitle: "Mil años en el metro",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "demora indefinida", en: "indefinite delay", example: "Sonó demora indefinida en el túnel." },
      { es: "el túnel", en: "the tunnel", example: "Nos quedamos paradas en el túnel." },
      { es: "empapada", en: "soaked", example: "Llegué empapada y tarde." },
      { es: "la vergüenza", en: "embarrassment", example: "Me muero de vergüenza." },
      { es: "minimizar", en: "to minimize, downplay", example: "No lo minimices por educación." },
    ],
    dialogue: {
      title: "Demora indefinida",
      situation: "El peor día de la semana — parada en el túnel",
      lines: [
        { speaker: "A", es: "Me muero de vergüenza. Llegué tarde otra vez.", en: "I'm dying of embarrassment. I was late again." },
        { speaker: "B", es: "¿Qué pasó?", en: "What happened?" },
        { speaker: "A", es: "Quedarse parada en el túnel es lo peor del mundo. Sonó \"demora indefinida\".", en: "Getting stuck in the tunnel is the worst thing in the world. They announced \"indefinite delay.\"" },
        { speaker: "B", es: "Esa frase da miedo en cualquier idioma.", en: "That phrase is scary in any language." },
        { speaker: "A", es: "Tardé mil años y la directora ya estaba en la puerta.", en: "It took me forever and the principal was already at the door." },
        { speaker: "B", es: "¿Y algo bueno en medio del desastre?", en: "And something good in the middle of the disaster?" },
        { speaker: "A", es: "Lo único bueno: es lo mejor del mundo que tú me escuchas.", en: "The one good thing: it's the best thing in the world that you listen to me." },
        { speaker: "B", es: "Pues aquí estoy. Sin decirte que no exageres.", en: "Well, I'm here. Without telling you not to exaggerate." },
        { speaker: "A", es: "Es una barbaridad y mañana lo vuelvo a intentar.", en: "It's outrageous, and tomorrow I'll try again anyway." },
      ],
    },
  },
  {
    day: 293,
    themeEs: "Es una barbaridad",
    storyTitle: "Mil años en el metro",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "comparar sufrimientos", en: "to compare suffering (playfully)", example: "Es una barbaridad comparar sufrimientos en voz alta." },
      { es: "el turno de noche", en: "the night shift", example: "Camila sale del turno de noche a las siete." },
      { es: "turismo", en: "tourism (here: easy ride)", example: "Camila dice que mi viaje es turismo." },
      { es: "quejarse", en: "to complain", example: "Es lo mejor del mundo quejarse sin que nadie corrija." },
      { es: "aun así", en: "even so, anyway", example: "Es una barbaridad, y aun así nos quedamos." },
    ],
    dialogue: {
      title: "Tres barbaridades, una mesa",
      situation: "Rocío se une al café del jueves — competencia de trayectos",
      lines: [
        { speaker: "B", es: "Rocío, cuéntale a Marlana tu trayecto.", en: "Rocío, tell Marlana about your commute." },
        { speaker: "A", es: "Rocío dice que tardó mil años en el bus 39.", en: "Rocío says it took her forever on the 39 bus." },
        { speaker: "B", es: "El bus de Rocío es lo peor del mundo, dice ella.", en: "Rocío's bus is the worst thing in the world, she says." },
        { speaker: "A", es: "Me muero de risa escuchándolas a las dos.", en: "I'm dying of laughter listening to you two." },
        { speaker: "B", es: "Camila sale del hospital a las siete. Eso sí es lo peor del mundo.", en: "Camila leaves the hospital at seven. That really is the worst thing in the world." },
        { speaker: "A", es: "Tardé mil años, pero Camila dice que eso es turismo.", en: "It took me forever, but Camila says that's tourism." },
        { speaker: "B", es: "Es una barbaridad lo que pagamos por vivir aquí.", en: "It's outrageous what we pay to live here." },
        { speaker: "A", es: "Es una barbaridad, y aun así nos quedamos.", en: "It's outrageous, and we stay anyway." },
        { speaker: "B", es: "Este café los jueves es lo mejor del mundo. Fin de la competencia.", en: "This café on Thursdays is the best thing in the world. End of the competition." },
      ],
    },
  },
  {
    day: 294,
    themeEs: "Repaso: Exagerar con gracia",
    isRecap: true,
    vocab: [
      { es: "con gracia", en: "with grace, gracefully", example: "Exagerar con gracia no es mentir." },
      { es: "contar el tiempo", en: "to tell time, to measure time", example: "Mil años es mi forma de contar el tiempo." },
      { es: "humanizar", en: "to humanize", example: "Suena humano, no a reporte." },
      { es: "dejar de", en: "to stop (doing something)", example: "Dejé de contar minutos." },
      { es: "material", en: "material, content", example: "El metro me dio material de sobra." },
    ],
    dialogue: {
      title: "Seis días de color",
      situation: "Repaso del jueves — qué cambió en la forma de contar el viaje",
      lines: [
        { speaker: "B", es: "Repaso. ¿Qué aprendiste esta semana del metro?", en: "Recap. What did you learn from the subway this week?" },
        { speaker: "A", es: "Dejé de contar minutos. Tardé mil años se convirtió en mi forma de contar el tiempo.", en: "I stopped counting minutes. \"It took me forever\" became my way of telling time." },
        { speaker: "B", es: "¿Y me muero de?", en: "And \"I'm dying of\"?" },
        { speaker: "A", es: "Me muero de ganas de usar esto en la vida real. Suena a mí.", en: "I'm dying to use this in real life. It sounds like me." },
        { speaker: "B", es: "¿Lo mejor y lo peor del mundo?", en: "The best and worst thing in the world?" },
        { speaker: "A", es: "Es lo mejor del mundo exagerar sin mentir. Es lo peor del mundo minimizarlo por educación.", en: "It's the best thing in the world to exaggerate without lying. It's the worst thing in the world to downplay it out of politeness." },
        { speaker: "B", es: "¿Y la barbaridad?", en: "And the outrage?" },
        { speaker: "A", es: "Es una barbaridad, dijo Rocío, y tenía razón. Es una barbaridad, y por eso me gusta.", en: "\"It's outrageous,\" Rocío said, and she was right. It's outrageous, and that's why I like it." },
        { speaker: "B", es: "Seis días de color. Cero mentiras. La próxima semana: historias con sabor.", en: "Six days of color. Zero lies. Next week: stories with flavor." },
      ],
    },
  },
];
