import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 4 — "Historias con sabor" (days 295–301).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week4-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek4SpeakDays: SpeakDay[] = [
  {
    day: 295,
    themeEs: "El ascensor se paró",
    themeEn: "The elevator stopped",
    missionEs: "Cuenta qué pasó en el ascensor con el gancho y para colmo.",
    missionEn: "Tell what happened in the elevator using the hook and \"on top of that.\"",
    line: "El ascensor se paró entre el quinto y el sexto piso.",
    lineEn: "The elevator stopped between the fifth and sixth floor.",
    prompts: [
      {
        id: "d295-no-te-vas",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what happened in the elevator today.",
        spanish: "No te vas a creer lo que pasó en el ascensor hoy.",
        situationLabel: "El gancho",
        why: "*No te vas a creer* is the hook — you say it *before* the story, not after. The listener leans in automatically.",
        wordHints: [
          { en: "you're not going to believe", es: "no te vas a creer" },
          { en: "what happened", es: "lo que pasó" },
          { en: "in the elevator", es: "en el ascensor" },
        ],
      },
      {
        id: "d295-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, parent night started in twenty minutes.",
        spanish: "Para colmo, la noche de padres empezaba en veinte minutos.",
        situationLabel: "Apilando lo malo",
        why: "*Para colmo* piles on the bad luck — the *second* thing that makes the story worse, not the first.",
        wordHints: [
          { en: "on top of that", es: "para colmo" },
          { en: "parent night", es: "la noche de padres" },
          { en: "twenty minutes", es: "veinte minutos" },
        ],
      },
      {
        id: "d295-y-de-repente",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — the elevator moved an inch.",
        spanish: "Y de repente, ¡pum!, el ascensor se movió un centímetro.",
        situationLabel: "El momento",
        why: "*¡Pum!* is the sound effect — the moment the story turns. You can whisper it or shout it; both work.",
        wordHints: [
          { en: "and suddenly", es: "y de repente" },
          { en: "bam", es: "¡pum!" },
          { en: "moved an inch", es: "se movió un centímetro" },
        ],
      },
      {
        id: "d295-lo-peor",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is I had to stay calm in front of the mom.",
        spanish: "Y lo peor es que tuve que quedarme tranquila delante de la mamá.",
        situationLabel: "Tu peor momento",
        why: "*Lo peor* is subjective — your worst moment, not necessarily the objectively worst thing that happened.",
        wordHints: [
          { en: "the worst part is", es: "y lo peor es que" },
          { en: "stay calm", es: "quedarme tranquila" },
          { en: "in front of the mom", es: "delante de la mamá" },
        ],
      },
      {
        id: "d295-imaginate",
        frameStem: "Imagínate que…",
        english: "Just imagine we're trapped between the fifth and sixth floor.",
        spanish: "Imagínate que estamos atrapadas entre el quinto y el sexto piso.",
        situationLabel: "Metiendo al oyente",
        why: "*Imagínate que* pulls the listener into the scene — more vivid than *te cuento que* because they have to see it.",
        wordHints: [
          { en: "just imagine", es: "imagínate" },
          { en: "we're trapped", es: "estamos atrapadas" },
          { en: "fifth and sixth floor", es: "quinto y sexto piso" },
        ],
      },
    ],
  },
  {
    day: 296,
    themeEs: "Atrapadas con la olla",
    themeEn: "Trapped with the pot",
    missionEs: "Describe los diez minutos atrapadas: para colmo y lo peor.",
    missionEn: "Describe the ten minutes trapped: \"on top of that\" and \"the worst part.\"",
    line: "Doña Carmen con la olla de sopa en brazos, y nadie se mueve.",
    lineEn: "Doña Carmen holding a pot of soup, and nobody's moving.",
    prompts: [
      {
        id: "d296-no-te-vas",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what Rocío said to calm Doña Carmen.",
        spanish: "No te vas a creer lo que dijo Rocío para calmar a Doña Carmen.",
        situationLabel: "Rocío en modo calma",
        why: "The hook can point at a person, not just an event — *lo que dijo Rocío* makes her part of the drama.",
        wordHints: [
          { en: "what rocío said", es: "lo que dijo rocío" },
          { en: "to calm", es: "para calmar" },
          { en: "doña carmen", es: "doña carmen" },
        ],
      },
      {
        id: "d296-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, the pot lid shifted and a little spilled.",
        spanish: "Para colmo, la tapa de la olla se movió y se derramó un poco.",
        situationLabel: "La olla ataca",
        why: "*Se derramó* — it spilled. Passive and blameless, like *se cortó* on a phone call.",
        wordHints: [
          { en: "the lid", es: "la tapa" },
          { en: "the pot", es: "la olla" },
          { en: "spilled a little", es: "se derramó un poco" },
        ],
      },
      {
        id: "d296-y-de-repente",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — someone pressed the emergency button again.",
        spanish: "Y de repente, ¡pum!, alguien apretó el botón de emergencia otra vez.",
        situationLabel: "Segundo susto",
        why: "Stories can have more than one *¡pum!* — each one is a mini-turn inside the bigger story.",
        wordHints: [
          { en: "someone pressed", es: "alguien apretó" },
          { en: "emergency button", es: "botón de emergencia" },
          { en: "again", es: "otra vez" },
        ],
      },
      {
        id: "d296-lo-peor",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is I had to smile like nothing was happening.",
        spanish: "Y lo peor es que tuve que sonreír como si nada pasara.",
        situationLabel: "Fingir calma",
        why: "*Como si nada pasara* — as if nothing were happening. The imperfect subjunctive arrives as a chunk you already need.",
        wordHints: [
          { en: "i had to smile", es: "tuve que sonreír" },
          { en: "as if nothing", es: "como si nada" },
          { en: "were happening", es: "pasara" },
        ],
      },
      {
        id: "d296-imaginate",
        frameStem: "Imagínate que…",
        english: "Picture Rocío saying \"let's breathe\" and me translating to English in my head.",
        spanish: "Imagínate que Rocío dice \"respiremos\" y yo traduzco al inglés en mi cabeza.",
        situationLabel: "Dentro de la cabeza",
        why: "Inner monologue in a story is fair game — *en mi cabeza* tells the listener you're showing them the inside.",
        wordHints: [
          { en: "let's breathe", es: "respiremos" },
          { en: "i translate", es: "traduzco" },
          { en: "in my head", es: "en mi cabeza" },
        ],
      },
    ],
  },
  {
    day: 297,
    themeEs: "Las luces se apagaron",
    themeEn: "The lights went out",
    missionEs: "Cuenta la parte oscura: ¡pum! y cómo salieron.",
    missionEn: "Tell the dark part: \"bam!\" and how they got out.",
    line: "Se fue la luz y a tu teléfono le quedaba dos por ciento.",
    lineEn: "The lights went out and your phone was at two percent.",
    prompts: [
      {
        id: "d297-no-te-vas",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what happened when the lights went out.",
        spanish: "No te vas a creer lo que pasó cuando se apagaron las luces.",
        situationLabel: "La oscuridad",
        why: "Darkness in a stuck elevator is a classic beat — the story earns drama without exaggerating the danger.",
        wordHints: [
          { en: "when the lights went out", es: "cuando se apagaron las luces" },
          { en: "what happened", es: "lo que pasó" },
        ],
      },
      {
        id: "d297-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, my phone had two percent battery.",
        spanish: "Para colmo, mi celular tenía dos por ciento de batería.",
        situationLabel: "Sin rescate digital",
        why: "Modern horror: *dos por ciento de batería*. Everyone understands that one instantly.",
        wordHints: [
          { en: "my phone", es: "mi celular" },
          { en: "two percent", es: "dos por ciento" },
          { en: "battery", es: "batería" },
        ],
      },
      {
        id: "d297-y-de-repente",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — the lights came back and we saw the broth on the floor.",
        spanish: "Y de repente, ¡pum!, volvieron las luces y vimos el caldo en el piso.",
        situationLabel: "Revelación",
        why: "The *¡pum!* plus a visual detail — *vimos el caldo* — is how you turn relief into comedy.",
        wordHints: [
          { en: "the lights came back", es: "volvieron las luces" },
          { en: "we saw", es: "vimos" },
          { en: "broth on the floor", es: "caldo en el piso" },
        ],
      },
      {
        id: "d297-lo-peor",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is we got out in front of a fifth-grade group.",
        spanish: "Y lo peor es que salimos frente a un grupo de quinto grado.",
        situationLabel: "Audiencia involuntaria",
        why: "Social embarrassment beats physical danger in most school stories — and it's funnier to retell.",
        wordHints: [
          { en: "we got out", es: "salimos" },
          { en: "in front of", es: "frente a" },
          { en: "fifth grade group", es: "grupo de quinto grado" },
        ],
      },
      {
        id: "d297-imaginate",
        frameStem: "Imagínate que…",
        english: "Just imagine you step out of the elevator and the principal is already waiting.",
        spanish: "Imagínate que sales del ascensor y la directora ya te está esperando.",
        situationLabel: "La directora",
        why: "*Ya te está esperando* — already waiting for you. The *ya* makes it worse before you say a word.",
        wordHints: [
          { en: "you step out", es: "sales" },
          { en: "the principal", es: "la directora" },
          { en: "already waiting", es: "ya te está esperando" },
        ],
      },
    ],
  },
  {
    day: 298,
    themeEs: "Contárselo en la noche de padres",
    themeEn: "Telling it at parent night",
    missionEs: "Cuenta la historia otra vez en la noche de padres.",
    missionEn: "Tell the story again at parent night.",
    line: "La segunda vez se la cuentas a una mamá, de pie, con café en la mano.",
    lineEn: "The second time you tell it to a mom, standing up, holding a coffee.",
    prompts: [
      {
        id: "d298-no-te-vas",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what I told a mom at parent night.",
        spanish: "No te vas a creer lo que le conté a una mamá en la noche de padres.",
        situationLabel: "Segunda audiencia",
        why: "Retelling to a new audience is practice — the hook works the same way every time.",
        wordHints: [
          { en: "what i told", es: "lo que le conté" },
          { en: "a mom", es: "una mamá" },
          { en: "parent night", es: "noche de padres" },
        ],
      },
      {
        id: "d298-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, I used all five stems without realizing.",
        spanish: "Para colmo, usé las cinco muletillas sin darme cuenta.",
        situationLabel: "Los stems solos",
        why: "When the frames become automatic, you stop thinking about grammar and start thinking about the story.",
        wordHints: [
          { en: "all five", es: "las cinco" },
          { en: "fillers/stems", es: "muletillas" },
          { en: "without realizing", es: "sin darme cuenta" },
        ],
      },
      {
        id: "d298-y-de-repente",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — the whole table laughed when I said \"bam!\"",
        spanish: "Y de repente, ¡pum!, toda la mesa se rió cuando dije \"¡pum!\"",
        situationLabel: "Meta-humor",
        why: "Quoting your own *¡pum!* inside the story is allowed — it's how you show you know you're performing.",
        wordHints: [
          { en: "the whole table", es: "toda la mesa" },
          { en: "laughed", es: "se rió" },
          { en: "when i said", es: "cuando dije" },
        ],
      },
      {
        id: "d298-lo-peor",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is I enjoyed telling it.",
        spanish: "Y lo peor es que me gustó contarlo.",
        situationLabel: "Disfrutar contar",
        why: "*Me gustó contarlo* — enjoying the telling is the primavera goal. The story is material now, not trauma.",
        wordHints: [
          { en: "i enjoyed", es: "me gustó" },
          { en: "telling it", es: "contarlo" },
        ],
      },
      {
        id: "d298-imaginate",
        frameStem: "Imagínate que…",
        english: "Picture telling the story and everyone stops eating cookies.",
        spanish: "Imagínate que cuentas la historia y todos dejan de comer galletas.",
        situationLabel: "Tienen tu atención",
        why: "A detail like *dejan de comer galletas* is proof the story landed — better than \"everyone listened.\"",
        wordHints: [
          { en: "you tell the story", es: "cuentas la historia" },
          { en: "everyone stops", es: "todos dejan de" },
          { en: "eating cookies", es: "comer galletas" },
        ],
      },
    ],
  },
  {
    day: 299,
    themeEs: "En el café del jueves",
    themeEn: "At Thursday café",
    missionEs: "Cuéntale a Camila la versión completa con los cinco stems.",
    missionEn: "Tell Camila the full version using all five stems.",
    line: "Camila pide drama. Tú se lo das.",
    lineEn: "Camila asks for drama. You deliver.",
    prompts: [
      {
        id: "d299-no-te-vas",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what happened to me Tuesday at school.",
        spanish: "No te vas a creer lo que me pasó el martes en el colegio.",
        situationLabel: "Abriendo en el café",
        why: "At the café, the hook is how you take the floor — Camila knows something happened before you say what.",
        wordHints: [
          { en: "what happened to me", es: "lo que me pasó" },
          { en: "tuesday", es: "el martes" },
          { en: "at school", es: "en el colegio" },
        ],
      },
      {
        id: "d299-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, Camila has a worse hospital elevator story.",
        spanish: "Para colmo, Camila tiene una historia del ascensor del hospital peor.",
        situationLabel: "Camila compite",
        why: "Storytelling between friends includes one-upping — *peor* invites her to tell hers next.",
        wordHints: [
          { en: "camila has", es: "camila tiene" },
          { en: "elevator story", es: "historia del ascensor" },
          { en: "worse", es: "peor" },
        ],
      },
      {
        id: "d299-y-de-repente",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — Camila hits the table when I say the lights went out.",
        spanish: "Y de repente, ¡pum!, Camila golpea la mesa cuando digo que se apagaron las luces.",
        situationLabel: "Camila reacciona",
        why: "A listener who physically reacts is the best sign your *¡pum!* landed on time.",
        wordHints: [
          { en: "hits the table", es: "golpea la mesa" },
          { en: "when i say", es: "cuando digo" },
          { en: "the lights went out", es: "se apagaron las luces" },
        ],
      },
      {
        id: "d299-lo-peor",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is Camila says the ending needs more drama.",
        spanish: "Y lo peor es que Camila dice que le falta más drama al final.",
        situationLabel: "Crítica de Camila",
        why: "*Le falta más drama* — feedback as a story beat. Camila is your editor, not your judge.",
        wordHints: [
          { en: "it needs", es: "le falta" },
          { en: "more drama", es: "más drama" },
          { en: "the ending", es: "al final" },
        ],
      },
      {
        id: "d299-imaginate",
        frameStem: "Imagínate que…",
        english: "Just imagine you're at the café and someone says: \"Tell me again.\"",
        spanish: "Imagínate que estás en el café y alguien te dice: \"Cuéntame otra vez.\"",
        situationLabel: "Cuéntame otra vez",
        why: "Camila asking you to start over is the practice — retelling is how stories get *sabor*.",
        wordHints: [
          { en: "you're at the café", es: "estás en el café" },
          { en: "someone tells you", es: "alguien te dice" },
          { en: "tell me again", es: "cuéntame otra vez" },
        ],
      },
    ],
  },
  {
    day: 300,
    themeEs: "Con todo el drama",
    themeEn: "With full drama",
    missionEs: "Cuenta la historia entera sin parar, con los cinco stems.",
    missionEn: "Tell the whole story without stopping, using all five stems.",
    line: "Doña Carmen te trajo sopa al día siguiente.",
    lineEn: "Doña Carmen brought you soup the next day.",
    prompts: [
      {
        id: "d300-no-te-vas",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what I learned telling this story.",
        spanish: "No te vas a creer lo que aprendí contando esta historia.",
        situationLabel: "La lección",
        why: "The hook can be about the telling, not the event — meta-storytelling is still storytelling.",
        wordHints: [
          { en: "what i learned", es: "lo que aprendí" },
          { en: "telling this story", es: "contando esta historia" },
        ],
      },
      {
        id: "d300-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, Doña Carmen brought me homemade soup the next day.",
        spanish: "Para colmo, Doña Carmen me trajo sopa hecha en casa al día siguiente.",
        situationLabel: "Epílogo dulce",
        why: "A good story gets an epilogue — *al día siguiente* tells the listener there's more after the elevator.",
        wordHints: [
          { en: "brought me", es: "me trajo" },
          { en: "homemade soup", es: "sopa hecha en casa" },
          { en: "the next day", es: "al día siguiente" },
        ],
      },
      {
        id: "d300-y-de-repente",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — I say it at the exact right moment now.",
        spanish: "Y de repente, ¡pum!, ya lo digo en el momento exacto.",
        situationLabel: "Timing",
        why: "Timing the *¡pum!* is a skill — *el momento exacto* is what rehearsal buys you.",
        wordHints: [
          { en: "i say it now", es: "ya lo digo" },
          { en: "the exact moment", es: "el momento exacto" },
        ],
      },
      {
        id: "d300-lo-peor",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is I almost didn't tell it because I was embarrassed to exaggerate.",
        spanish: "Y lo peor es que casi no la cuento porque me daba vergüenza exagerar.",
        situationLabel: "Vergüenza de exagerar",
        why: "Primavera wants color — *vergüenza de exagerar* is the fear this week is designed to dissolve.",
        wordHints: [
          { en: "i almost didn't tell it", es: "casi no la cuento" },
          { en: "i was embarrassed", es: "me daba vergüenza" },
          { en: "to exaggerate", es: "exagerar" },
        ],
      },
      {
        id: "d300-imaginate",
        frameStem: "Imagínate que…",
        english: "Picture closing your eyes and being there with us and the pot.",
        spanish: "Imagínate que cierras los ojos y estás ahí con nosotras y la olla.",
        situationLabel: "Invitación final",
        why: "The last *imagínate que* in a story is an invitation — you're handing the scene to the listener.",
        wordHints: [
          { en: "you close your eyes", es: "cierras los ojos" },
          { en: "you're there", es: "estás ahí" },
          { en: "with us and the pot", es: "con nosotras y la olla" },
        ],
      },
    ],
  },
  {
    day: 301,
    themeEs: "Repaso: Historias con sabor",
    themeEn: "Review: Stories with flavor",
    missionEs: "Historia nueva, mismos cinco engranajes. Cuéntala completa.",
    missionEn: "New story, same five gears. Tell the whole thing.",
    line: "Llegaste a las nueve y había un perro en tu cocina.",
    lineEn: "You got home at nine and there was a dog in your kitchen.",
    prompts: [
      {
        id: "d301-no-te-vas-a-creer",
        frameStem: "No te vas a creer lo que…",
        english: "You're not going to believe what I found when I opened the door.",
        spanish: "No te vas a creer lo que encontré cuando abrí la puerta.",
        situationLabel: "Abriendo la puerta",
        why: "The hook withholds the noun. Whatever you found, don't name it in the first sentence.",
        wordHints: [
          { en: "what i found", es: "lo que encontré" },
          { en: "when i opened", es: "cuando abrí" },
          { en: "the door", es: "la puerta" },
        ],
      },
      {
        id: "d301-para-colmo",
        frameStem: "Para colmo…",
        english: "And on top of that, the neighbor wasn't answering her phone.",
        spanish: "Para colmo, la vecina no contestaba el teléfono.",
        situationLabel: "Nadie contesta",
        why: "Imperfect *contestaba* — not that she failed to answer once, but that she kept not answering.",
        wordHints: [
          { en: "on top of that", es: "para colmo" },
          { en: "the neighbor", es: "la vecina" },
          { en: "wasn't answering", es: "no contestaba" },
        ],
      },
      {
        id: "d301-y-de-repente-pum",
        frameStem: "Y de repente, ¡pum!",
        english: "And suddenly, bam — the dog comes out from under the bed.",
        spanish: "Y de repente, ¡pum!, el perro sale de debajo de la cama.",
        situationLabel: "El perro aparece",
        why: "Present tense in the middle of a past story. Spanish does it too, and it's what makes a listener lean in.",
        wordHints: [
          { en: "the dog", es: "el perro" },
          { en: "comes out", es: "sale" },
          { en: "from under the bed", es: "de debajo de la cama" },
        ],
      },
      {
        id: "d301-y-lo-peor-es-que",
        frameStem: "Y lo peor es que…",
        english: "And the worst part is he'd already eaten half the bread.",
        spanish: "Y lo peor es que ya se había comido medio pan.",
        situationLabel: "El pan",
        why: "Pluperfect *se había comido* — it happened before you walked in, which is exactly why it's the worst part.",
        wordHints: [
          { en: "he'd already eaten", es: "ya se había comido" },
          { en: "half the bread", es: "medio pan" },
        ],
      },
      {
        id: "d301-imaginate-que",
        frameStem: "Imagínate que…",
        english: "Just imagine you get home at nine and there's a dog in your kitchen.",
        spanish: "Imagínate que llegas a las nueve y hay un perro en tu cocina.",
        situationLabel: "Ponla a ella en la escena",
        why: "*Imagínate que* + present indicative puts the other person inside the story. It's the last move, not the first.",
        wordHints: [
          { en: "you get home", es: "llegas" },
          { en: "there's a dog", es: "hay un perro" },
          { en: "your kitchen", es: "tu cocina" },
        ],
      },
    ],
  },
];
