import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 1 — "Sonar como yo" (days 274–280).
 *
 * Marlana and Camila continue the Thursday café exchange. Spring is about
 * personality, not technique — describe yourself with flair, not a job title.
 * Six installments, then a fresh recap on the repaso day.
 */
export const priWeek1ReadingDays: ReadingDay[] = [
  {
    day: 274,
    themeEs: "El primer jueves de primavera",
    storyTitle: "Sonar como yo",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el currículum", en: "the résumé", example: "No me presento con un currículum, me presento con una historia." },
      { es: "con chiste incluido", en: "with a joke included", example: "Le cuento a mamá la versión con chiste incluido." },
      { es: "sonar como yo", en: "to sound like myself", example: "Quiero sonar como yo, no solo sonar correcta." },
      { es: "la personalidad", en: "personality", example: "La primavera es de personalidad, no de técnica." },
      { es: "perderse en", en: "to get lost in", example: "Lo mío es contar historias y perderme en los detalles." },
    ],
    dialogue: {
      title: "Sin el cargo primero",
      situation: "En el café, el primer jueves de primavera",
      lines: [
        { speaker: "B", es: "Primavera. ¿Qué cambia hoy?", en: "Spring. What's different today?" },
        { speaker: "A", es: "Soy de las que se presentan con una anécdota, no con un currículum.", en: "I'm the kind of person who introduces herself with an anecdote, not a résumé." },
        { speaker: "B", es: "Bien. Cuéntame la anécdota.", en: "Good. Tell me the anecdote." },
        { speaker: "A", es: "Lo mío es contar historias y perderme en los detalles. Si algo me define es que nunca doy la respuesta corta.", en: "My thing is telling stories and getting lost in the details. If something defines me, it's that I never give the short answer." },
        { speaker: "B", es: "Eso ya lo sé. ¿Y quién eres cuando no eres maestra?", en: "I already know that. And who are you when you're not a teacher?" },
        { speaker: "A", es: "Yo soy más bien de las que escuchan primero y hablan después.", en: "I'm more the type who listens first and talks after." },
        { speaker: "B", es: "¿Y qué dirían de ti las que te conocen?", en: "And what would people who know you say?" },
        { speaker: "A", es: "Me conocen por llegar temprano y quedarme tarde. Pero eso es el trabajo, no yo.", en: "People know me for arriving early and staying late. But that's the job, not me." },
        { speaker: "B", es: "Entonces esta semana buscamos el \"yo\", no el cargo. Trato hecho.", en: "Then this week we look for the \"you,\" not the job title. Deal." },
      ],
    },
  },
  {
    day: 275,
    themeEs: "En el pasillo",
    storyTitle: "Sonar como yo",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "el pasillo", en: "the hallway", example: "Rocío me paró en el pasillo entre clases." },
      { es: "el cargo", en: "the job title", example: "Respondí con la verdad, no con el cargo." },
      { es: "cosas de verdad", en: "real things", example: "Lo mío es que los estudiantes me cuenten cosas de verdad." },
      { es: "sin hacer show", en: "without making a show", example: "Yo soy más bien de las que ayudan sin hacer show." },
      { es: "un marcador extra", en: "an extra marker", example: "Me conocen por tener siempre un marcador extra." },
    ],
    dialogue: {
      title: "Treinta segundos",
      situation: "En el pasillo del colegio, entre clases",
      lines: [
        { speaker: "B", es: "Oye, Marlana. ¿Quién eres tú, de verdad? No el cargo.", en: "Hey, Marlana. Who are you, really? Not the job title." },
        { speaker: "A", es: "Soy de las que en el pasillo responden con la verdad, no con el cargo.", en: "I'm the kind of person who answers in the hallway with the truth, not the job title." },
        { speaker: "B", es: "Ok. ¿Y qué te importa en este colegio?", en: "OK. And what matters to you at this school?" },
        { speaker: "A", es: "Lo mío es que los estudiantes me cuenten cosas de verdad. Si algo me define es que hablo con las madres como con amigas.", en: "My thing is that students tell me real things. If something defines me, it's that I talk to the mothers like they're friends." },
        { speaker: "B", es: "Eso sí suena a ti. ¿Y cómo eres con nosotras?", en: "That does sound like you. And what are you like with us?" },
        { speaker: "A", es: "Yo soy más bien de las que ayudan sin hacer show.", en: "I'm more the type who helps without making a show." },
        { speaker: "B", es: "¿Y qué dirían de ti en la oficina?", en: "And what would people in the office say about you?" },
        { speaker: "A", es: "Me conocen por tener siempre un marcador extra. Y por no comerme el almuerzo hasta las tres.", en: "People know me for always having an extra marker. And for not eating lunch until three." },
        { speaker: "B", es: "Eso es mucho más interesante que \"maestra de inglés.\" Gracias.", en: "That's much more interesting than \"English teacher.\" Thanks." },
      ],
    },
  },
  {
    day: 276,
    themeEs: "La videollamada",
    storyTitle: "Sonar como yo",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "la videollamada", en: "the video call", example: "Tengo videollamada con mamá los domingos." },
      { es: "extrañar", en: "to miss (a place/person)", example: "Extraño Atlanta y no me voy." },
      { es: "filtrar", en: "to filter", example: "Le cuento todo, pero filtro lo que la preocupa." },
      { es: "fotos de más", en: "too many photos", example: "Me conocen por ser la tía que manda fotos de más." },
      { es: "no se van del todo", en: "they never leave completely", example: "Soy de las que se van lejos pero no se van del todo." },
    ],
    dialogue: {
      title: "La versión con alma",
      situation: "Videollamada con mamá en Atlanta, domingo por la noche",
      lines: [
        { speaker: "B", es: "¿Cómo estás, mija? Cuéntame de verdad.", en: "How are you, honey? Tell me for real." },
        { speaker: "A", es: "Soy de las que le cuentan a mamá la versión con chiste incluido.", en: "I'm the kind of person who tells Mom the version with a joke included." },
        { speaker: "B", es: "Bueno, incluye el chiste. ¿Quién eres allá?", en: "All right, include the joke. Who are you over there?" },
        { speaker: "A", es: "Lo mío es seguir siendo la hija que llama los domingos. Si algo me define es que extraño Atlanta y no me voy.", en: "My thing is still being the daughter who calls on Sundays. If something defines me, it's that I miss Atlanta and I'm not leaving." },
        { speaker: "B", es: "Eso suena a mi Marlana. ¿Y cómo eres en Boston?", en: "That sounds like my Marlana. And what are you like in Boston?" },
        { speaker: "A", es: "Yo soy más bien de las que se van lejos pero no se van del todo.", en: "I'm more the type who goes far away but never leaves completely." },
        { speaker: "B", es: "¿Y qué diría la familia de ti?", en: "And what would the family say about you?" },
        { speaker: "A", es: "Me conocen por ser la tía que manda fotos de más. Y por llegar con un plato y quedarme a lavar los trastes.", en: "People know me for being the aunt who sends too many photos. And for showing up with a dish and staying to wash the dishes." },
        { speaker: "B", es: "Eso eres tú. No me cuentes el progreso. Cuéntame eso.", en: "That's you. Don't tell me about progress. Tell me that." },
      ],
    },
  },
  {
    day: 277,
    themeEs: "El código",
    storyTitle: "Sonar como yo",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "programar", en: "to code, to program", example: "Programo de noche después de corregir papeles." },
      { es: "armar herramientas", en: "to build tools", example: "Lo mío es armar herramientas para otros maestros." },
      { es: "un prototipo", en: "a prototype", example: "Tengo una idea el domingo y un prototipo el martes." },
      { es: "leer el error", en: "to read the error", example: "Leo el error en voz alta antes de arreglarlo." },
      { es: "de corazón", en: "from the heart", example: "No soy programadora de título, pero sí de corazón." },
    ],
    dialogue: {
      title: "La otra mitad",
      situation: "Marlana le cuenta a Camila su proyecto de código",
      lines: [
        { speaker: "B", es: "Dijiste que tenías un proyecto. ¿De qué se trata?", en: "You said you had a project. What's it about?" },
        { speaker: "A", es: "Soy de las que programan de noche después de corregir papeles.", en: "I'm the kind of person who codes at night after grading papers." },
        { speaker: "B", es: "¿En serio? ¿Y qué construyes?", en: "Really? And what do you build?" },
        { speaker: "A", es: "Lo mío es armar herramientas que le ahorren tiempo a otros maestros. Si algo me define es que no puedo ver un problema sin querer arreglarlo.", en: "My thing is building tools that save other teachers time. If something defines me, it's that I can't see a problem without wanting to fix it." },
        { speaker: "B", es: "Eso no lo sabía. ¿Y cómo programas?", en: "I didn't know that. And how do you code?" },
        { speaker: "A", es: "Yo soy más bien de las que prueban, fallan y vuelven a probar.", en: "I'm more the type who tries, fails, and tries again." },
        { speaker: "B", es: "¿Y qué dirían de ti en el mundo de la tecnología?", en: "And what would people in the tech world say about you?" },
        { speaker: "A", es: "Me conocen por ser la maestra que también sabe de tecnología. No soy programadora de título, pero sí de corazón.", en: "People know me for being the teacher who also knows about technology. I'm not a programmer by degree, but I am by heart." },
        { speaker: "B", es: "Hay otra Marlana entera que no había conocido. Me gusta.", en: "There's a whole other Marlana I hadn't met. I like her." },
      ],
    },
  },
  {
    day: 278,
    themeEs: "Lo que ve Camila",
    storyTitle: "Sonar como yo",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "devolverle a alguien", en: "to hand back to someone", example: "Camila me devolvió mi propia voz." },
      { es: "relajarse", en: "to relax", example: "La gente se relaja contigo sin saber por qué." },
      { es: "de verdad", en: "for real", example: "Habla español de verdad, no de libro." },
      { es: "sin levantar la voz", en: "without raising one's voice", example: "Convences sin levantar la voz." },
      { es: "el espejo", en: "the mirror", example: "A veces necesitas un espejo que hable." },
    ],
    dialogue: {
      title: "Lo que yo veo",
      situation: "Camila le devuelve a Marlana lo que ve en ella",
      lines: [
        { speaker: "B", es: "Llevas una semana hablando de ti. ¿Quieres saber lo que yo veo?", en: "You've spent a week talking about yourself. Want to know what I see?" },
        { speaker: "A", es: "Sí. Dímelo.", en: "Yes. Tell me." },
        { speaker: "B", es: "Eres de las que no se dan cuenta de lo graciosas que son.", en: "You're the kind who don't realize how funny you are." },
        { speaker: "A", es: "¿Graciosa? En español me siento torpe.", en: "Funny? In Spanish I feel clumsy." },
        { speaker: "B", es: "Lo tuyo es que la gente se relaje contigo sin saber por qué. Si algo te define es que apareces cuando alguien lo necesita.", en: "Your thing is that people relax around you without knowing why. If something defines you, it's that you show up when someone needs you." },
        { speaker: "A", es: "Si algo me define es que aparezco cuando alguien lo necesita. Eso suena raro en mi boca.", en: "If something defines me, it's that I show up when someone needs me. That sounds strange in my mouth." },
        { speaker: "B", es: "Tú eres más bien de las que convencen sin levantar la voz.", en: "You're more the type who convinces without raising her voice." },
        { speaker: "A", es: "Yo soy más bien de las que convencen sin levantar la voz. ¿De verdad?", en: "I'm more the type who convinces without raising her voice. Really?" },
        { speaker: "B", es: "Te conocen por ser la gringa que habla español de verdad. Eso te lo digo yo.", en: "People know you for being the gringa who actually speaks Spanish. That's me saying it, not you." },
      ],
    },
  },
  {
    day: 279,
    themeEs: "Cuando me llevan la contraria",
    storyTitle: "Sonar como yo",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "llevar la contraria", en: "to contradict", example: "Cuando alguien me lleva la contraria, me encojo." },
      { es: "encogerse", en: "to shrink", example: "Todavía me encojo un poco cuando me contradicen." },
      { es: "ceder", en: "to give in", example: "Cedo antes de terminar la frase." },
      { es: "la salida diplomática", en: "the diplomatic way out", example: "Siempre busco la salida diplomática." },
      { es: "quedarse en su opinión", en: "to stand by one's opinion", example: "Quiero aprender a quedarme en mi opinión." },
    ],
    dialogue: {
      title: "Lo que falta",
      situation: "Último jueves de la semana; Camila nombra lo que queda",
      lines: [
        { speaker: "B", es: "Llevamos seis días. ¿Qué falta?", en: "We've been at this six days. What's missing?" },
        { speaker: "A", es: "Soy de las que dicen \"tienes razón\" antes de pensarlo.", en: "I'm the kind of person who says \"you're right\" before thinking about it." },
        { speaker: "B", es: "Exacto. Lo dijiste en invierno y lo repites ahora.", en: "Exactly. You said it in winter and you're saying it again." },
        { speaker: "A", es: "Lo mío es buscar el acuerdo, no la pelea. Si algo me define es que evito la confrontación hasta que explota.", en: "My thing is looking for agreement, not a fight. If something defines me, it's that I avoid confrontation until it blows up." },
        { speaker: "B", es: "¿Y qué haces cuando alguien no está de acuerdo?", en: "And what do you do when someone disagrees?" },
        { speaker: "A", es: "Yo soy más bien de las que ceden antes de terminar la frase.", en: "I'm more the type who gives in before finishing the sentence." },
        { speaker: "B", es: "Eso. Cuando alguien te lleva la contraria, todavía te encoges un poco.", en: "That. When someone contradicts you, you still shrink a little." },
        { speaker: "A", es: "Me conocen por ser la que siempre busca la salida diplomática. Pero eso no es todo lo que soy.", en: "People know me for always looking for the diplomatic way out. But that's not all I am." },
        { speaker: "B", es: "No. La próxima semana viene el humor. Y después, discutir. Pero primero esto: quédate cuando no estén de acuerdo.", en: "No. Next week comes humor. And after that, arguing. But first this: stay when they disagree." },
      ],
    },
  },
  {
    day: 280,
    themeEs: "Repaso: Tu estilo",
    isRecap: true,
    vocab: [
      { es: "el estilo", en: "style", example: "Esta semana fue de estilo, no de gramática." },
      { es: "presumir", en: "to brag", example: "Me describo sin presumir." },
      { es: "detrás del trabajo", en: "behind work", example: "Ya no me escondo detrás del trabajo." },
      { es: "con alma", en: "with soul", example: "Hablo español con alma, no solo con reglas." },
      { es: "el retrato", en: "the portrait", example: "Cinco frases y tienes un retrato." },
    ],
    dialogue: {
      title: "Cinco formas de hablar de ti",
      situation: "Repaso de la semana, con las cinco estructuras sobre la mesa",
      lines: [
        { speaker: "B", es: "Bueno. Repaso. ¿Qué te llevas de esta semana?", en: "All right. Recap. What are you taking from this week?" },
        { speaker: "A", es: "Soy de las que ya no se presentan con el cargo primero.", en: "I'm the kind of person who doesn't lead with the job title anymore." },
        { speaker: "B", es: "¿Y las cinco? Soy de las que, lo mío es, si algo me define…", en: "And the five? Soy de las que, lo mío es, si algo me define…" },
        { speaker: "A", es: "Lo mío es contar quién soy, no qué hago. Si algo me define es que ya no me escondo detrás del trabajo.", en: "My thing is telling who I am, not what I do. If something defines me, it's that I don't hide behind work anymore." },
        { speaker: "B", es: "¿Y las otras dos?", en: "And the other two?" },
        { speaker: "A", es: "Yo soy más bien de las que se describen sin presumir. Me conocen por ser la que habla español con alma.", en: "I'm more the type who describes herself without bragging. People know me for being the one who speaks Spanish with soul." },
        { speaker: "B", es: "Eso es un retrato. No un currículum.", en: "That's a portrait. Not a résumé." },
        { speaker: "A", es: "Todavía me encojo cuando me contradicen. Pero ya sé cómo hablar de mí.", en: "I still shrink when someone contradicts me. But I already know how to talk about myself." },
        { speaker: "B", es: "El humor viene la semana que viene. Hoy te quedas con tu estilo.", en: "Humor comes next week. Today you keep your style." },
      ],
    },
  },
];
