import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 7 — "La misma frase, dos formas" (days 316–322).
 * Parent conference week: Marlana speaks usted with families all day, then
 * retells the same conversations in tú with Camila — the year's third
 * intentional usted week.
 */
export const priWeek7ReadingDays: ReadingDay[] = [
  {
    day: 316,
    themeEs: "Ensayando con Rocío",
    storyTitle: "La misma frase, dos formas",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "ensayar", en: "to rehearse", example: "Rocío me hace ensayar en usted." },
      { es: "la conferencia de padres", en: "the parent conference", example: "Mañana empiezan las conferencias de padres." },
      { es: "de usted", en: "on formal terms (usted)", example: "Con las mamás hablo de usted." },
      { es: "el registro", en: "register (formal/informal)", example: "Cambiar de registro no es cambiar de idioma." },
      { es: "¿tendría?", en: "would you have? (usted conditional)", example: "Disculpe, ¿tendría un momento?" },
    ],
    dialogue: {
      title: "Mañana hablas con mamás",
      situation: "Rocío cierra la puerta del salón después de clase",
      lines: [
        { speaker: "B", es: "Mañana conferencias. ¿Ya ensayaste en usted?", en: "Tomorrow, conferences. Have you rehearsed in usted yet?" },
        { speaker: "A", es: "Un poco. Pero suena a disfraz.", en: "A little. But it sounds like a costume." },
        { speaker: "B", es: "Por eso ensayamos. Repite: Disculpe, ¿tendría un momento antes de que empiece la fila?", en: "That's why we rehearse. Repeat: Excuse me, would you have a moment before the line starts?" },
        { speaker: "A", es: "Disculpe, ¿tendría un momento antes de que empiece la fila.", en: "Excuse me, would you have a moment before the line starts." },
        { speaker: "B", es: "Bien. Ahora: Le quería comentar que… — siempre *le*, no *te*, con una mamá.", en: "Good. Now: I wanted to tell you that… — always *le*, not *te*, with a mother." },
        { speaker: "A", es: "Le quería comentar que su hijo participa más. ¿Me permite explicarle? Muchas gracias por su tiempo.", en: "I wanted to tell you that her son participates more. May I explain to you? Thank you so much for your time." },
        { speaker: "B", es: "¿Ves? *Te* con Camila. *Le* con la señora López. Mismo mensaje.", en: "See? *Te* with Camila. *Le* with Mrs. López. Same message." },
        { speaker: "A", es: "Con permiso… ¿tendría un momento? — eso abre. Oye, perdona — eso es contigo.", en: "Excuse me… would you have a moment? — that opens. Hey, sorry — that's with you." },
        { speaker: "B", es: "Exacto. La misma frase, dos formas. Mañana usas la de usted. El jueves me cuentas en tú.", en: "Exactly. The same phrase, two forms. Tomorrow you use the usted one. Thursday you tell me in tú." },
      ],
    },
  },
  {
    day: 317,
    themeEs: "La primera madre",
    storyTitle: "La misma frase, dos formas",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "sentarse", en: "to sit down", example: "La mesa está por aquí, siéntese." },
      { es: "en voz alta", en: "aloud", example: "Mateo lee en voz alta sin miedo." },
      { es: "la carpeta", en: "the folder", example: "Busco la carpeta de Mateo." },
      { es: "el apellido", en: "the last name", example: "¿Cómo se pronuncia su apellido?" },
      { es: "tercero", en: "third grade", example: "Tiene otro hijo en tercero." },
    ],
    dialogue: {
      title: "La señora López se sienta",
      situation: "Primera conferencia del día; Marlana no cambia al inglés",
      lines: [
        { speaker: "A", es: "Disculpe, ¿tendría un momento? La mesa está por aquí.", en: "Excuse me, would you have a moment? The table is over here." },
        { speaker: "B", es: "Sí, claro. Perdón por llegar tarde.", en: "Yes, of course. Sorry for arriving late." },
        { speaker: "A", es: "No se preocupe. Le quería comentar que Mateo lee en voz alta sin miedo ahora.", en: "Don't worry. I wanted to tell you that Mateo reads aloud without fear now." },
        { speaker: "B", es: "¿De verdad? En casa no quiere leer.", en: "Really? At home he doesn't want to read." },
        { speaker: "A", es: "¿Me permite explicarle cómo leemos aquí? No es como en su país.", en: "May I explain to you how we read here? It's not like in your country." },
        { speaker: "B", es: "Por favor. A veces no entiendo la tarea.", en: "Please. Sometimes I don't understand the homework." },
        { speaker: "A", es: "Le explico. Y si quiere, le mando un resumen por correo.", en: "I'll explain. And if you'd like, I'll send you a summary by email." },
        { speaker: "B", es: "Muchas gracias. Usted habla despacio y eso ayuda.", en: "Thank you very much. You speak slowly and that helps." },
        { speaker: "A", es: "Muchas gracias por su tiempo — sé que tiene otro hijo en tercero. Disculpe, ¿cómo se pronuncia su apellido? Quiero escribirlo bien.", en: "Thank you so much for your time — I know you have another child in third grade. Excuse me, how do you pronounce your last name? I want to write it correctly." },
      ],
    },
  },
  {
    day: 318,
    themeEs: "Un momento difícil",
    storyTitle: "La misma frase, dos formas",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "reprueba", en: "failing (a class)", example: "Pregunta por qué su hijo reprueba." },
      { es: "vago", en: "lazy", example: "Su hijo no es vago — le cuesta leer." },
      { es: "le cuesta", en: "it's hard for him/her", example: "Le cuesta la lectura en inglés." },
      { es: "calcular la nota", en: "to calculate the grade", example: "¿Me permite explicarle cómo calculamos la nota?" },
      { es: "de otra forma", en: "another way", example: "Disculpe, déjeme decirlo de otra forma." },
    ],
    dialogue: {
      title: "¿Por qué reprueba?",
      situation: "Tercera conferencia; la mamá de Daniela llega con una carpeta de papeles",
      lines: [
        { speaker: "B", es: "Disculpe — ¿por qué mi hija reprueba? Ella estudia todas las noches.", en: "Excuse me — why is my daughter failing? She studies every night." },
        { speaker: "A", es: "Disculpe, ¿tendría un momento más? Preferiría que nos sentáramos.", en: "Excuse me, would you have a moment more? I'd prefer we sit down." },
        { speaker: "A", es: "Le quería comentar que su hija no es vaga — le cuesta la lectura en inglés.", en: "I wanted to tell you that your daughter isn't lazy — English reading is hard for her." },
        { speaker: "B", es: "Entonces ¿por qué la nota es tan baja?", en: "Then why is the grade so low?" },
        { speaker: "A", es: "¿Me permite explicarle cómo calculamos la nota? No es que no quiera aprender.", en: "May I explain to you how we calculate the grade? It's not that she doesn't want to learn." },
        { speaker: "B", es: "Sí. Por favor.", en: "Yes. Please." },
        { speaker: "A", es: "Disculpe, déjeme decirlo de otra forma. Ella entiende cuando le leo en voz alta. Sola, se traba.", en: "Excuse me, let me say it another way. She understands when I read aloud to her. Alone, she gets stuck." },
        { speaker: "B", es: "Nadie me había explicado eso.", en: "Nobody had explained that to me." },
        { speaker: "A", es: "Muchas gracias por su tiempo — entiendo que esto no es fácil. La llamo la semana que viene.", en: "Thank you so much for your time — I understand this isn't easy. I'll call you next week." },
      ],
    },
  },
  {
    day: 319,
    themeEs: "La misma frase, en tú",
    storyTitle: "La misma frase, dos formas",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "desahogarse", en: "to vent, to unburden oneself", example: "Necesitaba desahogarme contigo." },
      { es: "contigo", en: "with you (informal)", example: "Contigo digo *te quería comentar*." },
      { es: "el mesero", en: "the waiter", example: "Casi le digo *con permiso* al mesero." },
      { es: "de verdad", en: "really, truly", example: "¿En serio casi lloraste?" },
      { es: "media hora", en: "half an hour", example: "Me escuchaste media hora." },
    ],
    dialogue: {
      title: "Oye, ¿tienes un momento?",
      situation: "Jueves en el café; Marlana acaba de terminar el segundo día de conferencias",
      lines: [
        { speaker: "A", es: "Oye, ¿tienes un momento? Necesito contarte la conferencia.", en: "Hey, do you have a moment? I need to tell you about the conference." },
        { speaker: "B", es: "Siempre. ¿Qué pasó?", en: "Always. What happened?" },
        { speaker: "A", es: "Te quería comentar que casi lloro con la tercera madre. Con ella dije *le quería comentar* — contigo digo *te quería comentar*.", en: "I wanted to tell you that I almost cried with the third mother. With her I said *le quería comentar* — with you I say *te quería comentar*." },
        { speaker: "B", es: "¿Y funcionó el usted?", en: "And did the usted work?" },
        { speaker: "A", es: "¿Me dejas explicarte lo que le dije sobre las notas? Con la mamá: *¿me permite explicarle?* Contigo: *¿me dejas explicarte?*", en: "Can I explain to you what I told her about the grades? With the mother: *may I explain to you?* With you: *can I explain to you?*" },
        { speaker: "B", es: "Misma frase. Dos formas.", en: "Same phrase. Two forms." },
        { speaker: "A", es: "Exacto. A las mamás: *muchas gracias por su tiempo.* A ti: *por tu tiempo.*", en: "Exactly. To the mothers: *thank you so much for your time.* To you: *for your time.*" },
        { speaker: "B", es: "Muchas gracias por tu tiempo — me escuchaste media hora.", en: "Thank you so much for your time — you listened for half an hour." },
        { speaker: "A", es: "Oye, perdona — casi le digo *con permiso* al mesero. Llevo usted en la cabeza.", en: "Hey, sorry — I almost said *excuse me* to the waiter. I've got usted stuck in my head." },
      ],
    },
  },
  {
    day: 320,
    themeEs: "Cambiando en seco",
    storyTitle: "La misma frase, dos formas",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "en seco", en: "on a dime, instantly", example: "Cambié de registro en seco." },
      { es: "la directora", en: "the principal", example: "Casi le digo *oye* a la directora." },
      { es: "el pasillo", en: "the hallway", example: "Mismo pasillo, otro registro." },
      { es: "ocho veces", en: "eight times", example: "Dije *su tiempo* ocho veces hoy." },
      { es: "practicar", en: "to practice", example: "¿Practicamos otra vez la de *¿me permite?*" },
    ],
    dialogue: {
      title: "Sale la mamá, entra Camila",
      situation: "Viernes al mediodía; Marlana en el pasillo entre conferencias",
      lines: [
        { speaker: "A", es: "Muchas gracias por su tiempo, señora. Que tenga buen día.", en: "Thank you so much for your time, ma'am. Have a good day." },
        { speaker: "A", es: "Disculpe, ¿tendría un momento? — ah, Camila, ¿tienes un momento?", en: "Excuse me, would you have a moment? — oh, Camila, do you have a moment?" },
        { speaker: "B", es: "¿Acabas de cambiar en seco?", en: "Did you just switch on a dime?" },
        { speaker: "A", es: "Te quería comentar que la misma frase suena distinta en usted. Le dije *le quería* a la mamá y a ti *te quería* en la misma hora.", en: "I wanted to tell you the same phrase sounds different in usted. I said *le quería* to the mother and *te quería* to you in the same hour." },
        { speaker: "B", es: "¿Y la difícil?", en: "And the hard one?" },
        { speaker: "A", es: "¿Me dejas explicarte lo de la nota de Mateo? Con ella: *¿me permite explicarle?* Contigo: *¿me dejas explicarte?*", en: "Can I explain to you what happened with Mateo's grade? With her: *may I explain to you?* With you: *can I explain to you?*" },
        { speaker: "A", es: "Dije *su tiempo* ocho veces hoy. *Tu tiempo* una, contigo.", en: "I said *your time* (formal) eight times today. *Your time* (informal) once, with you." },
        { speaker: "B", es: "Oye, perdona — ¿casi le dijiste *oye* a la directora?", en: "Hey, sorry — did you almost say *hey* to the principal?" },
        { speaker: "A", es: "Casi. Con permiso en la puerta; oye, perdona en el café. ¿Practicamos otra vez?", en: "Almost. *Excuse me* at the door; *hey, sorry* at the café. Shall we practice again?" },
      ],
    },
  },
  {
    day: 321,
    themeEs: "La conferencia entera",
    storyTitle: "La misma frase, dos formas",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "once veces", en: "eleven times", example: "La abrió once veces hoy." },
      { es: "ni una vez", en: "not once", example: "No cambié al inglés ni una vez." },
      { es: "equivocarse de", en: "to get the wrong (thing)", example: "Me equivoqué de carpeta." },
      { es: "seguir", en: "to continue, to keep going", example: "Me corregí y seguí." },
      { es: "ensayar", en: "to rehearse", example: "Me ayudaste a ensayar." },
    ],
    dialogue: {
      title: "Seis horas, once familias",
      situation: "Viernes a las cuatro; Marlana cuenta el día a Camila",
      lines: [
        { speaker: "A", es: "Disculpe, ¿tendría un momento? — la abrió once veces hoy. Funcionó con todas.", en: "Excuse me, would you have a moment? — she opened with it eleven times today. It worked with all of them." },
        { speaker: "B", es: "¿Y el inglés?", en: "And English?" },
        { speaker: "A", es: "Te quería comentar que hoy no cambié al inglés ni una vez. *Le quería comentar que…* — así empecé las once conferencias.", en: "I wanted to tell you that today I didn't switch to English once. *I wanted to tell you that…* — that's how I started all eleven conferences." },
        { speaker: "B", es: "¿Hubo momentos difíciles?", en: "Were there hard moments?" },
        { speaker: "A", es: "¿Me permite explicarle? — la usé cuando no sabía qué decir. ¿Me dejas explicarte por qué esa frase me salvó?", en: "May I explain to you? — I used it when I didn't know what to say next. Can I explain to you why that phrase saved me?" },
        { speaker: "B", es: "Cuéntame.", en: "Tell me." },
        { speaker: "A", es: "Compra tiempo. Te organizas. Y la mamá respira.", en: "It buys time. You get organized. And the mother breathes." },
        { speaker: "A", es: "Disculpe, me equivoqué de carpeta — me corregí y seguí. Muchas gracias por tu tiempo, Camila. Me ayudaste a ensayar.", en: "Excuse me, I grabbed the wrong folder — I corrected myself and kept going. Thank you so much for your time, Camila. You helped me rehearse." },
        { speaker: "B", es: "La misma frase, dos formas. Y las dos son tuyas.", en: "The same phrase, two forms. And both are yours now." },
      ],
    },
  },
  {
    day: 322,
    themeEs: "Repaso: Cambiar de registro",
    isRecap: true,
    vocab: [
      { es: "cambiar de registro", en: "to switch register", example: "Aprendí a cambiar de registro sin pensar." },
      { es: "la misma frase", en: "the same phrase", example: "La misma frase, dos formas." },
      { es: "contigo / con una mamá", en: "with you / with a mother", example: "Contigo digo tú; con una mamá, usted." },
      { es: "sin pensar", en: "without thinking", example: "Ya cambio sin pensar." },
      { es: "el disfraz", en: "the costume", example: "El usted ya no suena a disfraz." },
    ],
    dialogue: {
      title: "Los cinco stems, dos registros",
      situation: "Repaso de la semana — Camila pide los cinco stems en orden",
      lines: [
        { speaker: "B", es: "Repaso. Semana siete. ¿Qué aprendiste?", en: "Recap. Week seven. What did you learn?" },
        { speaker: "A", es: "Que la misma frase tiene dos formas. Oye, ¿tienes un momento? — contigo. Disculpe, ¿tendría? — con una mamá.", en: "That the same phrase has two forms. Hey, do you have a moment? — with you. Excuse me, would you? — with a mother." },
        { speaker: "B", es: "Dos.", en: "Two." },
        { speaker: "A", es: "Te quería comentar que… / Le quería comentar que… — *te* o *le*, el resto igual.", en: "I wanted to tell you that… / I wanted to tell you that… — *te* or *le*, the rest the same." },
        { speaker: "B", es: "Tres.", en: "Three." },
        { speaker: "A", es: "¿Me dejas explicarte? Contigo. ¿Me permite explicarle? Con una familia.", en: "Can I explain to you? With you. May I explain to you? With a family." },
        { speaker: "B", es: "Cuatro y cinco.", en: "Four and five." },
        { speaker: "A", es: "Muchas gracias por tu tiempo — Camila. Muchas gracias por su tiempo — señora. Oye, perdona — contigo. Con permiso — con un padre en el pasillo.", en: "Thank you so much for your time — Camila. Thank you so much for your time — ma'am. Hey, sorry — with you. Excuse me — with a father in the hallway." },
        { speaker: "B", es: "Tercer usted del año. Verano día veinticinco, invierno ciento noventa y ocho, ahora. ¿Suena a disfraz?", en: "Third usted of the year. Summer day twenty-five, winter one ninety-eight, now. Does it sound like a costume?" },
        { speaker: "A", es: "Ya no. Suena a mí, cuando toca.", en: "Not anymore. It sounds like me, when it's time." },
      ],
    },
  },
];
