import type { SpeakDay } from "../../prompts/types";

/**
 * Primavera Week 6 — "Debate suave II" (days 309–315).
 * Each `spanish` is copied verbatim from content/drafts/primavera/week6-frames.ts
 * for the matching `frameStem` (convention 2).
 */
export const priWeek6SpeakDays: SpeakDay[] = [
  {
    day: 309,
    themeEs: "Puede que tengas razón en el invierno",
    themeEn: "You might be right about winter",
    missionEs: "Defiende la primavera sin sonar a un no rotundo.",
    missionEn: "Defend spring without sounding like a flat no.",
    line: "La tía quiere febrero. Tú sobreviviste uno. Ella no.",
    lineEn: "Your aunt wants February. You survived one. She didn't.",
    prompts: [
      {
        id: "d309-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that February is cheaper.",
        spanish: "Puede que tengas razón en que febrero sale más barato.",
        situationLabel: "Primera concesión",
        why: "*Puede que tengas razón en…* opens the door without walking through it — you grant one thing, not the whole argument.",
        wordHints: [
          { en: "you might be right", es: "puede que tengas razón" },
          { en: "february", es: "febrero" },
          { en: "is cheaper", es: "sale más barato" },
        ],
      },
      {
        id: "d309-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, February here isn't what you imagine.",
        spanish: "Aun así, febrero aquí no es lo que imaginas.",
        situationLabel: "Volviendo a tu punto",
        why: "*Aun así* is where you stand back up — the concession was real, the boundary is too.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "isn't what you imagine", es: "no es lo que imaginas" },
          { en: "here", es: "aquí" },
        ],
      },
      {
        id: "d309-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought about your vacation being only in January.",
        spanish: "No había pensado en que tus vacaciones son solo en enero.",
        situationLabel: "Algo nuevo",
        why: "Real surprise buys you a beat — you're not pretending to agree, you're actually listening.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "your vacation", es: "tus vacaciones" },
          { en: "only in january", es: "solo en enero" },
        ],
      },
      {
        id: "d309-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point — you want to see real snow.",
        spanish: "Tienes un punto: quieres ver la nieve de verdad.",
        situationLabel: "Reconocer algo",
        why: "*Tienes un punto* is warm and short — concession without sounding defeated.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "you want to see", es: "quieres ver" },
          { en: "real snow", es: "la nieve de verdad" },
        ],
      },
      {
        id: "d309-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point about February.",
        spanish: "Me convenzo hasta cierto punto con lo de febrero.",
        situationLabel: "Medio acuerdo",
        why: "*Hasta cierto punto* keeps you in the conversation — partial yes, not full surrender.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "about february", es: "con lo de febrero" },
        ],
      },
    ],
  },
  {
    day: 310,
    themeEs: "Aun así no es mi temporada",
    themeEn: "Even so, it's not my season",
    missionEs: "Mira las fotos de nieve y sigue defendiendo la primavera.",
    missionEn: "Look at the snow photos and still defend spring.",
    line: "Bonito en Instagram. Tú recuerdas las tuberías.",
    lineEn: "Pretty on Instagram. You remember the pipes.",
    prompts: [
      {
        id: "d310-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that it looks beautiful in the photos.",
        spanish: "Puede que tengas razón en que se ve precioso en las fotos.",
        situationLabel: "Las fotos que mandó",
        why: "Granting the photos are pretty costs you nothing — and makes *aun así* land harder.",
        wordHints: [
          { en: "you might be right", es: "puede que tengas razón" },
          { en: "looks beautiful", es: "se ve precioso" },
          { en: "in the photos", es: "en las fotos" },
        ],
      },
      {
        id: "d310-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, February here is work, snow, and more snow.",
        spanish: "Aun así, febrero aquí es trabajo, nieve y más nieve.",
        situationLabel: "La realidad",
        why: "*Aun así* after a concession is the whole week — you heard her, you're not surrendering.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "work", es: "trabajo" },
          { en: "snow and more snow", es: "nieve y más nieve" },
        ],
      },
      {
        id: "d310-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought about you never having seen a snowstorm.",
        spanish: "No había pensado en que tú nunca has visto una tormenta de nieve.",
        situationLabel: "Su perspectiva",
        why: "She's never seen what you lived through last winter — that's a real reason to want February.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "you've never seen", es: "tú nunca has visto" },
          { en: "a snowstorm", es: "una tormenta de nieve" },
        ],
      },
      {
        id: "d310-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point with the photos — they make you want to go.",
        spanish: "Tienes un punto con las fotos — dan ganas de ir.",
        situationLabel: "Admitiendo el efecto",
        why: "*Dan ganas de ir* — the photos work. Saying so doesn't mean you're booking.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "the photos", es: "las fotos" },
          { en: "make you want to go", es: "dan ganas de ir" },
        ],
      },
      {
        id: "d310-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point about a long weekend.",
        spanish: "Me convenzo hasta cierto punto con un fin de semana largo.",
        situationLabel: "Una opción más chica",
        why: "Shrinking the visit is how compromise starts — not yes to everything, yes to something.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "a long weekend", es: "un fin de semana largo" },
        ],
      },
    ],
  },
  {
    day: 311,
    themeEs: "No había pensado en eso",
    themeEn: "I hadn't thought of that",
    missionEs: "Reacciona al vuelo guardado y a que mamá está de su lado.",
    missionEn: "React to the saved flight and mom taking her side.",
    line: "Dos contra una — y todavía tienes que hablar en español.",
    lineEn: "Two against one — and you still have to speak in Spanish.",
    prompts: [
      {
        id: "d311-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that mom misses seeing you soon.",
        spanish: "Puede que tengas razón en que mamá extraña verte pronto.",
        situationLabel: "Mamá entra en la conversación",
        why: "Mamá's feelings are real data — conceding them doesn't mean conceding the date.",
        wordHints: [
          { en: "mom misses", es: "mamá extraña" },
          { en: "seeing you soon", es: "verte pronto" },
          { en: "you might be right", es: "puede que tengas razón" },
        ],
      },
      {
        id: "d311-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, I want to be able to host you well, not between storms.",
        spanish: "Aun así, quiero poder recibirte bien, no entre tormentas.",
        situationLabel: "Tu condición",
        why: "*Recibirte bien* is the goal — hosting in winter last year was survival mode, not hospitality.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "host you well", es: "recibirte bien" },
          { en: "between storms", es: "entre tormentas" },
        ],
      },
      {
        id: "d311-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought you already had a flight saved.",
        spanish: "No había pensado en que ya tienes un vuelo guardado.",
        situationLabel: "El vuelo marcado",
        why: "*No había pensado en eso* buys you a beat — real surprise, not fake surrender.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "you already have", es: "ya tienes" },
          { en: "a flight saved", es: "un vuelo guardado" },
        ],
      },
      {
        id: "d311-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point about the flight — prices go up.",
        spanish: "Tienes un punto con lo del vuelo — los precios suben.",
        situationLabel: "Lo económico",
        why: "The flight argument is practical, not emotional — *tienes un punto* fits practical concessions.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "about the flight", es: "con lo del vuelo" },
          { en: "prices go up", es: "los precios suben" },
        ],
      },
      {
        id: "d311-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point to look at dates with you.",
        spanish: "Me convenzo hasta cierto punto de revisar fechas contigo.",
        situationLabel: "Abriendo la puerta",
        why: "Looking at dates together isn't saying yes — it's the next step in a negotiation.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "look at dates with you", es: "revisar fechas contigo" },
        ],
      },
    ],
  },
  {
    day: 312,
    themeEs: "Tienes un punto, tía",
    themeEn: "You have a point, aunt",
    missionEs: "En la videollamada con mamá y la tía, cede sin rendirte.",
    missionEn: "On the video call with mom and your aunt, concede without surrendering.",
    line: "Tres personas, dos pantallas, una fecha por negociar.",
    lineEn: "Three people, two screens, one date to negotiate.",
    prompts: [
      {
        id: "d312-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that I'm being stubborn.",
        spanish: "Puede que tengas razón en que estoy siendo terca.",
        situationLabel: "Autocrítica suave",
        why: "Admitting stubbornness disarms the room — and gives you room to explain why.",
        wordHints: [
          { en: "you might be right", es: "puede que tengas razón" },
          { en: "i'm being", es: "estoy siendo" },
          { en: "stubborn", es: "terca" },
        ],
      },
      {
        id: "d312-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, February leaves me exhausted after school.",
        spanish: "Aun así, febrero me deja agotada después del colegio.",
        situationLabel: "Tu energía",
        why: "The boundary is practical — you can't host well when you're running on empty.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "leaves me exhausted", es: "me deja agotada" },
          { en: "after school", es: "después del colegio" },
        ],
      },
      {
        id: "d312-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought about mom wanting to cook with you in winter.",
        spanish: "No había pensado en que mamá quiere cocinar contigo en invierno.",
        situationLabel: "El argumento de mamá",
        why: "Mamá's reason is emotional — soup, warmth, family. Worth naming even if it doesn't decide the date.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "mom wants to cook", es: "mamá quiere cocinar" },
          { en: "with you in winter", es: "contigo en invierno" },
        ],
      },
      {
        id: "d312-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point, aunt — mom is right about the soup.",
        spanish: "Tienes un punto, tía — mamá tiene razón con lo de la sopa.",
        situationLabel: "Ceder con cariño",
        why: "*Tienes un punto* is shorter than *puede que tengas razón* — same job, less ceremony.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "aunt", es: "tía" },
          { en: "about the soup", es: "con lo de la sopa" },
        ],
      },
      {
        id: "d312-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point about late March.",
        spanish: "Me convenzo hasta cierto punto con finales de marzo.",
        situationLabel: "La propuesta",
        why: "*Finales de marzo* is the compromise — snow maybe, walks definitely, school manageable.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "late march", es: "finales de marzo" },
        ],
      },
    ],
  },
  {
    day: 313,
    themeEs: "Me convenzo hasta cierto punto",
    themeEn: "You convince me up to a point",
    missionEs: "Cierra el trato: última semana de marzo, condiciones incluidas.",
    missionEn: "Close the deal: last week of March, conditions included.",
    line: "Nadie gana todo. Nadie pierde todo.",
    lineEn: "Nobody wins everything. Nobody loses everything.",
    prompts: [
      {
        id: "d313-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that there's still snow in late March.",
        spanish: "Puede que tengas razón en que a finales de marzo aún hay nieve.",
        situationLabel: "El compromiso",
        why: "Late March might still give her snow — you can concede that without giving February.",
        wordHints: [
          { en: "you might be right", es: "puede que tengas razón" },
          { en: "late march", es: "finales de marzo" },
          { en: "there's still snow", es: "aún hay nieve" },
        ],
      },
      {
        id: "d313-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, I need you to confirm before you buy.",
        spanish: "Aun así, necesito que confirmes antes de comprar.",
        situationLabel: "Tu condición final",
        why: "The deal isn't done until you say so — *aun así* keeps one foot on the brake.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "i need you to confirm", es: "necesito que confirmes" },
          { en: "before you buy", es: "antes de comprar" },
        ],
      },
      {
        id: "d313-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought March also has cheap flights.",
        spanish: "No había pensado en que marzo también tiene vuelos baratos.",
        situationLabel: "Datos nuevos",
        why: "She found March flights — your surprise is honest, and it moves the conversation forward.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "march also has", es: "marzo también tiene" },
          { en: "cheap flights", es: "vuelos baratos" },
        ],
      },
      {
        id: "d313-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point — late March sounds good.",
        spanish: "Tienes un punto — finales de marzo suena bien.",
        situationLabel: "Casi cerrado",
        why: "*Suena bien* is agreement with room — not *está decidido*, just *suena bien*.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "late march", es: "finales de marzo" },
          { en: "sounds good", es: "suena bien" },
        ],
      },
      {
        id: "d313-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point — we're set for the last week of March.",
        spanish: "Me convenzo hasta cierto punto — quedamos en la última semana de marzo.",
        situationLabel: "El trato",
        why: "*Hasta cierto punto* is the honest ending — nobody wins everything, nobody loses everything.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "last week of march", es: "última semana de marzo" },
        ],
      },
    ],
  },
  {
    day: 314,
    themeEs: "Sin colapsar",
    themeEn: "Without collapsing",
    missionEs: "Cuéntale a Camila cómo fue la negociación — sin decir que cediste.",
    missionEn: "Tell Camila how the negotiation went — without saying you gave in.",
    line: "No dijiste que sí a febrero. Negociaste.",
    lineEn: "You didn't say yes to February. You negotiated.",
    prompts: [
      {
        id: "d314-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that I sound too formal with my aunt.",
        spanish: "Puede que tengas razón en que sueno muy formal con mi tía.",
        situationLabel: "Camila opina",
        why: "Camila's teasing is fair — debate stems can sound stiff until you've used them a few times.",
        wordHints: [
          { en: "you might be right", es: "puede que tengas razón" },
          { en: "i sound too formal", es: "sueno muy formal" },
          { en: "with my aunt", es: "con mi tía" },
        ],
      },
      {
        id: "d314-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, I didn't say yes to February.",
        spanish: "Aun así, no dije que sí a febrero.",
        situationLabel: "Lo que no cediste",
        why: "The win isn't total — but *no dije que sí a febrero* is the line you held.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "i didn't say yes", es: "no dije que sí" },
          { en: "to february", es: "a febrero" },
        ],
      },
      {
        id: "d314-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought arguing in Spanish tired me out less than giving in in English.",
        spanish: "No había pensado en que discutir en español me cansaba menos que ceder en inglés.",
        situationLabel: "La lección",
        why: "Having the stems ready means you don't switch to English to escape the disagreement.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "arguing in spanish", es: "discutir en español" },
          { en: "giving in in english", es: "ceder en inglés" },
        ],
      },
      {
        id: "d314-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point — it sounds different from last week.",
        spanish: "Tienes un punto — suena distinto a la semana pasada.",
        situationLabel: "Debate suave I → II",
        why: "Week 5 opened with *pero*; week 6 closes with partial yes — Camila hears the difference.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "sounds different", es: "suena distinto" },
          { en: "from last week", es: "a la semana pasada" },
        ],
      },
      {
        id: "d314-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point to record the next video call.",
        spanish: "Me convenzo hasta cierto punto de grabar la próxima videollamada.",
        situationLabel: "Practicar otra vez",
        why: "Recording the call is practice — another partial yes, same pattern as with your aunt.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "record the next video call", es: "grabar la próxima videollamada" },
        ],
      },
    ],
  },
  {
    day: 315,
    themeEs: "Repaso: Debate suave II",
    themeEn: "Review: Gentle debate II",
    missionEs: "Repasa los cinco stems sin colapsar ni pelear.",
    missionEn: "Review the five stems without collapsing or fighting.",
    line: "Conceder no es perder. Es negociar con cariño.",
    lineEn: "Conceding isn't losing. It's negotiating with warmth.",
    prompts: [
      {
        id: "d315-puede-que",
        frameStem: "Puede que tengas razón en…",
        english: "You might be right that this sounds more natural than week five.",
        spanish: "Puede que tengas razón en que esto suena más natural que la semana cinco.",
        situationLabel: "Repaso",
        why: "Week 5 opened the debate; week 6 teaches you to stay standing after you concede.",
        wordHints: [
          { en: "you might be right", es: "puede que tengas razón" },
          { en: "sounds more natural", es: "suena más natural" },
          { en: "than week five", es: "que la semana cinco" },
        ],
      },
      {
        id: "d315-aun-asi",
        frameStem: "Aun así…",
        english: "Even so, it's not the same as \"I understand your point, but…\"",
        spanish: "Aun así, no es lo mismo que \"entiendo tu punto, pero…\"",
        situationLabel: "Semana cinco vs seis",
        why: "Week 5 opens with *pero*; week 6 closes with partial yes — you need both.",
        wordHints: [
          { en: "even so", es: "aun así" },
          { en: "it's not the same as", es: "no es lo mismo que" },
          { en: "i understand your point, but", es: "entiendo tu punto, pero" },
        ],
      },
      {
        id: "d315-no-habia",
        frameStem: "No había pensado en eso",
        english: "I hadn't thought how useful it is when the other person has data.",
        spanish: "No había pensado en lo útil que es cuando la otra persona tiene datos.",
        situationLabel: "Escuchar de verdad",
        why: "The flight prices, mamá's schedule — new information isn't defeat, it's material.",
        wordHints: [
          { en: "i hadn't thought", es: "no había pensado" },
          { en: "how useful it is", es: "lo útil que es" },
          { en: "the other person has data", es: "la otra persona tiene datos" },
        ],
      },
      {
        id: "d315-tienes",
        frameStem: "Tienes un punto",
        english: "You have a point — it's the short version of conceding.",
        spanish: "Tienes un punto — es la versión corta de ceder.",
        situationLabel: "Los cinco en orden",
        why: "*Tienes un punto* is warm and fast — use it when you don't need the full *puede que*.",
        wordHints: [
          { en: "you have a point", es: "tienes un punto" },
          { en: "the short version", es: "la versión corta" },
          { en: "of conceding", es: "de ceder" },
        ],
      },
      {
        id: "d315-me-convenzo",
        frameStem: "Me convenzo hasta cierto punto",
        english: "You convince me up to a point — and that's where the deal closes.",
        spanish: "Me convenzo hasta cierto punto — y ahí se cierra el trato.",
        situationLabel: "La meta de la semana",
        why: "*Hasta cierto punto* is how La tía en Atlanta ended — and how most real arguments should.",
        wordHints: [
          { en: "you convince me", es: "me convenzo" },
          { en: "up to a point", es: "hasta cierto punto" },
          { en: "the deal closes", es: "se cierra el trato" },
        ],
      },
    ],
  },
];
