import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 11 — "Cuarenta minutos seguidos" (days 344–350).
 * Marlana and Camila's first intentional long Thursday session — bridges
 * and callbacks that hold forty minutes together without a script.
 */
export const priWeek11ReadingDays: ReadingDay[] = [
  {
    day: 344,
    themeEs: "Cuarenta minutos",
    storyTitle: "Cuarenta minutos seguidos",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "el temporizador", en: "the timer", example: "Camila pone el temporizador en cuarenta minutos." },
      { es: "seguidos", en: "in a row, straight", example: "Cuarenta minutos seguidos, sin parar." },
      { es: "el puente", en: "the bridge (fig.)", example: "Los puentes sostienen una charla larga." },
      { es: "el callback", en: "the callback", example: "Volviendo a lo que dijiste es un callback." },
      { es: "el hilo", en: "the thread", example: "Donde íbamos retoma el hilo." },
    ],
    dialogue: {
      title: "El reto del jueves",
      situation: "Camila llega al café con un plan — cuarenta minutos seguidos",
      lines: [
        { speaker: "B", es: "Hoy no es un café normal. Hoy son cuarenta minutos seguidos. Sin teléfono. Sin inglés.", en: "Today isn't a normal coffee. Today is forty straight minutes. No phone. No English." },
        { speaker: "A", es: "¿Cuarenta? La semana pasada aguantamos veinticinco y ya me sentí orgullosa.", en: "Forty? Last week we held twenty-five and I already felt proud." },
        { speaker: "B", es: "Veinticinco fue profundizar. Cuarenta es arquitectura: puentes, callbacks, volver al hilo.", en: "Twenty-five was going deeper. Forty is architecture: bridges, callbacks, getting back to the thread." },
        { speaker: "A", es: "Suena a clase.", en: "Sounds like class." },
        { speaker: "B", es: "Suena a conversación de verdad. Te doy cinco stems y un temporizador.", en: "Sounds like a real conversation. I'll give you five stems and a timer." },
        { speaker: "A", es: "Volviendo a lo que dijiste del hospital, ¿sigue igual de caótico?", en: "Going back to what you said about the hospital — is it still as chaotic?" },
        { speaker: "B", es: "Bien. Ese es el primero. Callback. ¿Y si me interrumpo?", en: "Good. That's the first one. Callback. And if I interrupt?" },
        { speaker: "A", es: "Como te contaba, retomas. Eso me recuerda lo de la mamá de Diego. Antes de que se me olvide, Rocío te manda saludos.", en: "As I was telling you, you resume. That reminds me Diego's mom. Before I forget, Rocío says hi." },
        { speaker: "B", es: "Donde íbamos, yo explicaba los cinco stems. Empezamos. Temporizador en marcha.", en: "Where we were, I was explaining the five stems. Let's start. Timer running." },
      ],
    },
  },
  {
    day: 345,
    themeEs: "Volviendo a lo que dijiste",
    storyTitle: "Cuarenta minutos seguidos",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "cansado/a", en: "tired", example: "Las enfermeras cansadas, las maestras cansadas." },
      { es: "hace un rato", en: "a little while ago", example: "Dijiste eso hace un rato." },
      { es: "cerrar el círculo", en: "to close the loop", example: "Volviendo a lo que dijiste cierra el círculo." },
      { es: "demostrar", en: "to prove, to show", example: "Responder tarde demuestra que escuchaste." },
      { es: "el turno de noche", en: "the night shift", example: "Llegas tarde por el turno de noche." },
    ],
    dialogue: {
      title: "Minuto ocho, minuto veintitrés",
      situation: "Camila habla de enfermeras; Marlana responde quince minutos después",
      lines: [
        { speaker: "B", es: "En el hospital hay turnos donde las enfermeras no paran. Hablan rápido, comen mal, se olvidan de beber agua.", en: "At the hospital there are shifts where the nurses don't stop. They talk fast, eat badly, forget to drink water." },
        { speaker: "A", es: "Como te contaba, ayer una maestra me pidió ayuda y no supe decir que no.", en: "As I was telling you, yesterday a teacher asked me for help and I didn't know how to say no." },
        { speaker: "B", es: "¿Eso es callback o tangente?", en: "Is that a callback or a tangent?" },
        { speaker: "A", es: "Todavía no sé. Sigo…", en: "I don't know yet. I'm still…" },
        { speaker: "B", es: "Sigue. Estamos en el minuto doce.", en: "Keep going. We're at minute twelve." },
        { speaker: "A", es: "Eso me recuerda lo que dijiste de traducir cuando estás cansada. En la escuela pasa igual.", en: "That reminds me what you said about translating when you're tired. The same thing happens at school." },
        { speaker: "B", es: "Bien. Tangente que conecta. ¿Y lo de las enfermeras?", en: "Good. Tangent that connects. And the nurses?" },
        { speaker: "A", es: "Volviendo a lo que dijiste de las enfermeras cansadas, eso pasa en la escuela también. Perdón por tardar.", en: "Going back to what you said about tired nurses — that happens at school too. Sorry for taking so long." },
        { speaker: "B", es: "No pidas perdón. Tardar en responder demuestra que escuchaste todo el rato.", en: "Don't apologize. Answering late proves you were listening the whole time." },
        { speaker: "A", es: "Antes de que se me olvide, anoté tu idea del silencio en el cuaderno. Donde íbamos, comparábamos hospital y escuela.", en: "Before I forget, I wrote down your idea about silence in the notebook. Where we were, we were comparing hospital and school." },
      ],
    },
  },
  {
    day: 346,
    themeEs: "Como te contaba",
    storyTitle: "Cuarenta minutos seguidos",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "el mesero", en: "the waiter", example: "Antes de que viniera el mesero." },
      { es: "interrumpir", en: "to interrupt", example: "El mesero interrumpe y retomas con como te contaba." },
      { es: "retomar", en: "to pick up again, to resume", example: "Retomar es más difícil que empezar." },
      { es: "le quería comentar", en: "I wanted to tell you (usted)", example: "Dije le quería comentar, no te quería comentar." },
      { es: "en la cabeza", en: "in one's head", example: "Tenía dos versiones en la cabeza." },
    ],
    dialogue: {
      title: "Pasa el mesero",
      situation: "Una interrupción — y Marlana retoma la historia de Yusuf",
      lines: [
        { speaker: "A", es: "Como te contaba, la madre se sentó y yo tenía dos versiones en la cabeza.", en: "As I was telling you, the mother sat down and I had two versions in my head." },
        { speaker: "B", es: "¿Tú y usted otra vez?", en: "Tú and usted again?" },
        { speaker: "A", es: "Otra vez. Dije \"le quería comentar\" y no \"te quería comentar.\" Funcionó.", en: "Again. I said \"le quería comentar\" and not \"te quería comentar.\" It worked." },
        { speaker: "B", es: "¿Café?", en: "Coffee?" },
        { speaker: "A", es: "Sí, gracias. Volviendo a lo que dijiste antes de que viniera el mesero, sí, me pasa igual con el silencio incómodo.", en: "Yes, thanks. Going back to what you said before the waiter came — yes, the same thing happens to me with awkward silence." },
        { speaker: "B", es: "Bien retomado. ¿Y Yusuf?", en: "Well resumed. And Yusuf?" },
        { speaker: "A", es: "Eso me recuerda la semana de usted, cuando ensayaba con Rocío. Yusuf sonrió cuando lo mencioné.", en: "That reminds me usted week, when I was rehearsing with Rocío. Yusuf smiled when I mentioned him." },
        { speaker: "B", es: "Antes de que se me olvide — eso va en el cuaderno también.", en: "Before I forget — that goes in the notebook too." },
        { speaker: "A", es: "Donde íbamos, yo contaba la reunión con la madre de Yusuf. Llevamos veinticinco minutos sin mirar el reloj.", en: "Where we were, I was telling the meeting with Yusuf's mom. We've gone twenty-five minutes without looking at the clock." },
        { speaker: "B", es: "Eso es señal.", en: "That's a sign." },
      ],
    },
  },
  {
    day: 347,
    themeEs: "Eso me recuerda",
    storyTitle: "Cuarenta minutos seguidos",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "traducir", en: "to translate", example: "La niña traducía para su mamá." },
      { es: "el tangente", en: "the tangent", example: "Un tangente bien cerrado no rompe la charla." },
      { es: "enlazar", en: "to link, to connect", example: "Los recuerdos no interrumpen, enlazan." },
      { es: "solo inglés en casa", en: "English only at home", example: "La mamá de Diego quería solo inglés en casa." },
      { es: "los dos idiomas", en: "both languages", example: "Diego leyó en los dos idiomas." },
    ],
    dialogue: {
      title: "La niña de ocho años",
      situation: "Camila cuenta un hospital; Marlana conecta con la escuela",
      lines: [
        { speaker: "B", es: "Ayer una señora no entendía a la doctora. La niña tenía ocho años y tradujo el diagnóstico mejor que nosotras.", en: "Yesterday a woman didn't understand the doctor. The girl was eight and translated the diagnosis better than we did." },
        { speaker: "A", es: "Eso me recuerda lo de la mamá de Diego y la reunión que no terminé.", en: "That reminds me Diego's mom and the meeting I never finished." },
        { speaker: "B", es: "Tangente. ¿Lo sigues?", en: "Tangent. Are you going to follow it?" },
        { speaker: "A", es: "Como te contaba, la mamá de Diego quería solo inglés en casa. En el café dijimos que quitar el español no acelera nada.", en: "As I was telling you, Diego's mom wanted English only at home. At the café we said taking away Spanish doesn't speed anything up." },
        { speaker: "B", es: "Semana ocho. Buen callback.", en: "Week eight. Good callback." },
        { speaker: "A", es: "Volviendo a lo que dijiste de la señora que traducía para su mamá, eso es Diego otra vez.", en: "Going back to what you said about the woman who translated for her mom — that's Diego again." },
        { speaker: "B", es: "Exacto. Hospital y escuela, un hilo.", en: "Exactly. Hospital and school, one thread." },
        { speaker: "A", es: "Antes de que se me olvide, Diego leyó en los dos idiomas este fin de semana.", en: "Before I forget, Diego read in both languages this weekend." },
        { speaker: "B", es: "Donde íbamos, tú contabas lo del hospital y yo conecté con la escuela. Faltan diez minutos y no se siente.", en: "Where we were, you were telling the hospital story and I connected it to school. Ten minutes left and it doesn't feel like it." },
        { speaker: "A", es: "Eso me recuerda por qué pusimos conversación larga en las metas.", en: "That reminds me why we put long conversation on the goals." },
      ],
    },
  },
  {
    day: 348,
    themeEs: "Antes de que se me olvide",
    storyTitle: "Cuarenta minutos seguidos",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "suenar distinta", en: "to sound different", example: "Rocío dice que sueno distinta." },
      { es: "intervenir", en: "to step in, to intervene", example: "Rocío me escuchó y no intervino." },
      { es: "contar huecos", en: "to count the gaps", example: "En invierno contaba huecos." },
      { es: "la servilleta", en: "the napkin", example: "Anoté los cinco stems en la servilleta." },
      { es: "lo mejor del jueves", en: "the best part of thursday", example: "Cuarenta minutos es lo mejor del jueves." },
    ],
    dialogue: {
      title: "Tres cosas pequeñas",
      situation: "Marlana guarda lo que casi se pierde en la charla",
      lines: [
        { speaker: "A", es: "Antes de que se me olvide, quería decirte que esto — cuarenta minutos — es lo mejor del jueves.", en: "Before I forget, I wanted to tell you this — forty minutes — is the best part of Thursday." },
        { speaker: "B", es: "Grábatelo. ¿Qué más?", en: "Burn that in. What else?" },
        { speaker: "A", es: "Antes de que se me olvide, Rocío pregunta si el jueves que viene hay sitio para una más.", en: "Before I forget, Rocío asks if there's room for one more next Thursday." },
        { speaker: "B", es: "Siempre hay sitio para Rocío.", en: "There's always room for Rocío." },
        { speaker: "A", es: "Volviendo a lo que dijiste de que sueno distinta, creo que ya sé por qué.", en: "Going back to what you said about me sounding different — I think I know why now." },
        { speaker: "B", es: "¿Por qué?", en: "Why?" },
        { speaker: "A", es: "Como te contaba, Rocío me escuchó hablar con una madre y no intervino. Eso nunca pasaba en otoño.", en: "As I was telling you, Rocío listened to me talk with a parent and didn't step in. That never happened in fall." },
        { speaker: "B", es: "Eso me recuerda el invierno, cuando contabas huecos.", en: "That reminds me winter, when you were counting holes." },
        { speaker: "A", es: "Antes de que se me olvide, guardé la servilleta donde anotaste los cinco stems.", en: "Before I forget, I saved the napkin where you wrote the five stems." },
        { speaker: "B", es: "Donde íbamos, hablábamos de por qué suenas distinta. Faltan cinco minutos y no quiero que acabe.", en: "Where we were, we were talking about why you sound different. Five minutes left and I don't want it to end." },
      ],
    },
  },
  {
    day: 349,
    themeEs: "Donde íbamos",
    storyTitle: "Cuarenta minutos seguidos",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "aterrizar", en: "to land (fig.)", example: "Dos minutos más para aterrizar." },
      { es: "cumplir", en: "to fulfill, to complete", example: "Cumplimos cuarenta minutos seguidos." },
      { es: "sin darse cuenta", en: "without noticing", example: "Llegué sin darme cuenta." },
      { es: "sonar como yo", en: "to sound like myself", example: "Quería sonar como yo, no como folleto." },
      { es: "la arquitectura", en: "the architecture (fig.)", example: "Los puentes son la arquitectura de la charla larga." },
    ],
    dialogue: {
      title: "Suena el temporizador",
      situation: "Cuarenta minutos — y Marlana pide dos más para aterrizar",
      lines: [
        { speaker: "B", es: "Tiempo.", en: "Time." },
        { speaker: "A", es: "Dos minutos más. Por favor. Donde íbamos, hablábamos de cuarenta minutos seguidos — y los cumplimos.", en: "Two more minutes. Please. Where we were, we were talking about forty straight minutes — and we did it." },
        { speaker: "B", es: "Te los doy.", en: "You got them." },
        { speaker: "A", es: "Volviendo a lo que dijiste al empezar, cuarenta minutos no asustan ya.", en: "Going back to what you said at the start — forty minutes don't scare me anymore." },
        { speaker: "B", es: "Como te contaba al principio del año, querías sonar como tú.", en: "As I was telling you at the start of the year, you wanted to sound like you." },
        { speaker: "A", es: "Eso me recuerda que hace un año no podía aguantar diez minutos.", en: "That reminds me a year ago I couldn't hold ten minutes." },
        { speaker: "B", es: "Usaste los cinco stems sin contarlos. Eso es arquitectura.", en: "You used all five stems without counting them. That's architecture." },
        { speaker: "A", es: "Antes de que se me olvide, gracias por no mirar el teléfono tampoco.", en: "Before I forget, thanks for not looking at your phone either." },
        { speaker: "B", es: "La próxima semana toca reactivar cuando se enfría: *Bueno, ¿y qué más?* · *Se me olvidaba contarte…*", en: "Next week is about re-energizing when it cools: *Well, what else?* · *I forgot to tell you…*" },
        { speaker: "A", es: "Bien. Pero hoy me quedo con cuarenta minutos seguidos.", en: "Good. But today I'm staying with forty straight minutes." },
      ],
    },
  },
  {
    day: 350,
    themeEs: "Repaso: Conversación larga I",
    isRecap: true,
    vocab: [
      { es: "la arquitectura", en: "the architecture (fig.)", example: "Los puentes son la arquitectura de la charla." },
      { es: "el callback", en: "the callback", example: "Volviendo a lo que dijiste es callback." },
      { es: "retomar", en: "to resume", example: "Como te contaba retoma el hilo." },
      { es: "entrenamiento", en: "training", example: "Cuarenta minutos es entrenamiento, no suerte." },
      { es: "reactivar", en: "to re-energize", example: "La semana que viene toca reactivar." },
    ],
    dialogue: {
      title: "Cinco puentes, cuarenta minutos",
      situation: "Repaso — la arquitectura de quedarse en una conversación",
      lines: [
        { speaker: "B", es: "Repaso. Cuarenta minutos seguidos. ¿Qué aprendiste?", en: "Recap. Forty straight minutes. What did you learn?" },
        { speaker: "A", es: "Volviendo a lo que dijiste toda la semana, cuarenta minutos es entrenamiento, no suerte.", en: "Going back to what you said all week — forty minutes is training, not luck." },
        { speaker: "B", es: "Dame los cinco stems en orden.", en: "Give me the five stems in order." },
        { speaker: "A", es: "Callback: volviendo a lo que dijiste… Retomar: como te contaba… Tangente: eso me recuerda… Salvar lo pequeño: antes de que se me olvide… Volver: donde íbamos…", en: "Callback: going back to what you said… Resume: as I was telling you… Tangent: that reminds me… Save the small thing: before I forget… Return: where we were…" },
        { speaker: "B", es: "¿Y qué cambió en los cuarenta minutos?", en: "And what changed in the forty minutes?" },
        { speaker: "A", es: "Como te contaba, retomar es más difícil que empezar — y más útil. Eso me recuerda Diego, Yesenia, el hospital — todo en una mesa.", en: "As I was telling you, resuming is harder than starting — and more useful. That reminds me Diego, Yesenia, the hospital — all at one table." },
        { speaker: "B", es: "Antes de que se me olvide, cuarenta minutos seguidos fue la meta de primavera — y llegó.", en: "Before I forget, forty straight minutes was primavera's goal — and it arrived." },
        { speaker: "A", es: "Donde íbamos, hablábamos de puentes — y cruzamos cuarenta minutos.", en: "Where we were, we were talking about bridges — and we crossed forty minutes." },
        { speaker: "B", es: "Semana que viene: cuando se enfría. *Bueno, ¿y qué más?* · *Oye, y cambiando de tema…*", en: "Next week: when it cools down. *Well, what else?* · *Hey, and changing topic…*" },
        { speaker: "A", es: "Bien. Pero hoy me quedo con la servilleta.", en: "Good. But today I'm keeping the napkin." },
      ],
    },
  },
];
