import type { ReadingDay } from "../../readings/types";

/**
 * Primavera Week 8 — "Lo que se pierde" (days 323–329).
 * The district cuts the 7pm ESOL section. Six installments carry it from
 * Yesenia's question to the three minutes Marlana gets at the school board —
 * big topics in spoken Spanish, always attached to a person with a name.
 */
export const priWeek8ReadingDays: ReadingDay[] = [
  {
    day: 323,
    themeEs: "La pregunta de Yesenia",
    storyTitle: "Lo que se pierde",
    part: 1,
    partsTotal: 6,
    vocab: [
      { es: "a mí lo que me molesta es", en: "what bugs me is", example: "A mí lo que me molesta es que le di la respuesta de folleto." },
      { es: "lo que pasa es que", en: "here's what's going on, the thing is", example: "Lo que pasa es que no pregunta por el inglés." },
      { es: "hacer cuentas", en: "to do the math, to weigh the cost", example: "Está agotada y está haciendo cuentas." },
      { es: "alcanzar", en: "to be enough, to suffice", example: "\"Oportunidades\" no le va a alcanzar." },
      { es: "aun así", en: "even so, and still", example: "Limpia oficinas todo el día y aun así llega a las siete." },
    ],
    dialogue: {
      title: "¿Para qué el inglés?",
      situation: "Jueves en el café — Marlana llega directo de la clase de la noche",
      lines: [
        { speaker: "A", es: "Yesenia me preguntó hoy: \"¿Para qué inglés si yo trabajo en cocina?\" Y me quedé muda.", en: "Yesenia asked me today: \"What do I need English for if I work in a kitchen?\" And I went silent." },
        { speaker: "B", es: "Buena pregunta. ¿Qué le dijiste?", en: "Good question. What did you tell her?" },
        { speaker: "A", es: "Algo sobre oportunidades. A mí lo que me molesta es que le di la respuesta de folleto.", en: "Something about opportunities. What bugs me is that I gave her the brochure answer." },
        { speaker: "B", es: "¿Y cuál era la buena?", en: "And what was the good one?" },
        { speaker: "A", es: "Lo que pasa es que no pregunta por el inglés, pregunta si vale las cuatro horas.", en: "Here's what's going on: she's not asking about English, she's asking whether it's worth four hours." },
        { speaker: "B", es: "Ah. Entonces la pregunta es de matemáticas, no de idioma.", en: "Ah. So the question is about math, not language." },
        { speaker: "A", es: "Exacto. No es que no quiera aprender, es que está agotada y está haciendo cuentas.", en: "Exactly. It's not that she doesn't want to learn — she's exhausted and she's doing the math." },
        { speaker: "B", es: "¿Y ella sigue yendo?", en: "And does she keep going?" },
        { speaker: "A", es: "Yo lo que veo es una mujer que limpia oficinas todo el día y aun así llega a las siete.", en: "What I see is a woman who cleans offices all day and still shows up at seven." },
        { speaker: "A", es: "¿Tú qué harías? Porque \"oportunidades\" no le va a alcanzar.", en: "What would you do? Because \"opportunities\" isn't going to be enough for her." },
        { speaker: "B", es: "Yo le preguntaría a ella para qué quiere el inglés. Y me callaría.", en: "I'd ask her what she wants English for. And then I'd be quiet." },
      ],
    },
  },
  {
    day: 324,
    themeEs: "La tarea que no escribió",
    storyTitle: "Lo que se pierde",
    part: 2,
    partsTotal: 6,
    vocab: [
      { es: "darse cuenta", en: "to notice, to realize", example: "Pensó que yo no me iba a dar cuenta." },
      { es: "el borrador", en: "the draft", example: "Nadie le enseñó cómo se ve un primer borrador." },
      { es: "hacer trampa", en: "to cheat", example: "No es que haya hecho trampa." },
      { es: "entregar", en: "to hand in, to turn in", example: "Un chico con miedo de entregar algo feo." },
      { es: "reprobar", en: "to fail (a student, a class)", example: "Yo no lo voy a reprobar por eso." },
    ],
    dialogue: {
      title: "El párrafo perfecto",
      situation: "Marlana trae la tarea de un estudiante de sexto",
      lines: [
        { speaker: "A", es: "Un chico me entregó un párrafo perfecto. En clase nunca termina una frase.", en: "A kid handed me a perfect paragraph. In class he never finishes a sentence." },
        { speaker: "B", es: "¿Lo escribió una app?", en: "Did an app write it?" },
        { speaker: "A", es: "En el pasillo, antes de entrar. A mí lo que me molesta no es la app, es que pensó que yo no me iba a dar cuenta.", en: "In the hallway, before coming in. What bugs me isn't the app — it's that he thought I wouldn't notice." },
        { speaker: "B", es: "¿Y él sabe del tema o no sabe nada?", en: "And does he know the material or nothing at all?" },
        { speaker: "A", es: "Lo que pasa es que él sí puede hablar del libro, lo que no puede es escribirlo.", en: "Here's what's going on: he can talk about the book, what he can't do is write it." },
        { speaker: "B", es: "Entonces el problema no es la honestidad.", en: "So the problem isn't honesty." },
        { speaker: "A", es: "No es que haya hecho trampa, es que nadie le enseñó cómo se ve un primer borrador.", en: "It's not that he cheated — nobody ever showed him what a first draft looks like." },
        { speaker: "B", es: "Nunca ha visto uno feo.", en: "He's never seen an ugly one." },
        { speaker: "A", es: "Yo lo que veo es un chico con miedo de entregar algo feo. ¿Tú qué harías el lunes? Porque yo no lo voy a reprobar por eso.", en: "What I see is a kid who's afraid to hand in something ugly. What would you do Monday? Because I'm not failing him over this." },
        { speaker: "B", es: "Enséñale el tuyo. El feo. El que tachaste tres veces.", en: "Show him yours. The ugly one. The one you crossed out three times." },
      ],
    },
  },
  {
    day: 325,
    themeEs: "Solo inglés en casa",
    storyTitle: "Lo que se pierde",
    part: 3,
    partsTotal: 6,
    vocab: [
      { es: "quitar", en: "to take away, to remove", example: "No me pide quitar el español." },
      { es: "darle pena a alguien", en: "to embarrass someone", example: "No es que le dé pena el idioma." },
      { es: "quedarse afuera", en: "to be left out", example: "Odia quedarse afuera de la conversación." },
      { es: "la cita médica", en: "the doctor's appointment", example: "Una niña de ocho años traduciendo una cita médica." },
      { es: "el sermón", en: "the lecture, the sermon", example: "¿Cómo se lo digo sin sonar a sermón?" },
    ],
    dialogue: {
      title: "La mamá de Diego",
      situation: "Después de una reunión de padres, otra vez en el café",
      lines: [
        { speaker: "A", es: "La mamá de Diego me pidió que le recomiende solo inglés en casa. Dijo que el español lo retrasa.", en: "Diego's mom asked me to recommend English only at home. She said Spanish holds him back." },
        { speaker: "B", es: "Uf. ¿Y de dónde sacó eso?", en: "Ugh. And where did she get that?" },
        { speaker: "A", es: "A mí lo que me molesta es que alguien le dijo que el español era el problema. Y no fui yo.", en: "What bugs me is that somebody told her Spanish was the problem. And it wasn't me." },
        { speaker: "B", es: "Alguien con autoridad, seguro.", en: "Somebody with authority, for sure." },
        { speaker: "A", es: "Lo que pasa es que no me pide quitar el español, me pide arreglar a su hijo.", en: "Here's what's going on: she's not asking me to take away Spanish, she's asking me to fix her son." },
        { speaker: "B", es: "Eso es otra cosa completamente.", en: "That's a completely different thing." },
        { speaker: "A", es: "No es que le dé pena el idioma, es que está cansada de no entender a la escuela.", en: "It's not that she's ashamed of the language — she's tired of not understanding the school." },
        { speaker: "B", es: "Yo veo eso todas las semanas en el hospital.", en: "I see that every week at the hospital." },
        { speaker: "A", es: "Yo lo que veo es una niña de ocho años traduciendo una cita médica. ¿Tú qué harías? Tú has estado del lado de ella en esa conversación.", en: "What I see is an eight-year-old translating a doctor's appointment. What would you do? You've been on her side of that conversation." },
        { speaker: "B", es: "Le diría que su hijo la necesita a ella entera, no traducida.", en: "I'd tell her that her son needs all of her, not a translated version." },
      ],
    },
  },
  {
    day: 326,
    themeEs: "Cortan la clase de la noche",
    storyTitle: "Lo que se pierde",
    part: 4,
    partsTotal: 6,
    vocab: [
      { es: "la inscripción", en: "enrollment, registration", example: "Lo llamaron \"poca inscripción\"." },
      { es: "el recorte", en: "the cut (budget)", example: "El recorte llegó en un correo de dos líneas." },
      { es: "la lista de espera", en: "the waiting list", example: "Hay una lista de espera de catorce personas." },
      { es: "presentarse", en: "to show up, to appear", example: "¿Escribirles o presentarte en la reunión?" },
      { es: "el uniforme", en: "the uniform, work clothes", example: "Llegan con el uniforme puesto." },
    ],
    dialogue: {
      title: "Un correo de dos líneas",
      situation: "Viernes por la noche, videollamada — Marlana acaba de leer el correo",
      lines: [
        { speaker: "A", es: "Cortaron la clase de las siete. La de Yesenia.", en: "They cut the seven o'clock class. Yesenia's." },
        { speaker: "B", es: "¿Cómo que la cortaron? Si esa es la que se llena.", en: "What do you mean they cut it? That's the one that fills up." },
        { speaker: "A", es: "A mí lo que me molesta es que cortaron la clase de la noche y lo llamaron \"poca inscripción\".", en: "What bugs me is they cut the night class and called it \"low enrollment.\"" },
        { speaker: "B", es: "¿Y adónde los mandan?", en: "And where are they sending them?" },
        { speaker: "A", es: "A la de las cuatro. Lo que pasa es que once personas no pueden venir a las cuatro de la tarde porque están trabajando.", en: "To the four o'clock. Here's what's going on: eleven people can't come at four in the afternoon because they're working." },
        { speaker: "B", es: "O sea que no la cortaron, la cerraron.", en: "So they didn't cut it, they closed it." },
        { speaker: "A", es: "No es que no haya dinero, es que somos la línea más fácil de cortar.", en: "It's not that there's no money — we're the easiest line to cut." },
        { speaker: "B", es: "Siempre. En el hospital pasa igual con los intérpretes.", en: "Always. Same thing happens with the interpreters at the hospital." },
        { speaker: "A", es: "Yo lo que veo es que la clase que se llena es la que están cerrando. Hay lista de espera, Camila.", en: "What I see is that the class that fills up is the one they're closing. There's a waiting list, Camila." },
        { speaker: "A", es: "¿Tú qué harías? ¿Escribirles o presentarte en la reunión?", en: "What would you do — write to them or show up at the meeting?" },
        { speaker: "B", es: "Ir. Un correo se archiva. Una persona de pie, no.", en: "Go. An email gets filed. A person standing up doesn't." },
      ],
    },
  },
  {
    day: 327,
    themeEs: "El examen del estado",
    storyTitle: "Lo que se pierde",
    part: 5,
    partsTotal: 6,
    vocab: [
      { es: "evaluar", en: "to test, to assess", example: "Los evalúan en inglés sobre cosas que ya saben." },
      { es: "la nota", en: "the score, the grade", example: "La nota mide el inglés, no al niño." },
      { es: "como si", en: "as if (+ imperfect subjunctive)", example: "La leen como si midiera al niño." },
      { es: "el enunciado", en: "the wording of a question, the prompt", example: "Fallan en el enunciado, no en las matemáticas." },
      { es: "calificar", en: "to grade", example: "¿Y si calificaran tu turno en otro idioma?" },
    ],
    dialogue: {
      title: "Diego saca un dos",
      situation: "Llegaron los resultados del examen del estado",
      lines: [
        { speaker: "A", es: "Llegaron las notas. Diego sacó un dos en matemáticas.", en: "The scores came in. Diego got a two in math." },
        { speaker: "B", es: "¿Diego? ¿El que te explicó las fracciones a ti?", en: "Diego? The one who explained fractions to you?" },
        { speaker: "A", es: "Ese. A mí lo que me molesta es que los evalúan en inglés sobre cosas que ya saben en español.", en: "That one. What bugs me is they test them in English on things they already know in Spanish." },
        { speaker: "B", es: "Entonces el examen no mide matemáticas.", en: "So the test doesn't measure math." },
        { speaker: "A", es: "Lo que pasa es que la nota mide el inglés, y después la leen como si midiera al niño.", en: "Here's what's going on: the score measures the English, and then they read it as if it measured the kid." },
        { speaker: "B", es: "¿Y tú qué haces con ese papel?", en: "And what do you do with that piece of paper?" },
        { speaker: "A", es: "No es que yo esté en contra de los exámenes, es que este no me dice nada que no supiera en octubre.", en: "It's not that I'm against tests — this one tells me nothing I didn't know in October." },
        { speaker: "B", es: "Y a la mamá le llega el número solo.", en: "And the mom just gets the number." },
        { speaker: "A", es: "Yo lo que veo es a Diego explicando fracciones perfecto y sacando un dos. ¿Tú qué harías si calificaran tu turno con un examen en un idioma que todavía estás aprendiendo?", en: "What I see is Diego explaining fractions perfectly and scoring a two. What would you do if they graded your shift with a test in a language you were still learning?" },
        { speaker: "B", es: "Renunciar. O aprender a hablar en la junta. Tú vas el martes, ¿no?", en: "Quit. Or learn to speak at the board meeting. You're going Tuesday, right?" },
      ],
    },
  },
  {
    day: 328,
    themeEs: "Lo que voy a decir el martes",
    storyTitle: "Lo que se pierde",
    part: 6,
    partsTotal: 6,
    vocab: [
      { es: "la junta escolar", en: "the school board", example: "Tengo tres minutos en la junta escolar." },
      { es: "el cargo", en: "the job title, the position", example: "Ya gasté dos minutos en mi cargo." },
      { es: "la gráfica", en: "the chart, the graph", example: "Me escuchan si llevo a Yesenia y no una gráfica." },
      { es: "sonar a", en: "to sound like (no article)", example: "Párame si empiezo a sonar a informe." },
      { es: "la petición", en: "the request, the ask", example: "La petición tiene que ir al final." },
    ],
    dialogue: {
      title: "Tres minutos",
      situation: "Domingo por la tarde — Camila es el público de práctica",
      lines: [
        { speaker: "B", es: "Ya. Tres minutos. Empieza y yo te paro.", en: "Okay. Three minutes. Start and I'll stop you." },
        { speaker: "A", es: "\"Buenas tardes, soy maestra de ESOL en el distrito desde hace seis años y…\"", en: "\"Good afternoon, I'm an ESOL teacher in the district and I've been here six years and…\"" },
        { speaker: "B", es: "Alto. Llevas treinta segundos y no has dicho nada.", en: "Stop. You're thirty seconds in and you haven't said anything." },
        { speaker: "A", es: "Ya sé. A mí lo que me molesta es que tengo tres minutos y ya gasté dos en mi cargo.", en: "I know. What bugs me is I have three minutes and I've already spent two on my job title." },
        { speaker: "B", es: "Entonces empieza por los números.", en: "Then start with the numbers." },
        { speaker: "A", es: "No. Lo que pasa es que si yo digo números, ellos me contestan con números. Y su hoja es más grande.", en: "No. Here's what's going on: if I give them numbers, they answer me with numbers. And their spreadsheet is bigger." },
        { speaker: "B", es: "¿Y qué quieres exactamente? Dilo en una frase.", en: "And what exactly do you want? Say it in one sentence." },
        { speaker: "A", es: "No es que quiera que se sientan mal, es que quiero que muevan la clase a las siete.", en: "It's not that I want them to feel bad — I want them to move the class to seven." },
        { speaker: "B", es: "Eso. Eso es lo primero que tienes que decir.", en: "That. That's the first thing you have to say." },
        { speaker: "A", es: "Yo lo que veo es que me van a escuchar si llevo a Yesenia y no una gráfica.", en: "What I see is they'll listen to me if I bring Yesenia and not a chart." },
        { speaker: "A", es: "¿Tú qué harías? Párame si empiezo a sonar a informe.", en: "What would you do? Stop me if I start sounding like a report." },
        { speaker: "B", es: "Trato hecho. Otra vez desde el principio, y esta vez sin tu cargo.", en: "Deal. From the top again, and this time without your job title." },
      ],
    },
  },
  {
    day: 329,
    themeEs: "Repaso: Temas grandes",
    isRecap: true,
    vocab: [
      { es: "enterarse por", en: "to find out through/from", example: "Te enteraste por el boletín y no por ellos." },
      { es: "el boletín", en: "the newsletter, the bulletin", example: "Lo pusieron en la página cuatro del boletín." },
      { es: "quejarse", en: "to complain", example: "Sola soy una maestra quejándose." },
      { es: "la votación", en: "the vote", example: "¿Ir el martes o esperar la votación?" },
      { es: "el timbre", en: "the bell", example: "Tengo cuatro minutos antes del timbre." },
    ],
    dialogue: {
      title: "Junto a la copiadora",
      situation: "Lunes, 7:40 de la mañana — Rocío está sacando copias",
      lines: [
        { speaker: "B", es: "Leí lo de la clase de la noche. En el boletín, página cuatro.", en: "I read about the night class. In the newsletter, page four." },
        { speaker: "A", es: "A mí lo que me molesta es que te enteraste por el boletín y no por ellos.", en: "What bugs me is that you found out from the newsletter and not from them." },
        { speaker: "B", es: "Así se hacen estas cosas aquí. ¿Hay reunión?", en: "That's how these things get done here. Is there a meeting?" },
        { speaker: "A", es: "El martes a las cinco. Lo que pasa es que nadie de la clase de la noche va a estar libre a esa hora tampoco.", en: "Tuesday at five. Here's what's going on: nobody from the night class is going to be free at that hour either." },
        { speaker: "B", es: "Claro. La reunión sobre la clase de la noche es de día.", en: "Of course. The meeting about the night class is during the day." },
        { speaker: "A", es: "Exacto. No es que no quiera ir sola, es que sola soy una maestra quejándose.", en: "Exactly. It's not that I don't want to go alone — alone I'm just one teacher complaining." },
        { speaker: "B", es: "Con dos ya es un asunto. Con cinco es un problema para ellos.", en: "With two it's already an issue. With five it's a problem for them." },
        { speaker: "A", es: "Yo lo que veo es que tú ya hiciste esto antes y sabes con quién hablar primero.", en: "What I see is that you've done this before and you know who to talk to first." },
        { speaker: "B", es: "Con la coordinadora. Antes del martes, no en el martes.", en: "With the coordinator. Before Tuesday, not at Tuesday." },
        { speaker: "A", es: "¿Tú qué harías? ¿Ir el martes o esperar la votación?", en: "What would you do — go Tuesday or wait for the vote?" },
        { speaker: "B", es: "Las dos. Y llévate a Yesenia. Ya suena el timbre — te escribo al mediodía.", en: "Both. And bring Yesenia. There's the bell — I'll text you at noon." },
      ],
    },
  },
];
